### ISSUE TITLE
build issue with harfbuzz

### ISSUE THREAD

**Issue by SolarAquarion** [wez/wezterm#1]
https://github.com/servo/rust-harfbuzz

**Comment by SolarAquarion** [comment]
https://docs.rs/harfbuzz-sys/0.1.15/harfbuzz_sys/ aka this crate

**Comment by wez** [comment]
Ideally, yes, but I need it to support freetype when it builds its bundled lib, and this prevents it from doing that:

https://github.com/servo/rust-harfbuzz/blob/master/harfbuzz-sys/makefile.cargo#L36

**Comment by wez** [comment]
https://github.com/wez/wezterm/commit/e7d99024bb57485e6067871081abcb5d5f6a4a08 is the commit where I switched away from it.  In the longer run I'd like to not have my own thing for this, but its an effective short term way to make sure that we get a new enough harfbuzz on travis and other linuxes.

**Comment by SolarAquarion** [comment]
I finally figured out what I was doing wrong forgot to clone the modules

**Comment by SolarAquarion** [comment]
Compiling term v0.1.0 (file:///home/solaraquarion/wezterm/term)
error: could not find native static library `harfbuzz`, perhaps an -L flag is missing?

error: Could not compile `harfbuzz`.

**Comment by wez** [comment]
Yeah, I saw this today on someone else's Fedora machine and on another person's Arch distro.  I'll fix this.

**Comment by wez** [comment]
Amazingly, I got the travis build bits right on the first iteration(!) so I think you should be good to go with this now; please let me know if it works for you!

**Comment by wez** [comment]
This is good to go now
