### ISSUE TITLE
[CRITICAL] Major issue, Immediate attention needed, ALERT!!!

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#100]
The https://wezfurlong.org homepage doesn't use the badass picture you have in your [Github profile](https://github.com/wez).

Please fix this as soon as humanly possible, thank you.

**Comment by wez** [comment]
Heh, that's probably better logged against this repo: https://github.com/wez/wez.github.io.
I'm going to close this one out and make a mental note to revisit the blog for the new year :)

**Comment by ImportTaste** [comment]
Heh, sorry, didn't even know that repo existed. Thanks for the quick fix!
