### ISSUE TITLE
default `color_scheme` rendered improperly in nightlies on Intel Macs

### ISSUE THREAD

**Issue by 4cm4k1** [wez/wezterm#1000]
## Describe the bug

The title says it all. Please see screenshots. I am on nightlies, updated manually via `brew` every week or so. Thank you in advance for the help navigating this issue.

## Environment (please complete the following information):

 - OS: macOS (Intel)
 - Version: `wezterm 20210804-162508-e3acbd59`
 - The active keyboard layout name: ENG

## To Reproduce

1. Update `wezterm` to latest nightly with `brew upgrade --cask wezterm-nightly --no-quarantine`.
2. Open `~/Applications/wezterm.app`.
3. Default shell prompt appears, but `color_scheme: 'Snazzy'` renders improperly.
4. See screenshots, expected behaviors, and additional context sections. 

## Configuration

```lua
local wezterm = require 'wezterm';
return {
  color_scheme = 'Snazzy',
  default_prog = {'/usr/local/bin/zsh', '-l'},
  font = wezterm.font({family='FiraCode Nerd Font', stretch='Normal', weight='Regular'}),
  font_dirs = {'/Users/4cm4k1/Library/Fonts'},
}
```

## Expected behavior
See https://wezfurlong.org/wezterm/colorschemes/s/index.html#snazzy.

## Screenshots

<img width="604" alt="wezterm color_scheme rendering issue" src="https://user-images.githubusercontent.com/15058720/128431804-f52d6c63-9dbe-4539-b332-64b4b56e0f90.png">

## Session Recording

n/a

## Additional context

I just installed the regular release channel `wezterm` with `brew install --cask wezterm --no-quarantine` (`wezterm 20210502-154244-3f7122cb`) and the `color_scheme` renders properly.

**Comment by wez** [comment]
Are you using an M1 or an Intel based mac?

I wonder if this might be https://github.com/wez/wezterm/issues/653 manifesting a little differently due to the recent changes around how the terminal is drawn.

Can you try setting `use_alternative_alpha_blending=true` in your config to see if that helps?

**Comment by 4cm4k1** [comment]
Thanks, @wez! I will try your suggestion later this evening. Intel-based Mac.

**Comment by 4cm4k1** [comment]
@wez Added your suggestion to my config; regression still present in nightly. This isn't a huge blocker for me as I can use the main release for now. If you need me to test anything regarding this or #653, let me know, and I'll be happy to help.

**Comment by wez** [comment]
I made a change that might help with this in the most recent commit; should be available as a nightly build download in ~30 minutes.

**Comment by 4cm4k1** [comment]
@wez I can confirm this is no longer an issue on my Intel Mac on the nightlies. :) Thanks!
