### ISSUE TITLE
Initial and first resize terminal size is incorrect

### ISSUE THREAD

**Issue by gaborbernat** [wez/wezterm#1002]
I'm running on a Wayland session with Arch Linux (`wezterm-git`) and the terminal sizes don't seem to load correctly, and they don't update after the first resize, but then does correctly on subsequent runs. I'm running with PowerShell, showcase:

```
❯ tput lines; tput cols
24
80
❯ tput lines; tput cols
24
80
❯ tput lines; tput cols
27
96
```

The above commands are run in: 1. as the terminal loads 2. maximise window 3. restore the window to initial size; see how 1 and 2 are incorrect (and inconsistent with 3). Subsequent resizes in form of maximizing/restore/snap left+right seems to trigger correctly. However, the opening state and the first resize (maximise or snap left/right) seems to be off.

My wezterm config https://github.com/gaborbernat/dotfiles/blob/main/dot_config/wezterm/wezterm.lua.tmpl

In the stdout I only see:

```
❯ wezterm
 2021-08-06T07:26:06.404Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-424985
 2021-08-06T07:26:06.468Z INFO  wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon RX 6700 XT (NAVY_FLOUNDER, DRM 3.42.0, 5.14.0-1-MANJARO, LLVM 12.0.1) OpenGL ES 3.2 Mesa 21.1.5
is_context_loss_possible=false wezterm version: 20210804-162508-e3acbd59
```

**Comment by wez** [comment]
I saw something funky with the initial size on macos, and pushed a commit to fix it.  I don't know yet if it is related to what you're seeing on wayland, but if you could give current `main` a try, maybe it's a little better?

**Comment by gaborbernat** [comment]
No change on my side:
```
 2021-08-06T17:20:37.000Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-548887
 2021-08-06T17:20:37.060Z INFO  wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon RX 6700 XT (NAVY_FLOUNDER, DRM 3.42.0, 5.14.0-1-MANJARO, LLVM 12.0.1) OpenGL ES 3.2 Mesa 21.1.5
is_context_loss_possible=false wezterm version: 20210806-095157-40bb5ddb

~
❯ tput lines; tput cols
24
80
~
❯ tput lines; tput cols
24
80
~
❯ tput lines; tput cols
27
96
```

**Comment by wez** [comment]
Are you using a tiling window manager?

**Comment by gaborbernat** [comment]
I'm using Gnome on Wayland :thinking: nothing fancier.

**Comment by gksudolol** [comment]
Hi wez, I'm using exwm (sort of a tiling window manager) with X11. On opening wezterm fullscreen the size is incorrect, but if switch to floating and back to tiling it resizes as expected

**Comment by wez** [comment]
@gksudolol https://github.com/wez/wezterm/issues/695 is the issue for tiling window managers

**Comment by wez** [comment]
I just pushed a couple of commits that may help with this; please give `main` or the nightly builds (in about 30 minutes) a try and let me know if this makes it better!

**Comment by gaborbernat** [comment]
```
❯ tput lines; tput cols
24
80
~
❯ tput lines; tput cols
77
384
~
❯ tput lines; tput cols
27
88
```

Seems those fixed the first resize issue :clap:. The initial size is still of though :thinking: (note 27 vs 24 and 88 vs 80), but the difference is not big enough for me to cause an issue.

**Comment by wez** [comment]
Could you give the latest `main` a try?

**Comment by gaborbernat** [comment]
```
❯ tput lines; tput cols
24
80
~
❯ tput lines; tput cols
67
349
~
❯ tput lines; tput cols
24
80
~
```

That seems to fix it :+1:
