### ISSUE TITLE
[Process didn't exit cleanly. (exit_behavior="CloseOnCleanExit")]

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#1004]
## Describe the bug

```
❯ exit

[Process didn't exit cleanly. (exit_behavior="CloseOnCleanExit")]
```
## Environment (please complete the following information):

 - OS: macOS 11.5
 - Version: wezterm 20210804-162508-e3acbd59
 - The active keyboard layout name US

## To Reproduce

Close wezterm with ``>exit``, doesn't always give the error mentioned above.

**Comment by wez** [comment]
Check out the last paragraph of https://wezfurlong.org/wezterm/config/lua/config/exit_behavior.html
The same thing applies if you do `false ; exit`; the exit status of `exit` with no explicit exit status is that of the last command.

**Comment by reportaman** [comment]
Oh ok, then I guess I need exit_behavior = "Close"?

**Comment by wez** [comment]
If you don't care about the exit status, then yeah, you can set it to `Close`

**Comment by tycho-kirchner** [comment]
For the record: see also [here](https://github.com/wez/wezterm/issues/1889) and [here](https://wezfurlong.org/wezterm/config/lua/config/clean_exit_codes.html) for fine grained control 👍️.

**Comment by yashpalgoyal1304** [comment]
I have similar problem `Process didn't exit cleanly. (exit_behavior="CloseOnCleanExit")` . I am running on version `wezterm 20220319-142410-0fcdea07`. I havent updated yet just so that i could report this 😅 . Will update now.

![image](https://user-images.githubusercontent.com/19423063/173254514-776e7125-e479-4334-9fbd-181391056094.png)

**Comment by yashpalgoyal1304** [comment]
In the latest version `wezterm 20220408-101518-b908e2dd` it shows the following error but the error exit code is still not shown. Any reasons why exit code is not show?

![image](https://user-images.githubusercontent.com/19423063/173255513-979c6652-d8a0-4688-b585-5c632d0cfb8a.png)

**Comment by wez** [comment]
@yashpalgoyal1304 try the nightly; this has been changed since the last release

**Comment by yashpalgoyal1304** [comment]
does it mention the exit code?

**Comment by yashpalgoyal1304** [comment]
My observation:
Since I have updated to `wezterm 20220624-141144-bd1b7c5d` , I havent faced the non-clean exit even once. So, is the default behaviour changed to "Close" instead of "hold" or are the exits done better now so that they are "clean" most of the times??

**Comment by wez** [comment]
Yes, I changed the default to `Close` because more people commented negatively about that than commented about wanting the hold behavior. https://github.com/wez/wezterm/issues/2105 is linked from the changelog, but it is hard to find because the changelog is long in this release.
