### ISSUE TITLE
wrong default_prog does not show a nice error message

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#1005]
## Describe the bug

I had ``default_prog = {"wsl.exe"}`` set on linux which resulted in ``fatal runtime error: assertion failed: output.write(&bytes).is_ok()`` or an immediate close of wezterm.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm unstable-2021-08-08 (basically today, I need to adjust the format in nixpkgs)
 - The active keyboard layout name DEU

## To Reproduce
Set ``default_prog = {"wsl.exe"}`` on linux.

## Configuration

Be sure to include the relevant section(s) of your `wezterm.lua` configuration file.

## Expected behavior
Show a descriptive error message.

## Screenshots

If applicable, add screenshots to help explain your problem.  Screenshots are most
appropriate for rendering issues.

## Session Recording

If the issue is with the way that escape sequences are processed it can be helpful
to capture the terminal output using the [`wt-record`](https://github.com/wez/wezterm/blob/master/wt-record)
script to run `wezterm` and record a transcript.  This requires the `script` utility
to be installed on your system (this is part of macOS and available in the `util-linux`
package on linux systems).

In the example below a file named `20180225161026.tgz` is produced.  Please attach that
file to this issue, or if it contains private or sensitive issue that you don't want the
public to see on GitHub, please find some other way to get that file to a project
contributor (perhaps Dropbox or email?).

```
$ ./wt-record
Transcript recorded in 20180225161026.tgz
```

You can use `wt-replay 20180225161026.tgz` to replay that file.

`wt-record` can only record the terminal output; it cannot record the input events going
in to the terminal, so if you are having an issue with input, please be sure to describe
it below!

**Comment by wez** [comment]
I'm not sure where that inscrutable error comes from, but it appears to be something in the rust stdlib itself.
I've added a check for existence; wezterm will log a meaningful error to stderr and attempt to show a toast notification, however, early start toast notifications aren't guaranteed to be visible if wezterm immediately exits.

**Comment by SuperSandro2000** [comment]
When started via a shell I get now a useful error:

```
 2021-08-09T07:55:09.394Z INFO  wezterm_mux_server_impl::local > setting up C:\Users\user\.local/share/wezterm\gui-sock-14264
 2021-08-09T07:55:09.797Z ERROR portable_pty::win::psuedocon   > CreateProcessW `"wsl__.exe\u{0}"` in cwd `Some("C:\\Users\\user\u{0}")` failed: The system cannot find the file specified. (os error 2)
 2021-08-09T07:55:09.801Z ERROR wezterm_gui                    > CreateProcessW `"wsl__.exe\u{0}"` in cwd `Some("C:\\Users\\user\u{0}")` failed: The system cannot find the file specified. (os error 2); terminating
 ```

but when I try to open it from the start menu I get nothing. It exists so fast that not even the window blobs up shortly.

**Comment by wez** [comment]
I didn't change the behavior on Windows, only unix!

As I mentioned in my comment above, we try to show a toast notification, but because the program exited so quickly, it's not guaranteed to register with the notification system.

wezterm's behavior here is a slightly better variation of `xterm`'s behavior.

I'm not saying it's great, but it's good enough for troubleshooting purposes.
Doing more requires substantial effort and I'd rather spend that time on something else.

**Comment by SuperSandro2000** [comment]
I can understand that. I think now it is better than nothing and most people will start it through the console in the debugging process.
