### ISSUE TITLE
Unable to remove bottom padding when window_decorations = RESIZE

### ISSUE THREAD

**Issue by shut-sh** [wez/wezterm#1010]
First of all thanks for the great terminal. I was trying it out and playing with the settings. I could not get it to take full height of the screen when `window_decorations = "RESIZE"`. May be I am missing some configuration. I tried many different window related configurations but couldn't get it to work. Following is my config:

```
local wezterm = require("wezterm")

local config = {
  -- font = wezterm.font("FiraCode Nerd Font"),
  window_decorations = "RESIZE",
  window_padding = {
    top = 0,
    bottom = 0,
  },
  enable_tab_bar = true,
  hide_tab_bar_if_only_one_tab = true,
  color_scheme = "Atom",
  font_size = 14.0,
  unix_domains = {
    {
      name = "unix",
      connect_automatically = true,
    }
  },
  keys = {
    {key="+", mods="CTRL", action="IncreaseFontSize"},
    {key="LeftArrow", mods="SHIFT|ALT", action=wezterm.action{ActivateTabRelative=-1}},
    {key="RightArrow", mods="SHIFT|ALT", action=wezterm.action{ActivateTabRelative=1}},
    {key="Escape", mods="CTRL", action=wezterm.action{SpawnCommandInNewTab={args={"/usr/local/bin/htop"}}}},
  },
}

return config
```

Also attaching a screenshot:

![image](https://user-images.githubusercontent.com/11995895/128868204-3f9aab71-0e6f-4f1a-994d-517e1ea88f9f.png)

When the setting is `window_decorations = "TITLE | RESIZE"`, there is very little (~2-5px) padding at bottom. Screenshot for same is:

![image](https://user-images.githubusercontent.com/11995895/128868701-759068a3-06e8-4f8f-8db4-b2a69bdfeb9c.png)

Would be great if I could get rid of that padding :)

**Comment by wez** [comment]
Can you try the nightly build?

**Comment by wez** [comment]
FWIW: the gap at the bottom is unusable space that is < the cell height.  It should match the background color, but on Intel based macs it can show up in a weird bright version of the background color.  That was recently fixed in the nightly build, so it won't be so noticeable.

**Comment by shutsh** [comment]
On the nightly build the gap doesn't go away just the color has changed. Attaching the screenshot.

![image](https://user-images.githubusercontent.com/65345217/128990333-6855e679-4fce-4e5a-9e71-5b7db60be030.png)

**Comment by shutsh** [comment]
> FWIW: the gap at the bottom is unusable space that is < the cell height. It should match the background color, but on Intel based macs it can show up in a weird bright version of the background color. That was recently fixed in the nightly build, so it won't be so noticeable.

This makes sense. On nightly the background color of the unusable space is better. I'll close this since it is fixed in nightly.

**Comment by shut-sh** [comment]
On the nightly build the gap doesn't go away but the color is changed. Attaching the screenshot.

![image](https://user-images.githubusercontent.com/65345217/128990333-6855e679-4fce-4e5a-9e71-5b7db60be030.png)

> FWIW: the gap at the bottom is unusable space that is < the cell height. It should match the background color, but on Intel based macs it can show up in a weird bright version of the background color. That was recently fixed in the nightly build, so it won't be so noticeable.

This makes sense. On nightly the background color of the unusable space is better. I'll close this since it is fixed in nightly.
