### ISSUE TITLE
Weird radial gradient background

### ISSUE THREAD

**Issue by OkanEsen** [wez/wezterm#1012]
## Describe the bug

I have this weird background which seems to be a radial gradient, even though I didn't set a background image whatsoever. I'm using a non-default Gruvbox color scheme variant (see config below).

I tried to git bisect and pin point the commit, which causes this weird bug/artifact but I wasn't able to, unfortunately, which leads me to the question, if this is related to wezterm at all. Maybe the another crate is causing the issue or it is system/driver related.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210811-230616-3370466d (nightly)
 - ENG

## Configuration

<details>
  <summary>wezterm.lua</summary>
  
  ```lua
local wezterm = require "wezterm"

local font = wezterm.font({family = "PragmataPro Liga"})

return {
  term = "wezterm",
  font = font,
  font_size = 11.0,
  -- font_shaper = "Allsorts",
  freetype_load_flags = "NO_HINTING",
  -- freetype_render_target = "Light",

  line_height = 1.0,
  harfbuzz_features = {"ss13"},
  -- allow_square_glyphs_to_overflow_width = "Always",
  -- font_antialias = "Subpixel",
  color_scheme = "Gruvbox Dark Hard",
  color_schemes = {
    ["Gruvbox Dark Hard"] = {
      -- The default text color
      foreground = "#ebdbb2",
      -- The default background color
      background = "#1d2021",
      -- Overrides the cell background color when the current cell is occupied by the
      -- cursor and the cursor style is set to Block
      cursor_bg = "#ebdbb2",
      -- Overrides the text color when the current cell is occupied by the cursor
      cursor_fg = "#333333",
      -- Specifies the border color of the cursor when the cursor style is set to Block,
      -- of the color of the vertical or horizontal bar when the cursor style is set to
      -- Bar or Underline.
      cursor_border = "#ebdbb2",
      -- the foreground color of selected text
      selection_fg = "#333333",
      -- the background color of selected text
      selection_bg = "#ebdbb2",
      -- The color of the scrollbar "thumb"; the portion that represents the current viewport
      scrollbar_thumb = "#333333",
      -- The color of the split lines between panes
      split = "#333333",
      ansi = {
        "#282828",
        "#cc241d",
        "#98971a",
        "#d79921",
        "#458588",
        "#b16286",
        "#689d6a",
        "#a89984"
      },
      brights = {
        "#928374",
        "#fb4934",
        "#b8bb26",
        "#fabd2f",
        "#83a598",
        "#d3769b",
        "#8ec07c",
        "#ebdbb2"
      }
    }
  },
  enable_tab_bar = false,
  window_padding = {
    left = 3,
    right = 3,
    top = 3,
    bottom = 3
  },
  scrollback_lines = 0,
  adjust_window_size_when_changing_font_size = false,
  mouse_bindings = {
    {
      event = {Up = {streak = 1, button = "Left"}},
      mods = "NONE",
      action = wezterm.action {
        CompleteSelectionOrOpenLinkAtMouseCursor = "ClipboardAndPrimarySelection"
      }
    }
  }
}
  ```

</details>

## Screenshots

![2021-08-12_11-40](https://user-images.githubusercontent.com/552226/129176767-23efcc22-3545-4dad-87c5-d4d3eb3d142b.png)

One more screenshot with a white background (warning, wear your sunglasses):

<details>
  <summary>I've put my sunglasses on</summary>

![image](https://user-images.githubusercontent.com/552226/129177288-e0a6ca25-87e7-4148-a8c0-43185eb5cd91.png)

</details>

**Comment by OkanEsen** [comment]
I'm using AwesomeWM 4.3 on Fedora 34.

Thank you for the link and potential issue you provided, though I don't think that it's relevant to my issue since it's related to transparency. I disabled the wallpaper completely just to make sure and just set a background color and unfortunately the issue still persists.

**Comment by kar1** [comment]
OK, thanks trying. I'll look more into it later

**Comment by wez** [comment]
I tried your config and it doesn't reproduce for me (Fedora 33, Gnome/Mutter). Could you try the last stable release and see if it also has this issue?
Are you able to try eg; Gnome on your system to compare to see if it might be related to the Window manager?

**Comment by OkanEsen** [comment]
I tried the the following assets from latest release 20210502-154244-3f7122cb:

- WezTerm-20210502-154244-3f7122cb-Ubuntu16.04.**AppImage**: works, no artifacts
- wezterm-20210502_154244_3f7122cb-1.fc34.x86_64.**rpm**: works, no artifacts

I also tried it on Gnome and had the same issue, with the locally compiled version. Could this be related to my own compiled version? Though this seems to be unlikely but who knows.

Forgot it initially but this is the printed log output:

Latest release:
```
 2021-08-12T14:17:50.057Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-54343
 2021-08-12T14:17:50.117Z INFO  wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.13.8-200.fc34.x86_64, LLVM 12.0.0) OpenGL ES 3.2 Mesa 21.1.6 is_context_loss_possible=false wezterm version: 20210502-154244-3f7122cb
```

Compiled version:
```
 2021-08-12T14:19:06.782Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-63010
 2021-08-12T14:19:06.841Z INFO  wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.13.8-200.fc34.x86_64, LLVM 12.0.0) OpenGL ES 3.2 Mesa 21.1.6 is_context_loss_possible=false wezterm version: 20210808-224710-80d26197
```

**Comment by OkanEsen** [comment]
Well, I'm an idiot... Each time I recompiled wezterm I always copied the `wezterm` binary to `~/.local/bin` but only the `wezterm` binary, nothing else. I somehow forgot to include `wezterm-mux-server` and `wezterm-gui` and still had the versions from eons ago. It is fixed now...

Sorry for stealing your time, it was just my idiocy.

**Comment by wez** [comment]
Glad you figured it out, and glad that it isn't something we need to dig into now!
