### ISSUE TITLE
Wezterm behaves badly/laggy with AltDrag on Windows

### ISSUE THREAD

**Issue by bew** [wez/wezterm#1013]
## Describe the bug

When using the tool AltDrag on Windows to easily move, resize, maximize, toggle-on-top, ... any windows, using it with a Wezterm window is laggy, buggy, and can even (sometimes..) ~breaks the Windows's window manager (but closing wezterm completely fixes it somehow).

## Environment (please complete the following information):

 - OS: Windows
 - Version: wezterm 20210530-205210-717a2157 (nightly, from ~ May 31)
 - The active keyboard layout name: FR

## To Reproduce

Install AltDrag from https://stefansundin.github.io/altdrag ([github repo](https://github.com/stefansundin/altdrag))
Configure it as:
![image](https://user-images.githubusercontent.com/9730330/129178507-597b7bb8-4f68-4b1f-bb32-e69b0587b509.png) ![image](https://user-images.githubusercontent.com/9730330/129178569-4ebe5f96-968b-4b0d-b103-4bbae2d282bd.png)

Open a small (non-maximized) Wezterm window, then try the following scenarios:

NOTE: the clicks can be anywhere on the window.

1. Try to move the window with AltDrag: `Super+left-click-and-drag`
   -> It's laggy
   -> See NOTE below.

2. Try to resize the window with AltDrag: `Super+right-click-and-drag`
   -> It's laggy when it works
   -> Sometimes it even breaks the Window's window manager in a way, where mouse input doesn't work anymore for other apps.. (until I close Wezterm completely).
   -> See NOTE below.

3. Try to maximize the window with AltDrag: hold `Super+left-click` and do a `right-click` (simultaneously)
   -> usually it works, except sometimes where the window is maximized, but the content is not refreshed at all, looking like some part is of the backgroud color, and some part is transparent (I see my wallpaper). 👉 after a few seconds it works, and the content is there.
   (note: I can't post a screenshot right now)
   It might be linked to the fact that I usually have this behavior when wezterm is opened on a bigger external screen than the screen of my laptop.

NOTE: For 1. & 2., wezterm behaves as if I clicked and started a selection, or sends mouse input to the program if it has enabled mous reporting. (whereas I think AltDrag _should_ not send anything to the window it's moving... Maybe Wezterm hooks on mouse input lower than AltDrag?)

NOTE: For 3. I'll try to update to the latest nightly, maybe it's because of slow font loading that happened in previous versions.

## Configuration

I tried to disable the SUPER + clicks, to avoid having the clicks send down/up/drag events to the toplevel program, with:
```lua
return {
  mouse_bindings = {
    { mods="SUPER", event={Up={streak=1, button="Left"}}, action="Nop" },
    { mods="SUPER", event={Down={streak=1, button="Left"}}, action="Nop" },
    { mods="SUPER", event={Drag={streak=1, button="Left"}}, action="Nop" },
  
    { mods="SUPER", event={Up={streak=1, button="Right"}}, action="Nop" },
    { mods="SUPER", event={Down={streak=1, button="Right"}}, action="Nop" },
    { mods="SUPER", event={Drag={streak=1, button="Right"}}, action="Nop" },
  }
}
```
But even with these, doing a window move with AltDrag will trigger drag events click & drag events in Wezterm.
👉 Might be related to #581? But not necessarily as even without any programs with mouse reporting wezterm behaves as if it got mouse inputs..
Maybe Wezterm is hooked up in the mouse input stack lower than AltDrag, but it is hooked up higher in the keyboard stack than AltDrag, in which case, Wezterm would only see the mouse inputs, but not that SUPER is pressed, meaning the workaround I tried wouldn't work?
(NOTE: I'm speculating, I don't know if there is a mouse/keyboard input stack at all on windows..)

## Expected behavior

Smooth movements, resize, and maximize properly.
Try AltDrag with a Window Explorer window for example!

## Considered alternative

Maybe I could reproduce the behavior I want with wezterm action `StartWindowDrag` but afaik there isn't one named `StartWindowResize`, and (less important) the maximize with left+right click isn't possible with current mouse bindings definitions.

---
I'm not sure how to debug that, I'm happy to give more info if necessary! 🙃

**Comment by wez** [comment]
FWIW, WezTerm doesn't do any hooking; just normal Windows event loop stuff scoped to its own process.

AltDrag however makes use of invasive system-wide hooks that inject DLLs into every application to change their behavior and attempt to override it.  I wouldn't recommend using software that uses that technique because it is prone to compatibility issues like this, where the impact is outsized: because the hook state is shared system-wide, an issue with one program can impact how the hooking program works across the others.

It's important to note that it isn't wezterm that is causing the problem in this case: AltDrag is doing "naughty" stuff and (runtime) patching other programs, making assumptions about how they work and overriding behaviors across the system.

(And this isn't a commentary on AltDrag itself, but system-wide hooks are potentially a bit scary from a security/integrity perspective, especially things that monitory all your keyboard input!).

My recommendation (which you probably won't like!) is to configure AltDrag to so that it doesn't hook into wezterm.  The code mentions a process blacklist so I'm assuming that there is a setting where you can add `wezterm-gui.exe` to have altdrag skip it.

**Comment by bew** [comment]
> (And this isn't a commentary on AltDrag itself, but system-wide hooks are potentially a bit scary from a security/integrity perspective, especially things that monitory all your keyboard input!).

True.. but these are so necessary as Windows isn't great for power users like me who wants specific behavior... I have the same security issue with AutoHotKey for example, but I think I can't live without it on Windows without becoming crazy ^^)



> My recommendation (which you probably won't like!) is to configure AltDrag to so that it doesn't hook into wezterm. The code mentions a process blacklist so I'm assuming that there is a setting where you can add `wezterm-gui.exe` to have altdrag skip it.

Hmmm that's I think the best thing I can do.. I also got the idea after writing the above issue (in the section `considered alternative` near the end).

I can probably reproduce the easy window movement with the action `StartWindowDrag`.
For the resize I'm a bit out of luck, except if you/someone/me add a `StartWindowResize` action.
What do you think of this?

**Comment by wez** [comment]
> For the resize I'm a bit out of luck, except if you/someone/me add a `StartWindowResize` action.
What do you think of this?

I'm open to adding that kind of functionality, but it's not high on my personal priorities (I tend to have a fairly static window arrangement!).  Happy to see a PR :-)

**Comment by bew** [comment]
Me too, but sometimes when I share a single screen it's handy to have the terminal in a smaller window `¯\_(ツ)_/¯`

**Comment by eugenesvk** [comment]
Have you tried the newly maintaned fork of AltDrag called [AltSnap](https://github.com/RamonUnch/AltSnap/releases) that fixes a lot of bugs in AltDrag?
This new fork mostly fixes this issue with WezTerm for me (it's still not immediate like in all other windows, but the delay is sub-second and it's only on "start", so not that big of a deal)

**Comment by bew** [comment]
Thanks, yeah I've been using AltSnap for a few months now, but avoiding to use it on wezterm since I knew it was kindof broken with AltDrag.
I tested it on wezterm today, it definitely is better and almost does not lag, so kudos to @RamonUnch 🥇👍.

I'm for close then.. and maybe add a note to promote AltSnap instead of AltDrag

**Comment by eugenesvk** [comment]
> I'm for close then.. 

Well, there is still initial lag, so would be great if wez could figure out the root cause since it might also be the one behind my issue with WinDivvy (there isn't a new maintaned fork of that one unlike with AltDrag :( ), but there is a separate issue for that, so guess this can be closed

> and maybe add a note to promote AltSnap instead of AltDrag

good idea, I've submitted a PR with this change

**Comment by wez** [comment]
Regarding lag with AltSnap, did you see and try the refresh rate options mentioned here?
https://github.com/RamonUnch/AltSnap/issues/87

**Comment by eugenesvk** [comment]
Yes, doesn't remove it
I had these settings
```
MoveRate=2
;[1] default
ResizeRate=4
;[2] default
; Sane values are below 10
; Recommended is 1 to 5
```
Changed both to `10`, the initial lag is still there, but the degradation of the overall experience masks it since everything becomes laggy

**Comment by wez** [comment]
AltSnap at least is no longer laggy for me, so I'm assuming this is good now

**Comment by wez** [comment]
https://github.com/wez/wezterm/issues/1398 was confirmed resolved, so I'm closing this one as well!
