### ISSUE TITLE
Disabling default ActivateTabRelative=-1 or ActivateTabRelative=1 does not work

### ISSUE THREAD

**Issue by djwf** [wez/wezterm#1019]
## Describe the bug

I have failed to disable the use of `SUPER+SHIFT+[` and `SUPER+SHIFT+]` to change to different tabs by changing their action to "Nop" or "DisableDefaultAssignment".

## Environment (please complete the following information):

 - OS: macOS 11.5
 - Version: wezterm 20210502-154244-3f7122cb
 - ENG

## To Reproduce

Place the following content in your `~/.wezterm.lua` (I tried it with just this setting to see if it would work):

```lua
return {
  keys = {
    {key = "]", mods="SUPER|SHIFT", action="DisableDefaultAssignment"},
}
```
Attempt to change the active tab to the left or right.

## Expected behavior

Pressing `SUPER+SHIFT+[` or `SUPER+SHIFT+]` would do nothing (if using "Nop") or pass that key combination to the terminal (if using "DisableDefaultAssignment").

**Comment by wez** [comment]
You also need to disable this assignment:

https://github.com/wez/wezterm/blob/main/config/src/keyassignment.rs#L372

On some systems we need to match `SHIFT+]` but on others that is reported to us as `}` so we have assignments for both combinations.  For the sake of brevity/clarity of intent, we only document one of those in the docs.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html is handy to troubleshoot this sort of thing in case you run into something else like this in the future!

**Comment by djwf** [comment]
Thanks! I tried all the combinations of `SUPER`, `SHIFT`, and `]`/`}`, but never tried `SUPER` without `SHIFT`. :)

Also, thanks for the tip about the debugging_key_events.
