### ISSUE TITLE
Glitches when resizing window in Wayland + Gnome 40

### ISSUE THREAD

**Issue by VarLad** [wez/wezterm#1020]
## Describe the bug

The resizing is bugged
The window is repositioned on every resize
Resize from the top extends the window at the bottom
Maximizing is broken. 
The bar with the maximize/minimize buttons sometimes goes "into" the activity bar in GNOME, sometimes

## Environment (please complete the following information):

 - OS: Fedora 34 Wayland (GNOME40)
 - Version: wezterm 20210814-124438-54e29167
 - The active keyboard layout name ENG

## To Reproduce
Enable NVIDIA proprietary drivers on Fedora 34 (my current and latest one being 3:470.57.02-1.fc34 version)
Then enable Wayland on Fedora and start Wezterm in a Wayland session

The problem also persists when using Intel drivers to run Wezterm. This might be an issue with Wezterm+GNOME Wayland, rather than NVIDIA problem

## Configuration

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("JuliaMono");
  font_size = 15.5;
  color_scheme = "Wombat";
  default_prog = {"fish", "-l"};
  enable_wayland = true;
}
```

## Expected behavior
The resizing works properly

## Screenshots
![Screenshot from 2021-08-15 14-07-36](https://user-images.githubusercontent.com/51269425/129472425-08c78003-0d89-46fb-ba64-63f1acfa34f2.png)

## Session Recording

https://user-images.githubusercontent.com/51269425/129472412-ebe3c023-29a6-417f-9881-2c50a267e54f.mp4

## Additional context

The top bar going into activities happens usually after starting up Wezterm immediately

**Comment by VarLad** [comment]
Note that the workaround here is to put:
```lua
enable_wayland = false;
```
in the config file
That makes it use XWayland instead 
But note that native-Wayland experience is _smoother_

**Comment by wez** [comment]
I'm surprised it runs at all with nvidia drivers, as the best I've seen from it on Fedora 33 and earlier is a failure to initialize: https://github.com/wez/wezterm/issues/484

However! The resize behavior is at the intersection of the compositor (Mutter in Gnome) and the smithay-client-toolkit crate that is used to provide the wayland implementation: when you grab a window edge, the compositor drives the resize and configures the window. 

Would you mind trying the following steps:

```bash
; cd /tmp
; git clone https://github.com/Smithay/client-toolkit.git --depth 1
; cd client-toolkit
; cargo run --example pointer_input
```

and then try resizing that window.  If it has the same behavior as you saw, then we should report this to the SCTK folks, but note that in the past, issues I've raised there have actually been Mutter issues, so we may have a bit of a journey.

**Comment by VarLad** [comment]
@wez Thanks for your response
I tried resizing the window
There's a tiny bit of a lag to it, but resizing the window works perfectly here!

**Comment by VarLad** [comment]
https://user-images.githubusercontent.com/51269425/129483610-a62c63b4-9c8a-4589-8250-3cccedee5062.mp4

Here's a video of the same

**Comment by wez** [comment]
I upgraded to Fedora 34 and enabled Wayland, but I still can't run with the nvidia drivers because #484 is still an issue with the nvidia egl implementation.  Did you do anything in particular to make egl work?

Please press CTRL-SHIFT-L to activate the debug overlay and copy and paste the `OpenGL initialized` log line so that I can see what wezterm thinks of the GPU!

That said, I can run with llvmpipe (using the `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json` workaround from #484) and reproduce the weird resize behavior, so I have something I can investigate here.

**Comment by VarLad** [comment]
```
21:29:04.796 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-92344
21:29:04.989 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 21.1.7 is_context_loss_possible=false wezterm version: 20210814-124438-54e29167
>
```

**Comment by VarLad** [comment]
I thought it was running on NVIDIA.... 
```fish
~ via ஃ v1.6.2 via ↯ v0.8.0
❯ glxinfo | grep vendor
server glx vendor string: SGI
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
```

**Comment by VarLad** [comment]
@wez Can I somehow "force" it to run on my NVIDIA GPU?

**Comment by wez** [comment]
I think there's an attribute that can be turned on in code that I can expose via the config system, but it's moot right now because https://github.com/NVIDIA/egl-wayland/issues/34 blocks egl from working with nvidia

**Comment by VarLad** [comment]
Should it work on the GPU with X11?
I can try on X11 too....

**Comment by wez** [comment]
Actually, I think you can run: `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json wezterm` to force only nvidia to be selected

**Comment by wez** [comment]
If you run with X11 then it works: that's how I typically run it

**Comment by VarLad** [comment]
True
Does work flawlessly in X11
I hope it works in Wayland soon too

Any idea by when can we see that?

**Comment by wez** [comment]
nvidia + fedora need to make wayland work well before it becomes usable platform for me to develop for.  I took a look at the resize issue a bit today, but because it runs with a software renderer, it's a pretty horrible experience to iterate on right now.

**Comment by VarLad** [comment]
Okay, @wez 
Suppose I've an AMD APU (CPU + Integrated GPU) + NVIDIA GPU
The integrated GPU is pretty powerful and good enough for me to give HW acceleration for Wez

Will I be experiencing the same resizing issue on GNOME40 + Wayland + AMDGPU as well?

**Comment by wez** [comment]
I expect that you'll see the same behavior there as well.  I'd like to see this fixed, but my personal motivation is low because Wayland doesn't work with my hardware.  Until it is gets on par with X11, it's going to be second-class compared to X11 support.

**Comment by VarLad** [comment]
Well, NVIDIA's infamous for other problems in Linux
But other than that, Wayland's considered quite stable with both Intel and AMD (both GPUs and iGPUs)

Fedora already gives Wayland as default along with many other distros. 

I suppose I can use it with my AMD card via XWayland so thats not an issue, but Wayland support would be nice as its much smoother

**Comment by wez** [comment]
I don't disagree, but in terms of my priorities: since I can't run it on my hardware, it will be slow for Wayland support on WezTerm to improve.  If someone with a working Wayland setup is willing to contribute energy to make it better, then it will move faster.

**Comment by VarLad** [comment]
I can't reproduce this issue anymore. I'll close it for now. 
I'll reopen it if I encounter it again on older hardware
