### ISSUE TITLE
Lag after selection

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#1027]
## Describe the bug
After selection of some text wezterm pauses for a moment, before you can actually input again. Happens especially often when using the primary clipboard on linux (middle click).

This seams to be a regression, it works in 20210502-154244-3f7122cb.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210815-182117-ab21910d

## To Reproduce

Select Text with your mouse, try to type or paste via middle click on linux.

## Configuration
Happens without config.

## Expected behavior
It should be possible to paste the selection or continue typing without delay

**Comment by wez** [comment]
Hmm, weird.  I can reproduce this.  When I read your report I thought you must have been hitting the cost of computing the zones that I'd shut off in e1ee1ddd97b544b68f29609a9f1e1eed6cb29ef0, but this lag is present even after that. Will need to dig into this to figure out where its coming from.

**Comment by wez** [comment]
Could you try fc5ca5a2975c74e106ab6165dd5496acc306c268 (or really: the latest nightly) and see if this is better for you?

**Comment by ModProg** [comment]
This seams to have solved it :+1:
