### ISSUE TITLE
wezterm-cli-split-pane doesn't respect PATH

### ISSUE THREAD

**Issue by malkomalko** [wez/wezterm#1029]
## Describe the bug

Trying to use `wezterm-cli-split-pane` to launch a program fails because I can't set a PATH.

## Environment (please complete the following information):

 - OS: macOS 11.4
 - Version: wezterm 20210815-182117-ab21910d
 - The active keyboard layout name ENG

## To Reproduce

`wezterm cli split-pane --horizontal -- kak` replacing kak with any program not in a default PATH.

```
 2021-08-16T14:17:48.847Z ERROR wezterm > unexpected response Ok(ErrorResponse(ErrorResponse { reason: "Error: Unable to spawn kak because it doesn't exist on the filesystem and was not found in PATH" })); terminating
```

## Configuration

I tried using the `set_environment_variables` config option, but it doesn't seem to be respecting it.  I've tried `PATH` instead of `path` and nothing seems to work.

```lua
  set_environment_variables = {
    path = "/usr/local/bin:/usr/bin",
  },
```

## Expected behavior

I would expect to be able to launch programs from the `cli` tool in a non-default PATH.

## Screenshots

n/a

## Session Recording

n/a

**Comment by malkomalko** [comment]
From looking at some code, the entry point appears to be:

https://github.com/wez/wezterm/blob/769f632a2679bc384a10d21c0ac04e86e0ce3e70/wezterm/src/main.rs#L448

Which ends up calling CommandBuilder

https://github.com/wez/wezterm/blob/769f632a2679bc384a10d21c0ac04e86e0ce3e70/pty/src/cmdbuilder.rs#L35-L43

Looks like env vars are always set to an empty list.  I could have this totally wrong of course :)

**Comment by wez** [comment]
I think the issue is that the process PATH was searched, rather than the path you set in the config.
If you try the commit I just pushed together with `set_environment_variables = { PATH = "..." }` then it should behave a bit better

**Comment by wez** [comment]
(that commit will show up in the nightly build within ~30 minutes; when the dot next to the commit turns green it'll be there)

**Comment by malkomalko** [comment]
Wonderful.  I'll give it a go soon once the build turns green.  Thanks wez!

**Comment by malkomalko** [comment]
This worked perfectly.  Thank you for the quick response.
