### ISSUE TITLE
Titlebar overhang with scrollbar disabled

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#103]
## Describe the bug

The titlebar overhangs the window with scrollbar disabled.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Frontend:  OpenGL
 - Version: wezterm 20191229-193639-e7aa2f3-31-g437b166

## To Reproduce

Start wezterm with no config
## Configuration

Default (no config file)

## Expected behavior

Titlebar to line up with window body

## Screenshots
![image](https://user-images.githubusercontent.com/147966/71685705-fbe45b80-2d4d-11ea-960b-a8b35fdf34dd.png)

**Comment by wez** [comment]
Fixed in master
