### ISSUE TITLE
configurable default gui subcommand (eg: `start` (default), `ssh` etc.)

### ISSUE THREAD

**Issue by djwf** [wez/wezterm#1030]
**Is your feature request related to a problem? Please describe.**
I have been frustrated when I try to configure wezterm to always connect to a particular ssh host by default, because setting default_prog to use ssh does not use the libssh2 built-in to wezterm, and using plink results in a login using the text encoding that the windows terminal uses by default (not UTF-8).

**Describe the solution you'd like**
I would like to be able to set the default action upon starting a new wezterm instance (or tab) to use the built-in ssh capabilities. I would like to be able to do this using entries in the configuration file, not on the command line.

As a bonus, it would be great to be able to launch an ssh session from within wezterm terminals that used the wezterm ssh capabilities.

**Describe alternatives you've considered**
I've thought about trying to make the default cmd.exe use the UTF-8 code page by default, only then launching plink from within wezterm, but haven't discovered a way to do that that is complete (covers input as well as output).

**Comment by wez** [comment]
Doing literally what you're asking for needs some thought, but in the meantime, have you considered using:
https://wezfurlong.org/wezterm/multiplexing.html#ssh-domains
You should be able to configure the ssh_domain to connect automatically and that sounds close to what you're asking for, if you're ok with installing the wezterm-mux-server on the target host.

**Comment by djwf** [comment]
Right now my workaround (I should have mentioned this) is to simply use a shortcut or launcher to start the terminal: `wezterm-gui ssh user@host`. I'll mess with the ssh-domains. I had looked at them, but not in-depth once I figured out I couldn't use the libssh2 subsystem.

**Comment by wez** [comment]
Today `wezterm` with no arguments is considered to be the same thing as `wezterm start` with no additional arguments.
The `start` subcommand will resolve and launch `default_prog`.

We could introduce a config option named something like `default_gui_startup_args` that defaults to `{"start"}` that can be overridden to specify `{"ssh", "somehost"}` and so on.
