### ISSUE TITLE
Error building wezterm from arch aur

### ISSUE THREAD

**Issue by nerdo** [wez/wezterm#1038]
## Build Environment (please complete the following information):
```
➜  wezterm-git git:(master) ✗ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

```
➜  wezterm-git git:(master) ✗ uname -a
Linux gladiator 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux
```

```
➜  wezterm-git git:(master) ✗ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/nerdo/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.50-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

## Dependencies

n/a, I'm using arch and simply ran `makepkg -si` to build and install wezterm from https://aur.archlinux.org/packages/wezterm-git/

## The build output

Rust starts to build dependencies but fails at this point...

```
   Compiling zvariant v2.8.0
error[E0599]: no variant or associated item named `Unsupported` found for enum `ErrorKind` in the current scope
   --> termwiz/src/escape/apc.rs:251:41
    |
251 |                 Err(std::io::ErrorKind::Unsupported.into())
    |                                         ^^^^^^^^^^^ variant or associated item not found in `ErrorKind`

   Compiling ssh2 v0.9.1 (https://github.com/wez/ssh2-rs.git?branch=win32ssl#c6506704)
   Compiling portable-pty v0.5.0 (/home/nerdo/arch/aur/wezterm-git/src/wezterm/pty)
error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `termwiz`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by wez** [comment]
You need Rust 1.53 or newer.  @gaborbernat: is there a way to express that in the PKGBUILD?  This is something that we check in [get-deps](https://github.com/wez/wezterm/blob/main/get-deps#L41) so it may be simply a matter of running that before we run `cargo build` in the PKGBUILD

**Comment by gaborbernat** [comment]
@nerdo arch rust is currently at version 1.54 - see https://archlinux.org/packages/extra/x86_64/rust/, so the only way this can happen is if you don't upgrade your OS but pull in wezterm-git. With arch being a rolling release I recommend upgrading the OS regularly, at least to build wezterm-git. I'm not aware of a way to express this constraint within the PKGBUILD.

**Comment by wez** [comment]
@gaborbernat the constraint is encoded in `get-deps`; can you try adding that to the PKGBUILD before it runs `cargo build`?  I think that will help explain this sort of error more clearly.  Rust doesn't have a way to encode rust compiler version constraints in `Cargo.toml` :-/

**Comment by gaborbernat** [comment]
> ; can you try adding that to the PKGBUILD before it runs `cargo build`

Can you detail how? 😊

**Comment by MuhammedZakir** [comment]
Doesn't adding version restriction for `rust` in `makedepends` solve this? From `PKGBUILD` arch wiki [1]:

`depends`:
> Version restrictions can be specified with comparison operators, e.g. `depends=('foobar>=1.8.0')`; if multiple restrictions are needed, the dependency can be repeated for each, e.g. `depends=('foobar>=1.8.0' 'foobar<2.0.0')`.

`makedepends`:
>  The minimum dependency version can be specified in the same format as in the `depends` array.

[1] https://wiki.archlinux.org/title/PKGBUILD#Dependencies

**Comment by nerdo** [comment]
Thanks everyone.

Apparently I had rust installed in a weird way. I had `rustup` installed in arch, but not the `rust` package itself. I removed that and just installed the `rust` package and now wezterm built successfully.

+1 for setting the version dependency in PKGBUILD

**Comment by wez** [comment]
> > ; can you try adding that to the PKGBUILD before it runs `cargo build`
> 
> Can you detail how?

I think just putting:

```
./get-deps
```

on the line before the cargo build might do it, if the depends syntax doesn't cover it.

**Comment by gaborbernat** [comment]
Added:

```
rust>=1.51 (rust-i586-git, rust-git, rustup-git, rust-nightly, rust-nightly-bin, rust-wasm, rustup) (make)
```
