### ISSUE TITLE
Scrollbar doesn't work for remote muxed windows

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#104]
## Describe the bug

When wezterm with a remote host, the scrollbar doesn't work.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Frontend: OpenGL
 - Version: wezterm 20191229-193639-e7aa2f3-35-g5b45071

## To Reproduce

1. set up a client/server pair
2. configure scrollbar
2. run server (`wezterm start --front-end MuxServer --daemonize`)
3. run client connecting to server (`wezterm connect <server>`)

List more than a page of output. Moving scrollbar doesn't work. Using mouse wheel does (though scrollbar doesn't move)

## Configuration

```
scrollback_lines = 100000
enable_scroll_bar = true
```

## Expected behavior
Scrollbar should work as it does for local terminal.

**Comment by wez** [comment]
This works now in master

**Comment by jsgf** [comment]
LGTM
