### ISSUE TITLE
Title corruption is "sticky"

### ISSUE THREAD

**Issue by andrewvaughanj** [wez/wezterm#1044]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20210818-083353-2013718

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Getting `wezterm` to print garbage can lead to "title corruption" -- however, once this "title corruption" has occurred it seems it cannot be "undone".

![image](https://user-images.githubusercontent.com/14277540/129933726-63fd2664-7992-42e8-9157-334fa3eb015a.png)

### To Reproduce

- open `wezterm`
- ssh to a Linux box
- run `echo -en "\e]2;mooo\a"`
- see that the title has changed
- run `dd if=/dev/urandom bs=1MB count=1`
- see that the title has become garbage
- run `echo -en "\e]2;mooo\a"`
- see that the title is still garbage

### Configuration

None; totally empty config

### Expected Behavior

Running `echo -en "\e]2;mooo\a"` should set the title, irrespective of what it is currently set to.

### Logs

(can provide logs, but capturing them with `WEZTERM_LOG=wezterm_gui::glyphcache=trace,info` didn't even show the original title-setting, so it seemed "pointless")

**Comment by wez** [comment]
There's no logic that would make it sticky, however, there is a separate concept of title and icon text:

https://wezfurlong.org/wezterm/escape-sequences.html#operating-system-command-sequences

Try using `OSC 0` instead of `OSC 2`?

**Comment by andrewvaughanj** [comment]
Yeah, `0` works 🥳 

However, based on your link, shouldn't `2` _at least_ set the window title (but not the icon)? It seems it doesn't do that either.

**Comment by wez** [comment]
The default window title logic is represented here:

https://wezfurlong.org/wezterm/config/lua/window-events/format-window-title.html

if you've set the icon and the window title, then the icon text will take precedence

**Comment by andrewvaughanj** [comment]
Okay, cool; so it is working as expected :)

Thanks!!!
