### ISSUE TITLE
No background opacity / transparency

### ISSUE THREAD

**Issue by kar1** [wez/wezterm#1049]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20210819-100706-66ff7740

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After installing the nightlies version I lost opacity. I only have it on the cursor line after the cursor, see attached screenshot,

![no_opacity](https://user-images.githubusercontent.com/1486711/130148094-df663081-fbcd-43d0-9af4-d294986f3b94.png)

![no_opacity-2](https://user-images.githubusercontent.com/1486711/130150552-dd26f656-c334-4017-b13a-db3215ec4a85.png)

And the window padding seems to be affected too.

### To Reproduce

```sh
wezterm --config 'window_background_opacity = 0.2'
```

### Configuration

```lua
return {
  window_background_opacity = 0.2,
}
```

### Expected Behavior

Beautiful semi-transparent terminal background 

### Logs

```
23:20:43.138 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2) 3.0 Mesa 20.3.5 is_context_loss_possible=false wezterm version: 20210819-100706-66ff7740
```

### Anything else?
The Glium error you can see in the screenshot only happens when I start a Wezterm from a Wezterm and not normally. This is unrelated to the loss of opacity, i.e. when the glium error doesn't happen there is still loss of opacity.

**Comment by wez** [comment]
Sorry about that: I think I've fixed this with the latest commit.

For the opengl/glium error, can you run with `WEZTERM_LOG=window=trace,info` set in the environment to see if it logs the actual error somewhere?

**Comment by kar1** [comment]
Fixed :-) Thanks

reg: glium
[issue-1049.log](https://github.com/wez/wezterm/files/7023227/issue-1049.log)

There isn't more info in the logs :-/ It's been doing it for a very long time, but I didn't report it because every thing seems to work. I'll try digging in to it and open another issue if I find something.
