### ISSUE TITLE
Pasting doesn't work for remote muxed terminals

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#105]
## Describe the bug

When using a terminal on a remote machine, I can select text, but I can't paste it - either with middle button, or with Ctrl-Shift-C / V.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Frontend:  OpenGL
 - Version: wezterm 20191229-193639-e7aa2f3-35-g5b45071

## To Reproduce

1. set up wezterm server
2. connect with client (matching version)
3. Select some text
4. try to paste it back into the same window, or a different one; nothing happens.

## Configuration

Be sure to include the relevant section(s) of your `wezterm.toml` configuration file.

## Expected behavior

Text should be pasted.

## Other notes

Existing text in the buffer is not replaced, so it looks like the select/cut operation isn't doing anything. Pasting in another (local) window shows the previous content. Selecting text in a local window can't be pasted to a remote wezterm session.

**Comment by wez** [comment]
master now processes selection 100% locally, so this should work now, modulo bugs from changing its guts around.

**Comment by jsgf** [comment]
I'm seeing problems pasting from a local gnome-terminal into a muxed wezterm. Middle-click and Shift-Ins paste doesn't work, but Ctrl-Shift-C/V does work.

**Comment by wez** [comment]
shift-ins and ctrl-shift-v should work identically, so that sounds weird!
