### ISSUE TITLE
Somehow indicate that there is new output in a tab

### ISSUE THREAD

**Issue by Tobbe** [wez/wezterm#1050]
**Is your feature request related to a problem? Please describe.**

This feature would help with two things when having multiple tabs open
1. I sometimes fire off a task that takes several seconds (or longer) to complete. While waiting for that I switch to other tabs to continue working there. Some kind of indication of new output would (depending on the nature of the task) help show when the task has completed without me having to constantly switch to the tab to check if it's done or not.
2. If I have a forever-running process in a couple of tabs that constantly produces output some kind of indication of new output would allow me to quickly identify what tabs have these processes running so I can switch to them to check their output or switch to them to kill the process if that's what I want

**Describe the solution you'd like**

Another terminal I use adds an asterisk (*) to the end of the tab title to indicate new output. Other options could be to change tab color, underline tab title, change tab border color, or any other kind of visual indicator.

**Describe alternatives you've considered**

What I'm really looking for is 1. A way to know that a task has completed in an inactive tab. 2. Know what tabs have forever-running processes. Any other way to solve those two use-cases that's not just indicating new output is obviously also welcome 🙂. Like maybe add a 🔄 icon to tabs with long-running processes. And then when/if they finish, change to a ✅ or ❌ icon depending on exit code.

**Additional context**

Nope

**Comment by wez** [comment]
A couple of things to consider:

There's a little bit of conceptual overlap with https://github.com/wez/wezterm/issues/3

Configuring [Shell Integration](https://wezfurlong.org/wezterm/shell-integration.html) would teach your shell to advise wezterm of prompting and output states through the use of OSC 133 semantic zones.  We could potentially teach wezterm to generate an internal event when the zone type in a pane changes.  The semantic escapes also allow for recording information about running commands and their exit results which could also be plumbed through in a similar way.

In the meantime, you may be able to satisfy yourself with a little bit of playing around with your shell dotfiles and your wezterm config; take a look at the discussion on https://github.com/wez/wezterm/issues/647 wherein *user vars* are used to convey information from the shell to the tab formatting function and color the tab based on its state.

**Comment by wez** [comment]
In terms of output-since-last-examined, the underlying pane object has a sequence number representing the "time" that the pane was last changed. We could track the last rendered sequence number in the gui state alongside the other per-pane data that we track.  Those two pieces of data could feed into the tab formatting to decide if there's been information since the last render.

**Comment by wez** [comment]
I forgot that we had this issue as well as this discussion; I pushed some changes and posted about them over here:
https://github.com/wez/wezterm/discussions/796#discussioncomment-1991786

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/PaneInformation.html is available in the current release
