### ISSUE TITLE
Provide Debian 11 Bullseye release

### ISSUE THREAD

**Issue by kar1** [wez/wezterm#1052]
**Is your feature request related to a problem? Please describe.**
When I run the latest nightlies on Debian 11 Bullseye I get the error:
```sh
/usr/bin/wezterm-gui: error while loading shared libraries: libxcb-util.so.0: cannot open shared object file: No such file or directory
```
In Debian 11 there is no `libxcb-util.so.0` but a `libxcb-util.so.1`. I think it's just a matter of building on a Debian 11 so it gets linked to the new libxcb-util version there. I have tried building from source on my Debian 11 system without any problems.

**Describe the solution you'd like**
A precompiled Debian 11 .deb version of Wezterm.

**Describe alternatives you've considered**
I'm not sure if you would like me to try and build it on github's ci system? I would copy the files:

```
gen_debian10.3.yml
gen_debian10.3_continuous.yml
gen_debian10.3_tag.yml
```

and replace debian10.3 with debian11 and see what happens :-)? Should I do that now or maybe next time? Is there a way I can build it on Github Actions without building the other releases and without uploading etc. Please advice, thanks.

**Comment by wez** [comment]
If you want to make a PR for this the steps are:

* Add a debian 11 line around here: https://github.com/wez/wezterm/blob/main/ci/generate-workflows.py#L557
* Run `ci/generate-workflows.py`
* Add the changes to the commit and a PR from it
* See if any other special cases are needed for debian11, and adapt, repeat!

**Comment by kar1** [comment]
Thanks for the help. Lets see if it runs #1053

**Comment by wez** [comment]
Once that lands, the next step is to add a Debian11 line to https://raw.githubusercontent.com/wez/wezterm/main/docs/install/linux.markdown

Since we don't yet have a stable release, what I usually do is make that cell say something like "nightly only", and then remember to go back and fill it in once a new release is made!

**Comment by kar1** [comment]
Thank you.

**Comment by wez** [comment]
Thank you!

**Comment by kar1** [comment]
The new debian11 link in the docs is not being processed.

I think I missed adding a debian11 line here:
https://github.com/wez/wezterm/blob/1e52016359338f88507a35dcf014aea0f7e116bf/ci/subst-release-info.py#L20

Is that correct? Should I push to the same branch?

PS - I really appreciate you taking the time to help me on this.

**Comment by jameschensmith** [comment]
Not sure if this is the best place to put this, but I ran into some problems when using the current Debian 11 nightly image. On my machine I was missing the following:

- `libxcb-util.so.1`
- `libxcb-image.so.0`

By running the command below, I was able to run Wezterm.

```
sudo apt install libxcb-util-dev libxcb-image0-dev
```

I'm still learning Debian/apt, but shouldn't this be automatically installed with the `.deb` package?

**Comment by wez** [comment]
@jameschensmith hmm, yeah, probably; I've pushed 83d159ae2158ad7bcba5d050c75d0adafe16252f which may help.  Not 100% sure about the package names, but you usually don't have an executable package depend on a `-dev` package, so let's see how we do when the CI tries to build this out.

**Comment by jameschensmith** [comment]
@wez, ahh. That makes sense. I think you were close, but it may fail. Looks like `libxcb-util` should be `libxcb-util1` (at least in Debian 11).
