### ISSUE TITLE
"Nerd Fonts" get rendered weirdly

### ISSUE THREAD

**Issue by 0neGal** [wez/wezterm#1058]
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland, FreeBSD X11, FreeBSD Wayland

### WezTerm version

20210821-070816-9a112e82

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I recently noticed after an update that certain shapes in my [nerd fonts](https://github.com/ryanoasis/nerd-fonts) were rendered very weirdly... Below is an example:
![image](https://user-images.githubusercontent.com/33325154/130328592-a0f7f746-25ba-4bb5-8db9-d3d25d835290.png)

Besides that for some reason when a new terminal is created nothing works but the first line, aka when you enter a command it's almost like it clears the screen. Below is a video of that, I briefly re-open the terminal *(which is why you get to see the ffmpeg terminal and my wallpaper)*

https://user-images.githubusercontent.com/33325154/130328684-921ff5f9-1d3b-41b4-8494-275ade8d4afc.mp4

This fixes itself if you:
 * Resize the window
 * Hit enter with nothing in the prompt

This also occurs in terminal programs such as Vim and fzf and alike... I'm simply assuming this is related to the font issue but I quite frankly have no clue.

### To Reproduce

 1. Have some kind of Nerd Font as a fallback/font
 2. Be on a version above `20210502-154244-3f7122cb`
   - I have no clue when it started happening but downgrading to that version solves the issue completely.
 
For reference my prompt should've looked like this:

![image](https://user-images.githubusercontent.com/33325154/130328948-33381f10-a48d-4668-b387-b8c6adf361e8.png)

### Configuration

My font configuration
```lua
font_shaper = "Harfbuzz",

font_antialias = "Greyscale",
font_hinting = "Full",

font_size = 12,
font = w.font_with_fallback({
	"RobotoMono Nerd Font",
	"Roboto Mono",
	"Noto Sans Mono",
	"Cantarell",
}, {weight="Medium"}),
```
However I would like to point out removing my entire config still produces the issue, I presume WezTerm fallbacks to the font.

### Expected Behavior

The symbols should rather look like they did before the update:
![image](https://user-images.githubusercontent.com/33325154/130328948-33381f10-a48d-4668-b387-b8c6adf361e8.png)
And it obviously shouldn't be clearing the screen when you type a command.

### Anything else?

My only guess is that for some reason it instead of using my actual desired font it uses some random font I have installed which has these malformed symbols, maybe? But that doesn't explain the clearing of the screen.

**Comment by wez** [comment]
Re: the nerd font glyphs, I think the difference in appearance is that wezterm is substituting its own versions of the those shapes. Take a look at https://wezfurlong.org/wezterm/config/lua/config/custom_block_glyphs.html to try disabling those if you prefer.
I'm not super sure what it is that you find weird about them; is it the shape of the curve?

Running `wezterm ls-fonts` can give some clues about font issues.

For the weird flash/emptiness issue: I've not seen that behavior before! Do you have any transparency or similar settings in your config?  Is there something showing up in the logs?  CTRL-SHIFT-L will show the debug overlay, or you can run wezterm from another terminal to see the stderr output.

Can you try `wezterm -n start bash -- --norc` to see if running bash with no dotfiles looks/behaves OK?

**Comment by 0neGal** [comment]
> I'm not super sure what it is that you find weird about them

Specifically those shapes were intended to be half circles, so the almost triangular like shape is a little off putting :p

But indeed disabling it with:

```lua
custom_block_glyphs = false,
```

Does fix the issue, funny enough it also fixed some other issues I had with some icons being the wrong size so that was very useful.

<br><br>

> Is there something showing up in the logs?

Nothing interesting besides this part

```
WARN  wezterm_term::terminalstate::performer > Unhandled OSC  708 #FFFFFF
```

Besides that some errors about `font_hinting` and `font_antialias` not being a real thing, perhaps it got removed without me realizing it, because I thought that was a real setting.

<br><br>

> Can you try `wezterm -n start bash -- --norc` to see if running bash with no dotfiles looks/behaves OK?

That seems to actually fix it. So that part is definitely on my Bash config for some reason somehow...

<br><br>

While on the topic and everything I had some random issues with certain characters simply crashing WezTerm if shown for too long (sometimes instant if there's a lot of them), the most prominent ones are binary files or alike, lets say I `cat` an mp3 file or similar, it'll then crash the terminal.

This isn't that big of a deal by itself because who would ever `cat` a file like that. The issue arrises since I use `fzf` to open files, which then cats the files on the right side so I can preview them, that means if `fzf` gets a file that's binary content or similar it'll usually crash. I don't know if there's any easy way to fix this, and it might need a separate issue on it's own.

**Comment by wez** [comment]
> I cat an mp3 file or similar, it'll then crash the terminal.

Please do file an issue for that: I'd like to see what wezterm logs to its stderr in that case!

**Comment by 0neGal** [comment]
In that case I'll go make that issue, but as a last comment, is there any way to disable WezTerm's custom cursors and just use the OS's cursors, they used to not be on by default and I can't find a setting to turn them off.

**Comment by wez** [comment]
Do you mean mouse cursors? wezterm should be loading cursors based on the XCURSOR theme settings/environment.  We've had a couple of edge cases with that in the past: would you mind opening a separate issue for that so we can work through troubleshooting it?

**Comment by 0neGal** [comment]
Will do!
