### ISSUE TITLE
Configure scroll bar color

### ISSUE THREAD

**Issue by jericdeleon** [wez/wezterm#1062]
I might have just missed something in the config docs, but:
Is there an easy way to configure the scroll bar's background and foreground color?

Also: thanks for this awesome project, planning to make it my daily driver soon! 👍

**Comment by wez** [comment]
The "thumb" color: https://wezfurlong.org/wezterm/config/appearance.html?highlight=scrollbar_thumb#defining-your-own-colors
The background is the window background color and isn't separately configurable (but it could be made an option if that is highly desirable).

**Comment by jericdeleon** [comment]
Ah, thanks for that!
I was wondering why my config wasn't working, but turns out I just missed the part where it says: `color_schemes` override `colors`.
