### ISSUE TITLE
Neovim + cursor blink not working

### ISSUE THREAD

**Issue by garyayo** [wez/wezterm#1073]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Cursor blink not working when using neovim.

![nvim-blink-2](https://user-images.githubusercontent.com/8942915/130469031-0d812d75-05e4-4ab1-ab61-08baf61f1610.gif)

### To Reproduce

1. Open WezTerm
2. Start neovim  -- `nvim` 

### Configuration

```
local wezterm = require 'wezterm';

return {
    font = wezterm.font("JetBrainsMono NF"),
    default_cursor_style = "BlinkingBlock",
    cursor_blink_rate = 800,
    color_scheme = "Dracula",
    enable_tab_bar = false,
    window_padding = {
        left = 15,
        right = 15,
        top = 0,
        bottom = 5,
    },
    keys = {
        {key="f", mods="SHIFT|CTRL", action="ToggleFullScreen"},
    }
}
```

### Expected Behavior

Cursor blinking within neovim.

### Logs

10:50:13.009 INFO wezterm_mux_server_impl::local > setting up /Users/garyaleixo/.local/share/wezterm/gui-sock-10178
10:50:13.177 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon Pro 555X OpenGL Engine 4.1 ATI-4.6.20 is_context_loss_possible=false wezterm version: 20210814-124438-54e29167

**Comment by garyayo** [comment]
Also impacting 20210821 nightly

**Comment by wez** [comment]
Most likely you (or your nvim defaults) have configured the equivalents to the vim `t_SI`, `t_SR` and `t_EI` settings that cause the editor to change the cursor style to a non-blinking cursor style based on the mode.

**Comment by bew** [comment]
In neovim this is configured with `guicursor`, check the help `:h guicursor` to change it

**Comment by garyayo** [comment]
Thanks for the quick response Wez, appreciate your work.

My `vim` and `nvim` share the same `vimrc` and I do have a chunk that does modify those equivalents but only when `tmux` is active (tmux was not active when submitting/recreating this bug):

```
" allows cursor change in tmux mode
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif
```

I removed the chunk from my `vimrc` but has not resolved my issue.

**Comment by garyayo** [comment]
Thank you @bew !!!! <3  `set guicursor=n:blinkon1` fixed this issue, thanks again!!

Question -- I use Kitty, Alacrity...etc that does not share this issue with WezTerm. Why does the guicursor need to be set with this terminal emulator? 

Thanks again and take care

**Comment by wez** [comment]
That's more a question for neovim: how is it deciding whether to use those features?  Often, programs use their own heuristics to decide this sort of thing, so it wouldn't surprise me if neovim has special cases for those other terminal emulators in its code.

**Comment by garyayo** [comment]
Appreciate you @wez, thanks again. I'm going to go ahead and close this issue.

Take care.
