### ISSUE TITLE
Chrome unable to locate wezterm window for screen sharing

### ISSUE THREAD

**Issue by rawhat** [wez/wezterm#1075]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In the prior version, 20210404-112810-b63a949d, I am able to select "Present Now" in Google Meet and select my WezTerm window.  With the new version listed above, the terminal window no longer appears.  In Firefox, I can share the new version in Google Meet, but Chrome does not seem to detect it.  I _am_ able to share it with Chrome through VcxSrv connecting to my WSL distro.  So it appears to be a Windows + Chrome + WezTerm combination.

### To Reproduce

Go to `meet.google.com` in Chrome, start a new instant meeting, click on "Present Now" at the bottom, and select "A window".  Note that the WezTerm window is not displayed.

### Configuration

I can definitely update this with my config if it's necessary, but I haven't set anything other than colors and keybinds.

### Expected Behavior

As noted above, in the previous release of WezTerm (which I am back to using), I was able to share the window.

### Anything else?

Happy to provide any other system settings as needed.  My Chrome version is 92.0.4515.159

**Comment by wez** [comment]
Try setting `prefer_egl = true`?

**Comment by rawhat** [comment]
That didn't seem to fix the issue, however while trying to capture a screen shot I did notice some odd behavior.  The initial window selection box doesn't show the terminal.  If I move the cursor around on the WezTerm window, it does show it, but only while the cursor is moving.  I have tried attaching a gif, hopefully it works.

![1piAsF8Mij](https://user-images.githubusercontent.com/2095509/130680575-d11bbfe9-3669-4bcf-9846-78fd989cf1d0.gif)

**Comment by wez** [comment]
This is weird.  I can reproduce it.

I don't think this is a wezterm issue per-se: there's not a Windows API that directly controls whether Chrome can share a window, and wezterm is just using either WGL (Windows OpenGL) or EGL mapped to Direct 2D depending on whether `prefer_egl` is enabled.  That option defaulted to `true` on Windows in the prior wezterm version but `false` in the nightly.  I'm running with egl enabled and see this, so it doesn't seem to be related to that.  I'm not aware of any other changes that might influence this.

I'd suggest looking for Chrome issues where apps don't show up and see if there's something to go on.

**Comment by rawhat** [comment]
Thanks for taking a look at this!  I will do some digging and report back.

**Comment by liketechnik** [comment]
I'm not sure if it's relevant, but for me this issue exists with Zoom on Linux too. Sharing other windows works totally fine. 

Interestingly I can share the Wezterm window in discord without any problems.

System info:
- wezterm version 20210814-124438-54e29167
- zoom Version: 5.8.3 (145) via flatpak
- discord version `Stable 103410 (c92cabc) Host 0.0.16 Linux 64-Bit (5.10.71)` via flatpak
- X11 on NixOs 21.05

**Comment by wez** [comment]
I wonder if this might have been fixed by https://github.com/wez/wezterm/commit/67b8c453cad275c7ea78fd505049e66016d17dba

**Comment by wez** [comment]
confirmed fixed!

**Comment by rawhat** [comment]
You're a legend!  Thank you :D
