### ISSUE TITLE
I-Beam cursor invisible when `force_reverse_video_cursor` is true

### ISSUE THREAD

**Issue by potamides** [wez/wezterm#1076]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20210824-085333-d38ba132

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The option `force_reverse_video_cursor` works fine when the cursor is a block. However as soon as the cursor is changed to a bar it is not visible anymore.

### To Reproduce

Simply use the provided minimal config table and start wezterm. No cursor should be visible.

### Configuration

```lua
-- minimal config
local config = {
  force_reverse_video_cursor = true,
  default_cursor_style = "SteadyBar"
}
```

### Expected Behavior

Even as a bar the cursor should be still be visible.

### Logs

```
21:45:58.705 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-1619080
21:45:58.773 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHDGraphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 21.2.1 is_context_loss_possible=false wezterm version: 20210824-085333-d38ba132
21:46:02.630 INFO wezterm_gui::frontend > Ding! (this is the bell)
21:46:02.900 INFO wezterm_gui::frontend > Ding! (this is the bell)
21:46:03.414 INFO wezterm_gui::frontend > Ding! (this is the bell)
```

**Comment by VKondakoff** [comment]
This does not seems to be fixed on my side (macOS 12.0.1, Neovim Nightly, Wezterm Nightly).
`force_reverse_video_cursor = true` is added to config.
Here is what I see, when there is a block cursor (everything is OK):

https://user-images.githubusercontent.com/230824/143225541-4645e4fa-0aa9-49a2-99a9-670684c0fb3b.mov

Here is what I see, when cursor is vertical bar:

https://user-images.githubusercontent.com/230824/143225648-b6a8857d-2d12-4684-aabc-8bd55206068d.mov

**Comment by wez** [comment]
@VKondakoff the I-beam is visible; it's just using the cursor color specified in your config.

What color would you expect it to have here?
Note that if we were to use the effective text color then the cursor would be invisible when it got to the end of the `C1'` text on the line in your example, where the background changes from blue to "black"  Is that OK?

**Comment by VKondakoff** [comment]
I was expecting I-beam cursor to have the foreground color of the current cell, so it is black on 'C' and '1', and green on the next ("'") cell. But this may be not optimal in the case of some Unicode symbol which may draw with foreground the entire cell (like this: '◼️').
So, maybe it is a good idea, to add an option to display some kind of shadow to the I-beam cursor?

Here is an example of such an option in iTerm2:

https://user-images.githubusercontent.com/230824/143311704-b6905b2b-30ea-4979-97e0-84ee99baf473.mov

What do you think?
