### ISSUE TITLE
Unable to load font "JetBrains Mono Nerd"

### ISSUE THREAD

**Issue by mzarnitsa** [wez/wezterm#1085]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Making config this
```
local wezterm = require 'wezterm';
return {
  font = wezterm.font("JetBrains Mono Nerd"),
}
```
and getting this message

Unable to load a font specified by your font=wezterm.font('JetBrains Mono
Nerd', {weight="Regular", stretch='Normal', italic=false}) configuration.
Fallback(s) are being used instead, and the terminal may not render as
intended. See https://wezfurlong.org/wezterm/config/fonts.html for more
information

### Configuration

wezterm.lua is this
```
local wezterm = require 'wezterm';
return {
  font = wezterm.font("JetBrains Mono Nerd"),
}
```

**Comment by wez** [comment]
Please run `wezterm ls-fonts --list-system | grep Nerd`; that should show all the fonts that have `Nerd` in their name on your system in a form that you can use in your config

**Comment by mzarnitsa** [comment]
That did work, thank you.

**Comment by wez** [comment]
Sounds like this is resolved!
