### ISSUE TITLE
Support reading dark mode preference from the OS

### ISSUE THREAD

**Issue by EpocSquadron** [wez/wezterm#1097]
Wouldn't it be cool if wezterm could detect whether the OS is set to dark or light mode, and provide that information to user configs? I imagine being able to query the dark mode status and set the terminal color theme based on it. Ideally there would even be an event fired, so when the OS switches (through something like the [Night Theme GNOME extension](https://nightthemeswitcher.romainvigier.fr/)), wezterm switches too. This wouldn't be a default thing since other applications in the terminal (notably text editors with their own themes) would also also need to change through a different mechanism. Although it might be neat if wezterm could spearhead a new OSC code for notifying terminal apps.

**Comment by wez** [comment]
Did you see: https://wezfurlong.org/wezterm/config/lua/window/get_appearance.html

**Comment by EpocSquadron** [comment]
:exploding_head: 

Yet another reason wezterm is my favorite terminal emulator. Thanks!
