### ISSUE TITLE
function keys don't work

### ISSUE THREAD

**Issue by pixelb** [wez/wezterm#11]
unhandled key: KeyboardInput { scancode: 68, state: Pressed, virtual_keycode: Some(F10), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }

**Comment by wez** [comment]
I think I've gotten this right, but the codes are rather inscrutable; is there a specific program that uses them that I can use to sanity  check this?

**Comment by pixelb** [comment]
Generally I use function keys with mc
