### ISSUE TITLE
[QUESTION] PRs?

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#110]
The project has a couple of PRs open, one recent and one old, was wondering if for some reason you don't have alerts for them on or if there's something wrong with them, you normally reply to everything so I'm thinking this must be an oversight.

**Comment by wez** [comment]
They're both from friends & colleagues and we sometimes chat about this stuff out of band from the PRs on github.  They are both in a related space--the terminal client library `termwiz` and its use in https://github.com/markbt/streampager.  I've been holding off on the older of the two while I consider the impact on https://github.com/wez/wezterm/issues/106, but am getting closer resolving it.

**Comment by ImportTaste** [comment]
Understood!
