### ISSUE TITLE
macOS: resize of single/first window lags

### ISSUE THREAD

**Issue by dev-zero** [wez/wezterm#1101]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20210902-091832-97831848

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When having a single wezterm window started via Launchpad, the resizing is noticeably "laggy".
The second window is snappy as it should be and it makes the first window resize also fast.
When closing the second window the lag for the resize of the first window is back.

https://user-images.githubusercontent.com/11307/131980444-6c9334fa-53dc-443d-9ba0-31172757cdfb.mp4

### To Reproduce

* install Wezterm Nightly with Homebrew
* start wezterm via Launchpad
* observe shown behavior

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  -- enable_wayland = true,
  font = wezterm.font("Hack Nerd Font"),
  font_size = 10,
  color_scheme = "OneHalfDark",
  keys = {
    {key="DownArrow", mods="SHIFT", action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
    {key="UpArrow", mods="SHIFT", action=wezterm.action{CloseCurrentTab={confirm=true}}},
    {key="LeftArrow", mods="SHIFT", action=wezterm.action{ActivateTabRelative=-1}},
    {key="RightArrow", mods="SHIFT", action=wezterm.action{ActivateTabRelative=1}},
    {key="LeftArrow", mods="SHIFT|CTRL", action=wezterm.action{MoveTabRelative=-1}},
    {key="RightArrow", mods="SHIFT|CTRL", action=wezterm.action{MoveTabRelative=1}},
  }
}
```

**Comment by dev-zero** [comment]
Starting wezterm from the macOS Terminal also gives a non-lagging window. It seems only to happen when started via Dock or Launchpad.

**Comment by wez** [comment]
I have no idea about this; wezterm doesn't directly know or care how it was launched, and the two processes are totally separate from each other.  This feels like it has to be a macOS thing somehow, but I don't know.
I use an M1 mac here and it is as smooth as butter either way :-/

**Comment by dev-zero** [comment]
Ok, I think this can be closed, I am unable to reproduce this.
