### ISSUE TITLE
tmux background colors are not applied to entire screen

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#1102]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20210903-162115-67e8bdc5

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

tmux background colors are not applied to the entire wezterm screen. I am using different colors for tmux's active (focussed) window & inactive (unfocussed) windows.

### To Reproduce

Steps: 
1) edit your tmux conf file to set some different background color for tmux active window, and inactive windows. 
2) open tmux by running ``>>tmux`` (it will create new session each time), 
3) detach the client
4) repeat steps 2-3 couple of times till you see the issue in the attached video.

```
tmux set -g window-style "bg=<some_hex_value>, fg=<some_hex_value>"
tmux set -g window-active-style "bg=<some_hex_value>, fg=<some_hex_value>"
```

### Configuration

Didn't try with no-config, so attaching the config here:

```lua
local wezterm = require 'wezterm';

-- A helper function for my fallback fonts
local font_with_fallback = function(name, params)
    local names = {name, "Noto Color Emoji", "Arial Unicode MS", "Apple Symbols"}
    return wezterm.font_with_fallback(names, params)
end

return {
    --font = font_with_fallback("OperatorMono Nerd Font"),
    font = font_with_fallback("OperatorMonoNerdR"),
    font_size = 22, -- 20 for 2880x1680, 22 for 3840x2160
    font_rules = {
        {
            italic = true,
            font = font_with_fallback("OperatorMonoNerdI"),
        },
        {
            italic = true,
            intensity = "Bold",
            font = font_with_fallback("OperatorMonoNerdMI"),
        },
        {
            intensity = "Bold",
            font = font_with_fallback("OperatorMonoNerdM"),
        },
    },
    term = "wezterm",
    --term = "xterm-256color",
    initial_cols = 260,
    initial_rows = 104,
    -- initial_cols = 80,
    -- initial_rows = 24,
    --mux_output_parser_buffer_size=1000000,
    color_scheme = "Calamity", --"Django",
    window_background_opacity = 0.96,
    window_close_confirmation = "NeverPrompt",
    allow_square_glyphs_to_overflow_width = "Always"
}

```

### Expected Behavior

tmux's background color should get applied to entire screen of wezterm pane/window tmux is opened in.

### Anything else?

Tmux version: Latest commit from GitHub (tmux next-3.3), though the issue has persisted from prior versions (don't know if it starts at a particular version).

https://user-images.githubusercontent.com/71736629/132080396-fa017c3a-219c-4106-9062-556c6740d684.mp4

**Comment by wez** [comment]
A session recording would help me resolve this faster: I don't have the bandwidth to recreate that tmux version/config combination!

**Comment by reportaman** [comment]
@wez Have sent you the typescript in matrix chat.

**Comment by wez** [comment]
This was similar but distinct from the other issue: the adjusted background color wasn't used to fill in blank rows when the `SU` (scroll up) sequence was used.

While looking at this, I noticed that the wezterm.terminfo had an incorrect setting for underline color, so I've updated that as well.  You should update your local copy!

**Comment by reportaman** [comment]
@wez This brought back the flickering that had stopped...

https://user-images.githubusercontent.com/71736629/132117558-88f01cd6-59e9-4644-985b-df5b9e5ac5a2.mov

**Comment by reportaman** [comment]
Sorry my bad... I forgot to change the terminfo in wezterm.lua to wezterm again (had changed it to xterm-256color instead for some other testing)
