### ISSUE TITLE
Copy mode cursor movement not visible on a terminal running Kakoune

### ISSUE THREAD

**Issue by unrelentingtech** [wez/wezterm#1113]
### What Operating System(s) are you seeing this problem on?

FreeBSD Wayland

### WezTerm version

20210906-110516-86f0bae1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In copy mode on a terminal running the [Kakoune](https://kakoune.org/) editor, the cursor visually stays at its original position, not reflecting the copy mode cursor movement. This does not happen with e.g. Neovim. And I've tested without my config too (`kak -n`).

https://user-images.githubusercontent.com/208340/132267288-72453b63-855c-45e7-9611-a8ddb6ddc180.mp4

### Configuration

even with empty config

**Comment by wez** [comment]
kak hides the cursor and does its own thing!  wezterm now forces the cursor to be visible as part of activating copy mode!
