### ISSUE TITLE
AnsiColor in wezterm.format for tab/status line is not respecting color_scheme

### ISSUE THREAD

**Issue by EpocSquadron** [wez/wezterm#1114]
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland

### WezTerm version

20210906-110516-86f0bae1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When setting AnsiColors in the tab/status line in my configuration, the current color_scheme is not applied to the ansi colors, instead showing the standard ansi colors (however that's defined -- black is #000000 for example).

### To Reproduce

Load my configuration (included below) on GNOME desktop environment. Use Night Theme extension or something else to change the theme between light and dark modes. Notice that the colors of the tab/status line do not change. Alternatively, just change color_scheme and observe that the tab/status line doesn't change colors.

### Configuration

```lua
local wezterm = require 'wezterm';

-- A helper function for my fallback fonts
function font_with_fallback(name, params)
  local names = {name, "SauceCodePro Nerd Font Mono", "Noto AnsiColor Emoji"}
  return wezterm.font_with_fallback(names, params)
end

function query_appearance_gnome()
  local success, stdout = wezterm.run_child_process(
    {"gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"}
  )
  -- lowercase and remove whitespace
  stdout = stdout:lower():gsub("%s+", "")
  local mapping = {
     highcontrast = "LightHighContrast",
     highcontrastinverse = "DarkHighContrast",
     adwaita = "Light",
     ["adwaita-dark"] = "Dark"
  }
  local appearance = mapping[stdout]
  if appearance then
     return appearance
  end
  if stdout:find("dark") then
     return "Dark"
  end
  return "Light"
end

function scheme_for_appearance(appearance)
  if appearance:find("Dark") then
    return "Ayu Mirage"
  else
    return "ayu_light"
  end
end

-- The filled in variant of the < symbol
local SOLID_LEFT_ARROW = utf8.char(0xe0b2)

-- The filled in variant of the > symbol
local SOLID_RIGHT_ARROW = utf8.char(0xe0b0)

local NEW_TAB_ICON = utf8.char(0xf055)

wezterm.on("update-right-status", function(window, pane)
  local cwd_uri = pane:get_current_working_dir()
  if cwd_uri then
    window:set_right_status(wezterm.format({
      {Background={AnsiColor="Black"}},
      {Foreground={AnsiColor="Blue"}},
      {Text="  "..cwd_uri:match("^.+/(.+)$").." "},
    }));
  end
  local overrides = window:get_config_overrides() or {}
  local appearance = query_appearance_gnome()
  local scheme = scheme_for_appearance(appearance)
  if overrides.color_scheme ~= scheme then
    overrides.color_scheme = scheme
    window:set_config_overrides(overrides)
  end
end)

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  -- ensure that the titles fit in the available space,
  -- and that we have room for the edges
  local title = wezterm.truncate_left(tab.active_pane.title, max_width-4)

  if tab.is_active then
    return {
      {Background={AnsiColor="Blue"}},
      {Foreground={AnsiColor="Black"}},
      {Text=SOLID_RIGHT_ARROW.." "..title.." "},
      {Background={AnsiColor="Black"}},
      {Foreground={AnsiColor="Blue"}},
      {Text=SOLID_RIGHT_ARROW},
    }
  elseif hover then
    return {
      {Background={AnsiColor="Aqua"}},
      {Foreground={AnsiColor="Black"}},
      {Text=SOLID_RIGHT_ARROW.." "..title.." "},
      {Background={AnsiColor="Black"}},
      {Foreground={AnsiColor="Aqua"}},
      {Text=SOLID_RIGHT_ARROW},
    }
  end
  return {
    {Background={AnsiColor="Black"}},
    {Foreground={AnsiColor="White"}},
    {Text="  "..title.."  "},
  }
end)


return {

  tab_bar_style = {
    new_tab = wezterm.format({
      {Background={AnsiColor="Black"}},
      {Foreground={AnsiColor="White"}},
      {Text="  "..NEW_TAB_ICON.."  "},
    }),
    new_tab_hover = wezterm.format({
      {Background={AnsiColor="Aqua"}},
      {Foreground={AnsiColor="Black"}},
      {Text=SOLID_RIGHT_ARROW.." "..NEW_TAB_ICON.." "},
      {Background={AnsiColor="Black"}},
      {Foreground={AnsiColor="Aqua"}},
      {Text=SOLID_RIGHT_ARROW},
    }),
  },

  -- Font with programming ligatures
  font = font_with_fallback("Rec Mono Linear"),
  font_rules= {
    {
      italic = true,
      font = font_with_fallback("Rec Mono Semicasual", {italic=true}),
    },

    {
      italic = true,
      intensity = "Bold",
      font = font_with_fallback("Rec Mono Semicasual", {italic=true, bold=true}),
    },

    -- This is automatically derived from the main font, so no need to be
    -- explicit about it.
    -- {
    --   intensity = "Bold",
    --   font = font_with_fallback("Rec Mono Linear", {bold=true}),
    -- },

    {
      intensity = "Half",
      font = font_with_fallback("Rec Mono Duotone"),
    },
  },
  font_size = 11.0,

  -- Use the dedicated terminfo so we get all the newest goodies,
  -- like fancy underline escapes
  term = "wezterm",

  -- Fancy terminal escapes so we can map Ctrl-J unambiguously
  -- in programs like kakoune
  enable_csi_u_key_encoding = true,

}
```

### Expected Behavior

I expect that AnsiColor will return a color that corresponds to the ansi colors defined in the color_scheme. If that is not the intended behavior, then something like SchemeColor should exist to do what I am expecting.

**Comment by wez** [comment]
I trimmed down your config to this:

```lua
local wezterm = require 'wezterm';

wezterm.on("update-right-status", function(window, pane)
  local cwd_uri = pane:get_current_working_dir()
  if cwd_uri then
    window:set_right_status(wezterm.format({
      {Background={AnsiColor="Olive"}},
      {Foreground={AnsiColor="Blue"}},
      {Text=" "..cwd_uri:match("^.+/(.+)$").." "},
    }));
  end

  local overrides = window:get_config_overrides() or {}
  local scheme = "matrix"
  if overrides.color_scheme ~= scheme then
    overrides.color_scheme = scheme
    window:set_config_overrides(overrides)
  end
end)

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  local title = wezterm.truncate_left(tab.active_pane.title, max_width-4)
  return {
    {Background={AnsiColor="Black"}},
    {Foreground={AnsiColor="White"}},
    {Text="  "..title.."  "},
  }
end)

return {
}
```

and the tab bar looks like this:

![Screenshot from 2021-09-06 20-12-40](https://user-images.githubusercontent.com/117777/132278532-02b37656-ecbb-4afa-b0df-5ade5918a277.png)

if I change the `local scheme` line to `local scheme = "Github"`, then it looks like this:

![Screenshot from 2021-09-06 20-13-42](https://user-images.githubusercontent.com/117777/132278607-bad5f6f5-044c-4432-a49e-418ca2a6910b.png)

so it looks like this is working to me; both the tab background and the cwd background changes colors to match the selected color scheme.

What are we missing from the repro steps?

**Comment by EpocSquadron** [comment]
I played around with this and I'm still a bti confused about how the tab bar is supposed to be styled, so bear with me:

* The `colors.tab_bar` config item - This seems to be the only way to define the background of the tab bar (meaning it controls the space between the tab titles on the left and the right status on the right). However, it only accepts a string value for what color that background should be, so you can't access AnsiColor to make that space dynamic.
* The `tab_bar_style` config item - This is deprecated, but seems to be the only other way besides `colors.tab_bar` to specify the `new_tab` and `new_tab_hover` styles. This time it does accept wezterm.format, and therefore can use AnsiColor. 
* The `format-tab-title` event - This is the preferred way to set the styling of the tab bar items, but as pointed out above, leaves out the new_tab and the tab bar's overall background. It also accepts wezterm.format and can use AnsiColor.
* The `update-right-status` event - This is the only way to set the right status. It also accepts wezterm.format() and therefore AnsiColor.

So after figuring out all of the above I think what my problem comes down to is two-fold:

1. There is no way to set the background of the tab bar as a whole with an AnsiColor, and therefore it will be unable to respond to changes in color scheme. This is visible in the screenshots in your response as well. Try setting scheme to AlienBlood, which has no true blacks in it, and you will see the tab bar remains solid black.
2. I'm confused as to how light themes change the background of everything to white from black. I would expect that the definition of Black and White ansi colors are swapped, but that does not appear to be the case. Instead in the definition of a color scheme there is a specific field for what the foreground and background colors are. However, programs like `bat` set to use ansi colors for their output still have background that is white, even though they are not changing their ansi codes. Are there separate ansi codes for "foreground" and "background" that programs like that are using? If so, I'd love to expose that to wezterm.format so that i can simply tell my tab bar options to "use the scheme's background". Maybe I have to inspect the config each time one of the two events is called?

**Comment by wez** [comment]
One way to interpret this request is to allow setting color theme settings in terms of palette indices, but that's problematic because those settings are what define the palette, so that introduces the possibility of cycles in the config.

As an alternative option, I think you may want to look at using https://wezfurlong.org/wezterm/config/lua/wezterm/get_builtin_color_schemes.html to resolve a color scheme definition and then use that to populate the config; something like this:

```lua
local wezterm = require 'wezterm';

local colors = wezterm.get_builtin_color_schemes()["Github"]
colors.tab_bar = {
  background = colors.background
}

return {
  use_fancy_tab_bar = false,
  colors = colors,
}
```
