### ISSUE TITLE
Using insert mode in Vim while inside Wezterm does not change the cursor shape

### ISSUE THREAD

**Issue by supercomputer1** [wez/wezterm#1116]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes

### Describe the bug

When entering insert mode while inside Vim, I'm expecting the cursor to be shaped as a underline. However, the cursor shape will not change at all, thus staying as a solid block. 

It would be helpful if there was some sort of visual indication on the cursor when entering insert mode. 

### To Reproduce

1. Open a file in Vim 
2. Press i to enter insert mode
3. The Vim cursor shape will still be a solid block

### Configuration

No config. 

### Expected Behavior

When entering insert mode I expect the cursor to be shaped as a underline instead of a solid block.

### Logs

No logs.

### Anything else?

If this can be fixed by tweaking my vimrc I would be really grateful if someone could point me in the right direction. I've tried changing the cursor shapes "manually" by entering this into my vimrc: 

let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

But this does not work as expected.

**Comment by wez** [comment]
Which vim are you running? Win32 native, WSL, msys, cygwin?

The vimrc config you mentioned works on unix so this may actually be an issue with the windows PTY layer.

I don't have time to dig into this right at this moment, but I'd suggest starting with https://github.com/microsoft/terminal/issues/8560 which is the first issue that sounds similar

**Comment by fransfreij** [comment]
Win32 native (version 8.2). 

The suggested fix does work (in the MT link), or at least it changes the cursor shape. However it does leave behind a "ghost" j after pressing jk to escape insert mode. I'll see if I can find a fix for that..
