### ISSUE TITLE
bypass_mouse_reporting_modifiers not working on Wayland

### ISSUE THREAD

**Issue by unrelentingtech** [wez/wezterm#1122]
~~**Is your feature request related to a problem? Please describe.**~~

~~Sometimes I'd like to use the terminal's mouse selection when a mouse-handling app like an editor is handling mouse input.
In most terminals this is done with Shift+drag because holding Shift makes the terminal ignore the running program's mouse handling.~~

~~**Describe the solution you'd like**~~

~~`StartWindowDrag`/`ExtendSelectionToMouseCursor` need a flag for this I guess?~~

**Comment by unrelentingtech** [comment]
Ah, there is `bypass_mouse_reporting_modifiers`, but it doesn't seem to work for me at all…

**Comment by bew** [comment]
Shift+mouse action should already work

**Comment by unrelentingtech** [comment]
Yeah, it just wasn't working on Wayland, I'll push a fix in a minute

**Comment by sandangel** [comment]
hi, I have the same issue today on wayland fedora. 
```lua
  bypass_mouse_reporting_modifiers = 'ALT',
  mouse_bindings = {
    {
      event = { Up = { streak = 1, button = 'Left' } },
      mods = 'CTRL|SHIFT',
      action = 'OpenLinkAtMouseCursor',
    },
    {
      event = { Down = { streak = 1, button = 'Left' } },
      mods = 'CTRL|SHIFT',
      action = 'Nop',
    },
  },
```
But ctrl+shift+click just doesn't work. @wez could you help check this issue again?

**Comment by wez** [comment]
@sandangel please file a new issue with the details about your setup and what's happening!
