### ISSUE TITLE
Repeat presses for leader keybindings

### ISSUE THREAD

**Issue by unrelentingtech** [wez/wezterm#1129]
**Is your feature request related to a problem? Please describe.**

In tmux, holding/mashing a key pressed after the prefix ("leader" like thing) works, so I can do e.g. `<Ctrl-q> + + + + + + +` and my pane resize command would work all 7 times. 

Currently in WezTerm, I have to press the leader before each command. I've replicated my tmux hotkeys in WezTerm, and this is the one difference I still notice.

**Describe the solution you'd like**

Implement this kind of "hold" behavior for the leader key. Possibly as an option, though I don't see any harm in it always working like that.

**Comment by bew** [comment]
Additional info on tmux:
The keybindings have a `allow-on-repeat` property that is enabled with `-r` (e.g: `bind -r KEY ACTION`).
After the first key binding that has `allow-on-repeat`, tmux has starts a timer (configured with `repeat-time` option), during which you can hold/mash other `allow-on-repeat`-enabled keybindings.
Any key that is not recognized by tmux cancels the 'repeat' mode, and pass the key to the active program.

**Comment by wez** [comment]
It's not quite the same thing, but https://wezfurlong.org/wezterm/config/key-tables.html allows activating a table that will stick until either popped or expired.  I'm curious to hear if this is close enough to what you're looking for?

**Comment by jason0x43** [comment]
The timeout is helpful, and the new `until_unknown` option is also very good for dropping out of a temporary key table. A combination of `until_unknown` and a resettable timer would be ideal. You would stay in the key table until you either hit an unknown key or just didn't use something in the key table for a while. That would be great for, say, doing a bunch of pane manipulation operations in a row, and then wanting to get back to typing. It's only saving you a keystroke, but it's a flow that has always seemed to work well (for me, at least) in tmux.

**Comment by wez** [comment]
I pushed a commit that resets the timeout each time a key press matches the activation. I think it's probably fine to always do that and that it doesn't require a separate config option to enable it.
Let me know what you think!

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jason0x43** [comment]
I tried this out and it's working great! When I enter the new key table, it sticks around as long as I'm pressing keys within the timeout, and it automatically gets popped after the timeout when I stop pressing keys.

**Comment by wez** [comment]
Great, let's call this done then!
