### ISSUE TITLE
use_ime=true on macOS prevents key repeat for some keys

### ISSUE THREAD

**Issue by shaozi** [wez/wezterm#1131]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When in vi, pressing and holding key `j`, `k`, or `h` does not repeatedly move the cursor. `l` somehow works.

### Configuration

no config

**Comment by wez** [comment]
Please try the nightly build.
Please also confirm whether you have any configuration; in particular whether you have `use_ime = true` configured.

**Comment by shaozi** [comment]
How to get nightly?

I do have `use_ime = true` in my config. Remove that the problem disappears.

**Comment by bew** [comment]
> How to get nightly?

You can get the nightly at https://wezfurlong.org/wezterm/install/macos.html

**Comment by wez** [comment]
> I do have `use_ime = true` in my config. Remove that the problem disappears.

Hrmm, your original report claims to have no configuration, which on top of being frustrating for both of us, makes it take longer to help you reach a resolution. :-(

The behavior you described is a known side effect of using the IME on macOS.  It's documented here:
https://wezfurlong.org/wezterm/config/keys.html#macos-and-the-input-method-editor-ime

**Comment by wez** [comment]
I found a reasonable workaround for this; it should be available to try out in the latest nightly download.
