### ISSUE TITLE
Please add `Provides: x-terminal-emulator` field to the .deb package control file.

### ISSUE THREAD

**Issue by jubalfh** [wez/wezterm#1139]
**Is your feature request related to a problem? Please describe.**

so this is absolutely a minor thing, and not even a problem _per se_.

basically: `x-terminal-emulator` is a virtual package provided by most terminal emulators in deb-based distributions (see the [list](https://packages.debian.org/stable/virtual/x-terminal-emulator) here), and the packaging mechanism tries to keep at least one of them installed when you're running a graphical environment.

having `wezterm` provide it means that the distro stops trying to install fallback packages when one wants only wezterm to be installed.

**Describe the solution you'd like**

add `x-terminal-emulator` to the `Provides:` field in debian package control file.

**Comment by wez** [comment]
Thanks for the suggestion; this should show up in the nightly .debs in the next 30 minutes
