### ISSUE TITLE
ssh into a server where fish shell as default, the tab title doesn't remain the user@server, but the actual command

### ISSUE THREAD

**Issue by beci** [wez/wezterm#1147]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I experienced the same with other versions.

### To Reproduce

1. need a target server to ssh into (localhost is also fine for test, if sshd running)
2. need a target user. for side by side comparison it's ok to create a temporary user 
3. set `fish` as default shell the target user on the server: `chsh -s /usr/bin/fish`
4. ssh into the target server with the target user

if the target user's shell is `bash`, the tab title remain `user@server`
if the target user's shell is `fish`, the tab title became `fish /home/...`

### Configuration

no config

### Expected Behavior

The tab title should remain `user@server` even if the target shell is `fish` .

### Anything else?

I'm happy to work on fix it, if you give me some directions.

**Comment by wez** [comment]
What's happening here is:

* On your local host you've got some shell integration that uses escape sequences to change the terminal window and/or tab title when you ssh to a remote host
* On the remote host, `bash` is not configured with any title changing escape sequences, but `fish` is configured to emit escape sequences that change the terminal window and/or tab title to something else, and that overrides the title that was set by your local shell.

`wezterm` (and other terminals) don't really know what programs are running, especially in a remote ssh session, so it's not `wezterm` deciding to change the titles for you :-)

What you'll need to do is take a look at your remote `fish` config and see if there is a way to tell fish not to change the title in this situation.  I don't use fish so I don't know what to suggest other than taking a look at the fish docs to see what options it provides for this!

**Comment by beci** [comment]
Thanks @wez for this details, it seems I misunderstand it first.
Btw `wezterm` is awesome!
