### ISSUE TITLE
Can't paste/enter emoji or other combining character sequences in zsh's line editor

### ISSUE THREAD

**Issue by Sduby22** [wez/wezterm#1157]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20210919-182757-8f0ab02b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Can't correctly render unicode characters when input with ime or `ls` the files with unicode names.
But I can `cat` a file or use `vi` editor with no problems

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  font = wezterm.font_with_fallback({
    "Monaco for Powerline",
    "Sarasa Mono SC Nerd",
  }),
  font_size = 18,
  line_height=1.2,
  harfbuzz_features = {"liga=0"},

  use_ime = true,
}
```

### Logs

15:27:13.105 WARNING wezterm_term::terminalstate::performer > Unhandled OSC  12 7
15:29:05.443 WARNING wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
15:29:05.445 WARNING mux::localpane > unknown DeviceControlMode::Enter EnterDeviceControlMode(params: [], intermediates: [], byte: 'z' 0x7a, ignored_extra_intermediates=false)
15:29:05.446 WARNING mux::localpane > unhandled DeviceControlMode::Data 7a z
15:29:05.446 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: "0%m"
15:29:12.084 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
15:29:12.084 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
15:29:31.584 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:29:31.617 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:29:31.650 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:29:31.683 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:29:31.717 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:29:31.750 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:29:31.784 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:29:31.817 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:29:31.850 INFO wezterm_gui::frontend > Ding! (this is the bell)
15:30:02.016 WARNING wezterm_term::terminalstate::performer > ESC: unhandled Unspecified { intermediate: None, control: 107 }
15:30:02.016 WARNING wezterm_term::terminalstate::performer > ESC: unhandled Unspecified { intermediate: None, control: 107 }
>

### Anything else?

<img width="701" alt="iShot2021-09-21 15 29 02" src="https://user-images.githubusercontent.com/29040696/134129797-54aa148f-7f74-4bf1-b65f-3612fa6445e7.png">
<img width="219" alt="iShot2021-09-21 15 29 10" src="https://user-images.githubusercontent.com/29040696/134129832-baf0d045-11ed-4416-8d89-d144e0077d80.png">
<img width="704" alt="iShot2021-09-21 15 29 59" src="https://user-images.githubusercontent.com/29040696/134129845-90231a94-132c-446e-9bb4-d4d924ef7904.png">
>

**Comment by wez** [comment]
This is a zsh configuration issue, see the explanation and resolution here:
https://unix.stackexchange.com/questions/598440/zsh-indic-fonts-support-rendering-issue-which-is-working-fine-on-bash

**Comment by wez** [comment]
I've added https://wezfurlong.org/wezterm/faq.html#pasting-or-entering-unicode-in-zsh-looks-broken to the FAQ

**Comment by Sduby22** [comment]
Thank you! Solved perfectly!!!
