### ISSUE TITLE
iTerm2 protocol: TIFF support

### ISSUE THREAD

**Issue by hpjansson** [wez/wezterm#1160]
Hi!

It'd be nice to have TIFF image support in the iTerm2 image extension. The rationale is the following:

- Very easy for applications to generate. You can write baseline TIFF headers and the image data in a few dozens of lines of C code without the need for an external library.
- Ability to send images uncompressed. This can save CPU resources and should run faster when the CPU is the bottleneck, such as on loopback or fast networks. PNG compression is pretty slow.
- TIFF already works in iTerm2 on MacOS.

I chose TIFF for the Chafa iTerm2 implementation due to its simplicity: https://github.com/hpjansson/chafa/blob/master/chafa/internal/chafa-iterm2-canvas.c

Of course, decoding is harder to support, but I noticed WezTerm can already do TIFF wallpapers, so maybe the groundwork is already laid...

**Comment by wez** [comment]
I think this already works?  Have you tried to send a tiff using the iterm2 protocol?

**Comment by wez** [comment]
FWIW, wezterm uses https://github.com/image-rs/image for parsing images, so any issues with tiff loading will likely need to be filed with them.  I'm happy to have an issue here to mirror the upstream issue(s) you surface.

**Comment by hpjansson** [comment]
Found the issue:

* image-rs does not extrapolate from a single-element BitsPerSample tag to multiple samples. The TIFF standard says to always provide the entire array (i.e. 4-element BitsPerSample for RGBA), so this is just a strict (but correct) interpretation of the standard.
* NSImage (iTerm2/MacOS) appears to extrapolate the remaining bit depths. However, it does not accept BitsPerSample of type BYTE (I think it should: the TIFF specification says _"TIFF readers should accept BYTE, SHORT, or LONG values for any unsigned integer field"_), which makes it impossible to pack the values into the 32-bit data field of the BitsPerSample tag.

What does work in both cases is to specify BitsPerSample as a 4-element array of SHORT, store it as an external field and point to it from the tag's data field.

Problem solved; apologies for the noise.
