### ISSUE TITLE
Can't render "IDEOGRAPHIC SPACE" correctly

### ISSUE THREAD

**Issue by topazape** [wez/wezterm#1161]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20210921-094309-89e4d7b7

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

"IDEOGRAPHIC SPACE" (U+3000) used as "SPACE" (U+0020) in Japanese, is not rendered in wezterm.
For example, `echo 'X　X'`, "IDEOGRAPHIC SPACE" sandwiched between "X" will be displayed as "XX", but Terminal.app will correctly display it as `X　X`.
![wezterm_terminal app](https://user-images.githubusercontent.com/38512143/134269400-cee226f7-387d-468b-8ae9-d16b3f1007dd.png)

### Configuration

no config

**Comment by wez** [comment]
Thanks for reporting this!
This is now resolved; it'll show up in the nightly downloads within ~30 minutes from now!
