### ISSUE TITLE
imgcat doesn't work inside neovim terminal

### ISSUE THREAD

**Issue by argapost** [wez/wezterm#1163]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Hello!

Imgcat works perfectly when I am in wezterm alone, but if I open neovim and open a terminal inside neovim using :terminal then imgcat doesn't display my image. Is it possible for imgcat to work inside nvim?

Thank you in advance for your help! 

### Configuration

no config

**Comment by wez** [comment]
`wezterm imgcat` uses the iterm2 image protocol that is documented here:
https://iterm2.com/documentation-images.html

from skimming https://neovim.io/doc/user/nvim_terminal_emulator.html it sounds like nvim's embedded terminal doesn't support this, as it is based on libvterm which itself doesn't support this protocol.

**Comment by argapost** [comment]
Ok, I see thanks anyway.
