### ISSUE TITLE
Gohu OTB font not displaying correctly

### ISSUE THREAD

**Issue by ConorHK** [wez/wezterm#1165]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20210919-182757-8f0ab02b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The bitmap font Gohu displays without any spacing between any of the characte
![2021-09-23-170108_949x479_scrot](https://user-images.githubusercontent.com/43848548/134543016-648e9ee4-54f8-4e8e-96ab-de4e8bd30516.png)
rs

### Configuration

```
local wezterm = require 'wezterm';
return {
  font = wezterm.font("Gohu GohuFont"),
  color_scheme = "Batman",
  font_size= 10,
}
```

### Logs

 ──── ─ ./wezterm                                                          ~/dl/wezterm_nightly/wezterm/usr/bin
 2021-09-23T16:01:00.392Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-6721
 2021-09-23T16:01:00.477Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) HD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 21.2.1 is_context_loss_possible=false wezterm version: 20210919-182757-8f0ab02b
^C

### Anything else?

`wezterm ls-fonts`
```
Primary font:
wezterm.font_with_fallback({
  -- /usr/share/fonts/gohufont-otb/gohufont.otb, FontConfig
  {family="Gohu GohuFont", weight="Medium"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- /usr/share/fonts/gohufont-otb/gohufont.otb, FontConfig
  -- Will synthesize italics
  -- Will synthesize dim
  {family="Gohu GohuFont", weight="Medium"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- /usr/share/fonts/gohufont-otb/gohufont.otb, FontConfig
  -- Will synthesize dim
  {family="Gohu GohuFont", weight="Medium"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /usr/share/fonts/gohufont-otb/gohufont-bold.otb, FontConfig
  {family="Gohu GohuFont", weight="Bold"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- /usr/share/fonts/gohufont-otb/gohufont-bold.otb, FontConfig
  -- Will synthesize italics
  {family="Gohu GohuFont", weight="Bold"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- /usr/share/fonts/gohufont-otb/gohufont.otb, FontConfig
  -- Will synthesize italics
  {family="Gohu GohuFont", weight="Medium"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

```

**Comment by wez** [comment]
This appears to be an issue with retrieving the metrics from the gohu OTB font specifically.  If you use the BDF version it renders fine.

**Comment by wez** [comment]
I've pushed a change that seems to make this work.  That'll be available in the pre-built nightly builds within 30 minutes, or you can pull and build from source if you prefer.
Please let me know how this works for you!

**Comment by ConorHK** [comment]
Will do, thank you!

**Comment by ConorHK** [comment]
Works, thank you! Just a note - the AUR nightly package seems to be way behind. I had to build from source to get the current version.

**Comment by wez** [comment]
Could you try the nightly AUR again? It needed to be updated for the EOL of ubuntu 16 and the switch to pulling from the ubuntu 18 appimage.

**Comment by ConorHK** [comment]
The current version I pulled just now from the AUR was `wezterm-nightly-bin-20210919.182757.8f0ab02b-1` which did not have the fix.

**Comment by wez** [comment]
AFAICS, wezterm-nightly-bin is pointing to a newer version than that.  I can't easily test directly on arch... @gaborbernat, could you verify/troubleshoot the nightly AUR when you have some time?  Thanks!

**Comment by oblitum** [comment]
I've hit this issue while searching issue tracker to learn why `font_size` for a bitmap font isn't taking any effect? Is it not supported?

**Comment by wez** [comment]
@oblitum: 

bitmap fonts only have certain predefined sizes (known as bitmap strikes) that are measured in pixels.

The `ftdump` utility (part of freetype) can show you the possible bitmap strikes:

```
; ftdump /home/wez/Downloads/gohufont-2.1-otb/gohufont.otb
There is 1 face in this file.

----- Face number: 0 -----

font name entries
   family:              Gohu GohuFont
   style:               Regular
   postscript:          UNAVAILABLE
   created:             1904-01-01
   modified:            1904-01-01
   revision:            1.00
   glyph count:         1694

font type entries
   FreeType driver:     truetype
   sfnt wrapped:        yes
   type:                fixed size
   direction:           horizontal
   fixed width:         no
   glyph names:         no

fixed size
     0: height 11, width 3
        size 11.000, x_ppem 11.000, y_ppem 11.000
     1: height 14, width 4
        size 14.000, x_ppem 14.000, y_ppem 14.000

charmaps (1)
   0: format  4, platform 3, encoding  1   language 0 (active)
```

The above shows that the font has an `11 pixel` and a `14 pixel` strike.

The `font_size` setting in wezterm is measured in points.  `72 points == 1 inch`, and the number of pixels in 1 inch depends on the DPI of your monitor.

wezterm will select the bitmap strike closest to the requested `font_size` on your display.

You can use a calculator like http://pttopx.com/ to punch in your DPI and the pixel sizes to figure out the point size you need to specify; for the font above, if you have a 96 dpi screen and want to select the `11 pixel` strike you need to set `font_size = 14.6`.  For the `14 pixel` strike you would set `font_size = 18.6`.

**Comment by gaborbernat** [comment]
I only maintain wezterm-git, wezterm-nightly-bin I have no control over 🤔

**Comment by oblitum** [comment]
@wez the Terminus installation on Arch has a bunch of otb files for  each strike size:

```
❯ fc-list | rg -i 'Terminus'
/usr/share/fonts/misc/ter-u22n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u20n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u22b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u20b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u24n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u32n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u28n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u24b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u18n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u12n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u16n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u14n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-x12b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x22b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x32b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x18b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x20b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x28b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x16b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x14n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x14b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x24n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x24b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x16n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x18n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x20n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x28n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x12n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x22n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-u12b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-x32n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-u16b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u14b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u18b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u32b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u28b.otb: Terminus:style=Bold
```

Problem is that on wezterm, no matter what `font_size` I set for `Terminus`, I always get the smallest size one. I don't have similar problem with Alacritty.
