### ISSUE TITLE
RFC: Color Schemes and Profiles

### ISSUE THREAD

**Issue by wez** [wez/wezterm#117]
Many terminal emulators offer a profile feature wherein you can reference a set of configuration options that should be applied for a given task.

I believe that most users use this in a relatively basic way; for example to make logging into a production host distinctively different in appearance as a reminder to be extra careful.

The master branch / nightly build of wezterm just introduced some configuration that allows the user to define color schemes, or to reference many pre-made color schemes.   The commit message for https://github.com/wez/wezterm/commit/1af9ded3ce71eecade534dbc2124d7dc9e1c58c8 has some configuration details inline.

At the moment this configuration is global in the same way that the `[colors]` section of the config applies by default to all tabs.

The purpose of this issue is to solicit some feedback on what shape "profiles" should take in wezterm by presenting some options.  I'm focusing on color scheme here as that is the easiest existing area of wezterm that could be configured in this way, but I can see that it might be desirable to specify alternate font or hyperlink rules options for different purposes, so moving towards that idea sounds reasonable.

## Profile vs. Color Scheme

I view a profile as being a subset of the allowed configuration settings that are grouped together and given a name.  When a profile is active, those settings take precedence over the global settings.

I think fonts and hyperlink rules are good candidates for being allowed as profile configuration options.  I'm not sure what others are practically useful here though.

A color scheme is a color palette definition.  A profile might specify a default color scheme.

## Explicit Command line option

Spawn a new process with the `Batman` scheme as the default color scheme.  When run this
way, the `color_scheme` in the config file is ignored.  This allows the simplest programmatic control over the appearance of the terminal.

```bash
$ wezterm start --color-scheme "Batman"
```

```bash
# activate the serious business profile for this invocation
$ wezterm start --profile "srs bzns"
```

## A domain level configuration option

Specify the color scheme in the config file when using ssh domains; for example, use a scheme with a red background when connecting to production:

```toml
[[ssh_domains]]
name = "prod"
remote_address = "my.production.system.com"
username = "wez"
color_scheme = "Red Alert"
```

```bash
$ wezterm connect prod
```

There could also be a `profile` option here.

The same option could also be added to TLS or other domains.

## Rules based

Allow selecting a color scheme based on properties of a given tab.
For instance, the working directory may be a file:// URI that includes the hostname and we could match on that.  Or more obviously, match on the tab title.  There may be additional properties from the semantic/shell integration specs that are valuable to match on here (see https://github.com/wez/wezterm/issues/115)

Switching between a dark and light theme based on the time of the day is a cute sounding feature that could be implemented in this way.

Configuration might look something like this, where the relative order of the blocks matters: the first one to match will win:

```toml
[[color_scheme_rules]]
hostname = "my.production.host"
color_scheme = "Red Alert"

[[color_scheme_rules]]
# regex against the tab title
title = "^wez@media-server"
color_scheme = "Relaxed"
```

## Manual selection via keyboard shortcuts

We could add a `SetDefaultColorScheme` action to override the color scheme with a named scheme.  There could also be actions to reset it to use the config file value and also a some scoped to the current tab or perhaps tab domain.

Likewise, there could be equivalent actions to change the profile on the fly.

## Escape sequences

It's worth noting that we have allowed setting the color scheme on a per-tab basic via escape sequences for a while.   https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/dynamic-colors has shell scripts that will do that in most versions of wezterm.

Should there also be escapes for activating a named color scheme and/or profile?

**Comment by frioux** [comment]
Maybe I'm a weirdo, but I'd rather this be more general, possibly using #225.  Here are my thoughts re the above:

 * CLI Arg: now I have to restart my term to change scheme.  Sad.
 * Domain: cute, but I switch color schemes based on environment (being outside for example.)
 * Rules based: seems like it'd be better to implement by the users based on lua scripts to me
 * Manual by keyboard: works for me, seems like the most basic but generally useful start (maybe in addition to cli arg?)
 * Escape sequences: honestly I feel like if this were slightly extended to your idea of profiles it might be an alternate way to do scripting.  Good: it can be initiated over ssh or whatever, Bad: what if I wanted to put the complexity in my term rather than shell scripts running on random hosts??
