### ISSUE TITLE
Padding between tab bar

### ISSUE THREAD

**Issue by aw1cks** [wez/wezterm#1176]
When using padding, the tab bar does not respect padding configuration

For example here is a window using padding:

![image](https://user-images.githubusercontent.com/12629429/134810350-bcea854a-70a2-4cfb-82ee-5cf6a76e1f8c.png)

---
Now when I open a new tab:

![image](https://user-images.githubusercontent.com/12629429/134810366-886b41db-8e24-4dd9-8649-ef755c5089ac.png)

---

IMO it would look really nice with some padding between the tab bar and the top of the prompt, either using the existing padding value or with another configurable value

**Comment by wez** [comment]
It may not be exactly what you're looking for, but the nightly builds put the tab bar outside of the padding:

![image](https://user-images.githubusercontent.com/117777/136322024-f28b3b13-b227-4fa1-b34c-7fa59c2c4ce9.png)

**Comment by aw1cks** [comment]
Yay! That already looks a lot better. Thanks!
