### ISSUE TITLE
starship prompt reports running job when using WezTerm

### ISSUE THREAD

**Issue by jameschensmith** [wez/wezterm#1178]
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland

### WezTerm version

wezterm 20210925-221901-9be8f92d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using the Debian 11 nightly release of WezTerm, I'm noticing the `jobs` module in starship is shown despite have no jobs. Oddly, when using another terminal (in my case, I used foot, as it was available to me), the `jobs` module is correctly hidden. I'm not sure if this is an issue with WezTerm or with starship.

### To Reproduce

1. Download current Debian 11 nightly release.
2. Download/Configure starship prompt.
3. Open WezTerm terminal.

### Configuration

no config

### Expected Behavior

The `jobs` module in starship is shown/hidden correctly when using WezTerm.

### Logs

```
19:01:38.749 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-4053
19:01:38.811 INFO wezterm_gui::termwindow > OpenGL initialized! NV168 4.3 (Compatibility Profile) Mesa 20.3.5 is_context_loss_possible=false wezterm version: 20210925-221901-9be8f92d
```

### Anything else?

As I'm not sure if it's related to WezTerm or starship, I've posted the issue in starship as well. You can view that [here](https://github.com/starship/starship/issues/3096).

**Comment by wez** [comment]
Please capture a session recording; you can use the [wt-record](https://github.com/wez/wezterm/blob/main/wt-record) script from the wezterm repo to start wezterm and record to a script file.  Perform the minimal actions required to reproduce the issue and exit your shell, then attach the generated script file to this issue.

**Comment by jameschensmith** [comment]
@wez, in this case, there's no actions to take once WezTerm boots up. Everything is already initialized in `~/.bashrc` via `eval "$(starship init bash)"`. When I remove this from my `~/.bashrc` and execute it manually after booting up WezTerm, there are no jobs shown. So, it appears to only be reproducible in the `~/.bashrc` :thinking:

Unfortunately, this appears to be happening only for WezTerm, and only with the bash shell. Testing it in Zsh, it's gone. Testing it in other terminals, it's gone :sweat_smile: :man_shrugging:

**Comment by wez** [comment]
Then the action to take is to simply type `exit`?  The script will record the escape sequences that your shell + starship outputs, and means that I don't have to install starship to reproduce or otherwise understand what is happening.

**Comment by jameschensmith** [comment]
Gotcha. Makes sense. Had a bit of trouble with the script :sweat_smile: Apparently, GitHub doesn't like `.tgz`. Perhaps the script can be modified to output `.tar.gz`. I think I noticed a couple closed issues which stated a similar issue. Let me know if this helps with the context :+1:

Attachment: [20210927022336.tar.gz](https://github.com/wez/wezterm/files/7232919/20210927022336.tar.gz)

**Comment by wez** [comment]
Hmm, I don't see anything funky in what it captured; looks like it didn't emit the jobs stuff when you ran it?

```
^[[?2004h^M
^[[1;33mjames^[[0m in ^[[1;2;32monomatopoeia^[[0m in ^[[1;36m~^[[0m ^M
^[[1;32m$^[[0m ^M^[[K^[[1;32m$^[[0m exit^M
^[[?2004l^Mexit^M
```

**Comment by jameschensmith** [comment]
That's odd. It showed up when I did the recording.

I found the problem :tada: [WezTerm is spawning each shell as a login shell by default](https://wezfurlong.org/wezterm/config/launch.html#on-posix-systems). I'm not sure how it's causing the spawning to happen (I'm assuming it's when `~/.profile` sources `~/.bashrc`), but by overriding the WezTerm configuration with `default_prog = {"/bin/bash"}`, it's fixed. This was painful to pinpoint :sweat_smile:

What's the reasoning behind every shell spawned by WezTerm to be a login shell? It's causing duplicate variables in my case, as I'm attempting to take advantage of the startup files lifecycle (i.e. `~/.profile` is run for login shells, `~/.bashrc` is run for interactive shells).

In my situation, I'm logging into the Sway window manager (Wayland/XWayland; no `xinit`), which is executed through the shell's login lifecycle file. Then, while in Sway, I open a terminal, and the login lifecycle is invoked again. This is what's giving my quite a lot of problems, and I'm still trying to figure out if the best way to resolve this is in WezTerm, or somewhere at the tty level. Probably best to figure out once I get some sleep :yum: Any input is much appreciated (especially regarding my question above) :blush:

**Comment by wez** [comment]
We spawn the login shell because it is usually what you want.

In the situation you described, I think your shell startup would be more robust if you also checked for eg: `$WAYLAND_DISPLAY` or some other environment to decide whether to set that up from scratch, as there is nothing inherently "wrong" with spawning a login shell nested inside another.

You can, of course, choose to set `default_prog` explicitly to avoid spawning a login shell in wezterm if you wish.

**Comment by jameschensmith** [comment]
Thanks, @wez :slightly_smiling_face: Looks like more discussion came up in the starship issue I created, highlighting a potential bug on their side. I think we are good to close this issue. I appreciate you looking into this!
