### ISSUE TITLE
wezterm doesn't handle bitmap fonts with strikes spread across multiple files

### ISSUE THREAD

**Issue by wez** [wez/wezterm#1189]
@wez the Terminus installation on Arch has a bunch of otb files for  each strike size:

```
❯ fc-list | rg -i 'Terminus'
/usr/share/fonts/misc/ter-u22n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u20n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u22b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u20b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u24n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u32n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u28n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u24b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u18n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u12n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u16n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-u14n.otb: Terminus:style=Regular
/usr/share/fonts/misc/ter-x12b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x22b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x32b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x18b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x20b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x28b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x16b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x14n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x14b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x24n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x24b.pcf.gz: xos4 Terminus:style=Bold
/usr/share/fonts/misc/ter-x16n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x18n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x20n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x28n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x12n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-x22n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-u12b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-x32n.pcf.gz: xos4 Terminus:style=Regular
/usr/share/fonts/misc/ter-u16b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u14b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u18b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u32b.otb: Terminus:style=Bold
/usr/share/fonts/misc/ter-u28b.otb: Terminus:style=Bold
```

Problem is that on wezterm, no matter what `font_size` I set for `Terminus`, I always get the smallest sized one. I don't have similar problem with Alacritty. I'm trying setting values after pt2px conversion to no avail as well (I have 96 dpi).

FWIW, I'm trying to replicate [this](https://github.com/kovidgoyal/kitty/issues/2701#issuecomment-932656050), not sure whether it's possible at all on wezterm.

_Originally posted by @oblitum in https://github.com/wez/wezterm/issues/1165#issuecomment-932732562_

**Comment by wez** [comment]
Thanks for reporting this; I confirmed that installing the fedora terminus font (which also has multiple .otb files) resulted in an undefined/mismatched selection of fonts; here you can see that the primary font is the 32 pixel version, but the bold variant is the 20 pixel version. With `font_size = 12` (the default), neither of those is close to the desired 16 pixel height at 96 dpi:

```
; wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /usr/share/fonts/terminus-fonts/ter-u32n.otb, FontConfig
  "Terminus",

  -- /usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/google-noto-emoji/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})

...

When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /usr/share/fonts/terminus-fonts/ter-u20b.otb, FontConfig
  {family="Terminus", weight="Bold"},

  -- /usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/google-noto-emoji/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

I've pushed a commit that teaches font matching about the requested pixel size and available pixel sizes, so with that same configuration I now get:

```
; wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /usr/share/fonts/terminus-fonts/ter-u16n.otb, FontConfig
  -- Pixel sizes: [16]
  "Terminus",

  -- /usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/google-noto-emoji/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})

...

When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /usr/share/fonts/terminus-fonts/ter-u16b.otb, FontConfig
  -- Pixel sizes: [16]
  {family="Terminus", weight="Bold"},

  -- /usr/share/fonts/jetbrains-mono-fonts/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/google-noto-emoji/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

**Comment by oblitum** [comment]
Gonna try it with wezterm-git, I know it's gonna be a PITA though, giving compiling Rust projects is often annoying.

**Comment by oblitum** [comment]
Great, it's setting sizes just fine now.

Now onto inspecting whether I can get a wezterm variation of https://github.com/kovidgoyal/kitty/issues/2701#issuecomment-932656050.

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html to get the Terminus and Terminess fallback, and https://wezfurlong.org/wezterm/config/lua/config/font_rules.html for specifying an alternative font for italics.

**Comment by oblitum** [comment]
Okay. I was expecting that, I'm just not sure I can go as far as having antialias OFF for Terminus chars, and antialias ON for the rest.

**Comment by wez** [comment]
re: antialiasing: no AA is performed on bitmap fonts; the bitmaps are simply passed through.

**Comment by oblitum** [comment]
hmmm, nice, so I guess it'll just work by default :-)

**Comment by wez** [comment]
Yep!

**Comment by oblitum** [comment]
@wez I'm having one problem with such new bitmap font sizing, which is to make it more compatible with the sizes of counterpart ttf fonts that make part in the fallback/alternative chain I use. First, for Terminus on my PC, to get the same size as Terminus 10 on Alacritty, I have to set Terminus 12 on wezterm, and I suspect that's where issues start. As I'm using an alternative italic font (IBM Plex Mono), it's looking bigger than expected on wezterm:

Alacritty (with font size = 10):

![img-2021-10-02-151409](https://user-images.githubusercontent.com/1269815/135727599-a97b1ee7-ee49-44b9-9278-d5c86d197e33.png)

wezterm (with font size = 12):

![img-2021-10-02-151517](https://user-images.githubusercontent.com/1269815/135727622-0429b161-4ce3-49b5-b5ac-b31731f1ee14.png)

**Comment by wez** [comment]
Sizing fonts across unrelated families is notoriously finicky.  You can read more about the background in https://tonsky.me/blog/font-size/

I'd suggest looking at https://wezfurlong.org/wezterm/config/lua/config/use_cap_height_to_scale_fallback_fonts.html and setting it to true.

However, that setting only works well if both fonts have good *cap height* metrics. It's quite likely that the bitmap fonts don't have that.

**Comment by oblitum** [comment]
Sadly no effect. The issue I have isn't in fact that the alternatives are bigger than expected, they're in accord with the size I set, size 12 for the TTF italic alternative have the same appearance either in Alacritty as in wezterm. The issue is with the bitmap font, I don't use size 12 in Alacritty conf, I use size 10, but then the bitmap font is smaller then size 10 on Alacritty, and by setting it to size 12 it gets the same size as in Alacritty, but then the size setting affects all other fonts.

Don't you consider there's something wrong with the new bitmap font sizing? Maybe some off-by-one error? I'm saying this because as-is now, even though sizing is supported, out-of-the-box it's impossible to make this two fonts compatible in size.

**Comment by wez** [comment]
What does `wezterm ls-fonts` show for you?

**Comment by wez** [comment]
and also `wezterm ls-fonts --list-system | grep Terminus`

**Comment by oblitum** [comment]
```
Primary font:
wezterm.font_with_fallback({
  -- /usr/share/fonts/misc/ter-u16n.otb, FontConfig
  -- Pixel sizes: [16]
  "Terminus",

  -- /usr/share/fonts/TTF/Terminess (TTF) Nerd Font Complete.ttf, FontConfig
  {family="TerminessTTF Nerd Font", weight="Medium"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Italic=true:
wezterm.font_with_fallback({
  -- /usr/share/fonts/TTF/IBMPlexMono-Italic.ttf, FontConfig
  {family="IBM Plex Mono", italic=true},

  -- /usr/share/fonts/TTF/Terminess (TTF) Nerd Font Complete.ttf, FontConfig
  {family="TerminessTTF Nerd Font", weight="Medium"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- /usr/share/fonts/misc/ter-u16n.otb, FontConfig
  -- Will synthesize italics
  -- Will synthesize dim
  -- Pixel sizes: [16]
  "Terminus",

  -- /usr/share/fonts/TTF/Terminess (TTF) Italic Nerd Font Complete.ttf, FontConfig
  -- Will synthesize dim
  {family="TerminessTTF Nerd Font", weight="Medium", italic=true},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Will synthesize italics
  -- Will synthesize dim
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- /usr/share/fonts/misc/ter-u16n.otb, FontConfig
  -- Will synthesize dim
  -- Pixel sizes: [16]
  "Terminus",

  -- /usr/share/fonts/TTF/Terminess (TTF) Nerd Font Complete.ttf, FontConfig
  -- Will synthesize dim
  {family="TerminessTTF Nerd Font", weight="Medium"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Will synthesize dim
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /usr/share/fonts/misc/ter-u16b.otb, FontConfig
  -- Pixel sizes: [16]
  {family="Terminus", weight="Bold"},

  -- /usr/share/fonts/TTF/Terminess (TTF) Bold Nerd Font Complete.ttf, FontConfig
  {family="TerminessTTF Nerd Font", weight="Bold"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- /usr/share/fonts/misc/ter-u16b.otb, FontConfig
  -- Will synthesize italics
  -- Pixel sizes: [16]
  {family="Terminus", weight="Bold"},

  -- /usr/share/fonts/TTF/Terminess (TTF) Bold Italic Nerd Font Complete.ttf, FontConfig
  {family="TerminessTTF Nerd Font", weight="Bold", italic=true},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Will synthesize italics
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- /usr/share/fonts/misc/ter-u16n.otb, FontConfig
  -- Will synthesize italics
  -- Pixel sizes: [16]
  "Terminus",

  -- /usr/share/fonts/TTF/Terminess (TTF) Italic Nerd Font Complete.ttf, FontConfig
  {family="TerminessTTF Nerd Font", weight="Medium", italic=true},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Will synthesize italics
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

---

```
  "Terminus",
  "Terminus",
  "Terminus",
  {family="Terminus", weight="Bold"},
  {family="Terminus", weight="Bold"},
  "Terminus",
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u12n.otb, FontConfig pixel_sizes=[12]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u14n.otb, FontConfig pixel_sizes=[14]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u16n.otb, FontConfig pixel_sizes=[16]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u18n.otb, FontConfig pixel_sizes=[18]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u20n.otb, FontConfig pixel_sizes=[20]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u22n.otb, FontConfig pixel_sizes=[22]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u24n.otb, FontConfig pixel_sizes=[24]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u28n.otb, FontConfig pixel_sizes=[28]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u32n.otb, FontConfig pixel_sizes=[32]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x12b.pcf.gz, FontConfig pixel_sizes=[12]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x12n.pcf.gz, FontConfig pixel_sizes=[12]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x14b.pcf.gz, FontConfig pixel_sizes=[14]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x14n.pcf.gz, FontConfig pixel_sizes=[14]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x16b.pcf.gz, FontConfig pixel_sizes=[16]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x16n.pcf.gz, FontConfig pixel_sizes=[16]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x18b.pcf.gz, FontConfig pixel_sizes=[18]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x18n.pcf.gz, FontConfig pixel_sizes=[18]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x20b.pcf.gz, FontConfig pixel_sizes=[20]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x20n.pcf.gz, FontConfig pixel_sizes=[20]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x22b.pcf.gz, FontConfig pixel_sizes=[22]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x22n.pcf.gz, FontConfig pixel_sizes=[22]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x24b.pcf.gz, FontConfig pixel_sizes=[24]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x24n.pcf.gz, FontConfig pixel_sizes=[24]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x28b.pcf.gz, FontConfig pixel_sizes=[28]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x28n.pcf.gz, FontConfig pixel_sizes=[28]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x32b.pcf.gz, FontConfig pixel_sizes=[32]
wezterm.font("Terminus", {weight="Regular", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-x32n.pcf.gz, FontConfig pixel_sizes=[32]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u12b.otb, FontConfig pixel_sizes=[12]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u14b.otb, FontConfig pixel_sizes=[14]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u16b.otb, FontConfig pixel_sizes=[16]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u18b.otb, FontConfig pixel_sizes=[18]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u20b.otb, FontConfig pixel_sizes=[20]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u22b.otb, FontConfig pixel_sizes=[22]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u24b.otb, FontConfig pixel_sizes=[24]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u28b.otb, FontConfig pixel_sizes=[28]
wezterm.font("Terminus", {weight="Bold", stretch="Normal", italic=false}) -- /usr/share/fonts/misc/ter-u32b.otb, FontConfig pixel_sizes=[32]
```

**Comment by oblitum** [comment]
I think I managed to make it work by hacking a special size value: `10.5`. `10` to get the smaller variants with the actual size I wish, which is `10`, and `.5` to bump the strike of the bitmap font from the smallish `10` to the size as when I set it to `12`.

**Comment by oblitum** [comment]
It's a hack though, it's working but... doesn't seem pretty.

**Comment by oblitum** [comment]
Onto another subject, the italic variant on wezterm looks a bit more bolder, can you inform whether it's expected and what should I set to control this aspect, if possible?

wezterm:
![img-2021-10-02-161537](https://user-images.githubusercontent.com/1269815/135729262-b40bacd5-6e3d-4502-9d20-d84d885dd927.png)

alacritty:
![img-2021-10-02-161641](https://user-images.githubusercontent.com/1269815/135729295-d5c77937-da05-436b-955e-1d0af29af38e.png)

**Comment by wez** [comment]
> Don't you consider there's something wrong with the new bitmap font sizing?

No; based on the info you shared, it is behaving correctly.  The font size you requested is accurately selected from the available fonts.  The reason they don't look the same size across different the fallback fonts is because there isn't a standard way to equate font sizes, as is explained in that link I shared earlier.

It's pretty frustrating!

**Comment by oblitum** [comment]
I'm using weight to reduce the default bold appearance (`{ family = 'IBM Plex Mono', weight = 'Light', italic = true }`), gladly this font has many weights. I still got curious though on that aspect of wezterm.

**Comment by wez** [comment]
for the bolder-looking italics, is vim actually showing you bold+italic for that text?
To sanity check, `cat test-data/styles.txt` from the wezterm repo (you can download it from https://raw.githubusercontent.com/wez/wezterm/main/test-data/styles.txt) if you don't have the repo handy.

**Comment by wez** [comment]
it might also be interesting to see `wezterm ls-fonts --list-system | grep 'IBM Plex Mono'` on your system

**Comment by oblitum** [comment]
By explicitly setting the weight in the variant, I suspect I won't get a different weight then? If so, the above is the appearance for normal/medium weight, which I've set explicitly. I know NeoVim isn't setting bold+italic because I've also tested this on a markdown file with some italic and bold italic text.

**Comment by oblitum** [comment]
Hmm, on markdown actually, both italic and bold italic is looking the same...

**Comment by oblitum** [comment]
Okay, managed to get the different italic variants for italic and bold italic on Markdown editing by setting:

```lua
local wezterm = require('wezterm')

return {
    font = wezterm.font_with_fallback {
        'Terminus',
        'TerminessTTF Nerd Font',
        'Noto Color Emoji'
    },
    font_rules= {
        {
            italic = true,
            intensity = 'Half',
            font = wezterm.font_with_fallback {
                { family = 'IBM Plex Mono', weight = 'Light', italic = true },
                'TerminessTTF Nerd Font',
                'Noto Color Emoji'
            }
        },
        {
            italic = true,
            intensity = 'Normal',
            font = wezterm.font_with_fallback {
                { family = 'IBM Plex Mono', italic = true },
                'TerminessTTF Nerd Font',
                'Noto Color Emoji'
            }
        },
        {
            italic = true,
            intensity = 'Bold',
            font = wezterm.font_with_fallback {
                { family = 'IBM Plex Mono', weight = 'Bold', italic = true },
                'TerminessTTF Nerd Font',
                'Noto Color Emoji'
            }
        }
    },
    font_size = 10.5
}
```

I got a even bolder italic for markdown bold italic text, so yep, the actual bold italic is bolder than the italic, which has a bold appearance by default, at least more than on Alacritty.

I noticed though that my hack didn't work that great, I noticed it fixed the problem with IBM Plex Mono (which is a variant), but I'm getting smallish nerd icons from Terminess (which is a fallback).

This is getting tricky, guess I'm giving up.

**Comment by wez** [comment]
I made some changes to `use_cap_height_to_scale_fallback_fonts` that I think will help with the font heights.

**Comment by oblitum** [comment]
Sadly not helping:

![img-2021-10-02-232004](https://user-images.githubusercontent.com/1269815/135737186-3cc6e650-83ea-4799-b90a-2756ef7b6cb2.png)

**Comment by wez** [comment]
For square symbol glyphs that are not defined by unicode as being double width, you may want to consider changing https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html to something like `allow_square_glyphs_to_overflow_width = "WhenFollowedBySpace"` or `allow_square_glyphs_to_overflow_width = "Always"`

**Comment by oblitum** [comment]
I've set it to `"Always"` but it didn't help. You may notice how the yellow warning glyph is specially tiny when compared to the Alacritty counterpart. I tried to increase font size just to check at which point it would become of same size as the other and I had to increase it quite a lot.

**Comment by wez** [comment]
I think I see what's happening.

The unicode `WARNING SIGN` character U+26A0 is defined as having "text presentation" by default, which makes it have 1 cell width.

You should use the emoji presentation variation selector to force it to have emoji presentation, which will force it to be double wide

```
; cat /tmp/wat.sh
printf "\u26a0 text presentation by default\n"
printf "\u26a0\ufe0e explicit text presentation\n"
printf "\u26a0\ufe0f explicit emoji presentation\n"
```

![image](https://user-images.githubusercontent.com/117777/135759431-7c841019-75bd-44bd-883c-99b48759f99f.png)

**Comment by oblitum** [comment]
Thanks for sharing that info, that's good to know. Though, this is not the case, the warning sign I use comes from Nerd Fonts (search nf-fa-warning at https://www.nerdfonts.com/cheat-sheet), specifically TerminessTTF Nerd Font fallback.

**Comment by oblitum** [comment]
Actually, that's exactly the case, obviously I just need to apply the same logic with the hexcode for that nerd font glyph:

![img-2021-10-03-175401](https://user-images.githubusercontent.com/1269815/135771250-2f7a8d36-18b3-4bcc-b9de-3c5cca989b3a.png)

Can't I switch the defaults on this?

**Comment by oblitum** [comment]
This is great I think now everything was figured out for me to replicate what I have on Alacritty, I have almost given up :P

I just need a new release though, yesterday I built it on my low end laptop due to the multi-file font strike support, and it took ages to finish compiling :)

I have interest in the curly undercurl extension, I tried it yesterday but I've found the undercurls quite glued/too-close to the chars. Can it be tweaked for them to be a bit more distant?

**Comment by wez** [comment]
> Can't I switch the defaults on this? (even though I'm gonna be explicit from now on to be certain of the output, I think I'd need this for stuff I don't have control of, like the nvim-web-devicons that are shown for filetypes and fileformats, e.g., the Tux glyph in the screenshot is also smaller)

No, there's not an option for this.  This behavior is consistent with the Unicode specification that defines presentation and character widths, and these properties are fundamentally part of how text is represented and mapped to cells in the terminal model.  It's not feasible to make this optional in wezterm.

WezTerm, Kitty and Contour are at least three modern terminal emulators that correctly handle this aspect of unicode and proper text shaping, and we anticipate others moving in the same direction.

> I just need a new release though, yesterday I built it on my low end laptop due to the multi-file font strike support, and it took ages to finish compiling :)

There are pre-compiled nightly binaries available from https://wezfurlong.org/wezterm/install/linux.html

> I have interest in the curly undercurl extension, I tried it yesterday but I've found the undercurls quite glued/too-close to the chars. Can it be tweaked for them to be a bit more distant?

Please file a separate issue for this!

**Comment by wez** [comment]
Closing this out as the original issue is resolved!
