### ISSUE TITLE
Mouse selection favours char on the left

### ISSUE THREAD

**Issue by yangit** [wez/wezterm#1199]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20211004-173554-f511f9f5

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If you want to select text with mouse, characters on the left of the cursor are selected much more easily than that on the right. For example if you'd like to copy Wezterm: Hover your mouse in the middle of "W" and start dragging to the right it will not select "W" at the same time you are going to barely touch "m" and it is already selected.
If you try to select in the opposite direction(right to left) "m" is selected easily even you touch the very edge of it, while "W" is not selected until you hover beyond middle of the letter.

![bug](https://user-images.githubusercontent.com/2031974/135966646-dc67fb6c-60aa-4ddf-a3fb-32acd5fb92fc.gif)

Sorry if there is a configuration parameter about this that I've missed or this is the intended behaviour. Just felt weird and selecting something took longer so I wanted to report.

### To Reproduce

Please see the animated gif above.

### Configuration

no config

### Expected Behavior

Be consistent with either
1) selecting all chars as soon at the mouse starts to hover over them
2) be a bit lazy any do not select char until I hover beyond the middle (preferably as that is default chrome behaviour)

**Comment by bew** [comment]
YES THIS!!!
I see this on all platforms as well and it got me kind of crazy a few times already ^^

I'm in favor of the lazy way, where char selection doesn't happen on drag until the mouse crossed the middle of a char (or some third, based on the drag direction?).

**Comment by wez** [comment]
the current logic to determine the cell coordinate is here:
https://github.com/wez/wezterm/blob/main/wezterm-gui/src/termwindow/mouseevent.rs#L81-L88
it's disconnected from the logic where the drag is detected or handled, so doing some equivalent to the browser experience requires a bit more effort.
