### ISSUE TITLE
Emoji is not aligned with text

### ISSUE THREAD

**Issue by shaozi** [wez/wezterm#1203]
Emojis displayed are lower than regular texts. see screenshot:

![Screen Shot 2021-10-05 at 9 52 04 AM](https://user-images.githubusercontent.com/417833/136047551-a277eb02-4fc2-4c7b-8411-6a4ed0893552.png)

**Comment by shaozi** [comment]
## What Operating System(s) are you seeing this problem on?

macOS

## WezTerm version

20210814-124438-54e29167

## Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes. Same issue.

## Config file

```lua
{
     key = "d", mods="CMD",
     action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}
    },
    {
     key = "D", mods="CMD",
     action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}
    },
    {
     key="w", mods="CMD",
     action=wezterm.action{CloseCurrentPane={confirm=true}}
    }
  }
}
```

**Comment by wez** [comment]
This was resolved a while ago, closing out
