### ISSUE TITLE
Select copy does not copy up to shift click select

### ISSUE THREAD

**Issue by shaozi** [wez/wezterm#1204]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20211004-231321-49d77138

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When use mouse to select text to copy to clipboard, you highlight some text with mouse click-hold-drag-release, then move the mouse to a further location and Shift-click to select more text.

You can see all text are highlighted, but when you paste, you will find only the text selected in the first part is pasted, the other text selected with Shift-click is not copied.

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  font_size = 15,
  -- use_ime = true,
  enable_scroll_bar = true,
  window_padding = {
    left = 2,
    -- This will become the scrollbar width if you have enabled the scrollbar!
    right = 8,
    top = 4,
    bottom = 0,
  },
  color = {
    scrollbar_thumb = "white",
  },
  inactive_pane_hsb = {
    saturation = 0.9,
    brightness = 0.8,
  },
  launch_menu = {
    {
      label = "Bash",
      args = {"bash", "-l"},
    },
  },

  keys = {
    {
     key = "d", mods="CMD",
     action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}
    },
    {
     key = "D", mods="CMD",
     action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}
    },
    {
     key="w", mods="CMD",
     action=wezterm.action{CloseCurrentPane={confirm=true}}
    }
  }
}
```

### Expected Behavior

all highlighted text should be automatically copied to clipboard

**Comment by wez** [comment]
This was really a timing issue with SHIFT being held down longer than the mouse button.
I've added a default assignment that allows both shift-left-button-release and unmodified-left-button-release to perform the copy to clipboard
This will show up in the nightly downloads within an hour!
