### ISSUE TITLE
Chinese char took a while to display

### ISSUE THREAD

**Issue by shaozi** [wez/wezterm#1206]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20211004-231321-49d77138

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When there is Chinese characters in display, it took a few seconds to update the char from garbage char to the right ones. Nightly is faster, but still noticeable. Consequential display is fine.

See attached screencast.

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  font_size = 15,
  use_ime = true,
  enable_scroll_bar = true,
  window_padding = {
    left = 2,
    -- This will become the scrollbar width if you have enabled the scrollbar!
    right = 8,
    top = 4,
    bottom = 0,
  },
  color = {
    scrollbar_thumb = "white",
  },
  inactive_pane_hsb = {
    saturation = 0.9,
    brightness = 0.8,
  },
  launch_menu = {
    {
      label = "Bash",
      args = {"bash", "-l"},
    },
  },

  keys = {
    {
     key = "d", mods="CMD",
     action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}
    },
    {
     key = "D", mods="CMD",
     action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}
    },
    {
     key="w", mods="CMD",
     action=wezterm.action{CloseCurrentPane={confirm=true}}
    }
  }
}
```

**Comment by shaozi** [comment]
https://user-images.githubusercontent.com/417833/136059320-a779028c-26fb-45fc-a98c-d83a6a98a950.mov

**Comment by wez** [comment]
Those aren't garbage chars, they are last-resort placeholder glyphs.

What's happening is that when those characters are first used, wezterm needs to find a font that contains the glyphs for them.  To do that, it has to get the system list of fallback fonts and examine each of them until it finds a font that contains them, and that can take a noticeable amount of time.  While the search is in progress last-resort placeholder glyphs are used.

Nightly builds made significant improvements in the speed of the fallback lookup, but if that is still not fast enough for you, then you can explicitly add your choice of font as described here:

https://wezfurlong.org/wezterm/config/fonts.html#fallback
