### ISSUE TITLE
font_antialias: No longer any difference between Subpixel and Greyscale

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#121]
`20200113-222147-724ad3a-40-g118b91b`

I'm on Windows 10, the font loads up fine, but in the past there was a very different look to both Subpixel and Greyscale rendering. However there no longer appears to be any difference whatsoever, they look identical. I'd save the toml with the window visible in the background, nothing happens. That's not how it used to behave.

I always preferred the Greyscale rendering, I'm not sure if Greyscale now looks like Subpixel or Subpixel now looks like Greyscale, but I'm guessing the former.

**Comment by wez** [comment]
I suspect that that is a consequence of this change, which effectively "lines up" the pixels better when rendering:
https://github.com/wez/wezterm/commit/66560977945c39052e68b9a56432d0443df1eab0

I believe that to be a positive change; the commit fixed some unpredictable and wrong rendering, and I wondered if that might have been related to the issues you had with the clarity of the text.

Does the text render acceptably for you now?

**Comment by ImportTaste** [comment]
That is apparently not it. I went and downloaded older releases, it happened sometime between the release of 12/18 and 12/29. And unfortunately, the one of the two I preferred is now no longer available, it was not my eyes playing tricks on me after all.

Please note you'll have to open these up in two browser tabs and scroll back and forth to appreciate the difference.

Here's what Greyscale anti-aliasing is currently, it is identical to Subpxiel anti-aliasing:
![image](https://user-images.githubusercontent.com/53661808/72764015-d52a7f80-3bab-11ea-8cbc-f798e8d26e46.png)

And here is what Greyscale anti-aliasing used to be in the 12/18 build that was lost by the time the 12/29 build rolled around:
![image](https://user-images.githubusercontent.com/53661808/72764024-e7a4b900-3bab-11ea-85af-4cc9bc902487.png)

While the text is a bit shorter and not quite as perfectly aligned as Subpixel rendering, it is also appreciably sharper.

**Comment by wez** [comment]
c8cd6007068ae112c1be8aa8eca2fa61e5df396a is the only other change that I can think of that might possibly influence this.

If you're still able to run a build for yourself, please try applying this change to master and let me know if it makes a difference:

```diff
diff --git a/src/frontend/gui/termwindow.rs b/src/frontend/gui/termwindow.rs
index 6017b23..2f27867 100644
--- a/src/frontend/gui/termwindow.rs
+++ b/src/frontend/gui/termwindow.rs
@@ -1640,8 +1640,7 @@ impl TermWindow {
         .to_column_arrays();

         let draw_params = glium::DrawParameters {
-            // No alpha blending for the background layer: let's make
-            // sure that our background pixels are at 100% opacity.
+            blend: glium::Blend::alpha_blending(),
             ..Default::default()
         };

@@ -1669,6 +1668,8 @@ impl TermWindow {
         )?;

         let draw_params = glium::DrawParameters {
+            blend: glium::Blend::alpha_blending(),
+            /*
             blend: glium::Blend {
                 color: BlendingFunction::Addition {
                     source: LinearBlendingFactor::SourceAlpha,
@@ -1687,6 +1688,7 @@ impl TermWindow {
                 },
                 constant_value: (0.0, 0.0, 0.0, 0.0),
             },
+            */
             ..Default::default()
         };

```

If that's not it, I'd suggest trying to use `git bisect` to help you search the range and narrow it down.

**Comment by ImportTaste** [comment]
Unfortunately that was not it... guess I'm going to be learning about git bisect today.

**Comment by ImportTaste** [comment]
Okay, well, after learning git bisect and doing a lot of tests... Literally the only commit that gave me the Greyscale style font rendering was the one _before_ the font_antialiasing option was implemented, which doesn't make any fucking sense.

I started digging around in my files and I managed to come across an older compilation, one from 12-20, which I figured surely must work... but it didn't.

The only thing that changed between then and now... is my Windows build. I went from 18363.535 to 19041.x and for some reason, that seems to make Greyscale font_antialiasing look like Subpixel in commit https://github.com/wez/wezterm/commit/fc9e5ea0f5044762ba0b02b7a156192c067aaa33, and yet, if I compile the commit just before, the font_antialiasing is Greyscale (with obviously no ability to make it look like Subpixel because that isn't implemented).

I made some screenshots w/ settings here https://github.com/wez/wezterm/issues/79#issuecomment-567284300, and on both the 12/18 and 12/29 builds, those font settings look different than they used to (an improvement actually), so that seems to confirm my suspicions that this was brought about by a Windows change.

Question is, why is it not possible to get the 12/18 Greyscale antialiasing on the new Windows build to work on the font_antialiasing commit? I'm positive the config file is valid because changing the antialiasing to 'None' works just fine.

**Comment by ImportTaste** [comment]
@wez What differs from the 12/18 font_aliasing and the 12/19 Greyscale font_aliasing? Would it be possible to get a test build that gets rid of whatever minor differences there might be between them?

**Comment by wez** [comment]
AFAICT from looking at https://github.com/wez/wezterm/commit/fc9e5ea0f5044762ba0b02b7a156192c067aaa33 the old behavior should be equivalent to selecting:

```toml
font_hinting = "Vertical"
font_antialias = "Subpixel" # or Greyscale; they're equivalent when using Vertical hinting
```
