### ISSUE TITLE
hide title bar

### ISSUE THREAD

**Issue by xiangpeng2008** [wez/wezterm#1233]
Is it possible to hide the title bar "[1/4] C:\windows\system32\cmd.exe" on windows 10?

It's quite large
![image](https://user-images.githubusercontent.com/15676035/137586761-457bd956-98d0-4127-bbe8-78a97ce33383.png)

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html
