### ISSUE TITLE
Closing the only zoomed pane in the only window causes wezterm gui window to close

### ISSUE THREAD

**Issue by junkblocker** [wez/wezterm#1235]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20211009-173426-8c613d85

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When a zoomed pane is exited, wezterm window closes. I was expecting the remaining  pane(s) to unzoom.

### To Reproduce

1. Launch wezterm.
2.  Split pane.
3.  Zoom pane.
4.  exit # from the shell

### Configuration

```lua
return {
    unix_domain = {
        name = "unix",
        connect_automatically = true
    }
}
```

### Expected Behavior

The remaining panes should unzoom instead of the wezterm gui window exiting.

**Comment by wez** [comment]
FWIW, the config you shared isn't valid, but this issue didn't depend on using unix domain multiplexing in any case!
This is now fixed in `main`, and should show up in a nightly build within ~30 minutes.
