### ISSUE TITLE
Choose better "overall" background color (for pane borders) when only the shell is setting a color scheme

### ISSUE THREAD

**Issue by unrelentingtech** [wez/wezterm#1256]
**Is your feature request related to a problem? Please describe.**

I use my shell to set the color scheme ([this](https://github.com/chriskempson/base16-shell)).

If I also set a `window_background_gradient`, that gradient (I assume any lua-configured background) is used as a background for the whole window, pane separators included. Looks fine:

![Screen_2021-10-24-14:15:12](https://user-images.githubusercontent.com/208340/138591675-a28c8678-1125-4c44-bf8f-72a4d9ff3526.png)

However just relying on the shell color scheme (not having a background set in lua) results in a jarring `#000` black background appearing outside the pane areas, i.e. behind the pane separators and even in tiny gaps at the top and bottom:

![Screen_2021-10-24-14:15:37](https://user-images.githubusercontent.com/208340/138591777-c4697756-baa2-4d8d-8af2-77a7c0ebd539.png)

**Describe the solution you'd like**

I think we could do this when no background is explicitly set in lua:

- track the shell-configured background colors in all the panes of each tab
- when they're all equal, use that color as the overall background when showing that tab
- otherwise use e.g. the tab bar background (purple in the screenshots)

**Describe alternatives you've considered**

Just updating the overall terminal background to whatever the last set background is would be a cheap quick fix that would work in the simple case, and you could just say "configure a background in lua" to anyone who doesn't fall into the simple case, but the above isn't rocket science tbh :)

**Comment by wez** [comment]
Please give the nightly a shot when you next have the chance!

**Comment by unrelentingtech** [comment]
Looks great!
