### ISSUE TITLE
[wezterm ssh] Auth backend libssh doesn't allow password based authentication

### ISSUE THREAD

**Issue by bew** [wez/wezterm#1262]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

WezTerm-windows-20211024-192045-f4ee31fe (nightly)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm trying to use `wezterm ssh user@host` without an ssh key, expecting a password prompt.

**With the new default libssh backend**:
```
Using libssh-rs to connect to user@host:22
Error: Fatal: kex error : no match for method server host key algo: server [ssh-rsa,ssh-dss], client [ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256]
```

**FTR, with the previous ssh2 backend**:
```
SSH-2.0-OpenSSH_6.6
Authentication for user
Password for user@host: ......
```

### Configuration

N/A

### Expected Behavior

Working ssh authentication, with password prompt

**Comment by bew** [comment]
I tried to play with `HostKeyAlgorithms` and `KexAlgorithms` in my `~/.ssh/config` without much success 😞

**Comment by wez** [comment]
in the nightly, you can now put this in your `~/.ssh/config` for that host:

```ssh_config
PubKeyAcceptedTypes ssh-rsa
```

from what I can tell, this is either a libssh specific option, or possibly an old and deprecated openssh option, as it doesn't appear in any current docs for openssh.

**Comment by wez** [comment]
> in the nightly

I mean, the nightly knows how to supply that option to libssh if you set it in overrides at the wezterm level (eg: cli overrides, or via wezterm.lua settings); I think it should also work when read from your `~/.ssh/config` in any existing build using the libssh backend.
