### ISSUE TITLE
document that mux panes default color scheme is specified by server side config file

### ISSUE THREAD

**Issue by jay7x** [wez/wezterm#1268]
### What Operating System(s) are you seeing this problem on?

Windows, Linux X11

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

On my new job I got a windows box as the main working environment.. I spent time choosing terminal and found wezterm quite useful (thanks to a leader key and multiplexing). As there is no WSL allowed at the moment I'm using `msys2` for the shell and tools. I hit the slow rendering in vim but it seems it's kind of "feature" so I'm not going to complain here (let me know if I should create another issue wrt this).

I'm using wezterm ssh multiplexing to reach my Linux VM. It works quite nice and I like it. The only problem I see is the different colorscheme of the ssh multiplexed panes. I'm using "Builtin Solarized Light" on my Windows box and...

- local windows shells are using right colorscheme (pwsh.exe, cmd.exe, zsh.exe from msys2)
- `wezterm ssh <my-linux-box>` shows the remote pane in proper colorscheme as well
- `wezterm connect <my-linux-box>` is using lightgray text on the black background

I didn't tried nightly so far as it's quite complicated to get it there..

My linux box is Ubuntu 20.04. Wezterm binaries are manually extracted into the `$HOME/bin` (which is configured on windows side with `remote_wezterm_path`). No shell integration is enabled (I don't really need it).

I can guess 3 reasons so far:
1. Ubuntu 20.04 have some default shell colorscheme I'm not aware of.
2. missing wezterm shell integration is the reason
3. there is some bug in wezterm which overrides the colorscheme for attached multiplexed sessions

### To Reproduce

On Ubuntu 20.04:
1. Download the latest release in tar.xz and extract binaries into the `$HOME/bin` directory

On windows 10:
1. Install latest wezterm release (I used `scoop` for this)
2. Configure it to use "Builtin Solarized Light" colorscheme (`color_scheme = "Builtin Solarized Light"`)
3. Configure ssh domain with `remote_wezterm_path` pointing to the `/home/<user>/bin/wezterm` (or where `$HOME` is expanded to on the Ubuntu box above)
4. Run `wezterm ssh <your-ubuntu-ssh-domain>` to ensure it uses the right colorscheme
5. Run `wezterm connect <your-ubuntu-ssh-domain>` to see it uses other colors

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  color_scheme = "Builtin Solarized Light",
  colors = {
    tab_bar = {
      background = "#cccccc",
      active_tab = {
        bg_color = "#333333",
        fg_color = "#cccccc",
        intensity = "Bold",
      },
      inactive_tab = {
        bg_color = "#cccccc",
        fg_color = "#333333",
      },
    },
  },
  ssh_domains = {
    {
      name = "ubuntu-ssh-domain",
      remote_address = "<your-ubuntu-address>",
      name = "<your-ubuntu-username>",
      remote_wezterm_path = "/home/<your-ubuntu-username>/bin/wezterm",
    }
  },
}
```

### Expected Behavior

`wezterm connect <your-ubuntu-ssh-domain>` should use the configured colorscheme

**Comment by rbutoi** [comment]
I cannot get `wezterm connect $HOST` to respect any config file, including the server's. It shows up as the generic dark background theme. I have the same `~/.config/wezterm/wezterm.lua` on both client and server. How can I debug this--is there anything I can put into the `ShowDebugOverlay` that would help?

**Comment by wez** [comment]
@rbutoi please open a separate issue
