### ISSUE TITLE
`wezterm connect` unreliable on a high-latency connection

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#127]
## Describe the bug

`wezterm connect <host>` on a high-latency connection often hangs after printing
```
run_message_loop:flush
```
I need to ^C and restart several times before the connection starts up normally.

Running it with more tracing or under strace increases the likelihood of a connection being successful.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Frontend: OpenGL
 - Version: wezterm 20200113-222147-724ad3a-51-gb2a4ec7

## To Reproduce

`wezterm connect <host>` using a tls mux connection.

Sometimes it Just Works; failure is when it hangs after only printing
```
run_message_loop:flush
```

## Configuration
```
[[tls_clients]]
name = "dev"
remote_address = "<host>:8080"
expected_cn = "host:/<host>"
pem_private_key = "/.../<file>.pem"
pem_cert = "/.../<file>.pem"
pem_ca = "/.../<file>.pem"
pem_root_certs = ["<dir>", "<dir>"]
```
Be sure to include the relevant section(s) of your `wezterm.toml` configuration file.

## Expected behavior
Reliable connection.

## Additional context

It also fails to reconnect after connection loss/laptop suspend. I need to kill and restart it, which then leads to this problem.

**Comment by jsgf** [comment]
It doesn't have to be a particularly high latency connection...

**Comment by wez** [comment]
I haven't seen anything like this in a while, so considering this particular issue to be closed!
