### ISSUE TITLE
sixels are sometimes drawn too tall

### ISSUE THREAD

**Issue by dankamongmen** [wez/wezterm#1270]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211021-185611-04768fd1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

This is happening on current `main` head, and has been happening since at least September 16th (full background at https://github.com/dankamongmen/notcurses/issues/2170). I've attached the file `longsixel.txt`. On a WezTerm with 12x26px cell-pixel geometry, `cat`ting this file will generate many more than 26 (or 30) pixels. So far as I can tell, this image ought be 12x30 pixels, where the bottom 4 rows are all transparent. Instead, they seem to be getting random data.

Here's WezTerm, XTerm, and Alacritty-ayosec:

![2021-10-26-115346_730x338_scrot](https://user-images.githubusercontent.com/143473/138915782-b0044e59-5a80-46ec-8956-0833f6c43caf.png)

[longsixel.txt](https://github.com/wez/wezterm/files/7419639/longsixel.txt)

### To Reproduce

Use sixel rather than Kitty graphics, and cat the file.

### Configuration

```
-- wezterm config --
local config = {
    warn_about_missing_glyphs = false,
    --enable_kitty_graphics = true,--
}
return config
```

**Comment by dankamongmen** [comment]
it might not have been clear from my filing, but this only happens in sixel mode. obviously the inputs for sixel and kitty mode are distinct, but i've verified them both via inspection and use in other terminals as being the same.

**Comment by wez** [comment]
Is that a hidpi display? Wondering if this might be related to https://github.com/wez/wezterm/issues/1387
Your screenshot makes the sixel appear 2x as tall as it should be, so I wonder if the reported pixel geometry is even correct there.
That particular issue was resolved by resizing the window.

**Comment by dankamongmen** [comment]
dimensions:    3440x1440 pixels (910x381 millimeters)
  resolution:    96x96 dots per inch

**Comment by wez** [comment]
I'm fairly sure that was the same underlying issue as #1300, which is fixed in main now.  I wouldn't be surprised if that caused something else to regress, but let's hope it hasn't :-p

**Comment by dankamongmen** [comment]
let me give it a quick test

**Comment by dankamongmen** [comment]
it looks like the length is now fixed, but we're getting a bizarre second column worth of output that wasn't there before =\

![2021-12-11-182425_894x592_scrot](https://user-images.githubusercontent.com/143473/145694681-ccb80416-8b59-4d64-8628-11fbab61702f.png)

**Comment by wez** [comment]
ah, this is sort of the same problem but shifted to a different layer. The issue is that that last fractional slice of image is being stretched across the remaining fraction of a cell in whichever dimension.  Previously the math spread the whole image evenly across the cells, distorting the overall aspect ratio, but now it is mostly correct except for the last slice.

I'll need to do something to pass through information on where to stop to avoid this; will take a bit of plumbing!

**Comment by wez** [comment]
Alright, I think latest `main` is doing the right things now!

**Comment by dankamongmen** [comment]
yep, looks good now, way to be champ
