### ISSUE TITLE
BS at last column ignored in reverse-wraparound mode 

### ISSUE THREAD

**Issue by ninjalj** [wez/wezterm#1273]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211025-155636-b8ff61da

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

While comparing the behavior at the last column for BS, CUF, CUB, CUD and CUU of different terminal emulators, I noticed that wezterm ignores BS at the last column in reverse-wraparound mode (https://invent.kde.org/utilities/konsole/-/merge_requests/510#note_326117 for the results of the comparison).

What xterm does in that specific case is to reset the Last Column Flag, so the next graphic character printed will overwrite the character at the last column.

  

### To Reproduce

`tput hpa $((COLUMNS - 1)); tput smam; printf "\e[?45hA\bB";echo;echo; printf "\e[?45l"`

### Configuration

no config

### Expected Behavior

When a backspace is received while on the last column with the last column flag on wraparound mode, the last column flag should be reset, i.e. something like the following patch:

    diff --git a/term/src/terminalstate/performer.rs b/term/src/terminalstate/performer.rs
    index 3649c6e2..712a9816 100644
    --- a/term/src/terminalstate/performer.rs
    +++ b/term/src/terminalstate/performer.rs
    @@ -321,7 +321,8 @@ impl<'a> Performer<'a> {
                     {
                         // If the cursor is in the last column and a character was
                         // just output and reverse-wraparound is on then backspace
    -                    // by 1 has no effect.
    +                    // by 1 cancels the pending wrap.
    +                    self.wrap_next = false
                     } else if self.cursor.x == self.left_and_right_margins.start {
                         // Respect the left margin and don't BS outside it
                     } else {

### Anything else?

The behavior for `A<CUB 1>B` at the last column on wraparound mode also differs from that of xterm. xterm apparently treats `<CUB>` the same way as `<BS>` for all intents and purposes, including supporting reverse-wraparound to the preceding lines.

OTOH, foot, which enables reverse-wraparound by default, has decided to not support reverse-wraparound for CUB (https://codeberg.org/dnkl/foot/issues/441), because some program used CUB with a large argument to move to the leftmost column (https://github.com/sbt/sbt/issues/6421).

**Comment by wez** [comment]
Thanks for raising this. Sorry for the delay in responding; I've recently moved house and I'm slowly catching up with my backlog.

I think your suggested change sounds good. Is this and the CUB behavior you mentioned something that is covered/coverable in esctest? I saw that you unified the esctest forks and I'm pleased to see that!

**Comment by ninjalj** [comment]
> I think your suggested change sounds good. Is this and the CUB behavior you mentioned something that is covered/coverable in esctest?

For BS, I added a test at https://invent.kde.org/ninjalj/esctest/-/commit/eafa5a08fdd7ceb11681ca4a04acb308986c59b3, which is basically a modification of the already existing test_BS_CursorStartsInDoWrapPosition.

For CUB, first a decision should be made on the desired behavior:

 - As xterm, treat CUB as BS, and allow it to reverse wraparound.
 - As urxvt, putty and foot, stop CUB when it reaches the left edge/margin of the current line. Note that urxvt and putty do reverse wraparound for BS whenever AWM (autowrap mode) is enabled (they have no DECSET 45 switch for reverse wraparound), while foot enables reverse wraparound by default, which caused it to find the trouble with sbt.

**Comment by wez** [comment]
Thanks for adding that test!

Hmm, my general approach in wezterm is to treat xterm as correct, but it sounds like it may be the odd one out as far as CUB is concerned.  Did you look at VTE/Gnome Terminal?

**Comment by ninjalj** [comment]
VTE doesn't support reverse wraparound.

Looking at iTerm2 code, there is another variant:

 - Allow BS to reverse wrap when:
   - Reverse wraparound and AWM are set.
   - Or the previous line didn't end with a hard EOL (explicit newline).
 -  Allow CUB to reverse wraparound when the previous line didn't end with a hard EOL (explicit newline).

What the terminal emulators that always limit CUB to the current line have in common is that they enable reverse wraparound by default, either because they have no DECSET 45 toggle (urxvt, putty), or because they enable reverse wraparound by default (foot). OTOH, xterm behavior makes CUB and BS behavior consistent.

**Comment by wez** [comment]
Thanks for your insights!

I'm inclined to implement the xterm behavior, as that's always been my model. If I were to make `Cursor::Left` call through to `ControlCode::Backspace`, would I be missing anything obvious/bad?

**Comment by ninjalj** [comment]
On Thursday, December 2, 2021, Wez Furlong ***@***.***> wrote:

> Thanks for your insights!
>
> I'm inclined to implement the xterm behavior, as that's always been my
> model. If I were to make Cursor::Left call through to
> ControlCode::Backspace, would I be missing anything obvious/bad?
>
As long as reverse wraparound is not enabled by default, everything should
be OK. Of course, enabling it by default would confuse apps that expect CUB
with a big parameter to stop at the left edge (but they should probably be
using CUP or HPA instead).
