### ISSUE TITLE
Layout issue with panes closed with confirmation

### ISSUE THREAD

**Issue by junkblocker** [wez/wezterm#1277]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211027-125648-539d72a9

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When there are multiple split panes to the right of a pane, closing the one second from the left (at least) makes the layout in the leftmost pane forget there are further panes to the right and spill content into it.

### To Reproduce

1. Have a fresh wezterm tab.
2. Create some long line of output in this tab
```sh
perl -le 'print "x" x 1000'
```
The number 1000 needs to be enough to wrap the output line.
3. Create a split to the right (`Ctrl+a |` based on the configuration)
```sh
wezterm cli split-pane --horizontal -- bash -c false
```
4. From the original pane, create another split to the right  (`Ctrl+a |` based on the configuration)
```sh
wezterm cli split-pane --horizontal -- bash -c false
```
5. Close the second split from the left by confirming close of the pane. (Ctrl+a x - based on the configuration)
6. The line in the leftmost pane has now spilled into the pane(s) to the right of the one that was just closed.
7. Resize the window and it gets fixed.

### Configuration

Most likely not relevant

```lua
local wezterm = require "wezterm"

return {
    unix_domains = {
        {
            name = "unix",
            connect_automatically = true
        }
    },
    leader = {key = "a", mods = "CTRL"},
    keys = {
        {mods = "LEADER", key = "a", action = wezterm.action {SendString = "\x01"}},
        {mods = "LEADER", key = "|", action = {SplitHorizontal = {domain = "CurrentPaneDomain"}}},
        {mods = "LEADER", key = "-", action = {SplitVertical = {domain = "CurrentPaneDomain"}}},
        {mods = "LEADER", key = "x", action = {CloseCurrentPane = {confirm = true}}}
    }
}
```

### Expected Behavior

The layout should not forget about more panes on the right.

**Comment by wez** [comment]
Confirmed that this is an issue with multiplexer client panes.
Not 100% sure what the precise cause is yet, but it is related to the client tab size getting out of sync with the server tab size and the order and timing of the updates between the client and server.

Likely the same root cause and resolution as https://github.com/wez/wezterm/issues/783
