### ISSUE TITLE
Windows powershell: how to hide the server console?

### ISSUE THREAD

**Issue by deostroll** [wez/wezterm#1278]
I have installed the binary zip version of wezterm. In powershell prompt I start the following way (for a fresh standalone instance):

```
start "d:\apps\wezterm\WezTerm-windows-20210502-154244-3f7122cb\wezterm.exe"
```
However, this starts up a server console as shown below:

![image](https://user-images.githubusercontent.com/415336/139198661-950c525f-e358-4b10-8e6c-0d38b23f8baa.png)

The wezterm terminal also opens up. (No problems there). Also this will default the wz terminal instance to the location where I spawned it from. So I may open up many instances this way. So is there a way to hide the server console?

Note: this does not happen by double clicking the exe file.

**Comment by wez** [comment]
Sorry for the delay in responding; I'm in the middle of moving house!
You should start `wezterm-gui.exe` instead of `wezterm.exe`.  `wezterm.exe` is the CLI interface/launcher for wezterm, and runs in the win32 Console subsystem, which is why the native terminal window pops up.
`wezterm-gui.exe` is the GUI application itself, which has no associated terminal window.

**Comment by deostroll** [comment]
Yes. I have tried the `wezterm-gui.exe` also. It doesn't shoot up another console window instance. But it pollutes the shell from where it was launched from. Some logs get asynchronously logged there...

![image](https://user-images.githubusercontent.com/415336/140704567-38985f25-610c-4ded-a2e7-a8bc5dbae43e.png)

Not a huge problem, but it kind of confuses me trying to recall what that shell was...

**Comment by deostroll** [comment]
Actually it is somewhat a problem...if you close the parent terminal the child terminal dies...

**Comment by wez** [comment]
I've pushed a commit that I think may help with this. It should make its way into the nightly binary downloads in about 30 minutes from now

**Comment by deostroll** [comment]
Thanks. Tried it. But it looses context of the previous shell. Exiting the previous shell doesn't kill the new shell though.

**Comment by wez** [comment]
Can you clarify what's happening now?

**Comment by deostroll** [comment]
Sorry for the delay. What I meant was, if I run the wezterm-gui.exe from some path in my file system (e.g. `d:\foo\bar\baz`) a new window comes up and it defaults to the user folder (`C:\Users\<my_windows_username>`). 

But closing the parent shell (one at `d:\foo\bar\baz`) doesn't kill the recently spawned shell.

**Comment by wez** [comment]
OK, what you've described sounds like it is working as intended.  https://wezfurlong.org/wezterm/config/lua/config/default_cwd.html shows the logic that is used to determine the working directory in a newly opened window.

You can use the `--cwd` flag to specify the directory; `--cwd .` might be what you want here.
