### ISSUE TITLE
ReloadConfiguration doesn't add a new [ssh] domain to existing windows

### ISSUE THREAD

**Issue by jay7x** [wez/wezterm#1279]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When new ssh domain is added via the config file there is no way to see it in the Launcher (`ShowLauncher`) in existing windows even after explicit `ReloadConfiguration`. The only way to see it is to run another wezterm instance (from a powershell cmdline or via Windows start menu e.g.).

### To Reproduce

1. Edit the config file and add an SSH domain
2. Run the `ReloadConfiguration` action
3. Open the Launcher (right-click on the `+` or run the `ShowLauncher` action) to see ssh domains. Check there is no domain you've just added.
4. Run new wezterm window via powershell or Windows menu.
5. Check Launcher in the newly opened wezterm window to see the ssh domain you've just added.

### Configuration

no specific config

### Expected Behavior

Launcher should pick-up the new [ssh] domain configured after the configuration reload.

**Comment by wez** [comment]
This should be fixed in the nightly build; it should publish within the next hour
