### ISSUE TITLE
Request for support for earlier versions of macOS

### ISSUE THREAD

**Issue by laggardkernel** [wez/wezterm#128]
The current version requirement for macOS is 10.15 only. Could you lower this requirement and support for earlier versions of macOS?

**Comment by wez** [comment]
ah, we're probably just picking that up by accident.  I think targeting 10.14 seems reasonable (I'm still running that on my local system), but expressly supporting earlier versions than that would require that someone have an earlier system that they can test/verify things on.

What version are you hoping to have support for?

**Comment by wez** [comment]
the build associated with my PR is: https://github.com/wez/wezterm/pull/130/checks?check_run_id=407575091
when it completes, you'll be able to download the artifacts from it; I'd appreciate it if you could try those and let me know if that build works for you.

**Comment by wez** [comment]
I can confirm that that build runs on my 10.14 system whereas the prior nightly build didn't, so I'm considering this resolved; the CI is set to 10.9 and later which sounds like a reasonable lower bound.  Nightly builds should pick this up in roughly the next hour.

**Comment by laggardkernel** [comment]
I'm still on macOS 10.13.6. The artifact downloaded from the above link failed to run on my machine.

Here's the [problem report](https://pastebin.com/raw/ZgeXSmJt) I got when I launched the app from the launcher.

When I try to run the executable directly from another terminal, the following err pops up,

```
❯ ./wezterm
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Menlo", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple Color Emoji", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple Symbols", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Zapf Dingbats", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple LiGothic", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Menlo", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple Color Emoji", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple Symbols", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Zapf Dingbats", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple LiGothic", bold: false, italic: false }
 ERROR wezterm::frontend::gui::termwindow > scale changed so resize to RowsAndCols { rows: 24, cols: 80 } Dimensions { pixel_width: 1280, pixel_height: 800, dpi: 192 }
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/WezTerm.app/./wezterm
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/WezTerm.app/./wezterm
  Expected in: /usr/lib/libSystem.B.dylib

[1]    23194 abort      ./wezterm
```

**Comment by wez** [comment]
OK, let's try that again with this build: https://github.com/wez/wezterm/pull/132/checks?check_run_id=408711669

It may be the case that we cannot physically build for older macOS releases from those CI systems.  If that happens to be true, then you'll need to build it from source for yourself.

**Comment by laggardkernel** [comment]
Still crashed. [problem report](https://pastebin.com/raw/1FDx50QQ)

I followed your advice to build it for myself, and the custom build works. Finally, I saw the wezterm window. Thanks for your help.

But I got the same font error when run the executable from another terminal,

```
❯ ./wezterm
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Menlo", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple Color Emoji", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple Symbols", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Zapf Dingbats", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple LiGothic", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Menlo", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple Color Emoji", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple Symbols", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Zapf Dingbats", bold: false, italic: false }
 ERROR wezterm::font::parser > Did not locate a font match for FontAttributes { family: "Apple LiGothic", bold: false, italic: false }
 ERROR wezterm::frontend::gui::termwindow > scale changed so resize to RowsAndCols { rows: 24, cols: 80 } Dimensions { pixel_width: 1280, pixel_height: 800, dpi: 192 }
 ERROR wezterm::font::parser              > Did not locate a font match for FontAttributes { family: "Menlo", bold: true, italic: false }
 ERROR wezterm::font::parser              > Did not locate a font match for FontAttributes { family: "Apple Color Emoji", bold: false, italic: false }
 ERROR wezterm::font::parser              > Did not locate a font match for FontAttributes { family: "Apple Symbols", bold: false, italic: false }
 ERROR wezterm::font::parser              > Did not locate a font match for FontAttributes { family: "Zapf Dingbats", bold: false, italic: false }
 ERROR wezterm::font::parser              > Did not locate a font match for FontAttributes { family: "Apple LiGothic", bold: false, italic: false }
 ERROR wezterm::mux                       > read_pty EOF: tab_id 0
 ERROR wezterm::mux                       > removing window 0
```

**Comment by wez** [comment]
Those font "errors" are really just slightly dumb logging statements; it's OK that they didn't find the fallback fonts on startup.  Those only come into play when you try to render a character that isn't present in your preferred font.

regarding whether we can teach the CI to build something usable for you, I found this issue:
https://github.com/sharkdp/bat/issues/680#issuecomment-554192072
I think we can pass those flags down to the freetype build (which is where the bad symbol reference is coming from), so I'll have a go at doing that and updating the linked PR.

**Comment by wez** [comment]
Let me know how https://github.com/wez/wezterm/runs/409226292 works out for you when it's done building.

**Comment by laggardkernel** [comment]
Sorry, It doesn't work. There's even a forbidden symbol on the application icon.

Here is the [problem report](https://pastebin.com/raw/jktQcfiY).

**Comment by wez** [comment]
I made another attempt in https://github.com/wez/wezterm/pull/132/checks?check_run_id=409951301

**Comment by laggardkernel** [comment]
Yeah. The latest attempt succeeded.

**Comment by wez** [comment]
Thanks for letting me know; I've pushed that commit, so the next nightlies and releases should be more compatible once they get built out.
