### ISSUE TITLE
Choose Split Pane Label based on current pane

### ISSUE THREAD

**Issue by kcking** [wez/wezterm#1282]
**Is your feature request related to a problem? Please describe.**
I frequently move between WSL and Windows native. I want to be able to choose which label my split panes are launched with without having separate keybinds for each.

**Describe the solution you'd like**
I would like to choose the Launcher label of a split pane based on my current pane. It would also be nice to be able to change the launched SpawnCommand for a current pane using the launcher.

Loving Wezterm, thanks so much for your work on it!

**Comment by wez** [comment]
Sorry for the delay in responding: I was moving to a new state when you filed this and I've been working my way through a backlog since then!

Could you clarify some more about how you're using wezterm?
Do you have a launch menu entry for wsl and another for cmd/powershell?

Is your request for something like the launcher menu to show up when you trigger a new split pane action, so that you can launch one of those programs into the new pane?

**Comment by wez** [comment]
For spawning based on the current pane, the way that works today is based on the *domain* of the current pane.
There's typically a `local` domain for directly spawning processes, and there may be some number of unix, ssh or tls domains if the [multiplexer](https://wezfurlong.org/wezterm/multiplexing.html) is configured.  It's possible to [configure the multiplexer for WSL](https://wezfurlong.org/wezterm/multiplexing.html#connecting-into-windows-subsystem-for-linux).

The default spawn/split actions spawn into the same domain as the active pane.

For mixed WSL / native usage, I've been contemplating expanding the domain concept to allow launching via `wsl` without using the wezterm multiplexer server.  There are trade-offs to this approach (eg: image protocols don't always pass through the conpty layer of Windows, so spawning through the `wsl` executable isn't as high fidelity as connecting directly to the multiplexer inside the WSL instance), but it would have the advantage of being simpler to configure.

**Comment by kcking** [comment]
Thanks for getting back to me! I hope the move went well.

I use the WSL launch entry that is added by wezterm by default. I see what you're saying about domains vs. the actual executable that is running in that domain, I didn't understand that distinction before.

In the current setup, I'm always using a local domain. I use nushell on windows and wsl -> zsh for WSL. I currently have wsl 2 installed but could try wsl 1.

The behavior I would like is splitting a wsl pane to create another wsl pane by default. But I did just realize I can manually run `wsl.exe` in a new pane and be on my way.

**Comment by wez** [comment]
I haven't written up formal docs for this yet, but I pushed some code earlier today that I think will help you with wsl.
https://github.com/wez/wezterm/issues/1242#issuecomment-1008165306 describes those changes

**Comment by kcking** [comment]
Just installed nightly and can confirm split-pane now preserves local/wsl domain depending on how that tab was opened. Nice work!

**Comment by wez** [comment]
I'm going to close this issue in favor of https://github.com/wez/wezterm/issues/1485 which is tracking contextual menus
