### ISSUE TITLE
window_background_image once applied can not be removed away

### ISSUE THREAD

**Issue by junkblocker** [wez/wezterm#1283]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211017-103747-32d18905

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If I apply a background image to wezterm once, I can not remove it by changing the config and reloading it. Setting it to nil, or "/dev/null", or "" don't work.

### To Reproduce

1. Apply a background image using window_background_image and start wezterm gui.
2. Edit the configuration to change the window_background_image to anything like nil or "/dev/null" or "" or even removing it from config and just reload it. 

### Configuration

Not relevant

return {
   background_image = "/some/image/path"
}

### Expected Behavior

Setting it to nil or an invalid path or not having a property set in the config should remove it.

**Comment by wez** [comment]
I cannot reproduce this.  I tried:

```lua
return {
  window_background_image = "/home/wez/Downloads/sunset-american-fork-canyon.jpg"
}
```

Then I commented out the `window_background_image` line and saved the file and the background image was replaced by the default black background.

I think that there are some steps missing from the issue to successfully reproduce this!

**Comment by junkblocker** [comment]
Ok, I thought I had reproduced it with just that minimal config but couldn't reproduce it now with only the image change in the config.

However this reproduces it. Sorry for the elaborate steps as they reproduce my workflow:

##Repro

1. Use the following config changing WALLPAPERS to a directory with a few images in it.
2. Start with one hardcoded wallpaper near the bottom at
    ```lua
     window_background_image = wezterm.home_dir .. "/Pictures/Terminal-Wallpapers/120433284861-1024x768.jpg"
    ```
3. Press `Ctrl+Alt+Shift+w` to apply/change to a random wallpaper a few times.
4. Press `Ctrl+Shift+o` to toggle the hsb a few times. Leave it at a setting where it is visible,
5. Modify the line from step 2 to set the image to `""`.

    window_background_image = ""

The wallpaper is not removed at this stage.

##Config

```lua
local wezterm = require "wezterm"

WALLPAPERS = wezterm.glob(wezterm.home_dir .. "/Pictures/Terminal-Wallpapers/*")
function random_wallpaper()
    if #WALLPAPERS > 0 then
        return WALLPAPERS[math.random(#WALLPAPERS)]
    else
        return wezterm.home_dir .. "/Pictures/Terminal-Wallpapers/120433284861-1024x768.jpg"
    end
end

function hsb_toggle(window, pane)
    local overrides = window:get_config_overrides() or {}
    if
        not overrides.window_background_image_hsb or not overrides.window_background_image_hsb.brightness or
            overrides.window_background_image_hsb.brightness == 0.0
     then
        overrides.window_background_image_hsb = {}
        overrides.window_background_image_hsb.brightness = 0.05
        overrides.window_background_image_hsb.hue = 0.1
        overrides.window_background_image_hsb.saturation = 0.1
    elseif overrides.window_background_image_hsb.brightness == 0.05 then
        overrides.window_background_image_hsb.brightness = 1.0
        overrides.window_background_image_hsb.hue = 1.0
        overrides.window_background_image_hsb.saturation = 1.0
    else
        overrides.window_background_image_hsb.brightness = 0.0
        overrides.window_background_image_hsb.hue = 0.0
        overrides.window_background_image_hsb.saturation = 0.0
    end
    window:set_config_overrides(overrides)
end


function change_wallpaper(window, pane)
    -- set a new one
    local overrides = window:get_config_overrides() or {}
    overrides.window_background_image = random_wallpaper()
    window:set_config_overrides(overrides)
end

return {
    keys = {
        {key = "o", mods = "CTRL|SHIFT", action = wezterm.action_callback(hsb_toggle)},
        {key = "w", mods = "CTRL|ALT|SHIFT", action = wezterm.action_callback(change_wallpaper)}
    },
    window_background_image_hsb = {
        -- Darken the background image by reducing it to 1/3rd
        brightness = 0.5,
        -- You can adjust the hue by scaling its value.
        -- a multiplier of 1.0 leaves the value unchanged.
        hue = 0.5,
        -- You can adjust the saturation also.
        saturation = 0.5
    },
    unix_domains = {
        {
            name = "unix",
            connect_automatically = true
        }
    },
    -- window_background_image = wezterm.home_dir .. "/Pictures/Terminal-Wallpapers/120433284861-1024x768.jpg"
    window_background_image = ""
}
```

**Comment by wez** [comment]
The override that you set with `window:set_config_overrides` takes precedence, so if you reload the config with an empty `window_background_image`, but still have it set in your overrides, then that is what will be used.

I think you probably want to use https://wezfurlong.org/wezterm/config/lua/window-events/window-config-reloaded.html to clear out your overrides?

```lua
wezterm.on("window-config-reloaded", function(window, pane)
 -- remove any overridden wallpaper
 local overrides = window:get_config_overrides() or {}
 overrides.window_background_image = nil
 window:set_config_overrides(overrides)
end)
```

**Comment by junkblocker** [comment]
Ok. So my goal was to clear the wallpaper being the last step in changing that sequence of hsb, so this works.

```lua
function hsb_toggle(window, pane)
    local overrides = window:get_config_overrides() or {}
    if
        not overrides.window_background_image_hsb or not overrides.window_background_image_hsb.brightness or
            overrides.window_background_image_hsb.brightness == 1.0
     then
        overrides.window_background_image_hsb = {}
        overrides.window_background_image_hsb.brightness = 0.05
        overrides.window_background_image_hsb.hue = 0.1
        overrides.window_background_image_hsb.saturation = 0.1
        if not overrides.window_background_image then
            overrides.window_background_image = random_wallpaper()
        end
    elseif overrides.window_background_image_hsb.brightness == 0.05 then
        overrides.window_background_image_hsb.brightness = 0.0
        overrides.window_background_image_hsb.hue = 0.0
        overrides.window_background_image_hsb.saturation = 0.0
        overrides.window_background_image = nil
    elseif overrides.window_background_image_hsb.brightness == 0.0 then
        overrides.window_background_image_hsb.brightness = 1.0
        overrides.window_background_image_hsb.hue = 1.0
        overrides.window_background_image_hsb.saturation = 1.0
        if not overrides.window_background_image then
            overrides.window_background_image = random_wallpaper()
        end
    end
    window:set_config_overrides(overrides)
end
```

I noticed something interesting while trying out your `window-config-reloaded` suggestion - it keeps getting triggered while nothing is happening AFAICT! If I replaces the `nil` in your suggestion to `random_wallpaper()` this becomes very obvious as the wallpaper just keeps flipping non-stop. I'll discuss that on matrix though. Thanks!
