### ISSUE TITLE
`wezterm-ssh`: support for public keys signed with certificates

### ISSUE THREAD

**Issue by david-perez** [wez/wezterm#1284]
I'm a user of [`distant`](https://github.com/chipsenkbeil/distant/), which depends on `wezterm-ssh`.

Is there support for authentication with public keys signed with certificates?

`libssh`'s docs are not clear on this aspect, but [this function](https://api.libssh.org/stable/group__libssh__auth.html#gaa38c4f3194ef36720da7eddb0aa99e23) ("Authenticate with public/private key or certificate.") and [this recent thread](https://archive.libssh.org/libssh/2021-10/0000006.html) in the mailing list suggest that it is.

Currently `wezterm-ssh` offers public keys e.g. `id_rsa.pub` to the server when connecting, but I'd also like to provide the certificate with which they are signed e.g. `id_rsa-cert.pub`. Is it possible?

**Comment by wez** [comment]
My understanding is that distant currently uses the `libssh2` backend, which doesn't support this.
The version of `wezterm-ssh` in `main` uses `libssh` which does use the function you referenced.

@chipsenkbeil: can you confirm/deny my understanding?

**Comment by chipsenkbeil** [comment]
Yes, we're currently locked to the wezterm-ssh release as I'm unable to compile the Lua module on top of wezterm-ssh main. See https://github.com/chipsenkbeil/distant/issues/72 for the error and a sample project demonstrating the compilation failure.

**Comment by wez** [comment]
I'm closing this out as I don't think there is anything for wezterm-ssh to do here!
