### ISSUE TITLE
Nvim crashes on open

### ISSUE THREAD

**Issue by andreicorpo** [wez/wezterm#1288]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20211027-125648-539d72a9

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Whenever I open nvim, after a few seconds it somehow crashes and closes. Using the same config for nvim in other terminals and this does not happen.

### Configuration

``` lua
local wezterm = require("wezterm")

return {
	color_scheme = "Batman",
	font = wezterm.font("JetBrainsMono Nerd Font"),
  term = "wezterm",
	font_rules = {
		{
			italic = true,
			font = wezterm.font("JetBrainsMono Nerd Font Mono", { italic = true }),
		},
		{
			italic = true,
			intensity = "Bold",
			font = wezterm.font("JetBrainsMono Nerd Font Mono", { italic = true, weight = "Bold" }),
		},
		{
			intensity = "Bold",
			font = wezterm.font("JetBrainsMono Nerd Font", { weight = "Bold" }),
		},
	},
}
```

### Expected Behavior

Nvim should not crash and close.

### Logs

```
13:16:05.352 WARNING mux::localpane > unhandled DeviceControlMode::Data 3a :
13:16:05.352 WARNING mux::localpane > unhandled DeviceControlMode::Data 20
13:16:05.352 WARNING mux::localpane > unhandled DeviceControlMode::Data 6e n
13:16:05.352 WARNING mux::localpane > unhandled DeviceControlMode::Data 75 u
13:16:05.352 WARNING mux::localpane > unhandled DeviceControlMode::Data 6c l
13:16:05.352 WARNING mux::localpane > unhandled DeviceControlMode::Data 6c l
13:16:05.352 WARNING mux::localpane > unhandled DeviceControlMode::Data 7d }
13:16:05.352 WARNING mux::localpane > unhandled DeviceControlMode::Data 7d }
```

**Comment by wez** [comment]
Please start wezterm from another terminal like this:

```
RUST_BACKTRACE=1 wezterm
```

and then start nvim inside, and share its output here.

If it doesn't show a backtrace or other information about a panic, then try this alternative, which will log a LOT more information:

```
WEZTERM_LOG=trace wezterm
```

**Comment by andreicorpo** [comment]
The issues doesn't seem to happen anymore. Even tho I didn't update Wezterm since. You can close the issue and I'll reopen it if this behavior occurs again.

**Comment by phdpe** [comment]
I am having this issue with the latest `wezterm 20220101-133340-7edc5b5a` and `neovim v0.6.1` on Windows 10. Although Wezterm would only crash if I use `nvim` for the second time, i.e., `vi some_file` would be fine, but `vi same_or_another_file` would cause Wezterm to freeze for a second and then crash.  

I turned on `WEZTERM_LOG=trace wezterm` but no panic log was produced. The screen simply froze for a second and the terminal would crash. The log does not produce any error message at all. 

Can you please direct me to any possible resolution (or anything I can do to provide more debug information)?

**Comment by wez** [comment]
Please try the nightly build and if you continue to have problems, please open a new issue with information about your system

**Comment by phdpe** [comment]
thank you for your reply. I am still trying to gather all the information - it seems like it crashes on other occasions too, such as `fzf`, and sometimes when saving in `nvim`.  So far I've found that if I start wezterm with `cmd`, and then start `pwsh` in `cmd`, everything works fine.  But if I start `pwsh`, or even `cmd /k pwsh`, things crash easily.
