### ISSUE TITLE
Feature Request: Optimization of the iterm2 image protocols (like in the bv script by daleroberts)

### ISSUE THREAD

**Issue by fboumol** [wez/wezterm#1291]
Hi all,

Wezterm has already implemented iTerm2 image protocols, and I am wondering whether it might be easy to adapt the [bv script](https://github.com/daleroberts/bv) by [daleroberts](https://github.com/daleroberts) to make it work under wezterm (in particular through ssh).

If the answer is positive I think this might be an interesting feature to add to the the image protocols supported in wezterm. 

And it might be also worth trying to export the ideas in the [itermplot repository](https://github.com/daleroberts/itermplot).

**Comment by wez** [comment]
From what I can see of the code, `bv` should just work in wezterm as-is.  Have you tried it?

**Comment by fboumol** [comment]
Yes, I tried and it didn't work.

I downloaded [this image](http://media3.s-nbcnews.com/j/newscms/2016_20/1541946/160518-trump-portrait-jsw-145p_1c226e6636be4572928409c157f0d50a.nbcnews-ux-2880-1000.jpg) and when I run
 `./bv 160518-trump-portrait-jsw-145p_1c226e6636be4572928409c157f0d50a.nbcnews-ux-2880-1000.jpg`
I do not see any image in wezterm. All I get when running the previous command is the following line in the terminal
 `1000x1571 pixels / 3 bands.  [tfr: 618.1KB]`
but no image

**Comment by wez** [comment]
I've traced the issue to wezterm not allowing an empty parameter that is hardcoded in the bv script here:

https://github.com/daleroberts/bv/blob/master/bv#L75

You can hack around it locally by changing:

```
File=;size=
```

into

```
File=size=
```

This commit f56a6aa276b7c4c5ed67d68cf033474fa057de29 fixes the issue in wezterm and will be available as a nightly download within about 30 minutes from now.

**Comment by fboumol** [comment]
Great, the change you suggested in the bv script works wonderfully in my computer.

By the way, I have just tested the [itermplot repository](https://github.com/daleroberts/itermplot) and it works in wezterm.

**Comment by wez** [comment]
The output of the script running in wezterm:
![image](https://user-images.githubusercontent.com/117777/140561246-f192194e-4470-43e5-9a29-a9d0338b6868.png)

is consistent with the way that the text is cut off in that example when using its native window display:
![image](https://user-images.githubusercontent.com/117777/140561295-abdb6b73-6c2d-4036-a21e-081c5f07f93d.png)

**Comment by fboumol** [comment]
You are rigth. My mistake.

I was using wezterm with black background, and this is the reason I as not able to see anything. I have just changed the background (to blue) and nothing is missing.

**Comment by wez** [comment]
The docs suggested setting `ITERMPLOT=rv` to enable reverse video mode!
