### ISSUE TITLE
three asterisk->asterism replacement doesn't run following asterisk and space in vim

### ISSUE THREAD

**Issue by dankamongmen** [wez/wezterm#1293]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211103-091732-154691a1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

![2021-11-05-061230_507x335_scrot](https://user-images.githubusercontent.com/143473/140494983-2970fc6e-cc03-49f2-89ee-db10efa9f3a6.png)

You're replacing `***` with what appears to be an asterism `⁂`, which, whatever, but if an asterisk ends the previous token, you don't do the conversion. This leads to unbalanced visuals when I'm editing man pages using pandoc syntax, and I'm already deeply unhappy when editing man pages using twicecursed pandoc and just hoping I don't have to end up learning more Haskell to get syntax colored correctly.

Now, if i `cat` this file, things *do* work as expected, So it's presumably some interplay between your replacement and vim, which I'm sure makes this ten times less appealing to investigate. Sorry =[.

### To Reproduce

In WezTerm, run vim (hopefully not just with some settings of mine, ugh)....actually, wow, this appears to be dependent on syntax coloring within vim. If i rename the file to a different extension, the problem doesn't happen. Yeah, only if it terminates in `md` do I get this behavior. Hah, yeah, `:syntax off` fixes the problem, and `syntax on` breaks it again.

If you are thinking "I don't want to deal with this", I totally understand. If you want to investigate further, I'm happy to investigate further.

### Configuration

```
[schwarzgerat](0) $ cat ~/.config/wezterm/wezterm.lua 
-- wezterm config --
local config = {
    warn_about_missing_glyphs = false,
    enable_kitty_graphics = true,
}
return config
[schwarzgerat](0) $ 
```

### Expected Behavior

Asterisms replacing three asterisks in all instances, or none.

### Logs

nothing applicable, sadly

**Comment by bew** [comment]
I would say this is a font issue, this is a ligature from the Jetbrains Mono font (the default in Wezterm)

**Comment by dankamongmen** [comment]
> The ligatures are broken => not transformed when there's an attribute change in the middle of the ligature, so maybe for the `***` that are not 'ligaturized' there's a background color change? or just a color reset?

my money is on this, especially given that it depends on syntax coloring. very possible this is a "bug" in said syntax coloring.

**Comment by dankamongmen** [comment]
![2021-11-05-080240_861x106_scrot](https://user-images.githubusercontent.com/143473/140507495-d2f8c273-52fb-4f5d-a2ea-b8a8cfa062ab.png)

**Comment by dankamongmen** [comment]
i'm surprised by the second result there (`*\e[39m****`). i would expect either the first three or last three to be converted under our working theory.

**Comment by wez** [comment]
wezterm converts a `Line` into `CellCluster`'s by looking for runs of `Cell`'s with the same `CellAttributes` (colors, styles, image attachments).  The textual portion of each `CellCluster` is shaped by harfbuzz, which will by default use any contextual ligature substitutions specified by the font.

You can spelunk with the shaper using the `hb-shape` utility; here you can see that a run of three `*` is replaced by the `asterisk_asterisk_asterisk.liga` defined in that font, but a run of four is not:

```bash
7:06 wez@cube main ~/wez-personal/wezterm
; hb-shape assets/fonts/JetBrainsMono-Medium.ttf '***'
[SPC=0+600|SPC=1+600|asterisk_asterisk_asterisk.liga=2+600]
7:10 wez@cube main ~/wez-personal/wezterm
; hb-shape assets/fonts/JetBrainsMono-Medium.ttf '****'
[asterisk=0+600|asterisk=1+600|asterisk=2+600|asterisk=3+600]
```

**Comment by wez** [comment]
My money is on an unexpected attribute change in the vim syntax highlighting rules.  I suspect something subtle, like the different between setting the cell fg or bg to default vs. explicitly selecting a palette index for the cell that both look the same with the configured palette, but are different attributes in the underlying model.

**Comment by dankamongmen** [comment]
> You can spelunk with the shaper using the `hb-shape` utility; here you can see that a run of three `*` is replaced by the `asterisk_asterisk_asterisk.liga` defined in that font, but a run of four is not:

hrmmm that explains the second one, then, but not the fourth (`***\e[39m*`). indeed, you can see that it *is* turned into an asterism when i *type* it, but *not* in the output.

but yeah, i'm fairly sure there's also a bug in the syntax highlighting. i'll go look into that. feel free to close this or not.

**Comment by wez** [comment]
The `***\e[39m*` case is ligatured when you type the first 3 `*`'s because the following backslash character doesn't prevent that expansion, but when displayed the run of text is really 4 `*`'s and whatever rules are defined in the font don't cause the first 3 `*`'s to combine:

```bash
; hb-shape assets/fonts/JetBrainsMono-Medium.ttf '***\\'
[SPC=0+600|SPC=1+600|asterisk_asterisk_asterisk.liga=2+600|backslash=3+600|backslash=4+600]

; hb-shape assets/fonts/JetBrainsMono-Medium.ttf '****'
[asterisk=0+600|asterisk=1+600|asterisk=2+600|asterisk=3+600]
```

So this bit is just the ligature rules in the font itself.  I don't know if there is an easy way to review those, short of opening up the font in a fancy editor and knowing how to use that tool :)

**Comment by dankamongmen** [comment]
cool! sounds like you're pretty confident with how wezterm is handling this, so i'll go bark up whatever tree this vim stuff lives in. i always knew those ugandan orphans were up to no good. sorry to waste your time big buddy!
