### ISSUE TITLE
"Wezterm would like to access file in your Documents folder" keeps reappearing

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#1297]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20211105

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Not sure this is a bug, but felt better putting the discussion  here rather than in Discussions.

This is on a new M1 Mac running Monterrey.

When issuing a command such as `cd Documents` I get prompted with a dialog box saying "Wezterm would like to access files in your Documents folder". I click OK and then get prompted again, for what appears to be every single file in my Documents folder. `Documents` is not special here. Happens with Desktop, Downloads, etc.

Below the "would like to access" message in smaller print is "An application launched via Wezterm would like to access you Documents folder".

I have been through every setting in `Security and Privacy` multiple times. `Full disk access` is allowed.

When I restart Wezterm the prompts restart.

I cannot see any difference in Privacy settings with my Intel Mac which is running Big Sur where Wezterm prompts on initial access and never prompts again. The only variables that I can think of are Big Sur -> Monterrey and Intel -> M1.

### To Reproduce

Download fresh install of Wezterm. Run it (will have to let MacOS it's ok to run). Type a command. `cd Documents` is the simplest I've seen. Get prompted again and again.

### Configuration

No changes to config. Vanilla config would work.

### Anything else?

I've Googled everything I can think of to figure out how to fix. Nothing I've found adds to what I've said here. Nothing I've found talks about a similar problem.

I tried `tccutil reset All com.github.wez.wezterm`. It removed all permissions as expected. I added `wezterm` back to the security permissions (full disk access). Same problem.

Other apps work OK with full disk access. For example `iTerm2` and `ForkLift` after initial prompts to access never re-prompt. They are set with full disk access. Both of those apps are signed while Wezterm is not.

Image of message:
<img width="275" alt="Screen Shot 2021-11-06 at 13 06 02" src="https://user-images.githubusercontent.com/3060128/140617917-030e5823-f6d0-4f54-a918-7cb15291e883.png">

**Comment by wez** [comment]
See also: https://github.com/wez/wezterm/issues/482
I think that resolving this will require me code signing the bundle, which means that I'll need to set up automation to do that at home, as I don't think there is a sane way to do that using GH CI.

**Comment by gwww** [comment]
Closing. Use #482 to continue discussion.
