### ISSUE TITLE
Faulty text copying in multi-monitor setup

### ISSUE THREAD

**Issue by darg2012** [wez/wezterm#1298]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

wezterm copies text in pages above/hidden within wezterm instead of selected in another application

### To Reproduce

This appears to occur only when ssh'ing into a system and not locally. I have a vertically stacked monitor setup with wezterm running below and text sources/vs code running above. When trying to copy text outside wezterm from the aforementioned sources into wezterm, wezterm copies text hidden in previous pages within wezterm instead of the selected text in the other applications.

### Configuration

I think it could be config-independent but I could be wrong

### Expected Behavior

copy text from external applications

### Logs

10:34:16.076 INFO wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GT 750M OpenGL Engine 4.1 NVIDIA-14.0.32 355.11.11.10.10.143 is_context_loss_possible=false wezterm version: 20210814-124438-54e29167
10:40:57.247 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))

**Comment by wez** [comment]
Would you mind spelling out the precise steps required to trigger the issue so that I might be able to reproduce it?

**Comment by darg2012** [comment]
It's on my work setup, I'll try to replicate it during the week and troubleshoot it by monitoring the clipboard. One thing I did noticed was that on the vertical setup, hovering on the top monitor triggered the hover property on the tab bar I have on western on the monitor below, suggesting that the mouse is still recognized despite being on a different screen.

**Comment by darg2012** [comment]
I still experience it but couldn't figure out how to consistently replicated and just adjusted my workflow a bit. The semester in getting packed, but will try to record my keystrokes and both monitors after the holidays to figure out what is causing the issue.
