### ISSUE TITLE
imgcat pixel geometry incorrect on windows

### ISSUE THREAD

**Issue by LollipopFt** [wez/wezterm#1300]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20211105-080803-f56a6aa2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

image from inline is stretched. note: image is a ```.ppm```.
wezterm:
![image](https://user-images.githubusercontent.com/62802897/140630069-08e81730-7c00-4252-bb75-8317315eb1d9.png)
magick:
![image](https://user-images.githubusercontent.com/62802897/140630085-020e07b6-3214-48ad-9bf1-0068061c6a29.png)

### To Reproduce

1) make a ```.ppm``` file.
2) open it using imagemagick and wezterm.
3) see the difference: wezterm's is stretched.

### Configuration

```lua
return {
}
```

### Logs

10:34:20.777 INFO wezterm_mux_server_impl::local > setting up C:\Users\lollipopft\.local/share/wezterm\gui-sock-1440
10:34:21.334 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
10:34:21.402 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(9001))
10:34:21.431 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) HD Graphics 620 4.5.0 - Build 27.20.100.8682 is_context_loss_possible=true wezterm version: 20211105-080803-f56a6aa2

**Comment by LollipopFt** [comment]
edit: it also has this problem with other image types, take this for example
magick:
![image](https://user-images.githubusercontent.com/62802897/140630897-d3fe98c6-3d31-43b0-8fa9-1eb2978fd9ea.png)
wezterm:
![image](https://user-images.githubusercontent.com/62802897/140630903-6341e891-5868-458e-9927-4ac3c946d258.png)

**Comment by bew** [comment]
Can you share the images, so it's easier to reproduce?

**Comment by LollipopFt** [comment]
1st image: ```.ppm``` is not supported, and the source code is too long, so change the file type below from ```.txt``` to ```.ppm```:
[image.txt](https://github.com/wez/wezterm/files/7492222/image.txt)

2nd image:
![red-circle](https://user-images.githubusercontent.com/62802897/140644774-26ab49f0-dbfa-4c31-8573-5c8879c1a598.png)

**Comment by mborejdo** [comment]
I am also having this problem with distorted images on windows, but for me this happens only if I resize my wezterm-window. If I keep its starting-size, images seem to be rendered correctly

**Comment by LollipopFt** [comment]
for me, once i enter the terminal, the size is already distorted.

**Comment by wez** [comment]
I think this was the same underlying issue as #1270
