### ISSUE TITLE
Unexpected ligature issue

### ISSUE THREAD

**Issue by maximko** [wez/wezterm#1302]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20211105-080803-f56a6aa2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have an issue with letter sequence "fi". When I type "i" after "f" these two letters joins together and become "ﬁ". Please see attached video.

https://user-images.githubusercontent.com/633363/140654319-ff8f559e-e5f2-412b-a891-81c97bf192fc.mov

### To Reproduce

Just type f then i

### Configuration

`local wezterm = require 'wezterm';

return {
  font = wezterm.font("Monaco"),
  font_rules={
    {
      intensity="Bold",
      font=wezterm.font("Monaco", {
        foreground="#ffffff",
        weight="Bold"
      })
    },
    {
      italic=true,
      font=wezterm.font("Monaco", {
        italic=true
      })
    },
  },
  font_size = 14.0,
  color_scheme = "iterm",
  scrollback_lines = 15000,
  tab_max_width = 32,
}`

### Logs

19:56:24.355 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 630 4.1 INTEL-14.7.18 is_context_loss_possible=false wezterm version: 20211105-080803-f56a6aa2

### Anything else?

macOS 10.15.7

**Comment by wez** [comment]
That's just one of the default Monaco ligatures.

https://wezfurlong.org/wezterm/config/font-shaping.html has more information about controlling the use of ligatures

**Comment by maximko** [comment]
Thank you, the setting did the trick.

I also have an unrelated question but I don't think it deserves a dedicated issue — looks like anti-aliasing settings are different on non-retina displays (please see the video from my first post and attached screenshot). How to make fonts look the same?
![Screenshot 2021-11-08 at 12 13 36](https://user-images.githubusercontent.com/633363/140714993-43c56f3c-fc02-46c6-822c-9701d44595aa.png)

**Comment by trombonehero** [comment]
It's neat that harfbuzz can do things with ligatures, but could they be disabled by default? When using a fixed-width font in a terminal, ligatures can mess up alignment, which is important for code. Maybe the people who want them could enable them, rather than those who don't want them having to discover how to disable them?

**Comment by wez** [comment]
@trombonehero ligatures being on by default is one of the headline features of this terminal.  Most people want them on.

**Comment by wez** [comment]
@maximko please open a separate issue for the other display problem; it helps me to track overall status and avoids keeping things open too long if there is one issue per issue.

I'm closing this one because the original issue is resolved.
