### ISSUE TITLE
Support always using the same cwd when starting a new process

### ISSUE THREAD

**Issue by belak** [wez/wezterm#1306]
**Is your feature request related to a problem? Please describe.**
I prefer to start all my tabs in my home directory, rather than the current directory, as I use tabs to separate contexts and panes to run multiple tasks.

**Describe the solution you'd like**
The ability to always use the same cwd when opening a new tab. Having it also work when splitting panes would also work, or a way to have separate cwds.

**Describe alternatives you've considered**
I first attempted to set default_cwd, but that only works for the first window.

**Additional context**
I do realize that this change would make the flowchart in the `default_cwd` docs more complicated - I guess it's sort of a `cwd_override`, though maybe there's a better API using a callback that would actually make this easier? One option would be implementing the current functionality as the default cwd_callback function, but allowing overriding it.

**Comment by wez** [comment]
Have you considered rebinding your tab spawning key assignment to use [SpawnCommandInNewTab](https://wezfurlong.org/wezterm/config/lua/keyassignment/SpawnCommandInNewTab.html)?

That gives you the ability to specify the cwd in the [SpawnCommand](https://wezfurlong.org/wezterm/config/lua/SpawnCommand.html) object, something like this:

```lua
local wezterm = require 'wezterm';

return {
  keys = {
    {key="t", mods="CMD", action=wezterm.action{SpawnCommandInNewTab={
      cwd = wezterm.home_dir,
    }}},
  }
}
```

**Comment by belak** [comment]
Thanks for the response! That seems to work, though I worry I'll be playing whack-a-mole until I find all the relevant keybinds.

I've been looking on https://wezfurlong.org/wezterm/config/keys.html for the default keybinds, but is that accurate? For some reason the binds for SplitVertical and SplitHorizontal don't work for me on Linux. If you'd rather I can file a separate issue for that.

```
% wezterm --version
wezterm 20210814-124438-54e29167
```

**Comment by wez** [comment]
The docs *should* be accurate.  The definitive source can be found here: https://github.com/wez/wezterm/blob/main/config/src/keyassignment.rs#L249

If you find that something isn't included in the docs, please either submit a PR to add it to https://github.com/wez/wezterm/blob/main/docs/config/keys.md, or file an issue for it to be added!

I'll close this issue now as your original issue is resolved.
