### ISSUE TITLE
Clicking on unfocused wezterm instance selects "a bunch" of text

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#1310]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20211109-074757-c47c7c6d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have an unselected wezterm window (focus in in another application). I click on wezterm to make it the active application. If the click is not "perfect", meaning no horizontal movement, then a "bunch" of text of the wezterm window is selected. A bunch varies from multiple lines to from top of window to where I clicked.

This is important to the workflow because what I'm often doing is going to a browser window, copying some text to paste into wezterm. When I select wezterm it selects when I don't want it to, and hence copies text, overwriting my copied text from the browser.

### To Reproduce

This happens all the time. When I tried to reproduce so I can tell you about it, I couldn't -- even though it continues to happen. The best I can describe is that when clicking to select a wezterm window do so a move the mouse ever so slightly horizontally.

### Configuration

No config.

### Expected Behavior

Proposed behaviour. Never select text on window that is gaining focus. Similar to the swallow first mouse click.

**Comment by wez** [comment]
I pushed a change that I think helps with this; give the nightly a try and let me know?

**Comment by gwww** [comment]
No apparent change for me. Here is some more observation...

It does not matter what text is on the screen (so not a variable to consider). But have some text is useful to have a reference point.

1. Click anywhere on the screen. I click somewhere near the top and beside a piece of text that I use as a reference point.
2. Unfocus wezterm.
3. Now click on wezterm again, far away from the reference point. When clicking move the mouse ever so slightly (like you were selecting some text).
4. A selection is made that includes from the reference point to where you clicked to focused.

**Comment by wez** [comment]
Thanks; those steps made it easy to repro; I pushed a fix!

**Comment by gwww** [comment]
Yup, that definitely fixed it! Thank you!!
