### ISSUE TITLE
Empty window when automatically started after restart on macOS

### ISSUE THREAD

**Issue by dev-zero** [wez/wezterm#1319]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20211007-192622-8c347700

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I get this after a restart of macOS when macOS tries to restart the apps running before:
<img width="399" alt="Screenshot 2021-11-15 at 14 35 30" src="https://user-images.githubusercontent.com/11307/141792714-712762f4-4ab3-4ea0-929c-c02df2b649a5.png">

### To Reproduce

Have a Wezterm window open, restart my Mac (11.6) with the option to restore the windows afterwards enabled.

### Configuration

```
local wezterm = require 'wezterm';
return {
  -- enable_wayland = true,
  -- font = wezterm.font("Hack Nerd Font"),
   font = wezterm.font("FiraCode Nerd Font"),
  -- font = wezterm.font("BlexMono Nerd Font"),
  font_size = 11,
  --color_scheme = "OneHalfDark",
  -- color_scheme = "base16-tomorrow-night",
  -- color_scheme = "Dracula",
  color_scheme = "Gruvbox Dark",
  freetype_load_target = "Light",
  keys = {
    {key="DownArrow", mods="SHIFT", action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
    {key="UpArrow", mods="SHIFT", action=wezterm.action{CloseCurrentTab={confirm=true}}},
    {key="LeftArrow", mods="SHIFT", action=wezterm.action{ActivateTabRelative=-1}},
    {key="RightArrow", mods="SHIFT", action=wezterm.action{ActivateTabRelative=1}},
    {key="LeftArrow", mods="SHIFT|CTRL", action=wezterm.action{MoveTabRelative=-1}},
    {key="RightArrow", mods="SHIFT|CTRL", action=wezterm.action{MoveTabRelative=1}},
  }
}
```

### Expected Behavior

Get a proper window.

### Anything else?

Wezterm did not react to `cmd+q`, and there's no menu to quit, so I had to right-click on the icon in the dock to get an option to quit.

**Comment by wez** [comment]
Since CMD-q doesn't seem to function on that window, it makes it sound like it might be stuck.
Collecting a sample from the process might be revealing; next time this reproduces for you, please open activity monitor, select the wezterm process, then click on the gear or ... icon in the toolbar (depending on your version of macos), then select "Sample Process".  Please attach the sample here.

**Comment by dev-zero** [comment]
will do, thanks!
