### ISSUE TITLE
`text_background_opacity` doesn't work on win11

### ISSUE THREAD

**Issue by meijieru** [wez/wezterm#1325]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

With the following config, it doesn't have any effect when I change the  `text_background_opacity`

`text_background_opacity=0.1`
![image](https://user-images.githubusercontent.com/9511136/142112665-0cfc8e0b-8f93-47be-ab78-a38fcce1652e.png)
`text_background_opacity=1.0`
![image](https://user-images.githubusercontent.com/9511136/142112894-ddfc2eb5-9d5b-4cdd-985e-153213c96a16.png)

### To Reproduce

1. Use the config below.
2. Varies `text_background_opacity`

### Configuration

```lua
window_background_image = "D:\\document\\nextcloud\\picture\\comic\\EVA_OneHalfLight.jpg",
  window_background_image_hsb = {
    brightness = 1.0,
    hue = 1.0,
    saturation = 1.0,
  },

  window_background_opacity = 1.0,
  text_background_opacity = 0.1,
```

### Expected Behavior

The background image should be more transparent when `text_background_opacity` goes down.

**Comment by wez** [comment]
`text_background_opacity` only affects cells whose background color is changed to something other than the default background color, so if text had its background color set to red, and you had set `text_background_opacity = 0.5` then you'd see more of a pink color when using a white background image.

`window_background_opacity` controls the opacity for cells that have the default background color.

**Comment by meijieru** [comment]
It doesn't work either.

If I understand correctly, it should affect the background of `Windows.old/` here.

`text_background_opacity = 0.1`
![image](https://user-images.githubusercontent.com/9511136/142261646-ac4fb814-e28c-4a72-bbe2-8629065d4eba.png)

`text_background_opacity = 1.0`
![image](https://user-images.githubusercontent.com/9511136/142261762-d6dd9ae0-0b7b-4ac6-aa04-25767aa20dc9.png)

In addition, how can I blend the background image and the background from colorscheme?
I want the image to be opacity over the colorscheme background for the visibility of texts.

**Comment by meijieru** [comment]
Also, `window_background_opacity` doesn't work if `window_background_image` is not set.
In addition, change `window_background_opacity=0.1` deteriorate the font rendering.

 `window_background_opacity=0.1`
![image](https://user-images.githubusercontent.com/9511136/142347686-23466ad0-a34b-443b-9c1b-a806b01a4e6d.png)

 `window_background_opacity=1.0`
![image](https://user-images.githubusercontent.com/9511136/142347714-0fd6cdba-090d-4f64-af11-81b92e94022a.png)

**Comment by wez** [comment]
Please try the nightly build; there have been some fixes around opacity handling

**Comment by meijieru** [comment]
> Please try the nightly build; there have been some fixes around opacity handling

Looking forward to it.
How can I do it using scoop?

**Comment by wez** [comment]
I don't know if scoop knows how to get the nightly builds, but there are a number of other options here: https://wezfurlong.org/wezterm/install/windows.html

**Comment by meijieru** [comment]
In the nightly build, small `window_background_opacity` works. Though the fonts are still deteriorates.

`window_background_opacity=0.15`
![image](https://user-images.githubusercontent.com/9511136/142354602-b2d1bf6f-9be8-4861-bcc0-10d04b8e5506.png)

**Comment by wez** [comment]
Could you try again with the latest nightly?

**Comment by meijieru** [comment]
Download the latest build from https://github.com/wez/wezterm/releases/download/nightly/WezTerm-windows-nightly.zip, still have the problem.

**Comment by wez** [comment]
OK, I think this is now actually fixed in the very latest nightly; please try it and let me know!

**Comment by meijieru** [comment]
Confirm that the problem is solved.
