### ISSUE TITLE
Save scrollback history to file

### ISSUE THREAD

**Issue by yyogo** [wez/wezterm#1326]
It's often desirable to save the entire scrollback history to a file, e.g after a long command has finished but it's output wasn't captured, or when running in a remote shell.

Ideally, wezterm would have this implemented as a mux server command accessible by the CLI, or as an action (that would include an overlay for filename input or some other configuration). 

# Prior art
* `tmux` has the `capture-pane` command

# Alternatives
* Copy mode -> `g0vG$` -> copy & paste to a file

**Comment by bew** [comment]
There is an example of something close in https://wezfurlong.org/wezterm/config/lua/wezterm/on.html#custom-events

**Comment by yyogo** [comment]
> There is an example of something similar in https://wezfurlong.org/wezterm/config/lua/wezterm/on.html#custom-events You can use a custom lua action to do this.

Alright, thanks! 

I suppose this could also be done from the CLI, right? I haven't been able to use `cli proxy`, maybe it's a bug
