### ISSUE TITLE
Fails to open the vis editor

### ISSUE THREAD

**Issue by erf** [wez/wezterm#134]
## Describe the bug

I fail to open the [vis editor](https://github.com/martanne/vis) in wezterm. 

## Environment (please complete the following information):

    macOS 10.15.2 (19C57)
    Frontend: not sure
    20200113-222147-724ad3a
    
Using zsh shell

## To Reproduce

Built latest version of vis from scratch

run `vis` from wezterm

## Expected behavior

I expect `vis` to open, but it just hangs

**Comment by wez** [comment]
FWIW, I don't see any hangs with the nightly build (I'm using the pre-built `vis` package on Fedora, but I don't expect that that will be significantly different than what you're running on the mac).  I just pushed a commit that accepts the alternative rgb color specs that `vis` uses to apply its color schemes.  

When this build completes https://github.com/wez/wezterm/runs/409579947 you'll be able to download its binaries and try it out.

**Comment by erf** [comment]
I tried with the latest build, but same problem. If i try to run just `vis` it hangs, if i run `vis test.txt`, it prints the output of the file and exits. Not sure how to debug this. Maybe i could use `dtrace`, but i have no experience using it, and it seem i`m not allowed to use it because of some macOS security measures. Maybe i`ll figure it out. It could be that i build vis using some optional libraries that causes the bug. If i run `vis -v`now it prints:
```vis v0.5-97-g3a1023e +curses +lua +tre```

**Comment by wez** [comment]
try starting it like this:

```
RUST_LOG=trace wezterm start vis >/tmp/trace.txt 2>&1
```

that should spawn a new window that launches vis, and dump a very verbose log to a log file; capture that log file and attach it to this issue and that will help to debug it.

Do you have any configuration files for vis that might influence how it behaves?

**Comment by wez** [comment]
FWIW, the version I have on Fedora is:

```
$ vis -v
vis v0.5 +curses +lua +tre +acl +selinux
```

**Comment by wez** [comment]
> I tried with the latest build, but same problem. If i try to run just `vis` it hangs, if i run `vis test.txt`, it prints the output of the file and exits.

I just installed `vis` using homebrew just now, and this is printed out during installation:

```
==> Caveats
To avoid a name conflict with the macOS system utility /usr/bin/vis,
this text editor must be invoked by calling `vise` ("vis-editor").
```

Given your comments on the vttest issue about your path, my theory is that you may have been running `/usr/bin/vis` rather than the editor; the behavior matches what I see when I run `/usr/bin/vis`.

However, if I run `vise` then the behavior I see is consistent with what I saw on Fedora.

**Comment by erf** [comment]
I think you may be right. It seem to work with your latest fix on the path, so will close this now.

**Comment by erf** [comment]
Hmm, actually vis did not work after i removed the `default_prog` from `.wezterm.toml`, but i aliased vis to `/usr/local/bin/vis` and that worked..
