### ISSUE TITLE
Per pane scrollback_lines setting/override

### ISSUE THREAD

**Issue by junkblocker** [wez/wezterm#1343]
**Is your feature request related to a problem? Please describe.**

Some use cases are just expected to generate a lot of lines or output (e.g. tailing a log) and are not important. In those cases I'd prefer to be able to say don't save too much scrollback history for this pane rather than fill up memory/disk and crash.

**Describe the solution you'd like**

A per pane override for scrollback_lines.

**Describe alternatives you've considered**

Live in fear of disk fills and crashes.

**Additional context**
.

**Comment by wez** [comment]
Today you can use https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html to set it for the panes that share the same window.

wezterm already supports per pane configuration under the covers, the challenge is in finding the right UX to expose it.  For example, how would you like to specify the override for your use case?  That's missing from the "describe the solution you'd like" section of this issue.

**Comment by junkblocker** [comment]
Good point. I was hoping to maybe use a user var (`get_user_vars()`) but haven't thought beyond that.

**Comment by wez** [comment]
I'm going to close this out; there have been improvements to the scrollback memory utilization in the most recent release and if you need bigger than that, then https://github.com/wez/wezterm/issues/1342 is probably needed
