### ISSUE TITLE
Path not expanded in `cwd` field of `SpawnCommand`

### ISSUE THREAD

**Issue by joschka** [wez/wezterm#1344]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211123-065748-f0f7110d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

wezterm fails to  recognize paths like `~/.config/wezterm` or `$HOME/.config` in the `cwd` field of the `SpawnCommand` struct and falls back to using the home directory. An absolute path like `/home/<USER>/.config/wezterm` works, though. 

### Configuration

```
local wezterm = require 'wezterm'
return {
  keys = {
    {key = 'F12', mods = 'CTRL', action = wezterm.action{SpawnCommandInNewTab={cwd = '~/.config/wezterm', args = {'nvim', './wezterm.lua'}}}},
  }
}
```

### Expected Behavior

expected: nvim opens `~/.config/wezterm/wezterm.lua`

(actual: nvim opens `~/wezterm.lua`)

### Logs

No log entry.

**Comment by wez** [comment]
This isn't a bug; `~` and environment expansion are not performed by lua.

You can use [wezterm.home_dir](https://wezfurlong.org/wezterm/config/lua/wezterm/home_dir.html) to determine the home directory, and use something like this in your config:

```lua
local wezterm = require 'wezterm'
return {
  keys = {
    {key = 'F12', mods = 'CTRL', action = wezterm.action{SpawnCommandInNewTab={cwd = wezterm.home_dir .. '/.config/wezterm', args = {'nvim', './wezterm.lua'}}}},
  }
}
```

**Comment by joschka** [comment]
Thank you for replying instantly. I didn't know this. Thank you very much for explaining. Your proposal works perfectly.
