### ISSUE TITLE
Blink the text cursor

### ISSUE THREAD

**Issue by danimesq** [wez/wezterm#1354]

**Comment by wez** [comment]
There's no information in this issue. I'm assuming that you didn't see https://wezfurlong.org/wezterm/config/lua/config/default_cursor_style.html
but if that's not the case, please re-open this and explain in more detail what you're looking for.

**Comment by danimesq** [comment]
> but if that's not the case, please re-open this and explain in more detail what you're looking for.

I'm suggesting the cursor blinking by default.
