### ISSUE TITLE
80x24 as default size

### ISSUE THREAD

**Issue by danimesq** [wez/wezterm#1355]

**Comment by wez** [comment]
Yes, it is!

**Comment by danimesq** [comment]
![Screenshot from 2021-11-29 03-12-29](https://user-images.githubusercontent.com/6765277/143817609-6e2fbb9f-6d47-4bfb-aad7-2628b93efe19.png)

I meant not only the columns/rows, but also the window size.

**Comment by wez** [comment]
The initial tty is sized to 80x24 and the window decorations fit around that

**Comment by danimesq** [comment]
I just would like that the window were smaller, the same size as the default on Ubuntu.

**Comment by wez** [comment]
You could make the font size smaller

**Comment by danimesq** [comment]
But the font is nearly the same size as the font in GNOME Term; I don't think using the same font and size will make the window the same size of the default we knew in Ubuntu.
