### ISSUE TITLE
make it easy to use BufferedTerminal

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#136]
Discussion from https://users.rust-lang.org/t/embedding-trait-inside-of-struct/37176/10?u=prabirshrestha

---

So now I'm trying another project with similar issue of storing generics impl in struct and since it returns `impl Trait` I can't seem to figure out how to add it to the sturct. I'm using [termwiz](https://crates.io/crates/termwiz) 0.6.0. 

I would like to store `BufferedTermainal<T>` inside `Editor` struct.

```rust
use anyhow::Error;
use termwiz::caps::Capabilities;
use termwiz::terminal::buffered::BufferedTerminal;
use termwiz::terminal::{new_terminal, Terminal};

pub struct Editor<T: Terminal> {
    buffer: BufferedTerminal<T>,
}

impl<T: Terminal> Editor<T> {
    pub fn new() -> Result<Editor<T>, Error> {
        let caps = Capabilities::new_from_env()?;
        let mut terminal = new_terminal(caps)?;
        let buffer = BufferedTerminal::new(terminal)?;
        Ok(Editor { buffer })
    }
}
```

The problem here is `new_terminal` returns `Result<impl Terminal, Error>` I can't get the actual generic type. Here seems like this is a use case where I would use `Box` with dynamic dispatch but can't seem to figure out.

Here are some relevant snippets from the termwiz source code. 

```rust
pub struct BufferedTerminal<T: Terminal> {
    terminal: T,
    ...
}

pub fn new_terminal(caps: Capabilities) -> Result<impl Terminal, Error> {
    SystemTerminal::new(caps)
}
```

Here is the direct link to the source code of termwiz. https://github.com/wez/wezterm/tree/152aa85e8217c39e74ea920a913140879373ed63/termwiz

Also how would one implement `Editor` without generics.

**Comment by prabirshrestha** [comment]
Primarily trying out to build the [kilo editor](https://viewsourcecode.org/snaptoken/kilo/index.html) using termwiz.

**Comment by wez** [comment]
It probably wouldn't hurt to make it easier to use boxed traits for this, but if you are targeting just a client of the system terminal types, then I'd suggest doing something like this:

```rust
pub struct Editor {
    buffer: BufferedTerminal<SystemTerminal>,
}
```

which will pick up the concrete implementation of `Terminal` on unix and windows platforms

**Comment by prabirshrestha** [comment]
Landed up using `SystemTerminal` which I prefer over box traits so should be good for now.

```rust
use anyhow::Error;
use termwiz::caps::Capabilities;
use termwiz::terminal::buffered::BufferedTerminal;
use termwiz::terminal::SystemTerminal;

pub struct Editor {
    pub buffer: BufferedTerminal<SystemTerminal>,
}

impl Editor {
    pub fn new() -> Result<Editor, Error> {
        Ok(Editor {
            buffer: BufferedTerminal::new(SystemTerminal::new(Capabilities::new_from_env()?)?)?,
        })
    }
}
```
