### ISSUE TITLE
New actions: ScrollToTop and ScrollToBottom

### ISSUE THREAD

**Issue by Funami580** [wez/wezterm#1360]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
New actions: ScrollToTop and ScrollToBottom

**Describe alternatives you've considered**
ScrollByLine=-5000
ScrollByLine=5000

**Additional context**
It would be nice if there was a more general solution than scrolling by an arbitrary number of lines.

**Comment by wez** [comment]
This will show up in the nightly builds within an hour:
https://wezfurlong.org/wezterm/config/lua/keyassignment/ScrollToTop.html
https://wezfurlong.org/wezterm/config/lua/keyassignment/ScrollToBottom.html

**Comment by Funami580** [comment]
Thanks!
