### ISSUE TITLE
Rectangular selection

### ISSUE THREAD

**Issue by Funami580** [wez/wezterm#1361]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A KeyAssignment action to toggle block selection mode (for copying).

**Describe alternatives you've considered**
Copying the text in an editor and using block selection mode there.

**Additional context**
N/A

**Comment by gegoune** [comment]
Would also be nice to have block mode selection with mouse.

**Comment by bew** [comment]
NOTE: rectangular/block selection was mentioned in #182 as an aside, but didn't find an issue just for it, so I guess we can use this one.

**Comment by wez** [comment]
Do you mean rectangular selection, or something else?

**Comment by Funami580** [comment]
> Do you mean rectangular selection

Yes, sorry if that wasn't clear.

**Comment by esurharun** [comment]
Would be great!

**Comment by wez** [comment]
This should be fixed now in `main`.  Holding down `Alt` while selecting will use block selection in the default key assignments.  You can explicitly use `"Block"` as the mode in custom assignments.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Funami580** [comment]
Thanks, I just tried it out. If I begin the selection from the top left corner, everything works well. If I begin with the top right or bottom left corner no selection shows up. Beginning with the bottom right corner only works, if you move the selection at least one line up. Also pressing Alt+Shift to select a range without pressing the left mouse button the entire time does not seem to work.
