### ISSUE TITLE
Wezterm with enable_wayland fails to show a window

### ISSUE THREAD

**Issue by srevinsaju** [wez/wezterm#1364]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Wezterm fails to start when `enable_wayland` was set to `true` in the configuration on the latest release, but it looks like this bug was introduced a while ago. I ran a `git bisect`, and found out the bad commit which introduced this issue.

8c613d85886aae0faec540b2d257621ae568d683 is the first bad commit, it has some description related to changes related to wayland decorations.

### To Reproduce

With the following as `wezterm.lua`
```lua
local wezterm = require 'wezterm';
return {
    enable_wayland = true,
}
```

starting the latest AppImage build, or building from source on latest release, a new task appears to be created on the task manager / app launcher, but probably it has a window size of `0x0`, which makes it seem invisible.  

### Configuration

Minimal reproducible configuration

```lua
local wezterm = require 'wezterm';
return {
    enable_wayland = true,
}
```

### Expected Behavior

The window should be visible.

### Logs

```
 2021-12-05T09:09:17.078Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-78925
 2021-12-05T09:09:17.412Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) Xe Graphics (TGL GT2) 4.6 (Compatibility Profile) Mesa 21.2.5 is_context_loss_possible=false wezterm version: 20211009-173426-8c613d858
 ```

**Comment by wez** [comment]
Possibly a duplicate of https://github.com/wez/wezterm/issues/1257

**Comment by srevinsaju** [comment]
Ah sorry, didnt see that one.
