### ISSUE TITLE
Update available message is shown despite using the latest version

### ISSUE THREAD

**Issue by orhun** [wez/wezterm#1365]
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland

### WezTerm version

20211204-082213-a66c61ee

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm maintaining the [wezterm](https://archlinux.org/packages/community/x86_64/wezterm/) package in the Arch Linux community repository. Today, I built `wezterm` and updated package to `20211204.082213.a66c61ee9`. However, due to the project version being one character short, `wezterm` now thinks that it is not up-to-date and shows an "Update Available" message.

```
Current version (wezterm -V):         20211204-082213-a66c61ee
Latest version according to wezterm:  20211204-082213-a66c61ee9
```

This is also been reported to downstream: https://bugs.archlinux.org/task/72923

### To Reproduce

1- Install [wezterm 20211204.082213.a66c61ee9-1](https://archlinux.org/packages/community/x86_64/wezterm/)
2- Run `wezterm`.
3- See the message.

![output_20211205T222142](https://user-images.githubusercontent.com/24392180/144760480-5280c848-3f28-4f96-9bec-718036fe61b7.png)

### Configuration

No config

### Expected Behavior

No "Update Available" message on startup.

### Logs

```
INFO wezterm_gui::update > latest release 20211204-082213-a66c61ee9 is newer than current build 20211204-082213-a66c61ee
```

### Anything else?

Although I tried building with `pkgver=20211204.082213.a66c61ee`, I am not sure if this is a packaging problem or not. So I appreciate your input on this.

**Comment by krestaino** [comment]
Experiencing the same issue on macOS with the latest `wezterm 20211204-082213-a66c61ee` build.

**Comment by wez** [comment]
I think this is a mismatch in git configurations between where I created the tag and where the version name is computed elsewhere in code.

I'll take a look at fixing this up for the next release.

Meanwhile, I've renamed the latest release to remove the trailing `9`; let's see if that makes things happier!

**Comment by onkoe** [comment]
Also experiencing this on Arch. Hope you can get it fixed; it's been taking three lines of blank, empty goodness from me :(

**Comment by mkpankov** [comment]
As of right now, AppImage still exhibits this bug. Is it expected to be rebuilt at this time?

**Comment by wez** [comment]
This should be resolved now; closing out!
