### ISSUE TITLE
invalid utf-8 symbols

### ISSUE THREAD

**Issue by erf** [wez/wezterm#137]
## Describe the bug

Some utf-8 symbols show up as invalid characters or codepoints in the terminal, instead of the expected symbols. Also some characters messes up the order / input of the terminal. 

## Environment (please complete the following information):

 - macOS Catalina 10.15.2 (19C57)
 - Frontend:  OpenGL ( i think )
 - Version: wezterm 20200113-222147-724ad3a-132-gbd179fa

### Case 1

1. open wezterm
2. enter `ø`

### Case 2

1. open wezterm
2. paste in `Σὲ γνωρίζω ἀπὸ τὴν κόψη`

## Configuration

Empty `wezterm.toml`

### Case 1
I would expect `ø` to show up. 

Instead `�ø` shows up, and if i try to delete the characters, the cursors just steps over the characters to the left.

### Case 2

I would expect `Σὲ γνωρίζω ἀπὸ τὴν κόψη` to show up.

Instead the following code points show up:
` Σὲ γν�0089>�0081>ίζ�0089> �0080>�0080>ὸ �0084>ὴν κ�008c>�0088>η`

This also happen with other characters i copy from [here](https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html)

**Comment by wez** [comment]
I cannot reproduce this when I run `wezterm -n` (which skips my local config and uses the defaults) and copy and paste your example text from this github page and into the terminal.

I wonder if this might be related to your shell/environment, as I've seen zsh get upset when pasting new emoji that it doesn't understand, but for which the terminal is passing the correct sequences.

Please run and share the output from the following commands:

```
echo $SHELL
env
```

From the environment, the most significant variables are these; here are my lang related environment variables:

```
LANG=en_US.UTF-8
LC_COLLATE=C
```

**Comment by erf** [comment]
```
SHELL=/bin/zsh
LC_CTYPE=UTF-8
```
`LANG` and `LC_COLLATE` are not set

**Comment by wez** [comment]
I've written up some information here:
https://wezfurlong.org/wezterm/faq.html#some-glyphs-look-messed-up-why-is-that
The TL;DR is that there isn't a font with that glyph in your current set of fallback fonts.  If you can identify which font has that glyph you can add it to the fallback list as mentioned [in that page](https://wezfurlong.org/wezterm/faq.html#fonts-and-fallback).
Please let me know which font it is so that I can see about adding it to our default fallback list!

**Comment by erf** [comment]
Thanks for the writeup. I manage to paste in `«` in the terminal, but i still get a question mark for the `«` character inside `vis`. Not sure what is shappening there. I don't set a font in wezterm.toml. But i'm fine with closing this now.
