### ISSUE TITLE
window_padding broken in new release (20211204-082213-a66c61ee)

### ISSUE THREAD

**Issue by azzamsa** [wez/wezterm#1370]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211204-082213-a66c61ee-Ubuntu18.04.

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Upgrading to `wezterm 20211204-082213-a66c61ee` from `wezterm 20210814-124438-54e29167` breaks `window_padding`

![image](https://user-images.githubusercontent.com/17734314/144801318-1c821dad-ba37-4695-97fd-de59906d153f.png)

- in the left: `wezterm 20210814-124438-54e29167`
- in the middle: `wezterm 20211204-082213-a66c61ee`
- in the right: my config:

``` lua
	-- Padding
	window_padding = { left = 10, right = 10, top = 50, bottom = 10 },
```

### To Reproduce

1. run both mentioned version with the same `window_padding` config.

### Configuration

```lua
-- Padding
	window_padding = { left = 10, right = 10, top = 50, bottom = 10 },
```

### Expected Behavior

1. new version should change the top window padding to `50`.

### Logs

no log.

### Anything else?

The tab bar title also changed in the new mentioned release. I will open a separate issue.

**Comment by permelin** [comment]
I consider the new way of placing tabs to be a big improvement and not a bug. In the best of worlds, tabs would have configurable margins, separate from window padding.

**Comment by wez** [comment]
This was an intentional change as part of the journey towards the "fancy" tab bar that is being tracked by https://github.com/wez/wezterm/issues/1180

The tabs are aligned to either the top or bottom edge of the window, and don't use the window padding.

**Comment by azzamsa** [comment]
Oh, Is this basically means that the tab bar will use the OS feature for drawing window decoration? Similar to Maximize, Minimize, and close bottom on each application?

Any reason for this. I can't find the concrete reason/goals in the related issue. I mean, Isn't the current tab bar is useful enough? And the fancy version will took a lot of effort to implement?

**Comment by wez** [comment]
The intent is to look "more native" than terminal cells, rather than to try to look 100% native based on the OS.  Breaking it out of the original "piggy back on the terminal cell display" approach allows for proportional fonts and thus a more compact display, and things like dragging to re-order tabs, and per-tab close UI and so on.

You can try it by setting `use_fancy_tab_bar = true` in your config, but note that it is incomplete and documentation on setting up the color scheme hasn't been written yet.

**Comment by azzamsa** [comment]
Closed, as this is the expected behavior https://github.com/wez/wezterm/issues/1370#issuecomment-989939291
