### ISSUE TITLE
format-tab-title breaks in new release `wezterm 20211204-082213-a66c61ee`

### ISSUE THREAD

**Issue by azzamsa** [wez/wezterm#1371]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20211204-082213-a66c61ee

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The `format-tab-title` breaks in the new mentioned release. 

In the new release (in the middle). The `solid right arrow is not shown`. Compare it to the left side.

![image](https://user-images.githubusercontent.com/17734314/144802211-e19f155f-fe5f-451f-bdfc-7dd6bdacc73b.png)

- in the left: `wezterm 20210814-124438-54e29167`
- in the middle: `wezterm 20211204-082213-a66c61ee`
- in the right: my config:

``` lua
-- The filled in variant of the < symbol
local SOLID_LEFT_ARROW = utf8.char(0xe0b2)
-- The filled in variant of the > symbol
local SOLID_RIGHT_ARROW = utf8.char(0xe0b0)

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
   -- omitted for brevity
	return {
		{ Background = { Color = edge_background } },
		{ Foreground = { Color = edge_foreground } },
		{ Text = SOLID_LEFT_ARROW },
		{ Background = { Color = background } },
		{ Foreground = { Color = foreground } },
		{ Text = title },
		{ Background = { Color = edge_background } },
		{ Foreground = { Color = edge_foreground } },
		{ Text = SOLID_RIGHT_ARROW },
	}
end)

```

### To Reproduce

Install the mentioned release than play with the config below:

```lua
wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
	local edge_background = COLOR0
	local background = COLOR2
	local foreground = COLOR3

	return {
		{ Background = { Color = edge_background } },
		{ Foreground = { Color = edge_foreground } },
		{ Text = " AAA" },
		{ Background = { Color = background } },
		{ Foreground = { Color = foreground } },
		{ Text = title },
		{ Background = { Color = edge_background } },
		{ Foreground = { Color = edge_foreground } },
		{ Text = "BBB " },
	}
end)
```

The `AAA` part will displayed correctly in the left side (three A), but only two B displayed in the right side.

![image](https://user-images.githubusercontent.com/17734314/144803327-b7868cdf-35e2-4033-8529-73ce7c6605c9.png)

This why if we only have one character such `SOLID_RIGHT_ARROW`. It will not be displayed. The work around is to add any invisible character before it. Such `" ".."BBB " `. But indeed it breaks the old version.

![image](https://user-images.githubusercontent.com/17734314/144803578-b8dedad1-90b2-4b40-8642-487d9d23a2cf.png)

### Configuration

```lua
wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
	local edge_background = "red"
	local background = COLOR2
	local foreground = COLOR3
	local edge_foreground = background
	local title = tab.active_pane.title
	return {
		{ Background = { Color = edge_background } },
		{ Foreground = { Color = edge_foreground } },
		{ Text = " AAA" },
		{ Background = { Color = background } },
		{ Foreground = { Color = foreground } },
		{ Text = title },
		{ Background = { Color = edge_background } },
		{ Foreground = { Color = edge_foreground } },
		{ Text = " ".."BBB " },
	}
end)
```

### Expected Behavior

It should display the character correctly.

**Comment by wez** [comment]
Thanks for the clear report!
I've pushed a fix for this; nightly binaries should be available to download for linux in ~20 minutes from now, but may take up to an hour.

**Comment by azzamsa** [comment]
Works well in the nightly release.

Thanks for Wezterm, Wez.
