### ISSUE TITLE
Colors dim when started from RDP

### ISSUE THREAD

**Issue by jdknezek** [wez/wezterm#1373]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20211205-192649-672c1cc1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

From Windows machine to Windows machine over TeamViewer, when starting a new wezterm window colors are represented correctly as they have been in the past. With the latest release & nightly, when connected to & from the same machine over RDP, the colors are instead represented with reduced brightness.

Looking at the logs it looks like a different graphics device is detected over RDP, whereas if the window is started outside of RDP and then the connection is switched to RDP it continues to function fine.

### To Reproduce

1. Start a wezterm window on a remote machine over TeamViewer using a configuration
2. Start a wezterm window on a remote machine over RDP using the same configuration
3. Compare colors

### Configuration

```lua
	force_reverse_video_cursor = true,
	color_scheme = 'hpluv',
	color_schemes = {
		hpluv = {
			background = '#1b1b1b',
			foreground = '#b9b9b9',
			ansi = {
				'#1b1b1b',
				'#a36572',
				'#5a814b',
				'#8d7343',
				'#517b9e',
				'#92689b',
				'#05867c',
				'#b9b9b9',
			},
			brights = {
				'#777777',
				'#fb9fb1',
				'#8dc877',
				'#d9b36b',
				'#80bff4',
				'#e1a3ee',
				'#0ccfc0',
				'#e2e2e2',
			},
		},
	},
```

### Logs

TeamViewer:
```
09:39:16.533 INFO wezterm_mux_server_impl::local > setting up C:\Users\jonathan.knezek\.local/share/wezterm\gui-sock-17028
09:39:17.258 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(9001))
09:39:17.287 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
09:39:17.821 INFO wezterm_gui::termwindow > OpenGL initialized! Quadro M1000M/PCIe/SSE2 4.5.0 NVIDIA 471.41 is_context_loss_possible=true wezterm version: 20211205-192649-672c1cc1
```

RDP:
```
09:48:43.327 INFO wezterm_mux_server_impl::local > setting up C:\Users\jonathan.knezek\.local/share/wezterm\gui-sock-20880
09:48:44.006 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(9001))
09:48:44.019 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
09:48:44.096 ERROR window::os::windows::wgl > failed to created extended OpenGL context (ChoosePixelFormatARB returned 0 formats), fall back to basic
09:48:44.132 INFO wezterm_gui::termwindow > OpenGL initialized! llvmpipe (LLVM 8.0, 256 bits) 3.1 Mesa 20.1.8 is_context_loss_possible=false wezterm version: 20211205-192649-672c1cc1
```

### Anything else?

TeamViewer: 
![image](https://user-images.githubusercontent.com/1338/144877580-1ec32371-276a-4235-83b8-167d4a4f7558.png)

RDP:
![image](https://user-images.githubusercontent.com/1338/144877613-8c93c391-078f-4106-ae40-268c6b1979d3.png)

**Comment by wez** [comment]
When running in an RDP session on Windows, wezterm forces the use of Mesa's software rasterizer to workaround some issues with GPU emulation in RDP sessions (https://github.com/wez/wezterm/issues/265)

If you manually start `wezterm --config "front_end='Software'"` in the TeamViewer (or natively), do you see the same brightness as RDP?  If so, that suggests that there might be an issue with Mesa and Dual Source Blending on Windows

**Comment by jdknezek** [comment]
Yes, with `--config "front_end='Software'"` the colors are the same as over RDP.

![image](https://user-images.githubusercontent.com/1338/145241169-1da5349d-b79c-4a5d-8b5e-da2c47393d3d.png)

```
09:59:07.988 INFO wezterm_mux_server_impl::local > setting up C:\Users\jonathan.knezek\.local/share/wezterm\gui-sock-2200
09:59:08.769 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(9001))
09:59:08.802 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
09:59:08.972 ERROR window::os::windows::wgl > failed to created extended OpenGL context (ChoosePixelFormatARB returned 0 formats), fall back to basic
09:59:09.013 INFO wezterm_gui::termwindow > OpenGL initialized! llvmpipe (LLVM 8.0, 256 bits) 3.1 Mesa 20.1.8 is_context_loss_possible=false wezterm version: 20211205-192649-672c1cc1
```

**Comment by wez** [comment]
Related to https://github.com/wez/wezterm/issues/544 and (somewhat ironically, given that this is darker and that one is about being brighter) to https://github.com/wez/wezterm/issues/1025

**Comment by olaf-rogalsky** [comment]
I can confirm this bug. In addition, I can't change the cursor color: It is always green, no matter which value I assign to the "cursor_color" config option.

**Comment by wez** [comment]
I believe this to be fixed in the latest nightly build; please give it a try and let me know how it goes!

**Comment by olaf-rogalsky** [comment]
Thanks you so much! For me the nightly build fixes the bug.
