### ISSUE TITLE
Build available via winget is out of date

### ISSUE THREAD

**Issue by ahupp** [wez/wezterm#1384]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The wezterm build available via winget is several months out of date:

```
C:\Users\adam>winget search wezterm
Name    Id          Version                  Source
----------------------------------------------------
WezTerm wez.wezterm 20210814-124438-54e29167 winget

```

### Configuration

no config

### Expected Behavior

I get the current build.

**Comment by wez** [comment]
I'm not responsible for that... Looks like @Trenly added it in https://github.com/microsoft/winget-pkgs/pull/34193
and maybe they'd be gracious enough to update for the latest release?

**Comment by Trenly** [comment]
@vedantmgoyal2009

**Comment by ahupp** [comment]
Since winget appears to be the "official" package manager of Windows, it would be nice if this was supported by wezterm directly, e.g. via publishing from CI.

**Comment by Trenly** [comment]
> Since winget appears to be the "official" package manager of Windows, it would be nice if this was supported by wezterm directly, e.g. via publishing from CI.

Winget is still fairly new, and I don’t believe there are many tools for integration with CI/CD pipelines yet. It is possible and I know that others have done it, but I tagged @vedantmgoyal2009 to see if he can add it to [winget-pkgs-automation](/vedantmgoyal2009/winget-pkgs-automation), which periodically can scan repositories for new releases and submit updates automatically

**Comment by wez** [comment]
I'm open to automating this, but I'm not sure how to produce the PR; if there's a tool that can spit out those yaml blobs, I think we can use https://cli.github.com/manual/gh_pr_create in the tag workflow

**Comment by Trenly** [comment]
> I'm open to automating this, but I'm not sure how to produce the PR; if there's a tool that can spit out those yaml blobs, I think we can use https://cli.github.com/manual/gh_pr_create in the tag workflow

I use the YamlCreate powershell script from winget-pkgs, and I know that vedant’s repo does too.

I believe @JanDeDobbeleer has implented automation for [oh my posh](/JanDeDobbeleer/oh-my-posh)

**Comment by wez** [comment]
the oh my posh bits seem fairly well contained in: https://github.com/JanDeDobbeleer/oh-my-posh/tree/main/packages/winget

**Comment by Trenly** [comment]
> the oh my posh bits seem fairly well contained in: https://github.com/JanDeDobbeleer/oh-my-posh/tree/main/packages/winget

Seems like thats correct; I will note though that having the files static like that means it won’t keep up to date with the latest manifest changes in winget

**Comment by Trenly** [comment]
Added the automation so when new releases are pushed, it should be caught within 2 hours
* https://github.com/vedantmgoyal2009/winget-pkgs-automation/pull/214

**Comment by wez** [comment]
Thanks!

What's the recommended way to install and upgrade using winget? I'd like to put that info in our docs

**Comment by Trenly** [comment]
> Thanks!
> 
> What's the recommended way to install and upgrade using winget? I'd like to put that info in our docs

`winget install wez.wezterm`
and
`winget upgrade wez.wezterm`

**Comment by wez** [comment]
I'm trying to find clear info on installing winget itself and failing... https://docs.microsoft.com/en-us/windows/package-manager/winget/#production-recommended links to a thing that talks about sideloading "My Employees".
Other things suggest installing a release from github :-/

**Comment by wez** [comment]
It sounds like https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1?activetab=pivot:overviewtab is the thing that installs `winget`, but that page does a terrible job at making that clear :-)

**Comment by Trenly** [comment]
It is included wuth that package if I’m not mistaken

https://github.com/microsoft/winget-cli#installing-the-client

**Comment by vedantmgoyal2009** [comment]
Thanks @Trenly for creating the PR. I am quite busy these days so I didn't notice that you've mentioned me two times. Will be free after 15 December and then will take a look at what has been going on at WinGet and other things.

**Comment by Trenly** [comment]
Not sure if you're still looking for additional documentation, but I did get a chance to look at the dev blogs and found one on winget - https://devblogs.microsoft.com/commandline/windows-package-manager-1-1

Other than that, I think this issue can be closed?

**Comment by JanDeDobbeleer** [comment]
> Seems like thats correct; I will note though that having the files static like that means it won’t keep up to date with the latest manifest changes in winget

@Trenly yes, but that shouldn't change as often. I do the same for scoop, Powershell and Homebrew and I haven't had to touch it for 1.5 years. Winget is the only one that keeps changing the manifest. But, they have a PR workflow so they can alert you if needed (which they do). I'd rather be in control of my own CD pipeline rather than rely on a third party solution (no offence @vedantmgoyal2009).

**Comment by ahupp** [comment]
> @wez I'm trying to find clear info on installing winget itself and failing.

It's installed by default with recent versions of windows

**Comment by wez** [comment]
Let's call this done!
