### ISSUE TITLE
Cannot paste when copied before opening wezterm (Wayland-specific?)

### ISSUE THREAD

**Issue by Funami580** [wez/wezterm#1385]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20211205-192649-672c1cc1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Cannot paste when copied before opening wezterm.

### To Reproduce

My guess is that it is Wayland-specific.
1. Copy something
2. Open wezterm after copying
3. Try to paste
4. Not working, nothing gets pasted
5. Copy it again, with wezterm open
6. Now pasting works

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  enable_wayland = true,
}
```

### Expected Behavior

Pasting works.

### Logs

When I try to paste the text, nothing new appears in the logs. Here are the startup messages, though:
```
19:17:15.301 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-16303
19:17:15.347 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa DRI Intel(R)HD Graphics 4600 (HSW GT2) 3.0 Mesa 21.2.5 is_context_loss_possible=false weztermversion: 20211205-192649-672c1cc1
```

### Anything else?

- I don't know if it's important, but I'm using a clipboard manager.
- When I execute `wl-paste`, it correctly prints the copied text.
- The problem doesn't occur with other applications.

**Comment by VarLad** [comment]
I'm getting the same issue as well

**Comment by pshanoop** [comment]
I'm facing the same issue, 
Another issue on `wayland`. Paste by mouse middle button also breaks. 

### To Reproduce
1. Select test from other program 
2. Try pasting using mouse middle button

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
