### ISSUE TITLE
Selection via shift off by one

### ISSUE THREAD

**Issue by Funami580** [wez/wezterm#1386]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20211205-192649-672c1cc1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When you use shift+mouse to select some text, the selection includes one character at the end too much. Whether you select the end or the start of the selection first, doesn't matter. It is always the end position where it happens.

### To Reproduce

1. Click between to characters
2. Press and hold shift
3. Move your mouse cursor to another position and click between two characters again
4. Release shift

### Configuration

No config.

### Expected Behavior

Selection ends where I clicked.

### Logs

Only startup logs:
```
 2021-12-09T18:53:57.488Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-1660
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/glium/glium/issues
 2021-12-09T18:53:57.552Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2) 3.0 Mesa 21.2.5 is_context_loss_possible=false wezterm version: 20211205-192649-672c1cc1
```

### Anything else?

N/A

**Comment by bew** [comment]
Is your problem the same as #1199 ?

**Comment by Funami580** [comment]
I'm not sure, but I think it is likely. The issue you linked described the issue with dragging the mouse, mine includes only clicking the position. But it is perfectly possible that these 2 issues originate from the same problem.
