### ISSUE TITLE
Some key bindings with SHIFT key don't work

### ISSUE THREAD

**Issue by nickjer** [wez/wezterm#1391]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20211211-233530-c885e5a6

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am attempting to run the key bindings [documented here](https://wezfurlong.org/wezterm/config/keys.html#default-shortcut--key-binding-assignments) for creating horizontal and vertical split.

So I attempt to press `CTRL+SHIFT+ALT+"` (split vertical) and/or `CTRL+SHIFT+ALT+%` (split horizontal). Unfortunately it seems since I use a US-layout keyboard that `SHIFT+'` is equivalent to `"`, so it is impossible to actually type `CTRL+SHIFT+ALT+"` as it swallows the `SHIFT` key.

I did eventually swap `CTRL+SHIFT+ALT+"` with `CTRL+ALT+"` and `CTRL+SHIFT+ALT+%` with `CTRL+ALT+%` and confirmed it worked, see below...

```lua
local wezterm = require 'wezterm';

return {
  keys = {
    {key="\"", mods="CTRL|ALT",
      action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
    {key="%", mods="CTRL|ALT",
      action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
  }
}
```

NOTE: On my computer the above config actually does the opposite of what I'd expect where `SplitVertical` is actually making a horizontal split and vice-versa (but one problem at a time).

### To Reproduce

Using a US-layout keyboard attempt to run the documented key binding to split your panes `CTRL+SHIFT+ALT+"` and `CTRL+SHIFT+ALT+%` and confirm nothing happens.

### Configuration

No config

### Expected Behavior

I expect a vertical and/or horizontal split pane to appear.

### Anything else?

The same happens when attempting to activate other tabs, e.g., `CTRL+SHIFT+1` (ActivateTab=0).

**Comment by nickjer** [comment]
I can confirm the key bindings do work in `wezterm 20211211-233530-c885e5a6` but stopped working in the following release `wezterm 20211211-233530-c885e5a6`.

My guess is that this is the offending commit: https://github.com/wez/wezterm/commit/61c52af491c24dc1a4beca920430b65556f618a5

**Comment by aca** [comment]
```
return {
  leader = { key=" ", mods="CTRL", timeout_milliseconds=100000 },
  keys = {
    {key="%", mods="LEADER", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    {key="5", mods="LEADER|SHIFT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    {key="5", mods="LEADER", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
  }
}
```

This mapping through replace tmux doesn't work. `ctrl-space %` 
Only last one with `ctrl-space 5` works fine.

**Comment by wez** [comment]
Please take a look at https://github.com/wez/wezterm/issues/1483 to understand the changes that have been made in nightly, and what you might need to do to your configuration to get things working!
