### ISSUE TITLE
Borderless mode

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1397]
**Is your feature request related to a problem? Please describe.**

I view the default window __title bar__ with min/max/close buttons useless, I use way more convenient keyboard/mouse combinations that don't lock me into those tiny :) buttons
Similarly, the window __resize border__ (the one that changes the mouse cursor on hover into a resize cursor) is useless as there is a more convenient way to resize without having to place your mouse at the exact border location, which is harder, but, say, anywhere in the right 20% width of the window (with <kbd>Win</kbd>), which is much easier and never triggers accidentally (and to move a window you can have the full window size to click on instead of just a tiny titlebar)

**Describe the solution you'd like**

I'd like WezTerm to add an option to hide both window's resize border and window's title bar

**Describe alternatives you've considered**

(on Windows) Currently I achieve the same via AutoHotkey by applying the following two styles

```
WS_Caption   	:= 0x00C00000 ; Title bar (WS_BORDER + WS_DLGFRAME)
WS_SizeBox   	:= 0x00040000 ; Sizing border (=WS_THICKFRAME)
WS_Borderless	:= WS_Caption|WS_SizeBox ; BitwiseOR (logical inclusive OR)
```

However, it's a bit worse than having a native solution as there are some scripting config frictions involved and the titlebar still flashes on launch before it's removed
Also, it's not a cross-platform solution, on a macOS I don't even know of a way for a user to achieve this (suggestions are welcome!)

**Additional context**

Current state with resize borders and a title bar
<img width="254" alt="1WezBorders" src="https://user-images.githubusercontent.com/12956286/145955133-e1bff510-d504-4042-9e03-8101fa18f42a.png">

Future state without that junk :)
(note that mouse cursor doesn't change into a resize cursor)

<img width="270" alt="2WezBorderless" src="https://user-images.githubusercontent.com/12956286/145955137-a475f581-4219-4401-bfbc-5ed939c0413e.png">

**Comment by Mattwmaster58** [comment]
Wow, what a coincidence, I was just about to write this issue, but from a slightly different perspective. IMO, the way Windows Terminal handles the title bar would be ideal:
![image](https://user-images.githubusercontent.com/26337069/145982438-f0b6206e-59b0-4bdf-b47a-f40757366137.png)

**Comment by eugenesvk** [comment]
> way Windows Terminal handles the title bar would be ideal:

nah, it's also poor design (besides the issues with the original title bar I mentioned in the original issue) the space waste above/to the left of the tab makes no sense — it doesn't help with visibility and just reduces the useful area (especially in the more precious vertical dimension) you can click on to select a tab. At least in the fullscreen mode the top padding disappears, though the left still remains for some mysterious reason :)

In this sense Wez does it better — after it gets rid of the title bar — it will have no wasted whitespace in its tab bar (just some styling issues making the tabs' visibility poor, but that's something a theme could fix)

**Comment by bew** [comment]
Did you try to configure `window_decorations` to `NONE` or `RESIZE` ? 
Doc: https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html

**Comment by eugenesvk** [comment]
> Did you try to configure `window_decorations` to `NONE` or `RESIZE` ?

Oops, thanks a lot! It even mentions the lovely AltDrag!
I've searched both issues and docs for 'borderless', but not for the proper terms that would've allowed me to find it!

(in general, I've left a comment in the documentation issue https://github.com/wez/wezterm/issues/548 that detailed example configs would be very helpful as currently there are just way too many separate pages to click through in the docs, though, granted, in this specific case I should've searched more)

**Comment by AnazThaj** [comment]
Hi, is there a way I could set the dimensions for the borderless mode so it fits my screen? Or native full screen mode without taking a separate window (in macOS)?

**Comment by wez** [comment]
Please file a separate issue if you have questions or something isn't working; this issue is closed.
