### ISSUE TITLE
Terrible window move/resize performance with Divvy

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1398]
**Update:** **workaround** for AltDrag: use its updated fork called [AltSnap](https://github.com/RamonUnch/AltSnap/releases), it takes a bit of time to start dragging/resizing, but after that it's responsive

### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20211213-091602-1f958fa1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm using AltDrag or Divvy to manage window's size/position and for some reason they both are extremely slow with WezTerm's window
For example, if I invoke Divvy and select window's size, WezTerm might respond in ~10 seconds while any other window would respond instantly

### To Reproduce

Install either Divvy and try to use it to resize WezTerm's window

### Configuration

Tried with an emtpy config

### Expected Behavior

Just like with any other window, the resize events should be handled ~immediately

### Logs

15:54:19.795 INFO wezterm_mux_server_impl::local > setting up C:\Users\usr\.local/share/wezterm\gui-sock-15724
15:54:19.850 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(9001))
15:54:19.868 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
15:54:20.028 INFO wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GTX 750/PCIe/SSE2 4.5.0 NVIDIA 471.11 is_context_loss_possible=true wezterm version: 20211213-091602-1f958fa1

**Comment by wez** [comment]
See also: https://github.com/wez/wezterm/issues/1013

**Comment by eugenesvk** [comment]
Thanks, in AltDrag case it's a duplicate, but I'm more worried about Divvy as that's the unique app that allows me to move a window to a pre-set size&position quickly (at least WezTerm is awesome enough to be able to replace AltDrag's functionality)

Also, after some more investigation, I've found that the newly maintained fork of AltDrag called [AltSnap](https://github.com/RamonUnch/AltSnap/releases) (didn't realize that on this machine I was still using the old version) actually behaves more or less fine with resizing&dragging with Wez (it's not immediate like in all other windows, but he delay is sub-second, so not that big of a deal)

Now, I don't know how Divvy behaves, maybe it's also doing some deep hook-thing or something like you mentioned in the other issue and that breaks with Wez (but nothing else) for some reason

**Comment by wez** [comment]
Are you talking about https://mizage.com/windivvy/ ?

**Comment by eugenesvk** [comment]
Yes, that's the one

**Comment by mborejdo** [comment]
I am also experiencing a small wezterm-window lag. It is indeed better with AltSnap, but still feels like a regression, as dragging the wezterm window was super smooth some time ago (even with AltDrag). I also notice a a lag using https://github.com/tarkah/grout

**Comment by wez** [comment]
FWIW, I have low motivation to look into divvy specifically: it's closed source and likely doing something naughty in any case

**Comment by eugenesvk** [comment]
> FWIW, I have low motivation to look into divvy specifically: it's closed source and likely doing something naughty in any case

Well, the https://github.com/tarkah/grout app is not only open source, but also from a fellow 🦀rustacean🦀, and WezTerm still bugs with it :(. And if they did do something naughty, wouldn't that also manifest in other apps? So far WezTerm is unfortunately unique in this regard, all other apps seem to be reacting fine to this class of window managers (AltDrag/Snap,Divvy,Grout)

**Comment by wez** [comment]
I fixed a wait function that improves latency when other apps post messages; I'm assuming that was the root cause for this.
Please give it a try and let me know!

**Comment by eugenesvk** [comment]
Gave it a try and letting you know that it seems to be working just fine (AltSnap, Grout; and even the old AltDrag seems to be working fine), thanks a bunch, can finally get use WezTerm in a fully borderless mode without worrying about being unable to move/resize it!
