### ISSUE TITLE
New Version Update Notification Appears Once Per Running Executable (And It's hard to dismiss)

### ISSUE THREAD

**Issue by dashdsrdash** [wez/wezterm#1402]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211213-090224-36a16cb7

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In the morning, every wezterm I have running has popped an update notification toast. Unlike normal notifications, it doesn't go away by itself and it doesn't close when I click on it, or on the close button, until I've clicked 3-5 times per notification.

### To Reproduce

Run multiple wezterm invocations and leave them running overnight.

### Configuration

It would be nice if there was a config to turn this off.

### Expected Behavior

Either:
one notification per new upstream release, regardless of how many wezterms are running

or

a config to not check for upstream releases. Let me subscribe to a release list, please.

**Comment by bew** [comment]
> a config to not check for upstream releases. Let me subscribe to a release list, please.

You can disable the checks with https://wezfurlong.org/wezterm/config/lua/config/check_for_updates.html
And you can subscribe to the releases of the project on Github :)

**Comment by dashdsrdash** [comment]
Peachy, thank you.

**Comment by dashdsrdash** [comment]
Well, that wasn't it.  Either I misconfigured check_for_updates:

 check_for_updates = false,

or it's a bug. 

The good news is that the eleventeen notifications popping up now properly close with one click apiece. The bad news is, there' still one of them per wezterm process per day elapsed since update.

**Comment by wez** [comment]
There were a couple of bugs:

1) There was no coordination between multiple wezterm-gui processes, so if you had multiple running (which is more common in certain Linux configurations than it is on other platforms), then they'd all assume that they needed to show the toast notification
2) The configuration to control update checking didn't respect reloading the configuration, so the values were considered only at process startup

I've pushed commits to address both of these issues; now only the eldest wezterm-gui process will show an update notification, and regardless: the configuration handling now respects changes to the config file.
