### ISSUE TITLE
consider enabling kitty graphics support by default

### ISSUE THREAD

**Issue by dankamongmen** [wez/wezterm#1406]
**Is your feature request related to a problem? Please describe.**
Currently, WezTerm requires `enable_kitty_graphics = true` to drive Kitty graphics. They are not enabled by default, despite use of Kitty graphics being.a fundamentally opt-in activity.

**Describe the solution you'd like**
I've probably driven more kitty+sixel graphics through WezTerm than anyone else in the world, and have had nothing but success with the former, despite it being a recent (and quickly accomplished!) implementation. Sixel has been less rewarding in WezTerm, and similarly forces some pessimizing in Notcurses. I don't doubt that the more regular design of Kitty bitmaps will lead to fewer bugs per feature in WezTerm's implementation thereof.

I think that Kitty graphics ought thus be enabled by default, especially so long as you continue advertising support for Sixel (and thus disturb no existing client code).

**Describe alternatives you've considered**
* Notcurses could detect that it's running in an acceptably recent WezTerm but without kitty support, and scroll a line at the bottom of the screen reading "only you can overcome @wez's cowardice" along with your physical address
* Notcurses could vomit kitty graphics anyway in an antifasque show of productive defiance
* Notcurses could rewrite the client's wezterm config because no one containerizes safely for the same reason half of eighteenth century europe was syphilitic, and send it SIGHUP
* if all else fails, continue using sixel

**Additional context**

![2021-12-15-175616_902x649_scrot](https://user-images.githubusercontent.com/143473/146277600-fbdccadb-5e60-4fb4-9f16-9db67282289a.png)

**Comment by klamonte** [comment]
This could be an opportunity to either document (if it exists), or just say screw it and make your own, a way to advertise kitty graphics support (and ONLY this feature) at whatever version of the protocol wezterm supports right now.  Maybe a flag in DA1, right next to sixel, and then applications can pick whatever they want?

**Comment by wez** [comment]
I'm cool with turning it on by default if you're satisfied that it's working well enough. I know we have #1156 open and I haven't had a chance to dive into that yet.  If you're happy that this wouldn't break things for notcurses users, I'm happy to flip the option to default to on!

**Comment by dankamongmen** [comment]
@klamonte we miss you on twitter! to those who're unaware, this gal's a national treasure

**Comment by dankamongmen** [comment]
@wez yes. my experience has been that your kitty implementation is flawless, and that your sixel implementation is not quite there.

**Comment by wez** [comment]
OK: we now default to enabled!

**Comment by dankamongmen** [comment]
note that with this change, notcurses will pretty much cease to be a tester/validator of your sixel implementation, so if you've been using it in that capacity, you'll want to find something else. the moment you start responding to those kitty APCs, that's all i'll be using.
