### ISSUE TITLE
Add more thorough check in skip_close_confirmation_for_processes_named for Xonsh

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1412]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20211205-192649-672c1cc1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`skip_close_confirmation_for_processes_named` doesn't work for `xonsh.exe` most likely due to the fact  that `xonsh.exe` spawns a `python.exe` process since it's a python-based shell

### To Reproduce

- Install [xonsh](https://github.com/xonsh/xonsh) in a virtual python environment (though not sure whether the install method matters)
- replace your `wezterm.lua` config with
```lua
local wezterm = require("wezterm")

return {
  default_prog = {"C:/path/to/xonsh.exe"},
  skip_close_confirmation_for_processes_named = {
    "xonsh.exe"    	, -- fails
    -- "python.exe"	, -- works with this enabled since xonsh process looks like this:
      -- "xonsh.exe" →
        -- → python.exe →
          -- → python.exe
  }
}
```
- Launch xonsh in wezterm and try to close a tab. It spawns a confirmation window
- Uncomment the "python.exe" line in the config above and try it again. Now it closes without a confirmation

### Configuration

```lua
local wezterm = require("wezterm")

return {
  default_prog = {"C:/path/to/xonsh.exe"},
  skip_close_confirmation_for_processes_named = {
    "xonsh.exe"    	, -- fails
    -- "python.exe"	, -- works with this enabled since xonsh process looks like this:
      -- "xonsh.exe" →
        -- → python.exe →
          -- → python.exe
  }
}
```

### Expected Behavior

I'd expect wezterm to treat this sequence of child processes `xonsh.exe → python.exe → python.exe` as one for the purposes of `skip_close_confirmation_for_processes_named` and close xonsh without confirmation
However, were it to spawn any additional python or whatever processes, then the confirmation rule should break just like it would for other shells spawning some long-running python process

**Comment by wez** [comment]
This isn't a bug: the feature is working as documented.

There isn't a sane way for wezterm to know whether a given `python.exe` is something you're happy killing without prompting you, and building in more complex heuristics that inspect process trees is baking in implementation details for other software that will be brittle in the face of changes in that software over time; I don't really want to make this more complex than it already is.

**Comment by eugenesvk** [comment]
Ok, understood.
Would an alternative optional config `count` (# of spawned processes) allow to both avoid building and parsing the full process tree and at the same time work for slightly more complicated shell architectures? For example, if instead of `"xonsh.exe"` you'd pass `{"xonsh.exe", 2}` and then when you get the list of spawned processes you'd:
- only compare the name to that of the top process
- for the spawned processes only compare their number `length of proc_list ≤ 2`
 
and then if both match, close without confirmation?

Or is that also too complicated?

**Comment by wez** [comment]
The complexity I want to avoid as much as possible is knowledge of unusual third-party software implementation details that may change as they evolve.

I've pushed a commit that defines a new `mux-is-process-stateful` event that allows you to define a lua callback to decide using whatever policy you want.  The event receives a process object that corresponds to the spawned process, and through which you can walk its process sub-tree and make your decision.

You can find docs on this here:
https://wezfurlong.org/wezterm/config/lua/mux-events/mux-is-process-stateful.html

This will be available in the nightly download for Windows once https://github.com/wez/wezterm/actions/runs/1596419346 completes.
