### ISSUE TITLE
Make Launcher Menu items selectable with a single key

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1413]
**Is your feature request related to a problem? Please describe.**

Selection by arrows in a long list, in this case, a list of shells in a **Launcher Menu** is a bit cumbersome

**Describe the solution you'd like**

I'd prefer to be able to immediately pick an item with a single key:
  - either by pressing an "accelerator symbol" marked by `&` in the label:
    `&WSL default shell` would launch on `w`
    `WSL &zsh login shell` would launch on `z`
  - or pressing the label's first symbol
    `1 WSL default shell` would launch on `1`
    `2 WSL zsh login shell` would launch on `2`
  - or using both of these in an overkill combo of convenience

**Describe alternatives you've considered**

You can use a shortcut to immediately launch a shell you like, but that's best used for the most frequently used shell or two, then invoking the Launcher Menu and quick selection is better

**Additional context**

This would be similar to ConEmu's "Create new console popup menu" where you can __press numbers__ after invoking the menu to select an item ![ConEmu New Console](https://conemu.github.io/img/ConEmuStartTask.png)

**Comment by wez** [comment]
With the changes proposed in #1485 we'll essentially add fuzzy matching and frecency to the launcher functionality.
I suppose we could also allow selecting an item by number, although I personally find matching by typed name less mental overhead than reading and parsing numbers :)

I'm going to close this issue in favor of the other one so that we can concentrate discussion in one place.

**Comment by eugenesvk** [comment]
> fuzzy matching and frecency to the launcher functionality.

that wouldn't resolve the issue and would actually make it worse as the order will be constantly shifting, so harder to remember.
Currently in, e.g., Conemu, I'm 100% certain what shell I run and I can do it with just 1(!) key (after invoking the menu, for the most frequently used shells, for some rare configs it's still just 2 keys)

With fuzzy matching in general you're not fully certain what the match is upfront and have to read the results (though in this case I can add numbers to the names, so the match is certain), and then you have to press an extra key to confirm the match, so 1 guaranteed key that can be memorized for some frequent shells turns into at least 2+ keys and becomes harder to remember
