### ISSUE TITLE
Add nowrap option to ActivateTabRelative to stop at first/last tab

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1414]
**Is your feature request related to a problem? Please describe.**

I sometimes do off-by-one mistakes during quick previous/next tab navigation (`ActivateTabRelative=` `-1`/`1` ), and when these happen to be at the tab bar edges, they're more annoying since since the tab selection moves to a rather distant place (from last to first or vice versa)

**Describe the solution you'd like**

I'd prefer the `ActivateTabRelative` command to have a `NoWrap` argument so that off-by-one mistakes don't lead to "jumps" duringtab navigation

(also WezTerm is very fast in tab cycling, so it's rather easy to reach the first/last tabs by just holding `ActivateTabRelative=` `-1`/`1` commands, so the default wrapping option isn't even much faster)

**Describe alternatives you've considered**

There might be a way to create a lua function that checks current tab's position and if it's the first/last doesn't execute the move 1 tab left/right, though obviously a simple argument is much more convenient :)!

**Comment by wez** [comment]
Adding a parameter will be a bit of a headache for users when they upgrade, so I'm adding `ActivateTabRelativeNoWrap` instead.
