### ISSUE TITLE
Misrendering of weechats go.py bufferlist (potentially related to the \u2068 glyph)

### ISSUE THREAD

**Issue by noctux** [wez/wezterm#1422]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20211219-110753-48dd57ab

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using weechat's go.py plugin, the channel list (which should stay on a single line due to my setting `weechat.bar.input.size=1` ) bleeds onto a second line. If tmux is used, this means bleeding into tmux's status bar, which is definitely not intended. It does not happen for other terminal emulators (urxvt and xterm tested). It only happens for me when the signal.py plugin is loaded, which introduces "\u2068" into the displayed channelnames, so I think this is the source of the trouble.

Screenshot:
![2021-12-19-203137_1276x1401_scrot](https://user-images.githubusercontent.com/291559/146688827-2b99a29c-a6f4-4368-ac3d-7557c90f2d3a.png)

### To Reproduce

Initial setup of weechat:

Start weechat and enter:
```
/set script.scripts.download_enabled on
/script install go.py
/set weechat.bar.input.size 1
/save
/quit
```

Reproducing the actual rendering bug (restart weechat):
```
/python eval -o weechat.buffer_new("\u2068Sam Vimes", "", "", "", "")
/python eval -o weechat.buffer_new("\u2068Lord Vetenari", "", "", "", "")
/python eval -o weechat.buffer_new("\u2068Adora Bella Dearheart", "", "", "", "")
/python eval -o weechat.buffer_new("\u2068Captain Carrot", "", "", "", "")
/python eval -o weechat.buffer_new("\u2068C.M.O.T Dribbler", "", "", "", "")
/python eval -o weechat.buffer_new("\u2068Willikins", "", "", "", "")
/python eval -o weechat.buffer_new("\u2068Death", "", "", "", "")
/python eval -o weechat.buffer_new("\u2068Moist van Lipwig", "", "", "", "")
/python eval -o weechat.buffer_new("\u2068Susan Sto Helit", "", "", "", "")
/go
```

### Configuration

Default configuration (empty config file)

### Expected Behavior

The menu should stay on a single line and definitely not bleed into tmux's status bar.

### Logs

```
20:55:27.811 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
20:55:27.812 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
20:55:31.724 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
20:55:31.727 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
20:55:38.240 WARNING wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
20:55:38.244 WARNING mux::localpane > unknown DeviceControlMode::Enter EnterDeviceControlMode(params: [], intermediates: [],byte: 'z' 0x7a, ignored_extra_intermediates=false)
20:55:38.244 WARNING mux::localpane > unhandled DeviceControlMode::Data 7a z
20:55:38.244 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: "0%m"
20:56:54.012 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
20:56:54.012 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
20:57:22.957 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
```

### Anything else?

On Matrix, it was suggested that I attach a script log file:
[script.txt](https://github.com/wez/wezterm/files/7741515/script.txt)
 
It reproduces the issue for me, but only with a fitting window size (probably understandable, that it is drawing some ncurses application and we have issues with overflowing lines):
```
xwininfo: Window id: 0x3400003 "eve@bombus:~"

  Absolute upper-left X:  1282
  Absolute upper-left Y:  18
  Relative upper-left X:  2
  Relative upper-left Y:  0
  Width: 1276
  Height: 1401
  Depth: 32
  Visual: 0xd0
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x3400004 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +1282+18  -2+18  -2-21  +1282-21
  -geometry 1276x1401-0+18
```

Oh, and thanks for providing the terminal emulator in the first place! It's really nice in most other regards :D And thanks for taking the time to read this issue!

**Comment by wez** [comment]
Thanks for the script; it made it easier to understand!
Yes, the issue was due to U+2068, which is a unicode BIDI control.
The unicode segmentation routines would return that zero-width grapheme on its own, and it would render as a space.
I've pushed a commit to skip that class of grapheme and elide it from the terminal model.
This will likely come back to bite us in the future, but I think its good enough for now.

**Comment by noctux** [comment]
Thanks for the swift response, glad the script has helped. I've just built nightly (d25580d10) and can confirm that the issue is solved within weechat itself as well! Thanks for that nice christmas present :)

Just as a small sidenote, tho: When I select the relevant text within urxvt, the copyied text includes the U+2068, when I do select the same passage within wezterm, it's absent (understandable given that the current fix nore or less seems to filter and discard that grapheme altogether). It does not pose any problem to the current me, but maybe it is something to be aware of in the "might come back to bite us in the future"-category. I'm not sure whether it is worth pondering right now, probably not. So feel free to close this bug for now, I just wanted to make sure that you are aware of this differing behaviour.

Thanks again and a merry christmas
  ~ Simon

**Comment by wez** [comment]
Agreed: I don't really like this, but I think it's OK for now and can be revisited if something crops up as a result
