### ISSUE TITLE
Copy/paste to PrimarySelection under wayland 

### ISSUE THREAD

**Issue by xanderio** [wez/wezterm#1423]
**Is your feature request related to a problem? Please describe.**
The ability to interact with the PrimarySelection under wayland.

**Describe the solution you'd like**
Using this the [primary-selection-unstable-v1](https://wayland.app/protocols/primary-selection-unstable-v1) to interact with it, if the wayland server supports this protocoll

**Comment by wez** [comment]
Seems like it is accessible to Rust via https://docs.rs/wayland-protocols/latest/wayland_protocols/unstable/primary_selection/v1/client/index.html
