### ISSUE TITLE
Feature request: option to not scroll cursor with iTerm2 images

### ISSUE THREAD

**Issue by ghost** [wez/wezterm#1424]
I'm playing with iTerm2 image output, and noticing that when I put image data on the bottom line it scrolls.  This can be seen via:

```
java -Djexer.ECMA48.iTerm2Images=true -Djexer.hideStatusBar=true -jar path/to/jexer.jar
```

Then open an image, drag it into the bottom row, and things scroll.  This is similar to sixel, but does not have to be.

The [iTerm2 document](https://iterm2.com/documentation-images.html) provides no means to prevent the cursor from being moved, and mintty did not [extend or document a way either](https://github.com/mintty/mintty/wiki/CtrlSeqs#image-support) in that implementation.  (I haven't been following the ecosystem for a while, has anyone else implemented iTerm2?)

It would be nice to have a way to put image data on the bottom row for fullscreen applications to use.  Would you have an objection to me implementing something like an optional "noScroll=1" to mean "leave the cursor where it was" for wezterm?

**Comment by klamonte** [comment]
Oh how convenient!   Seeing as how do_not_move_cursor is already there, I am stubbing in a path for "doNotMoveCursor=1" to do exactly what I want.  (It's just like the inline option.)

**Comment by klamonte** [comment]
Compatibility: I just validated that both mintty (current) and iTerm2 (circa 2020) do not have adverse behavior to including "doNotMoveCursor=1" in the image sequence, i.e. they behave the same with and without the parameter.

**Comment by wez** [comment]
I don't have an objection to the implementation, I'm just a little cagey about diverging behavior over time.  I wonder if @gnachman would consider making a similar change to iTerm2?

**Comment by wez** [comment]
I went ahead and merged your PR in the meantime :)
