### ISSUE TITLE
Background opacity not applied on explicit background color

### ISSUE THREAD

**Issue by Mange** [wez/wezterm#1425]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20211219-110753-48dd57ab

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

:warning:  **I am unsure if this is a bug!** I think this is a question of taste.

In some terminals, like for example Kitty, when background opacity is set it is applied to all cases of background color matching the theme's background color. When using 24-bit true color escape sequences, this might affect opacity.

### To Reproduce

Enable `window_background_opacity` (to an excessive value to show the problem). Set background color to `#1E1E29`.

Print out text using that explicit background color.
```sh
clear; echo $'This uses the default background\n\e[48;2;30;30;41mThis uses the same explicit background\n\e[0mThis uses the default background'
```

### Configuration

```lua
local wezterm = require "wezterm"

return {
  window_background_opacity = 0.5,
  color_scheme = "Catppuccino",
  color_schemes = {
    -- https://github.com/catppuccin/catppuccin/issues/17
    Catppuccino = {
      background = "#1E1E29",
    },
  },
}
```

### Expected Behavior

The section with the same background color as the terminal's background should use transparent background.

### Anything else?

**Screenshot from Wezterm:**

![image](https://user-images.githubusercontent.com/1599/146695474-e78baaba-9601-443e-bb5f-a2130625731f.png)

**Screenshot from Kitty:**

![image](https://user-images.githubusercontent.com/1599/146695495-94360bdc-4fb3-4b94-81f1-2d52e59000ae.png)

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/appearance.html?highlight=text#text-background-opacity

**Comment by Mange** [comment]
Not quite right. Here I'm experimenting with `window_background_opacity = 0.0`.

`text_background_opacity = 1.0` (default):

![image](https://user-images.githubusercontent.com/1599/147093715-938c5b29-812d-44b2-a388-b9406d28e739.png)

`text_background_opacity = 0.0`

![image](https://user-images.githubusercontent.com/1599/147093752-3fa39679-e79c-447e-ac5a-2a61bf48f809.png)

The red background disappears too as `text_background_opacity` is for all background colors, not just the terminal background color.

**Comment by wez** [comment]
The behavior isn't a bug, it's just different from Kitty :)
In wezterm, we classify the background color like this:

* If the background attribute is set to default, then we use `window_background_opacity`
* Otherwise, we use `text_background_opacity`

If an application requests that the background be an explicit true color value or an explicit palette index we respect that and use it: it is distinctly different from setting the background color attribute to default.

**Comment by Mange** [comment]
Cool! Great to know. :-)
