### ISSUE TITLE
Option to hide tab if only one tab

### ISSUE THREAD

**Issue by erf** [wez/wezterm#143]
**Is your feature request related to a problem? Please describe.**
If only one tab is open, the tab is still shown. This is not the case in iTerm2.

**Describe the solution you'd like**
I would like to be able to set a variable in the `.wezterm.tom` to hide the tab if only one tab. 

Or alternatively default to this behaviour.

**Comment by ImportTaste** [comment]
I might be wrong, but I think the tab bar counts as a line in the terminal, so making the tab bar flexible like this seems like an avenue for a whole host of re-rendering issues.

Do consider that one advantage to having the tab bar even with a single tab is the + button, which will not only open a copy of the shell that you're in, but in the same directory. https://github.com/wez/wezterm/pull/114 (Although I notice this feature currently isn't working for Windows cmd, I'll have to open an issue regarding that.)

**Comment by erf** [comment]
I don't think it should be too much of a problem to render one line differently..?

Instead of the + button you would add a keyboard shortcut instead.

**Comment by wez** [comment]
I think this is a reasonable request; it is possible to set `enable_tab_bar = false` in the config and save it to hide the bar dynamically and the tabs in all the windows will resize appropriately, so I'm not worried about the resize behavior.

There is already a key assignment for creating a new tab (CMD+T and CTRL-SHIFT-T) so a hidden tab bar won't block that flow.

I'll keep the current tab bar behavior as the default as it makes things a little more discoverable/accessible for new users.

**Comment by wez** [comment]
This is in the latest "nightly" build

**Comment by erf** [comment]
Great! Thanks :)
