### ISSUE TITLE
Disable inactive_tab_hover style when not hovering

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1434]
**Is your feature request related to a problem? Please describe.**

Currently the `inactive_tab_hover` style sticks even when mouse is not hovering over, which isn't great. It only seems to reset when you hover on a different tab or type something

**Describe the solution you'd like**
`inactive_tab_hover` should only be active when the mouse cursor is actually hovering over the tab and reset to the default style when hovering is over

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by davidrios** [comment]
Which OS are you testing this? On Windows the hover state doesn't clear when you move the mouse directly outside the application window, and #1679 fixes that.

**Comment by eugenesvk** [comment]
Windows and Mac
