### ISSUE TITLE
termwiz: Displaying non-ASCII characters works fine under Linux but not under Windows.

### ISSUE THREAD

**Issue by hamamo** [wez/wezterm#1435]
Example (using umlaut-ö instead of o in "World"):

**Cargo.toml**
```
[package]
name = "termwiz-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
termwiz = "*"
```
**src/main.rs**
```
use termwiz::{terminal::{buffered::BufferedTerminal, new_terminal}, caps::Capabilities, surface::Change};

fn main() -> anyhow::Result<(), anyhow::Error> {
    let mut term = BufferedTerminal::new(new_terminal(Capabilities::new_from_env().unwrap())?)?;

    term.add_change(Change::Text("Hello, Wörld!\r\n".into()));
    term.flush()?;
    Ok(())
}
```
Windows shows two terminal graphics characters instead of ö (looks like utf-8 interpretation is missing).

**Comment by wez** [comment]
I think the Terminal implementation on Windows is missing:

* Save result of `GetConsoleCP`
* Call `SetConsoleCP` to set it to UTF-8
* Restore the original CP when exiting

(and the same for the output CP as well)

**Comment by wez** [comment]
termwiz 0.15 has been published with a fix for this
