### ISSUE TITLE
Allow using HSL colors instead of HEX RGB in configuration

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1436]
**Is your feature request related to a problem? Please describe.**
I find RGB color scheme in general (and especially the added hex conversion complexity) rather unintuitive, especially when I'm trying to tweak a shade or two, so I have to use some color converter, which is less convenient vs. being able to edit colors "in real time" with just an editor and terminal side-by-side.

**Describe the solution you'd like**

I'd like to be able to enter colors via 
  - `fg_color="0 0 75"` in HSL (`h°, s%, l%`, though these extra symbols are definitely not welcome in the actual entry field, space-separated match of ` *(\d{1,3}) *(\d{1,3}) *(\d{1,3})` is the best)  instead of 
  - `fg_color="#BFBFBF"` in HEX RGB
  
then tweaking a shade of gray is not only 1 number away (vs 3), but also easier reason about

**Describe alternatives you've considered**
I'm currently using a "color calculator" to tweak colors and paste the resulting hex in WezTerm's config and see how that fits there

**Additional context**

**Comment by eugenesvk** [comment]
Thanks for such a quick fix!
May I suggest a couple of minor improvements:
  - simplifying color entering a bit and moving the `hsl:` to a variable as I'd not expect any user to mix&match these extra color schemes (and hex already has a legacy `#` prefix), but rather set it once and enjoy not needing to type for every color
  - allowing leading spaces for each of the values (currently I get an error on `"hsl: 20 100 50"`) to make thew following kind of vertical alignment possible as it helps in color differentiation/comparison (some random colors)
```lua
"  0   0 100" -- "white" 
"  0   0  98" -- "white2" 
"193 100  50" -- "caret" 
"220  62  36" -- "blue1" 
"217  97  35" -- "blue2" 
"214  67  42" -- "blue3" 
```

**Comment by wez** [comment]
> * simplifying color entering a bit and moving the `hsl:` to a variable

Do you mean that you'd want to set something that says "treat all colors as hsl"?

If so, then no, it won't work for wezterm because the way the configuration works is by mapping the data types of the values from a lua table into Rust structs. This is done essentially as a deserialization process which is pure in the functional programming sense: a given input must always produce the same output, independently from any global state.

**Comment by wez** [comment]
> * allowing leading spaces for each of the values

Done in f9366ad96

**Comment by eugenesvk** [comment]
> Do you mean that you'd want to set something that says "treat all colors as hsl"?
> 
> If so, then no

Yes, exactly. It's a pity that better color schemes take more effort vs. the ugly hex :), but no big deal, lua to the rescue: I've added a function that allows one to skip the prefix to the [discussions](https://github.com/wez/wezterm/discussions/1449) to make better colors easier
