### ISSUE TITLE
On unfocused window on Windows, click events are passed through, scroll events are blocked

### ISSUE THREAD

**Issue by bew** [wez/wezterm#1437]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20211213-091602-1f958fa1 (nightly)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When the terminal window is not focused, focusing it by clicking on it now also forwards the click to the running program (e.g nvim/tmux with enabled mouse).
It's not a problem when the program does not have the mouse enabled, but it is when it has, because there's no way to focus the terminal without moving the cursor.
In the case of tmux (e.g: a shell running in a tmux pane), this is very annoying because focusing the terminal window now sends a click that makes tmux go in copy-mode and I have to quit it (by pressing `q`) if all I wanted to do is enter some command.

Similarly, when the window is not focused, scrolling events do not send scroll events to the program anymore (this was helpful!).

With current stable (20211205-192649-672c1cc1) this does not happen:
* click to focus did not send anything to the running program
* scrolling events was sent to the running program

---
I know these might sound opposite (some events should pass directly, some events should be guarded), I wonder if this could be made configurable? => To decide which mouse event is allowed to be passed directly when window is not focused, and which event should be blocked until window is focused.

### Configuration

no relevant config

### Logs

10:00:42.130 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
10:00:42.664 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) HD Graphics 530 4.5.0 - Build 27.20.100.9126 is_context_loss_possible=true wezterm version: 20211213-091602-1f958fa1

### Anything else?

NOTE: I didn't check on Linux how that behaves, but I don't really have this problem because I have focus-follows-mouse, so I never need to _click_ on terminal windows to select them, I only need to _hover_ them. Windows (the OS) does not have that

**Comment by wez** [comment]
I tweaked this to allow wheel events through but not clicks or moves.  Let me know what you think!

**Comment by bew** [comment]
Scrolling on unfocused windows seems to be fixed, but clicks are still passed through.

My test case, is in WSL, I have neovim installed.
I open a long file (or write a bunch of random text), make sure the mouse is enabled with at least `set mouse=nv` or `set mouse=a`, then focus another window (like Window Explorer).
Now click in neovim, the cursor should not move.

Also I noticed that it's a problem with AltSnap when trying to use it to move a wezterm window (I never do this in practice because of #1013, but tried it anyway): With Alt+LeftClick-and-drag, it starts a visual selection in neovim while moving (but does not end it, similar to #916 but in this case I think it's a AltSnap issue).

**Comment by wez** [comment]
I think this is really really fix in the night now

**Comment by bew** [comment]
Yess good for me, thanks :+1:
