### ISSUE TITLE
Option to remove tab ids from tab title

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1442]
**Is your feature request related to a problem? Please describe.**

I'm using my shell's [builtin function](https://github.com/xonsh/xonsh/blob/5091c8368ef15e9910423e4853f9a40dc3d72444/xonsh/base_shell.py#L534) to set tab title via an environment variable `TITLE` (it seems to be using the OSC 0 or `SetConsoleTitle` on Windows, though I've tried to limit to the escape sequence and the results are the same)

This seems to work fine except for the fact that WezTerm adds tab ids `1: `, `2: `, etc. which I don't ever need and which take valuable tab space 

**Describe the solution you'd like**
An option to not add any additional information to the tab title

**Describe alternatives you've considered**
There seems to be a complicated callback-based solution in [this comment](https://github.com/wez/wezterm/issues/522#issuecomment-902203635), though I believe that configuring WezTerm to not anything to the name on its own should be much easier

**Additional context**

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/config/show_tab_index_in_tab_bar.html

**Comment by eugenesvk** [comment]
Wow the config search is weird, `https://wezfurlong.org/wezterm/config/lua/config/swap_backspace_and_delete.html?search=tab%20index` finds the command that changes index base, but not the one that disables the index!
