### ISSUE TITLE
Update archlinux aur packages

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#1447]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20210405-110924-a5bb5be8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

AUR package is very old.

https://aur.archlinux.org/packages/wezterm-bin/

As of now it points to 20210405.110924.a5bb5be8-2.

Can we get the latest stable version to be more frequent?

### Configuration

no config

### Expected Behavior

Get latest stable version

### Anything else?

Might be can be automated in CI?

**Comment by wez** [comment]
That package is deprecated in favor of https://archlinux.org/packages/community/x86_64/wezterm/ (it says so at the bottom of that page)

**Comment by prabirshrestha** [comment]
Works now moving to wezterm package. Thanks.
