### ISSUE TITLE
remote ssh domain should not use `default_prog` when spawning/splitting

### ISSUE THREAD

**Issue by wez** [wez/wezterm#1456]
When using `wezterm ssh`, we should ensure that `default_prog` (which is scoped to the local machine) is not used to spawn commands on the remote host.

**Comment by bew** [comment]
I'm using `wezterm ssh HOST CMD` would it be possible to run `CMD` again when opening new panes/tab?

**Comment by wez** [comment]
My brain was working on this while I slept(!) and my game plan here is:

* Introduce equivalents to `default_prog`, `default_cwd` and `set_environmental_variables` as methods of the mux `Domain`
* Introduce config options that can be set per-domain for these
* Cook up a way to represent these for `RemoteSshDomain`, which is currently ad-hoc and generated dynamically when `wezterm ssh` is run.  `man ssh_config` mentions `RemoteCommand`; respecting that feels like a good thing to support.  I think it may be nice to also support defining shortcuts/configs for these in wezterm.lua, but need to spend some time thinking more about that configuration and how to balance it with the existing ssh config files.

I don't think `wezterm ssh HOST CMD` should effectively set `default_prog` to `CMD` by default, as `CMD` may not be idempotent and may be quite dangerous if say, someone were to mis-click the new tab button.  However, we could introduce a shortcut CLI switch that allows you to explicitly make it have that behavior.

**Comment by wez** [comment]
You can now do:

```lua
return {
  ssh_domains = {
    {
      name = "woot",
      remote_address = "192.168.1.8",
      multiplexing = "None",
      default_prog = {"fish"},
    }
  },
}
```

and then: `wezterm connect woot` will act like `wezterm ssh 192.168.1.8`, but with the tabs/panes defaulting to running `fish`.

You can take it a step further and set `default_domain = "woot"` to make wezterm default to ssh'ing to that destination; something that I think is potentially interesting for WSL users that want to cut out conpty from the terminal processing flow.

**Comment by wez** [comment]
More info: https://wezfurlong.org/wezterm/config/lua/SshDomain.html
