### ISSUE TITLE
Reduced transparency when splitting the terminal

### ISSUE THREAD

**Issue by athre0z** [wez/wezterm#1459]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm-gui 20211225-001431-b5d156c2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, built `main` from source, issue is still present.

### Describe the bug

The amount of transparency / opacity set via `window_background_opacity` changes depending on whether the terminal is tiled or not, which doesn't seem like it would be intentional. Tiling it again doesn't further change opacity -- it only matters whether it is tiled at all.

### To Reproduce

Start wezterm with given config, then tile the terimal.

### Configuration

Reduced to what is substantial to reproduce:

```
local wezterm = require 'wezterm';

return {
    window_background_opacity = 0.75,
}
```

### Expected Behavior

Opacity remains the same regardless of tiling.

### Anything else?

I'm on Nvidia proprietary drivers.

#### Untiled

![non-tiled](https://user-images.githubusercontent.com/6553158/147380201-c92e39d3-1142-42d0-bcb0-01333c9d04b7.png)

#### Tiled

![tiled](https://user-images.githubusercontent.com/6553158/147380203-a005a8da-970c-4e81-bdf1-dafade81e7dc.png)

**Comment by wez** [comment]
What does "tile the terminal" mean?  How do you do that?

**Comment by athre0z** [comment]
Using `wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}`, which I bound to a hotkey.

**Comment by wez** [comment]
Thanks for spotting this! It is fixed now in `main`.

**Comment by athre0z** [comment]
Can confirm that the fix works, thanks a lot! :-)
