### ISSUE TITLE
Default distribution of wsl fails to launch when windows's locale is not English

### ISSUE THREAD

**Issue by nazo6** [wez/wezterm#1462]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20211221-075657-b9102466

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I tried to start default distribution of wsl from wezterm's launcher it fails with this message.
```
指
[Process didn't exit cleanly. (exit_behavior="CloseOnCleanExit")]
定された名前のディストリビューションはありません。
```
it means specified distribution does not exist and I think this is caused because `wsl -l` returns localized message as follows. ('既定' means default.)
```
~ ❯  wsl -l
Linux 用 Windows サブシステム ディストリビューション:
Arch (既定)
docker-desktop-data
docker-desktop
Ubuntu
```

I think it would be better to use `wsl -l -v` to get distribution list, which seems to return not localized message.

### To Reproduce

Set windows locale to language other than English (in my environment it's Japanese) and select wsl's default distribution in wezterm's launcher.

### Configuration

```lua
local wezterm = require("wezterm")
return {
	font = wezterm.font("HackGenNerd"),
	font_size = 10,
	enable_kitty_graphics = true,
	default_prog = { "pwsh.exe" },
	keys = {
		{ key = "l", mods = "ALT", action = "ShowLauncher" },
	},
}
```

### Expected Behavior

Distribution is launched without error.

**Comment by wez** [comment]
I've pushed a change that seems to work with the `wsl -l -v` output on my system, but note that I only have a single english distro installed.
That change should be available in the nightly download for windows within the next hour.
Please give it a try and let me know if it works for you.

Please also share the output from `wsl -l -v` from your system, as I'd like to capture that as a test case!

**Comment by nazo6** [comment]
I tried nightly and it works well. Thanks for quick fix!

And here is output of `wsl -l -v` in my environment.
```
  NAME                   STATE           VERSION
* Arch                   Running         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
  Ubuntu                 Stopped         2
  nvim                   Stopped         2
```
