### ISSUE TITLE
Add option for pane:get_lines_as_text() to join wrapped lines.

### ISSUE THREAD

**Issue by aca** [wez/wezterm#1468]
I'm trying to replace `tmux capture-pane -J`.  `-J` option join wrapped lines which is important
to preserve the output of the commands regardless of the window/pane sizes.
Also useful to build plugin like https://github.com/roosta/tmux-fuzzback.

**Comment by wez** [comment]
I added [pane:get_logical_lines_as_text](https://wezfurlong.org/wezterm/config/lua/pane/get_logical_lines_as_text.html)
Give it a few minutes to show up in the docs online, and about an hour to show up in the nightly downloads.

**Comment by aca** [comment]
Thanks @wez. It's so fun to script terminal in lua!
