### ISSUE TITLE
debug_assert with decomposed Hangul

### ISSUE THREAD

**Issue by ninjalj** [wez/wezterm#1469]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211226-125814-4cf90bf7

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Non-precomposed Hangul causes an assert. e.g:

    printf 'Complete syllable \u1100\u1161\n'

```
thread 'main' panicked at 'assertion failed: width < 3', termwiz/src/cell.rs:602:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'task has failed', /home/lj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
```

Updating ridiculousfish/widecharwidth to a version that gives 0 width to V and T jamos (https://github.com/ridiculousfish/widecharwidth/pull/17) should fix it.

### Configuration

no config

**Comment by wez** [comment]
That PR is currently incomplete, but we could also relax the assertion in the meantime, and just cap the max possible width to 2.
