### ISSUE TITLE
Mouse selection is invalidated after text-cursor position

### ISSUE THREAD

**Issue by bew** [wez/wezterm#1472]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211228-232418-93a9b5a7 (nightly)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hard to 'describe', see the reproduction steps.

### To Reproduce

Start a terminal, then run `wezterm` from it (can't reproduce from a simple `sleep 99`, although from my understanding it should be the same).

Now try to select the log, but extend the selection below the cursor position.
=> When the mouse selection goes after cursor position, the mouse selection is ended, and moving the mouse up (while still clicking to extend the selection) makes it look like the selection starts from the end..

Here is a video example, first time with char selection, second time with word selection and third time with line selection:

https://user-images.githubusercontent.com/9730330/147674462-6d43d38a-f171-44c3-ad7b-a9485a4f2d79.mp4

### Configuration

N/A (same behavior with `wezterm -n`)

**Comment by wez** [comment]
Hmm, I've seen this on Windows and fixed the case I was hitting with https://github.com/wez/wezterm/commit/88b8cb3e21b942088188e878ced5d55e4f14a9de

I can't reproduce it here on my Linux box!

The effect you are seeing is triggered by this block of code, whose purpose is to invalidate the selection when the selected region is changed:

https://github.com/wez/wezterm/blob/93a9b5a7fefdef599c82fde6a781c75407d2c12c/wezterm-gui/src/termwindow/mod.rs#L1224-L1259

```rust
let dirty = pane.get_changed_since(visible_range, seqno);
```

will return `Line`s whose seqno is `SEQ_ZERO` or whose seqno is larger than the one provided.

`SEQ_ZERO` should ideally not be present in the lines in the terminal model; I suspect that something about the sequence of the output on your screen resulted in a line with a SEQ_ZERO at the row with the cursor, and that is causing the selection to be invalidated.

**Comment by wez** [comment]
Ah, repro steps:

fill the viewport (eg: `ls`) so that the cursor is at the bottom of the display.
Run `sleep 99`, 
Resize the window to make it taller.

The newly generated rows at the bottom are SEQ_ZERO.
You need the `sleep` or any long running command that doesn't repaint the screen on SIGWINCH to trigger this.

**Comment by bew** [comment]
Hmm based on your repro steps I'm guessing that I saw it (but not you initially) because I was in a tiled window setup, and running `wezterm` from that terminal triggered a resize of that terminal, and these SEQ_ZERO lines would have came from that resize (?)

**Comment by bew** [comment]
Amazing, it's now fixed :+1:
