### ISSUE TITLE
Focus not updated until key input when "ActivatePaneDirection"

### ISSUE THREAD

**Issue by aca** [wez/wezterm#1475]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20211205-192649-672c1cc1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Pane remains inactive and activated at next input.

### Configuration

```
wezterm.on("move-left", function(window, pane)
  window:perform_action(wezterm.action({ ActivatePaneDirection = "Left" }), pane)
end)

local config = {
  keys = {
    { key = "h", mods = "CTRL", action = wezterm.action({ EmitEvent = "move-left" }) },
  }
}
```

### Expected Behavior

I believe it should work the same as 
```
{ key = "h", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Left" }) },
```

**Comment by wez** [comment]
Thanks for the report; this is now fixed and will be available in the nightly downloads within the next hour!
