### ISSUE TITLE
-e flag for running command on start

### ISSUE THREAD

**Issue by Personator01** [wez/wezterm#1478]
**Is your feature request related to a problem? Please describe.**
As of now, there is no  way to specify a command to run when running wezterm from another shell instance, such as both opening a new wezterm window and running a program within it from a script. For example, I can't make a button in my WM which opens wezterm and runs ncmpcpp within the newly opened window.

**Describe the solution you'd like**
Addition of a flag similar to xterm's `-e` which specifies shell script to run when opening wezterm

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by wez** [comment]
Take a look at `wezterm start --help`

**Comment by wez** [comment]
And: https://wezfurlong.org/wezterm/config/launch.html#launching-a-different-program-as-a-one-off-via-the-cli

**Comment by Personator01** [comment]
Sorry, I didn't interpret the help screen correctly.

**Comment by wez** [comment]
It's understandable: it wasn't very clear what it did, but that is fixed now!
