### ISSUE TITLE
You have to set ALL styles for for tabs for it to work

### ISSUE THREAD

**Issue by erf** [wez/wezterm#148]
## Describe the bug
I tried to set `colors.tab_bar`, but in then i had to set all the other tab bar styles as well, or else i get the error message:

"Error parsing TOML from ..wezterm.toml  missing field `inactive_tab_hover` for key `colors.tab_bar`". 

It works when i set all tab styles.

## Environment (please complete the following information):

 - OS: macOS
 - Frontend:  OpenGL
 - Version:  WezTerm-macos-github-20200202-200216-b07ed454-5-g9558fbe

## To Reproduce
Startup wizterm with only a subset of the `tab_bar`styles.

## Configuration

```
[colors.tab_bar]
background = "#000000"
```

## Expected behavior
I would expect to use the default colors for tab bar attributes not set, instead of an error.

**Comment by wez** [comment]
While it is certainly annoying, this isn't a bug; it's related to how the serde serialization layer interacts with types and defaults and it is behaving "correctly".  It could do with being more streamlined though!
