### ISSUE TITLE
position based key binding support

### ISSUE THREAD

**Issue by wez** [wez/wezterm#1483]
Today, key assignments can be made either via the `raw` keycode, a platform-dependent code that has different values depending on the windowing environment being used, or via the processed unicode values that are obtained after the OS keyboard layout has been applied to the raw input.

It is desirable to be able to express key bindings in terms of the physical position of the key on a US qwerty keyboard.
For example I might want to make `SUPER+Q` quit wezterm, and make it so that that Q key is the one I press even if
I switch to a keyboard layout such as AZERTY where the Q and the A keys are switched.  In the AZERTY layout the Q has become an A, but that physical position still binds to the key assignment.

I happen to know from my mechanical keyboard building hobby that the key positions have defined codes in the USB HID specification.  Those get interpreted by the OS and are exposed to wezterms input layer in the form of the `raw` values that we already support.

The goal then is to allow using a configuration like:

```lua
return {
   keys = {
     {physical="Q", mods="CMD", action="QuitApplication"},
   },
}
```

Internally, we'd need:

* [x] An enum of physical key positions that we can plumb through to the config
* map raw keycode to physical position:
  * [x] X11
  * [x] Wayland
  * [x] macOS
  * [x] Windows
* [x] Adjust keyboard input mapper to handle this, likely by adding an additional matching phase
* [x] ~~Decide the precedence/match order of `physical`, `raw` and `key` based assignments~~ -> physical, then raw, then mapped
* [x] ~~Decide whether the default key assignments should be re-configured using `physical`~~ -> physical
* [x] ~~Should the key assignment syntax default to `physical` rather than the current cooked value?~~ -> physical

Open Questions:

* Should the default key assignments really be position based?
* Should we allow the user to select position or mapped variations of the default key assignments?
* Is there something better we could do for non-US layout users? (potentially tangential to the main thesis of this issue)

**Comment by wez** [comment]
Current `main` allows:

```lua
local wezterm = require 'wezterm'

return {
  debug_key_events = true,
  keys = {
    {key="phys:Q", action=wezterm.action{SendString="woot"}},
  },
}
```

The above will send "woot" to the pane whenever the key in same
physical position as Q on an ANSI standard US keyboard is pressed.

**Comment by JeanMertz** [comment]
@wez question, I just updated to the latest nightly, noticed my key configurations no longer working when they are targeted at the `CMD` modifier key, and found this issue. Could it be related to the latest changes proposed in this issue?

These commands:

```lua
    keys = {
        {key="K", mods="CMD", action=wezterm.action{ClearScrollback="ScrollbackAndViewport"}},
        {key="<", mods="CMD", action=wezterm.action{MoveTabRelative=-1}},
        {key=">", mods="CMD", action=wezterm.action{MoveTabRelative=1}},
        {key="m", mods="CMD", action="Nop"}
	}
```

All stopped working for me because they use the `CMD` modifier.

**Comment by JeanMertz** [comment]
Another — perhaps related — issue is that this mapping no longer works:

```lua
{key="n", mods="CTRL|SHIFT", action="ToggleFullScreen"},
```

From the change log, I understand I can now use this instead:

```lua
{key="N", mods="CTRL", action="ToggleFullScreen"},
```

But neither work as expected. Previously, this would toggle Wezterm's full screen, but now it seems to behave as if I type `CMD+N`, that is, it opens a new Wezterm window.

**Comment by wez** [comment]
@JeanMertz can you open a new issue for what you're seeing? I'd like to capture more information about your setup so we can figure what's going on!

**Comment by wez** [comment]
Summarizing the changes since the prior release:

* You may now use `phys:A` to refer to the key in the same physical position as A on an ANSI US layout keyboard
* Formally split the internal `KeyEvent` into `RawKeyEvent` and `KeyEvent`, which are the pre- and post-mapped/composed key events, respectively
* `RawKeyEvent`s are matched against your key assignments (+ defaults). If they match then the raw key event will not contribute to dead key or other IME compositions.
* If `RawKeyEvent` didn't match any assignments, the event is fed through dead keys and composition to produce a `KeyEvent`
* `KeyEvent` is matched against your key assignments. If it doesn't match any, it is passed through to the pane.
* The default key assignments have all be redefined in terms of physical positions on an ANSI US layout keyboard.  For users of non-US layouts, some of them (notably those on brackets and punctuation keys) may now appear to have stopped working because they live on different keys compared to a prior release
* The config loader will now assume that `key="a"` should be `key="phys:A"` so that your key assignments in your config will match based on the physical position of the key in a US ANSI layout.
  * If you had `{key="N", mods="CMD", ..}` it will now be treated as though you wrote `{key="phys:N", mods="CMD", ...}`, BUT! the old syntax would only match a shifted, uppercase `N`, whereas the rewritten form cannot represent the shift state in the `key` portion. If you had assignments in that style, you will need to explicitly add `SHIFT` into your `mods` for them.
* You can use `key="mapped:a"` to explicitly refer to the post-mapped version of the key instead.

**Comment by JeanMertz** [comment]
@wez FYI, I managed to solve my above two issues by changing the above-mentioned mappings to these:

```lua
        {key="phys:K", mods="CMD", action=wezterm.action{ClearScrollback="ScrollbackAndViewport"}},
        {key="<", mods="SHIFT|CMD", action=wezterm.action{MoveTabRelative=-1}},
        {key=">", mods="SHIFT|CMD", action=wezterm.action{MoveTabRelative=1}},
        {key="phys:M", mods="CMD", action="Nop"},
        {key="phys:N", mods="SHIFT|CTRL", action="ToggleFullScreen"},
```

I assume you'd still like this to be backward compatible as much as possible, but at least the new feature-set allowed me to get my existing shortcuts working again.

**Comment by wez** [comment]
@JeanMertz with the latest `main` (should be available as a mac nightly download once this job completes: https://github.com/wez/wezterm/runs/4694742839?check_suite_focus=true), you can rewrite that as:

```lua
        {key="K", mods="SHIFT|CMD", action=wezterm.action{ClearScrollback="ScrollbackAndViewport"}},
        {key="<", mods="SHIFT|CMD", action=wezterm.action{MoveTabRelative=-1}},
        {key=">", mods="SHIFT|CMD", action=wezterm.action{MoveTabRelative=1}},
        {key="M", mods="SHIFT|CMD", action="Nop"},
        {key="N", mods="SHIFT|CTRL", action="ToggleFullScreen"},
```

**Comment by Mattwmaster58** [comment]
This changed seems to have introduced a regression in specific circumstances with modifiers. I've only seen it happen when `mods="CTRL|SHIFT"` and key is a number. For example:

```lua
    {key="1", mods="CTRL", action=wezterm.action{SendString="woot"}},
    {key="1", mods="CTRL|SHIFT", action=wezterm.action{SendString="woot"}},
```
The first shortcut works, the second does not.

As a temporary workaround I've found that this does work:
```lua
    {key="phys:1", mods="CTRL|SHIFT", action=wezterm.action{SendString="woot"}},
```

**Comment by Mattwmaster58** [comment]
FWIW, whatever you changed in these last commits has things working for me again 👍
