### ISSUE TITLE
Placing font.font before other settings disables them

### ISSUE THREAD

**Issue by erf** [wez/wezterm#149]
## Describe the bug

If i set the `font.font` attribute before `font_size` in the `.wezterm.toml` file, the later is not used. This is also the case for other settings like `initial_rows` etc. 

## Environment (please complete the following information):

 - OS: macOS
 - Frontend:  OpenGL
 - Version: WezTerm-macos-github-20200202-200216-b07ed454-5-g9558fbe

## To Reproduce

Start up the terminal with the `font.font` attribute set before and after the other mentioned settings.

## Configuration

```
[[font.font]]
family = "Fira Code"

font_size = 13
initial_rows = 30
initial_cols = 100

hide_tab_bar_if_only_one_tab = true
```

## Expected behavior

I would expect the configuration to work regardless of the order.

**Comment by wez** [comment]
That's not a bug; that's just how TOML works.
The spec is here: https://github.com/toml-lang/toml
