### ISSUE TITLE
Glitchy window resize regression

### ISSUE THREAD

**Issue by athre0z** [wez/wezterm#1491]
When updating to latest wezterm recently, I noticed that the window resize had become a bit weird. It's a bit hard to describe, but it essentially jumps back and forth between random sizes during resizes instead of being fluent like before.

I bisected it to this particular commit which introduced this regression:

```console
$ git bisect good
ada35ff3db5e6ab4996366068db014547282fe12 is the first bad commit
commit ada35ff3db5e6ab4996366068db014547282fe12
Author: Wez Furlong <wez@wezfurlong.org>
Date:   Sun Dec 12 09:27:37 2021 -0700

    gui: improve handling of dpi changes especially during window creation

    This fixes up the Windows issue, but I wonder if it also helps with the
    mac issue?

    refs: https://github.com/wez/wezterm/issues/1039
    refs: https://github.com/wez/wezterm/issues/1381

 docs/changelog.md                    |  1 +
 wezterm-gui/src/termwindow/resize.rs | 48 +++++++++++++++++++++++++++++++++---
 2 files changed, 45 insertions(+), 4 deletions(-)
````

### Videos

Because it's hard to describe, I just created screen recordings.

#### Borked (`ada35ff3`)

https://user-images.githubusercontent.com/6553158/147908563-476fc2fa-acd4-401f-a965-d3530c4c129b.mp4

#### Expected (`136b4a9b` aka `ada35ff3~1`)

https://user-images.githubusercontent.com/6553158/147908551-1fdcfe66-1149-40e6-b5f5-acebca323521.mp4

### Configuration

Irrelevant, also reproduces with defaults.

### Platform

Linux / X11 / Gnome 41 / Nvidia proprietary

**Comment by ghifarit53** [comment]
Can confirm this also occurs in macOS. WezTerm version is `wezterm 20211230-092051-07af7e0c` with default configuration. macOS is Monterey (12.0.1). Not sure if I need to open a new issue because I think it's also resizing problem although the behavior looks different.

https://user-images.githubusercontent.com/59758342/147929353-9439c28d-8547-4c9d-920a-734d03176468.mov

**Comment by athre0z** [comment]
@ghifarit53 I can confirm that I have the same issue on Linux. Whether the window does the wobbly effect / moves across the screen seems to depend on which corner I use for resizing. With the lower right corner as shown in my video, the problem doesn't occur. When resizing on the top bar, it moves. I again compared the two revisions from above and can confirm that it regressed in the same commit.

**Comment by wez** [comment]
Thanks for the report, and the bisect was helpful!  I had noticed the glitch, but since I rarely resize my windows, it hadn't bothered me enough to dig into it yet!

I've pushed some changes that make things better on all systems except Wayland.

**Comment by athre0z** [comment]
I can confirm it's fixed when building from `main`, thanks!
