### ISSUE TITLE
Font rendering a lowercase `l` as an uppercase `L`

### ISSUE THREAD

**Issue by smsegal** [wez/wezterm#1496]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

WezTerm-macos-20220103-002251-c0502012

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using the [Recursive](https://github.com/arrowtype/recursive) font, the lowercase `l` is rendered in uppercase as `L`. 

### To Reproduce

1. Download the latest font from [Recursive](https://github.com/arrowtype/recursive).
2. In `~/.config/wezterm/wezterm.lua`, set the font as:
```lua
  font = wezterm.font({
    family = "Recursive",
    weight = "Regular",
  })
```
3. Save the file and observe lowercase `l`s being rendered in uppercase. 

### Configuration

```lua
  font = wezterm.font({
    family = "Recursive",
    weight = "Regular",
  })
```

### Expected Behavior

Expected Behaviour: The font should render a lowercase `l` correctly. 

### Anything else?

The `Recursive` font is a variable font, meaning that it can accept float parameters to adjust how monospaced-proportional it is, among other axes. The producers of the font also provide "static" versions with the variable parameters fixed to a specific configuration. These work fine in WezTerm, but do not support font-hinting. The difference in quality is unfortunately noticeable on my setup. 

A screenshot of the incorrectly rendering font is below:
![image](https://user-images.githubusercontent.com/7110093/147954212-2be95fa0-18c2-430e-8dc8-239b6f3e7add.png)

**Comment by wez** [comment]
wezterm doesn't do anything special per-character.  It sounds like the opentype features are telling harfbuzz to do something.
I notice from https://github.com/arrowtype/recursive#opentype-features that `ss05` which you have enable changes the presentation of the `l`.  I would suggest removing that feature to see if it looks better.

**Comment by wez** [comment]
Looking at that likst, `ss05` and `ss08` both impact the `l` glyph; I suspect that this is an issue for the provider of the font to reconcile.

**Comment by smsegal** [comment]
> wezterm doesn't do anything special per-character. It sounds like the opentype features are telling harfbuzz to do something. I notice from [arrowtype/recursive#opentype-features](https://github.com/arrowtype/recursive#opentype-features) that `ss05` which you have enable changes the presentation of the `l`. I would suggest removing that feature to see if it looks better.

I've tried without any of the opentype features enabled, same result. I'll open an issue on the font's github page. 
I don't know much about opentype, but I suppose it's possible those two flags still interact even if I'm not setting them.

**Comment by arrowtype** [comment]
Hi @wez and @smsegal, thanks for discussing this. As I posted in the font’s repo issue:

> My first guess is that the software is activating the `MONO` variable axis, but without correctly applying the `rvrn` feature that swaps from the default `MONO=0` (Sans) forms to the `MONO=1` (Monospaced) forms. You can also see the issue in the `f r i` glyphs, thought it is less of a legibility problem there.

For an immediate user solution, I recommend using one of the static fonts instead of the variable font.

For the software, I recommend that `rvrn` should be on by default, as outlined in the OpenType spec for [rvrn](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-rvrn):

> Application interface: Application of the 'rvrn' feature is mandatory in implementations that support OpenType Font Variations whenever a variable font is in use. The feature should be processed in any layout process that supports use of variations, even if other OpenType Layout processing is not supported.

**Comment by arrowtype** [comment]
Oh, or, it may be slightly more complicated.

https://github.com/arrowtype/recursive/issues/497#issuecomment-1023721986

It seems that the `rvrn` feature probably _is_ being processed, and thereby selecting the "sans" form of `l`, but then the font is being rendered in the monospace proportions after that. I don’t understand font layout and rendering super deeply, so I’m slightly unsure of how that could happen.

**Comment by wez** [comment]
@smsegal based on those comments, I'd suggest adding `"rvrn"` to the list of `harfbuzz_features` in your config and see if that helps.

**Comment by wez** [comment]
I can't reproduce this issue with current `main` and the current recursive font download:

![image](https://user-images.githubusercontent.com/117777/159127208-b1982e3f-9dd1-4ada-8e59-07082595935f.png)

so I'm going to close out this issue!

**Comment by arrowtype** [comment]
Thanks for trying it out again, @wez! I wonder if it's also an OS update or something ... 🤔 Anyway, glad it seems to be working!

**Comment by wez** [comment]
harfbuzz has been updated since earlier, so I wonder if that may have fixed something? I didn't try the older version, but I'm happy that I couldn't reproduce this with the current build so I'm fine with not looking deeper!
