### ISSUE TITLE
No scrolling or selection, and characters entered are duplicated twice or thrice after resume on Wayland

### ISSUE THREAD

**Issue by VarLad** [wez/wezterm#1497]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Selection and scrolling don't work, and everything I enter gets entered twice or thrice (it takes aaa if I type a), after resume

### To Reproduce

1. Open Wezterm. Do some stuff
2. Suspend your system (sleep mode)
3. Resume your system
4. Check on Wezterm

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  font = wezterm.font("JuliaMono"),
  color_scheme = "Kibble",
  enable_wayland = true,
-- default_prog = {"/usr/bin/nu"},
}
```

### Expected Behavior

Wezterm works as it did before suspending the system. 

### Logs

![wezinfo](https://user-images.githubusercontent.com/51269425/147969369-c25ecd81-de86-444e-adaf-a691ab23ebbe.png)

### Anything else?

It also opens and removes 3 tabs with Ctrl+Shift+T after resume

**Comment by wez** [comment]
From the description and the error message, this sounds like is is related to seat handling; presumably the suspend/resume operation changes the set of wayland seats and we need to do something better than we're doing already.

**Comment by foundObjects** [comment]
I'm also affected by this, if there's debug info or testing I can supply feel free to ping me

**Comment by wez** [comment]
Thanks to @LawnGnome the keyboard handling is improved in `main`, and I pushed a speculative fix for the pointer handling just now.
I can't test suspend/resume on my hardware, so I don't know for sure if this is fixed; could you give it a try?

**Comment by VarLad** [comment]
@wez I can't reproduce this issue with the nightly Fedora 35 rpm build. I guess this issue is resolved.
