### ISSUE TITLE
colors.tab_bar.new_tab_hover.bg_color and fg_color settings don't work when the use_fancy_tab_bar option is enabled

### ISSUE THREAD

**Issue by bio** [wez/wezterm#1498]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220103-110538-2890e4e7

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`colors.tab_bar.new_tab_hover.bg_color` and `colors.tab_bar.new_tab_hover.fg_color` settings don't work when the use_fancy_tab_bar option is enabled.

### To Reproduce

1. open `~/.config/wezterm/wezterm.lua` and set `use_fancy_tab_bar = true,`
2. then set some colors for the new_tab_hover
```
  colors = {
    tab_bar = {
      new_tab_hover = {
        bg_color = "#ff0000",
        fg_color = "#00ff00",
      },
```
3. open WizTerm and then hover the mouse cursor over the new tab button

### Configuration

```
  colors = {
    tab_bar = {
      new_tab_hover = {
        bg_color = "#ff0000",
        fg_color = "#00ff00",
      },
```

**Comment by wez** [comment]
Thanks for the report; fixed in `main`; a new nightly should be downloadable within an hour!

**Comment by bio** [comment]
Awesome, thank you!
