### ISSUE TITLE
Font: character not aligned correctly

### ISSUE THREAD

**Issue by Funami580** [wez/wezterm#1499]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Character `🞄` not aligned correctly.

### To Reproduce

```
echo -e 'a\xf0\x9f\x9e\x84b'
```
Font installed: Noto Sans Symbols2
```
$ fc-list | grep Symbols2
/usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf: Noto Sans Symbols2:style=Regular
```

### Configuration

No config.

### Expected Behavior

Should be in the center, but it is positioned to the top left corner.

### Logs

```
2022-01-03T20:07:40.118Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-16205
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/glium/glium/issues
2022-01-03T20:07:40.176Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2) 3.0 Mesa 21.3.3 is_context_loss_possible=false wezterm version: 20220101-133340-7edc5b5a
2022-01-03T20:07:48.699Z WARN  wezterm_term::terminalstate::performer > unhandled ControlCode StartOfHeading
2022-01-03T20:07:48.699Z WARN  wezterm_term::terminalstate::performer > unhandled ControlCode StartOfText
```

### Anything else?

![wezterm_font](https://user-images.githubusercontent.com/63090225/147975514-bcdd9253-a0ad-43ea-abd0-da5fcb20c1db.png)

**Comment by wez** [comment]
What does: `wezterm ls-fonts --text $(echo 'a\xf0\x9f\x9e\x84b')` output for you?

**Comment by Funami580** [comment]
```
$ wezterm ls-fonts --text $(echo -e 'a\xf0\x9f\x9e\x84b')
a🞄b  \u{61}\u{1f784}\u{62} glyph=118  wezterm.font("Hack", {weight="Regular", stretch="Normal", italic=false})
                             /usr/share/fonts/TTF/Hack-Regular.ttf, FontConfig
a🞄b  \u{61}\u{1f784}\u{62} glyph=508  wezterm.font("Noto Sans Symbols2", {weight="Regular", stretch="Normal", italic=false})
                             /usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf, FontConfig
a🞄b  \u{61}\u{1f784}\u{62} glyph=129  wezterm.font("Hack", {weight="Regular", stretch="Normal", italic=false})
                             /usr/share/fonts/TTF/Hack-Regular.ttf, FontConfig
```

**Comment by wez** [comment]
I pushed a commit that seems to resolve this, potentially at the cost of regressing #1203 although my quick tests on linux and mac seem to be fine.  Hopefully all is good now?

**Comment by Funami580** [comment]
Yep, seems to be fixed, thanks!
