### ISSUE TITLE
Main terminal area has padding all around it

### ISSUE THREAD

**Issue by SpyrosRoum** [wez/wezterm#1501]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220103-233836-9919745d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The main terminal area has a padding all around it.
This is a little hard to describe verbally so here is a screenshot:
![image](https://user-images.githubusercontent.com/38166823/148031647-026a1dae-b22f-47d1-a8a7-bf8929a4e3f7.png)

Notice that the tabs are were they need to be but nvim has black all around it.
This also noticeable outside of TUI apps since the prompt is affected by it and all output doesn't reach to the very end

### To Reproduce

This has been happening for a couple of versions but it also happens in the current main branch, and it happens with my config or without (`-n` flag)
So to reproduce just start wezterm and open any tui app such as vim for maximum effect

### Configuration

no config

### Expected Behavior

The output should take the whole window

### Logs

```
 2022-01-04T08:41:22.422Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-39340
 2022-01-04T08:41:22.540Z INFO  wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon RX 6800 (SIENNA_CICHLID, DRM 3.42.0, 5.15.12-zen1-1-zen, LLVM 13.0.0)4.6 (Compatibility Profile) Mesa 21.3.3 is_context_loss_possible=false wezterm version: 20220103-233836-9919745d
```

### Anything else?

Not sure if it's relevant but I'm using a tilling wm (dwm), although the bug occurs when starting wezterm while in floating mode as well

**Comment by wez** [comment]
Take a look at https://wezfurlong.org/wezterm/config/lua/config/window_padding.html

**Comment by SpyrosRoum** [comment]
Oh wow, okay,
Is there a reason there is a default padding at all? I really don't see how it helps

**Comment by wez** [comment]
It looks nicer in the default configuration

**Comment by Monirzadeh** [comment]
> 

I set
```
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
```
but still have padding
