### ISSUE TITLE
Problem with the tilde (~) character in wezterm 

### ISSUE THREAD

**Issue by erf** [wez/wezterm#151]
## Describe the bug

I have a problem with typing the `tilde (~)` character in the wezterm.

I have a US keyboard, but i'm using Norwegian as input source. 

I have disable my `.wezterm.toml` for this and i only have a limited `.zshrc` ( yes using Zsh ).

In other applications i can type `Ctrl+]` to create the tilde character, but in wezterm the output is either nothing, if i have `set -o vi` disabled in my `.zshrc`, else it is  `^` and sometimes `¨~`, so kind of random.

My other `.zshrc` settings are as follows:
```
set -o vi
LANG=en_US.UTF-8
LC_COLLATE=C
export LC_ALL=en_US.UTF-8
```
If i remove these settings, as mentioned before, typing utf-8 characters like `ø` produces `�ø`, and if i then press `delete` the cursors just steps over both characters to the left + 1. This is a different problem, but it seem related.

So this is a weird one and probably related to my keyboard, language, environment settings or font.. but with Terminal and iTerm2 it seem to work as expected.

## Environment (please complete the following information):

 - OS: macOS
 - Frontend:  OpenGL
 - Version: please run `wezterm -V` and include its output here

## To Reproduce

Have the same Norwegian input configuration on a US keyboard as mentioned and try to type the tilde character by pressing `Ctrl+]`.

**Comment by ImportTaste** [comment]
Just to be clear, you're also using zsh in Terminal and iTerm2 without issue?

**Comment by erf** [comment]
@ImportTaste yes, i have no issues there

**Comment by erf** [comment]
Nice! =D
