### ISSUE TITLE
Activating pane by index as done with tabs

### ISSUE THREAD

**Issue by NikosEfthias** [wez/wezterm#1517]
**Is your feature request related to a problem? Please describe.**
One has to navigate to the pane either by manually cycling through with the `ActivatePaneDirection` command or moving away from the keyboard and using a mouse. 

**Describe the solution you'd like**
It would be amazing to have an action to activate a pane by an index such as `ActivatePane=2`

**Describe alternatives you've considered**
Using `ActivatePaneDirection=Prev/Next` is the only thing comes remotely close to this feature at the moment

**Comment by wez** [comment]
Sounds reasonable; this is implemented in 3c6bc2c366c5c557efc1d72961a1f9b217e6e17a which should be available in a nightly download within the next hour.
