### ISSUE TITLE
Expand relative wezterm variable from toml

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#152]
The new [set_environment_variables] feature, added as part of servicing #146 is really useful, and I can think of a really useful purpose outside of its originally intended purpose right away: being able to have some IDE stuff in a portable wezterm subdirectory that requires some environmental variables pointing at the right locations. Normally I have to handle setting up a portable compiling environment like that using batch files, but this would be MUCH easier.

My suggestion would be to use angle brackets since those are reserved characters on the windows filesystem (and very uncommonly used elsewhere)... like `<wtdir>`.

**Comment by wez** [comment]
What you're effectively asking for here is the ability to script the configuration.  TOML is not a great fit for this sort of thing; it has no native interpolation support and requires explicitly coding for each option.  Even the path resolving logic that we have already has to be specially handled.  I have an alternative configuration language in the works that I think will be better suited for this class of problem, but it will take a bit of time to flesh that out and wrap it up.

One thing that could be made to happen sooner is for wezterm to export a couple of environment variables to its child processes:

* `WEZTERM_EXECUTABLE` would be the full path to the wezterm executable
* `WEZTERM_CONFIG_FILE` would be the full path to the `wezterm.toml` file that should be used (`wezterm` already reads this environment variable on startup if set; having it export it again gives some symmetry)

With those set, your scripts could then use those to set up the appropriate paths; that may be a slight improvement over your current arrangement.

**Comment by ImportTaste** [comment]
That would work well, yeah!

**Comment by ImportTaste** [comment]
Ah, I didn't realize the files would be included in the path. CMD's substring replacement syntax requires the variable to already be expanded, so if did something like `WEZTERM_DIRECTORY = "%%WEZTERM_EXECUTABLE%:\\wezterm.exe=%"`, well, that wouldn't work.

I guess I could just make a directory named wezterm.exe.d and make the variable `WEZTERM_DIRECTORY = "%WEZTERM_EXECUTABLE%.d"` but maybe there's something obvious I'm missing.

**Comment by ImportTaste** [comment]
👍
