### ISSUE TITLE
Scrollbar thumb moves offscreen

### ISSUE THREAD

**Issue by nh2** [wez/wezterm#1525]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The thumb gets rendered off-screen when there is a lot of output.

For example, after typing dmesg, the thumb is invisible:

https://user-images.githubusercontent.com/399535/148723616-935b2f81-bebe-49e3-9548-5e53297ced96.mp4

The video shows how I scroll it into screen, and back off-screen.

The more height I give the window, the less it goes offscreen. If I fullscreen the window, it looks like it's fully onscreen

### To Reproduce

Make wezterm window with ~300 pixels height, type `dmesg` on Linux.

(I haven't reproduced on nightly because I haven't had the time to look how to build that yet.)

### Configuration

```lua
return {
  enable_scroll_bar = true,
  colors = {
    scrollbar_thumb = "#f00",
  }
}
```

### Expected Behavior

Full height of the thumb is always on-screen.

**Comment by davidrios** [comment]
@wez I'm working on this now, it's a general issue, not platform dependent.
