### ISSUE TITLE
Hot config reload does not work with persistent SSH multiplexing

### ISSUE THREAD

**Issue by nh2** [wez/wezterm#1526]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When using `wezterm connect` to a remote SSH server (from Linux X11 to Linux), changing the remote side's `scrollbar_thumb` in the config file does not result in hot reloading the config and the thumb changing colour.

Only when I type `reset` does the thumb update the colour.

### To Reproduce

`wezterm connect` to an SSH machine, change config file to change thumb colour to e.g. red.

### Configuration

Remote side's config (Linux server):

```lua
return {
  default_prog = {"zsh", "--norcs"}, -- to ensure that zsh does not change the palette for this repro (it renders without any colours)
  enable_scroll_bar = true,
  colors = {
    scrollbar_thumb = "#aaa",
  },
}
```

**Comment by wez** [comment]
This is fixed in `main`.  Config reloading was working, it's just that nothing knew to suggest to the client that the palette may have changed.

**Comment by nh2** [comment]
@wez Thanks!
