### ISSUE TITLE
Zooming in and out is broken 

### ISSUE THREAD

**Issue by AbleTheAbove** [wez/wezterm#1527]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

zooming in breaks tab text rendering

Opening new tab fixes the tab bar

### To Reproduce

zoom in and out via the ctrl + + and ctrl + - keys

### Configuration

no config

### Expected Behavior

Zoomed in text scales

### Logs

04:26:45.983 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-4451
04:26:46.439 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 550 / 550 Series (POLARIS12, DRM 3.42.0, 5.15.12-arch1-1, LLVM 13.0.0) 4.6 (Compatibility Profile) Mesa 21.3.3 is_context_loss_possible=false wezterm version: 20220101-133340-7edc5b5a
05:37:46.948 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 1

### Anything else?

![image](https://user-images.githubusercontent.com/75036841/148760464-3b207246-a9c1-4bfd-9903-12183b7a36bb.png)
![image](https://user-images.githubusercontent.com/75036841/148760505-13e6d5ae-e4d3-4ef3-ba4a-6c404a0d8326.png)

**Comment by wez** [comment]
I can't reproduce this here.  Is there something in particular that you are running that might encourage it to repro?  This sort of issue usually correlates with using a lot of different glyphs or lots of graphics.
