### ISSUE TITLE
Degraded startup time

### ISSUE THREAD

**Issue by erf** [wez/wezterm#1529]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

e8995c53708cba6e0e4c569618de3fae6f4c34bf

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I believe the startup time on macOS was degraded in the mentioned commit. I did a visual comparison between the commit mentioned and the previous one and it seem like there is a difference. Like a few hundred milliseconds or so. I added a screen capture comparing the two versions.

### To Reproduce

Open wezterm, compare to prev version.

### Configuration

no config

### Expected Behavior

I expect startup time to remain fast

### Logs

23:25:37.312 INFO wezterm_mux_server_impl::local > setting up /Users/erlend/.local/share/wezterm/gui-sock-4313
23:25:37.451 INFO wezterm_gui::termwindow > OpenGL initialized! Apple M1 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220107-171235-e8995c53

### Anything else?

https://user-images.githubusercontent.com/1562523/148849398-97007001-ba64-4280-bdd0-88d45602bfb1.mov

**Comment by wez** [comment]
Good catch; this is fixed now in `main`!
