### ISSUE TITLE
Low responsiveness if started in RDP session

### ISSUE THREAD

**Issue by kaddkaka** [wez/wezterm#1530]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220110-203101-58d969e7

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When Wezterm is started in an Windows RDP session, the responsiveness of keyboard input seems to go down a lot. The terminal feels very slow/sluggish. When I move the the cursor in vim I can do up/down about 8 times before I see the cursor move and then I just have time to see it go up/down once(1) instead of four(4) times.

Even if I close my RDP session and continue to use the terminal on the host machine the terminal feels slow. If I restart wezterm on the host machine, it feels quick and responsive again.

### To Reproduce

1. Start Wezterm in Windows RDP session (started with ssh connection: `wezterm-gui.exe ssh user@remote_ip`), (attach to tmux session, with nvim application in the foreground) - slow.
2. Log out of RDP and use the same terminal window on host machine - still slow. 
3. Restart Wezterm on host machine - quick.

### Configuration

no config

### Expected Behavior

No performance difference when started in RDP session.

**Comment by wez** [comment]
Please do include the logs you see from the debug console; press CTRL-SHIFT-L to see it and copy and paste them.
I'd like to see them from the window you start in RDP and also for the one you start from outside RDP.
