### ISSUE TITLE
Cursor only shor half of Chinese hanzi

### ISSUE THREAD

**Issue by epii1** [wez/wezterm#1533]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

<img width="77" alt="image" src="https://user-images.githubusercontent.com/2030591/149057012-beb5c254-e214-4348-a232-8b6dad2415b8.png">

### Configuration

```lua
local wezterm = require 'wezterm';
return {
    font_size = 24,
    font = wezterm.font_with_fallback({
        {family='Inconsolata', weight="Regular"},
        {family="InconsolataGo Nerd Font", weight="Regular"},
        {family="Apple Color Emoji"},
    }),
    use_ime = true,
    unicode_version = 14,
    hide_tab_bar_if_only_one_tab = true,
    scrollback_lines = 0,
    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
    },
    native_macos_fullscreen_mode = true,
    check_for_updates = true,
    check_for_updates_interval_seconds = 86400,
    colors = {
        cursor_bg = '#eeeeee',
        cursor_fg = '#282828',
        cursor_border = '#eeeeee',
        foreground = '#eeeeee',
        background = '#000000',
        ansi = {
            '#282828',
            '#f43753',
            '#c9d05c',
            '#ffc24b',
            '#b3deef',
            '#d3b987',
            '#73cef4',
            '#eeeeee',
        },
        brights = {
            '#4c4c4c',
            '#f43753',
            '#c9d05c',
            '#ffc24b',
            '#b3deef',
            '#d3b987',
            '#73cef4',
            '#feffff',
        }
    }
}
```

### Expected Behavior

highlight the full hanzi like `国`

**Comment by wez** [comment]
That was fixed in b05cb1241e3bce8b6c7c5b068606bce71f4f2ea6 and 59f5b849c56d90e2bc2b2e0555f265e99750d136
Please try the nightly download!

![image](https://user-images.githubusercontent.com/117777/149071906-3d71231e-5e80-43c5-9fb9-1b5041b2845c.png)
