### ISSUE TITLE
Poor performance compare with Alacritty

### ISSUE THREAD

**Issue by kevinhwang91** [wez/wezterm#1535]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220110-203101-58d969e7

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Colorful `undercurl` is the reason for me trying `wezterm` . I appreciate `wezterm` giving a lot of options for `alacritty` users, I have configured the `wezterm` as the same look and keymaps of `alacritty`.  However, when I move the cursor inside Neovim under `wezterm`  or scroll the screen under `wezterm`, I feel so lagging compare with `alacritty` .

### To Reproduce

1. `nvim -u NORC` test under `wezterm`, open a large file, type `j` last a few seconds, observe the screen.
2. Repeat step 1, but test under `alacritty`;

FYI: the CPU usage of `wezterm` during scrolling is low but `alacritty` is nearly 100%.

### Configuration

no config

### Expected Behavior

I don't expect `wezterm` will get the same performance as `alacritty`, but it should not lag for normal use.

**Comment by wez** [comment]
For me, alacritty and wezterm appear to perform the same for this scenario:

* `nvim -u NORC`
* `:help`
* hold `j` to scroll down

I think there is something missing about your environment/test scenario that is influencing what you are seeing, but the problem, as described above, doesn't capture enough information to reproduce it.

A few things that might influence this are:
* OS level key repeat speed
* The content in the file that you are scrolling
* the size of the screen (both in pixels and cells)
* font configuration (eg: `font-config` cache may need rebuilding, or may have unusual configuration)

and so on.

In general: I do not give much weight to bug reports that compare wezterm to alacritty, as the comparisons are often flawed.
https://github.com/wez/wezterm/issues/1453#issuecomment-1000068807 has more context on some of the architectural differences that can impact performance and how I consider performance in wezterm.
