### ISSUE TITLE
OSC "133;I" Semantic Prompt not handled

### ISSUE THREAD

**Issue by RoniJacobson** [wez/wezterm#1539]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220112-071616-4452fbe7

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I tried setting up semantic prompts in cmd.exe. Because I can't make output of my choice appear after a program is run, I tried using the `I` command, which is meant to terminate the command on a new line. This worked kind of strangely, and after looking at the logs I saw the code was not being handled properly.

### To Reproduce

Running
```bash
printf "\e]133;I\a"
```
in a linux shell should do it

### Configuration

```lua
return {
    set_environment_variables = {
      prompt = "$E]133;N\a$P$G $E]133;I\a$E[0m",
    }
  }
```

### Expected Behavior

I expected the rest of the line to be marked semantically as a command, so I could scroll to places based on that properly.

### Logs

```
17:14:36.801 INFO wezterm_mux_server_impl::local > setting up C:\Users\...\.local/share/wezterm\gui-sock-3096
17:14:36.803 INFO wezterm_client::discovery::windows > published gui path as gui-sock-3096
17:14:36.860 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
17:14:36.960 WARNING wezterm_term::terminalstate::performer > unhandled: MarkEndOfPromptAndStartOfInputUntilEndOfLine
17:14:37.002 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) HD Graphics 520 4.5.0 - Build 27.20.100.8854 is_context_loss_possible=true wezterm version: 20220112-071616-4452fbe7
```

**Comment by RoniJacobson** [comment]
After looking at the code, I think that supporting the escape code itself is easy - the difficult part is handling leaving the input semantic type when a new line is found

**Comment by wez** [comment]
I've pushed a commit that I think resolves this; it should show up in the nightly downloads within the next hour.
Please let me know how this works out for you!
