### ISSUE TITLE
`option` key in macOS doesn't work properly with Kakoune.

### ISSUE THREAD

**Issue by leira** [wez/wezterm#1541]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220112-071944-f6e56aab

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I use Kakoune editor. It relies on `alt` key heavily. One example is `<alt-h>`, it jumps to the head of the line. In the default macOS Terminal, I have to set "Use Option as Meta key" to make the `alt` combination keys work.

I used `xxd` to see the difference. In Terminal, with "Use Option as Meta key" off, press `<alt-h>` prints out `˙`:
```
> xxd
˙˙˙˙˙˙˙˙
00000000: cb99 cb99 cb99 cb99 cb99 cb99 cb99 cb99  ................
```

In Terminal, with "Use Option as Meta key" on, press `<alt-h>` prints out `^[h`:
```
> xxd
^[h^[h^[h^[h^[h^[h^[h^[h
00000000: 1b68 1b68 1b68 1b68 1b68 1b68 1b68 1b68  .h.h.h.h.h.h.h.h
```

So I suppose `^[h` for `<alt-h>` is the behavior I need.

Now with Wezterm, `<alt-h>` doesn't work with Kakoune. Run `xxd`, press `<alt-h>` I got `˙`:

```
> xxd
˙˙˙˙˙˙˙˙
00000000: cb99 cb99 cb99 cb99 cb99 cb99 cb99 cb99  ................
```

According to the document [macOS Left and Right Option Key](https://wezfurlong.org/wezterm/config/keys.html#macos-left-and-right-option-key), I played with `send_composed_key_when_left_alt_is_pressed`, `use_ime` and `use_dead_keys`. I tried all the combinations of these 3 options, but all get the same `xxd` result.

What configuration is needed to have `^[h` for `<alt-h>` key on macOS?

### To Reproduce

1. Start wezterm
2. run `xxd`
3. type `<alt-h>` 8 times.

### Configuration

﻿﻿  -- attempt to fix macOS option keys for Kakoune
  -- send_composed_key_when_left_alt_is_pressed = false,
  -- send_composed_key_when_right_alt_is_pressed = true,
  -- use_dead_keys = true,
  -- use_ime = true,

### Expected Behavior

Expect `xxd` to print `^[h` when `<alt-h>` is pressed:

```
> xxd
^[h^[h^[h^[h^[h^[h^[h^[h
00000000: 1b68 1b68 1b68 1b68 1b68 1b68 1b68 1b68  .h.h.h.h.h.h.h.h
```

### Logs

14:08:34.345 INFO wezterm_mux_server_impl::local > setting up /Users/leira.hua/.local/share/wezterm/gui-sock-22903
14:08:34.495 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon Pro 5300M OpenGL Engine 4.1 ATI-4.7.101 is_context_loss_possible=falsewezterm version: 20220110-083110-5d52902b
14:08:55.904 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 0
14:08:58.256 WARNING wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(1)
14:08:58.256 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: ">5u"
14:08:58.256 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: "22t"
14:16:55.184 ERROR wezterm_mux_server_impl::local > decoding a PDU: reading PDU length: EOF while reading leb128 encoded value
15:02:44.612 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: "23t"
15:02:44.612 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: "<u"
15:02:44.612 WARNING wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
15:02:47.145 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 0
>

**Comment by wez** [comment]
What keyboard layout do you have configured in the macOS keyboard settings?

**Comment by wez** [comment]
Please also enable key event debugging: https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html
and share what is logged when you press those keys!

**Comment by wez** [comment]
I see; this reproduced on my US layout. I've pushed a fix; it should show up in the nightly download within about an hour from now.

**Comment by leira** [comment]
That's really quick! Thanks!
