### ISSUE TITLE
Feature request: add subcommand to change the working dir of current tab

### ISSUE THREAD

**Issue by QiangF** [wez/wezterm#1545]
Usecase is to open wezterm from emacs and set the directory to emacs buffer's directory. 
So to make wezterm work with:
https://github.com/davidshepherd7/terminal-here
A suggestion is to add a cwd subcommand for this: 
 
    wezterm cwd "dir to switch to"

Thank you!

**Comment by wez** [comment]
You can use: `wezterm start --cwd "dir to switch to"` for this

See `wezterm start --help` and https://wezfurlong.org/wezterm/config/launch.html#specifying-the-current-working-directory

**Comment by QiangF** [comment]
But it opens in a new window, I would prefer to open a new tab.

**Comment by wez** [comment]
In that case, look at: `wezterm cli spawn --cwd "dir to switch to"`.
