### ISSUE TITLE
Add option to theme the tab divider

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#1547]
The vertical seperator between the tabs can currently not be styled:
![grafik](https://user-images.githubusercontent.com/11978847/149576797-7b996a52-08b7-44ac-980c-89e112d26275.png)

**Comment by wez** [comment]
It's not documented yet, but you can do:

```lua
return {
  colors = {
    tab_bar = {
      inactive_tab_edge = "red",
    }
  }
}
```

**Comment by wez** [comment]
@xpufx ah, the docs have the wrong example.  https://github.com/wez/wezterm/issues/1547#issuecomment-1013562903 above shows how to do this.  I've pushed a fix to the docs and it should show up there in a few minutes.

**Comment by xpufx** [comment]
Thanks !
