### ISSUE TITLE
cursor style isn't right sometimes

### ISSUE THREAD

**Issue by hosxy** [wez/wezterm#1548]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220114-222835-170bb31f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I set `default_cursor_style =  SteadyBar`,
+ when cursor at end of line, it is right
![image](https://user-images.githubusercontent.com/17108640/149625523-5b67972c-ef7f-4d3f-8da8-0f240192e021.png)
+ when cursor  betwen of two chinense charactor, it will be wrong
![image](https://user-images.githubusercontent.com/17108640/149625641-b7d758dc-e099-48fe-90da-5effbd4995eb.png)
+ when cursor  betwen of two ASCII charactor, it's right
![image](https://user-images.githubusercontent.com/17108640/149625712-d9fb2bb5-27bd-4817-ba9e-4079e9636ed6.png)
+ when cursor  betwen of ASCII charactor and chinese charactor 
  + when ascii charactor  on the left, it will be wrong
![image](https://user-images.githubusercontent.com/17108640/149625779-fb547702-b976-4133-9925-d03d16e1072f.png)
  + when chinese charactor  on the left, it's right
![image](https://user-images.githubusercontent.com/17108640/149625793-7a7551c8-bb37-49fa-8bd7-eda23be3022e.png)

### Configuration

```
local wezterm = require 'wezterm';

return {
	-- 颜色主题
	color_scheme = "Material",
	
	-- 禁用连体
	harfbuzz_features = {"calt=0", "clig=0", "liga=0"},
	
	-- 开启 tab 栏
	enable_tab_bar = true,
	hide_tab_bar_if_only_one_tab = true,
	--use_fancy_tab_bar = false,
	
	-- 上下左右边距
	window_padding = {
		left = 4,
		--right = 4,
		top = 4,
		--bottom = 0,
	},
	
	-- 启用滚动条
	enable_scroll_bar = true,
	
	-- 光标类型为 竖线
	default_cursor_style = "SteadyBar",
	
	
	-- 按键绑定
	keys = {
		{key="c", mods="CTRL", action="Copy"},
		{key="v", mods="CTRL", action="Paste"},
		{key="t", mods="CTRL|ALT", action=wezterm.action{SpawnTab="DefaultDomain"}},
		{key="PageUp", action=wezterm.action{ScrollByPage=-1}},
		{key="PageDown", action=wezterm.action{ScrollByPage=1}},
	},
	
	window_frame = {
		active_titlebar_bg = "#ffffff",
		inactive_titlebar_bg = "#ffffff",
	},
	
	colors = {
		tab_bar = {
			background = "#ffffff",
			active_tab = {
				bg_color = "#ffffff",
				fg_color = "#16afca",
				--intensity = "Normal",
				underline = "Single",
				--italic = false,
				--strikethrough = false,
			},
		  
			inactive_tab = {
				bg_color = "#ffffff",
				fg_color = "#808080",
			},

			inactive_tab_hover = {
				bg_color = "#eaeaea",
				fg_color = "#909090",
				--italic = true,
			},

		  -- The new tab button that let you create new tabs
			new_tab = {
				bg_color = "#ffffff",
				fg_color = "#000000",
			},

			new_tab_hover = {
				bg_color = "#eaeaea",
				fg_color = "#000000",
				--italic = true,
			},
		}
	}
}
```

**Comment by wez** [comment]
Thanks for the report!  This is now fixed and should be available in the nightly download within the next hour!

**Comment by hosxy** [comment]
Thanks for your work，Now it‘s always right
