### ISSUE TITLE
Add support for moving a tab in a new window

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#1550]
**Is your feature request related to a problem? Please describe.**
When you have opened multiple tabs, but want to move one of them to a separate screen, that is not possible.

**Describe the solution you'd like**
An option to move a tab into a new window.

This could be similar to as web browsers do it with support of moving it back into an existing window via drag+drop, but that is not something I need.

**Comment by wez** [comment]
Duplicate of #1253
