### ISSUE TITLE
Add left status bar

### ISSUE THREAD

**Issue by gegoune** [wez/wezterm#1561]
**Is your feature request related to a problem? Please describe.**
I would like to be able to format status bar in its entirety, not only right hand side with `set_right_status`.

**Describe the solution you'd like**
Replace `set-right-status` in favour of more generic status bar generator. I have something similar to vim's statusline in mind where one can influence generation of entire bar.

I can think of situation where current left hand side, tabs bar, is returned by builtin function and together with some control characters for aligning content, placed as per user's desire.

```lua
wezterm.on('update-status-bar', function(window, _)
  window:set_status_bar(
    wezterm.format { { Text = '[' .. window:active_workspace() .. ']' .. '<center from here>' ..window.tabwidget .. '<right align from here>' .. wezterm.strftime '%Y-%m-%d %H:%M '  } }
  )
end)
```

**Describe alternatives you've considered**
Leave things as they are, I am not sure if added complexity is worth it. tmux does have such flexibility though.

I am not sure about rate of refreshing the entire bar.

**Additional context**
As you mention on discussions' topic and I agree, this is rather low priority. I can definitely live with current degree of configurability here. Just putting it here as a food for thought, maybe someone (or yourself) can come up with sensical and better interface than one above.

(Loving wezterm, amazing job! Thanks a lot!)

**Comment by wez** [comment]
I don't want to make the whole tab bar get parsed out of text; there are more structured ways to tackle that.
I'd prefer to interpret this issue as a request for a `set_left_status_bar` to mirror the current right status bar.
In my mind, the left status bar is a bit simpler than the right status bar, as it can unconditionally occupy the left space before the tabs are rendered.  (The right bar has some math gymnastics to right align and truncate/hide behind other text).

**Comment by gegoune** [comment]
Feel free to completely scrap that issue, it's not that important at all.

**Comment by Lenbok** [comment]
A left-status-bar would be great. I would personally use it to show the workspace name (at the moment I have it on the right in wezterm, but I conceptually think it belongs closer to the tabs).

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Lenbok** [comment]
@wez Just to check in here, there is a `update_right_status` event but no `update_left_status` event. Are you envisioning that we would typically call both `set_left_status` and `set_right_status` from a function hooked into `update_right_status`? Or do you have a recommendation of where else to hook it?

**Comment by wez** [comment]
Ah, the `update-right-status` event is triggered whenever the status line needs to be updated, regardless of whether it is left or right.

**Comment by gegoune** [comment]
Thanks for adding it! Perhaps `update-right-status` could be aliased by `update-status` event with former getting removed with some deprecation notice and period?
