### ISSUE TITLE
shaping: '!=' ligature in "Recursive Mono Linear Static" is double wide but shows as single cell

### ISSUE THREAD

**Issue by pinpox** [wez/wezterm#1563]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The text in this image is `deviceFilter = ''path!~"^(/var/lib/docker|/nix/store).*"'';` Notice the ~ is overlayed
![image](https://user-images.githubusercontent.com/1719781/149948500-66ee138b-1bbf-4e88-a337-4466dafc2a14.png)

Notice the `--` in `--help` are overlayed
![image](https://user-images.githubusercontent.com/1719781/149948567-f6b8f1bb-db39-42d5-9d54-80c173c3979f.png)

### To Reproduce

Use wezterm with [this font configuration](https://github.com/pinpox/nixos/blob/main/home-manager/modules/wezterm/wezterm.lua#L69-L103).

### Configuration

https://github.com/pinpox/nixos/blob/3201733216d50e2edae6d8364ab776b601c8cc79/home-manager/modules/wezterm/wezterm.lua

### Logs

```
 2022-01-18T13:45:20.255Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-7450
 2022-01-18T13:45:20.322Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 21.3.3 is_context_loss_possible=false wezterm version: 20220101-133340-7edc5b5a
```

### Anything else?

Font works fine in alacritty

**Comment by pinpox** [comment]
Upon further digging, the problem seems to happen for characters after a ligature. Here is another example
![image](https://user-images.githubusercontent.com/1719781/149951163-307d7493-90f3-4bb5-895f-14ab7c54408d.png)
The text is `test !=test`

**Comment by wez** [comment]
Please run and share the output from:

```
wezterm ls-fonts --text "test !=test"
```

**Comment by pinpox** [comment]
> Please run and share the output from:
> 
> ```
> wezterm ls-fonts --text "test !=test"
> ```

```
» wezterm ls-fonts --text "test !=test"
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=409  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=287  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=398  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=409  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=1    wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=846  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=409  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=287  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=398  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
test !=test \u{74}\u{65}\u{73}\u{74}\u{20}\u{21}\u{3d}\u{74}\u{65}\u{73}\u{74} glyph=409  wezterm.font("Recursive Mono Linear Static", {weight="Medium", stretch="Normal", italic=false})
                             /nix/store/4dlvwl90n89mqb112808b92z94nqzydk-home-manager-path/share/fonts/truetype/RecursiveMonoLnrSt-Med.ttf, FontConfig
```

**Comment by wez** [comment]
What's happening here is that that font defines that `!=` ligature as a single double-wide glyph.
Because the shaping library gives limited insight into how ligatures are substituted, wezterm doesn't realize that that glyph should advance by two cells.

What you can do for now is add `experimental_shape_post_processing = true` to your config to adjust the shaping logic to use a differently-flawed approach to detecting this situation.  It appears to resolve this case for me, but you may find other cases where it produces surprising results!

**Comment by pinpox** [comment]
I'll try that workaround later and report back. To be clear though, this problem is new and was not happening before. I suppose there have been changes recently in the postprocessing then?

**Comment by wez** [comment]
I checked out that commit and built it; it behaves the same way with that font. I don't think the shaping code has changed in a really long time; since I made `experimental_shape_post_processing` an option.  It was on by default for a while, but it didn't solve enough of the problems around #478, which I only recently solved in a different way.

**Comment by pinpox** [comment]
Setting `experimental_shape_post_processing = true` solves the issue with version `20220101-133340-7edc5b5a` (current version in nixpkgs).

> I checked out that commit and built it; it behaves the same way with that font. I don't think the shaping code has changed in a really long time; since I made `experimental_shape_post_processing` an option. It was on by default for a while, but it didn't solve enough of the problems around #478, which I only recently solved in a different way.

This is very strange. I just rebuild [that older version](https://github.com/pinpox/nixos/blob/main/packages/wezterm-nightly/default.nix#L31-L37) and can confirm that the problem does *not* happen for me in that one. Not sure why. 

There has to have been some change between `24875004f66640e220bb1e4369afc93e5417e0c0` and `20220101-133340-7edc5b5a` that changed something, everything else (including the font) is the same system.

**Comment by pinpox** [comment]
I just noticed adding `experimental_shape_post_processing = true` has broken support for emoji fonts in my configuration so it's not really a fix.

**Comment by wez** [comment]
7edc5b5 is different from the version you mentioned earlier; I'll look at that when I'm next in the mode for debugging this

**Comment by wez** [comment]
bisected to 225e7a124396362f2233394156d45cc156d438b5

**Comment by wez** [comment]
"fixed" in `main`, but at the cost of unicode version conformance in some configurations

**Comment by pinpox** [comment]
Thank you! I can confirm the problem is solved for me on latest main.
