### ISSUE TITLE
Font size changes when switching from laptop to clamshell mode

### ISSUE THREAD

**Issue by arnaudlimbourg** [wez/wezterm#1566]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220117-081618-7eec41c2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using a macbook in clamshell mode wezterm is started with a font size of 16.

![image](https://user-images.githubusercontent.com/53919/150102718-9a6c9424-a237-4eec-b56c-7c86347cd359.png)

Unplugging it from the external screen and using the laptop screen wezterm was unresponsive and I had to restart it.

Plugging it back in clamshell into the external screen wezterm displays a font that increased in size.  
![image](https://user-images.githubusercontent.com/53919/150102624-7c747172-6693-47fa-b8c6-0147f46b57e9.png)

### Configuration

` font_size = 16.0,`

**Comment by gwww** [comment]
I have a similar, but different issue. I'll comment here as it seems like it could be the same bug.

My situation is that I have a monitor plugged into my laptop. Wezterm running on laptop screen, Mac M1, using a a "regular" size font ~13pt. Monitor is widescreen 3440x1440.

I leave laptop open, unplug monitor, and Wezterm switches to ~4pt font. The only way that I know to fix this is to quit Wezterm and restart. It restarts using normal font size.

So you can see why I say this is similar. I end up with smaller font size while OP gets a bigger font size.

**Comment by wez** [comment]
I've pushed a commit that might help with this: I'm not in a position to easily test this scenario, but I think this is the right area of the code.  It will show up in a nightly build within an hour of this comment being posted.  Please give it a try and let me know!
