### ISSUE TITLE
Feature Request: Make it possible to connect to a remote wezterm-mux-server through an existing ssh tunnel.

### ISSUE THREAD

**Issue by leira** [wez/wezterm#1568]
**Is your feature request related to a problem? Please describe.**
Because of the limitation of libssh, wezterm doesn't support ForwardAgent. It limited the use cases wezterm can support. If an ssh setup needs ForwardAgent, it is really hard to connect to an ssh host and use wezterm for multiplexing. Please refer to #1567.

**Describe the solution you'd like**
If wezterm can connect to a remote mux server through an existing ssh tunnel, it can work around the ForwardAgent issue.

**Describe alternatives you've considered**
1. Make libssh to support ForwardAgent. It is a really longshot, if ever possible.
2. Make libssh2 to support ForwardAgent. Same.

**Comment by leira** [comment]
wezterm-mux-server can serve through a unix socket file. A possible solution is to use `ssh` to forward connections to a local socket file to the remote socket file. I tried in #1567, but couldn't get it work yet.

**Comment by leira** [comment]
* My current understanding of the structure of wezterm connect is:
  * `wezterm-mux-server` is the mux server which runs one instance on one
    machine. It creates a socket file and listen on it. A socket file name can
    be specified in config or generated if not configed.
  * `wezterm connect unix_domain` command connect to a socket file specified
    with `sock_path` to talk to a `wezterm-mux-server`, to be a UI of a domain
    maintained within the mux server. Or if a `proxy_command` is specified,
    rather than connect to `sock_path`, it will run the command in
    `proxy_command`, and use its input and output as a way to communicate to a
    mux server.
  * `wezterm cli proxy` is a typical `proxy_command`, it checks if a
    `wezterm-mux-server` is already running. If not it will launch
    `wezterm-mux-server`. Then it connects its own input and output to the
    socket file of `wezterm-mux-server`, acting as a transparent tunnel.

* To verify this understanding, I manually recreated a
    connection structure locally, to see if this structure works? 
  * Run `wezterm-mux-server` in a terminal, so I can see logs.
  * In a unix domain named `proxy` set `proxy_command` to `wezterm cli proxy`,
    without a `ssh` tunnel.
  * `wezterm connect proxy`, to see if it works.
  * It works! Though there was no error message printed on the server side
    when wezterm connects and started a terminal, I saw the session is
    preserved between each `wezterm connect`. And killing `wezterm-mux-server`
    kills the session.
  * So this structure of `wezterm connect` -> `wezterm cli proxy` -> `wezterm-mux-server` is correct.

* Then I need to make sure a clean tunnel is created, and the communication is accurate. I created a tunnel with `socat` and `ssh` to a socket file.
  * on server side, run `socat UNIX-LISTEN:/tmp/socat.sock -` to listen to a
    socket file and connect with STDIO, so I can interact through the screen.
  * on local side, run
    `socat - EXEC:'ssh cruise "/home/leira.hua/bin/with-nix" socat - /tmp/socat.sock'`. 
    `socat` connects STDIO, triggers to ssh to the server side, run `socat` to
    connect its IO to the socket file being listened on. Then I can interact
    through screen.
  * I saw both side communicated accurately.


* Now my attempt to a solution:
  * On server side, run `wezterm-mux-server` in a terminal, so I can see logs.
  * on local side, Set the `proxy_command` to:
    ```lua
    proxy_command = {
      "socat",
      "-r", "/Users/leira.hua/temp/l2s.bin",
      "-R", "/Users/leira.hua/temp/s2l.bin",
      "-",
      "EXEC:'ssh host wezterm cli proxy'",
    },
    ```
  * on local side, run `wezterm connect cruise`.
  * It didn't work. I can see 2 lines printed on the server side. It is a good sign, at least 2 sides talked:
    ```
     2022-01-23T00:02:32.608Z ERROR wezterm_mux_server_impl::local > decoding a PDU: reading PDU length: EOF while reading leb128 encoded value
     2022-01-23T00:02:34.683Z ERROR wezterm_mux_server_impl::local > decoding a PDU: reading PDU length: EOF while reading leb128 encoded value

    ```
  * On the client side, I saw these error lines:
    ```
     2022-01-23T00:02:32.607Z ERROR wezterm_client::client  > Error while decoding response pdu: failed to fill whole buffer
     2022-01-23T00:02:32.608Z ERROR wezterm_gui             > Please install the same version of wezterm onboth the client and server! The server reported error 'Error while decoding response pdu: failed to fill whole buffer' while being asked for its version.  This likely means that the server is older than the client.
    ; terminating
     2022-01-23T00:02:32.608Z ERROR mux::connui             > while running ConnectionUI loop: recv_timeout: channel is empty and disconnected
    ```
  * Dump of the communications through `socat`:
  * From client to server:
    ```
    > xxd l2s.bin
    00000000: 0201 1a                                  ...
    ```
  * From server to client:
    ```
    > xxd s2l.bin
    00000000: 1c01 1b0a 1832 3032 3230 3130 312d 3133  .....20220101-13
    00000010: 3333 3430 2d37 6564 6335 6235 61         3340-7edc5b5a
    ```

It seems server did respond its version back to the client. What is the problem here? What is `ERROR wezterm_client::client  > Error while decoding response pdu: failed to fill whole buffer`?

**Comment by leira** [comment]
I attempt to reproduce this issue on my Macbook Pro locally. 
* I enabled ssh server on the Macbook Pro. Copied the public key into
    `~/.ssh/authorized_keys`. `ssh localhost` succeed.
  * Add a new unix domain `ssh-proxy`:
    ```lua
    {
      name = "ssh-proxy",
      proxy_command = {
        "socat",
        "-r", "/Users/leira.hua/temp/l2ls.bin",
        "-R", "/Users/leira.hua/temp/ls2l.bin",
        "-",
        "EXEC:'ssh -T localhost wezterm cli proxy'",
      },
    },

    ```
  * `wezterm connect ssh-proxy` works!
  * Because it worked, the dumps are really long!
    ```
    >  l -l *ls*
    .rw------- 10k leira.hua 22 Jan 16:48  l2ls.bin
    .rw------- 30k leira.hua 22 Jan 16:48  ls2l.bin
    ```
  * client to server:
    ```
    > xxd -l 128 l2ls.bin
    00000000: 0201 1a22 0228 0c43 3032 474a 3837 594d  ...".(.C02GJ87YM
    00000010: 4436 4d09 6c65 6972 612e 6875 61a9 b203  D6M.leira.hua...
    00000020: d6ca b28f 0601 0203 0303 0418 0006 0516  ................
    00000030: 0001 0018 0306 1800 0607 1600 0137 3806  .............78.
    00000040: 0816 0001 3637 0a09 0c00 0200 3700 1e05  ....67......7...
    00000050: 0003 0a18 000a 0b0c 0002 0037 001e 0500  ...........7....
    00000060: 0a0c 0c00 0200 3700 1e05 000a 0d0c 0002  ......7.........
    00000070: 0037 001d 0500 0a0e 0c00 0200 3700 1c05  .7..........7...
    ```
  * server to client:
    ```
    > xxd -l 128 ls2l.bin
    00000000: e780 8080 8080 8080 8001 011b 28b5 2ffd  ............(./.
    00000010: 0058 e502 00f4 0411 1832 3032 3230 3131  .X.......2022011
    00000020: 382d 3139 3236 3434 2d36 3065 6130 3665  8-192644-60ea06e
    00000030: 3127 2f55 7365 7273 2f6c 6569 7261 2e68  1'/Users/leira.h
    00000040: 7561 2f62 696e 2f77 657a 7465 726d 2d6d  ua/bin/wezterm-m
    00000050: 7578 2d73 6572 7665 7201 2c2e 636f 6e66  ux-server.,.conf
    00000060: 6967 2e6c 7561 0300 2b04 4045 18c1 6665  ig.lua..+.@E..fe
    00000070: 0602 020a 5003 0401 0200 0000 1566 6973  ....P........fis
    ```

**Comment by leira** [comment]
With the help from @wez in the #wezterm:matrix.org, this issue is resolved. It was because I didn't have the same version of wezterm on the server side and on the client side. The wezterm on the server side was installed from nix, which is older. I used a recently nightly on the Macbook.

The local ssh server works because it has the same wezterm on both side. From the `xxd` dumps, the server response from the local ssh was different from the server response from the remote host. So the protocols are different, they don't talk to each other. Actually, the error message spelled out to me but I didn't see:
```
 2022-01-23T00:02:32.608Z ERROR wezterm_gui             > Please install the same version of wezterm onboth the client and server! The server reported error 'Error while decoding response pdu: failed to fill whole buffer' while being asked for its version.  This likely means that the server is older than the client.

```

I installed a wezterm.app with the same version as the server. Use full path to the command to make sure it runs the same version:
   ```
   > ~/Downloads/WezTerm-macos-20220101-133340-7edc5b5a/WezTerm.app/Contents/MacOS/wezterm connect host
   ```

It worked!

**Comment by leira** [comment]
Actually, `socat` was not neccessary. Now with the same version, a simpler solution is just use  `proxy_command = { "ssh", "-T", "host", "wezterm", "cli", "proxy" }`. That was the one @wez told me in the beginning, but I ran a full circle. The learning is great!

**Comment by leira** [comment]
The feature is already supported. Close this issue.

**Comment by nerosnm** [comment]
Thanks for the really detailed explanation of the process you went through with this! I'm trying to get this working, specifically so that I can have agent fowarding through a wezterm unix domain. I've got the following in my `wezterm.lua`:

```lua
unix_domains = {
  {
    name = "talitha",
    proxy_command = { "ssh", "-T", "-A", "talitha", "wezterm", "cli", "proxy" },
  },
},
```

If I connect to `talitha` just by running `ssh -A talitha`, agent forwarding works just fine. But `wezterm connect talitha`, while it connects just fine, doesn't appear to forward my agent. I've also tried adding this to my SSH config (even though it should be redundant with `-A`):

```
Host talitha
  ForwardAgent yes
```

Am I missing some piece of the puzzle here, or has there been a regression? @leira I'm not sure if there's some bit of config that I didn't see above or that you haven't mentioned, but I'd really appreciate your help.

**Comment by wez** [comment]
You may want to adjust https://wezfurlong.org/wezterm/config/lua/config/mux_env_remove.html in the wezterm.lua on the remote host

**Comment by nerosnm** [comment]
That doesn't seem to have helped, unfortunately. It seems like whether or not I include a `mux_env_remove = { }` section, the `$SSH_AUTH_SOCK` variable is empty whenever I connect through wezterm. When I connect with `ssh -A`, it's set to (e.g.) `/tmp/ssh-XXXXC8dNqf/agent.222975`.

**Comment by nerosnm** [comment]
`ls -al /tmp/ssh*` shows that each time I connect with `wezterm connect talitha`, the socket is different, and if I manually `export SSH_AUTH_SOCK=/tmp/ssh-XXXXC8dNqf/agent.222975`, then the forwarding works. So (at least according to my limited understanding of SSH) that socket is being created correctly, the environment variable just isn't being set.

**Comment by nerosnm** [comment]
I should add, also (and please let me know if at any point you'd like me to move any of this to a new issue) that if I right-click `+` in the tab bar and choose "Attach domain `talitha`", I get this:

```
Connect to Proxy(["ssh", "-T", "-A", "talitha", "wezterm", "cli", "proxy"])
Connected!
Checking server version
Please install the same version of wezterm on both the client and server! The server reported error 'Error while decoding response pdu: decoding a PDU: readingPDU length: EOF while reading leb128 encoded value' while being asked for its version.  This likely means that the server is older than the client.

Failed: Please install the same version of wezterm on both the client and server! The server reported error 'Error while decoding response pdu: decoding a PDU:reading PDU length: EOF while reading leb128 encoded value' while being asked for its version.  This likely means that the server is older than the client.

Error during attach: Please install the same version of wezterm on both the client and server! The server reported error 'Error while decoding response pdu: decoding a PDU: reading PDU length: EOF while reading leb128 encoded value' while being asked for its version.  This likely means that the server is older than the client.
```

On both the client and the remote host, `wezterm --version` comes back with `wezterm 20220101-133340-7edc5b5a`.

**Comment by wez** [comment]
Please open a separate issue so we can run this down!
