### ISSUE TITLE
Feature Request: Optional delay before triggering search

### ISSUE THREAD

**Issue by aorith** [wez/wezterm#1569]
**Is your feature request related to a problem? Please describe.**
I work with really big logs, also my terminal history is usually long.
Searching in the terminal is a very common task and with the current implementation the search triggers as soon as you type the first character, that together with the possibility that the terminal is still printing output makes it really unresponsive on my machine, specially when regex is used.

**Describe the solution you'd like**
Avoiding at all costs that the terminal gets stuck, maybe adding a (optionally configurable) delay before the search triggers:

`action={Search={Regex="",Delay=250}}`

I think adding 250ms of delay would save many people from those "one-letter-search" terminal hiccups.

I really like (and dislike at the same time) that the current search function updates as the terminal outputs more text, but that is a really big performance penalty. Tmux on the other hand, (probably because of it's own limitations) just pauses the output when you enter copy-mode, a mode that you have to enter in order to search, and you have to press ENTER before the search is triggered, which is perfect when the terminal history is big.

**Describe alternatives you've considered**
Removing the live update of the search function on terminal output, or making it optional.

**Comment by wez** [comment]
This is a good suggestion.  I'll consider it!  There are a few things around how scrollback is managed that I'd like to improve, and they all need to be considered together.

Ideally, search would be fast and not block the gui thread: https://github.com/wez/wezterm/issues/1209

re: live updating, have you considered eg: using CTRL-S to pause the output before you trigger search, then CTRL-Q to resume it?  (those are `stop` and `start` in your `stty` settings)

Also worth noting that wezterm also has a copy mode: https://wezfurlong.org/wezterm/copymode.html but I think the search and quickselect functions are much more ergonomic than copy mode.

**Comment by wez** [comment]
`main` now adds 350ms of debounce delay.
I didn't make it configurable, but it is possible to do so; kinda hoping that this doesn't need another config option.
In addition, the scrollback data structures have been tweaked to use less memory, which typically makes search
latency lower.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by MuhammedZakir** [comment]
About pausing output: you can use `Ctrl`+`s` to pause the output and `Ctrl`+`q` to continue it. See below link for more information.

https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal

**Comment by aorith** [comment]
I've been playing with a version without the fix and the latest nightly and the improvement is very noticeable.
Before that I couldn't type the full search term on a big scrollback at once.

Although that delay may annoy some people, those working with small scrollback buffers or with powerful enough machines. Let's see if someone complains...

For my machine and my use case it's completely perfect, thank you for taking the time to fix it.
