### ISSUE TITLE
Log to file

### ISSUE THREAD

**Issue by martinlindhe** [wez/wezterm#1576]
**Is your feature request related to a problem? Please describe.**
I have been running wezterm on Windows 10 for some weeks now and it is mostly stable. A few times wezterm crashed tho, and I would like to file an issue about it.
But since I did not spawn wezterm from another terminal window, I can not see any log output.

**Describe the solution you'd like**
A new config directive to redirect the STDERR log output to a file.

**Comment by wez** [comment]
The behavior in `main` is to log to `gui-log-PID.txt` in the runtime dir (typically: `%HOME%/.local/share/wezterm/`) if there is no stderr handle.
If you launch via `wezterm.exe` then the stderr is captured in the console output of `wezterm.exe`.
You can launch `wezterm-gui.exe` with stderr explicitly redirected somewhere else if you don't like the default location.

**Comment by martinlindhe** [comment]
> You can launch `wezterm-gui.exe` with stderr explicitly redirected somewhere else if you don't like the default location.

I'm at loss as to how I redirect stderr with wezterm-gui.

**Comment by rashil2000** [comment]
What CLI arguments does the `wezterm-gui.exe` binary support?

**Comment by wez** [comment]
stderr can be redirected like this:

`wezterm-gui.exe 2> some-file.txt`

**Comment by wez** [comment]
> What CLI arguments does the `wezterm-gui.exe` binary support?

The `connect`, `ls-fonts`, `serial`, `ssh` and `start` subcommands that you see in `wezterm --help` are forwarded to `wezterm-gui` and behave the same way.

You can run `wezterm-gui.exe --attach-parent-console --help` from a windows terminal to directly see its help output, but generally speaking you are no expected to use that flag: just use `wezterm --help` when you want to see stderr in a terminal instead and it will do the appropriate thing.

**Comment by rashil2000** [comment]
Okay, thanks for the info

**Comment by martinlindhe** [comment]
I feel like a noob all over again.

So, in order for me to launch this I had to resort to using a .cmd or powershell launcher. I cannot figure out a way to just launch wezterm-gui.exe without ending up with multiple windows.

The way I launch it now adds a second window (the cmd.exe or pwsh.exe), so then I might just use these to launch and get redirected stderr.
I feel I am missing something obvious.

All of this work just to try to nail a random crash I experience after several days of running wezterm.exe on Windows :-)

**Comment by wez** [comment]
You can either:
* Just run the GUI as your would normally.  If something breaks, the log file will be found in `%HOME%/.local/share/wezterm/`
* From another terminal, run `wezterm.exe`.  The logs will output to stderr in that other window.
