### ISSUE TITLE
`SSH.*` environment variables lost when connect to mux server through ssh.

### ISSUE THREAD

**Issue by leira** [wez/wezterm#1578]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220122-100747-ebaa796b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When connecting to a remote wezterm-mux-server through ssh domain, or unix domain over an ssh connection proxy, the `SSH.*` environment variables are lost in the new wezterm terminal. `set | grep SSH` prints nothing.

### To Reproduce

1. Enable ssh server on the local machine.
2. Setup public key auth and ssh-agent, so `ssh localhost` won't ask password.
3. Add the unix_domain and the ssh_domain as the Configuration below.
4. `wezterm connect ssh-proxy` or `wezterm connect ssh-local`.
5. Run `set | grep SSH` in the newly openedn `wezterm` window.

### Configuration

```lua
  unix_domains = {
    -- For testing purpose
    {
      name = "ssh-proxy",
      proxy_command = {"ssh", "-T", "localhost",
                       "/Users/leira.hua/bin/wezterm", "cli", "proxy"},
    },
  },

  ssh_domains = {
    {
      name = "ssh-local",
      remote_address = "localhost",
    },
  },
```

### Expected Behavior

`set | grep SSH` should print at least `SSH_CLIENT` and `SSH_CONNECTION`, as it is under an ssh environment.

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/config/mux_env_remove.html

**Comment by leira** [comment]
Thanks for the quick response. So turn out it is not a bug but a feature.
