### ISSUE TITLE
Neovim not rendering opacity set by wezterm config

### ISSUE THREAD

**Issue by wilkinson4** [wez/wezterm#1587]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220123-221909-403757fc

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I currently have my `window_background_opacity` set to 0.8 and outside of Neovim that works just fine, but as soon as I open Neovim the opacity goes away.
Wezterm running without Neovim:
![Screen Shot 2022-01-24 at 9 31 42 AM](https://user-images.githubusercontent.com/40211746/150813043-cf76ce03-4903-461b-be13-deb7184a458f.png)
.

Neovim open in a tmux tab in Wezterm:
![Screen Shot 2022-01-24 at 9 33 26 AM](https://user-images.githubusercontent.com/40211746/150813288-9ac65326-c747-4ff4-b0a5-8fadf1518f00.png)

### To Reproduce

I'm using the following Neovim color scheme/config
```lua
use 'tanvirtin/monokai.nvim'

local monokai = require('monokai')
local palette = monokai.pro
monokai.setup {
  palette = monokai.pro,
  custom_hlgroups = {
    GitSignsChange = {
      fg = palette.purple
    }
  }
}

local monokai = require('monokai')
local palette = monokai.pro

vim.highlight.create('Constant', {ctermfg=37})
vim.highlight.create('Normal', {ctermbg='NONE'})
vim.highlight.create('NonText', {ctermbg='NONE', guibg='NONE'})
vim.highlight.create('Pmenu', {ctermbg=240})
vim.highlight.create('PmenuSel', {ctermbg=25})

vim.highlight.create('sqlKeyword', {guifg=palette.red})
vim.highlight.create('TSConstructor', {guifg=palette.purple})
vim.highlight.create('TSParameter', {guifg=palette.orange})

-- lighten non-active windows
vim.highlight.create('NormalNC', {guibg=palette.base4})

vim.highlight.create('GitSignsCurrentLineBlame', {guifg=palette.grey})
```

I also have the following set in my `.tmux.conf` file
```
set-option -g default-terminal "tmux-256color"
```

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  font = wezterm.font("FiraCode Nerd Font"),
  color_scheme = "Monokai Remastered",
  window_background_opacity = 0.8,
  enable_tab_bar = false,
  keys = {
    {key="LeftArrow", mods="OPT", action=wezterm.action{SendString="\x1bb"}},
    {key="RightArrow", mods="OPT", action=wezterm.action{SendString="\x1bf"}},
  },
    font_rules = {
    {
      italic = true,
      font = wezterm.font("FiraCode Nerd Font", {italic=false}),
    }
  }
}
```

**Comment by gegoune** [comment]
Try setting `guibg=NONE` of `Normal` highlight group.

**Comment by wilkinson4** [comment]
That worked! Thank you!
