### ISSUE TITLE
panic when spawning new window

### ISSUE THREAD

**Issue by hahuang65** [wez/wezterm#1588]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220123-221909-403757fc

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

```
RUST_BACKTRACE=1 wezterm cli spawn --new-window
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', wezterm/src/main.rs:662:68
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: wezterm::run_cli_async::{{closure}}
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: async_io::driver::block_on
   9: std::thread::local::LocalKey<T>::with
  10: async_std::task::builder::Builder::blocking
  11: wezterm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### To Reproduce

Even without config, simply open a wezterm, run `wezterm cli spawn --new-window` and it panics.

### Configuration

no config

### Expected Behavior

A new window should open.

**Comment by wez** [comment]
Thanks for the report; fixed in `main`!
