### ISSUE TITLE
Dragging by the tab bar scrolls the text upwards

### ISSUE THREAD

**Issue by g6ai** [wez/wezterm#1589]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220123-221909-403757fc

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When there are texts / command output history more than one window in the shell console, dragging by the tab bar scrolls the text upwards.

### Configuration

https://github.com/g6ai/dotfiles/blob/main/private_dot_config/wezterm/wezterm.lua

**Comment by wez** [comment]
Fixed by #1805
