### ISSUE TITLE
add support for tasks

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#159]
Would be great if there was some sort of  [ConEmu Tasks](https://conemu.github.io/en/Tasks.html).

![image](https://user-images.githubusercontent.com/287744/74624459-60d8f280-50fd-11ea-88d1-4b54c5e9a5af.png)

This is specially useful in windows where I might sometimes want to run cmd, powershell, mingw-64 or even Visual Studio dev environments for C/C++ builds.

**Comment by ImportTaste** [comment]
Wow. That would be amazing.

**Comment by wez** [comment]
I can see the utility and convenience.  How do you think this feature should interact with https://github.com/wez/wezterm/issues/117 ?

**Comment by ImportTaste** [comment]
@wez I would make profiles a separate file so that wezterm.toml's size and indentation doesn't get too crazy, stored in a profiles folder that's relative to wezterm.toml. By default, global settings (i.e. the ones in wezterm.toml) would be used unless the profile defines the same section, even if there's nothing under it.

This could be overridden with settings that are only valid in profile tomls as to whether or not they should use global settings, and whether sections should try to replace (the default) or overlap.

I think it'd be easiest both from a development and end-user perspective.

**Comment by ImportTaste** [comment]
To more specifically address the task issue, a task command that would import non-conflicting settings from another profile would work wonders, so you could essentially just have a profile that is nothing else but a task section.

**Comment by wez** [comment]
The next nightly build will have a config section for this sort of thing; docs are live here:

http://wezfurlong.org/wezterm/config/launch.html#the-launcher-menu

**Comment by prabirshrestha** [comment]
Awesome. Is there an option to hide for some is such as cmd.exe doesn’t make sense in non windows.

**Comment by wez** [comment]
You can conditionally add things to the menu section in the config by testing the target triple:
http://wezfurlong.org/wezterm/config/lua.html#weztermtarget_triple

```lua
local wezterm = require 'wezterm';
local menu = {}

if wezterm.target_triple == "x86_64-pc-windows-msvc" then
  table.insert(menu, {
     args = {"cmd.exe"}
  })
end

return {
  launch_menu = menu
}
```

**Comment by wez** [comment]
I added a fancy example to https://wezfurlong.org/wezterm/config/launch.html that shows how to probe for the visual studio command prompt thingies as well as any WSL distributions and add those to the menu.

**Comment by wez** [comment]
(the very latest nightly is required for that!)

**Comment by prabirshrestha** [comment]
Just tried it out and seems very good. I like how it is implemented like the tmux right menu. Lot better then ConEmu Tasks.

![image](https://user-images.githubusercontent.com/287744/79077121-d8696f00-7cb3-11ea-9c07-4c868c6d046a.png)

I wasn't aware it was already using lua as config. I use a rolling distribution arch, would be good if wezterm was part of [AUR](https://aur.archlinux.org/). Because everything comes via the package manger I don't have a habit of manually updating packages manually. For AUR you can manually go and create the packages there.
Alacritty seems to be in the the default arch packages repo. Not sure how they got it there but would like to see WezTerm there too.

I'm closing since this is fixed now.
