### ISSUE TITLE
Vim split broken with SSH and UNIX domains

### ISSUE THREAD

**Issue by qperret** [wez/wezterm#1597]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220126-105230-0c6b4e26

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using vim through an SSH or UNIX domain, scrolling in split view (`:sp foobar`) fills one of the two vim panes with junk. See the gif below for an example: first I open a file (`fair.c`) in vim, and scroll through the file using the arrow keys without issues. Then I open a second file (`other.c`) in split mode, and scroll through it the same way. And as a result, one pane scrolls through the file correctly while the second one gets corrupted.

![wezterm-vim-split](https://user-images.githubusercontent.com/19532754/151592909-08e3f2fc-1dd1-4d4d-b473-94a339a4dd9d.gif)

An additional note: when not using SSH or UNIX domains everything in vim seems to work just fine.

### To Reproduce

1. connect to a unix or ssh domain
2. open a text file in vim
3. open a second file in split mode (`:sp second-file `)
4. scroll through the file on the top pane using the arrow keys

### Configuration

I can reproduce with only this as a configuration:

```
return {
	unix_domains = {
		{
			name = "unix",
		}
	},
}
```

If that can be of any help, I'm using `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 06 2022 06:42:04)`, and can reproduce with an empty `.vimrc`.

### Expected Behavior

Scrolling through the top pane in vim split mode should leave the bottom pane untouched.

### Logs

$ wezterm connect unix
 2022-01-28T17:29:13.451Z INFO  wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 21.2.6 is_context_loss_possible=false wezterm version: 20220126-105230-0c6b4e26
 2022-01-28T17:29:13.791Z WARN  wezterm_client::client  > While connecting to Socket("/run/user/724031/wezterm/sock"): connecting to /run/user/724031/wezterm/sock.  Will try spawning the server.
 2022-01-28T17:29:13.791Z WARN  wezterm_client::client  > Running: "/home/qperret/tools/wezterm/target/release/wezterm-mux-server" "--daemonize"
 2022-01-28T17:29:14.053Z INFO  wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 21.2.6 is_context_loss_possible=false wezterm version: 20220126-105230-0c6b4e26

**Comment by wez** [comment]
Confirmed!  I hadn't seen this because I tend to use vsplit on the session I daily drive

**Comment by qperret** [comment]
I believe the culprit is somewhere in this range:

```1fd53d4a5d36 mux: propagate User Vars across to the client
3ae38eb5bfc2 mux: synthesize PaletteChanged event when config is reloaded
a189bb57c14e mux: don't include unchanged lines in the bonus lines
0d18a40d60f8 improve some of our counters/stats
aa648797ae72 Include executable path and config path in version info
fc5c435949dc stats: fix .size counters showing up as time counters
5d52902b4ab6 invalidate fancy title bar before we potentially error out
f48e2d9a858c SshDomain: assume_unix -> assume_shell = "Posix"
```

But sadly it's not bisectable. These `mux:` commits look 'promising', though.

**Comment by qperret** [comment]
Yup, the issue goes away if I revert `a189bb57c14e ("mux: don't include unchanged lines in the bonus lines")` and apply the following diff:

```diff --git a/wezterm-mux-server-impl/src/sessionhandler.rs b/wezterm-mux-server-impl/src/sessionhandler.rs
index 9cb7f1f23267..cb9e34d0c132 100644
--- a/wezterm-mux-server-impl/src/sessionhandler.rs
+++ b/wezterm-mux-server-impl/src/sessionhandler.rs
@@ -1,5 +1,5 @@
 use crate::PKI;
-use anyhow::anyhow;
+use anyhow::{anyhow, Context};
 use codec::*;
 use mux::client::ClientId;
 use mux::pane::{Pane, PaneId};```

**Comment by wez** [comment]
I think the heart of the issue might be a bit more subtle: if the server doesn't think those lines have changed then there is some kind of invalidation problem somewhere. I think the client is probably over-invalidating the affected lines and then losing their content, as this sort of scrolling works fine without the multiplexer client/server in the flow.

**Comment by qperret** [comment]
Looking good now, thanks. Should I close this now or do you plan to investigate this some more?

**Comment by wez** [comment]
I can follow up on improving this later
