### ISSUE TITLE
Universal Borders

### ISSUE THREAD

**Issue by Mythbusters123** [wez/wezterm#1600]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220129-055924-a2779caf

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have the homepage in vim. and whenever I open wezterm it has a very ugly border around it. This border is actually universal, but just more noticeable with vim. Top, forexample, or btop. Screenshots of Wezterm vs Alacritty. 

https://i.imgur.com/aNkbLXv.png
https://i.imgur.com/56Xmn47.png

### To Reproduce

Either use bashtop, bpytop, or btop and observe

### Configuration

```lua
local wezterm = require('wezterm')

return {
  font = wezterm.font("FiraCode Nerd Font"),
  font_size = 13,

  colors = {
    foreground = "#eff0f1",
    background = "#31363b", 
    cursor_bg = "#eff0f1",
    cursor_border = "#eff0f1",
    cursor_fg = "#31363b",
    selection_bg = "#eff0f1",
    selection_fg = "#31363b",
    ansi = {"#31363b","#ed1515","#11d116","#ffe599","#1d99f3","#9b59b6","#1abc9c","#eff0f1"},
    brights = {"#7f8c8d","#c0392b","#1cdc9a","#ffd966","#3daee9","#8e44ad","#16a085","#fcfcfc"}
  }
}
```

### Expected Behavior

the terminal window should take up the whole screen, because thats what a terminal emulator is for.

### Logs

10:41:45.137 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-84181
10:41:45.354 INFO wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 4.6.0 NVIDIA 495.46 is_context_loss_possible=false wezterm version: 20220129-055924-a2779caf

### Anything else?

Sorry if I sound rude, I just didn't see an issue opened up to this. Thank you

**Comment by wez** [comment]
Take a look at https://wezfurlong.org/wezterm/config/lua/config/window_padding.html
