### ISSUE TITLE
set sticky bit if XDG_RUNTIME_DIR is relocated to a temporary location

### ISSUE THREAD

**Issue by dch** [wez/wezterm#1601]
### What Operating System(s) are you seeing this problem on?

FreeBSD X11

### WezTerm version

wezterm 20220129-225143-66b227bb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

On many unix systems, the /tmp/ dir is regularly and automatically pruned. It should be possible to set the whole `/tmp/$USER..../wezterm/` to a different location, not just the specified socket_path.

I'm not yet clear if this is an actual problem in practice, but the current softlink in that directory points to a non-existent path, when `socket_path` is used.

```
$ ls -AFGhl
 x11-unix:0.0-org.wezfurlong.wezterm@ -> /tmp/dch.XXXXXX.VOV7m2YI/wezterm/gui-sock-88713
$ l /tmp/dch.XXXXXX.VOV7m2YI/wezterm/gui-sock-88713
ls: /tmp/dch.XXXXXX.VOV7m2YI/wezterm/gui-sock-88713: No such file or directory
```

### Configuration

    unix_domains = {
        {
            name = "unix",
            socket_path = "/home/dch/.local/share/wezterm/sock",
            no_serve_automatically = false,
        }
    },

    default_gui_startup_args = {"connect", "unix"},

### Expected Behavior

all wezterm sockets and configs should be in a specific and controllable directory.

### Logs

```
$ wezterm-gui connect unix
 2022-01-30T17:32:14.579Z INFO  wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GTX 1650/PCIe/SSE2 4.6.0 NVIDIA 470.86 is_context_loss_possible=false wezterm version: 20220129-225143-66b227bb
 2022-01-30T17:32:14.813Z WARN  wezterm_client::client  > While connecting to Socket("/home/dch/.local/share/wezterm/sock"): connecting to /home/dch/.local/share/wezterm/sock.  Will try spawning the server.
 2022-01-30T17:32:14.813Z WARN  wezterm_client::client  > Running: "/usr/local/bin/wezterm-mux-server" "--daemonize"
 2022-01-30T17:32:15.129Z INFO  wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GTX 1650/PCIe/SSE2 4.6.0 NVIDIA 470.86 is_context_loss_possible=false wezterm version: 20220129-225143-66b227bb
```

### wezterm-gui fd 

```
$ sudo procstat fd 26681
  PID COMM                FD T V FLAGS    REF  OFFSET PRO NAME
26681 wezterm-gui       text v r r-------   -       - -   /usr/local/bin/wezterm-gui
26681 wezterm-gui       ctty v c rw------   -       - -   /dev/pts/3
26681 wezterm-gui        cwd v d r-------   -       - -   /usr/home/dch
26681 wezterm-gui       root v d r-------   -       - -   /
26681 wezterm-gui          0 v c rw------   6   34245 -   /dev/pts/3
26681 wezterm-gui          1 v c rw------   6   34245 -   /dev/pts/3
26681 wezterm-gui          2 v c rw------   6   34245 -   /dev/pts/3
26681 wezterm-gui          3 v r -wa-----  13    2125 -   /var/log/slim.log
26681 wezterm-gui          4 s - rw---n--   2       0 UDS 0 0 /tmp/.X11-unix/X0
26681 wezterm-gui          5 k - rw------   2       0 -   -
26681 wezterm-gui          6 s - rw---n--   2       0 UDS 0 0 -
26681 wezterm-gui          7 s - rw---n--   1       0 UDS 0 0 -
26681 wezterm-gui          8 p - rw---n--   2       0 -   -
26681 wezterm-gui          9 p - rw---n--   1       0 -   -
26681 wezterm-gui         10 k - rw------   2       0 -   -
26681 wezterm-gui         11 p - rw---n--   2       0 -   -
26681 wezterm-gui         12 p - rw---n--   1       0 -   -
26681 wezterm-gui         18 v c rw------   2       0 -   /dev/nvidiactl
26681 wezterm-gui         19 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         20 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         21 s - rw------   1       0 UDD /var/run/nvidia-xdriver-e597a5cc
26681 wezterm-gui         22 s - rw------   1       0 UDD /var/run/nvidia-xdriver-e597a5cc
26681 wezterm-gui         23 v c rw------   8       0 -   /dev/nvidiactl
26681 wezterm-gui         24 v c rw------   1       0 -   /dev/nvidia-modeset
26681 wezterm-gui         25 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         26 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         27 v r rw------   1     368 -   /usr/home/dch/.nv/GLCache/7dbca991ec52d8dcb1ddd33e42015b63/ea5ddbf1d9a4bb5d/09b1e1a084d06ea6.toc
26681 wezterm-gui         28 v r rw------   1   36206 -   /usr/home/dch/.nv/GLCache/7dbca991ec52d8dcb1ddd33e42015b63/ea5ddbf1d9a4bb5d/09b1e1a084d06ea6.bin
26681 wezterm-gui         29 v c rw------   1       0 -   /dev/nvidia-modeset
26681 wezterm-gui         30 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         31 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         32 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         33 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         34 v c rw------   1       0 -   /dev/nvidia0
26681 wezterm-gui         35 s - rw---n--   1       0 UDS 0 1037 /home/dch/.local/share/wezterm/sock
```

### wezterm-mux-server fd

```
$ sudo procstat fd 37
  PID COMM                FD T V FLAGS    REF  OFFSET PRO NAME
   37 wezterm-mux-server  text v r r-------   -       - -   /usr/local/bin/wezterm-mux-server
   37 wezterm-mux-server   cwd v d r-------   -       - -   /usr/home/dch
   37 wezterm-mux-server  root v d r-------   -       - -   /
   37 wezterm-mux-server     0 v c r-------   1       0 -   /dev/null
   37 wezterm-mux-server     1 v r -wa-----   1       0 -   /tmp/dch.XXXXXX.4NuopoY5/wezterm/log
   37 wezterm-mux-server     2 v r -wa-----   1     112 -   /tmp/dch.XXXXXX.4NuopoY5/wezterm/log
   37 wezterm-mux-server     3 v r -wa-----  13    2125 -   /var/log/slim.log
   37 wezterm-mux-server     4 s - rw------   2       0 UDS 0 0 /home/dch/.local/share/wezterm/sock
   37 wezterm-mux-server     5 k - rw------   2       0 -   -
   37 wezterm-mux-server     6 s - rw---n--   2       0 UDS 0 0 -
   37 wezterm-mux-server     7 s - rw---n--   1       0 UDS 0 0 -
   37 wezterm-mux-server     8 s - rw---n--   1       0 UDS 0 5 /home/dch/.local/share/wezterm/sock
   37 wezterm-mux-server     9 t - rw------   4       0 -   pts/1
   37 wezterm-mux-server    10 s - rw------   1       0 UDS 0 0 -
   37 wezterm-mux-server    11 t - rw------   4       0 -   pts/1
   37 wezterm-mux-server    12 t - rw------   4       0 -   pts/1
   37 wezterm-mux-server    13 s - rw------   1       0 UDS 0 0 -
   37 wezterm-mux-server    14 ? - --------   2       0 -   -
```

**Comment by wez** [comment]
wezterm should be using `${XDG_RUNTIME_DIR}/wezterm` if that environment variable if it is set, else falls back to `${HOME}/.local/share/wezterm`.

I'm assuming that in your environment `XDG_RUNTIME_DIR is set to `/tmp/$USER`?

**Comment by dch** [comment]
My bad, thanks I learned something today! Apparently back in 2017 I set this, with the cryptic comment "OpenBSD's mktemp is rightfully picky", so the `/tmp/$USER...` location is all mine. I've moved this to a different location, so we're good now.

However according to [freedesktop spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) these files/dirs in `XDG_RUNTIME_DIR` should be either sticky bit set on, or get regularly updated.

> $XDG_RUNTIME_DIR defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored. The directory MUST be owned by the user, and he MUST be the only one having read and write access to it. Its Unix access mode MUST be 0700.
>
> The lifetime of the directory MUST be bound to the user being logged in. It MUST be created when the user first logs in and if the user fully logs out the directory MUST be removed. If the user logs in more than once he should get pointed to the same directory, and it is mandatory that the directory continues to exist from his first login to his last logout on the system, and not removed in between. Files in the directory MUST not survive reboot or a full logout/login cycle.
>
> The directory MUST be on a local file system and not shared with any other system. The directory MUST by fully-featured by the standards of the operating system. More specifically, on Unix-like operating systems AF_UNIX sockets, symbolic links, hard links, proper permissions, file locking, sparse files, memory mapping, file change notifications, a reliable hard link count must be supported, and no restrictions on the file name character set should be imposed. Files in this directory MAY be subjected to periodic clean-up. To ensure that your files are not removed, they should have their access time timestamp modified at least once every 6 hours of monotonic time or the 'sticky' bit should be set on the file. 

Maybe at least set the sticky bit for the socket?
