### ISSUE TITLE
Zooming weirdness when switching between external monitor and laptop display on macOS

### ISSUE THREAD

**Issue by rjwalsh** [wez/wezterm#161]
I've noticed sometimes when I switch from using an external monitor to the built-in display on my MacBook Pro that my wezterm window is left in a weird zoomed-in state. Similarly, switching from built-in display back to external display sometimes leave me with a really small zoomed-out display, where the entire window contents are shrunk down into the lower-left of the window. Resizing the window fixes either case.

 - OS: macOS 10.15.3
 - Frontend: whatever the default is for macOS.
 - Version: wezterm 20200202-200216-b07ed454-43-g95fb9c0

This doesn't happen all the time, but it happens when I'm switching to and from an external HDMI display connected to my MacBook Pro via a USB-C to HDMI adapter.

I'll drop screenshot and config files in person, as they have some fb-internal info in them.

**Comment by mborejdo** [comment]
I am experiencing something similar I think.
My sharp, non-antialiased font looks sometimes like this 

![image](https://user-images.githubusercontent.com/52340/82738744-5e101e00-9d3a-11ea-8fcd-418f63793794.png)

This happens to me after quitting [dwm-win32](https://github.com/prabirshrestha/dwm-win32) and all windows being released. This only happens with wezterms. Resizing the windows by 1 pixel fixes the rendering problem.
