### ISSUE TITLE
What is the key combo to put Wezterm in full screen?

### ISSUE THREAD

**Issue by sdbbs** [wez/wezterm#1611]
As the title says, what is the key combo to put Wezterm in full screen?

The reason I'm asking is, I'm working on a Ubuntu 20.04 machine over VNC; and I pressed some key combo, don't know what - and suddenly wezterm is in full screen, and I cannot restore it to plain floating window anymore :(

I found https://wezfurlong.org/wezterm/config/lua/keyassignment/ToggleFullScreen.html - but apparently, I have to copy that code in a config file to have it run - and I don't think I use the config file at all. In any case, I couldn't parse `key="n", mods="SHIFT|CTRL",` - <kbd>SHIFT</kbd>+<kbd>n</kbd> would just give "N"; <kbd>CTRL</kbd>+<kbd>n</kbd> gives me a beep over VNC (bell?) and nothing happens,  and <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>n</kbd> starts a new Wezterm window.

Any ideas how I would recover from this situation?

-----

EDIT: Tried https://superuser.com/questions/186748/how-to-hide-or-minimize-x11-window-from-console - `wmctrl` approach did not work for me; `xdotool windowunmap $window_id` worked, but it killed the window - however having started a new window earlier (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>n</kbd>) my active `ssh` session is not dead yet.

**Comment by wez** [comment]
`ALT + Enter` is the default assignment for `ToggleFullScreen`
https://wezfurlong.org/wezterm/config/keys.html?highlight=ToggleFullScreen#default-shortcut--key-binding-assignments
