### ISSUE TITLE
When wezterm stays open for a long time (overnight), a pressed key is duplicated

### ISSUE THREAD

**Issue by timlag1305** [wez/wezterm#1613]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I kept an instance of Wezterm opened overnight and when I type say 'a' a single time in the terminal, it shows up three times. This also happens to chords such as '^d'

### To Reproduce

Leave wezterm open overnight, then type in it the following day.

### Configuration

```
local wezterm = require 'wezterm';

return {
    enable_wayland = true,
    -- Note that Iosevka Term contains ligatures that I don't want
    font = wezterm.font('Iosevka Fixed'),
    font_size = 11,
    color_scheme = 'Snow Light',
    -- The following seems to display Iosevka the best. Perhaps test other
    -- options in the future.
    freetype_load_target = 'HorizontalLcd',

    keys = {
        {
            key = "\"", mods = "CTRL|ALT",
            action = wezterm.action {
                SplitVertical = {
                    domain = "CurrentPaneDomain"
                }
            }
        },
        {
            key = "%", mods = "CTRL|ALT",
            action = wezterm.action {
                SplitHorizontal = {
                    domain = "CurrentPaneDomain"
                }
            }
        }
    },

    ssh_domains = {
        {
            name = '<server>',
            remote_address = '<server>',
            username = '<username>'
        }
    }
}
```

### Expected Behavior

When I type a key, wezterm will recognize a single instance of it, not multiple instances.

### Logs

I couldn't copy and paste the logs for some reason so I took a screenshot.

![screenshot](https://user-images.githubusercontent.com/247823/152284742-9befd0be-dd5a-4984-b425-b693ef8193d0.png)

### Anything else?

I can try the nightly, I didn't get around to switching because it takes a while to reproduce. I'll update this ticket tomorrow with the status on the nightly build.

**Comment by wez** [comment]
Probably a duplicate of https://github.com/wez/wezterm/issues/1497 which is partially resolved by https://github.com/wez/wezterm/pull/1599

**Comment by timlag1305** [comment]
You're correct. Let's close this as a duplicate.
