### ISSUE TITLE
Transparent selection color

### ISSUE THREAD

**Issue by dtomvan** [wez/wezterm#1615]
**Is your feature request related to a problem? Please describe.**
The selection color has to be fixed, whereas with other terminals it will put a background color and leave the original text colors the same.

**Describe the solution you'd like**
Setting colors to "transparent" or some variable to set some color to "nothing".

**Describe alternatives you've considered**
I've searched [this documentation page](https://docs.rs/palette/0.4.1/palette/named/index.html#constants) (from your website) for any colors to use as "transparent", but they don't seem to exist.

**Additional context**
This is my color scheme (from rebelot/kanagawa.nvim):
```lua
local colors = {
    foreground = 'silver',
    background = '#1F1F28',
    cursor_bg = '#C8C093',
    cursor_fg = 'black',
    cursor_border = '#C8C093',
    selection_bg = '#2D4F67',
    selection_fg = 'black',
    scrollbar_thumb = '#222222',
    split = '#444444',
    ansi = {
        '#090618',
        '#C34043',
        '#76946A',
        '#C0A36E',
        '#7E9CD8',
        '#957FB8',
        '#6A9589',
        '#C8C093',
    },
    brights = {
        '#727169',
        '#E82424',
        '#98BB6C',
        '#E6C384',
        '#7FB4CA',
        '#938AA9',
        '#7AA89F',
        '#DCD7BA',
    },
    indexed = { [136] = '#af8700' },
    compose_cursor = 'orange',
}
```
These are screenshots to show how wezterm handles different situations right now, regarding selection colors:
- wezterm selecting colored ls output
![image](https://user-images.githubusercontent.com/51440893/152574443-249950b7-f61a-43cb-9c2f-e17139cbc165.png)
- wezterm hovering over a song in ncmpcpp
![image](https://user-images.githubusercontent.com/51440893/152574816-9fbc7d61-982b-4984-a6d3-dcb9dcbc2b04.png)

These are the same situations, but in my st build with the same color scheme:
- st selecting colored ls output
![image](https://user-images.githubusercontent.com/51440893/152576022-fb4962cf-0191-4233-bdba-5ebd70153155.png)
- st hovering over a song in ncmpcpp
![image](https://user-images.githubusercontent.com/51440893/152576086-6aba64b2-e3f8-4931-be7a-0d1470576e2b.png)

**Comment by wez** [comment]
I just pushed a commit that allows:

```lua
return {
  colors = {
    selection_fg = "none", 
    selection_bg = "rgba:50% 50% 50% 50%"
  }
}
```

When `selection_fg` is fully transparent (alpha == 0), then wezterm will use the normal fg color:

![image](https://user-images.githubusercontent.com/117777/152660844-9324546c-aad6-4c33-82b6-b7f0a879634d.png)

When `select_bg` is transparent, it alpha blends over a pre-existing background color:

![image](https://user-images.githubusercontent.com/117777/152660848-48d7fb4e-d0e4-4b02-aaa5-8612d217c57c.png)

These change should be available in a nightly build within about an hour from now.
