### ISSUE TITLE
Kitty images not working the same as the other terminal

### ISSUE THREAD

**Issue by ghost** [wez/wezterm#1616]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220204-085823-3e2f5263

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I added Kitty image support to the backend, using only two of its commands (erase all images on a row, and place image), and getting different output between wezterm and the other terminal.

### To Reproduce

I'm sorry to do this you, I don't have a nice clean case of output. :(

To see it, take the attached jexer.zip, rename to jexer.jar, and run via `java -Djexer.ECMA48.iTerm2Images=false` .  (Without -Djexer.ECMA48.iTerm2Images=false jexer will detect wezterm and use iTerm2 images and not Kitty images.)

[jexer.zip](https://github.com/wez/wezterm/files/8005067/jexer.zip)

You will see a screen like this:

https://user-images.githubusercontent.com/4357501/152576341-92fccb00-5102-4b51-9298-57e304421f53.mp4

The errors appear to be related to erasing images, and text being re-exposed underneath images in the wrong location.

Jexer's entire repertoire of Kitty commands (taken from a couple spots) is:

```
                // There are no images, or different images, on this row, so
                // erase whatever might have been here before.
                sb.append(String.format("\033_Ga=d,d=Y,y=%d\033\\", y + 1));

        sb.append("\033_Ga=T,f=100,C=1,");
        while (data.length() > 0) {
            // This chunking stuff is stupid.
            String chunk = data.substring(0, Math.min(4096, data.length()));
            boolean last = false;
            if (chunk.length() == data.length()) {
                last = true;
                data = "";
            } else {
                data = data.substring(chunk.length());
            }
            if (last) {
                sb.append("m=0;");
            } else {
                sb.append("m=1;");
            }
            sb.append(chunk);
            sb.append("\033\\");
            if (!last) {
                sb.append("\033_G");
            }
        }
```

### Configuration

no config

### Expected Behavior

The other terminal looks like this:

https://user-images.githubusercontent.com/4357501/152576417-5e846442-0280-4bc0-ae15-b8305f739bec.mp4

### Anything else?

There are only two implementations of this protocol, so it may be that wezterm is correct as per the spec and the other is wrong.  If I need to change my strategy just let me know.

**Comment by AutumnMeowMeow** [comment]
@wez

I have removed Jexer's support for kitty images, and will never put it back in.

It turns out that kitty writes to the user's .bashrc with no notification.

With all of the other "issues" surrounding that terminal going back several years, this was just yet another thing, and I'm done.

Please expend no further effort on my behalf here.  If I could close this issue now I would.  Sorry.
