### ISSUE TITLE
CloseOnCleanExit Error

### ISSUE THREAD

**Issue by Faetu** [wez/wezterm#1618]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220205-104949-bd479792

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hi,

if I try to close wezterm with `exit` command, I got this:
`[Process didn't exit cleanly. (exit_behavior="CloseOnCleanExit")]`
and the terminal stay open.

Is there some workaround?

### To Reproduce

Currently it happens only when I run a `ELF 64-bit LSB pie executable` file.
It is a QML(C++) application.

I created a fresh QML project with minimal functionality (only a button to click), just to make sure that no programming error generates this behavior.

### Configuration

no config

### Expected Behavior

wezterm closing

**Comment by wez** [comment]
Take a look at https://wezfurlong.org/wezterm/config/lua/config/exit_behavior.html
in particular, the last paragraph!

**Comment by Faetu** [comment]
It happens only when I terminate the process with CTRL+C. But if I close the application properly or with $mod+shift+q (i3wm), this problem does not occur.

Thank you very much for the quick answer! The explanation on the page from the link, helped me a lot to understand the problem better.

From my side, the ticket can be closed here.
