### ISSUE TITLE
Standard Mac menu bars and hotkeys

### ISSUE THREAD

**Issue by rjwalsh** [wez/wezterm#162]
It would be nice to have a standard Mac-app-like appearance and interactions on the Mac. Decades of muscle-memory and all that...

i.e. the WezTerm menu would have something like:

  About
  Preferences (although that's a bit of a chore and probably unnecessary)
  Services
  Hide WezTerm
  Hide Others
  Show All
  Quit.

The Shell menu might have:

  New Window
  New Tab
  New Remote Connection
  ... etc.

and so on for Edit, View, Window and Help.

Setting up standard Mac key mappings in the absence of overrides (like command-q) would be good, too.

**Comment by wez** [comment]
This, and the domain spawning that we've been discussing in chat, has some conceptual overlap with this feature request: https://github.com/wez/wezterm/issues/159

**Comment by wez** [comment]
Closing in favor of https://github.com/wez/wezterm/issues/1485
