### ISSUE TITLE
Custom glyphs vertically misaligned after bd479792

### ISSUE THREAD

**Issue by sdrik** [wez/wezterm#1621]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220205-212818-d0a7fc9f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Custom glyphs are rendered with a vertical offset:

![Capture d’écran de 2022-02-06 13-45-19](https://user-images.githubusercontent.com/623981/152681517-1b813997-ca22-4c3a-bac6-649412ce46a0.png)

Bissecting the issue leads to bd479792 which judiciously states: As is tradition with these renderer changes, there's a good chance that I overlooked something in testing and that the metrics or alignment might be slightly off for some font/text combo.  Let's see how this goes!

### To Reproduce

printf $'\n**\uE0B0**\n'

### Configuration

no config

### Expected Behavior

![Capture d’écran de 2022-02-06 13-46-54](https://user-images.githubusercontent.com/623981/152681523-39cedcf9-6d1c-429d-8831-7ede573ccbf6.png)

**Comment by wez** [comment]
Heh! Thanks for the report; should be fixed now in `main`!

**Comment by sdrik** [comment]
It is indeed!
Thanks for this timely fix! As usual...
