### ISSUE TITLE
wezterm does not use environment variables from `$HOME/.pam_environment` when connected to wezterm-mux-server

### ISSUE THREAD

**Issue by Felixoid** [wez/wezterm#1622]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220206-073701-7956e71b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have file [.pam_environment](https://github.com/Felixoid/dotfiles/blob/master/pam_environment), and I clearly see the environment variable for wezterm-mux-server process started under the hood.

```
> cat /proc/$(pgrep wezterm-mux )/environ | tr '\0' '\n' | grep SSH
SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
```

But it's not in the terminal sessions inside the freshly opened wezterm window:

```
> env | grep SSH || echo failed
failed
```

### To Reproduce

Create `~/.pam_environment` with some parameters and start wezterm with the following configuration.

Without connecting to a Unix socket everything works. I feel like mux-server doesn't provide the environment for a children's session.

### Configuration

```
return {
  unix_domains = {
    {
      name = "unix",
      connect_automatically = true,
    }
  }
}
```

### Expected Behavior

PAM environments are presented in shells.

### Logs

$ wezterm connect unix
 2022-02-06T14:49:03.372Z INFO  wezterm_gui::termwindow > OpenGL initialized! AMD RENOIR (DRM 3.44.0, 5.16.5-arch1-1, LLVM 13.0.0) 4.6 (Compatibility Profile) Mesa 21.3.5 is_context_loss_possible=false wezterm version: 20220206-073701-7956e71b
 2022-02-06T14:49:03.752Z WARN  wezterm_client::client  > While connecting to Socket("/run/user/1000/wezterm/sock"): connecting to /run/user/1000/wezterm/sock.  Will try spawning the server.
 2022-02-06T14:49:03.752Z WARN  wezterm_client::client  > Running: "/usr/bin/wezterm-mux-server" "--daemonize"
 2022-02-06T14:49:03.973Z INFO  wezterm_gui::termwindow > OpenGL initialized! AMD RENOIR (DRM 3.44.0, 5.16.5-arch1-1, LLVM 13.0.0) 4.6 (Compatibility Profile) Mesa 21.3.5 is_context_loss_possible=false wezterm version: 20220206-073701-7956e71b

**Comment by wez** [comment]
Note that PAM can effectively only be used directly by privileged processes, so there is no way for wezterm to directly look at PAM related configuration. The mux server will inherit the environment from where it is spawned, so if eg: ssh is using PAM then those env vars will be present, but if you spawn it through some other means that doesn't also have those env vars defined, then neither will wezterm.

All that aside, take a look at: https://wezfurlong.org/wezterm/config/lua/config/mux_env_remove.html which is a list of env vars which the mux server will strip from the environment, because they have the potential to be misleading.

**Comment by Felixoid** [comment]
> All that aside, take a look at: https://wezfurlong.org/wezterm/config/lua/config/mux_env_remove.html

It pretty much looks like the reason why the ENV is not set on the mux server to me. Let me please test it closer

**Comment by wez** [comment]
You can now use `mux_env_remove = {}` in `main` to specify an empty list
