### ISSUE TITLE
force_reverse_video_cursor = true makes neovim's cursor color setting invalid when openning nvim

### ISSUE THREAD

**Issue by jdhao** [wez/wezterm#1625]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220129-051846-0b636fc0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am not sure if this is a bug or feature. I have not found the relevant issue, so I thought I might help other neovim users.

I found that if I set option [`force_reverse_video_cursor `](https://wezfurlong.org/wezterm/config/lua/config/force_reverse_video_cursor.html) to `true`, then my `guicursor` setting for nvim does not work anymore even if I am inside nvim.

### To Reproduce

Use the following `mini.vim` as config and start nvim `nvim -u mini.vim mini.vim`:

```vim
set termguicolors

highlight Cursor cterm=bold gui=bold guibg=#00c918 guifg=black
highlight Cursor2 guifg=red guibg=red

set guicursor=n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor20
```

+ When `force_reverse_video_cursor = true`, the cursor color will still be controlled by wezterm, i.e., cursor color will be set to fg of text
+ When `force_reverse_video_cursor = false`, the cursor color will be controlled by my guicursor option,  showing greenish color

![image](https://user-images.githubusercontent.com/16662357/152741193-58211271-871b-4510-8f35-f33ea591e580.png)

![image](https://user-images.githubusercontent.com/16662357/152741051-ed1adaf5-fdd5-4aae-bf98-449c288e17d8.png)

### Configuration

the single config that affects this is `force_reverse_video_cursor` that has been described before.

### Expected Behavior

By solely checking the doc of option `force_reverse_video_cursor`, I am not sure if this is a feature or bug. But I think when we are inside neovim, the cursor color should be controlled by nvim, not by wezterm, I may be wrong.

Feel free to close this issue if you think this is the intended behavior.

**Comment by wez** [comment]
dbf190d414877cd025a234f11e83256e727527f8 fixes the behavior so that the color set via escape sequences is used if it is different from the color in your main configuration.
This should be available in a nightly download within ~1 hour from now
