### ISSUE TITLE
High memory use (> 5 GiB) in some terminals

### ISSUE THREAD

**Issue by nh2** [wez/wezterm#1626]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220101-133340-7edc5b 5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Some of my wezterms have extreme memory use; `htop` output:

Screenshot:

![image](https://user-images.githubusercontent.com/399535/152787013-b2144d38-945d-496d-9c0b-d244c131a55d.png)

`htop` output as text:

<details>

```
    1[||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                   74.5%] Tasks: 354, 2239 thr, 132 kthr; 2 running
    2[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                76.5%] Load average: 2.62 3.31 2.98
  Mem[||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                 25.2G/46.8G] Uptime: 49 days, 22:52:37
  Swp[|||||||||||||||||||||||||||||||||||||||||                                              8.89G/48.2G]

    PID USER      PRI  NI  VIRT   RES▽  SHR S CPU%    DISK R/W MEM%   TIME+  Command
2801696 niklas     20   0 7214M 5659M  3296 S  0.0    0.00 B/s 11.8 14:28.44 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
2923251 niklas     20   0 2391M  478M  5876 S  0.0    0.00 B/s  1.0  2:28.27 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3582325 niklas     20   0 2186M  173M  2920 S  0.0    0.00 B/s  0.4 11:17.19 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
2608610 niklas     20   0 2159M  156M  2460 S  0.0    0.00 B/s  0.3  1:23.03 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3241921 niklas     20   0 2621M 86280  3400 S  0.0    0.00 B/s  0.2  1:45.50 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3490976 niklas     20   0 1930M 80484 39404 S  0.0    0.00 B/s  0.2  0:02.82 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3485315 niklas     20   0 1910M 70480 39036 S  0.0    0.00 B/s  0.1  0:02.80 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3491492 niklas     20   0 1905M 67184 39584 S  0.0    0.00 B/s  0.1  0:00.64 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
 818276 niklas     20   0 2110M 63720  2736 S  0.0    0.00 B/s  0.1  4:26.49 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
 802304 niklas     20   0 2122M 58056  3696 S  0.0    0.00 B/s  0.1  4:17.68 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
2914129 niklas     20   0 1956M 49780  4872 S  0.0    0.00 B/s  0.1  1:01.42 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
2092961 niklas     20   0 1939M 40716  4008 S  0.0    0.00 B/s  0.1  1:06.87 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3483915 niklas     20   0 1912M 40256  7628 S  0.0    0.00 B/s  0.1  0:03.98 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3481500 niklas     20   0 1909M 37680  7772 S  0.0    0.00 B/s  0.1  0:02.85 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3262825 niklas     20   0 1900M 36976  7596 S  0.0    0.00 B/s  0.1  0:01.62 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
1982864 niklas     20   0 1933M 36788  2964 S  0.0    0.00 B/s  0.1  0:54.96 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3482104 niklas     20   0 1904M 36732  8488 S  0.0    0.00 B/s  0.1  0:02.46 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3262949 niklas     20   0 1904M 35656  7564 S  0.0    0.00 B/s  0.1  0:01.57 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3481292 niklas     20   0 1898M 35116  8436 S  0.0    0.00 B/s  0.1  0:00.82 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
2445525 niklas     20   0 2595M 33156  4140 S  0.0    0.00 B/s  0.1  0:30.14 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
2446170 niklas     20   0 1931M 28020  6020 S  0.6    0.00 B/s  0.1  0:23.62 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
3519717 niklas     20   0 1945M 20964  3472 S  0.0    0.00 B/s  0.0  1:33.85 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
2423312 niklas     20   0 1962M 20084  3824 S  0.0    0.00 B/s  0.0  0:51.49 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
2379596 niklas     20   0 1918M 18620  3588 S  0.0    0.00 B/s  0.0  0:15.58 /nix/store/m5my5rz5ql1x4l1wqx1n42l4n4jyxmr4-wezterm-20220101-133340-7edc5b5a/bin/wezterm-gui
```

</details>

As you can see, there is a `5659M` process on top.

I use `scrollback_lines = 10000000,` (10M lines), but I wouldn't expect 10M lines to be able to occupy 5 GiB of memory.

I don't use any of the fancy features like catting images or similar, only plain-old terminal and ncurses use.

---

I would also like to know how can I can find _which_ of my numerous terminals is the one with the extreme memory use.

Maybe there's a way I can find a window by PID?

### To Reproduce

Nothing special, only my normal terminal use.

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  -- Enable the scrollbar.
  -- It will occupy the right window padding space.
  -- If right padding is set to 0 then it will be increased
  -- to a single cell width
  enable_scroll_bar = true,

  scrollback_lines = 10000000,

  -- https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
  colors = {
    -- The color of the scrollbar "thumb"; the portion that represents the current viewport
    scrollbar_thumb = "#aaa",
  },

  font = wezterm.font("JetBrains Mono"),
  font_size = 11.0,

  -- Disable ligatures in most fonts, see https://wezfurlong.org/wezterm/config/font-shaping.html
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},

  use_fancy_tab_bar = false, -- I like the terminal-font style for tabs better
  hide_tab_bar_if_only_one_tab = true,

  exit_behavior = "Close", -- like VTE terminals

}
```

**Comment by wez** [comment]
Let's do some math!

10M lines x 180 columns (width estimated from the htop output you pasted) = 1.8GB just for ASCII bytes.

A terminal needs to store more than just those bytes though; each cell has its own attributes and there additionally per-line attributes.
At the time of writing, a `Cell` occupies 24 bytes, so the theoretical max memory utilization for 10M lines is pretty huge at that width.

Could we make it smaller?
It's a trade off.

This weekend I've been looking at an additional alternative storage for a `Line` where the attributes can be factored out and stored in runs, which takes the per-cell overhead down for those lines to be ~1 byte for ASCII, depending on how frequently the color changes.

This comes at a significant performance cost: we need to convert from the fast array of `Cell` into this alternative storage when lines go into scrollback which makes pathological cases like `cat bigfile` almost 2x slower.  It also impacts cases like window resizing, where we need to convert back and forth to recompute wrapped lines across the entire scrollback.

The conversion is a killer.  Could we make the `Line` smarter about storing runs of attributes?  Possibly, but it's a bit awkward because a decent amount of code assumes that it can access the cell array and there is a lot of fan out to adjust those access patterns.  It will also increase the general cost of updating the display in all cases.

I haven't convinced myself that it is worth the effort or the performance trade-off, because, when it comes down to it:

**10M lines is a *lot* of lines**.  Is there a situation where it is reasonable for a human to read and comprehend 10M lines?  Any case I can think of is much better served by redirecting output to a temporary file and grepping it, or using a pager like `less`.

**Comment by wez** [comment]
> I would also like to know how can I can find _which_ of my numerous terminals is the one with the extreme memory use.
> 
> Maybe there's a way I can find a window by PID?

`xprop` will show `_NET_WM_PID` for wezterm windows, you can use that to figure which window has which pid.

This will list wezterm window ids:

```
; xdotool search --class org.wezfurlong.wezterm
44040195
```

and you can resolve the pid:

```
; xdotool getwindowpid 44040195
2636820
```

**Comment by ninjalj** [comment]
Note that VTE compresses the scrollback with zlib (and encrypts it with AES-256 GCM!).

**Comment by wez** [comment]
`main` now has the ability to use an alternative backing for the line data that can reduce per-cell overhead by up to 40x for simple uncolored ascii text output, but less than that for other attributed text.

The alternate backing is enabled for a given line once it moves into the scrollback, but will also be used for simple sequential output case (eg: `cat bigfile`).
