### ISSUE TITLE
SplitVertical Does Not Show Prompt in Right Half

### ISSUE THREAD

**Issue by rrpolanco** [wez/wezterm#1627]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220206-220952-7a5956d3

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Splitting the current pane in half, vertically, causes the prompt to **not** render.
![wezterm_split_vertical_bug](https://user-images.githubusercontent.com/6497491/152809028-cb743393-0ccd-448b-92fc-90259a290404.gif)

### To Reproduce

1. Start `wezterm` version `20220206-220952-7a5956d3`
2. Perform `SplitVertical` action

### Configuration

I have not changed my config.

### Expected Behavior

Splitting the current pane vertically should show the prompt in the new right half pane.

### Logs

2022-02-07T14:26:09.977Z INFO  wezterm_gui::termwindow::render > breaking on overflow 1490 > 1474 + 1456

**Comment by wez** [comment]
Thanks for the report! Should be fixed now in `main`

**Comment by rrpolanco** [comment]
Thanks for the quick fix @wez !

**Comment by MostHated** [comment]
I just went to test this out using the appimage and while it looks like the display issue is fixed, if I split the pane, everything is good for a few seconds, but after something like 5-10 seconds, the terminal no longer accepts any keyboard input. Mouse input still works, ex I can click/right-click the tab menus, but can't type anything in either of the pane splits or the new tab window.

**Comment by wez** [comment]
@MostHated please file a separate issue for that!
