### ISSUE TITLE
Clickable URLs not following to the next line

### ISSUE THREAD

**Issue by AutumnMeowMeow** [wez/wezterm#1629]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220204-085823-3e2f5263

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When a URL is being detected by wezterm, it did not include the portion that wrapped to the next line.

Example below.  The mouse is over the partially-underlined URL, which you can't see because switching to the window to capture turned off the mouse pointer.  But the underlined part is what my browser tried to open:

![url_lines](https://user-images.githubusercontent.com/99296476/153099023-c2785ac4-2a4d-4434-8fc6-bf2403245e1b.png)

### Configuration

no config

### Anything else?

Sorry if this is a dupe.  I didn't see it when I looked for "url" in the issues.

**Comment by AutumnMeowMeow** [comment]
(Hello from my new account going forward. :-) )

**Comment by wez** [comment]
Hi!

I was originally going to write that the URLs are matched against the physical post-wrapped lines, but looking at the code, we do actually match against logical lines, which you can test with pasting this into an 80x24 terminal shell prompt:

```
echo http://example.com/thisisareallylongurlthatwrapsaroundtothenextline/woot.html
```

In your screenshot, it looks like perhaps `more` is breaking the lines and rendering two discrete lines, which is confirmed with:

```
; echo woot woot woot woot woot http://example.com/thisisareallylongurlthatwrapsaroundtothenextline/woot.html  > wat.txt
; more wat.txt
```

If you switch to `less` then it looks like it is smart enough to avoid breaking the lines and the URL remains a single line!

**Comment by AutumnMeowMeow** [comment]
Ah!  'less is more' indeed. :)

I think wezterm is doing it right/best then.  You can't infer logical lines are connected because a URL could exactly fit to the last column.  And the application has control: if it wants the behavior, it can set line wrap appropriately and then wrap -- or use the OSC for this.

Thank you for checking!

Closing it out.
