### ISSUE TITLE
Window moves around as you resize the window height/width.

### ISSUE THREAD

**Issue by McFrappe** [wez/wezterm#1634]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220102-082619-c05491f8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When you resize wezterm to a larger window, it can be seen that the placements of the window is not stationary, but instead it moves a bit along with the resizing direction. It can be clearly seen in 

### To Reproduce

Resize the window as seen in the attached video demonstration of the bug.

### Configuration

no config

### Expected Behavior

The wezterm window should stay in place and simply just increase in size depending on the direction it is being increased/decreased to.

### Logs

14:42:41.443 INFO wezterm_mux_server_impl::local > setting up /Users/fadde/.local/share/wezterm/gui-sock-16696
14:42:41.566 INFO wezterm_gui::termwindow > OpenGL initialized! Apple M1 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220102-082619-c05491f8
>

### Anything else?

https://user-images.githubusercontent.com/17787601/153599085-f4890b3e-65d3-4913-b1a1-50bd12e1770f.mov

**Comment by McFrappe** [comment]
Noticed that similar findings are reported in #1491.

**Comment by McFrappe** [comment]
Ok, i was stupid and realised there is a newer version.
Now using `20220210-082022-41342ef7`. Ignore this issue!

**Comment by bew** [comment]
ahahah I love that behavior, it looks like a squishy ball ^^
(but it's good to have it fixed 😛)
