### ISSUE TITLE
Whitespace is lost during copy-paste if it's at the end of the terminal line

### ISSUE THREAD

**Issue by nh2** [wez/wezterm#1635]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

If I have a wrapped line like this (note, whitespace at the end of the first line, the string typed is `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  BBB`):

```
niklas:~/ $ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  
BBB
```

and I select it with the mouse, copy-pasting it into another wezterm instance with Shift+Ctrl+C, Shift+Ctrl+V, then the whitespace from the middle is lost:

```
niklas:~/ $ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaB
BB
```

The pasted string is now `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaBBB` (2 spaces in the middle were removed).

Video:

https://user-images.githubusercontent.com/399535/153628353-e7c26738-9941-4120-8f00-fad2e42c452c.mp4

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  -- Enable the scrollbar.
  -- It will occupy the right window padding space.
  -- If right padding is set to 0 then it will be increased
  -- to a single cell width
  enable_scroll_bar = true,

  scrollback_lines = 1000000,

  -- https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
  colors = {
    -- The color of the scrollbar "thumb"; the portion that represents the current viewport
    scrollbar_thumb = "#aaa",
  },

  font = wezterm.font("JetBrains Mono"),
  font_size = 11.0,

  -- Disable ligatures in most fonts, see https://wezfurlong.org/wezterm/config/font-shaping.html
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},

  use_fancy_tab_bar = false, -- I like the terminal-font style for tabs better
  hide_tab_bar_if_only_one_tab = true,

  exit_behavior = "Close", -- like VTE terminals

}
```

### Expected Behavior

Copy-pasting preserves input exactly.

**Comment by wez** [comment]
Thanks for the report; this is fixed now in `main` and should show up in a nightly building within the next hour!
