### ISSUE TITLE
XCursor not applying system theme

### ISSUE THREAD

**Issue by Riyyi** [wez/wezterm#1655]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220218-071628-85a8434e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I can't seem to get the cursor theme to work in the tab bar, the split resize cursor does seem to work correctly.
![wezterm-cursors](https://user-images.githubusercontent.com/1911807/154965825-0c4831f2-271e-4e5d-8df9-375663518898.png)

I have verified the themes settings with these commands:
```
$ find /usr/share/icons ~/.local/share/icons ~/.icons -type d -name "cursors"
/usr/share/icons/capitaine-cursors-light/cursors
/usr/share/icons/Adwaita/cursors
/usr/share/icons/capitaine-cursors/cursors
find: ‘/home/user/.local/share/icons’: No such file or directory
find: ‘/home/user/.icons’: No such file or directory
```

```
$ grep 'Xcursor.theme' ~/.config/xorg/Xresources
Xcursor.theme: capitaine-cursors-light
```

```
$ xprop -root | grep RESOURCE_MANAGER | perl -pe 's/\\n/\n/g' | grep -i cursor.theme
Xcursor.theme:\tcapitaine-cursors-light
```

```
$ grep 'cursor-theme-name' ~/.config/gtk-3.0/settings.ini
gtk-cursor-theme-name=capitaine-cursors-light
```

```
$ grep 'cursor-theme-name' ~/.config/gtk-2.0/gtkrc
gtk-cursor-theme-name="capitaine-cursors-light"
```

### To Reproduce

I tried running the application with the following commands, but none of them made the theme apply:
```
$ wezterm
$ XCURSOR_THEME="capitaine-cursors-light" wezterm
$ XCURSOR_PATH="/usr/share/icons" wezterm
$ XCURSOR_PATH="/usr/share/icons" XCURSOR_THEME="capitaine-cursors-light" wezterm
$ XCURSOR_PATH="/usr/share/icons/capitaine-cursors-light" wezterm
$ XCURSOR_PATH="/usr/share/icons/capitaine-cursors-light/cursors" wezterm
```
This is on Arch Linux with the `wezterm-nightly-bin` AUR package.

### Configuration

no config

### Expected Behavior

To apply the correct theme in the tab bar.

### Logs

```
$ wezterm
 2022-02-21T14:02:39.757Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-378704
 2022-02-21T14:02:39.800Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) HD Graphics 530 (SKL GT2) 4.6 (Compatibility Profile) Mesa 21.3.6 is_context_loss_possible=false wezterm version: 20220218-071628-85a8434e
```

```
$ WEZTERM_LOG=trace wezterm
```
[full log output](https://www.toptal.com/developers/hastebin/husayuzuta.rust)

### Anything else?

I have read the commits in #524 and @wez's comment in #1061, but I couldn't figure it out.

**Comment by Frikilinux** [comment]
Maybe you can try adding the symlink  `top_left_arrow` to `left_ptr` like the Breeze theme https://github.com/KDE/breeze/commit/6316df30a995812003df9c1f31f9162e28c2bbcc

**Comment by Riyyi** [comment]
That works, I dont know if its appropriate to have a fallback, or if I should close the issue.

**Comment by wez** [comment]
I think it's reasonable to add a fallback in `load_themed` that tries `top_left_arrow` and so on for the current original X11 names.

**Comment by Riyyi** [comment]
Just tested the nightly, it works!
