### ISSUE TITLE
Support vim-like visual block selections in copy mode

### ISSUE THREAD

**Issue by nwithers-ecr** [wez/wezterm#1656]
**Is your feature request related to a problem? Please describe.**
Copying tabular data generally requires multiple extra steps. I find myself wanting to quickly view different data in gnuplot. But currently in order to achieve that I will need to write out to multiple files. If I could select columwise in copymode, I could pass data to gnuplot directly through stdin without ever needing to open vim, which would be much faster. 

**Describe the solution you'd like**
When in copy mode, lower-case `v` behaves the same. However, upper-case `V` would activate visual block mode for selecting columns of text from the scrollback buffer. 

**Describe alternatives you've considered**
I could tee the command output to a file, open it with vim, select columwise the data I need, then either yank to the system clip board register or perform an incantation `:echo system("xsel -b", @")` to get it into the system clipboard.

**Comment by wez** [comment]
Another alternative you might consider in the meantime is the example here: https://wezfurlong.org/wezterm/config/lua/wezterm/on.html#custom-events which opens the scrollback directly in vim

**Comment by wez** [comment]
Related to #1361

**Comment by ExpandingMan** [comment]
Just wanted to second that vim-like binding and selection modes would be a very big deal to me as well.  (I'm on alacritty, would like to switch mostly because of sixel [as alacritty seems like it'll never ever support it], but feel I can't without this feature.)

**Comment by wez** [comment]
This should be fixed now in `main`.  `CTRL-v` will enable rectangular block selection in copy mode.  Alt-dragging the mouse also does block selection.

In addition, copy mode key assignments can now be customized. See https://github.com/wez/wezterm/issues/993#issuecomment-1118214414 for more information.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by ExpandingMan** [comment]
Awesome! Seems to work great.  Thanks so much, this was the most important thing I was missing from alacritty and it really caused a lot of headaches not to have it.

By the way, I followed the other comment to add copy-mode key bindings, but I can't quite figure out how to express the [visual block mode action](https://github.com/wez/wezterm/blob/main/wezterm-gui/src/overlay/copy.rs#L1154-L1160) in lua, could you provide an example?

**Comment by wez** [comment]
Try, something like this:

```lua
{key="v", mods="CTRL", action=wezterm.action{CopyMode={SetSelectionMode="Block"}}},
```

**Comment by wez** [comment]
I added examples for how to replicate the default bindings to the docs: https://wezfurlong.org/wezterm/copymode.html#configurable-key-assignments
