### ISSUE TITLE
Wayland client side decorations

### ISSUE THREAD

**Issue by OmegaRogue** [wez/wezterm#1659]
**Is your feature request related to a problem? Please describe.**
In gnome with wayland enabled, wezterm has the default wayland titlebar instead of the gnome gtk titlebar it has in xorg or xwayland, because mutter (the gnome window manager) doesn't support server side decorations in wayland and as of now there are no plans to support this
**Describe the solution you'd like**
A fix for that would be to optionally enable client side decorations when wayland is enabled in the config, and then use something like gtk to render the decoration client side
**Describe alternatives you've considered**

**Comment by wez** [comment]
There is no such thing as a default wayland titlebar.  Either the server side renders decorations or the client side does.
What you're seeing is the simple client side decorations that wezterm produces when the server doesn't support server side decorations.

wezterm will never be a GTK program, so these decorations will never look the the same as GTK programs.  It is not a goal to make things look like GTK.

The plan for the future is to finish up #1180 and then just disable server side decorations under wayland.

I'm going to close this in favor of #1180 as we already support client side decorations.
