### ISSUE TITLE
Windows to remote Linux ssh_domains connection requires password even when ssh keys configured

### ISSUE THREAD

**Issue by siddharthagudgunti** [wez/wezterm#1660]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220223-075425-755f1c28

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

wezterm Client is on Windows.
wezterm-mux-server is on a remote Ubuntu 20.04.2 LTS server.

Setup up ssh key based login between windows and remote Linux Server.
Confirm from `cmd> ssh <user>@<server>` does connect without password prompt.

Now from `cmd> wezterm.exe connect <my.server>`
A new terminal window pops up to request password. After connecting and setting up few tabs and panes, close the remote window. And try again to connect with above command. Again password request terminal window pops up. I was expecting this second one to connect without password as the ssh connection is setup passwordless.

Note that, I am able to connect from Windows to Local WSL Linux with just ssh keys (passwordless).
Also, I am able to connect from WSL Linux to remote Linux with just ssh keys (passwordless).

### To Reproduce

Described in above section.

### Configuration

my wezterm.lua contains the ssh_domains section with following fields:
```
    {
      -- This name identifies the domain
      name = "<my.server>",
      -- The address to connect to
      remote_address = "<ip-address>",
      -- The username to use on the remote host
      username = "<user>",
   },
```

### Expected Behavior

connect to the remote wezterm-mux-server passwordless similar to linux.

### Anything else?

by using `WEZTERM_LOG=trace wezterm.exe connect <my.server>`, only difference I observe Password: prompt coming back instead of "Running: wezterm cli proxy".

**Comment by wez** [comment]
If you use `ssh user@host` then:

Assuming that your ssh config file uses something like:

```
Host host
   IdentityFile /path/to/key
```

then your ssh_domain config should look like:

```lua
 {
    name = "host", -- can be whatever you like
    remote_address = "host", -- not the IP address!
    username = "user",
 }
```

so that your ssh config rules will match based on the hostname.

**Comment by siddharthagudgunti** [comment]
> If you use `ssh user@host` then:
> 
> Assuming that your ssh config file uses something like:
> 
> ```
> Host host
>    IdentityFile /path/to/key
> ```
> 
> then your ssh_domain config should look like:
> 
> ```lua
>  {
>     name = "host", -- can be whatever you like
>     remote_address = "host", -- not the IP address!
>     username = "user",
>  }
> ```
> 
> so that your ssh config rules will match based on the hostname.

Perfect. So, the mismatch was on the remote_address being hostname (of ssh_config) vs. IP address. I think this information should be present in example given @ https://wezfurlong.org/wezterm/multiplexing.html#ssh-domains
