### ISSUE TITLE
Kitty graphics support does not implement w and h options correctly

### ISSUE THREAD

**Issue by VrIgHtEr** [wez/wezterm#1663]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220223-075425-755f1c28

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In the kitty graphics protocol, the ``x``, ``y``, ``w`` and ``h`` options allow you to specify a rectangle to which the image will be cropped. The ``c`` and ``r`` options should be used to specify scaling. However, wezterm seems to be resizing the image to the size specified by the ``w`` and ``h`` options, instead of cropping a rectangle of that size from the image with the top-left corner at the ``x`` and ``y`` position.

### To Reproduce

I tried implementing an animation by using a spritesheet. I upload the image once and then select different areas of it to display by updating the placement. Here's the relevant section of my code (some options such as``i`` are specified elsewhere)

```lua
terminal.execute_at(rows - 2, xcell + 1, function()
    img:display {
        x = sprite_offset_x + sprite_x * sprite_w,
        y = sprite_offset_y + sprite_y * sprite_h,
        w = sprite_w,
        h = sprite_h,
        q = 2,
        p = 1,
        C = 1,
        z = -1,
        X = xoff,
    }
end)
```

### Configuration

no config

### Expected Behavior

The area specified should be cropped out of the image, and then resized to the ``c`` and ``r`` sizes.

Here's wezterm's output (resizing the entire spritesheet to the ``w`` and ``h`` size)
![image](https://user-images.githubusercontent.com/2790760/155501142-d88791df-7be6-4cec-86f0-9c7f65e99dd5.png)

While here's the output from kitty (correctly cropping, not resizing the image)
![image](https://user-images.githubusercontent.com/2790760/155501609-44b1712b-de88-4625-a9cf-40c06e812cab.png)

**Comment by VrIgHtEr** [comment]
I forgot to mention, I'm using wezterm ssh to connect to wsl

**Comment by AnonymouX47** [comment]
See https://github.com/wez/wezterm/issues/986#issuecomment-1120622597

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
