### ISSUE TITLE
Use a different font for non-ASCII text

### ISSUE THREAD

**Issue by Junnplus** [wez/wezterm#1668]
**Is your feature request related to a problem? Please describe.**

I use wezterm instead of iTerm2 on macos, but there is a difference:

wezterm:
![image](https://user-images.githubusercontent.com/8097526/155831921-b83f7f1a-38c1-459e-b923-bae182b96bfc.png)

iTerm2:
![image](https://user-images.githubusercontent.com/8097526/155831923-68feae57-6068-4bdd-8bbc-55fc672b5155.png)

Icons look a little small. I am not sure if I am missing some configuration.

My wezterm config:
```
return {
    font = wezterm.font('Hack Nerd Font Mono'),
    font_size = 14,
}
```

**Describe the solution you'd like**
Like iTerm2, support use a different font for non-ASCII text:
![image](https://user-images.githubusercontent.com/8097526/155831908-b4364916-88a1-450c-86e2-c90d20cc202e.png)

**Describe alternatives you've considered**

**Comment by wez** [comment]
For the icon size, take a look at this option: https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html

Also, I don't recommend using patched Nerd Fonts, as they have had a number of issues with broken naming and sizes over the past couple of years.

wezterm's nightly build bundles the Nerd Font symbols as a default fallback font, so you can use those icons with any font.

I would suggest setting your config to this:

```lua
return {
    font = wezterm.font('Hack'), -- you may need to install this font if you haven't already
    allow_square_glyphs_to_overflow_width = "WhenFollowedBySpace", -- or consider "Always"
    font_size = 14,
}
```

**Comment by Junnplus** [comment]
> wezterm's nightly build bundles the Nerd Font symbols as a default fallback font, so you can use those icons with any font.

Good job.

`allow_square_glyphs_to_overflow_width` is working for me, thank you for much!

Have a nice weekend.
