### ISSUE TITLE
High CPU usage under Wayland and Nvidia proprietary driver

### ISSUE THREAD

**Issue by Mofiqul** [wez/wezterm#1671]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

CPU usage goes high when focusing on the wezterm window and comes back to normal when focusing to other application window

### To Reproduce

Open wezterm and open any other application, then focus on wezterm and observe the CPU usage. Now focus on other application window and observe the CPU usage.

### Configuration

```lua
local wezterm = require 'wezterm';

local function set_neovim_theme(appearance)
    local file = "/home/mofi/.config/nvim/lua/variables.lua"
    local cmd = {}
    if appearance:find("Dark") then
        cmd = {"sed", "-i", "-e", 's/light/dark/g', file}
    else
        cmd = {"sed", "-i", "-e", 's/dark/light/g', file}
    end
    wezterm.background_child_process(cmd)
end

local function scheme_for_appearance(appearance)
  if appearance:find("Dark") then
    return "Dark+"
  else
    return "Light+"
  end
end

wezterm.on("window-config-reloaded", function(window, _)
  local overrides = window:get_config_overrides() or {}
  local appearance = window:get_appearance()
  local scheme = scheme_for_appearance(appearance)
  set_neovim_theme(appearance)
  if overrides.color_scheme ~= scheme then
    overrides.color_scheme = scheme
    window:set_config_overrides(overrides)
  end
end)

return {
  font = wezterm.font("JetBrainsMono Nerd Font"),
  font_size = 11,
  color_scheme = "Dark+",
  color_scheme_dirs = {"/home/.config/wezterm/colors"},
  window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
  },
  window_decorations = "TITLE | RESIZE",
  enable_tab_bar = true,
  use_fancy_tab_bar = false,
  hide_tab_bar_if_only_one_tab = true,
  tab_bar_at_bottom = true,
  default_cursor_style = "BlinkingBar",
  window_close_confirmation = "NeverPrompt",
  initial_cols = 120,
  initial_rows = 38
}
```

### Expected Behavior

CPU usage should be normal

### Anything else?

https://user-images.githubusercontent.com/23612580/155851124-85b08a9f-ac17-4cb6-ad93-1136ddf8f7bf.mp4

**Comment by wez** [comment]
Please also share the opengl information reported in the debug console; press CTRL-SHIFT-L and paste the line that looks something like:

```
OpenGL initialized! NVIDIA GeForce GT 1030/PCIe/SSE2 4.6.0 NVIDIA 510.47.03 is_context_loss_possible=false wezterm version: 20220213-203140-4a1c4b55
```

**Comment by wez** [comment]
Please also try the nightly build!

**Comment by wez** [comment]
Closing out due to lack of information; if/when you've had a chance to act on my earlier comments, please re-open this and we can follow up.
