### ISSUE TITLE
add support for -e flag

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#168]
**Is your feature request related to a problem? Please describe.**
All major terminal emulators such as `xterm`, `alacritty` support `-e` flag to open the executable and then run the command.

**Describe the solution you'd like**
Add support for `wezterm -e vim`

**Describe alternatives you've considered**
Currently no alternatives besides using another terminal.

**Additional context**
For AwesomeWM I would like to replace this with wezterm.

```lua
termianl="alacritty"
editor = os.getenv("EDITOR") or "vim"
editor_cmd = terminal .. " -e " .. editor
```

**Comment by wez** [comment]
You can use `wezterm start -- vim` for this.

**Comment by prabirshrestha** [comment]
Thanks that is exactly what I'm looking for.
