### ISSUE TITLE
[Question] Change the background color for each wezterm ssh

### ISSUE THREAD

**Issue by yutkat** [wez/wezterm#1680]
**Is your feature request related to a problem? Please describe.**
I want to change the background color for each wezterm ssh and wezterm connect.
I would like an easy way to tell if I am connecting via ssh so that accidents do not occur on the ssh server.

**Describe the solution you'd like**
Is there any way to tell if wezterm ssh is in progress using Lua?
If I know whether it is in ssh or not, and what the IP address is, I can implement it.

**Describe alternatives you've considered**
Can I get wezterm startup arguments from Lua? If I can do that, it would solve the problem for now.

**Comment by wez** [comment]
We don't have a direct way to inspect this from the config today, but there are a couple of different things that might get you close to this goal.

## If you are using a remote multiplexer server with `wezterm connect`

The colors are defined by the `wezterm.lua` config file on the remote server, so you could just those to a different color.

## Using color palette altering escape sequences in the remote host's shell configuration

The `OSC 11` escape sequence can be used to change the default background color, so you could put something like this into the `.bashrc` on the remote host to have it change the color when you login to it:

```bash
# Set default background to bright blue
printf "\x1b]11;#0000ff\x1b\\"
```

(You can reset it using OSC 111: `printf "\x1b]111\x1b\\"`)

## You can try to infer it from the pane information

If you define a [window-config-reloaded](https://wezfurlong.org/wezterm/config/lua/window-events/window-config-reloaded.html) event handler, you are passed a `pane` object.  You can use [pane:get_foreground_process_name](https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html) to determine which program is running in the pane and then use [window:set_config_overrides](https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html) to adjust the color accordingly.

When using `wezterm connect`, `wezterm ssh`, or `wezterm serial` the foreground process name will be `nil`.

Something like this might do what you want:

```lua
local wezterm = require 'wezterm';

wezterm.on("window-config-reloaded", function(window, pane)
   local overrides = {}

   -- If there's no foreground process, assume that we are "wezterm connect" or "wezterm ssh"
   -- and use a different background color
   if pane:get_foreground_process_name() == nil then
     -- This changes the color but note that if you are using color schemes that the `color_scheme`
     -- config takes precedence over `colors` and that you'll probably want to override the `color_scheme`
     -- here instead. 
     overrides.colors = { background = "blue" }
   end

   window:set_config_overrides(overrides)
end)

return {
}
```

## You could use UserVars as a kind of hybrid of both techniques

iTerm2 defined an escape sequence for passing key/value pairs from a terminal session back to the terminal emulator.
Those values are made available to your lua config via [pane:get_user_vars](https://wezfurlong.org/wezterm/config/lua/pane/get_user_vars.html).

```bash
# Sets "foo" to the value "bar"
printf "\033]1337;SetUserVar=%s=%s\007" foo `echo -n bar | base64`
```

You might consider having your remote shell session set a variable to indicate that you are on a production system:

```bash
# Put this in the remote bashrc. It sets production=1
printf "\033]1337;SetUserVar=%s=%s\007" production `echo -n 1 | base64`
```

then in your local wezterm config you can use the [update-right-status](https://wezfurlong.org/wezterm/config/lua/window-events/update-right-status.html) to override the config:

```lua
local wezterm = require 'wezterm';

-- This event fires when user vars are changed.
-- We use it to update the window configuration 
wezterm.on("update-right-status", function(window, pane)
   local overrides = {}

   if pane:get_user_vars().production == "1" then
     overrides.color_scheme = "Red Alert"
   end

   window:set_config_overrides(overrides)
end)

return {
}
```

This approach has the advantage that you don't need to encode you color scheme choice on the remote system; you can define symbolic variables and leave it to your local configuration to interpret them.

**Comment by yutkat** [comment]
Thanks for the reply. I switched from alacritty+tmux to wezterm and am very satisfied.

I was able to achieve what I wanted to do with your advice.

```zsh
function wezterm() {
  if [ "$#" == 0 ]; then
    command wezterm
    return
  fi
  if [ "$1" == "ssh" ]; then
    if [ "$2" =~ ".*example.com" ]; then
      command wezterm $@ -- sh -c 'printf "\033]1337;SetUserVar=%s=%s\007" production `echo -n 1 | base64`; eval $SHELL'
      return
    fi
  fi
  command wezterm $@
}
```

```lua
wezterm.on("update-right-status", function(window, pane)
	local overrides = window:get_config_overrides() or {}
	if pane:get_user_vars().production == "1" then
		overrides.color_scheme = "Red Alert"
	end
	window:set_config_overrides(overrides)
end)
```

Preferably I would like to be able to process with the arguments given at startup in the wezterm module ( like target_triple ).

Well anyway, I have now succeeded in getting it to work. Thanks.
