### ISSUE TITLE
Missing "WSL:" in documentation example using default_wsl_domains

### ISSUE THREAD

**Issue by wbeeftink** [wez/wezterm#1681]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220301-061825-9ba7ca19

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

This isn't really a bug. In the documentation for setting up WslDomain, there is a [code example](https://wezfurlong.org/wezterm/config/lua/wezterm/default_wsl_domains.html#weztermdefault_wsl_domains) which checks `dom.name == "Ubuntu-18.04"` which, at least for my machine, is missing the `WSL:` prefix in the name.

```lua
local wezterm = require 'wezterm'

local wsl_domains = wezterm.default_wsl_domains()

for idx, dom in ipairs(wsl_domains) do
  if dom.name == "Ubuntu-18.04" then
    dom.default_prog = {"fish"}
  end
end

return {
  wsl_domains = wsl_domains,
}
```

Setting the name value to `WSL:Ubuntu` solved the issue for me:

```lua
for idx, dom in ipairs(wsl_domains) do
  if dom.name == "WSL:Ubuntu" then
    -- snipped
  end
end
```

Using `dom.distribution` might also solve the issue but as you can see from my logs, my distribution is simply called `Ubuntu` without the version suffix.

### Configuration

wezterm.lua:

```lua
local wsl_domains = wezterm.default_wsl_domains()
print(wsl_domains)
```

Debug output:

```
11:37:03.635 INFO wezterm_mux_server_impl::local > setting up C:\Users\wouter.beeftink\.local/share/wezterm\gui-sock-10600
11:37:03.639 INFO wezterm_client::discovery::windows > published gui path as gui-sock-10600
11:37:03.713 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
11:37:03.923 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 630 4.5.0 - Build 27.20.100.9664 is_context_loss_possible=true wezterm version: 20220301-061825-9ba7ca19
11:37:06.857 INFO config::lua > lua: [{"distribution": "Ubuntu", "name": "WSL:Ubuntu"}, {"distribution": "docker-desktop", "name": "WSL:docker-desktop"}, {"distribution": "docker-desktop-data", "name": "WSL:docker-desktop-data"}]
```

Output of `wsl -l -v`:

```
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
```

**Comment by wez** [comment]
Thanks for fixing this in #1682!
