### ISSUE TITLE
certain character is input wrongly when using IME

### ISSUE THREAD

**Issue by jdhao** [wez/wezterm#1683]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220301-061825-9ba7ca19

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am using the macOS builtin IME for Chinese, and I have noticed a random bug that I have not been able to reproduce reliably.

Sometimes, when IME is on, and when I input `。` (the Chinese counterpart of dot), I saw strange bytes `ã<80><82>` on the terminal instead of the character itself. Currently, I have observed errors with this one character only.

### To Reproduce

I have not found a reliable way to reproduce it, but it definitely exists... 

### Configuration

```lua
-- config: https://wezfurlong.org/wezterm/config/lua/config/index.html
local wezterm = require 'wezterm';

return {
  font = wezterm.font_with_fallback({
    "Iosevka Nerd Font",
    "Noto Sans SC",
  }),
  font_size = 14.0,
  -- color scheme can be found here: https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/wezterm
  color_scheme = "Solarized Dark - Patched",
  default_cursor_style = "BlinkingBar",
  cursor_blink_rate = 400,
  force_reverse_video_cursor = false,
  enable_tab_bar = true,
  use_fancy_tab_bar = true,
  hide_tab_bar_if_only_one_tab = true,
  tab_bar_at_bottom = false,
  window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
  },
  window_decorations = "TITLE | RESIZE",
  native_macos_fullscreen_mode = false,
  send_composed_key_when_left_alt_is_pressed=false,
  send_composed_key_when_right_alt_is_pressed=false,
  use_ime = true,
  window_background_opacity = 1.0,
}

```

### Expected Behavior

I can input `。` as is instead of three weird bytes.

### Logs

An image is worth a thousand words

![wezterm-bug](https://user-images.githubusercontent.com/16662357/156585497-c7fbe52a-11e6-4dd3-a2ba-035f3e122064.gif)

**Comment by wez** [comment]
When you see `<XX>` (where XX is a hex number), when typing into a shell (especially `zsh`!), it is usually because the shell does not understand the input sequence and is translating it to that `<XX>` string instead.

If you try entering that same input into an editor (eg: `vim`), does it appear as you expect?

Take a look at this FAQ entry: https://wezfurlong.org/wezterm/faq.html#pasting-or-entering-unicode-in-zsh-looks-broken which may influence zsh's behavior.

**Comment by jdhao** [comment]
1. I am typing inside nvim (which is in turn opened nvim zsh), not directly inside zsh.
2. This issue only occurs occasionally, not all the time, i.e., with IME on, I can input `。` correctly sometimes, and all of a sudden, the bug occurs, which is why I can not reproduce it reliably.

**Comment by wez** [comment]
Then I think this might be an nvim bug or configuration. Can you try it in vim or another editor?

`。` encoded as UTF-8 has the byte sequence: `e3 80 82`.

`e3` in ISO-8859-1 is the `ã` character.

wezterm only produces UTF-8, never any other encoding (it doesn't know how to produce anything else), so it seems to me as though nvim is misinterpreting the input text and producing that incorrect result.

Are there configuration options in nvim where it might try to auto-detect the input encoding?
Are your LANG and locale related environment variables set to a UTF-8 locale?

**Comment by wez** [comment]
I'd suggest setting [debug_key_events = true](https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html) and launching wezterm from another terminal so that you can see the key input logging.
Then reproduce the issue and share the logs from around the place where it misbehaves.
