### ISSUE TITLE
color residue after exiting vim

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#169]
## Describe the bug

Color residue after exiting vim.
Need to use `reset` command to reset the colors after quiting vim.

## Environment

 - OS: Linux X11
 - Frontend:  OpenGL
 - Version: wezterm 20200406-151651-5b700e4
- vim:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 13:23:00)
Included patches: 1-510
Compiled by Arch Linux

(side note: might be have a command that will auto print this as part of `-V`?

## To Reproduce

Open terminal vim with solaried dark theme and quit. No theme were set in wezterm.

## Expected behavior
It should use wezterm default theme and not partial theme from vim.

## Screenshots

![image](https://user-images.githubusercontent.com/287744/79644618-f83ede00-815e-11ea-97da-8b169f45c40e.png)

Doesn't repro in xterm.

**Comment by wez** [comment]
Please install the `script` utility and then capture a session recording.  If you're running from the git repo you can use the `wt-record` script to do that, but you can also run it manually; this will spawn a new wezterm:

```bash
NOW=`date -u +%Y%m%d%H%M%S`
wezterm start -- script -t$NOW.timing $NOW.typescript
tar -cz --remove-files -f $NOW.tgz $NOW.timing $NOW.typescript
```

In the spawned wezterm, run through your test and then exit the shell (CTRL-D or just type `exit`) and then attach the `$NOW.tgz` to this issue.

Please also attach the output from running `infocmp` on that system, as this sort of thing can be influenced by the terminfo database.

Finally, please also attach the output from `set`; I'm most interested in the prompt related settings if you don't want to include the whole of that.

**Comment by prabirshrestha** [comment]
attached below.

[infocmp.log](https://github.com/wez/wezterm/files/4498073/infocmp.log)
[20200418235739.t.gz](https://github.com/wez/wezterm/files/4498077/20200418235739.t.gz) - rename this `.t.gz` to `tgz`. github didnt allow to upload `.tgz` extension.

prompt and shell related settings:

```
PS1='[\u@\h \W]\$ '
PS2='> '
PS4='+ '
SHELL=/bin/bash
SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
SHLVL=1
TERM=xterm-256color
```

**Comment by wez** [comment]
Thanks for the report!  I've pushed a commit that should take care of this.

Alternatively, you can workaround it by adding an SGR reset escape at the front of your PS1, something like this:

```bash
PS1="\x1b[0m[\\u@\\h \W]\\$ "
```

**Comment by prabirshrestha** [comment]
Awesome. It works. Thanks for the quick fix. This was quite an annoying one for me.
