### ISSUE TITLE
wezterm does not reload config if it's a symlink (and target has changed)

### ISSUE THREAD

**Issue by colemickens** [wez/wezterm#1697]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

wezterm doesn't reload config automatically. I looked at the code and I think it just boils down to this: https://github.com/notify-rs/notify/issues/381

### Configuration

n/a

### Expected Behavior

it reloads the config when the symlink target is updated

alternatively, if we could send a signal to wezterm to reload config, I could handle this externally very easily.

(is there a way to listen for a signal in lua?)

**Comment by wez** [comment]
Please provide more information on your configuration; I need specifics on where the files actually live and where the symlinks are, how often they change, how they change and so on.

**Comment by colemickens** [comment]
Of course, sorry for not just including that up-front - it can be a lot of detail so I try to omit it generally.

I'm using Nix/NixOS and Home-Manager to manage my system config. For example, last night I extended `nix-rice` to be able to utilize iterm2-colorschemes in Nix, and then I configured my `zellij`, `wezterm`, and `alacritty` modules to use one of these schemes. This now means a single string value change changes the theme across all of my terminal apps.

When I re-generate my system config, effectively my entire system is built immutably. For config files in /etc, and for config in /home (via home-manager), this means they appears as:
- symlinks in the "config" location
- those symlinks point to read-only files in `/nix/store/...`

So what happens is, I "rebuild and activate" the symlinks are replaced with new ones that point to their new read-only immutable store files. As this happens:
* `waybar` reloads (this is because we have a hook into the update process and send a signal to waybar procs)
* `alacritty` reloads, apparently it's watcher notices the symlink update
* `wezterm` does **not** notice the update and I have to manually reload.

It did also occur to me that there might be another out-of-band way to "listen" from lua and then trigger the reload, but I'm not really experienced enough here to know for sure.

**Comment by colemickens** [comment]
I tried `add_to_config_reload_watch_list` with wezterm's entire config dir and it does the trick. Thanks!

**Comment by wez** [comment]
Did you try literally `wezterm.add_to_config_reload_watch_list(wezterm.config_dir)` or did you need to specify the config dir some other way?

**Comment by blmhemu** [comment]
On the same boat, The following worked.
```
wezterm.add_to_config_reload_watch_list("/home/user/.config/wezterm/")
```

**Comment by wez** [comment]
OK, I've added logic to make wezterm do this automatically
