### ISSUE TITLE
fragment shader artefact

### ISSUE THREAD

**Issue by Lompik** [wez/wezterm#17]
Some color artefacts shows up around the font on certain fg / bg combinations :
![2019-02-05-11 35 19_1440x324 0 1849](https://user-images.githubusercontent.com/3791334/52259511-6a514b80-293c-11e9-9534-09d361c5250c.png)

Instead if i use ```color.rgb = o_fg_color.rgb``` in place of the ```multiply``` in the fragment shader, artefacts are gone.
![2019-02-05-11 35 21_1440x338 0 2197](https://user-images.githubusercontent.com/3791334/52259519-74734a00-293c-11e9-98d6-ccc7353957e4.png)

 In my case, Freetype returns a gray-level bitmap, so all color rgba are the same value (between 0 & 1.0). But it works also with a colored font.

is there a better fragment shader ?

screenshots are outputs of https://github.com/eikenb/terminal-colors/blob/master/terminal-colors with ```-o```

**Comment by wez** [comment]
Thanks for reporting this and suggesting a resolution!

I'm no shader expert, and what you suggested does appear better to me, so I've applied that change to the repo.
