### ISSUE TITLE
Background Color Handling

### ISSUE THREAD

**Issue by radj307** [wez/wezterm#1709]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220101-133340-7edc5b5a (Nightly: 20220310-055045-d5391fa5)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm doesn't allow transparency when using escape sequences to set background colors, resulting in some very strange behaviour.

Here is an image showing the problem:  
_(I erased some of the more sensitive information, but did not change the background colors at all)_  
![image](https://user-images.githubusercontent.com/1927798/157716759-43541952-c432-457b-821b-61a50070c992.png)

### To Reproduce

 1. Set the background color to anything using the escape sequence `CSI 48;5;`___(SGR)___`m`.
 2. Reset the background color to black using `CSI 48;5;0m`.
 3. Observe strange behaviour.

### Configuration

```lua
window_background_opacity = 0.5,
-- This happens with any value other than `1.0`
```

### Expected Behavior

Correctly apply transparency to background colors.

This is the correct output in Visual Studio's cmd, using the same background transparency of 50%:  
![image](https://user-images.githubusercontent.com/1927798/157714445-404fe3e3-78dc-4110-a1a3-69810a8920e8.png)

### Logs

This is the output from the debug window:
```
12:01:35.489 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
12:01:35.638 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(9001))
12:01:35.666 INFO wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GTX 1070/PCIe/SSE2 4.5.0 NVIDIA 511.79 is_context_loss_possible=true wezterm version: 20220101-133340-7edc5b5a
12:01:36.843 WARNING wezterm_font > No fonts contain glyphs for these codepoints: \u{f898}.
                                                                                           Placeholder 'Last Resort' glyphs are being displayed instead.
                                                                                                                                                        You may wish to install additional fonts, or adjust your
        configuration so that it can find them.
                                               https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
                                                                                                                                             Set warn_about_missing_glyphs=false to suppress this message.
```

### Anything else?

This is the code that causes it:  
![image](https://user-images.githubusercontent.com/1927798/157714306-077c62d3-ee94-429b-a56f-0a774ac900d3.png)

**Comment by wez** [comment]
Take a look at https://wezfurlong.org/wezterm/config/appearance.html#text-background-opacity

**Comment by radj307** [comment]
Thanks for the quick response!  
After changing `text-background-opacity` to match _(`0.5`)_, the problem seems to persist:  
![image](https://user-images.githubusercontent.com/1927798/157769555-3d515b93-25ee-47e4-9aa7-34769016e790.png)

**Comment by radj307** [comment]
Also of note, using the SGR reset sequence `CSI 0m` does work:  
![image](https://user-images.githubusercontent.com/1927798/157772720-ac84f8b3-3cd6-4374-a060-ea9c4715ab12.png)  
...but it also resets all other attributes in the terminal, which is a bit of a non-starter.

**Comment by wez** [comment]
I'm having a hard time understanding what the problem is because the color contrast and hue in your screen shots is really hard for me to perceive a difference :-(

> Is there a preferred way to reset the background color of terminal text when using wezterm?

`CSI 49 m` is the ANSI escape sequence to reset the background color to the default color: `ESC [ 49 m`

**Comment by radj307** [comment]
Sorry about the contrast, I went for 50% transparency which is a little much.

The problem as I saw it is the discrepancy between black-background text on other terminal emulators vs wezterm. However, I realized this might be by-design, and if that is the case then there isn't really a problem & I'll close the issue.

Here's a better example of the discrepancy.  
This code:
```cpp
std::cout
  << "\033[48;5;0m"
  << "black background"
  << "\033[49m"
  << "  "
  << "no background"
  << '\n';
```
produces this output on wezterm:  
![image](https://user-images.githubusercontent.com/1927798/157786704-16c890d7-c919-462b-88d7-343f9581c0e8.png)
and this output on mintty:  
![image](https://user-images.githubusercontent.com/1927798/157786716-4cbc2514-bfb1-485b-8051-582dea176f56.png)

Thanks for the suggestion to use `CSI 49 m`, I guess I missed that when looking at the table of SGR sequences; It works as expected.

**Comment by wez** [comment]
wezterm looks to see if a cell has its background set to the default background (eg: as set by `CSI 49 m`). If it has default background color then `window_background_opacity` will be used to specify the alpha channel value for its background.

Otherwise, `text_background_opacity` is used.  wezterm doesn't do color matching for this assessment, so if a cell is explicitly set to black and the default background happens to be black, that is *not* treated the same as the default background color, and the `text_background_opacity` is needed to specify the alpha channel.

Over in https://github.com/PerBothner/DomTerm/issues/109 we've been discussing the idea of an escape sequence to allow specifying RGB and A values for fg and bg that will make this sort of thing more explicitly controllable by an application.
