### ISSUE TITLE
Mouse cursor changes on tabbar and scrollbar

### ISSUE THREAD

**Issue by deathtrip** [wez/wezterm#1715]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Wezterm doesn't use the system mouse cursor on the tabbar and the scrollbar, instead it changes it to this:

![wezterm-cursor](https://user-images.githubusercontent.com/8403455/158076535-c3d9d144-023b-4a88-afc6-223d44f6d6d9.jpeg)

### Configuration

no config

### Expected Behavior

Mouse cursor should not change.

**Comment by wez** [comment]
Please try the nightly build!

**Comment by deathtrip** [comment]
I just tried to install the nightly version from the AUR, but there seems to be an error in the PKGBUILD:

> /home/deathtrip/.cache/pikaur/build/wezterm-nightly-bin/PKGBUILD: line 39: /tmp/makepkg/wezterm-nightly-bin/src/wezterm: Permission denied  
==> ERROR: pkgver is not allowed to be empty.
==> ERROR: pkgver() generated an invalid version:


Also, when starting wezterm i get the OpenGl initialization error discussed in #1471 ,not sure but it can have something to do with it.

**Comment by deathtrip** [comment]
It doesn't happen on nightly, so it seems fixed. I'm gonna close this.
