### ISSUE TITLE
cursor still blinks despite setting to Steady* and even setting cursor_blink_rate to 0

### ISSUE THREAD

**Issue by bsferrazza** [wez/wezterm#1720]
This is using the latest Windows .zip file, https://github.com/wez/wezterm/releases/download/20220101-133340-7edc5b5a/WezTerm-windows-20220101-133340-7edc5b5a.zip

**Comment by wez** [comment]
Please try the nightly build

**Comment by bsferrazza** [comment]
Thank you. That totally worked. Really enjoying WezTerm, btw. Finally a terminal emulator that is truly cross-platform and allows font fallbacks on my company issued Windows PC. And was able to get mosh working using the cygwin binary. Cheers!

**Comment by xpufx** [comment]
> Thank you. That totally worked. Really enjoying WezTerm, btw. Finally a terminal emulator that is truly cross-platform and allows font fallbacks on my company issued Windows PC. And was able to get mosh working using the cygwin binary. Cheers!

Doesn't wezterm ssh domains provide the functionality of both tmux and mosh ?
