### ISSUE TITLE
WezTerm gets stuck when a URL-click opens a *new* browser session

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#1721]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220312-150607-d22b7a51

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm gets stuck if a new browser session is opened by clicking a URL. This doesn't happen when the browser is already running. ~Happens~ Tested in both Firefox and Luakit (uses Webkit-GTK)

### To Reproduce

1. Close the browser if already open.
2. Type `https://www.example.com` in WezTerm.
3. Click it.
4. WezTerm will be stuck.

Note: If you do anything like typing something or opening new tab, WezTerm will do all that after the browser is closed.

### Configuration

NIL

### Expected Behavior

WezTerm should run normally even if clicking URL results in a new browser session.

### Anything else?

https://user-images.githubusercontent.com/8190126/158339794-fb8f099e-f83b-4e2d-9079-83e9325591b4.mp4

**Comment by bew** [comment]
I second that, this is happening since a long time, but never bothered reporting it.. (very easy to workaround, just start a browser)
