### ISSUE TITLE
scrolling up is followed by scroll down in neovim on windows

### ISSUE THREAD

**Issue by KitCarson03** [wez/wezterm#1725]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

when running neovim on windows and trying to scroll up a buffer using the touchpad (with mouse it works properly) at the end of scrolling up there is a scroll down not given in input.

### Configuration

```lua
local wezterm = require 'wezterm'

return {
  default_prog = {"powershell"},
  exit_behaviour = "Close",
  color_scheme = "Gruvbox Dark",
  window_decorations = 'RESIZE',
  warn_about_missing_glyphs = false,
  font = wezterm.font_with_fallback({
    "Cascadia Mono PL",
    "JetBrains Mono"}),
  initial_cols = 100,
  initial_rows = 40,
  font_size = 10,
  keys = {
    {key=' ', mods="CTRL", action = {Multiple = {
      {SendKey={key="x", mods="CTRL"}},
      {SendKey={key="o", mods="CTRL"}},
    }}},
    {key='1', mods='ALT', action = "DisableDefaultAssignment"},
    {key='2', mods='ALT', action = "DisableDefaultAssignment"},
    {key='3', mods='ALT', action = "DisableDefaultAssignment"},
    {key='4', mods='ALT', action = "DisableDefaultAssignment"},
    {key='5', mods='ALT', action = "DisableDefaultAssignment"},
    {key='6', mods='ALT', action = "DisableDefaultAssignment"},
    {key='7', mods='ALT', action = "DisableDefaultAssignment"},
    {key='8', mods='ALT', action = "DisableDefaultAssignment"},
    {key='9', mods='ALT', action = "DisableDefaultAssignment"},
    {key='0', mods='ALT', action = "DisableDefaultAssignment"},
  },
}
```

**Comment by wez** [comment]
Could you also provide some information about your touchpad make/model?

**Comment by kaddkaka** [comment]
I have had the same scrolling behavior with a TouchPad from an HP laptop. I would set it scrolling up (much like you can flick a long web page on an android phone to keep scrolling after you let go of the screen) but once it stops it would start going down without me doing anything.

**Comment by KitCarson03** [comment]
The laptop model is a Lenovo Ideapad Gaming 3, the productor doens't provide information about the touchpad model but there is a Elantech Touch Pad Firmware 1.0.0.1 installed so probably that's the model
