### ISSUE TITLE
Allow scrolling between tabs with the mouse wheel like Google Chrome

### ISSUE THREAD

**Issue by sharifhsn** [wez/wezterm#1726]
**Is your feature request related to a problem? Please describe.**
Not really a *problem* per se, but I'm very used to the behavior in Google Chrome (and optionally enabled in Visual Studio Code) which allows you to scroll back and forth through tabs with the scroll wheel on the mouse.

**Describe the solution you'd like**
Provide an opt-in option in the `wezterm` config to scroll between tabs with the mouse scroll wheel while the mouse is on the tab.

**Describe alternatives you've considered**
Clicking between tabs is fine, but scrolling would be more convenient.

**Additional context**

**Comment by eaglgenes101** [comment]
Can this be configurable? I personally would prefer not to have this on, as a scroll when the mouse happens to be on the tab bar row causes the panes to switch in rapid succession, but understandably others have their own preferences.
