### ISSUE TITLE
support Chinese input method

### ISSUE THREAD

**Issue by diucicd** [wez/wezterm#1728]
**Is your feature request related to a problem? Please describe.**
switch to Chinese input method can not input Chinese in terminal console, but Alaritty support it well.

**Comment by wez** [comment]
Please try the nightly build!

**Comment by jgcodes2020** [comment]
just tried nightly, i'll say that it doesn't work (Ubuntu 21.10 Wayland, GNOME)

**Comment by diucicd** [comment]
Just tried the nightly version, and it works! Awesome, @wez !
