### ISSUE TITLE
Windows: Repeating dead keys is not consistent with other Windows programs

### ISSUE THREAD

**Issue by bew** [wez/wezterm#1729]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220317-165235-27088fab

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Repeating a dead key like `^` twice is not consistent with other windows programs.

On these other Windows programs, when repeating a dead key it's inserted twice (note: on Linux it's inserted once, I don't know the behavior for MacOS).
On Wezterm, repeating a dead key inserts it once: `^` then `^` sends a single `^`, whereas on chrome for example it sends `^^`.

### Configuration

`return {}`

### Expected Behavior

**> If I'm being pragmatic:**
be consistent with other windows programs, and send `^^` when pressing dead key twice.

**> If I want a unified behavior across systems:**
I'd like to keep the existing behavior, where typing `^` then `^` sends a single `^`..
👉 Maybe it could be behind an option? like `dead_keys_repeat_mode = "System|Linux|Windows"` (assuming MacOS works like Linux))

**Comment by wez** [comment]
I opted to just make this consistent with other windows apps: making configurable feels a bit too difficult and I double most people would want to have one app that doesn't behave like the others :)

**Comment by bew** [comment]
Yeah well, I suspected you'd do that ^^
At least it's consistent now
