### ISSUE TITLE
Restore binary blinking of cursor

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#1738]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220319.142410.0fcdea07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, this version is just recently released so is fairly up-to-date.

### Describe the bug

I want binary blinking of the cursor, and no animations/fading whatsoever.

https://github.com/wez/wezterm/blob/ee5d5714ca3e4734f01c346c55780f030fd31ad7/docs/config/lua/config/animation_fps.md says we can use:

```lua
animation_fps = 1,
```

However even with this setting, after typing a letter, the cursor still slowly fades out.

### To Reproduce

Type 1 letter.

### Configuration

```lua
-- Cursor
default_cursor_style = 'BlinkingBlock',
cursor_blink_rate = 500,
animation_fps = 1,
```

### Expected Behavior

The letter will fade out slowly, but there should be no fading out at all.

**Comment by CIAvash** [comment]
I don't know if there is another way, but you can specify the ease in/out functions:
```lua
cursor_blink_ease_in = {CubicBezier={0.0, 0.0, 0.0, 0.0}},
cursor_blink_ease_out = {CubicBezier={0.0, 0.0, 0.0, 0.0}},
```

**Comment by stevenxxiu** [comment]
Thanks! That works.

I'll leave this open to see if @wez knows a better way, or if this is the best way.

**Comment by wez** [comment]
I'd suggest setting the easing function to `"Linear"`, which I think is equivalent to that cubic bezier with all zeroes.

You can play with beziers at:

https://cubic-bezier.com/#0,0,0,0

**Comment by CIAvash** [comment]
From MDN on Linear:
> This keyword represents the easing function cubic-bezier(0.0, 0.0, 1.0, 1.0).

I think it may not be a bad idea to add zeroes as a `Constant` function. This term is used in Blender to refer to no interpolation.

**Comment by stevenxxiu** [comment]
> I'd suggest setting the easing function to "Linear", which I think is equivalent to that cubic bezier with all zeroes.

Don't think that's the case, as the cursor animates when I set:

```lua
cursor_blink_ease_in = 'Linear',
cursor_blink_ease_out = 'Linear',
```

**Comment by wez** [comment]
I added `Constant` as an easing function and added an example to the docs

**Comment by CIAvash** [comment]
@wez I really appreciate you and what your'e doing, you are truly great!
