### ISSUE TITLE
how to disable update notifications?

### ISSUE THREAD

**Issue by eruizc-dev** [wez/wezterm#1739]
**Is your feature request related to a problem? Please describe.**

Getting a notification + banner on my terminal that an update is available is distracting and annoying

**Describe the solution you'd like**

Do not notify about updates by default

**Describe alternatives you've considered**

Notify by default but allow a config flag to disable it

**Additional context**

This is what I mean
![image](https://user-images.githubusercontent.com/58179604/159169154-e103d185-6fd8-4b35-80b4-895611e8d264.png)

In addition to the desktop notification I couldn't screenshot

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/config/check_for_updates.html

**Comment by eruizc-dev** [comment]
Oh nice, I was not expecting it to be under lua reference! You can close the issue now unless you see a doc improvement (by the fact you labeled this with docs)

If it serves as documentation purposes this is what I looked for:

 1. Searched in docs for update (now I see it is the 9th entry, but stopped looking after seeing so many entries for change logs)
![image](https://user-images.githubusercontent.com/58179604/159179744-94ddc20c-be1c-4313-b1ac-9254acd9cf3d.png)
 2. Looked in the install section
![image](https://user-images.githubusercontent.com/58179604/159179793-4eb8d9d1-745b-485e-aa05-21afbf709da6.png)
 3. Looked in configuration
![image](https://user-images.githubusercontent.com/58179604/159179813-66270e78-3141-4061-af06-589493996153.png)
 4. Searched through GitHub issues and found nothing

Thank you for creating and maintaining this awesome tool :heart:

**Comment by wez** [comment]
Thanks for sharing what you searched for.  It's a bit unfortunate for that particular keyword; mdbook has limited ability to influence the search results and I don't think it's possible to do better with this, without making it more difficult to find other sections of the docs.

Hopefully the presence of this issue here on GH helps others in the future!
