### ISSUE TITLE
Incorrect scaling after sleep with external monitor

### ISSUE THREAD

**Issue by SteadBytes** [wez/wezterm#1745]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220321-074757-aba3da6a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When waking from sleep with a scaled external display, Wezterm _sometimes_ does not scale correctly - leading to a very small UI. I am using a 4K external monitor via thunderbolt with "Larger text" scaling configuration and the laptop _closed_. 

In this screenshot, the top instance of Wezterm was running prior to sleep and the bottom instance was opened after waking to show the scaling difference.

<img width="597" alt="Screenshot 2022-03-21 at 19 03 35" src="https://user-images.githubusercontent.com/14834132/159346960-3d2aece3-efcb-4b19-8eeb-924977c5e26a.png">

This doesn't happen every time and I've been unable to pin-point any behaviour differences that do/not trigger it. Once the scaling is incorrect, no manner of moving/resizing the window causes it to correct itself.

### To Reproduce

1. Configure an external monitor with scaling
2. Open Wezterm
3. Shut MacBook lid to use only the external monitor
4. Unplug thunderbolt to the monitor
5. Wait for MacBook to sleep
6. Open lid, log in, plug in thunderbolt cable and close the lid
7. Wezterm _may_ have incorrect scaling

Note: I have reproduced this on two different MacBook Pro M1 devices (using the same external display).

### Configuration

no config

### Expected Behavior

Wezterm retains it's UI scaling from prior to sleep.

**Comment by wez** [comment]
Probably a duplicate of #1566

**Comment by SteadBytes** [comment]
Yep that does sound like the same issue - apologies for the duplicate.

Is there anything I can do to help track down the cause? (additional debug info, logs etc)

**Comment by SteadBytes** [comment]
With a sample size of 1, https://github.com/wez/wezterm/commit/409ff74b8432c21f93c99c3acf028aa8b9c39c28 does _seem_ to have addressed the problem (top instance is the latest nightly, bottom is stable):

<img width="597" alt="Screenshot 2022-03-22 at 19 43 15" src="https://user-images.githubusercontent.com/14834132/159563127-6d59e590-b41a-4804-b6d5-0a71a2df44a3.png">

I'll keep running nightly for a while to see if the issue crops up again in normal usage but for now I'll close this issue. Thank you @wez for taking a look at this so promptly (and for your work on wezterm in general of course)!
