### ISSUE TITLE
Add an option to remove title bar in gnome

### ISSUE THREAD

**Issue by jsomedon** [wez/wezterm#1748]
**Is your feature request related to a problem? Please describe.**
There is no option to hide title bar in gnome.

**Describe the solution you'd like**
Add an option to hide title bar.

**Describe alternatives you've considered**
No alternate solution that I know about.

**Additional context**
None

**Comment by jubalfh** [comment]
i think that [`window_decorations`](https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html?highlight=window_decorations#window_decorations--title--resize) might be what you're looking for.

**Comment by wez** [comment]
Yep, `window_decorations` is what you're looking for!

**Comment by jsomedon** [comment]
hmm I just saw this:
> This feature is not supported on Wayland; the titlebar and resizable border are always requested by wezterm.

I wonder when does wezterm support wayland?

**Comment by jsomedon** [comment]
The title bar is gone but there is this extra blank line on the bottom of the window. Anyway to fix that?
![ss](https://user-images.githubusercontent.com/2172297/159707450-3a9f75e6-9d3b-4aca-9f6c-3845ae345ac5.png)

**Comment by jubalfh** [comment]
@jsomedon does that change when you resize the window or is it always a whole line? (i'm running wezterm in gnome + pop-shell extension, so my terminal windows are always maximised within the tile, and don't see this type of behaviour, but i'm defining wezterm internal padding explicitly and have `adjust_window_size_when_changing_font_size` set to `false` for good measure.)
