### ISSUE TITLE
Box drawings arcs look weird

### ISSUE THREAD

**Issue by samoylovfp** [wez/wezterm#1753]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220322-095052-5c8ff787

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Arcs do not look the constant width, they "thin out" in the middle
![image](https://user-images.githubusercontent.com/17025459/159647416-ea23438e-bb4b-4ec2-a77d-c57caa357cd2.png)

They do look better with extreme zoom
![image](https://user-images.githubusercontent.com/17025459/159647273-a0e4babc-4966-48f4-a85f-c4b02473e665.png)

This is how gnome-terminal renders those on the default zoom level
![image](https://user-images.githubusercontent.com/17025459/159647364-2ec197f9-3984-40c1-814c-ba9af2fe047b.png)

and zoomed out
![image](https://user-images.githubusercontent.com/17025459/159647605-a1a6c685-d8e8-4c7c-84a5-ffd330dbbdef.png)

### To Reproduce

```bash
printf "\u256D\n"
```

### Configuration

no config

### Expected Behavior

I expect the width of the arc be constant

### Logs

09:35:14.138 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-138002
09:35:14.310 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 21.2.6 is_context_loss_possible=false wezterm version: 20220319-142410-0fcdea07
09:36:32.178 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 0

### Anything else?

Thanks for the awesome tool!

**Comment by samoylovfp** [comment]
I'll try to take a look an see if this is an easy fix

**Comment by samoylovfp** [comment]
Disabling aliasing in [wezterm-gui/src/customglyph.rs#L3662](https://github.com/wez/wezterm/blob/5c8ff787c67d80b501dc9081dda92dd6da7d17b8/wezterm-gui/src/customglyph.rs#L3662) seems to be fixing the drawing issue, which probably means that there is an issue in the `tiny-skia` antialiasing, will try to reproduce

**Comment by samoylovfp** [comment]
I've repeated the sequence of calls in tiny-skia and got this
![image](https://user-images.githubusercontent.com/17025459/159697578-b75c7069-cfd5-40b9-b0d3-9f08279052b0.png)
which looks like it has more consistent width than what wezterm renders.

I am not sure now if the problem is in what skia returns or somewhere between the skia result and the screen

**Comment by wez** [comment]
I haven't had a chance to dig into this, but I wonder if the issue here is something like the coordinates being a fraction of a pixel and the AA has a hard time rendering a decent stroke--instead of a single solid white pixel it might produce a pair of dim grey pixels.

This class of problem is addressed in font rendering through "hinting" which is a fancy way of saying that coordinates get artificially shifted to integer pixel boundaries.

**Comment by wez** [comment]
I just added the ability to `anti_alias_custom_block_glyphs = false` to `main`.  I don't consider this a great solution, it's just an option for now.
