### ISSUE TITLE
A red window icon is shown instead of a blue one

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#1754]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220319.142410.0fcdea07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

I built the latest commit 5c8ff787c67d80b501dc9081dda92dd6da7d17b8. The bug is still present.

### Describe the bug

The *WezTerm* window icon in my taskbar is red instead of being blue since the latest release.

![Screenshot_2022-03-23_20-36-09](https://user-images.githubusercontent.com/2058940/159668717-2e1a13e4-b4fa-40fb-a47c-51969627b822.png)

### To Reproduce

Run *WezTerm*.

### Configuration

The configuration doesn't matter, but having no config will reproduce this.

### Expected Behavior

The blue icon https://github.com/wez/wezterm/blob/20220319-142410-0fcdea07/assets/icon/terminal.png is shown instead.

### Anything else?

I bisected this, and the first bad commit is 435ff1e93b7648945a131644f3a0c1117ebeaf2a. [`apply_icon()`](https://github.com/wez/wezterm/blob/20220319-142410-0fcdea07/wezterm-gui/src/termwindow/mod.rs#L1059) appears to be related to this issue. It now loads the image using RGB instead of BGR.

Probably related to https://github.com/image-rs/image/issues/1686.

**Comment by wez** [comment]
Thanks; I fixed this in a slightly different place!
