### ISSUE TITLE
`force_reverse_video_cursor = yes` is set, the text color under the cursor is affected by the transparency of the window

### ISSUE THREAD

**Issue by shelaf** [wez/wezterm#1758]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220323-070126-623f6179

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`force_reverse_video_cursor=yes` is set, the text color under the cursor is affected by the transparency of the window

alacritty:
https://user-images.githubusercontent.com/980272/159769067-a01bed91-1429-4045-b61d-fcc218a4560d.mp4

wezterm:
https://user-images.githubusercontent.com/980272/159769092-036270b9-5f01-40eb-ad5c-5e81e7d94308.mp4

Probably a similar issue, cursor border color is affected by the `cursor_border` setting when wezterm is inactive.

alacritty:
![alacritty](https://user-images.githubusercontent.com/980272/159770596-976f4fe3-fc55-4e5e-811a-06ba6d6f4c50.png)

wezterm:
![wezterm](https://user-images.githubusercontent.com/980272/159770628-a2c7f5d3-364d-4ffb-be11-729dcc0495b6.png)

### To Reproduce

Apply the following configurations.

### Configuration

```
local wezterm = require "wezterm"
return {
  font = wezterm.font("Monospace", {weight="Regular"}),
  font_size = 12.0,
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},
  exit_behavior = "Close",
  tab_bar_at_bottom = true,
  scrollback_lines = 10000,
  window_background_opacity = 0.9,
  default_cursor_style = "BlinkingBlock",
  force_reverse_video_cursor = true,
  cursor_blink_rate = 600,
  cursor_blink_ease_in = {CubicBezier={0.0, 0.0, 0.0, 0.0}},
  cursor_blink_ease_out = {CubicBezier={0.0, 0.0, 0.0, 0.0}},
  window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
  },
  colors = {
    foreground = "#dcdccc",
    background = "rgba(63, 63, 63, 90%)",
    selection_fg = "none",
    selection_bg = "#242424",
    cursor_border = "#dcdccc",
    ansi = {"#3f3f3f", "#b57575", "#60b48a", "#dfaf8f", "#6183a5", "#dc8cc3", "#8cd0d3", "#dcdccc"},
    brights = {"#709080", "#dca3a3", "#c3bf9f", "#f0dfaf", "#94bff3", "#ec93d3", "#93e0e3", "#ffffff"},
  },
}
```

### Expected Behavior

Like alacritty, the text color under the cursor is not affected by the transparency of the window. 

### Logs

```
2022-03-23T18:46:18.664Z INFO  wezterm_gui::termwindow        > OpenGL initialized! NVIDIA GeForce GTX 970/PCIe/SSE2 4.6.0 NVIDIA 510.54 is_context_loss_possible=false wezterm version: 20220323-070126-623f6179
```

**Comment by Vanaldito** [comment]
I have the same problem when I use window_background_image

**Comment by wez** [comment]
I think this may be resolved by https://github.com/wez/wezterm/commit/28d803e3f4fe5f5ded0c1b48eb22e34820c82a25
Could you try the latest nightly build to confirm?

This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Vanaldito** [comment]
I tried the nightly version, and now it works perfectly, thanks.
