### ISSUE TITLE
Fallback font doesn't work for Chinese.

### ISSUE THREAD

**Issue by ekilzen** [wez/wezterm#1761]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220319-142410-0fcdea07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I set fallback font as document said, but it does not work.

```lua
local wezterm = require 'wezterm';

return {
    font_size = 16,
    font = wezterm.font_with_fallback({
        {family = "Input", stretch= "Expanded", weight = "Bold"},
        'Noto Sans Mono CJK SC',
    }),
    color_scheme = "Dracula+",
    line_height = 1.2,
    enable_tab_bar = false,
    window_padding = {
        left = 12,
        right = 12,
        top = 8,
        bottom = 8,
    },
    freetype_load_target = "Light",
}
```
![image](https://user-images.githubusercontent.com/10057502/159874257-182dd80c-4f78-4a9b-9bd0-67f0dbbfa666.png)

 I also tried Chinese font only.
```lua
font = wezterm.font_with_fallback({
        -- {family = "Input", stretch= "Expanded", weight = "Bold"},
        'Noto Sans Mono CJK SC',
    }),
```
![image](https://user-images.githubusercontent.com/10057502/159874664-50c91c60-1dff-4fec-907d-8704bc868dc8.png)

### Configuration

```lua
local wezterm = require 'wezterm';

return {
    font_size = 16,
    font = wezterm.font_with_fallback({
        -- {family = "Input", stretch= "Expanded", weight = "Bold"},
        'Noto Sans Mono CJK SC',
    }),
    color_scheme = "Dracula+",
    line_height = 1.2,
    enable_tab_bar = false,
    window_padding = {
        left = 12,
        right = 12,
        top = 8,
        bottom = 8,
    },
    freetype_load_target = "Light",
}
```

### Expected Behavior

Shows Chinese character instead question mark.

**Comment by Typas** [comment]
Can you show your `wezterm ls-fonts` result?
Mine is great with more complicated font fallback setting.
Even set with "Noto Serif CJK TC" it shows Chinese as I expect.

**Comment by ekilzen** [comment]
@Typas 
```shell
Primary font:
wezterm.font_with_fallback({
  -- /Users/like/Library/Fonts/JetBrainsMono-Bold.ttf, CoreText
  {family="JetBrains Mono", weight="Bold"},

  -- /Users/like/Library/Fonts/NotoSansCJK.ttc index=18 variation=0, CoreText
  "Noto Sans Mono CJK SC",

  -- /Users/like/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- /Users/like/Library/Fonts/JetBrainsMono-Medium-Italic.ttf, CoreText
  {family="JetBrains Mono", weight="Medium", style="Italic"},

  -- /Users/like/Library/Fonts/NotoSansCJK.ttc index=18 variation=0, CoreText
  -- Will synthesize italics
  -- Will synthesize dim
  "Noto Sans Mono CJK SC",

  -- /Users/like/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- /Users/like/Library/Fonts/JetBrainsMono-Medium.ttf, CoreText
  {family="JetBrains Mono", weight="Medium"},

  -- /Users/like/Library/Fonts/NotoSansCJK.ttc index=18 variation=0, CoreText
  -- Will synthesize dim
  "Noto Sans Mono CJK SC",

  -- /Users/like/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /Users/like/Library/Fonts/JetBrainsMono-ExtraBold.ttf, CoreText
  {family="JetBrains Mono", weight="ExtraBold"},

  -- /Users/like/Library/Fonts/NotoSansCJK.ttc index=30 variation=0, CoreText
  {family="Noto Sans Mono CJK SC", weight="Bold"},

  -- /Users/like/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- /Users/like/Library/Fonts/JetBrainsMono-ExtraBold-Italic.ttf, CoreText
  {family="JetBrains Mono", weight="ExtraBold", style="Italic"},

  -- /Users/like/Library/Fonts/NotoSansCJK.ttc index=30 variation=0, CoreText
  -- Will synthesize italics
  {family="Noto Sans Mono CJK SC", weight="Bold"},

  -- /Users/like/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- /Users/like/Library/Fonts/JetBrainsMono-Bold-Italic.ttf, CoreText
  {family="JetBrains Mono", weight="Bold", style="Italic"},

  -- /Users/like/Library/Fonts/NotoSansCJK.ttc index=18 variation=0, CoreText
  -- Will synthesize italics
  "Noto Sans Mono CJK SC",

  -- /Users/like/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})

Title font:
wezterm.font_with_fallback({
  -- /Users/like/Library/Fonts/Roboto-Bold.ttf, CoreText
  {family="Roboto", weight="Bold"},

  -- /Users/like/Library/Fonts/JetBrainsMono-Bold.ttf, CoreText
  {family="JetBrains Mono", weight="Bold"},

  -- /Users/like/Library/Fonts/NotoSansCJK.ttc index=18 variation=0, CoreText
  "Noto Sans Mono CJK SC",

  -- /Users/like/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


```

**Comment by wez** [comment]
wezterm doesn't use `?` for missing glyphs; instead, a placeholder from the last resort font will be used and a notification will pop up to tell you about the missing glyphs.

I think `ls` is outputting `?` instead of the appropriate glyphs because your `LANG` environment isn't set appropriately.

https://wezfurlong.org/wezterm/faq.html#lang-and-locale has a bit more information about this.

**Comment by ekilzen** [comment]
@wez Thanks, I set `LANG=en_US.UTF-8` and it works. 

But in the document it said "If you're running on macOS, upgrade to 20200620-160318-e00b076c or newer and WezTerm will automatically set LANG appropriately." Why does it not set by default right now?

**Comment by wez** [comment]
@ekilzen what is `LANG` set to on your system?  Is it unset or set incorrectly?

**Comment by ekilzen** [comment]
@wez It was unset.

**Comment by wez** [comment]
Thanks; I've pushed a commit that tries a bit harder to set LANG to something useful, and that will log if something went wrong.  That should show up in a nightly build within an hour of this comment being posted.  Please give it a try and let me know how it goes!

**Comment by zhangmx** [comment]
When I type some Chinese characters like '？',got the output like this:

<img width="576" alt="WX20220325-151903@2x" src="https://user-images.githubusercontent.com/1308646/160075053-0ac30e83-91a7-4ed9-8b6d-e21f484512b7.png">

**Comment by wez** [comment]
@ekilzen could you press `CTRL-SHIFT-L` to show the debug overlay?  I'm curious to see whether this fallback case was triggered when figuring out the `LANG` value:

https://github.com/wez/wezterm/commit/638278f7e74841315df6bae1c4c09d2b8aaf3c6f#diff-6fdef1573276ab558fca56abad26cfe19a078b5d75bfba265737bc6beebb896bR126

For that Chinese font, is `"微软雅黑"` a font that is available by default on macOS?  If not, where can I download it?

Something else to try is `wezterm ls-fonts --list-system` and see if that font shows up in that list.  Fonts can have multiple names in multiple languages, so it's possible that it will show up with an english name.

**Comment by ekilzen** [comment]
@wez 
![image](https://user-images.githubusercontent.com/10057502/160149548-895f07b3-447a-4f80-972a-fc8c06604331.png)
You can download the font here https://ekil-image.oss-cn-hangzhou.aliyuncs.com/chinese.msyh20220325232116.ttf
I can find it via `wezterm ls-fonts --list-system`, it has English name as 'Microsoft YaHei'.
```
↪ wezterm ls-fonts --list-system |rg chinese
wezterm.font("Microsoft YaHei", {weight="Regular", stretch="Normal", style="Normal"}) -- /Users/like/Library/Fonts/chinese.msyh.ttf, CoreText
```
The English name is valid in setting.
However, one of my Chinese fonts has name with "?????".
```
↪ wezterm ls-fonts --list-system |rg 喜鹊
wezterm.font("?????????", {weight="Regular", stretch="Normal", style="Normal"}) -- /Users/like/Library/Fonts/喜鹊古风小楷简体.ttf, CoreText
wezterm.font("XQmuyeJT", {weight="Regular", stretch="Normal", style="Normal"}) -- /Users/like/Library/Fonts/喜鹊木叶体简体版.ttf, CoreText
wezterm.font("XQxiaoqingsong", {weight="Regular", stretch="Normal", style="Normal"}) -- /Users/like/Library/Fonts/喜鹊小轻松体简体
版.ttf, CoreText
wezterm.font("XiQuezhaopaiti", {weight="Regular", stretch="Normal", style="Normal"}) -- /Users/like/Library/Fonts/喜鹊招牌体-Regular.ttf, CoreText
```
Does it causes by the font itself?

**Comment by wez** [comment]
I'll investigate the fonts a little later today; thanks!

For the debug logging, the debug overlay uses a ring buffer that I think has been filled up with the warnings from the fig related escape sequences.  Could you try running `wezterm` from inside wezterm, and sharing the output that shows up?

**Comment by wez** [comment]
> You can download the font here https://ekil-image.oss-cn-hangzhou.aliyuncs.com/chinese.msyh20220325232116.ttf I can find it via `wezterm ls-fonts --list-system`, it has English name as 'Microsoft YaHei'.
> 
> ```
> ↪ wezterm ls-fonts --list-system |rg chinese
> wezterm.font("Microsoft YaHei", {weight="Regular", stretch="Normal", style="Normal"}) -- /Users/like/Library/Fonts/chinese.msyh.ttf, CoreText
> ```

While that font does have an alias for `微软雅黑`, CoreText doesn't return that font when we ask for that name. :-(

> The English name is valid in setting. However, one of my Chinese fonts has name with "?????".
> 
> wezterm.font("?????????", {weight="Regular", stretch="Normal", style="Normal"}) -- /Users/like/Library/Fonts/喜鹊古风小楷简体.ttf, CoreText

That appears to be a limitation of the freetype API; you can see someone else with a similar issue over here: https://fonts.xfree86.narkive.com/5nT2eviq/font-family-name-problem

I think we can do better though, so I pushed 32bf0d281eab81cf08af98916bd1424a87e6b4e3 which causes wezterm to look at the underlying name table and decode the font names for itself.

I think you should then be able to see its name without the `????` characters.

**Comment by ekilzen** [comment]
![image](https://user-images.githubusercontent.com/10057502/160244186-1c330efd-438a-4b66-8b4c-efb452f2b238.png)
It is fixed, Good Work!

**Comment by ekilzen** [comment]
Is it possible to set font_size of a fallback font? 
![image](https://user-images.githubusercontent.com/10057502/160244595-bb954691-9ad5-452d-9a31-43331ee2a269.png)
![image](https://user-images.githubusercontent.com/10057502/160244604-174de5d2-c09d-45db-b90b-7bfe7b9f67fd.png)

**Comment by wez** [comment]
> Is it possible to set font_size of a fallback font?

Not directly: the terminal is a monospace grid whose cell size is derived from the requested font size.  Fallback fonts need to fit within that cell so it doesn't make sense to specify an alternate size.

https://wezfurlong.org/wezterm/config/lua/config/use_cap_height_to_scale_fallback_fonts.html is an option that exists to help deal with this sort of situation; it works by comparing metrics based on the size of roman capital glyphs and produces a scaling factor to use when displaying a fallback font.  Because it is roman-centric I'm not sure that it will be helpful with CJK right now.

Could you give it a try?  Set `use_cap_height_to_scale_fallback_fonts = true` in your config.

If it doesn't work, I'd be interested to see if we can make it work for CJK by teaching it to look at one or two CJK glyphs that are present in most fonts.  I'd appreciate your input on which glyphs are the best candidates for this!

https://github.com/wez/wezterm/blob/895a96f8421c7d61f8e1a03ca6ed637a05b29be4/wezterm-font/src/ftwrap.rs#L639-L646

**Comment by wez** [comment]
I just pushed a commit that allows you do something like this, which causes the YaHei font to be rendered at 1.5x the normal size:

```lua
local wezterm = require 'wezterm'

return {
  line_height = 1.2,
  font = wezterm.font_with_fallback({
    "JetBrains Mono",
    {family="Microsoft YaHei", scale=1.5},
  }),
}
```

**Comment by wez** [comment]
This is now documented at https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html#manual-fallback-scaling
