### ISSUE TITLE
Typo in `wezterm ls-fonts --list-system` output

### ISSUE THREAD

**Issue by dimitris-triantafyllidis** [wez/wezterm#1762]
The value for the key `style` is not quoted:
```wezterm.font("Z003", {weight="Medium", stretch="Normal", style=Italic}) -- /usr/share/fonts/gsfonts/Z003-MediumItalic.otf, FontConfig```
Maybe it's intentional for some reason?
This is a very nice project by the way, thank you!

**Comment by wez** [comment]
Thanks for the report! This is fixed now in `main` and will show up in the nightly downloads within an hour
