### ISSUE TITLE
With large rows/columns has extra "%" on startup.

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#1763]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220325-084058-4f2539f8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Mysterious "%" showing up on start. Was not there on the last release (vs nightly) build.

<img width="154" alt="Screen Shot 2022-03-25 at 12 44 27" src="https://user-images.githubusercontent.com/3060128/160165848-8b750fbf-7ef8-4876-84cb-7f64dbbc72f3.png">

### To Reproduce

Just start wezterm.

### Configuration

no config

### Logs

```
12:51:42.798 INFO wezterm_mux_server_impl::local > setting up /Users/glenn/.local/share/wezterm/gui-sock-63006
12:51:42.916 INFO wezterm_gui::termwindow > OpenGL initialized! Apple M1 Pro 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220325-084058-4f2539f8
12:51:52.923 ERROR wezterm_mux_server_impl::local > decoding a PDU: reading PDU length: EOF while reading leb128 encoded value
```

**Comment by wez** [comment]
That looks like something zsh would output... are you sure you didn't change something in your zsh config/startup?

https://github.com/vercel/hyper/issues/2144

**Comment by wez** [comment]
And: https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol/167600#167600

**Comment by gwww** [comment]
I ran the very latest and then the last release build. Only the latest has that. Will look...

**Comment by wez** [comment]
`wezterm -n start -- zsh --no-rcs` can be helpful to rule out zshrc issues

**Comment by gwww** [comment]
Thx for the command line to help rule out. Not there when I use that. Odd that it started with this new version. Looking at zsh start up now. Will report back.

**Comment by gwww** [comment]
In new version $LANG is en_CA.UTF-8.
In release build $LANG is also en_CA.UTF-8.

In starting release build about 10 times the % shows up there about 20% of the time. In latest build shows up 100% of the time.

When using `wezterm -n start -- zsh --no-rcs` to start the % does not show up.

When running with a empty .zshrc and no .zshenv the % shows up. Running zsh 5.8.1.

It appears to be something in the system startup. ¯\_(ツ)_/¯

I've ended up putting `unsetopt PROMPT_SP` in my .zshrc (from https://superuser.com/questions/645599/why-is-a-percent-sign-appearing-before-each-prompt-on-zsh-in-windows) which does the job.

Thanks for you help!!!!

**Comment by gwww** [comment]
I have narrowed this down to wezterm. Using `wezterm start -- zsh --no-rcs` to start and my `wezterm.lua` below, the problem happens. Note the commented out row/cols works (i.e.: no %).

```
local config = {}

-- config.initial_cols = 179
-- config.initial_rows = 47
config.initial_cols = 300
config.initial_rows = 100

return config
```

**Comment by wez** [comment]
Presumably the window is being resized smaller by the system while zsh is starting up.  What does `echo $COLUMNS x $LINES` show in that scenario?

**Comment by gwww** [comment]
177 x 49 -- resizing indeed; and it must be outputting an empty string when doing so.  It's when one of rows or cols is "huge" that this happens. When they are slightly larger than screen size it doesn't happen. Closing again, since I think you are right, zsh is doing something when the sizes are large.
