### ISSUE TITLE
Hover state of retro tab bar not updating on pointer exit from label's bottom or top.

### ISSUE THREAD

**Issue by dimitris-triantafyllidis** [wez/wezterm#1764]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220319-142410-0fcdea07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I tried to launch the nightly AppImage (or the archive, don't remember, but it was the latest) GUI but it crashes with an EGL error. I was able to use it to confirm the fix for my previous issue though since no GUI was needed there.

Basically what the title says.

### To Reproduce

- Enable the retro tab bar
- Create a few tabs
- Move the mouse pointer over a tab label
- Move the mouse pointer outside the label through its bottom or top side
- The label still has the "hover" look

### Configuration

```
local wezterm = require 'wezterm';
 
return {
    use_fancy_tab_bar = false,
}
```

### Expected Behavior

The label is displayed as inactive whenever the mouse pointer is not over it.

### Logs

```
20:49:45.759 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-105805
20:49:45.819 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon HD 7900 Series (TAHITI, DRM 3.42.0, 5.15.31-1-lts, LLVM 13.0.1) 4.6 (Compatibility Profile) Mesa 21.3.7 is_context_loss_possible=false wezterm version: 20220319-142410-0fcdea07
20:50:13.879 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 0
```

### Anything else?

- I use Arch Linux + i3, no gaps.
- Focusing another container with the keyboard triggers the state update.
- Changing focus by moving the mouse pointer outside the terminal's window through the left, right or bottom sides also triggers the update.
- Top side (i3 titlebar), no update
- New prompt, update

**Comment by wez** [comment]
This is fixed in `main` and should show up in a nightly download within ~30 minutes
