### ISSUE TITLE
Support CJK input

### ISSUE THREAD

**Issue by xfoxfu** [wez/wezterm#1765]
**Is your feature request related to a problem? Please describe.**

I cannot type CJK characters in WezTerm. After commiting the characters, an escaping sequence appears instead of the intended characters.

![](https://vip2.loli.io/2022/03/26/ALC1a5xDUKSEcJT.jpg)

![](https://vip1.loli.io/2022/03/26/TKlOYA4yMCW96i3.jpg)

![](https://vip2.loli.io/2022/03/26/Waj4UQsKLdR8nbI.jpg)

![](https://vip2.loli.io/2022/03/26/GtXMzgODVx9vC1h.jpg)

**Describe the solution you'd like**

Support CJK input.

**Describe alternatives you've considered**

N/A.

**Additional context**

I am using macOS with Squirrel input or the build-in Japanese input.

**Comment by wez** [comment]
I suspect an issue with the shell/environment, as CJK definitely works in wezterm.
I suspect that `LANG` isn't set correctly and that your shell is getting confused. 

See: https://wezfurlong.org/wezterm/faq.html#lang-and-locale for more information.

I would recommend trying the latest nightly build as https://github.com/wez/wezterm/commit/638278f7e74841315df6bae1c4c09d2b8aaf3c6f was pushed today to help ensure that `LANG` is set to something with a UTF-8 locale.

**Comment by xfoxfu** [comment]
Thanks for your so-fast reply. I have confirmed that my `LANG` is set to empty, and the latest nightly fixes the problem.

FYI, I am using macOS English with locale set to China.
