### ISSUE TITLE
FullScreen key assignment does nothing

### ISSUE THREAD

**Issue by wez** [wez/wezterm#177]
This was a casualty of migrating away from the `winit` crate, and because I rarely use that functionality except on Linux where the window manager often has an equivalent function, I haven't gotten around to adding it back yet.

https://github.com/wez/wezterm/issues/172

**Comment by mfiers** [comment]
I'd much appreciate this ability to return.

**Comment by wez** [comment]
The current status is that this is now working everywhere except Windows

**Comment by hnspn** [comment]
should I create another issue called "FullScreen key assignment does nothing on windows"?

**Comment by wez** [comment]
38e6a1b  made it work again on Windows, which is why this issue was closed.
If you're running version `20210314-114017-04b7cedd` or later and it doesn't work, please file a new issue.

**Comment by dufferzafar** [comment]
@wez Is there a way I can start the terminal in full screen mode by default?

**Comment by wez** [comment]
@dufferzafar: not yet, see https://github.com/wez/wezterm/issues/284
