### ISSUE TITLE
ERROR wezterm_gui > failed to open X11 display; terminating

### ISSUE THREAD

**Issue by timsofteng** [wez/wezterm#1774]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220319-142410-0fcdea07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Wezterm just doesn't start.

### To Reproduce

1. Open foot terminal.
2. Invoke `wezterm`

### Configuration

no config

### Expected Behavior

Should work in wayland

### Logs

 2022-03-27T10:22:17.286Z ERROR wezterm_gui > failed to open X11 display; terminating

### Anything else?

Distro:
Alpine linux edge

**Comment by wez** [comment]
This isn't a bug: wayland is not enabled by default as wayland support isn't quite as good as X11 support, so I recommend using XWayland.

See https://wezfurlong.org/wezterm/config/lua/config/enable_wayland.html for how to enable wayland.
