### ISSUE TITLE
wezterm doesn't terminate XTGETTCAP responses with ST

### ISSUE THREAD

**Issue by dankamongmen** [wez/wezterm#1781]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220327-153043-77e5cdd0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

see https://github.com/dankamongmen/notcurses/issues/2637 and #217. `ncplayer` is always starting off in ascii mode with wezterm, or so it seems. it's actually starting in pixel mode as expected, but due to a flurry of uninterpreted wezterm sequences, it switches to ascii.

notcurses queries wezterm using XTGETTCAP. wezterm responds, but does not terminate with ST as specified in https://invisible-island.net/xterm/ctlseqs/ctlseqs.html:

```
         xterm responds with
          DCS 1 + r Pt ST for valid requests, adding to Pt an = , and
          the value of the corresponding string that xterm would send,
          or
          DCS 0 + r Pt ST for invalid requests.
          The strings are encoded in hexadecimal (2 digits per
          character).
```

notcurses thus interprets the response as standard keyboard input. this can be seen by running `notcurses-input`.

### To Reproduce

run `ncplayer` with a video file. it will switch to ascii mode.

### Configuration

la di da

### Expected Behavior

terminate with ST

### Logs

la di da

### Anything else?

herp derp

**Comment by wez** [comment]
Heh, everything comes back around in the end :-p
The response is ST'd, but it is returned semicolon separated and doesn't consistently have the values hex encoded, so it's bad but simultaneously not as bad and worse than you might think.
