### ISSUE TITLE
Map `t` on keys not working

### ISSUE THREAD

**Issue by martinsrso** [wez/wezterm#1784]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220319-142410

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I tested following the documentation https://wezfurlong.org/wezterm/config/keys.html#physical-vs-mapped-key-assignments. 

I use Dvorak layout and the mapping is like QWERTY, even though I set it with the mapper command.

When I used `{ key = "mapped:r", mods = "SUPER", action = wezterm.action({ SpawnTab = "CurrentPaneDomain" }) }`, every key tested works except `t`.

This bug was reported through this issue. https://github.com/wez/wezterm/issues/1744

### Configuration

```
local wezterm = require("wezterm")

return {
	disable_default_mouse_bindings = true,
	exit_behavior = "Close",
	scrollback_lines = 3500,
	skip_close_confirmation_for_processes_named = {
		"bash",
		"sh",
		"zsh",
		"fish",
		"tmux",
	},
	font = wezterm.font("Hasklug Nerd Font"),
	-- font = wezterm.font("Monolisa", {weight="Regular", stretch='Normal', italic=false}),
	font_size = 15,
	color_scheme_dirs = { "$HOME/.config/wezterm/colors" },
	color_scheme = "solarized_light",
	use_fancy_tab_bar = false,
	tab_bar_at_bottom = true,
	hide_tab_bar_if_only_one_tab = true,
	tab_max_width = 40,
	window_padding = {
		left = 2,
		right = 2,
		top = 2,
		bottom = 2,
	},
	colors = {
		tab_bar = {
			-- The color of the strip that goes along the top of the window
			-- (does not apply when fancy tab bar is in use)
			background = "#eee8d5",

			-- The active tab is the one that has focus in the window
			active_tab = {
				-- The color of the background area for the tab
				bg_color = "#268bd2",
				-- The color of the text for the tab
				fg_color = "#fdf6e3",

				-- Specify whether you want "Half", "Normal" or "Bold" intensity for the
				-- label shown for this tab.
				-- The default is "Normal"
				intensity = "Normal",

				-- Specify whether you want "None", "Single" or "Double" underline for
				-- label shown for this tab.
				-- The default is "None"
				underline = "None",

				-- Specify whether you want the text to be italic (true) or not (false)
				-- for this tab.  The default is false.
				italic = false,

				-- Specify whether you want the text to be rendered with strikethrough (true)
				-- or not for this tab.  The default is false.
				strikethrough = false,
			},

			-- Inactive tabs are the tabs that do not have focus
			inactive_tab = {
				bg_color = "#839496",
				fg_color = "#fdf6e3",

				-- The same options that were listed under the `active_tab` section above
				-- can also be used for `inactive_tab`.
			},

			-- You can configure some alternate styling when the mouse pointer
			-- moves over inactive tabs
			inactive_tab_hover = {
				bg_color = "#839496",
				fg_color = "#fdf6e3",

				-- The same options that were listed under the `active_tab` section above
				-- can also be used for `inactive_tab_hover`.
			},

			-- The new tab button that let you create new tabs
			new_tab = {
				bg_color = "#d33682",
				fg_color = "#fdf6e3",

				-- The same options that were listed under the `active_tab` section above
				-- can also be used for `new_tab`.
			},

			-- You can configure some alternate styling when the mouse pointer
			-- moves over the new tab button
			new_tab_hover = {
				bg_color = "#d33682",
				fg_color = "#fdf6e3",

				-- The same options that were listed under the `active_tab` section above
				-- can also be used for `new_tab_hover`.
			},
		},
		-- foreground = "#2a1a4a",
		-- background = "#2a1a4a",
		ansi = {
			"#0a0520",
			"#ff796d",
			"#99b481",
			"#efdfac",
			"#66d9ef",
			"#e78fcd",
			"#ba8cff",
			"#000000",
		},
		-- brights = {
		--   "#100b23",
		--   "#f99f92",
		--   "#b4be8f",
		--   "#f2e9bf",
		--   "#79daed",
		--   "#ba91d4",
		--   "#a0a0d6",
		--   "#b9aed3"
		-- }
	},
	-- leader = { key=" ", mods="CTRL", timeout_milliseconds=1000 },
	keys = {
		{ key = "mapped:r", mods = "SUPER", action = wezterm.action({ SpawnTab = "CurrentPaneDomain" }) },
		{ key = "mapped:n", mods = "SUPER", action = wezterm.action({ SpawnTab = "DefaultDomain" }) },
		{ key = "mapped:t", mods = "SUPER", action = "ActivateLastTab" },
		{ key = "_", mods = "SUPER", action = "ActivateCopyMode" },
		{
			key = "'",
			mods = "SUPER",
			action = wezterm.action({
				QuickSelectArgs = {
					patterns = {
						"(?:')(.*)(?:')",
					},
				},
			}),
		},
		{
			key = '"',
			mods = "SUPER",
			action = wezterm.action({
				QuickSelectArgs = {
					patterns = {
						'(?:")(.*)(?:")',
					},
				},
			}),
		},
		{
			key = "u",
			mods = "SUPER",
			action = wezterm.action({
				QuickSelectArgs = {
					patterns = {
						"https?://\\S+",
					},
					action = wezterm.action_callback(function(window, pane)
						local url = window:get_selection_text_for_pane(pane)
						wezterm.log_info("opening: " .. url)
						wezterm.open_with(url)
					end),
					alphabet = "dvorak",
				},
			}),
		},
	},
}
```

**Comment by wez** [comment]
I'm a bit confused because the title mentions `t` but the main issue text mentions `r`!

Can you break this down so that I'm able to reproduce what you're seeing?
What physical keys are you pressing, and what is the behavior that you're observing?

Please see https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html for how to enable key event logging and include the logs from when you press those keys

**Comment by wez** [comment]
I think what's happening is that default physical mapping is taking precedence.

We should probably do something to make this less surprising, but in the meantime,
I would suggest doing something like this to remove the default physical assignment
before defining your mapped assignment.

```lua
local wezterm = require 'wezterm'

return {
  debug_key_events = true,
  keys = {
    { key = "k", mods = "SUPER", action = "DisableDefaultAssignment" },
    { key = "mapped:t", mods = "SUPER", action = "ActivateLastTab" },
  }
}
```

**Comment by martinsrso** [comment]
I modified my keyboard to qwerty and nothing works either.

Tried with colemak, qwerty and dvorak. All macos patterns. In other emulators, they work normally.

I left the config with only these changes and it doesn't work.

and as you can see in the log `cmd+k` works as `cmd+v`.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/11994788/160508317-489aa0bc-ac53-43b3-9bf4-ad8251cbdec3.png">

**Comment by wez** [comment]
Are those screenshots from the debug overlay?  That's not the best way to review key event debugging.
I'd recommend running wezterm from inside wezterm, so that its stderr logs to the first window.

I'd like to understand what is happening so that we can find a way to resolve this.

Have you considered setting `disable_default_key_bindings = true` to see if that makes things behave better?

**Comment by martinsrso** [comment]
I've already tested the `disable_default_key_bindings` and it only disables the shortcuts that work in QWERTY mode. For example the shortcut of quit.
For now, I'll put all the manual mappings.

**Comment by wez** [comment]
I've just pushed support for a new option that will give you more control over this:
https://wezfurlong.org/wezterm/config/lua/config/key_map_preference.html
That will show up in a nightly build within an hour.

**Comment by martinsrso** [comment]
Thanks for the solution. It's work.
