### ISSUE TITLE
Font width too small with Broot's VSCode Font

### ISSUE THREAD

**Issue by cbirchinger** [wez/wezterm#1787]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220328-070617-ec022275

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm has only half the width for the Broot vscode icons font (https://dystroy.org/broot/icons/)
This causes an overlap with the following characters. **Broot is not required to reproduce the issue**.

Here is a screenshot comparing the rendering with other known terminals. The "s" character from
"string" is missing in WezTerm:

![vscode-spacing](https://user-images.githubusercontent.com/4973300/160504938-349c6d40-ce3b-4763-9fe5-c9030c220c52.png)

### To Reproduce

The font is available here on GitHub and can be used in the "font_with_fallback" list. The original
font name is "Untitled1": https://github.com/Canop/broot/blob/master/resources/icons/vscode/vscode.ttf
(I renamed the font for personal use, so I don't have to use "Untitled1")

This simple command will demonstrate the behaviour, so broot is not required for testing:
`~$ echo "\U00100002 string"`

WezTerm will output the following error log when the character is echoed:
`ERROR wezterm_font::ftwrap           > Couldn't find any glyphs for metrics, so guessing width == height`

### Configuration

font = wezterm.font_with_fallback({
	"Terminus",
	"Symbols Nerd Font",
	"Untitled1",
}),

### Expected Behavior

The icon shouldn't cover the "s" character of "string"

### Logs

ERROR wezterm_font::ftwrap           > Couldn't find any glyphs for metrics, so guessing width == height

### Anything else?

I don't know how all other terminals detect the correct width. I personally wouldn't mind if I had to set some manual values either.

**Comment by wez** [comment]
That font has broken metrics; the glyphs have horizontal advances of 0 which means that harfbuzz won't move the x position after drawing the glyph:

```
; hb-shape /tmp/vscode.ttf "$(echo \\U00100002 string)"
[glyph2=0+0|.notdef=1+364|.notdef=2+364|.notdef=3+364|.notdef=4+364|.notdef=5+364|.notdef=6+364|.notdef=7+364]
```

<img width="676" alt="image" src="https://user-images.githubusercontent.com/117777/160510472-eb900278-3546-49f7-a506-815193d7032a.png">

```
; wezterm --config-file /tmp/1787.lua ls-fonts --text "$(echo \\U00100002 string)"
LeftToRight
 0 􀀂    \u{100002}   x_adv=0  cells=0  glyph=2    wezterm.font("Untitled1", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/wez/Downloads/issue-1787/vscode.ttf, FontDirs
 4      \u{20}       x_adv=7  cells=1  glyph=686  wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
 5 s    \u{73}       x_adv=7  cells=1  glyph=312  wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
 6 t    \u{74}       x_adv=7  cells=1  glyph=320  wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
 7 r    \u{72}       x_adv=7  cells=1  glyph=308  wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
 8 i    \u{69}       x_adv=7  cells=1  glyph=246  wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
 9 n    \u{6e}       x_adv=7  cells=1  glyph=272  wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
10 g    \u{67}       x_adv=7  cells=1  glyph=236  wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
```

**Comment by wez** [comment]
I've put in a slightly hinky workaround for this sort of situation that helps:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/117777/160514611-68926d03-690f-4745-942c-496802501be6.png">
