### ISSUE TITLE
Default key bindings broken on non-QWERTY layouts

### ISSUE THREAD

**Issue by keichan34** [wez/wezterm#1788]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220328-224732-f478672f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Since 20220319-142410-0fcdea07, [key bindings default to physical positions](https://wezfurlong.org/wezterm/config/keys.html#physical-vs-mapped-key-assignments), which is a backwards incompatible change when the user has a non-QWERTY layout activated.

### To Reproduce

1. Install 20220319-142410-0fcdea07 or later
2. Try to use a key binding (such as Ctrl-Shift-C) using the Dvorak layout
3. The key binding is not recognized, so Ctrl-C is sent to the running process

### Configuration

no config

### Expected Behavior

I expected Ctrl-Shift-C to copy text.

### Anything else?

Is there a configuration setting that will set the default to `mapped:`? Or should I reproduce the whole default key mappings in wezterm.lua and prefix everything with mapped?

I think this confusion may be the root cause of #1784 and #1744 ?

**Comment by jubalfh** [comment]
note the sixth para in the link you referenced above:

> When upgrading from earlier releases, if you had {key="N", mods="CMD", ..} in your config, you will need to change it either {key="N", mods="CMD|SHIFT", ..} or {key="mapped:N", mods="CMD", ..} in order to continue to respect the SHIFT modifier.

**Comment by MuhammedZakir** [comment]
OP is talking about _default key bindings_. Users shouldn't need to touch the config to make those work.

@wez: I think we need to make `mapped:` the default rather than physical. Is there a reason why "physical" was preferred as the default?

**Comment by wez** [comment]
Physical was chosen because mapped isn't meaningful for non-roman keyboard layouts, and those users are accustomed to using the physical locations for common shortcuts like ctrl-c/ctrl-v.

**Comment by keichan34** [comment]
Sorry, I don't really understand this:

> those users are accustomed to using the physical locations for common shortcuts like ctrl-c/ctrl-v

All of the OSes I've used (macOS, since OS 8+, Windows, and now Linux), when you select the Dvorak layout, all application keyboard shortcuts are in the mapped key layout. There's even a special Dvorak-with-QWERTY-key-layout-when-pressing-command layout in macOS to preserve the QWERTY shortcuts when pressing the command key.

I personally don't mind having the distinction between physical/mapped or choosing one over the other as a default, but it would be really nice to have an option to change the default. I can't use newer versions of wezterm in its current state without replicating the default keymappings and prefixing them all with `mapped:`

**Comment by rumpelsepp** [comment]
see also: https://github.com/wez/wezterm/discussions/1799

**Comment by rumpelsepp** [comment]
> Physical was chosen because mapped isn't meaningful for non-roman keyboard layouts

This perhaps makes sense for e.g. Thai or Russian keyboards. There are also alternative layouts such as neo2 and dvorak. As a neo user I am used to the “mapped” variant of ctrl+c/ctrl+v since this is my system default. It doesn't make any sense that the terminal behaves completely different from rest of my system.

**Comment by wez** [comment]
I've just pushed support for a new option that will give you more control over this:
https://wezfurlong.org/wezterm/config/lua/config/key_map_preference.html
That will show up in a nightly build within an hour.

**Comment by rumpelsepp** [comment]
:heart: Thank you!

**Comment by keichan34** [comment]
Beautiful! Thanks so much. I tried to start a PR to add the default key mapping config, but I'm not so familiar with Rust and got lost halfway though. I'll look through the patch to see how you implemented it.

Just tried out the nightly, my issue is resolved. Thanks again -- will be using nightly until next release. ❤️
