### ISSUE TITLE
Add an option set the initial window position

### ISSUE THREAD

**Issue by cbirchinger** [wez/wezterm#1794]
Please add an option to set the initial window position, similar to what "initial_rows" and "initial_cols" does for width and height.

"initial_xpos" and "initial_ypos" would be good names to match the existing 2 options.

The option will probably be used less in the config file, but rather with "--config" CLI parameters to place the windows.

**Comment by jvzr** [comment]
I was looking for that kind of option today, glad to see that I'm not the only one interested.

My use case would be in the config file to set windows to open at the center of the screen, to mimic Gnome's Center New Windows option

**Comment by wez** [comment]
Question about the semantics for this: if you specify this on the command line, then used [SpawnWindow](https://wezfurlong.org/wezterm/config/lua/keyassignment/SpawnWindow.html) to create a new window, would you expect that (and all subsequently created windows) to use the position you set from the command line?

**Comment by cbirchinger** [comment]
Wouldn't it be better to limit the scope here and handle "initial_xpos" and "initial_ypos" exactly like "initial_rows" and "initial_cols" as a first step and then later decide on a basic design choice if "--config" options should be just for a single session or passed down to all child spawns?

**Comment by wez** [comment]
> later decide on a basic design choice if "--config" options should be just for a single session or passed down to all child spawns?

There's no question about this: config overrides specified via the CLI are global, and will be passed to everything in that same process.

We need a command line option that will override the positioning for a single window that will take precedence over anything we might potentially also want to put into the main config.

Furthermore, that option needs to think ahead so that it doesn't feel uncomfortable when it needs to be extended later.
There are a couple of things to support or that need to be considered when figuring out a way to express this sort of geometry:

* Simple pixel x/y coordinates
* centering in either/or/both of x/y 
* Specify if coordinates are relative to the "active" vs. "default"/"main" screen for multi-monitor systems, a specific screen, or just the overall screen coordinate system.
* Express position (and perhaps window dimensions!) as % of selected screen size.

**Comment by wez** [comment]
Current nightly builds support:

```
; wezterm start --help
...
        --position <position>
            Override the position for the initial window launched by this process.

            --position 10,20          to set x=10, y=20 in screen coordinates
            --position screen:10,20   to set x=10, y=20 in screen coordinates
            --position main:10,20     to set x=10, y=20 relative to the main monitor
            --position active:10,20   to set x=10, y=20 relative to the active monitor
            --position HDMI-1:10,20   to set x=10, y=20 relative to the monitor named HDMI-1
...
```

This option is supported on:

* macOS
* Windows
* X11.  XRANDR is required to set monitor-relative coordinates.  Doesn't yet support `active:`.

Note that Wayland is not supported at this time.  (Wayland is weird, and SCTK doesn't expose the ability to set a window position on its default Window type).

In addition, you can use:

`--position 'main:30%,30%'`

to set position based on percentage of screen dimensions.

**Comment by cbirchinger** [comment]
"wezterm start --position 20,20" has no effect here and the window opens on the default position.

I'm using old school X11 with Xfce4, so no Wayland or other things that would prevent placement.

xfce4-terminal --geometry +20+20
xterm -geometry +20+20
mlterm --geometry=+20+20

All the above work and place a window at x=20 y=20 while "wezterm start --position 20,20" doesn't.

**Comment by wez** [comment]
Urgh.  603f6d69cefb34acbe95db7ba55e211c5da54711 will perhaps resolve this?

**Comment by cbirchinger** [comment]
Yeah, this makes it work. It wouldn't be good old X11, if it worked without any hacks.

**Comment by cbirchinger** [comment]
All this has the side effect of mapping a window without any "--position" option to 0,0 instead of the default position.
Maybe calling "set_window_position" should be avoided if "--position" hasn't been used as an option.

**Comment by wez** [comment]
ack. 0284bcdd3

**Comment by MuhammedZakir** [comment]
If WezTerm is already running, passing `--position` doesn't work; WezTerm is always started in default position. As a workaround, I had to pass `--always-new-proces`.

**Comment by cocoonkid** [comment]
@wez My apology for hijacking this thread but I can't for the life of me figure out how to add this to the .wezterm.lua

I tried position , xpos but no dice.
How would I set it to 0,0 ?

Thanks

**Comment by wez** [comment]
@cocoonkid use https://wezfurlong.org/wezterm/config/lua/gui-events/gui-startup.html and call https://wezfurlong.org/wezterm/config/lua/window/set_position.html

**Comment by cocoonkid** [comment]
@wez gotcha & thank you sooo much! worked like a charm now!
Now if I could make it slide down i'd have a real quake console :-) 
But this is veeerry near while I trigger it with option + space (setup with bettertouchtool)

❤️

**Comment by eugenesvk** [comment]
I've tried the gui-startup and set_position and it works, but with an annoying "jump" not present in, e.g., iTerm — the window is created at the default coordinates and then gets relocated to the ones I've added in my setup.
Is there a way to force the WezTerm app to read coordinates earlier, before the window is created?

**Comment by wez** [comment]
@eugenesvk please file an enhancement issue for that; I can't track comments on closed issues, so this will otherwise be forgotten 5 minutes after reading it!

**Comment by eugenesvk** [comment]
Sure thing, I just thought that maybe I was missing something, so thought would ask here before filing an issue 

> this will otherwise be forgotten 5 minutes after reading it!

You have a good memory if a random comment stays that long :)!
