### ISSUE TITLE
How to disable update notifcations on distros?

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#1795]
**Is your feature request related to a problem? Please describe.**
I want to disable update notifications in nixpkgs and wondered how other distros do this and if you thought about that yet.

**Describe the solution you'd like**
A better one than removing the if here https://github.com/wez/wezterm/blob/cf518c9186adfb767d1f63bea12bbf7defff0762/wezterm-gui/src/update.rs#L260-L262=

**Describe alternatives you've considered**
Leave them enabled.

**Additional context**
I am the wezterm maintainer on NixOS/nixpkgs.

**Comment by wez** [comment]
I suppose we could add a `"distro-defaults"` feature flag that changes the default to false:

https://github.com/wez/wezterm/blob/cf518c9186adfb767d1f63bea12bbf7defff0762/config/src/config.rs#L493-L494

To something like:

```rust
    #[serde(default = "default_check_for_updates")]
    pub check_for_updates: bool,
```

```rust
fn default_check_for_updates() -> bool {
   cfg!(not(feature = "distro-defaults"))
}
```

**Comment by SuperSandro2000** [comment]
Yeah, that sounds like a good idea.

**Comment by wez** [comment]
I've added that flag and also https://github.com/wez/wezterm/blob/main/README-DISTRO-MAINTAINER.md with notes for package maintainers

**Comment by SuperSandro2000** [comment]
Great! Now I only need that in a release. :)
