### ISSUE TITLE
-e option for running program in terminal

### ISSUE THREAD

**Issue by ExpandingMan** [wez/wezterm#1797]
**Is your feature request related to a problem? Please describe.**
Most terminals have a `-e` command line argument to start a program when the terminal starts.  For example, by default the `rofi` `ssh` menu starts ssh sessions simply by e.g. `alacritty -e 'ssh hostname'`.  Other uses include opening a terminal specifically for a programming language REPL.

**Describe the solution you'd like**
Replicate this functionality in wezterm.

**Describe alternatives you've considered**
It doesn't have to be `-e`, but it seems like by far the best option since it doesn't appear to be already taken and most terminals use `-e`.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/launch.html#launching-a-different-program-as-a-one-off-via-the-cli

`wezterm start --help`

**Comment by ExpandingMan** [comment]
Sorry, I had looked at `wezterm --help` and for some reason it just didn't click for me.
