### ISSUE TITLE
can't run in macOS 10.13

### ISSUE THREAD

**Issue by hronro** [wez/wezterm#1798]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220330-080645-53c47143

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Can't run the app.

When I try run `/Applications/WezTerm.app/Contents/MacOS/wezterm` in command line, I got this error:

```
dyld: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications
  Referenced from: /Applications/WezTerm.app/Contents/MacOS/wezterm-gui
  Reason: image not found
fish: Job 1, '/Applications/WezTerm.app/Con...' terminated by signal SIGABRT (Abort)
```

### Configuration

no config

**Comment by wez** [comment]
If you double click the icon via Finder, or run `open /Applications/WezTerm.app` does it open successfully?

**Comment by hronro** [comment]
@wez Tried both, neither of them works.

This is what I got when I run `open /Applications/WezTerm.app`

```
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/WezTerm.app.
```

**Comment by hronro** [comment]
I think the reason is, wezterm is linked to a system lib that does not exist on macOS 10.13.

As you can see, there's no `UserNotifications` in the `/System/Library/Frameworks/UserNotifications.framework/Versions/A` in macOS 10.13:

![CleanShot 2022-03-31 at 12 24 42](https://user-images.githubusercontent.com/15059605/160976577-be4eaccd-95a8-4109-b870-103729eea5dd.png)

**Comment by wez** [comment]
It sounds as though 10.13 is too old to support. According to https://en.wikipedia.org/wiki/MacOS_High_Sierra it's not been supported by Apple since December 2020.
I'm not going to put any meaningful effort into making this work.

You might have more luck with an older release of wezterm from https://github.com/wez/wezterm/releases
