### ISSUE TITLE
Not being able to insert special characters

### ISSUE THREAD

**Issue by PedroHLC** [wez/wezterm#18]
## Is it a build problem?
No, build happens happens happily!
I use `--release`

## Did something not work the way you expected?
Yes, I cannot type any of this characters:
```
~ ç Ç á è Ï õ Ũ ñ
```
As well as anything that uses "Alt Gr" mod, as `/?`(I'm on a notebook) `¹²³£¢¬{[}§ªº€`, also, nothing on numpad works `/*--+789456123`.
Tabs hotkey (Super-T, Super-[, Super-]) don't works either....

### What did you try?
Do what I always do, from bash, fish, tmux, vim...
Can't even `cd ~/Projects`

Trace:
https://drive.google.com/open?id=1rQVuDGW1Gjf-KNWJkQFzXAQ7yAQ8YIUJ

### What did you expect to happen?
The same behavious as anywhere

### What actually happened?
Any other thing I typed worked, It's way faster than konsole, ligatures, colors and text effects (bold) are fine too.

### Others note:
I use i3, on archlinux, with latest NVIDIA drivers and libglvnd. Only setting is `font = { fontconfig_pattern = "Fira Code" }`

There is also this error, visible with RUST_BACKTRACE:
https://gist.github.com/PedroHLC/0e8b46a77f6925136842110bab4cdded

**Comment by wez** [comment]
Can you open a separate issue for the panic you saw?  Please build that one in debug mode (just use `cargo run` without the `--release` flag).

For this issue, which is inserting special characters, those all need to be handled "manually" in code.
Here's where the key handling code lives:

https://github.com/wez/wezterm/blob/master/term/src/terminalstate.rs#L722
Do you feel like taking a run at adding the code for the `Alt Gr` character expansion?

Regarding `Super-T` and other keys: is your window manager intercepting those before they get to wezterm?  That's the most likely cause.

**Comment by PedroHLC** [comment]
> Regarding `Super-T` and other keys: is your window manager intercepting those before they get to wezterm? That's the most likely cause

Yeah makes sense, I use Super as i3 $mod

> Can you open a separate issue for the panic you saw?

Yeah I can!

> Do you feel like taking a run at adding the code for the `Alt Gr` character expansion?

I'll try

**Comment by Lompik** [comment]
Input internationalization is probably best handled with an external lib like ```xkbcommon```. ```X``` has many options w.r.t. to input methods  ... layouts, options, maps, compose keys. For example I use ```<scroll-lock>^ e``` to type ```ê```. It works everywhere but not in wezterm.
https://github.com/rtbo/xkbcommon-rs seems to be updated.

**Comment by wez** [comment]
This is a messy area.  The `glutin` gui system (you can enable it on linux by setting `gui_system = "Glutin"` in your `~/.wezterm.toml`) has a way to pass on exactly the composed characters you want, but it is not consistently implemented.  In the commit above I've turned this off because it was breaking things on macos, but the same code running on my ubuntu system didn't generate any unicode text.

**Comment by Lompik** [comment]
Your're right. With 6a617aefbb462bcb9b379a75f7dd8122a4aa1642 key composition works and I get the unicode char expected using the ```glutin``` gui.  Behind the scene on x11,```winit``` uses ```xlib```'s XIM & Input Context to decode the keys ... hmm.
 Not sure what's wrong with macs but handling ```ReceivedChar``` event is the way to go.
I'm actually inclined to use the ```xcb```/````x11`` backend as it feels butter smooth during window creation, best of many guiapps I've seen. Is this backend deprecated ? Would it be possible to let glutin handle input while still using x11 custom window ?

**Comment by wez** [comment]
re: `x11` backend, I was considering removing it, but only if glutin worked out to be superior.  My experience with glutin so far has not been great, so we're keeping both gui systems for the foreseeable future, as glutin means that we at least have a functional UI for windows and macOS without needing to own a ton of code.

What I think the next steps are:

1. For me: Understand how you differentiate between wanting the terminal to receive `alt-1` verses sending a composed key.  Do you have a "plain" alt key vs. an "alt gr" key?  Do you have a compose leader key?  Right now in glutin I don't see how we can distinguish between the two things.
2. Grow some code for the x11 backend to handle this.  IIRC, when I last checked, the best available interface for this was the xlib interface and that is a slight bummer because our x11 backend uses xcb
3. Grow some code that allows specifying key bindings in a config file, which should help as an ultimate override and should help to solve eg: the `Super` key conflict with the WM by simply using a different key binding for that function in wezterm.

**Comment by Lompik** [comment]
yeah everyone should be using ```xcb```.. so they said... except keyboard & opengl support is very subpar with ```XLib```.. How convenient for us...

The point I'm trying to make is to let some external library handle this. It is messy. There are tons of possibilities. The end key can be a combination of layout, variant, keymap, Options (XkbOptions) & locale.

  1. Sorry for the confusion. The ```Alt Gr``` https://en.wikipedia.org/wiki/AltGr_key which @PedroHLC is using is a modifier key (mod5) bound to ```XK_ISO_Level3_Shift```. For most of the unicode you can type there are no keysyms associated. Instead Apps calls ```Xutf8LookupString``` or ```XLookupString``` to get associated char.  I believe it's a similar (but lighter) mechanism to compose key below. 
Another way to input unicode is to make use of the compose key (or multi_key) which I bind on ```scrolllock``` by putting ```keycode  78 = Multi_key NoSymbol Multi_key```` in ```~/.xmodmap``` then I get a bunch of ```dead keys``` like ```'"``` which don't print when combined with ```MultiKey``` unless combined with the right next key. This is an extra mechanism ...

  2. GTK,QT, GLFW, i3,... uses xkbcommon & xkbcommon-x11 . see ```required by``` https://www.archlinux.org/packages/extra/x86_64/libxkbcommon-x11/ . But it add a (hard or optional?) dependency on a c lib(and rust binding by the same guy that ships xcb).   ```winit```'s XIM/Xlib way should be doable too. Funny enough, ```XLib``` predates ```Unicode```.

**Comment by Lompik** [comment]
I have a WIP branch with xkbcommon integration. https://github.com/Lompik/wezterm/tree/ime_xcb . 
It just does what one expect: composition, numpad keys, live keyboard change.

What I found out is that xkbcommon requires some extra xcb event (with a runtime ```response_type```) which AFAICT do not have a window_id so dispatching in ```x11.rs``` will probably require a hashmap of kbd_ev / window_id.

**Comment by PedroHLC** [comment]
So, from now what I miss the most is `~`, `/` from AltGr, {`/`,`*`} from Numpad
`~` from (ABNT)[https://en.wikipedia.org/wiki/Portuguese_keyboard_layout] is  `keycode 48 (keysym 0xfe53, dead_tilde)`
`/` from AltGr is `keycode 108 (keysym 0xfe03, ISO_Level3_Shift)` with `keycode 24 (keysym 0x2f, slash)`
`/` from NumPad is `keycode 106 (keysym 0xffaf, KP_Divide)`
`*` from NumPad is `keycode 63 (keysym 0xffaa, KP_Multiply)`

Is it still a good ideia to add it to terminalstate?

**Comment by wez** [comment]
@PedroHLC did you try those on @Lompik's fork?   I'll take a look at that more closely later this evening.

**Comment by PedroHLC** [comment]
@wez just tested @Lompik fork, and it works awesomely, all keys are working, performance seems to be the same, on arch just added `libxkbcommon-x11` as dep.
There are some warnings at `xwindows/keyboard.rs`, they don't affect anything at runtime...

**Comment by wez** [comment]
@Lompik sounds like it's working :-)  I'm looking forward to you turning it into a PR!

**Comment by wez** [comment]
I've merged and pushed @Lompik's PR, so let's call this issue done.  If you find other aspects of this that need to be fixed, please open separate issues!
