### ISSUE TITLE
Font baseline adjustment for specific font

### ISSUE THREAD

**Issue by Typas** [wez/wezterm#1803]
**Is your feature request related to a problem? Please describe.**

In #1761 the scale attribute is available in nightly build,  but it doesn't display well enough when combining CJK characters with Latin characters.

**Describe the solution you'd like**

A new attribute for baseline adjustment. For example,
```lua
{
  family = "Noto Sans CJK TC",
  scale = 1.2,
  baseline = -0.1, -- new attribute, move the baseline downward by 10%
}
```

**Describe alternatives you've considered**

A new boolean attribute `centered`, which would place the character in the center (at least horizontally to avoid left-aligned character). For example,

```lua
{
  family = "Noto Sans CJK TC",
  centered = true,
}
```

**Additional context**

With Latin font `Fira Code` and CJK font `Noto Sans CJK TC`, font size 13.0,
Chinese character is `中` `工` `永` `申`, punctuation `？` ` ！`.

- scale=1.0, height=1.0, default setting
![scale-1 0-height-1 0](https://user-images.githubusercontent.com/44962044/161316178-0d2d1674-f87f-408d-ad39-1d68a69affc9.jpeg)

- scale=1.2, height=1.0, matching width
![scale-1 2-height-1 0](https://user-images.githubusercontent.com/44962044/161316220-dd53377b-6e87-4a69-89de-1c511bafd526.jpeg)

- scale=1.2, height=1.2, considered "fit in block well"
![scale-1 2-height-1 2](https://user-images.githubusercontent.com/44962044/161316205-25380b8a-5635-409a-a581-0d43eeae8738.jpeg)

- scale=1.2, height=1.5
![scale-1 2-height-1 5](https://user-images.githubusercontent.com/44962044/161316232-e9ebe77c-8f8b-401a-a7ec-aae005328bb1.jpeg)

**Comment by wez** [comment]
Can you help me improve my understanding of what looks good?

This little shell script turns on a red underline at the underline height, and includes some of the characters that you used above:

```
printf "\x1b[58:2::255:0:0m\x1b[4:1mI工永申中Fg_\x1b[0m\n"
```

There appear to be a lot of different Noto Sans CJK fonts.  I found a set over here https://github.com/googlefonts/noto-cjk/releases/tag/Sans2.004 which includes monospace fonts; those seem like they would be most appropriate for a terminal.

```lua
local wezterm = require 'wezterm'

return {
  font_size = 13.0,
  font = wezterm.font_with_fallback({
    "Fira Code",
    {family="Noto Sans Mono CJK TC",
     scale=1.0},
  })
}
```

<img width="768" alt="image" src="https://user-images.githubusercontent.com/117777/161360614-12854220-f5ab-4f85-b402-be8195135521.png">

When I try increasing the scale for the CJK font, the text still seems well-aligned to my unfamiliar eyes.

Would you mind capturing the configuration and screenshots for the cases you mentioned above, but also to annotate the screenshots to show how you consider alignment and what is good or bad about them?

That would help me understand how to manipulate the rendering: what I'd like to do is expand https://wezfurlong.org/wezterm/config/lua/config/use_cap_height_to_scale_fallback_fonts.html to make this kind of adjustment automatic.

**Comment by Typas** [comment]
The problem of mixing fonts here is since the width of Latin character is not exact half-width of CJK character. It takes `scale=1.2` for CJK font to make CJK character width is exactly twice as Latin character. However, when you scaled CJK font, it looks unbalanced vertically, that's why I want baseline adjustment after individual font scale.

The main idea I think of looking good is
1. scale=1.0, the CJK character has been placed centered horizontally while baseline is the same as default.
2. scale=1.2, the CJK character has baseline shifted -0.1 (half of the scale changed to maintain vertically centered), the horizontal centered is unaffected since it's already 2x wide as Latin character.

Some screenshots to explain the idea:

scale=1.0, height=1.0, default setting, the left margin and right margin of `申` surrounded with `I` are not equal.
![scale-100-height-100](https://user-images.githubusercontent.com/44962044/161365563-d3b27b11-4cac-449d-bf75-51d31a7b05d5.png)

scale=1.2, height=1.2, the margins are equal now, but you can notice the the upper part of `永` is out of block while the baseline is remained the same, and it makes similar graph `I` and `工` have different center in vertical way.
![scale-120-height-120](https://user-images.githubusercontent.com/44962044/161365571-0628d2e8-2d9f-4494-ab94-b55e15df54bb.png)

Configuration can be found in my repository: https://github.com/Typas/wezterm-config/blob/master/conf-fonts.lua

minimal functional equivalent for testing is code below:
```lua
local wezterm = require 'wezterm'

return {
  line_height = 1.2, -- "height" of tests, can also be 1.0 or 1.5
  font_size = 13.0,
  font = wezterm.font_with_fallback({
    "Fira Code",
    {family="Noto Sans CJK TC",
     scale=1.2}, -- "scale" of tests, can also be 1.0
  })
}
```

**Comment by Typas** [comment]
Some more supplementary images,

with scale = 1.0,  line_height = 1.0, you can see the mid line of `中` is not on the line of the cursor block's right border, while the top lines of `I`  and `工` are coincident.
![scale-100](https://user-images.githubusercontent.com/44962044/161411833-b7ced9ab-ca7e-4702-b660-86ec395b8f89.png)

with scale = 1.2, line_height = 1.2, you can see the mid line of `中` now coincide with the line of the cursor block's  right border, but the top lines of `I` and `工` become two parallel lines.
![scale-120](https://user-images.githubusercontent.com/44962044/161411830-35536145-4625-4ebe-97ac-6aeaaf1fb6b2.png)

These two situation are best practice for mixing typical CJK and Latin font. Typical CJK font needs to set scale to 1.2 to match the width of typical Latin font. For people that write CJK less and Latin/Greek/Cyrillic more, they tend to use default setting, but not horizontally centered CJK character is a pain. For people write more CJK characters, they would tend to use scale=1.2 and line_height=1.2, this setting makes a more smooth experience for native CJK users.

**Comment by wez** [comment]
I've pushed a commit that should result in scaled fallback font glyphs having the y-position adjusted down by the difference between their original descender and the scaled descender.

That should show up in the nightly builds within an hour (some platforms build within ~20 minutes).
Please give it a try and let me know how it works out.

If you're in a position to build from source and want to play around with the precise adjustment, this is the relevant section of the code:

https://github.com/wez/wezterm/blob/14323a08d121cd824ace08e36b0749d628393422/wezterm-font/src/shaper/harfbuzz.rs#L596-L602

**Comment by Typas** [comment]
It becomes slightly better now, I will try to tune more to see what would be the best.
![Screen Shot 2022-04-04 at 1 27 10 AM](https://user-images.githubusercontent.com/44962044/161440296-ade033c3-b6c2-4a29-9acb-6302be1c87a1.png)

**Comment by khaledhosny** [comment]
HarfBuzz APIs for getting baseline information might be useful here (https://harfbuzz.github.io/harfbuzz-hb-ot-layout.html#hb-ot-layout-get-horizontal-baseline-tag-for-script and the following functions).

**Comment by Typas** [comment]
After some tests of tuning, I think this automated adjustment suits the best. The only problem is when you scale too much (like scale=2.0), the size of the scaled characters would not be the same.
