### ISSUE TITLE
How can I switch between panes?

### ISSUE THREAD

**Issue by gimbles** [wez/wezterm#1809]
![image](https://user-images.githubusercontent.com/93856041/161387857-67d28cae-e8ba-4105-81c8-a157b1188669.png)
For example, I have three panes open like this. How can I switch between them using my keyboard instead of clicking them through the mouse?

**Comment by wez** [comment]
CTRL-SHIFT+ArrowKey will activate the pane in the direction of the arrow.

https://wezfurlong.org/wezterm/config/keys.html?highlight=activatepanedire#default-shortcut--key-binding-assignments

**Comment by gimbles** [comment]
Cheers :+1:
