### ISSUE TITLE
Powerline glyphs present in the primary font get ignored and a built-in fallback gets used.

### ISSUE THREAD

**Issue by cbirchinger** [wez/wezterm#1817]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220403-183725-e76525b6

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Even though the Powerline glyphs OxE0B0 and OxE0B1 are present in the OTB Terminus font  (http://terminus-font.sourceforge.net/), an anti-aliased fallback version gets used. Anti-aliasing is correctly fully disabled in the Terminus font but the Powerline symbols still have them.

original version:
![wezterm-terminus](https://user-images.githubusercontent.com/4973300/161619137-ef74f43a-8033-40ce-afe9-b8cf2942c9d0.png)

4x version:
![wezterm-terminus-zoom](https://user-images.githubusercontent.com/4973300/161619222-751439e2-3203-4800-999d-e043237789d6.png)

### To Reproduce

Run WezTerm with the minimal config below and a font like Terminus (http://terminus-font.sourceforge.net/) that contains Powerline symbols.

I've used this to display a string that shows the symbols not being used from the main font:
~$ echo "\UE0B1 \UE0B0 The quick brown fox jumps over the lazy dog"

### Configuration

```
local wezterm = require 'wezterm';

return {
        font_size = 9.0,
        font = wezterm.font("Terminus"),
}       

```

### Expected Behavior

Powerline glyphs like E0A0..E0A2 and E0B0..E0B3 should be rendered using the defined font and not a fallback version.

### Anything else?

Did i fail to read the manual correctly? I've really tried to check the documentation on this, but couldn't find something.

I've also tried to get at lest rid of the AA with 'freetype_load_target = "Mono"' and 'freetype_render_target = "Mono"' but the render result remains the same. But AA is fine anyway in the fallback TTF fonts. I just don't use it in the pixel perfect bitmap  font Terminus. WezTerm already renders Terminus perfectly fine. It just doesn't use all glyphs already present in the font.

```
~ % wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /usr/share/fonts/terminus/ter-u12n.otb, FontConfig
  -- Pixel sizes: [12]
  "Terminus",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- /usr/share/fonts/noto-emoji/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})

```

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/config/custom_block_glyphs.html

**Comment by wez** [comment]
FWIW `wezterm ls-fonts --text` will show the custom glyph info:
 
```
; wezterm ls-fonts --text "$(echo \\UE0B1 \\UE0B0 hello)"
LeftToRight
 0   hello \u{e0b1}     drawn by wezterm: Poly([Poly { path: [MoveTo(Zero, Zero), LineTo(One, Frac(1, 2)), LineTo(Zero, One)], intensity: Full, style: Outline }])
 3      \u{20}       x_adv=8  cells=1  glyph=2    wezterm.font("Operator Mono SSm Lig", {weight="DemiLight", stretch="Normal", style="Normal"})
                                      /Users/wez/.fonts/OperatorMonoSSmLig-Medium.otf, FontDirs
 4   hello \u{e0b0}     drawn by wezterm: Poly([Poly { path: [MoveTo(Zero, Zero), LineTo(Zero, One), LineTo(One, Frac(1, 2)), Close], intensity: Full, style: Fill }])
 7      \u{20}       x_adv=8  cells=1  glyph=2    wezterm.font("Operator Mono SSm Lig", {weight="DemiLight", stretch="Normal", style="Normal"})
                                      /Users/wez/.fonts/OperatorMonoSSmLig-Medium.otf, FontDirs
 8 h    \u{68}       x_adv=8  cells=1  glyph=36   wezterm.font("Operator Mono SSm Lig", {weight="DemiLight", stretch="Normal", style="Normal"})
                                      /Users/wez/.fonts/OperatorMonoSSmLig-Medium.otf, FontDirs
 9 e    \u{65}       x_adv=8  cells=1  glyph=33   wezterm.font("Operator Mono SSm Lig", {weight="DemiLight", stretch="Normal", style="Normal"})
                                      /Users/wez/.fonts/OperatorMonoSSmLig-Medium.otf, FontDirs
10 l    \u{6c}       x_adv=8  cells=1  glyph=40   wezterm.font("Operator Mono SSm Lig", {weight="DemiLight", stretch="Normal", style="Normal"})
                                      /Users/wez/.fonts/OperatorMonoSSmLig-Medium.otf, FontDirs
11 l    \u{6c}       x_adv=8  cells=1  glyph=40   wezterm.font("Operator Mono SSm Lig", {weight="DemiLight", stretch="Normal", style="Normal"})
                                      /Users/wez/.fonts/OperatorMonoSSmLig-Medium.otf, FontDirs
12 o    \u{6f}       x_adv=8  cells=1  glyph=43   wezterm.font("Operator Mono SSm Lig", {weight="DemiLight", stretch="Normal", style="Normal"})
                                      /Users/wez/.fonts/OperatorMonoSSmLig-Medium.otf, FontDirs
```

**Comment by cbirchinger** [comment]
Setting that to false fixes the issue for me, yes. I'm really sorry for wasting your time. I was almost sure it is something, a config change can fix, i just failed to find the option..
