### ISSUE TITLE
mux: split, close, split again -> wonky sizing

### ISSUE THREAD

**Issue by wez** [wez/wezterm#1818]
The position problem still exists. (Split a pane, close a pane, split again, this time pane goes to the place of a third pane, as if the second pane was split.)

_Originally posted by @CIAvash in https://github.com/wez/wezterm/issues/1752#issuecomment-1088858264_

![image](https://user-images.githubusercontent.com/117777/161790486-6f6233cc-9f93-42a2-91c7-2202f7897af7.png)

**Comment by mtanda** [comment]
When I'm using `top-level` split, I hit similar issue.
The upper left pane is original pane.
I expect bottom pane height is same as upper pane height.

How to reproduce.
```
wezterm cli split-pane --right
wezterm cli split-pane --top-level --bottom
# close bottom pane
wezterm cli split-pane --top-level --bottom
```

The wezterm version is `20220905-102802,7d4b8249`.
I hit this issue on macOS and Windows.

![image](https://user-images.githubusercontent.com/224552/190028954-30c68c9d-7876-404f-a282-f82608f2a608.png)

**Comment by aca** [comment]
Any updates on this?
