### ISSUE TITLE
Improve selection extension

### ISSUE THREAD

**Issue by wez** [wez/wezterm#182]
@bew suggested some improvements inspired by urxvt:

* Currently the extended region is always relative to the start of the selection.  This is great when extending right/down but not when going left/up.  We should probably union the existing selection and the correct region around the mouse rather than joining those two starting points into a selection.
* Would be nice to remember the mode (character/word/line) along with the selection so that a simple shift-click extends in the same mode.  The mode could then be changed (toggled?) by eg: shift-double-clicking.
* shift-double-click seems to clear the selection making it even harder to extend in word mode

They also asked about rectangular selection.  That feels quite a bit harder than the improvements above so I'd prefer to punt that into a separate issue and see what the demand looks like :)

**Comment by bew** [comment]
Another thing that is missing around mouse selection is the ability to change what is considered a word when doing a word selection.

I saw a TODO about that here:
https://github.com/wez/wezterm/blob/2603f9d4b4007916217ade5c50a551a1a4838064/wezterm-gui/src/gui/selection.rs#L54-L64

**Comment by DarkPark** [comment]
+1 for rectangular selection
