### ISSUE TITLE
Unable to select text from pane

### ISSUE THREAD

**Issue by gegoune** [wez/wezterm#1822]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220405-085405-b2ba7383

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Once pane is created within window user is unable to copy text by mouse (double clicking or dragging cursor with pressed left button) from it. Please note that triple click highlights and copies entire line as expected (from new pane).

Copying text from original window (now also a pane) is unaffected. Only new panes are.

### To Reproduce

1. Open new wezterm window
2. Split window into two panes
3. Run any command or input text into new pane to produce text to copy
4. Try to copy any word/text by either double clicking on word or dragging cursor over it from new pane

### Configuration

No relevant config, I have changed only colours and keybinding (no mouse bindings).

### Expected Behavior

Able to copy text by double clicking on words or dragging cursor over it in any open panes.

**Comment by wez** [comment]
cc: @davidrios I think this might be related to your recent changes; can you take a look?

**Comment by davidrios** [comment]
Sure
