### ISSUE TITLE
Mouse selection of text in Vim doesn't update while draging

### ISSUE THREAD

**Issue by cbirchinger** [wez/wezterm#1825]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220405-091515-8a0072ad

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In the following example text is slowly marked from top/left to bottom/right. In WezTerm the block is not updated until the left mouse button is released:

![vimselect-wezterm](https://user-images.githubusercontent.com/4973300/161985941-a6afc4ac-f9d6-4614-8cbb-7424bcc2087f.gif)

The same example in other terminals (tested: XTerm, Xfce4-Terminal, Alacritty, Kitty, mlterm):

![vimselect-xfce4terminal](https://user-images.githubusercontent.com/4973300/161986249-ac3a3bc9-ef88-4b5a-9856-1d7e419cb607.gif)

### To Reproduce

This command disables any user configuration and possible xlib support, which would open a different can of worms.
It should make it as standardized as possible to reproduce.

`vim -XR -u NONE -U NONE -N -i NONE -c "set mouse=a" dots.txt`

It can be reproduced using flatpak to avoid installing unwanted packages:

`flatpak run org.vim.Vim -XR -u NONE -U NONE -N -i NONE -c "set mouse=a" dots.txt`

### Configuration

no config

### Expected Behavior

The marked area should expand while moving the mouse

### Anything else?

If not deactivated using "-X" Vim will read the $WINDOWID environment variable set by every other terminal.
If WezTerm doesn't set it, i could get passed down from the previous X program resulting in programs reading
from a wrong window. Kitty previously ran into exactly the same problem: https://github.com/kovidgoyal/kitty/issues/232 . 
Setting it will prevent people from running into strange behaviors, it will not enable Vim's enhanced mouse
reporting, because that would need more xprops like WM_NORMAL_HINTS(WM_SIZE_HINTS) to be exposed by
WezTerm.

But as i previously said, for this specific issue i fully disabled xlib support using "vim -X" to avoid mixing
completely different code paths. This issue is strictly narrowed down to terminal only functionality.

Neovim has different console mouse code and works out of the box, just as tmux mouse mode also works.

**Comment by wez** [comment]
a0ce1f952650cc4808633f17f2098071d0729f53 removes stray WINDOWID passed down from above

**Comment by wez** [comment]
After some discussion on Element, we realized that the heart of this problem was due to the secondary DA response; vim was defaulting `ttymouse=xterm` because it thought we were a really old xterm.  The response has been bumped to 277 which causes xterm to adopt `ttymouse=sgr` by default.
