### ISSUE TITLE
Using Raw Key Events with alt + shift doesn't work

### ISSUE THREAD

**Issue by kjmph** [wez/wezterm#1826]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220319-142410-0fcdea07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

First of all, really excited about Wezterm. It is very nice on macos, after fighting with many other terminals, wezterm is almost completely there out of the box!

The default of wezterm is to properly send the raw key events ALT is pressed! That's awesome, unfortunately, when the SHIFT modifier is used, the composed key event is sent instead. Can the `send_composed_key_when_left_alt_is_pressed` and/or `send_composed_key_when_alt_is_pressed` config settings please also ignore the SHIFT modifier as well? Note, when CONTROL is used, it does use the raw key event.

Small note, `send_composed_key_when_left_alt_is_pressed` isn't in the documentation of in the config section on the website.

### To Reproduce

Open a wezterm and use:

```shell
$ read
ALT+2: ^[2
$ read
ALT+CTRL+2: ^[^@
$ read
ALT+SHIFT+2: €
```

### Configuration

Doesn't appear relevant.. Note, however `send_composed_key_when_left_alt_is_pressed` set to true does produce ™!! So, it does behave when requested.

### Expected Behavior

```shell
$ read
ALT+SHIFT+2: ^[@
```

### Logs

```
 2022-04-06T14:22:47.757Z INFO  wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('@'), modifiers: SHIFT | ALT | LEFT_ALT, phys_code: Some(K2), raw_code: 19, repeat_count: 1, key_is_down: true, handled: Handled(false) }
 2022-04-06T14:22:47.757Z INFO  wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('€'), modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Char('@'), modifiers: SHIFT | ALT | LEFT_ALT, phys_code: Some(K2), raw_code: 19, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
 2022-04-06T14:22:47.757Z INFO  wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('€') mods=NONE
 2022-04-06T14:22:47.757Z INFO  wezterm_term::terminalstate::keyboard > key_down: sending "€", Char('€') NONE
 2022-04-06T14:22:47.896Z INFO  wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('@'), modifiers: SHIFT | ALT | LEFT_ALT, phys_code: Some(K2), raw_code: 19, repeat_count: 1, key_is_down: false, handled: Handled(false) }
 2022-04-06T14:22:47.896Z INFO  wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('€'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('@'), modifiers: SHIFT | ALT | LEFT_ALT, phys_code: Some(K2), raw_code: 19, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
 2022-04-06T14:22:47.896Z INFO  wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('€') mods=NONE
```

### Anything else?

Thanks again!

**Comment by kjmph** [comment]
(Sorry, I didn't explain why I'm not using nightly.. the instructions for tapping and installing via Homebrew from the wezterm homepage failed. I believe that would get me access to nightly. So, I just fell back to the cask that shows up from `brew search wezterm`, that seems to install just fine.)

**Comment by kjmph** [comment]
Also note, I don't think `ALT+CTRL+2` should be `^[^@`, probably `^[^2`.. A lot of the `ALT+CTRL` sequences seem odd..

**Comment by wez** [comment]
Please try a nightly build: you can download a DMG using the nightly button on https://wezfurlong.org/wezterm/install/macos.html and just run it ad-hoc for the sake of testing.

The reason I ask is that key mapping has changed (improved!) since the last release

**Comment by kjmph** [comment]
Thanks, I tried that, same results:

```shell
$ read
^[2 ^[^@ €
```

**Comment by wez** [comment]
I've pushed a change that make this only consider the alt/option modifiers.  I have no memory of why it only wanted exclusively alt mods... I wouldn't be surprised if this breaks some other obscure corner of key input on the mac!
These changes should show up in a macOS nightly build in about an hour from now.

**Comment by cstyles** [comment]
I encountered the same problem so I built WezTerm from source on the `main` branch (specifically 5eb3b122a656be74e7a6980d71338524a560dfed) and confirmed that the issue is fixed so thanks! 🎉 

However, I'm also running into an issue where `OPTION + TAB` works correctly but `OPTION + SHIFT + TAB` does not. It's worth nothing that it's not working on the 20220319-142410-0fcdea07 release either so it's not a regression. Is that related to this issue or should I open a new issue?

**Comment by kjmph** [comment]
My apologies, I know it is marked closed, yet.. I can confirm it works in nightly with the builtin keyboard. However, with my external keyboard, apparently `LEFT ALT` and `RIGHT ALT` are swapped? That's crazy.. Anyway, the reason I'm pinging back is because nightly doesn't recognize `send_composed_key_when_alt_is_pressed` anymore.. effectively requiring me to set both `send_composed_key_when_left_alt_is_pressed` and `send_composed_key_when_right_alt_is_pressed` to `false`. Not a big deal to me, it all works for me, thanks for the fix.. Yet, I thought you may want to know in case other people encounter this.

**Comment by wez** [comment]
`send_composed_key_when_alt_is_pressed` is a legacy option and is mentioned in passing in the docs for users of old versions.  I'm just going to remove it.

Regarding left/right alt being swapped for an external keyboard: is that keyboard a programmable keyboard?  Perhaps its firmware has left/right flipped?  Or alternatively: if you are running keyboard remapping software, it's possible that is affecting how that particular keyboard is reporting.

**Comment by kjmph** [comment]
Oh thanks, I appreciate the feedback. Yet, it is a Microsoft Natural Keyboard Elite, and the CTRL/ALT/META(WINDOWS) keys are all swapped RIGHT and LEFT (SHIFT is fine); it isn't wezterm's fault. I just never noticed before. No remapping software is running. Totally silly. I was just leaving the comment in case someone else was confused. https://keycode.info/ seems to report the same reversed events, so it could be helpful for someone else.

**Comment by wez** [comment]
OK, let's call this one done!
