### ISSUE TITLE
Touchpad scrolling on Wayland does not register slow swipes

### ISSUE THREAD

**Issue by szbergeron** [wez/wezterm#1827]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220317-165235-27088fab

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If I try to scroll in vim or scrollback, if the swipe is done below a certain speed the deltas are not added together and no scroll ticks are dispatched.

When deltas for a given period do not add up to a full scroll unit, they should be added to an accumulator and applied once the required threshold to dispatch a tick is reached.

### Configuration

```
local wezterm = require 'wezterm';

return {
    font = wezterm.font("FiraCode Nerd Font Mono"),

    color_scheme = "Aurora",

    enable_wayland = true,

    default_prog = {"/usr/bin/fish"},

    -- enable_scroll_bar = true,

    warn_about_missing_glyphs = false,

    hide_tab_bar_if_only_one_tab = true,

    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
    },

    window_decorations = "RESIZE"
}
```

**Comment by szbergeron** [comment]
I seem to still have the described behavior on `wezterm 20220406-081134-1b0f5cf2`

**Comment by wez** [comment]
@davidrios: could you take a look when you have a chance? Thanks!

**Comment by szbergeron** [comment]
Additional env info:

Gnome wayland (mutter 42.0)
Libinput 1.20.0
Running on Dell XPS 17 (9700)

**Comment by szbergeron** [comment]
This is now fixed for me on master, thanks!
