### ISSUE TITLE
homebrew install didn't work

### ISSUE THREAD

**Issue by justinabrahms** [wez/wezterm#1828]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

N/A

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

```
❯ brew tap wez/wezterm
Running `brew update --preinstall`...
...snip...
==> Tapping wez/wezterm
Cloning into '/usr/local/Homebrew/Library/Taps/wez/homebrew-wezterm'...
remote: Enumerating objects: 136, done.
remote: Counting objects: 100% (136/136), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 136 (delta 35), reused 108 (delta 26), pack-reused 0
Receiving objects: 100% (136/136), 19.87 KiB | 924.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.
Tapped 2 casks and 1 formula (16 files, 34.7KB).

❯ brew install --cask wez/wezterm/wezterm
==> Caveats
Cask wezterm related executables like 'wezterm', 'wezterm-gui',
'wezterm-mux-server', are linked into
  /usr/local/bin/    for x86 Mac,
  /opt/homebrew/bin/ for M1 Mac.

Removal of them is ensured by 'brew uninstall --cask wezterm'.

==> Downloading https://github.com/wez/wezterm/releases/download/20220405-091515
#=#=#
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'wezterm' with message: Download failed: https://github.com/wez/wezterm/releases/download/20220405-091515-8a0072ad/WezTerm-macos-20220405-091515-8a0072ad.zip
```

### Configuration

no config

### Expected Behavior

I expected it to actually download & install.

**Comment by kjmph** [comment]
Yes, it appears those install instructions could be updated. Homebrew now has default cask that can be installed via `brew install wezterm` located here: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/wezterm.rb

The tapped cask from @wez is referencing a non-existant wezterm release, which may have been a mistakenly committed file, see the 20220405 release in your output? GitHub doesn't list it as an existing release. See the cask file: https://github.com/wez/homebrew-wezterm/blob/fbec901dad36e3d2ee900f4ce5441814d60df39d/Casks/wezterm.rb

If you want to continue using the tapped cask, the nightly package will install via `brew install --cask wez/wezterm/wezterm-nightly`

Does this help?

**Comment by kjmph** [comment]
For a more stable version, would the default Homebrew cask work? It does install the latest release, `20220319-142410-0fcdea07`..

**Comment by wez** [comment]
I pushed a new release, so this should be resolved now.
