### ISSUE TITLE
Linux: Clipboard/Primary selection handling

### ISSUE THREAD

**Issue by bew** [wez/wezterm#183]
_explanations on X11 selections: https://unix.stackexchange.com/a/139193/159811_

After "renting" about the importance of the primary selection in my workflow, @wez [implemented it](https://github.com/wez/wezterm/commit/5ebdcc3642c0760a98b14a553696a737d9c72cf4) as the default one when pasting some text in the terminal.
It turns out that this implementation makes the primary selection the only one we can paste from, which can be problematic when using other apps that does not put their clipboard content in the primary selection.

To properly handle both selections when pasting (copying still writes to both selections for now), we need another keybind/mousebind to paste from a selection or the other. (in comparison, urxvt uses Alt-MiddleClick for clipboard selection & MiddleClick for primary selection)

Looking at the "Key binding" page on wezterm's website, there is a `Paste` command, there could be a `AltPaste` command that would do the same as `Paste` for most OSs but would be different by default for X11.
I don't know which one should be for clipboard/primary. [I agree with you](https://gitter.im/wezterm/Lobby?at=5ec03180863019312a636f4a), it's not intuitive to have multiple selection buffers, so I guess `Paste` should paste from the clipboard selection, and `AltPaste` could paste from the primary selection?

**Comment by wez** [comment]
In about an hour (or really now if you grab the artifacts direct from https://github.com/wez/wezterm/actions/runs/111582984) you should be able to assign `PastePrimarySelection` to a key.

Note that there were some potentially breaking changes in the key assignment config stuff to support this, if you use `arg = ` in some of your key assignments you will need to migrate your config to the newer style.

**Comment by bew** [comment]
Thanks a lot @wez, it works well!!
