### ISSUE TITLE
`Alt + Shift + Tab` doesn't work as expected

### ISSUE THREAD

**Issue by cstyles** [wez/wezterm#1831]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220406-095008-eefe4bd2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm not sure what's "correct" here but I recently switched to WezTerm from iTerm2 and I've encountered a discrepancy in behavior when I press `Alt + Shift + Tab`.

In iTerm2 (with left option set to the "Esc+" setting):

```fish
> od -c
^[^Y

> fish_key_reader
Press a key:
bind \e\cY 'do something'
```

In WezTerm:

```fish
> od -c
^[^[[Z

> fish_key_reader
Press a key:
bind -k btab 'do something'
bind \e\e\[Z 'do something'
```

Interestingly, it looks like pressing `Shift + Tab` works the same in both iTerm2 and WezTerm. I get the following:

```fish
> od -c
^[[Z

> fish_key_reader
Press a key:
bind -k btab 'do something'
bind \e\[Z 'do something'
```

The output from WezTerm for `Alt + Shift + Tab` is the same as the output for `Shift + Tab` but with `^[` in front of it which seems at least consistent though not very useful (how do I input two metas?). iTerm2, on the other hand, is doing something weird but that weirdness is useful because it allows me to create a mapping in NeoVim for `<M-C-Y>` (meta + control + Y) which works when I press `Alt + Shift + Tab`. I don't know why iTerm2 produces the output that it does but is it possible to do the same in WezTerm?

### Configuration

no config

**Comment by wez** [comment]
Firstly, I'd recommend updating to the latest nightly as a number of fixes with key handling have landed.
That should allow you to define a key assignment like:

```lua
  -- Alt-Shift-Tab -> iterm2 compatible ESC-CTRL-Y
  {key="Tab", mods="ALT|SHIFT", action=wezterm.action{SendString="\x1b\x19"}},
```


Secondly, I'm not sure what the correct behavior is for `Alt + Shift + Tab`.  I'll check to see what xterm is doing when I'm next at my linux machine!

**Comment by cstyles** [comment]
I tried that key assignment on stable (`wezterm 20220408-101518-b908e2dd`) and it works perfectly! Thanks so much!

Should we close this issue or did you want to leave it open until you can figure out how xterm treats `Alt + Shift + Tab`?

**Comment by wez** [comment]
xterm treats `Alt + Shift + Tab` the same as `Shift + Tab` (in other words, it doesn't care about the Alt mod).
gnome terminal just sends ESC followed by a Tab (it doesn't care about either mod).

Kitty sends `^[^[[Z`, same as wezterm does currently.

I don't think there is a clear winner, but I'm inclined to not change wezterm's behavior for the time being as it "makes sense": it's an Escape follow by the normal Shift-Tab sequence, which is following the idea that Alt sends a leading escape before the normal sequence.

**Comment by cstyles** [comment]
> I don't think there is a clear winner, but I'm inclined to not change wezterm's behavior for the time being as it "makes sense": it's an Escape follow by the normal Shift-Tab sequence, which is following the idea that Alt sends a leading escape before the normal sequence.

This makes a lot of sense. If I change my NeoVim mapping from `<M-C-Y>` to `<Esc><S-Tab>`, it works as expected without needing to add the iTerm2 compatibility key assignment to WezTerm's config. I think that's all I need. Thanks for your help!
