### ISSUE TITLE
Font weights also impact bold styling

### ISSUE THREAD

**Issue by kjmph** [wez/wezterm#1836]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220407-064715-c96396bd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When setting the font weight to be `Bold`, I would expect that I could set a color for bolded text as well, like in other terminal software. I believe font weights and bold control characters could resolve to different foreground colors. I'll attach a screenshot.

### To Reproduce

```shell
$ echo "$(tput bold)bold$(tput sgr0) | not bold"
bold | not bold
```

Results in this in Wezterm:

![Screen Shot 2022-04-07 at 3 53 19 PM](https://user-images.githubusercontent.com/1075649/162285353-96586ad1-ae1d-4fc7-9ef2-3d340453236a.png)

Results in this in Terminal.app:

![Screen Shot 2022-04-07 at 3 53 31 PM](https://user-images.githubusercontent.com/1075649/162285406-1deb1258-b0c7-48bf-80a5-5034502988b7.png)

### Configuration

Relevant configuration:

```lua
local wezterm = require 'wezterm';

return {
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},
  font = wezterm.font("Menlo", { weight="Bold" }),
  font_size = 14.0,
}
```

### Expected Behavior

I expect a color configuration for foreground_bold.. at least, I think so.

**Comment by wez** [comment]
Take a look at `font_rules`:
https://wezfurlong.org/wezterm/config/lua/config/font_rules.html?highlight=tomato#font_rules

**Comment by kjmph** [comment]
Awesome, that does fix the coloring issue!
