### ISSUE TITLE
Window border could have a single pixel border around it.

### ISSUE THREAD

**Issue by kjmph** [wez/wezterm#1837]
**Is your feature request related to a problem? Please describe.**

If you are silly like me, and have the whole screen taken up by a single terminal window, then hit `⌘+N` to open a new window that overlays on top, *then* want to resize it with the mouse, you'll notice it is near impossible to find the corner of the overlapping terminal, since it shares the same background color.

**Describe the solution you'd like**

A single pixel border around the window wouldn't be too intrusive. That's what Terminal.app does, it makes the corner easier to find.

**Describe alternatives you've considered**

I drag the overlapping window till the corner is viewable over some text, then resize the window from there. Alternatively, I can use shortcut keys to enlarge the new window, yet sometimes I want to treat this new window as ephemeral and exit it soon.

**Additional context**

Wezterm overlapping windows:
![Screen Shot 2022-04-07 at 4 06 18 PM](https://user-images.githubusercontent.com/1075649/162287266-adb9b1d6-bcf0-4ce3-9745-c3a578dc6ce0.png)

Terminal.app overlapping windows:
![Screen Shot 2022-04-07 at 4 06 54 PM](https://user-images.githubusercontent.com/1075649/162287293-3ef7134d-af8c-450d-933e-3e9f2e57331d.png)

**Comment by wez** [comment]
Take a look at the border related options that are now available in nightly builds:
https://wezfurlong.org/wezterm/config/lua/config/window_frame.html

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
