### ISSUE TITLE
Focus issue causes a distraction

### ISSUE THREAD

**Issue by kjmph** [wez/wezterm#1838]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220407-064715-c96396bd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using two terminals back to back, there seems to be a focus issue, which in my case causes flickering with the Emacs status bar. This may be related to bug #1757, and perhaps this is helpful as I'm using `macos`? My description skills are lost here, because I have less of a handle on what's going on. A video may be helpful; the bottom two windows are Terminal.app windows, the top two are Wezterm windows.

https://user-images.githubusercontent.com/1075649/162288794-817f505e-4b36-4aba-b58e-6a38a91ffa60.mov

### To Reproduce

Open two windows side by side, and have an update to the terminal when the window loses focus?

### Configuration

I don't believe anything is relevant here..

### Expected Behavior

Apparently, I expect the window losing focus to not try and take back the focus???

### Anything else?

Please, let me know what logs you would like me to capture. I'm here to assist.

**Comment by wez** [comment]
More focused repro is:

* Start wezterm
* CMD-N to spawn a new window
* `printf "\e[?1004h" ; od -c` in the window
* Focus the other window
* A series of focus-in/out events are reported in the original window, followed by a ton of bell notifications

**Comment by wez** [comment]
This is fixed now in `main` and available in the latest nightly build.  Thanks for reporting this!

**Comment by kjmph** [comment]
This works great! Thanks a lot!
