### ISSUE TITLE
Disable copy on select for Windows?

### ISSUE THREAD

**Issue by kvnxiao** [wez/wezterm#1847]
**Is your feature request related to a problem? Please describe.**
Is there a way to disable copy on selection of text on Windows? This is very annoying because it overwrites my current clipboard. I want to explicitly perform a CTRL+SHIFT+C to copy from the selection made in wezterm. Sometimes I drag click my mouse throughout the window and create a selection by accident, which inadvertently overwrites my clipboard.

**Describe the solution you'd like**
Config option to disable automatic overwriting clipboard on Windows

**Comment by wez** [comment]
You can reconfigure mouse assignments; https://wezfurlong.org/wezterm/config/mouse.html has more information.
Something like this might do what you want:

```lua
local wezterm = require 'wezterm';

return {
  mouse_bindings = {
    -- Change the default selection behavior so that it only selects text,
    -- but doesn't copy it to a clipboard or open hyperlinks.
    {
      event={Up={streak=1, button="Left"}},
      mods="NONE",
      action=wezterm.action{ExtendSelectionToMouseCursor="Cell"}
    },
    -- Don't automatically copy the selection to the clipboard
    -- when double clicking a word
    {
      event={Up={streak=2, button="Left"}},
      mods="NONE",
      action="Nop",
    },
    -- Ctrl-click will open the link under the mouse cursor
    {
      event={Up={streak=1, button="Left"}},
      mods="CTRL",
      action="OpenLinkAtMouseCursor",
    },
  },
}
```

**Comment by kvnxiao** [comment]
Thanks, that did the trick! May be a good idea to add a dedicated section for Windows with the above example snippet for those similarly looking for this.
