### ISSUE TITLE
Refresh environment variables?

### ISSUE THREAD

**Issue by archiif** [wez/wezterm#1848]
**Is your feature request related to a problem? Please describe.**
I'm on Windows, and when I add or update environment variables, the shells I use don't pick them up even when I open a new tab. I need to restart Wezterm entirely so that it can see the new variables.

**Describe the solution you'd like**
Some way to refresh environment variables without restarting Wezterm entirely would be nice

**Comment by wez** [comment]
It's not possible to change the environment of a running process.

On unix systems, wezterm will, by default, spawn shells as login shells, which encourages them to do things to setup the environment from scratch.

https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-environment mentions that:

`HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Sessionmanager\Environment`

and

`HKEY_USERS\<user>\Environment`

are two registry keys that define the environment. Having a config option (default=true) that enables populating the environment from that seems like a reasonable request.

**Comment by wez** [comment]
This should be fixed now in `main`; the behavior is to merge in the environment settings from the registry.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by archiif** [comment]
Thank you! I tried the nightly build and it works as expected.
Would it also be appropriate to have this feature available as a command (so you can merge environment settings from the registry without having to spawn a new shell), or do you think it's too platform-specific?

**Comment by wez** [comment]
There isn't a way for wezterm (or any program) to manipulate the environment of a running process, so it wouldn't be possible to make a command to do that. The best we can do is spawn a new shell with the appropriate environment. If you wanted to get your shell to update its environment from the registry, you'll need to find a way to teach your shell how to do that.

**Comment by archiif** [comment]
Alright, I'll consider this issue closed then!
