### ISSUE TITLE
Conditionally set up keybinds depending on if text is selected? (CTRL+c for copy + sigint)

### ISSUE THREAD

**Issue by kvnxiao** [wez/wezterm#1849]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use regular CTRL+c (without SHIFT) only when a text selection exists, to perform `action=wezterm.action{CopyTo="Clipboard"}`. But send a regular ^C sigint when no selection exists.

Is this possible to do so? I've scoured the lua config docs but it's hard to gauge if this is a supported feature, and https://wezfurlong.org/wezterm/config/keys.html doesn't seem to mention it.

Also to note that I tested using 
```lua
  keys = {
    {key="c", mods="CTRL", action=wezterm.action{CopyTo="Clipboard"}},
  }
```
which will allow me to CTRL+c to copy, but will prevent me from sending ^C when no text selection exists, which effectively prevents me from sending a SIGINT unless I remove this keybinding.

**Comment by bew** [comment]
Yes it's possible, I made a similar keybind, using `win:get_selection_text_for_pane(pane)` to select the action to do.
See https://github.com/bew/dotfiles/blob/a83e8226187b592efb29b681d8392962f8bfff14/gui/wezterm/cfg_keys.lua#L46

**Comment by kvnxiao** [comment]
Thanks! I think I got it working with

```lua
  keys = {
    {
      key="c",
      mods="CTRL",
      action = wezterm.action_callback(function(win, pane)
        local has_selection = win:get_selection_text_for_pane(pane) ~= ""
        if has_selection then
          win:perform_action(wezterm.action{CopyTo="ClipboardAndPrimarySelection"}, pane)
        else
          win:perform_action(wezterm.action{SendKey={key="c", mods="CTRL"}}, pane)
        end
      end)
    }
  }
```

**Comment by 1player** [comment]
I'm happy that someone already requested this feature, but one crucial thing to make smart copy very ergonomic is clearing the selection after copy. That way you can force a SIGINT even with selected text by pressing Ctrl-C twice.

Yet I don't think I've seen an API function to clear the selection, is that right? Is it planned by any chance?

**Comment by wez** [comment]
Latest nightly allows this:


```lua
local wezterm = require 'wezterm'
return {
  keys = {
    {
      key="c",
      mods="CTRL",
      action = wezterm.action_callback(function(window, pane)
        local has_selection = window:get_selection_text_for_pane(pane) ~= ""
        if has_selection then
          window:perform_action(
            wezterm.action{CopyTo="ClipboardAndPrimarySelection"},
            pane)
          window:perform_action("ClearSelection", pane)
        else
          window:perform_action(
            wezterm.action{SendKey={key="c", mods="CTRL"}},
            pane)
        end
      end)
    }
  }
}
```

**Comment by 1player** [comment]
This is the full configuration for reference, requires latest nightly:

```
local wezterm = require 'wezterm'
return {
  keys = {
    {
      key="c",
      mods="CTRL",
      action = wezterm.action_callback(function(window, pane)
        local has_selection = window:get_selection_text_for_pane(pane) ~= ""
        if has_selection then
          window:perform_action(
            wezterm.action{CopyTo="ClipboardAndPrimarySelection"},
            pane)
          window:perform_action("ClearSelection", pane)
        else
          window:perform_action(
            wezterm.action{SendKey={key="c", mods="CTRL"}},
            pane)
        end
      end)
    }
  },
  {
    key="c",
    mods="CTRL|SHIFT",
    action = wezterm.action{SendKey={key="c", mods="CTRL"}}
  },
  {
     key="v",
     mods="CTRL",
     action="Paste",
  },
  {
     key="v",
     mods="CTRL|SHIFT",
     action=wezterm.action{SendKey={key="v", mods="CTRL"}},
  },
}
```

* Ctrl-C copies and clear selection, if there's a selection — sends Ctrl-C signal (SIGINT) otherwise.
* Ctrl-Shift-C always sends Ctrl-C signal (SIGINT).
* Ctrl-V pastes.
* Ctrl-Shift-V always sends Ctrl-V.

Would be cool to add this to the FAQs
