### ISSUE TITLE
German keymap on Windows 10 does not work correctly

### ISSUE THREAD

**Issue by mardukbp** [wez/wezterm#185]
## Describe the bug

In the German keymap some characters (like |) are inserted pressing the modifier key `Alt Gr`. This does not work in wezterm.

## Environment (please complete the following information):

 - OS: Windows 10
 - Frontend:  OpenGL
 - Version: 20200517-122836-92c201c6

## To Reproduce

1. Activate the German keymap in Windows
2. Fire up wezterm
3. Press `Alt Gr + <`

Instead of inserting `|`, nothing happens.

Setting `RUST_LOG=debug` reveals that the problem is that the `rustyline` crate uses Emacs mode by default and interprets `Alt Gr` as Meta and it complains that `Alt Gr + <` is not a recognized Emacs command.

## Configuration

```lua
return {
   font_size = 16.0,
   hide_tab_bar_if_only_one_tab = true
}

```

## Expected behavior

Pressing `Alt Gr + <` should insert `|`.

**Comment by wez** [comment]
@mardukbp I think I've figured this out.  I've pushed a commit that seems to resolve this for me.

You'll be able to download a build from here when it completes:
https://github.com/wez/wezterm/actions/runs/111075072

Please let me know how that works for you!

**Comment by electronicminds** [comment]
@wez I can confirm the provided build does resolve the windows AltGr handling

**Comment by mborejdo** [comment]
@wez  I can confirm the provided build does resolve the windows AltGr handling

**Comment by mardukbp** [comment]
Thank you @wez! This issue is indeed solved.
