### ISSUE TITLE
CTRL-i is treated as CTRL-Tab

### ISSUE THREAD

**Issue by demiflat** [wez/wezterm#1851]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220409-221922-b83c3272

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have the following config for rotating through tabs:

CTRL-"k" and CTRL-"l" work but CTRL="i" prints out the string ";5u" on the console.  This used to work.
...
keys = {
     {key="i", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
     {key="k", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
     {key="l", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
      ...
}

Working:
* aba3da6a0 - (HEAD) deps: cargo update (3 weeks ago) <Wez Furlong>

Not working:
* 317bfeef4 
* b83c3272f - (HEAD -> main, origin/main, origin/HEAD) Add some more entries to command defs (5 hours ago) <Wez Furlong>

### To Reproduce

Use the following config:

keys = {
     {key="i", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
     {key="k", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
     {key="l", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
}

Press CTRL-i

Observe ";5u"  printed to the console.

OS: Fedora 35, x86_64, Wayland (wlroots), SwayWM

### Configuration

keys = {
     {key="i", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
     {key="k", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
     {key="l", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
      ...
}

### Expected Behavior

focus on next tab

### Logs

20:52:15.144  INFO   wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 630 (CFL GT2) 4.6 (Compatibility Profile) Mesa 21.3.8 is_context_loss_possible=false wezterm version: 20220409-221922-b83c3272

(no logs during error)

**Comment by wez** [comment]
Please enable https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html and capture the logs from pressing the broken key, thanks!

**Comment by demiflat** [comment]
Another note, this was self compiled using 

cargo build --release
~ $ rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
~ $ cargo version
cargo 1.60.0 (d1fd9fe 2022-03-01)

**Comment by demiflat** [comment]
> Please enable https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html and capture the logs from pressing the broken key, thanks!

20:59:38.379  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Control mods=NONE
20:59:38.972  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: true, handled: Handled(false) }
20:59:38.972  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('\t'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
20:59:38.972  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Tab mods=CTRL
20:59:38.972  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[9;5u", Tab CTRL
20:59:39.055  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('i'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
20:59:39.055  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('i') mods=CTRL
20:59:39.415  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
20:59:39.415  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=CTRL

**Comment by demiflat** [comment]
just in case it's any different, this was the log for the keyboard on my laptop (as opposed to the external keyboard previously):
21:00:37.611  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Control mods=NONE
21:00:38.119  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:00:38.119  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('\t'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:00:38.119  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Tab mods=CTRL
21:00:38.119  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[9;5u", Tab CTRL
21:00:38.234  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('i'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:00:38.234  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('i') mods=CTRL
21:00:39.765  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:00:39.765  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=CTRL

**Comment by wez** [comment]
Hmm, looks like CTRL-l is being mapped to tab somehow?

Let's see the output from this, which turns up more tracing from the keymap processing:

```
WEZTERM_LOG=window::os::x11::keyboard=trace,info wezterm
```

What keyboard layout do you have active?

**Comment by wez** [comment]
Are we talking about L or I?  I'm not sure because l and I look the same here in the browser :-p

**Comment by demiflat** [comment]
> Are we talking about L or I? I'm not sure because l and I look the same here in the browser :-p

Ctrl-I

**Comment by wez** [comment]
ell or eye?

**Comment by wez** [comment]
I literally cannot see the difference between CTRL-l (lower case ell) and CTRL-I (upper case eye) here

**Comment by wez** [comment]
Relevant commit: c96396bd2f99dfc1076e543e39ffa7e1f55cd171

**Comment by demiflat** [comment]
> 

eye

**Comment by demiflat** [comment]
> Hmm, looks like CTRL-l is being mapped to tab somehow?
> 
> Let's see the output from this, which turns up more tracing from the keymap processing:
> 
> ```
> WEZTERM_LOG=window::os::x11::keyboard=trace,info wezterm
> ```
> 
> What keyboard layout do you have active?

21:08:06.900  INFO   wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 630 (CFL GT2) 4.6 (Compatibility Profile) Mesa 21.3.8 is_context_loss_possible=false wezterm version: 20220409-221922-b83c3272
21:08:09.453  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:08:09.453  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", 65507. kc -> None
21:08:09.453  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:08:09.453  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=NONE
21:08:09.780  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: CTRL, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:08:09.780  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", 65505. kc -> None
21:08:09.780  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Shift, modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: CTRL, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:08:09.780  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Shift mods=CTRL
21:08:10.287  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(T), modifiers: SHIFT | CTRL, phys_code: Some(T), raw_code: 28, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:08:10.287  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "\u{14}", 84. kc -> Some(Char('\u{14}'))
21:08:10.287  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('T'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(T), modifiers: SHIFT | CTRL, phys_code: Some(T), raw_code: 28, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:08:10.288  INFO   wezterm_gui::termwindow::keyevent > Char('T') CTRL -> perform SpawnTab(CurrentPaneDomain)
21:08:10.392  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('T'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(T), modifiers: SHIFT | CTRL, phys_code: Some(T), raw_code: 28, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:08:10.392  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('T') mods=CTRL
21:08:10.669  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: SHIFT | CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: SHIFT | CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:08:10.669  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Control mods=SHIFT | CTRL
21:08:10.701  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Shift, modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:08:10.701  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Shift mods=SHIFT
21:08:19.552  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:08:19.552  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", 65507. kc -> None
21:08:19.553  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:08:19.553  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=NONE
21:08:19.686  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:08:19.686  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "\t", 105. kc -> Some(Char('\t'))
21:08:19.686  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\t'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:08:19.686  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Tab mods=CTRL
21:08:19.687  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[9;5u", Tab CTRL
21:08:19.775  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('i'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:08:19.775  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('i') mods=CTRL
21:08:20.276  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:08:20.276  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=CTRL
^C

------

in that log i created a new tab and then clicked CTRL-eye

**Comment by demiflat** [comment]
> What keyboard layout do you have active?
I'm using a Lenovo P53 in locale LANG=en_US.UTF-8.  My external keyboard is running qmk but I get the same behavior using the laptop's keyboard so I don't think this is a keymapping problem. I'll try reverting commit c96396b and seeing if that reverts this behavior.

**Comment by wez** [comment]
This bit from your logs indicates that the keyboard layout is remapping CTRL-i to Tab; that "makes sense" because that is actually the same thing in ASCII:

```
21:08:19.686 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:08:19.686 TRACE window::os::x11::keyboard > process_key_event: RawKeyEvent FeedResult::Nothing: "\t", 105. kc -> Some(Char('\t'))
21:08:19.686 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\t'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(I), modifiers: CTRL, phys_code: Some(I), raw_code: 31, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
```

What I'd suggest is using this:

```
   {key="phys:i", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
```

so that the key binding matches against the physical key event rather than the OS's mapped event.

Why did this change since the earlier build?

* The key assignments changed from defaulting to implicit `phys:` mapping to implicit `mapped:` mapping
* c96396bd2f99dfc1076e543e39ffa7e1f55cd171 fixed the opposite of this mapping, where ctrl-tab got remapped to `ctrl-i`.  I don't want to revert that change, because tab->i is more lossy and annoying than i->tab.  I don't feel great about either of these :-/

**Comment by wez** [comment]
I'll think a bit about how to resolve this more sanely: for now I'd suggest using the explicit `phys:` syntax!

**Comment by demiflat** [comment]
Thanks!

I can confirm that reverting c96396b fixes this problem for me.
Also using the "phys:I" workaround allows me to keep running on the main code base.

Thanks again!  I really appreciate your work on wezterm, it allows me to keep my gnome-terminal tab workflow as I start using sway as a window manager.

**Comment by SuperSandro2000** [comment]
I am on `wezterm 20220408-101518-b908e2dd` and have the following config snippet which also triggers with both key combos.

```lua
   keys = {
     {
       key = "phys:I",
       mods = "CTRL|SHIFT",
       action = wezterm.action({ ActivateTabRelative = -1 }),
     },
     {
       key = "phys:I",
       mods = "CTRL",
       action = wezterm.action({ ActivateTabRelative = 1 }),
     },
```

**Comment by gpanders** [comment]
I didn't see mention of the `enable_csi_u_key_encoding` option in this thread, but that seems to be relevant due to the reports of seeing `;5u` in the terminal.

It looks like WezTerm is incorrectly encoding both <kbd>C-I</kbd> as well as <kbd>C-Return</kbd>. WezTerm encodes these as `CSI 9 ; 5 u` and `CSI 109 ; 5 u`, respectively, meaning that <kbd>C-I</kbd> is interpreted as <kbd>C-Tab</kbd> and <kbd>C-Return</kbd> is interpreted as <kbd>C-M</kbd>. Of course, the whole point of CSI u encoding is that these combinations *aren't* ambiguous.

For reference, iTerm2 correctly encodes all of these keys:

* <kbd>C-I</kbd> = `CSI 105 ; 5 u`
* <kbd>C-M</kbd> = `CSI 109 ; 5 u`
* <kbd>C-Tab</kbd> = `CSI 9 ; 5 u`
* <kbd>C-Return</kbd> = `CSI 13 ; 5 u`

**Comment by wez** [comment]
This should be fixed now in `main` for **X11/Wayland systems**.  I'll revisit this on macOS when I'm next at my mac.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wez** [comment]
> When I run WezTerm on macOS, C-I and C-Tab _are_ correctly disambiguated, but C-Return is still encoded as C-M.

@gpanders: 3688055cedaec2adf62bcfd6975e54afa8381c31 seems to take care of this for me

**Comment by gpanders** [comment]
> > When I run WezTerm on macOS, C-I and C-Tab _are_ correctly disambiguated, but C-Return is still encoded as C-M.
> 
> @gpanders: [3688055](https://github.com/wez/wezterm/commit/3688055cedaec2adf62bcfd6975e54afa8381c31) seems to take care of this for me

Works for me too 👍

**Comment by demiflat** [comment]
Works for me too building main, version:
_wezterm --version
wezterm 20220415-072701-fdb34710_

Closing.

**Comment by demiflat** [comment]
Thanks!
