### ISSUE TITLE
Categories validation hint in desktop file

### ISSUE THREAD

**Issue by sio-funmatsu** [wez/wezterm#1852]
I ran ```desktop-file-validate``` command and received the following hint. Is it OK?

```shell
> desktop-file-validate wezterm/assets/wezterm.desktop 
wezterm/assets/wezterm.desktop: hint: value "System;TerminalEmulator;Utility;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
```

desktop categories reference
https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry

**Comment by wez** [comment]
Yeah, this is desirable and is what other terminal emulators also do
