### ISSUE TITLE
ssh_domain connect - colors not respected.

### ISSUE THREAD

**Issue by tycho-kirchner** [wez/wezterm#1861]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Apparently configured colors don't work when performing a `wezterm connect $HOST`. I put this snippet on the local `~/.config/wezterm/wezterm.lua`, but the colors do not change. When executing `wezterm ssh $HOST` everything is fine. 

~~~
colors = {
    foreground = "white",
    background = "black",
    scrollbar_thumb = "white",
}
~~~

Thanks
Tycho

### To Reproduce

see above.

### Configuration

see above.

### Expected Behavior

`wezterm connect $HOST` should respect color settings 🙂.

**Comment by wez** [comment]
See: https://github.com/wez/wezterm/issues/1268#issuecomment-951562027
