### ISSUE TITLE
`CTRL+SHIFT+X` does not call `ActivateCopyMode` on Windows by default

### ISSUE THREAD

**Issue by NikGovorov** [wez/wezterm#1863]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220410-183634-1d908457

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`CTRL+SHIFT+X` does not activate `Copy Mode` on Windows as is stated in the docs.

### To Reproduce

1. Open `WezTerm`
2. Press `CTRL+SHIFT+X`

### Configuration

```
local wezterm = require 'wezterm';
return {}
```

### Expected Behavior

WezTerm enters to `Copy Mode`.

### Logs

```
14:22:05.589 INFO wezterm_client::discovery::windows > published gui path as gui-sock-21556

14:22:05.613 WARN window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL

14:22:05.710 INFO wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GTX 1080/PCIe/SSE2 4.5.0 NVIDIA 512.15 is_context_loss_possible=true wezterm version: 20220410-183634-1d908457
```

### Anything else?

If I change the config to handle the key binding explicitly then it starts to work:
```
local wezterm = require 'wezterm';

return {
    keys = {
        {key="X", mods="CTRL|SHIFT", action="ActivateCopyMode"}
    }
}
```

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by NikGovorov** [comment]
Verified in main([20e019d](https://github.com/wez/wezterm/commit/20e019d2ed3a90794a2bb665c1ba2de7548ca2dd)).
