### ISSUE TITLE
`nf-mdi-contacts` icon does not render

### ISSUE THREAD

**Issue by NikGovorov** [wez/wezterm#1864]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220410-183634-1d908457

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`nf-mdi-contacts` icon does not render

### To Reproduce

1. Open WezTerm
2. Type in pwsh "`u{fbc9}" or in bash echo -e '\ufbc9'
![ScreenClip](https://user-images.githubusercontent.com/129254/162884660-d47b6509-0f95-4239-9300-b220d6f12072.png)

### Configuration

```
local wezterm = require 'wezterm';

return {}
```

### Expected Behavior

The icon should be rendered in the same way as all other font icons, for example `nf-mdi-contact_mail`

![ScreenClip](https://user-images.githubusercontent.com/129254/162884239-19b45c3d-c542-406d-9118-dec84e233b13.png)

### Logs

```
14:54:09.201 INFO wezterm_client::discovery::windows > published gui path as gui-sock-7392
14:54:09.231 WARN window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
14:54:09.421 INFO wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GTX 1080/PCIe/SSE2 4.5.0 NVIDIA 512.15 is_context_loss_possible=true wezterm version: 20220410-183634-1d908457
```

### Anything else?

The icon works well if I use it in fancy tabs.

**Comment by wez** [comment]
This is fixed now in `main`. The issue was that that particular glyph is using the unassigned range of codepoints, which is considered to be zero width.  It's a bit naughty of it to do that as there is potential for conflicting with future versions of unicode :-/

The fix should be available in a Windows nightly build within about an hour of this comment being posted.

**Comment by NikGovorov** [comment]
Verified with `wezterm 20220412-181441-4cf74e3d`
