### ISSUE TITLE
Scrollbar broken after fast output

### ISSUE THREAD

**Issue by tycho-kirchner** [wez/wezterm#1866]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hi. After fast output the scrollbar is consitently broken and does not recover.
Easily reproducible with
~~~
$ yes | head -99999
$ clear
$ yes | head -500
~~~
When mousewheel-scrolling up to the top after the second `yes` command the scrollbar remains far from top (see screenshot). Further it is not dragable at all :(

Thanks 
Tycho
![Screenshot_20220412_112436](https://user-images.githubusercontent.com/29805132/162927822-d93c4446-9677-4d46-b4c7-09a90c68147f.png)
 

### To Reproduce

See above.

### Configuration

enable_scroll_bar = true,

### Expected Behavior

The scrollbar should work or at least recover on reset.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
