### ISSUE TITLE
Keymapping for `CMD + .` does not work.

### ISSUE THREAD

**Issue by drmingdrmer** [wez/wezterm#1867]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Keymapping for `CMD + .` does not work.

### To Reproduce

Mapping `CMD + .` on my mac m1 produces nothing. I expect pressing `CMD + .` output string `dot`.

But `ALT + .` works well. Pressing `ALT + .` it output a string `dot`.

### Configuration

```
local wezterm = require 'wezterm';
return {
    keys = {
        {key=".", mods="CMD", action={SendString="dot"}}, 
        {key=".", mods="ALT", action={SendString="dot"}}, 
    }, 
}
```

### Expected Behavior

Pressing `CMD + .` output string `dot`.

**Comment by wez** [comment]
Please share what you see when you enable https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html and press that key combination

**Comment by drmingdrmer** [comment]
When I press `CMD+.`, the debug info is:

```
01:24:56.607  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\u{1b}'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: None }
01:24:56.607  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Escape mods=CTRL
01:24:56.607  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}", Escape CTRL
```

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by drmingdrmer** [comment]
Fix confirmed in the the latest main branch: 20e019d2ed3a90794a2bb665c1ba2de7548ca2dd

Thank you so much for your great work and the elaborate explanation!
