### ISSUE TITLE
pty examples fail on OSX Catalina

### ISSUE THREAD

**Issue by house-mouse** [wez/wezterm#187]
## Describe the bug

Running on MacOS Catalina, 10.15.3, the pty examples fail to output any information from whoami as follows:

% cargo run --example whoami
child status: ExitStatus { successful: true }
output: %           
                                                                                                                  
% cargo run --example whoami_async
child status: ExitStatus { successful: true }

## Environment (please complete the following information):

 - OS: MacOS Catalina, 10.15.3
 - Version: git commit fa86850a859357a197efcc0932a9e97d818cf980

## To Reproduce

Steps to reproduce the behavior.

git clone https://github.com/wez/wezterm.git
cd wezterm/pty
cargo run --example whoami
cargo run --example whoami_async

## Expected behavior

The expected output is the same output correctly seen on linux:
cargo run --example whoami_async
child status: ExitStatus { successful: true }
output: len=5 stark

cargo run --example whoami
child status: ExitStatus { successful: true }
output: stark\r\n

I suspect this may show up in more serious problems elsewhere?

**Comment by wez** [comment]
if you run `whoami` directly what does it output?
Can you apply `dtruss` to see what is happening to the example?
My primary macOS system hasn't been upgraded to Catalina yet so testing this directly will take me a little time.

Are you able to run the nightly wezterm build on that catalina system?  If so, then we know that the pty crate is basically working.

Another thing to try is adjusting the example to run a different command than `whoami` to see if this is somehow related to that particular command.

**Comment by house-mouse** [comment]
whoami works as expected on linux and OSX Catalina (Boy autocorrect is having a field day with this email — sorry for any weird autocorrects)


stark@Time ~ % whoami
stark
stark@Time ~ % /Applications/WezTerm.app/wezterm -V
wezterm 20200517-122836-92c201c6

wezterm 20200517-122836-92c201c6 works quite well… so… there’s that...


wezterm built from git b18e66968daba76d0deac032307b3913076a5a15 using “cargo build” fails trying to build freetype:

error: failed to run custom build command for `freetype v0.1.0 (/Users/stark/checkout/wezterm/deps/freetype)`

I’m not yet sure what that’s all about.


Changing ‘whoami’ to ‘ls’ does the same thing… it doesn’t seem to be grabbing the output properly.
Changing ‘whoami’ to ‘df’ seems to cause the examples to hang.  Perhaps because there’s enough data to fill a buffer somewhere?

Attached is the output of
sudo dtruss .//target/debug/examples/whoami 2>&1 | bzip2  > /tmp/whoami-dtruss-output.bz
(With ‘whoami’ back in as the executable)


Putting “df” back in and running dtruss, the last lines dtruss outputs before hanging are:
fork()		 = 99383 0
close_nocancel(0x9)		 = 0 0
close_nocancel(0x8)		 = 0 0
close_nocancel(0x5)		 = 0 0
close_nocancel(0x6)		 = 0 0
close_nocancel(0x7)		 = 0 0
close_nocancel(0x4)		 = 0 0
fcntl(0x3, 0x43, 0x0)		 = 4 0

I’m no dtruss expert, but it seems like this is somehow missing the important part, which I imagine is a call to read…

**Comment by wez** [comment]
I finally have a machine with Catalina to test this on.  It turns out to be a weirdness with the order waitpid vs. read.
Pushing updated examples momentarily!
