### ISSUE TITLE
Include list of default bindings in the docs

### ISSUE THREAD

**Issue by ghost** [wez/wezterm#1870]
Maybe I'm missing it, but I've been looking around the docs for a list of the default keys for like 5 minutes now and I'm coming up short. It'd be super convenient if I could just look at your guys' defaults, and only change what I want, rather than have to scroll through each section in the docs to find the defaults, or just remap everything all at once

**Comment by wez** [comment]
Hmm, how can we make it clearer?

<img width="252" alt="image" src="https://user-images.githubusercontent.com/117777/163099604-1c4a7356-f9be-4a93-aff4-0c94eb4f0d70.png">

links to:

https://wezfurlong.org/wezterm/config/default-keys.html
