### ISSUE TITLE
Allow configuring indexed colors in a color theme

### ISSUE THREAD

**Issue by chtenb** [wez/wezterm#1876]
**Is your feature request related to a problem? Please describe.**
Some applications use or allow using the extended colors, but they are currently not themable in a color scheme.
I would like to be able to switch colors schemes automatically based on if my system is in darkmode. It is already possible to switch color schemes by using

```lua
function scheme_for_appearance(appearance)
    if appearance:find("Dark") then
        return "Builtin Solarized Dark"
    else
        return "Builtin Solarized Light"
    end
end

wezterm.on("window-config-reloaded", function(window, pane)
    local overrides = window:get_config_overrides() or {}
    local appearance = window:get_appearance()
    local scheme = scheme_for_appearance(appearance)
    if overrides.color_scheme ~= scheme then
        overrides.color_scheme = scheme
        window:set_config_overrides(overrides)
    end
end)

```

However, if I want to customize some of the extended colors, they remain fixed.

**Describe the solution you'd like**
Allow settings indexed colors from the color scheme (from the extended 16-256 range)

**Describe alternatives you've considered**

**Additional context**
Personally I want to repurpose some of the rarely used extended ansi colors for use as background color for my git diffs and other such applications. I can configure a pager which uses some fixed indexed color. However, this indexed color should change once my terminal color scheme changes. I can't use dark background colors on a light color scheme because that is not readable.

There are other use cases as well, such as supporting [base16-shell](https://github.com/chriskempson/base16-shell).

**Comment by bew** [comment]
It is already possible to set a custom color for the indexed colors (16-255), search for `indexed` in https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
Example:
```lua
return {
  colors = {
    -- Arbitrary colors of the palette in the range from 16 to 255
    indexed = {[136] = "#af8700"},
  }
}
```

**Comment by chtenb** [comment]
@bew Thanks for your reply! That's right, but you can't set them from a [*color scheme*](https://wezfurlong.org/wezterm/config/appearance.html#defining-a-color-scheme-in-a-separate-file)

So I guess I can hack some hardcoded colors in the `wezterm.on("window-config-reloaded", function(window, pane)` handler I posted above, but the "nice" way of doing things would be to be able to tie these things to colorschemes and perhaps even distribute them as such.

**Comment by chtenb** [comment]
@bew I'm not even sure if that works (anymore?).

setting         

```
indexed = {[136] = "#ffffff"},
```

and printing the colors gives

![image](https://user-images.githubusercontent.com/1030961/163626046-28d45f3e-bfa0-4b97-8756-0ef1e6823024.png)

Is that a bug?

**Comment by chtenb** [comment]
Okay, apparently if I remove the 

```
wezterm.on("window-config-reloaded", function(window, pane)
    local overrides = window:get_config_overrides() or {}
    local appearance = window:get_appearance()
    local scheme = scheme_for_appearance(appearance)

    if overrides.color_scheme ~= scheme then
        overrides.color_scheme = scheme
        window:set_config_overrides(overrides)
    end
```

part from my config it works again. Apparently setting the color_scheme resets all the other color related config?

**Comment by wez** [comment]
`color_scheme` takes precedence over `colors`.

You should be able to set `indexed` in a color scheme file/table.

If you want to take an existing color scheme and override some aspect(s) of it, see the example at the bottom of: https://wezfurlong.org/wezterm/config/lua/wezterm/get_builtin_color_schemes.html

**Comment by chtenb** [comment]
>You should be able to set indexed in a color scheme file

Sweet, I fiddled a bit around and found that the following syntax indeed works.

```toml
[colors.indexed] 
52 = "#fbdada" # minus
88 = "#f6b6b6" # minus emph
22 = "#d6ffd6" # plus
28 = "#adffad" # plus emph
53 = "#feecf7" # purple
17 = "#e5dff6" # blue
23 = "#d8fdf6" # cyan
58 = "#f4ffe0" # yellow
```
