### ISSUE TITLE
Wezterm doesn't send C-[

### ISSUE THREAD

**Issue by gpanders** [wez/wezterm#1877]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220415-072701-fdb34710

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Pressing <kbd>C-[</kbd> (which should send Esc) doesn't send anything. The normal <kbd>Esc</kbd> key still works.

Bisected to e680cc848a58033684c9fb1294c5235a68fe1358.

### To Reproduce

Run `cat` and press <kbd>C-[</kbd>. Nothing is printed.

### Configuration

no config

### Expected Behavior

When running `cat` and pressing <kbd>C-[</kbd> you should see `^[` in the console.

### Logs

```
INFO   wezterm_gui::termwindow > OpenGL initialized! Apple M1 Pro 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220412-174137-e680cc84
```

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by gpanders** [comment]
Thanks for the quick response.

I can confirm that on `main` it does now correctly send the combination on the key up event (i.e. when I release the `[` key), but not when I first press the key. This gives it the feeling of being slightly "laggy" as there is a small but perceptible delay between the keypress and key release. It is also not possible to hold the key down and send the same sequence repeatedly (although granted, that's not something I would typically need to do with <kbd>C-[</kbd>).

Not sure if this is intended behavior or not, but just wanted to let you know.

**Comment by wez** [comment]
Ah!  Interesting observation.  I think I see a better way to resolve this: 47addfa53c3cc6b54550aace374c53aa2bffec0f

**Comment by gpanders** [comment]
That works great. Thanks!
