### ISSUE TITLE
TogglePaneZoomState causes a bunch of empty lines to appear

### ISSUE THREAD

**Issue by dnguyener** [wez/wezterm#1878]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When utilizing multiple panes, togglePaneZoomState causes a bunch of empty lines to appear above the prompt.  This happens when a large amount of text has been generated.

### To Reproduce

1.  Horizontal Split.  
1.  On the left window, generate a large amount of output.  In my case, I'm using dmesg.  
![image](https://user-images.githubusercontent.com/12126945/163664508-1584da7e-3bfa-4166-b95f-050cf335b55d.png)
1.  On the left window, togglePaneZoomState .   The pane is maximized but now there are a bunch of empty space above the prompt.  The prompt also moved up a line.
![image](https://user-images.githubusercontent.com/12126945/163664517-3bff6ab2-009a-490e-9dc4-1127ff3cee83.png)

### Configuration

no config. 

### Expected Behavior

I expect no empty space and the prompt to stay in the same position.

### Logs

23:03:40.103 INFO wezterm_client::discovery::windows > published gui path as gui-sock-6252
23:03:40.147 WARN window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
23:03:40.338 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 4.5.0 - Build 30.0.100.9955 is_context_loss_possible=true wezterm version: 20220408-101518-b908e2dd
23:24:00.603 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 4

**Comment by wez** [comment]
This isn't really related to pane zooming so much as it is to the general category of ConPTY resizing behavior being weird.
https://github.com/wez/wezterm/issues/1265#issuecomment-1083290957 has more background on this.  I'm going to close this issue in favor of that one.
