### ISSUE TITLE
Display the domain name in title

### ISSUE THREAD

**Issue by Junnplus** [wez/wezterm#1881]
**Is your feature request related to a problem? Please describe.**

I want to be able to display the domain name in the title, like follow:

![image](https://user-images.githubusercontent.com/8097526/163671271-0135080d-8b47-4aec-aa13-bb4cc0d743c6.png)

**Describe the solution you'd like**
~~A clear and concise description of what you want to happen.~~

Get `domain_name` from pane (`PaneInformation`).
```lua
wezterm.on('format-tab-title', function(tab)
    local pane = tab.active_pane
    local title = pane.title
    if pane.domain_name then
        title = title .. ' - (' .. pane.domain_name .. ')'
    end
    return title
end)
```

**Describe alternatives you've considered**
~~A clear and concise description of any alternative solutions or features you've considered.~~

**Additional context**
~~Add any other context or screenshots about the feature request here.~~

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Junnplus** [comment]
Thanks for the quick response! It works in nightly version now.

[N] ❯ wezterm-gui -V
wezterm-gui 20220416-110254-3ca45cf2
