### ISSUE TITLE
Expand nerd font icon to two columns if possible

### ISSUE THREAD

**Issue by dripware** [wez/wezterm#1884]
is it possible to make nerd font icons expand if the next column is a tab or whitespace? (similar to kitty terminal)

**Comment by wez** [comment]
Yeah, that's the default behavior:

![image](https://user-images.githubusercontent.com/117777/163720375-80a1b1dc-b45e-4643-b0f9-f8e4dbac5821.png)

https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html is a config option that affects this.

**Comment by dripware** [comment]
don't know how i missed it. thanks!
