### ISSUE TITLE
Add an option to treat Ambiguous width characters as fullwidth

### ISSUE THREAD

**Issue by kyanagi** [wez/wezterm#1888]
**Is your feature request related to a problem? Please describe.**

Wezterm can't display [Ambiguous width characters](http://www.unicode.org/reports/tr11/#Ambiguous) correctly with some fonts.

**Describe the solution you'd like**

Currently, Wezterm always treats "Ambiguous width characters" as halfwidth.
https://github.com/wez/wezterm/blob/main/termwiz/src/widechar_width.rs#L1500

But in Japanese or other Asian languages, these characters are sometimes used for full-width characters,
so Wezterm can't display these characters correctly.

Could you add an option to treat these characters as fullwidth, like Terminal.app and iTerm2 have?

**Additional context**

Install [Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP) and run Wezterm with it.

```
brew install font-noto-sans-cjk-jp
wezterm -n --config "font=require('wezterm').font('Noto Sans Mono CJK JP')"
```

Display 'WHITE STAR' (U+2606)

```
print "\xe2\x98\x86\xe2\x98\x86\xe2\x98\x86\xe2\x98\x86\xe2\x98\x86"
```

Wezterm

<img width="604" alt="スクリーンショット 2022-04-19 13 42 15" src="https://user-images.githubusercontent.com/181194/163924944-72c2c374-fda4-4875-972b-56132e685ff2.png">

Terminal.app ("Unicode East Asian Ambiguous characters are wide" is checked)

<img width="602" alt="スクリーンショット 2022-04-19 13 42 41" src="https://user-images.githubusercontent.com/181194/163924773-06a1a411-7e60-4c55-8aba-45844c2de708.png">

Preference of Terminal.app 

<img width="779" alt="スクリーンショット 2022-04-19 14 04 53" src="https://user-images.githubusercontent.com/181194/163924557-73a22369-c031-4850-b418-865a95bfcd3e.png">

**Comment by wez** [comment]
This should be fixed now in `main`: 

`.wezterm -n --config "font=wezterm.font('Noto Sans Mono CJK JP')" --config treat_east_asian_ambiguous_width_as_wide=true`

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by kyanagi** [comment]
I tried new settings and confirmed that ambiguous characters are shown as wide. Thank you very much.

**Comment by wez** [comment]
It may look weird, but it's not a wezterm bug.  Terminal.app behaves the same way!

What you're seeing is a consequence of the disagreement between wezterm and zsh on the width of those ambiguous width cells.

I made a note about this at the bottom of the docs for this new option: https://wezfurlong.org/wezterm/config/lua/config/treat_east_asian_ambiguous_width_as_wide.html

**Comment by kyanagi** [comment]
Sorry for my misunderstood.
I met the similar problem on Terminal.app/iTerm and there was no problem when I edit the characters on vim.
I appreciate your kind support.
