### ISSUE TITLE
Add exit_behavior = "CloseOnNormalExit"

### ISSUE THREAD

**Issue by tycho-kirchner** [wez/wezterm#1889]
Hi.

**Is your feature request related to a problem? Please describe.**
 I often cancel program execution with CTRL+C and exit the shell with CTRL+D afterwards. 
Since my `exit_behavior` is set to  `CloseOnCleanExit` I get the message 
~~~
Process "/bin/bash" in domain "local" didn't exit cleanly
Exited with code 130.
...
~~~
This is annoying as I already know, that the last program didn't exit cleanly. 

**Describe the solution you'd like**
Exit code 130 is extremely common, it would be nice to be able to ignore it, e.g. with an additional `exit_behaviour` `CloseOnNormalExit`. Optionally SIGTERM (exit code 143) may be considered here as well as some software kills itself with that signal when receiving CTRL+C.

**Describe alternatives you've considered**
`exit_behaviour` `Close` is not a nice alternative as in the past my shell (rarely) died  without me having a chance to view the output. So in principle I like that functionality.

**Additional context**
None

Thanks
Tycho

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/config/clean_exit_codes.html is what I came up with for this!

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by tycho-kirchner** [comment]
Thanks. Works perfectly. You may even want to consider making `clean_exit_codes = {130}` the default (like e.g. KDE konsole does), but of course that design decision is up to you 😉.

**Comment by wez** [comment]
> the default (like e.g. KDE konsole does),

I don't see a way to get KDE to automatically hold when the program exits uncleanly.  Are you sure that that is the default behavior?

**Comment by tycho-kirchner** [comment]
On konsole 20.12.3 a `kill -9 $$` keeps my window open 😉.

**Comment by wez** [comment]
Ah, that's a bit different: it's holding only when the program terminates due to a signal
