### ISSUE TITLE
High cpu usage and stuttering input in nightly 

### ISSUE THREAD

**Issue by tycho-kirchner** [wez/wezterm#1895]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220419-232436-924b63eb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hi. Current nightly (version see above) eats 60% of a single core and has stuttering input. The issue is not present in current latest release 20220408-101518-b908e2dd (I suspect a commit within the last week).
It seems to be not graphics related, as `LIBGL_ALWAYS_SOFTWARE=1 wezterm`  yields the same result.
Note that in virtualbox the idle usage is zero, however when holding a key the cpu usage also rises to 100%.

~~~
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
           Device-2: Sunplus Innovation Dell E5570 integrated webcam type: USB driver: uvcvideo 
           Display: x11 server: X.Org 1.20.11 driver: loaded: intel resolution: 1920x1200~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 20.3.5 
~~~

Thanks
Tycho

### To Reproduce

see above.

### Configuration

no config

### Expected Behavior

see above.

**Comment by wez** [comment]
I don't experience the same thing here.
Can you bisect to find the revision where this started to happen for you?

Please also try turning up debugging: `WEZTERM_LOG=trace wezterm 2> /tmp/wezterm.txt` and then attach the logs; they will likely be long and very verbose.

You mentioned virtualbox; are you running wezterm in a virtual machine?  Can you describe that setup?

**Comment by tycho-kirchner** [comment]
I can bisect (soon), do you provide a binary archive or is compilation from source necessary?
Logs are attached: [wezterm.txt](https://github.com/wez/wezterm/files/8522544/wezterm.txt)
The virtualbox setup is Debian 11 Xfce, no 3D acceleration on. However, I just checked the last regular release 20220408-101518-b908e2dd  in virtualbox and see no difference. Indeed running that release on my real host with
`LIBGL_ALWAYS_SOFTWARE=1 wezterm` results in the same stuttering as in nightly without that flag **but** after finishing typing the cpu quickly calms down.
So I conclude: 3D acceleration on Intel Skylake GT2 is broken in nightly. 
In below gif I just hold `d` pressed. It jumps.
![output](https://user-images.githubusercontent.com/29805132/164264115-c36228b1-ddfb-4fcd-a8de-bb70bbccc46e.gif)
.

**Comment by wez** [comment]
> I can bisect (soon), do you provide a binary archive or is compilation from source necessary?

There's no archive of nightly builds; you'll need to follow the [build from source](https://wezfurlong.org/wezterm/install/source.html) directions using the full git repo.

> Logs are attached: [wezterm.txt](https://github.com/wez/wezterm/files/8522544/wezterm.txt)

It appears as though wezterm was started and immediately exited; I was hoping to see the logs from the time that it was experiencing high CPU utilization!  Can you keep it running for long enough to gather that information?

> The virtualbox setup is Debian 11 Xfce, no 3D acceleration on. However, I just checked the last regular release 20220408-101518-b908e2dd in virtualbox and see no difference.

Do you mean that the last stable release is also stuttering with high cpu?

> Indeed running that release on my real host with
> `LIBGL_ALWAYS_SOFTWARE=1 wezterm` results in the same stuttering as in nightly without that flag **but** after finishing typing the cpu quickly calms down.
> So I conclude: 3D acceleration on Intel Skylake GT2 is broken in nightly.

There haven't been any changes relating directly to OpenGL in wezterm since the last release.

When using software rendering, the CPU needs to work hard to produce the terminal display so it is reasonable for the CPU utilization to be high when rendering (https://github.com/wez/wezterm/issues/1735).  When running in a VM, CPU is harder for the host to schedule than if it was running on bare metal, so it sounds "OK" to have the characteristics you described.

The thing I'd like to get to the bottom of is the idle CPU being high; that doesn't sound right.

**Comment by tycho-kirchner** [comment]
Cheers. Things are getting interesting. The bisect ran over night and the
relevant commit is
7977fe7ee15a3fea188bfc272c027b8b63d04e5a config: watch the directory containing the wezterm.lua too

I can now reliably reproduce the bug (also in Debian 11 VM), but it is a bit difficult to setup. 
**All** of the following must be true:
* Install [DockbarX](https://github.com/M7S/dockbarx) from master branch (has some old python dependencies, could become difficult)
* Let it run without controlling terminal, so errors are logged to ~/.xsession-errors (launch via Alt+F2)
* install the openbox window manager and use it: `setsid openbox --replace &`
* place wezterms config file in the home directory and run it: `wezterm --config-file  ~/weztermtest.lua`

As soon as wezterm started, ~/.xsession-errors is flooded with messages 
`(dockx:97712): Wnck-WARNING **: 13:33:41.889: Unhandled action type _OB_WM_ACTION_UNDECORATE`.

wezterm goes wild with actions seen in attached [strace_log.txt](https://github.com/wez/wezterm/files/8530585/strace_log.txt)
I think something like the following happens:
 wezterm somehow triggers that "openbox undecorate action", whereupon DockbarX writes that to ~/.xsession-errors. As wezterm monitors that directory it wakes up and triggers that undecorate action again. And again ...

**Comment by tycho-kirchner** [comment]
> Speculatively fixed now in `main`; let me know how it goes!

Yep. It's fixed. Thanks 👍️.



> so the issue is that the home directory is being watched, and any time something writes to the home directory we get a config reload and stutter because that is relatively expensive!

I think that's half of the issue. In this case the reloading of wezterm's config file triggered itself an error written to  ~/.xsession-errors, whereupon wezterm reloads the config file again, resulting in an endless reload-loop. So in simple terms: wezterm monitores a file which it changes itself from within the handler whereupon the handler has to run over and over again. Kind of funny, in my own project [shournal](https://github.com/tycho-kirchner/shournal) (which may be useful for you too) I had to be __very__ pedantic for such cases 😉.
