### ISSUE TITLE
crash upon window maximize

### ISSUE THREAD

**Issue by kalikaneko** [wez/wezterm#1897]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I've observed this a couple of times (cannot reproduce deterministically).

When clicking on the top window row to maximize, the terminal crashes with this message:

```
thread 'main' panicked at 'phys_row called with negative row -6232', term/src/screen.rs:409:9
```

I'll try to get the full backtrace.

### To Reproduce

Cannot reproduce consistently.

### Configuration

no config

### Expected Behavior

maximize window

### Logs

20:07:03.357  INFO   wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) UHD Graphics (CML GT2) 4.6 (Compatibility Profile) Mesa 21.3.5 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2d

**Comment by wez** [comment]
Please do try to capture that backtrace; without it, or a consistent repro, this will be difficult to nail down!

**Comment by kalikaneko** [comment]
sure! I've only seen this every few days, so hope to catch it soon-ish.

**Comment by kalikaneko** [comment]
I've been stressing what I thought was the trigger for the last week and did not happen again. Will close for now and reopen with a backtrace if it happens again.
