### ISSUE TITLE
Panic on the spawn of new windows

### ISSUE THREAD

**Issue by PedroHLC** [wez/wezterm#19]
## Is it a build problem?
No, builds runs fine!

## Did something not work the way you expected?
When a try to spawn a new window with the hotkey `Super-N`, process crashes.

### What did you try?
Happens in any time `Super-N` is pressed. No other problem or activity is related.
Recording: https://drive.google.com/open?id=1yNzQzsdtTg_Cx72HIuhMSNvLYxQFWzUb

I'm using archlinux, i3, compton, nvidia dkms drivers, zen kernel. Everything is up to date.

### What did you expect to happen?
Spawn a new window!

### What actually happened?
It crashes with log: https://gist.github.com/PedroHLC/3921865cf9df583c25cd0c93df982e31

**Comment by wez** [comment]
I pushed a commit with @Lompik's suggested fix; please let me know if that works for you!

**Comment by PedroHLC** [comment]
Working perfect!
