### ISSUE TITLE
Cannot input { and } in wezterm [Italian layout]

### ISSUE THREAD

**Issue by FraSharp** [wez/wezterm#1901]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220420-094356-f9c48551

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When i try to input '{' and '}' _(left and right curly brackets)_ in wezterm it just doesn't work, this is what i get instead of the expected output: left curly bracket - `<ffffffff>`, right curly bracket - nothing.

i tried on multiple keybaord layouts and it seems to happen on italian layout only.

QUICK NOTE: curly brackets work as expected in any other terminal

i also tried to set `send_composed_key_when_right_alt_is_pressed = true` (i use right ALT) but it still didn't work

### To Reproduce

to reproduce this you can just select IT (italian) layout and do this combination: `SHIFT ALT è` (è is the key on the right of the p)

### Configuration

```lua
local wezterm = require 'wezterm';

return {
         debug_key_events = true,
         color_scheme = "Fairyfloss",
         font = wezterm.font("JetBrains Mono"),
         font_size = 13,
         default_cwd = "~/",
         send_composed_key_when_left_alt_is_pressed=true,
         send_composed_key_when_right_alt_is_pressed=true,
 }
```

### Expected Behavior

expected behavior: `SHIFT ALT è` printing `{` and `SHIFT ALT +` printing `}`

actual behavior: `SHIFT ALT è` printing `<ffffffff>` and `SHIFT ALT +` printing nothing

### Logs

```
wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Char('é'), modifiers: SHIFT | ALT | RIGHT_ALT, phys_code: Some(LeftBracket), raw_code: 33, repeat_count: 1, key_is_down: true, handled: Handled(false) }

wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('é'), modifiers: SHIFT | ALT | RIGHT_ALT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Char('é'), modifiers: SHIFT | ALT | RIGHT_ALT, phys_code: Some(LeftBracket), raw_code: 33, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }

wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('é') mods=SHIFT | ALT

wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}é", Char('é') SHIFT | ALT

wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('é'), modifiers: SHIFT, phys_code: Some(LeftBracket), raw_code: 33, repeat_count: 1, key_is_down: false, handled: Handled(false) }

wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('é'), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('é'), modifiers: SHIFT, phys_code: Some(LeftBracket), raw_code: 33, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }

wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('é') mods=SHIFT
```

### Anything else?

after pressing `SHIFT ALT è`

<img width="768" alt="Screen Shot 2022-04-21 at 11 01 51" src="https://user-images.githubusercontent.com/60934657/164419826-d366965b-6031-405a-80e3-9b64ec25f56d.png">

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by FraSharp** [comment]
> This should be fixed now in `main`.

Yep, i just tried and it works now, thank you
