### ISSUE TITLE
Shift-Tab not working in macOS

### ISSUE THREAD

**Issue by g6ai** [wez/wezterm#1902]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220421-080024-55174056

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have binded Shift-Tab to me custom settings:
https://github.com/g6ai/dotfiles/blob/2b9eed707d765ad634748155d8f9192a6aabc429/.chezmoitemplates/zim.zsh#L114-L116

But after recent nightly upgrade, Shift-Tab does nothing.

### Configuration

no config (I have tried no config and the problem persists)

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by g6ai** [comment]
The fix works well. Thanks Wez, you are a legend :)

**Comment by kahnclusions** [comment]
@wez I have a similar issue, Ctrl+Tab works for cycling right through tabs, but Ctrl+Shift+Tab doesn't work for cycling left. I see the same `\u{19}` in the output...

My mappings:

```lua
keys = {
  { key = "Tab", mods = "CTRL", action=wezterm.action{ActivateTabRelative=1}},
  { key = "Tab", mods = "SHIFT|CTRL", action=wezterm.action{ActivateTabRelative=-1}},
}
```

Debug key logging:
```
15:07:12.769  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Char('\t'), modifiers: SHIFT | CTRL, phys_code: Some(Tab), raw_code: 48, repeat_count: 1, key_is_down: false, handled: Handled(false) } 
15:07:12.770  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\u{19}'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('\t'), modifiers: SHIFT | CTRL, phys_code: Some(Tab), raw_code: 48, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
15:07:12.770  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('\u{19}') mods=NONE
```

I'm running

```
❯ wezterm --version
wezterm 20220609-200947-af815a2
```

**Comment by wez** [comment]
@kahnclusions: thanks for reporting; this should now also be fixed in main and available in a build in about an hour
