### ISSUE TITLE
Support alpha channel in tab_bar background config

### ISSUE THREAD

**Issue by codehz** [wez/wezterm#1903]
**Is your feature request related to a problem? Please describe.**
It seems only window_background_opacity option can be used to control opacity, all alpha channel in colors is got ignored, and I want make tab bar transparent.

**Describe the solution you'd like**
Make color config support rgba color

**Describe alternatives you've considered**
Or add tab_bar_background_opacity ?

**Additional context**
<img width="601" alt="image" src="https://user-images.githubusercontent.com/13158903/164564370-bf131348-72f8-4823-95d0-d3296cfc40cc.png">
I'm trying to make window has fully acrylic backdrop, but seems the tab bar don't like this.

**Comment by wez** [comment]
I think you might want: https://wezfurlong.org/wezterm/config/appearance.html#text-background-opacity

**Comment by codehz** [comment]
> I think you might want: https://wezfurlong.org/wezterm/config/appearance.html#text-background-opacity

It works, but not perfect. the problem is if I set it to zero
<img width="240" alt="image" src="https://user-images.githubusercontent.com/13158903/164580736-38df3382-83d7-4f53-bf3a-7d4ccacad0db.png">
it also removes ALL text background regardless active or not, and it also effect terminal content background which I don't want to change, I only want make tab_bar semi-transparent. 
since color config already support rgba format, why not just use that.

**Comment by wez** [comment]
Nightly builds now support setting rgba for all colors in the `colors` section, as well as for colors set by wezterm.format.
