### ISSUE TITLE
`CTRL` mod is ignored in some contexts with `allow_win32_input_mode` enabled

### ISSUE THREAD

**Issue by NikGovorov** [wez/wezterm#1904]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220421-183827-26500c67

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`CTRL` mod is ignored in some contexts with `allow_win32_input_mode` enabled

### To Reproduce

1. Open `nvim` or `wsl` in `wezterm`
2. Press `Ctrl+d` it sends `d` to an app (deletes in `nvim` and type `d` in `wsl` )

### Configuration

```
local wezterm = require 'wezterm';
return {debug_key_events = true, allow_win32_input_mode = true}
```

### Expected Behavior

It should send `Ctrl+d` in case of `nvim` by default it should move one page down 

### Logs

13:47:32.398 WARN window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
13:48:09.050 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
13:48:15.444 INFO wezterm_gui::termwindow::keyevent > send to pane UP key=LeftControl mods=NONE
13:48:15.444 INFO wezterm_gui::termwindow::keyevent > Encoded input as "\u{1b}[17;29;0;0;0;1_"
13:48:15.863 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 17, scan_code: 29, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:48:15.863 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftControl, modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 17, scan_code: 29, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:48:15.863 INFO wezterm_gui::termwindow::keyevent > send to pane DOWN key=LeftControl mods=CTRL
13:48:15.864 INFO wezterm_gui::termwindow::keyevent > Encoded input as "\u{1b}[17;29;0;1;8;1_"
13:48:16.105 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT | CTRL, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:48:16.105 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftShift, modifiers: SHIFT | CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT | CTRL, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:48:16.105 INFO wezterm_gui::termwindow::keyevent > send to pane DOWN key=LeftShift mods=SHIFT | CTRL
13:48:16.105 INFO wezterm_gui::termwindow::keyevent > Encoded input as "\u{1b}[16;42;0;1;24;1_"
13:48:16.275 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(L), modifiers: SHIFT | CTRL, phys_code: Some(L), raw_code: 76, scan_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:48:16.275 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('L'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(L), modifiers: SHIFT | CTRL, phys_code: Some(L), raw_code: 76, scan_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:48:16.275 INFO wezterm_gui::termwindow::keyevent > Char('L') CTRL -> perform ShowDebugOverlay

### Anything else?

The bug mentioned in another closed issue https://github.com/wez/wezterm/issues/1509#issuecomment-1007895196

Windows Terminal or Alacritty work fine in these scenarios

**Comment by NikGovorov** [comment]
Is there currently a way to set a setting only for a specific tab or a window? I usually have FAR opened on a tab and it's the only app where I need `allow_win32_input_mode`?

**Comment by NikGovorov** [comment]
> Is there currently a way to set a setting only for a specific tab or a window? I usually have FAR opened on a tab and it's the only app where I need `allow_win32_input_mode`?

https://wezfurlong.org/wezterm/config/files.html#configuration-overrides

**Comment by wez** [comment]
Would you mind opening an issue for this in the microsoft/terminal repo and linking back to this one?
I think we need @DHowett and the other MS folks to weigh in and/or track this!

**Comment by NikGovorov** [comment]
Windows Terminal and Alacritty both work fine in FAR Manager, WSL and neovim.

**Comment by NikGovorov** [comment]
Sorry maybe I've misunderstood you, could you please elaborate on why you would like me to create the issue in  microsoft/terminal repo?

**Comment by wez** [comment]
We need assistance from the ConPTY folks to understand what is happening, because as far as I understand it, we're sending the correctly formed information to ConPTY but it isn't behaving as we expect.

I don't use FAR manager and don't use win32 input mode enough (really, at all) for this to be top of my list of things to investigate.  You have a more direct interest in seeing this resolved more quickly than either myself or the ConPTY folks so you filing the issue over there will act as a bridge between us!

**Comment by Event-Horizon-Labs** [comment]
@wez https://github.com/microsoft/terminal/issues/13134
Issue in microsoft/terminal

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by NikGovorov** [comment]
Verified with `20220522-065018-1f554886`.
