### ISSUE TITLE
[MacOS] When wezterm is focused the menu bar at the top does not open the secondary bar when bartender is installed.

### ISSUE THREAD

**Issue by cocoonkid** [wez/wezterm#1909]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

[MacOS] When wezterm is focused the menu bar at the top does not open the secondary bar when bartender is installed.

This issue does not appear with any other application so this might be a  general thing to fix.

### To Reproduce

Install Bartender.
Install wezterm.

Click top menubar to make secondary bar appear.

Does not work.

Works with every other application.

### Configuration

no needed. Not  a conf issue.

### Expected Behavior

Secondary menubar appears.

**Comment by wez** [comment]
I would suggest contacting the bartender folks to find out why it doesn't work with wezterm; I cannot see into what closed source software is doing so I have no idea what bartender doesn't like about wezterm. If you can have them comment here with technical details then we stand a chance of understanding and resolving this.
