### ISSUE TITLE
Restore last search term and settings on search overlay activation.

### ISSUE THREAD

**Issue by tycho-kirchner** [wez/wezterm#1912]
**Is your feature request related to a problem? Please describe.**
Hi. I often find myself in filtering the scrollback for specific search terms, then relaunching the same command, and searching for the same terms again. Doing so I have to  re-type the same search term again, which is a little annoying.

**Describe the solution you'd like**
Restart with the same search term (and case sensitivity) as before when activating the search overlay.

**Describe alternatives you've considered**
I have considered [Saved Searches](https://wezfurlong.org/wezterm/scrollback.html#configuring-saved-searches) but in my case the search terms change too frequently in order to make a dedicated keyboard shortcut effective.
**Additional context**
None.

**Comment by wez** [comment]
This is a bit challenging to do today, because the overlay and its state is discarded when it is closed, and there isn't currently a way to stash overlay state separately.  Needs a bit of thought.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by tycho-kirchner** [comment]
Thanks, this works great now. However, when the search overlay is activated, hitting ENTER in another tab has no effect now (did not bisect though). Can you reproduce?

**Comment by wez** [comment]
Ah, that's an unintended consequence of some changes with the search overlay; the overlay activates a new layer in the input map and that redefines Enter to an action in the search overlay.  I'll get that sorted out!

**Comment by wez** [comment]
The enter issue is fixed in main!

**Comment by Funami580** [comment]
> I think it's most useful to restore the last search-term if nothing is selected.
> ...
> When the search overlay is already activated and the user hits CTRL+SHIFT+F again, the search term could be replaced by the currently selected word.

You can achieve that with a custom function:
```lua
{key="f", mods="CTRL|SHIFT", action=wezterm.action_callback(function(window, pane)
  local selection = window:get_selection_text_for_pane(pane)
  window:perform_action(wezterm.action{Search={CaseInSensitiveString=selection}}, pane)
end)}
```

**Comment by tycho-kirchner** [comment]
Thanks @Funami580: that's good enough for me. Is there any way to use the the previous search sensitivity?.
@wez : you may want to consider this as default option or otherwise document @Funami580 ' in the "search action docs"
https://wezfurlong.org/wezterm/config/lua/keyassignment/Search.html

Thanks
Tycho

**Comment by wez** [comment]
Changes in `main`:
* `CTRL-SHIFT-F` now defaults to the new `CurrentSelectionOrEmptyString` mode, which will take the first line of the currently selected text and use that to search.  This is always case-sensitive.
* If the search pattern is empty, then the saved search *for that tab* will be used
