### ISSUE TITLE
Add Ubuntu 22.04 builds 

### ISSUE THREAD

**Issue by gimbles** [wez/wezterm#1915]
Ubuntu 22.04 just got released! However, the 20.04 deb packages fail to install on it.

Just a request to add a 22.04 deb package too, I'd be glad to send a PR if pointed into the right direction

Thanks! =)

**Comment by wez** [comment]
Please send a PR; it should be pretty straight forward:

1. make a copy of this line, but adjust it to 22.04, assuming that they already published a docker image for it:
https://github.com/wez/wezterm/blob/3dfe75362ae74729e8b02f8a248df536236d5252/ci/generate-workflows.py#L721
2. Then run that script; it will generate some workflow files that you'll need to add to the PR
3. make a copy of this line, but adjust it for the new version:
https://github.com/wez/wezterm/blob/3dfe75362ae74729e8b02f8a248df536236d5252/ci/subst-release-info.py#L31
4. make a copy of this line, but adjust for the new version:
https://github.com/wez/wezterm/blob/3dfe75362ae74729e8b02f8a248df536236d5252/docs/install/linux.markdown?plain=1#L46

Add all the changed/generated files to the commit and submit as a PR!

**Comment by gimbles** [comment]
Fantastic, thanks. Will be done in a few hours.

**Comment by gimbles** [comment]
Submitted the PR, #1918 🌿

**Comment by wez** [comment]
Thanks! The docs and download links for the nightly builds should update within ~1 hour!
