### ISSUE TITLE
Readline keybinding for undo (CTRL + SHIFT + - ) is replaced by DecreaseFontSize ( CTRL + - )

### ISSUE THREAD

**Issue by huibosa** [wez/wezterm#1919]
### What Operating System(s) are you seeing this problem on?

Windows, Linux X11

### WezTerm version

20220421-183827-26500c67

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Can't use (CTRL + SHIFT + - ) to undo changes in command line editing and emacs. When 3 keys are pressed the font size is changed instead.

Bug is found both in Windows and Linux x11.

### Configuration

```
local wezterm = require 'wezterm'

local wsl_domains = wezterm.default_wsl_domains()

for _, dom in ipairs(wsl_domains) do
  if dom.name == "WSL:Ubuntu" then
    dom.default_cwd = "/home/huibosa"
  end
end

local window_padding = {
  left = "0.5cell",
  right = "0.5cell",
  top = "0.2cell",
  bottom = "0cell",
}

local mouse_bindings = {
  -- Change the default click behavior so that it only selects
  -- text and doesn't open hyperlinks
  {
    event={Up={streak=1, button="Left"}},
    mods="NONE",
    action=wezterm.action{CompleteSelection="PrimarySelection"},
  },
  -- and make CTRL-Click open hyperlinks
  {
    event={Up={streak=1, button="Left"}},
    mods="CTRL",
    action="OpenLinkAtMouseCursor",
  },
}

local colors = {
  foreground = "#d3c6aa",
  background = "#2b3339",
  selection_bg = "#3B5360",
  scrollbar_thumb = "#222222",
  ansi = {"#4b565c", "#e67e80", "#a7c080", "#dbbc7f", "#7fbbb3", "#d699b6", "#83c092", "#d3c6aa"},
  brights = {"#4b565c", "#e67e80", "#a7c080", "#dbbc7f", "#7fbbb3", "#d699b6", "#83c092", "#d3c6aa"},
}

return {
  wsl_domains = wsl_domains,
  default_domain = "WSL:Ubuntu",

  window_padding = window_padding,
  -- window_decorations = "NONE",

  mouse_bindings = mouse_bindings,

  force_reverse_video_cursor = true,
  enable_tab_bar = false,

  colors = colors,
  font = wezterm.font("Source Code Pro"),
  font_size = 12.6,
}
```

**Comment by wez** [comment]
This is not a bug; that's one of the default key assignments. You can find them all on https://wezfurlong.org/wezterm/config/default-keys.html

You may disable that binding by assigning that key combination to [DefaultDefaultAssignment](https://wezfurlong.org/wezterm/config/lua/keyassignment/DisableDefaultAssignment.html)

**Comment by MuhammedZakir** [comment]
But in the doc, only `ctrl + -` is mentioned. There is no mention of `ctrl + shift + -`. `ctrl + shift + =` also have the same behavior - it inreases font size - even though only `ctrl + =` should do that. It looks like a bug, or maybe you just forget to add these in the doc?
