### ISSUE TITLE
Wezterm is not particularly fast

### ISSUE THREAD

**Issue by aslpavel** [wez/wezterm#192]
## Describe the bug
I'm playing with a program that renders images to terminal using half-block characters `﻿▀ - \u{2580}`. It produces quite a lot of output.  And wezterm is very slow in comparison to other terminals.

## Environment (please complete the following information):

 - OS: macOS
 - Frontend:  I dont know how to check (default)
 - Version: wezterm 20200517-122836-92c201c6 (download prebuild package from github)

## To Reproduce
Here is the file that contains log of the output of my program. It renders mandelbrot set multiple times using half-block symbols. [mandelbrot.log.gz](https://github.com/wez/wezterm/files/4673345/mandelbrot.log.gz)
```
# wezterm
$ time gzcat ~/mandelbrot.log.gz
real 0m24.821s
user 0m0.011s
sys  0m0.058s

# kitty
time gzcat ~/mandelbrot.log.gz
real 0m0.186s
user 0m0.010s
sys  0m0.053s

# alacritty
$ time gzcat ~/mandelbrot.log.gz
real 0m0.147s
user 0m0.011s
sys  0m0.047s

# iterm2
time gzcat ~/mandelbrot.log.gz
real 0m5.613s
user 0m0.013s
sys  0m0.073s
```

## Configuration
```
enable_scroll_bar = true
font_size = 9.5
font_antialias = "Subpixel"
font_hinting = "Full"

default_cursor_style = "SteadyBar"

[[font.font]]
family = "Iosevka"

[[font.font]]
family = "Symbols Nerd Font"

[colors]
foreground = "#ebdbb2"
background = "#282828"
cursor_bg = "#ebdbb2"
cursor_fg = "#ebdbb2"
cursor_border = "#ebdbb2"
scrollbar_thumb = "#504945"
ansi = ["#282828", "#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#ebdbb2"]
brights = ["#7c6f64", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c","#fbf1c7"]

[colors.tab_bar]
background = "#1d2021"
[colors.tab_bar.active_tab]
bg_color = "#076678"
fg_color = "#ebdbb2"
[colors.tab_bar.inactive_tab]
bg_color = "#458588"
fg_color = "#3c3836"
[colors.tab_bar.inactive_tab_hover]
bg_color = "#83a598"
fg_color = "#3c3836"
```

## Expected behavior
It should be fast :)

**Comment by wez** [comment]
wezterm has configurable throttles to manage the rate at which
data is processed to help balance between making progress and
allowing CTRL-C/S to be recognizable within a reasonable interactive
latency.

This sort of scenario will saturate the throttle.
You can configure the throttle using the config file:

```lua
return {
  -- Constrains the rate at which output from a child command is
  -- processed and applied to the terminal model.
  -- This acts as a brake in the case of a command spewing a
  -- ton of output and allows for the UI to remain responsive
  -- so that you can hit CTRL-C to interrupt it if desired.
  -- The default value is 400,000 bytes/s.
  ratelimit_output_bytes_per_second = 400000,
}
```

**Comment by aslpavel** [comment]
I see, it was indeed the case. I think the default value might be too low, and might create wrong impression about the speed of the terminal. I understand that this use cases might be very marginal but for example `mpv -vo tct` do not work properly with such low limit.

**Comment by wez** [comment]
Would you mind experimenting to find a value that works with `mpv` and sharing it here?
I'm open to adjusting the defaults, but I need feedback from people such as yourself that use things differently from me!

**Comment by aslpavel** [comment]
Sure, I think it starts being reasonably fast and work without dropping frames at about 10_000_000.

**Comment by aslpavel** [comment]
This might also be important when sending images via any type of protocol be it a Sixel, Kitty, iTerm, since this object are usually large.
