### ISSUE TITLE
Mouse cursor changes on wezterm

### ISSUE THREAD

**Issue by HideOnLie** [wez/wezterm#1924]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220425-132756-9f6d2db1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Desktop : awesomewm
linux : ArchLinux

Wezterm doesn't use the system mouse cursor,  instead it changes it to this:
![image](https://user-images.githubusercontent.com/51672711/165421207-8936b824-505b-4064-8e60-08963fdefed9.png)

### Configuration

no configuration

### Expected Behavior

Mouse cursor should not change.

**Comment by wez** [comment]
Please take a look at: https://wezfurlong.org/wezterm/faq.html#i-use-x11-or-wayland-and-my-mouse-cursor-theme-doesnt-seem-to-work

**Comment by HideOnLie** [comment]
> Please take a look at: https://wezfurlong.org/wezterm/faq.html#i-use-x11-or-wayland-and-my-mouse-cursor-theme-doesnt-seem-to-work

Thank !!! It working now.
Forgive me for only looking some the previous part in document .I didn't see this section. Sorry to disturb you～
