### ISSUE TITLE
wezterm-nightly-bin AUR package does not automatically update

### ISSUE THREAD

**Issue by Anomalocaridid** [wez/wezterm#1933]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220405-085405-b2ba7383

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In order to update `wezterm-nightly-bin`, I need to manually update it rather than having it update normally.

### To Reproduce

- Install `wezterm-nightly-bin` using an AUR helper
- Wait for the next nightly build
- Update using the AUR helper normally
- `wezterm-nightly-bin` has not been updated
- Update it by reinstalling it with the AUR helper
- It should now be updated to the latest version

### Configuration

no config

### Expected Behavior

I expected that `wezterm-nightly-bin` would be updated like any other AUR package on my system.

### Logs

N/A

### Anything else?

I use `paru` as my AUR helper, but the same thing occurs with `yay`.

**Comment by TheGentleChainsaw** [comment]
@wez was indeed the maintainer for `wezterm-nightly-bin` on the AUR, but he has no real reason to keep bumping the version number anymore now that there's an official `wezterm` package [in Arch's community repo](https://archlinux.org/packages/community/x86_64/wezterm/). (Which he's already mentioned in #1447, so this should probably be closed as a duplicate.)

**Comment by Anomalocaridid** [comment]
Understandable

**Comment by wez** [comment]
The nightly-bin package builds whatever is the nightly when it is built.
Nightly builds are not officially released packages so there are no official version numbers to track.
I don't use Arch so I don't know if it is possible to make it play nicer with the its packaging ecosystem to make it such that you can track nightly. Right now I believe that you need to uninstall and then reinstall to get it to pick up a more recently binary.

I will accept PRs that improve this if someone is motivated, but I don't have the bandwidth (or desire!) to become proficient in arch and drive this.
