### ISSUE TITLE
French macos keyboard ~ and | does not work out of box

### ISSUE THREAD

**Issue by kakawait** [wez/wezterm#1934]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Out of box isn't possible to write (print?) `|` (aka `option ⌥ + shift + l`) or `~` (aka `option ⌥ + n`) (and maybe any chars that rely on `option ⌥`) on macos - french keyboard

### To Reproduce

1. Having a macos with french (I don't know if is mandatory but is my setup) keyboard/layout
2. brew install wezterm
3. run wezterm
4. try to write/print `~` or `|`

### Configuration

no config

### Expected Behavior

working out of box, `~` and `|` is really common char used on terminal :)

### Logs

1. `~` log

```
21:31:24.006  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('n'), modifiers: ALT | LEFT_ALT, phys_code: Some(N), raw_code: 45, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:31:24.006  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('n'), modifiers: ALT | LEFT_ALT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Char('n'), modifiers: ALT | LEFT_ALT, phys_code: Some(N), raw_code: 45, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:31:24.006  INFO   wezterm_gui::termwindow::keyevent     > Char('n') ALT | LEFT_ALT -> send to pane Char('n') ALT
21:31:24.006  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}n", Char('n') ALT
21:31:24.014  INFO   wezterm_gui::termwindow               > Ding! (this is the bell) in pane 0
21:31:24.055  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('n'), modifiers: ALT | LEFT_ALT, phys_code: Some(N), raw_code: 45, repeat_count: 1, key_is_down: false, handled: Handled(false) }
```

2. `|` log

```
21:32:22.201  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('L'), modifiers: SHIFT | ALT | LEFT_ALT, phys_code: Some(L), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:32:22.202  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('L'), modifiers: ALT | LEFT_ALT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Char('L'), modifiers: SHIFT | ALT | LEFT_ALT, phys_code: Some(L), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:32:22.202  INFO   wezterm_gui::termwindow::keyevent     > Char('L') ALT | LEFT_ALT -> send to pane Char('L') ALT
21:32:22.202  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}L", Char('L') ALT
21:32:22.260  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('L'), modifiers: SHIFT | ALT | LEFT_ALT, phys_code: Some(L), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }
21:32:22.260  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('L'), modifiers: ALT | LEFT_ALT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('L'), modifiers: SHIFT | ALT | LEFT_ALT, phys_code: Some(L), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:32:22.260  INFO   wezterm_gui::termwindow::keyevent     > Char('L') ALT | LEFT_ALT -> send to pane Char('L') ALT
```

**Comment by wez** [comment]
Can you try a more recent nightly build? There have been some fixes for macOS keyboard handling

**Comment by kakawait** [comment]
I've tried 

```
# never installed nightly until now
brew install --cask wez/wezterm/wezterm-nightly
```

and so `wezterm 20220427-144728-efcc4b48`

But same result

**Comment by wez** [comment]
I tried this just now and Right-Option-Shift-L produces `|`.
Left-Option is treated as a plain ALT modifier by default, so you need to use Right-Option to get the composition effect.
Take a look at https://wezfurlong.org/wezterm/config/keyboard-concepts.html#macos-left-and-right-option-key for more information about this and the config options that affect it

**Comment by wez** [comment]
Can you try that and let me know how it goes?

**Comment by kakawait** [comment]
> I tried this just now and Right-Option-Shift-L produces |.

Is working (I'll check to change the _left and right option_ because is totally not obvious for me to us the right option haha)

**Comment by wez** [comment]
The reason for this is because the Alt modifier is widely used for shortcuts or is otherwise meaningful in terminal programs, so having one of the alt keys work that way while having the other work like AltGr to produce composed characters gives users the ability to use both functions without requiring them to change the configuration.

**Comment by wez** [comment]
I'm going to close this as it is working as documented!
