### ISSUE TITLE
Customize the minimum size of the scroll bar

### ISSUE THREAD

**Issue by yar999** [wez/wezterm#1936]
**Is your feature request related to a problem? Please describe.**
Tail -f Displays Web access logs. As the log increases, the scroll bar becomes very small and it is difficult to click the scroll bar

**Describe the solution you'd like**
Provides a setting for setting the minimum scrollbar size

**Describe alternatives you've considered**
My current solution is to set the scrollbar color to a color that contrasts with the background color.

```
local scheme = wezterm.get_builtin_color_schemes()["Ubuntu"]
scheme.scrollbar_thumb = "#ffffff"
return {
    ...
    color_schemes = {
        ["Ubuntu"] = scheme,
    },
    color_scheme = "Ubuntu",
    ...
}
```

**Additional context**
As shown in the screenshot:
Too much content
The Windows Terminal scrollbar is easy to click on
The Wezterm scroll bar becomes very small
![scrollbar](https://user-images.githubusercontent.com/7338900/165941147-e739ff27-aa10-45e3-8e69-5f8636a3df72.jpg)

**Comment by wez** [comment]
Can you try the nightly build?  The scroll thumb min size minimum is now 1/2 the cell height

**Comment by yar999** [comment]
I have installed the latest [nightly build](https://github.com/wez/wezterm/releases/download/nightly/WezTerm-nightly-setup.exe) , But the effect is as small as before, is there any special setting needed?

```
❯ wezterm - version
wezterm 20220509-215718-156b0ae4
```

**Comment by wez** [comment]
I pushed a change that adds a new option: https://wezfurlong.org/wezterm/config/lua/config/min_scroll_bar_height.html

You may wish to set `min_scroll_bar_height = "1cell"` for example.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by yar999** [comment]
Thank you very much. I set `min_scroll_bar_height = 2cell`, and now it's easy to click the scroll bar.
@wez
