### ISSUE TITLE
fzf preview for images

### ISSUE THREAD

**Issue by ianqsong** [wez/wezterm#1951]
I was trying `wezterm` with `fzf`, but it doesn't seem to work to preview images.    
**Is your feature request related to a problem? Please describe.**
fzf preview like `ls *.png | fzf --preview 'wezterm imgcat {}' ` not working.

**Describe the solution you'd like**
`wezterm` has excellent support for images and I hope it could work with fzf preview. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by wez** [comment]
it looks like that is an open issue in fzf itself; from what I can gather from skimming that issue, fzf is interpreting the output to compose the TUI display, and it doesn't know how to pass through the iterm2 image protocol that is used by `wezterm imgcat` or by iterm's own `imgcat`:

*  https://github.com/junegunn/fzf/issues/1102

**Comment by ianqsong** [comment]
Thanks for the quick reply.
Actually another question was how to use `wezterm imgcat` to show images in a new wezterm window, because instead of `fzf preview` it has optional key binding to invoke external program. I was trying the following but got no luck.
```sh
fzf --bind 'tab:execute(wezterm imgcat {})'
fzf --bind 'tab:execute(wezterm start script.sh {})' # script.sh has just one line: wezterm imgcat $*
```

**Comment by wez** [comment]
You might want to try having it run something like `wezterm --config exit_behavior="Hold" start wezterm imgcat {}` so that the window doesn't close as soon as the image is done showing.

**Comment by wez** [comment]
Or perhaps this:

```
fzf --bind 'tab:execute(wezterm cli spawn --new-window --cwd . -- bash -c "wezterm imgcat {}; sleep 86400")'
```
