### ISSUE TITLE
mac OPT/META key not recognised 

### ISSUE THREAD

**Issue by xiangpeng2008** [wez/wezterm#1958]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220507-145508-b365cdbb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I config my `cat .config/wezterm/wezterm.lua` this way

```
local wezterm = require 'wezterm';

return {
  leader = { key="t", mods="META", timeout_milliseconds=1000 },
  keys = {
    {key="|", mods="LEADER|SHIFT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    -- Send "CTRL-A" to the terminal when pressing CTRL-A, CTRL-A
    --{key="a", mods="LEADER|CTRL", action=wezterm.action{SendString="\x01"}},
  }
}
```
But when I press `opt+t >> shift+\`, the pane doesn't split.
I tested that if I replace META by CTRL in lua file, then `ctrl+t >> shift+\` works

### Configuration
```
local wezterm = require 'wezterm';

return {
  leader = { key="t", mods="META", timeout_milliseconds=1000 },
  keys = {
    {key="|", mods="LEADER|SHIFT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    -- Send "CTRL-A" to the terminal when pressing CTRL-A, CTRL-A
    --{key="a", mods="LEADER|CTRL", action=wezterm.action{SendString="\x01"}},
  }
}
```
### Expected Behavior

split pane

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by xiangpeng2008** [comment]
The fix will be reflected in brew too right ?

https://wezfurlong.org/wezterm/install/macos.html
```
$ brew upgrade --cask wezterm-nightly --no-quarantine --greedy-latest
```

**Comment by wez** [comment]
Yes, but you need to wait for the binaries to build which takes about an hour after the commit was pushed.
