### ISSUE TITLE
Custom Emoji Font Not Rendering

### ISSUE THREAD

**Issue by donutmonger** [wez/wezterm#1959]
### What Operating System(s) are you seeing this problem on?

Linux X11, macOS

### WezTerm version

wezterm 20220507-145508-b365cdbb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I cannot configure a custom emoji/unicode font with the `font_with_fallback` config. It always falls back to using the builtin "Noto Color Emoji" to render emoji.

### To Reproduce

Install the [Noto Emoji](https://fonts.google.com/noto/specimen/Noto+Emoji) font (or any other emoji font) and set it as a fallback font in your config. 

### Configuration

```lua
  font = wezterm.font_with_fallback({"MonoLisa", "Noto Emoji"}),
```

### Expected Behavior

After setting the fallback font to "Noto Emoji" I expected to see the monochrome emoji (as is rendered on Google Fonts) instead of the default "Noto Color Emoji" glyphs.

### Anything else?

The `ls-fonts` command shows that my second fallback font is "Noto Emoji":
```console
$  wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /home/chris/.local/share/fonts/MonoLisa-Regular.ttf, FontConfig
  "MonoLisa",

  -- /home/chris/.local/share/fonts/NotoEmoji-Regular.ttf, FontConfig
  "Noto Emoji",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

But, it will always choose "Noto Color Emoji" when rendering emoji. I'd expect it to realize that "Noto Emoji" can render these emoji before it falls back to the colored one.

```console
$ wezterm ls-fonts --text 🎈🎺🎉🎊
LeftToRight
 0 🎈    \u{1f388}    x_adv=136 cells=2  glyph=380  wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
 4 🎺    \u{1f3ba}    x_adv=136 cells=2  glyph=425  wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
 8 🎉    \u{1f389}    x_adv=136 cells=2  glyph=381  wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
12 🎊    \u{1f38a}    x_adv=136 cells=2  glyph=382  wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
```

**Comment by jpoppe** [comment]
I have the same issue, it is not only for `Noto Emoju`  also does not work for Twemoji, Segoe UI Emoji, etc. which work fine with the `foot` terminal, it also seems if a local (Symbol, etc.) font has the same the built-in will used, maybe this is related.

I could not find an option to disable `built-in` fallback fonts, that would make debugging a lot easier.

**Comment by wez** [comment]
I've pushed a commit that I think will help with this:

```
; ./target/debug/wezterm --config-file /tmp/1959.lua ls-fonts --text "🎈🎺🎉🎊"
LeftToRight
 0 🎈    \u{1f388}    x_adv=20 cells=2  glyph=u1F388,297  wezterm.font("Noto Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-emoji/NotoEmoji-Regular.ttf, FontConfig
 4 🎺    \u{1f3ba}    x_adv=20 cells=2  glyph=u1F3BA,335  wezterm.font("Noto Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-emoji/NotoEmoji-Regular.ttf, FontConfig
 8 🎉    \u{1f389}    x_adv=20 cells=2  glyph=u1F389,298  wezterm.font("Noto Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-emoji/NotoEmoji-Regular.ttf, FontConfig
12 🎊    \u{1f38a}    x_adv=20 cells=2  glyph=u1F38A,299  wezterm.font("Noto Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-emoji/NotoEmoji-Regular.ttf, FontConfig
```

There's an explanation about what was happening in the commit message: 50ead11ccb67daadfa112fbd321a0120c16cae0a

I want to note that I couldn't reproduce the problem with `Twemoji` as that font is a color font and worked just fine for me.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by donutmonger** [comment]
:partying_face: It works now, thank you so much!
