### ISSUE TITLE
Hide or disable tabs

### ISSUE THREAD

**Issue by huuson235** [wez/wezterm#1965]
Hi I'm using mainly tmux so the tab feature is not necessary so do we have any options to hide tab or disable tab feature?

**Comment by wez** [comment]
A couple of options:
* https://wezfurlong.org/wezterm/config/lua/config/hide_tab_bar_if_only_one_tab.html
* https://wezfurlong.org/wezterm/config/lua/config/enable_tab_bar.html

**Comment by huuson235** [comment]
That's awesome, thank you so much
