### ISSUE TITLE
incomplete wezterm cli list on wezterm server

### ISSUE THREAD

**Issue by xiangpeng2008** [wez/wezterm#1966]
### What Operating System(s) are you seeing this problem on?

Windows 10 ssh to centos 7

### WezTerm version

empty
![image](https://user-images.githubusercontent.com/15676035/167351320-91dec0b5-e20c-46b4-a5b1-85e7486a67c4.png)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`wezterm cli list` doesn't show all panes opened on wezterm server.

### To Reproduce

Download wezterm from https://wezfurlong.org/wezterm/install/windows.html
![image](https://user-images.githubusercontent.com/15676035/167350879-4a045c36-5ea7-4e13-8e33-c1d4c035d8ba.png)

Build wezterm for Centos 7

From windows 10, ssh to centos 7 ( https://wezfurlong.org/wezterm/ssh.html )
![image](https://user-images.githubusercontent.com/15676035/167350992-11af8557-55b8-4167-834b-f3f0287627c9.png)

open 2 tabs and some panes
![image](https://user-images.githubusercontent.com/15676035/167351057-b389f582-3fb5-464a-b2a5-19aaa736640c.png)

`wezterm cli list` shows only 1 record, which is not expected.

### Configuration

```
local wezterm = require 'wezterm';

return {
    window_decorations = "NONE",

    ssh_domains = {{
        -- This name identifies the domain
        name = "sgzls147c",
        -- The address to connect to
        remote_address = "sgzls147c",
        -- The username to use on the remote host
        username = "zhangxia"
    }},
    leader = {
        key = "a",
        mods = "CTRL",
        timeout_milliseconds = 1000
    },

    -- timeout_milliseconds defaults to 1000 and can be omitted
    leader = {
        key = "t",
        mods = "META",
        timeout_milliseconds = 1000
    },
    keys = {{
        key = "|",
        mods = "LEADER|SHIFT",
        action = wezterm.action {
            SplitHorizontal = {
                domain = "CurrentPaneDomain"
            }
        }
    }, {
        key = "H",
        mods = "LEADER",
        action = wezterm.action {
            AdjustPaneSize = {"Left", 5}
        }
    }, {
        key = "J",
        mods = "LEADER",
        action = wezterm.action {
            AdjustPaneSize = {"Down", 5}
        }
    }, {
        key = "K",
        mods = "LEADER",
        action = wezterm.action {
            AdjustPaneSize = {"Up", 5}
        }
    }, {
        key = "L",
        mods = "LEADER",
        action = wezterm.action {
            AdjustPaneSize = {"Right", 5}
        }
    }, {
        key = "h",
        mods = "LEADER",
        action = wezterm.action {
            AdjustPaneSize = {"Left", 1}
        }
    }, {
        key = "j",
        mods = "LEADER",
        action = wezterm.action {
            AdjustPaneSize = {"Down", 1}
        }
    }, {
        key = "k",
        mods = "LEADER",
        action = wezterm.action {
            AdjustPaneSize = {"Up", 1}
        }
    }, {
        key = "l",
        mods = "LEADER",
        action = wezterm.action {
            AdjustPaneSize = {"Right", 1}
        }
    }, {
        key = "_",
        mods = "LEADER|SHIFT",
        action = wezterm.action {
            SplitVertical = {
                domain = "CurrentPaneDomain"
            }
        }
    }, {
        key = "w",
        mods = "CTRL",
        action = wezterm.action {
            CloseCurrentPane = {
                confirm = true
            }
        }
    }}

}
```

### Expected Behavior

It should show multiple records for each pane of each tab

**Comment by wez** [comment]
`wezterm ssh host` doesn't talk to the remote multiplexer server; it establishes an ad-hoc ssh session.  When you run `wezterm cli list` from inside a pane created by `wezterm ssh`, `wezterm cli` is talking to the mux server and reporting what it sees there, not what is visible in `wezterm ssh`.

I think you can resolve this by using `wezterm connect sgzls147c` instead of `wezterm ssh sgzls147c`.

That will use your `ssh_domain` configuration to connect to the mux server on the remote host instead of making an ad-hoc ssh connection to the host.

**Comment by xiangpeng2008** [comment]
I see

`wezterm connect sgzls147c` works.
![image](https://user-images.githubusercontent.com/15676035/167359012-09d31169-4de7-4ca7-b36b-e3099a3bf144.png)
