### ISSUE TITLE
When more than one wezterm window is spawned from the same GUI instance, closing one window closes all of them with error

### ISSUE THREAD

**Issue by xpufx** [wez/wezterm#1974]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220509-073852-74e1cdcb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

OpenSUSE tumbleweed.   Closing one window closes all children of the same GUI instance with the following error.

> 10:35:55.201  ERROR  wezterm_gui             > X(Window(ValueError { response_type: 0, error_code: 3, sequence: 312, bad_value: 100663299, minor_opcode: 0, major_opcode: 4, pad: 1 }), Some("x::DestroyWindow")); terminating

### To Reproduce

Start more than one wezterm window via command line (wezterm) or using icons.  It does NOT happen when "always-new-process" is specified.

### Configuration

Tested without wezterm.lua. Same result.

### Logs

```
10:37:37.022  INFO   wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 22.0.3 is_context_loss_possible=false wezterm version: 20220509-073852-74e1cdcb
10:37:40.914  INFO   wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 22.0.3 is_context_loss_possible=false wezterm version: 20220509-073852-74e1cdcb
10:37:45.444  ERROR  wezterm_gui             > X(Window(ValueError { response_type: 0, error_code: 3, sequence: 329, bad_value: 100663305, minor_opcode: 0, major_opcode: 4, pad: 1 }), Some("x::DestroyWindow")); terminating

```

**Comment by starmatt** [comment]
I can confirm this happens to me as well.

I'm on archlinux running a KDE Plasma wayland session.    
wezterm version: `20220509-073852-74e1cdcb`

**Comment by xpufx** [comment]
Fix works for me. Thanks!
