### ISSUE TITLE
jump to another pane with keyboard easily

### ISSUE THREAD

**Issue by xiangpeng2008** [wez/wezterm#1975]
**Is your feature request related to a problem? Please describe.**

I need to just to different pane a lot, but I don't see easy way to do so with `wezterm` without mouse.

**Describe the solution you'd like**

I may have some key combination to show a number [0-9] or alphabet letter [a-z] on each of pane, then I could press corresponding key to jump to that pane.

**Additional context**

Tmux supports this currently: when I press come shortcuts, it will show number on each pane for a few seconds, and if I press for example "1" before those numbers disappears, then I will jump to pane "1".
![image](https://user-images.githubusercontent.com/15676035/167795330-591ae391-bb4f-41e6-88fb-372c89a93d85.png)

**Comment by xpufx** [comment]
https://wezfurlong.org/wezterm/config/default-keys.html?highlight=shortcuts#default-shortcut--key-binding-assignments

You're probably aware of this but just in case you're not, the default key binding for switching panes (CTRL+SHIFT + ARROW keys) does not require the mouse. The arrow keys are not particularly efficient but they can be rebound of course.

**Comment by wez** [comment]
Note that https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivatePaneByIndex.html will let you jump to a pane given its index in its containing binary tree.  I think what's missing is the ability see that index and then activate it.

**Comment by wez** [comment]
5bf736bd2186d6c41a24703db4cfbe8a600cc383 has a new `PaneSelect` key assignment that has this function.

It's not 100% complete; there's more config/styling to come, but it is functional.

When `PaneSelect` is active, labels are generated for the panes based on an alphabet that you supply (the default is to reuse your `quick_select_alphabet`).

The mode will remain active until you select a pane or press escape.

```lua
local wezterm = require 'wezterm'

return {
   -- 36 is the default, but you can choose a different size
   pane_select_font_size=36

   keys={
     -- Show the selector, using the quick_select_alphabet
     {key="o", mods="CTRL",
      action=wezterm.action{PaneSelect={}}
     },
     -- Show the selector, using your own alphabet
     {key="p", mods="CTRL",
      action=wezterm.action{PaneSelect={alphabet="0123456789"}}
     },
   }
}
```

![image](https://user-images.githubusercontent.com/117777/169853597-33914578-e664-4450-852a-a14369d589d0.png)

**Comment by wez** [comment]
You can now set a mode parameter that allows swapping the active pane with the selected pane: https://github.com/wez/wezterm/issues/1842#issuecomment-1136760787

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/keyassignment/PaneSelect.html
