### ISSUE TITLE
Can I get a Ctrl-g in the Launcher?

### ISSUE THREAD

**Issue by Lenbok** [wez/wezterm#1977]
**Describe the solution you'd like**

Finger habit for this emacs-user is to have Ctrl-g cancel/close out of things. Many parts of wezterm already have this bound (e.g. search mode and copy mode). However, the Launcher requires Escape to close, and if the fuzzy searching is enabled, it even sees Ctrl-g as `G`.

Please Ctrl-g when in the Launcher close the launcher.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Lenbok** [comment]
Works when in the main part of the launcher, but not when in the middle of fuzzy searching.

**Comment by wez** [comment]
fixed in 3018a8f32e81a2bc3d6e17b08fb1f9f5743a9a89

**Comment by Lenbok** [comment]
Sweet, looks good, thanks!!

**Comment by dagadbm** [comment]
Is this something that can be disabled?

I use Ctrl-g followed by another chord to invoke fzf to get commits/tags etc.

I tries to go to the default key maps but ctrl-g was not there

**Comment by wez** [comment]
@dagadbm please file a separate issue describing your situation in detail

**Comment by dagadbm** [comment]
Sorry for stealing your time in such a rude manner.

In the mean time I found the problem. It is this zsh-vi-mode that binds everything like crazy.

I uninstalled, and it works.

I wanted to comment sooner but I couldn't find the issue  😅
