### ISSUE TITLE
Working directory not preserved when opened from Nemo file manager

### ISSUE THREAD

**Issue by mariodon** [wez/wezterm#1982]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220512-090239-64921bf8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When wezterm is launched from file manager context menu, working directory is not set to path in Nemo.

### To Reproduce

1. Change default terminal used by file manager.
`gsettings set org.cinnamon.desktop.default-applications.terminal exec wezterm`
2. Navigate anywhere that is not `default_cwd`.
3. Launch wezterm from "Open in Terminal" context menu.

### Configuration

No config

### Expected Behavior

Wezterm launches with working directory corresponding to path in file manager.

### Logs

Nothing relevant

### Anything else?

If default terminal is set to Alacritty or konsole, working directory is properly set.
I noticed that when spawning a new wezterm window without explictly setting `--cwd` from any terminals, working directory is also not preserved. I believe Nemo launches terminals without arguments as well. This may or may not be relevant.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/config/default_cwd.html explains how the current working directory is determined.

I think you want to use something like : `gsettings set org.cinnamon.desktop.default-applications.terminal exec wezterm --cwd .` if you want it to spawn into the current directory.

**Comment by mariodon** [comment]
After some digging, I found that Nemo sets the working directory when launching the default terminal ([src](https://github.com/linuxmint/nemo/blob/214131ed02c66ba18d873e34ec9b3d50c5c6988d/src/nemo-window-menus.c#L1297)). Extra arguments can not be used.

Alacritty uses the working directory from the parent process unless overridden by [config](https://github.com/alacritty/alacritty/blob/5c51d528ea8ded63b127a4f17ee6136653db09b9/alacritty.yml#L441), while wezterm defaults to home directory if `default_cwd` is not set. That explains why the working directory is preserved in Alacritty and not in wezterm.

Should we match the behavior of Alacritty (and potentially other terminals in terms of using the working directory of the parent process)?

**Comment by wez** [comment]
> Should we match the behavior of Alacritty (and potentially other terminals in terms of using the working directory of the parent process)?

No; wezterm has well-defined and consistent (especially across platform) semantics for how processes are spawned and their working directory.

What I'd suggest is for you to deploy a shell script wrapper that runs `wezterm --cwd .` to workaround that limitation of Nemo, then configure Nemo to run that shell script.

**Comment by mariodon** [comment]
Thanks for your help.

**Comment by AdsonCicilioti** [comment]
> Thanks for your help.

I've just create a `wezter_nemo` executable with the content:
```shell
#!/bin/sh

wezterm start --cwd "$PWD"
```

Put the file on an PATH dir. This workaround solves this Wezterm limitation.

**Comment by wez** [comment]
Note that wezterm's .deb and .rpm packages ship with `/usr/bin/open-wezterm-here` which is essentially that script that you can use in situations like this
