### ISSUE TITLE
Clipboard hook support like tmux

### ISSUE THREAD

**Issue by kohnish** [wez/wezterm#1984]
Tmux supports clipboard hook something like this. Which set action when clipboard copy event happens. 

```
set-hook -g 'pane-set-clipboard' "run-shell '(tmux show-buffer | wl-x11-pb-copy)'"
```

It is especially useful for osc52 yank on vim where it's not compiled with clipboard support with something like this. (if wezterm supports osc52 like tmux does)

```
autocmd TextYankPost * call system("printf $'\\e]52;c;%s\\a' \"$(base64 <<(</dev/stdin))\" >> /dev/tty", v:event.regcontents)
```

**Comment by wez** [comment]
What are you trying to do exactly? OSC 52 populates the clipboard already

**Comment by kohnish** [comment]
I'm trying to trigger these two commands on osc 52 event.
```
    echo -n "$stdin" | wl-copy
    echo -n "$stdin" | wl-copy -p
```

But nothing happens. This is the example command which works on tmux.  

printf $'\e]52;c;%s\a' "$(base64 <<('test_str\ntest_str2'))" >> /dev/tty

**Comment by kohnish** [comment]
Sorry, I was assuming that shift-insert works by default. This solved the issue. 
```
{key = "Insert", mods = "SHIFT", action=wezterm.action{PasteFrom = "Clipboard"}},
```
