### ISSUE TITLE
show-buffer support like tmux

### ISSUE THREAD

**Issue by kohnish** [wez/wezterm#1985]
Tmux has support for printing selected text to stdout. 

It is useful for piping to text editor and get the real key bind with something like this.  

`tmux show-buffer | vim -`  
  
It'd be awesome to map to ActivateCopyMode or something with like editor command option.

**Comment by wez** [comment]
Take a look at:
* https://wezfurlong.org/wezterm/config/lua/pane/get_lines_as_text.html
* https://wezfurlong.org/wezterm/config/lua/pane/get_logical_lines_as_text.html

and the example here: https://wezfurlong.org/wezterm/config/lua/wezterm/on.html#custom-events

**Comment by kohnish** [comment]
Thank you for the documentation. 
I copied the example, but nothing seems to happen. Maybe it's my setup issue. I'll try to debug.   

But is there a chance that SpawnCommandInNewWindow could support specifying stdin? (and even stdout, stderr)

**Comment by kohnish** [comment]
Example started work when I replaced the function with get_logical_lines_as_text.
However, I can't seem to open the command in the same pane.  

I wanted to replace the pager with vim, similar to scrollback_pager option in kitty terminal.

It'd be super nice if I could just do something like this the callback.
```
pane:perform_action({SpawnCommand={args={"vim", "-"}, stdin=pane:get_logical_lines_as_text()})
```

**Comment by kohnish** [comment]
SpawnCommandInNewTab was good enough, as it closes the whole tab by default. Thank you. 🙏🏻
