### ISSUE TITLE
Pane: get foreground process id

### ISSUE THREAD

**Issue by Funami580** [wez/wezterm#1987]
**Is your feature request related to a problem? Please describe.**
I’d like to kill the current foreground process via `kill -9 <pid>` using a shortcut/action.
But there is no way to get the foreground process id.

**Describe the solution you'd like**
A variation of [get_foreground_process_name](https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html), e.g. `get_foreground_process_id`.

**Describe alternatives you've considered**
I’m not sure, if there are any good alternatives.

**Comment by wez** [comment]
You may now use [pane:get_foreground_process_info](https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_info.html) to retrieve the [LocalProcessInfo](https://wezfurlong.org/wezterm/config/lua/LocalProcessInfo.html) for the foreground process.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Funami580** [comment]
Works like a charm, thanks!
