### ISSUE TITLE
Quickselect, multi-line and line anchors

### ISSUE THREAD

**Issue by tcbtcb** [wez/wezterm#2008]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am trying to match to a regex in quick_select_patterns in my config. In particular i'm trying to match only when a string begins with a string, so using the ^ anchor. When I add ^ it's interpreted as a literal ^, not a 'starts with' regex. Escaping it as I would try nomrally \^ throws a regex compile error (which is helpful, thanks). 

I guess I'm wondering how the config is passed to the quickselect code, which includes in its extant config a bunch of regex's far more complex and well escaped than one that starts with ^. 

### To Reproduce

Put a single string in the quick_select_patters, match to it, put a ^ in front of it. 

### Configuration

I have reproduced with a wezterm.lua that only contained the match patterns. 

### Expected Behavior

A more compete set of available regex tools

### Anything else?

Love the terminal. I'm trying to use it to match to kubernetes pods in our installs that begin with a known string. Which will make me look really cool.

**Comment by wez** [comment]
The set of patterns is combined as an alternation, so if you have `foo` and `bar` as quick select patterns, the regex `(foo|bar)` is constructed by literally concatenating the pattern strings together; there's no quoting or escaping applied on top of what you specify.

That alternation is then matched against logical lines in the scrollback to identify matches.

The regex syntax is described here: https://docs.rs/regex/latest/regex/#syntax

There's nothing that should prevent the `^` character from matching the start of text, but given that individual logical lines are the subject text, what you perceive as the start of the line might be a wrapped line and not actually be at the start of the logical line from where it came.

Can you provide some more concrete details on what you tried and and what didn't work out?  Right now this issue is rather abstract!

**Comment by tcbtcb** [comment]
Hey - thanks for the super quick response. I understand better what's happening I think with the regex's that are the defaults, how they are being parsed. And it looks to me like the 'perl syntax' regex's (i.e. \w or \s) are supposed to be supported by the rust crate. I'm still getting the same behavior. 

To see what I'm talking about, maybe try 

touch foo whelp-foo whelp-foo-whelp

in a dir and then add just `foo` as a pattern match. That works exactly as I would expect. Then try `foo$`which I would expect to match foo and whelp-foo, but does not. 

I'm probably missing something really silly here, so if nobody else has a problem obviously it's not a huge deal. I'll keep poking at it.

Thanks again!

**Comment by wez** [comment]
I'm still not clear exactly what you're trying: please be more explicit!

**Comment by MuhammedZakir** [comment]
You can use `\b`. E.g. `\\bfoo\\b`. Other anchors such as `^`, `$`, `\A`, etc don't work. It seems like word-boundary-anchors work, but line-boundary-anchors don't?

> I'm still not clear exactly what you're trying: please be more explicit!

1. In shell: `printf "foo\nfoobar\n"
2. If pattern `foo` is used, then both `foo` and `foobar` will be matched.
3. But, he wants a way to match only `foo` (shouldn't match `foobar`). However, patterns like `^foo`, `foo$`, `^foo$`, etc. don't work (i.e. doesn't match only `foo`).

**Comment by wez** [comment]
I've pushed a commit that enables multi-line matching by default, and that cleans up trailing blanks from the strings that are used as the subject text for the regex.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by tcbtcb** [comment]
Excellent! I'm watching the CI build for MacOs right now and will give it try. 

I'm not a rust coder but if I can ever pitch in on doco or low hanging fruit, I'll try to find some useful way to contribute.

**Comment by tcbtcb** [comment]
Took me a little while to get the build chain on my M1 Mac but it works like a charm.

Thanks again!
