### ISSUE TITLE
font_with_fallback: error converting Lua table to Rust Type

### ISSUE THREAD

**Issue by JeanMertz** [wez/wezterm#2012]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220519-224534-39bb8b3f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

It appears defining the font weight as an integer is no longer supported. I suspect it's related to https://github.com/wez/wezterm/commit/f587cac145868320937a3cd28c426126d83c0257:

```
        [string "/Users/jean/.config/wezterm/wezterm.lua"]:77: in main chunk
caused by: error converting Lua table to Rust Type (Error processing
LuaFontAttributes::weight: Cannot convert `I64` to `FontWeight`.
{
    "family": "Operator Mono Ssm Lig",
    "weight": 325,
})
```

Specifically, I can see Serde's `visit_i64` was replaced by a pattern match on `Value::U64`, so that _appears_ to be the cause of this problem?

### Configuration

```lua
local fonts = {}
fonts["Operator Mono SSm Light"]         = { family = "Operator Mono Ssm Lig", weight = 275 }
fonts["Operator Mono SSm Light Italic"]  = { family = "Operator Mono Ssm Lig", weight = 275, italic = true }
fonts["Operator Mono SSm Book"]          = { family = "Operator Mono Ssm Lig", weight = 325 }
fonts["Operator Mono SSm Book Italic"]   = { family = "Operator Mono Ssm Lig", weight = 325, italic = true }
fonts["Operator Mono SSm Medium"]        = { family = "Operator Mono Ssm Lig", weight = "DemiLight" }
fonts["Operator Mono SSm Medium Italic"] = { family = "Operator Mono Ssm Lig", weight = "DemiLight", italic = true }
fonts["Operator Mono SSm Bold"]          = { family = "Operator Mono Ssm Lig", weight = "Regular" }
fonts["Operator Mono SSm Bold Italic"]   = { family = "Operator Mono Ssm Lig", weight = "Regular", italic = true }

-- A helper function for my fallback fonts
function Font_with_fallback(name)
  local names = {
    fonts[name],
    { family = "Apple Color Emoji" },
    { family = "Apple Symbols" },
    { family = "JetBrainsMono Nerd Font Mono" },
    { family = "JetBrains Mono" },
    { family = "SF Mono" },
    { family = "San Francisco" },
    { family = "sans-serif" },
  }

  return wezterm.font_with_fallback(names)
end
```

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
