### ISSUE TITLE
Crashes with native wayland and display scaling enabled on Sway

### ISSUE THREAD

**Issue by mariodon** [wez/wezterm#2028]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220523-230118-a5162765

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Setting `enable_wayland = true` in the config and starting Wezterm causes it to crash instantly on Sway.

### To Reproduce

Launch wezterm

### Configuration

```
local wezterm = require 'wezterm';
return {
	enable_wayland = true,
}
```

### Expected Behavior

Wezterm launches

### Logs

```
21:19:44.921  INFO   wezterm_gui::termwindow > OpenGL initialized! AMD RENOIR (LLVM 13.0.1, DRM 3.44, 5.17.9-arch1-1) 4.6 (Compatibility Profile) Mesa 22.1.0 is_context_loss_possible=false wezterm version: 20220523-230118-a5162765
21:19:44.985  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 36, cols: 69 }) because window_state is MAXIMIZED
xdg_surface@22: error 3: xdg_surface has never been configured
21:19:45.032  ERROR  wezterm_gui                     > error during event_q.dispatch protocol_error=Some(ProtocolError { code: 3, object_id: 22, object_interface: "xdg_surface", message: "" }): Protocol error (os error 71); terminating
```

### Anything else?

This issue does not occur with latest release (20220408-101518-b908e2dd).

**Comment by wez** [comment]
Sounds like: https://github.com/wez/wezterm/issues/1727#issuecomment-1133908225

**Comment by mariodon** [comment]
Looks like the same issue. A build without the mentioned [commit](https://github.com/wez/wezterm/commit/f72207e7f0770cd91e2f33f6361411360fad86e1) works for me. I couldn't reproduce the original issue on Gnome wayland though.

**Comment by wez** [comment]
8f222d9559820b2e63f72a3a9a492a2be2d420ef seems to resolve this for me!

**Comment by mariodon** [comment]
Also works for me. Thank you!
