### ISSUE TITLE
It renders `!=` into `=/=` instead of `!=`

### ISSUE THREAD

**Issue by tempegarit** [wez/wezterm#2029]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I write `!=` in a code but it renders it into ![Capture](https://user-images.githubusercontent.com/44483328/170147560-4e4bce7e-aa16-442c-b77d-f2b2cab472c0.PNG).

### To Reproduce

It happens every time I write `!=`.

### Configuration

```
return {
        default_prog = { "C:\\Windows\\System32\\wsl.exe" },
        color_scheme = "Aurora",
}
```

### Expected Behavior

Every time I write `!=` it should render it into `!=` instead of ![Capture](https://user-images.githubusercontent.com/44483328/170147560-4e4bce7e-aa16-442c-b77d-f2b2cab472c0.PNG).

**Comment by wez** [comment]
Those are ligatures defined by the font.
Take a look at https://wezfurlong.org/wezterm/config/font-shaping.html for information about font shaping; on that page is a config snippet you can use to disable ligatures if you don't want to see them.

**Comment by tempegarit** [comment]
Thanks @wez.
