### ISSUE TITLE
Problems rendering dakuten in UTF-8 NFD

### ISSUE THREAD

**Issue by WORKINGJONNI** [wez/wezterm#2032]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220524-225254-2725559f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm shows kana with dakuten (kana with the small " character on top right) in double. I believe this occuers when they are encoded in UTF-8 NFD. Strings that are encoded in NFC show up properly. See the attached screenshots for demonstration (test has NFD and test2 normal NFC). 

WezTerm:
<img width="725" alt="スクリーンショット 2022-05-25 10 26 46" src="https://user-images.githubusercontent.com/98011727/170205516-0789bedc-c6ef-4b08-9998-4c52ffad50a3.png">

Terminal:
<img width="725" alt="スクリーンショット 2022-05-25 10 27 26" src="https://user-images.githubusercontent.com/98011727/170205524-381a6ce1-fb01-4a42-8fa6-997c77f34ab4.png">

### Configuration

no config

**Comment by WORKINGJONNI** [comment]
Sorry, here you go! I've zipped them as I'm not sure if pasting them here would change the encoding.

[アーカイブ.zip](https://github.com/wez/wezterm/files/8771046/default.zip)

**Comment by wez** [comment]
Thanks!

This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by WORKINGJONNI** [comment]
Hi @wez!
Sorry for the delayed response and thanks a lot for fixing the issue, everything is working properly with the nightly ver (atm using 20220529-095438-c591217c).

Keep up the good work and thanks for providing both great software and support!
