### ISSUE TITLE
SpawnCommandInNewTab should reuse the current directory of the spawner tab

### ISSUE THREAD

**Issue by rcdosado** [wez/wezterm#2036]
**Is your feature request related to a problem? Please describe.**

i tried using SpawnCommandInNewTab to create another tab that is supposed to use the spawner tab current working directory,
but instead it uses default_cwd value, i have tried `cwd = os.getenv("cd")` which uses Windows environment variable CD to retrieve the current directory so i can pass it to cwd variable for the spawned tab, but it doesn't work also. i don't know if this is a feature request or just a bug. 

**Describe the solution you'd like**
if it is possible to use the current directory of the spawner as the same working directory of the spawnee

**Describe alternatives you've considered**
a way to get the current directory of the spawner, os.getenv("cd") is not working for me,  so i can assign it to cwd variable of SpawnCommandInNewTab action

**Additional context**
using Windows 10 , with wezterm version 20220101-133340-7edc5b5a

**Comment by yar999** [comment]
Here's my solution:

I like to use CMD +clink locally, we can set aliases

```cmd
Desktop
❯ alias cd
cd=cd $* && lua d:\tools\scwd.lua
```

d:\tools\scwd.lua:

```lua
local h = io.popen("cd")
local r = h:read("*a")
h:close()
io.write("\x1b]7;".. r .."\x1b\\")
```

wezterm.lua
```
...
local function urlDecode(s)  
    s = string.gsub(s, '%%(%x%x)', function(h) return string.char(tonumber(h, 16)) end) 
    return s
end

wezterm.on("newtab-cwd",function(window, pane)
    local cwd = urlDecode(pane:get_current_working_dir())
    -- wezterm.log_info(pane:get_current_working_dir())
    -- wezterm.log_info(cwd)
    window:perform_action(wezterm.action{SpawnCommandInNewTab={
        args={"cmd","/k","cd /d "..cwd}}
    }, pane)
end)
...
        {key="t", mods="ALT", action=wezterm.action{EmitEvent="newtab-cwd"}},
...
```

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by yar999** [comment]
The fix makes it easier to open the current directory in a new TAB,
Just update the OSC 7 Escape Sequence Working Directory after each CD execution


I like to use CMD +clink locally, we can set aliases

```cmd
❯ alias cd
cd=cd $* && lua d:\tools\scwd.lua
```

The following code sets the current directory at startup.
`load(io.popen('starship.exe init cmd'):read("*a"))()` is [startship](https://starship.rs/) configuration under CMD + Clink.

My starship configuration file is `D:\tools\clink\vendor\starship.lua`. your estimate is different, this needs to be modified according to the actual situation.

d:\tools\clink\vendor\starship.lua:

```lua
load(io.popen('starship.exe init cmd'):read("*a"))()

-- OSC 7 Escape Sequence Working Directory at cmd startup
local h = io.popen("cd")
local r = h:read("*a")
h:close()
io.write("\x1b]7;file://".. r .."\x1b\\")
```

Custom events are no longer required

**Comment by rcdosado** [comment]
tested it. now working fine. Thanks!
