### ISSUE TITLE
mods no longer support multiple keys?

### ISSUE THREAD

**Issue by yar999** [wez/wezterm#2037]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220525-232509-3be4dbc8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

  The following problems occur after upgrading to the latest night version:

CTRL + Shift +F cannot open search
CTRL + Shift +L cannot open ShowDebugOverlay
mods="ALT" is ok, mods="ALT|CTRL" not work, mods="ALT|SHIFT" not work too.

 

### To Reproduce

CTRL + Shift +F cannot open search
CTRL + Shift +L cannot open ShowDebugOverlay

### Configuration

```
        {key="l", mods="ALT", action="ShowDebugOverlay"},
        -- alt+d 复制当前ssh会话
        {key="d", mods="ALT", action=wezterm.action{EmitEvent="duplicate-current-ssh"}},
        {key="t", mods="ALT", action=wezterm.action{EmitEvent="newtab-cwd"}},
        -- {key="t", mods="ALT", action=wezterm.action{SpawnTab="DefaultDomain"}},
        {key="n", mods="ALT", action="SpawnWindow"},
        {key="1", mods="ALT", action=wezterm.action{ActivateTab=0}},
        {key="2", mods="ALT", action=wezterm.action{ActivateTab=1}},
        {key="3", mods="ALT", action=wezterm.action{ActivateTab=2}},
        {key="4", mods="ALT", action=wezterm.action{ActivateTab=3}},
        {key="5", mods="ALT", action=wezterm.action{ActivateTab=4}},
        {key="6", mods="ALT", action=wezterm.action{ActivateTab=5}},
        {key="7", mods="ALT", action=wezterm.action{ActivateTab=6}},
        {key="8", mods="ALT", action=wezterm.action{ActivateTab=7}},
        {key="9", mods="ALT", action=wezterm.action{ActivateTab=8}},
        {key="0", mods="ALT", action=wezterm.action{ActivateTab=9}},
        {key="1", mods="ALT|CTRL", action=wezterm.action{MoveTab=0}},
        {key="2", mods="ALT|CTRL", action=wezterm.action{MoveTab=1}},
        {key="3", mods="ALT|CTRL", action=wezterm.action{MoveTab=2}},
        {key="4", mods="ALT|CTRL", action=wezterm.action{MoveTab=3}},
        {key="5", mods="ALT|CTRL", action=wezterm.action{MoveTab=4}},
        {key="6", mods="ALT|CTRL", action=wezterm.action{MoveTab=5}},
        {key="7", mods="ALT|CTRL", action=wezterm.action{MoveTab=6}},
        {key="8", mods="ALT|CTRL", action=wezterm.action{MoveTab=7}},
        {key="9", mods="ALT|CTRL", action=wezterm.action{MoveTab=8}},
        {key="0", mods="ALT|CTRL", action=wezterm.action{MoveTab=9}},
        {key="\\", mods="ALT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
        {key="/", mods="ALT", action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
```

### Expected Behavior

CTRL + Shift +F  open search
CTRL + Shift +L  ShowDebugOverlay

### Logs

15:30:13.305 INFO wezterm_client::discovery::windows > published gui path as gui-sock-15968
15:30:13.498 INFO wezterm_gui::termwindow > OpenGL initialized! ANGLE (Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0) OpenGL ES 3.0.0 (ANGLE 2.1.1 git hash: 07ea804e6201) is_context_loss_possible=true wezterm version: 20220525-232509-3be4dbc8

### Anything else?

  
Does mods no longer support multiple keys?

**Comment by wez** [comment]
Sorry; I broke this as part of b2cd800c700f518b2321cc62f7120b2cf0dd6540.
This should be fixed now in `main`, and available in a nightly download within about an hour from now.

**Comment by yar999** [comment]
Thank you. wezterm 20220526-053815-b2cd800c works fine
