### ISSUE TITLE
How can I make my neovim full screen?

### ISSUE THREAD

**Issue by HideOnLie** [wez/wezterm#2040]
As my posted pictures, you can see that,  when I open my neovim, it will have a purple border in the terminal, which is my terminal's theme I deliberately set makes this problem easier to see. 

And when I use alacritty, I don't have this problem.

I found the document nothing about it. Hope to get help~

![image](https://user-images.githubusercontent.com/51672711/170647500-300301ab-5e4a-4c87-9900-564b77e0a304.png)
![image](https://user-images.githubusercontent.com/51672711/170647647-a7321cb2-39c4-4fc3-8e84-009ae981df95.png)

**Comment by HideOnLie** [comment]
Oh, I found the solution. In before, I was searching for 'widge' or 'window', this were wrong ways. XD

https://wezfurlong.org/wezterm/config/lua/config/window_padding.html?highlight=wid#window_padding

**Comment by wez** [comment]
Yes, changing the window padding (which you found in your comment above) is what you want here!
