### ISSUE TITLE
[wayland] Wezterm .desktop file always launches new instance

### ISSUE THREAD

**Issue by 1player** [wez/wezterm#2041]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220526-164715-509fd98b (latest nightly)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

(Stable is unaffected)

I have WezTerm pinned to my GNOME dock. Every time I click on it, it starts a new instance, instead of raising the previous one. I see the previous instance in the dock as an "unknown" application (i.e. it's not using the WezTerm icon).

Can't reproduce when `enable_wayland = false`

### Configuration

`enable_wayland = true`

**Comment by wez** [comment]
I can't reproduce this. It sounds like Gnome/Mutter may have gotten confused. Can you try restarting the desktop environment?

**Comment by wez** [comment]
I'm running on the same OS/configuration and this doesn't happen for me.
Are there really no logs with any interesting information?

**Comment by 1player** [comment]
No real difference in the logs. So, I've opened the GNOME looking glass inspector (Alt-F2, enter `lg`). 

When Wayland is disabled, under the inspector Windows screen it shows `wmclass = org.wezfurlong.wezterm`. When Wayland's enabled, it shows `wmclass = null`, which might be the reason GNOME gets confused. No idea why that happens.

**Comment by wez** [comment]
![image](https://user-images.githubusercontent.com/117777/170761715-6ba2ff60-932b-4001-a9d4-445ec3aaeae5.png)

It is set for me here.  How did you install wezterm?

**Comment by 1player** [comment]
I downloaded `wezterm-nightly-fedora36.rpm` from https://wezfurlong.org/wezterm/install/linux.html

```
#sha256sum
7816866e018fc9514db7887d9d3ba5f77f773290fc49ed36735241d86914c255  Downloads/wezterm-nightly-fedora36.rpm
```

**Comment by 1player** [comment]
Sorry for double posting, but I tried the latest nightly, and it's OK now. Still broken if I downgrade to the previous one.

wezterm-20220526_164715_509fd98b-1.fc36.x86_64 -- broken
wezterm-20220527_194712_c4a248f1-1.fc36.x86_64 -- OK

I'll close for now.

**Comment by wez** [comment]
Probably related to #1727; one of the workarounds in an earlier iteration was to unmap a surface.
I would expect that to only matter if you had display scaling set to something other than 100%

**Comment by 1player** [comment]
I am in fact using 200% scaling.
