### ISSUE TITLE
`window_padding` is not changed on `window_resized` example

### ISSUE THREAD

**Issue by erf** [wez/wezterm#2042]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220527-085629-03e07ece

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When going full screen, `window_padding` is not changed on `window_resized` events from the [window_resized example](https://wezfurlong.org/wezterm/config/lua/window-events/window-resized.html).

We log the following:
```
00:51:46.387  WARN   wezterm_dynamic::error      > `window_padding` is not a valid ValueLua field. Possible alternatives are `value`
```

### To Reproduce

Add the [window_resized](https://wezfurlong.org/wezterm/config/lua/window-events/window-resized.html) example to the `.wezterm` config file and return a blank config `{}` or a valid `window_padding` object.

Run Wezterm from another terminal and go fullscreen. Noticed the `window_resized` event but also the following WARNING:
```
00:51:46.387  WARN   wezterm_dynamic::error      > `window_padding` is not a valid ValueLua field. Possible alternatives are `value`
```
And the padding is not changed.

### Configuration

```
local wezterm = require 'wezterm'

function recompute_padding(window)
  local window_dims = window:get_dimensions();
  local overrides = window:get_config_overrides() or {}

  if not window_dims.is_full_screen then
    if not overrides.window_padding then
      -- not changing anything
      return;
    end
    overrides.window_padding = nil;
  else
    -- Use only the middle 33%
    local third = math.floor(window_dims.pixel_width / 3)
    local new_padding = {
      left = third,
      right = third,
      top = 0,
      bottom = 0
    };
    if overrides.window_padding and new_padding.left == overrides.window_padding.left then
      -- padding is same, avoid triggering further changes
      return
    end
    overrides.window_padding = new_padding

  end
  window:set_config_overrides(overrides)
end

wezterm.on("window-resized", function(window, pane)
  	wezterm.log_info("YO window-resized")
    recompute_padding(window)
end);

wezterm.on("window-config-reloaded", function(window)
  	wezterm.log_info("YO window-config-reloaded")
    recompute_padding(window)
end);


return {}
```

### Expected Behavior

I would expect a new `window_padding` to be set based on screen dimension on full screen (this used to work).

### Logs

``´
01:14:27.233  INFO   logging                 > lua: YO window-config-reloaded
01:14:33.141  INFO   logging                 > lua: YO window-resized
01:14:33.141  WARN   wezterm_dynamic::error  > `window_padding` is not a valid ValueLua field. Possible alternatives are `value`
01:14:35.463  INFO   logging                 > lua: YO window-resized
```

### Anything else?

_No response_

**Comment by wez** [comment]
Thanks for reporting this!

This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
