### ISSUE TITLE
Disable padding for text editor (micro)? 

### ISSUE THREAD

**Issue by onkoe** [wez/wezterm#2044]
Hello, 

Is there any way to disable padding while using my text editor, micro? I love the WezTerm padding, but in some cases, it starts to get ridiculous! 
![Screenshot from 2022-05-28 07-51-57](https://user-images.githubusercontent.com/66580279/170826335-100c18b9-01c6-4e1b-ab55-3b62f7a6290e.png)

Any assistance or mockery would be greatly appreciated!

**Comment by MuhammedZakir** [comment]
Note: I haven't tested this.

---

AFAIK, there is no `foreground-process-changed` event. So you'll have to use a different event [1] to

1. determine the current foreground process using either
    - https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html
    - https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_info.html

2. Then, change the padding inside the event handler depending on the process.

Example: https://wezfurlong.org/wezterm/config/lua/window-events/window-resized.html

[1] https://wezfurlong.org/wezterm/config/lua/window-events/index.html. If you only use WezTerm, then `bell` event maybe better. You can emit a bell whenever you open `micro`. E.g. `alias micro='printf \\a; micro'`.

**Comment by wez** [comment]
What I'd suggest is looking at user vars: https://wezfurlong.org/wezterm/config/lua/pane/get_user_vars.html

Setting a user var will trigger the [format-window-title](https://wezfurlong.org/wezterm/config/lua/window-events/format-window-title.html) event.

You can define an event handler for that, but have it return `nil` to use the default window title format, but in the body of that handler, "do something" to recompute and set a padding override similar to the examples you can see that adjust padding on https://wezfurlong.org/wezterm/config/lua/window-events/window-resized.html

So, pulling it together:

* define `format-window-title` handler that triggers your padding override based on the value of a user var
* In your shell (or editor config) arrange to set that user var when it starts the editor, and remove/clear it when it completes
