### ISSUE TITLE
[FEATURE] Windows admin privileges

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#205]
This request isn't easy and I don't think mac and linux separate non-admin and admin processes in quite the same way Windows does, making it very hard for them to interact with one another for security reasons.

What I imagine is this:
(1) wezterm, as user level, is able to launch admin-privileged shells, but UAC would need to be cleared each time.

(2) wezterm, when launched with admin privileges (which could involve a flag when calling the wezterm executable), still launches all of its subprocesses are user level by default. Either through its own shortcut system or through a wezterm subcommand, admin-level versions of subprocesses are launched. This would mean UAC would only have to be passed once, rather than for each admin-level subprocess.

Of course, the problem is, you would have to come up with a way for the admin-level and user-level processes to communicate to a wezterm that doesn't match its privelege level, in a way that Windows won't block.

**Comment by ImportTaste** [comment]
While I can't deny that UAC is more secure on paper than Linux's permission system, it's such a hassle that people will either stop paying attention to security prompts and always click yes regardless, or turn the prompts off entirely... making it less secure in practice.

**Comment by wez** [comment]
https://github.com/wez/wezterm/issues/155#issuecomment-638277142 captures my current thinking on this.

See also: https://github.com/wez/wezterm/issues/167#issuecomment-629714816 for an earlier comment on a related request

**Comment by wez** [comment]
Closing in favor of the linked issues
