### ISSUE TITLE
Need blink ease in/out configuration options for text with the blink attribute

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#2055]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Haven't tried it.

### Describe the bug

Cursor blinking in the terminal, when output via an ANSI escape code, ignores the `cursor_blink_ease_in = 'Constant'` & `cursor_blink_ease_out = 'Constant'` setting. It still animates.

I thought this was a *Btop* issue at first, when I hit `F` to filter for processes.

Stripped down its code to figure out the cause. It ended up being a *WezTerm* one.

### To Reproduce

Run:

    $ echo -e "\033[5m█\033[25m"

### Configuration

```lua
default_cursor_style = 'BlinkingBlock',
cursor_blink_rate = 500,
cursor_blink_ease_in = 'Constant',
cursor_blink_ease_out = 'Constant',
```

### Expected Behavior

The cursor blink does not animate.

**Comment by wez** [comment]
The `cursor_blink_xxx` options apply to the cursor. In this scenario, you're outputting blinking text.
There isn't a currently an option to control the animation style for blinking text.
