### ISSUE TITLE
tmux 3.3 leaks text into shell

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#2060]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220531-232011-d9f54a7c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When starting the recently released tmux 3.3 I get the following text leaked into my prompt ``:>|WezTerm 20220531-232011-d9f54a7c^[\``. This does not happen with tmux 3.2a.

### To Reproduce

Start tmux 3.3 with the following config options set 

```
# set terminal title
set -g set-titles on
# update currently running command
setw -g automatic-rename on
 ```

### Configuration

```lua
local wezterm = require("wezterm")

-- see https://wezfurlong.org/wezterm/config/lua/wezterm/target_triple.html for values
local is_linux = wezterm.target_triple == "x86_64-unknown-linux-gnu"
local is_windows = wezterm.target_triple == "x86_64-pc-windows-msvc"

return {
  audible_bell = "Disabled",
  color_scheme = "Gruvbox Dark",
  default_domain = is_windows and "WSL:Ubuntu" or nil,
  default_prog = is_windows and { "wsl.exe" } or nil,
  -- debug_key_events = true,
  -- exit_behavior = "Close",
  font = wezterm.font_with_fallback({
    "JetBrains Mono",
    "Symbols Nerd Font",
  }),
  font_size = 12.15,
  hide_tab_bar_if_only_one_tab = false,
  hyperlink_rules = {
    -- This is actually the default if you don't specify any hyperlink_rules
    {
      regex = "\\b\\w+://(?:[\\w.-]+)\\.[a-z]{2,15}\\S*\\b",
      format = "$0",
    },
    -- linkify email addresses
    {
      regex = "\\b\\w+@[\\w-]+(\\.[\\w-]+)+\\b",
      format = "mailto:$0",
    },
    -- Make task numbers clickable
    -- {regex = "\\b[tT](\\d+)\\b", format = "https://example.com/tasks/?t=$1" }

    -- Linkify things that look like URLs

    -- file:// URI
    {
      regex = "\\bfile://\\S*\\b",
      format = "$0",
    },
    -- nixpkgs review current program
    {
      regex = "nixpkgs-review pr (\\d+)",
      format = "https://github.com/NixOS/nixpkgs/pull/$1",
    },
    {
      regex = "pr-(\\d+)-?\\d?",
      format = "https://github.com/NixOS/nixpkgs/pull/$1",
    },
    -- nix flake github references
    {
      regex = "github:([\\w\\d_-]+)/([\\w\\d_\\.-]+)",
      format = "https://github.com/$1/$2",
    },
    -- nix flake github references with commit
    {
      regex = "github:([\\w\\d_-]+)/([\\w\\d_\\.-]+)/([\\d\\w-]+)",
      format = "https://github.com/$1/$2/commit/$3",
    },
    -- git ssh remote url
    {
      regex = "git@(\\w+\\.\\w+):(\\w+/\\w+)\\.git",
      format = "https://$1/$2",
    },
    -- go packages on github.com
    {
      regex = "github.com/([\\w_-]+)/([\\w_-]+)",
      format = "https://github.com/$1/$2",
    },
  },
  keys = {
    -- because of some bug Tab is detect as i
    {
      key = "phys:I",
      mods = "CTRL|SHIFT",
      action = wezterm.action({ ActivateTabRelative = -1 }),
    },
    {
      key = "phys:I",
      mods = "CTRL",
      action = wezterm.action({ ActivateTabRelative = 1 }),
    },
    -- scroll between prompts with Shift+Arrow up/down
    {
      key = "UpArrow",
      mods = "SHIFT",
      action = wezterm.action({ ScrollToPrompt = -1 }),
    },
    {
      key = "DownArrow",
      mods = "SHIFT",
      action = wezterm.action({ ScrollToPrompt = 1 }),
    },
    -- split current pane vertical
    {
      key = '"',
      mods = "CTRL|SHIFT|ALT",
      action = wezterm.action({
        SplitVertical = { domain = "CurrentPaneDomain" },
      }),
    },
    -- split current pane horizontal
    {
      key = "%",
      mods = "CTRL|SHIFT|ALT",
      action = wezterm.action({
        SplitHorizontal = { domain = "CurrentPaneDomain" },
      }),
    },
  },
  launch_menu = is_windows and { { args = { "cmd.exe" }, domain = { DomainName = "local" } } } or nil,
  scrollback_lines = 40000,
  set_environment_variables = {
    TERMINFO_DIRS = "/home/" .. (os.getenv("USERNAME") or os.getenv("USER")) .. "/.nix-profile/share/terminfo",
    WSLENV = "TERMINFO_DIRS",
    prompt = is_windows and "$E]7;file://localhost/$P$E\\$E[32m$T$E[0m $E[35m$P$E[36m$_$G$E[0m " or nil,
  },
  term = "wezterm",
  text_background_opacity = 1.0,
  warn_about_missing_glyphs = false,
  window_background_opacity = 0.9,
}
```

### Expected Behavior

This shouldn't happen.

### Logs

```
14:55:05.205  INFO   wezterm_client::discovery::windows > published gui path as gui-sock-8988
14:55:05.287  WARN   window::os::windows::window        > EGL init failed Config says to avoid EGL, fall back to WGL
14:55:05.442  INFO   wezterm_gui::termwindow            > OpenGL initialized! Intel(R) UHD Graphics 4.5.0 - Build 30.0.101.1122 is_context_loss_possible=true wezterm version: 20220531-232011-d9f54a7c
14:55:14.867  WARN   wezterm_term::terminalstate        > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
```

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use 80x24 for the terminal dimensions as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps; start up `tmux`, pause for a few seconds, then exit it.
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by wez** [comment]
@nicm: thoughts on this? wezterm's response to `DCS >q` looks like `\u{1b}P>|WezTerm 20220530-085148-3ef533e8\u{1b}\\` and is flushed immediately once recognized by the terminal.  How much time does tmux allow for the response to come back? I'm wondering if there is a latency issue here, or whether there is something else happening.

**Comment by nicm** [comment]
tmux allowed one second until 333cf6429ae16da6fb3892978ea450bc62c3e873 when it was changed to three seconds because some terminals (Windows Terminal, whatever that is) were apparently slow to respond.

**Comment by nicm** [comment]
I wonder if the escape sequence is being sent twice (either the request or response); tmux will only process the first it receives.

@SuperSandro2000 please show the tmux server log, see [here](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux).

**Comment by wez** [comment]
The relevant portion of the screen recording asciicast above is this; the query is sent once:

```
[10.182313,"o","\u001b[?12l\u001b[?1000l"]
[10.182359,"o","\u001b[?1002l"]
[10.182439,"o","\u001b[?1003l"]
[10.182491,"o","\u001b[?1006l"]
[10.182524,"o","\u001b[?1005l\u001b[?12l\u001b[?1006l\u001b[?1000l\u001b[?1002l\u001b[?1003l\u001b[?2004l"]
[10.182577,"o","\u001b[>q"]
[10.182611,"o","\u001b[?1006l"]
[10.182645,"o","\u001b[?1000l"]
[10.182673,"o","\u001b[?1002l"]
[10.182699,"o","\u001b[?1003l"]
[10.182727,"o","\u001b[?1006h"]
[10.182752,"o","\u001b[?1000h"]
[10.182793,"o","\u001b[?1002h"]
[10.182818,"o","\u001b[?2026h"]
[10.182858,"o","\u001b[?12l"]
[10.182901,"o","\u001b[?2026l"]
[10.183195,"o","\u001b[?1004h"]
[10.183225,"o","\u001b[?7727h"]
[10.186115,"o","\u001b[?12l"]
[10.186352,"o","\u001b[?1006l\u001b[?1000l\u001b[?1002l\u001b[?1003l\u001b[?2004l"]
[10.186401,"o","\u001b[?1006l"]
[10.186427,"o","\u001b[?1000l"]
[10.186448,"o","\u001b[?1002l"]
[10.186468,"o","\u001b[?1003l"]
[10.186489,"o","\u001b[?1006h"]
[10.186508,"o","\u001b[?1000h"]
[10.18653,"o","\u001b[?1002h"]
[10.18655,"o","\u001b[?2026h"]
[10.186584,"o","\u001b[?12l"]
[10.186615,"o","\u001b[?2026l"]
[10.19411,"o","^[P>|WezTerm 2022^[[0;0;48;1;0;1_531-232011-d9f54^[[0;0;97;1;0;1_7c^[\\\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[38;5;234m\u001b[48;5;246m\r\n 1 \u001b[38;5;246m\u001b[48;5;237m\u001b[38;5;237m\u001b[48;5;239m \u001b[38;5;246m1  bash \u001b[38;5;239m\u001b[48;5;237m                          \u001b[38;5;246m\u001b[48;5;239m 2022-06-01  15:07 \u001b[38;5;234m\u001b[48;5;246m W-PF2ZA0JC-wsl \u001b[1;71H"]
[10.209947,"o","\u001b[m"]
```

The numbers in the left column are the number of seconds since the recording started, so this is in the tens of milliseconds time scale.

As a sniff test to verify that wezterm isn't accidentally responding twice:

```
; printf "\e[>q" ; xxd
^[P>|WezTerm 20220530-085148-3ef533e8^[\
00000000: 1b50 3e7c 5765 7a54 6572 6d20 3230 3232  .P>|WezTerm 2022
00000010: 3035 3330 2d30 3835 3134 382d 3365 6635  0530-085148-3ef5
00000020: 3333 6538 1b5c 0a                        33e8.\.
```

**Comment by wez** [comment]
> it was changed to three seconds because some terminals (Windows Terminal, whatever that is) were apparently slow to respond.

FWIW, ConPTY (the pty layer on Windows) is also involved in this scenario and it has been known to emit surprising extra stuff.  My sniff test above is on a linux system, but it should be repeated in the same WSL setup that I think @SuperSandro2000 is running to confirm that.

**Comment by SuperSandro2000** [comment]
> Windows Terminal, whatever that is

The new Windows Terminal that is used by default in Windows 11.

> it should be repeated in the same WSL setup that I think @SuperSandro2000 is running to confirm that.

I am running multiple setups. One is on WSL2 and the other is on NixOS.

[tmux-out-113490.log](https://github.com/wez/wezterm/files/8815134/tmux-out-113490.log)
[tmux-server-113490.log](https://github.com/wez/wezterm/files/8815135/tmux-server-113490.log)
[tmux-client-113488.log](https://github.com/wez/wezterm/files/8815136/tmux-client-113488.log)

**Comment by nicm** [comment]
The problem is that the period between the first part of the response (`^[P>|WezTerm 20220530-085148-3ef533e8`) comes in a separate read from the terminator (`^[\`) and your `escape-time` is exceeded.

Increase `escape-time` and it should work.

**Comment by nicm** [comment]
We could probably make `escape-time` zero actually mean one, it seems unlikely anyone would notice one millisecond.

**Comment by nicm** [comment]
I've changed to force 0 to 1 but it will not be until tmux 3.4.

**Comment by SuperSandro2000** [comment]
Still happening with the 20220602-080055-c3b1aa72 release

**Comment by wez** [comment]
@SuperSandro2000 the root cause is that you have set `escape-time` to 0 in your tmux config. That prevents tmux from recognizing escape sequences that are fragmented across read/packet boundaries. You should raise that to a more reasonable value such as 100ms which should be enough time for most cases while still being quick enough that it shouldn't cause human-scale interaction issues.

**Comment by SuperSandro2000** [comment]
A good to know that! I only have set it to 0 because otherwise vim always takes a bit to react.

**Comment by bew** [comment]
FWIW I've always set it to 10ms, never had issues
