### ISSUE TITLE
garbage output can lead to crashing of wezterm

### ISSUE THREAD

**Issue by ChrisOboe** [wez/wezterm#2062]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I accidentaly executed cat on a binary file, than wezterm crashed. 
I doesn't happen on every binary file. As test i catted my grep binary which worked fine. So i assume there are only some sequence that lead to crashing. 

I didn't use nighly since i don't know how to get a nighly build running without investing to much time on it on my distro (nixos). But i read the changelog.md to see if nighly has my error fixed already (it doesn't seem so). I hope (and assume) it's a different bug then one here https://github.com/wez/wezterm/pull/1990

### To Reproduce

here is a file that i catted that always leads to crashing
[MT_XY.pdf](https://github.com/wez/wezterm/files/8817885/MT_XY.pdf)

otherwise cat /dev/random also leads to crashes after a random time
cat /dev/random doesn't always lead to the same crash. 

### Configuration

i don't think my config is relevant as this crash is reproducable even without a config. 

### Expected Behavior

i expect that wezterm doesn't crash. 

### Logs

[wezterm.log](https://github.com/wez/wezterm/files/8817900/wez.log)

### Anything else?

i excecuted wezterm with the env var RUST_BACKTRACE=full so a backtrace is included in the log.

**Comment by wez** [comment]
Please try the nightly build!
