### ISSUE TITLE
slow startup time on windows

### ISSUE THREAD

**Issue by amstaniec** [wez/wezterm#2066]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

start up time - seems too long

the default windows terminal `cmd.exe` takes **14ms**
whereas `wezterm` takes **1899ms**,

### To Reproduce

I tested using the powershell, like this:

```

PS C:\Users\Adrian> wezterm -V
wezterm 20220408-101518-b908e2dd
PS C:\Users\Adrian>
PS C:\Users\Adrian> Measure-Command -Expression { wezterm start -- echo "done" }
15:40:45.698  INFO   wezterm_mux_server_impl::local > setting up C:\Users\Adrian\.local/share/wezterm\gui-sock-8240
15:40:45.700  INFO   wezterm_client::discovery::windows > published gui path as gui-sock-8240
15:40:45.757  WARN   window::os::windows::window        > EGL init failed Config says to avoid EGL, fall back to WGL
15:40:45.996  INFO   wezterm_gui::termwindow            > OpenGL initialized! Quadro M1200/PCIe/SSE2 4.5.0 NVIDIA 511.79 is_context_loss_possible=true wezterm version: 20220408-101518-b908e2dd


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 899
Ticks             : 18991690
TotalDays         : 2.19811226851852E-05
TotalHours        : 0.000527546944444444
TotalMinutes      : 0.0316528166666667
TotalSeconds      : 1.899169
TotalMilliseconds : 1899.169



PS C:\Users\Adrian> Measure-Command -Expression { cmd /c echo "done" }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 14
Ticks             : 144845
TotalDays         : 1.67644675925926E-07
TotalHours        : 4.02347222222222E-06
TotalMinutes      : 0.000241408333333333
TotalSeconds      : 0.0144845
TotalMilliseconds : 14.4845

PS C:\Users\Adrian> 
```

### Configuration

```
local wezterm = require 'wezterm';
return {
}
```

### Expected Behavior

I expected startup ties close to `cmd.exe` so around **20ms**

### Logs

?

### Anything else?

maybe I an doing something wrong,
or maybe the slow startup tiem is cause by those warning?
if so , please advise

**Comment by adrianstaniec** [comment]
I have just noticed that starting up wezterm, just to get a prompt is slower that what I was expecting.
comparing it to just starting up cmd.exe
(sorry, I am confused wheather cmd.exe is a shell or terminal or both)
whatever it is in Windows, it starts up much faster in my experiance

So I just tried to put an objective number on it.

Can you suggest a more appropriate method to measure the time between:
- double clicking the wezterm-gui.exe icon and
- seeing the prompt (also from cmd.exe for best comparison) and being able to type in it?

**Comment by samoylovfp** [comment]
On Ubuntu I noticed startup time shoot up from unnoticeable to a second or two after the last update.
Should I create a new issue? I am willing to do some profiling.

**Comment by samoylovfp** [comment]
Recorded a video of different versions of wezterm startup time. Nightly starts up the same time as the  `20220408-101518-b908e2dd` one

https://user-images.githubusercontent.com/17025459/171988721-d54a8d09-303d-42ea-bada-7afc254bf046.mp4

**Comment by wez** [comment]
> On Ubuntu I noticed startup time shoot up from unnoticeable to a second or two after the last update. Should I create a new issue? I am willing to do some profiling.

Yes please!  I would suggest setting `WEZTERM_LOG=trace` in the environment to help identify slow spots in the logs that it generates.

**Comment by wez** [comment]
I'm closing this because I think there was some confusion about what to measure and because wezterm has similar startup time to wt.exe

**Comment by adrianstaniec** [comment]
I also recorded a video on Windows 10,
and measured the time with Avidemux,
here are the results:

```
wezterm.exe  2.68s
wt.exe       1.45s
cmd.exe      0.35s
```

https://user-images.githubusercontent.com/15216366/175039244-36b9ae0b-63ca-4852-bcc9-a6933b981a65.mp4

IMHO that's still a problem
