### ISSUE TITLE
Some artifacts in vim signcolumn since commit a0ad3dd3

### ISSUE THREAD

**Issue by mckellygit** [wez/wezterm#2068]
Hi,
Thank you for wezterm.  No big deal esp since commit comment says Prep for future work ...
But since commit a0ad3dd3 gui: move ease/interpolation into shader - I see a few small rectangles in the signcolumn in vim that are not correct when moving around.
Happens with both x11 and wayland setting.  Do you want a screen cast ?
thx,
-m

**Comment by wez** [comment]
hmm, I suspect that f60e39b4c3228ffa933b5d6911782d3964e7db26 will take care of that. Could you try it and let me know?

**Comment by mckellygit** [comment]
Yes, this commit fixes my issue.
Thanks so much!
