### ISSUE TITLE
Can't open new tab in same folder

### ISSUE THREAD

**Issue by erf** [wez/wezterm#207]
## Describe the bug

I'm not able to open a new tab in the same folder on macOS. 

I tried all the default keyboard shortcuts:

```
SUPER | t | SpawnTab="CurrentTabDomain"
CTRL+SHIFT | t | SpawnTab="CurrentTabDomain"
SUPER+SHIFT | T | SpawnTab="DefaultDomain"
```

I also tried to add the following to `.wezterm.lua`

```
    {key="t", mods="CMD", action=wezterm.action{SpawnTab="CurrentTabDomain"}},
```

But it always open in the `$HOME` folder.

Not sure if `DefaultDomain` and `CurrentTabDomain` is described in the docs?

## Environment (please complete the following information):

 - macOS
 - Version: wezterm 20200517-122836-92c201c6-78-g970db643

## To Reproduce

Go to a folder other than $HOME, e.g. "$HOME/projects" and press CMD-t 

## Configuration

Empty config when trying the default keys.

## Expected behavior

I expected to open the folder in "$HOME/projects"

Sorry if this was discussed before, i could not find the notes.

**Comment by wez** [comment]
Knowledge about the current directory needs to be provided by the shell by having it emit an `OSC 7` sequence:

https://wezfurlong.org/wezterm/shell-integration.html#osc-7-escape-sequence-to-set-the-working-directory

An example of the Fedora vte.sh can be found here:

https://pastebin.com/raw/MmVmjXS8

**Comment by erf** [comment]
I use zsh

**Comment by wez** [comment]
The other terminals definitely also require some assistance from the shell for this.
The mac I have to hand is still running Mojave.  Poking around in `/etc` I can see:

```bash
$ tail -1 /etc/bashrc
[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"
```

Which means that Apple's bash config will source a terminal specific profile:

```
$ head /etc/bashrc_Apple_Terminal
# bash support for Terminal.


# Working Directory
#
# Tell the terminal about the current working directory at each prompt.

if [ -z "$INSIDE_EMACS" ]; then
    update_terminal_cwd() {
        # Identify the directory using a "file:" scheme URL, including
...
```

Recent versions of WezTerm export `TERM_PROGRAM=WezTerm` into the environment so it would be possible to use the same technique, however, macOS's packaging and deployment makes it basically impossible to deploy things there.

My suggestion is to put something like this in your `.zshrc` and/or `.bashrc` (it will work for both shells):

```bash
__vte_urlencode() (
  # This is important to make sure string manipulation is handled
  # byte-by-byte.
  LC_ALL=C
  str="$1"
  while [ -n "$str" ]; do
    safe="${str%%[!a-zA-Z0-9/:_\.\-\!\'\(\)~]*}"
    printf "%s" "$safe"
    str="${str#"$safe"}"
    if [ -n "$str" ]; then
      printf "%%%02X" "'$str"
      str="${str#?}"
    fi
  done
)

__vte_osc7 () {
  printf "\033]7;file://%s%s\007" "${HOSTNAME:-}" "$(__vte_urlencode "${PWD}")"
}

__vte_prompt_command() {
  local command=$(HISTTIMEFORMAT= history 1 | sed 's/^ *[0-9]\+ *//')
  command="${command//;/ }"
  local pwd='~'
  [ "$PWD" != "$HOME" ] && pwd=${PWD/#$HOME\//\~\/}
  printf "\033]777;notify;Command completed;%s\007\033]0;%s@%s:%s\007%s" "${command}" "${USER}" "${HOSTNAME%%.*}" "${pwd}" "$(__vte_osc7)"
}

case "$TERM" in
  xterm*|vte*)
    [ -n "$BASH_VERSION" ] && PROMPT_COMMAND="__vte_prompt_command"
    [ -n "$ZSH_VERSION"  ] && precmd_functions+=(__vte_osc7)
    ;;
esac

true
```

**Comment by erf** [comment]
That works. Thanks
