### ISSUE TITLE
Slow start-up on ubuntu

### ISSUE THREAD

**Issue by samoylovfp** [wez/wezterm#2073]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220603-180851-da59a222

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

It takes 1-2 seconds for wezterm to show the window

### Configuration

no config

### Expected Behavior

I expect wezterm to take no longer than 200 ms to show the window in which the user can start typing on a modern hardware. Everything slower should be done in the background after the prompt is shown or on first start up and cached.

### Logs

Logs for the slow startup
https://gist.github.com/samoylovfp/16cce32c5ba2a2e5bfb88b51f6492ea2
the interesting part is 
```
16:15:53.794  TRACE  wezterm_gui::termwindow            > RequestedWindowGeometry { width: Pixels(820.0), height: Pixels(583.0), x: None, y: None, origin: ScreenCoordinateSystem }
16:15:54.802  TRACE  window::os::x11::window            > {"HDMI-2": Rect(1920x1080 at (0, 0))}
```

Here's logs from an older version that does not have this problem `WezTerm-20220319-142410-0fcdea07-Ubuntu18.04.AppImage` for reference
https://gist.github.com/samoylovfp/6a09b7466e9cb3118534d26c05d54665

the window is shown and closed via "Ctrl+D" in 1 second

### Anything else?

Thanks for the awesome tool!

**Comment by wez** [comment]
FWIW, on my system this only takes 3ms:

```
06:46:32.224  TRACE  wezterm_gui::termwindow            > RequestedWindowGeometry { width: Pixels(1066.0), height: Pixels(743.0), x: None, y: None, origin: ScreenCoordinateSystem }
06:46:32.227  TRACE  window::os::x11::window            > {"DisplayPort-1": Rect(3840x2160 at (0, 0))}
```

Is there a local configuration issue that might result in that being slow on your system?

Is `time xrandr` fast on your system?

**Comment by samoylovfp** [comment]
Mind you the "fast" log is from the same system and session

xrandr is pretty slow
`xrandr  0.00s user 0.00s system 0% cpu 1.501 total`
```
Benchmark 1: xrandr
  Time (mean ± σ):     824.3 ms ±  66.3 ms    [User: 0.8 ms, System: 1.0 ms]
  Range (min … max):   799.2 ms … 1013.0 ms    10 runs
```

**Comment by wez** [comment]
I think the slowness is a system/driver/kernel issue.  https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/855124 may be relevant or offer some suggestions on how to run that down, even though it is an old issue.

**Comment by samoylovfp** [comment]
When I disconnect the external monitor the startup time falls down to ~ 400 ms.
I'll try to debug my setup, thank you for the hint!
