### ISSUE TITLE
The shell spawned by assume_shell=Posix is not a "login shell"

### ISSUE THREAD

**Issue by TomiBelan** [wez/wezterm#2076]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220605-063531-e7258e0e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hi Wez! Nice terminal!

When wezterm runs an `env -C ... $SHELL` command via ssh, the shell not invoked "as a login shell". This means it may read different rc files than usual.

For example, in Debian/Ubuntu/Arch, scripts in `/etc/profile.d/*.sh` only run in a login shell. I heard Fedora runs them in both cases.

### To Reproduce

Ssh to a Linux server. (I'm using Linux Mint here but any distro should give the same output.)

With the wezterm.lua below: It is not a login shell. argv0 is "/bin/bash" (from $SHELL).

```console
$ shopt login_shell
login_shell     off
$ ps x
  PID TTY      STAT   TIME COMMAND
[...]
15617 ?        S      0:00 sshd: example@pts/2
15618 pts/2    Ss     0:00 /bin/bash
15719 pts/2    R+     0:00 ps x
```

With plain `wezterm ssh example@example.com` or if I remove `assume_shell = "Posix"`: It is a login shell. argv0 is "-bash" (from sshd).

```console
$ shopt login_shell
login_shell     on
$ ps x
  PID TTY      STAT   TIME COMMAND
[...]
29846 ?        S      0:00 sshd: example@pts/2
29847 pts/2    Ss     0:00 -bash
29875 pts/2    R+     0:00 ps x
```

### Configuration

```lua
return {
  default_domain = "my_ssh",
  ssh_domains = {
    {
      name = "my_ssh",
      remote_address = "example.com",
      username = "example",
      multiplexing = "None",
      assume_shell = "Posix",
    }
  },
}
```

### Expected Behavior

Run a login shell when multiplexing="None" and assume_shell="Posix". In other words add a "-" before the argv0.

(Note: I don't know whether multiplexing="Wezterm" starts a login shell or not, but either option is probably fine. I'm guessing from the wezterm changelog that you intentionally prefer login shells because of macOS.)

### Anything else?

This workaround fixes it: `default_prog = {"bash", "-c", "SHLVL= exec -a -bash bash"},`

Explanation: It makes wezterm send this command:
`env 'COLORTERM=truecolor' 'WSLENV=TERM:COLORTERM:TERM_PROGRAM:TERM_PROGRAM_VERSION' 'TERM_PROGRAM=WezTerm' 'TERM=xterm-256color' 'TERM_PROGRAM_VERSION=20220605-063531-e7258e0e' 'WEZTERM_REMOTE_PANE=0' bash -c 'SHLVL= exec -a -bash bash'`
It is executed by sshd as execve("/bin/bash", {"bash", "-c", command}). So it's sshd->bash->env->bash->bash. Oh well.

It also resets $SHLVL to 1 -- not that it affects anything, as far as I'm aware.

Links:

- bash docs (slightly Debian specific): https://manpages.debian.org/bullseye/bash/bash.1.en.html#INVOCATION
- bash source: https://github.com/bminor/bash/blob/9439ce094c9aa7557a9d53ac7b412a23aa66e36b/shell.c#L1056
- sshd source: https://github.com/openssh/openssh-portable/blob/acb2059febaddd71ee06c2ebf63dcf211d9ab9f2/session.c#L1678
- Old discussion about distros handling /etc/profile.d/*.sh differently: https://bugzilla.gnome.org/show_bug.cgi?id=697475

Personal opinion: I think you should probably **close this as WONTFIX**. I'm just filing the bug to record it. ;) In most cases it shouldn't matter whether you have a login shell or not. And I don't know of any easy portable fix. The `exec -a ARGV0` option is not POSIX-standard (e.g. bash and zsh have it, fish does not).

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
