### ISSUE TITLE
Create homebrew tap

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#208]
Currently every few weeks I need to manually update wezterm. 

Windows already is using scoop.

Can we include a tap for homebrew?
https://docs.brew.sh/Taps

As for archlinux someone already created an aur package which I currently use.

https://aur.archlinux.org/packages/wezterm-bin/

https://aur.archlinux.org/packages/wezterm-git/

**Comment by wez** [comment]
Yeah, that makes sense.  I put this together for macos:
https://github.com/wez/homebrew-wezterm#homebrew-wezterm
(caveat emptor: I've only tried installing this over ssh to my mac, I haven't tried to actually run it from the gui)

and another one for linuxbrew:
https://github.com/wez/homebrew-wezterm-linuxbrew/#homebrew-wezterm-linuxbrew

**Comment by prabirshrestha** [comment]
Thanks for the quick push. I tested on a mac and it works.

It would be good to update the docs to point to the new installation mechanism too.

Also might be worth looking into automating it:
https://github.com/garden-io/update-homebrew-action
https://medium.com/@Extrawurst/github-actions-homebrew-%EF%B8%8F-2789ae5023fd. There might be actions that automatically does this.

I don't use homebrew-linux. So didn't test it.
