### ISSUE TITLE
Could status bar be shown when tab bar is hidden?

### ISSUE THREAD

**Issue by mostafaqanbaryan** [wez/wezterm#2082]
**Is your feature request related to a problem? Please describe.**
I use Vim in fullscreen mode and don't need any tab (I use panes and splits which works great)
So because of that, I added  `hide_tab_bar_if_only_one_tab = true` in my config that hides tab bar and gives me that extra space.
But now, if I want to use status bar and `update-right-status` hook, there is no status bar.

**Describe the solution you'd like**
I don't need tab bar and want to use that space in my Vim.
So I think it would be great to fix status bar on screen (without occupying 1-2 lines at the top, just a floating status bar at top-right)
Or maybe something like that parallax background at another (maybe below) layer!

**Additional context**
Without tab bar:
![Screenshot from 2022-06-06 18-40-28](https://user-images.githubusercontent.com/94293456/172177789-64b3e542-9c1d-45a6-9329-5c0b1e39d26c.png)
With tab bar:
![Screenshot from 2022-06-06 18-40-19](https://user-images.githubusercontent.com/94293456/172177803-b826d782-c4b3-4332-a6ad-1d3d92de2eeb.png)
2 lines removed.

**Comment by toothlesslizard** [comment]
@wez something like this

![term](https://user-images.githubusercontent.com/106248555/202869903-62741703-05ea-4299-8f91-ac7f9bbefc09.png)

**Comment by wez** [comment]
I just pushed a commit to `main` that allows:

```lua
local wezterm = require 'wezterm'

wezterm.on('update-right-status', function(window, pane)
  window:set_left_status("left")
  window:set_right_status("right")
end)

return {
  use_fancy_tab_bar = false,
  show_tabs_in_tab_bar = false,
  show_new_tab_button_in_tab_bar = false,
}
```

<img width="525" alt="Screenshot 2022-11-19 at 13 46 38" src="https://user-images.githubusercontent.com/117777/202871036-cf9ca023-88d1-46b4-8dd8-9cf68374b5f3.png">
<img width="525" alt="image" src="https://user-images.githubusercontent.com/117777/202871068-97cc027c-0b30-482c-8418-9037641d24eb.png">

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
