### ISSUE TITLE
Implement iterm2 like OSC 1337;ReportCellSize

### ISSUE THREAD

**Issue by MatanZ** [wez/wezterm#2085]
iterm2 has an OSC command releated to graphics

`OSC 1337 ; ReportCellSize`

It seems that it is recognized but not handled, log entry
`WARN   wezterm_term::terminalstate::performer > unhandled iterm2: RequestCellSize`

Unlike in unrecognized command:
`WARN   wezterm_term::terminalstate::performer > Unhandled OSC  1337 abcdef`

This information is available in reply to `CSI 16 t`, so this OSC command is not strictly necessary, but it useful for recognizing support for iterm2 inline image protocol, as it is the only command related to inline images that replies to the terminal.

See for example, here: 
https://github.com/dotcs/xkcd-cli/blob/3ea7dfa110fc81cb01983c47694c237463618dcb/xkcd_cli/iv.py#L372-L392
https://github.com/dotcs/xkcd-cli/blob/3ea7dfa110fc81cb01983c47694c237463618dcb/xkcd_cli/iv.py#L410-L419

**Comment by wez** [comment]
It's conceptually simple to emit a response to this, except: the iTerm2 sequence wants to return the size in *points*, but the terminal layer doesn't know the DPI which is necessary to calculate the correct dimensions in points: it only tracks the cell and pixel dimensions.

Adding that information needs to cross a few layers and IPC boundaries, so it's a bit more of a churn.
I'm going to tag this as multiplexer so that I can consider it when I'm next looking at that.

**Comment by MatanZ** [comment]
I believe the points are not 1/72 of inch, but something to do with MacOS high resolution API. The documentation says:

> [scale] gives the number of pixels (physical units) to points (logical units). 1.0 means non-retina, 2.0 means retina. It could take other values in the future.

I expect that on non-MacOS it is safe to give size in pixels and scale=1.0.

**Comment by wez** [comment]
What documentation are you quoting? The docs for `ReportCellSize` at https://iterm2.com/3.3/documentation-escape-codes.html don't mention a dpi scaling factor; they just say points.  I would expect iterm to report the same point value used by the configured font regardless of whether the display was retina or not.

**Comment by MatanZ** [comment]
https://iterm2.com/documentation-escape-codes.html

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
