### ISSUE TITLE
Mouse selection includes the first character of the next line

### ISSUE THREAD

**Issue by TomiBelan** [wez/wezterm#2089]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220605-063531-e7258e0e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When you drag the mouse downwards along the left window edge, it also selects the first character from the line where you stop dragging.

### To Reproduce

- `printf 'ABCD\nEFGH\n'`
- drag the mouse from left of "A" to left of "E"
- the selected string is: "ABCD\nE"

![image](https://user-images.githubusercontent.com/1022278/172065711-7b49f8ca-77ab-409e-ab3d-ebaa295c4c45.png)

### Configuration

no config

### Expected Behavior

I think it makes more sense to only select the first line. The clipboard should not contain "E".

If users want to select "ABCD\nE", they'll have to drag the mouse from left of "A" to between the center of "E" and the center of "F". I think this is an unusual case so I don't think a config option is needed. (https://xkcd.com/1172/)

By analogy, when you start on other X-coordinates and move one line Y-downwards, it selects a 5 character string, not 6. E.g. dragging vertically from between (the centers of) "B" and "C" to between "F" and "G" selects "CD\nEF".

### Anything else?

By the way, I also noticed that wezterm strips all newlines from the start and end of the selected text. Personally I'd prefer to select "ABCD\n" rather than "ABCD", but I'm ok with both, and I guess other users are the opposite so maybe this could be configurable. I can file a separate feature request if you'd like. Just as long as it isn't "ABCD\nE".

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Lenbok** [comment]
Do the fixes for this help with #1954, so that we can also have keyboard based selection that doesn't include the final character?

**Comment by wez** [comment]
@Lenbok: you'll have to try it to find out! Note that line-based selection is now also supported in copy mode
