### ISSUE TITLE
auto publish to aur via github actions for archlinux

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#209]
Would be good if aur packages gets automatically updated during every release. 

https://aur.archlinux.org/packages/wezterm-bin
https://aur.archlinux.org/packages/wezterm-git

I only use `wezterm-bin`. Might be also good to have `wezterm-nightly-bin` which currently doesn't exist.

The aur package is owned by @ragouel so might need to transfer ownership first in order to publish.

Here is the github action that could be used to automate publishing packages. https://github.com/marketplace/actions/publish-aur-package

**Comment by wez** [comment]
I was looking into this tonight too; @ragouel: I am `wez` on AUR; would you mind transferring the bin package to me?  @PedroHLC (hi again!) would you mind transferring the source package to me too?

**Comment by ragouel** [comment]
Sure.

**Comment by wez** [comment]
> Sure.

Thanks!

**Comment by wez** [comment]
I took a stab at adding one for nightly builds:
https://aur.archlinux.org/packages/wezterm-nightly-bin/
This one uses the AppImage so it has fewer arch dependencies because (almost!) everything needed is included from the build machine.

**Comment by PedroHLC** [comment]
Ok, you're now maintainer of https://aur.archlinux.org/packages/wezterm-git/

**Comment by wez** [comment]
> Ok, you're now maintainer of https://aur.archlinux.org/packages/wezterm-git/

Thanks!

**Comment by prabirshrestha** [comment]
I tried `wezterm-nightly-bin`. It works.

**Comment by wez** [comment]
When it comes to writing up the installation instructions, do you guys have a preferred AUR helper to install/update things?  I'm not terribly familiar with Arch and the raw steps feel a bit manual!

I found `yay` but I don't know if "everyone" is using something else :)

**Comment by wez** [comment]
OK, we now have these building current versions when run manually; these all now include the .desktop and icon files for better integration with various window managers, as well as including the color scheme files.

* https://aur.archlinux.org/packages/wezterm-git/
* https://aur.archlinux.org/packages/wezterm-nightly-bin/
* https://aur.archlinux.org/packages/wezterm-bin/

**Comment by PedroHLC** [comment]
The thing with arch is that you'll never know what is being used besides "base" package.
You can just leave the AUR link, people will know what to do from there.

**Comment by prabirshrestha** [comment]
There are too many AUR package managers. Arch folks will know what to use so just adding links as mentioned above would be good.

Thanks for the quick turnaround.
