### ISSUE TITLE
Ssh fails because working directory from local domain doesn't exist

### ISSUE THREAD

**Issue by TomiBelan** [wez/wezterm#2092]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220605-063531-e7258e0e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hi Wez! Nice terminal!

The current process working directory from my Windows cmd.exe tab is reused in a (non-multiplexed) ssh tab. The server says the directory doesn't exist, and exits with an error.

### To Reproduce

1. Use below configuration (with username and hostname of a normal Linux server)
2. Start wezterm normally. The first tab will say e.g.: `C:\Users\Tomi>`
3. Right click the new tab button
4. Select "New tab (domain my_ssh)"
5. Enter your password

Result:
```
Using libssh-rs to connect to example@example.com:22
SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.7
Password:
env: cannot change directory to 'C:/Users/Tomi/': No such file or directory

⚠️  Process RemoteSshDomain didn't exit cleanly
Exited with code 125.
This message is shown because exit_behavior="CloseOnCleanExit"
```

### Configuration

```lua
return {
  ssh_domains = {
    {
      name = "my_ssh",
      remote_address = "example.com",
      username = "example",
      multiplexing = "None",
      assume_shell = "Posix",
    }
  },
}
```

### Expected Behavior

A) The new pane should inherit the previous pane's working directory only if they are in the same domain.
Actually, the diagram at https://wezfurlong.org/wezterm/config/lua/config/default_cwd.html already says "Does current pane have same domain and have a value set by OSC 7?". Maybe the problem is that the node "Can cwd be resolved via the process group leader?" should also have a same domain check.

AND/OR

B) The ssh command should still work if the directory doesn't exist. Instead of `env -C DIR VAR=value $SHELL` maybe `cd DIR ; env VAR=value $SHELL` would work. Or `cd DIR 2>/dev/null ; env VAR=value $SHELL` if you don't want to show the error.

### Anything else?

This only fails in nightly, because of the fix for #2036. In the last stable release it works correctly by coincidence because the cmd.exe working directory detection was broken.

wezterm used to use `cd` before 25b4b3ff87829c14017df28376e486b83606e6a9.

**Comment by TomiBelan** [comment]
Thanks for the fix! I'll try that build later today and report back.

Just for my curiosity: in d2faa96271d336aad812cb17919e3228f94cfd33, does `resolve_cwd()` deal with both the "set by OSC 7" case and the "resolve via the process group leader" case? (i.e. will the same domain check now pertain to both?)

Will you also implement fix "B)"? For example, even within a single ssh domain, someone could rmdir our cwd. If you're in /foo, run `rmdir /foo` and Ctrl+Shift+T, env will say `cannot change directory to '/foo'` and fail. So fixing both A) and B) sounds best to me.

**Comment by TomiBelan** [comment]
wezterm 20220608-084332-f601c775 works. 👍 

I took a try at implementing B). I didn't feel like making a fork and creating a PR so it's just a patch file. I think `git am /path/to.patch` can apply it. It is just a suggestion, so feel free to modify it or discard it - I don't have a proper dev setup so it might not even build.

[0001-mux-run-command-via-ssh-even-if-dir-doesn-t-exist.patch.txt](https://github.com/wez/wezterm/files/8865170/0001-mux-run-command-via-ssh-even-if-dir-doesn-t-exist.patch.txt)

**Comment by wez** [comment]
This is now fully implemented in `main`
