### ISSUE TITLE
Problem with entering backslashes

### ISSUE THREAD

**Issue by FlamesCN** [wez/wezterm#2095]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

My keyboard is japanese. Entering backslashes "\\" in other terminals has no problem by option + ¥, but using WezTerm show "\<ffffffff\>".

### Configuration

return {
    color_scheme = "Dracula+",
}

**Comment by wez** [comment]
Please try the nightly build
