### ISSUE TITLE
Scrollbar barely noticeable under Gruvbox Dark Theme

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#2101]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220605-223126-4776c8d9

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have a really hard time to see the scrollbar and first I thought it wasn't there at all.

![image](https://user-images.githubusercontent.com/7258858/172848680-e1d42dd0-eb8d-4224-86d6-0037de9c38d0.png)

### To Reproduce

Apply configuration 

### Configuration

```lua
return {
  color_scheme = "Gruvbox Dark",
  enable_scroll_bar = true,
  text_background_opacity = 1.0,
  window_background_opacity = 0.9,
  window_padding = {
    right = "2cell",
  }
```

### Expected Behavior

I thought it would look more like the video in https://wezfurlong.org/wezterm/config/lua/config/background.html

### Anything else?

I tried the following snipped which did not work sadly.

```lua
  colors = {
    scrollbar_thumb = "#e6d4a3";
  };
```

**Comment by wez** [comment]
See https://wezfurlong.org/wezterm/config/lua/wezterm/get_builtin_color_schemes.html for an example of how to override colors from a color scheme

Color schemes have their source of truth in https://github.com/mbadolato/iTerm2-Color-Schemes, so if you wish to propose a change to them, you will need to do so over there so that we can then sync the changes back over here.

**Comment by SuperSandro2000** [comment]
Thanks! That worked. I wouldn't mind if that would be a bit easier to do. Also that I now see the scrollbar can I make it a bit more beautiful and rounded? Something like Konsole would be awesome.

![image](https://user-images.githubusercontent.com/7258858/173185617-f63b98da-4be6-45f5-b44a-57ce7fb54753.png)
