### ISSUE TITLE
Unable to type backticks with german keyboard layout

### ISSUE THREAD

**Issue by CptPotato** [wez/wezterm#2102]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220608-084332-f601c775

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

(originally mentioned in #2098)

I am unable to type backticks \` with a german keyboard layout. The key combination is <kbd>Shift</kbd> <kbd>´</kbd>.
The <kbd>´</kbd> key is located to the left of <kbd>Backspace</kbd>, I believe this is the `+/=` key on the US layout (see [image on wikipedia](https://en.wikipedia.org/wiki/File:KB_Germany.svg)).

This appears to be a regression somewhere between the stable version and current nightly build.

### Configuration

The bug can be reproduced with an empty configuration. Changing `use_dead_keys` has no effect.

### Logs

<details>
<summary>entering a backtick</summary>

```
09:41:49.071  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT | LEFT_SHIFT, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: true, handled: Handled(false) }
09:41:49.073  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftShift, modifiers: SHIFT | LEFT_SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT | LEFT_SHIFT, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
09:41:49.074  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=LeftShift mods=SHIFT
09:41:49.166  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(RightBracket), modifiers: SHIFT | LEFT_SHIFT, phys_code: Some(RightBracket), raw_code: 221, scan_code: 13, repeat_count: 1, key_is_down: true, handled: Handled(false) }
09:41:49.167  ERROR  window::os::windows::window       > unexpected dead key expansion: [96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09:41:49.213  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(RightBracket), modifiers: SHIFT | LEFT_SHIFT, phys_code: Some(RightBracket), raw_code: 221, scan_code: 13, repeat_count: 1, key_is_down: false, handled: Handled(false) }
09:41:49.214  ERROR  window::os::windows::window       > unexpected dead key expansion: [96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09:41:49.288  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: false, handled: Handled(false) }
09:41:49.289  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftShift, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
09:41:49.290  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=LeftShift mods=NONE
```
</details>

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wez** [comment]
Sorry, 3d9898eb54cf4378e9000c478af5bc531c3c359f really really fixes this; the prior version broke AltGr based dead keys
