### ISSUE TITLE
Dolphin: Open in terminal should open the current directory.

### ISSUE THREAD

**Issue by Quackdoc** [wez/wezterm#2103]
**Is your feature request related to a problem? Please describe.**

In Linux and windows, you can use a context menu to open terminals from inside file managers. on desktops etc. it would be nice to have this functionality work in wezterm.

**Describe the solution you'd like**

current behavior just opens wezterm as if it was opened normally, instead of opening at the location specified by the menu

**Comment by Quackdoc** [comment]
I am using dolphin, I think the issue stems from wezterm not opening in the directory it's being called from. 

say you desend into into another directoy most terminals if you launch them via another terminal emulator from that directory will open in said directory. 

Ie in konsole, if I launch `foot` from `/usr/lib` foot will open in `/usr/lib` in contrast, wezterm will still open the default directory, in linux's case usually, `$HOME`

**Comment by Quackdoc** [comment]
I believe this is how most things implement various "open terminal here" functionality

**Comment by wez** [comment]
I see.  wezterm chooses the home dir by default (actual logic is shown here: https://wezfurlong.org/wezterm/config/lua/config/default_cwd.html) for consistency across platforms, as some GUI environments will spawn the terminal with a surprising and undesirable location by default.

In the Nautilus integration, it knows to tell wezterm to use a specific directory.
I think there should probably also be a Dolphin integration that does something similar.

**Comment by wez** [comment]
Thanks to @Anomalocaridid, this should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by reidrac** [comment]
I tried it with Thunar (XFCE) and I didn't see any change, but I don't know if I'm testing it correctly or if the fix doesn't apply to XFCE.

**Comment by Anomalocaridid** [comment]
@reidrac I was only able to replicate the problem in Dolphin on my system. When I tried it with Thunar on my system it wouldn't even open a terminal. Although I should note that I use Sway, not XFCE, so that could be part of it.

**Comment by Quackdoc** [comment]
@wez Im not sure if that fix will work across the board, as some apps will open terminal using the .desktop, but some will open it by simply executing the binary. 

It would be nice to have the option to have that behavior when executing the binary directly. at the very least as something we can enable in config files.

**Comment by reidrac** [comment]
> @wez Im not sure if that fix will work across the board, as some apps will open terminal using the .desktop, but some will open it by simply executing the binary.
> 

I believe this is the case for XFCE.

**Comment by wez** [comment]
@reidrac do you know how whichever app you're using under XFCE figures out that wezterm is even a thing it could run?

If you want to override behavior in your config file, then you could do something like this (nightly build required):

```lua
local wezterm = require 'wezterm'
local mux = wezterm.mux

wezterm.on('gui-startup', function(cmd)
  -- allow `wezterm start -- something` to affect what we spawn
  -- in our initial window. If they didn't specify it, use a default empty SpawnCommand.
  local cmd = cmd or {}
  -- I prefer to use the cwd of the gui process instead of (probably) the home dir
  if not cmd.cwd then
     cmd.cwd = wezterm.procinfo.current_working_dir_for_pid(wezterm.procinfo.pid())
  end
  mux.spawn_window(cmd)
end)

return {}
```

**Comment by Quackdoc** [comment]
Just tested this, it works when launching via terminal and dolphin (after reverting the desktop file fix too) but only on the first window spawned, any additional windows spawned after will default to the old cwd

**Comment by wez** [comment]
Did you install wezterm from the .deb package?

**Comment by wez** [comment]
OK, so my recommendation for this is for folks to use the new `open-wezterm-here` script that is now included in the various packages produced by wezterm's CI, or if that isn't available for some reason, it is a simple shell script that can be copied installed to the user's path:

https://github.com/wez/wezterm/blob/main/assets/open-wezterm-here

The .deb packages register that script as the x-terminal-emulator alternative.

**Comment by ambition-echo** [comment]
I think the problem still exists，I'm using` wezterm 20220921-212238-694ffdbe`

When I open wezterm via context menu in dolphin, it looks ok, But if I don't close this terminal, and open a terminal in another directory in dolphin, The new terminal is still started in the previous directory.

Is this problem not solved? or do I need to config something else?

Looking forward to your reply.

**Comment by wez** [comment]
@ambition-echo are you using the `open-wezterm-here` script?
Does it make sense to also ship a similar `.desktop` file to the one that you linked with wezterm?  Can that be integrated into the main `.desktop` file, or does it need to be a separate file?

**Comment by ambition-echo** [comment]
> are you using the `open-wezterm-here` script? 

Sorry, I don't konw what is this

**Comment by wez** [comment]
@ambition-echo as mentioned above: https://github.com/wez/wezterm/issues/2103#issuecomment-1192596255

**Comment by ambition-echo** [comment]
> @ambition-echo as mentioned above: [#2103 (comment)](https://github.com/wez/wezterm/issues/2103#issuecomment-1192596255)

Ok, I see it, but I don't think this script is useful, because it is not integrated in the file manager. 
As far as I know, dolphin's context menu is controlled by a desktop file, like this
[https://raw.githubusercontent.com/ambition-echo/dolphin-open-in-wezterm/main/open-in-wezterm.desktop](https://raw.githubusercontent.com/ambition-echo/dolphin-open-in-wezterm/main/open-in-wezterm.desktop)

**Comment by ambition-echo** [comment]
Maybe you can put [this](https://raw.githubusercontent.com/ambition-echo/dolphin-open-in-wezterm/main/open-in-wezterm.desktop) desktop file in `~/.local/share/kio/servicemenus/` via the install script, this will work under kde desktop.
