### ISSUE TITLE
Two consecutive backticks change backtick position

### ISSUE THREAD

**Issue by Funami580** [wez/wezterm#2108]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220610-071805-aa4dcbc1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When you type `` (two backticks right next to each other), the backtick position changes.

### To Reproduce

type `` (two backticks right next to each other)

### Configuration

no config

### Expected Behavior

Position stays the same.

### Logs

21:42:51.174  INFO   wezterm_gui::termwindow > OpenGL initialized! NVIDIA GeForce GTX 750 Ti/PCIe/SSE2 4.6.0 NVIDIA 515.48.07 is_context_loss_possible=false wezterm version: 20220610-071805-aa4dcbc1

### Anything else?

![out](https://user-images.githubusercontent.com/63090225/173141665-1d30522e-9757-490c-b45e-e9da3538ecbc.gif)

**Comment by wez** [comment]
That's just the ligatures defined in the JetBrains Mono font.
See https://wezfurlong.org/wezterm/config/font-shaping.html for a way to disable ligatures if you prefer.
Alternatively, you could switch to a different font that doesn't have those ligatures.

**Comment by Funami580** [comment]
Oh, I see. Thanks!
