### ISSUE TITLE
X11: copy/pasting between two wezterm windows can produce stale pastes

### ISSUE THREAD

**Issue by ratmice** [wez/wezterm#2110]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220611-073758-dc947ed0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When you have selected text in a wezterm window, pasting into that window will sometimes paste the selected text rather
than the current contents of the clipboard.

### To Reproduce

In theory this is simple to reproduce, 

1. start up 2 wezterms
2. select the text 'a' in first wezterm using the mouse (with the behavior where that copies it into the x11 pasteboard), 
3. paste it into the first window
4. paste into the second window
5. select text 'b' in the second wezterm
6. paste into the second window
7. paste into the first window

At step 6 you will see 'b' pasted into the first window and at 7 you will see 'a' pasted into first window.

This issue isn't always reproducible, where other running applications usage of the pasteboard can seem to affect reproducibility.
for instance, if you start up an `xterm`, and two `wezterm`'s and repeat the process for all three windows.

with window 1 as a wezterm, window 2 as an xterm, and select/paste in that order, the bug does not appear to reproduce between the wezterms both paste the latest selection from both wezterms and xterms.  So from what I can tell the easiest way to reproduce this is with a minimal x session with just 2 instances wezterm.

### Configuration

wezterm.on("open-uri", function(window, pane, uri)
  return false 
end)

return {
   enable_tab_bar = false,
}

### Expected Behavior

after selecting text 'b' pasting into both windows should produce text 'b'.

### Logs

14:03:04.101 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 560 Series (POLARIS11, DRM 3.44.0, 5.17.13-200.fc35.x86_64, LLVM 13.0.0) 4.6 (Compatibility Profile) Mesa 21.3.8 is_context_loss_possible=false wezterm version: 20220611-073758-dc947ed0
14:03:06.078 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 560 Series (POLARIS11, DRM 3.44.0, 5.17.13-200.fc35.x86_64, LLVM 13.0.0) 4.6 (Compatibility Profile) Mesa 21.3.8 is_context_loss_possible=false wezterm version: 20220611-073758-dc947ed0

### Anything else?

I experienced this running xwayland under sway, discussing this with a user on matrix channel, they were using plain x11,
`X11/qtile`,  I have noticed that if i set `enable_wayland = true,` in my `wezterm.lua` I cannot reproduce, so it appears to be specific to xwayland and x11.

**Comment by ackstorm23** [comment]
I also encountered this problem but only a Xorg system, so XWayland not included.

In my observations,  one of the terminals is able to copy and paste properly, but all of the others can only copy and paste within themselves.

**Comment by ackstorm23** [comment]
I'm  confused why this was tagged with Wayland, when enabling Wayland caused the issue to go away?

**Comment by ratmice** [comment]
The person I was speaking to (I didn't catch their git username) also mentioned they were only able to reproduce it after days.

With XWayland/sway I can basically reproduce it every time, and it happens with both terminals.
At some point in the past, a few releases ago I was also able to reproduce it only intermittently/occasionally.
are you running the latest on git master @ackstorm23 if not which SHA1 or release?

If it helps I launch `wezterm`, via the following shell script which boils down to a fancy way of calling:
`wezterm cli spawn --new-window --cwd file:///${pwd}` or `wezterm`
Where the `--new-window` parameter I imagine could affect this. 

https://gist.github.com/ratmice/72705ded485c59931c221fb6b05944ad

I think a pretty standard `~/.sway/config` but could post the whole thing if it helps...
```
set $term ~/.local/bin/hereterm
```

I'm guessing part of what makes it reproducible easily here is that I don't have other windows which accept copy/paste which interfere with the bug somehow causing it to work.

**Comment by ackstorm23** [comment]
@ratmice I believe I was the person you were speaking with.    I did update to the latest git the day after you reported this,  but not enough time would have passed to reliability recreate the problem from my experience.

**Comment by wez** [comment]
I tagged this as wayland because I haven't seen this on regular X11 and it seemed only to apply to XWayland users.  Wayland has very strict rules about accessing the clipboard that make it far more prone to this sort of issue than straight up X11.

The wayland tag is something I search for when I'm triaging from a linux box running wayland and makes it easier for me to find issues that match that context.

**Comment by ackstorm23** [comment]
I seem to be running into this with Wezterm in wayland mode as well. 

With this command ```while sleep 1; do print -f "sel: %20s\n" "`xsel -o --primary`"; print -f "clip: %20s\n" "`xsel -o --clipboard`"; done``` running in all of the terminals,  I selected and then copied "ratmice opened this issue 9 days ago · 5 comments " from the github issue in firefox.

In the terminals this is repeating

```
ratmice opened this issue 9 days ago · 5 comments
sel:
ratmice opened this issue 9 days ago · 5 comments
clip:
ratmice opened this issue 9 days ago · 5 comments
sel:
ratmice opened this issue 9 days ago · 5 comments
clip:
ratmice opened this issue 9 days ago · 5 comments
```

However if I try to paste into any of those terminals, nothing happens.

**Comment by ackstorm23** [comment]
> If you start wezterm with `WEZTERM_LOG=window::os::x11=trace,info` set in the environment, wezterm will log the incoming X events to its stderr and its log file which is typically at a path something like `$XDG_RUNTIME_DIR/wezterm/wezterm-gui-log-PID.txt`.

I did an `EXPORT WEZTERM_LOG=window::os::x11=trace,info set` and then executed `wezterm` to spawn a new window, but it just spawns a new child under the main pid and does not create log files for that pid.

I'll kill wezterm off entirely and start a new one, but it may be days before the issue pops up again to report on.

**Comment by ackstorm23** [comment]
After closing all wezterm's and opening a 4 new ones, I immediately ran into this.   

However nothing is generated in the logs  when I try to paste unsuccessfully in the second terminal. :/

**Comment by Funami580** [comment]
@ackstorm23 Are you using the nightly builds? Also, isn't `xsel` for X11? If you are using `enable_wayland = true`, shouldn't you use `wl-paste` or `wl-paste -p`?

**Comment by ackstorm23** [comment]
> @ackstorm23 Are you using the nightly builds? Also, isn't `xsel` for X11? If you are using `enable_wayland = true`, shouldn't you use `wl-paste` or `wl-paste -p`?

A person in matrix suggested I use xsel, I'll try it with wl-paste next.

I built git last Thursday, so this is a recent codebase.
