### ISSUE TITLE
Neovim's title and titlestring options don't work when TERM=wezterm

### ISSUE THREAD

**Issue by frabjous** [wez/wezterm#2112]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220611-073758-dc947ed0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In order to get fancy undercurls, etc., in neovim, I followed the instructions [here](https://wezfurlong.org/wezterm/faq.html?highlight=undercurl#how-do-i-enable-undercurl-curly-underlines) to install the wezterm terminfo and put `term = "wezterm"` in my wezterm.lua.

The undercurls work great. 

However, since making that change, neovim's [title](https://neovim.io/doc/user/options.html#'title') and [titlestring](https://neovim.io/doc/user/options.html#'titlestring') options no longer work to set the pane title. They do work if I do `TERM=xterm-256color nvim`, but of course I then lose the undercurls.

I appears that the terminfo for wezterm does not properly inform nvim of the right escape codes for setting the title.

### To Reproduce

Start wezterm with the configuration given below (so `TERM=wezterm`). Then run:
```
nvim -u NONE -c 'set title' -c 'set titlestring=xxx'
```
Compare with:
```
TERM=xterm-256color nvim -u NONE -c 'set title' -c 'set titlestring=xxx'
```

### Configuration

I've tested the issue when wezterm.lua is simply:

```
return { term = "wezterm" }
```

### Expected Behavior

The pane title should be 'xxx'. Instead it is simply 'nvim' or whatever it was set to by the underlying shell.

### Logs

Log is simply this:
```
11:19:54.214 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) HD Graphics 630 (KBL GT2) 4.6 (Compatibility Profile) Mesa 22.1.1 is_context_loss_possible=false wezterm version: 20220611-073758-dc947ed0
```

### Anything else?

I realize the issue might be on Neovim's side. Happy to file a bug with them instead if that's the case.

Interestingly, I can get both undercurls and title setting to work if I set `TERM=xterm-kitty`, but that doesn't seem like the right "solution".

**Comment by frabjous** [comment]
Follow up: osc-copy and similar tools for copying to the clipboard by means of escape codes over ssh also weren't working when TERM=wezterm, but work when TERM=xterm-256color....

I decided to try my hand at improving things, but I don't really know what I'm doing. I downloaded [terminfo.src from the ncurses site](https://invisible-island.net/ncurses/ncurses.html)

I added the entry:

```
wezterm|Wez's terminal emulator,
  use=xterm-256color,
  Tc,
  sitm=\E[3m, ritm=\E[23m,
  Cr=\E]112\007, Cs=\E]12;%p1%s\007, Ms=\E]52;%p1%s;%p2%s\007, Se=\E[2\sq,
  Ss=\E[%p1%d\sq,
  Smulx=\E[4:%p1%dm,
  Sync=\E[?2026%?%p1%{1}%-%tl%eh,
  Setulc=\E[58:2::%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%d%;m,
  Smol=\E[53m,
```
Trying to mix what was in the file linked from the FAQ page with xterm-256color's abilities. 

Anyway that got osc-copy to work, but still no luck with neovim's titles.

**Comment by MuhammedZakir** [comment]
It seems like Neovim uses the value of `TERM` instead of checking terminfo caps for this. I have verified this by changing `wezterm` in `wezterm.terminfo` to `xterm-wezterm-256color`. If you want full compatibility with TUI apps [1], then use `xterm-256color` as the name.

[1] Many apps still check for `xterm` instead of checking terminfo caps.

**Comment by frabjous** [comment]
THanks for your reply!

Let me make sure I understand. So the idea is still to use `wezterm.terminfo` but change the first uncommented line to something like `xterm-256color|Wez's terminal emulator,`, and then remove `term = 'wezterm'` from the settings table in wezterm.lua?

It makes me a little nervous to redefine an existing terminfo entry, but I'm trying it now and so far it seems to be working well. The undercurls and osc-copy and the like seem to work, as well as neovim's title/titlestring options.

Would you consider it a bug in neovim that it just checks for "xterm" rather than checking terminfo caps? Happy to redirect the issue to their tracker if that makes more sense.

**Comment by MuhammedZakir** [comment]
> Thanks for your reply!

You're welcome! :-)

> Let me make sure I understand. So the idea is still to use `wezterm.terminfo` but change the first uncommented line to something like `xterm-256color|Wez's terminal emulator,` , and then remove `term = 'wezterm'` from the settings table in wezterm.lua?

Yes.

> It makes me a little nervous to redefine an existing terminfo entry, but I'm trying it now and so far it seems to be working well. The undercurls and osc-copy and the like seem to work, as well as neovim's title/titlestring options.

I understand. But because many apps still use `TERM` env var to check for capabilities, this solution is the one that works consistently. As long as you don't overwrite existing terminfo entry, it seems fine to me.

> Would you consider it a bug in neovim that it just checks for "xterm" rather than checking terminfo caps? Happy to redirect the issue to their tracker if that makes more sense.

I would open an issue there.

**Comment by wez** [comment]
It sounds like this is primarily a neovim bug, but is there something that should also be added to the wezterm terminfo file?

**Comment by MuhammedZakir** [comment]
> It sounds like this is primarily a neovim bug, but is there something that should also be added to the wezterm terminfo file?

A doubt: shouldn't WezTerm's terminfo entry be based on `xterm-direct` or `xterm-direct256` rather than `xterm-256`?

**Comment by wez** [comment]
I don't think there is a clear "winner" between those:

```
; infocmp -d xterm-direct256 xterm-256color
comparing xterm-direct256 to xterm-256color.
    comparing booleans.
        ccc: F:T.
    comparing numbers.
        colors: 16777216, 256.
        pairs: 65536, 32767.
    comparing strings.
        initc: NULL, '\E]4;%p1%d;rgb:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\'.
        ka1: '\EOw', NULL.
        ka3: '\EOy', NULL.
        kb2: '\EOu', '\EOE'.
        kc1: '\EOq', NULL.
        kc3: '\EOs', NULL.
        kmous: '\E[<', '\E[M'.
        mgc: '\E[?69l', NULL.
        nel: '\EE', NULL.
        oc: NULL, '\E]104\007'.
        rs1: '\Ec', '\Ec\E]104\007'.
        setab: '\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e%?%p1%{256}%<%t48;5;%p1%d%e48:2::%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%d%;%;m', '\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m'.
        setaf: '\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e%?%p1%{256}%<%t38;5;%p1%d%e38:2::%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%d%;%;m', '\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m'.
        smglr: '\E[?69h\E[%i%p1%d;%p2%ds', NULL.
```

**Comment by jdhao** [comment]
@MuhammedZakir  Hi, do you open an issue on neovim?

**Comment by wez** [comment]
4ed2fd8e94387fa597b5769c2e91212c2ee4d970 updates the terminfo file for this. The nvim folks are planning to make that fallback the default in a future release

**Comment by frabjous** [comment]
This is great, thanks!
