### ISSUE TITLE
Diversifying non clean exits

### ISSUE THREAD

**Issue by yashpalgoyal1304** [wez/wezterm#2113]
### Is your feature request related to a problem? Please describe.
#1004 

### Describe the solution you'd like
For non-clean exits, some option like following will ease the situation very much: 

```
[Process didn't exit cleanly. (exit_behavior="CloseOnCleanExit")]

Choose any of the following to continue:
    Reopen at
    Exit
```

* "Reopen at" \
will ask for a location, and will open the shell at that location

* "Exit" \
will function as a shortcut for clicking close button and choosing yes

### Describe alternatives you've considered

Following were the options i considered earlier, these are both suitable individually, but the above combo seems to make much more sense to me.

* "Press any key (or some specific key) to exit" \
Pretty self explanatory. I have seen this in many other places as well.

* "Exiting in 25s" - timeout for auto exit

### Additional context
https://wezfurlong.org/wezterm/config/lua/config/exit_behavior.html

### Versions
* Wezterm : `wezterm 20220319-142410-0fcdea07` and `wezterm 20220408-101518-b908e2dd`
* OS: Win 10 20H2

**Comment by yashpalgoyal1304** [comment]
the keys for selection can be "o" for reopen, and "x" for exit. and this can be underlined to indicate.

**Comment by bew** [comment]
Related issues: #2080 #580
Both issues request a way to do some action (optionaly keyboard based) when a pane exits.

**Comment by yashpalgoyal1304** [comment]
awesome

**Comment by wez** [comment]
I'm going to close this as there are other overlapping issues already open
