### ISSUE TITLE
Provide hashes for download files integrity checking

### ISSUE THREAD

**Issue by yashpalgoyal1304** [wez/wezterm#2114]
* Currently, no file integrity checksum file is provided.
* `sha256sum` GNU core-utility can be used to generate a single `.sha256` file which will contain the hashes of all the file for a particular release version, this makes verifying much straightforward

E.g. https://github.com/wez/wezterm/releases/tag/20220408-101518-b908e2dd

**Comment by jirutka** [comment]
Or you can provide just one `checksums.txt` file that will contain a hash of every other file in the release. It can be used like this:

```sh
curl -sSLO https://github.com/jirutka/tty-copy/releases/download/v0.2.2/tty-copy.x86_64-linux
curl -sSL https://github.com/jirutka/tty-copy/releases/download/v0.2.2/checksums.txt | sha256sum -c --ignore-missing
```

**Comment by wez** [comment]
Each artifact now has a corresponding `.sha256` file. You can see those in the [nightly release](https://github.com/wez/wezterm/releases/tag/nightly); they will get populated for subsequent releases: I'm not going to back-fill prior releases.

Combining them into a single file is a distributed computing synchronization problem that I don't have time or plans to tackle: one per artifact file seems fine to me.

**Comment by yashpalgoyal1304** [comment]
awesome

i had one question: 
* how did u write the same thing at all those places in https://github.com/wez/wezterm/commit/360b3f347902d610ba307b41c40ff8a5cafb37ba ?? 
* wasn't it cumbersome and error prone? 
* or was there some single/few places (like configuration files etc) where you entered and it got automatically populated in everywhere??

**Comment by wez** [comment]
Doing it by hand would be horrible! https://github.com/wez/wezterm/blob/main/ci/generate-workflows.py is used to automate that and avoid living in yaml hell
