### ISSUE TITLE
Process "/usr/bin/fish" in domain "local" didn't exit cleanly

### ISSUE THREAD

**Issue by mostafaqanbaryan** [wez/wezterm#2122]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220601-204427-3dfb5701

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When a program in `fish` crashes or closes with an exit code that is not zero, fish keeps that exit code.
And when I want to close that shell/pane:
![image](https://user-images.githubusercontent.com/94293456/173517433-0063f615-4e07-49ba-8700-17c26b9c5cfb.png)

### To Reproduce

1. Install fish shell.
2. `Telnet xx.xx.xx.xx` to a non-exist ip address.
3. Telnet get closed by exit code 1.
4. Type `exit`

### Configuration

no config

### Expected Behavior

Close pane when there is no process running

### Anything else?

I don't know if there is expected behavior or this problem exists because of fish.

**Comment by cadl** [comment]
I used to have the same confusion. You can change your [exit_behavior](https://wezfurlong.org/wezterm/config/lua/config/exit_behavior.html) configuration to ignore it.

**Comment by MuhammedZakir** [comment]
> @cadl Oh, ok.
> So it is a shell problem.
> Maybe there is some way to change the behavior of shell to remove the exit code before closing the shell.

I don't recommend doing this; it will create problems in shell scripts. I recommend you to configure WezTerm according to the link posted above.
