### ISSUE TITLE
Gap between tab bar and terminal

### ISSUE THREAD

**Issue by Fingel** [wez/wezterm#2123]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When using wezterm under wayland, sometimes a gap will appear between the tab bar and the terminal window.
![Screenshot from 2022-06-14 14-08-06](https://user-images.githubusercontent.com/3046397/173689842-0a4eb7ac-6ca6-4d41-a732-1a08da7ace6c.png)

### To Reproduce

Open a new window, resize/move it a few times. It cannot be reproduced easily, but I thought it might be good to be aware of it when making decisions about how to implement window decorations on wayland.

### Configuration

```lua
local wezterm = require 'wezterm';

return {
    color_scheme = "Gruvbox Dark",
    default_prog = {"/usr/bin/fish"},
    font = wezterm.font("Fira Code"),
    enable_scroll_bar = false,
    enable_wayland = true,
    font_size = 14,
    window_background_opacity = 0.98,
}
```

**Comment by wez** [comment]
Can you try the nightly build and see it is still an issue there? There have been some relatively recent adjustments to how the tab bar is rendered and I wonder if they might have resolved this.

**Comment by Fingel** [comment]
OK, I just installed wezterm-nightly-bin from the AUR, I'll keep an eye on it.

**Comment by Fingel** [comment]
Yes, that looks exactly like it. I'd say this is a duplicate of #1620.
