### ISSUE TITLE
default_cwd is only considered on startup not new tabs

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#2126]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220614-094817-62744bf0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am only put into the wsl_domains.default_cwd on startup. Any new tab ignores that.

### To Reproduce

- Start wezterm in WSL
- open a new tab

### Configuration

```lua
local wezterm = require("wezterm")

local wsl_domains = wezterm.default_wsl_domains()

for _, dom in ipairs(wsl_domains) do
  if dom.name == "WSL:NixOS" then
    dom.default_cwd = "/home/nixos"
  end
end

return {
  default_domain = "WSL:NixOS",
  default_prog = { "wsl.exe" },
  wsl_domains = wsl_domains,
}
```

### Expected Behavior

All tabs open in the same directory.

### Logs

```
14:03:24.890  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow←[0m > OpenGL initialized! Intel(R) UHD Graphics 4.5.0 - Build 30.0.101.1122 is_context_loss_possible=true wezterm version: 20220614-094817-62744bf0                                   14:03:28.351  ←[33mWARN  ←[0m ←[1mwezterm_term::terminalstate←[0m > unhandled XtermKeyMode OtherKeys Some(1)            14:03:28.353  ←[33mWARN  ←[0m ←[1mwezterm_term::terminalstate←[0m > unhandled XtermKeyMode OtherKeys Some(2)            14:03:31.807  ←[33mWARN  ←[0m ←[1mwezterm_term::terminalstate←[0m > unhandled XtermKeyMode OtherKeys Some(1)            14:03:31.808  ←[33mWARN  ←[0m ←[1mwezterm_term::terminalstate←[0m > unhandled XtermKeyMode OtherKeys Some(2)
```

### Anything else?

I tried it with default_cwd = "/var/lib" which only worked for the first tab.

**Comment by wez** [comment]
Running with this config:

```lua
local wezterm = require("wezterm")
local wsl_domains = wezterm.default_wsl_domains()

for _, dom in ipairs(wsl_domains) do
    dom.default_cwd = "~"
end

return {
  wsl_domains = wsl_domains,
}
```

opening the first tab in the wsl domain puts me in the home dir.
Spawning new tabs when the wsl panes are active will copy the cwd from the pane and use it for the new one.
I have shell integration installed inside wsl.

This behavior is consistent with the flow chart shown at https://wezfurlong.org/wezterm/config/lua/config/default_cwd.html

**Comment by SuperSandro2000** [comment]
I think my shell integration broke somehow in the last months. It would be nice to have some way to query if it is enabled and working like it should.
