### ISSUE TITLE
allow_win32_input_mode = true breaks {[]} inputs on German keyboard in wsl

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#2127]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220614-094817-62744bf0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Since https://github.com/wez/wezterm/commit/b59b51ee2aed4b274588ac09abcc8c44e56c1dff I can not longer input the follow characters ``{[]}`` on a German keyboard (like https://upload.wikimedia.org/wikipedia/commons/f/fd/German-Keyboard-Layout-T2-Version2-large-alternative-style.png) with the <kbd>AltGr</kbd>+<kbd>8</kbd> key combination.

### To Reproduce

- open default wezterm
- press <kbd>AltGr</kbd>+<kbd>8</kbd>

### Configuration

default configuration

### Expected Behavior

to work like before without needing to set ``allow_win32_input_mode = false``

**Comment by wez** [comment]
Looks like it is only wsl that gets broken by this.  Asking for assistance in 
https://github.com/microsoft/terminal/discussions/13239#discussioncomment-2977049

**Comment by wez** [comment]
e0616e5eb fixes this for me!

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by SuperSandro2000** [comment]
works again, thanks!
