### ISSUE TITLE
wezterm does not fit dwm window after change font size

### ISSUE THREAD

**Issue by huibosa** [wez/wezterm#2129]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220612-201748-75066cb5

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using dwm as window manager (no desktop environment) under x11.

After Using `Ctrl+-` to decrease font size,  the terminal will not fit the window:

![smaller](https://user-images.githubusercontent.com/78707242/174228323-267a7c81-2a5e-43ff-a568-e5e818de1fc7.png)

Then Using `Ctrl+0` to resume font size, the will be a gap between terminal and window border, which can be erased when change window size:

![2022-06-17_12-46](https://user-images.githubusercontent.com/78707242/174227815-7d281a96-fbbc-42c4-b0c0-9fa1905055d5.png)

Using `Ctrl+=` will make terminal get outside of window (Only part of terminal is visible in window).

### Configuration

no config

**Comment by bew** [comment]
Checkout the [adjust_window_size_when_changing_font_size](https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html) option.
> If you use a tiling window manager then you may wish to set this to `false`.

**Comment by huibosa** [comment]
> Checkout the [adjust_window_size_when_changing_font_size](https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html) option.
> 
> > If you use a tiling window manager then you may wish to set this to `false`.

It worked, thank you sir.
