### ISSUE TITLE
Provide a way to see all current key bindings

### ISSUE THREAD

**Issue by ittaysw** [wez/wezterm#2134]
This is useful for debugging as well as finding a new assignment that doesn't conflict with existing ones. 

For me, for example, splitting with Ctrl-Shift-Alt-% and Ctrl-Shift-Alt-" does not work and I don't know why or what other combination may have been assigned to these actions. I couldn't find any wezterm.lua file.

**Comment by MuhammedZakir** [comment]
Is it possible to change the representation of keys? Some of them are hard to understand. For instance, `Escape` is shown as `\u{1b}`. Functions keys are shown in `Function(x)` format.
