### ISSUE TITLE
In vim normal model, `Ctrl + i` does not work as expected (i.e. does not move forward in jump list)

### ISSUE THREAD

**Issue by krishnakumarg1984** [wez/wezterm#214]
## Bug description

Inside `vim`, after performing a jump action to a previous position, the `Ctrl + i` sequence is used to jump forward in the jump list.

## Environment (please complete the following information):

 - OS: macOS
 - Version: wezterm 20200608-110940-3fb3a61
 - Vim: 8.2.0539

## To Reproduce

1. Fire up `vim` without any plugins or startup file like so: `vim -u NONE`
2. Open up any moderately long text file.  Just as an example to demo this issue, in normal mode, perform a sequence of some random jumps, eg. `G`, `gg`, `50%`,`25%`, `75%`
3. Now, press `Ctrl + o` to go to an older position
4. Now, press `Ctrl + i` to go forward in jump list (i.e. to the newer position)
4. `vim` unexpectedly enters insert mode!

## Configuration

This issue occurs even with a default install of `wezterm`. No specific configuration file was created.

## Expected behavior

`vim` should jump forward in the jump list when `Ctrl + i` sequence is pressed in normal mode.

## Additional context

The same issue occurs in `neovim (v0.4.3)` as well.

**Comment by wez** [comment]
(this is the same underlying issue as #213

**Comment by krishnakumarg1984** [comment]
Thanks for the fix!

**Comment by krishnakumarg1984** [comment]
@wez Hopefully this will make it to `homebrew` soon.

**Comment by wez** [comment]
I tend to review and tag releases roughly every 4-6 weeks, and we just had a tag last weekend.

You can however use `brew install --HEAD wezterm` to pick up the nightly build via our homebrew tap!

**Comment by krishnakumarg1984** [comment]
@wez Using the `head` (nightly) version shall not work for me because every `brew update` will trigger downloads everyday, and I am on a metered internet connection.

Perhaps it is best for me to wait out until the next release.

**Comment by wez** [comment]
`brew update` just syncs the recipe definitions.  `brew upgrade` is what will install recipes if their versions have changed.  If you have performed a HEAD install, `brew` will consider you to already be on head and won't actually upgrade unless you first uninstall; I tried this just now:

```bash
$ brew upgrade wezterm
Warning: wez/wezterm/wezterm HEAD already installed
```

so I don't think this will impose any additional cost on your metered connection.
WezTerm will display a window advising you of when the next tag is made,
and at that time you can switch back to the normal tagged install if you wish.

**Comment by krishnakumarg1984** [comment]
@wez Installing from `brew HEAD` did not work for me and gave me the following errors:

>You can’t open the application “WezTerm.app” because it may be damaged or incomplete.

Do you think this is because of `macOS` Catalina's System Integrity Protection (SIP) coupled with developer signing policies?
