### ISSUE TITLE
Held-down key repetition does not work for certain keys on macOS when use_ime is enabled (the default)

### ISSUE THREAD

**Issue by krishnakumarg1984** [wez/wezterm#215]
## Bug description

When they are held down, only some keys seem to respond (i.e. repetition does not work for quite a few keys)

## Environment

 - OS: macOS
 - Version: wezterm 20200608-110940-3fb3a61

## To Reproduce

1. Fire up `wezterm` without any special config file 
2. At the default `bash` prompt, hold down various keys (`a`,`b`,`c`,`d` and so on)
3. Notice that only certain keys support repetition
4. Even those keys which repeat seem quite slow

## Configuration

This issue occurs even with a default install of `wezterm`. No specific configuration file was created.

## Expected behavior

Smooth repetition of all keys on the keystrokes is expected when repeated. A config parameter for the key-repeat rate might also help (feature creep?)

## Additional context

This is helpful for `vim` users who (ab)use `j`,`k` etc. motions by holding them down.

**Comment by wez** [comment]
You may wish to try setting `use_ime = false` so that the macOS input method editor doesn't get in the way of processing repeats.

**Comment by wez** [comment]
For context on this: the macOS IME can swallow key repeats in a number of situations, which seems to be related to its ability to hold down a key to pop up a UI with accented variants of a given glyph.  I'm not aware of a way to make repeats work better when the IME is enabled, but it is possible to disable the IME and allow the normal key repeat processing to kick in.

**Comment by krishnakumarg1984** [comment]
This problem does not occur on iterm2. Does iterm2 disable IME?

**Comment by krishnakumarg1984** [comment]
Okay. This works now! Thanks a lot for your help in solving this issue.
