### ISSUE TITLE
Switching tabs should occur on key down, not key up

### ISSUE THREAD

**Issue by evanrelf** [wez/wezterm#2151]
**Is your feature request related to a problem? Please describe.**

Normally actions are performed on key down/press, not key up/release. <kbd>Command</kbd>-<kbd>N</kbd> opens a new window on key down, <kbd>Command</kbd>-<kbd>T</kbd> opens a new tab on key down, <kbd>Command</kbd>-<kbd>W</kbd> closes the window on key down, etc.

Switching tabs with <kbd>Control</kbd>-<kbd>Tab</kbd> and <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>Tab</kbd> performs the action on key _up_, which is inconsistent.

In addition to being inconsistent, this has been causing me issues with incorrect input: my muscle memory expects the action on key down, so sometimes I accidentally release the modifier _before_ releasing <kbd>Tab</kbd>, which gets interpreted as just <kbd>Tab</kbd>.

**Describe the solution you'd like**

Switching tabs with Control-Tab and Control-Shift-Tab happens on key _down_, not _up_.

**Describe alternatives you've considered**

- Allow configuring whether an action is performed on key down or up (I don't care about this personally)
- Do nothing (doesn't solve the problem)

**Additional context**

- macOS 12.4 (21F79)
- wezterm 20220408-101518 ([`b908e2dd`](https://github.com/wez/wezterm/commit/b908e2dd8cd27c613c8d76e9e6abc5245e500d7d))
- My configuration: https://github.com/evanrelf/dotfiles/blob/edc4ca7a27f5f981654820410afc80c9b99f17b9/configs/wezterm/.config/wezterm/wezterm.lua (still a problem when started with `wezterm --config-file=/dev/null`)

**Comment by wez** [comment]
That's a macOS quirk that I think has been resolved in the nightly build; please try it!

**Comment by evanrelf** [comment]
Fixed in the nightly build 👍
