### ISSUE TITLE
Gruvbox Light.toml has inverted ansi/bright colours

### ISSUE THREAD

**Issue by gravndal** [wez/wezterm#2160]
https://github.com/wez/wezterm/blob/14282f99bc8709e0f86607714021043fc56c4c9c/assets/colors/Gruvbox%20Light.toml#L11-L12

The non-white ansi/brights colours are inverted when compared to the original vim colorscheme: https://github.com/morhetz/gruvbox.

Direct link to image showing original light palette: https://camo.githubusercontent.com/d080d9c204408ef06b862b76bc795f930b3a9b1be4c5d2de149f1d8eb765b660/687474703a2f2f692e696d6775722e636f6d2f3439714b7959572e706e67

The corrected colour arrays should be:
```
ansi    = ['#fbf1c7','#cc241d','#98971a','#d79921','#458588','#b16186','#689d69','#7c6f64']
brights = ['#9d8374','#9d0006','#79740e','#b57614','#076678','#8f3f71','#427b58','#3c3836']
```

Note that the brights are actually darker, which in turn makes them stand out more when set against the light background.

**Comment by wez** [comment]
The color schemes are synced from the upstream https://github.com/mbadolato/iTerm2-Color-Schemes project.
Please file this issue over there and we can sync back the changes once they have been merged there.

**Comment by wez** [comment]
Nightly builds of wezterm include some other variants of gruvbox synced from Gogh and base16 projects.
You can browse how they look starting at: https://wezfurlong.org/wezterm/colorschemes/g/index.html#gruvbox-gogh and scrolling down from there.
