### ISSUE TITLE
Ctrl+Shift+u unicode input on Linux

### ISSUE THREAD

**Issue by seqizz** [wez/wezterm#2163]
**Is your feature request related to a problem? Please describe.**
Afaik Linux does not support alt codes, but we can have nice things with Ctrl-Shift-u [unicode input method](https://fsymbols.com/keyboard/linux/unicode/). This seems not supported.

**Describe the solution you'd like**
Most other GUI apps / some terminal emulators supports it. It might be nice to have on wezterm.

**Describe alternatives you've considered**
Copy-paste :grimacing: 

**Additional context**
nil

**Comment by tpoliaw** [comment]
An alternative that already works is to use the [compose key](https://help.ubuntu.com/community/ComposeKey). eg `RightAlt`, `"`, `a` = `ä`

**Comment by wez** [comment]
`main` now has a character selector overlay which you can activate with `CTRL-SHIFT-U` (`u` for unicode). It looks like this:

![image](https://user-images.githubusercontent.com/117777/187812301-df0f232b-747e-4052-8bf1-c1c2aeae344d.png)

Blurb from the commit message:

CTRL-SHIFT-U is a new default key assignment for this new modal.
It opens up a fuzzy searchable browser that defaults to showing
emoji/emoticons.  The category can by cycled through the suggested
emoji categories using CTRL-r.  Unlike the system emoji palette,
wezterm includes a category for nerdfont symbols, and another
that is a list of all unicode codepoint names, so you should be
able to browse for pretty much any codepoint you can think of.

The modal also allows fuzzy searching based on:

* The official unicode name
* The github shortcode
* codepoint value in hex

so if you know the codepoint value but not the name, you can
still find a way to input what you're looking for.

Pressing Enter will copy the selected item to the clipboard
send it to the active pane, and cancel the modal. You can therefore
repeat the insert by simply pasting.

I plan to add frecency to this in a later commit: that way the
frequently/recently used selections will show in a category of
their own and make it easier to re-input them.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by MuhammedZakir** [comment]
> Pressing Enter will copy the selected item to the clipboard

Can you add an option to send it to the active pane without copying it to clipboard?

**Comment by seqizz** [comment]
Oh wow sorry for late response. This is way more than enough, thanks for the effort :tada:
