### ISSUE TITLE
Unified scroll/copy/search mode bindings have no effect 

### ISSUE THREAD

**Issue by NikosEfthias** [wez/wezterm#2170]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220624-171939-c29a513a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I copy pasted the config from wez's reply [here](https://github.com/wez/wezterm/issues/1592#issuecomment-1118722289)
however it doesn't seem to do anything

### To Reproduce

- Go into copy mode using `<C-S-x>`
- hit `/` for search mode (nothing happens)
- activate search mode manually via `<c-s-f>`
  - search something
  - activate copy mode via `<c-s-x>` 
  - at this point its impossible to clear selection from search mode

### Configuration
```
local wezterm = require("wezterm");
return {
	font = wezterm.font("Fira Code"),
	color_scheme = "OneHalfDark",
	font_size = 16,
	send_composed_key_when_left_alt_is_pressed = false,
	send_composed_key_when_right_alt_is_pressed = true,
	native_macos_fullscreen_mode = true,
	hide_tab_bar_if_only_one_tab = true,
	use_fancy_tab_bar = false,
	tab_bar_at_bottom = true,
	keys = {
		{ key = "e", mods = "SUPER", action = wezterm.action { SplitHorizontal = {} } },
		{ key = "e", mods = "SUPER|CTRL", action = wezterm.action { SplitVertical = {} } },
		{ key = "k", mods = "SUPER|ALT", action = wezterm.action { ActivatePaneDirection = "Prev" } },
		{ key = "j", mods = "SUPER|ALT", action = wezterm.action { ActivatePaneDirection = "Next" } },
		{ key = "L", mods = "CTRL", action = "DisableDefaultAssignment" },
		{ key = "Z", mods = "CTRL", action = "DisableDefaultAssignment" },
		{ key = "z", mods = "SUPER", action = "TogglePaneZoomState" },
		copy_mode = {
			{ key = "Escape", mods = "NONE", action = wezterm.action { CopyMode = "Close" } },
			{ key = "h", mods = "NONE", action = wezterm.action { CopyMode = "MoveLeft" } },
			{ key = "j", mods = "NONE", action = wezterm.action { CopyMode = "MoveDown" } },
			{ key = "k", mods = "NONE", action = wezterm.action { CopyMode = "MoveUp" } },
			{ key = "l", mods = "NONE", action = wezterm.action { CopyMode = "MoveRight" } },
			-- Enter search mode to edit the pattern.
			-- When the search pattern is an empty string the existing pattern is preserved
			{ key = "/", mods = "NONE", action = wezterm.action { Search = { CaseSensitiveString = "" } } },
			-- navigate any search mode results
			{ key = "n", mods = "NONE", action = wezterm.action { CopyMode = "NextMatch" } },
			{ key = "N", mods = "SHIFT", action = wezterm.action { CopyMode = "PriorMatch" } },
		},
		search_mode = {
			{ key = "Escape", mods = "NONE", action = wezterm.action { CopyMode = "Close" } },
			-- Go back to copy mode when pressing enter, so that we can use unmodified keys like "n"
			-- to navigate search results without conflicting with typing into the search area.
			{ key = "Enter", mods = "NONE", action = "ActivateCopyMode" },
		},
	},
	--quick_select_patterns={
	--	--"[a-zA-Z.]+",-- any word with a possible dot in it
	--}
}
```

### Expected Behavior

being able to switch between copy and search modes for easy movement any copying in the buffer

### Logs

debug overlay doesn't work either.
had do start another instance from terminal `wezterm 2>&1 | pbcopy`

10:24:38.944  INFO   wezterm_gui::termwindow > OpenGL initialized! Apple M1 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220624-171939-c29a513a

**Comment by bew** [comment]
(note: your key tables should be under the config named `key_tables`, not under `keys`, see: https://wezfurlong.org/wezterm/config/key-tables.html)

**Comment by NikosEfthias** [comment]
@bew that makes sense let me try that :) thanks for pointing out

**Comment by NikosEfthias** [comment]
@bew Selection issue persists tho. Once a selection is made theres no way to clear existing selection and create a new one without exiting the copy mode and reentering which results in loosing the cursor position in the buffer

**Comment by NikosEfthias** [comment]
@wez and whats the act? where do i import that from ?

**Comment by NikosEfthias** [comment]
thanks
