### ISSUE TITLE
Mouse: ScrollUp and ScrollDown events

### ISSUE THREAD

**Issue by Funami580** [wez/wezterm#2173]
**Is your feature request related to a problem? Please describe.**
I would like to use `Ctrl+MouseWheelScroll` to increase/decrease the font size.

**Describe the solution you'd like**
Some binding in the config would be nice, e.g.
```
mouse_bindings = {
    {
      event={ScrollUp},
      mods="CTRL",
      action="IncreaseFontSize",
    },
}
```

**Describe alternatives you've considered**
Just use a keyboard binding.

**Comment by wez** [comment]
It's not documented, but button should recognize wheel events:
https://github.com/wez/wezterm/blob/main/term/src/input.rs#L21-L22

Have you tried something like this?

```lua
mouse_bindings = {
  {
     event={Down={streak=1, button=WheelUp={1}}},
     mods="CTRL",
     action=wezterm.action.IncreaseFontSize,
   }
}
```

it might need some finesse to make it usable: I think both the `streak` and the delta value in the `WheelUp` might make it difficult to match.

**Comment by Funami580** [comment]
I just tried
```lua
mouse_bindings = {
  {
    event={Down={streak=1, button={WheelUp=1}}},
    mods="CTRL",
    action=wezterm.action.IncreaseFontSize,
  },
},
```
but nothing happened.
