### ISSUE TITLE
Issue with `get-deps` script on arch

### ISSUE THREAD

**Issue by daylinmorgan** [wez/wezterm#2175]
## Build Environment (please complete the following information):

 - OS: [e.g. Linux X11, Linux Wayland, macOS, Windows].  If on Linux, Please include `lsb_release -a` in your report.
 - Linux: what distro, version and architecture?  Please include `uname -a` in your report.
 - Compiler: are you using `clang`, `gcc`, `Microsoft Visual Studio` or something else?  Which version?
 - Rust version: Please include the output from `rustup show`. Best results are
   generally had with a recent stable version of the rust toolchain.

## Dependencies

Did you run the `get-deps` script to install required system dependencies?
Was it successful?

**Wasn't successful due to what is I suspect a typo in the arch dependencies.**

If building from the git repo, did you update the submodules?  Not doing this
is a common source of problems; see the information at
<https://wezfurlong.org/wezterm/install/source.html> for more information.

## The build output

Please include the output from running the build command:

```
cargo build --release
```

--------------

Based on the other distro sections I assume this should be the change:
```diff
diff --git a/get-deps b/get-deps
index 63f1dd1..bd353f6 100755
--- a/get-deps
+++ b/get-deps
@@ -180,9 +180,9 @@ arch_deps() {
     'xcb-util-keysyms' \
     'xcb-util-wm'

-  if test_cmd; then
+  if test_flag; then
     $PACMAN -S --noconfirm --needed \
-      'openssh-server'
+      'openssh'
   fi
 }
```

If this looks right I can open a PR.

**Comment by wez** [comment]
Yeah, looks like it should be conditional on `test_flag`. I'll trust your judgement on the name of the openssh dependency; happy to see a PR to fix this!
