### ISSUE TITLE
Macos stable release not found

### ISSUE THREAD

**Issue by lispyclouds** [wez/wezterm#2176]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, this issue is on the latest stable version.

### Describe the bug

The mac installed seems to be unreleased and the `brew install --cask wez/wezterm/wezterm` fails with a 404 error.

### To Reproduce

Try running `brew install --cask wez/wezterm/wezterm`

### Configuration

no config

### Expected Behavior

wezterm is successfully installed.

### Anything else?

Thanks a lot for making this, this is my absolute favourite terminal! ❤️

**Comment by wez** [comment]
Can you include the full 404 error message?

**Comment by lispyclouds** [comment]
Here it is:
```
$ brew install --cask wez/wezterm/wezterm

==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
Running `brew update --auto-update`...

You have 2 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Caveats
Cask wezterm related executables like 'wezterm', 'wezterm-gui',
'wezterm-mux-server', are linked into
  /usr/local/bin/    for x86 Mac,
  /opt/homebrew/bin/ for M1 Mac.

Removal of them is ensured by 'brew uninstall --cask wezterm'.

==> Downloading https://github.com/wez/wezterm/releases/download/20220624-141144-bd1b7c5d/WezTerm-macos-20220624-14114
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'wezterm' with message: Download failed: https://github.com/wez/wezterm/releases/download/20220624-141144-bd1b7c5d/WezTerm-macos-20220624-141144-bd1b7c5d.zip
```

**Comment by lispyclouds** [comment]
I think it should be there in the releases page right? I don't think I can see it [here](https://github.com/wez/wezterm/releases/tag/20220624-141144-bd1b7c5d) ?

**Comment by wez** [comment]
Weird, looks like there are a number of builds labelled nightly there, but they should be release builds

**Comment by wez** [comment]
I renamed the assets with the wrong names and updated the script that generated the workflows to (hopefully!) resolve this for the next tag.
Please try again and let me know if it is working now!

**Comment by lispyclouds** [comment]
Works perfectly now! Thanks a lot for the quick fix! 🚀
