### ISSUE TITLE
Key table activation that lives until unknown key

### ISSUE THREAD

**Issue by bew** [wez/wezterm#2178]
**Is your feature request related to a problem? Please describe.**
In tmux there is a way to define keybinds that can be repeated until you type an unknown key.
That key would be sent to the active pane instead of processed by tmux.

For example we can write a pane management key table that works like this:
1. Ctrl-b then Ctrl-p (for example) to enter pane management keytable
2. Ctrl-Alt-h/j/k/l (multiple times) to create a few panes in various directions
3. Ctrl-h/j/k/l (multiple times) to navigate in the opened panes (NOTE: we're still in the pane management keytable)
4. foobar (just type some letters that are not in the key table)
   The pane management key table is disabled, and `foobar` is inserted in current pane.

**Describe the solution you'd like**
(not sure about the name of the option)
A new option for `ActivateKeyTable` to remove the keytable when an unknown key is typed.

**Describe alternatives you've considered**
Disable the key table manually (but that eats another key!! And I need to think about it!), or wait until a timeout, or retype the key table activation everytime.
All these solution are not optimal compared to the workflow I'm used to with tmux :shrug:

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by bew** [comment]
Thanks a lot, I'll be in vacation tomorrow, will try to try this (:

**Comment by bew** [comment]
Works well, thank you! :)
