### ISSUE TITLE
ActivateKeyTable requires the field `replace_current`, documented as optional

### ISSUE THREAD

**Issue by bew** [wez/wezterm#2179]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

```
callback error
stack traceback:
        [C]: in field 'ActivateKeyTable'
        /home/lesell_b/.config/wezterm/cfg_keys.lua:22: in local 'define_and_activate_keytable'
        /home/lesell_b/.config/wezterm/cfg_keys.lua:94: in main chunk
        [C]: in function 'require'
        [string "/home/lesell_b/.config/wezterm/wezterm.lua"]:41: in main chunk
caused by: Error processing ActivateKeyTable::replace_current: missing field
`replace_current`.
{
    "name": "my-panes-management",
    "one_shot": false,
}
```

### Configuration

(you don't want me to paste it :smile:)

should be enough:
```lua
return {
  keys = {
    { key="p", mods="CTRL", action=wezterm.action.ActivateKeyTable{name="foo", one_shot=false} }
  }
}
```

### Expected Behavior

use the default for `replace_current` should be used.

NOTE: the documentation only says it is an optional boolean, but does not say what is the default value.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
