### ISSUE TITLE
what are apks for?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [wez/wezterm#2183]
* Does it mean that this terminal work on android? and 
* what does "alpine" mean in apk files' names? 
* i've heard alpile linux before, does it have any relation to it?

![image](https://user-images.githubusercontent.com/19423063/175806282-f1b45d58-467f-48ee-8312-a5e083d6a1e4.png)

**Comment by wez** [comment]
They are for Alpine Linux: https://wezfurlong.org/wezterm/install/linux.html#alpine-linux
