### ISSUE TITLE
Kitty input with Neovim incompatibility problems

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#2186]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220625-194053-9dc19892

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With kitty input enabled, while e.g. the differentiation from <c-i> and <Tab> is possible, it introduces a few strange problems

- `;` is inputted as `<S-;>` this is probably due to the fact, that `;` is `<S-,>` on my German ISO layout.
- (viw) `S)` the key bind to surround something with parentheses results in surrounding with `ü)` represented as `<80><fc>^B)` in vim. 

This might be considered a bug in Neovim IDK, but these problems do not occur when using kitty, so I'm not sure what the reason is.

### To Reproduce

enable kitty input mode
enable the german keyboard layout (this can probably also happen with US layout not sure)
open neovim (`nvim -u NONE`);
enter `: nmap ; <CMD>echo "hi"<CR>` press Enter
press `;` (S-,) and notice nothing happens
enter `: nmap <S-;> <CMD>echo "hi"<CR>` press Enter
press `;` (S-,) again and notice that "hi" is printed.

### Configuration

{
    enable_kitty_keyboard = true
}

### Expected Behavior

Probably the same that happens in kitty, but not sure what that means in terms of actual sent inputs

**Comment by xorander00** [comment]
Just wanted to echo that I'm seeing the same thing.

**Comment by wez** [comment]
Probably the same underlying issue as https://github.com/wez/wezterm/issues/1906 (both X11 and Wayland use the same low level keyboard layer)

**Comment by wez** [comment]
I fixed a couple of kitty keyboard encoding issues today; it's possible that they improve this, but I haven't tried to reproduce exactly this scenario and I'm not sure.

Could you try with the next nightly build?

0540301121fc66854e261c0b0395951520dc63df
8bb39bd6f3044d2ab42ef76d3667569cf0cfef43
d239e65e64ee5f68264b50408d6d7850e8b8cc2e
