### ISSUE TITLE
Wezterm ignoring the Windows rule in KDE and always open in the center of the screen 

### ISSUE THREAD

**Issue by bluebyt65** [wez/wezterm#2201]
### What Operating System(s) are you seeing this problem on?

Wayland KDE Plasma 5.25.2, Arch Linux

### WezTerm version

20220628-124345-241e19ba

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm always open in the center of the screen and disregarded the Windows rules Position. 

Downgraded to version 20220408.101518.b908e2dd is working as expected.

I tried on both version with the same result.
Nightly built 20220628-124345-241e19ba
Arch repo 20220624.141144.bd1b7c5d

### To Reproduce

Make a new rules in the Systems settings in Plasma KDE and set the position. Wezterm will open in the center of the screen.

### Configuration

[wezterm.txt](https://github.com/wez/wezterm/files/9005922/wezterm.txt)

### Expected Behavior

Wezterm opening in the position set by the Windows rule. (System settings KDE)

### Logs

19:07:33.755  INFO   wezterm_gui > Spawned your command via the existing GUI instance. Use --always-new-process if you do not want this behavior. Result=SpawnResponse { tab_id: 2, pane_id: 2, window_id: 2, size: TerminalSize { rows: 20, cols: 74, pixel_width: 592, pixel_height: 320, dpi: 0 } }

**Comment by wez** [comment]
Please start wezterm like this:

```
WEZTERM_LOG=window::os::x11::window=trace,info wezterm
```

and share the logs that it outputs. Please also confirm whether that instance has the same behavior that you described above.

**Comment by bluebyt65** [comment]
Yes that instance has the same behavior as described above.
WEZTERM_LOG=window::os::x11::window=trace,info wezterm
19:49:30.235  INFO   wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 630 (CFL GT2) 4.6 (Compatibility Profile) Mesa 22.1.2 is_context_loss_possible=false wezterm version: 20220628-124345-241e19ba

**Comment by wez** [comment]
There should be a lot more logs than that single line. Make sure that you close any existing wezterm instances and try again!

**Comment by bluebyt65** [comment]
I think this is because I executed this command with Konsole, because I have another bug maybe with Wezterm, When I tried to paste the result nothing come up. Here a screenshot
![wezterm](https://user-images.githubusercontent.com/18442224/176324844-79a23a92-3d07-4c68-9ac2-150c5106a151.png)

**Comment by wez** [comment]
That message means that you are already running wezterm and that it opened the new window in the existing instance.
You can either close the existing instance, or run it this way instead:

```
WEZTERM_LOG=window::os::x11::window=trace,info wezterm start --always-new-process
```

**Comment by bluebyt65** [comment]
Same result:
WEZTERM_LOG=window::os::x11::window=trace,info wezterm start --always-new-process
20:31:23.998  INFO   wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics 630 (CFL GT2) 4.6 (Compatibility Profile) Mesa 22.1.2 is_context_loss_possible=false wezterm version: 20220628-124345-241e19ba

**Comment by wez** [comment]
Oh, sorry, I didn't notice that you're running wayland!

Wayland doesn't allow applications to specify a window location at all; what you see is what your wayland compositor is deciding the window location should be.

I don't know why you're seeing different behavior for different versions of wezterm as there isn't code that it can call to influence this (which https://gitlab.freedesktop.org/wayland/wayland/-/issues/183 says is by design).  The nature of the wayland related changes also doesn't seem like it could impact this.

It might be interesting to compare running `WAYLAND_DEBUG=1 wezterm start --always-new-process` between the two versions.

**Comment by bluebyt65** [comment]
Yes I am only Wayland, but it's strange that before the version 20220408-101518-b908e2dd I never had this problem.

Also since I updated to the version 20220624.141144.bd1b7c5d when I copy things they don't paste. Is it the same issue with Wayland or should I report this behavior?

Here the difference between both version:

**wezterm 20220408-101518-b908e2dd**
WAYLAND_DEBUG=1 wezterm start --always-new-process         04:43:08 AM
04:43:10.599  INFO   wezterm_mux_server_impl::local > setting up /run/user/1001/wezterm/gui-sock-3487140
04:43:10.656  INFO   wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) UHD Graphics 630 (CFL GT2) 4.6 (Compatibility Profile) Mesa 22.1.2 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd



**wezterm 20220624.141144.bd1b7c5d**
WAYLAND_DEBUG=1 wezterm start --always-new-process  
https://pastebin.com/asNUg2yD

**Comment by wez** [comment]
OK, I think I can explain this: one of the things that changed in the latest release is that `enable_wayland` now defaults to `true` when it was previously `false`.

What I suspect to be happening with window positioning is that you have rules defined for wezterm running as an X11 app but not as a Wayland app. You may have to add them again for wezterm when it is run as a wayland app.  I don't use KDE so I'm not sure how that works, but that's my theory.

You can add `enable_wayland = false` in your config to use the original behavior and run using XWayland.

**Comment by bluebyt65** [comment]
Yes adding "enable_wayland = false" in the config are working for the position and copy/paste.

Thanks for the support!
