### ISSUE TITLE
tab display error

### ISSUE THREAD

**Issue by Kurt-Shiwz** [wez/wezterm#2208]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

WezTerm-macos-20220624-141144-bd1b7c5d  "dont have 'wezterm"

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

when drag window from mac to outside display
mac:
![image](https://user-images.githubusercontent.com/7554917/176901309-26d3c04d-36ed-4eff-8e27-28b40b1bcdf6.png)

outside display:
![image](https://user-images.githubusercontent.com/7554917/176901340-c2efceae-7ed2-4c2f-9314-aac76d3be532.png)

### Configuration

no config, i download just now

**Comment by Kurt-Shiwz** [comment]
> Do the tab titles return if you resize the window?

yes. Add a new tab also return.

**Comment by Kurt-Shiwz** [comment]
and why ?
![image](https://user-images.githubusercontent.com/7554917/176926894-f0b01a4d-3346-4915-9b39-bd4b554e5d48.png)

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
