### ISSUE TITLE
Panic when matching hyperlinks

### ISSUE THREAD

**Issue by hoop33** [wez/wezterm#221]
## Describe the bug

wezterm crashes and disappears (launched from Gnome Activities). Error in syslog is:

```
Jun 18 10:18:52 tatum gsd-media-keys[717828]: thread 'main' panicked at 'index out of bounds: the len is 192 but the index is 192', termwiz/src/surface/line.rs:197:20
Jun 18 10:18:52 tatum gsd-media-keys[717828]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 18 10:18:52 tatum gsd-media-keys[717828]:  2020-06-18T14:18:52.081Z ERROR wezterm::mux                > read_pty EOF: tab_id 0
Jun 18 10:18:52 tatum systemd[2690]: gnome-launched-wezterm-717828.scope: Succeeded.
```

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm UNKNOWN

This was built from source just now (June 18, 2020)

## To Reproduce

Can't reliably reproduce. Have seen three times.

- Running under tmux 3.0a
- Once, I was running `yarn test` and output was scrolling
- Once, I was typing up-arrow in neovim
- Once, I don't remember what I was doing
- Each time, the tmux window was split both horizontally and vertically

## Configuration

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("DankMono Nerd Font"),
  font_size = 14.0
}
```

## Expected behavior
No crash

## Screenshots

N/A

## Session Recording

N/A

## Additional context

I had it happen once with AppImage, downloaded and installed yesterday. Not the Nightly -- the release AppImage. That crash was on line 192 of `line.rs`, but when I looked at the code in the master branch, that was a comment. So I cloned the repo, built, and installed. Behavior persists, but now I can see in the code where the crash is happening:

```rust
        for m in Rule::match_hyperlinks(&line, rules) {
            // The capture range is measured in bytes but we need to translate
            // that to the char index of the column.
            for (cell_idx, (byte_idx, _char)) in line.char_indices().enumerate() {
                if self.cells[cell_idx].attrs().hyperlink.is_some() { // <-- crashes here
                    // Don't replace existing links
                    continue;
                }
                if m.range.contains(&byte_idx) {
                    let attrs = self.cells[cell_idx]
                        .attrs()
                        .clone()
                        .set_hyperlink(Some(Arc::clone(&m.link)))
                        .clone();
                    let cell = Cell::new_grapheme(self.cells[cell_idx].str(), attrs);
                    self.cells[cell_idx] = cell;
                    self.bits |= LineBits::HAS_IMPLICIT_HYPERLINKS;
                }
            }
        }
```

So I guess `self.cells` changes during this loop? I haven't really started looking yet.

**Comment by wez** [comment]
Thanks for the report!

If you can capture this in a script session (see https://github.com/wez/wezterm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#session-recording) that would capture the output that is triggering this.

I suspect that it contains a multi-byte sequence that renders in only one or two cells on the same line as a URL... thinking about it, yarn does use emoji for some of its status output so perhaps it is one of those?

I think the root of the issue here is that the `line.char_indices()` iteration isn't using graphemes but only code points and the indices don't match the line which is purely grapheme indexed.

**Comment by hoop33** [comment]
Running `wt-record` now and trying to duplicate -- will let you know. I have multi-byte chars in my prompt and in neovim as well, so your line of thinking definitely sounds plausible.

**Comment by hoop33** [comment]
I haven't been able to reproduce the error with the existing code -- I've tried with and without tmux, running neovim, running `yarn test`, and nothing is crashing. How about I pull the latest and you close the issue? If it happens again I'll reopen. Thanks for your help!

**Comment by wez** [comment]
I'm happy to keep this open for a few days while you run with this, and we can close it out if we don't see any further signs by the weekend!
