### ISSUE TITLE
Entire window background doesn't update when window has splits

### ISSUE THREAD

**Issue by jason0x43** [wez/wezterm#2210]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Windows may have a few pixels of background color along the right and/or bottom edges, presumably because the cell size doesn't divide evenly into the window size. Initially, this extra space uses the background color specified in the active color scheme or in the `colors` property, and it doesn't stand out too much.

<img width="782" alt="Screen Shot 2022-07-03 at 9 51 37 AM" src="https://user-images.githubusercontent.com/1042866/177043276-696c858a-a296-4aa5-a339-2cd9e80a937d.png">

However, when the color scheme or colors value is changed via `window:set_config_overrides`, any extra space along the window edges keeps the original background color. This can be a bit distracting.

<img width="782" alt="Screen Shot 2022-07-03 at 9 51 51 AM" src="https://user-images.githubusercontent.com/1042866/177043339-accc2dc8-d385-4fbd-9d84-16f611d778be.png">

If the `color_scheme` or `colors` property in the config is updated and the config is saved, the color of any extra space will change to the background color specified by that property. In the example below, the initial color scheme is set to "dark", but the active window color scheme is "light" because of a "window-config-reloaded" handler. The extra space keeps the "dark" background.

<img width="782" alt="Screen Shot 2022-07-03 at 9 52 24 AM" src="https://user-images.githubusercontent.com/1042866/177043431-34189494-2974-45a7-8d13-d55b638d93d6.png">

Note that this issue only occurs in windows or tabs with splits. In a window or tab with no splits, the entire window background will be set to the expected color.

### To Reproduce

Setup a wezterm config to change between light and dark themes in response to a "window-config-reloaded" event. Split the window into two panes, and focus the top/left one. Resize the window so that there is some space between the bottom/right pane and the window edge (this should be easy to see assuming that the inactive pane background color is slightly different from the window background color). Change the system appearance between light and dark (System Preferences -> General) and note that the color of the extra space doesn't change.

### Configuration

```lua
local wezterm = require("wezterm")

local color_schemes = {
    light = {
        foreground = "#53676d",
        background = "#fbf3db",
        cursor_bg = "#d2212d",
        cursor_fg = "#fbf3db",
        ansi = {
            "#e9e4d0",
            "#d2212d",
            "#489100",
            "#ad8900",
            "#0072d4",
            "#ca4898",
            "#009c8f",
            "#909995"
        },
        brights = {
            "#cfcebe",
            "#cc1729",
            "#428b00",
            "#a78300",
            "#006dce",
            "#c44392",
            "#00978a",
            "#3a4d53"
        },
        indexed = {
            [16] = "#fbf3db",
            [17] = "#53676d",
            [18] = "#c25d1e",
            [19] = "#bc5819",
            [20] = "#8762c6",
            [21] = "#825dc0",
        },
        selection_fg = "none",
        selection_bg = "#cfcebe",
    },
    dark = {
        foreground = "#b9b9b9",
        background = "#181818",
        cursor_bg = "#ed4a46",
        cursor_fg = "#181818",
        ansi = {
            "#252525",
            "#ed4a46",
            "#70b433",
            "#dbb32d",
            "#368aeb",
            "#eb6eb7",
            "#3fc5b7",
            "#777777"
        },
        brights = {
            "#3b3b3b",
            "#ff5e56",
            "#83c746",
            "#efc541",
            "#4f9cfe",
            "#ff81ca",
            "#56d8c9",
            "#dedede"
        },
        indexed = {
            [16] = "#181818",
            [17] = "#b9b9b9",
            [18] = "#e67f43",
            [19] = "#fa9153",
            [20] = "#a580e2",
            [21] = "#b891f5",
        },
        selection_fg = "none",
        selection_bg = "#3b3b3b",
    }
}

wezterm.on("window-config-reloaded", function(window)
    local overrides = window:get_config_overrides() or {}
    local appearance = window:get_appearance()
    local scheme = "light"
    if appearance:find('Dark') then
        scheme = "dark"
    end
    if overrides.color_scheme ~= scheme then
        overrides.color_scheme = scheme
        window:set_config_overrides(overrides)
    end
end)

return {
    color_schemes = color_schemes,
    color_scheme = "light",
}
```

### Expected Behavior

The active color scheme should affect the entire terminal window.

### Anything else?

The answer in [this discussion](https://github.com/wez/wezterm/discussions/2205#discussioncomment-3060929) may be related, since it sounds like the use of a mux server may affect how colors are applied to a window.

I'm not 100% sure this is the latest nightly build. It's the latest build on the releases page, and I didn't see a list of nightly builds anywhere else.

**Comment by wez** [comment]
39e727db5831e624a68eeb4592aa145cdd98af1a fixed the gap at the top right, while af5938d4143683ab7adb1310f5c54b6363cee794 should take care of the rest.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jason0x43** [comment]
Thanks for looking into this!

I found the macOS nightlies link in the docs (I had missed that before), and downloaded a copy this morning to try. The pane edges now use the pane background rather than the window background when the colors are updated, but the tab bar is still showing the original window background at the edge.

<img width="673" alt="Screen Shot 2022-07-11 at 10 28 42 AM" src="https://user-images.githubusercontent.com/1042866/178288857-28580fb0-ecae-42db-9488-383ea7abfbf8.png">

**Comment by jason0x43** [comment]
A bit more info -- the above case only happens when the tab bar is visible _and_ the active tab has a split. If the active tab doesn't have split (even if other tabs do), then any extra space after the tab bar will use the pane background color.

**Comment by wez** [comment]
Haven't had a chance to look at this yet, but I don't see this, however, I have https://wezfurlong.org/wezterm/config/lua/window/set_right_status.html configured. You might be able to workaround this by setting that to set it to spaces.

**Comment by jason0x43** [comment]
> Haven't had a chance to look at this yet

No rush, just adding more info. 🙂 

I tried this, but it didn't appear to make a difference:

```lua
wezterm.on("update-right-status", function(window)
	window:set_right_status(wezterm.format({
		{ Text = "foo  " },
	}))
end)
```

https://user-images.githubusercontent.com/1042866/178803720-1d8a72f1-c17b-40f8-bbcb-71410ef90605.mov

The incorrect background color shows up on the second tab (the one with a split), but not the first tab, and the background reverts to the proper color in the second tab when the split is closed.

**Comment by wez** [comment]
To reproduce this `use_fancy_tab_bar = false,` is needed in the config; that wasn't in the config that you shared!
This should now be resolved in `main`.

Also in `main`, you can simplify your light/dark mode appearance adjustment to this; no need to use the event to override it anymore:

```lua
local appearance = wezterm.gui.get_appearance()
local scheme = "light"
if appearance:find('Dark') then
  scheme = "dark"
end

return {
  use_fancy_tab_bar = false,
  color_schemes = color_schemes,
  color_scheme = scheme
}
```

**Comment by jason0x43** [comment]
Sorry about that!

I can verify that the nightly is working great now, and the new way of handling appearance is much cleaner. Nice!
