### ISSUE TITLE
set_environment_variables in set_config_overrides not working

### ISSUE THREAD

**Issue by rjpgt** [wez/wezterm#2211]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Setting environment variables through the key `set_environment_variables` in `window:set_config_overrides` when `window-config-reloaded` is called does not seem to work. They are not set. 

I am trying to cyclically go through a list of preferred schemes. Along with setting the scheme I want to set a suitable theme for the `bat` pager that will provide enough contrast. I am trying to do that through an environment variable.

### Configuration

```
wezterm.on("window-config-reloaded", function(window, pane)
    -- If there are no overrides, this is our first time seeing
    -- this window, so we can pick a random scheme.
    local overrides = window:get_config_overrides()
    if not overrides then
      local schemes = {"Belafonte Day", "Blazer", "tokyonight-storm", "seoulbones_dark", "MaterialDesignColors", "Belafonte Night"}
      local bat_schemes = {"GitHub", "Nord", "Nord", "DarkNeon", "Nord", "DarkNeon"}
      local scheme_file_name = "/home/jarav/.config/wezterm/wez_scheme_index"
      local scheme_file = io.open(scheme_file_name, "r")
      io.input(scheme_file)
      local scheme_index = io.read("*number")
      io.close(scheme_file)
      local scheme_file = io.open(scheme_file_name, "w")
      io.output(scheme_file)
      io.write((scheme_index % #schemes) + 1, "\n")
      io.close(scheme_file)
      wezterm.log_info(scheme_index)
      window:set_config_overrides({
        color_scheme = schemes[scheme_index],
        set_environment_variables = { batscheme = bat_schemes[scheme_index] },
      })
    end
  end)
```

### Expected Behavior
The environment variables should be set.

**Comment by digitallyserviced** [comment]
THis is not something you would be changing through the window's set_config_overrides method AFTER the window exists. 

Think about it, a window can have multiple panes, and tabs, do ALL of those now have the environment updated? 

Even so, the idea of overriding or setting environ vars with this config value is actually geared for BEFORE the terminal session is initiated, whereas you are mainly starting ONE instance in that new window.

**Comment by rjpgt** [comment]
I guess you are right. This shows my lack of understanding of the various stages of the wezterm process. In any case I have solved my problem through other means.
I am closing this issue. Thanks.

**Comment by wez** [comment]
Two things to note:

* This option is looked at when launching a new program
* It is physically impossible, on any operating system, to change the environment variables of a running process, so it's not possible for wezterm to try to apply this setting to running programs after a config reload or when you set config overrides

I've added a note about this to the docs.
