### ISSUE TITLE
Termwiz widgets_nested example: Panick when reducing window width/height

### ISSUE THREAD

**Issue by dennisschagt** [wez/wezterm#2222]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220704-063908-51406cfe

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried (build manually from the main branch)

### Describe the bug

When running the `widgets_nested` termwiz example, resizing the terminal causes a crash/panic.

### To Reproduce

1. Start example by running `RUST_BACKTRACE=1 cargo run --features widgets --example widgets_nested` in the `termwiz` directory
2. Resize window (seems to be fine while width/height are increasing but panics when either width or height of the window gets smaller

First line of output: `thread 'main' panicked at 'assertion failed: x + width <= self.width', termwiz/src/surface/mod.rs:767:9`

### Configuration

no config

### Anything else?

Running in `konsole 22.04.1` with i3wm on X11

Screenshot:
![image](https://user-images.githubusercontent.com/4629607/177211502-152eb210-a171-4db3-9546-72c0411608ad.png)

Text from screenshot in a slightly more readable form:
```
thread 'main' panicked at 'assertion failed: x + width <= self.width', termwiz/src/surface/mod.rs:767:9
stack backtrace:
    0: rust_begin_unwind
        at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
    1: core::panicking::panic_fmt
        at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
    2: core::panicking::panic
        at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:48:5
    3: termwiz::surface::Surface::diff_region
        at ./src/surface/mod.rs:767:9
    4: termwiz::surface::Surface::draw_from_screen
        at ./src/surface/mod.rs:834:23
    5: termwiz::widgets::Ui::render_recursive
        at ./src/widgets/mod.rs:372:13
    6: termwiz::widgets::Ui::render_to_screen
        at ./src/widgets/mod.rs:447:13
    7: widgets_nested::inner::run
        at ./examples/widgets_nested.rs:156:20
    8: widgets_nested::main
        at ./examples/widgets_nested.rs:212:5
    9: core::ops::function::FnOnce::call_once
        at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Probably unrelated, just in case:
When starting the example (before the crash), it shows `2::49:27:146m` on the first line.
I guess this has something to do with the color used in the `Change::ClearScreen` call.

**Comment by dennisschagt** [comment]
It looks like someone else has mentioned this issue before as a reply to a feature request: https://github.com/wez/wezterm/issues/171#issuecomment-631324088

**Comment by wez** [comment]
Thanks for reporting this. This is fixed now in `main`.
