### ISSUE TITLE
flatpak / flathub support.

### ISSUE THREAD

**Issue by Vantadaga** [wez/wezterm#2229]
**Is your feature request related to a problem? Please describe.**
This PR is not related to a problem

**Describe the solution you'd like**
I would like wezterm added to Flatpak /Flathub for better distribution and quick installation of the program

**Describe alternatives you've considered**
None needed

**Additional context**
None needed

**Comment by azzamsa** [comment]
Possible duplicate https://github.com/wez/wezterm/discussions/2094

**Comment by Vantadaga** [comment]
> Possible duplicate #2094

I was not aware of that issue, will close this one.

**Comment by wez** [comment]
That other one is a discussion not an issue; let's keep this open

**Comment by VarLad** [comment]
Would be awesome for Silverblue users

**Comment by wez** [comment]
I have a prototype for this in the attached PR, but I'm not convinced that it is a good solution because flatpaks are sandboxed and isolated, which limits the utility of a terminal.

Are there cases where that doesn't matter?

How can we make it clear to users when they should use the flatpak and when they want a real package?

Every time I've installed an app via flatpak, it's ended up being frustrating.  My most recent experience was with Arduino, which makes no sense to be a flatpak and yet that is what is shown in the Fedora Software app: https://github.com/earlephilhower/arduino-pico/issues/660

**Comment by azzamsa** [comment]
Thank you so much for your efforts. I don't think we need to continue if this is the case.

> Are there cases where that doesn't matter?

Currently, my only advantage is seamless upgrade than appimage and separating external package from debian source list.

But it can be easely solved using the script which download the binary and put it in the PATH. As I did every couple of weeks with rust-analyzer.

**Comment by VarLad** [comment]
@wez Have you tried https://flathub.org/apps/details/com.raggesilver.BlackBox by the way? Its another terminal application packaged as Flatpak. (I can't confirm whether its GPU accelerated or not) 
Here's the link https://flathub.org/apps/details/com.raggesilver.BlackBox and https://github.com/flathub/com.raggesilver.BlackBox
This makes it super easy to install and update on distros like Fedora Silverblue. 
Also, I'd really recommend you to take a look at [Flatseal](https://github.com/tchx84/Flatseal) :P

**Comment by wez** [comment]
Thanks for linking to blackbox; it looks like it breaks out of the sandbox using flatpak-spawn, but there are issues to overcome in order to have a working shell:

* https://github.com/flatpak/flatpak/issues/3697
* https://github.com/flatpak/flatpak/issues/3285

**Comment by VarLad** [comment]
@wez I've encountered those before (in in-built terminals of certain editors), but stuff seems to work out of the box in Blackbox. Including settings like "setting default shell" among other things.

**Comment by wez** [comment]
BlackBox's GPL license has me hesitant to actually look at how it solves these problems in its code. If someone could summarize the approach then I'm open to engineering a solution for wezterm.

**Comment by wez** [comment]
Figured out that I could skip setting the controlling tty to unblock.
It's at least usable, but there's no `wezterm cli` available on the host system.
`flatpak enter org.wezfurlong.wezterm /app/bin/wezterm cli list` does function ok though, so it is something that can be aliased by a motivated user.

**Comment by VarLad** [comment]
Thats the way for flatpak users :P

**Comment by wez** [comment]
The latest release is now on flathub: https://flathub.org/apps/details/org.wezfurlong.wezterm
Please give it a try and let me know how it goes!

**Comment by wez** [comment]
docs up at: https://wezfurlong.org/wezterm/install/linux.html#installing-on-linux-via-flathub

**Comment by Vantadaga** [comment]
> docs up at: https://wezfurlong.org/wezterm/install/linux.html#installing-on-linux-via-flathub

Excellent, I will close this issue.

**Comment by azzamsa** [comment]
- all the configs loads correctly. looks 100% with the locally installed deb version
- ssh works well

Looks good to me. Thanks for all your hard work you put into Wezterm!
It is the integral part of my workflow.

**Comment by grilix** [comment]
Hey, sorry for commenting on a closed issue, but if anyone is confused about where to put the configuration file, adding it at `~/.var/app/org.wezfurlong.wezterm/config/wezterm/wezterm.lua` worked for me. Thanks for the great work! :heart:

**Comment by wez** [comment]
You can also use `~/.wezterm.lua` for the config file path
