### ISSUE TITLE
IncompatibleVersionError even if same version installed

### ISSUE THREAD

**Issue by raivivek** [wez/wezterm#2230]
### What Operating System(s) are you seeing this problem on?

Linux X11, macOS

### WezTerm version

wezterm 20220707-062543-2c093b97

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have installed the same version of nightly on local macOS and remote linux machine running CentOS 7. In fact, I specified the remote wezterm path directly in the config and have checked the versions. However, `wezterm connect` reports incompatible version regardless and I am not sure why.

On my local machine when I try to to connect:

```
$ wezterm connect server
19:13:52.725  ERROR  wezterm_gui::termwindow > new_window has no tabs... yet?
19:13:52.785  INFO   wezterm_gui::termwindow > OpenGL initialized! Apple M1 Pro 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220707-062543-2c093b97
19:13:53.598  INFO   wezterm_client::client  > going to run /home/raiv3/.local/bin/wezterm cli --prefer-mux proxy
19:13:58.730  ERROR  wezterm_client::client  > IncompatibleVersionError { version: "20220612-201748-75066cb5", codec_vers: 24 }
19:13:58.730  ERROR  wezterm_gui             > Please install the same version of wezterm on both the client and server!
The server version is 20220612-201748-75066cb5 (codec version 24),
which is not compatible with our version
20220707-062543-2c093b97 (codec version 25).; terminating
```

On remote server:
```
$ /home/raiv3/.local/bin/wezterm --version
wezterm 20220707-062543-2c093b97
```

Please note that there are no other wezterm binaries anywhere else locally or on the remote server.

### To Reproduce

1. On the remote server, I downloaded the nightly rpm for CentOS and cherry picked the binaries from there
2. On local macOS, installed using homebrew
3. Try to connect

### Configuration
```
local wezterm = require 'wezterm';

return {
  ssh_domains = {
    {
    name = "sc1",
    remote_address = "sc1",
    remote_wezterm_path = "/home/raiv3/.local/bin/wezterm"
    },
  },
}
```

**Comment by wez** [comment]
The error message says:

```
The server version is 20220612-201748-75066cb5 (codec version 24),
which is not compatible with our version
20220707-062543-2c093b97 (codec version 25)
```

You have two different versions that are not compatible.

Things to check:
* On the server, you may need to stop/restart the older version of the server before the newly installed/upgraded version takes effect
* Verify that you don't have multiple versions installed in either client or server.
* Verify that you're running the one you think you're running (check `which wezterm` and verify that it is the path you expect)
