### ISSUE TITLE
Blurry fonts and window on Hyprland w/ fractional scaling

### ISSUE THREAD

**Issue by fufexan** [wez/wezterm#2232]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

5c6312c6a58207bbb211032c3f2d9ac31a04158b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I want to switch to wezterm from kitty, but I noticed its text and window are blurry in [Hyprland](https://github.com/hyprwm/Hyprland) when the display scale is set to >1. Alacritty has the same issue so I suppose it's got something to do with [winit](https://github.com/rust-windowing/winit/issues/837), but I'm not sure.

About the version: I don't know how to use nightly on Nix, so I just grabbed the latest commit and compiled using that.

### To Reproduce

Launch Wezterm in Hyprland side by side with Kitty, with a scaling factor > 1.

### Configuration

no config

### Expected Behavior

Wezterm would display sharp fonts, without blurriness.

### Logs

16:22:53.371 INFO wezterm_gui::termwindow > OpenGL initialized! AMD RENOIR (LLVM 13.0.1, DRM 3.46, 5.18.1-xanmod1) 4.6 (Compatibility Profile) Mesa 22.1.1 is_context_loss_possible=false wezterm version: 20220624-141144-bd1b7c5d

### Anything else?

![image](https://user-images.githubusercontent.com/36706276/178000924-b77c398f-9836-4f05-b652-500e48fe5098.png)
This screenshot was taken with scale `1.6`.

**Comment by wez** [comment]
Try setting `enable_wayland = false` in your wezterm config, then restarting wezterm

**Comment by wez** [comment]
If that doesn't help, can you share what you're using to set the scaling factor? Is that a compositor setting? Is it a gsetting?

**Comment by fufexan** [comment]
> Try setting `enable_wayland = false` in your wezterm config, then restarting wezterm

I did that, no change.

> If that doesn't help, can you share what you're using to set the scaling factor? Is that a compositor setting? Is it a gsetting?

It's a compositor/wlroots setting. It can either be set in [Hyprland's config file](https://github.com/fufexan/dotfiles/blob/main/home/wayland/hyprland/config.nix#L22) (the last `1.6` part), or through `kanshi` or `wlr-randr`.

**Comment by wez** [comment]
The challenge here is that the wayland protocol only supports integer scaling, and wezterm can only tell that scaling is being used if wayland reports that for the surface configuration.  On a HiDPI display, wayland typically informs wezterm that the scale factor is 2x and wezterm will adjust for that and render at twice the resolution and tell wayland that it is pre-scaled to 2x; that prevents wayland from scaling it again and the results look sharp.

Compositors that implement fractional scaling do so outside of what the wayland protocol supports, so there isn't a way (that I know of) for the application and the compositor to share understanding of the scaling level, so what you see if a buffer that is scaled poorly: it is rendered at the wrong resolution and scaled by the compositor, with a blurry result.

I'd suggest adjusting wezterm's [dpi](https://wezfurlong.org/wezterm/config/lua/config/dpi.html) setting to try to compensate for the font scaling.  I'd suggest either trying `192 / 1.6` to try to "undo" the compositor scaling factor, or perhaps try `96` to undo the buffer scale doubling, but you can play around with other values too to see if you can find something that makes it look good.

I don't know why kitty doesn't seem to be affected: perhaps it doesn't know about the 2x surface scaling stuff I mentioned in the first paragraph, or perhaps it knows something I don't know about wayland.

**Comment by fufexan** [comment]
I've tried all of the above, even tried them with scaling set to `2`, but the font is still blurry. The only scale it doesn't happen with is `1` or less.

**Comment by wez** [comment]
Is it also blurry in wayfire (another wlroots compositor)? I can't easily install Hyprland on my Fedora system but I can install wayfire.

**Comment by fufexan** [comment]
Just tested in both wayfire and sway.
- in wayfire it looks better than in hyprland (not as crisp as kitty but definitely better)
- in sway it looks better than both (as crisp as kitty's fonts)

**Comment by wez** [comment]
I've been reading around this, and it seems like there is a lot of variance in how different compositors handle scaling, especially fractional scaling factors.
I don't have a definitive explanation for why kitty doesn't seem to suffer from the fractional scaling, but it does use a different core library and also uses a different approach to rendering, so I'm not going to worry too much about that difference.

There are three different threads discussion approaches for handling fractional scaling:
https://gitlab.freedesktop.org/search?group_id=1158&project_id=2891&scope=merge_requests&search=fractional+surface

once those settle down there should be a way for an application to coordinate with the compositor to avoid undesirable scaling, and then this can be solved properly!

**Comment by fufexan** [comment]
Thanks for looking into this! I'll keep using kitty until the Wayland people come to a conclusion regarding fractional scaling.

(or I'll rewrite the scaling mechanism in Hyprland to mirror that of Sway :D)

**Comment by fufexan** [comment]
This issue was fixed a few hours ago along with all other "blurry wayland programs" issue I've been having on Hyprland. Sorry for wasting your time Wez!
