### ISSUE TITLE
Command Completed notification generated for every command entered

### ISSUE THREAD

**Issue by jcowgar** [wez/wezterm#2237]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After launching WezTerm, any command entered into the console, for example clear or ls, results in a desktop notification from Gnome stating: "Command Completed" and then the command that just completed.

In previous installations of WezTerm notifications were generated only when a command completed and WezTerm was not the active window.

I have a Fedora 36 and Clear Linux installation both running Gnome 42. Both environments exhibited the same problem.

I used the AppImage version on Clear Linux, on Fedora 36, I compiled from sources.

### To Reproduce

1. In Gnome (use wayland but also tried in X11) launch WezTerm
2. Type clear at the prompt
3. Notice the "Notification" that appears stating "Command Completed" clear

### Configuration

no config and also same behavior with my custom config (mainly just colors and fonts)

### Expected Behavior

No Notification dialog should appear unless WezTerm is in the background

### Logs

10:33:32.175 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX Vega (vega10, LLVM 14.0.0, DRM 3.44, 5.17.5-300.fc36.x86_64) 4.6 (Compatibility Profile) Mesa 22.1.3 is_context_loss_possible=false wezterm version: 20220624-141144-bd1b7c5d

**Comment by wez** [comment]
wezterm doesn't generate notifications like this, so I don't know where this is coming from.
Can you share a screenshot of the notification?
Is there something in your shell configuration that might be the source?

**Comment by jcowgar** [comment]
OK, interestingly it is something in my bash configs somewhere. This is a brand new installation, none of my personal config is here yet. If I launch sh, then notifications do not appear. So, Fedora and Clear Linux must be doing something by default.

I'll continue to track it down and post here what I find in case others have this problem, again fresh install of Fedora.

You can close this ticket if you wish. Thank you for the quick response.

**Comment by wez** [comment]
Interesting!

```
; rg 'Command completed' /etc/profile.d
/etc/profile.d/vte.sh
41:  printf '\033]777;notify;Command completed;%s\033\\\033]777;precmd\033\\\033]0;%s@%s:%s\033\\' "${command}" "${USER}" "${HOSTNAME%%.*}" "${pwd}"
```

as far as I can tell, that script should only run if `VTE_VERSION` is set appropriately

**Comment by wez** [comment]
Are you perhaps launching wezterm from inside gnome-terminal?

**Comment by jcowgar** [comment]
Yes, indeed I was getting my system up and running. Running outside of gnome-terminal or unsetting VTE_VERSION causes the problem to go away.

Thank you for helping out. WezTerm is my term of choice and I was really bummed I couldn't use it w/my new install. The notifications for every command was just too much.

This had nothing to do with WezTerm, should I remove the "bug" label on this ticket?

**Comment by wez** [comment]
I think I'll teach wezterm to clear VTE_VERSION to avoid this surprising others in the future!

**Comment by wez** [comment]
OK, this shouldn't be a problem for others in the future; thanks for working through it with me!
