### ISSUE TITLE
Unable to determine CWD from under Tmux and Zellij

### ISSUE THREAD

**Issue by dmilith** [wez/wezterm#2238]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220709-231243-60728793

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I use Wezterm with this configuration:

https://gist.github.com/dmilith/841de041c27f559dff774638a4ed2286

As you see, I used to use tmux as my "default shell" (commented out), now I want to move to Zellij, but I experience a severe issue with CWD (current working dir) for both multiplexers under Wezterm (I'm not even sure if it's Wezterm issue or it's just Tmux-way-of-doing-things).

In my gist I wrote a simple Lua hyperlink extension that allows triggering the Rust compilation lines like 

```
   --> src/utils.rs:285:7
```

I just click on such from Wezterm and it opens my favourite editor precisely where failure happens. Very cool.

Everything's nice until I try to do the same thing from the tmux/ zellij. Wezterm is unable to determine the current working directory that's opened under tmux… which is somewhat obvious right?

The question is how to work around this :)

I've been thinking about calling some external command magic that's notifying the terminal from the current tmux pane about the current dir, but this seems hacky and I'd like something more elegant ;) 

NOTE: I tried the OSC7 magic in Zsh, but that didn't help.

### To Reproduce

Use my configuration and fail a rust project build from the tmux session

### Configuration

https://gist.github.com/dmilith/841de041c27f559dff774638a4ed2286

**Comment by dmilith** [comment]
I also tried calling `wezterm set-working-directory` from the tmux pane… but that also didn't help.

**Comment by wez** [comment]
If you're running other multiplexers inside wezterm then you're going to have a hard time with the cwd because wezterm will see your entire multiplexer as a single pane when it could be a set of panes.

For tmux, you'll need to tell it pass through OSC 7 to wezterm:
https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it

but you'll need to take care on the tmux side to send that through each time you change the tmux pane focus, otherwise wezterm may see a stale value.

I don't know if zellij has equivalent functionality.

I'm curious which functions of tmux/zellij you need that wezterm doesn't have: ideally you wouldn't need to run either of those inside wezterm.

**Comment by dmilith** [comment]
Actually, I'm moving forward with my configuration to finally get rid of Tmux, so I can tell you what's missing:

- Keyboard-driven output selection. I really like my Trackpad, but for selecting text a well-configured Tmux could help a lot. Basically, I hit ctrl-x x, then V and visually select a block of wanted text and hit 'y' to yank it to the Clipboard.
 
 
Below's my ~/.tmux.conf for reference:

```conf
# color scheme (style based on vim-powerline)
setw -g status-left-length 52
setw -g status-right-length 451
setw -g status-fg colour35
setw -g status-bg colour234
setw -g window-status-format '#[fg=colour69,bg=colour234] #I #W '
setw -g window-status-current-format '#[fg=colour234,bg=colour39]#[fg=colour65,bg=colour235,noreverse,bold] #I #W #[fg=colour69,bg=colour235,nobold]'

# set -g default-terminal "wezterm"
set -g default-terminal "xterm-256color"
set -g focus-events on


# Prefix
unbind C-b
set -g prefix C-x
bind C-x send-prefix


# Vim selection:
unbind [
unbind x
#bind Escape copy-mode
bind x copy-mode
#unbind p
#bind p paste-buffer
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe "~/.zsh/copies"

setw -g mode-keys vi

set -g focus-events on

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Quiet
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

# selection color
setw -g mode-style fg=colour120,bg=colour60

# Panes
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=blue
set -g base-index 1

# Statusbar
set -g status-left ''
set -g status-right "#h, #S, #[default]"
# #[fg=green,bg=black]#(/usr/local/bin/tmux-mem-cpu-load --colors --interval 2)
set -g status-right-length 70
set -g window-status-separator ''
set -g status-interval 2
set-option -g history-limit 350000
```

**Comment by dmilith** [comment]
Holy moly, I just found https://wezfurlong.org/wezterm/copymode.html

**Comment by dmilith** [comment]
Ok, now I know kung-fu, and have all my tmux features with just Wezterm Nightly. Awesome terminal app. Much appreciated <3
