### ISSUE TITLE
wayland: fullscreen/maximized state broken under mutter

### ISSUE THREAD

**Issue by jeromegn** [wez/wezterm#224]
## Describe the bug

When trying to toggle fullscreen on WezTerm (by dragging the window to the top of the screen, on Gnome), the window gets the right width and height, but it's not "clamped" like other fullscreen windows.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Version: wezterm 20200608-110940-3fb3a61

## To Reproduce

Drag window to top of the screen to toggle fullscreen

## Configuration

(doubt this is relevant)

```lua
local wezterm = require 'wezterm';
return {
  font = wezterm.font("JetBrains Mono"),
  color_scheme = "Dracula",
  enable_wayland = true,
  default_cursor_style = "SteadyBar",
}
```

## Expected behavior

It should use the whole screen and be clamped to all edges.

## Screenshots

![image](https://user-images.githubusercontent.com/43325/85128376-1d9fa500-b1ff-11ea-8f47-6d70284ecb67.png)

**Comment by wez** [comment]
We use https://github.com/smithay/client-toolkit for the wayland client window handling.
`mutter` (the wayland compositor used by gnome) and the client toolkit tickle
problems with each other's implementation; the last similar issue was actually
a bug in mutter exposed by the client toolkit https://github.com/Smithay/client-toolkit/issues/92 https://gitlab.gnome.org/GNOME/mutter/issues/1024

You can work around this issue by setting `enable_wayland = false` in your config.

Next steps:

* Someone should probably report this to both smithay-client and mutter
* It's worth thinking about how much effort it would be to remove this dep in the hope that we don't see this class of issue again

**Comment by jeromegn** [comment]
Interesting. That makes sense.

`enable_wayland = false` doesn't appear to help though.

**Comment by wez** [comment]
You need to restart wezterm for that particular config to take effect; the choice of window system is global and processed only at startup!

**Comment by jeromegn** [comment]
Even with a restart. This is odd. Any way to confirm the settings are applied?

**Comment by wez** [comment]
It should be fairly apparent if it has taken effect, as the title bar will render differently when falling back to X.

I'd suggest launching wezterm from a different terminal for debugging purposes;

```
RUST_LOG=trace wezterm 2>/tmp/verbose.txt
```

and attach `/tmp/verbose.txt` to this issue.

**Comment by jeromegn** [comment]
My bad, I had 2x enable_wayland and they conflicted.

Fullscreen does work with X11.
