### ISSUE TITLE
Paste from clipboard shows weird character when wezterm ssh over jumpserver

### ISSUE THREAD

**Issue by Alex-Hou** [wez/wezterm#2244]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220711-001839-cfd9c0b3

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

We use a 'Jumpserver' (something like [this](https://github.com/jumpserver/jumpserver) and [this](https://github.com/gravitational/teleport)) to secure our production environment. Normally we login this server with two-factor authentication 
 token, and then select the server we actually want to login to.
When I use normal SSH (OpenSSH_8.6p1, LibreSSL 2.8.3) with or without wezterm, everything is OK.
But when I use `wezterm ssh <host>`, the paste action will add extra characters after the second step (it still good after the first login step), something like this:

```bash
~$ 0~hello1~
~$ 0~world1~
```

I think it is some sort of escaping characters but don't know how to avoid it.
It didn't happen in iTerm or macOS Terminal.

### To Reproduce

1. `wezterm ssh <serverA>`
2. ssh <serverB>
3. paste something.

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  cursor_blink_rate = 0,
  canonicalize_pasted_newlines = "None",
  font = wezterm.font("Ubuntu Mono"),
  font_size = 19.0,
  line_height = 1.2,
  color_scheme = "Chalk",
  window_background_opacity = 0.95,
  set_environment_variables = {
    LANG = "zh_CN.UTF-8"
  },
  ssh_backend = "Ssh2",  -- tried with / without this 
  keys = {
    {key="v", mods="CMD", action=wezterm.action.PasteFrom("Clipboard")}
    -- tried with / without this key binding config
  }
}
```

**Comment by wez** [comment]
If you run `cat` (no arguments) on the remote and paste, what do you see?
Is that different from what you see in your shell?
I suspect that the application on the other end has enabled bracketed paste mode and what you're seeing is the bracketing escapes.

Two things might be a factor here:
* If your jump host is doing something (in the name of security, logging, filtration) with the data flowing through the connection, it may not understand bracketed paste mode and might be doing the wrong thing. If that is true, then you may wish to disable bracketed paste mode in the config of the applications on the remote host
* If you have high latency going through that link, it may be the case that the escapes are being recognized "atomically". That seems unlikely to me given the size of the paste, but if that is somehow part of it, then you might be able to adjust an escape sequence timeout parameter in something like the inputrc.  Again: I don't think this is likely, but it is a possibility.

Take a look at the bottom of this answer for info on how to disable bracketed paste mode:
https://stackoverflow.com/a/50654284/149111

**Comment by Alex-Hou** [comment]
This is what I see with `cat`:

```sh
~$ cat
^[[200~hello^[[201~
```

The servers are in the same local network, so I think it might be more like the first case.
I'll try to disable bracketed paste mode.

**Comment by Alex-Hou** [comment]
I tried this:

```
printf '\e[?2004l'
```

on the second step server, and it worked, no `^[[200~` in `cat` output.

But then I found that this issue will only happen on the first 'second step server'.

If I open a new tab, wezterm ssh will reuse the connection to the jumpserver, then I jump to another 'second step server', everything works fine whether or not the bracketed paste mode is turned on.

Could it be some mechanism of wezterm ssh?

**Comment by wez** [comment]
wezterm's ssh doesn't do anything with bracketed paste.

The most likely explanation is that the shell configuration on either your first or second hops have conflicting thoughts about bracketed paste.

For instance, perhaps the first one turns it on and leaves it on for the duration of the `ssh` command that you run.
Perhaps the second hop is running an older version of the shell that doesn't understand bracketed paste.
If that's the case, then the resolution would be for you to disable bracketed paste in the config for your first hop,
or to have your second hop unconditionally `printf '\e[?2004l'` when you login.
