### ISSUE TITLE
Consistent Lua code formatting with StyLua

### ISSUE THREAD

**Issue by azzamsa** [wez/wezterm#2253]
Hi.

What if we format all the Lua code snippets in the documentation using [StyLua](https://github.com/JohnnyMorganz/StyLua)?
It keeps the code consistent and more readable.

However, I don't think we can feed him with a markdown file. We need to do it by hand.

**Comment by wez** [comment]
Provided:
* It's easy to build/install (looks like a Rust program, so I have high hopes)
* It can be made to run over the docs without breaking them
* It's actually a style I like(!)

then I'd be interested to see that integrated.
I don't personally have bandwidth to work on that myself.

I have zero interest in manually feeding each snippet through a formatter: it's too much effort.
