### ISSUE TITLE
How do I switch between tabs?

### ISSUE THREAD

**Issue by ninjarogue** [wez/wezterm#2254]
What is the default way of switching between tabs? I can't seem to find any answers on the docs or from a google search.

**Comment by MuhammedZakir** [comment]
Search for `Tab` in https://wezfurlong.org/wezterm/config/default-keys.html.

**Comment by wez** [comment]
FWIW, the [Features Page](https://wezfurlong.org/wezterm/features.html) has a quick list of tab related shortcuts, but the full list is on the default-keys page that MuhammedZakir linked above.
You can also just click on them with the mouse!
