### ISSUE TITLE
Option to control "unprintable character error" notification.

### ISSUE THREAD

**Issue by aca** [wez/wezterm#2256]
Everytime I ls files which has some wierd characters (or chinese), wezterm sends notification to the host that there's an unprintable character. 
`No fonts contain glyphs for these codepoints`.
It would be better if there's option to control this behavior. Maybe something like "silence_error" in font configuration.

**Comment by bew** [comment]
There is :) 
https://wezfurlong.org/wezterm/config/lua/config/warn_about_missing_glyphs.html

@wez maybe mention it in the "Fonts" page? Or add a page about font finding, mentioning it?

**Comment by aca** [comment]
I really thought I read the document. Sorry! Yeah it would be nice If it's mentioned in font fallback page. 
Thanks @bew

**Comment by wez** [comment]
The notification itself tells you what to do to suppress the notification:

https://github.com/wez/wezterm/blob/21e6fcedd9693ae1d507ba48fb31ba3dc3cdb821/wezterm-font/src/lib.rs#L408-L417

https://github.com/wez/wezterm/issues/2188 is a request for debouncing these notifications. I'll probably default these to something like once per hour.
