### ISSUE TITLE
`cursor_bg` and `cursor_fg` cannot be overriden by neovim/vim in some cases

### ISSUE THREAD

**Issue by milanglacier** [wez/wezterm#2260]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I tried the nightly build (manually build from source) and it has the same problem.

Some neovim/vim colorschemes doesn't specifically set the cursor fg and bg as a fixed color value, sometimes they uses:
`highlight Cursor cterm=reverse` to reverse the fg and bg of the cell under the cursor.
In alacritty(if don't set any curor color in`alacritty.yml`) or iterm2 (set `Preferences-Profiles-Colors-Smart box cursor color` to true), `cterm=reverse` is respected, and in wez, `cterm=reverse` is not respected.

### To Reproduce

```bash
cd ~/.config/wezterm
vim --clean -c "hi Cursor cterm=reverse" wezterm.lua # run in no plugin mode
nvim --clean -c "hi Cursor cterm=reverse" wezterm.lua # run in no plugin mode
```

### Configuration

wezterm config:

```lua
return {
    color_scheme = 'Builtin Solarized Light'
}
```

### Expected Behavior

Respect `highlight Cursor cterm=reverse` by vim/neovim

### Anything else?

screenshot:
<img width="347" alt="Screen Shot 2022-07-13 at 17 29 18" src="https://user-images.githubusercontent.com/45728125/178839706-6ebd3f4e-d257-4ac6-9ecc-61a301c07566.png">

alacritty

<img width="270" alt="Screen Shot 2022-07-13 at 17 28 56" src="https://user-images.githubusercontent.com/45728125/178839748-f99d055d-d2d7-4845-a9e6-51ddcc9c751c.png">

wezterm

**Comment by wez** [comment]
Perhaps you want to enable https://wezfurlong.org/wezterm/config/lua/config/force_reverse_video_cursor.html ?

**Comment by milanglacier** [comment]
`force_reverse_video_cursor = true` and `force_reverse_video_cursor = false` does not have effect to my situation

**Comment by milanglacier** [comment]
This works amazingly! Thanks!

**Comment by milanglacier** [comment]
For people like me who prefer to swtich the colorscheme dynamically (based on OS theme), I find that every time if a colorsheme resets, then `force_reverse_video_cursor` automatically sets to `false`, then manually set it to true in everytime override works:

```lua

local function switch_color_scheme_with_OS()
    wezterm.on('window-config-reloaded', function(window, _)
        local overrides = window:get_config_overrides() or {}
        local appearance = window:get_appearance()
        local scheme = scheme_for_appearance(appearance, _)
        if overrides.color_scheme ~= scheme then
            overrides.color_scheme = scheme
            overrides.force_reverse_video_cursor = true
            window:set_config_overrides(overrides)
        end
    end)
end

```
