### ISSUE TITLE
Rose Pine scheme doesn't work

### ISSUE THREAD

**Issue by luxus** [wez/wezterm#2261]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220625-114047-ce89e33f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

i tried some schemes, but i cannot get [rose pine](https://wezfurlong.org/wezterm/colorschemes/r/index.html#rosé-pine-base16) working or any of its variants

### To Reproduce

adding scheme to `.config/wezterm/wezterm.lua` 

### Configuration

```lua
return {
  color_scheme = "Rosé Pine (base16)",
}
```

### Expected Behavior

changing Colors of the terminal, other schemes are working 

### Logs

01:43:25.712 ERROR config::config > Your configuration specifies color_scheme="Rosé Pine (base16)" but that scheme was not found

**Comment by wez** [comment]
The `(base16)`, `(gogh)` and `(terminal.sexy)` schemes are all new in the nightly builds. We don't currently have versioning information in the docs for schemes because of the way they are synced.
You can download a nightly build from https://wezfurlong.org/wezterm/installation.html

**Comment by luxus** [comment]
thanks for the  quick help
`brew upgrade --cask wezterm-nightly --no-quarantine --greedy-latest`
fixed it.. thanks
