### ISSUE TITLE
Default shortcuts for switching tabs not working on Ubuntu

### ISSUE THREAD

**Issue by paulkre** [wez/wezterm#2264]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When I press CTRL+SHIFT+[0-9] or SUPER+[0-9] the tabs are not switching.

### Configuration

None

**Comment by wez** [comment]
You can use [debug_key_events](https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html) to figure out what is happening when you press a key.

**Comment by diucicd** [comment]
local mykeys = {}
for i = 1, 8 do
  -- CTRL+ALT + number to activate that tab
  table.insert(mykeys, {
    key=tostring(i),
    mods="ALT",
    action=wezterm.action{ActivateTab=i-1},
  })
  -- F1 through F8 to activate that tab
  table.insert(mykeys, {
    key="F" .. tostring(i),
    action=wezterm.action{ActivateTab=i-1},
  })
end

maybe the document config should be the default ubuntu setting

**Comment by paulkre** [comment]
Thank you @diucicd, that config works great. For anyone having the same issue, here is my complete `.wezterm.lua`:

```lua
local wezterm = require "wezterm"

local keys = {}
for i = 1, 8 do
  table.insert(keys, {
    key = tostring(i),
    mods = "ALT",
    action = wezterm.action{ ActivateTab = i - 1 },
  })
end

return {
  keys = keys,
}

```
