### ISSUE TITLE
Add Action to alternate between current and previous tab?

### ISSUE THREAD

**Issue by tamlok** [wez/wezterm#2267]
Hi,

Is there a shortcut action to alternate between current and previous tab? For example, I am working on tab 2 and tab6 back and forth. I want to use a shortcut to alternate between these two tabs.

Thanks! Wezterm saves my work and life on Windows!

**Comment by wez** [comment]
Take a look at https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateLastTab.html
