### ISSUE TITLE
The close button on the tab overlaps the tab title if the window is too narrow

### ISSUE THREAD

**Issue by rockyzhang24** [wez/wezterm#2269]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220715-193330-73993a60

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If the window is not that narrow, everything works well. 

<img width="805" alt="image" src="https://user-images.githubusercontent.com/11582667/179338519-58cc87fe-7267-42bb-9823-90b730d51267.png">

However, As I keep narrowing the window, the tab title will be covered by the close button.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/11582667/179338591-70b54c87-d166-43b8-b27b-8f59b093a201.png">

### To Reproduce

Just keep narrowing the window.

### Configuration

no config

### Expected Behavior

The tab title should be truncated before it touches the close button.

**Comment by rockyzhang24** [comment]
Or even though the window is maximized, if we open some tabs and their titles are kinda long, this issue happens as well. 
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/11582667/179682113-918bd067-d636-49ed-8d92-f3889f8a8ce4.png">

I already went through the existing issues, discussions and the documentation, but I didn't find a way to deal with it. @wez Any workaround for this? Thank you so much.

**Comment by rockyzhang24** [comment]
Thank you. I just want to make sure whether the solution is existing in some place but I didn't find it. I  don't mean to push you at all. Btw, I love wezterm so much and thank you for putting so much effort into developing and maintaining it.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by rockyzhang24** [comment]
Appreciate your investigation and fixing and thank you for this detailed instructions. I just gave it a shot and it works like a charm. 

Would it be better if the gap between the text and `x` button is a little larger? To make it look harmonious and consistent, what do you think of making the gap equal to the one between `x` button and right edge of the tab, i.e., making the width of the yellow area is equal to the width of the red? 

<img width="556" alt="180353321-8e907da9-e878-4892-a3d4-22dabc7ca268" src="https://user-images.githubusercontent.com/11582667/180355723-491dd215-578a-476a-894b-a444015d85b3.png">

Thank you so much.

**Comment by wez** [comment]
Do you want to try playing around with the padding/margins for the x-button and submit a PR?

https://github.com/wez/wezterm/blob/67ae0e021f9e2c1fb768f0e9d0038a979d11c395/wezterm-gui/src/termwindow/render.rs#L743-L754

The x button floats to the right of the tab, so it doesn't directly influence the tab title text, but sits in front of it.

**Comment by rockyzhang24** [comment]
Sure. I will try to see whether I can make it better. Because this issue has been fixed, I will close it. Thank you again.
