### ISSUE TITLE
F5-F12 all produce ";1~"

### ISSUE THREAD

**Issue by luben** [wez/wezterm#227]
## Describe the bug

F5-12 keys all produce ";1~" (in the terminal)  and "Ding! (this is the bell)" in the log.

## Environment (please complete the following information):

 - OS: Linux X11, tried Ubuntu 16.04 and Debian Sid
 - Version: wezterm 20200608-110940-3fb3a61-62-g28eda766 (recent builds from /master)

## To Reproduce

I have noticed it running `htop` where F6 is used to change ordering. It does not open the menu but jumps to PID 1, same as typing "~1". The same happens for the rest of F5-F12 keys.

On another side, vim does not have problems.

## Configuration

The same behavior with no configuration

## Expected behavior
I would extpect F5-F12 to work like in other terminals

## Additional context
TERM=xterm-256color
The same behavior under zsh/bash/dash

**Comment by wez** [comment]
Thanks for reporting this!  This was an accidental unconditional bleed through of the CSI-u key encoding stuff.
This should be resolved by 59ca0da (and by that I mean, I ran htop with this and F5 toggles the display mode, so that part at least works for me!)

**Comment by luben** [comment]
Thanks! Works here also
