### ISSUE TITLE
When using domain sockets, terminal inside pane doesn't get resized.

### ISSUE THREAD

**Issue by aca** [wez/wezterm#2270]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220709-231243-60728793

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I split pane vertically and close the pane. terminal doesn't get resized. 
If you look at the bottom of the screenshot. it should show vim's statusline but it doesn't.
It get resized if I resize the wezterm itself.

![image](https://user-images.githubusercontent.com/50316549/179341572-35ad4d0c-48f3-4cb1-aae1-e5732afad824.png)

It only happens when I use daemon? feature.
```
    unix_domains = {
        {
            name = "unix"
        }
    },
    default_gui_startup_args = {"connect", "unix"},
```

### To Reproduce

With the setup below, fill the pane with some text like `find .` or `vim`.
Split vertically and close it.

### Configuration

```
local config = {
    unix_domains = {
        {
            name = "unix"
        }
    },
    default_gui_startup_args = {"connect", "unix"},
    leader = { key = " ", mods = "CTRL", timeout_milliseconds = 1000 },
    send_composed_key_when_left_alt_is_pressed = false,
    keys = {
        { key = "w", mods = "CTRL", action = "QuickSelect" },

        {
            key = '"',
            mods = "LEADER",
            action = wezterm.action({ SplitVertical = { domain = "CurrentPaneDomain" } }),
        },
        {
            key = '"',
            mods = "LEADER|SHIFT",
            action = wezterm.action({ SplitVertical = { domain = "CurrentPaneDomain" } }),
        },

        -- close
        { key = "x", mods = "LEADER", action = wezterm.action({ CloseCurrentPane = { confirm = false } }) },
        { key = "x", mods = "LEADER|SHIFT", action = wezterm.action({ CloseCurrentTab = { confirm = false } }) },
        -- { key = "X", mods = "LEADER", action = wezterm.action({ CloseCurrentTab = { confirm = false } }) },
       }
}

return config
```

### Expected Behavior

Should be resized if other pane is closed.

**Comment by wez** [comment]
I can't reproduce this. Are there other steps needed?
Note that there are a couple of known issues of something being funky around this:
* https://github.com/wez/wezterm/issues/1818
* https://github.com/wez/wezterm/issues/783
