### ISSUE TITLE
like   clink.arg.register_parser  of  cmder

### ISSUE THREAD

**Issue by ooing** [wez/wezterm#2272]
**Is your feature request related to a problem? Please describe.**
Press tab to automatically supplement arg

**Describe the solution you'd like**
 
``` lua
--demo
clink.arg.register_parser("poetry",parser({
    "add",
    "shell",
    "init",
    "build",
    "show",
    "remove",
    "version",
}))
```
1   when  I  input  `poetry` ,   and press   `tab`    will  show
```
➜ poetry
add      build    init     remove   shell    show     version
``` 
2  when  I  input  `poetry   a ` ,   and press   `tab`   will  show
```
➜ poetry  add
```

**Comment by wez** [comment]
Did you try setting up wezterm to launch clink?
Docs are here: https://wezfurlong.org/wezterm/shell-integration.html#using-clink-on-windows-systems
