### ISSUE TITLE
A way to handle hyperlinks with local programs.

### ISSUE THREAD

**Issue by GitSkunk** [wez/wezterm#2275]
Hyperlinks are great but it'd be nice if we could use them with local programs. I tried defining one with a file: target, but I can't find a way to give it parameters.

Ideally something like:
return {
  hyperlink_rules = {
    {
    regex = "[[somepattern]]",
    format = "shell:/home/me/bin/somescript.py $0",
    },
  },
}

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/window-events/open-uri.html

**Comment by GitSkunk** [comment]
> Take a look at: https://wezfurlong.org/wezterm/config/lua/window-events/open-uri.html

Ah, this is very cool. Thanks for the reply and writing wezterm.
