### ISSUE TITLE
Visual feedback after item copied to clipboard

### ISSUE THREAD

**Issue by azzamsa** [wez/wezterm#2276]
**Is your feature request related to a problem? Please describe.**

I am having hard time making sure that the selection is copied to clipboard. Because after hitting `Copy to Clipboard` the selection persists.

**Describe the solution you'd like**

It is okay if the selection persist. We can do multiple copy action with this. However, it will be very useful if we add some visual feedback, such as flashing the selection.

**Describe alternatives you've considered**

Remove the selection if the copy successful.

**Comment by wez** [comment]
You could clear the selection yourself; see: https://wezfurlong.org/wezterm/config/lua/keyassignment/ClearSelection.html
Alternatively, you could use the same mechanism to show a notification when you copy: https://wezfurlong.org/wezterm/config/lua/window/toast_notification.html

**Comment by azzamsa** [comment]
Amazing!
