### ISSUE TITLE
cant exit nano because of copy mode

### ISSUE THREAD

**Issue by alexfeed1990** [wez/wezterm#2282]
this is just stupid and i dont think it's intended to be that way since copy mode is bound to ctrl + shift + x by default to my knowledge, and still, ctrl + x doesnt work and turns on copy mode. ive tried making a custom config with erases the keybind but that didn't work. is there any way to turn copy mode off or anything?

**Comment by wez** [comment]
You should be able to assign `ctrl-shift-X` to https://wezfurlong.org/wezterm/config/lua/keyassignment/DisableDefaultAssignment.html
