### ISSUE TITLE
ScrollbackClear excluding the last line

### ISSUE THREAD

**Issue by vickylance** [wez/wezterm#2290]
**Is your feature request related to a problem? Please describe.**
I use Powerlevel10K with ZSH and I have setup for the prompt to show on next line

<img width="864" alt="image" src="https://user-images.githubusercontent.com/5861833/180244272-4318734f-6c45-4ea0-a92a-409ae5f31ef5.png">

But when I clear using ScrollbackAndViewport its clearing all the lines including the first line of ZSH as shown below.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/5861833/180244757-99f01fde-bbe5-4927-9f32-388a416c29e9.png">

I want to keep the first line generated by Powerlevel10K and prompt on the second line.

ScrollbackOnly is not working in MacOS

**Describe the solution you'd like**

I want a way to ScrollbackClear excluding the last line.

**Describe alternatives you've considered**
Not sure how it works in Alacritty but it works out of the box in Alacritty and it clears excluding the last line keeping the powerlevel10K line intact and prompt on second line.

**Additional context**
Added screenshots above.

My config.

keys = {
     {
       key = 'k',
       mods = 'CMD',
       action = act.ClearScrollback 'ScrollbackAndViewport',
     },
   },

**Comment by wez** [comment]
You can use `act.Multiple` to combine `ClearScrollback` with `SendKey` to send CTRL-L afterwards; that will usually tell the shell to redraw its prompt

**Comment by wez** [comment]
Something like this:

```lua
action = act.Multiple {
   act.ClearScollback 'ScrollbackAndViewport',
   act.SendKey { key = 'L', mods = 'CTRL' },
}
```

**Comment by wez** [comment]
I've clarified the behavior of this action in the docs and added an example for this; that should show up in a few minutes:
https://wezfurlong.org/wezterm/config/lua/keyassignment/ClearScrollback.html
