### ISSUE TITLE
where are man files stored?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [wez/wezterm#2291]
I was trying to find where are the source files for man page corresponding to `wezterm show-keys` are stored??

I tried searching for it, but couldnt find. I did however stumble on the "doc" files - but those are for the documentation stored on the [wezterm](https://wezfurlong.org/wezterm) website.

some files i stumbled upon:
1. https://wezfurlong.org/wezterm/config/lua/keyassignment/index.html
2. https://github.com/wez/wezterm/blob/main/config/src/keyassignment.rs
3. https://github.com/wez/wezterm/blob/main/docs/cli/show-keys.md
4. https://github.com/wez/wezterm/blob/main/docs/config/key-tables.md

----
coming via : https://github.com/wez/wezterm/issues/1592

**Comment by MuhammedZakir** [comment]
What do you mean by "man page"? Output of `wezterm show-keys` is generated when it is executed [1]. There is no man page for WezTerm.

[1] https://github.com/wez/wezterm/blob/d78cc6edb8146c3c2653fd09019029d2cb1cc1e8/wezterm-gui/src/inputmap.rs#L268

**Comment by yashpalgoyal1304** [comment]
ohkay, so, i was thinking that the "generation" could be streamlined a lot, there are many duplicate enteries there which do NOT help when browsing it.

so, where are the key tables?

https://github.com/wez/wezterm/blob/d78cc6edb8146c3c2653fd09019029d2cb1cc1e8/wezterm-gui/src/inputmap.rs#L268-L289

**Comment by MuhammedZakir** [comment]
> so, where are the key tables?

Check for `show_key_table` function.

**Comment by wez** [comment]
`show-keys` purpose is to show you the set of key assignments defined by your config.
It is not appropriate for it to choose to *not* show some of those assignments, so I don't think any modification of that command is necessary.

There are no duplicate entries in the default key assignments.
There are some actions that have multiple different assignments.
Those are present for various portability reasons.

The default assignments are defined starting over here:

https://github.com/wez/wezterm/blob/397bddbf6bcca6e569dfeb89bbbbbb7faa5ea21d/wezterm-gui/src/commands.rs#L189-L196

What exactly are you trying to do?

**Comment by yashpalgoyal1304** [comment]
> What exactly are you trying to do?

i was thinking if the enteries could be made smaller somehow, that is multiple key combos for same action be somehow shown in a more elegant and succinct manner

**Comment by yashpalgoyal1304** [comment]
the matter is not as simple as i thought t'd be... so, closing 😅
