### ISSUE TITLE
not launching hx properly

### ISSUE THREAD

**Issue by yashpalgoyal1304** [wez/wezterm#2294]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220624-141144-bd1b7c5d
wezterm 20220722-074625-ca8bdb83

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

~No, and I'll explain why below~
Yes, and I've updated the version above

### Describe the bug

helix editor `hx` is behaving very weirdly on `wezterm`, but not on any of the following:
* `mintty -o ConPTY=on` 
* `conhost`
* `alacritty`

### To Reproduce

1. Get [helix-22.05-x86_64-windows.zip](https://github.com/helix-editor/helix/releases/tag/22.05)
2. Extract it in the folder
3. Navigate to inside the folder
4. Right click > Open Wezterm here
5. `./hx`

### Configuration

no config

### Expected Behavior

hx editor works

### Logs

19:22:55.261 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 630 4.5.0 - Build 25.20.100.6446 is_context_loss_possible=true wezterm version: 20220624-141144-bd1b7c5d

20:14:05.425  INFO   wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 630 4.5.0 - Build 25.20.100.6446 is_context_loss_possible=true wezterm version: 20220624-141144-bd1b7c5d

```
Debug Overlay
wezterm version: 20220722-074625-ca8bdb83
OpenGL version: Intel(R) UHD Graphics 630 4.5.0 - Build 25.20.100.6446
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>
```

### Anything else?

https://user-images.githubusercontent.com/19423063/180470975-a1c443d4-6d29-4ba5-a397-5a3445e90d7d.mp4

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use 80x24 for the terminal dimensions as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps: open `hx`, then quit `hx`.
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by wez** [comment]
You may also wish to try experimenting with https://wezfurlong.org/wezterm/config/lua/config/allow_win32_input_mode.html

**Comment by yashpalgoyal1304** [comment]
> * Then type `exit`

the issue is that i am unable to interact with the terminal after i launch `hx` as can be seen in the vid

**Comment by yashpalgoyal1304** [comment]
[wezterm-recording-EoY9a1.cast.txt](https://github.com/wez/wezterm/files/9173358/wezterm-recording-EoY9a1.cast.txt)

above is the asciicast recording file, though i was not able to play it

i was able to quit the by typing `:q` thanks to https://github.com/helix-editor/helix/issues/2953#issue-1292549547

**Comment by wez** [comment]
I just tried this with the current nightly build of wezterm and I cannot reproduce the strange effects that you saw:

![image](https://user-images.githubusercontent.com/117777/182197213-102e0737-8fc6-45d0-b66c-f516402ea1f1.png)

There must be something else in your environment that is influencing what's happening for you; it may literally be environment variables, but could be something else that hx is sensitive to.

**Comment by yashpalgoyal1304** [comment]
> There must be something else in your environment that is influencing what's happening for you; it may literally be environment variables, but could be something else that hx is sensitive to.

so, i retried and yeah, you're right.

* wezterm is set to open msys2's bash on my system by default (i dont remember how i did that 😅, and can't figure out the location of config file, `~/.wezterm.lua` doesn't exit)

so, referring to [wezterm/config/launch](https://wezfurlong.org/wezterm/config/launch.html), i tested with the `conhost` or `cmd` as following:
* `cmd` > `wezterm start -- hx` (works)
* `cmd` > `wezterm start -- cmd` > `hx` (works)
* `cmd` > `wezterm start -- cmd` > `bash` > `hx` (doesn't work) > `:q` (quit hx) > `exit` (exit bash) > `hx` (works)
* `wezterm` (starts in bash) > `cmd` > `hx` (doesnt't work) > `:q` (quit hx)
* `wezterm` (starts in bash) > `hx` (doesn't work) (this was the filed issue)

**Comment by yashpalgoyal1304** [comment]
(OT: reply as for the website's sha sum pr:
i can't pull myself together... so, can't focus to work on new things... hopefully will get back to you in few days on that. sry for delay)

**Comment by yashpalgoyal1304** [comment]
for the records, here's a bit more "complete" testing:

* i am launching the commands via the "run" (<kbd>win</kbd> + <kbd>r</kbd>) 
* so that the shell doesn't interfere with the environment variables (as was seen above)

Conclusion:
* launching `hx` from `bash` works only with `mintty` among the 4 tty tested
* launching `hx` from every other combination works

what next:
* a point which can be related to this is that 
* when i launched `wsl` from `mintty` (with msys bash shell), the prompt launched in no color mode, i.e. was plain and colorless
* but when i launched `wsl` from `wezterm` (with msys bash shell), the prompt of that had color
* so, i think this has something to do with how other terminals set the color, vs how `mintty` sets the color

| `tty` ↓ \ `PROG` →                                           | `hx` <br/>(direct) | `cmd` | `powershell` | `bash` |
| ------------------------------------------------------------ | :----------------: | :---: | :----------: | :----: |
| `conhost PROG`                                               |         v          |   v   |      v       | **x**  |
| `alacritty -e PROG` <br/>`alacritty --command PROG`          |         v          |   v   |      v       | **x**  |
| `mintty -o ConPTY=on -e PROG` <br/>`mintty -o ConPTY=on --exec PROG` |         v          |   v   |      v       |   v    |
| `wezterm start PROG` <br/>`wezterm start -- PROG`            |         v          |   v   |      v       | **x**  |

**Comment by yashpalgoyal1304** [comment]
Wow, nice information:

This is not reproduced on `wezterm 20220807-113146-c2fee766` with same `helix 22.05 (27609f50)` 

- awesome, finally - i can use some terminal based text editor in my favourite terminal wezterm

aside, can u do a bisect to see what was causing this, or what has fixed it?

**Comment by wez** [comment]
>  can u do a bisect to see what was causing this, or what has fixed it?

No; I could never reproduce it and I can't afford the time to run down something that was only a problem for one person in a version from months in the past.

**Comment by yashpalgoyal1304** [comment]
would u please allow me dropping my investigations regarding bash on this issue? 
as i do want to try to find out what fixed the issue (which will obviously unearth what was causing it as wel)?? 

u can unsubscribe from this issue if u want.

**Comment by yashpalgoyal1304** [comment]
* current & working version of `bash`: `GNU bash, version 5.2.9(1)-release (x86_64-pc-msys)`
*

**Comment by yashpalgoyal1304** [comment]
Just for summary from above shown issue: this bug was _likely_ caused by `msys2-runtime` - the bug was in cygwin upstream code.
