### ISSUE TITLE
Incorrect background color in new windows and debug overlay after system appearance change

### ISSUE THREAD

**Issue by jason0x43** [wez/wezterm#2295]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220722-074625-ca8bdb83

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If the system appearance is changed, and WezTerm's color scheme depends on the system appearance, the debug overlay and any new windows started WezTerm won't use the correct color scheme.

For example, say I start WezTerm while the system appearance is light. WezTerm uses my light color scheme, and the debug overlay and new windows (created with cmd-n) will also use the light color scheme. If the system appearance changes to dark, the theme in the original WezTerm window and new windows that were created from it will update. However, the debug overlay in either window will still use the light theme, and any new windows created from that point will use the light theme.

The same thing happens if the initial system appearance is dark. WezTerm will be dark, and newly spawned windows will be dark. Updating the system appearance will cause any visible windows to switch to the light theme. However, the debug overlay in any window, and any new windows created from that point, will use the dark theme.

I'm using the following snippet to choose the color scheme based on the system appearance:

```lua
local scheme = "light"
if wezterm.gui.get_appearance():find("Dark") then
  scheme = "dark"
end
```

Changing the initial value of `scheme` affects the debug overlay. For example, if I start WezTerm while the system appearance is light, the debug overlay will use the light scheme. If I toggle the system appearance to dark, the debug overlay will still use the light scheme. However, if I edit my config so that the initial value of `scheme` is `"dark"` and save my config, then open the debug overlay, the overlay will be dark.

### To Reproduce

1. Create a config with light and dark schemes. Use `wezterm.gui.get_appearance` to select the theme.
2. Open a new WezTerm window. Create a new window with cmd-n. Verify that both windows and the debug overlay in both windows use the same color scheme.
3. Change the system appearance.
4. Verify that both windows switch to the appropriate color scheme.
5. Create a new window with cmd-n. Note that it uses the original color scheme.
6. Note that the debug overlays in all windows use the original color scheme.

### Configuration

```lua
local color_schemes = {
  light = {
    foreground = "#53676d",
    background = "#fbf3db",
  },
  dark = {
    foreground = "#b9b9b9",
    background = "#181818",
  }
}

local scheme = "light"
if wezterm.gui.get_appearance():find("Dark") then
  scheme = "dark"
end

return {
  color_schemes = color_schemes,
  color_scheme = scheme,
}
```

### Expected Behavior

New WezTerm windows and the debug overlay should use the same color scheme as existing WezTerm windows.

**Comment by wez** [comment]
Weird bug! Thanks for the precise repro steps!

This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jason0x43** [comment]
I tried the latest nightly and it's working great. Thanks for taking a look!
