### ISSUE TITLE
Incorrect encoding with json_encode

### ISSUE THREAD

**Issue by jason0x43** [wez/wezterm#2302]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220724-225546-4bf89e0c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The new `json_encode` function doesn't always encode correctly. In particular, it seems to have issues with arrays.

### To Reproduce

Run the following snippet in a wezterm.lua and check the debug console:

```lua
local arr = {}
table.insert(arr, {
	top = 0,
	left = 0,
	width = 0,
	height = 20
})
print(wezterm.json_encode(arr))
print(wezterm.json_encode({ foo = "bar", stuff = { 1, 2, 3 } }))
```

The output (at least for me) is:

```
09:44:52.559 INFO logging > lua: [{"height":null,"left":null,"top":null,"width":0}]
09:44:52.559 INFO logging > lua: {"foo":"bar","stuff":[1,null,null]}
```

### Configuration

```lua
local save_win_state = function()
  local arr = {}
  table.insert(arr, {
    top = 0,
    left = 0,
    width = 0,
    height = 20
  })
  print(wezterm.json_encode(arr))
  print(wezterm.json_encode({ foo = "bar", stuff = { 1, 2, 3 } }))
end

return {
  keys = {
    {
      key = "s",
      mods = "CMD|CTRL",
      action = wezterm.action_callback(save_win_state)
    }
  }
}
```

### Expected Behavior

`wezterm.json_encode` should encode Lua structures into equivalent JSON.

### Anything else?

This may be a bit premature since `json_encode` is quite new, but I thought I'd mention it just in case. 🙂

**Comment by wez** [comment]
This should be fixed now in `main`; thanks for reporting it!

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jason0x43** [comment]
I tried this out and it's working great!

On an administrative note, I've been closing issues that I opened when they're resolved. Is that OK, or is there a different workflow in use?

**Comment by wez** [comment]
I like to keep them open until I've written up a changelog + docs; since this is a new feature, there's no changelog needed so we can just close it.
