### ISSUE TITLE
Add support for libssh backend to portable-pty (instead of or in addition to libssh2)

### ISSUE THREAD

**Issue by jirutka** [wez/wezterm#2303]
_wezterm-ssh_ can be built with _libssh_, _(lib)ssh2_ or both. According to the documentation, _libssh_ is the preferred SSH backend and it has been added recently. _portable-pty_ currently supports only _(lib)ssh2_. This means that WezTerm effectively cannot be built without _(lib)ssh2_, i.e. with _libssh_-only.

I don’t think it makes sense to build WezTerm with two SSH backends, at least not for Linux distributions. If _libssh_ and _(lib)ssh2_ are complementary(?) and _libssh_ is preferred, I’d like to build WezTerm with _libssh_-only.

**Comment by wez** [comment]
I'd actually like to remove libssh2 from portable-pty as it fights a bit with running multiple channels on the same session.
wezterm-ssh provides a more flexible interface for that usecase.
Regarding libssh vs libssh2: they both have pros and cons and I don't plan to remove one or the other.
Both libraries are small so it's not a significant overhead to build both or to include both.
