### ISSUE TITLE
Closing panes too quickly causes wezterm to stop accepting input

### ISSUE THREAD

**Issue by dojoteef** [wez/wezterm#2304]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220724-225546-4bf89e0c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If you first open multiple panes in quick succession using `wezterm cli`, if you later close them in quick succession, it is possible to get into a situation where wezterm believes there is no active pane and thus stops accepting input (both keyboard and mouse). This is evidenced by the tab bar [showing the string](https://github.com/wez/wezterm/blob/main/wezterm-gui/src/tabbar.rs#L141) `no pane`.  This also interferes with ⌘+Q for quitting wezterm on macOS, though you can still interact with the red 'X' to close the window (you are prompted with an overlay asking to confirm; the overlay can also be interacted with). Sadly, this means any other panes or tabs in that window can no longer receive input. It seems that other windows are unaffected.

### To Reproduce

I have only been able to cause the issue while using [kakoune](https://kakoune.org). It's an editor with a client/server model, such that you can have multiple clients on different terminals attached to the same editing session. If you issue the `:kill` command on a client, it will close all the clients associated with the connected session and kill the session itself.

In my `kakrc` configuration file I have a command to create a minimal IDE-like setup with a main code window, a documentation window, and a diagnostics window.

```kak
# located in $HOME/.config/kak/kakrc
define-command ide %{
    # Main client
    rename-client main
    set-option global jumpclient main

    evaluate-commands %sh{
        if [ "$kak_client_env_TERM_PROGRAM" = "WezTerm" ]; then
            TOOLS_PANE_ID=$(
                wezterm cli split-pane --cwd $kak_client_env_PWD --cells 10 --bottom -- \
                kak -c $kak_session -e "rename-client tools; set-option global toolsclient tools"
            )
            printf "echo -debug 'Created tools pane (id=$TOOLS_PANE_ID)'"
            DOCS_PANE_ID=$(
                wezterm cli split-pane --cwd $kak_client_env_PWD --right --pane-id $TOOLS_PANE_ID -- \
                kak -c $kak_session -e "rename-client docs; set-option global docsclient docs"
            )
            printf "echo -debug 'Created docs pane (id=$DOCS_PANE_ID)'"
        fi
    }
}
```

If I start the editor with `kak -e ide`, then type `:kill` and press `<enter>` it triggers the bug (the `docs` client should be the active pane at this point). Weirdly, it seems to depend on how many panes I create and which pane I issue the `:kill` command from. For example, if I focus the pane with the `main` or `tools` clients and issue `:kill` it does not run into this issue. If I create an additional split, issuing `:kill` from that split will not cause the issue (though, if you focus the split with the `docs` client and issue `:kill`, weirdly it will *still* cause the issue even though it was not the last pane created).

### Configuration

no config

### Logs

10:28:13.234  INFO   wezterm_gui::termwindow > OpenGL initialized! Apple M1 Pro 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220624-141144-bd1b7c5d
10:28:26.876  WARN   wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(1)
10:28:26.876  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "22t"
10:28:26.913  WARN   wezterm_term::terminalstate            > unhandled XtermKeyMode OtherKeys Some(1)
10:28:26.913  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "22t"
10:28:26.944  WARN   wezterm_term::terminalstate            > unhandled XtermKeyMode OtherKeys Some(1)
10:28:26.944  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "22t"
10:28:32.642  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "23t"
10:28:32.642  WARN   wezterm_term::terminalstate            > unhandled XtermKeyMode OtherKeys Some(0)
10:28:32.642  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "23t"
10:28:32.642  WARN   wezterm_term::terminalstate            > unhandled XtermKeyMode OtherKeys Some(0)
10:28:32.652  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "23t"
10:28:32.652  WARN   wezterm_term::terminalstate            > unhandled XtermKeyMode OtherKeys Some(0)

**Comment by wez** [comment]
Could you run and capture the output from `wezterm cli list` when this reproduces? That might be informative!
Do you think you could try to reduce the repro for this so that kak isn't required?

**Comment by dojoteef** [comment]
You know, I was initially having trouble getting an isolated case, but challenge accepted! Try this minimal repro:

```
mkfifo /tmp/bugtest
wezterm cli split-pane --right --pane-id $(wezterm cli split-pane --bottom -- head -n1 /tmp/bugtest) -- head -n1 /tmp/bugtest && echo "foo" > /tmp/bugtest
```

That seems to reproduce it for me. In order to run `wezterm cli list` I have to have a second window open before issuing the above commands. When I do, I get this output:

```
~> wezterm cli list
WINID TABID PANEID WORKSPACE SIZE   TITLE              CWD
    0     0      0 default   106x56 ~                  file://mbp.local/Users/dojoteef
    1     1      1 default   106x56 wezterm cli list ~ file://mbp.local/Users/dojoteef
```

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by dojoteef** [comment]
Thanks for the super fast turnaround! The fix seems to be working. It's really appreciated!

There is one peculiarity, though. Closing the panes one-by-one rather than all at once (which previously triggered the bug) results in a different pane becoming the active pane. That's a very minor annoyance, so I'll close this as fixed. Thanks again!

**Comment by wez** [comment]
When you say different, what do you see and how is it different?

**Comment by dojoteef** [comment]
Let's say I have a pane layout that initially looks like:

```
-------------------------
|           |           |
|           |           |
|    [A]    |     B     |
|           |           |
|           |           |
-------------------------
```

where `A` is the active pane. Then I split the panes like this:

```
-------------------------
|           |           |
|     A     |           |
|___________|     B     |
|     |     |           |
|  C  | [D] |           |
-------------------------
```

such that `D` is now the active pane. If I quickly kill panes `C` and `D`, then `B` becomes the active pane. But if I kill those two panes one-by-one, then `A` becomes the active pane (which is the behavior I expected).

**Comment by wez** [comment]
Curious about why you expect `A` to be active? I'm not challenging that expectation; it will help me figure out how to reconcile the state in this situation.

**Comment by dojoteef** [comment]
I guess I mentally think of the panes as a tree, with the relationships defined by splitting. In this case, if I split pane `A` to get pane `C`, then split pane `C` to get pane `D`, when I close pane `D` I expect that pane `C` would become active. Similarly closing pane `C` (now that `D` is closed), should activate pane `A`.

Maybe this is an incorrect mental model, but it's one that seemingly reflected my experience when using iTerm2 and also seems to be the case when closing panes one-by-one.

**Comment by wez** [comment]
Thanks; I tweaked the logic a bit; let me know how it works out.  Should be available in a download within about an hour from now.
