### ISSUE TITLE
Wait for process after `wezterm start`

### ISSUE THREAD

**Issue by tgharib** [wez/wezterm#2309]
**Is your feature request related to a problem? Please describe.**

To edit the URL in qutebrowser, qutebrowser launches your specified editor command (`wezterm start -- nvim {file}` in my case) to edit a temporary file and waits for the editor to close to read what you wrote. The problem is that `wezterm start` does not block so qutebrowser gets an empty file back.

**Describe the solution you'd like**

For `wezterm start` to block after launching.

**Describe alternatives you've considered**

**Additional context**

I'm pretty sure this is already possible (I remember reading it) but I can't find the documentation.

**Comment by wez** [comment]
Perhaps you want to run: `wezterm start --always-new-process -- nvim file` ?

**Comment by tgharib** [comment]
Ah yes, that was it, thank you. I guess my eyes glanced over the long description `--always-new-process` because I thought I fully understood it.
