### ISSUE TITLE
support RGBA for OSC 11 (and others)

### ISSUE THREAD

**Issue by kittywitch** [wez/wezterm#2313]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Sway

### WezTerm version

wezterm 20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I ran wezterm with a base16 setup with an alpha channel. Wezterm's OSC 11 handler does not support RGBA. I contemplate this is unlikely to be resolved in a newer version.
```
17:40:23.826  WARN   wezterm_term::terminalstate::performer > Unhandled OSC  11 rgba:efff/ecff/f4ff/d000
17:40:23.827  WARN   wezterm_term::terminalstate::performer > Unhandled OSC  12 7
17:40:23.827  WARN   wezterm_term::terminalstate::performer > Unhandled OSC  708 rgba:efff/ecff/f4ff/d000
17:40:23.827  WARN   wezterm_term::terminalstate::performer > Unhandled OSC  707 rgb:be/46/78
```
It therefore defaults to black instead of stripping the alpha or using the alpha.

### To Reproduce

Use RGBA in your OSC 11 escape sequence.

### Configuration

```lua
       local wezterm = require 'wezterm'
		return {
			font = wezterm.font "Iosevka Nerd Font",
			font_size = 10.000000,
		}
```

### Expected Behavior

For the background to have the alpha value as requested in the OSC sequence.

### Logs

17:40:23.826  WARN   wezterm_term::terminalstate::performer > Unhandled OSC  11 rgba:efff/ecff/f4ff/d000
17:40:23.827  WARN   wezterm_term::terminalstate::performer > Unhandled OSC  12 7
17:40:23.827  WARN   wezterm_term::terminalstate::performer > Unhandled OSC  708 rgba:efff/ecff/f4ff/d000
17:40:23.827  WARN   wezterm_term::terminalstate::performer > Unhandled OSC  707 rgb:be/46/78

**Comment by wez** [comment]
OSC 11 doesn't "officially" support RGBA. I'm interested in enabling that though. I'm curious about the other OSCs that show up in your log output; are those supported by another terminal emulator? Which one?

**Comment by wez** [comment]
`main` now allows `printf "\e]10;rgba(127,127,127,0.4)\x07"` as well as `printf "\e]11;rgba:efff/ecff/f4ff/d000\x07"` styles of setting alpha.  OSC 10 through 12 support alpha values.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by kittywitch** [comment]
urxvt supports it, so my partner tells me

**Comment by kittywitch** [comment]
this fix works (in that it is now the correct RGB value), although i guess you don't have adding color transparency support on your roadmap?

**Comment by wez** [comment]
I see transparency here on my mac:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/117777/181152762-7770bbb6-ff23-4398-98ea-dd659c8d9edc.png">

What are you seeing?

**Comment by kittywitch** [comment]
![image](https://user-images.githubusercontent.com/67870215/181153059-c83635a5-7a70-4e6b-b018-ba4ea53ff1cf.png)

**Comment by kittywitch** [comment]
Thank you tonnes!

**Comment by AnonymouX47** [comment]
Hello!

I just came across this and seem to really buy the idea, most especially the changes in https://github.com/wez/wezterm/commit/6e9a22e199cc40ed75a26708343ea34a899542d5

Please, it would be helpful to have these officially documented [here](https://wezfurlong.org/wezterm/escape-sequences.html#operating-system-command-sequences). Otherwise, it seems the only way to discover support for these would be by experimentation or accident.

Thank you.

**Comment by wez** [comment]
@AnonymouX47 done: https://wezfurlong.org/wezterm/escape-sequences.html#csi-386---foreground-color-rgba
Also note that 718a0218173a1e70896d13d739f87b11afcdb38a switched to using colorspace ID 6 to avoid conflicting with the rarely used CMYK colorspace.

**Comment by AnonymouX47** [comment]
Thanks for your quick response and for the heads up on the vhange, though I had noticed the change among the commit's comments earlier.
