### ISSUE TITLE
wrong rendering for rustup update output

### ISSUE THREAD

**Issue by espositofulvio** [wez/wezterm#2318]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When running `rustup update` in a PowerShell Core 7.3 session
![issue_wezterm](https://user-images.githubusercontent.com/11587761/181297566-4f7ceaa4-6dc6-4701-89c7-ec9e1ba713d8.png)
 the download progress is wrongly rendered, text is appended at an offset instead of being replaced. I noticed the same thing happens with Alacritty but Windows Terminal correctly render the output.

### To Reproduce

Open wezterm with a PowerShell Core session and type `rust update`, if the rust toolchain is updated, the download progress shows as the above picture

### Configuration

local wezterm = require 'wezterm'
return {
    default_prog = { 'pwsh.exe' },
    color_scheme = "Dark+",
    font_size = 11.0,
    font = wezterm.font_with_fallback {
       'Fira Code',
       'Cascadia',
     },
}

### Expected Behavior

The ouput of the download progress should replace the current text instead of being appended

**Comment by wez** [comment]
Did you resize the window while that command was running?

**Comment by espositofulvio** [comment]
No, I didn't. I also tried maximizing the window before launching the command to see if it was a layout problem when the line wraps around, but the result was the same. I tried with the Windows Powershell instead of Powershell Core, same result.
As I said, I noticed the same behaviour with Alacritty, while Windows Terminal rendering is fine.

**Comment by wez** [comment]
I made a recording of the output from rustup. I haven't analyzed it yet; just attaching it here so I don't lose it before I get a chance to really dive in.

[wezterm-recording-nhVfPy.cast.txt](https://github.com/wez/wezterm/files/9235417/wezterm-recording-nhVfPy.cast.txt)

**Comment by espositofulvio** [comment]
I changed for a while to Alacritty, and today tried again WezTerm, this looks fine now, so I there's been some commit that fixed it. I'll close it then.
