### ISSUE TITLE
`replace_current` and `one_shot` in ActivateKeyTable aren't actually optional

### ISSUE THREAD

**Issue by strash** [wez/wezterm#2325]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Documentation says `ActivateKeyTable.replace_current` and `ActivateKeyTable.one_shot` are optional. But if I'm not setting them I'm getting this error:
```
callback error
stack traceback:
        [C]: in field 'ActivateKeyTable'
        /Users/strash/.config/wezterm/wez_map.lua:46: in main chunk
        [C]: in function 'require'
        [string "/Users/strash/.config/wezterm/wezterm.lua"]:3: in main chunk
caused by: Error processing ActivateKeyTable::replace_current: missing field
`replace_current`.
{
    "name": "b",
    "timeout_milliseconds": 10000,
}
```
(and another one for the `missing one_shot`)

### To Reproduce

```lua
local wez = require("westerm")
local A = wez.action
local M = {
  disable_default_key_bindings = true,
  leader = { key = "b", mods = "CTRL", timeout_milliseconds = 10000 },
  keys = { key = "b",
    mods = "LEADER",
    action = A.ActivateKeyTable({
      name = "b",
      timeout_milliseconds = 10000,
      --replace_current = true,
      --one_shot = true,
    })
  },
  key_tables = {
    b = {
      -- tabs
      { key = "h", action = A.MoveTabRelative(-1) },
      { key = "l", action = A.MoveTabRelative(1) },
    },
  }
}
return M
```

### Configuration

^

### Logs

22:08:30.022  ERROR  mux::connui > Configuration Error: callback error
stack traceback:
	[C]: in field 'ActivateKeyTable'
	/Users/strash/.config/wezterm/wez_map.lua:47: in main chunk
	[C]: in function 'require'
	[string "/Users/strash/.config/wezterm/wezterm.lua"]:3: in main chunk
caused by: Error processing ActivateKeyTable::replace_current: missing field `replace_current`.
{
    "name": "b",
    "timeout_milliseconds": 10000,
}
22:08:30.105  INFO   wezterm_gui::termwindow > OpenGL initialized! Apple M1 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220624-141144-bd1b7c5d
22:08:30.133  INFO   wezterm_gui::termwindow > OpenGL initialized! Apple M1 4.1 Metal - 76.3 is_context_loss_possible=false wezterm version: 20220624-141144-bd1b7c5d
22:09:07.017  ERROR  wezterm_gui::termwindow > PaneOutput: wanted mux_window_id=1 from mux, but was not found, cancel mux subscription
22:09:19.099  WARN   wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
22:09:40.393  WARN   wezterm_dynamic::error      > `forse_reverse_video_cursor` is not a valid Config field. Did you mean `force_reverse_video_cursor`? There are too many alternatives to list here; consult the documentation!
22:09:40.401  WARN   wezterm_dynamic::error      > `forse_reverse_video_cursor` is not a valid Config field. Did you mean `force_reverse_video_cursor`? There are too many alternatives to list here; consult the documentation!
22:09:40.419  WARN   wezterm_dynamic::error      > `forse_reverse_video_cursor` is not a valid Config field. Did you mean `force_reverse_video_cursor`? There are too many alternatives to list here; consult the documentation!
22:09:45.225  WARN   wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
22:10:32.811  WARN   wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
22:10:35.257  WARN   wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
22:10:52.912  WARN   wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)

**Comment by wez** [comment]
This is already fixed in nightly builds.

From the changelog:

[Fixed](https://wezfurlong.org/wezterm/changelog.html#fixed)
* [ActivateKeyTable](https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateKeyTable.html)'s replace_current field was not actually optional. Made it optional. [#2179](https://github.com/wez/wezterm/issues/2179)
