### ISSUE TITLE
Allow to set/specify the cursor thickness

### ISSUE THREAD

**Issue by idr4n** [wez/wezterm#2326]
Hi and thanks for an amazing terminal. I found it recently and I'm using it as my daily driver.

I was wondering if there is an option for setting the cursor (beam) thickness to something wider when in insert mode in vim/neovim (I couldn't find that option in the docs), just like `cursor_beam_thickness` in Kitty. The current width is quite good as it is but I just like it slightly wider to make it more visible.

Thanks in advance!

**Comment by idr4n** [comment]
Moved to discussion #2328.

**Comment by idr4n** [comment]
Reopening based on discussion #2328. Thanks again!

**Comment by wez** [comment]
This is now implemented now in `main`:

* [cursor_thickness](https://wezfurlong.org/wezterm/config/lua/config/cursor_thickness.html), [underline_thickness](https://wezfurlong.org/wezterm/config/lua/config/underline_thickness.html), [underline_position](https://wezfurlong.org/wezterm/config/lua/config/underline_position.html) and [strikethrough_position](https://wezfurlong.org/wezterm/config/lua/config/strikethrough_position.html) options to fine tune appearance.


It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by idr4n** [comment]
Hi @wez,

I just tried this new feature out and it is working great for me (in MacOS). I tried the different variants (px, pt, cell, %) and with all I can accomplish the thickness I like (3px in my case).

Thanks a lot for this!

**Comment by AdsonCicilioti** [comment]
Hi @wez,

How i can increase the BlinkingBar thickness?

I'm setting `default_cursor_style = "BlinkingBar"` and ` cursor_thickness = "4px"` but the still with the same thickness.

**Comment by wez** [comment]
@AdsonCicilioti you need to be running a recent nightly build for those options to have an effect
