### ISSUE TITLE
Support ProxyCommand for SSH connections

### ISSUE THREAD

**Issue by vseguip** [wez/wezterm#233]
Wezterm supports SSH connections via libssh2 which means it does not support ProxyCommand in ssh_config. This makes connections from outside the internal network at work fail since they need to go through a proxy. It would be nice if wezterm supported ProxyCommand either by using the ssh crate (libssh supports ssh_config out of the box) or by implementing the same mechanism with libssh2.

**Comment by wez** [comment]
The current state of the `main` branch has improved ssh support; we still use libssh2 under the covers, but now parse and understand a number of options from ssh_config, as well as allow specifying them from the command line:

```
wezterm ssh "-oProxyCommand=nc localhost 22" localhost
```

**Comment by SuperSandro2000** [comment]
Does it use libssh2 to also parse the ssh_config file?

**Comment by wez** [comment]
libssh2 doesn't parse ssh_config files.  wezterm has its own code to parse those files here: https://github.com/wez/wezterm/blob/main/wezterm-ssh/src/config.rs
