### ISSUE TITLE
Program that needs bluetooth permissions just exits

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#2330]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220726-094044-858bc3cc

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm running a program (Home Assistant) that requires bluetooth permissions. I did not have that permission granted to wezterm. When I run Home Assistant it just exits with kill 9 signal from zsh rather than ask me for bluetooth permissions.

I discovered why I was getting a "random" kill -9 from zsh because I ran Home Assistant in MacOS Terminal. When I did it asked for bluetooth permissions and then continued running as expected.

I then went and added wezterm to my list of apps with bluetooth permissions and Home Assistant ran fine.

### To Reproduce

See above.

### Configuration

No relevant config.

### Expected Behavior

Pause running program and ask for bluetooth permissions.

**Comment by wez** [comment]
This is a bit of a macOS wart: wezterm doesn't need bluetooth at all, but now we're going to prompt users about it and make it seem like wezterm is doing something nefarious.  Also, FWIW, wezterm isn't involved in the decision to show a prompt, and has no idea whether a prompt is shown or what the outcome was. This is all magic that happens somewhere else in macOS in response to other programs running :-/

We probably need to add https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_bluetooth to https://github.com/wez/wezterm/blob/main/ci/macos-entitlement.plist for macOS to choose to show the prompt.

**Comment by gwww** [comment]
I'm OK if nothing happens with this. I opened the bug more to alert you this was happening. It took me a bit to figure out what was going on and that the Terminal app prompted.

**Comment by gwww** [comment]
Thanks!
