### ISSUE TITLE
Some ligatures do not display correctly in the shell prompt

### ISSUE THREAD

**Issue by pgosar** [wez/wezterm#2331]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Whatever is default with Gnome 42

### WezTerm version

20220729-180003-ae2e78d8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Some ligatures do not display correctly on the shell prompt, for example >=, <=. However, they do work inside another program like vim, or when you are providing input to a command (for example if you run cat without any args). Other ones like != and === display correctly.

I have tested this with the default fonts and with Fira Code, same result

### To Reproduce

Start wezterm in ZSH use the plugin https://github.com/zsh-users/zsh-syntax-highlighting

I was able to isolate the issue to this plugin so let me know if this is not an issue coming from wezterm, but I think it is since this works fine on kitty terminal

### Configuration

Issue happens with 0 configurations as well.

### Expected Behavior

Ligatures such as <= and >= display correctly.

**Comment by wez** [comment]
Ligatures in wezterm are only expanded for text that has clusters/runs of the same attributes. Most likely your zsh plugin is changing the attributes (color, style and so on) between the codepoints that comprise the ligature, which prevents the ligature from being shaped and rendered by the rules defined in the font.

**Comment by pgosar** [comment]
I see. The way that plugin works is it changes the color of the text you input to red or green based on whether its a valid command. Its interesting then that some ligatures dont have their color changed at all while some do. Anyways, it does sound like this behavior is just a side effect of the way ligatures are implemented, not a bug, and since its not really a big deal anyways we can close this. 

Thanks for your prompt reply.
