### ISSUE TITLE
Background Daemon for faster startup

### ISSUE THREAD

**Issue by pgosar** [wez/wezterm#2332]
**Is your feature request related to a problem? Please describe.**
Wezterm takes a noticeable delay to start (around a second).

**Describe the solution you'd like**
The kitty terminal uses a simple background daemon that runs always, of course automatically on startup. Having a similar thing in wezterm would be very convenient

**Describe alternatives you've considered**
Keeping the terminal open at all times but a background daemon would just be a lot better quality of life

**Additional context**
I have a pretty solid machine in terms of specs and for context even beefier applications like firefox and vscode open near instantly

**Comment by wez** [comment]
There's already a multiplexing daemon, and you can just start wezterm at system start.  I don't think we need another daemon.
1 second to start up sounds long; could you file a separate issue to understand why it takes so long on your system?
