### ISSUE TITLE
Slow startup time (1 second)

### ISSUE THREAD

**Issue by pgosar** [wez/wezterm#2339]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Default with Gnome 42

### WezTerm version

20220729-180003-ae2e78d8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Quite slow startup time (around one second). For context, many other more intensive programs including vscode and firefox open nearly instantly.

Intel 1280p CPU with integrated iris xe graphics, 32gb of ddr5 ram, running Fedora 36 with Linux Kernel 5.18.3. 

As a baseline, it would be helpful to know what startup times others generally experience.

### To Reproduce

Open Wezterm

### Configuration

No Config

### Expected Behavior

I would expect it to open faster since this is a relatively lightweight app

**Comment by wez** [comment]
start wezterm like this: `WEZTERM_LOG=trace wezterm` and detailed logs with timestamps will be created. Look for log lines that seem like a long time apart and please share that context here.

Making an educated guess: I think that a likely cause of such a long delay may correlate with the graphics configuration on your system, and that running `xrandr` on your system may also be similarly slow.  https://github.com/wez/wezterm/issues/2073 is a similar sounding thread with some suggestions.

**Comment by pgosar** [comment]
![image](https://user-images.githubusercontent.com/55164602/182255339-e16b95bb-1d23-4e78-ad69-799594a690ad.png)

Here is the time for xrandr (0.009 seconds). Can you clarify on running that trace wezterm command? 
Any wezterm command is only valid within the wezterm terminal, and trying that command inside wezterm generates hundreds of lines of output near instantaneously, about 2-3 per 0.001 seconds.

**Comment by wez** [comment]
Some people have reported that the appimage runs slower than installing the native packages for their system, so you may wish to try installing the .deb/.rpm or whatever is most compatible with your system.

**Comment by pgosar** [comment]
That is indeed instant! Thanks so much
