### ISSUE TITLE
Right status bar partially shows incorrect background color

### ISSUE THREAD

**Issue by wren** [wez/wezterm#2356]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220803-082104-63d5c00a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When setting the background color on the right status bar, there is always a small section that won't change color.

### To Reproduce

Set the background color to anything (except for `#333333`, because that's the section that always shows up), and observe that there's always a small (~3px wide) section that always shows on the left side of the right status bar.

### Configuration

```lua
wezterm.on("update-right-status", function (window, pane)
  window:set_right_status(wezterm.format({
    {Background={Color='#FFFFFF'}},
    {Text="something"},
  }))
end)
```

### Expected Behavior

I would expect that only the background color that I set show in the status bar (like it does for the title).

### Anything else?

![Item-1_and_Item-0_and_Item-0_and_Item-0_and_Sound_and_Battery_and_ItsycalStatusItem_and_BentoBox_and_Clock](https://user-images.githubusercontent.com/9453067/182722124-bb733e55-81e2-47c0-a407-ba728f095f17.png)

![ItsycalStatusItem_and_BentoBox_and_Clock](https://user-images.githubusercontent.com/9453067/182722545-144d20e2-b593-46a0-bf87-950f12e28920.png)

**Comment by wren** [comment]
I also just wanted to say thank you for such a wonderful terminal! And also thank you for being such a nice person! I've seen how you respond to people here on Github, and I have to say that both the quality of the app, and the quality and empathy in your responses convinced me to switch to Wezterm. Thank you!

**Comment by wez** [comment]
Thanks for the kind words!

I think you're seeing the titlebar color show through in a strip there.

The tab bar will (one day) grow up to be a titlebar replacement and it takes its main background color from the `window_frame` config which was originally used solely for drawing the titlebar on Wayland systems.
Over the top of that are rendered the tabs and the right status area.

https://wezfurlong.org/wezterm/config/appearance.html#native-fancy-tab-bar-appearance has info on how you can change those colors.

**Comment by wren** [comment]
I think it makes sense that it could be the titlebar, but I still can't seem to get rid of the strip.

When I set `active_titlebar_bg = '#ff0000'`, this is what I see:
![Clock_and_Item-0_and_Item-0_and_Sound_and_Battery_and_ItsycalStatusItem_and_BentoBox](https://user-images.githubusercontent.com/9453067/182917714-0d0cfaa7-33ab-4d63-bc30-ff12ccbdac67.png)

I tried every setting on the page from your link but I can't seem to get the strip of `#333333` to go away.

**Comment by wez** [comment]
It turns out that it was using the inactive tab bg color. I've pushed a fix to make it use the titlebar bg color instead!

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wren** [comment]
Just tried the nightly and no longer see the problem. Thank you!
