### ISSUE TITLE
Strange gap between characters in right status bar

### ISSUE THREAD

**Issue by wren** [wez/wezterm#2357]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220803-082104-63d5c00a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have a small battery indicator in the right status bar built using the progress bar glyphs from the Fira Code font (see: https://github.com/tonsky/FiraCode/blob/master/extras/progress.png). But no matter what I do, there is always a small gap after the first character in the progress bar (see screenshot below).

The strange part is that I can print those same characters in the command line below, and it displays as expected, so I don't think it has anything to do with my font settings.

I'm not sure if this happens with other fonts, or only Fira Code. I've tried changing as many variables as I can think of (font size, color, placement, formatting, etc) to no avail.

### To Reproduce

1. Install Fira Code font (`brew install font-fira-code` or `brew install font-fira-code-nerd-font`)
2. Use the below config to see a gap in the bar
3. Run `print -P '100%% %F{green}\uEE03\uEE04\uEE04\uEE04\uEE04\uEE01\uEE01\uEE01\uEE02'` (this `print` is the zsh builtin) to see a similar bar with a gap in the bar

### Configuration

```lua
wezterm.on("update-right-status", function (window, pane)
  local LEFT_FULL = utf8.char(0xee03)
  local MID_FULL = utf8.char(0xee04)
  local MID_EMPTY = utf8.char(0xee01)
  local RIGHT_EMPTY = utf8.char(0xee02)

  local battery = LEFT_FULL .. string.rep(MID_FULL, 5) .. string.rep(MID_EMPTY, 3) .. RIGHT_EMPTY

  window:set_right_status(wezterm.format({
    {Background={Color=_G.COLORS.background}},
    {Foreground={Color='#FFFFFF'}},
    {Foreground={Color=_G.COLORS.split}},
    {Text=' 100% '},
    {Foreground={Color='#98BE65'}},
    {Text=string.format(' %s  ', battery)},
  }))
end)
```

### Expected Behavior

I would expect the same characters in the same font to be displayed in the same way regardless of whether they are in the right status bar or in the main window.

### Anything else?

![font_lua____Dotfiles_bundles_wezterm_config__-_NVIM](https://user-images.githubusercontent.com/9453067/182725400-973fdeae-deb9-468c-815d-57672de7a7fd.png)

**Comment by wez** [comment]
Confirmed. Weird!

While I look into this, if it's really driving you nuts, you may want to try setting `use_fancy_tab_bar = false` to use the retro tab bar; that will use your monospace fonts for the tab bar and right status area.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wren** [comment]
Sorry for the slow reply, but I just tested this on the latest nightly, and it works as expected. Thank you for such a quick fix!
