### ISSUE TITLE
In vim normal mode, ctrl+^ incorrectly enters visual block mode (instead of switching to the alternate buffer)

### ISSUE THREAD

**Issue by krishnakumarg1984** [wez/wezterm#236]
## Description

In `vim` normal mode, `C-^` key combination incorrectly enters the visual-block mode. This is incorrect behaviour. visual block mode is to be entered only upon `C-v`, whereas  `C-^` is meant to switch to alternate buffer.

## Environment

 - OS: macOS 10.15.5 (Catalina)
 - Version: wezterm 20200620-160318-e00b076c

## To Reproduce

1. start vim with all plugins disabled and no rc files, `vim -u NONE`
2. Now do `:set hidden`
3. Open two files, say `file1` and `file2` from disk. `:e file1` followed by `:e file2`.
4. Edit `file2` for a bit. 
5. Ensure that we are in normal mode by pressing `esc` or `C-[`.
5. **Now press `C-^`**
6. `vim` _unexpectedly_ enters visual block mode!

## Configuration

Wezterm was started with the default configuration (`wezterm -n`), and hence not relevant.

## Expected behavior
The `vim` buffer shall switch to the alternate file, in the above case `file 2`.

**Comment by wez** [comment]
Please compare the raw key output in wezterm vs. your iterm configuration:

* Run `xxd`
* Press C-^
* Press enter
* Press CTRL-D

Share the output; on my linux system in both xterm and wezterm I get `1e0a`.
On my macOS system in both iterm and wezterm I also get `1e0a`

In all four of those environments, that key press toggles the alternate buffer in vim.

I cannot reproduce the behavior that you've described, so this sounds like a local configuration issue.

**Comment by krishnakumarg1984** [comment]
Well. This is what I got overall. 

`^M00000000: 0d`

Weirdly, there are two additional observations.

1. Pressing `return/enter` causes a `^M` to appear
2. I had to press `C-d` twice to terminate `xxd`.

**Comment by krishnakumarg1984** [comment]
Okay, I got it. `iterm2` by default provides the following. I am not doing anything specific. The default settings of `iterm2` provide the required already.

<img width="1044" alt="Screenshot 2020-06-29 at 03 03 49" src="https://user-images.githubusercontent.com/15239509/85965693-669ce980-b9b5-11ea-9998-6fa54cad9590.png">

**Comment by krishnakumarg1984** [comment]
@wez any thoughts?

**Comment by wez** [comment]
Are you pressing `CTRL-6` or `CTRL+SHIFT+6`?

**Comment by wez** [comment]
Closing due to lack of feedback

**Comment by krishnakumarg1984** [comment]
@wez  can you please reopen and look into this issue? I have exactly the same issue on my linux workstation as well.  Pressing `CTRL + 6` just makes vim go into visual block mode (which is incorrect).  Just like macOS, I need to force the alternate buffer action using `CTRL + SHIFT + 6`

**Comment by wez** [comment]
`CTRL 6` is not the same thing as `CTRL SHIFT 6`.  They send different sequences.

`iTerm` treating those the same is not a behavior that I plan to emulate; it's the only terminal I've tried that does that, and the behavior is ambiguous.

If you want your particular wezterm to treat `CTRL 6` as `CTRL SHIFT 6` then you can configure a key assignment for that key press to mirror the configuration you see in your iterm settings screenshot.

```lua
local wezterm = require 'wezterm';

return {
  keys = {
    {key="6", mods="CTRL", action=wezterm.action{SendString="\x1e"}},
  }
}
```

**Comment by krishnakumarg1984** [comment]
My wording was not clear, which led to a misunderstanding.

- In Gnome-terminal on Linux, `Ctrl + 6` works correctly as expected in vim, i.e. opens the alternate buffer
- In Wezterm, `Ctrl + 6` incorrectly enters the `visual block` mode in vim. 

Hope I made it clear that there exists a bug in wezterm where `Ctrl + 6` is not working correctly. This has nothing to do with `iterm`.
