### ISSUE TITLE
support csiu

### ISSUE THREAD

**Issue by glepnir** [wez/wezterm#2362]
**Is your feature request related to a problem? Please describe.**
@wez  compare with bug most like a feature ? try this code in neovim. 
```lua
vim.keymap.set('n', '<C-;>', '<C-w>l')
```
in wezterm can't capture the keycode of `;` .so this is not work .in kitty or iterm2 works well.

https://iterm2.com/documentation-csiu.html

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/key-encoding.html

**Comment by glepnir** [comment]
@wez  sorry for bother. make sense! thanks for work
