### ISSUE TITLE
use keyboard-types for termwiz

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#237]
Based on this https://www.reddit.com/r/rust/comments/hi9aq2/platform_keyboard_event_handling/, seems like druid is moving to [keyboard-types](https://crates.io/crates/keyboard-types) trait. Would be good to align here and would avoid learning new apis.

**Comment by wez** [comment]
I saw that crate recently.  I'm not opposed to this idea for termwiz, but for wezterm, those types aren't sufficient to convey enough information about key presses where we know both the composed and raw key information, which we do use to determine how to handle key presses.  I don't think that blocks adopting those types for termwiz, but a little bit of care will be to be taken to ensure that wezterm's key handling isn't impacted (there is some translation from our `window` crate to the termwiz types).

I'm not likely to have time to look at this any time soon... so this might make a good PR for `termwiz` if someone is motivated!

**Comment by prabirshrestha** [comment]
closing since crossterm also might not use. unless everyone uses it doesn't make sense. https://github.com/crossterm-rs/crossterm/issues/450
