### ISSUE TITLE
Scroll unfocused pane

### ISSUE THREAD

**Issue by DanCardin** [wez/wezterm#2373]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220807-193129-ac3a9c00

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Seemingly similar to https://github.com/wez/wezterm/issues/1437. Cannot scroll on a pane which is unfocused, it will instead scroll the currently active pane.

### To Reproduce

Create two panes, attempt to scroll on the inactive one.

### Configuration

no config

### Expected Behavior

(It should be possible to enable the behavior that) scrolling over the inactive pane should scroll the hovered pane, not the currently focused one.

### Anything else?

I could imagine this behavior not being desirable to people, given the lack of mention of it that i can find in config/issues, so perhaps a there ought to be a config option?

**Comment by aaronkollasch** [comment]
I am seeing this as well on Ubuntu 22.04 with WezTerm 20220907-164742-2bbad26d and on macOS 12.6.1 with WezTerm 20220905-102802-7d4b8249.

If the inactive pane has mouse reporting on, I can scroll the hovered inactive pane as expected. However, if the inactive pane has mouse reporting disabled, I cannot scroll on it, for example to access the scrollback. Instead, the scroll input gets sent to the active pane.

**Comment by Felixoid** [comment]
Dear @wez, can I provide some logs to nail the issue down? `debug_key_events` unfortunately doesn't show anything

**Comment by mhanberg** [comment]
What is odd to me is that if I have Pane A: Neovim, Pane B: shell and Pane C: shell, and have Pane C focused, i can't scroll pane B but I can scroll Pane A that has neovim in it

**Comment by djthread** [comment]
I notice this behavior, too! Yes, it would be pretty great to be able to scroll an inactive pane.

I will say I'm otherwise having an excellent time with WezTerm! I really like this one. :+1:
