### ISSUE TITLE
Seems colors, tab_bar, background no longer has any effect

### ISSUE THREAD

**Issue by theherk** [wez/wezterm#2376]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220808-084502-d5755f3e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I use `use_fancy_tab_bar = false` and configure the colors. This has been working nicely, but upon upgrading to 20220807-113146-c2fee766 then again to the nightly 20220808-084502-d5755f3e, the property `colors = { tab_bar = { backgroup = '#xxxxxx'` no longer has any effect at all. It is just the same gray as the fancy tab bar.

### To Reproduce

Using the configuration below, the bar should be solid white.

### Configuration

```lua
local wezterm = require 'wezterm';

-- tokyonight
local C_ACTIVE_BG = "#454459";
local C_ACTIVE_FG = "#7dcfff";
local C_BG = "#1a1b26";
local C_HL_1 = "#7aa2f7";
local C_HL_2 = "#bb9af7";
local C_INACTIVE_FG = "#575673";

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  if tab.is_active then
    return {
      {Foreground={Color=C_HL_1}},
      {Text=" " .. tab.tab_index+1},
      {Foreground={Color=C_HL_2}},
      {Text=": "},
      {Foreground={Color=C_ACTIVE_FG}},
      {Text=tab.active_pane.title .. " "},
      {Background={Color=C_BG}},
      {Foreground={Color=C_HL_1}},
      {Text="|"},
    }
  end
  return {
    {Foreground={Color=C_HL_1}},
    {Text=" " .. tab.tab_index+1},
    {Foreground={Color=C_HL_2}},
    {Text=": "},
    {Foreground={Color=C_INACTIVE_FG}},
    {Text=tab.active_pane.title .. " "},
    {Foreground={Color=C_HL_1}},
    {Text="|"},
  }
end)

return {
  leader = { key="a", mods="CTRL"},
  color_scheme = "tokyonight",
  font = wezterm.font("VictorMono Nerd Font"),
  font_size = 20.0,
  tab_bar_at_bottom = true,
  tab_max_width = 96,
  use_fancy_tab_bar = false,

  colors = {
    tab_bar = {



      -- this doesn't work
      -- usually C_BG, but testing any value here
      background = '#ffffff',




      new_tab = {
        bg_color = C_BG,
        fg_color = C_HL_2,
      },
      active_tab = {
        bg_color = C_ACTIVE_BG,
        fg_color = C_ACTIVE_FG,
      },
      inactive_tab = {
        bg_color = C_BG,
        fg_color = C_INACTIVE_FG,
      },
      inactive_tab_hover = {
        bg_color = C_BG,
        fg_color = C_INACTIVE_FG,
      }
    }
  }
}
```

### Expected Behavior

The retra tab_bar background should be the color given by this attribute.

### Logs

```
Debug Overlay
wezterm version: 20220808-084502-d5755f3e
OpenGL version: Apple M1 4.1 Metal - 76.3
```

### Anything else?

<img width="1014" alt="Screenshot 2022-08-08 at 20 31 50" src="https://user-images.githubusercontent.com/3605078/183488484-83ce5a26-245a-4700-90df-ae58bec1bb5d.png">

**Comment by wez** [comment]
You're using a color scheme, which takes precedence over `colors`:
https://wezfurlong.org/wezterm/config/appearance.html#color-scheme

**Comment by wez** [comment]
See https://wezfurlong.org/wezterm/config/lua/wezterm/get_builtin_color_schemes.html for how to use a color scheme as a base and override specific colors

**Comment by theherk** [comment]
Ah, okay. I remember reading about this before, but not thinking much of it as my configuration was working. I'm not clear on why it went from working to not working if this was the case already, but I understand it shouldn't work as is. Thank you.

**Comment by theherk** [comment]
Actually, @wez, I think I've closed this too hastily. How can the background of the tab bar be set? It is not set to anything, under any color scheme. It would be great if it were, but I can set it with neither the color scheme nor colors.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/appearance.html#tab-bar-appearance--colors describes how to configure the tab bar colors; the config is slightly different depending on whether the fancy tab bar is enabled or not.

FWIW, the nightfox schemes in the nightly now define tab bar colors for retro tab bar:
https://github.com/wez/wezterm/commit/d5755f3ee82ffe89a14ea1c34fe700014d75b2cb
and they are also defined fancy tab bar in the latest stable release.

**Comment by theherk** [comment]
It is possible I'm simply not understanding, but it is also possible I'm just not communicating clearly. Until recently it was possible to change the background color of the retro tab bar. Now it is not at all; using any method described. It is only one color, no matter the setting or the color scheme.

**Comment by theherk** [comment]
Okay. For the sake of posterity if other come looking, here is the working implementation if you want a method to set the tab bar configuration for a given scheme. There are other ways.

```lua
local wezterm = require 'wezterm';

local selected_scheme = "tokyonight";
local scheme = wezterm.get_builtin_color_schemes()[selected_scheme]

local C_ACTIVE_BG = scheme.selection_bg;
local C_ACTIVE_FG = scheme.ansi[6];
local C_BG = scheme.background;
local C_HL_1 = scheme.ansi[5];
local C_HL_2 = scheme.ansi[4];
local C_INACTIVE_FG;
local bg = wezterm.color.parse(scheme.background);
local h, s, l, a = bg:hsla();
if l > 0.5 then
  C_INACTIVE_FG = bg:complement_ryb():darken(0.3);
else
  C_INACTIVE_FG = bg:complement_ryb():lighten(0.3);
end

scheme.tab_bar = {
  background = C_BG,
  new_tab = {
    bg_color = C_BG,
    fg_color = C_HL_2,
  },
  active_tab = {
    bg_color = C_ACTIVE_BG,
    fg_color = C_ACTIVE_FG,
  },
  inactive_tab = {
    bg_color = C_BG,
    fg_color = C_INACTIVE_FG,
  },
  inactive_tab_hover = {
    bg_color = C_BG,
    fg_color = C_INACTIVE_FG,
  }
}

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  if tab.is_active then
    return {
      {Foreground={Color=C_HL_1}},
      {Text=" " .. tab.tab_index+1},
      {Foreground={Color=C_HL_2}},
      {Text=": "},
      {Foreground={Color=C_ACTIVE_FG}},
      {Text=tab.active_pane.title .. " "},
      {Background={Color=C_BG}},
      {Foreground={Color=C_HL_1}},
      {Text="|"},
    }
  end
  return {
    {Foreground={Color=C_HL_1}},
    {Text=" " .. tab.tab_index+1},
    {Foreground={Color=C_HL_2}},
    {Text=": "},
    {Foreground={Color=C_INACTIVE_FG}},
    {Text=tab.active_pane.title .. " "},
    {Foreground={Color=C_HL_1}},
    {Text="|"},
  }
end
)

return {
  color_schemes = {
    [selected_scheme] = scheme
  },
  color_scheme = selected_scheme,
  tab_bar_at_bottom = true,
  use_fancy_tab_bar = false,
}
```

With the remained of the configuration that was omitted for not being relevant to this topic, it ends up looking like:

![Screenshot 2022-08-09 at 03 43 32](https://user-images.githubusercontent.com/3605078/183544597-043bdf7d-9821-4719-80d1-f2e445c2c34a.png)

Thank you for the help, @wez... and of course the excellent software.

**Comment by wez** [comment]
Good to see you use complement_ryb and other color functions!

**Comment by wimstefan** [comment]
I just drop by to thank you. I'm not that bright to find out for myself how I could manage builtin colour schemes with my own needs for some specific colour settings and your configuration helped me a lot to get a working configuration!
So thanks a lot for that 😁🙏
