### ISSUE TITLE
ShowLauncherArgs({ flags = "FUZZY" }) shows an empty launcher

### ISSUE THREAD

**Issue by jason0x43** [wez/wezterm#2377]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220807-193129-ac3a9c00

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When starting the launcher with `wezterm.action.ShowLauncherArgs({ flags = "FUZZY" })`, the launcher is in fuzzy mode, but has no entries.

### To Reproduce

Create a key map to open the launcher menu with `wezterm.action.ShowLauncherArgs({ flags = "FUZZY" })`. Open the launcher, and see that it's empty.

### Configuration

```lua
return {
  keys = {
    { key = "/", mods = "ALT", action = wezterm.action.ShowLauncherArgs({ flags = "FUZZY" }) }
  }
}
```

### Expected Behavior

The launcher should display the default list of entries, but with fuzzy mode active.

### Anything else?

This may be a feature request rather than a bug, but the documentation implies (to me) that passing only the FUZZY flag should open the launcher as normal, but with fuzzy mode enabled.

**Comment by wez** [comment]
When you specify `flags` you are overriding all of the flags, including those that specify what will be shown in the launcher.  So you must also specify those too, as shown in the example at the bottom of the page.

I think the docs could spell this out more clearly.

**Comment by jason0x43** [comment]
I did consider that, but even with all the described flags present, the list of commands doesn't contain everything in the default list. There doesn't seem to be a flag to include the the top block of commands, like "Close the active pane".

Default list:

<img width="745" alt="Screen Shot 2022-08-09 at 10 22 23 AM" src="https://user-images.githubusercontent.com/1042866/183674022-4c63408c-1cd6-4254-8aa1-24f0954c8f6f.png">

List with `ShowLauncherArgs({ flags = "FUZZY|TABS|LAUNCH_MENU_ITEMS|DOMAINS|KEY_ASSIGNMENTS|WORKSPACES" })`:

<img width="1092" alt="Screen Shot 2022-08-09 at 10 19 44 AM" src="https://user-images.githubusercontent.com/1042866/183674520-bb4867b3-1644-47ab-ab18-8e75653dfa95.png">

**Comment by wez** [comment]
ah, you want to add `COMMANDS` for those; looks like that didn't get documented, will add it now

**Comment by jason0x43** [comment]
That works -- thanks!
