### ISSUE TITLE
Tab title misses final character

### ISSUE THREAD

**Issue by TimStricker** [wez/wezterm#2379]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

```
$ wmctrl -m
Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF
```

### WezTerm version

wezterm 20220808-211601-d2892c6f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Usually, the currently running command is shown as the tab title. After upgrading to the latest release (and also to the latest nightly), the final character of the command is missing.

Image below, showing tabs with three different command (`bash`, `top`, `od`). Each tab title is missing the final character.

![image](https://user-images.githubusercontent.com/68423550/183608274-4432d32a-c986-419d-8309-f93650efdf42.png)

### To Reproduce

- Open wezterm
- Run any command
- Check tab title to see missing character

### Configuration

```lua
return {
  initial_cols = 120,
  initial_rows = 36,
  color_scheme = "Hardcore",
  window_background_opacity = 0.92,
  tab_bar_at_bottom = true,
  audible_bell = "Disabled",
  font_size = 12.0,
  enable_scroll_bar = true,
}
```

### Expected Behavior

The complete command name should be shown in the tab title.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by TimStricker** [comment]
That was quick! Tested with the latest nightly AppImage, version ` wezterm 20220807-113146-c2fee766`. 

Tab titles are working as expected with this version, so the issue can be closed. Thanks a lot for the quick fix!
