### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by luben** [wez/wezterm#238]
## Describe the bug

I noticed memory leak in the terminal activity

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20200620-160318-e00b076c-11-gb936e968

## To Reproduce

Run `htop` inside wezterm and monitor the wezterm RSS

**Comment by wez** [comment]
I've been poking at this on and off for a couple of days but I can't capture anything that looks obviously like a leak.
There are a number of caches that we maintain that have a healthily sized upper bound so it is expected to see RSS climb over time, so long as it eventually flattens out.

While looking into this I did spot a recent report in the `lru` crate about some leaky behavior when the cache is full so I updated the lru dep.

**Comment by luben** [comment]
I have build the last commit and tested it. It does not leak on my Debian Sid but leaks on Ubuntu 16.04. I think the problem may be somewere in the Ubutnu X11 stack, so closing

**Comment by wez** [comment]
Would you mind trying a nightly AppImage binary on your Sid system when you have a few minutes?  The AppImage is built on ubuntu 16 and if it is bundling leaky libs then it's worth revising how the AppImage gets built!

**Comment by luben** [comment]
Hmm, didn't try the app image, but noticed that it also leaks on Debian Sid, up to 700MB since last comment.

**Comment by wez** [comment]
Let's keep this open until we get to the bottom of it!

**Comment by luben** [comment]
I have compiled and tested the above changes but it does not bring any improvement. I think it's about redrawing (that htop forces each second). If the tab is not focused it does not leak. Here are some stats taken on 1 minute intervals:
```$ while true; do ps axu | grep wezterm | grep -v grep; sleep 60; done
luben    27148  6.0  0.3 748928 54676 pts/13   Sl+  14:32   0:02 ./target/release/wezterm
luben    27148  3.4  0.3 756108 62860 pts/13   Sl+  14:32   0:03 ./target/release/wezterm
luben    27148  2.6  0.4 764732 71496 pts/13   Sl+  14:32   0:04 ./target/release/wezterm
luben    27148  2.2  0.4 772508 79428 pts/13   Sl+  14:32   0:04 ./target/release/wezterm
luben    27148  2.1  0.5 779892 86564 pts/13   Sl+  14:32   0:05 ./target/release/wezterm
luben    27148  1.9  0.5 787600 94416 pts/13   Sl+  14:32   0:06 ./target/release/wezterm
luben    27148  1.8  0.6 795000 101700 pts/13  Sl+  14:32   0:07 ./target/release/wezterm
luben    27148  1.8  0.6 802208 109060 pts/13  Sl+  14:32   0:08 ./target/release/wezterm
luben    27148  1.7  0.7 809692 116276 pts/13  Sl+  14:32   0:09 ./target/release/wezterm
luben    27148  1.7  0.7 817948 124824 pts/13  Sl+  14:32   0:09 ./target/release/wezterm
luben    27148  1.6  0.8 826392 132996 pts/13  Sl+  14:32   0:10 ./target/release/wezterm
luben    27148  1.6  0.8 827348 134168 pts/13  Sl+  14:32   0:11 ./target/release/wezterm
luben    27148  1.5  0.8 827348 134184 pts/13  Sl+  14:32   0:11 ./target/release/wezterm
luben    27148  1.4  0.8 827348 134196 pts/13  Sl+  14:32   0:11 ./target/release/wezterm
luben    27148  1.3  0.8 827348 134212 pts/13  Sl+  14:32   0:12 ./target/release/wezterm
luben    27148  1.3  0.8 827348 134224 pts/13  Sl+  14:32   0:12 ./target/release/wezterm
luben    27148  1.2  0.8 827348 134240 pts/13  Sl+  14:32   0:12 ./target/release/wezterm
... here we switched the htop tab of, stayed focus on the "while true ..." tab, so no noticeable increase ...
... then I switched back ...
luben    27148  0.6  0.8 828736 135596 pts/13  Sl+  14:32   0:32 ./target/release/wezterm
luben    27148  0.6  0.8 828736 135628 pts/13  Sl+  14:32   0:32 ./target/release/wezterm
luben    27148  0.6  0.8 828736 135656 pts/13  Sl+  14:32   0:32 ./target/release/wezterm
luben    27148  0.6  0.8 828876 135684 pts/13  Sl+  14:32   0:33 ./target/release/wezterm
luben    27148  0.6  0.8 828876 135712 pts/13  Sl+  14:32   0:33 ./target/release/wezterm
luben    27148  0.6  0.8 828876 135744 pts/13  Sl+  14:32   0:33 ./target/release/wezterm
luben    27148  0.6  0.8 828876 135776 pts/13  Sl+  14:32   0:33 ./target/release/wezterm
luben    27148  0.6  0.8 835452 142316 pts/13  Sl+  14:32   0:35 ./target/release/wezterm
luben    27148  0.6  0.9 846496 153264 pts/13  Sl+  14:32   0:35 ./target/release/wezterm
luben    27148  0.6  1.0 857036 163920 pts/13  Sl+  14:32   0:36 ./target/release/wezterm
...
luben    27148  0.8  3.6 1280376 586928 pts/13 Sl+  14:32   1:12 ./target/release/wezterm
luben    27148  0.8  3.6 1287724 594488 pts/13 Sl+  14:32   1:12 ./target/release/wezterm
luben    27148  0.8  3.6 1295260 602052 pts/13 Sl+  14:32   1:13 ./target/release/wezterm
luben    27148  0.8  3.7 1302320 609024 pts/13 Sl+  14:32   1:14 ./target/release/wezterm
luben    27148  0.8  3.7 1308984 615496 pts/13 Sl+  14:32   1:15 ./target/release/wezterm
luben    27148  0.8  3.8 1315824 622636 pts/13 Sl+  14:32   1:16 ./target/release/wezterm
luben    27148  0.8  3.8 1322784 629596 pts/13 Sl+  14:32   1:17 ./target/release/wezterm
luben    27148  0.8  3.8 1326728 633540 pts/13 Sl+  14:32   1:17 ./target/release/wezterm
```

**Comment by wez** [comment]
Ah, the focus is an interesting data point.  I wasn't keeping it focused while I was letting it run.  I'll retest this way a bit later.

**Comment by wez** [comment]
Do you have a blinking cursor enabled in your config?

**Comment by luben** [comment]
No, no blinking cursor. Here is my config: https://gist.github.com/luben/f3a0811179b50c3d422e55cf6ab0aab5

I have tried also with commented the `harfbuzz_features` config with no change.

**Comment by wez** [comment]
I think this was related to https://github.com/wez/wezterm/issues/306 and I haven't seen any truly leaky behavior in a while, so let's call this closed.

**Comment by jsbarrett** [comment]
I just downloaded wezterm tonight and it's using up over 1GB of RAM almost immediately after it starts up, while just sitting and not running any programs.

I'm on OSX 10.15.7
I'm happy to give any other details that may be of help

**Comment by wez** [comment]
> I just downloaded wezterm tonight and it's using up over 1GB of RAM almost immediately after it starts up, while just sitting and not running any programs.
> 
> I'm on OSX 10.15.7
> I'm happy to give any other details that may be of help

Please file a new issue using this template: https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by jsbarrett** [comment]
Sorry it took so long to get back ... my mac is not my primary machine so I just don't get on it as often. But I downloaded nightly and installed/ran it and now the memory sits around 70MB on start up which is WAY better than the gig from before so it seems the issue is already fixed. =)
