### ISSUE TITLE
Support MoveForwardEndWord

### ISSUE THREAD

**Issue by sluongng** [wez/wezterm#2381]
**Is your feature request related to a problem? Please describe.**

I often use `e` instead of `w` in vim to move forward to the end(instead of beginning) of a word.

I would like to use that in Wezterm but it seems like only `MoveForwardWord` is supported

**Describe the solution you'd like**
Introduce `MoveForwardEndWord`, which is similar to `MoveForwardWord` but put the cursor at the end instead of the begining of a word.

**Describe alternatives you've considered**
Binding `e` to run `MoveForwardWord` twice, then back by 1 space. This does not work for a lot of cases.

**Additional context**
N/A

**Comment by activaigor** [comment]
i would like to see this feature as well. i like how wezterm ignores spaces by default so it's also convenient sometimes to just double-w and then cursor left you'll get some word with spaces. but ideally yeah, using 'e' will be much better)

**Comment by wez** [comment]
This was implemented in `main` a little while back: https://github.com/wez/wezterm/pull/2908

**Comment by wez** [comment]
You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.
