### ISSUE TITLE
Fedora RPM assets links are broken in generated docs

### ISSUE THREAD

**Issue by kappa** [wez/wezterm#2382]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

https://wezfurlong.org/wezterm/install/linux.html

See screenshot

![Screenshot from 2022-08-09 08-26-24](https://user-images.githubusercontent.com/47310/183695353-908f59de-5411-452d-9a96-810fbcc5b8b7.png)

### Configuration

no config

**Comment by wez** [comment]
Thanks for reporting this, fixed!
