### ISSUE TITLE
How do I turn off the upgrade prompt?

### ISSUE THREAD

**Issue by onexming** [wez/wezterm#2383]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3,  kde

### WezTerm version

wezterm 20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

How do I turn off the upgrade prompt?  
![image](https://user-images.githubusercontent.com/35001930/183693643-703525a5-96c4-44ab-bcb2-4a0ecc2e57b4.png)
I use manjaro linux. I would like to know how to set, can turn off the upgrade prompt

### Configuration

```lua
local wezterm = require('wezterm')
local catppuccin = require("colors/catppuccin").setup {
    -- whether or not to sync with the system's theme
    sync = true,
    -- the flavours to switch between when syncing
    -- available flavours: "latte" | "frappe" | "macchiato" | "mocha"
    sync_flavours = {
            light = "frappe",
            dark = "frappe"
    },
}
return {
    font = wezterm.font('Fira Code'),
    font_size = 15,
    --window_background_opacity = 0.85,
    enable_scroll_bar = true,
    colors = catppuccin,
}
```

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/config/check_for_updates.html
