### ISSUE TITLE
If use_fancy_tab_bar is set to false, custom tab bar colors are ignored when using a color scheme

### ISSUE THREAD

**Issue by forbjok** [wez/wezterm#2385]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220808-211601-d2892c6f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If *use_fancy_tab_bar* is set to false, custom tab bar colors are ignored completely when using a color scheme.

### To Reproduce

Using the configuration below should reproduce the problem. This config sets the tab bar background to pure white, but as long as *color_scheme* is set, this will be ignored and the bar background will just be gray instead. If *color_scheme* is commented out, the bar background will change to white as it is supposed to.

### Configuration

local wezterm = require 'wezterm'

return {
  color_scheme = 'Dark Pastel',
  use_fancy_tab_bar = false,

  colors = {
    tab_bar = {
      background = '#ffffff',
    },
  },
}

### Expected Behavior

Custom tab bar colors take precedence over color scheme and/or defaults when specified.

**Comment by wez** [comment]
color_scheme takes precedence over `colors`.  See https://github.com/wez/wezterm/issues/2376
