### ISSUE TITLE
bypass_mouse_reporting_modifiers is not working on Mac

### ISSUE THREAD

**Issue by miki725** [wez/wezterm#2389]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

running on mac

### WezTerm version

wezterm 20220810-061048-13064541

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using `tmux`, the bypass mouse reporting function does not seem to work at all. As per https://github.com/wez/wezterm/issues/581 tried adding `bypass_mouse_reporting` to each mouse action however that does not help either. When I open wezterm without `tmux` and open something like `fish` directly, mouse events work as expected. Issue is just when using `tmux`.

In case it matters:

```
➜ tmux -V
tmux 3.3a

➜ wezterm -V
wezterm 20220810-061048-13064541
```

### To Reproduce

works as expected:

```
➜ wezterm start -- fish --login
```

cannot bypass mouse events:

```
➜ wezterm start -- tmux
```

### Configuration

```
    -- disable_default_mouse_bindings = true,
    bypass_mouse_reporting_modifiers = "SHIFT",
    mouse_bindings = {
        {
            bypass_mouse_reporting = true,
            event = { Down = { streak = 1, button = "Left" } },
            action = wezterm.action.SelectTextAtMouseCursor("Block"),
            mods = "SHIFT",
        },
        {
            bypass_mouse_reporting = true,
            event = { Drag = { streak = 1, button = "Left" } },
            mods = "SHIFT",
            action = wezterm.action.ExtendSelectionToMouseCursor("Word"),
        },
        {
            bypass_mouse_reporting = true,
            event = { Up = { streak = 1, button = "Left" } },
            mods = "SHIFT",
            action = wezterm.action.CompleteSelectionOrOpenLinkAtMouseCursor("PrimarySelection"),
        },
    },
```

### Expected Behavior

Would expect to be able to bypass mouse reporting to tmux with `SHIFT`

### Logs

```
Debug Overlay
wezterm version: 20220810-061048-13064541
OpenGL version: Intel(R) UHD Graphics 630 4.1 INTEL-16.5.9
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
09:09:59.563 WARN wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
09:09:59.641 WARN wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(7727))
09:09:59.641 WARN wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(7727))
```

### Anything else?

This used to work just fine before recent update (wasnt nightly version) however not sure what was the previous Wezterm version. It must of been at least a month old though.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by miki725** [comment]
wow that was crazy fast! will test when mac build is out. thank you so much

**Comment by miki725** [comment]
works great. thank you so much again!
