### ISSUE TITLE
`CloseCurrentPane` with `confirm = true` doesn't bring up a confirm window

### ISSUE THREAD

**Issue by bwbuhse** [wez/wezterm#2391]
My current config has the line

`{ key = "w", mods = "CTRL|SHIFT", action = wezterm.action.CloseCurrentPane { confirm = true } },`

in the `keys` table. Adding that line did make Ctrl+shift+w close the current pane, but I'm not getting a confirmation window like I do when trying to close the current tab with Super+w.

**Comment by MuhammedZakir** [comment]
See https://wezfurlong.org/wezterm/config/lua/config/skip_close_confirmation_for_processes_named.html.

**Comment by wez** [comment]
@bwbuhse can you share more about what is running in the pane that doesn't prompt? Does it match the list of skippable processes?

**Comment by bwbuhse** [comment]
Ah yeah, it does. I was just in a fish shell. I must've missed that list when I was adding the keybind, thanks!
