### ISSUE TITLE
Borked font rendering in WezTerm 

### ISSUE THREAD

**Issue by gimbles** [wez/wezterm#2393]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME

### WezTerm version

wezterm 20220811-130824-4e0c7771

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

![image](https://user-images.githubusercontent.com/93856041/184300584-64d45b7e-518c-4db5-b98d-24a20387cf29.png)

Notice the weird rendering of the g and i, also notice the extra space between the arrow. There's only one space character there. 

### To Reproduce

Note that this weird rendering only happens in Space Mono for some reason? JetBrains Mono is fine

- Use Space Mono as font
- Type..?

 
![image](https://user-images.githubusercontent.com/93856041/184301075-d154f9ca-4fef-4440-a0bf-139f0c8d4fd3.png)
It isn't a problem with the font itself since it renders OK in other terminals such as GNOME Terminal

### Configuration

```lua
local wezterm = require 'wezterm'
return {
   font = wezterm.font 'Space Mono',
   font_size = 12,
   set_environment_variables = {
      POWERSHELL_TELEMETRY_OPTOUT = "1"
   },
   default_prog = { '/usr/bin/pwsh', '/nologo' },
   color_scheme = "Gruvbox (Gogh)",
   show_update_window = false,
   hide_tab_bar_if_only_one_tab = true,
   default_cursor_style = "SteadyBar"
}

```

### Expected Behavior

I expected it to render correctly :)

### Logs

Starting wezterm from the terminal, there are no logs in stdout. 

### Anything else?

<nil>

**Comment by wez** [comment]
It looks like Space Mono has a ligature for `fi` that causes those letters to cluster together like that.
You can disable ligatures for that font like this:

```lua
font = wezterm.font {
    family = 'Space Mono',
    harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' },
},
```

**Comment by gimbles** [comment]
Oh 🤔

That's..certainly interesting, is there anyway I can leave *some* ligatures? Or possibly use ligatures from another font? I like the arrow ligatures :P

**Comment by wez** [comment]
It depends on the font. Some have stylistic sets that allow you some degree of control.

The Apple Monaco font is another font that has an annoying `fi` ligature like this: I think the font may be "buggy" in that it either doesn't restrict the ligature to be `fi` with no subsequent glyphs, or doesn't correctly encoding spacing for subsequent glyphs.

https://wezfurlong.org/wezterm/config/font-shaping.html has more information on this topic.

**Comment by gimbles** [comment]
Thanks! Will look into it, closing now. 🎉

**Comment by wimstefan** [comment]
You can load the font into [Wakamai Fondue](https://wakamaifondue.com/) ...
There you'll see that the `fi` ligature can switched off with `liga=0`

**Comment by gimbles** [comment]
Thanks for that website! 🤎 
I'll probably use it a lot :)
