### ISSUE TITLE
CMD+ doesn't seem to work with a Swedish keyboard

### ISSUE THREAD

**Issue by Lilja** [wez/wezterm#2398]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220812-094449-c8ca80f6

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Pressing `CMD+` on my MacOS system doesn't zoom in. `CMD-` zooms out, business as usual.

I'm running a Swedish keyboard, which beside the 0, I have a character that produces a plus sign and then a question mark when pressed with shift. Next to it there is a backtick-character(´) and (` with shift) respectively.

[Swedish keyboard on the apple store for reference](https://www.apple.com/se/shop/product/MK2A3S/A/magic-keyboard-svenskt)

When I'm pressing `CMD+`, my CMD mod seems to be ignored, producing a plus character:

<details>

<summary>xxd with CMD+, then +</summary>

<img width="380" alt="bild" src="https://user-images.githubusercontent.com/6134511/184435705-0d2f65dc-6872-402b-b525-4b00c4352b3d.png">

</details>

It seems like when pressing `CMD0`(one char to the left of my plus sign key), it resets the zoom.

### Configuration

no config

**Comment by wez** [comment]
Can you try the latest release?

**Comment by Lilja** [comment]
Woohoo! Works great.
