### ISSUE TITLE
Ctrl + L completely removes the previous output

### ISSUE THREAD

**Issue by chenzhiwei** [wez/wezterm#2405]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Archlinux + Wayland + KDE + KWin

### WezTerm version

20220807-113146-c2fee766

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When I pressed ctrl+l on gnome-terminal, the buffer was shifted upwards outside my view, but I could still scroll back and find the stuff there...

In wez-term, when I press ctrl+l, what's currently in the screen gets cleared and lost forever... while the buffer outside the screen view remains there, unchanged.

### Configuration

I installed with flatpak, nothing configured.

### Expected Behavior

After run `Ctrl + L`, the previous output should be found by scrolling back.

**Comment by wez** [comment]
This isn't a bug; gnome-terminal behaves differently from other terminals in how it handles `CTRL-L`. wezterm behaves the same way as xterm, as do most other terminals.

**Comment by bew** [comment]
(probably too much info in one go if you've never heard of these things, but at least now it's written somewhere)

---

To give a bit more info and propose a basic solution:
Usually with `Ctrl-L` the shell (bash, zsh, ...) (or the program `clear`) tell the terminal to clear the terminal in the following way (using [CSI ANSI sequences](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences)): (for example)

1. `CSI H` Put cursor at the top left corner of the terminal
2. `CSI 2 J` Clear what's currently displayed on the terminal

With this scenario, existing things displayed on the terminal are simply cleared, only lines that were not visible anymore are still available in the scrollback buffer (when you scroll up).

A solution that should work on any terminal, is to change what `Ctrl-L` do to first save existing  content in the scrollback buffer:
1. `CSI n S` Scroll the visible content of the terminal by `n` lines (needs to be computed), to move all useful terminal output to the scrollback buffer
2. then do the same operations as before: put cursor to top left corner, then clear the terminal

To know by how much the terminal needs to be scrolled by (find `n`), it's possible to ask the terminal where the cursor is currently (using `CSI 6n`) and read the reply, then scroll the terminal by the cursor row.

---
If you're using zsh as your shell, you could get inspired by what an implementation of the ideal behavior I did in my config:
https://github.com/bew/dotfiles/blob/1e1117fec1a043027a40e27434acf85d5fdeb00d/zsh/rc/mappings.zsh#L543

_(maybe some day I'll make a proper helper program or a plugin for easy use by everybody)_

**Comment by chenzhiwei** [comment]
@wez Is it possible to add an option for this short cut? If ok, I can try to create a PR for this.

**Comment by wez** [comment]
gnome terminal chooses to implement the `CSI 2 J` behavior differently from its specified behavior. It's not a keyboard shortcut issue but a fundamental terminal emulation/conformance difference, and I don't want it in wezterm.

**Comment by chenzhiwei** [comment]
Thank you for your reply.
