### ISSUE TITLE
How to disable updates avalable title bar text

### ISSUE THREAD

**Issue by TheSafdarAwan** [wez/wezterm#2413]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11

### WezTerm version

wezterm 20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

it's a good thing to show updates info about a program but every time i open up the terminal it shows up the updates available text and it annoys me how can i disable it  

### To Reproduce

`

### Configuration

`

### Expected Behavior

`

### Logs

`

### Anything else?

`

**Comment by TheSafdarAwan** [comment]
![image](https://user-images.githubusercontent.com/87114084/184699395-4288550b-3f04-47be-9421-9c249b2eb721.png)

**Comment by bew** [comment]
Check https://wezfurlong.org/wezterm/config/lua/config/check_for_updates.html

**Comment by TheSafdarAwan** [comment]
> Check https://wezfurlong.org/wezterm/config/lua/config/check_for_updates.html

but somehow it still comes back i already tried the config to update it for a long time
