### ISSUE TITLE
Ability to define window border size and color

### ISSUE THREAD

**Issue by ww7** [wez/wezterm#2417]
Ability to set `window_padding` color would be very useful when background color merges with other windows

**Comment by wez** [comment]
padding is defined as using the background color. I think what you're asking for is a border color, if you're thinking in terms of the css box model:

https://www.w3.org/TR/css-box-3/#box-model

**Comment by ww7** [comment]
I meant to ask about the color for `window_padding`, in my case it is wide`'2cell'` and another color then main background can't help to focus attention when `window_decorations = "RESIZE",`

Sure, border size and color is better.

**Comment by wez** [comment]
This should be fixed now in `main`.  Docs at: https://wezfurlong.org/wezterm/config/lua/config/window_frame.html

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
