### ISSUE TITLE
wezterm can not run in my computer

### ISSUE THREAD

**Issue by r-xiumu** [wez/wezterm#2436]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

windows （One Virtual Desktop ）

system version: 17763.2686
RAM: 16G
no GPU

### WezTerm version

WezTerm-20220807-113146-c2fee766

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I download wezterm from [this page](https://github.com/wez/wezterm/releases/download/20220807-113146-c2fee766/WezTerm-20220807-113146-c2fee766-setup.exe), installed it. When I click wezterm in my Desktop，nothing happened, no  wezterm screen pops up.

### To Reproduce

My system is a virtual desktop, not  a usual laptop with win10. I connect it by chrome. Then:
1. download wezterm
2. installed wezterm
3. click wezterm at desktop

### Configuration

no config

### Expected Behavior

wezterm can open normally.

### Logs

ERROR  wezterm_gui::frontend > Failed to create window: The OpenGL implementation is too old to work with glium

**Comment by r-xiumu** [comment]
I read this issue. https://github.com/wez/wezterm/issues/1813
set "prefer_egl=true", wezterm can start successfully!
But another question happened. When my mourse pointer move to wezterm scrren , mouse pointer's  color change to blank auto, I can't see mouse pointer in wezterm creen. What should I do?

**Comment by wez** [comment]
The mouse cursor hides while you are typing text, but should show again when you move the mouse

**Comment by r-xiumu** [comment]
> 

Maybe my description is not  clearly.
When my mouse pointer move from tab bar to screen, mouse pointer's color from white to black.
If i set one light color scheme. I can see the mouse pointer . But when I set a dark color scheme, I can't see the mouse pointer In screen.

**Comment by r-xiumu** [comment]
@wez When I connect virtual desktop by clientware rather than chrome website ,this bug doesn't appear.
Maybe this bug belong to virtual desktop, not wezterm.

**Comment by wez** [comment]
Yeah, I don't think this is a wezterm bug, so let's close it out!
