### ISSUE TITLE
Foreground selection transparency

### ISSUE THREAD

**Issue by eaglgenes101** [wez/wezterm#2437]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

20220820-080145-8b2ef50c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Selection foreground coloring seems to disregard the alpha channel; all selected text is displayed as the selection foreground color regardless of its original, unselected color

### To Reproduce

Set the foreground color to a value with an alpha value corresponding to some transparency. Then select some text (preferably of various colors to visualize the problem more easily).  

### Configuration

    colors = {
        selection_bg = "rgba(87, 87, 87, 0.5)", 
        selection_fg = "rgba(255, 255, 255, 0.5)", 
        -- And other options which shouldn't be relevant to the issue
        -- No color scheme is used
    },

### Expected Behavior

With the selected foreground color specified to have partial transparency, the color of selected text should be some combination of the RGB (or hsl, or similar) component of the selection color and the unhighlighted color of the text.

### Anything else?

![Screenshot_20220820_131133](https://user-images.githubusercontent.com/8121128/185760645-062894a9-0af6-4ce9-a443-258c665d4086.png)
![Screenshot_20220820_131210](https://user-images.githubusercontent.com/8121128/185760652-a36038b4-56f4-4f08-bc73-31b336939532.png)

**Comment by wez** [comment]
What is currently supported is this behavior:
* If selection_fg is `none` (fully transparent), then the original text foreground color is used
* otherwise, the selection_fg is used

The alpha channel from the foreground is used to blend the text foreground color over the cell background.

There is no alpha blending between text foreground and selection foreground colors as they are mutually exclusive.
