### ISSUE TITLE
Scrolling stops working when a dialog is displayed

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#2447]
### What Operating System(s) are you seeing this problem on?

macOS (currently confirmed) (/ linux -> I remember being annoyed by this)

### Which Wayland compositor or X11 Window manager(s) are you using?

On gnome: mutter, I think (whatever comes with gnome on debian)

### WezTerm version

20220821-195934-0702a716

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have a long running update scripts, e.g. running apt/brew updates and sometimes this scripts shows a dialog in between to confirm or input a password using a dialog. If I've scrolled up during that time, scrolling back stops working. Pressing `<up>` works (at least on mac, have to get back to my linux to confirm there as well), but sometimes I'm unsure what the confirmation is and pressing any key might be dangerous.

### To Reproduce

A way to reproduce (on a mac) is `cat longfile_which_scrolls; sleep 5; dialog --yesno "whatever" 20 20` -> if you scroll up during the sleep, scrolling stops working when the dialog is shown.

### Configuration

no config (at least starting with `wezterm --config-file /dev/null` showed the same problem)

### Expected Behavior

I'm not sure, either:

- Scrolling keeps working and will bring me back to the region where the dialog is shown or
- Even when scrolled up, the dialog is shown (and either after leaving the dialog, I jump to the current cursor or I stay wherever I scrolled to)

**Comment by wez** [comment]
> at least starting with `wezterm --config-file /dev/null`

Pro tip: use `wezterm -n` to conveniently skip loading any config file(s)

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jankatins** [comment]
Works like a charm, thank you!

BTW: I'm always amazed by your turnaround times on any kind of issues and also how small and well explained your commits are. If I ever need to point to a well maintained and exemplary project, wezterm will be my go-to one!

**Comment by wez** [comment]
Thanks for the kind words!
