### ISSUE TITLE
Support parsing tokens in SSH config HostNames

### ISSUE THREAD

**Issue by wespiard** [wez/wezterm#2448]
**Is your feature request related to a problem? Please describe.**
I use the `%h` token in my SSH config file to condense several simlar/sequential hostnames into one `Host` entry, like so:

```
Host foo0 foo1 foo2
  HostName server-%h
  User example
```

However, when I try to connect using `wezterm ssh foo0`, for example, it seems Wezterm is trying to connect directly to `server-%h`, and not expanding properly. `foo0` should expand to `server-foo0`, etc.

**Describe the solution you'd like**
When Wezterm is reading the SSH config file, it should handle some of the relevant tokens found in the `ssh_config` manpage: https://man7.org/linux/man-pages/man5/ssh_config.5.html#TOKENS

I believe `%h` is one of the more commonly used tokens, and is the only one I really care about. 

**Describe alternatives you've considered**
I currently need to change my `.ssh/config` file to have a separate `Host` entry for each unique `HostName`, as follows: 

```
Host foo0
  HostName server-foo0
  User example

Host foo1
  HostName server-foo1
  User example

Host foo2
  HostName server-foo2
  User example
```

**Additional context**
This is more of a quality of life change, but it is really annoying for connecting to over 10 servers with common HostNames.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wespiard** [comment]
Sorry for not replying earlier, I decided to wait a day or two for the Windows nightly build, but forgot. It is working fine for me with the new build. 

Thanks!
