### ISSUE TITLE
wezterm-nightly fails to create a visible window on macOS 10.14.6 (Mojave)

### ISSUE THREAD

**Issue by KyleKing** [wez/wezterm#2451]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

`wezterm 20220821-195934-0702a716`

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

1. WezTerm starts
2. WezTerm appears in the menu bar
3. but a window is never created

### To Reproduce

I'm not familiar with Apple's NSScreen, but I imagine this is just isolated to still using macOS Mojave and not having `localizedName` present.

The last working version of WezTerm on Mojave for me was the stable release: `20220624-141144,bd1b7c5d` (which was before changes in https://github.com/wez/wezterm/commit/99f6fbda15e84792536a4b69b2702b3d502a3c14)

### Configuration

no config

### Expected Behavior

Visible WezTerm UI

### Logs

```sh
2022-08-23 14:19:54.766 wezterm-gui[30185:1561789] -[NSScreen localizedName]: unrecognized selector sent to instance 0x7fdecd635c20
```

### Anything else?

This is closely related to #2440 and likely needs a very similar fix

https://github.com/wez/wezterm/blob/f4b8028e5ea03de5dec975861a9844cb87ccb1e1/window/src/os/macos/connection.rs#L159-L182

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by KyleKing** [comment]
Thanks for the quick fix

Works on Mojave with `wezterm 20220823-123045-65d350be`
