### ISSUE TITLE
Obscene Memory Usage, Possible Memory Leak?

### ISSUE THREAD

**Issue by braxtons12** [wez/wezterm#2453]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE Plasma

### WezTerm version

20220823-195419-3b4e8599

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

This is really a two-part problem:
1. Memory usage is massive when doing anything non-trivial (eg using vim, or even plain old vi, scrolling ls output, etc)
2. The memory will not be freed until ALL wezterm windows have been closed, simply closing the offending window is not enough to reclaim the memory

### To Reproduce

Below are a couple of simple methods to quickly display this behavior:

Method one:
1. open a file in vi (or vim, colored output seems to make it significantly worse)
2. scroll up and down
3. watch memory usage climb until it stabilizes around 1.7GB

Method two:
1. cd /usr/bin
2. ls
3. scroll up and down
4. watch memory usage climb until it stabilizes around 2.2GB

### Configuration

no config necessary

### Expected Behavior

Memory usage should remain low. For example with method two above, Alacritty stays below 60 MB

### Logs

Debug overlay:
wezterm version: 20220823-195419-3b4e8599
OpenGL version: NVIDIA GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 4.6.0 NVIDIA 515.65.01

No log files in $XDG_RUNTIME_DIR/wezterm

### Anything else?

Running on EndeavourOs (Arch Linux)
uname output:
Linux 5.19.3-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sun, 21 Aug 2022 18:55:27 +0000 x86_64 GNU/Linux

**Comment by braxtons12** [comment]
Note: after switching to the latest release build this isn't happening, so it's specific to the nightly version (or more specifically the wezterm-git version in the AUR)

**Comment by wez** [comment]
Most likely its the aggressively over-sized lrucaches. I just pushed a commit to make those a bit more reasonably bounded

**Comment by braxtons12** [comment]
Much better (by an order of magnitude)! Still a little high compared to the stable release and Alacritty (150 MB vs ~60MB for the `ls` example above), but also feels much more responsive, so I'd say that might be a reasonable tradeoff.
