### ISSUE TITLE
No (visible) overlay in Search/Quick Select mode

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#2455]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220823-223426-ad7199c1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I press `CMD+F` (for find) or `Ctrl+Shift+space` (for quick select mode), My cursor moves, but no visible overlay for the search/quick select mode appears. In quick select mode, I also do not see the mentioned chars to select stuff. On the other hand, I do get a response if I e.g. type `A`, it pastes my shown clock (which I display using starship) or when I am in search mode and blindly type a word, the words are highlighted in the shown screen and up/down highlights other instances. I did try opening bash (and without starship), but this also does not show any overlay as described int he screenshots. 

See this video (with `wezterm -n`), where I first insert search mode with `CMD+F` (strangely shown as Copy mode in the tab) and search for `hello` and then quick selection mode and `A`. 

https://user-images.githubusercontent.com/890156/186464478-b0d1e05a-7761-45a8-8f1d-cdb518e54695.mp4

### To Reproduce

No idea. I did run without config (`wezterm -n`) but the same thing happens.

### Configuration

no config

### Expected Behavior

I get the overlay for search and quick select

### Logs

Wehn opening `wezterm -n` from another wezterm (and recording the above video), I got this single line

```
17:40:36.175  WARN   wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
```

**Comment by wez** [comment]
I think https://github.com/wez/wezterm/commit/0fe8bba1472fb4b9a629c68a8adfd28dde793205 fixed this

**Comment by jankatins** [comment]
Wow, the overlay is there, but the highlights within the page are still kept, even if I'm out of the quick select modus:

![image](https://user-images.githubusercontent.com/890156/186480246-bfedcbc3-02f4-4304-86b5-859f174f4335.png)

**Comment by jankatins** [comment]
Just updated to wezterm 20220830-094332-97eaa581 97eaa581 and the above artefact is gon: exeting the quick select area will return the screen to normal formatting
