### ISSUE TITLE
`wezterm ssh` failed on macOS, error `failed to exec: Os { code: 2, kind: NotFound, message: "No such file or directory" };`

### ISSUE THREAD

**Issue by bnoctis** [wez/wezterm#2457]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220824-230415-6962d680

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Running `wezterm ssh usr@host` prints this error message:
```
18:45:38.911  ERROR  wezterm > failed to exec: Os { code: 2, kind: NotFound, message: "No such file or directory" }; terminating
```

### Configuration

no config

**Comment by wez** [comment]
I can't reproduce this, but that error message can only be caused in the case where `wezterm-gui` is not able to be executed.  That is normally installed alongside the `wezterm` executable.
How did you install wezterm?  Can you try reinstalling it?

**Comment by bnoctis** [comment]
Should have noted this - installed through MacPorts. Knowing the root cause it's easy to find out that, the Portfile linked only `wezterm` to a `$PATH` directory, without `wezterm-gui`. I'll patch it there.

**Comment by bnoctis** [comment]
Btw, is `wezterm-mux-server` needed too?

**Comment by wez** [comment]
Yes, `wezterm-mux-server` is also needed for users that wish to use the multiplexer server.

https://github.com/wez/wezterm/blob/main/README-DISTRO-MAINTAINER.md has some notes for redistribution/packaging, but it doesn't explicitly say what goes where.

For reference, here are the major files that get installed by the rpm, and that may make sense for the portfile to install:

```
/etc/bash_completion.d/wezterm
/etc/profile.d/wezterm.sh
/usr/bin/open-wezterm-here
/usr/bin/strip-ansi-escapes
/usr/bin/wezterm
/usr/bin/wezterm-gui
/usr/bin/wezterm-mux-server
/usr/share/zsh/site-functions/_wezterm
```

**Comment by bnoctis** [comment]
The main binaries all have the `wezterm` prefix so I think it's safe to link them to a $PATH directory. But I'd rather let the maintainer decide - cc @herbygillot
