### ISSUE TITLE
Switching input source in macOS

### ISSUE THREAD

**Issue by ncihnegn** [wez/wezterm#246]
## Describe the bug

Switching macOS input source doesn't work

## Environment (please complete the following information):

 - OS: [macOS]
 - Version: 20200620-160318-e00b076c-30-gf64b268e

## Expected behavior

Support macOS input source

## Additional context

It seems ```NSTextInputClient``` support is incomplete. What is missing?

**Comment by wez** [comment]
Please describe exactly what you tried so that I know how to reproduce what you're experiencing!

Did you try enabling the IME?
https://wezfurlong.org/wezterm/config/keys.html#macos-and-the-input-method-editor-ime

**Comment by ncihnegn** [comment]
Got it.
