### ISSUE TITLE
clearScrollback with "ScrollbackAndViewport" does not clear viewport.

### ISSUE THREAD

**Issue by ninjarogue** [wez/wezterm#2464]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Cinnamon and i3wm

### WezTerm version

wezterm 20220827-172221-1398c0d4

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below:

I downloaded the app image because I was unable to install wezterm via "apt" or "linuxbrew".

### Describe the bug
After setting my custom key in the config file, I pressed `ctrl + shift + L` and the viewport was partially cleared but not completely. I had to press the custom key mappings a few more times to completely clear the viewport.

### To Reproduce

Set custom keys as shown in my config file. Press `ctrl + shift + L` in the terminal to observe the behavior.

### Configuration

```lua
local wezterm = require 'wezterm'
local act = wezterm.action



return {
  font = wezterm.font 'JetBrains Mono',
  color_scheme = 'nord',
  enable_tab_bar = false,
  font_size = 16,

  keys = {
    {
      key = 'L',
      mods = 'CTRL|SHIFT',
      action = act.ClearScrollback 'ScrollbackAndViewport',
    }
  }
}
```

### Expected Behavior

When I click `ctrl shift + L`, the terminal viewport should be clear.

### Anything else?

The viewport and scrollback finally clears after pressing `ctrl + shift + L` a few times.

Here is some info about my linux distro:
```md
Distributor ID: Linuxmint
Description:    Linux Mint 21
Release:        21
```

**Comment by wez** [comment]
If you don't experience this issue in the current stable release, then I believe that this is possibly the same visual glitch as https://github.com/wez/wezterm/issues/2467.
In which case, I'd like for you to try the latest stable release in about an hour from now.

**Comment by ninjarogue** [comment]
Okay so I discovered that vi mode was turned on, and when I turned it off it all worked.
