### ISSUE TITLE
Rendering/Glitch Issues When Splitting a Window

### ISSUE THREAD

**Issue by rrpolanco** [wez/wezterm#2467]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220828-205027-b9d0843b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm seeing odd rendering issues and glitches with terminal output when working with splits. Issues such as my prompt not rendering, output from one pane interleaving with adjacent panes, background color flickering, etc.

### To Reproduce

1. Open Wezterm
2. Split the window vertically
3. Split right half horizontally
4. Output text in all the panes and observe your cursor disappear, terminal output interleaving with other panes, etc. 

### Configuration

I made no changes to my config.

### Anything else?

Screen capture of what I'm seeing:
- Split window vertically
- Split right vertical half horizontally
- Cursor is now in the bottom right corner pane
  - Hit <kbd>Enter</kbd> a couple of times and notice how my prompt disappears
  - Tried `clear`ing the screen
  - notice the pane directly above how it changes and the cursor is active (solid block) even though it's not the active pane

![Wezterm_rendering_glitches](https://user-images.githubusercontent.com/6497491/187453959-73d3b7b3-5fd0-4f55-adc3-b97ebd4801e4.gif)

**Comment by wez** [comment]
Should be fixed by a combination 60c5eb1f51b0299bef4055478649fb9280943e5b and ccc1a2beff5f3761bb476a7039aca9126d02c569

**Comment by rrpolanco** [comment]
Thanks @wez . Installing `wezterm 20220830-094332-97eaa581` seemed to have fixed the issue.
