### ISSUE TITLE
Wrong shell selected on macOS

### ISSUE THREAD

**Issue by dev-zero** [wez/wezterm#2469]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220831-225658-7670c4f0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I get this in a new tab/window:

```
colossus:~ tiziano$
```

should be this:

```
~ ❯
```

Trying to identify the shell:

```
colossus:~ tiziano$ ps -p $$
  PID TTY           TIME CMD
97723 ttys004    0:00.01 -sh
```

I suspect commit ad9490ee8ff2c39d7df2f9996055555a9a538b59

### Configuration

```
local wezterm = require 'wezterm';
return {
  audible_bell = "Disabled",
  font = wezterm.font("FiraCode Nerd Font"),
  font_size = 12,
  color_scheme = "Dracula",
  keys = {
    {key="DownArrow", mods="SHIFT", action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
    {key="UpArrow", mods="SHIFT", action=wezterm.action{CloseCurrentTab={confirm=true}}},
    {key="LeftArrow", mods="SHIFT", action=wezterm.action{ActivateTabRelative=-1}},
    {key="RightArrow", mods="SHIFT", action=wezterm.action{ActivateTabRelative=1}},
    {key="LeftArrow", mods="SHIFT|CTRL", action=wezterm.action{MoveTabRelative=-1}},
    {key="RightArrow", mods="SHIFT|CTRL", action=wezterm.action{MoveTabRelative=1}},
  }
}
```

**Comment by MuhammedZakir** [comment]
Also happens on Linux.

OS: Linux X11 -- Manjaro XFCE
WezTerm version: same as OP

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by bigpick** [comment]
Was seeing the same problem and was waiting for the nightly to refresh (on macOS, using brew)

Last retry just now pulled the newest version, and can confirm fixed the above issue for me; now:

```
wezterm --version
wezterm 20220901-052405-9082c79b
```
