### ISSUE TITLE
Why I can't copy and paste

### ISSUE THREAD

**Issue by fire2016you** [wez/wezterm#2470]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I copy text from command、txt、browser url，
paste to wezterm，it become `^V`

### Configuration

Nothing to config, it's empty.

**Comment by wez** [comment]
What precisely are you doing when you paste to wezterm?
Which keys or mouse button(s) are you pressing?

**Comment by wez** [comment]
You need to use either `CTRl-SHIFT-V` or `SHIFT-Insert` to paste.
https://wezfurlong.org/wezterm/config/default-keys.html shows the default key assignments.

**Comment by fire2016you** [comment]
> You need to use either `CTRl-SHIFT-V` or `SHIFT-Insert` to paste. https://wezfurlong.org/wezterm/config/default-keys.html shows the default key assignments.

Thanks.  I have been using `CTRL-V` for many years. I need to take some time to read your document. But from the design point of view, this is abnormal maybe. Of course, this does not affect my liking for wezterm. I should be able to get used to `CTRL-SHIFT-V `.

**Comment by wez** [comment]
wezterm doesn't use `CTRL-v` because that is meaningful to unix terminal applications.
If you don't wish to learn a new shortcut, you can define your own key assignment to let you use it that way:

```lua
local wezterm = require 'wezterm'
local act = wezterm.action

return {
  keys = {
    { key = 'v', mods = 'CTRL', action = act.PasteFrom 'Clipboard' },
  }
}
```
