### ISSUE TITLE
Sluggish window resize on MacOS with integrated graphics

### ISSUE THREAD

**Issue by vdrandom** [wez/wezterm#2473]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220901-084136-ab2c368a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Resizing wezterm window while running integrated graphics on Intel Mac feels very laggy.

If i disable integrated graphics or switch to external normal dpi display it stops lagging.

### Configuration

no config

**Comment by wez** [comment]
I have no plans to optimize for that scenario
