### ISSUE TITLE
Support Variation Selectors VS1 and VS2

### ISSUE THREAD

**Issue by cormullion** [wez/wezterm#2475]
According to https://www.unicode.org/charts/PDF/Unicode-14.0/U140-1D400.pdf, there are variation selectors VS1 (0xFE00) and VS2 (0xFE01) that can change character sets:

<img width="713" alt="Screenshot 2022-09-02 at 16 00 50" src="https://user-images.githubusercontent.com/52289/188177871-a214e622-9586-4c1b-8b49-6e5b28867a7b.png">

I've been struggling to get this working (and struggling to test the font I'm building as a result).

This piece of text contains the VS1 and VS2 characters:

```
1d49c       𝒜    𝒜︀    𝒜︁
212c        ℬ    ℬ︀    ℬ︁
1d49e       𝒞    𝒞︀    𝒞︁
```

(which is constructed from 
```
1d49c       𝒜    𝒜fe00    𝒜fe01
212c        ℬ    ℬfe00    ℬfe01
1d49e       𝒞    𝒞fe00    𝒞fe01
```
)

In VS-Code, I can see it working, occasionally at least:

<img width="227" alt="Screenshot 2022-09-02 at 16 01 49" src="https://user-images.githubusercontent.com/52289/188178061-3841ee7a-1393-4c94-9823-223fc4cd23dc.png">

MacOS Terminal and iTerm2 can only do one:

<img width="281" alt="Screenshot 2022-09-02 at 16 03 25" src="https://user-images.githubusercontent.com/52289/188178374-fe6cd8f6-66e5-4bf4-8dee-51f6b952c0ad.png">

kitty does some:

<img width="278" alt="Screenshot 2022-09-02 at 16 26 51" src="https://user-images.githubusercontent.com/52289/188182886-315d6400-a4fa-4df1-8d56-ca937ee1e04e.png">

wezterm doesn't do any, but it would be nice if it did:

<img width="344" alt="Screenshot 2022-09-02 at 16 16 57" src="https://user-images.githubusercontent.com/52289/188181019-8aec8baf-16b3-48fe-8e09-678a86e75a81.png">

**Comment by wez** [comment]
Do you have a font that I can test this with?

wezterm delegates this sort of thing to the underlying harfbuzz.
Here's what harfbuzz tells me with the symbol font I have available on my linux system:

```
; hb-shape /usr/share/fonts/gdouros-symbola/Symbola.ttf $(printf "\u1d49c") --show-extents --show-flags
[e.sup=0+719<40,1237,640,-674>|c=1+920<53,960,815,-984>]
; hb-shape /usr/share/fonts/gdouros-symbola/Symbola.ttf $(printf "\u1d49c\ufe00") --show-extents --show-flags
[e.sup=0+719<40,1237,640,-674>|c=1+920<53,960,815,-984>|space=1+0<0,0,0,0>]
; hb-shape /usr/share/fonts/gdouros-symbola/Symbola.ttf $(printf "\u1d49c\ufe01") --show-extents --show-flags
[e.sup=0+719<40,1237,640,-674>|c=1+920<53,960,815,-984>|space=1+0<0,0,0,0>]
```

it appears as though harfbuzz is generating a spacing glyph in the place of the variation selector.
I don't know if that is what the font says to do, or if that is an error, but it does show that harfbuzz
is doing something differently from the base case when the variation selector is present.

It's possible that this is a harfbuzz bug?  https://github.com/harfbuzz/harfbuzz/pull/744 is the closest thing to a similar issue I could find in a brief search.

**Comment by wez** [comment]
my printf there is bogus: it doesn't actually do the unicode escape :-p

**Comment by wez** [comment]
```
; hb-shape /usr/share/fonts/gdouros-symbola/Symbola.ttf $(printf "\U1d49c") --show-extents --show-flags
[Ascript=0+1762<-62,1439,2123,-1456>]
; hb-shape /usr/share/fonts/gdouros-symbola/Symbola.ttf $(printf "\U1d49c\Ufe00") --show-extents --show-flags
[Ascript=0+1762<-62,1439,2123,-1456>|space=0+0<0,0,0,0>]
; hb-shape /usr/share/fonts/gdouros-symbola/Symbola.ttf $(printf "\U1d49c\Ufe01") --show-extents --show-flags
[Ascript=0+1762<-62,1439,2123,-1456>|space=0+0<0,0,0,0>]
```

**Comment by cormullion** [comment]
>Do you have a font that I can test this with?

Well, I'm struggling to make something that works, but I'm currently using this to investigate terminal support:

[JuliaMono-Light.ttf.zip](https://github.com/wez/wezterm/files/9480120/JuliaMono-Light.ttf.zip)

Your help and knowledge is most appreciated, Wes!

**Comment by wez** [comment]
![image](https://user-images.githubusercontent.com/117777/188243767-a6e12c8f-bae3-4252-9ba3-0c9f8990b6ea.png)

**Comment by wez** [comment]
so harfbuzz can see it, but `printf "\U1d49c\Ufe01"` doesn't render with the roundhand style in wezterm. Investigating!

**Comment by wez** [comment]
```
; ./target/debug/wezterm --config-file /tmp/2475.lua ls-fonts --text "$(printf \\U1d49c\\Ufe01)"
LeftToRight
 0                   x_adv=10 cells=1  glyph=u1D49C,3387 wezterm.font("JuliaMono", {weight="Light", stretch="Normal", style="Normal"})
                                      /home/wez/Downloads/JuliaMono-Light.ttf/JuliaMono-Light.ttf, FontDirs
 0 𝒜︁   \u{1d49c}\u{fe01} x_adv=0  cells=0  glyph=space,3    wezterm.font("JuliaMono", {weight="Light", stretch="Normal", style="Normal"})
                                      /home/wez/Downloads/JuliaMono-Light.ttf/JuliaMono-Light.ttf, FontDirs
```

that's glyphs 3387 followed by 3.


compared to:

```
; hb-shape ./JuliaMono-Light.ttf $(printf "\U1d49c\Ufe01")  --show-flags --show-extents --no-glyph-names --shapers=ot
[3388=0+1200<26,1463,1147,-1481>]
```

that's glyph 3388

compared to:

```
; hb-shape ./JuliaMono-Light.ttf $(printf "\U1d49c\Ufe01")  --show-flags --show-extents --no-glyph-names --shapers=fallback
[3387=0+1200<69,1494,1080,-1518>|3=1+0<0,0,0,0>]
```

which is glyphs 3387 followed by 3.

So the behavior in wezterm appears to be equivalent to using the fallback shaper in harfbuzz.
However, wezterm doesn't use the fallback shaper.  I've also tried compiling that out, so that only the `ot` shaper is present and wezterm still has that same behavior.

It's taking a bit of effort to drill into this. I'll come back to this a bit later.

**Comment by wez** [comment]
OK, traced this to using harfbuzz's freetype functions for fonts, rather than its opentype functions for fonts.

**Comment by wez** [comment]
Since this seemed to trace to an issue with the font and how freetype handled that, I'm going to close this!

**Comment by cormullion** [comment]
Cool, and thanks! I might be back, if the font-making software gets updated! :)

**Comment by cormullion** [comment]
Just fyi, Georg the Glyphs dev updated the app, I rebuilt the fonts, and now these Variation Selectors all work perfectly in wezterm:

<img width="397" alt="Screenshot 2022-09-08 at 11 54 12" src="https://user-images.githubusercontent.com/52289/189105023-b14a02da-ead2-4a45-95db-502047e77efc.png">

So thanks for helping me investigate and solve this (via the harfbuzz folks)... !

**Comment by wez** [comment]
Good to hear!
