### ISSUE TITLE
update popups are spam

### ISSUE THREAD

**Issue by diefans** [wez/wezterm#248]
## Describe the bug

wezterm is regularly poping up update messages, which are a real spam, since I usually run more than a couple of terminals in my awesome wm. I consider this a bug, since it stops my usual workflow and forces me to do things I do not want to do (closing a lot of messages)

## Environment (please complete the following information):

 - OS: archlinux
 - Version: wezterm 20200620-160318-e00b076c-14-g573f2435

## Expected behavior
Do not disturb.

**Comment by wez** [comment]
You can configure update checking by setting `check_for_updates = false` in your config to disable update checking if you don't want to update to the latest stable version.  Alternatively, you can set `check_for_updates_interval_seconds` to your preferred update interval.
