### ISSUE TITLE
Ability to set Retina font weight

### ISSUE THREAD

**Issue by matthewswitzer** [wez/wezterm#2494]
**Is your feature request related to a problem? Please describe.**

[FiraCode Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode) has a Retina font weight that sits between Normal and Medium. When trying to set Retina as the weight using `wezterm.font('FiraCode Nerd Font', { weight = 'Retina' })` the following error is given:

```bash
callback error
stack traceback:
        [C]: in function 'wezterm.font'
        [string "~/.config/wezterm/wezterm.lua"]:10: in main chunk
caused by: error converting Lua table to Rust Type (Error processing
TextStyleAttributes::weight: invalid font weight Retina.
{
    "weight": "Retina",
})
```

**Describe the solution you'd like**

When setting `{ weight = 'Retina' }`, wezterm should find and use the `Fira Code Retina Nerd Font Complete.ttf` font file.

**Describe alternatives you've considered**

Not sure of any other workarounds other than using one of the other available weights.

**Comment by wez** [comment]
"Retina" isn't a proper or widely used name for a font weight. Under the covers, fonts actually use a numerical weight as the canonical information.

If you run `wezterm ls-fonts --list-system | grep Fira`  you should see something like:

```
wezterm.font("Fira Code", {weight=450, stretch="Normal", style="Normal"}) -- /home/wez/.fonts/FiraCode-Retina.otf, FontConfig
```

so the "Retina" weight is really opentype weight 450.

The bit on the left should be the thing you can copy and paste into your wezterm config to select that font; please give it a try!

```lua
  font = wezterm.font("Fira Code", {weight=450, stretch="Normal", style="Normal"}),
```

**Comment by matthewswitzer** [comment]
Got it, must have skimmed over the fact that you can set numerical weights also. That config you posted works out great. Thanks for the help!
