### ISSUE TITLE
Hyperlinks no longer underlined

### ISSUE THREAD

**Issue by rodolf0** [wez/wezterm#2496]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter (gnome shell)

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hyperlink underlining went away. Click-through seems to work without issues. I couldn't find a styling change in the change-log nor a way to add this in then config.

I've tried the stable and nightly versions.
Stable version: 20220905-102802-7d4b8249
Nightly version: 20220906-085809-c25e6820

### To Reproduce

1. open terminal, and at shell prompt do something like echo 'https://www.google..com'
2. hover mouse cursor over the above output expecting the link to be underlined.
3. link is not underlined :-(

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  -- enable_wayland = false,
  window_frame = {
    border_left_width = '0.2cell', border_left_color = 'grey',
    border_right_width = '0.2cell', border_right_color = 'grey',
    border_top_height = '0.1cell', border_top_color = 'grey',
    border_bottom_height = '0.1cell', border_bottom_color = 'grey',
  },
  window_padding = { left = 0, right = 0, top = 0, bottom = 0, },

  exit_behavior = "Close",
  color_scheme = "Cobalt2",
  initial_cols = 140,
  initial_rows = 40,
  hide_tab_bar_if_only_one_tab = true,

  -- fonts
  font = wezterm.font("JetBrains Mono"), --, {weight="Light"}),
  font_size = 10.5,
  warn_about_missing_glyphs = false,
  -- freetype_load_target = "HorizontalLcd",
  -- freetype_load_flags = "FORCE_AUTOHINT",

  -- keys = {
    -- search for things that look like git hashes
    -- {key="H", mods="SHIFT|CTRL", action=wezterm.action{Search={Regex="[a-f0-9]{6,}"}}},
  -- },

  selection_word_boundary = " \t\n{}[]()<>\"'`,;:=",

  mouse_bindings = {
    -- Default behavior is to follow open links. Disable, just select text.
    {event={Up={streak=1, button="Left"}}, mods="NONE", action=wezterm.action.CompleteSelection("PrimarySelection")},
    -- and make CTRL-Click open hyperlinks (even when mouse reporting)
    {event={Up={streak=1, button="Left"}}, mods="CTRL", action="OpenLinkAtMouseCursor", mouse_reporting=true},
    {event={Up={streak=1, button="Left"}}, mods="CTRL", action="OpenLinkAtMouseCursor"},
    -- Since we capture the 'Up' event, Disable 'Down' of ctrl-click to avoid programs from receiving it
    {event={Down={streak=1, button="Left"}}, mods="CTRL", action="Nop", mouse_reporting=true},
  },

  hyperlink_rules = {
     -- Linkify things that look like URLs
    -- This is actually the default if you don't specify any hyperlink_rules
    {
      regex = "\\b\\w+://(?:[\\w.-]+)\\.[a-z]{2,15}\\S*\\b",
      format = "$0",
    },
    -- file:// URI
    {
      regex = "\\bfile://\\S*\\b",
      format = "$0",
    },
  },
}
```

### Expected Behavior

Hyperlinks should be underlined on mouse-cursor hover.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by azzamsa** [comment]
Worked like a charm! :tada: 

Before:

https://user-images.githubusercontent.com/17734314/189458084-01a7b2e4-781c-4199-9c96-c3319a42611e.mp4

After:

https://user-images.githubusercontent.com/17734314/189458166-1af15a4e-5721-4561-a0af-baad6210d1e8.mp4
