### ISSUE TITLE
ClearScrollback("ScrollbackAndViewport") not working properly

### ISSUE THREAD

**Issue by tngranados** [wez/wezterm#2498]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`ClearScrollback("ScrollbackAndViewport")` seems to be leaving the prompt behind, after typing another key, it seems to update and clear the leftover prompt.

https://user-images.githubusercontent.com/593079/188829351-04f47071-16c9-448f-9364-d8cbf0732773.mov

In the video, I first run `ClearScrollback("ScrollbackAndViewport")` and then type a space.

### To Reproduce

Use `ClearScrollback("ScrollbackAndViewport")`, there should be a duplicated leftover prompt where it used to be before running the function. It will go away after typing another key.

### Configuration

I've tried replicating it without any config (except for the hotkey) and it keeps happening
```lua
local wezterm = require 'wezterm'

return {
  keys = {
    -- Use Shift+Cmd+K to first clear screen and viewport
    {key="k", mods="CMD|SHIFT", action=wezterm.action.ClearScrollback("ScrollbackAndViewport")},
}
```

### Expected Behavior

`ClearScrollback("ScrollbackAndViewport")` should clear the full viewport and scrollback, without leaving a leftover prompt.

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by tngranados** [comment]
That is some quick fix. Works perfectly, thanks @wez.
