### ISSUE TITLE
Supporting LuaRocks Packages

### ISSUE THREAD

**Issue by jeongsoolee09** [wez/wezterm#2501]
It would be nice to support third-party lua scripts installed via LuaRocks, as it would unlock some interesting possibilities like configuring WezTerm with Fennel, just like one would do so with Neovim.

For instance, after installing Fennel via LuaRocks, adding a line starting with `local fennel = require "fennel"` would load the package. Right now, the built-in Lua interpreter seems to not be able to find packages installed through LuaRocks.

**Comment by wez** [comment]
You can manipulate `package.path` from within your `wezterm.lua` to be whatever you wish in order to locate additional `.lua` files.

wezterm doesn't and won't support loading shared object files; see https://github.com/wez/wezterm/issues/2088
