### ISSUE TITLE
A way to modify underline like you can with `modify_font` on Kitty

### ISSUE THREAD

**Issue by datwaft** [wez/wezterm#2505]
**Is your feature request related to a problem? Please describe.**
I am trying to implement [this configuration](https://github.com/lukas-reineke/indent-blankline.nvim#with-context-indent-highlighted-by-treesitter) on the Neovim plugin `indent-blankline`, but for it to work properly I need to be able to modify the underline.

Currently it looks like this on my configuration:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189505839-f2840772-037d-4e64-b9e8-96c7800ef7ba.png">

And I want it to look like this:

![](https://user-images.githubusercontent.com/12900252/188080732-5b7d98b9-3cb8-4789-b28d-67cad0bfbcde.png)

**Describe the solution you'd like**
I would like a way to modify the underline like you can in Kitty by using `modify_font`. [Here](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.modify_font) is the documentation about that.

**Describe alternatives you've considered**
At the moment my only option is to disable the option and have it behave like this:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189505888-7ffa7deb-6f70-48d2-8229-f4a24dd4f1b3.png">

Thanks a lot, btw! I love your terminal

**Comment by wez** [comment]
Related to:
* https://github.com/wez/wezterm/issues/2326
* https://github.com/wez/wezterm/discussions/2328

**Comment by datwaft** [comment]
Thanks! I tried to search for similar issues but couldn't find anything.

**Comment by wez** [comment]
This is now implemented now in `main`:

* [cursor_thickness](https://wezfurlong.org/wezterm/config/lua/config/cursor_thickness.html), [underline_thickness](https://wezfurlong.org/wezterm/config/lua/config/underline_thickness.html), [underline_position](https://wezfurlong.org/wezterm/config/lua/config/underline_position.html) and [strikethrough_position](https://wezfurlong.org/wezterm/config/lua/config/strikethrough_position.html) options to fine tune appearance.


It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by datwaft** [comment]
Thanks! I will test this change in about 2 hours, when the macOS build is available.

**Comment by datwaft** [comment]
I just tested it with `underline_thickness` and `underline_position` and it works perfectly now.

Thanks a lot!

Here is an screenshot of it working:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189513820-81b05a70-f405-42e7-8062-969dd7597c93.png">

For if someone comes here looking for the configuration I used to get this working, here it is:

#### `wezterm.lua`

```lua
return {
  underline_position = "-3.2pt",
  underline_thickness = "1.5pt",
}
```

#### `init.lua` (Neovim)

```
local indent_blankline = require("indent_blankline")

indent_blankline.setup({
  char = "▏",
  show_current_context = true,
  show_current_context_start = true,
})
```

**Comment by gegoune** [comment]
See how that scales when you change font size. I have used:

```lua
  underline_position = '250%',
  underline_thickness = '250%',
```
and it works pretty well I think.
