### ISSUE TITLE
Exclude large test files from bidi data directory

### ISSUE THREAD

**Issue by markbt** [wez/wezterm#2518]
**Is your feature request related to a problem? Please describe.**
The `termwiz-bidi` crate includes several large files as part of tests (e.g. `data/BidiCharacterTest.txt` and `data/BidiTest.txt`).  These files are much larger than the rest of the crate, and they bloat the crate when vendored.

**Describe the solution you'd like**
Exclude these files from the published version of the crate.   They are used in some tests, so the tests will need to handle running without them if compiled from the published crate alone.

**Describe alternatives you've considered**
We could live with the large files, but it would be nice not to have them in our vendored crates.

**Comment by wez** [comment]
It looked like it was just a simple one-line change and publish in the end: doesn't seem necessary to do stuff with the tests.
I published 0.2.1 without the data directory!
