### ISSUE TITLE
Monaco renders very poorly.

### ISSUE THREAD

**Issue by lshoravi** [wez/wezterm#2523]
### What Operating System(s) are you seeing this problem on?

macOS 12.5

### Which Wayland compositor or X11 Window manager(s) are you using?

Running Yabai on macOS 

### WezTerm version

wezterm 20220915-082358-10cd78a8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Monaco renders very poory. See the image, comparing 14pt Monaco on Terminal and on wezTerm 

![Screenshot 2022-09-16 at 15 41 16](https://user-images.githubusercontent.com/42211142/190652733-5fb4c6e7-9ba5-4002-be79-88cc4a20460e.png)

### Configuration

config.font = wezterm.font("Monaco")
config.font_size = 14.0

### Logs

Debug Overlay
wezterm version: 20220915-082358-10cd78a8
OpenGL version: Apple M1 Max 4.1 Metal - 76.3
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
15:37:54.305 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
15:38:24.917 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
15:39:02.466 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
15:39:36.371 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
>

**Comment by lshoravi** [comment]
looks like

```
config.freetype_load_flags = "NO_BITMAP"
```

fixes it.

**Comment by wez** [comment]
Monaco includes bitmap strikes and the closest matching size to your requested font size is selected by default.
You can use `wezterm ls-fonts` to see what wezterm will use when it renders text.

wezterm uses freetype to render text, so it is expected there will be differences with the macOS system text rendering.
