### ISSUE TITLE
Support for modifyOtherKeys escape sequences

### ISSUE THREAD

**Issue by hovsater** [wez/wezterm#2527]
**Is your feature request related to a problem? Please describe.**

I'm trying to migrate from iTerm2, but having some difficulties getting my setup to work correctly. In iTerm2, by default, I'm in the terminal state `Standard Key Reporting Mode`. When I enter [tmux](https://github.com/tmux/tmux/wiki) I automatically enter `modifyOtherKeys Mode 1` due to having [extended-keys](https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys) set to `on` in my tmux config.

<img width="266" alt="Screenshot 2022-09-18 at 12 06 35" src="https://user-images.githubusercontent.com/503025/190896809-c0b3f293-ba7b-493d-9617-f76fd01c504d.png">

The above allow me to use `enter`, `C-enter`, `M-enter`, `S-C-enter` and so on. Without it, only `M-enter` would be recognized.

Unfortunately, I haven't been able to get this to work in WezTerm. It makes it hard for me to use my editor that relies on `C-enter` and `C-S-enter` as an example.

**Describe the solution you'd like**

A way of automatically switching the keyboard encoding to [modifyOtherKeys](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:modifyOtherKeys) when requested.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by wez** [comment]
This has a preliminary implementation now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the change and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
