### ISSUE TITLE
Panic when attempting search in launcher menu

### ISSUE THREAD

**Issue by Eschryn** [wez/wezterm#2529]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

20220917-073624-427477df

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When opening the Launcher menu (I did it via rightclick on the tabbar plus) and pressing Ctrl + Shift + F, wezterm panics

### Configuration

no config is relevant

### Expected Behavior

I expected to be able to search in the Launcher menu 

### Logs

19:31:45.170  ERROR  env_bootstrap           > panic at wezterm-gui/src/overlay/copy.rs:105:14 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: __libc_start_main
  29: <unknown>

thread 'main' panicked at 'pane to have a containing tab', wezterm-gui/src/overlay/copy.rs:105:14
stack backtrace:
   0:     0x562d98a9fcfd - <unknown>
   1:     0x562d98ac98cc - <unknown>
   2:     0x562d98a972b1 - <unknown>
   3:     0x562d98aa1a05 - <unknown>
   4:     0x562d98aa1726 - <unknown>
   5:     0x562d976042f8 - <unknown>
   6:     0x562d98aa204a - <unknown>
   7:     0x562d98aa1e87 - <unknown>
   8:     0x562d98aa01b4 - <unknown>
   9:     0x562d98aa1bb9 - <unknown>
  10:     0x562d9726a303 - <unknown>
  11:     0x562d98ac6d81 - <unknown>
  12:     0x562d98ac6d2b - <unknown>
  13:     0x562d9726a176 - <unknown>
  14:     0x562d9735b1de - <unknown>
  15:     0x562d972c30b3 - <unknown>
  16:     0x562d972946b1 - <unknown>
  17:     0x562d972ad6d8 - <unknown>
  18:     0x562d97343ab3 - <unknown>
  19:     0x562d97f40816 - <unknown>
  20:     0x562d97ee7a58 - <unknown>
  21:     0x562d97ee710f - <unknown>
  22:     0x562d97f2d1ed - <unknown>
  23:     0x562d97fa2ff9 - <unknown>
  24:     0x562d97fa2d32 - <unknown>
  25:     0x562d97fa185b - <unknown>
  26:     0x562d973ede51 - <unknown>
  27:     0x562d9750f528 - <unknown>
  28:     0x562d97375673 - <unknown>
  29:     0x562d973a5249 - <unknown>
  30:     0x562d98a8f80e - <unknown>
  31:     0x562d97515082 - <unknown>
  32:     0x7faecc2f7290 - <unknown>
  33:     0x7faecc2f734a - __libc_start_main
  34:     0x562d9726aa65 - <unknown>
  35:                0x0 - <unknown>

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Eschryn** [comment]
Thank you, it works perfectly now!
And thank you for this amazing Terminal
