### ISSUE TITLE
Support option+left/right on mac to jump words

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#253]
**Is your feature request related to a problem? Please describe.**

On linux I can use ctrl+left/right to jump a word to the left/right. On iterm2 on mac, I similarly configured it to do this in iterm2 using option+left/right (it sends an escape sequence: https://coderwall.com/p/h6yfda/use-and-to-jump-forwards-backwards-words-in-iterm-2-on-os-x). When I press option+left/right in wezterm it inserts `OD` (option+left)/`OC` (option+ right). 

**Describe the solution you'd like**
It would be nice if this word-jumping could be supported and enabled by default or at least described as a config in the manual. Bonus would be if pressing shift+option+left/right would select stuff...

**Comment by wez** [comment]
Did you find and/or play with `SendString` in the keybinding section of the docs?

https://wezfurlong.org/wezterm/config/keys.html#sendstring

```lua
local wezterm = require 'wezterm';

return {
  keys = {
    -- Make Option-Left equivalent to Alt-b which many line editors interpret as backward-word
    {key="LeftArrow", mods="OPT", action=wezterm.action{SendString="\x1bb"}},
    -- Make Option-Right equivalent to Alt-f; forward-word
    {key="RightArrow", mods="OPT", action=wezterm.action{SendString="\x1bf"}},
  }
}
```

**Comment by jankatins** [comment]
AMAZING!

Thanks a lot, I didn't realize that this can send a key combi and not only a simple string. I suppose, as I coudn't find a key combo to "select left/right word", that this is not possible with this approach?

Should I make a PR that adds the above to the key config documentation?

**Comment by wez** [comment]
> I coudn't find a key combo to "select left/right word", that this is not possible with this approach?

Not today.  The closest thing is [copy mode](http://wezfurlong.org/wezterm/copymode.html); you'd press `CTRL SHIFT X` to enable, then `v` to begin selecting, then you could press `OPT LeftArrow` or `OPT RightArrow` to select by word, `CTRL SHIFT C` to copy and then `ESC` to exit copy mode.

That's not quite as streamlined as you want; I can see it being useful to have a way to get into copy mode with selection immediately active, and then a quicker way to copy and exit copy mode.

> Should I make a PR that adds the above to the key config documentation?

Yes please!  I think it would fit well in the `SendString` section.
