### ISSUE TITLE
Dragging the window using tabbar does not respect DEs dragging behavior

### ISSUE THREAD

**Issue by Eschryn** [wez/wezterm#2530]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE Plasma, KWin, SDDM

### WezTerm version

20220917-073624-427477df

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Dragging the window using the tabbar does not respect the desktop environments dragging behavior. In my KDE setup I have wobbly windows, when I drag the window this way, the window doesn't wobble.

### To Reproduce

You need to have KDE set up with wobbly windows. Then move the window by clicking on an empty space on the tabbar - the window does not wobble.

### Configuration

nothing relevant?

### Expected Behavior

The window should wobble as it does by dragging with the titlebar or with Meta + Primary Mouse Button

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Eschryn** [comment]
Finally got around to testing this one too! Everything works as expected. Thank you! Now I can wobble my wezterm 😁
