### ISSUE TITLE
KeyTable Indicator, To know the current keytable's name?

### ISSUE THREAD

**Issue by hh9527** [wez/wezterm#2534]
**Is your feature request related to a problem? Please describe.**
KeyTable is a wonderful feature, but when I enter a keytable, there is no different in the UI to indicate.

**Describe the solution you'd like**
An api to known current keytable's name. And then with event 'format-window-title', I can update the 'window-bar' with the keytable's name.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bew** [comment]
Hello, it is already possible:
```lua
-- Show which key table is active in the status area
wezterm.on('update-right-status', function(window, pane)
  local name = window:active_key_table()
  if name then
    name = 'TABLE: ' .. name
  end
  window:set_right_status(name or '')
end)
```
Found on: https://wezfurlong.org/wezterm/config/key-tables.html
Ref: https://wezfurlong.org/wezterm/config/lua/window/active_key_table.html

**Comment by hh9527** [comment]
@bew Thank you, it works perfect.
