### ISSUE TITLE
Exit confirmation screen ignores config overrides.

### ISSUE THREAD

**Issue by SalomonSmeke** [wez/wezterm#2544]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Preamble: The zip file name disagrees with the output of `wezterm -V` for the nightly, version number might be inaccurate. Archive name is `WezTerm-macos-20220922-073256-c839aeb4`.

Overriding the appearance of Wezterm via `window:set_config_overrides(overrides)` works as expected, but the themeing is lost when in the exit confirmation screen.

See short video:
[WebM](https://user-images.githubusercontent.com/9869123/191872241-513d35cf-bf22-4a50-99df-fd4b249025ee.webm)

### To Reproduce

```lua
local wezterm = require 'wezterm'

wezterm.on('window-config-reloaded', function(window, pane)
  local overrides = {colors = {}, color_scheme = "zenbones"}

  if wezterm.GLOBAL.appearance ~= "set" then
    window:set_config_overrides(overrides)
    wezterm.GLOBAL.appearance = "set"
  end
end)
```

open a wezterm instance with ^ as `.wezterm.lua`. Hit cmd+q. Notice the exit screen looks like the default theme.

### Configuration

see above

### Expected Behavior

The quit confirmation screen retains appearance overrides.

### Anything else?

This is quite minor! there just might be some underlying problem with the whole config and the exit confirmation screen that might be worth exploring?

**Comment by wez** [comment]
As an aside, using `wezterm.GLOBAL.appearance` to gate calling a per-window callback will not work how you expect if you open multiple windows.  I don't think you need to use it at all if you use `window:get_config_overrides` and `window:set_config_overrides` to check and set the config.

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by SalomonSmeke** [comment]
<details>
<summary>Nightly attempt and `.wezterm.lua` followup folded in here (click).</summary>  

### Nightly
I gave the nightly a shot it seems to be not there yet!
I noticed the archive name of the nightly build is the same as it was last night, not sure if that means that name is stuck or maybe the build has not happened yet.

### `.wezterm.lua`
Noted about `GLOBAL`! My actual .wezterm.lua looks like this:
```lua
wezterm.on('window-config-reloaded', function(window, pane)
  local overrides = window:get_config_overrides() or {}
  local appearance = window:get_appearance()


  if wezterm.GLOBAL.last_appearance ~= appearance then
    theme_for_appearance(overrides, appearance)
    window:set_config_overrides(overrides)

    if appearance:find 'Dark' then
      window:toast_notification('wezterm', 'what a horrible night to have a curse.', nil, 1750)
    end

    wezterm.GLOBAL.last_appearance = appearance
  end
end)
```

I was hoping not to set overrides if they had not changed, basically. If this is not necessary I will RM! Thank you for the suggestion.
</details>

I built from source using the instructions [Here](https://wezfurlong.org/wezterm/install/source.html) and it works! Thank you so much.

<img width="842" alt="Screen Shot 2022-09-23 at 09 48 02" src="https://user-images.githubusercontent.com/9869123/191988778-81e21fcb-8cfd-4dd6-bd36-ebbfc089337a.png">

I would close but I don't want to break whatever etiquette/process you prefer, but feel free to!

**Comment by wez** [comment]
Thanks for confirming!
re: macos nightly, looks like there was a burp in the CI.  It should show up eventually!
