### ISSUE TITLE
Add release asset for linux with MUSL

### ISSUE THREAD

**Issue by j-xella** [wez/wezterm#2545]
**Is your feature request related to a problem? Please describe.**
I would like to run wezterm on an older linux box that has outdated libc. Currently, the release assets produce something like this:

```
./wezterm: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./wezterm)
./wezterm: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./wezterm)
./wezterm: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./wezterm)
./wezterm: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_wezterXlTuJL/usr/bin/../lib/libcrypto.so.1.1)
```

**Describe the solution you'd like**
If a release would include an asset built with musl instead of glibc, that could solve the problem. I had success using MUSL assets with other rust projects like bat and ripgrep

**Describe alternatives you've considered**

- I am not proficient at rust, and rust is not installed on my box, so building from sources ( #728 ) is not an option for me.
- I have considered building the newer version of glibc, but I would not like using it, especially with terminal emulator. I would have to modify the library path for that, and the modified library path would be passed down to everything started from the terminal, resulting in potential incompatibility issues.

**Comment by wez** [comment]
This is bigger than just glibc: if glibc is outdated, then there is also a high chance that the other system libraries (X11, Wayland, Mesa) are incompatible.
I don't think there is a supportable-by-me path for your outdated system with pre-built binaries.

The simplest path is for you to build from source following the instructions at https://wezfurlong.org/wezterm/install/source.html

An alternative option might be for you to try taking the Alpine packages and doing something with those.
https://wezfurlong.org/wezterm/install/linux.html#alpine-linux
