### ISSUE TITLE
Close the wezterm with htop running on zoomed pane is not stopping the wezterm process.

### ISSUE THREAD

**Issue by lucasvs** [wez/wezterm#2548]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE/Kwin

### WezTerm version

20220923-050031-8e7a2cce

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Close the wezterm with htop running on zoomed pane is not stopping the wezterm process.

### To Reproduce

- split the pane 
- toggle zoom
- run htop
- close wezterm
- check on other terminal wezterm keep running `ps aux | grep wez`

### Configuration

``` lua
local wezterm = require 'wezterm'
local mux = wezterm.mux

wezterm.on('gui-startup', function(window)
  local tab, top_pane, window = mux.spawn_window(cmd or {})
  local gui_window = window:gui_window();
  local bottom_pane = top_pane:split { direction = 'Bottom' }
  local top_right_pane = top_pane:split { direction = 'Right' }
  local bottom_right_pane = bottom_pane:split { direction = 'Right' }
  gui_window:maximize()
end)

return {
    font = wezterm.font 'JetBrains Mono',
    harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' },
    tab_bar_at_bottom = true,
    font_size = 10.5,
    use_fancy_tab_bar = false,
    color_scheme = 'Dracula+',
    window_close_confirmation = 'NeverPrompt',
    scrollback_lines = 3500,
}
```

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by lucasvs** [comment]
I just tried it and it works now., thank you so much!!
