### ISSUE TITLE
Wezterm doesn't ask for the camera permission when launching apps requiring them

### ISSUE THREAD

**Issue by s-d-m** [wez/wezterm#2551]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220924-081622-3c1cf930

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When launching an app that tries to use the camera, the terminal is supposed to ask MacOS for the permission. This is supposed to open a pop-up where the user can grant the camera permission to the terminal. From there on, apps launched from the terminal can use the camera.

Unfortunately Wezterm doesn't requires the permission.
This bug seems to be exactly like issue #2242 which was fixed at commit 
https://github.com/wez/wezterm/commit/73993a60b42d2bd195712e4e3c408c13da79b3ed

It would probably be wise to do the same with the microphone permission.

Note that Camera permission is already part of wezterm plist.

### To Reproduce

open an app that uses the camera. I used the example_cpp_videocapture_camera from the opencv examples but anything will do.

A workaround in the meantime is:
1. start the terminal app from mac
2. start a camera app from that terminal
3. grant the camera permission
4. launch wezterm from the mac default terminal app
5. enjoy using wezterm

### Configuration

MacOS 12.6 (Monterey)
M1 cpu
Wezterm executed as arm64

### Expected Behavior

popup asking for camera permission should show up

**Comment by wez** [comment]
I've pushed a speculative fix for this to `main`.
That should show up in a nightly build in about an hour; please give it a try and let me know if it works for you!

**Comment by s-d-m** [comment]
Hi,

Thanks for the prompt reply. I just tried it and it works now.

Many thanks!

**Comment by s-d-m** [comment]
I just saw that you added the camera permission to a plist file. I think adding the microphone one too would be wise, for the same reason.
