### ISSUE TITLE
Crash on X11 systems with DRI2 based Intel graphics drivers

### ISSUE THREAD

**Issue by roadriverrail** [wez/wezterm#2559]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3 (Regolith)

### WezTerm version

20220924-194137-47a15153

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Trying to launch Wezterm leads to immediate crash

### To Reproduce

Just launch it, and it crashes

### Configuration

local wezterm = require 'wezterm'
local act = wezterm.action

return {
  scrollback_lines = 3500,
  enable_scroll_bar = true,
  keys = {
    -- Clears the scrollback and viewport, and then sends CTRL-L to ask the
    -- shell to redraw its prompt
    {
      key = 'K',
      mods = 'CTRL|SHIFT',
      action = act.Multiple {
        act.ClearScrollback 'ScrollbackAndViewport',
        act.SendKey { key = 'L', mods = 'CTRL' },
      },
    },
  },
  harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' },
}

### Expected Behavior

Expected behavior is no fatal crash on launch

### Logs

10:39:30.846  ERROR  env_bootstrap > panic at /__w/wezterm/wezterm/target/release/build/xcb-e9d7e40c68a49154/out/randr.rs:777:18 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  15: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  16: <unknown>

thread 'main' panicked at 'internal error: entered unreachable code: Could not resolve randr Event with response_type 120 and first_event 89', /__w/wezterm/wezterm/target/release/build/xcb-e9d7e40c68a49154/out/randr.rs:777:18
stack backtrace:
   0:     0x55f55d940f0d - <unknown>
   1:     0x55f55d96aa7c - <unknown>
   2:     0x55f55d9384c1 - <unknown>
   3:     0x55f55d942c15 - <unknown>
   4:     0x55f55d942936 - <unknown>
   5:     0x55f55c6a8748 - <unknown>
   6:     0x55f55d94325a - <unknown>
   7:     0x55f55d943097 - <unknown>
   8:     0x55f55d9413c4 - <unknown>
   9:     0x55f55d942dc9 - <unknown>
  10:     0x55f55c3131e3 - <unknown>
  11:     0x55f55cf2a441 - <unknown>
  12:     0x55f55cf29483 - <unknown>
  13:     0x55f55ce43bbc - <unknown>
  14:     0x55f55c3a370d - <unknown>
  15:     0x55f55c411b33 - <unknown>
  16:     0x55f55c46ce79 - <unknown>
  17:     0x55f55d930a1e - <unknown>
  18:     0x55f55c3a8f82 - <unknown>
  19:     0x7fa2aa85dd90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  20:     0x7fa2aa85de40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  21:     0x55f55c313945 - <unknown>
  22:                0x0 - <unknown>
rhett@thelappy:~$

**Comment by wez** [comment]
If you run `xrandr` from the command line, what happens?

**Comment by wez** [comment]
Sounds similar to https://github.com/rust-x-bindings/rust-xcb/issues/195

**Comment by roadriverrail** [comment]
`xrandr` output, as you requested.

```
rhett@thelappy:~$ xrandr
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
eDP1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 280mm x 160mm
   1366x768      60.00*+
   1360x768      59.96  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   680x384       60.00  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

**Comment by xxuejie** [comment]
I'm running into similar problems here. Funny story: wezterm worked fine when I first installed Ubuntu 22.04 on my laptop but would start crashing once I enabled `TearFree` feature from Intel Graphics driver.

**Comment by roadriverrail** [comment]
@xxuejie Funny you'd mention that...**I just enabled TearFree too!**  This must be the source of the issue.

**Comment by dch** [comment]
FWIW I see this on FreeBSD too, i915 driver, auto detected config, I will try with tear-free disabled. Xorg.log below, no mention of tear.

[bt.txt](https://github.com/wez/wezterm/files/9690208/bt.txt)
[xorg.log](https://github.com/wez/wezterm/files/9690212/xorg.log)

**Comment by wez** [comment]
This is an issue with the upstream rust-xcb bindings. Can you try the following to see if it reproduces with a more minimal application?

```bash
cd /tmp
git clone https://github.com/rust-x-bindings/rust-xcb.git --depth 1
cd rust-xcb
patch -p1
```

Then paste this diff:

```
diff --git a/examples/basic_window.rs b/examples/basic_window.rs
index 86c32a0..7bca4d4 100644
--- a/examples/basic_window.rs
+++ b/examples/basic_window.rs
@@ -12,7 +12,10 @@ xcb::atoms_struct! {
 }

 fn main() -> xcb::Result<()> {
-    let (conn, screen_num) = xcb::Connection::connect(None).unwrap();
+    let (conn, screen_num) = xcb::Connection::connect_with_xlib_display_and_extensions(
+        &[xcb::Extension::RandR],
+        &[],
+    )?;
     let setup = conn.get_setup();
     let screen = setup.roots().nth(screen_num as usize).unwrap();
```

and hit CTRL-D.

Then:

```
cargo run --example basic_window --features xlib_xcb,randr
```

**Comment by dch** [comment]
that pops up a nice white basic window, no crash:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/basic_window`
window: 44040194
root: 1877
root_visual: 33
atoms = Atoms {
    wm_protocols: Atom {
        res_id: 380,
    },
    wm_del_window: Atom {
        res_id: 381,
    },
    wm_state: Atom {
        res_id: 353,
    },
    wm_state_maxv: Atom {
        res_id: 413,
    },
    wm_state_maxh: Atom {
        res_id: 414,
    },
}
Received event X(
    Expose(
        ExposeEvent {
            response_type: 12,
            pad: 1,
            sequence: 18,
            window: Window {
                res_id: 44040194,
            },
            x: 0,
            y: 0,
            width: 307,
            height: 990,
            count: 0,
            pad: 2,
        },
    ),
)
Received event X(
    Expose(
        ExposeEvent {
            response_type: 12,
            pad: 1,
            sequence: 18,
            window: Window {
                res_id: 44040194,
            },
            x: 307,
            y: 0,
            width: 307,
            height: 990,
            count: 0,
            pad: 2,
        },
    ),
)
```

**Comment by dch** [comment]
@wez thanks for pointing the way on this. I see you're involved upstream already, do you want me to do an issue there, or is that just makework?

**Comment by wez** [comment]
@dch I think having more than one person report this sort of thing might help the maintainers of the upstream understand the priority, and weigh in on the issue(s)!

**Comment by roadriverrail** [comment]
Just want to confirm I see no crash either, although I don't have the same output as above:
```
rhett@thelappy:/tmp/rust-xcb$ cargo run --example basic_window --features xlib_xcb,randr
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/basic_window`
```

No window pops up.

I confess I don't work in Rust much and I'm not deeply familiar with X11, so I don't know what else to expect here.  I also use i3, which may have something to do with it.

**Comment by dch** [comment]
from last bump ba57f73 I now get a different backtrace:

```
dch@akai ~> RUST_BACKTRACE=full wezterm-gui start
19:39:42.367  ERROR  env_bootstrap > panic at /home/dch/.cargo/git/checkouts/rust-xcb-41cc7e93ef1d12da/a85a4cf/src/event.rs:255:83 - called `Option::unwrap()` on a `None` value
   0: env_bootstrap::register_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: xcb::event::resolve_event
   8: xcb::base::Connection::handle_poll_for_event
   9: xcb::base::Connection::poll_for_event
  10: <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop
  11: wezterm_gui::main
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal
  15: main

thread 'main19:39:42.367' panicked at '  called `Option::unwrap()` on a `None` value', ERROR/home/dch/.cargo/git/checkouts/rust-xcb-41cc7e93ef1d12da/a85a4cf/src/event.rs :255 :83wezterm_toast_notification::dbus
stack backtrace:
 > while showing notification: I/O error: No such file or directory (os error 2)
   0:     0x23ff977a8b9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf9bca0a54f465bd9
   1:     0x23ff977c2b5e - core::fmt::write::hdf9e1b7bc0c7ef23
   2:     0x23ff9777b971 - std::io::Write::write_fmt::h6e00616d8cf5d394
   3:     0x23ff977909b5 - std::panicking::default_hook::{{closure}}::ha5a1e37665f439d8
   4:     0x23ff9779061e - std::panicking::default_hook::h791a251cba6fed5f
   5:     0x23ff9648ec08 - env_bootstrap::register_panic_hook::{{closure}}::hf0cd4c27e5df469c
   6:     0x23ff9779112b - std::panicking::rust_panic_with_hook::h184324b56212ec2b
   7:     0x23ff977a96e9 - std::panicking::begin_panic_handler::{{closure}}::hdd7dccc960a25e4f
   8:     0x23ff977a8cb4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1fb3000d64dd03f0
   9:     0x23ff97790c72 - rust_begin_unwind
  10:     0x23ff977c5433 - core::panicking::panic_fmt::hc3aba48bba555f86
  11:     0x23ff977c52fd - core::panicking::panic::h22ea410a7394d7e6
  12:     0x23ff96d44b4f - xcb::event::resolve_event::hbd8fcb14db1ac362
  13:     0x23ff96d4556a - xcb::base::Connection::handle_poll_for_event::habb1f33627ff54a7
  14:     0x23ff96d456e1 - xcb::base::Connection::poll_for_event::h5226df8a4b129b37
  15:     0x23ff96cca341 - <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop::hd50f24ca92d7e4eb
  16:     0x23ff96342d47 - wezterm_gui::main::h4633f49e8f4fadb7
  17:     0x23ff96200a23 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5e41ac2d23ec46c8
  18:     0x23ff96231fb9 - std::rt::lang_start::{{closure}}::hbca65b9fdf54362b
  19:     0x23ff97779a91 - std::rt::lang_start_internal::h1d0782bd0a0efa37
  20:     0x23ff9634dd92 - main
```

**Comment by KaziSadmanAhmed** [comment]
7f8d3a31d78534ab21e60099642e653ac8171aaf Fixed it for me. Thanks.

**Comment by dch** [comment]
ace!! same here, fixed even on my most hipster of unix systems. thanks both @rtbo and @wez for your help and insight!

**Comment by wez** [comment]
Thanks for working through this with me!
