### ISSUE TITLE
Changing font sizes using Ctrl-+/- causes output smaller/larger than the window

### ISSUE THREAD

**Issue by dotdash** [wez/wezterm#2565]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

awesome

### WezTerm version

wezterm 20220927-071112-9be05951

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Pressing Ctrl-+/- to change the font size on the fly causes the content area to no longer fit the window. wezterm seems to assume that the window gets resized, but with a tiling window manager, that isn't necessarily the case.

### To Reproduce

1. Start wezterm in a tiling window manager, so that the window won't be resized, even if the app requests it.
2. Use Ctrl-+/- to resize the font
3. Observe that the content area either underflows or overflows the actual window size.

### Configuration

no config

### Expected Behavior

wezterm should check the actual window size after changing the font size and adjust its content area appropriately. This already work correctly when you change the font size in the `wezterm.lua` config file while a wezterm instance is running.

### Anything else?
![wezbug](https://user-images.githubusercontent.com/230962/193017635-fab71a5d-c8d6-4276-9524-d3ef7194a80f.jpg)

**Comment by wez** [comment]
I think you want to change: https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html

**Comment by dotdash** [comment]
Ah, that works. Sorry, I didn't expect that to be a configurable option.
