### ISSUE TITLE
Display is wrong when there are multibyte characters, url and wrap-around

### ISSUE THREAD

**Issue by yutkat** [wez/wezterm#2568]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

sway

### WezTerm version

wezterm 20220927-071112-9be05951

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When the following text is displayed, part of the text is lacking.

` echo 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaグループaaaaaaa://aaa.aaa'`

wezterm output:
![swappy-20220930-154858](https://user-images.githubusercontent.com/8683947/193208297-c495ba71-fe22-40a3-ba2c-999a8ffaa0af.png)

It should be displayed as "グループ", but it is displayed as "グー".

This bug occurs only under the following conditions.
1. There is a wrap-around.
2. Multibyte characters(`グループ`) are on the second line.
3. There is text that looks like a URL(`a://aaa.aaa`). Thus, it does not occur when `hyperlink_rules = {}`

Also, the cursor position is wrong.
![swappy-20220930-155049](https://user-images.githubusercontent.com/8683947/193208601-78526619-ca6c-4bd3-a2ef-b0d93d5eccbf.png)

I think there' s something wrong with the handling of multibyte characters when they are wrapped.

### To Reproduce

1. Adjust window size so that the word 'グループ' is on the second line
2. paste
` echo 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaグループaaaaaaa://aaa.aaa'`

### Configuration

This will be reproduced by `weztern -n`.

### Expected Behavior

- Correct display
- The cursor is in the correct position.

### Anything else?

Not reproduced in alacritty

![swappy-20220930-154909](https://user-images.githubusercontent.com/8683947/193208345-be3ade05-adc1-4b5f-bd8a-2ae6e31782c3.png)

**Comment by gen740** [comment]
I found similar bug.
In vim, if you type multibyte url sequence like "あ://example.com あああああああああああああああああああああああああああああああああああああああああああああああああ", and `set relativenumber`, japanese charactor `あ` disappear corresponding to cursor movement.

**Comment by gen740** [comment]
As a workaround, disabling hyperlink feature by `hyperlink_rules = {},` (or set hyperlink_rules properly) will fix this bug.

**Comment by hanxi** [comment]
> As a workaround, disabling hyperlink feature by `hyperlink_rules = {},` (or set hyperlink_rules properly) will fix this bug.

Thanks, you solved my problem.  https://github.com/wez/wezterm/issues/2567

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by yutkat** [comment]
I just tried and it was fixed in `main`. Thanks :smiley:
