### ISSUE TITLE
IME preedit string is displayed on all cursor position of all panes

### ISSUE THREAD

**Issue by statiolake** [wez/wezterm#2569]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220927-071112-9be05951

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The IME preedit string is rendered on the all cursor position of all splitted panes, as below.

![image](https://user-images.githubusercontent.com/20490597/193243378-6c8f4b9a-2754-484b-9598-efdd9cd834cf.png)

It is just a temporary appearance issue. Confirming input correctly sends input to the active pane only.

![image](https://user-images.githubusercontent.com/20490597/193243554-a6e23fab-8588-4ae8-8e79-ca0ba054e66c.png)

### To Reproduce

1. Open WezTerm.
2. Split the window as you like.
3. Start typing with IME ON (The above screenshot is taken with Microsoft IME for Japanese).
4. Observe all cursor position of each pane.

### Configuration

Though above screenshots are taken with my configs, the same issue reproduced with an empty config:

```
return {}
```

### Expected Behavior

String is displayed only on the active pane.

### Logs

(Log file (or debug overlay) was empty)

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
