### ISSUE TITLE
Trailing unicode character not displayed after line break

### ISSUE THREAD

**Issue by taoso** [wez/wezterm#2571]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220930-092527-e74defad

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm does not show trailing character after line break.

In the following screen short, there is another "二" in the end, which is not displayed.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/2030591/193433751-113dcd5e-e0a9-4d85-8582-6764f98ba8f6.png">

### To Reproduce

Create a file `a.md` with the following content

```
一一一一一一一一一一一一一一一一[RFC4303](https://datatracker.ietf.org/doc/html/rfc4303)二二二

```

Open WezTerm with column of 24, and run the following command

```
cat a.md
```

### Configuration

```lua
local wezterm = require 'wezterm';
return {
    font_size = 24,
    font = wezterm.font_with_fallback({
        {family="Inconsolata", weight="Regular"},
        {family="InconsolataGo Nerd Font Complete Mono", weight="Regular"},
        {family="Source Han Mono SC", weight="Regular"},
        {family="Source Han Mono TC", weight="Regular"},
        {family="Apple Color Emoji", weight="Regular"},
    }),
    unicode_version = 14,
    custom_block_glyphs = false,
    hide_tab_bar_if_only_one_tab = true,
    tab_bar_at_bottom = true,
    scrollback_lines = 0,
    native_macos_fullscreen_mode = true,
    window_padding = { left = 0, right = 0, top = 0, bottom = 0 },
    check_for_updates = true,
    colors = {
        cursor_bg = '#eeeeee',
        cursor_fg = '#282828',
        cursor_border = '#eeeeee',
        foreground = '#eeeeee',
        background = '#000000',
        ansi = {
            '#282828',
            '#f43753',
            '#c9d05c',
            '#ffc24b',
            '#b3deef',
            '#d3b987',
            '#73cef4',
            '#eeeeee',
        },
        brights = {
            '#4c4c4c',
            '#f43753',
            '#c9d05c',
            '#ffc24b',
            '#b3deef',
            '#d3b987',
            '#73cef4',
            '#feffff',
        },
    },
}
```

### Expected Behavior

<img width="888" alt="image" src="https://user-images.githubusercontent.com/2030591/193433859-5dcb7afe-d421-4742-a2b2-bb33bf54a0ff.png">

### Anything else?

I record the output by wezterm record

```
{"version":2,"width":80,"height":24,"timestamp":1664672781,"env":{"WEZTERM_VERSION":"20220930-092527-e74defad","WEZTERM_TARGET_TRIPLE":"x86_64-apple-darwin","LANG":"en_US.UTF-8","TERM":"xterm-256color"},"theme":{"fg":"#eeeeee","bg":"#000000","palette":"#282828:#f43753:#c9d05c:#ffc24b:#b3deef:#d3b987:#73cef4:#eeeeee:#4c4c4c:#f43753:#c9d05c:#ffc24b:#b3deef:#d3b987:#73cef4:#feffff"}}
[0.23649937,"o","\u001b[1m\u001b[7m%\u001b[27m\u001b[1m\u001b[0m                                                                               \r \r"]
[0.23656604,"o","\u001b]2;foo@bar:~\u0007\u001b]1;~\u0007"]
[0.248061,"o","\r\u001b[0m\u001b[27m\u001b[24m\u001b[J\u001b[01;32m➜ \u001b[36m~\u001b[00m \u001b[K"]
[0.24825515,"o","\u001b[?1h\u001b=\u001b[?2004h"]
[6.1476398,"o","c"]
[6.443559,"o","\bca"]
[6.6806684,"o","t"]
[6.846863,"o"," "]
[6.986207,"o","a"]
[7.1373353,"o","."]
[7.410321,"o","m"]
[7.52213,"o","d"]
[7.7896338,"o","\u001b[?1l\u001b>"]
[7.789685,"o","\u001b[?2004l"]
[7.789695,"o","\r\r\n"]
[7.791191,"o","\u001b]2;cat a.md\u0007\u001b]1;cat\u0007"]
[7.8023033,"o","一一一一一一一一一一一一一一一一[RFC4303](https://datatracker.ietf.org/doc/html/rfc4303)二二二\r\n"]
[7.8027506,"o","\u001b[1m\u001b[7m%\u001b[27m\u001b[1m\u001b[0m                                                                               \r \r"]
[7.802821,"o","\u001b]2;foo@bar:~\u0007"]
[7.802877,"o","\u001b]1;~\u0007"]
[7.815098,"o","\r\u001b[0m\u001b[27m\u001b[24m\u001b[J\u001b[01;32m➜ \u001b[36m~\u001b[00m \u001b[K"]
[7.8151746,"o","\u001b[?1h\u001b="]
[7.8152113,"o","\u001b[?2004h"]
[9.493487,"o","\u001b[?2004l\r\r\n"]
```

**Comment by wez** [comment]
Even though this was posted first, I'm considering this a duplicate of https://github.com/wez/wezterm/issues/2568 which has a more precise description of how this triggers

**Comment by wez** [comment]
This should be implemented now in `main`. 

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by taoso** [comment]
The nightly build works. Thank you @wez
