### ISSUE TITLE
There is a problem with the font display

### ISSUE THREAD

**Issue by cecho0** [wez/wezterm#2572]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20221001-071223-478109de

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Use neovim open a text，just move cursor, don‘t do other operation, the text looks changed，but infact no change. And it only appears when you move between the first and second characters of the second line. And this program will not occur in alacritty or Windows terminal. 
[text.txt](https://github.com/wez/wezterm/files/9692829/text.txt)

![GIF 2022-10-2 22-51-53_wezterm](https://user-images.githubusercontent.com/102601089/193460770-8d33261d-0d5c-4b48-951b-2f2013d57ae4.gif)

### Configuration

no config

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by cecho0** [comment]
[wezterm-recording-4m7Bqt.cast.txt](https://github.com/wez/wezterm/files/9693127/wezterm-recording-4m7Bqt.cast.txt)

**Comment by wez** [comment]
Haven't fully resolved this yet, but investigation so far shows:

```
; wezterm  ls-fonts --codepoints 28,ff9f
LeftToRight
 0                   x_adv=8.328125 cells=2  glyph=parenleft,283  wezterm.font("Operator Mono SSm Lig", {weight="DemiLight", stretch="Normal", style="Normal"})
                                      /home/wez/.fonts/OperatorMonoSSmLig-Medium.otf, FontDirs
 1 (ﾟ   \u{28}\u{ff9f} x_adv=6.65625 cells=2  glyph=59204 wezterm.font("Noto Sans CJK TC", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-cjk/NotoSansCJK-Regular.ttc index=3 variation=0, FontConfig
```

and with a proper monospace font, the advance metrics are better, but the shaping and cell widths are still not right:

```
; wezterm --config 'font=wezterm.font("Noto Sans Mono CJK JP")' ls-fonts --codepoints 28,ff9f
LeftToRight
 0                   x_adv=6.65625 cells=2  glyph=63172 wezterm.font("Noto Sans Mono CJK JP", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-cjk/NotoSansCJK-Regular.ttc index=5 variation=0, FontConfig
 1 (ﾟ   \u{28}\u{ff9f} x_adv=6.65625 cells=2  glyph=59204 wezterm.font("Noto Sans Mono CJK JP", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-cjk/NotoSansCJK-Regular.ttc index=5 variation=0, FontConfig
```

What I think is expected is that both codepoints should have `cells=1` and the same `x_adv`

**Comment by wez** [comment]
After a bit more digging: `(ﾟ` is a single grapheme of width 2, but the component parts are resolved from two different fonts. The issue here is that the logic that computes the cell width doesn't know how to correctly weight and distribute the widths in this scenario.

**Comment by mfiano** [comment]
I just stumbled on this thread after experiencing the same behavior, and bisected my config down to it only being slow when defining `font` or `font_with_fallback`. I use `Iosevka Slab`, and I am getting integers for the x advance and cells:

```
mfiano@workstation ~$ wezterm --config 'font=wezterm.font("Iosevka Slab")' ls-fonts --codepoints 28,ff9f
LeftToRight
 0                   x_adv=8  cells=2  glyph=parenleft,11   wezterm.font("Iosevka Slab", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/TTF/iosevka-slab-regular.ttc, FontConfig
 1 (ﾟ   \u{28}\u{ff9f} x_adv=8  cells=2  glyph=59106 wezterm.font("Noto Serif CJK KR", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/noto-cjk/NotoSerifCJK-Regular.ttc index=1 variation=0, FontConfig
mfiano@workstation ~$ wezterm --config 'font=wezterm.font("Noto Sans Mono CJK JP")' ls-fonts --codepoints 28,ff9f
LeftToRight
 0                   x_adv=8  cells=2  glyph=63172 wezterm.font("Noto Sans Mono CJK JP", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc index=5 variation=0, FontConfig
 1 (ﾟ   \u{28}\u{ff9f} x_adv=8  cells=2  glyph=59204 wezterm.font("Noto Sans Mono CJK JP", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc index=5 variation=0, FontConfig
```

**Comment by wez** [comment]
The issue here isn't performance related, it's that the glyphs should be distributed as two glyphs each with `cells=1`, for a total width of 2 cells for that grapheme, to match the terminal model.

Because the shaper returns 2 glyphs with cells=2, the renderer gets confused and renders with artifacts/misalignment because of the mismatch between the model and what is rendered on screen.

**Comment by mfiano** [comment]
You're right, sorry. I'm not sure what I was thinking. This might have meant to go to #2503

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by cecho0** [comment]
I will try the nightly version to provide you with more information

**Comment by khaledhosny** [comment]
> After a bit more digging: `(ﾟ` is a single grapheme

I think HarfBuzz only considers combining marks (and some emoji sequences) when merging clusters (at cluster level 0), and  U+FF9F is a modifier letter not a combining mark.

It does not implement the full Unicode grapheme clustering spec and probably not meant to. It might be worth to report on HarfBuzz issue tracker, though, in case Behdad has a different opinion.

**Comment by cecho0** [comment]
ﾟin (ﾟ will be combined with the preceding character, no matter what the preceding character is.

**Comment by cecho0** [comment]
[recording.txt](https://github.com/wez/wezterm/files/9792819/recording.txt)

**Comment by cecho0** [comment]
Now the font will not drift after moving the cursor, but sometimes the characters  ﾟ  will disappear during some movements.
