### ISSUE TITLE
Crash on C-S-U and unfound sequence of chars

### ISSUE THREAD

**Issue by benhurstein** [wez/wezterm#2580]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20221001-071223-478109de

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When selecting an unicode char with Ctrl-Shift-U, wezterm shows a list of characters that is updated as keys are typed.
If the list goes empty because it doesn't find a match with the typed characters and <enter> is typed, wezterm crashes.

### To Reproduce

Press Ctrl-Shift-u )) enter

### Configuration

no config

### Expected Behavior

survival of the program

### Logs

[benhur@nababinho t0]$ /tmp/WezTerm-nightly-Ubuntu18.04.AppImage 
11:36:07.414  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{200aa}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
11:36:19.605  ERROR  env_bootstrap > panic at wezterm-gui/src/termwindow/charselect.rs:606:47 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: __libc_start_main
  25: <unknown>

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', wezterm-gui/src/termwindow/charselect.rs:606:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
