### ISSUE TITLE
Compatibility of Ctrl-Shift-U behaviour with that of IBus/GTK in linux

### ISSUE THREAD

**Issue by benhurstein** [wez/wezterm#2581]
**Is your feature request related to a problem? Please describe.**
Some programmable keyboards (for example, with QMK) can be configured to send unicode chars. In linux, it sends those chars with Ctrl-Shift-U followed by the hex codepoint of the char. It doesn't work in wezterm.

**Describe the solution you'd like**
For wezterm to be compatible with the behaviour expected by QMK. A way of doing it is to put the char corresponding to the codepoint as the first option of the list when all the keyes typed after C-S-U are hex digits.

**Comment by wez** [comment]
Can you describe in more detail what doesn't work about it?
What is the specific behavior you observe?

**Comment by benhurstein** [comment]
My keyboard has a key configured to send letter á (unicode 'LATIN SMALL LETTER A WITH ACUTE' (U+00E1)).
The keyboard is configured to send unicode keys using linux input mode (https://github.com/qmk/qmk_firmware/blob/master/docs/feature_unicode.md#input-modes).

When I press that key, the keyboard sends ctrl-shift-u e1 enter.
In most programs, the intended letter is input (á).
In wezterm, HENTAIGANA LETTER E-1 (U+1B001) is input, because it is the first option in wezterm's proposed characters list.
My suggestion is to put as first option in the list the exact codepoint as typed, when all chars typed after ctrl-shift-u are hex digits.

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by benhurstein** [comment]
Thank you for implementing this.
It works most of the time, but there seems to be a timing issue, sometimes
it misses the "enter" sent by the keyboard at the end of the sequence, and
the selection panel stays on the screen. It happens mostly when two such
keys are typed in rapid succession.
I've put some sleeps in the keyboard firmware and it works better, so it
seems to be a timing problem.
