### ISSUE TITLE
Copy on selection

### ISSUE THREAD

**Issue by hktonylee** [wez/wezterm#2582]
**Is your feature request related to a problem? Please describe.**
I miss a feature that the term can automatically copy the selected text, whenever I change the selection.

**Describe the solution you'd like**
The solution is already described above :)

**Describe alternatives you've considered**
I tried to do this via the Lua scripting or config. But it seems impossible to do so.

**Additional context**
No additional context :)

**Comment by wez** [comment]
This is the default behavior. If it isn't working, please file a bug report issue and provide all the information requested in the bug report form.
