### ISSUE TITLE
Copy on selection not working

### ISSUE THREAD

**Issue by hktonylee** [wez/wezterm#2588]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Windowing system = X11
GNOME version = 3.36.8

### WezTerm version

wezterm 20221004-075346-ba57f73b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I use mouse to select text in the WezTerm, it does not automatically copy the content to the clipboard.

### To Reproduce

1. Install nightly build
   ```
   curl -OL https://github.com/wez/wezterm/releases/download/nightly/WezTerm-nightly-Ubuntu18.04.AppImage
   chmod +x ./WezTerm-nightly-Ubuntu18.04.AppImage
   ./WezTerm-nightly-Ubuntu18.04.AppImage
   ```
2. Enter `wezterm -V`
3. Use mouse to select the content
4. It should have automatically copied the content to clipboard. But it does not.

### Configuration

no config

### Expected Behavior

WezTerm should automatically copy the text

### Logs

Log is empty 
![image](https://user-images.githubusercontent.com/587925/193891610-028405a0-ae06-4d81-9052-6a55f3b637e2.png)

**Comment by hktonylee** [comment]
```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

**Comment by bew** [comment]
On X11 there are multiple buffers, the main ones are the clipboard and the primary selection (this is a X thing).
The mouse selection is usually copied to the 'primary selection', which you should be able to paste with a middle click in any apps (or Shift-Insert).
If you want instead mouse selection to copy the text to the clipboard (which you usually paste with Ctrl-v in other apps), you need to update the mouse binding in your config.

You can see an example of what you want to do in:
https://wezfurlong.org/wezterm/config/lua/keyassignment/CompleteSelectionOrOpenLinkAtMouseCursor.html
```lua
local wezterm = require 'wezterm'

return {
  mouse_bindings = {
    -- Change the default click behavior so that it populates
    -- the Clipboard rather the PrimarySelection.
    {
      event = { Up = { streak = 1, button = 'Left' } },
      mods = 'NONE',
      action = wezterm.action.CompleteSelectionOrOpenLinkAtMouseCursor 'Clipboard',
    },
  },
}
```

**Comment by hktonylee** [comment]
Thanks! I could fix the problem by using your solution.

--

For those who are interested, the following config will change all the mouse keys to use `ClipboardAndPrimarySelection`

```lua
local wezterm = require 'wezterm'

function make_mouse_binding(dir, streak, button, mods, action)
  return {
    event = { [dir] = { streak = streak, button = button } },
    mods = mods,
    action = action,
  }
end

return {
  mouse_bindings = {
    make_mouse_binding('Up', 1, 'Left', 'NONE', wezterm.action.CompleteSelectionOrOpenLinkAtMouseCursor 'ClipboardAndPrimarySelection'),
    make_mouse_binding('Up', 1, 'Left', 'SHIFT', wezterm.action.CompleteSelectionOrOpenLinkAtMouseCursor 'ClipboardAndPrimarySelection'),
    make_mouse_binding('Up', 1, 'Left', 'ALT', wezterm.action.CompleteSelection 'ClipboardAndPrimarySelection'),
    make_mouse_binding('Up', 1, 'Left', 'SHIFT|ALT', wezterm.action.CompleteSelectionOrOpenLinkAtMouseCursor 'ClipboardAndPrimarySelection'),
    make_mouse_binding('Up', 2, 'Left', 'NONE', wezterm.action.CompleteSelection 'ClipboardAndPrimarySelection'),
    make_mouse_binding('Up', 3, 'Left', 'NONE', wezterm.action.CompleteSelection 'ClipboardAndPrimarySelection'),
  },
}
```

**Comment by mkpaz** [comment]
Came here from Google search asking for the same this and I wan't to say, wow, it's just a single string in kitty `copy_on_select yes`. I can't even parse this string `event = { Up = { streak = 1, button = 'Left' } }`. It's really sad that something that obvious made so hard to find and configure.
