### ISSUE TITLE
macos, support key assignment to open a new window when no existing windows have focus

### ISSUE THREAD

**Issue by kr** [wez/wezterm#2602]
**Is your feature request related to a problem? Please describe.**

On macos, I have some muscle memory from Terminal.app that I miss. I'd like to keep that muscle memory and use it in wezterm, if this sounds reasonable.

Specifically, I'd love to be able to use the keyboard (Command-n) to open a new window when WezTerm.app is active even when none of wezterm's windows have focus.

Here's the situation that I know of where that can happen:

1. In System Preferences, Mission Control, make sure that "When switching to an application, switch to a Space with open windows for the application" is **unchecked**.
2. Make sure at least one wezterm window is open.
3. Switch to another Space that has no wezterm windows open.
4. Click on WezTerm in the dock (or in Spotlight or whatever) to make it active. Now WezTerm.app should have keyboard focus, but all of its open windows are on other Spaces and none of them have focus.
5. (this part is the feature request) press Command-n to open a new wezterm window.

Right now, step 5 just makes a beep sound.

**Describe the solution you'd like**

I want wezterm to process at least some of its key assignments when it's in this state (app is receiving keyboard events, but no windows are focused). It seems not really possible to make _all_ key assignments work like this, I guess some don't make sense when there's no window currently focused. But at least I would like to be able to open a new window this way.

**Describe alternatives you've considered**

 * By hand. This is what I do right now. It's not very fun lol.
   1. Switch to a Mission Control Space where a wezterm window is already open
   2. Use the already-open window to open a new window
   3. Move the new window back to the Space where I wanted to use it
   4. Switch back to that Space
 * Write an Automator or AppleScript script to do it.
   This would probably work pretty well and I'll probably end up doing this if the feature request doesn't work out. If I'm the only one who wants this, this alternative could be the best option.
 * Switch back to Terminal.app. Included only for completeness. Not worth it for me.

**Additional context**

I'm using wezterm 20220905-102802-7d4b8249 right now.

I did look over the documentation at https://wezfurlong.org/wezterm/ but I didn't see anything that looked super relevant. Apologies if I missed it!

**Comment by wez** [comment]
Related to:
* https://github.com/wez/wezterm/issues/1443
