### ISSUE TITLE
No macOS build for latest release

### ISSUE THREAD

**Issue by erf** [wez/wezterm#261]
I noticed there is no macOS build in the latest release. Also the download url for macOS on the web page fails.

**Comment by wez** [comment]
I wonder if you were racing with the CI?  I see both the macos download on the release page:
https://github.com/wez/wezterm/releases/tag/20200909-002054-4c9af461
and the download link on 
https://wezfurlong.org/wezterm/install/macos.html
works for me.

There was a window where some of the releases were built out and published before the others and I think that may result in some missing links while it "waits" for the rest to build

**Comment by erf** [comment]
You are right - i was just too fast 😄
