### ISSUE TITLE
Request: mouse mode 1005

### ISSUE THREAD

**Issue by Ennea** [wez/wezterm#2613]
**Is your feature request related to a problem? Please describe.**
Despite modes 1006 and 1016 already being implemented, there are applications that only support 1005. WeeChat, for example, which can only handle mouse events in the top left region of wezterm, due to mode 1005 not being implemented.

**Describe the solution you'd like**
I'd like mouse mode 1005 to be supported. From what I've gathered, this is just like X10, but involves encoding Cx and Cy via UTF-8, upping the maximum position to 2015 (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Extended-coordinates).

**Describe alternatives you've considered**
I've considered using tmux to work around my particular problem with WeeChat, but that is really just a workaround. Another alternative would be asking affected programs' maintainers to implement support for modes 1006 and/or 1016. I think adding 1005 support to wezterm instead might be the better solution :)

**Additional context**
My reading on this topic was mostly done on this page: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Extended-coordinates

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Ennea** [comment]
Holy smokes, that was fast. Yup, just tested it. Works perfectly, as far as I can tell. Both x and y coordinates work as expected. Thank you so much :)
