### ISSUE TITLE
ClearScrollback not being handled in multiplexer

### ISSUE THREAD

**Issue by mfiano** [wez/wezterm#2624]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 i3

### WezTerm version

wezterm 20221011-202755-7ba9c00e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`wezterm.action.ClearScrollback()` (with any arguments) is not working in nightly. I tried various keybindings and confirmed they are listed with `wezterm show-keys`, and `debug_key_events` shows that the keys are actually being received (not intercepted by another process) and actually being sent to the proper event handler. 

Result: nothing happens at all. Even with "ScrollbackAndViewport" shows no change whatsoever, not even any stdout/stderr shown in the parent process.

### To Reproduce

Bind any key to `ClearScrollback()` and try emitting that event via a key press.

### Configuration

```
keys = {
  { key = "L", mods = "CTRL|SHIFT", action = wezterm.action.ClearScrollback("ScrollbackAndViewport") }
}
```

### Expected Behavior

I would expect it to do something, but it does nothing, and the debug log even shows that it receives the proper key sequence and emits the event. Additionally, I can scroll up and see the backlog just fine.

### Logs

I see this with `debug_key_events = true`:

```log
12:09:49.928  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(L), modifiers: SHIFT | CTRL, phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }
12:09:49.928  INFO   wezterm_gui::termwindow::keyevent > Char('L') CTRL -> perform ClearScrollback(ScrollbackAndViewport)
12:09:50.035  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('L'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(L), modifiers: SHIFT | CTRL, phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
```

and this with `wezterm show-keys`:

```
CTRL             L            ->   ClearScrollback(ScrollbackAndViewport)
```

### Anything else?

I see no additional output in the parent process when `show_key_events` is off.

**Comment by wez** [comment]
I can't reproduce this.

```lua
local wezterm = require 'wezterm'

return {
  -- helps to show the scrollback being pruned, but doesn't change
  -- the behavior of ClearScrollback
  enable_scroll_bar = true,
  keys = {
    { key = "L", mods = "CTRL|SHIFT", action = wezterm.action.ClearScrollback("ScrollbackAndViewport") }
  },
}
```

With that config saved to `/tmp/2624.lua`, I run `wezterm --config-file /tmp/2624.lua`, then I run `ls -l /etc/` to get more than a screen full of text, and the scroll thumb moves to reflect that.

Pressing CTRL-SHIFT-K clears the scrollback and the scroll thumb adjusts accordingly.
Pressing CTRL-SHIFT-L clears both.

Is there something else different in your environment?

It's unlikely that this action has no effect, but it is perhaps possible that this might be a rendering issue. If you try to select the text in the terminal, what pastes?  If you resize or split the the terminal, does it update?

**Comment by mfiano** [comment]
It's not a rendering issue. Resizing or splitting the terminal doesn't update and I can still scrollback. That said, your minimal config does work for me, so it must be a conflict in my config I have to bisect.

**Comment by mfiano** [comment]
Ok reproducible with this:
```
local wezterm = require 'wezterm'

return {
  -- helps to show the scrollback being pruned, but doesn't change
  -- the behavior of ClearScrollback
  enable_scroll_bar = true,
  default_domain = "main",
  keys = {
    { key = "L", mods = "CTRL|SHIFT", action = wezterm.action.ClearScrollback("ScrollbackAndViewport") }
  },
  unix_domains = { { name = "main" } }
}
```

**Comment by BetaRavener** [comment]
Just ran into this too. `wezterm 20230320-124340-559cb7b0` on Windows 11, connected to WSL2 via SSH domain.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
