### ISSUE TITLE
pane.has_unseen_output never returns true

### ISSUE THREAD

**Issue by mfiano** [wez/wezterm#2625]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 i3

### WezTerm version

wezterm 20221011-202755-7ba9c00e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If I split a window and run a long running process that updates stdout frequently, or if I just do `sleep 5 && echo test` and switch to the other pane, the `format-table-title` hook does not detect a change in any panes when iterating over all panes in the tab.

### To Reproduce

Set the foreground and background color of tab titles both to red or blue dependent on the boolean value of the `has_unseen_output` field of a pane, as done in the below configuration snippet. The result is always blue, despite other panes updating their output.

### Configuration

```lua
wezterm.on("format-tab-title", function(tab)
  local active = tab.is_active
  local mux_window = weztern.mux.get_window(tab.window_id)
  local workspace = mux_window:get_workspace()
  local title = tab.active_pane.title
  local title_text = {}
  -- theme.text_item is just a convenience function that returns a FormatItem table.
  local text_items = {
    theme.text_item { text = " " .. workspace, fg = "blue", bg = "grey1", bold = true },
    theme.text_item { bg = "grey1", fg = "grey2", bold = false }
  }

  local unseen = false
  if active then
    title_text = { text = " " .. title .. " ", fg = "white2" }
  else
    for _, pane in ipairs(tab.panes) do
      if pane.has_unseen_output then
        unseen = true
        break
      end
    end
    if unseen then
      print("hit!") -- nope, never hits here.
      title_text = { text = " " .. title .. " ", fg = "red", bg = "red" }
    else
      title_text = { text = " " .. title .. " ", fg = "blue", bg = "blue" }
    end
  end

  table.insert(text_items, theme.text_item(title_text))
  return fn.format_text(text_items)
end)
```

### Expected Behavior

I would expect this flag to be true when the output of a pane has changed.

### Logs

No abnormal logs.

### Anything else?

I also tried the second example from the docs [here](https://wezfurlong.org/wezterm/config/lua/PaneInformation.html#paneinformation).

**Comment by mfiano** [comment]
Update: I forgot to mention, I used `print` to check the value (I love how Lua print generates wezterm info log messages). Printing the value always shows `false`, not `nil`. I was unsure if I had the `MuxPane` or `Mux` object, so I at least ruled that problem out.

**Comment by wez** [comment]
This isn't implemented for the multiplexer yet 0bf1b8d13eb4c1ec132d609e12ae7ed78266688b

**Comment by mfiano** [comment]
Ah that explains it. All my stuff is either a unix or ssh domain.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
