### ISSUE TITLE
CTRL-Q needs to be pressed twice to register in macOS

### ISSUE THREAD

**Issue by g6ai** [wez/wezterm#2630]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221012-092613-6415ba0e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In macOS Monterey, I have to press CTRL-Q twice to make this key-binding work.

### Configuration

no config

### Anything else?

This bug also appears in Alacritty: https://github.com/alacritty/alacritty/issues/5085, and a solution has been suggested in https://github.com/alacritty/alacritty/issues/1359. Per this solution, I put this line into the `key` section of `wezterm.lua` as a workaround:

```lua
{key = "q", mods = "CTRL", action = wezterm.action.SendString '\x11'},
```

The root cause is upstream: https://github.com/rust-windowing/winit/issues/1267

**Comment by wez** [comment]
wezterm doesn't use winit.  The issue is different here: when `use_ime=true` (the default), the IME swallows the key-down event for CTRL-Q.  If you set `use_ime=false` then it will pass through to the terminal.

**Comment by vvvvv** [comment]
If you want to leave the default `use_ime=true` set but still want CTRL+Q to work as expected set your keys config to 
```lua
keys = {
        {mods = "CTRL", key = "q",  action=wezterm.action{SendString="\x11"}},
}
```

Just thought I'd leave this here if you stumble upon this issue later.

**Comment by achimnol** [comment]
I just hit this issue after updating wezterm to the latest nightly, and the workaround above works for me.

**Comment by joshua7v** [comment]
same here, upgrade from 20220905 to 20221119 and suddenly I need to hit <c-q> twice
the workaround works fine, but I'm wondering why its not an issue in last version

**Comment by g6ai** [comment]
> If you want to leave the default `use_ime=true` set but still want CTRL+Q to work as expected set your keys config to 
> 
> ```lua
> 
> keys = {
> 
>         { mods = "CTRL", key = "q", action=wezterm.action{ SendString="\x11" } },
> 
> }
> 
> ```
> 
> 
> 
> Just thought I'd leave this here if you stumble upon this issue later.  

It's included in the issue description but thanks

**Comment by wez** [comment]
> I'm wondering why its not an issue in last version

because the behavior changed:
https://github.com/wez/wezterm/issues/2771#issuecomment-1322873607

**Comment by wez** [comment]
This should be resolved now in `main`. https://wezfurlong.org/wezterm/config/lua/config/macos_forward_to_ime_modifier_mask.html makes this configurable and the default is back to its original value.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by g6ai** [comment]
Can confirm it's resolved, thanks for your time as always!
