### ISSUE TITLE
Startup time

### ISSUE THREAD

**Issue by erf** [wez/wezterm#264]
**Is your feature request related to a problem? Please describe.**

I noticed the startup time for wezterm is a little over 1 second, whilst iterm2 opens almost instantly on macOS.

**Describe the solution you'd like**

Maybe it would be possible to profile and improve the startup time?

**Comment by erf** [comment]
Tested on Nightly now and Wezterm still seem to have a slight more delay when opening compared to iTerm2 and Terminal. But we are talking sub-second here.. Not sure if there is a way to measure startup of an app?

**Comment by wez** [comment]
I think the actual time-to-interaction in both wezterm and iterm2 is similar.  A difference is that iterm2 shows the window before starting the shell inside, whereas wezterm starts the shell and then shows the window.  But it takes about the same amount of time for both them to allow working with the new process.

It's also worth noting that both wezterm and iterm start login shells and that seems to take a noticeable chunk of time to start the shell compared to a non-login shell.  You can observe this by running `zsh -l` and waiting for it print to the prompt.

**Comment by erf** [comment]
Ok, i think you are right. I'll close thiss.

**Comment by tuananh** [comment]
I'm not sure if it's the same. time to interaction on `Terminal.app` is very fast. whereas i have to wait 1.5/2 seconds for wezterm to start.

**Comment by erf** [comment]
I think wezterm startup is faster than iTerm2 now after i built it for the macbook m1, like instant

**Comment by tuananh** [comment]
> I think wezterm startup is faster than iTerm2 now after i built it for the macbook m1, like instant

lemme try compiling from source
