### ISSUE TITLE
option to detach and exit rather than activating hidden workspaces when a window is closed

### ISSUE THREAD

**Issue by mfiano** [wez/wezterm#2644]
**Is your feature request related to a problem? Please describe.**
I would like the ability to be able to override the gui shutdown procedure. In my setup, I connect to a local unix domain, and I have a `mux-startup` event that creates and configures the layout of several workspaces. Currently when I close (with my window manager) the window shown for the active workspace, a window tagged with another workspace is spawned.

**Describe the solution you'd like**
I would like to be able to call a `quit_application` (see #2643) method in the handler of a new event, called `gui-shutdown`, which would be emitted before the window is destroyed. This would allow me to close all workspaces, with the intention to reconnect to the local mux server later if I need any of the windows.

**Describe alternatives you've considered**
Define a keybinding that calls `wezterm.action.QuitApplication`. This is not very ideal. My muscle memory closes every other application with my window manager's key binding.

**Additional context**
It might be worth doing the same for a `mux-shutdown` event, just to be symmetric?

**Comment by wez** [comment]
Most events in wezterm are advisory (eg: something happened) rather than hooks (eg: change how something should happen).
The former are relatively easy to add, but the latter have some architectural impositions because of how the lua runtime integrates and whether it should be possible to allow async functions in the hook or not.

From your description it isn't clear whether you intend to change the behavior of something that is built into wezterm or not. Can you elaborate on the shutdown behavior you mentioned?

**Comment by mfiano** [comment]
Sure, currently there is no way to use a window manager to close a the last window of the active workspace without the next workspace spawning its windows. I do not want to see the next workspace. I just want to exit the terminal, and attach to it later since all windows are locally muxed.

**Comment by mfiano** [comment]
Thanks, that would be a good solution.

**Comment by mfiano** [comment]
Out of all the bugs and feature requests I filed, this one is the only thing blocking my "perfect setup". I can wait though :)

**Comment by mfiano** [comment]
@Lenbok no problem, though please bare in mind that I'm not used to Lua at all. I did however try to make it a modular config, with per-machine local.lua files, [here](https://github.com/mfiano/wezterm-config).

Currently I'm using this in a test scenario where my workstation connects to a local unix domain socket to save the state of all the workspaces I configure in local.lua:

```lua
--- workstation's ~/.config/wezterm/local.lua

return {
  remote_muxers = {
    { name = "vps", remote_address = "vps" }
  },
  workspaces = {
    shell = {
      { layout = "vertical" },
      { layout = "vertical" },
      { layout = "quad" },
      { layout = "quad" }
    },
    dev = {
      { layout = "vertical", commands = { "nvim", "nvim" } },
      { layout = "vertical", commands = { "nvim" } },
      { layout = "vertical" },
    },
    monitor = {
      { commands = { "htop" } },
      { commands = { "btm -fg" } },
      { commands = { "clzb" } }
    },
    net = {
      { commands = { "toxic -4 -L" } },
      { commands = { "neomutt" } },
      { commands = { "newsboat" } },
      { commands = { "ncmpcpp" } },
    }
  }
}
```

 It also has an entry for a single remote server headlessly running sshd and wezterm-mux-server with this local.lua:

```lua
--- vps's ~/.config/wezterm/local.lua

return {
  remote_muxers = {},
  workspaces = {
    main = {
      { layout = "vertical" },
      { layout = "quad" },
      { commands = { "htop" } },
      { commands = { "weechat-curses" } }
    }
  }
}
```

**Comment by wez** [comment]
I've made the effect of closing a window have the side effect of an implicit domain detach in `main`.

I'd wanted to find a way to be smart about this for the case where you have two or more GUI windows open on the same domain, but it would end up being annoying in some dimension no matter what options or defaults are chosen, unless those options get sophisticated and complex, which I just don't have bandwidth for.

For example, one approach would be to realize that there were multiple windows and then prompt you about closing all of them, which feels like high friction if you just want to detach and move on to something else.

The behavior we have now is potentially annoying if you close one but expected to use the other, but at least the detach is non-destructive so you can always attach and kill off the tabs/panes if that is what you really wanted.
