### ISSUE TITLE
Mouse scrolling in Kakoune triggers `Alt-[`

### ISSUE THREAD

**Issue by kkga** [wez/wezterm#2649]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

macOS

### WezTerm version

20221017-204532-ec4d5eb1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Mouse scrolling in Kakoune triggers a command which is typically triggered by pressing `Alt-[`:

https://user-images.githubusercontent.com/1460122/196570075-d3ef6a10-670e-453e-8eb6-a606a378bfe7.mp4

### To Reproduce

scroll the buffer in Kakoune with mouse; sometimes takes a few seconds of scrolling to reproduce, but often starts immediately after first scroll.

### Configuration

no config

**Comment by kkga** [comment]
Thanks for quick response. Here you go:
[recording.txt](https://github.com/wez/wezterm/files/9818724/recording.txt)

**Comment by pomdtr** [comment]
I encounter the same issue on the latest version of kakoune.
To disable the mouse in kakoune, you can add this line to your kakrc.

```
set -add global ui_options terminal_enable_mouse=false
```

**Comment by kkga** [comment]
After some more experimentation: this happens specifically when using horizontal scroll in my case, which is easy to trigger accidentally on a trackpad.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by pomdtr** [comment]
Thanks, I'll take a look !

**Comment by pomdtr** [comment]
It works fine on my device :)
