### ISSUE TITLE
mux workspaces cannot be closed/cause un-intuitive behavior

### ISSUE THREAD

**Issue by mfiano** [wez/wezterm#2655]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 i3

### WezTerm version

wezterm 20221019-200013-cc4a155a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Closing the last mux window tagged with a workspace identifier causes a new workspace to have windows spawned. I think this violates the rule of least surprise and should not be a default behavior.

### To Reproduce

Create a setup with a few windows, each having a unique workspace tag. Activate a workspace. Close the single window of that workspace using the window decorations or your windowing environment's key bindings. The window is closed, but a new workspace is shown by drawing N more windows.

### Configuration

Not really configuration related. Only need to `wezterm connect` to any mux server instance with more than 1 workspace.

### Expected Behavior

I would expect that when closing the last visible window that any remaining workspaces remain hidden. As a user I know that my other mux windows are being served by a separate application and can be reconnected to again. I would not expect to have to keep closing windows that keep re-appearing to hide the whole GUI.

The workaround would be to make a keybinding to call `wezterm.action.QuitApplication`, which will shut down the GUI. This has two main problems:

- The GUI is shutdown. Any stateful applications in windows on workspaces that wished to remain hidden would be lost. Muxed windows only can be considered for cleanly shutting down.

- I must do this with a separate keybinding, and all bets are off if muscle memory forces me to use my X11 window manager's keybindings to close the window.

I think the simplest solution to avoid this surprise is to do something like:

Add a new option, that does:

- If the last window of the active workspace is closed by the window manager, and there are existing inactive workspaces, check that all remaining windows are mux windows. If so, quit the GUI application. If not, prompt or retain the current behavior of showing the next workspace.

**Comment by wez** [comment]
The latest release now simply detaches the domain when closing the window.
