### ISSUE TITLE
sign binaries and setup

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#266]
Not sure if there is an easy way. Not high priority for me but seems like Edge Chromium shows this when downloading.

![image](https://user-images.githubusercontent.com/287744/93003850-0965fe00-f4f7-11ea-892a-4e02a9dbb462.png)

Feel free to close if no plans to fix this anytime soon.

**Comment by wez** [comment]
I've looked into code signing a couple of times; there are a couple of hurdles:

- Economically it doesn't make sense.  There is a recurring non-trivial fee to maintain a certificate, and that in turn requires notarized documentation to prove identity, which also requires a fee and a visit to the notary (which I'm not keen on doing during the pandemic).  None of my open source projects generate any income to cover these costs.
- Technologically it is awkward.  The cheapest option (Certum) only offer a solution that will run on a local machine which rules it out from being used in CI/CD pipelines on GH actions.  It is possible to get a private key file from eg: Comodo, but I worry about the security model of GH actions; it's not clear to me that someone couldn't submit a PR that would code sign some arbitrary code with my certificate.
- Even with an individual code signing certificate, the SmartScreen prompt may still be shown, which makes me question the value of paying for it. The only way to guarantee that SmartScreen prompt is not shown is by purchasing an EV certificate which requires extended vertification and may not be available to individuals in some jurisdictions.  The extended verification typically raises the price of these to ~$350 per year and up.

If it was possible to obtain an EV certificate for up to $100 per year and have it be safely usable from GH actions then I'd be on board with setting something up, but as the current state of things stands, it just doesn't seem feasible :-/

So, while I'd like to see this implemented, I don't see it happening.
