### ISSUE TITLE
Set the color of titlebar with lua

### ISSUE THREAD

**Issue by premeq** [wez/wezterm#2663]
**Is your feature request related to a problem? Please describe.**
Is it possible to set the color of title bar?  I would like to make it black for my theme on macos.

**Describe the solution you'd like**
I would like to be able to configure the color of the title bar in the lua file, but the (closest?) setting I found for this does not work for me.... 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/33295482/197414540-b81e3c6b-3fef-453f-9c7b-ce7f146810db.png">
https://wezfurlong.org/wezterm/config/lua/config/window_frame.html?highlight=client%20side%20decorations#window_frame

**Describe alternatives you've considered**
Switching the title bar completely off with RESIZE window decorations.

**Additional context**
I really love what you do here! <3

**Comment by wez** [comment]
We don't have guaranteed control over the OS title bar on all systems.  Turning off the OS decorations is probably the way to go.
Note that this PR will enable the best of both worlds:
* https://github.com/wez/wezterm/pull/2722

**Comment by wez** [comment]
As mentioned above, you can achieve this using the integrated title bar feature.
https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html?h=integrated_buttons
