### ISSUE TITLE
Support for iTerm2 marks

### ISSUE THREAD

**Issue by swsnr** [wez/wezterm#2666]
**Is your feature request related to a problem? Please describe.**
iTerm2 has this handy feature which lets you place a "mark" in arbitrary output with `OSC 1337 ; SetMark ST`.  For every mark it puts a small indicator onto the left border, and let's you scroll back to past marks with Cmd+Shift+M.

Back when I used macOS and iTerm I had my prompt emit a mark, so I could scroll back to the previous prompt with a single hotkey.  I found this handy in cases where I accidentally dumped too much text onto a terminal, and wanted to see the first lines.

**Describe the solution you'd like**
I'd love to have this escape code, and with all the recent changes to wayland support Wezterm has become so great that I figured I could ask for the last piece to perfection 😇 

**Describe alternatives you've considered**
Are there any other ways to mark shell prompts and scroll back to past prompts?

**Additional context**
See https://iterm2.com/documentation-escape-codes.html

**Comment by lunaryorn** [comment]
Oh indeed, I had totally forgotten about this feature.  I even had it in my config and didn't remember 🙈 

As far as I'm concerned I'm happy; feel free to close this ticket if you like.

**Comment by swsnr** [comment]
I'm not using wezterm anymore, and I'm closing this ticket as I no longer care.
