### ISSUE TITLE
Installer does not work on arm64 windows 

### ISSUE THREAD

**Issue by xeysz** [wez/wezterm#2667]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20221023-205047-43f2265e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Installer fails with message "This program can only be installed on versions of Windows designed for the following processor architectures: x64"

### To Reproduce

Download installer and run as administrator

### Configuration

no config

### Expected Behavior

x64 Inno Setup should work on arm64 targets under emulation

### Anything else?

Windows on arm64 will [emulate x64](https://blogs.windows.com/windows-insider/2020/12/10/introducing-x64-emulation-in-preview-for-windows-10-on-arm-pcs-to-the-windows-insider-program/) if x64 binaries are used. The zipfile (portable) version of wezterm works fine (as far as I can tell), but the installer will refuse to run. That means users can't use winget to install or update and have to manually do both.

A native arm64 build would work but that might be more effort than getting Inno Setup to run where [x64 emulation is supported](https://stackoverflow.com/questions/73707415/can-inno-setup-detect-windows11-on-arm64-hardware-which-can-emulate-x64).

I haven't tested on native windows arm64 installations (like a Surface Pro X), but I have access to one if that helps testing.

**Comment by wez** [comment]
Blocked on GitHub Actions not supporting arm64: https://github.com/actions/runner-images/issues/768

**Comment by wez** [comment]
I'll accept a PR that allows the inno setup stuff to run on arm64 and allow emulation to kick in, but I have no way to validate it

**Comment by xeysz** [comment]
I have a patch that works for x64 emulation on arm64. I will make sure this doesn't break native x64 and that it properly works or reports errors on older versions of windows and will send a PR your way.
