### ISSUE TITLE
"Open WezTerm Here" opens WezTerm in default directory if using supplied auto-fullscreen config script

### ISSUE THREAD

**Issue by jackschedel** [wez/wezterm#2675]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220905-102802-7d4b8249

### Describe the bug

When using the "Open Wezterm Here" function from the right-click menu in Windows Explorer, a wezterm window is opened, but in the default directory, not in the chosen directory.

This only occurs when my config has the supplied code for auto-fullscreening the program:

`wezterm.on("gui-startup", function()
  local tab, pane, window = mux.spawn_window{}
  window:gui_window():maximize()
end)`

### To Reproduce

set config to contain 
`wezterm.on("gui-startup", function()
  local tab, pane, window = mux.spawn_window{}
  window:gui_window():maximize()
end)`
(entire config supplied below, this is basically my whole config)

Use "Open Wezterm Here" function from the right-click menu in Windows Explorer:
![image](https://user-images.githubusercontent.com/26682594/198755450-935aba31-d972-4104-8463-fb2068ac1d1a.png)

Result:
![image](https://user-images.githubusercontent.com/26682594/198755455-5a9373b3-70ba-424a-a43e-21fc29119d0c.png)
(default user directory)

### Configuration

local wezterm = require 'wezterm'
local mux = wezterm.mux

wezterm.on("gui-startup", function()
  local tab, pane, window = mux.spawn_window{}
  window:gui_window():maximize()
end)

return {}

### Expected Behavior

(removed config file):

Use "Open Wezterm Here" function from the right-click menu in Windows Explorer:
![image](https://user-images.githubusercontent.com/26682594/198755450-935aba31-d972-4104-8463-fb2068ac1d1a.png)

Result:
![image](https://user-images.githubusercontent.com/26682594/198755486-79a30f9f-f016-41b0-9305-ab47ba0df53a.png)

**Comment by wez** [comment]
Take another look at https://wezfurlong.org/wezterm/config/lua/gui-events/gui-startup.html; you're missing the `cmd` parameter to the event. That was added in a slightly later revision of the startup hook

**Comment by jackschedel** [comment]
ah, I took the script from the comment on the original github issue asking for the feature, the script in the wiki works as expected. thanks
