### ISSUE TITLE
[WSL2 + ZSH + Starship Prompt] - Shell command output sometimes being swallowed

### ISSUE THREAD

**Issue by sgoudham** [wez/wezterm#2678]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20221023-205047-43f2265e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using WezTerm on WSL2 + Starship Prompt with the zsh shell integration, the following behaviour is observed:
![starship-bug](https://user-images.githubusercontent.com/58985301/198853688-ff5a9ab0-d6da-4fe6-9e03-4374a8cc4709.gif)
It is important to note that the output is correctly shown after going into an editor such as `lvim` and exiting.

### To Reproduce

1. Add `. "$HOME/.config/wezterm/wezterm.sh"` to `.zshrc` (The content of this file is https://github.com/wez/wezterm/blob/main/assets/shell-integration/wezterm.sh)
2. Install Starship.rs and include `eval "$(starship init zsh)"` at the bottom of `.zshrc`
3. Run `exec zsh`
4. Run normal commands and observe output being swallowed randomly

### Configuration

no config

### Expected Behavior

The output should not be swallowed by WezTerm

### Logs

21:39:50.611  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{1f162}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
22:07:56.691  INFO   wezterm_gui::termwindow > clicking https://github.com/starship/starship/issues/new?template=Bug_report.md&body=%23%23%23%23+Current+Behavior%0A%3C%21--+A+clear+and+concise+description+of+the+behavior.+--%3E%0A%0A%23%23%23%23+Expected+Behavior%0A%3C%21--+A+clear+and+concise+description+of+what+you+expected+to+happen.+--%3E%0A%0A%23%23%23%23+Additional+context%2FScreenshots%0A%3C%21--+Add+any+other+context+about+the+problem+here.+If+applicable%2C+add+screenshots+to+help+explain.+--%3E%0A%0A%23%23%23%23+Possible+Solution%0A%3C%21---+Only+if+you+have+suggestions+on+a+fix+for+the+bug+--%3E%0A%0A%23%23%23%23+Environment%0A-+Starship+version%3A+1.11.0%0A-+zsh+version%3A+zsh+5.8+%28x86_64-ubuntu-linux-gnu%29%0A-+Operating+system%3A+Ubuntu+20.04%0A-+Terminal+emulator%3A+WezTerm+20220923-164403-61752504%0A-+Git+Commit+Hash%3A+%0A-+Branch%2FTag%3A+master%0

### Anything else?

Without the `. "$HOME/.config/wezterm/wezterm.sh"` included within the `.zshrc`, Starship works properly

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by sgoudham** [comment]
Apologies! I didn't realise that command existed. 
I didn't have time today but will get this around to you when I can 👍 

Thanks for the speedy response!

**Comment by sgoudham** [comment]
So I have been testing more and more with this issue, and I don't think the problem is with starship integrating with wezterm I was able to reproduce behaviour while customising my oh-my-posh prompt today which leads me to believe that it's not limited to one type of prompt.

I'm finding this issue hard to debug as the behaviour almost seems non-deterministic.
