### ISSUE TITLE
cannot call async functions from `format-tab-title` event

### ISSUE THREAD

**Issue by hosxy** [wez/wezterm#2679]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20221023-205047-43f2265e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

it alaways show ` [fail](format-tab-title: runtime error: attempt to yield from outside a coroutine) ` when I call `MuxWindow:gui_window()`

### Configuration

``` lua
local wezterm = require 'wezterm';

function basename(s)
  return string.gsub(s, '(.*[/\\])(.*)', '%2')
end

wezterm.on('format-tab-title', function(tab, tabs, panes, config, hover, max_width)
    local new_padding = {left = 0, top = 0, bottom = 0}
    
    local pane = tab.active_pane
    local program_name = basename(pane.foreground_process_name)
    local mux_window = wezterm.mux.get_pane(pane.pane_id):window()
    
    wezterm.log_info(mux_window:get_title())
    
    local current_window = mux_window:gui_window()
    local overrides = current_window:get_config_overrides() or {}
    
    if program_name == "nvim.exe" then
        overrides.window_padding = new_padding
        current_window:set_config_overrides(overrides)
    end
end)
```

### Logs

```
11:57:40.444  INFO   logging > lua: C:\WINDOWS\system32\cmd.exe
11:57:40.445  WARN   wezterm_gui::tabbar > format-tab-title: runtime error: attempt to yield from outside a coroutine
stack traceback:
        [C]: in ?
        [C]: in function 'coroutine.yield'
        [string "?"]:9: in method 'gui_window'
        [string "D:\Wezterm\wezterm.lua"]:16: in function <[string "D:\Wezterm\wezterm.lua"]:7>
```

**Comment by wez** [comment]
This is expected; please read the second and third paragraphs of https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html

I'd suggest using the [update-status](https://wezfurlong.org/wezterm/config/lua/window-events/update-status.html) event instead; it is triggered periodically as well as in a number of situations where the title information changes.

**Comment by hosxy** [comment]
> This is expected; please read the second and third paragraphs of https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html
> 
> I'd suggest using the [update-status](https://wezfurlong.org/wezterm/config/lua/window-events/update-status.html) event instead; it is triggered periodically as well as in a number of situations where the title information changes.

Thank you, Now I use the `update-status` event, it works well.
