### ISSUE TITLE
mux server needs to be restarted in order to apply color scheme changes to existing panes

### ISSUE THREAD

**Issue by rbutoi** [wez/wezterm#2686]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Sway

### WezTerm version

wezterm 20221023-205047-43f2265e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm seeing that the mux server doesn't respect any colour schemes at all (see repro instructions). Interestingly, other options seem to work - for example, in this basic config, I'm able to update `font_size` and get live-reloading of both mux and non-mux `wezterm`s, but not `color_scheme`:

```
 return {
    -- text & colours
    font = wezterm.font("JetBrains Mono"),
    font_size = font_size,
    color_scheme = "Gruvbox Dark",
}
```

### To Reproduce

This, from no config (`-n`) shows as the default colour scheme:

```
wezterm -n --config 'color_scheme="Gruvbox Dark"' --config 'unix_domains = {{name="test"}}' connect test
```

This, without multiplexing, works:

```
wezterm -n --config 'color_scheme="Gruvbox Dark"'
```

### Configuration

no config needed

### Expected Behavior

`color_scheme` respected

### Anything else?

Came here from https://github.com/wez/wezterm/issues/1268#issuecomment-1295232229, and realized the issue I was facing was specific to colour schemes.

**Comment by wez** [comment]
Using `wezterm --config ...` doesn't propagate those command-line specific overrides to the `wezterm-mux-server` that gets spawned; it uses the config file as-is.
Would that explain the behavior you're seeing?

**Comment by rbutoi** [comment]
> Using wezterm --config ... doesn't propagate those command-line specific overrides to the wezterm-mux-server that gets spawned; it uses the config file as-is.

Ah ok sorry, the example I gave isn't helpful then. The same thing would be demonstrated by putting the contents of the `--config <blah>` into the file itself. The simple thing I was trying to demonstrate was that, when making a new window with `wezterm connect auto` (where `auto` is from `unix_domains = {{name = 'auto',},},`), the new window would pop up with the default colour scheme, rather than Gruvbox Dark (from my config).

>  Would that explain the behavior you're seeing?

I don't think so - it seems like `wezterm-mux-server` isn't using my config file at all (or something else is up).

**Comment by stvhay** [comment]
I think I am experiencing the same behavior on my system. In my case, I've installed wezterm on a mac using homebrew, and remote system is Debian 11 with the .deb installed. I've created the ssh_domains and then connected to it, but on the remote end I am getting the default color scheme instead of in my case, "lovelace". Maybe the .deb isn't installing some kind of theme data that is needed for the theming to work?

**Comment by wez** [comment]
@stvhay the palette and color scheme are specified by the multiplexer where the panes are created (eg: the mux server). See:
* https://github.com/wez/wezterm/issues/1268

**Comment by stvhay** [comment]
@wez yes i have the config in my server-side $HOME and its not picking up the theme. sorry if that wasn't clear

**Comment by stvhay** [comment]
Here on the client (my laptop) I have

~/.wezterm.lua
```
local wezterm = require 'wezterm'
return {

    font = wezterm.font 'Hack Nerd Font Mono',

    color_scheme = 'lovelace',

    ssh_domains = {
        {
            name = 'dst1',
            remote_address = '1.1.1.1',
            username = 'stvhay',
        },
    },
}
```

And on the server I have

$HOME/.wezterm.lua
```
local wezterm = require 'wezterm'
return {
    color_scheme = 'lovelace',
}
```

**Comment by stvhay** [comment]
Got it.

I had to kill -9 the **wezterm-mux-server** process. It wasn't enough to exit all the shells and reconnect.

Thanks for making this term--its quite great.

**Comment by wez** [comment]
Ah, so can we call this issue closed?

**Comment by stvhay** [comment]
@wez The original ticket #1268 indicated documentation might be written. Up to you, but I suggest/propose the following addition to the docs https://wezfurlong.org/wezterm/multiplexing.html here: (Sorry, not sure how to phrase this as a proper PR)

# Multiplexed Configuration

When creating a multiplexed wezterm session, a remote process **wezterm-mux-server** starts on the remote end. This process is responsible for creating new multiplexed sessions at the remote end, and derives any settings for these sessions from a remote configuration file. (For example, in the user's $HOME directory). When updating settings for remote sessions, it is currently necessary to shutdown the connection and kill this process for the configuration file to reload.

The above behavior is different from a wezterm ssh session, which does not persist server-side and therefore continues to uses local configuration values.

**Comment by wez** [comment]
I added a note as the last paragraph in the color scheme section of the docs:
https://wezfurlong.org/wezterm/config/appearance.html#color-scheme

That doesn't cover restarting the mux server; I suppose it could be expanded to do that, and a similar note could be added to the multiplexer section.

**Comment by wez** [comment]
Note that ea92df9486af052a12994ccad8c561f45bc61345 and 338174b430d0957fd0351846b006397e0bbfc4f4 improve things a bit here

**Comment by wez** [comment]
This issue should now be obsolete: the latest release shifts ownership of the color scheme to the client
