### ISSUE TITLE
double click selection selects tmux's pane separator

### ISSUE THREAD

**Issue by mzr** [wez/wezterm#2688]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

In iTerm double click on a word at the beginning of a line in a pane that has another pane left of it, in tmux, selects just the word:

<img width="160" alt="Screenshot 2022-10-31 at 19 53 13" src="https://user-images.githubusercontent.com/16736821/199098946-e82dec13-5e1f-4010-a532-269ec77de7e1.png">

In wezterm, the pane separator is treated as part of the word, and it's also selected:

<img width="169" alt="Screenshot 2022-10-31 at 19 53 36" src="https://user-images.githubusercontent.com/16736821/199098944-4088cd84-e818-4674-ab5c-c1263ca8fdea.png">

### To Reproduce

Open tmux, split the window vertically, run `echo abcd` in the right pane, double click on `abcd`.

### Configuration

```
local wezterm = require 'wezterm';

return {
  hide_tab_bar_if_only_one_tab = true,
  window_close_confirmation = "NeverPrompt",
  hyperlink_rules = {
    {
      regex = "\\b\\w+://(?:[\\w.-]+)\\.[a-z]{2,15}\\S*\\b",
      format = "$0",
    },
    {
      regex = "\\b([tTdDpP]\\d+)\\b",
      format = "https://websiteurl.com/b/$1",
    },
  },
  quick_select_patterns = {
    "\\b([tTdDpP]\\d+)\\b",
  },
  color_scheme = "tokyonight",
  font = wezterm.font_with_fallback {
    'SauceCodePro Nerd Font',
    'Fira Code',
  },
  font_size = 14,
  exit_behavior = "Close",
}
```

### Expected Behavior

Pane separator shouldn't be selected.

**Comment by bew** [comment]
You can control what is considered part of a word using https://wezfurlong.org/wezterm/config/lua/config/selection_word_boundary.html

**Comment by mzr** [comment]
Thanks! That's awesome!
