### ISSUE TITLE
[aur] broken PKGBUILD

### ISSUE THREAD

**Issue by timescam** [wez/wezterm#269]
## Build Environment:
 - OS: Linux X11, Arch Linux
 -  package: [wezterm-git](https://aur.archlinux.org/packages/wezterm-git/)
 - pkgrel=2

## The build output
==> ERROR: makedepends contains invalid characters: ','

## Fix
```sh
-makedepends=('rust' 'cargo' 'cmake' 'git' 'pkgconf', 'python')
+makedepends=('rust' 'cargo' 'cmake' 'git' 'pkgconf' 'python')
```

**Comment by wez** [comment]
Thanks for reporting!
I just pushed a speculative fix

**Comment by timescam** [comment]
tested and its fixed
