### ISSUE TITLE
Disable all input to terminal while a key table is active

### ISSUE THREAD

**Issue by JakeHL** [wez/wezterm#2702]
Hi there, not sure if this already exists but I couldn't find it. 

For context:

I have my key table set up to behave modally. I use 'Ctrl + SomeKey' to enter a mode such as pane splitting or resizing. I show which mode I'm in in the right hand status bar.
 
![image](https://user-images.githubusercontent.com/9119973/199986337-e19ef868-b68d-48a1-afd5-3047640eed3b.png)
![image](https://user-images.githubusercontent.com/9119973/199986365-e74b2d80-dad8-4ad1-b189-2af770cf5d87.png)
![image](https://user-images.githubusercontent.com/9119973/199986401-d03353a5-b557-433d-8001-80dea72c94fc.png)

etc. 

A problem I face is that sometimes I forget I'm in a mode and find myself typing a command only to eventually end up accidentally splitting my pane, spawning tabs etc. As a workaround I use the `until_unknown` in the `ActivateKeyTable` action to make it so that other keypresses drop me out of the mode. This stops me from accidentally performing actions unless the first key of the command happens to be bound in a mode.

What I'd like to know is would it be possible to disable sending any other key presses to the terminal while one of these key tables are active?

Sorry for the long winded issue. I wasn't sure how else to describe it.

As an aside: I've achieved this modal system with a module I have created to automatically generate these menus and modes as well as assign the key bindings so this feature would be the final piece of the puzzle to make me happy with it for sharing as a 'plugin' of sorts.

**Comment by wez** [comment]
Sounds reasonable. 6aceb97dedec7054947e19f98fbf961d344325cd adds a `prevent_fallback` boolean to `ActivateKeyTable` that will prevent falling back to later key tables.

Can you try that and let me know how it goes?
I can then write up the docs for it.

**Comment by wez** [comment]
> As an aside: I've achieved this modal system with a module I have created to automatically generate these menus and modes as well as assign the key bindings so this feature would be the final piece of the puzzle to make me happy with it for sharing as a 'plugin' of sorts.

Looks great!

**Comment by JakeHL** [comment]
> Can you try that and let me know how it goes?
> I can then write up the docs for it.

Ah absolutely, thanks for the heads up! I don't have a lot of time this afternoon but I'll try to get some feedback to you this weekend.

**Comment by jankatins** [comment]
@JakeHL Any chance to share this code? I would be really interested how to make such tables and such nice UI :-)

**Comment by JakeHL** [comment]
I'll be sharing it soon. Few things I want to tidy up first. I'll ping you when it's ready 👍🏻

**Comment by JakeHL** [comment]
@wez 
> Sounds reasonable. [6aceb97](https://github.com/wez/wezterm/commit/6aceb97dedec7054947e19f98fbf961d344325cd) adds a `prevent_fallback` boolean to `ActivateKeyTable` that will prevent falling back to later key tables.

I build with the latest commit on `main` and tried the prevent fallback behavior. I'm not sure if I'm doing something wrong but it seems like no keypresses at all are being registered once I've activated a key table. I'm unable to exit the table with `PopKeyTable` or perform any other actions.

**Comment by JakeHL** [comment]
@wez It works great now, thanks!
