### ISSUE TITLE
update key binding documentation

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wez/wezterm#2704]
updating keybindings by now seems to require the format described [here](https://github.com/wez/wezterm/blob/77b6870ff397d8a4fed7399e25b5fc3f80ebfd6d/docs/config/lua/keyassignment/MoveTabRelative.md).
however, the `action` property is not yet mentioned in the [docs](https://wezfurlong.org/wezterm/config/keys.html). it would be nice if those were updated to reflect this change.

**Comment by wez** [comment]
Thanks; updated!
