### ISSUE TITLE
reintroduce gnome-friendly key bindings for moving tabs

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wez/wezterm#2705]
the default key binding [documentation](https://github.com/wez/wezterm/blob/ecd7bc984282f90f0519063c14d1b638f906a664/docs/config/default-keys.md) mentions a familiar keybinding for `MoveTabRelative`: CTRL+SHIFT PageUp / PageDown, matching how linux users are used to moving around tabs in common web browsers.
however, the present [default keybindings](https://github.com/wez/wezterm/blob/ec4d5eb1d5f9faabd78efd88abad06f039973364/wezterm-gui/src/commands.rs#L496-L515) appear more in line with what one might expect on OSX, using SUPER+SHIFT over CTRL+SHIFT.
on gnome, however, this keybinding actually is not only unidiomatic, but furthermore clashes with the gnome keybinding to move windows across workspaces.
it would be nice if both keybindings were included by default such as to make wezterm work nicely across both environments.

**Comment by wez** [comment]
Thanks; this was actually a bug and is fixed now in `main`.
