### ISSUE TITLE
compose_cursor color setting ignored for leader key

### ISSUE THREAD

**Issue by dinkonin** [wez/wezterm#2708]
### What Operating System(s) are you seeing this problem on?

Windows, Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Plasma

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I want a to change the cursor color when leader mode is active, but setting  `compose_cursor` has no effect.

### Configuration

```
 hide_tab_bar_if_only_one_tab = true,
 colors = {
    compose_cursor = 'orange',
 },
 leader = { key = 'a', mods = 'CTRL', timeout_milliseconds = 2000 },
  keys = {
    {key = '/', mods = 'LEADER', action = wezterm.action.SplitHorizontal { domain = 'CurrentPaneDomain' },},
```

### Logs

wezterm version: 20220905-102802-7d4b8249
OpenGL version: AMD Radeon Graphics (renoir, LLVM 14.0.6, DRM 3.48, 6.0.7-arch1-1) 4.6 (Compatibility Profile) Mesa 22.2.1

**Comment by dinkonin** [comment]
I just built the current version from git, the problem is fixed. Sorry for the spam.

**Comment by dinkonin** [comment]
Actually no, the problem is still present on `wezterm 20221106-210748-de7f5e56`.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
