### ISSUE TITLE
Where to locate the log file when wezterm starts?

### ISSUE THREAD

**Issue by ktrNozomi** [wez/wezterm#2711]
I use archlinux + openbox. When I configured shortcuts to open the wezterm, I notice that it will stuck a while for the first start, but works well afterwards. So I want to locate the problem, where can I find the logs? I tried xterm instead, it will not stuck. Thanks for your reply!

**Comment by wez** [comment]
You can see logs in a couple of different ways:

* activate the Debug Overlay by pressing CTRL-SHIFT-L to see recent errors
* You can find log files in `$XDG_RUNTIME_DIR/wezterm` on unix systems, or `$HOME/.local/share/wezterm` on macOS and Windows systems.

You may wish to start wezterm with `WEZTERM_LOG=trace wezterm` set in the environment to turn up very verbose logging. Logs will show on stderr.
