### ISSUE TITLE
AUR wezterm-nightly-bin: Error loading shared library

### ISSUE THREAD

**Issue by latipun7** [wez/wezterm#2712]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20221105-090535-a135f536

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm can't start on Arch Linux. Recently Arch Linux updated `openssl` to version 3.0.7-2 which cause [WezTerm from AUR](https://aur.archlinux.org/packages/wezterm-nightly-bin) failed to start with the following error:

```log
wezterm: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
wezterm: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

`/usr/lib` now only contains `libssl.so` & `libssl.so.3`

### Configuration

I think it's not relevant.

### Expected Behavior

WezTerm launch.

### Anything else?

For now, as workaround, I extracted `libssl.so.1.1` & `libcrypto.so.1.1` from previous cache of `openssl` to `/usr/lib` and WezTerm can launch successfully.

**Comment by wez** [comment]
Please try https://aur.archlinux.org/packages/wezterm-git instead; the bin version uses binaries built on ubuntu and those don't seem to be compatible with arch any longer

**Comment by latipun7** [comment]
Personally I didn't want to build `wezterm-git` yet since my PC is low end, but I suppose `wezterm-git` would works because it build againts our own machine.

I understand, you are free to close this since the workaround is simple enough only copy those libraries from the previous version of that library, and eventually the binaries from ubuntu would catch up. 😢

Thank you.

**Comment by wez** [comment]
I have submitted a request to delete `wezterm-nightly-bin` as I don't think there is a way to "fix" it.

Here's the text I submitted in my request:

```
wez [1] filed a deletion request for wezterm-nightly-bin [2]:

This PKGBUILD works by unpacking an AppImage (that was built on ubuntu
18) and sticking the binaries on the filesystem.

The recent openssl upgrade in arch has rendered this completely broken
due to DSO version differences between Ubuntu and Arch.

I don't think there is a way to "fix" this, so let's remove this
package.

Alternatives for the user who wants pre-built binaries are:

* Use flatpak
* Use the full AppImage

Otherwise, building from source:

* Use the wezterm-git AUR
* Manually build from source

```

**Comment by latipun7** [comment]
TBH, you don't need to delete it. Just update the PKGBUILD if something is not right. For example, for my use case, I edit the PKGBUILD like this and it is working again:
```diff
 package() {
   install -Dm755 squashfs-root/usr/bin/wezterm -t "${pkgdir}/usr/bin/"
   install -Dm755 squashfs-root/usr/bin/wezterm-gui -t "${pkgdir}/usr/bin/"
   install -Dm755 squashfs-root/usr/bin/wezterm-mux-server -t "${pkgdir}/usr/bin/"
+  install -Dm755 squashfs-root/usr/lib/libcrypto.so.1.1 -t "${pkgdir}/usr/lib/"
+  install -Dm755 squashfs-root/usr/lib/libssl.so.1.1 -t "${pkgdir}/usr/lib/"
   install -Dm644 squashfs-root/usr/share/icons/hicolor/128x128/apps/org.wezfurlong.wezterm.png \
     "${pkgdir}/usr/share/icons/hicolor/128x128/apps/org.wezfurlong.wezterm.png"
   install -Dm644 squashfs-root/usr/share/applications/org.wezfurlong.wezterm.desktop \
     "${pkgdir}/usr/share/applications/org.wezfurlong.wezterm.desktop"
 }
```
I really need this because I tried full appimage and I have issue with symlink.

**Comment by sdrik** [comment]
I think wezterm-nightly-bin should simply depends on openssl-1.1 which provides libssl.so.1.1 and libcrypto.so.1.1 for compatibility reason.

**Comment by vimpostor** [comment]
> Alternatives for the user who wants pre-built binaries are:
> 
> * Use flatpak
> * Use the full AppImage

You forgot the most sane alternative, which is simply install the official Arch Linux [wezterm](https://archlinux.org/packages/community/x86_64/wezterm/) package, which got [automatically rebuilt](https://github.com/archlinux/svntogit-community/commit/41e544032537dfd1cca7dc9ead08e367e6d52e73) once openssl 3 dropped.

**Comment by wez** [comment]
Can you tell the official package to build from `main`/git?

**Comment by latipun7** [comment]
ofc they are not. `wezterm` and other packages in official repo always pin to the latest version, not build from development repo. So yeah, `wezterm` official Arch repo is not alternative. You Wez is correct, imo.

https://github.com/archlinux/svntogit-community/blob/packages/wezterm/trunk/PKGBUILD#L4-L5

**Comment by vimpostor** [comment]
>Can you tell the official package to build from `main`/git?
>

Arch only builds the stable releases that you tag on Github, and is 
usually quite fast with updating once you have created a release on 
Github.

You described alternatives for pre-built binaries and mentioned the 
Flatpak binary first, which also only builds the stable releases, so I 
thought it would be fair to include the official Arch package as well.

Of course Arch does not ship nightly images (and neither does Flatpak), 
so for that you'd have to use something else.

**Comment by vimpostor** [comment]
> For me, the alternative is download the current PKGBUILD from wezterm-nightly-bin AUR, then edit and install myself, only in my machine.
> +  install -Dm755 squashfs-root/usr/lib/libcrypto.so.1.1 -t "${pkgdir}/usr/lib/"
> +  install -Dm755 squashfs-root/usr/lib/libssl.so.1.1 -t "${pkgdir}/usr/lib/"

Please don't use this cursed workaround of installing Ubuntu openssl
binaries systemwide on an Arch system!

The correct workaround would simply to add openssl-1.1 to the package's
dependencies, `/usr/lib/libcrypto.so.1.1` is installed by openssl-1.1
from the Arch repo.

**Comment by wez** [comment]
Honestly, I don't use arch and I view this wezterm-nightly-bin AUR as a support burden that I don't want to bear: it's trying to run stuff from ubuntu on arch and is destined to have a higher incidence of people reporting problems with it.
My preference is to delete it to avoid sinking my time into it, which is why I've already requested its removal.

If you need to run a nightly, you'll need to build it from git using the `wezterm-git` AUR, or by building it from source for yourself, or by using the full AppImage in its entirety.

Those are the options that I'm willing to support.
