### ISSUE TITLE
Battery of "command not found: append_path"

### ISSUE THREAD

**Issue by grappas** [wez/wezterm#2713]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Each time on new terminal session is opened before prompt is up:

```
/etc/profile.d/flatpak-bindir.sh:10: command not found: append_path
we set XMODIFIERS GTK_IM_MODULE QT_IM_MODULE in profile.d
/etc/profile.d/perlbin.sh:6: command not found: append_path
/etc/profile.d/perlbin.sh:8: command not found: append_path
/etc/profile.d/perlbin.sh:10: command not found: append_path
```
![image](https://user-images.githubusercontent.com/1036957/200168879-6a0a1ccb-d986-4ea4-8fb0-238d6df48c84.png)

It's only happening in wezterm (tried also konsole, gnome-terminal, kitty, alacritty).

Yes: I'm using powerlevel10k in oh-my-zsh, but there's no mention in config and/or scripts of above.

### To Reproduce

In arch linux/gnome just open wezterm.

### Configuration

local wezterm = require 'wezterm'
local act = wezterm.action
local mykeys = {}

for i = 1, 8 do
  -- CTRL+ALT + number to activate that tab
  table.insert(mykeys, {
    key = tostring(i),
    mods = 'CTRL|ALT',
    action = act.ActivateTab(i - 1),
  })
  -- F1 through F8 to activate that tab
  table.insert(mykeys, {
    key = 'F' .. tostring(i),
    action = act.ActivateTab(i - 1),
  })
end

return {
    font = wezterm.font 'VictorMono Nerd Font',
    color_scheme = 'Gruvbox Dark',
    window_background_opacity = 0.9,
    keys = mykeys,
}

### Expected Behavior

On new session only prompt is popping out.

### Logs

Debug Overlay
wezterm version: 20220905-102802-7d4b8249
OpenGL version: AMD Radeon RX 6750 XT (navi22, LLVM 14.0.6, DRM 3.48, 6.0.6-arch1-1) 4.6 (Compatibility Profile) Mesa 22.2.1
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

**Comment by wez** [comment]
Those messages are not from wezterm, but are from the various shell rc files that are installed on your system.

If you run `flatpak install flathub org.wezfurlong.wezterm start -- bash --norc` that will tell wezterm to run bash without loading your shell rc files; I would expect for it to not to show those error messages.

If you run `bash -lx` from any terminal, it should run bash as a login shell and log information about what it is trying to do; that should help you debug your rcfiles.

**Comment by grappas** [comment]
> If you run `flatpak install flathub org.wezfurlong.wezterm start -- bash --norc` that will tell wezterm to run bash without loading your shell rc files; I would expect for it to not to show those error messages.

Problem is i have it installed from arch repo, not from flatpak.

**Comment by wez** [comment]
Sorry, misread the error.  Just run `wezterm start -- bash --norc` then.

**Comment by grappas** [comment]
`wezterm start -- bash --norc`
no errors
`wezterm start -- bash`
no errors
`wezterm start -- zsh --norc`
no errors
`wezterm start -- zsh`
no errors

**Comment by wez** [comment]
wezterm will run your shell as a login shell by default.  Those errors are problems with your system/shell setup when launching a login shell.  They are not caused by wezterm and can not be fixed by wezterm.

You can use `default_prog = {'bash'}` to explicitly *not* run a login shell if you wish.

See: https://wezfurlong.org/wezterm/config/lua/config/default_prog.html

**Comment by grappas** [comment]
and that worked like a charm
It shoud've been default. Read passwd for default shell and run it via default_prog.
