### ISSUE TITLE
allow selecting and copying text using the keyboard

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wez/wezterm#2715]
**Is your feature request related to a problem? Please describe.**
I sometimes want to copy some text in the terminal.
I prefer using keyboard over mouse.
It would be nice if there was an option to select and copy text using the keyboard.

**Describe the solution you'd like**
Functionality like Alacritty's [Vi Mode](https://github.com/alacritty/alacritty/blob/master/docs/features.md#vi-mode) would address this.

**Describe alternatives you've considered**
- Using a different terminal (:crying_cat_face:)
- Using a mouse (:crying_cat_face::crying_cat_face:)

**Additional context**
n/a

**Comment by wez** [comment]
Take a look at:
* [Copy Mode](https://wezfurlong.org/wezterm/copymode.html)
* [Quick Select](https://wezfurlong.org/wezterm/quickselect.html)
