### ISSUE TITLE
Kitty protocol produces garbled or no output in specific cases

### ISSUE THREAD

**Issue by hpjansson** [wez/wezterm#2716]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm-20220905.102802.7d4b8249+git147-2.1.x86_64

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Kitty-protocol images produced by `chafa` will not display correctly in WezTerm. I think this may be due to missing/incorrect protocol handling in WezTerm or one of us having misinterpreted the specification.

I'll attach a test case that should produce a single-cell magenta square when catted to the terminal. It's chunked raw RGBA of the form:

```<ESC>_Ga=T,f=32,s=10,v=22,c=1,r=1,m=1<ESC>\<ESC>_Gm=1;<DATA><ESC>\<ESC>_Gm=1;<DATA><ESC>\<ESC>_Gm=0<ESC>\```

[wezterm-kitty-test.txt](https://github.com/wez/wezterm/files/9946822/wezterm-kitty-test.txt)

It displays correctly in Kitty. This was prompted by https://github.com/hpjansson/chafa/issues/114.

### Configuration

no config

**Comment by jstkdng** [comment]
Bumping because this happens to my [application](https://github.com/jstkdng/ueberzugpp) as well. I'm using openssl to base64 encode and no image output is being generated on wezterm, output does show up on kitty and konsole. I have tried the sample python script on the kitty website and it does show up. Perhaps there's some difference in python's base64 encode and openssl's?

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by hpjansson** [comment]
@latipun7 reported that this works now. Thanks for the fix!
