### ISSUE TITLE
Question about github actions

### ISSUE THREAD

**Issue by MehdiGol** [wez/wezterm#273]
Sorry to bother you here It is not an issue I just asked my question here because I couldn't find any email address.

My question is about your Github actions configuration.  I was wondering why you did create 37 different configuration files for each OS and Os version, Isn't it possible to do all of these with matrixes in one configuration file?

**Comment by wez** [comment]
It's technically possible to set up a matrix, but it is pretty unwieldy to express the various conditions in a giant yaml file.
Instead, I programmatically generate the yaml using this script: https://github.com/wez/wezterm/blob/master/ci/generate-workflows.py

Having the actions separate has the nice side benefit of allowing the artifacts from a build to be downloaded as soon as it completes.  With a matrix build you have to wait until all systems are done before you can download for any of them.
