### ISSUE TITLE
`wezterm connect --workspace` to a not-yet-started mux doesn't use the specified workspace

### ISSUE THREAD

**Issue by cole-h** [wez/wezterm#2734]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

swaywm

### WezTerm version

wezterm 20221113-085835-274b1819

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When running `wezterm --config-file weztest.lua connect --workspace test lol` with the below config, and without the `lol` domain already running / alive, the title of the window shows that the spawned GUI instance is using the `default` workspace, rather than the specified `test` workspace.

### To Reproduce

1. `wezterm --config-file weztest.lua connect --workspace test lol`
2. Notice the title says `[ws:default] (dom:lol)`
3. Close that window (without killing the mux)
4. Run `wezterm --config-file weztest.lua connect --workspace test lol` again
5. Notice that the title now says `[ws:test] (dom:lol)` (as expected)

### Configuration

```lua
local wezterm = require 'wezterm'

wezterm.on('format-window-title', function(tab, pane, tabs, panes, config)
  local workspace = '(none)'
  local domain = '[none]'

  local window = wezterm.mux.get_window(tab.window_id)
  local ws = window:get_workspace()

  if ws ~= nil and #ws > 0 then
    workspace = '[ws:' .. ws .. ']'
  end

  if pane.domain_name then
    domain = '(dom:' .. pane.domain_name .. ')'
  end

  local index = ''
  if #tabs > 1 then
    index = string.format('[%d/%d] ', tab.tab_index + 1, #tabs)
  end

  return index .. tab.active_pane.title .. ' ' .. workspace .. ' ' .. domain
end)


return {
  unix_domains = {
    {
      name = 'lol',
    },
  },
}

```

### Expected Behavior

I would expect for the workspace to be properly set when connecting to a domain, even if the domain has not been set up yet.

### Anything else?

I tried doing some print debugging, but I was unable to figure out where this issue arose. I was checking `Mux.active_workspace()` in various places where it is accessible (in almost every function called by [`run_mux_client`](https://github.com/wez/wezterm/blob/274b1819a14d8518223ec6bb2b980dd3038976bc/wezterm-gui/src/main.rs#L294)), but it was always the expected `test` domain.

Maybe this is similar to my previous issue in that I'm fundamentally misunderstanding how this should work :sweat_smile:

**Comment by cole-h** [comment]
I took a short recording and was able to catch this transition:

![image](https://user-images.githubusercontent.com/28582702/201543443-f509ecc6-baeb-4b14-b5ec-05aef18b2c2d.png)
![image](https://user-images.githubusercontent.com/28582702/201543468-665730c7-81f3-4b6c-ab0a-a1da151e3152.png)

So it starts in the correct workspace, but then after connecting to the domain, it doesn't set the workspace there (maybe because that "set workspace" was already done by the "Connecting..." part).

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
