### ISSUE TITLE
“launchPackager.command” can’t be opened with react native

### ISSUE THREAD

**Issue by vickylance** [wez/wezterm#2741]
**Is your feature request related to a problem? Please describe.**
When you start a new react native project and run the project via cmd. It spawns another terminal once it's successfully build the project and runs Metro bundler automatically on it. However with WezTerm that new spawning of terminal doesn't happen. And hence the project never starts without Metro bundler running.

**Describe the solution you'd like**
It should either spawn a non WezTerm terminal window. Or a new Wezterm terminal window or better just a new WezTerm tab for the Metro bundler to run.

**Describe alternatives you've considered**
Just when starting a react native project I use normal terminal.

**Comment by wez** [comment]
Please provide more information about how you are using wezterm in this scenario: wezterm doesn't do or know anything about react native, and I don't think react native knows anything about wezterm.
I need to understand more about what you're doing or trying to do!

**Comment by vickylance** [comment]
This is the error popup I get when it tries to open a shell

![image](https://user-images.githubusercontent.com/5861833/203280491-806db8ad-de87-43ef-a2a1-70bdaec96f26.png)

**Comment by wez** [comment]
I think this may be a strange issue with macOS itself.
This stackoverflow issue shows that the same problem manifests with Terminal.app:
https://stackoverflow.com/questions/74187734/launchpackager-command-can-t-be-opened
and suggests a workaround using iTerm to handle those `.command` scripts.

**Comment by wez** [comment]
I added support for associating wezterm with `.command` files, perhaps that helps to solve this case?

This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
