### ISSUE TITLE
Way to remove key bindings

### ISSUE THREAD

**Issue by kentprimrose** [wez/wezterm#2742]
The only thing preventing me using WezTerm as my daily driver is the inability to get it to work with my preferred TMux configuration. I use the following across all terminals (snippet from .tmux.conf):

`bind -n M-Left  select-pane -L`
`bind -n M-Right select-pane -R`
`bind -n M-Up    select-pane -U`
`bind -n M-Down  select-pane -D`

This conflicts with the WezTerm mappings for pane navigation. But since I prefer to use TMux for window and tab navigation, I would need to UNMAP these key bindings in WezTerm to get that to work.

Is there a way to UNBIND keys that I don't find in the documentation? Or would this be a possible feature?

**Comment by gegoune** [comment]
You can use `action = 'DisableDefaultAssignment'`.
