### ISSUE TITLE
Unable to set cursor to xterm: cursor not found

### ISSUE THREAD

**Issue by psydvl** [wez/wezterm#2743]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

weston (GNOME)

### WezTerm version

20220905.102802.7d4b8249+git147-2.1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found`
This line is spammed in journalctl for me like a hell
Can logging be disabled with some variable or config option?

GNOME Shell 43.1, OpenSUSE Tumbleweed, wezterm 20220905.102802.7d4b8249+git147-2.1

### Configuration

no config

### Logs

19:51:17.636  ERROR  window::os::wayland::frame > Unable to set cursor to left_ptr: cursor not found
19:51:18.528  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.535  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.542  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.549  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.557  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.564  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.571  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.579  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.586  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.593  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.601  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.608  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.615  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.623  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.630  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.637  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.644  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.652  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.659  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.666  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.674  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.681  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.688  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.696  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.703  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.710  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.717  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.725  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.732  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.739  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.747  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.755  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.761  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.769  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.776  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.783  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.791  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.798  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.805  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:18.813  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:51:19.036  ERROR  window::os::wayland::frame   > Unable to set cursor to left_ptr: cursor not found
19:51:19.040  ERROR  window::os::wayland::pointer > Unable to set cursor to arrow: cursor not found

**Comment by psydvl** [comment]
openSUSE Tumbleweed (rolling release of openSUSE) 
Build related things https://build.opensuse.org/package/show/X11:terminals/wezterm 

However, `export XCURSOR_THEME=Adwaita` or 
```lua
return {
  xcursor_theme = 'Adwaita',
}
```
solved issue for me, but shouldn't it fallback to it by default?


PS: Just in case:
```
$ find /usr/share/icons ~/.local/share/icons ~/.icons -type d -name "cursors"
/usr/share/icons/Adwaita/cursors
/usr/share/icons/handhelds/cursors
/usr/share/icons/redglass/cursors
/usr/share/icons/whiteglass/cursors
```

**Comment by wez** [comment]
If `$XCURSOR_THEME` isn't set, wezterm will fall back to using `default`.  Do you have a `default` theme symlink? Where is it located?

Can you share the output from `env | grep -E '(XCURSOR|XDG)'`

**Comment by psydvl** [comment]
```
$ env | grep -E '(XCURSOR|XDG)'
XDG_CONFIG_DIRS=/etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg
XDG_MENU_PREFIX=gnome-
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=GNOME
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/home/nixi/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```

**Comment by wez** [comment]
> Do you have a `default` theme symlink? Where is it located?

^^

**Comment by psydvl** [comment]
> Do you have a default theme symlink? Where is it located?

Since install I've set nothing about this, so, probably, no.
But, until now, there was no necessity in this.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by bigpick** [comment]
FWIW, using the nightly appimage on ubuntu 20.04, it fixes this issue for me.

Latest stable flatpak (flathub) version with issue:

```
wezterm --version
wezterm 20220905-102802-7d4b8249
```

... compared to latest nightly app image that is fixed:

```
WezTerm-nightly-Ubuntu18.04.AppImage --version
wezterm 20221115-084118-c55cecae
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```
