### ISSUE TITLE
add_wsl_distributions_to_launch_menu has no effect

### ISSUE THREAD

**Issue by Dead0fNight** [wez/wezterm#2750]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Added 'add_wsl_distributions_to_launch_menu = false' to no effect.

### To Reproduce

Add 'add_wsl_distributions_to_launch_menu = false' to config and observe no effect.

### Configuration

```lua
local wezterm = require 'wezterm'
return {
    add_wsl_distributions_to_launch_menu = false,
    font = wezterm.font 'Iosevka NF',
	launch_menu = {
	{
            label = 'WSL Arch',
	    args = { 'wsl', '-d', 'Arch' },
	}
	},
}
```

### Expected Behavior

Not to list WSL in launcher menu.

### Logs

WARN wezterm_dynamic::error > `add_wsl_distributions_to_launch_menu` is not a valid Config field.  There are too many alternatives to list here; consult the documentation!

### Anything else?

This config does affect the terminal, changes to font, additions to launch menu, etc. so it's reading the config I added this in.

**Comment by wez** [comment]
Ah, that got replaced by the [wsl_domains](https://wezfurlong.org/wezterm/config/lua/config/wsl_domains.html) configuration.

Set: `wsl_domains = {}` in your config to prevent the default list from being used.

I'll get the docs updated.

**Comment by wez** [comment]
For your config, you probably want:

```lua
local wezterm = require 'wezterm'
return {
   wsl_domains = {
      {
         name = "WSL:Arch",
         distribution = "Arch",
      },
   },
   font = wezterm.font 'Iosevka NF',
}
```

**Comment by Dead0fNight** [comment]
Thanks for the quick response! Worked like a charm! Apologies for the close and re-open, but wanted to make sure I left a comment about it.
