### ISSUE TITLE
Background image scaling that preserves aspect ratio

### ISSUE THREAD

**Issue by chris-martin** [wez/wezterm#2757]
Currently background images scale to the window size, stretching the image horizontally or vertically to fit. This distortion is often rather unattractive. I'd love to have a setting to make the image scale to cover the window in a ratio-preserving way, with cropping to fit the window's ratio. (This is the behavior achieved in CSS with `background-size: cover`, in case that is more clarifying than my words.)

**Comment by wez** [comment]
Take a look at https://wezfurlong.org/wezterm/config/lua/config/background.html
but also note that https://github.com/wez/wezterm/pull/2636 is pending review for making an adjustment to the cover logic.

**Comment by chris-martin** [comment]
Oh, sorry I missed that part of the documentation. I saw this section https://wezfurlong.org/wezterm/config/appearance.html#window-background-image and assumed that's all there was on background image configuration. Maybe there should be a link from that section of the docs to the more full API description?

**Comment by wez** [comment]
I've added a little note to the docs. Also: since I wrote my earlier comment, the PR I mentioned was landed and a new wezterm release has been made, so you should have no blockers to trying out that background option using `cover`.
