### ISSUE TITLE
Window dragging in GNOME X11 by the tab bar is broken (classic tab bar)

### ISSUE THREAD

**Issue by jfaz1** [wez/wezterm#2758]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20221118-102931-dad5fbd1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When dragging Wezterm via the tab bar, the window teleports around is nearly un-moveable. This issue does NOT happen using the native window bar/title. 
[Screencast from 2022-11-18 22-24-53.webm](https://user-images.githubusercontent.com/56184947/202829992-6019f842-037d-4ab5-9ddd-193473b9278c.webm)

### To Reproduce

Drag the Wezterm window by the tab bar when fancy tab bar is disabled.

### Configuration

use_fancy_tab_bar = false

**Comment by wez** [comment]
This should be resolve now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
