### ISSUE TITLE
Closing first ssh domain tab attaching prevents creating new tabs in the same domain

### ISSUE THREAD

**Issue by mjlbach** [wez/wezterm#2759]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

N/A

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Connecting to a new ssh domain, then closing the tab, prevents reconnecting.

### To Reproduce

0. Use confic from below
1. shift-t, choose attach test_server domain
2. Close the new tab
3. shift-t, choose new tab test_domain

Should result in a noop

Note, creating new tabs works fine so long as you don't close the original domain tab.

### Configuration

```lua
local wezterm = require("wezterm")
local act = wezterm.action

return {
        -- NOTE: this needs to be updatedd
	ssh_domains = {
		{
			name = "test_server",
			remote_address = "test_server_ip",
		},
	},

	keys = {
		{ key = 't', mods = 'SHIFT', action = act.ShowLauncherArgs { flags = 'FUZZY|DOMAINS' }},
	},
}
```

### Expected Behavior

Should be able to reconnect to the same ssh domain.

### Logs

❯ wezterm cli spawn --domain-name test_server
14:28:21.442  ERROR  wezterm > unexpected response Ok(ErrorResponse(Erel_height: 1584, dpi: 144 } command=None cwd=None" })); terminating

N/A

### Anything else?

N/A

**Comment by wez** [comment]
Can you try a recent nightly to see if this is still an issue?

**Comment by mjlbach** [comment]
Seems fixed to me. Thanks!

**Comment by mjlbach** [comment]
Sorry to reopen @wez this still seems to be an issue, not sure if the bug returned or if I did not correctly test it, but it's reproducing for me again.

**Comment by mjlbach** [comment]
Got these logging errors:

```
19:59:37.650 ERROR wezterm_gui::spawn > Failed to spawn: spawn_tab_or_window: Spawning in domain `fedora`: TerminalSize { rows: 49, cols: 187, pixel_width: 2992, pixel_height: 1617, dpi: 144 } command=None cwd=None: unexpected response Ok(ErrorResponse(ErrorResponse { reason: "Error: window_id 1 not found on this server" }))
19:59:37.651 ERROR wezterm_gui::spawn > Failed to spawn: spawn_tab_or_window: Spawning in domain `fedora`: TerminalSize { rows: 49, cols: 187, pixel_width: 2992, pixel_height: 1617, dpi: 144 } command=None cwd=None: unexpected response Ok(ErrorResponse(ErrorResponse { reason: "Error: window_id 1 not found on this server" }))
19:59:37.651 ERROR wezterm_gui::spawn > Failed to spawn: spawn_tab_or_window: Spawning in domain `fedora`: TerminalSize { rows: 49, cols: 187, pixel_width: 2992, pixel_height: 1617, dpi: 144 } command=None cwd=None: unexpected response Ok(ErrorResponse(ErrorResponse { reason: "Error: window_id 1 not found on this server" }))
19:59:37.811 ERROR wezterm_gui::termwindow > dispatch_window_event: dispatch_notif: pane id 41 is not valid
```

**Comment by wez** [comment]
I can't reproduce this issue

**Comment by mjlbach** [comment]
I also see that it happens with local unix domains, but now pain ID is invalid instead of window id.

```
19:46:50.136 ERROR wezterm_gui::termwindow > dispatch_window_event: dispatch_notif: pane id 65 is not valid
```

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by mjlbach** [comment]
Fixed! Thanks!
