### ISSUE TITLE
env_bootstrap panic in tiling WM: Viewport dimentions are too large

### ISSUE THREAD

**Issue by asolkar** [wez/wezterm#2760]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

DWL (https://github.com/djpohly/dwl/) - Tiling window manager like DWM for Wayland

### WezTerm version

wezterm 20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

In the DWL tiling window manager in Wayland, if multiple wezterm windows are opened, they are arranged in master-stack format. New windows make older windows progressively smaller. When enough windows are opened, wezterm dies with the panic error included in the attached debug log.

If RUST_BACKTRACE is not enabled, windows appeared to be unresponsive.

```
thread 'main' panicked at 'Viewport dimensions are too large', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.31.0/src/draw_parameters/mod.rs:711:9
stack backtrace:
21:29:29.028  TRACE  async_std::task::builder                > block_on
   021:29:29.028:   TRACE     async_io::driver   0x 55dc60095efd  -  <unknown> 
            1 :          0x 55dc600c09ac  -  > <unknown>block_on()

   2:     0x55dc6008d4c1 - <unknown>
   3:     0x55dc60097c55 - <unknown>
   4:     0x55dc60097971 - <unknown>
   5:     0x55dc5ee2c2a8 - <unknown>
   6:     0x55dc6009829a - <unknown>
   7:     0x55dc5fb7d6bb - <unknown>
   8:     0x55dc5fb7d684 - <unknown>
```

### To Reproduce

In a tiling window manager environment, open large number of windows in a single screen such that window sizes become very small

### Configuration

```
local wezterm = require 'wezterm'

return {
    enable_wayland = true,

    enable_tab_bar = false,
    -- hide_tab_bar_if_only_one_tab = true,

    font = wezterm.font("Iosevka"),
    adjust_window_size_when_changing_font_size = false,
}
```

### Expected Behavior

If more windows cannot be created due to lack of space on the screen, weztem is expected to gracefully fail with a log message of some kind. Not hang or panic

### Logs

[wezterm.debug.log](https://github.com/wez/wezterm/files/10048951/wezterm.debug.log)

**Comment by wez** [comment]
Note that the log file you attached doesn't include any panic or backtrace information; did you share the file you intended to share?  What I was hoping to see in that log was a combination of nonsense window dimensions and the panic backtrace, but grepping for `resize` shows pretty reasonable sizes and there is no panic message.

* Approximately how many windows do you have prior to the panic? 
* Approximately how large are they on screen?

Please try a nightly build.

If the issue persists there, please try that nightly build with `front_end = "WebGpu"` set in your config. That will use a different rendering front end from the one that is generating the panic.  WebGpu is rather new; see this issue for more details:
* https://github.com/wez/wezterm/issues/2756

**Comment by asolkar** [comment]
The wezterm.debug.log file attached has the following. It also has the trace information, a snipped of which I pasted in the initial report. I wonder if that is not the debug information you are looking for or if it is truncated in upload:

```
$ grep -n panic wezterm.debug.log.submitted
42866:21:29:29.028  ERROR  env_bootstrap                           > panic at /build/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.31.0/src/draw_parameters/mod.rs:711:9 - Viewport dimensions are too large
42892:thread 'main' panicked at 'Viewport dimensions are too large', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.31.0/src/draw_parameters/mod.rs:711:9
42954:21:29:29.030  ERROR  env_bootstrap                           > panic at /rustc/1.64.0/library/std/src/thread/local.rs:421:26 - !?
42977:21:29:29.030thread '  mainTRACE' panicked at ' cannot access a Thread Local Storage value during or after destruction: AccessError ', polling::epoll/rustc/1.64.0/library/std/src/thread/local.rs : 421 : 26 
43011:                 fatal runtime error: failed to initiate panic, error 5
```

I tried the latest nightly (20221120-093910-0bf36e5a) with and without WebGpu option. I see similar behavior. I am attaching the two log files. Please let me know if the files don't have the information you seek:

[wezterm.debug.no_WebGpu.log](https://github.com/wez/wezterm/files/10051060/wezterm.debug.no_WebGpu.log)
[wezterm.debug.WebGpu.log](https://github.com/wez/wezterm/files/10051061/wezterm.debug.WebGpu.log)

```
$ grep -Hn panic wezterm.debug.Web*.log 
wezterm.debug.WebGpu.log:596:15:41:16.928  ERROR  env_bootstrap                           > panic at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.31.0/src/draw_parameters/mod.rs:711:9 - Viewport dimensions are too large
wezterm.debug.WebGpu.log:622:15:41:16.951  ERROR  env_bootstrap                          > panic at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.31.0/src/draw_parameters/mod.rs:711:9 - Viewport dimensions are too large
wezterm.debug.WebGpu.log:648:thread 'main' panicked at 'Viewport dimensions are too large', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.31.0/src/draw_parameters/mod.rs:711:9
wezterm.debug.WebGpu.log:650:thread 'main' panicked at 'Viewport dimensions are too large', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.31.0/src/draw_parameters/mod.rs:711:9
wezterm.debug.WebGpu.log:813:15:41:17.732  ERROR  env_bootstrap                           > panic at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:26 - !?
wezterm.debug.WebGpu.log:836:thread 'main' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:26
wezterm.debug.WebGpu.log:865:fatal runtime error: failed to initiate panic, error 5
wezterm.debug.WebGpu.log:866:15:41:17.732  ERROR  env_bootstrap                          > panic at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:26 - !?
wezterm.debug.WebGpu.log:889:thread 'main' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:26
wezterm.debug.WebGpu.log:918:fatal runtime error: failed to initiate panic, error 5
```
When this happens, the size of the window is pretty small, roughly one line height with the selected font-size. Attaching a screenshot to show the layout at the time:

![20221120_15h46m05s_grim](https://user-images.githubusercontent.com/142463/202933992-5b167d9c-cfba-4492-a53c-5c83f0ecead9.png)

**Comment by wez** [comment]
I don't think either of those two new logs have webgpu enabled; they both still mention glium in the panic, and glium is not used when webgpu is enabled.  Please double check that you had the appropriate config set!

How many windows are present when you encounter the error? I wonder if this correlates with the number of windows rather than the size of the windows?

**Comment by asolkar** [comment]
My config was missing double-quotes around WebGpu. Attaching a log with WebGpu enabled.
[wezterm.debug.log](https://github.com/wez/wezterm/files/10099099/wezterm.debug.log)

I do not see the panic message in the log anymore. Nevertheless, some clients do die once I open 17-18 windows.

**Comment by wez** [comment]
To recap, using webgpu you don't see any panics, but you do see something spontaneously quit, or do you see an attempt to spawn a new window fail?
