### ISSUE TITLE
cannot install wezterm-nightly-bin via aur

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#277]
I get the following error when running `yay -Syu wezterm-nightly-bin`.

```
install: cannot stat 'squashfs-root/usr/share/wezterm/colors/*': No such file or directory
```

`wezterm-bin` doesn't have this issue.

**Comment by wez** [comment]
Ah, this is because the colors directory no longer exists in the install (94fb5094a4d99291e0ddd7c86703e6cc64449329)
I've updated wezterm-nightly-bin; thanks for reporting!

**Comment by wez** [comment]
I've also updated `wezterm-git`.  `wezterm-bin` should automatically pick up the equivalent change when the next release is cut.

**Comment by prabirshrestha** [comment]
works. thanks for the quick fix.
