### ISSUE TITLE
Ctrl-... commands don't work with mapped keys in alternative keyboard layouts on macOS

### ISSUE THREAD

**Issue by jaredramirez** [wez/wezterm#2771]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221120-221837-51e45a47

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using an alternative keyboard layout (https://workmanlayout.org/), shortcuts in Wezterm like `ctrl-c`, `ctrl-d` do not work (where `c` and `d` are the mapped keys, not the physical one). For example, typing `ctrl-c` simply types `c`. If I switch back to the default keyboard layout (`qwerty`), wezterm works as expected.

> I know this isn't a problem with the keyboard layout itself, as in other applications using the mapped keys for shortcuts works as expected

### To Reproduce

Open wezterm, try to exit with `ctrl-d` and see wezterm type `d`

### Configuration

no config

### Expected Behavior

Wezterm should respond to `ctrl` with mapped keys

### Anything else?

In the previous stable release of Wezterm (`20220905-102802-7d4b8249`) using the same layout, `ctrl-...` shortcuts work as expected

**Comment by wez** [comment]
Can you set `debug_key_events = true` and show the logs for when you press `ctrl-c`?
Also worth noting, on macOS, in the latest release, the CTRL key is now routed via the IME, which may do things to the control key:
* https://github.com/wez/wezterm/pull/2435
* https://github.com/wez/wezterm/issues/2725
* https://github.com/wez/wezterm/issues/2630

so you may wish to try setting `use_ime = false` to see if that changes the behavior.

**Comment by wez** [comment]
I want to do something to "fix" this, so keeping this open

**Comment by devvit** [comment]
Make `forward_to_ime`  configurable even better😄.

**Comment by wez** [comment]
This should be resolved now in `main`. https://wezfurlong.org/wezterm/config/lua/config/macos_forward_to_ime_modifier_mask.html makes this configurable and the default is back to its original value.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
