### ISSUE TITLE
wezterm crashes on startup

### ISSUE THREAD

**Issue by matthias-Q** [wez/wezterm#2772]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

awesomewm

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When starting wezterm, it get the following Error message:
```
12:19:53.501  ERROR  wezterm_gui::frontend > Failed to create window: obtaining metrics for font_size=10 @ dpi 142: unable to load font idx 1!?
```

### To Reproduce

start wezterm

### Configuration

I tested it with my config and the basic config below. I get the same error:

```lua
local wezterm = require 'wezterm'
return {
  font = wezterm.font 'JetBrains Mono',
}
```

### Expected Behavior

Should not crash on startup.

### Logs

I cannot start the debug overlay in that version. In the older version it shows this line for the OpenGL Version:

wezterm version: 20220905-102802-7d4b8249
OpenGL version: NVIDIA GeForce GTX 1650/PCIe/SSE2 4.6.0 NVIDIA 520.56.06

**Comment by wez** [comment]
Please run `wezterm ls-fonts` and share the output here

**Comment by matthias-Q** [comment]
```
Primary font:
wezterm.font_with_fallback({
  -- /usr/local/share/fonts/j/JetBrains_Mono_Regular_Nerd_Font_Complete_Mono.ttf, FontConfig
  "JetBrainsMono Nerd Font Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- /usr/local/share/fonts/j/JetBrains_Mono_Italic_Nerd_Font_Complete_Mono.ttf, FontConfig
  -- Will synthesize dim
  {family="JetBrainsMono Nerd Font Mono", style="Italic"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- /usr/local/share/fonts/j/JetBrains_Mono_Regular_Nerd_Font_Complete_Mono.ttf, FontConfig
  -- Will synthesize dim
  "JetBrainsMono Nerd Font Mono",

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /usr/local/share/fonts/j/JetBrains_Mono_Bold_Nerd_Font_Complete_Mono.ttf, FontConfig
  {family="JetBrainsMono Nerd Font Mono", weight="Bold"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- /usr/local/share/fonts/j/JetBrains_Mono_Bold_Italic_Nerd_Font_Complete_Mono.ttf, FontConfig
  {family="JetBrainsMono Nerd Font Mono", weight="Bold", style="Italic"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- /usr/local/share/fonts/j/JetBrains_Mono_Italic_Nerd_Font_Complete_Mono.ttf, FontConfig
  {family="JetBrainsMono Nerd Font Mono", style="Italic"},

  -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

})

Title font:
15:56:25.884  ERROR  wezterm_gui > obtaining metrics for font_size=10 @ dpi 96: unable to load font idx 1!?; terminating

```

**Comment by wez** [comment]
From what you shared, it sounds like the title font (which defaults to `Roboto Mono`) has some kind of issue preventing it from being used.  wezterm ships with a copy of that, but it will prefer to use the one it finds on your system.

Can you try uninstalling and/or reinstalling the `Roboto Mono` font?

**Comment by matthias-Q** [comment]
I checked, and it looks like, it is not installed. In the log above, I don't see `Roboto Mono` mentioned.

**Comment by matthias-Q** [comment]
Here you go:
[font_trace.log](https://github.com/wez/wezterm/files/10071122/font_trace.log)

**Comment by wez** [comment]
Hmm, wezterm should have Roboto Mono built-in, but in your case, it hasn't found it and is getting confused.
How did you install wezterm?

**Comment by matthias-Q** [comment]
I cloned the repo, then cargo build --release and copied the binaries. Is there a install script that I am missing?


Btw: I have other, but apparently similar issues on my private machine. There, wezterm starts, but later complaints about missing fonts. Bt lets try to fix this one first... maybe it solves the other issue as well.

**Comment by wez** [comment]
Are you sure that you didn't pass in any `--feature` related arguments when you ran `cargo build --release`?

**Comment by wez** [comment]
Please run `wezterm ls-fonts --list-system | grep BuiltIn` and share the output!

**Comment by matthias-Q** [comment]
Yes, I found the issue. I have build with `--no-default-features`

Building it just with `--release` makes it run perfect. Thanks for the help.!
