### ISSUE TITLE
Shift-Space shows `;2;32~` under `tmux` on some systems

### ISSUE THREAD

**Issue by lnicola** [wez/wezterm#2774]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

While connected over SSH to a system running `tmux 1.8-4` (on CentOS 7), I noticed that pressing Shift-Space inserts `;2;32~` instead of a space. To sum up:

 - WezTerm SSH -> `tmux 1.8`: ``;2;32~``
 - WezTerm SSH -> `tmux 3.3a-2.1`: space
 - WezTerm local -> `tmux 3.3a-2.1`: space
 - GNOME Terminal SSH -> `tmux 1.8`: space
 - Alacritty SSH -> `tmux 1.8`: fails (`missing or unsuitable terminal: alacritty`)
 - Foot -> `tmux 1.8`: fails (`missing or unsuitable terminal: foot`)

Feel free to close if supporting old versions of tmux is not a priority.

### Configuration

no config

### Logs

Noting, I think

**Comment by wez** [comment]
Take a look at https://wezfurlong.org/wezterm/config/key-encoding.html to understand a bit more about keyboard encoding.  Note that shift-space is somewhat special and is more likely to highlight bugs.  I think what you're seeing may be a bug in that older version of tmux; if that is the case, I'm not going to correct for that in wezterm.

Turning on https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html can help to understand how a given key is being interpreted.

**Comment by lnicola** [comment]
Do I enable that setting, trigger the issue, then bring up the logs with Ctrl-Shift-L? Because I only see my the latter key combination in the logs:


```
17:14:58.295 INFO wezterm_gui::termwindow::keyevent > send to pane DOWN key=Shift mods=SHIFT | CTRL
17:14:58.464 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(L), modifiers: SHIFT | CTRL, phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }
17:14:58.464 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('L'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(L), modifiers: SHIFT | CTRL, phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
17:14:58.464 INFO wezterm_gui::termwindow::keyevent > Char('L') CTRL -> perform ShowDebugOverlay
```

**Comment by wez** [comment]
![image](https://user-images.githubusercontent.com/117777/203352107-2fd9426e-1409-4472-9122-dc07850019f5.png)

**Comment by lnicola** [comment]
Ah, sorry for that.

```
17:21:33.649  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
17:21:33.650  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Shift, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
17:21:33.650  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Shift mods=NONE
17:21:35.370  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(Space), modifiers: SHIFT, phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
17:21:35.370  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: SHIFT, phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
17:21:35.370  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char(' ') mods=SHIFT
17:21:35.370  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[27;2;32~", Char(' ') SHIFT
17:21:35.415  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: SHIFT, phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
17:21:35.415  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char(' ') mods=SHIFT
17:21:35.617  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Shift, modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
17:21:35.618  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Shift mods=SHIFT
```

**Comment by wez** [comment]
Sounds like `modifyOtherKeys` has been set to level 2 in the first case, but not the second case.
I think this is a tmux issue in that older version. https://github.com/tmux/tmux/search?q=modifyOtherKeys&type=issues shows that there have been a number of issues in the past.
Speaking honestly, I don't want to spend time running this down: using a newer version of tmux sounds like it will save everyone a lot of energy!

**Comment by lnicola** [comment]
Yeah, it makes sense to not spend time on this, since it works on newer versions.
