### ISSUE TITLE
add option to render the tab at the bottom

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#278]
Given that now weterm support spits and I would like to remove dependency on tmux and have an option to render the tabs at the bottom similar to tmux here. Conemu also supports rendering tabs at the bottom. 

![image](https://user-images.githubusercontent.com/287744/94347643-cfaef000-ffea-11ea-9d30-bc3aba532690.png)

Primary reason for this is I consider the bottom few lines as a command bar and usually my focus is on the top half of the screen most of the time.

This will also help when `prompt` gets implemented in the future. Here is an example of confirmation prompt when trying to kill a pane in tmux.

![image](https://user-images.githubusercontent.com/287744/94347732-857a3e80-ffeb-11ea-9b5f-ecb00e634399.png)

Here is an example when you want to rename a window in tmux (i.e. tab in wezterm). Since I barely restart my machine and have multiple projects in different tabs being able to rename of fly is helpful.

![image](https://user-images.githubusercontent.com/287744/94347760-c2decc00-ffeb-11ea-94b8-5b63cdde4127.png)

**Comment by bradparks** [comment]
any update on this? no worries if not! thanks...
