### ISSUE TITLE
wezterm ignores cursor styles of some applications

### ISSUE THREAD

**Issue by ExpandingMan** [wez/wezterm#2781]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

[`qtile`](https://github.com/qtile/qtile)

### WezTerm version

wezterm 20221122-073509-b26da030

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The rendering of the cursor ignores the variables set by my shell.  For example with fish shell I have
```fish
set -gx fish_cursor_default block
set -gx fish_cursor_insert line blink
set -gx fish_cursor_visual block
set -gx fish_cursor_replace_one underscore
```
but rather than respecting these options wezterm always renders the cursor the way I specify in `wezterm.lua`.

Oddly, wezterm *does* respect the `nvim` cursor config.  It therefore seems this is a rather obscure problem.  I have no clue how the API works for setting the cursor via fish.

### Configuration

for example
```lua
return {
    default_cursor_style = "BlinkingBar",
}
```

### Expected Behavior

On e.g. kitty, the cursor looks the way it is set in the kitty config in insert mode, but changes to a block in normal mode.

### Anything else?

Yeah, I realize this is just an obscure pain-in-the-ass.

**Comment by wez** [comment]
I suspect that fish may not think that those cursor shapes are supported.
I'd suggest checking the fish docs/folks to see how it makes that decision.

**Comment by ExpandingMan** [comment]
I'm not sure what conclusion to draw from this, but a fish person linked me [this](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_cursor.fish).

**Comment by ExpandingMan** [comment]
Yikes, see [here](https://github.com/fish-shell/fish-shell/blob/b98cee10bb37bcc33c8686d092eb8a85ff23ae3c/share/functions/fish_vi_cursor.fish#L40-L57).  This definitely looks like their problem and not yours.  I'm probably going to have to work out which variables to set to hack this.

**Comment by ExpandingMan** [comment]
Ok, this is fixable with `fish_vi_force_cursor` which probably should be the default, but in fairness to the fish devs it probably *was* the default and broke some terminals.
