### ISSUE TITLE
support `-e` command line flag as an alternative to `start`

### ISSUE THREAD

**Issue by ExpandingMan** [wez/wezterm#2782]
Admittedly `wezterm`'s CLI `wezterm start -- args` is undoubtedly better than using a flag like `-e`, however tons of linux stuff assumes that any terminal will have the `-e` flag.  Examples include `rofi`, `rifle` and whatever the hell happens when you run `*.desktop` files (which is not a behavior that's exclusive to desktop environments as other programs can try to run these).

It would therefore be really nice if in addition to the current behavior, `wezterm` supported a `-e` flag as it would greatly simplify the usage of `wezterm` as a default terminal.

**Comment by vimpostor** [comment]
Have you seen #2670? Support for `-e` is already implemented, i.e. you can use `wezterm start -e bash`.

Note that right now you still have to specify the `start` in `wezterm start`, i.e. `wezterm -e bash` does not work. Given that `wezterm` defaults to `wezterm start` it might make sense to accept just `wezterm -e command` as well. Is this what you want or is #2670 enough for you?

**Comment by ExpandingMan** [comment]
Thanks, I was not aware of that.  Indeed, I don't feel that really solves the problem, even `wezterm start -e` will require special handling in many contexts.  It would make things far simpler to accept `wezterm -e`.

**Comment by vimpostor** [comment]
> even `wezterm start -e` will require special handling in many 
> contexts.  

If your third-party application parses the desktop file correctly, it 
will work automatically, so unless they are buggy, usually no special 
handling is required.

I don't have any strong opinion against adding support for `wezterm -e` 
though.

So if @wez doesn't mind it either, I might send in a patch later.

**Comment by ExpandingMan** [comment]
Yes, `wezterm start -e` does *mostly* fix this issue, but, at least for me personally, it's still kind of annoying.  If, for example, you expect to just set the terminal in some environment variable, `wezterm` now needs special handling compared to every other terminal.  This is because, though simply setting `wezterm start` works fine to directly launch terminal applications, for wezterm (and only for wezterm) the command for starting a terminal application is *different* than starting the terminal itself.

**Comment by wez** [comment]
@vimpostor if you can find a way to treat `-e` as an alias for `start` in clap, that feels conceptually clean.
I have my doubts that it will be that clean and simple though!

**Comment by Abdiramen** [comment]
@wez if alias is an acceptable solution to this problem is there any issue with just slapping `#[command(alias = "-e")]` above: https://github.com/wez/wezterm/blob/1fad25e926f186e33dc547cc6060a901bfaa1311/wezterm-gui-subcommands/src/lib.rs#L149

**Comment by wez** [comment]
I don't know; I haven't tried it, and it's not high on my list of things to try. If it works, then that would be good. I have my doubts about it, as argument parsing typically uses `-` to indicate an argument rather than a subcommand.

**Comment by Abdiramen** [comment]
I can try it out! If it works I'll send out a PR.

**Comment by ExpandingMan** [comment]
Thanks all!
