### ISSUE TITLE
Copy on select does not work on Wayland

### ISSUE THREAD

**Issue by cole-h** [wez/wezterm#2786]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

sway

### WezTerm version

wezterm 20221122-154621-68c754b1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes (updated version above to match)

### Describe the bug

Selecting text does not copy to the clipboard on Wayland.

~~(I did not try the latest nightly because I wanted to file this issue before I left for class -- I'll try it and report back afterwards.)~~

### To Reproduce

1. Run `wezterm -n`
2. `echo hello_there_wezterm_here_is_a_long_line_I_would_like_to_copy`
3. Double-click to select the entire "word" echoed above
4. Attempt to paste it into e.g. Firefox, or another wezterm tab.
5. Notice that nothing was pasted.

### Configuration

no config

### Expected Behavior

I would expect to be able to paste whatever I just selected, even if the selection gets cleared immediately.

### Logs

No logs.

### Anything else?

There was a similar issue at https://github.com/wez/wezterm/issues/2588, but it was for X11, and the suggested binds had to effect for me.

**Comment by Funami580** [comment]
Do you paste with mouse middle-click?

**Comment by Funami580** [comment]
Selecting only copies to the primary selection. Ctrl+V pastes the regular selection. So either use middle-click or change the mouse bindings as in https://github.com/wez/wezterm/issues/2588.

**Comment by TheTrio** [comment]
Huh I remember that not working before but it works now. Yay. 

Thanks!

**Comment by cole-h** [comment]
Yeah, same here... wez even suggested I try that on Matrix, I did, and it still didn't work at that time :thinking: 

Oh well, it seems to work now...? (Running `wezterm 20221130-111338-8d8d7d3f`)

Maybe it was thanks to 9d109337e76c31b24c9486649d017bbc5a810262 :shrug:
