### ISSUE TITLE
Confirmation before quitting

### ISSUE THREAD

**Issue by JoyceBabu** [wez/wezterm#280]
**Is your feature request related to a problem? Please describe.**
I have configured wezterm to quit on `CMD+q`. But I pressed the combination by mistake, when trying to press `CMD+1` for activating the first tab, and the window got closed immediately.

**Describe the solution you'd like**
Display a confirmation dialog before quitting.

iTerm allows configuring a list of programs (shell and tmux by default). If another program is running, then iTerm asks for user confirmation before quitting.

**Describe alternatives you've considered**
Another solution is to change the shortcut to a key combination that cannot be pressed by accident. But it is convenient to configure it as per the convention followed by other applications.

**Comment by bew** [comment]
@wez this is done (in https://github.com/wez/wezterm/commit/b2911ccc41134b13f2d5722e96731891f3f5bb4e) and can be closed?

**Comment by wez** [comment]
We don't have an overall confirm to quit the app option, or one for closing a window, so this isn't quite done.

**Comment by JoyceBabu** [comment]
@bew As mentioned above, the feature request was for confirming the app exit action.

_There was a mistake in the original post. I had configured `CMD-q`, not `CMD-t`, to quit wezterm._

**Comment by wez** [comment]
I added window close confirmation to master (in 5787bdff530ec5cef57dafdbb1d4f0870c37fbc1); that'll show up in the nightly downloads in the next hour or so.

I'm on Linux at the moment so I didn't have an opportunity to test what happens with `CMD-q`; it's possible that that will trigger normal window closing and thus the new confirmation logic.  I'll try this out when I open up my mac a bit later today, but if you beat me to it, please let me know if that's sufficient to call this issue done!

**Comment by JoyceBabu** [comment]
@wez Pressing `⌘+q` displayed the confirmation prompt. But selecting yes closes only the current window, not the entire app.
