### ISSUE TITLE
Wezterm freezes after killing fcitx5

### ISSUE THREAD

**Issue by sudhanv09** [wez/wezterm#2819]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

AwesomeWM

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Wezterm freezes after killing fcitx5. I can't input anything else after the fcitx5 is killed with Ctrl+c. The cursor blinks but cant input anything or go to newline.  I have to pkill -9 wezterm-gui to restart wezterm.

![fcitx5](https://user-images.githubusercontent.com/46046879/205011925-17480f9d-7edd-44e2-bea2-0bf0342331e8.png)

### To Reproduce

1. Run fctitx5
2. Kill by pressing Ctrl+c

### Configuration

```lua
 -- WezTerm
 -- https://wezfurlong.org/wezterm/

 local wezterm = require 'wezterm'
 local act = wezterm.action

 wezterm.on("update-right-status", function(window, pane)
  window:set_right_status(window:active_workspace())
 end)

 return {
  -- Smart tab bar [distraction-free mode]
  hide_tab_bar_if_only_one_tab = true,

  -- Disable updates
   check_for_updates = false,
   show_update_window = false,

  color_scheme = 'Gruvbox Dark',

  window_background_opacity = 0.99,

  font = wezterm.font('Fantasque Sans Mono'),
  font_size = 13.0,

  harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' },

  default_cursor_style = 'BlinkingBar',

  -- Enable CSI u mode
  enable_csi_u_key_encoding = true,

  -- exit
  exit_behavior = "Close";


  leader = { key = "a", mods = "CTRL", timeout_milliseconds = 1000 },
  -- Keybindings
  keys = {

    -- Split Panes
    { key = "w", mods = "LEADER", action = wezterm.action.SplitPane { direction = "Right" } },
    { key = "v", mods = "LEADER", action = wezterm.action.SplitVertical { domain = "CurrentPaneDomain" } },

    -- Workspaces

    { key = "i", mods = "LEADER", action = act.SwitchToWorkspace },
    { key = "r", mods = "ALT", action = act.ShowLauncherArgs { flags = "FUZZY|WORKSPACES" } },
    { key = "l", mods = "LEADER", action = act.SwitchWorkspaceRelative(1) },
    { key = "h", mods = "LEADER", action = act.SwitchWorkspaceRelative(-1) },

    -- Custom Workspaces
    { key = "p", mods = "LEADER", action = wezterm.action { SwitchToWorkspace = { name = "vim" } } },
    { key = "m", mods = "LEADER", action = wezterm.action { SwitchToWorkspace = { name = "mpv" } } },

  }
};
```

### Expected Behavior

Take input after killing fcitx5

**Comment by wez** [comment]
This is outside of wezterm's direct control. Communication with the IME is performed by https://github.com/fcitx/xcb-imdkit, which is wrapped up by https://github.com/h-m-h/xcb-imdkit-rs

Those libraries need to provide a way to detect and disable the IME if the underlying channel to the IME is broken.

Could you open an issue at https://github.com/fcitx/xcb-imdkit/issues so that we can discuss this with the fcitx folks?

**Comment by wez** [comment]
You might be able to workaround a dead IME by updating the wezterm configuration to set `use_ime = false` and saving it.

**Comment by sudhanv09** [comment]
That worked. Thanks

**Comment by wengxt** [comment]
@wez xcb-imdkit does not freeze like libX11. I think it's xcb-imdkit-rs bug that doesn't handle the disconnection of im server.

**Comment by wengxt** [comment]
The fix looks good to me. Did a quick test on my side and it's working now.

**Comment by wez** [comment]
@wengxt thanks for suggesting the fix and verifying that it works!

**Comment by sudhanv09** [comment]
@wez @wengxt thanks for all your work. I can confirm that it works as intended now.

**Comment by wez** [comment]
Great!
