### ISSUE TITLE
Quick select mode for hyperlink

### ISSUE THREAD

**Issue by CloneSnows** [wez/wezterm#2822]
**Is your feature request related to a problem? Please describe.**
My current workflow consist of using keyboard and find it little bit uncomfortable and slow to use mouse to hover over a hyperlink in terminal.

**Describe the solution you'd like**
A possible solution is to implement a quick select mode but for hyperlinks.

Although I am currently working on was to implement this feature into the terminal itself I would like some to hear some people opinion and some guidance.

**Comment by gegoune** [comment]
You can use custom map such as

```lua
    action = act.QuickSelectArgs {
      label = 'open url',
      patterns = { 'https?://\\S+' },
      action = wezterm.action_callback(function(window, pane)
        local url = window:get_selection_text_for_pane(pane)
        wezterm.open_with(url)
      end),
    },
```

**Comment by CloneSnows** [comment]
Thank you so much i didn't realise you could do that
