### ISSUE TITLE
Autoshift not working in Linux X11

### ISSUE THREAD

**Issue by aulin** [wez/wezterm#2829]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME Shell. Due to some issues with Wayland in Ubuntu 22.04, I've moved back to X11 and am using the defaults for it.

### WezTerm version

20221130-111338-8d8d7d3f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I use a mechanical keyboard and have come to rely on a lot of special settings to work more efficiently in my day to day work.

This issue relates specifically to a feature called auto-shift. Basically, if I tap a letter key, one of two things can happen:
- I release it quickly, and get the lower case letter
- I hold the key slightly longer before releasing it, and get the upper case letter

In Alacritty on the same Ubuntu laptop, as well as in the Windows build of Wezterm (`20221119-145034-49b9839f`), this functionality works as intended. In the Linux version (I installed the deb package nightly build) it doesn't however. It always outputs a lower case letter.

If I run `xev` I see the correct KeyPress events, first for `L_SHIFT` and then `A`. Then I see the correct KeyRelease events for `A` and `L_SHIFT`. The same is output if I actually press and hold the left shift button to type the upper case A.

The one difference I can see is in the timing.
- With auto-shift, the time between keypresses for shift and letter is always only 1 ms, and the same is true for the KeyRelease events, which are automatically fired 1 ms after the second KeyPress event. The KeyRelease events happen while still holding the letter key, and no event is fired when physically releasing it. This means the whole auto-shift sequence always lasts 3 ms.
- When using the physical shift button, the time was 389 ms between presses, and 33 ms between releases.

Since it works in the Windows build, I suspect this has to do with X11, but perhaps it could be mitigated by allowing some configuration as a workaround?

### To Reproduce

I guess you either have to use a keyboard with this feature or simulate the inputs by giving the keycodes for left shift and then a letter, with a very short delay (1 ms).

### Configuration

no config

### Expected Behavior

Pressing a letter key slightly longer than usual should produce an upper case letter.

### Logs

No log output

**Comment by wez** [comment]
Try setting `use_ime = false` and see if that helps? 
https://wezfurlong.org/wezterm/config/lua/config/use_ime.html

**Comment by aulin** [comment]
Thank you! This fixed the issue. I see from the manual that this setting defaults to `false` except for in X11, which explains why it worked in Windows.
