### ISSUE TITLE
Index out of bound while scrolling (cannot reproduce)

### ISSUE THREAD

**Issue by bew** [wez/wezterm#283]
## Environment (please complete the following information):

- OS: Linxu X11
- Version: 20200909-002054-4c9af461

## To Reproduce

Well, cannot reproduce for now, I don't think this is an issue with the config though.

I had a small window, with ~5-6 lines of height (but ~80 width), with a non-empty scrollback (maybe 200-300 lines, but not sure).
I tried to do a mouse selection of a few lines, quickly hit the top of my 5-6 visible lines and it scrolled verry fast for a second (don't know if it has hit the top of my scrollback), then crashed, with:
```
thread 'main' panicked at 'index out of bounds: the len is 9 but the index is 24', /home/runner/work/wezterm/wezterm/termwiz/src/surface/line.rs:262:29
```

**Comment by bew** [comment]
Is it a wild guess? Or did you manage to reproduce something?

**Comment by wez** [comment]
I didn't reproduce it, but from inspection, the `click_col` parameter can be a position to the right of a line and that wasn't constrained to the line width.  The most likely way to trigger this would be to resize to a narrow width, output some text, then make the terminal wider, and then try a double click drag selection.

The included unit test verifies that this function now safely checks the bound for the wrapped line case and returns the correct range.

**Comment by bew** [comment]
>  The most likely way to trigger this would be to resize to a narrow width, output some text, then make the terminal wider, and then try a double click drag selection.

This sounds like the kind of things I did with the terminal that crashed!
Thanks for tracking this one down, I hope I won't get a crash like this anymore
