### ISSUE TITLE
Wezterm crashes immediately when starting from launchpad on Mac

### ISSUE THREAD

**Issue by ZodiacWind** [wez/wezterm#2839]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I use nushell and wezterm on my Mac. 

Nushell is installed in `/usr/local/bin`, which is added to `$PATH` in `/etc/paths`. And is set as default shell for wezterm, but **not** for the system.

When I start wezterm from **launchpad**, it crashes immediately, and the reason I guess is that `nu` is not found. 
When I start weaterm from **terminal**， evertyhing works well.
If the full path of nu, i.e. `/usr/local/bin/nu` is used, evertyhin works well.

Is there is bug here and how can I fix it?

### Configuration

return {
    -- default program
    default_prog = {"nu"}
}

### Expected Behavior

Wezterm starts from launchpad.

**Comment by wez** [comment]
Please attach the log file from the session you started from launchpad.
You can find logs files in `~/.local/share/wezterm` on macOS; there should be a file named `wezterm-gui-log-PID.txt` for the session that started and exited.

My guess at what is happening is that launchpad.app doesn't set up the path to include `/usr/local/bin`, so wezterm can't find `nu`.  In that case, the simple fix is is to use `default_prog = {'/usr/local/bin/nu'}`.
