### ISSUE TITLE
I've got ERROR --> wezterm_gui > XOpenDisplay failed to open a display. Check the $DISPLAY env var; terminating

### ISSUE THREAD

**Issue by PorcoRosso85** [wez/wezterm#2850]
![image](https://user-images.githubusercontent.com/40359643/206627609-95a0807b-d602-42e2-a706-f05de1a06035.png)
and
My env var of $DISPAY is blank
Is there what I have to do ?
OR
Can't I use wezterm on my env?

**Env**
Windows10home
WSL2
ubuntu22.04

**Reference I followed**
https://wezfurlong.org/wezterm/install/linux.html

**Command I used to install**
```bash
wezterm_install() {
  app="WezTerm-20221119-145034-49b9839f-Ubuntu18.04.AppImage"
  command="wezterm"
  path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
  echo $path
  if [ -f $path/$app ]; then
    rm -r $path/$app
    echo $app" removed"
  fi
  if [ -f /usr/bin/$command ]; then
	  rm /usr/bin/$command
	  echo "/usr/bin/"$command" removed"
  fi
  curl -o $path/$app -LO "https://github.com/wez/wezterm/releases/download/20221119-145034-49b9839f/"$app
  chmod +x $path/$app
  ln -s $path/$app /usr/bin/$command
}
wezterm_install

```

P.S.
I've tried using windows native one ( setup.exe, and potable.zip archive),
but they also did not show my any terminal on GUI.
Excuse me my basically question.

**Comment by wez** [comment]
You either need to install an X server inside WSL to use the linux version of wezterm in WSL, or install the Windows version of wezterm outside WSL.  Using the Windows version is recommended for the best performance on Windows.

**Comment by PorcoRosso85** [comment]
Really appreciate it.

Will any X server app be accepted?
I've installed both of 'setup.exe' and portable app and then, also tried
vcxserv ( https://sourceforge.net/projects/vcxsrv/files/latest/download ).
Run server, then run app.
But app did not show itself.

I know this is question about X server itself, but I think it is ok for me
to ask here because of dependencies.
Should I place it as another issue or not?

[image: image.png]
[image: image.png]
[image: image.png]

**Comment by gimbles** [comment]
This is really odd. I am getting this even while *not* in WSL. Currently on Fedora 38.

**Comment by wez** [comment]
@gimbles please open an issue of your own so that we can dig into it together more effectively
