### ISSUE TITLE
`tmate` does not work on wezterm

### ISSUE THREAD

**Issue by nahuakang** [wez/wezterm#2859]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Running `tmate` works on my other terminal emulators but not on wezterm:

```sh
> tmate
lost server
```

### To Reproduce

- Install `tmate`
- Run `tmate` in the terminal

### Configuration

local wezterm = require 'wezterm'

return {
    color_scheme = "Gruvbox dark, medium (base16)",

    font = wezterm.font_with_fallback{
        'Comic Code Ligatures',
        'FiraCode Nerd Font',
        'JetBrains Mono',
    },

    initial_cols=160,
    initial_rows=48,
    
    leader = { key = 'a', mods = 'CTRL', timeout_milliseconds = 1000 },
    keys = {
        { key = 'a', mods = 'LEADER|CTRL',  action = wezterm.action.SendString '\x01' },
        { key = '|', mods = 'LEADER|SHIFT', action = wezterm.action.SplitHorizontal {domain = 'CurrentPaneDomain'} },
        { key = '-', mods = 'LEADER',       action = wezterm.action.SplitVertical {domain = 'CurrentPaneDomain'} },
        { key = 'z', mods = 'LEADER',       action = "TogglePaneZoomState" },
        { key = "t", mods = "LEADER",       action=wezterm.action{SpawnTab="CurrentPaneDomain"} },
        { key = "h", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Left"} },
        { key = "j", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Down"} },
        { key = "k", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Up"} },
        { key = "l", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Right"} },
        { key = "H", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Left", 5}} },
        { key = "J", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Down", 5}} },
        { key = "K", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Up", 5}} },
        { key = "L", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Right", 5}} },
        { key = "1", mods = "ALT",       action=wezterm.action{ActivateTab=0} },
        { key = "2", mods = "ALT",       action=wezterm.action{ActivateTab=1} },
        { key = "3", mods = "ALT",       action=wezterm.action{ActivateTab=2} },
        { key = "4", mods = "ALT",       action=wezterm.action{ActivateTab=3} },
        { key = "5", mods = "ALT",       action=wezterm.action{ActivateTab=4} },
        { key = "6", mods = "ALT",       action=wezterm.action{ActivateTab=5} },
        { key = "7", mods = "ALT",       action=wezterm.action{ActivateTab=6} },
        { key = "8", mods = "ALT",       action=wezterm.action{ActivateTab=7} },
        { key = "9", mods = "ALT",       action=wezterm.action{ActivateTab=8} },
    },

    enable_scroll_bar = true,
    scrollback_lines = 3500,

    warn_about_missing_glyphs=false,
}

### Expected Behavior

Run `tmate` spins up a `tmux` with relevant `tmate` information.

### Logs

Debug Overlay
wezterm version: 20221119-145034-49b9839f
OpenGL version: AMD RENOIR (DRM 3.42.0, 5.15.0-56-generic, LLVM 12.0.1) 4.6 (Compatibility Profile) Mesa 21.3.9 (git-78c96ae5b6)
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
14:21:03.070 ERROR window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
14:21:03.078 ERROR window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
14:21:03.086 ERROR window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
14:21:03.096 ERROR window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
14:21:03.173 ERROR window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
14:21:03.279 ERROR window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found

**Comment by nahuakang** [comment]
`tmate` is a fork of `tmux` for instant sharing of a shell session: https://tmate.io/. I haven't reported it to `tmate` because it works on Ubuntu's default terminal emulator and another terminal emulator. Would this be possibly an issue from `tmate`'s side? :)

**Comment by nahuakang** [comment]
Sure. I'll ask them about it. I can also close this and open it again in case of any update. Thanks for helping :)

**Comment by goek-han** [comment]
tmate 2.4.0 works on X11 with wezterm for me.

**Comment by nahuakang** [comment]
I'm using Wayland so maybe that's a reason? :thinking:

**Comment by Mo8it** [comment]
I can confirm "Lost server". I am also on Wayland.

But I use Zellij. If you launch tmate inside Zellij, everything works fine. Weird :O But a workaround for now.

**Comment by nahuakang** [comment]
I can confirm that `tmate` works with `zellij`. This is a fine workaround for me :) No response from the folks at `tmate` though.

**Comment by wez** [comment]
Until we have information from tmate about why it exits, I'm considering this issue to be primarily a tmate issue with no direct action for me to take for now.
