### ISSUE TITLE
Possible error in `window:spawn_tab`

### ISSUE THREAD

**Issue by kruger** [wez/wezterm#2860]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221212-091509-91ea1095

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am trying the multiplexing workspace feature.   I would like multiple tabs, so I tried the configuration shown below based on the documentation.   I am developing this in a separate lua file called `wezterm-multitab.lua` and then starting from the command-line with `wezterm --config-file $HOME/.config/wezter/wezterm-multitab.lua`.

When I start it up, I get this:
```
✦  ➜ 10:14:40.921  ERROR  wezterm_gui > while processing gui-startup event: callback error
stack traceback:
        [C]: in local 'poll'
        [string "?"]:5: in field 'spawn_tab'
        [string "/Users/kruger/.config/wezterm/wezterm-multita..."]:33: in function <[string "/Users/kruger/.config/wezterm/wezterm-multita..."]:7>
caused by: error converting Lua table to userdata
```

I get the first tab and two panes setup correctly, including the correct cwd.   The second tab does not appear.

I do not know Lua well so am aware that I might be missing something, but if nothing else nvim with LSP isn't showing an error.

If it is not a bug per se, then I think it is a bug in the documentation since my configuration comes from this page: https://wezfurlong.org/wezterm/config/lua/mux-window/spawn_tab.html

### To Reproduce

If you just change the directories in my config below or remove them, then would be reproducible.  The directories are left in to demonstrate my goal.

### Configuration

```
wezterm.on('gui-startup', function(cmd)
  -- allow `wezterm start -- something` to affect what we spawn
  -- in our initial window
  local args = {}
  if cmd then
    args = cmd.args
  end
      local project_dir = wezterm.home_dir .. '/efitairoot/efitall'
      local efitdb_dir = project_dir .. '/efitai_database'
      -- Main tab
      local efittab, efit_pane, efit_window = mux.spawn_window {
        workspace = 'efitai',
        cwd = project_dir .. '/efit',
      }
        -- Main tab, second pane is for building efit
        local build_pane = efit_pane:split {
            direction = 'Right',
            size = 0.3,
            cwd = project_dir .. '/efit/build',
        }
      -- Second tab is for efitaidb (not sure why spawn_tab returns window)
      local edb_tab, edb_pane, edb_window = efit_window.spawn_tab {}
end)
```

### Expected Behavior

To launch with a second tab and no error.

### Logs

Debug Overlay
wezterm version: 20221119-145034-49b9839f
OpenGL version: Intel(R) Iris(TM) Plus Graphics OpenGL Engine 4.1 INTEL-20.2.44
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

**Comment by wez** [comment]
I think you want `efit_window:spawn_tab {}` (`:` rather than `.`), so that you are making a method call.

`efit_window.spawn {}` is equivalent to `efit_window.spawn({})`, which passes a single table as the first parameter.
However, since this is an object and we want a method call, that `spawn` method requires the window to be passed as the first parameter, which is why there is an error about trying to convert a table value (the `{}`) where we expected a userdata value (the window itself).

We need to use the `:` operator to do that:

`efit_window:spawn_tab {}` is equivalent to `efit_window.spawn_tab(efit_window, {})`

**Comment by kruger** [comment]
Thank you!   I feel that I should have caught that, but I learned  a bit of Lua from our comment.  Thanks.
