### ISSUE TITLE
When using rectangle on mac with window decorations NONE it stops being able to be tiled

### ISSUE THREAD

**Issue by itstheandre** [wez/wezterm#2866]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

Rectangle App on Mac

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Whenever I remove window_decorations, i lose the ability to tile the app. if i turn it back on , i can tile it and maximize and move it around.

### To Reproduce

```sh
brew install --cask rectangle wezterm
```
open rectangle and set some shortcut for maximization / tiling the apps.

edit `$XDG_CONFIG_HOME/wezterm/wezterm.lua`

window_decorations = "NONE"

try to move app. it shouldnt work

### Configuration

```lua
return {
    window_decorations = "NONE",
}

```

### Expected Behavior

i assume it should work the same way as if the window_decorations was allowed

**Comment by ylorn** [comment]
Not sure about Rectangle, I am using [swish](https://highlyopinionated.co/swish/) for window management, and the WezTerm works with it with following:

```diff
return {
-    window_decorations = "NONE",
+    window_decorations = "RESIZE",
}
```

**Comment by itstheandre** [comment]
that was it! @ylorn , thanks
