### ISSUE TITLE
Starship bash prompt is not displayed only for the first prompt after spawning new wezterm client

### ISSUE THREAD

**Issue by silaswaxter** [wez/wezterm#2870]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

20221212-091509-91ea1095

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When a new wezterm window, pane, or tab is created, the default bash prompt is shown instead of the [starship](https://starship.rs/) bash prompt. Subsequent prompts use the starship prompt as expected. I think its an issue with wezterm because kitty does not have this issue.

### To Reproduce

Use my attached bashrc. Install starship and use its default configuration. Finally, spawn a new window of wezterm.

### Configuration

No wezterm.lua config

I truncated my `.bashrc` to only contain the following.
```
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Use starship bash prompt if starship is installed
[[ -x $(command -v starship) ]] && eval "$(starship init bash)"
```

**Comment by silaswaxter** [comment]
Okay, I captured and attached a terminal recording. This capability is super cool.

[wezterm-recording-BOqBzK.cast.txt](https://github.com/wez/wezterm/files/10262242/wezterm-recording-BOqBzK.cast.txt)

**Comment by aptinio** [comment]
@silaswaxter, I had a similar issue and it went away after I set the `default_prog`:

https://wezfurlong.org/wezterm/config/launch.html#changing-the-default-program

**Comment by aptinio** [comment]
@wez, what's weird is that both `$SHELL` and the passwd database are set to the same shell I set as the `default_prog`.

**Comment by wez** [comment]
The default behavior in wezterm is to spawn a login shell, and that can influence which dotfiles are read on startup.
See: https://wezfurlong.org/wezterm/config/launch.html#on-posix-systems
You could try explicitly launching eg: `bash -l` and comparing the behavior to just `bash` in any terminal.

**Comment by aptinio** [comment]
@wez, that was it! Setting `default_prog = { "/bin/bash", "-l" }` brought back the behavior @silaswaxter and I were seeing.

I'll figure out if I should change my dotfiles or if I should use a non-login shell. Thanks for pointing that out :relaxed:

**Comment by wez** [comment]
FWIW, the rationale behind starting a login shell by default is summarized well here in this question/answer that relates to tmux. The same logic applies to wezterm which has similar multiplexing and headless client/server capabilities and concerns:

* https://superuser.com/a/970847/45480

This answer talks a bit more about the differences between a login and regular interactive shell:

* https://unix.stackexchange.com/a/46856/123914

IMO, if something that you use in a regular interactive shell doesn't work right when spawned as a login shell, it is *probably* an indication that something is buggy in the dotfiles of the user.  There are some nuances to shell startup that *usually* don't matter in todays linux-ised world that can occasionally be surprising to folks that have never had a fully-grey-bearded-unix-hacker to help shepherd them through setting things up 100% correctly!
