### ISSUE TITLE
MacOS: WezTerm cannot open files in the “Terminal shell script” format.

### ISSUE THREAD

**Issue by aivanise** [wez/wezterm#2871]
Hi,

I want to be able to associate .command shell scripts in MAcOS to be opened in WezTerm. iTerm, kitty  and Teminal can do it. My specific  use case is that i would like WezTerm to open a linux terminal from a multipass menu, like described here: https://multipass.run/docs/changing-terminal

if I do that now, I get a modal saying The document “aa.command” could not be opened. WezTerm cannot open files in the “Terminal shell script” format.

here is a similar issue for kitty: https://github.com/kovidgoyal/kitty/issues/3366

Thank you for considering

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by aivanise** [comment]
ok, partial success :)

I can assosicate .command files (i.e. shell scripts) and double clicking in Finder will open and run them in wezterm, but multipass shell menu option still does not work, i.e. it opens wezterm if it is not already open, but if it is, it opens a new terminal window for a millisecond and closes it immediately.

Any idea how to debug this further? Also an option to open in a tab instead of a new window would be nice.

**Comment by aivanise** [comment]
now I see

Process "/bin/sh -c /private/var/folders/78/506z78g92095wxb42r6p80c40000gn/T/multipass-gui.XjhVIJ.command" in domain "local" didn't exit cleanly
Exited with code 127.

if I run this in an already open wezterm window, it runs correctly. 

the command file is very simple
 
~ > cat /private/var/folders/78/506z78g92095wxb42r6p80c40000gn/T/multipass-gui.WLwXgX.command
clear
multipass shell primary


and the problem is most probably that multipass is in /usr/local/bin but the path when opening .command files is set to 

PATH=/usr/bin:/bin:/usr/sbin:/sbin

I've tried adding

 set_environment_variables = {
      PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
  },

to the config, and now it works, so all good.

Which makes me wonder, I have tried opening a test .command from Terminal and it shows the same default path, but it works somehow when called from the menu bar widget, how?

**Comment by wez** [comment]
Interesting. I noticed that Terminal.app runs a shell, and then sends a command line like `/private/var/folders/78/506z78g92095wxb42r6p80c40000gn/T/multipass-gui.XjhVIJ.command ; exit` to its stdin.  I suppose that is to persuade it to run all your rc files and setup the environment fully first.
I'll play around with this.

**Comment by wez** [comment]
I pushed a commit to use a similar technique as Terminal.app; it'll take about an hour to build out.
Could you try it? It should allow you to remove the `set_environment_variables` workaround.

**Comment by aivanise** [comment]
yeah, I can confirm that wezterm 20221220-083007-eb8dfd32 works without anything special in the PATH or config in general

thank you very much!
