### ISSUE TITLE
Poor perf when using WezTerm via Windows Remote Desktop Connection

### ISSUE THREAD

**Issue by tamlok** [wez/wezterm#2876]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Running on local desktop, open NeoVim and edit a large file. It works fine when moving the cursor up and down quickly and continuously.

If I use a Remote Desktop Connection to connect to another Windows PC and use WezTerm on that PC, now the perf looks poor when I move the cursor up and down. I can feel obvious cursor dragging.

### To Reproduce

Use Windows built-in remote desktop client to remote desktop to another Windows PC and use NeoVim to edit a large test file and then move the cursor up and down.

### Configuration

no config

### Expected Behavior

The perf should be the same as that on local host.

**Comment by wez** [comment]
When an RDP session is detected, wezterm uses CPU rather than GPU rendering to work around opengl issues with RDP.  See:
* https://github.com/wez/wezterm/issues/265

It's possible that the new WebGPU based frontend resolves this. Please take a look at:

* https://github.com/wez/wezterm/issues/2756

for information on trying that out.

**Comment by tamlok** [comment]
Thanks! Will try that out. I can see that Windows Terminal does not have this perf issue. Can we learn something from it?

**Comment by tamlok** [comment]
After setting the webgpu options, it still sucks.

```
Debug Overlay
wezterm version: 20221119-145034-49b9839f
OpenGL version: llvmpipe (LLVM 8.0, 256 bits) 3.1 Mesa 20.1.8
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
18:12:50.233 WARN window::os::windows::wgl > failed to created extended OpenGL context (ChoosePixelFormatARB returned 0 formats), fall back to basic
> wezterm.gui.enumerate_gpus()
[
    {
        "backend": "Vulkan",
        "device": 7350,
        "device_type": "DiscreteGpu",
        "driver": "NVIDIA",
        "driver_info": "451.48",
        "name": "Quadro P620",
        "vendor": 4318,
    },
    {
        "backend": "Dx12",
        "device": 7350,
        "device_type": "DiscreteGpu",
        "name": "NVIDIA Quadro P620",
        "vendor": 4318,
    },
    {
        "backend": "Dx12",
        "device": 140,
        "device_type": "Cpu",
        "name": "Microsoft Basic Render Driver",
        "vendor": 5140,
    },
    {
        "backend": "Dx12",
        "device": 7350,
        "device_type": "DiscreteGpu",
        "name": "NVIDIA Quadro P620",
        "vendor": 4318,
    },
]
```

**Comment by wez** [comment]
You need to install a newer version of wezterm to try webgpu

**Comment by tamlok** [comment]
Yep! After installing the latest nightly build of WezTerm, it works fine and looks pretty good on perf. Thank you! Can't even breathe without WezTerm on Windows!
