### ISSUE TITLE
Add `ANY` mod choice to effectively ignore mods

### ISSUE THREAD

**Issue by bew** [wez/wezterm#288]
**Is your feature request related to a problem? Please describe.**
When writing key/mouse bindings, I would like to bind something regardless of the current modifiers.

I want this because sometimes I go too fast, and I didn't release some modifiers before doing an action.
Or I simply want it to work while I'm doing something else that requires a modifier, and don't want to release it just to do an action.

**Describe the solution you'd like**
Add a `ANY` modifier, that would match any pressed modifiers, effectively ignore the modifiers for this binding.

**Describe alternatives you've considered**
The current workaround is to define the same binding multiple times for all the modifiers to "ignore". But even if it's easy to do with a little Lua function, it would be simpler to have this `ANY` modifier.

For example I have this in my config:
```lua
-- Clipboard / PrimarySelection paste
-- Alt-Middle click pastes from the clipboard selection
table.insert(mouse_bindings, {
  mods="ALT",
  event={Down={streak=1, button="Middle"}},
  action="Paste",
})
-- Middle click pastes from the primary selection (for any other mods).
-- Wezterm wants an exact match so we must register the bind for all the mods to 'ignore'
local bind_middle_to_primary = {
  event={Down={streak=1, button="Middle"}},
  action="PastePrimarySelection",
  mods = "invalid", -- to ensure this bind is not used directly
}
table.insert(mouse_bindings, bind_with_mods("NONE", bind_middle_to_primary))
table.insert(mouse_bindings, bind_with_mods("CTRL", bind_middle_to_primary))
table.insert(mouse_bindings, bind_with_mods("SHIFT", bind_middle_to_primary))
-- make it work even when SUPER is pressed
table.insert(mouse_bindings, bind_with_mods("SUPER", bind_middle_to_primary))
```
It would be simpler to write it like:
```lua
-- Clipboard / PrimarySelection paste
-- Alt-Middle click pastes from the clipboard selection
table.insert(mouse_bindings, {
  mods="ALT",
  event={Down={streak=1, button="Middle"}},
  action="Paste",
})
-- Middle click pastes from the primary selection (for any other mods).
table.insert(mouse_bindings, {
  mods="ANY",
  event={Down={streak=1, button="Middle"}},
  action="PastePrimarySelection",
})
```

**Comment by wez** [comment]
What do you think about wezterm providing a couple of helper functions to let you do:

```lua
local wezterm = require 'wezterm';
local mouse_bindings = {}
wezterm.permute_any_or_no_mods(mouse_bindings, {
  event={Down={streak=1, button="Middle"}},
  action="PastePrimarySelection"
})
```

`permute_any_or_no_mods` (suggestions on better naming are always welcome!) would produce all combinations of modifier mask bits, including NONE, and append it to the target table.

`permute_any_mods` would produce all combinations of modifier mask bits except NONE and append it to the target table.

**Comment by bew** [comment]
That's a good idea! And I completely forgot about permutations, good call!

I have a question though:
Could we make it so that these helpers does not insert to an existing table, but instead return a new table? 
And continuing on this thought, can the main configs `mouse` & `keys` tables handle non-flat list of key/mouse assignments? 

In other words, make this work:
```lua
local wezterm = require 'wezterm'
return {
  mouse_bindings = {
    {
      mods="ALT",
      event={Down={streak=1, button="Middle"}},
      action="Paste",
    },
    wezterm.permute_any_or_no_mods({
      event={Down={streak=1, button="Middle"}},
      action="PastePrimarySelection"
    })
  }
}
```

**Comment by wez** [comment]
I think the builtin lua `unpack` function will let you do this:

```lua
local wezterm = require 'wezterm'
return {
  mouse_bindings = {
    {
      mods="ALT",
      event={Down={streak=1, button="Middle"}},
      action="Paste",
    },
    unpack(wezterm.permute_any_or_no_mods({
      event={Down={streak=1, button="Middle"}},
      action="PastePrimarySelection"
    }))
  }
}
```

**Comment by bew** [comment]
Nice idea, but it doesn't actually work, only the first element of the unpack is taken

**Comment by wez** [comment]
`table.unpack` does appear to do the right thing when used inside a table initializer; commit incoming!

**Comment by wez** [comment]
Docs at: https://wezfurlong.org/wezterm/config/lua/wezterm/permute_any_mods.html

**Comment by bew** [comment]
How do you explain this?
```lua
function get_more_elems()
  return {"A", "B", "C"}
end

function print_all(elems)
  for _, ev in ipairs(elems) do
    print(ev)
  end
end

elems = {
  "first",
  table.unpack(get_more_elems()),
  "last",
}
print_all(elems)
```
Gives:
```
first
A
last
```
Tested on https://www.lua.org/cgi-bin/demo (I'm not at my computer)

**Comment by wez** [comment]
It works better with tables of tables:

```lua
function foo()
   return {{a="1"}, {a="2"}}
end
e = {{a="a"}, table.unpack(foo())}
for _, v in pairs(e) do
   print(v.a)
end
```

```
$ lua /tmp/unpack.lua
a
1
2
```

**Comment by bew** [comment]
Well still not, indeed the unpack works if it's the last thing in the table, but as soon as you add another element after it it's broken:
```lua
function foo()
   return {{a="1"}, {a="2"}}
end
e = {{a="a"}, table.unpack(foo()), {a="b"}}  -- added the last {a="b"} for _, v in pairs(e) do
   print(v.a)
end
```
Gives:
```
a
1
b
```

**Comment by wez** [comment]
If you need multiple then I think you might need to supply a little helper function along the lines of:

```lua
function append_tables(...)
  local args = {...};
  local result = {};
  for _, t in ipairs(args) do
    for _, element in ipairs(t) do
      table.insert(result, element)
    end
  end
  return result
end

function get_stuff()
  return {{a = "woot"}}
end

local c = append_tables(
  {{a=1}, {a=2}},
  get_stuff(),
  {{a=3}, {a=4}}
);

for _, v in ipairs(c) do
  print(v.a)
end
```

outputs:

```
1
2
woot
3
4
```

I'm not sure that wezterm should provide that `append_tables` function; it seems a bit hyper specialized and I'm not super sure that it makes sense to include; part of the rationale behind using lua is that it allows users more flexibility to do things that aren't directly expressible in the default case.   It doesn't seem unreasonable for you to have a little bit of support code in your configuration file.

If lots of people want this then it makes sense to include it!

**Comment by bew** [comment]
I agree completely, my thoughts is that if the functions `wezterm.permute_any_or_no_mods` & co are provided, the documentation should show an example of use.

I implemented a `flatten_list` helper in my config to be able to have arbitrarily nested lists of bindings and flatten everything at the end. I'm just saying it can be helpful either in the docs, or in the stdlib.

**Comment by wez** [comment]
> if the functions wezterm.permute_any_or_no_mods & co are provided

Note that there's no *if*; those functions landed in the nightly builds a few days ago; please give them a try!

The docs are at: https://wezfurlong.org/wezterm/config/lua/wezterm/permute_any_mods.html and I'd welcome your feedback on those!
