### ISSUE TITLE
Incorrect F1 through F4 key release events in Kitty mode

### ISSUE THREAD

**Issue by djarb** [wez/wezterm#2883]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

qtile

### WezTerm version

wezterm 20221221-163401-72da5d16

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm is sending unmodified F1 though F4 key **release** events as SS3 P, SS3 Q, SS3 R, and SS3 S respectively, which is correct encoding for the key press but not for release. Releases and repeats need to use one of the other escape code formats which supports event type, as per https://sw.kovidgoyal.net/kitty/keyboard-protocol/#legacy-functional-keys

### To Reproduce

1. Send kitty protocol code to enable kitty the keyboard protocol
2. Send kitty protocol code to enable reporting event types
3. Press F1, F2, F3, or F4 without pressing any modifier keys

### Configuration

enable_kitty_keyboard = true,

### Expected Behavior

Expected F1 release to produce CSI 11 ; 1 : 3 ~ or CSI 1 ; 1 : 3 P
Expected F2 release to produce CSI 12 ; 1 : 3 ~ or CSI 1 ; 1 : 3 Q
Expected F3 release to produce CSI 13 ; 1 : 3 ~ or CSI 1 ; 1 : 3 R
Expected F4 release to produce CSI 14 ; 1 : 3 ~ or CSI 1 ; 1 : 3 S

### Logs

at 02:52 ❯ wezterm
02:52:46.976  WARN   wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1015))
02:53:01.346  WARN   wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1015))

**Comment by wez** [comment]
Fixed in d239e65e64ee5f68264b50408d6d7850e8b8cc2e
I'm going to mark this as a dup of https://github.com/wez/wezterm/issues/3473 even this one came first, because the other one has the edge with the repro scenario.
