### ISSUE TITLE
Which property should I adjust to change the code completion background?

### ISSUE THREAD

**Issue by 0123takaokeita** [wez/wezterm#2885]
‘irb’ などで window が出たときに見えない問題を解決したい。

テーマの変更で対応はできるが、このwindow だけ調整できる方法は無いだろうか？

だれかご存知だったら教えていただけませんか？

I want to solve the problem of not being able to see the window when it appears in 'irb', etc.

I can change the theme, but is there any way to adjust only this window?

If anyone knows of a way to do this, please let me know.

![image](https://user-images.githubusercontent.com/65272471/209413073-d6da8392-bb1e-43ed-b1dd-a8e2431eba32.png)

**Comment by wez** [comment]
This is something that irb controls; there is an open issue about it over here: https://github.com/ruby/irb/issues/328

**Comment by 0123takaokeita** [comment]
Thank you for letting me know.
