### ISSUE TITLE
ANSI art cannot be displayed well, glyphs are being replaced

### ISSUE THREAD

**Issue by poetaman** [wez/wezterm#2886]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221212-091509-91ea1095

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Some glyphs used in ANSI art are being replaced by WezTerm. This could be because of this [vte bug](https://gitlab.gnome.org/GNOME/vte/-/issues/205), but I am not sure. A string search for ``vte`` does not return any hit in WezTerm's GitHub repository. Perhaps bypass vte if it is the source, as the [vte bug](https://gitlab.gnome.org/GNOME/vte/-/issues/205) seems closed.

### To Reproduce

Download [arttime](https://github.com/poetaman/arttime), and run:

If you install arttime*, it's a single command [installer](https://github.com/poetaman/arttime#installation):
```
arttime --nolearn -a picard -t '"Stop replacing glyphs" - Capt. Picard'
```

Or from arttime directory:
```
./bin/arttime --nolearn -a picard -t '"Stop replacing glyphs" - Capt. Picard'
```

\*Note: arttime does not dial the internet, it's perfectly respecting of your privacy.

### Configuration

n/a

### Expected Behavior

Don't replace glyphs, or provide a config option to disable this feature/bug.

### Anything else?

In iTerm2 (looks correct):
<img width="899" alt="picard_iterm2" src="https://user-images.githubusercontent.com/71736629/209414994-dcb357f4-84f1-475f-8c72-9335fafe5fe5.png">

In WezTerm (same glyphs are affected as in screenshot at [vte bug](https://gitlab.gnome.org/GNOME/vte/-/issues/205)):
<img width="899" alt="picard_wezterm" src="https://user-images.githubusercontent.com/71736629/209414978-5c20e9a5-a11a-4b1b-80da-de3eafbb1a76.png">

**Comment by wez** [comment]
wezterm doesn't use vte.
wezterm does replace certain block drawing glyphs with graphics that are perfectly sized for the cell size, to avoid issues with box drawing characters in various fonts and hinting issues with freetype.
You can disable that if you like; see https://wezfurlong.org/wezterm/config/lua/config/custom_block_glyphs.html for more information.

**Comment by poetaman** [comment]
That setting worked well... Not sure why the default would be to replace glyphs. My guess would be that over the course of time more and more users will have fonts which already have these glyphs built into them. Anyway, thanks! Here's how it looks like now:

<img width="899" alt="Screenshot 2022-12-23 at 9 01 13 PM" src="https://user-images.githubusercontent.com/71736629/209422362-8bdd34b6-6d7a-4006-9a75-441e559f1b69.png">
