### ISSUE TITLE
Ligatures are rendered into the cell to the left

### ISSUE THREAD

**Issue by phha** [wez/wezterm#2888]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221224-001004-b1c3103a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

https://user-images.githubusercontent.com/376139/209436465-8b350819-09c9-45e9-8a1f-51e4fdb5d68a.mov

### Configuration

```lua
local wezterm = require 'wezterm'

return {
  font = wezterm.font {
    family = 'Lilex Nerd Font',
    harfbuzz_features = { 'ss05=1' },
  },
}
```

### Logs

lots of these:
`13:20:59.241  WARN   wezterm_term::terminalstate > unhandled SetMode(Unspecified(34))`

[ls-fonts.txt](https://github.com/wez/wezterm/files/10298577/ls-fonts.txt)

**Comment by wez** [comment]
Can you try removing the `harfbuzz_features` setting from your config to see if that changes things?
Can you try a different font? eg: Instead of `Lilex Nerd Font` just try the regular Lilex font?

Please run and share the output from:

`wezterm ls-fonts --text 'a->b'`

**Comment by phha** [comment]
disabling `harfbuzz_features` makes no difference.

The regular Lilex font looks ok, though.

Here's the output of `wezterm ls-fonts --text 'a->b'`:

```
 0 a    \u{61}       x_adv=7  cells=1  glyph=a,68   wezterm.font("Lilex Nerd Font", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/philipp/Library/Fonts/Lilex Regular Nerd Font Complete.otf, CoreText
 1 -    \u{2d}       x_adv=7  cells=1  glyph=LIG,4963 wezterm.font("Lilex Nerd Font", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/philipp/Library/Fonts/Lilex Regular Nerd Font Complete.otf, CoreText
 2 >    \u{3e}       x_adv=7  cells=1  glyph=hyphen_greater.liga,4999 wezterm.font("Lilex Nerd Font", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/philipp/Library/Fonts/Lilex Regular Nerd Font Complete.otf, CoreText
 3 b    \u{62}       x_adv=7  cells=1  glyph=b,69   wezterm.font("Lilex Nerd Font", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/philipp/Library/Fonts/Lilex Regular Nerd Font Complete.otf, CoreText
```

**Comment by wez** [comment]
Sounds like this might be another case where the patched nerdfont is a bit broken.  If Lilex works, then I'd recommend using that. Note that wezterm has a default fallback font which contains all of the the nerdfont symbols, which makes them work with any font, so you shouldn't need to use a patched font.

**Comment by phha** [comment]
Yes looks like a problem with the font itself. Thanks for the suggestion about just using the regular font, it works just fine. Closing this.
