### ISSUE TITLE
ssh hostname resolution doesn't respect AddressFamily ssh option

### ISSUE THREAD

**Issue by phha** [wez/wezterm#2893]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20221224-162859-e8886752

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm can't connect via ssh when specifying a host name. It works when I use the corresponding IP Address directly. I already tried deleting `wezterm.lua` and `.ssh/config`, but the problem persists.

Connecting to the same host via openssh client works as expected, so there seems to be something funky going on with name resolution in wezterm or libssh.

```
[0] ~% wezterm ssh -v <REDACTED>
22:46:28.741  INFO   libssh::ssh_config_parse_file > Reading configuration data from /etc/ssh/ssh_config
22:46:28.741  INFO   libssh::local_parse_file      > Cannot find file /etc/ssh/ssh_config.d/* to load
22:46:28.741  INFO   libssh::ssh_config_parse_line > Unapplicable option: SendEnv, line: 55
22:46:28.741  INFO   libssh::ssh_connect           > libssh 0.8.90 (c) 2003-2021 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
22:46:28.985  INFO   libssh::ssh_socket_connect    > Nonblocking connection socket: 20
22:46:28.985  INFO   libssh::ssh_connect           > Socket connecting, now waiting for the callbacks to work
22:46:28.985  INFO   libssh::ssh_connect           > Actual timeout : 10000
22:46:38.990  INFO   libssh::ssh_connect           > Timeout connecting to <REDACTED>
22:46:38.990  INFO   libssh::ssh_connect           > current state : 9
22:46:38.991  ERROR  mux::ssh                      > WrappedSshChild err: RecvError
```

### Configuration

no config

**Comment by wez** [comment]
Is there something in one of the files mentioned in the `/etc/ssh/ssh_config.d/*` log line that might influence the settings?
It sounds like there may be some globbing happening in openssh that isn't happening in the libssh integration, so perhaps some config is not being applied.

Beyond that, there's not really any information in this report that I can use to understand what is happening.
Can you reduce the ssh config to something that you can share that will reproduce the issue?

**Comment by phha** [comment]
Switching to `ssh_backend = "Ssh2"` doesn't help.

Neither does passing `-oAddressFamily=inet` to the ssh command.

**Comment by phha** [comment]
I've commented out everything in `/etc/ssh_config`. It's still not working:

```
23:14:32.134  INFO   libssh::ssh_config_parse_file > Reading configuration data from /etc/ssh/ssh_config
23:14:32.134  INFO   libssh::ssh_connect           > libssh 0.8.90 (c) 2003-2021 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
23:14:32.370  INFO   libssh::ssh_socket_connect    > Nonblocking connection socket: 20
23:14:32.370  INFO   libssh::ssh_connect           > Socket connecting, now waiting for the callbacks to work
23:14:32.370  INFO   libssh::ssh_connect           > Actual timeout : 10000
23:14:42.375  INFO   libssh::ssh_connect           > Timeout connecting to <REDACTED>
23:14:42.375  INFO   libssh::ssh_connect           > current state : 9
23:14:42.377  ERROR  mux::ssh                      > WrappedSshChild err: RecvError
```

**Comment by wez** [comment]
There's not really anything for me to act on here. I use hostnames all the time. There must be something about your environment that is affecting what you are experiencing, but you haven't shared any information that will help in that understanding.  For example, does the hostname resolve to the IP you expect? Is it IPv4 vs IPv6? Does IPv6 work in your network? Is there something else about your network that might be influencing this? Do you have local security software that might impact connectivity?

**Comment by phha** [comment]
Yeah I'm pretty baffled by it as well.

I've used `dig` to resolve the hostname and when I connect to the resolved IP Address it works.

I've assumed that using `wezterm ssh -oAddressFamily=inet my.host` would disable IPv6. I already tried that but it doesn't help.

There's no security software running and I deleted `~/.ssh/config` and `/etc/ssh/ssh_config` so there should be nothing in my environment impacting this. I can connect to this host with all kinds of clients to all kinds of ports, it's just `wezterm ssh` that is causing problems.

From the messages above, I'm assuming that it already fails at establishing a TCP connection to the host, so there should be nothing impacting this on the host side either.

I'm now trying to maybe find some clues with wireshark.

**Comment by phha** [comment]
Ok, so wezterm seems to always resolve to an IPv6 address, which I can't reach from where I am for whatever reason. Openssh OTOH resolves to an IPv4 address by default, which works.

Is there a way to enforce IPv4? `oAddressFamily=inet` should do it, but it seems like it's not honoured.

**Comment by wez** [comment]
I'd suggest adding something like this to your `~/.ssh/config`:

```
Host hostname
  HostName X.X.X.X
```

where `X.X.X.X` is the IPv4 address of `hostname`

**Comment by phha** [comment]
Sure, that would work, but there are a lot of scenarios where it wouldn’t be ideal. Think of dyndns or a split horizon setup.

**Comment by wez** [comment]
FWIW, and IMO, the real problem is that your network infrastructure is handing out broken addresses (perhaps you actually to deploy split horizon dns?), so the real fix would be to correct that network configuration so that individual clients don't need any special configuration.

Putting on my pragmatist hat: If you have to put a configuration workaround into the ssh config, it doesn't make too much difference whether that line is `AddressFamily inet` or `HostName X.X.X.X`.  The former is slightly cleaner as it is more resilient to eg: the address being re-assigned, but either way you need to hack around a problem that exists elsewhere in your environment, and either way, there's an additional line needed in a config.

I generally try to recommend a configuration-only option as a first-pass workaround as that tends to be the fastest way to unblock someone while I figure out how to deal with the underlying problem.  I don't make that suggestion to avoid making a fix.  I do understand the utility and why you might want to do this. I don't need additional commentary on that front.

In this case, the underlying libraries don't support this feature, but thankfully they do expose enough stuff so that it is possible to cut out their own internal connection logic and do it all ourselves, for better or worse.

Those code changes are now present in `main`, and should show up in a macOS nightly download in about an hour.

Please give it a try and let me know how it goes.

**Comment by phha** [comment]
Thanks. I know it’s a hack either way, but unfortunately sometimes you have to work with the infrastructure that you’re given. 

Really appreciate your swift response and pragmatic attitude. 

I will try the nightly and let you know how it went.

**Comment by phha** [comment]
Nightly is honouring `AddressFamily` now, thanks again!
