### ISSUE TITLE
wezterm-nightly-bin failing to install via aur

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#290]
`yay -S wezterm-nightly-bin` is failing to install. sha256sum validation is failing for LICENSE file.

**Comment by prabirshrestha** [comment]
`wezterm-bin` also seems to be failing.

**Comment by prabirshrestha** [comment]
Temporarily using `yay -S wezterm-nightly-bin --mflags --skipinteg`

**Comment by wez** [comment]
I pushed a couple of commits to AUR earlier in the week that should have resolved this, as well as the commit to this repo today that should fix it for the next release.
I'm going to speculatively close this!
