### ISSUE TITLE
High cpu usage for Xorg when using picom

### ISSUE THREAD

**Issue by kaiphat** [wez/wezterm#2901]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3-gaps. I tried with lightdm and gdm - the same.

### WezTerm version

20221225-233013-ff2caf4f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When i open wezterm, Xorg uses a lot of cpu resource. It doesn't always happen right away, sometimes after a while. And value of cpu usage gradually increases before 100%. I see freezes in wezterm in the same time.
![image](https://user-images.githubusercontent.com/53742299/209949033-6f8a0c5f-d9bb-4e42-bee3-3a780ebc56ef.png)
![image](https://user-images.githubusercontent.com/53742299/209949210-144ed2a1-3722-4843-b15e-54c91811f3b4.png)

It doesn't happen with alacritty and kitty.
It doesn't happen in gnome ubuntu, only when i use i3wm.

### Configuration
```lua
local wezterm = require 'wezterm'

-- FONTS --

local font = function(name, params)
  local names = {
    name,
    'Iosevka Nerd Font',
  }

  return wezterm.font_with_fallback(names, params)
end

local font_config = ({
  jet_brains = {
    font_size = 9.5,
    font = wezterm.font('JetBrainsMono Nerd Font'),
    cell_width = 0.87,
    font_rules = {
      {
        font = wezterm.font('JetBrainsMono Nerd Font', { weight = 'Medium' }),
      },
    },
    line_height = 0.9,
  },
  iosevka = {
    font_size = 10.7,
    font = wezterm.font('Iosevka Nerd Font'),
    line_height = 0.9,
    font_rules = {
      {
        font = font('Iosevka Nerd Font', { italic = false, weight = 'Medium' })
      }
    }
  },
  victor_mono = {
    font_size = 10,
    font = font('VictorMono'),
    line_height = 0.80,
    font_rules = {
      {
        font = font('VictorMono', { italic = false })
      }
    }
  },
  caskaydia = {
    font_size = 10.2,
    line_height = 1,
    cell_width = 1,
    font = wezterm.font('CaskaydiaCovePL Nerd Font'),
    font_rules = {
      {
        italic = true,
        font = wezterm.font('CaskaydiaCovePL Nerd Font', { italic = false, weight = 'Regular' })
      },
      {
        intensity = 'Bold',
        font = wezterm.font('CaskaydiaCovePL Nerd Font', { italic = false, weight = 'Regular' })
      },
      {
        font = wezterm.font('CaskaydiaCovePL Nerd Font', { italic = false, weight = 'Regular' })
      }
    }
  },
  mononoki = {
    font_size = 10.3,
    font = font 'mononoki Nerd Font',
    cell_width = 0.87,
    line_height = 1,
    font_rules = {
      {
        font = font('mononoki Nerd Font', { italic = false, weight = 'Bold' })
      }
    }
  },
  fira = {
    font_size = 9.4,
    font = wezterm.font 'FiraCode Nerd Font',
    line_height = 1,
    cell_width = 0.83,
    font_rules = {
      {
        font = wezterm.font('FiraCode Nerd Font', { italic = false, weight = 'Medium' })
      }
    }
  },
  hack = {
    font_size = 10.2,
    font = font 'Hack Nerd Font',
    line_height = 1,
    font_rules = {
      {
        font = wezterm.font('Hack Nerd Font', { italic = false, weight = 'Regular' })
      }
    }
  },
}).jet_brains

-- UTILS --

local merge = function(list)
  local result = list[1]

  for i = 2, #list do
    for key, value in pairs(list[i]) do
      result[key] = value
    end
  end

  return result
end

-- EVENTS --

wezterm.on('gui-startup', function(cmd)
  local _, _, window = wezterm.mux.spawn_window(cmd or {})
  window:gui_window():maximize()
end)

-- THEME --

local colors = {
  foreground = "#787C99",
  background = "#202837",
  cursor_bg = "#ffcc66",
  cursor_border = "#ffcc66",
  cursor_fg = "#404060",
  selection_fg = "#333355",
  selection_bg = "#787c99",
  scrollbar_thumb = "#222222",
  compose_cursor = "orange",
  ansi = {
    '#404060',
    '#F7768E',
    '#9CC4B2',
    '#88C0D0',
    '#6e88a6',
    '#9398cf',
    '#c8ae9d',
    '#E5E9F0',
  },
  brights = {
    '#9CC4B2',
    '#F7768E',
    '#9CC4B2',
    '#ffcc66',
    '#6e88a6',
    '#9398cf',
    '#c8ae9d',
    '#ACB0D0',
  },
}

local padding = {
  left = 0,
  right = 0,
  top = 0,
  bottom = 0,
}

-- RESULT --

local config = {
  colors = colors,
  window_padding = padding,
  enable_tab_bar = false,
  scrollback_lines = 10000,
  cursor_blink_rate = 700,
  max_fps = 60,
  animation_fps = 30,
  window_background_opacity = 0.93,
  enable_kitty_graphics = true,
  default_cursor_style = 'BlinkingBlock',
  freetype_load_target = 'HorizontalLcd',
}

return merge {
  config,
  font_config,
}
```

**Comment by wez** [comment]
Please fill out the logs section:

Activate the Debug Overlay by pressing CTRL-SHIFT-L and then copy
and paste the log lines in here. If you launched wezterm from
the command line, copy and paste that output here.
You can also find log files in $XDG_RUNTIME_DIR/wezterm on unix systems,
or $HOME/.local/share/wezterm on macOS and Windows systems.

You may wish to try altering the values of the following configuration to adjust the load on your system:
* `animation_fps` (or disable the use of blinking cursors)
* `window_background_opacity` (try making it fully opaque)

You may also wish to try enabling WebGPU to see if that affects the load, see:
* https://github.com/wez/wezterm/issues/2756

**Comment by kaiphat** [comment]
I tried it previous, but it doesn't help. Also the same with `front_end = "WebGpu"`.
![image](https://user-images.githubusercontent.com/53742299/209989526-61d74551-0b8d-49ab-849c-515326482287.png)

**Comment by kaiphat** [comment]
After ctrl+shift+l
```
Debug Overlay
wezterm version: 20221225-233013-ff2caf4f
OpenGL version: Mesa Intel(R) HD Graphics 530 (SKL GT2) 4.6 (Compatibility Profile) Mesa 22.2.1
Enter lua statements or expressions and hit Enter.
````

**Comment by kaiphat** [comment]
In logs i didn't find something interesting.

**Comment by kaiphat** [comment]
I noticed that it connects with picom. When i disabled picom, xorg doesn't use a lot of cpu. But still is happens only with wezterm.

**Comment by wez** [comment]
This sounds like it is an issue at the intersection of picom and the intel graphics drivers on your system.
wezterm can't control those. If disabling picom resolves the CPU utilization issue, it sounds like this may be more of a picom issue than a wezterm issue.

I'd suggest looking at the picom issue tracker to see if others have similar problems, or to help you uncover issues with the picom configuration; here's the first one I found:
* https://github.com/yshui/picom/issues/446

but there may be other things that are more applicable to your system
