### ISSUE TITLE
hyperlinks broken for IP-based domains

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wez/wezterm#2903]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter (gnome shell)

### WezTerm version

20221119-081400-d96b05c0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

i'm having trouble getting underlining on hyperlinks featuring IP-based domains.

when trying the instructions to build the new nightly from source i get a warning stating rustup should not be installed alongside Rust, so my version is still behind by a month.

### To Reproduce

- run a jupyter docker
- find a link like http://127.0.0.1:8888/lab?token=dcd0800f4c871840fee6c462bec81b95d77cb3e831d08991
- find no such underlining as promised at #2496

### Configuration

no config

### Expected Behavior

find underlining for any valid URI

### Logs

```
17:35:03.426  INFO   wezterm_gui::update > latest release 20221119-145034-49b9839f is newer than current build 20221119-081400-d96b05c0
17:45:15.958  WARN   wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
18:29:02.564  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "0;3^"
18:30:31.669  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "34;1^"
20:03:23.998  WARN   wezterm_term::terminalstate            > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
12:50:02.047  WARN   wezterm_term::terminalstate            > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
15:43:47.207  WARN   wezterm_term::terminalstate            > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
17:21:16.422  WARN   wezterm_term::terminalstate            > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
17:33:07.318  WARN   wezterm_term::terminalstate            > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
20:19:38.031  INFO   wezterm_gui::update                    > latest release 20221119-145034-49b9839f is newer than current build 20221119-081400-d96b05c0
20:25:29.384  WARN   wezterm_term::terminalstate            > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
16:46:12.108  WARN   wezterm_term::terminalstate            > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
18:18:02.048  INFO   wezterm_gui::update                    > latest release 20221119-145034-49b9839f is newer than current build 20221119-081400-d96b05c0
14:39:56.458  WARN   wezterm_term::terminalstate            > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
```

**Comment by wez** [comment]
This is essentially the same as:
* https://github.com/wez/wezterm/issues/928

The default hyperlink rules don't include IP address or port numbers, but you can configure your own rules that do.

https://wezfurlong.org/wezterm/hyperlinks.html has information about hyperlink rules.
