### ISSUE TITLE
wezterm is really slow

### ISSUE THREAD

**Issue by manfredlotz** [wez/wezterm#2916]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

xfwm4

### WezTerm version

wezterm 20230102-155114-67896f67

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Actually, I am not sure if there is a bug. But I thought it is best to report here.

The output in wezterm is pretty slow although it is stated that wezterm is GPU-accelerated.

### To Reproduce

My test looks like this:

Issuing a `time find .` command which lists 2258150 files and directories the total running time is

- alacritty: 7.2 secs
- kitty: 13.9 secs
- wezterm: 37 secs

Is this something to be expected?

### Configuration

no config

### Logs

wezterm version: 20230102-155114-67896f67
OpenGL version: AMD Radeon Graphics (renoir, LLVM 14.0.6, DRM 3.49, 6.1.2-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.3.2
Enter lua statements or expressions and hit Enter.

**Comment by bew** [comment]
You can read this answer from Wez on a similar comment: https://github.com/wez/wezterm/issues/1453#issuecomment-1000068807

**Comment by manfredlotz** [comment]
@bew I searched the issues for something like this but didn't find anything.

Thanks a lot for that pointer.
