### ISSUE TITLE
Meta/Opt key not detected in Neovim

### ISSUE THREAD

**Issue by kuntau** [wez/wezterm#2921]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

**Opt/meta/Alt** key is not working in neovim, I have multiple mapping that use Alt `<A-key>` but none of them is working.

Pressing `alt`+`key` only produce garbage mac Unicode character.

But `alt` shortcut in `wezterm` config work as expected

### To Reproduce

1. Lunch `neovim`
2. Enter command `:nn <A-q> :qall!<cr>`
3. Press `alt+q`
4. Nothing happens

### Configuration

no config, but I tried setting `enable_kitty_keyboard = true`. Same result.

### Expected Behavior

`neovim` will exit

**Comment by bsferrazza** [comment]
I'm using the nightly build on Windows connected to a Linux server and don't see Meta/Alt registered at all with Wezterm. Doesn't work in emacs and other programs that make use of the Meta key

**Comment by sboesebeck** [comment]
not sure, if that is related, but I had a similar issue on OSX, maybe it is related? https://github.com/wez/wezterm/issues/2920

key was to set these two options:

```lua
        send_composed_key_when_left_alt_is_pressed = true,
	send_composed_key_when_right_alt_is_pressed = true,
```

in your case, maybe you need to set it to false? not sure though....

**Comment by kuntau** [comment]
> not sure, if that is related, but I had a similar issue on OSX, maybe it is related? #2920
> 
> key was to set these two options:
> 
> ```lua
>         send_composed_key_when_left_alt_is_pressed = true,
> 	send_composed_key_when_right_alt_is_pressed = true,
> ```
> 
> in your case, maybe you need to set it to false? not sure though....

This did it. Thank you!
