### ISSUE TITLE
Copying in wezterm doesn't trigger X11 event after it own clipboard

### ISSUE THREAD

**Issue by wrvsrx** [wez/wezterm#2926]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11, xmonad

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

X11 clipboard change event is triggered only for first time coping in wezterm. For copying after the first time, wezterm doesn't notify X11.

### To Reproduce

1. install [clipnofity](https://github.com/cdown/clipnotify) or other scripts that can listen to clipboard event in X11.
2. copy something in wezterm, you'll find clipboard event is triggered.
3. copy something else in wezterm, you'll find clipboard event is not triggered.

### Configuration

no config

### Expected Behavior

Every time copying in wezterm, X11 event is triggered.

### Anything else?

According to its behavior, I guess the reason is that wezterm doesn't notify X11 after it becomes clipboard owner, it only change content of clipboard in its momery and wait for some other app to ask for clipboard.

**Comment by wez** [comment]
Can you describe how you are copying in wezterm? Are you selecting text, or are you using a key assignment like `CTRL+SHIFT+C` to copy?

**Comment by wrvsrx** [comment]
> Can you describe how you are copying in wezterm?

Select some text with mouse and press `CTRL+SHIFT+C`

> Are you selecting text, or are you using a key assignment like CTRL+SHIFT+C to copy?

I use `CTRL+SHIFT+C` to copy.

---

According to X11 standard [ICCCM](https://x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#acquiring_selection_ownership), wezterm should reacquire the selection owner when selection value changes.

> If the selection value completely changes, but the owner happens to be the same client (for example, selecting a totally different piece of text in the same xterm as before), then the client should reacquire the selection ownership as if it were not the owner, providing a new timestamp. If the selection value is modified, but can still reasonably be viewed as the same selected object, [[3](https://x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#ftn.id2584539)] the owner should take no action.

However, in the code:

https://github.com/wez/wezterm/blob/36bf634e931f1a03f35479f5421132820d65a31a/window/src/os/x11/window.rs#L657-L687

When selection value change, wezterm doesn't do that if it has owned the selection.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wrvsrx** [comment]
I build from source and test it. Now the problem is solved. Thanks!
