### ISSUE TITLE
Text and font display differently compared to Alacritty

### ISSUE THREAD

**Issue by farzadmf** [wez/wezterm#2927]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I honestly love your terminal, and the fact that the configuration is in Lua.

However, one issue I have is with the font display that I haven't managed to resolve.

Here's what I see in WezTerm:
![image](https://user-images.githubusercontent.com/5768792/211130811-e4e33cb5-54e1-4a3e-8265-7dc0b5bea261.png)

And what I see in Alacritty:
![image](https://user-images.githubusercontent.com/5768792/211130667-e66dbb89-6d57-4580-8aa7-e5f8174d4690.png)

- In general, Alacritty's font looks "thicker/more bright/smoother"
- For example, if you compare the `Ran all test suites` between the two, the one in WezTerm looks pale compared to the one in Alacritty
- And, in general, Alacritty's font is easier on the eye (at least my eye)

Maybe it's some anti-aliasing or something done by Alacritty (I'm not a font expert at all!), but both terminals are using the same font on my system (`Fira Code`) and the same weight (`Regular`)

### Configuration

I added this section with the hope of making WezTerm's font a bit "brighter" similar to Alacritty
```lua
foreground_text_hsb = {
  hue = 1.0,
  saturation = 1.0,
  brightness = 1.15,
},
```

```lua
font = wezterm.font_with_fallback({
  {
    family = "Fira Code",
    weight = "Regular",
  }
})
```

### Expected Behavior

It would be great if I'd see the same thing in both terminals. I've been going back and forth, and this font issue with WezTerm is the only blocker for me

**Comment by wez** [comment]
Try using the webgpu front end:
* https://github.com/wez/wezterm/issues/2756

That happens to render a bit brighter/bolder than opengl.  That may technically be a bug, but if it is, it's not something that is obviously within the control of wezterm(!)

**Comment by farzadmf** [comment]
Hey @wez , thank you for the reply.

> That may technically be a bug

Not exactly sure which part you mean? The fonts being rendered "thinner" compared to Alacritty? Or the fonts looking brighter with WebGPU?

So, I tried adding `front_end = "WebGpu"` to my config and I thought, like other settings, saving my config would reflect the changes, and I was almost giving up, but then I tried restarting WezTerm, and I think the font looks MUCH nicer

However, it seems that I lost my window opacity 🤔

**Comment by farzadmf** [comment]
Hey @wez , didn't hear from you. Was wondering if there's a setting that I need to change to have the opacity?

**Comment by wez** [comment]
Looks like a webgpu + macos specific issue; please file a separate issue for that. I'm not surprised by it: I had to play some tricks to get MetalANGLE + opacity working and those may need to be translated to webgpu as well.

**Comment by farzadmf** [comment]
OK, sure, gonna create a new one a bit. For now, this is the only show stopper for me to go back to WezTerm
