### ISSUE TITLE
Bright color text on minecraft server console look thicker then normal color text

### ISSUE THREAD

**Issue by netherstar** [wez/wezterm#2932]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

i  used to use Windows Terminal, MobaXterm, Alacritty and Wezterm to run Minecraft server, and i noticed that with Wezterm and Alacritty bright text display on Minecraft server console (maybe java console in general?)  look thicker  than normal color text, but in linux shell console it look corectly.

Sorry for bad English, and this is image:
![compare](https://user-images.githubusercontent.com/12563466/211273959-eb22a21d-3422-4e8d-8630-786de706a01b.png)

If Wezterm can't find configured font and used fallback font then text look normal and equal every where. This is when fallback font is used:
![fallback-font](https://user-images.githubusercontent.com/12563466/211276925-48ff9e56-d5c7-43ae-8579-d3974df282a6.png)

Text display in Windows Terminal and MobaXterm all look perfect.
![window-terminal](https://user-images.githubusercontent.com/12563466/211277921-be441845-4cf4-4165-994e-a45fbc4512d7.png)

### Configuration

default, no config file

**Comment by wez** [comment]
Take a look at:
* https://wezfurlong.org/wezterm/config/lua/config/bold_brightens_ansi_colors.html

**Comment by wez** [comment]
Please run `wezterm ls-fonts` and share the output; that shows what wezterm will use for different styles of text

**Comment by netherstar** [comment]
> Please run `wezterm ls-fonts` and share the output; that shows what wezterm will use for different styles of text

wezterm ls-fonts > show.txt
```
Primary font:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})

Title font:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="Roboto", weight="Bold"},

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})

```

**Comment by wez** [comment]
Can we focus on a single scenario? I'm confused about what you're trying and seeing.

Please pick one configuration and include both that configuration and a screenshot of the text in that situation.

Please also capture a terminal recording of that same thing:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by wez** [comment]
Also important: is the program that you're testing a native win32 console program, or is it running under WSL, cygwin or a remote linux program?

**Comment by netherstar** [comment]
> Can we focus on a single scenario? I'm confused about what you're trying and seeing.
> 
> Please pick one configuration and include both that configuration and a screenshot of the text in that situation.
> 
> Please also capture a terminal recording of that same thing:
> 
> * Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
> * Inside that terminal run `wezterm record` to start a recording session.
> * Run through your reproduction steps
> * Then type `exit`
> * You should see a message like:
> 
> ```
> *** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
> ```
> 
> * Attach the file that it produced to this issue.
> 
> The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.
> 
> The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

[wezterm-recording-HuUybO.cast.txt](https://github.com/wez/wezterm/files/10375453/wezterm-recording-HuUybO.cast.txt)

here are wezterm config when running above:
```
Primary font:
wezterm.font_with_fallback({
  -- C:\USERS\MANHT\APPDATA\LOCAL\MICROSOFT\WINDOWS\FONTS\CONSOLAS NERD FONT COMPLETE MONO WINDOWS COMPATIBLE.TTF, DirectWrite
  "Consolas NF",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- <imported to RAM>, Gdi
  -- Will synthesize italics
  -- Will synthesize dim
  "Consolas NF",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- <imported to RAM>, Gdi
  -- Will synthesize dim
  "Consolas NF",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- <imported to RAM>, Gdi
  -- Will synthesize bold
  "Consolas NF",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- <imported to RAM>, Gdi
  -- Will synthesize italics
  -- Will synthesize bold
  "Consolas NF",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- <imported to RAM>, Gdi
  -- Will synthesize italics
  "Consolas NF",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})

Title font:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="Roboto", weight="Bold"},

  -- C:\USERS\MANHT\APPDATA\LOCAL\MICROSOFT\WINDOWS\FONTS\CONSOLAS NERD FONT COMPLETE MONO WINDOWS COMPATIBLE.TTF, DirectWrite
  "Consolas NF",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})
```

**Comment by wez** [comment]
I've trimmed down the recording to just the `testcolors` portion:

[wezterm-recording-2932-trimmed.txt](https://github.com/wez/wezterm/files/10375549/wezterm-recording-2932-trimmed.txt)

Replaying that locally (I'm on linux at the moment) looks how I'd expect in the default configuration (running `wezterm -n`):

![image](https://user-images.githubusercontent.com/117777/211371220-ff253794-d4ec-41ba-84d6-92b71fb201be.png)

Running:

```
wezterm replay wezterm-recording-2932-trimmed.txt --explain
```

shows how the output is parsed:

```
        Print("[00:17:10 INFO]: ")
        Action(CSI(Sgr(Foreground(PaletteIndex(5)))))
        Action(CSI(Sgr(Intensity(Bold))))
        Print("This is Light Magenta")
```

so these are ansi palette indices 0-7 + bold which translates to using the bright version (palette indices 8-15) because of https://wezfurlong.org/wezterm/config/lua/config/bold_brightens_ansi_colors.html

I'd expect these to appear as both bold and brighter than the the non-light versions.

Please download the trimmed recording and run:

```
wezterm replay wezterm-recording-2932-trimmed.txt 
```

and attach a screenshot of how that renders, so that I can see it.

**Comment by wez** [comment]
Aside from the "This is Gray" line showing in black (I'm assuming you have set a different color scheme?), that looks how I'd expect it to look.  Is there a problem with it?

**Comment by netherstar** [comment]
> Aside from the "This is Gray" line showing in black (I'm assuming you have set a different color scheme?), that looks how I'd expect it to look. Is there a problem with it?

From Light Red to White text look thicker. When you see it on console full of text you will notice it more clearly
![image](https://user-images.githubusercontent.com/12563466/211375318-2b2b2ba5-812d-4e68-8680-a49f0834e2e8.png)

**Comment by netherstar** [comment]
compare to same text display on Window terminal
![image](https://user-images.githubusercontent.com/12563466/211375652-c3b1d5c1-e082-4b7e-adb3-09cd73befe21.png)

**Comment by wez** [comment]
That text has the bold attribute set, so it is rendered using a bold font in addition to using the brighter colors from the palette.

**Comment by netherstar** [comment]
> 

it is not bold text, you can see it show normal on Window Terminal, i swear with you it normal text, i don't know why wezterm show it as bold text, same as Aclaritty terminal.
When display on Window terminal
![winterminal](https://user-images.githubusercontent.com/12563466/211377669-e97242e3-b8da-42f1-85e5-90699f96b58e.png)
When display on wezterm
![wezterm](https://user-images.githubusercontent.com/12563466/211377727-a2039c17-a4f9-4d36-8fae-e0cd4e72a456.png)
When display on MobaXterm
![mobaxterm](https://user-images.githubusercontent.com/12563466/211377756-55f1a0e9-82ec-4533-b976-406fa315469f.png)

**Comment by netherstar** [comment]
This is simple code to show text on test, as you see below, not ```&l``` mean no bold text
![image](https://user-images.githubusercontent.com/12563466/211379867-e1b84ad1-bfcd-455f-81cc-5b6bd22a3ca3.png)

![example2](https://user-images.githubusercontent.com/12563466/211380056-7737b472-acaf-4f56-8fb4-197fec182c65.png)

This is text display with same code above
on Window terminal, text is equally
![windowterminal-2](https://user-images.githubusercontent.com/12563466/211380159-144726e7-8221-4947-b54b-458d176da57b.png)
on wezterm, text bright text look thicker clearly
![wezterm2](https://user-images.githubusercontent.com/12563466/211380392-4217a16e-9045-42ba-b8bc-8409d1662055.png)
on Mobaxterm, text look equally
![mobaxterm-2](https://user-images.githubusercontent.com/12563466/211380456-a880165a-5852-4581-99cc-a85e6d9faace.png)

**Comment by wez** [comment]
It is bold; the recording you provided sets the color and then sets bold. That is how bright colors are/were set for an 8-color terminal; by setting them bold.

Other terminals may choose to render this kind of bold/bright differently, but this is how wezterm renders it: by making it bright and by using a bold variant of the font.

**Comment by netherstar** [comment]
it is not bold text, i tried all kind of terminal:
 Windows terminal, MobaXterm, Linux default terminal, Linux Tilix, ConEmu, KiTTy, ZocTerminal, Android's Termius app.
all display text perfect.
Only Wezterm and Alacritty show text look weird. I don't know why wezterm and Alacritty get bold attribute from where, may be wezterm and alacritty use same something.

**Comment by netherstar** [comment]
and as i said from post 1, that when wezterm forced to use fallback font, text display correct

**Comment by wez** [comment]
It is definitely bold. In your fallback scenario, it looks like you have a font_rule that uses the regular weight JetBrains Mono font when bold text is selected, which is why it doesn't appear bold.

I've pushed a commit that will allow you to set:

```lua
 bold_brightens_ansi_colors = "BrightOnly",
```

the effect of setting that is that when text is bold + ANSI color palette 0-7, wezterm will add 8 to the palette index for color selection (shifting it to the bright range), and treat it as though it was not bold for font selection.

That change should be available in the nightly build in about an hour.

**Comment by netherstar** [comment]
@wez You are right, minecraft server use log4j to display log, log4j display 'bright' text as 'bold' (in old version).
i am
 just logged into linux to testing again, so gnome terminal and tilix show text just like wezterm, it is my fault.

I found mistyping, this message shoud be 'None' is not valid, use one of 'No'.... 
![aaa](https://user-images.githubusercontent.com/12563466/211514751-63a2dc16-106f-4eb7-82f1-f63674477daa.png)
