### ISSUE TITLE
Option to match system color scheme light/dark mode

### ISSUE THREAD

**Issue by ahupp** [wez/wezterm#2939]
**Is your feature request related to a problem? Please describe.**
Most of the time I'm indoors and prefer a dark color scheme.  Occasionally I'll work outdoors where it's brighter and switch to a light color scheme system-wide.  Everything I use is set to match the system color scheme so this is more or less universal.  One exception is Wezterm.

**Describe the solution you'd like**
In wezterm.lua, a new config option:

```
color_scheme_auto = {
  light = 'My light scheme',
  dark = 'My dark scheme',
}
```

Unclear what should happen if used on a system that doesn't have a concept of light/dark system theme.

**Comment by wez** [comment]
Did you find this? https://wezfurlong.org/wezterm/config/lua/wezterm.gui/get_appearance.html

**Comment by ahupp** [comment]
Excellent, that's exactly what I want!  So I guess this issue is about mentioning the feature on the[ "Colors & Appearance"](https://wezfurlong.org/wezterm/config/appearance.html) doc.
