### ISSUE TITLE
Cannot log out with WezTerm running. (Same for Restart / Shut Down).

### ISSUE THREAD

**Issue by CoralPink** [wez/wezterm#2944]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221219-110612-28c7c0ba

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Cannot log out with WezTerm running. (Same for Restart / Shut Down).

Details are in [To Reproduce].

First of all, please note that I am a non-English speaker so I am using DeepL to create the text...
I am sorry if I am expressing myself in some strange way.

### To Reproduce

Create release builds according to
https://wezfurlong.org/wezterm/install/source.html

step 1: Start using Terminal.app

```
cargo run --release --bin wezterm -- start
```
![step1](https://user-images.githubusercontent.com/30016220/211982320-28312eab-50da-4e09-bbaf-df9d75a01df3.png)

step 2: Log out from the OS menu

![step2](https://user-images.githubusercontent.com/30016220/211982333-308e3647-27a9-4c35-afc9-2056fd0dfdd1.png)

result:
No change as far as can be seen on the screen.
I was able to exit from the terminal using Ctrl-C.

![step-ng](https://user-images.githubusercontent.com/30016220/211982352-f1c3f63a-a7bd-4bea-ab04-7e9dfcc1dc37.png)

By the way, in `wezterm 20221218-103721-e70f9790`, after step2, we have the following.

![step-ok](https://user-images.githubusercontent.com/30016220/211982371-4d2e4182-f37d-4a3d-aa8f-eba6205a6d58.png)

If my identification is correct, there is something between these two builds.

### Configuration

no config

### Expected Behavior

Logout can be completed even while WezTerm is running, or...

That logout can be completed while WezTerm is still running,
or that the behavior described in [Anyting else] returns to the way it was before.

### Anything else?

Since a different time than this case, the application is not exiting after exit on the last pane.

(`exit_behavior` is not specified in wezterm.lua.)

Is this an intended change?
Or is this a related issue?

**Comment by wez** [comment]
This should be fixed now in `main`.  Probably!

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by CoralPink** [comment]
Thank you!!

I updated my regular wezterm from homebrew and now it logs me out properly.

<img width="372" alt="Screenshot 2023-01-13 at 11 36 05" src="https://user-images.githubusercontent.com/30016220/212226076-1111a28b-48eb-4b14-bf08-95901585d5b2.png">

by the way...
Was the behavior of the `exit` command that you wrote in [Anything else] the intended change? This one remained the same.

(Sorry if I missed checking the changelog...)

I really need to know this one thing🤔

**Comment by wez** [comment]
Ah, I didn't notice you ask:

> the application is not exiting after exit on the last pane.

Since adding the macOS native menubar, wezterm no longer closes after the last window is closed, which is more in line with other native macOS applications even though it's not my personal preference.

This is in preparation for supporting:
* https://github.com/wez/wezterm/issues/1751
* https://github.com/wez/wezterm/issues/2869

**Comment by CoralPink** [comment]
Thanks for your time.

This has been bothering me for a long time, as I don't like it either, but if that's what you intended, that's refreshing. Glad to hear you got the macOS sleep thing sorted out too! I'm sure @wez will have a good night's sleep too!

Thank you so much!!

**Comment by wez** [comment]
You're welcome!
Let's close this one!
