### ISSUE TITLE
Cannot change user var in tmux

### ISSUE THREAD

**Issue by XXiaoA** [wez/wezterm#2945]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Kde x11

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

As the docs https://wezfurlong.org/wezterm/config/lua/window-events/user-var-changed.html,  I tried to change my colorscheme by cli. But it only work outside the tmux

### To Reproduce

run `printf "\033]1337;SetUserVar=Nvim_Colorscheme=R3J1dmJveCBEYXJr\007"` in tmux (PS: R3J1dmJveCBEYXJr means "Gruvbox Dark")

### Configuration

```lua
local wezterm = require("wezterm")

wezterm.on("user-var-changed", function(window, pane, name, value)
    local overrides = window:get_config_overrides() or {}
    if name == "Nvim_Colorscheme" then
        overrides.color_scheme = value
    end
    window:set_config_overrides(overrides)
end)

return {}
```

### Expected Behavior

Change the colorscheme both inside and outside the tmux

### Logs

Debug Overlay
wezterm version: 20221119-145034-49b9839f
OpenGL version: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 4.6.0 NVIDIA 525.78.01
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

### Anything else?

https://user-images.githubusercontent.com/62557596/212010807-935b3fd1-bc2f-4262-a4d2-e58997d86c07.mp4

**Comment by wez** [comment]
Take a look at:
https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it

**Comment by XXiaoA** [comment]
Thx!
I tried do `printf "\033Ptmux;\033\033]1337;SetUserVar=Nvim_Colorscheme=R3J1dmJveCBEYXJr\007\033\\"` but it didn't work

**Comment by wez** [comment]
If the documented stuff works in wezterm without tmux, and you're only having trouble in tmux, then I suggest you follow up with the tmux folks to figure out how to get that passthru working correctly for this.

**Comment by XXiaoA** [comment]
Okay, thx.
