### ISSUE TITLE
Ctrl + Shift + R don't work in CharSelect mode

### ISSUE THREAD

**Issue by netherstar** [wez/wezterm#2947]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230109-162248-c19b6505

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

- Ctrl + Shift + R don't work in CharSelect mode (Ctrl + Shift + U)
- Search somethings and then moment on search result seem to be lag (example search `jj`, `jk`)

### Configuration

don't need

### Expected Behaviors
Cycle to the previous group of characters

**Comment by wez** [comment]
What do you expect to happen when you press CTRL-SHIFT-R?  It's not clear from this report what you expected to happen and what actually happened

**Comment by netherstar** [comment]
> What do you expect to happen when you press CTRL-SHIFT-R? It's not clear from this report what you expected to happen and what actually happened

It should cycle to the previous group of characters

**Comment by wez** [comment]
The issue is that `CTRL-SHIFT-R` is also registered as `ReloadConfiguration` by default, and that takes precedence over key actions in modals like charselect.  If you wanted to, you could use https://wezfurlong.org/wezterm/config/lua/keyassignment/DisableDefaultAssignment.html to remove that assignment.

I think picking a different key combination for this is probably a good idea.

Changing the key handling precedence of modals might be possible, but it needs some thought.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
