### ISSUE TITLE
Watery ripple on resize

### ISSUE THREAD

**Issue by dsvensson** [wez/wezterm#295]
When resizing the window, characters wobble between nicely rendered and not so nicely rendered. Maximizing looks bad.

Example of maximized: https://pasteboard.co/JvAwXd9.png

Example video of resizing: https://streamable.com/va5c67

In the video, the characters wobble on the x axis due to me resizing the window, not due to caffeine :)

This is wezterm from master, under Xorg @ Ubuntu 20.04.

**Comment by wez** [comment]
That's weird!  Could you share your config file?  My first guess is that this might be a rounding issue tickled by your configured font and font size.  Please also let me know which window manager is in use in case that might be relevant.

**Comment by dsvensson** [comment]
Reproducible without configuration, Ubuntu 20.04, GNOME 3.

**Comment by dsvensson** [comment]
Interesting - or sad. My other Ubuntu 20.04 towards the same monitor, but Nvidia 980 Ti instead of Nvidia 1650, does not exhibit this behavior. Sharp fonts no matter how I resize it. The ConfigInfo line from the logging is identical.

**Comment by wez** [comment]
I'm thinking that what you're seeing might be somehow specific to the drivers on that system; are you able to try switching between say the nouveau and the true nvidia drivers just to rule that out?

Another thing to try is setting `front_end = "Software"` in your config to use the llvmpipe software rasterizer and see if that also has the same problem; that would help understand which layer has the issue.

**Comment by wez** [comment]
(as an aside: what are you using to get the file/folder icons in your `ls` output?  is that using a special font or is it using one of the image protocols?)

**Comment by dsvensson** [comment]
That's [exa](https://github.com/ogham/exa). Tried adding `front_end = "Software"` but it's still initializing GL. Distortion remains.

**Comment by wez** [comment]
Does the `OpenGL initialized!` log line on stderr show different info when you add/remove `front_end = "Software"`?  (Also, that is one of the few options where you need to re-launch wezterm for changes to it to take effect).

**Comment by dsvensson** [comment]
```
$ cat ~/.wezterm.lua
return {
	front_end = "Software"
}
```

With and without config yields:
```
 2020-10-17T17:45:50.387Z INFO  window::egl                 > ConfigInfo { config: 0xcaf32d, alpha_size: Some(8), red_size: Some(8), green_size: Some(8), blue_size: Some(8), depth_size: Some(18), conformant: Some("OPENGL OPENGL_ES2 OPENGL_ES3 "), renderable_type: Some("OPENGL OPENGL_ES2 OPENGL_ES3 "), native_visual_id: Some(7e), surface_type: Some("PBUFFER PIXMAP WINDOW ") }
 2020-10-17T17:45:50.387Z INFO  window::egl                 > initialized libEGL.so.1
 2020-10-17T17:45:50.410Z INFO  wezterm::gui::renderstate   > compiling a prog with version 330
 2020-10-17T17:45:50.425Z INFO  wezterm::gui::renderstate   > compiling a prog with version 300 es
 2020-10-17T17:45:50.426Z ERROR wezterm::gui::termwindow    > OpenGL initialized! GeForce GTX 1650/PCIe/SSE2 OpenGL ES 3.2 NVIDIA 450.66 is_context_loss_possible=false
```

**Comment by wez** [comment]
Ah, it looks like it always finds the official nvidia libEGL.so.1 there.
If you `locate libEGL.so.1` I suspect that you'll have two different implementations.
You one of them should be the Mesa3D implementation.  You could try setting `LD_LIBRARY_PATH=/dir/holding/the/mesa/one` and see if that affects the behavior.

**Comment by dsvensson** [comment]
Ok, my Google-driven shader-skills made me attempt the following:

```diff
diff --git a/wezterm/src/gui/fragment.glsl b/wezterm/src/gui/fragment.glsl
index 15a8427c..de306307 100644
--- a/wezterm/src/gui/fragment.glsl
+++ b/wezterm/src/gui/fragment.glsl
@@ -1,4 +1,4 @@
-precision mediump float;
+precision highp float;

 in vec2 o_tex;
 in vec4 o_fg_color;
diff --git a/wezterm/src/gui/vertex.glsl b/wezterm/src/gui/vertex.glsl
index e635b14a..4e520be8 100644
--- a/wezterm/src/gui/vertex.glsl
+++ b/wezterm/src/gui/vertex.glsl
@@ -1,4 +1,4 @@
-precision mediump float;
+precision highp float;
 in vec2 position;
 in vec2 adjust;
 in vec2 tex;
```

And now it's rendering correctly. Is that a solution?

**Comment by wez** [comment]
That looks good to me; thanks!  My only reservation is compatibility with different versions of GL and whether it might be necessary to select between `highp` and `mediump` based on some runtime version.  I'll give your change a try on my various systems and see if any of those complain, and if not, I can apply it.   If you'd to have a commit with your name in this repo, you're welcome to open a PR :)
