### ISSUE TITLE
Launch as "externalTerminal" in Visual Studio Code

### ISSUE THREAD

**Issue by erf** [wez/wezterm#2954]
**Is your feature request related to a problem? Please describe.**

I'm working on a terminal app using Dart lang in Visual Studio Code where you are able to specify  a `launch.json` file with a  "console" property of "externalTerminal" to debug it there.

```
	"version": "0.2.0",
	"configurations": [
		{
			"name": "myApp",
			"request": "launch",
			"type": "dart",
			"program": "bin/myApp.dart",
			"console": "externalTerminal",
			"args": []
		}
	]
```

You are also able to specify which external terminal to use in settings or `vscode/settings.json` like:

```
"terminal.external.osxExec": "WezTerm.app",
```

If i try to run this i get the following:

```
Unable to start debugging: 'WezTerm.app' not supported
```

**Describe the solution you'd like**

I would like to be able to debug my console app using `WezTerm`

**Describe alternatives you've considered**

Using internal terminal app or `Terminal.app` .. no way ;)

**Additional context**

I build Wezterm from source `67ce66a5b`
I'm on macOS 13.1 (22C65)
Using Visual Studio Code Version: 1.74.3

Links:
https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch
https://code.visualstudio.com/docs/terminal/

**Comment by wez** [comment]
I think this is more of a question for the vscode folks? wezterm doesn't know anything about vscode, and it's up to vscode to launch wezterm appropriately if you want to run something and have it show in a wezterm window.

I think you need to engage with the vscode folks to find out what is involved in making it consider wezterm to be a supported external terminal.

Potentially related/relevant things on the wezterm side:

* https://github.com/wez/wezterm/issues/2871 allows associating wezterm with `.command` files on macOS, which is something that some other utilities use to launch scripts into your preferred terminal on macOS.
* https://github.com/wez/wezterm/issues/2416 might be required for vscode on windows, maybe?

But hopefully neither of those are needed and it's just a simple matter of teaching vscode how to run `wezterm start` with the appropriate parameters when you ask it to use wezterm for the external terminal.
