### ISSUE TITLE
Neovim Buffer Switch Support

### ISSUE THREAD

**Issue by MikePresman** [wez/wezterm#2956]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't use the native `<Ctrl+6>` vim/nvim keystroke to switch back and forth between buffers. Works in gnome-terminal but not wezterm

**Describe the solution you'd like**
<Ctrl-6> to work natively in wezterm

**Describe alternatives you've considered**
An alternative is a neovim custom keymap just for wezterm

**Additional context**
Open two files in neovim in gnome-terminal and do `<Ctrl-6>` you'll see you switch back and forth between these two "files" (buffers). This is not working in wezterm out of the box.

**Comment by wez** [comment]
This sounds like it might be a keyboard related configuration issue in your environment.  Please share more information about:

* Your keyboard layout
* Your IME (if applicable)
* Whether setting `use_ime=false` changes this behavior
* The operating system and window environment you are using (open the debug overlay: press `CTRL-SHIFT-L`, and copy and paste what is shown into this issue)
* What is logged when you press CTRL-6 when debug_key_events is enabled: https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html

**Comment by MikePresman** [comment]
I sincerely apologize, I overlooked something ridiculous.
I had this
```
 {key="6", mods="CTRL", action=act{ActivateTab=5}},
```
which caused the issue.

Thank you wez for all your continued help and support. Please feel free to close.
