### ISSUE TITLE
Cannot map CTRL-/ in neovim with wezterm

### ISSUE THREAD

**Issue by boltlessengineer** [wez/wezterm#2960]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230113-210839-14c749e5

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I can't map some keymaps like `CTRL-/` and `CTRL-Q` in neovim. Works fine with other terminal emulators (kitty, iterm, alacritty).

### To Reproduce

1. Open neovim (v0.8.2) in wezterm
2. type `i` to begin insert-mode
3. type `CTRL+K`. You will see `?` mark is shown at cursor position.
4. type `CTRL+/`

### Configuration

no config

same thing happens with `disable_default_key_bindings` option.

### Expected Behavior

`<C-k>` in vim's insert mode shows the keycode of typed key.

So after step 4, string `<C-/>` should be printed. At least in kitty and iTerm2, it works like that.

But in wezterm, nothing happens with Mac's pop sound.

Same thing happens when typed `CTRL+Q` in step 4, but no pop sound in this case.

**Comment by wez** [comment]
Possibly the same thing as:
* https://github.com/wez/wezterm/issues/2845

Please try enabling debug_key_events as shown in that issue and let me know what you see

**Comment by wez** [comment]
Ah, sorry, that issue is not applicable to macOS, but the key event debugging will still be useful.

On macOS I'd suggest setting `use_ime=false` to see if that changes the behavior.
This issue is perhaps relevant:
* https://github.com/wez/wezterm/issues/2630

**Comment by boltlessengineer** [comment]
It seems to be a same issue. After adding `use_ime=false`, both `CTRL-/` and `CTRL-Q` works fine. Closing the issue.

But because I'm not English-only user, able to use IME is pretty important to me. Is this problem planned to fixed?

**Comment by wez** [comment]
I'd like to fix it; just haven't had time to do it so far.
