### ISSUE TITLE
Switching between windows with a key-binding (e.g. Alt-Command-1-9)

### ISSUE THREAD

**Issue by alfa07** [wez/wezterm#2973]
**Is your feature request related to a problem? Please describe.**
iTerm supports switching between windows with Alt-Command-1-9 which is very convenient for multi-monitor setups.

**Describe the solution you'd like**
Add actions parallel to those of ActivateTab(N), e.g. ActivateWindow(N)

**Describe alternatives you've considered**
I've tried to implement it given current approaches but it seems API lacks focus() function

**Comment by wez** [comment]
`main` now has:

* [wezterm.gui.gui_windows()](https://wezfurlong.org/wezterm/config/lua/wezterm.gui/gui_windows.html)
* [window:focus()](https://wezfurlong.org/wezterm/config/lua/window/focus.html)
* [ActivateWindow](https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateWindow.html)
* [ActivateWindowRelative](https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateWindowRelative.html)
* [ActivateWindowRelativeNoWrap](https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateWindowRelativeNoWrap.html)

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the changes and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wez** [comment]
Important note: Wayland does not allow applications to change the focused window, so these actions will not work on Wayland.

**Comment by alfa07** [comment]
I am wondering how I can get window's index in `format-window-title` event:
```lua
wezterm.on('format-window-title', function(tab, pane, tabs, panes, config)
...
end)
```

**Comment by wez** [comment]
There isn't a direct way to map back to it, but you could probably use [wezterm.gui.gui_windows()](https://wezfurlong.org/wezterm/config/lua/wezterm.gui/gui_windows.html) to get the complete list of windows in the same consistent order, something like:

```lua
function window_index_from_tab_info(tab_info)
  for idx, window in pairs(wezterm.gui.gui_windows()) do
    if tab_info.window_id == window:window_id() then
      return idx - 1 -- lua indices are 1-based, but we want 0-based
   end
   return 0 -- didn't find it, guess?
end
```
