### ISSUE TITLE
wezterm chokes on spaces in path

### ISSUE THREAD

**Issue by t-bltg** [wez/wezterm#2975]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Unrelated (`xubuntu`), but:
```
$ inxi -Sx
System:
  Host: t5600 Kernel: 5.15.0-58-generic x86_64 bits: 64 compiler: gcc
    v: 11.3.0 Desktop: Xfce 4.16.0 Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
```

### WezTerm version

20230115-214820-a2e027df

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`wezterm` chokes when started from a path with spaces, on `linux`.

### To Reproduce

```bash
user@foo:~$ mkdir '/tmp/evil path'
user@foo:~$ cd '/tmp/evil path'
user@foo:/tmp/evil path$ wezterm
15:09:50.935  WARN   mux::domain > Directory "/tmp/evil" is not readable and will not be used for the command we are spawning: No such file or directory (os error 2)
15:09:50.936  ERROR  wezterm_gui > Unable to spawn path because it doesn't exist on the filesystem and was not found in PATH; terminating
```

Note that the path is truncated: `/tmp/evil` instead of `/tmp/evil path`, causing the spawn failure.

### Configuration

no config

### Expected Behavior

`wezterm` starts correctly.

**Comment by wez** [comment]
I can't reproduce this. Are you sure you don't have something in your config file?

Note that wezterm will start in your home directory by default and shouldn't care about a path under `/tmp`, so there is presumably some other configuration being used in your environment.

Is `wezterm` an alias for something else on your system?

**Comment by t-bltg** [comment]
Crap, I removed to config files before posting the issue, but you were right an alias got in the way.

Very much sorry for the noise !
