### ISSUE TITLE
Set initial window position before a window is created

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#2976]
**Is your feature request related to a problem? Please describe.**
From https://github.com/wez/wezterm/issues/1794 you can set up the position of a newly launched WezTerm window with `gui-startup` and `set_position` lua callbacks in your config, which is great and useful for many other things dealing with moving/resizing a window!
However, just for the __initial loading__ part the way loading works is that these options are applied only __AFTER__ the window had been created in it's __default__ location, so you get an annoying visual "__jump__" of the window from it's default location to the user configured location
This usually doesn't happen in other apps that accept initial window placement/size coordinates (e.g., iTerm, where the window is created at the user configured coordinates right away)

**Describe the solution you'd like**
The initial window coordinates should be read before a window is created

**Describe alternatives you've considered**
I've thought about overriding the gui app with some wrapper that passes the coordinates as cli parameters, but that'd be a rather brittle solution (with integration with various app switcher/keybinding utilities and what not) with potential extra latency, so didn't attempt it

**Additional context**
None

**Comment by wez** [comment]
This should be implemented now in `main`; `wezterm.mux.spawn_window` and `SpawnCommandInNewWindow` now both accept a position field that can be used to set the initial position:

* https://wezfurlong.org/wezterm/config/lua/SpawnCommand.html
* https://wezfurlong.org/wezterm/config/lua/wezterm.mux/spawn_window.html#position

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by eugenesvk** [comment]
Thanks for a quick fix, this seems to be working! Modified from 
```lua
wezterm.on('gui-startup', function(cmd) -- set startup Window position
  local tab, pane, window = mux.spawn_window(cmd or{})
  window:gui_window():set_position(0, 0)
end)

```
to
```lua
wezterm.on('gui-startup', function(cmd) -- set startup Window position
  local tab, pane, window = mux.spawn_window(cmd or
    {position={x=0,y=0}}
  )
end)
```

But it seems the coordinates work differently not accounting for the macOS system menu bar: `x=0,y=0` fails with the window opened at the its defaults, and any value for `y` below `46` (which I guess it the height of the system menu bar) adds a blank offset between the menu bar and the wezterm window.
So `x=0,y=46` in the new system works like `x=0,y=0` in the old system

Might be nice if these were consistent and the new system also accounted for the menu bar

**Comment by wez** [comment]
I've fixed up the initial window positioning to use the same technique as `window:set_position`

**Comment by eugenesvk** [comment]
Seems to be working fine! Thanks again
