### ISSUE TITLE
wezterm fail to start

### ISSUE THREAD

**Issue by Sherlock-Holo** [wez/wezterm#2992]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME with mutter

### WezTerm version

20230120-200449-133a47a2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

wezterm report

> 02:23:32.381  ERROR  wezterm_gui::frontend > Failed to create window: with_egl_lib failed: with_egl_lib(libEGL.so.1) failed: egl Initialize: BAD_ACCESS, with_egl_lib(libEGL.so) failed: egl Initialize: BAD_ACCESS, with_egl_lib(libEGL.so.1) failed: egl Initialize: BAD_ACCESS, with_egl_lib(libEGL.so) failed: egl Initialize: BAD_ACCESS

### To Reproduce

start wezterm

### Configuration

```lua
local wezterm = require 'wezterm'
local act = wezterm.action


local mykeys = {}
for i = 1, 9 do
  -- ALT + number to activate that tab
  table.insert(mykeys, {
    key = tostring(i),
    mods = 'ALT',
    action = act.ActivateTab(i - 1),
  })
end

-- move tab
table.insert(mykeys, { key = '{', mods = 'SHIFT|ALT', action = act.MoveTabRelative(-1) })
table.insert(mykeys, { key = '}', mods = 'SHIFT|ALT', action = act.MoveTabRelative(1) })

return {
    keys = mykeys,

    window_padding = {
        left = 0,
        top = 0,
        bottom = '0.1cell',
    },

    enable_scroll_bar = true,

    animation_fps = 165,
    max_fps = 165,
    
    cursor_blink_rate = 900,
    default_cursor_style = 'BlinkingBlock',
    
    initial_rows = 56,
    initial_cols = 165,
    
    bold_brightens_ansi_colors = true,
    font = wezterm.font_with_fallback {
        'Cascadia Code PL',
        {family="Noto Sans CJK SC", weight="Medium"},
    },

    font_rules = {
        {
            intensity = 'Bold',
            italic = false,
            font = wezterm.font_with_fallback {
              {family="Cascadia Code PL", weight="Bold"},
              {family="Noto Sans CJK SC", weight="Bold"}
            },
        },
        {
            italic = true,
            font = wezterm.font_with_fallback {
              {family="Cascadia Code PL", weight="Bold", italic = true},
              {family="Noto Sans CJK SC", weight="Bold", italic = true}
            },
        },
    },

    font_size = 14,
--     font_antialias = 'Subpixel',
    
    color_scheme = 'My Solarized Dark',
    colors = {
        selection_fg = 'none',
        selection_bg = 'rgba(50% 50% 50% 50%)',
    },
}
```

### Expected Behavior

start normally

### Logs

> 02:23:32.381  ERROR  wezterm_gui::frontend > Failed to create window: with_egl_lib failed: with_egl_lib(libEGL.so.1) failed: egl Initialize: BAD_ACCESS, with_egl_lib(libEGL.so) failed: egl Initialize: BAD_ACCESS, with_egl_lib(libEGL.so.1) failed: egl Initialize: BAD_ACCESS, with_egl_lib(libEGL.so) failed: egl Initialize: BAD_ACCESS

**Comment by Sherlock-Holo** [comment]
after reboot the archlinux, wezterm can run again, before reboot, I update these packages

> [2023-01-22T02:22:52+0800] [ALPM] upgraded docker (1:20.10.22-1 -> 1:20.10.23-1)
> [2023-01-22T02:22:52+0800] [ALPM] upgraded libx11 (1.8.3-5 -> 1.8.3-6)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded nvidia-utils (525.78.01-1 -> 525.85.05-1)
> [2023-01-22T02:22:53+0800] [ALPM-SCRIPTLET] If you run into trouble with CUDA not being available, run nvidia-modprobe first.
> [2023-01-22T02:22:53+0800] [ALPM-SCRIPTLET] If you use GDM on Wayland, you might have to run systemctl enable --now nvidia-resume.service
> [2023-01-22T02:22:53+0800] [ALPM] upgraded lib32-nvidia-utils (525.78.01-1 -> 525.85.05-1)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded libgit2 (1:1.5.0-2 -> 1:1.5.1-2)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded libxnvctrl (525.78.01-1 -> 525.85.05-1)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded mold (1.9.0-1 -> 1.10.0-1)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded nvidia-open (525.78.01-13 -> 525.85.05-1)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded nvidia-settings (525.78.01-1 -> 525.85.05-1)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded pipewire-media-session (1:0.4.1-2 -> 1:0.4.2-1)
> [2023-01-22T02:22:53+0800] [ALPM-SCRIPTLET] >>> pipewire-media-session is deprecated and will soon be removed from the
> [2023-01-22T02:22:53+0800] [ALPM-SCRIPTLET]     repositories. Please use 'wireplumber' instead.
> [2023-01-22T02:22:53+0800] [ALPM] upgraded python-trove-classifiers (2023.1.12-1 -> 2023.1.20-1)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-common (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-audio-alsa (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-audio-dbus (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-audio-jack (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-audio-oss (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-audio-pa (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-audio-sdl (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-ui-opengl (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-ui-spice-core (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-audio-spice (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-block-curl (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-block-dmg (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-block-nfs (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-block-ssh (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-chardev-spice (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-display-qxl (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-display-virtio-gpu (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-display-virtio-gpu-gl (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-display-virtio-gpu-pci (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-display-virtio-gpu-pci-gl (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-display-virtio-vga (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-display-virtio-vga-gl (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-s390x-virtio-gpu-ccw (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-usb-host (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-usb-redirect (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-hw-usb-smartcard (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-img (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-pr-helper (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-system-x86-firmware (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-system-x86 (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-tools (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-ui-curses (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-ui-dbus (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-ui-egl-headless (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-ui-gtk (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-ui-sdl (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-ui-spice-app (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-vhost-user-gpu (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-virtiofsd (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded qemu-desktop (7.2.0-1 -> 7.2.0-3)
> [2023-01-22T02:22:53+0800] [ALPM] upgraded wezterm-git (20230119.205418.9a76a540-1 -> 20230120.200449.133a47a2-1)

maybe updating `libx11` or `nvidia-utils` breaked the wezterm?

**Comment by wez** [comment]
Sounds like your system was in an inconsistent state before you rebooted; that can happen when upgrading the drivers.
Since things are working now, I think we can close this?

**Comment by Sherlock-Holo** [comment]
yes, this issue is completed
