### ISSUE TITLE
position flag doesn't appear to work under sway

### ISSUE THREAD

**Issue by salameme** [wez/wezterm#2993]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

sway version 1.8

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Trying to set the position of the window using `wezterm start --class floating --position 10,10` fails to set the position.

### To Reproduce

Add this to your sway configuration:

```
for_window [app_id="floating"] floating enable
```

Then run in a terminal:
```console
$ wezterm start --class floating --position 10,10
```

The window will start in the center of the screen instead of the top-left corner.

### Configuration

no config

### Expected Behavior

The position flag should work as described and change the starting position of the window (unless that is not possible under Wayland, in that case the flag should document that in `--help`)

### Logs

Debug Overlay
wezterm version: 20221119-145034-49b9839f
OpenGL version: AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.49, 6.1.6-arch1-3) 4.6 (Compatibility Profile) Mesa 22.3.3
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

**Comment by salameme** [comment]
As a workaround for those using sway you can do:

```swayconfig
for_window [app_id="floating terminal"] {
    floating enable
    # `man sway(5)` move [absolute] position <pos_x> [px|ppt] <pos_y> [px|ppt]
    move position 10 px 10 px
}
```

But if this isn't supposed to work under wayland it should be documented

**Comment by wez** [comment]
Wayland (the protocol) doesn't allow applications to set the window position.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/window/set_position.html documented this for the lua api, but I just pushed an extra line of text to the `--help` output to make this less surprising.
