### ISSUE TITLE
Hidden mouse pointer is not always getting vissible when it should 

### ISSUE THREAD

**Issue by snaggen** [wez/wezterm#2995]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20230118-232519-5dbdd36a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When using hide pointer when typing, the mouse gets hidden, but sometime it doesn't get visible until it is moved over another application. 

I was asked to reproduce this in a comment to #2943 , and it seems to work as it should for a regular terminal, but when I split the terminal to have 2 panes side by side I see this problem. 
To reproduce the issue I
1. Split the terminal to get side by side panes.
2. Move the mouse over the right pane and click.
3. Type in the right pane so the mouse is hidden
4. Move the mouse to make it vissible. Now it should be visible but it is not.

When I try to find a reliable way to always reproduce this, I notice that sometimes it actually seems to work. However, it fails more often than not, so I hope some developer is actually able to reproduce this by fiddling around a bit. 

### Configuration

no config

### Expected Behavior

Mouse should get visible as soon as the mouse is moved

**Comment by wez** [comment]
Closing in favor of https://github.com/wez/wezterm/issues/3334
