### ISSUE TITLE
Do something about the Bell

### ISSUE THREAD

**Issue by wez** [wez/wezterm#3]
Currently we don't handle this at all, so we end up printing `unhandled vte execute 7` to stderr.
There are varying degrees of support:

* Print `bell!` to stderr instead of letting it hit the unhandled case.  This is lameish.
* Don't print anything to stderr at all, but do nothing.  This is logically equivalent to explicitly configuring that the bell be disabled.
* Hook up an audible bell tone.  This definitely should be something that we can turn off because I totally hate audible bells.
* Hook up a visual bell rendering of some kind.  There are simplistic approaches of forcing the inverse video bit on, but I'd like something more tasteful and less bright.  This also definitely needs an option to turn it off because I hate visual bells too, but they've always been super bright and distracting.
* Teach tabs about being in an alert state and render some kind of bell graphic in the tab UI that sticks until acknowledged in some way
* On systems that allow bouncing icons in the dock area, add configurable support for doing that
* Generate a system "toast" notification

others?

**Comment by wez** [comment]
Having laid some groundwork for https://github.com/wez/wezterm/issues/489 I think the plan here is:

* Add `ToastNotificationHandler::bell` alongside [ToastNotificationHandler::show_notification](https://github.com/wez/wezterm/blob/main/term/src/terminal.rs#L50)
* Make [MuxNotification::ToastNotification](https://github.com/wez/wezterm/blob/main/mux/src/lib.rs#L38) accept an `enum` that can represent the notification or a `Bell` variant
* At the GUI layer ([start here](https://github.com/wez/wezterm/blob/main/wezterm-gui/src/gui/mod.rs#L67)) do something about indicating that the bell was triggered.

The GUI layer changes could be based on some options:

* Behavior when the tab containing the pane with the bell has focus:
  * Visual bell "flash"
  * Bell noise / system alert
  * Toast notification
  * Nothing
* Behavior when the tab containing the pane with the bell doesn't have focus:
  * Bell noise / system alert
  * Toast Notification
  * Nothing
  * Bounce icon in dock
  * Annotate tab title with a bell status symbol.  Focusing the tab will clear that state (maybe after a configurable delay?)

Panes make it a bit awkward to indicate which pane has the bell state, not sure if we need to do something about that, given that we've gotten this far without anyone making a fuss about the bell doing nothing.

**Comment by unrelentingtech** [comment]
With a custom lua hook it would be possible for users to do anything, like hook up an actual physical bell over USB… :D

**Comment by klamonte** [comment]
With the reverse_video flag fixed for #904, you now have a way to quickly flash the screen.
