### ISSUE TITLE
Dead keys not working on macOS

### ISSUE THREAD

**Issue by mardukbp** [wez/wezterm#300]
## Describe the bug

With the Spanish ISO or the U.S. International keyboard layout pressing `´` + `a` should insert `á`. Instead `a` is inserted.

## Environment (please complete the following information):

 - OS: macOS 10.14.6
 - Version: wezterm 20200909-002054-4c9af461-187-g2364b0a2

## To Reproduce

1. Select any of the above mentioned keyboard layouts.
2. Launch WezTerm.app and press the keys mentioned in the description.

## Configuration

```lua
local wezterm = require 'wezterm';
return {
  font_size = 14.0,
  font = wezterm.font("Fira Code"),
  keys = {
    {key="F", mods="SHIFT|CTRL", action="Nop"},
    {key="F", mods="SHIFT|CTRL", action=wezterm.action{Search={CaseInSensitiveString=""}}},
  }
}
```

## Expected behavior

It should be possible to insert accented characters using dead keys, just like in Terminal.app.

## Screenshots

None.

## Session Recording

None.

## Additional context

None.

**Comment by wez** [comment]
Not sure if this is an ideal solution, but you could try this:
https://wezfurlong.org/wezterm/config/keys.html?highlight=use_ime#macos-and-the-input-method-editor-ime

**Comment by mardukbp** [comment]
Setting `use_ime=true` solves it. Thank you @wez! Maybe the documentation should mention that this setting affects the use of dead keys.

**Comment by wez** [comment]
Yep; I honestly had never considered dead keys on macOS previously.
I've pushed an update for the docs that mentions them.

**Comment by mardukbp** [comment]
Perfect! Thanks a lot!
