### ISSUE TITLE
<home> <end> keys don't work inside neovim inside tmux

### ISSUE THREAD

**Issue by kiyoon** [wez/wezterm#3003]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20230123-190635-dd28dbae

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

home and end keys do not work in neovim when using TERM=wezterm terminfo inside tmux.

My tmux configuration:

```tmux
# 256 colour
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
```

I tried to change the default-terminal to `wezterm` but it introduces another problem: <home> and <end> doesn't work in zsh and the cursor changes to box (not |)

If I don't pass `TERM=wezterm` it works well in neovim.

### Configuration

I don't think any config is relevant here.

```lua
local wezterm = require("wezterm")

return {
	color_scheme = "Dracula (Official)",

	font = wezterm.font_with_fallback({
		"JetBrainsMono Nerd Font",
		"Fira Code Nerd Font",
	}),
	font_size = 14.3,

	hyperlink_rules = {
		-- Linkify things that look like URLs and the host has a TLD name.
		-- Compiled-in default. Used if you don't specify any hyperlink_rules.
		{
			regex = "\\b\\w+://[\\w.-]+\\.[a-z]{2,15}\\S*\\b",
			format = "$0",
		},

		-- linkify email addresses
		-- Compiled-in default. Used if you don't specify any hyperlink_rules.
		{
			regex = [[\b\w+@[\w-]+(\.[\w-]+)+\b]],
			format = "mailto:$0",
		},

		-- file:// URI
		-- Compiled-in default. Used if you don't specify any hyperlink_rules.
		{
			regex = [[\bfile://\S*\b]],
			format = "$0",
		},

		-- Linkify things that look like URLs with numeric addresses as hosts.
		-- E.g. http://127.0.0.1:8000 for a local development server,
		-- or http://192.168.1.1 for the web interface of many routers.
		{
			regex = [[\b\w+://(?:[\d]{1,3}\.){3}[\d]{1,3}\S*\b]],
			format = "$0",
		},

		-- Make task numbers clickable
		-- The first matched regex group is captured in $1.
		-- {
		-- 	regex = [[\b[tT](\d+)\b]],
		-- 	format = "https://example.com/tasks/?t=$1",
		-- },

		-- Make username/project paths clickable. This implies paths like the following are for GitHub.
		-- ( "nvim-treesitter/nvim-treesitter" | wbthomason/packer.nvim | wez/wezterm | "wez/wezterm.git" )
		-- As long as a full URL hyperlink regex exists above this it should not match a full URL to
		-- GitHub or GitLab / BitBucket (i.e. https://gitlab.com/user/project.git is still a whole clickable URL)
		{
			regex = [[["]?([\w\d]{1}[-\w\d]+)(/){1}([-\w\d\.]+)["]?]],
			format = "https://www.github.com/$1/$3",
		},
	},

	-- undercurl becomes ugly if underline_position < -4
	underline_position = -4,
	keys = {
		{
			key = "Enter",
			mods = "ALT",
			action = wezterm.action.DisableDefaultAssignment,
		},
	},
}
```

**Comment by wez** [comment]
I'm not clear on what term is set to or where in your configuration.

The way things should be configured is:

The value of `TERM` should be either `xterm-256color` or `wezterm` (the latter only if you have installed the wezterm terminfo file) when you launch `tmux`, so that `tmux` knows what terminal it is interacting with and so it can translate accordingly.

For programs spawned inside tmux, `TERM` must be set to `tmux-256color` as that is the terminal which they communicating with.  It is not valid to set `TERM` to `xterm-256color` or `wezterm` for processes running inside `tmux`.

**Comment by kiyoon** [comment]
Thanks for the clear explanation. I was putting TERM to wezterm for nvim process and it was the problem.

I added this in `wezterm.lua`  
```lua
  term = 'wezterm',
```

And now `echo $TERM` prints `wezterm` outside tmux.

This should be in `.tmux.conf`  
```tmux
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
```

`echo $TERM` prints `tmux-256color inside tmux.  
Finally, do not change the TERM variable for processes separately.

**Comment by kiyoon** [comment]
Out of curiosity, is it not valid to set `set -g default-terminal "xterm-256color"`? I saw many people doing this in tmux configuration. And also in iTerm2 tmux-256color didn't work and I had to use `xterm-256color`.

**Comment by kiyoon** [comment]
I'm sorry, but my configuration introduced another problem. Now in neovim I can use home and end keys, but it does not show undercurl. Why is this happening?

**Comment by kiyoon** [comment]
I originally followed [here](https://wezfurlong.org/wezterm/faq.html?highlight=undercurl#how-do-i-enable-undercurl-curly-underlines) to set the undercurl. And I believe this is setting the process TERM value to wezterm?

Which the explicit `TERM=wezterm` the undercurl works, however the home and end keys don't

**Comment by wez** [comment]
In terms of reaching a resolution on this issue, can you remove `tmux` from the equation?

I'm interested to hear whether the home/end keys work for you when using `TERM=wezterm` and the default `TERM=xterm-256color` when you run nvim directly in wezterm.

If they both work outside of tmux, then I think you'll need to follow up with the tmux folks to troubleshoot your tmux configuration.

**Comment by kiyoon** [comment]
Yes, it works outside of tmux.

Based on your description I think I configured it correctly. `wezterm.lua` has `term = "wezterm"` and setting `tmux-256color` to tmux. I guess I need to talk to tmux folks instead
