### ISSUE TITLE
Some emojis are too small

### ISSUE THREAD

**Issue by kiyoon** [wez/wezterm#3004]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20230123-190635-dd28dbae

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The cloud, railway, film emojis are smaller than others.  
![image](https://user-images.githubusercontent.com/12980409/214350101-b1cac393-2ab4-40bb-b6aa-46cfa60e4e74.png)

Same happens outside tmux as well.

### To Reproduce

🛤️ 📽️ ☁

### Configuration

```lua
local wezterm = require("wezterm")

return {
	color_scheme = "Dracula (Official)",

	font = wezterm.font_with_fallback({
		"JetBrainsMono Nerd Font",
		"Fira Code Nerd Font",
	}),
	font_size = 14.3,

	hyperlink_rules = {
		-- Linkify things that look like URLs and the host has a TLD name.
		-- Compiled-in default. Used if you don't specify any hyperlink_rules.
		{
			regex = "\\b\\w+://[\\w.-]+\\.[a-z]{2,15}\\S*\\b",
			format = "$0",
		},

		-- linkify email addresses
		-- Compiled-in default. Used if you don't specify any hyperlink_rules.
		{
			regex = [[\b\w+@[\w-]+(\.[\w-]+)+\b]],
			format = "mailto:$0",
		},

		-- file:// URI
		-- Compiled-in default. Used if you don't specify any hyperlink_rules.
		{
			regex = [[\bfile://\S*\b]],
			format = "$0",
		},

		-- Linkify things that look like URLs with numeric addresses as hosts.
		-- E.g. http://127.0.0.1:8000 for a local development server,
		-- or http://192.168.1.1 for the web interface of many routers.
		{
			regex = [[\b\w+://(?:[\d]{1,3}\.){3}[\d]{1,3}\S*\b]],
			format = "$0",
		},

		-- Make task numbers clickable
		-- The first matched regex group is captured in $1.
		-- {
		-- 	regex = [[\b[tT](\d+)\b]],
		-- 	format = "https://example.com/tasks/?t=$1",
		-- },

		-- Make username/project paths clickable. This implies paths like the following are for GitHub.
		-- ( "nvim-treesitter/nvim-treesitter" | wbthomason/packer.nvim | wez/wezterm | "wez/wezterm.git" )
		-- As long as a full URL hyperlink regex exists above this it should not match a full URL to
		-- GitHub or GitLab / BitBucket (i.e. https://gitlab.com/user/project.git is still a whole clickable URL)
		{
			regex = [[["]?([\w\d]{1}[-\w\d]+)(/){1}([-\w\d\.]+)["]?]],
			format = "https://www.github.com/$1/$3",
		},
	},

	-- undercurl becomes ugly if underline_position < -4
	underline_position = -4,
	keys = {
		{
			key = "Enter",
			mods = "ALT",
			action = wezterm.action.DisableDefaultAssignment,
		},
	},
}
```

**Comment by erf** [comment]
I noticed the [red heart emoji](https://emojipedia.org/red-heart/) ❤️ (code points [10084, 65039]) only takes up 1 column in the terminal, whilst on other terminals like the iTerm2 and Terminal app on macOS it takes up 2 column spaces.

`wcswidth` reports it to be 2 columns, in addition to some other packages i tried.

The mismatch in size messes up the cursor position on a terminal app i'm writing

**Comment by wez** [comment]
The interpretation of these in wezterm is determined by the currently selected https://wezfurlong.org/wezterm/config/lua/config/unicode_version.html

`\u{2764}` is the dingbats heavy black heart, which predates emoji by a long time. It is defined as having width 1.

The sequence `\u{2764}\u{fe0f}` modifies that with an emoji presentation variation selector. That sequence has width 2, starting in unicode version 14.

**Comment by kiyoon** [comment]
I see. Thanks for the explanation. At the time of writing I saw that Gnome terminal was rendering them alright, so I thought it was maybe a bug. But later I saw that Windows Terminal really messes up even more and breaks everything. The last thing I want is things breaking just because of some emojis, so I just removed the problematic ones now.

But the annoying part is I don't know if they're problematic before trying out with multiple terminal emulators so it's hard to choose an emoji in my scripts. I always thought I should avoid emojis because of compatibility reasons for a long time, but recently I adopted them thinking it might be stable by now. It sounds like they're still changing the standard and not necessarily stable yet. Thanks for the insight.

**Comment by erf** [comment]
Thanks for the explanation! The heart is now 2 cols wide looking good. Would it be applicable to update the default unicode version to 14? In the latest macOS update unicode version 15 is supported, but i understand if this is a problem for older hardware. Not sure how well supported unicode 14 is on various OS'es 🤔

**Comment by wez** [comment]
I've had more people file bugs about character widths when 14 was previously the default than I've had since I set it back down to 9.  I'm going to wait and see if we get more people asking about this before changing the default.

**Comment by erf** [comment]
Sorry to hijack this thread, but i have another question @wez if you don't mind. I now understand the variation selector that some Unicode characters use to determine if it should be presented as text VS15 (0xFE0E) or emoji VS16 (0xFE0F). Although there are still some characters that only have a single code point but can have a "default presentation" of either text or emoji, like the ones mentioned in [Miscellaneous_Technica](https://en.wikipedia.org/wiki/Miscellaneous_Technical#References). I wonder if you know of a document which lists ALL "default presentation" styles for Unicode characters, in case they have only one code point and obviously don't have the variation selector, so that i can figure out which width i can assume used for these characters when rendered in the terminal. How do you determine how to render these characters? (have not digged into the source yet) Thanks!

**Comment by wez** [comment]
That information comes from the unicode character database (UCD).
https://github.com/BurntSushi/ucd-generate is a tool that can generate various tables from the database and Emoji_Presentation is one of them.
