### ISSUE TITLE
Add option to SwapWithActive to keep focus in moved pane

### ISSUE THREAD

**Issue by brandonchinn178** [wez/wezterm#3014]
**Is your feature request related to a problem? Please describe.**
`PaneSelect { mode = 'SwapWithActive' }` is super nice, but it's a bit disorienting that the focus isn't in the same pane.

**Describe the solution you'd like**
It would be great if there could be an additional `keep_focus_after_swap` parameter to the `PaneSelect` action. Alternatively, the Lua API could expose any of the following functions:
1. Add `MuxTab:select_pane()`: shows alphabet, waits for input, and returns the selected pane
2. Change `Window:perform_action()` to return metadata about the action; `window:perform_action(PaneSelect)` could then return which pane was selected

**Describe alternatives you've considered**

**Additional context**

**Comment by wez** [comment]
In `main` you can now use `mode = 'SwapWithActiveKeepFocus'`

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by brandonchinn178** [comment]
Seems to work great, thanks! However, both `SwapWithActive` and `SwapWithActiveKeepFocus` are buggy with unix domains (not new, I see this in the latest release too). I assume you want that in a separate issue?

**Comment by wez** [comment]
Yes, a separate issue please. It may already be tracked; search for existing multiplexer related issues first!
