### ISSUE TITLE
Key-bindings with `CMD` modifier don't trigger events as expected

### ISSUE THREAD

**Issue by jdhoffa** [wez/wezterm#3019]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

Yabai: https://github.com/koekeishiya/yabai

### WezTerm version

20230126-170021-36519f0d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Binding a `wezterm.action.SendString` to any `CMD + key` binding, doesn't trigger the action. 
I have tried different variations of keys, and actions  with the `CMD` modifier, and none of them seem to work.

I notice the issue template asks for any additional window management software used, so just to pre-empt, the key combination is also not bound to anything in my Yabai config. 

Additional info relating to a few of the open issues I have read:
* My keyboard layout is U.S. (only)
* I have set `use_ime = false` in my config

Note: `CMD|SHIFT` modifiers work as expected. 

### To Reproduce

``` bash
# maybe
brew install koekeishiya/formulae/yabai

# use config file attached

tmux new-session
```

and try `CMD+E` keybinding. 

### Configuration

``` lua
local wezterm = require 'wezterm'

return {
  default_prog = {"/opt/homebrew/bin/fish"},
  term = 'wezterm',
  keys = {
    {
      -- split tmux window vertically
      key = "E",
      mods = "CMD",
      action = wezterm.action.SendString '\x02\"'
    },
    {
      -- split tmux window horizontally
      key = "E",
      mods = "CMD|SHIFT",
      action = wezterm.action.SendString "\x02%"
    }
  },
  use_ime = false,
  debug_key_events = true
}
```

### Expected Behavior

I expect that pressing `CMD+E` while to trigger appropriate SendString action (in a tmux session, it should split panes vertically)

### Logs

I included in the log both the functional `CMD+SHIFT+E` keybind, and the non-functional `CMD+E` keybind, for comparison. 

``` log
14:14:59.436  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('E'), modifiers: SHIFT | SUPER, phys_code: Some(E), raw_code: 14, repeat_count: 1, key_is_down: true, handled: Handled(false) }
14:14:59.436  INFO   wezterm_gui::termwindow::keyevent     > Char('E') SHIFT | SUPER -> perform SendString("\u{2}%")
14:15:01.206  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('e'), modifiers: SUPER, phys_code: Some(E), raw_code: 14, repeat_count: 1, key_is_down: true, handled: Handled(false) }
14:15:01.207  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('e'), modifiers: SUPER, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Char('e'), modifiers: SUPER, phys_code: Some(E), raw_code: 14, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
14:15:01.207  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('e') mods=SUPER
14:15:01.207  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "e", Char('e') SUPER
```

### Anything else?

I have read through a similar open issues (e.g. https://github.com/wez/wezterm/issues/2630) and followed most of the advice found there to no avail. That said, apologies if this ends up being a duplicate of something already open.

**Comment by wez** [comment]
If you want <kbd>CMD</kbd> + <kbd>e</kbd> (no shift pressed), to trigger the action then you should use a lowercase value for `key`:

```lua
    {
      -- split tmux window vertically
      key = "e",  -- make this lowercase
      mods = "CMD",
      action = wezterm.action.SendString '\x02\"'
    },
```

**Comment by jdhoffa** [comment]
Oh wow that's very embarrassing. Thank you haha
