### ISSUE TITLE
Transparency blending compared with iTerm2

### ISSUE THREAD

**Issue by erf** [wez/wezterm#302]
## Describe the bug

I noticed when setting `window_background_opacity` from `1.0` to `0.9`, the background color is suddenly much darker.  I also noticed when i the `window_background_opacity` value goes below `0.5` the background gets even more brighter (more white) than it originally was, so this makes me think there is an issue with blending of colors when transparancy is enabled.

## Environment (please complete the following information):

 - OS: macOS
 - Version: 20200909-002054-4c9af461-210-gb0fdd15d

## To Reproduce

1. Open wezterm with a config file with only `window_background_opacity = 1.0`.

2. Type: `echo -e "\e[1;43m\e[1;31m WEZTERM "` which should print WEZTERM in red text on a yellow background.

3. Open another terminal (e.g. `iTerm2`), and change the value of `window_background_opacity` to `0.9` and save.

4. Notice how dark the yellow background suddenly becomes.

5. Then if you set `window_background_opacity` to `0.1` it's almost back to yellow ( on a black desktop background ), but then on `0.0` the background is transparent.

Also notice if you set the value to `0.5` with a white background, it's completely white, no yellow.

## Configuration

I only use `window_background_opacity`.

## Expected behavior

I would expect the background color to gradually be less opaque and blend in with the background windows as you lessen the opacity value. This is what happens on `iTerm2`.

## Screenshots

I have added a set of screenshots, with iTerm2 on the left and Wezterm on the right, where i progressively turn the opacity down from 1.0 to 0.0 and compare them with `iTerm2`. iTerm2 has a slider so the transparency values are approximated.

 `window_background_opacity = 1.0` on black background

<img width="1200" alt="Screenshot 2020-10-21 at 17 40 40" src="https://user-images.githubusercontent.com/1562523/96744748-a99c2600-13c5-11eb-8594-030069235e72.png">

 `window_background_opacity = 0.9`

<img width="1194" alt="Screenshot 2020-10-21 at 17 41 00" src="https://user-images.githubusercontent.com/1562523/96744795-b28cf780-13c5-11eb-98af-2bc168803775.png">

 `window_background_opacity = 0.5`

<img width="1167" alt="Screenshot 2020-10-21 at 17 41 33" src="https://user-images.githubusercontent.com/1562523/96744850-c2a4d700-13c5-11eb-9c1c-6b16b46539be.png">

 `window_background_opacity = 0.25`

<img width="1177" alt="Screenshot 2020-10-21 at 17 41 59" src="https://user-images.githubusercontent.com/1562523/96744894-cdf80280-13c5-11eb-997c-4c19986aa142.png">

 `window_background_opacity = 0.1`

<img width="1177" alt="Screenshot 2020-10-21 at 17 42 50" src="https://user-images.githubusercontent.com/1562523/96744939-d81a0100-13c5-11eb-9177-623db151aad8.png">

 `window_background_opacity = 0.0`

<img width="1181" alt="Screenshot 2020-10-21 at 17 43 06" src="https://user-images.githubusercontent.com/1562523/96744985-e700b380-13c5-11eb-9f8a-23df86097d9e.png">

 `window_background_opacity = 1.0` on white backround

<img width="949" alt="Screenshot 2020-10-21 at 17 44 07" src="https://user-images.githubusercontent.com/1562523/96745085-0ac3f980-13c6-11eb-963f-8781ca2a2085.png">

 `window_background_opacity = 0.5` on white backround

<img width="1052" alt="Screenshot 2020-10-21 at 17 44 27" src="https://user-images.githubusercontent.com/1562523/96745155-1ca59c80-13c6-11eb-9aa1-813f58f5c326.png">

 `window_background_opacity = 0.1` on white backround

<img width="1045" alt="Screenshot 2020-10-21 at 17 44 55" src="https://user-images.githubusercontent.com/1562523/96745219-2deea900-13c6-11eb-903b-421b3a4dbba7.png">

 `window_background_opacity = 0.0` on white backround

<img width="1101" alt="Screenshot 2020-10-21 at 17 45 09" src="https://user-images.githubusercontent.com/1562523/96745249-38a93e00-13c6-11eb-81c5-2656c1b5330b.png">

## Additional context

I noticed `iTerm2` has an option **Keep background colors opaque**, which perhaps could be added as a options, and i think is how your initial implementation worked, if not mistaken.

I also noticed sometimes some fonts seemed a bit "jarred" after i enabled transparency, but i think that has to do with something else, which i will create an issue for if i'm able to recreate it.

**Comment by wez** [comment]
This should be resolved in the nightly builds.  The docs have been updated to reflect how the latest nightlies work:
https://wezfurlong.org/wezterm/config/appearance.html#window-background-opacity

**Comment by erf** [comment]
@wez I noticed that the window is only transparent when `window_background_opacity` goes below `0.6`, if it's above, it's always opaque.

`text_background_opacity` can be whatever.
