### ISSUE TITLE
Frame rate drop when window_background_opacity = 1.0

### ISSUE THREAD

**Issue by adrwstone** [wez/wezterm#3022]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Verified that it was also an issue with nightly. Version is most recently version install from brew.

Setting window_background_opacity = 1.0 causes significant frame rate drop (maybe 10fps?) system-wide when wezterm is moved into Mission Control, App Exposé view (there may be other instances where this is an issue). This can't be captured with screen record since it seems that screen recording is capturing at too low fps to capture?

I set up my phone to record the screen at 60FPS which it is very apparent that something weird is going on.

Notice that the first time entering Mission Control there is a clear stutter in and out of MC  when window_background_opacity = 1.0, the second time is after changing window_background_opacity = 0.9

I use window_background_opacity = 0.9 anyway so this isn't a big issue but as a new user this took me a while to diagnose what was causing the behaviour.

https://user-images.githubusercontent.com/61954919/215252403-06221f0d-5074-4435-93c5-445aa88a254f.mov

### To Reproduce

Set window_background_opacity = 1.0
On Intel MBP2019, use trackpad to initiate mission control, app exposé (three finger swipe up/down on track pad)
Notice the the screens becomes very unresponsive

**Work around:**
Set window_background_opacity < 1.0

### Configuration

...
window_background_opacity = 1.0,
...

### Expected Behavior

FPS does not drop as if i was running cyberpunk @4k on a raspberry pi

### Logs

No log messages.

### Anything else?

This could be resolved easily by setting the default background opacity to 0.99;

Let me know if theres any additional info I can provide to help resolve.

**Comment by wez** [comment]
Possible a duplicate of:
* https://github.com/wez/wezterm/issues/2669

**Comment by adrwstone** [comment]
you are correct. marking as closed.
