### ISSUE TITLE
time.call_after() does not work from user callback (or any other context other than first time after config loaded)

### ISSUE THREAD

**Issue by rogueeve575** [wez/wezterm#3026]
### What Operating System(s) are you seeing this problem on?

Linux X11, macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 / XFCE & MacOS

### WezTerm version

Nightly 20230127-155254-691ec187

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Context

First of all this is the coolest terminal program I've ever used. I have been really enjoying getting my config set up and adding some advanced functionality via Lua scripting (my full config is starting to become more of a mutli-module mini-program than just a table of key/values), which seems to fit in really great with Awesome WM's similar lua-based config style which I've been migrating to as well.

One of the things I'd like to do is write a "timer manager" that is supposed to enable things such as allowing me to set a "right_status" from Lua on various events and then clear the message automatically after a few seconds, while arbitrating to extend the time if another message is posted before the first was cleared, etc. I wrote it today, but it doesn't work, and so I started pairing things down and debugging.

### The Apparent Bug

wezterm.time.call_after() appears to be the right building block to base this sort of thing on, but it seems that this may not be currently possible because what I've found is that call_after() seems to _*only*_ work as you'd expect for the simplistic "periodic config reload" scenario demoed in the docs. Timers scheduled _*after*_ the config is loaded seem to never fire, you have to force-reload the config, and then all your program state will be reset. This seems to significantly impact not just this particular use case but the overall available possibilities of what you can do with advanced Lua configs, since the inability to schedule asynchronous events means that all Lua-triggered actions can only be in direct response to some user action or an event.

I looked at the source code and from what little I could tell since I mostly code in C and don't know Rust very well, this happens because the call_after timers are merely added to a list whose scheduling is tied to the config reload event rather than being immediately scheduled.

### To Reproduce

Paste the below paired-down config into a wezterm.lua and start wezterm while being able to view the console output from another terminal. The first start_countdown timer, kicked off during config load, fires but then the subsequent timer schedulings intended to continue the sequence appear to be (silently) ignored.

Also, upon pressing the configured CTRL+ALT+U shortcut, you can see that the more minimalist user_callback_test() test runs as expected, but the (separate) timer it schedules never fires.

### Configuration

	local wezterm = require('wezterm')
	local act = wezterm.action

	-- this works, but only the first time
	function start_countdown()
		local countdown = 10
		local countdown_cb

		countdown_cb = function(window, pane)
			print(tostring(countdown) .. "...")
			countdown = countdown - 1
			if countdown > 0 then
				print("scheduling next cb " .. tostring(countdown_cb))
				wezterm.time.call_after(1, countdown_cb)
			end
		end

		-- kick off the initial timer
		wezterm.time.call_after(1, countdown_cb)
		print("scheduled initial timer " .. tostring(countdown_cb))
	end

	start_countdown()

	-- timer does not fire from this function
	function user_callback_test(window, pane)
		print("user_callback_test()")
		window:set_right_status("in callback: It Works!!")

		wezterm.time.call_after(1000, function()
				print("You won't see me!!")
		end)
	end

	function gen_config()
		_config = {
			tab_bar_at_bottom = true,
			use_fancy_tab_bar = false,
			color_scheme = 'Banana Blueberry',
			font = wezterm.font('Hack Nerd Font Mono'),
			font_size = 16,
			enable_scroll_bar = true,
			pane_focus_follows_mouse = true,
			adjust_window_size_when_changing_font_size = false,
			warn_about_missing_glyphs = false,
			use_ime = false,	-- or ctrl keys won't work with Colemak

			leader = { mods = 'CTRL', key = 'Enter', timeout_milliseconds = 3000 },
			keys = {
				{ mods = 'CTRL|ALT',
				  key = 'u',
				  action = wezterm.action_callback(user_callback_test)
				}
			}
		}

		return _config
	end

	return gen_config()

### Expected Behavior

I would assume that wezterm.time.call_after() is intended to work anywhere, not just only once after a config reload, as I couldn't find anything about that restriction in the docs and having this work would enable an important hook for a lot of possibilities with various advanced Lua-based custom functionality.

### Logs
```
 ~/.config/wezterm $ wezterm | tee wt.log

16:15:57.141  INFO   logging > lua: scheduled initial timer function: 0x7feafde11ec0
16:15:57.338  INFO   logging > lua: scheduled initial timer function: 0x7fc47dd141b0
16:15:57.592  INFO   logging > lua: scheduled initial timer function: 0x7fc47dd727c0
16:15:57.769  WARN   wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
16:15:58.765  INFO   logging                     > lua: 10...
16:15:58.765  INFO   logging                     > lua: scheduling next cb function: 0x7fc47dd727c0
(...at this point I wait a few seconds and then push Ctrl+Alt+U to trigger the other timer test)
16:16:01.551  INFO   logging                     > lua: user_callback_test()

```

**Comment by eugenesvk** [comment]
Is what you're asking for an equivalent of a nonexisting function `time.call_every(X)`?
I'd also love to have a periodic ticker with sub-second precision for some of my timers, but currently I'm hooking into status updates periodically invoked by wezterm that tracks timers, but it's not precise enough, this seems to tick ~1/sec

```lua
wezterm.on("update-status", function(win, pane)
  timer.update()
...
```

(the timer lib is in this gist if you're interested https://gist.github.com/eugenesvk/c131284ea2ca572010722d798f6865f4)

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by eugenesvk** [comment]
That seems to work, thanks! Am I correct that the timer's minimum resolution is 1 second, though?

**Comment by wez** [comment]
You can use fractional seconds: eg: `0.5` for half a second
