### ISSUE TITLE
Wezterm fails to start with "too many files open" error

### ISSUE THREAD

**Issue by gmile** [wez/wezterm#3027]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

kwin

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

`wezterm` will not start

### To Reproduce

Try to start wezterm

### Configuration

no config

### Expected Behavior

Application starts.

### Anything else?

App start backtrace:

```
$ RUST_BACKTRACE=full wezterm
10:34:22.982  ERROR  env_bootstrap > panic at config/src/lib.rs:441:59 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  16: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  17: <unknown>

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }), paths: [] }', config/src/lib.rs:441:59
stack backtrace:
   0:     0x561cb648c090 - <unknown>
   1:     0x561cb64b546e - <unknown>
   2:     0x561cb6484045 - <unknown>
   3:     0x561cb648dcd3 - <unknown>
   4:     0x561cb648d9bf - <unknown>
   5:     0x561cb59da7d7 - <unknown>
   6:     0x561cb648e41d - <unknown>
   7:     0x561cb648e277 - <unknown>
   8:     0x561cb648c53c - <unknown>
   9:     0x561cb648df92 - <unknown>
  10:     0x561cb59432e3 - <unknown>
  11:     0x561cb5943433 - <unknown>
  12:     0x561cb5fc5cc8 - <unknown>
  13:     0x561cb5fc3cb6 - <unknown>
  14:     0x561cb598a5a9 - <unknown>
  15:     0x561cb5988109 - <unknown>
  16:     0x561cb596ef03 - <unknown>
  17:     0x561cb59a99f9 - <unknown>
  18:     0x561cb647c74f - <unknown>
  19:     0x561cb599e798 - <unknown>
  20:     0x7faa05d4bd90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21:     0x7faa05d4be40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  22:     0x561cb594361e - <unknown>
  23:                0x0 - <unknown>
$
```

**Comment by wez** [comment]
The line that is generating the error is attempting to watch files for configuration changes.
A "too many open files" error when working with inotify indicates an issue with inotify kernel limits.

Take a look a https://medium.com/@ivanermilov/how-to-fix-inotify-cannot-be-used-reverting-to-polling-too-many-open-files-bb1c1437dbf for a discussion of this class of problem.  That article was written for users of `tail` experiencing a specific error message. I suspect that you will encounter the same error if you try to use `tail -f /some/file`. That article talks through adjusting the relevant system limits to allow it to work again.
