### ISSUE TITLE
window:set_config_overrides is resetting fish_bind_mode

### ISSUE THREAD

**Issue by cacilhas** [wez/wezterm#3034]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

XFCE4 and its default compositor.

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Whenever Wezterm calls `window:set_config_overrides`, it resets `fish_bind_mode` to `insert`.

I used to use it to change the cursor between `*Bar` (which I use for `insert` mode) and `*Block` (for other modes) in Debian GNU/Linux, but when I had to migrate to ArchLinux, I found this bug.

### Configuration

```
local *

wezterm = require "wezterm"
ocean   = require "ocean"

cyan              = Color:     ocean.brights[7]
green             = AnsiColor: "Green"
magenta           = Color:     ocean.brights[6]
red               = AnsiColor: "Red"
VIM               = utf8.char 0xe7c5
EMACS             = utf8.char 0xe632
SOLID_LEFT_ARROW  = utf8.char 0xe0b6
SOLID_RIGHT_ARROW = utf8.char 0xe0b4


wezterm.on "update-status", (pane) =>
    return unless @
    config = @\get_config_overrides! or {}
    -- FIXME: `if wezterm.GLOBAL.isvim` always fails to else-block
    isvim  = wezterm.GLOBAL.isvim
    if isvim
        vimmode    = wezterm.GLOBAL.vimmode
        Foreground = red
        Background = Color: ocean.background
        chevron    = "N"
        cstyle     = wezterm.GLOBAL.cursorstyle
        config.default_cursor_style = cstyle .. "Block"
        switch vimmode
            when "insert"
                config.default_cursor_style = cstyle .. "Bar"
                Foreground = green
                chevron = "I"
            when "replace_one"
                Foreground = green
                chevron = "R"
            when "replace"
                Foreground = cyan
                chevron = "R"
            when "visual"
                Foreground = magenta
                chevron = "V"

        -- FIXME: it’s resetting fish_bind_mode
        --@\set_config_overrides config
        @\set_left_status wezterm.format {
            {Foreground: green}
            {Text: VIM}

            "ResetAttributes"
            {Text: " "}

            {:Foreground}
            {:Background}
            {Text: SOLID_LEFT_ARROW}

            {Foreground: Background}
            {Background: Foreground}
            {Text: chevron}

            {:Foreground}
            {:Background}
            {Text: SOLID_RIGHT_ARROW}
        }

    else
        @\set_left_status wezterm.format {
            {Foreground: magenta}
            {Text: EMACS}
        }
```

### Expected Behavior

Uncommenting the following line:

```
--@\set_config_overrides config
```

I expect the cursor to be a bar when `fish_bind_mode` is `insert`, and a block otherwise. Instead, Wezterm is always resetting `fish_bind_mode` to `insert`.

### Logs

wezterm version: 20221119-145034-49b9839f
OpenGL version: AMD RENOIR (DRM 3.49.0, 6.1.8-arch1-1, LLVM 12.0.1) 4.6 (Compatibility Profile) Mesa 21.3.9 (git-78c96ae5b6)

**Comment by wez** [comment]
I'm sorry, but I don't understand this issue. The configuration is not a valid wezterm lua configuration file and wezterm doesn't have a `fish_bind_mode` option. I'm assuming that is something to do with the fish shell, which I don't use and have no familiarity with.
I just don't know what you're trying here, what is going wrong or what you expect to happen.
Please break this down into a minimal set of steps that are easy to reproduce without copying your environment.
