### ISSUE TITLE
Calling `wezterm` starts a new instance instead of opening a new window on an existing instance

### ISSUE THREAD

**Issue by szbergeron** [wez/wezterm#3039]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230129-210825-df12dd9d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When opening multiple instances, multiple icons appear in dock and do not go away when their window is closed

### To Reproduce

1. Run `wezterm --start` from bash in another emulator
2. Run it again
3. Close the window for the second instance (eg, ctrl+d on that shell)

### Configuration

```lua
local wezterm = require 'wezterm';

return {
    -- font = wezterm.font("FiraCode Nerd Font Mono"),
    -- font = wezterm.font_with_fallback({
        -- "FiraCode Nerd Font Mono",
        -- "Hack Nerd Font Mono",
        -- "Iosevka Nerd Font Complete Mono",
        -- "Unifont",
        -- "Roboto"
    -- }),

    color_scheme = "Aurora",

    color_schemes = {
        ["Aurora"] = {
            background = 'red'
        }
    },

    colors = {
        background = 'rgb(0, 0, 0)'
    },

    enable_wayland = true,

    default_prog = {"fish"},

    -- enable_scroll_bar = true,

    warn_about_missing_glyphs = false,

    hide_tab_bar_if_only_one_tab = true,

    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
    },

    animation_fps = 1,

    cursor_blink_rate = 0,

    warn_about_missing_glyphs = true,

    native_macos_fullscreen_mode = true,

    keys = {
        {
            key = 'f',
            mods = 'CMD',
            action = wezterm.action.ToggleFullScreen,
        },
        {
            key = 'q',
            mods = 'CMD',
            action = wezterm.action.QuitApplication
        },
    },

    window_decorations = "RESIZE"
}
```

### Expected Behavior

Instances with no remaining window exit, or they are started joined to the initial instance (the additional `wezterm --start` commands exit after telling existing instance to create a new window)

**Comment by szbergeron** [comment]
In case this is related to OS version, this is macOS Ventura (13.2) running on M1

**Comment by wez** [comment]
Can you confirm exactly what you're using to launch wezterm windows, as `wezterm --start` is probably not it!

```
; wezterm --start
error: unexpected argument '--start' found

Usage: wezterm [OPTIONS] [COMMAND]

For more information, try '--help'.
```

**Comment by wez** [comment]
This is from my linux box, but the same concept should apply on macOS; it should launch wezterm and show something like this when re-using an existing instance:

```
; wezterm
13:58:02.420  INFO   wezterm_gui > Spawned your command via the existing GUI instance. Use wezterm start --always-new-process if you do not want this behavior. Result=SpawnResponse { tab_id: 9, pane_id: 13, window_id: 4, size: TerminalSize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384, dpi: 0 } }
```

Please share the output from:

`ls -l ~/.local/share/wezterm`

that should help me to understand some state that influences that.

It may also be useful to share the output from `env` run in the other bash window where you are spawning additional wezterms.

**Comment by szbergeron** [comment]
Whoops, I was typing on autopilot.

`wezterm start`

...And in trying to collect info I seem to have lost the ability to reproduce the issue, so I'll see if I can get it to do it again
