### ISSUE TITLE
scroll hovered pane rather than selected one

### ISSUE THREAD

**Issue by Porkepix** [wez/wezterm#3040]
A nice feature that you can find in other tools would be for scrolling to scroll the pane the mouse cursor is hover rather than the selected one, when working on several panes at once it can ease some things.

**Describe alternatives you've considered**
Alternative is to change selection of the pane to scroll the one you need to scroll.

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/config/pane_focus_follows_mouse.html

**Comment by Porkepix** [comment]
> Take a look at: [wezfurlong.org/wezterm/config/lua/config/pane_focus_follows_mouse.html](https://wezfurlong.org/wezterm/config/lua/config/pane_focus_follows_mouse.html)

Didn't see that one as I was looking for "scroll" in the doc (for this issue, and another one I've not yet opened/discussed on Matrix, which is scroll speed, but I might have missed things in doc for that one).
While it could be some kind of workaround, for me it doesn't fit the need in the sense it modify the focus which you might not want: for example you could still be typing on your focused pane while scrolling other ones for logs, doc or whatever.

**Comment by wez** [comment]
FWIW, "full screen" terminal applications require input focus to correctly process mouse events, such as scrolling in vim/editor buffers, so there's a lot more complexity to this than it seems at first glance.

**Comment by Porkepix** [comment]
> FWIW, "full screen" terminal applications require input focus to correctly process mouse events, such as scrolling in vim/editor buffers, so there's a lot more complexity to this than it seems at first glance.

To be honest I'm not knowledgeable enough when it comes to GUI and graphical things, but I've no doubts it can be really annoying to do, yes (and changes in focus in itself can come with its faire share of issues like I noticed with wezterm and default vim conf (where they added the damn mouse support by default) where, if you click in wezterm to select another pane, your click is not only selecting the pane but also goes through directly up to vim, changing mode to visual and so on)).

If it may help though, Zellij does what I describe here. It's developed in the same language, but it might also use completely different libs/toolkits/logic so I've no idea if it might be useful to take a look at it or if it's worthless to even mention it.

**Comment by olmokramer** [comment]
FWIW I got it to scroll the hovered pane by using `action_callback`:

```lua
local ScrollHoveredPane = wezterm.action_callback(function(window, pane)
  window:perform_action(act.ScrollByCurrentEventWheelDelta, pane)
end)

config.mouse_bindings = {
  {
    mods = 'NONE',
    event = { Down = { streak = 1, button = { WheelUp = 1 } } },
    action = ScrollHoveredPane,
  },
  {
    mods = 'NONE',
    event = { Down = { streak = 1, button = { WheelDown = 1 } } },
    action = ScrollHoveredPane,
  },
}
```

**Comment by aaronkollasch** [comment]
This solution didn't work for me, the `pane` in the callback function was still the active pane even when the mouse was over an inactive pane. (version 20230522-115955-bb23d046 on macOS Ventura)

Is there a wezterm function that can get the pane under the current mouse position? It seems like that could make this solution work.

**Comment by wez** [comment]
This is fixed in the current release
