### ISSUE TITLE
How to add custom arguments to the wsl_domain

### ISSUE THREAD

**Issue by tuxflo** [wez/wezterm#3048]
I currently switching from Windows Terminal to wezterm and I really like it so far.
In my WSL2 version I need to use the "genie" workaround to start systemd in WSL (see https://gist.github.com/djfdyuruiry/6720faa3f9fc59bfdf6284ee1f41f950). To use this I need to start WSL using the following comand:

```
C:\Windows\system32\wsl.exe -d Ubuntu -- genie -s
```
![Screenshot of the Windows Terminall Settings menu](https://user-images.githubusercontent.com/2816893/216262992-0ba481ff-8028-4fad-9e29-d570fe0d3215.png)

How can I add the `-- genie -s` argument to the Wezterm `wsl_domain`?

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/wezterm/default_wsl_domains.html shows how you can amend the wsl domain information; it sounds like you'd want to adapt the example shown there to set `dom.default_prog = {'genie', '-s'}` for the appropriate domain(s) on your system.

**Comment by tuxflo** [comment]
I had some problem with adding the args to the dom object but if I just set the "global" default_prog it works like a charm:
```
    default_prog = {
    'C:\\Windows\\System32\\wsl.exe',
    '-d',
    'Ubuntu',
    '--',
    'genie',
	'-s',
  },
  ```
