### ISSUE TITLE
Tilde character cannot be inserted with Spanish keyboard

### ISSUE THREAD

**Issue by mardukbp** [wez/wezterm#305]
## Describe the bug

In a Spanish (Spain variant, not LatAm) keyboard the tilde character is a dead key. But, unlike an accent, which requires a single key press, it is obtained by pressing `Alt Gr` + `4`. Pressing `SPACE` afterwards should insert `~`. Instead, nothing happens.

## Environment (please complete the following information):

 - OS: Windows 10
 - Version: wezterm 20200909-002054-4c9af461-210-gb0fdd15d

## To Reproduce

Just press the keys mentioned in the description.

## Configuration

```lua
local wezterm = require 'wezterm';

return {
   font = wezterm.font_with_fallback({
    "Consolas",
    "DengXian"
   }),
   font_size = 16.0,
   hide_tab_bar_if_only_one_tab = true,
   default_prog = {"cmd.exe"},
   keys = {
      {key="F", mods="SHIFT|CTRL", action=wezterm.action{Search={CaseInSensitiveString=""}}},
      {key="l", mods="ALT", action="ShowLauncher"},
    },
}
```

## Expected behavior

After pressing the above keys the tilde character `~` should be inserted, just like in any other application.

## Screenshots

None

## Session Recording
 
None

## Additional context

None

**Comment by bew** [comment]
Related #300, #275

**Comment by wez** [comment]
FWIW, that is a recent enough nightly; I've confirmed that this is an issue with altgr + dead keys.

**Comment by wez** [comment]
This is fixed in the nightly builds!

**Comment by mardukbp** [comment]
Perfect! Now I can go home :) Thank you @wez!
