### ISSUE TITLE
On activating WezTerm, spawn a new window if none is open

### ISSUE THREAD

**Issue by piechologist** [wez/wezterm#3057]
**Is your feature request related to a problem? Please describe.**
Note: I'm on macOS but this may apply to other platforms too. 

Imagine: close all panes in WezTerm. Switch to another GUI app. Switch back to WezTerm via the OS app switcher (command-tab) or any other method (clicking the Dock icon, activating via AppleScript, ...). You explicitly need to open a new window. I know, it's just cmd-n. I tried hard, but after many years of using iTerm I can't get around that 😭.

**Describe the solution you'd like**
I'd like WezTerm to spawn a new window in the DefaultDomain.

**Describe alternatives you've considered**
I'd be happy if wezterm would emit an event when it's being activated so I could do whatever I'm fancy. Or, if that's easier, an event on closing a window so I could check if it's the last window and quit wezterm (btw, that was the old behavior in 20221119-145034-49b9839f).

**Additional context**
-

**Comment by wez** [comment]
I've implemented that in main, but also added https://wezfurlong.org/wezterm/config/lua/config/quit_when_all_windows_are_closed.html to restore the original behavior of quitting the application when the windows are closed. 

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
