### ISSUE TITLE
Wezterm open two windows on startup

### ISSUE THREAD

**Issue by erf** [wez/wezterm#3064]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

16d75c972

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When i open Wezterm two windows are opnened.

### To Reproduce

Open Wezterm.app 

### Configuration

no config

### Expected Behavior

I expect only one window to open.

### Logs

Debug Overlay
wezterm version: 20230205-215311-16d75c97 aarch64-apple-darwin
Window Environment: macOS 13.1 (22C65)
OpenGL version: Apple M1 4.1 Metal - 83
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
13:30:39.574 WARN env_bootstrap > setlocale(en_NO.UTF-8) failed, fall back to en_US.UTF-8

**Comment by haoming-li-ling** [comment]
Having the same issue here with the latest nightly.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
