### ISSUE TITLE
reloading config when a pane is zoomed breaks rendering

### ISSUE THREAD

**Issue by kaddkaka** [wez/wezterm#3068]
### System

Linux X11, Ubuntu 22.04, Xubuntu (Xfce)

### WezTerm version

wezterm 20230206-084838-d1d48444

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When changing the window_padding setting left or right with live config reloading inside a zoomed pane, the rendering of that pane stops at the width of the unzoomed state (for most lines), see screenshots:

![Screenshot from 2023-02-07 06-56-59](https://user-images.githubusercontent.com/4508793/217161600-69d2eb5b-61d8-476a-9d3a-ba90d8143ad3.png)
![Screenshot from 2023-02-07 06-58-02](https://user-images.githubusercontent.com/4508793/217161603-cf93c766-a96a-4606-a5f9-0d3e9b3681ca.png)

### To Reproduce

1. Open a split pane `SplitHorizontal`
2. Zoom in either pane with `<c-Z>`
3. Modify windows padding left/right, e.g.
    a. from: `window_padding = { left = 0, right = 0, top = 0, bottom = 0 },`
    b. to `window_padding = { left = 1, right = 0, top = 0, bottom = 0 },`

It happens 99% of the time, and is most prominent when changing between `0<->1`

### Configuration

```lua
return {
  window_padding = { left = 0, right = 1, top = 0, bottom = 0 },
}
```

### Expected Behavior

No rendering issues

### Logs

Overlay seems to log nothing during the process.

### Anything else?

Behavior seen when changing setting through vim or neovim.

Stopping neovim with `ctrl-z` and foregrounding it again repairs the rendering problem sometimes. But it might re-appear the next time neovim or vim is started.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by kaddkaka** [comment]
Thanks for super quick response! :)
 I will test this tomorrow since I'm not able to split a pane in my ssh domain session and it's getting late.

**Comment by snaggen** [comment]
Not sure if this is related but I can now, with a nightly I just installed break rendering in a simmilar way. 
1. I have a terminal maximized on the desktop, split it into 2 panes. 
2. In the left I do cat on a file with super long lines. 
3. zoom the left pane to fill the whole window and back. 
4. Now the rendering is broken, the text still fills the whole screen, not just the left pane. 
5. When I cat the file again, it will extend over both panes... so it is not just old text, but also new text. I can even type over in to the right pane. 

On a upgraded Fedora 37 under wayland on a x86_64 machine.

**Comment by snaggen** [comment]
This issue is not just with maximized terminals, a regular window have the same bahaviour. Resize of the terminal will get it back in to a sane state.

**Comment by wez** [comment]
@snaggen please file a separate issue, thanks!

**Comment by kaddkaka** [comment]
Fix seems to work :+1:  The hot reloading does not break the rendering any longer :)
