### ISSUE TITLE
Opening the second tab is slow when hide_tab_bar_if_only_one_tab is true

### ISSUE THREAD

**Issue by erf** [wez/wezterm#308]
**Is your feature request related to a problem? Please describe.**

Opening the second tab is slow if `hide_tab_bar_if_only_one_tab=true`. It takes about a second to open a new tab then.

**Describe the solution you'd like**

Make it faster to open the first tab when `hide_tab_bar_if_only_one_tab=true`.

**Describe alternatives you've considered**

I could disable the option..

**Additional context**

macOS
wezterm 20200909-002054-4c9af461-237-g42aeb6f1

**Comment by wez** [comment]
I think this is partially a perception issue similar to https://github.com/wez/wezterm/issues/264#issuecomment-710491937

When the tab is displayed unconditionally, creating a new tab immediately shows the tab title but it takes a little bit for the rest of the tab to show up.

When the `hide_tab_bar_if_only_one_tab=true`, the tab doesn't show up until the pane is full started up.

I think it's reasonable to see if we can force an invalidation earlier in the latter case, but in terms of "time to display the shell prompt", both appear the same to me.

You can hit CMD-T and start typing immediately and the input does get sent to the new tab even before the prompt starts rendering.

**Comment by erf** [comment]
When `hide_tab_bar_if_only_one_tab=false` i see second tab and can type immediately, if `hide_tab_bar_if_only_one_tab=true` i can type immediately, but it takes about a second for the tab bar to show. If a forced invalidation would fix this, that would improve the user experience somewhat i think.

**Comment by erf** [comment]
I works fine for me now on the latest on a M1, so i'll close this now
