### ISSUE TITLE
Wezterm Crashes in WSL2 with WSLg

### ISSUE THREAD

**Issue by trev-dev** [wez/wezterm#3080]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

Wayland via WSL2 & WSLg, NixOS 22.05. 

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

If I maximize Wezterm, it often crashes.

Here is the console output.  It looks like a notification is fired, which fails.  Maybe this is the source of the crash.

### To Reproduce

Do something silly like attempt to install NixOS on wsl2 and then use GUI apps on WSLg in general.

### Configuration

```lua
local wezterm = require 'wezterm'

return {
  font = wezterm.font 'JetBrainsMono Nerd Font',
  font_size = 11,
  color_scheme = 'Material Darker (base16)',
  window_background_opacity = 0.95,
  window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0
  },
  colors = {
    background = "#131313"
  },
  hide_tab_bar_if_only_one_tab = true
}
```

### Expected Behavior

I don't know what to expect. honestly.  I am hoping maybe I can get lucky and use Wezterm from within wsl2 as a GUI terminal emulator without it performing poorly or crashing.

### Logs

19:33:57.272  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.312  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.326  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.338  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.356  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.368  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.398  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.408  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.466  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.481  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.498  ERROR  window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
19:33:57.523  ERROR  window::os::wayland::frame   > Unable to set cursor to left_ptr: cursor not found
19:33:57.524  ERROR  window::os::wayland::frame   > Unable to set cursor to left_ptr: cursor not found
19:33:57.524  ERROR  window::os::wayland::pointer > Unable to set cursor to arrow: cursor not found
19:33:58.987  WARN   window::os::wayland::connection > Enter { serial: 1126, surface: wl_surface@33, keys: [] }, no known surface
xdg_wm_base@16: error 4: xdg_surface buffer (720 x 510) does not match the configured maximized state (1920 x 1050)
19:33:59.001  ERROR  wezterm_gui                     > running message loop: error during event_q.dispatch protocol_error=Some(ProtocolError { code: 4, object_id: 16, object_interface: "xdg_wm_base", message: "" }): Protocol error (os error 71); terminating
19:33:59.005  ERROR  wezterm_toast_notification::dbus > while showing notification: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

### Anything else?

I know the recommended course of action is a native installation but there's always some compromise in relying on ConPTY.  In my case it causes Neovim to totally sh*t the bed in wsl2.

I tried `wezterm ssh` which seems to work really well until you realize that the Windows interop gets broken.  You may also not launch (some) GUI stuff from ssh, like my pinentry or chrome for e2e testing.

I have been able to fall back on Kitty for the functionality I am looking for but I really like what I've seen from Wezterm so far.  Thanks for the great program!

**Comment by trev-dev** [comment]
I had a productive conversation in the neovim issues that may have resolved my issues with using Wez in native Windows:
https://github.com/neovim/neovim/issues/21713#issuecomment-1424504615

However the WSLg issue can still stand, if you prefer to treat it as separate :)

**Comment by dantesg** [comment]
@trev-dev can you check if running `wsl --update` as admin solves the issue for you. it seems to have solved for me.

**Comment by trev-dev** [comment]
Thanks for the heads up!  While I am sure that might work, I have moved on.
