### ISSUE TITLE
Wezterm Generates Many Warnings due to Getting Appearance

### ISSUE THREAD

**Issue by acook** [wez/wezterm#3082]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Budgie, default for Solus

### WezTerm version

wezterm 20230208-091928-fd5c6dce

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm building from source and I've looked at the code, basically if Wezterm isn't able to get the appearance (constantly) from the portal it will spam errors to the Lua term or the term it is launched from.

### To Reproduce

Run Wezterm and don't let it talk to xdg_desktop_portal to get the current desktop appearance. 

### Configuration

no config

### Expected Behavior

Wezterm would detect is the portal was available, maybe make one warning and then cache the result instead of constantly re-querying it.

### Logs

```
00:57:16.967  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

### Anything else?

Any time there is a redraw you'll see the error. If you move the window there will be a ton of them for ever pixel moved.

It occurs to me that maybe we shouldn't be looking this up every tick anyway. It's taking what would normally be an async call and blocking on it every time.

If I"m reading PR https://github.com/wez/wezterm/pull/2402 it looks like we're caching the value, so it could be even more I supposed.

The code was introduced in this PR https://github.com/wez/wezterm/pull/2268 which does the check.

https://github.com/wez/wezterm/blob/main/window/src/os/x11/connection.rs#L186 is its current home. 

I went looking to see if there was a way to subscribe to a change using xdg portal, so then we could get notified and either invoke an event handler or just check it at our leisure. But I'm not savvy to it and didn't find anything. 

Of course, I also have the portal libraries installed and it isn't clear to me why Wezterm isn't find the setting, but that's a separate issue.

I'm pretty tired right now, so apologies if I missed anything obvious.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by acook** [comment]
I pulled the latest and compiled. Now I see the message just once and never again.

I took a look at the code too, looks like it is handling different conditions and storing them now.

Awesome, thanks!
