### ISSUE TITLE
disable_default_key_bindings cannot be changed if it started as false

### ISSUE THREAD

**Issue by hunterliao29** [wez/wezterm#3090]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230209-090846-a5b449f3

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

disable_default_key_bindings can only be changed when the initial value is set to true. 

### Configuration

```lua
local wezterm = require("wezterm")
local config = wezterm.config_builder()

-- cannot be toggled when the value is false
config.disable_default_key_bindings = false
config.keys = {
	{
		key = "g",
		mods = "CTRL",
		action = wezterm.action_callback(function(window, pane)
			local overrides = window:get_config_overrides() or {}
			if overrides.disable_default_key_bindings == false then
				-- If we haven't overridden it yet, then override with ligatures disabled
				overrides.disable_default_key_bindings = true
			else
				-- else we did already, and we should disable out override now
				overrides.disable_default_key_bindings = false
			end
			window:set_config_overrides(overrides)
			-- ==
		end),
	},
}
return config
```

### Expected Behavior

toggle disable_default_key_bindings no matter it's initial value

**Comment by wez** [comment]
It works fine; you have a logic error in the initial press of ctrl-g when you set `overrides` to its initial value of `{}`, so you end up assigning `disable_default_key_bindings = false` on the first ctrl-g press.

You can account for that like this:

```lua
local wezterm = require("wezterm")
local config = wezterm.config_builder()

config.disable_default_key_bindings = false
config.keys = {
	{
		key = "g",
		mods = "CTRL",
		action = wezterm.action_callback(function(window, pane)
			local overrides = window:get_config_overrides() or {disable_default_key_bindings=window:effective_config().disable_default_key_bindings}
			if overrides.disable_default_key_bindings == false then
				overrides.disable_default_key_bindings = true
			else
				overrides.disable_default_key_bindings = false
			end
			window:set_config_overrides(overrides)
			-- ==
		end),
	},
}
return config
```

**Comment by hunterliao29** [comment]
@wez sorry for the pin. The example you provide does not work
I also try the code below but it does not seem to work too.
```lua
local wezterm = require("wezterm")
local config = wezterm.config_builder()

config.disable_default_key_bindings = false
config.keys = {
	{
		key = "g",
		mods = "CTRL",
		action = wezterm.action_callback(function(window, pane)
			local overrides = window:get_config_overrides()
				or { disable_default_key_bindings = window:effective_config().disable_default_key_bindings }
			overrides.disable_default_key_bindings = true
			window:set_config_overrides(overrides)
		end),
	},
}
return config
```

**Comment by wez** [comment]
My test scenario was with the config I posted.
On startup, CTRL-+ and CTRL-- change the font size.
When I press CTRL-g, CTRL-+ and CTRL-- no longer change the font size.

Perhaps you are running into a different issue, like: https://github.com/wez/wezterm/issues/2771

**Comment by hunterliao29** [comment]
@wez Interesting. you test scenario does work. Can you test super + t or super + 2

When I set config.disable_default_key_bindings = true, 
I am not able to use super + t to create new tab.
However, using the the config you posted I am still able to create new tab after change to from false to true.

**Comment by wez** [comment]
Hmm, the other thing that is macOS specific is the menubar. When you toggle off the default keybindings, if you look in the menubar, does it still list the CMD-T for creating a new tab?
