### ISSUE TITLE
neovim interprets `*` different than kitty itself when using kitty kbd protocol

### ISSUE THREAD

**Issue by craigmac** [wez/wezterm#3092]
Issue explained here: https://github.com/kylechui/nvim-surround/issues/200

With kitty protocol turned on, neovim HEAD build interprets `*` as `<S-*>` while when using kitty itself  it reports `*` while using the kitty protocol.

**Comment by wez** [comment]
Potentially a duplicate of https://github.com/wez/wezterm/issues/2546

**Comment by craigmac** [comment]
Looks like it, yes!

**Comment by wez** [comment]
OK, I'll close this in favor of that!
