### ISSUE TITLE
CloseCurrentPane on ssh doesn't close pane

### ISSUE THREAD

**Issue by JMarkin** [wez/wezterm#3095]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

if I connect thought `wezterm ssh` create tab or pane, close it and it will freeze and not close.

### Configuration

```lua
local wezterm = require("wezterm")
local act = wezterm.action

return {
	font = wezterm.font("JetBrainsMonoNL Nerd Font Mono"),
	font_size = 13.0,
	line_height = 1.0,
	cell_width = 1.0,
	bold_brightens_ansi_colors = true,
	color_scheme = "OneDark (base16)",

	keys = {
		{
			key = "w",
			mods = "CMD",
			action = act.CloseCurrentPane({ confirm = false }),
		},
}
```

### Expected Behavior

tab or pane closed

### Logs

16:17:36.172  DEBUG  wezterm_gui::termwindow                > RawKeyEvent(RawKeyEvent { key: Char('w'), modifiers: SUPER, phys_code: Some(W), raw_code: 13, repeat_count: 1, key_is_down: true, handled: Handled(false) })
16:17:36.172  DEBUG  mux                                    > removing pane 1
16:17:36.173  DEBUG  mux                                    > killing pane 1
16:17:36.173  DEBUG  mux::localpane                         > killing process in pane 1, state is Running { child_waiter: Receiver { .. }, pid: None, signaller: SshChildKiller { tx: Some(SessionSender { tx: Sender { .. }, pipe: Mutex { data: FileDescriptor { handle: OwnedHandle { handle: 8, handle_type: () } }, poisoned: false, .. } }), channel: 2 }, killed: false }

### Anything else?

I try to build wezterm from source. Pane or tab didn't close but not freezes. Close again didn't work, because pane_id removed from hashmap.

if you describe me, how I can fix this, I will try to fix this bug and will create pull request.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by JMarkin** [comment]
@wez It resolved. Thank you.

But, I tried to change ssh_backend to "Ssh2", and found this bug again
