### ISSUE TITLE
Tab bar background can't be overridden

### ISSUE THREAD

**Issue by jason0x43** [wez/wezterm#3104]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230212-103106-a5c2b1f3

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am able to override most parts of the tab bar theme, but not the tab bar background. I read through https://github.com/wez/wezterm/issues/2376, and I am overriding the theme rather than just specifying custom colors (at least that's the goal).

### To Reproduce

I'm attempting to autogenerate tab bar colors from themes rather than using the theme's default colors. I have a function `Scheme` that, among other things, does this:

```lua
function get_schemes(window)
	local config = window:effective_config()
	local schemes = {}

	for name, scheme in pairs(wezterm.color.get_builtin_schemes()) do
		schemes[name] = scheme
	end

	for name, scheme in pairs(config.color_schemes) do
		schemes[name] = scheme
	end

	return schemes
end

function Scheme(name)
	local scheme = get_schemes(window)[name]
	local overrides = window:get_config_overrides() or {}

	local bg = wezterm.color.parse(scheme.background)
	local bar_bg = bg:darken(0.2)
	local dim_bg = bg:darken(0.1)

	local fg = wezterm.color.parse(scheme.foreground)
	local dim_fg = fg:lighten(0.5)

	scheme.tab_bar = {
		background = bar_bg,
		active_tab = {
			bg_color = scheme.background,
			fg_color = scheme.foreground,
		},
		inactive_tab = {
			bg_color = dim_bg,
			fg_color = dim_fg,
		},
		new_tab = {
			bg_color = bar_bg,
			fg_color = scheme.brights[1],
		},
	}

	overrides.color_schemes = overrides.color_schemes or {}
	overrides.color_schemes[name] = scheme
	overrides.color_scheme = name
	window:set_config_overrides(overrides)

	-- ...
end
```

When the scheme function is called, either with an action I have to flip through themes, or by calling `Scheme('scheme name')` in the debug pane, the tab bar colors are updated, except for the tab bar background. The background will continue using the color defined in the theme, or some other default color.

### Configuration

The relevant code is in the **To Reproduce** section.

### Expected Behavior

The `tab_bar.background` property should be used.

**Comment by wez** [comment]
Is this still an issue in the latest release?
Is this the fancy or the retro tab bar?
Can you minimize the config to something self contained that I can try?

**Comment by jason0x43** [comment]
I think it’s no longer an issue, but I’ll double check and get back to you.

**Comment by jason0x43** [comment]
The issue appears to have been resolved at some point. Nice! I got to remove some work-around code from my config. 🙂
