### ISSUE TITLE
Cursor is either wrong or invisible

### ISSUE THREAD

**Issue by paveloom** [wez/wezterm#3106]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter 43.2.

### WezTerm version

wezterm a5c2b1f3adb06054bf522cb3d350697938d6f8e9

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Upon entering the window, the cursor either has a wrong style or is invisible. 

### To Reproduce

Put your cursor in the window.

### Configuration

I can reproduce the issue without a config by running `wezterm -n`.

### Expected Behavior

The cursor should be present and have a correct style. 

### Logs

```
Debug Overlay
wezterm version: a5c2b1f3adb06054bf522cb3d350697938d6f8e9 x86_64-unknown-linux-gnu
Window Environment: Wayland
OpenGL version: AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.49, 6.1.11) 4.6 (Compatibility Profile) Mesa 22.3.4
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
23:08:52.226 ERROR window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
23:08:52.384 ERROR window::os::wayland::pointer > Unable to set cursor to xterm: cursor not found
```

Also getting the following errors when running `wezterm -n`:

```
23:08:57.021  ERROR  window::os::wayland::frame   > Unable to set cursor to left_ptr: cursor not found
23:08:57.021  ERROR  window::os::wayland::frame   > Unable to set cursor to right_side: cursor not found
23:08:57.022  ERROR  window::os::wayland::pointer > Unable to set cursor to arrow: cursor not found
```

### Anything else?

Here's a recording:

https://user-images.githubusercontent.com/49961859/218564572-e2b9f1b7-3bf0-4936-9c59-7f5972dfef82.mp4

Interesting that the cursor is visible in the last part of the recording, even though I haven't seen it on my screen.

**Comment by wez** [comment]
How did you install wezterm? The version information seems a bit unusual.
Is this a duplicate of https://github.com/wez/wezterm/issues/2687 ?

**Comment by paveloom** [comment]
Using [Nix](https://nixos.org). [Here](https://github.com/NixOS/nixpkgs/blob/c79e326a5919075eb6386e7485b691324595e71c/pkgs/applications/terminal-emulators/wezterm/default.nix)'s the package, and [here](https://github.com/paveloom/dotfiles/blob/1205baa17dff24ab9ae96958ea68ee50c7fa9451/home.nix#L22-L38)'s my overlay for a version from the `main` branch. The version information is the contents of the `.tag` file.

I do believe https://github.com/wez/wezterm/issues/2687 is the same issue, but the reasons for why paths to cursor files are not found are different. NixOS doesn't follow [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). There are no directories like `~/.icons`, `/usr/local/share/icons`, `/usr/share/icons` by default. There are also no environment variables like `XDG_DATA_HOME`, `XCURSOR_PATH`, `XCURSOR_THEME` by default. 

There is `XDG_DATA_DIRS`, though, but those are links to the Nix store. Except one: `/run/current-system/sw/share`. I found it mentioned in https://github.com/NixOS/nixpkgs/issues/140505. It does contain the cursor themes of my system (GNOME), and all I had to do to make Wezterm see them is to set `XCURSOR_THEME` to `Adwaita`:

```bash
XCURSOR_THEME=Adwaita WEZTERM_LOG=window::os::x11::cursor=trace,window::os::wayland::pointer=trace,info wezterm start --always-new-process
```

It stopped complaining about missing cursors, and I think it works now:

![image](https://user-images.githubusercontent.com/49961859/219847472-a47d561e-15b8-4417-a5e9-ffd752872303.png)

I would say that's just a quirk of NixOS.
