### ISSUE TITLE
portable-pty release with `get_termios`

### ISSUE THREAD

**Issue by FuegoFro** [wez/wezterm#3108]
Hey there! I've been using and appreciating the `portable-pty` crate and just ran into a use case where I'd like to get access to the termios pty handle on Unix (to do stuff like forward the echo or canonical modes to any [pt]ty my process is being run in). It looks like a `get_termios` method was introduced in 1b9ea2de3f2942b6766407c6a1ec80d68a15c9be for a very similar reason but isn't available in the existing 0.7.0 release. Would it be possible to do another release of `portable-pty` which has that function? Thank you!

**Comment by wez** [comment]
I published 0.8.0 from the current `main` 0bcbdc1baa57fe8d644604d202f377f2753a03be
