### ISSUE TITLE
Hover on retro inactive/new tab not working when `tab_tar_at_bottom` enabled

### ISSUE THREAD

**Issue by g6ai** [wez/wezterm#3113]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230212-103106-a5c2b1f3

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Under the retro tab bar setting: `use_fancy_tab_bar = false`, the options set in `inactive_tab_hover` and `new_tab_hover` do not work if `tab_bar_at_bottom` is set to `true`. Actually if I do not set the hover options at all, the default 'italics on hover' doesn't work either with such settings.

### Configuration

```lua
return {
  use_fancy_tab_bar = false,
  tab_bar_at_bottom = true,
}
```

**Comment by craigmac** [comment]
Can confirm using nightly wezterm on macOS and:

```lua
colors = {
  tab_bar = {
    new_tab_hover = {
      bg_color = '#ffffff',
      fg_color = '#000000',
      italic = false,
    }
  }
}
```

Doesn't apply the styling when mouse hovers over the new tab button.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by derekthecool** [comment]
I can confirm the issue running on version 20221119-145034-49b9839f¶ on windows 11.
I can also confirm the fix using the nightly build as of 2023-03-21.

Thanks!
