### ISSUE TITLE
Wezterm not working after upgrde kernal to 5.19.1-32-generic

### ISSUE THREAD

**Issue by CharlesChiuGit** [wez/wezterm#3117]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

gnome and bspwm

### WezTerm version

20230212-103106-a5c2b1f3(nightly) and 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

```
$ wezterm                                                                                      
11:08:09.148  ERROR  wezterm_gui > running message loop: process_queued_xcb: poll_for_queued_event: X(Match(RequestError { response_type: 0, error_code: 8, sequence: 274, bad_value: 41943049, minor_opcode: 4, major_opcode: 149, pad: 1 }), None); terminating
```

### To Reproduce

Upgrade kernel and relative stuff via `apt update` and `apt upgrade`.
Type `wezterm` in terminal or called wezterm in app menu. Both showed the same error msg.

But to be sure, I don't know what's the root cause of this issue. Maybe it's not about the new kernal.

### Configuration

no config.

### Expected Behavior

Fire wezterm as before.

### Logs

```log
  │ File: wezterm-gui-log-39091.txt
──┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  │ 11:15:12.864  ERROR  wezterm_gui > running message loop: process_queued_xcb: poll_for_queued_event: X(Match(RequestErr
  │ or { response_type: 0, error_code: 8, sequence: 274, bad_value: 41943049, minor_opcode: 4, major_opcode: 149, pad: 1 }
  │ ), None); terminating

```

**Comment by Colduck** [comment]
Have you checked that wezterm is present in the path? I had this issue on Mac and I fixed it by adding it to the path and now `Navigator.nvim` plugin works like a charm with Wezterm:

`export PATH="/path/to/wezterm:$PATH"`

**Comment by CharlesChiuGit** [comment]
> Have you checked that wezterm is present in the path? I had this issue on Mac and I fixed it by adding it to the path and now `Navigator.nvim` plugin works like a charm with Wezterm:
> 
> `export PATH="/path/to/wezterm:$PATH"`

Hi, @Colduck thanks for the reply. I think it's in the path since I can call wezterm in the terminal, but i'll check if wezterm does exist in it or not.

**Comment by CharlesChiuGit** [comment]
still having this issue after adding it to my zshrc.

cc @Colduck @wez

**Comment by CharlesChiuGit** [comment]
The exact same error still exist after 2 months. Tried download the binary and build from git repo, non of it works.
![圖片](https://user-images.githubusercontent.com/32497323/233889105-fc6592e4-de97-43f5-8e0a-b71302cdbaac.png)

**Comment by CharlesChiuGit** [comment]
Fixed after change `front_end = "WebGpu",` to `front_end = "OpenGL",`
