### ISSUE TITLE
wezterm terminal settings shortcut key clear to previous cursor position

### ISSUE THREAD

**Issue by wangmings** [wez/wezterm#3119]
#  wezterm terminal settings shortcut key clear to previous cursor position

ESC M | 0x8D | RI | Reverse Index | Move the cursor up one line. If the cursor is at the top margin, scroll the region down

```bash
{
      key="l", 
      mods="CMD", 
      ESC M
      action = wezterm.action.SendString '\x1B\x4D'
 },
```
It never worked.

**Comment by wez** [comment]
I'm not sure I understand this issue; are you asking for this to be added, or are you asking for help with it not doing what you expect?
