### ISSUE TITLE
wezterm ls-fonts --list-system panics

### ISSUE THREAD

**Issue by girtsf** [wez/wezterm#3120]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230212-103106-a5c2b1f3

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Running `wezterm.exe ls-fonts --list-system` results in a panic.

Full log (with `WEZTERM_LOG=wezterm_font=trace,info`) is here: https://gist.github.com/girtsf/3609cfc5d7fafae602a6295ea8360d35

```
10:24:07.471  ERROR  env_bootstrap                  > panic at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\dwrote-0.11.0\src\font_family.rs:75:13 - assertion failed: hr == 0
   0: git_tag_tagger
   1: git_tag_tagger
   2: <unknown>
   3: git_filter_source_mode
   4: git_filter_source_mode
   5: git_filter_source_mode
   6: git_filter_source_mode
   7: git_credential_username_new
   8: git_credential_username_new
   9: git_tag_tagger
  10: git_tag_tagger
  11: git_tag_tagger
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: git_filter_source_mode
  17: <unknown>
  18: git_credential_username_new
  19: BaseThreadInitThunk
  20: RtlUserThreadStart

thread 'main' panicked at 'assertion failed: hr == 0', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\dwrote-0.11.0\src\font_family.rs:75:13
stack backtrace:
   0:     0x7ff634261312 - git_filter_source_mode
   1:     0x7ff63428735b - git_filter_source_mode
   2:     0x7ff63425864a - git_filter_source_mode
   3:     0x7ff63426105b - git_filter_source_mode
   4:     0x7ff634263fb9 - git_filter_source_mode
   5:     0x7ff634263c3b - git_filter_source_mode
   6:     0x7ff6331f26ad - <unknown>
   7:     0x7ff634264880 - git_filter_source_mode
   8:     0x7ff63426459b - git_filter_source_mode
   9:     0x7ff63426200f - git_filter_source_mode
  10:     0x7ff634264290 - git_filter_source_mode
  11:     0x7ff6347a7e05 - git_credential_username_new
  12:     0x7ff6347a7efc - git_credential_username_new
  13:     0x7ff633ce4876 - git_tag_tagger
  14:     0x7ff633cbdaf2 - git_tag_tagger
  15:     0x7ff633ca1d69 - git_tag_tagger
  16:     0x7ff63309c66d - <unknown>
  17:     0x7ff633096bbb - <unknown>
  18:     0x7ff633009e36 - <unknown>
  19:     0x7ff6330a26ec - <unknown>
  20:     0x7ff634250c3e - git_filter_source_mode
  21:     0x7ff6330a1f1c - <unknown>
  22:     0x7ff634701150 - git_credential_username_new
  23:     0x7ff804ae7614 - BaseThreadInitThunk
  24:     0x7ff8066626a1 - RtlUserThreadStart
```

### Configuration

no config

### Expected Behavior

no panic :)

**Comment by wez** [comment]
I can't reproduce this.
Looking at the code in the upstream dwrote crate:

https://github.com/servo/dwrote-rs/blob/master/src/font_family.rs#L67-L75

it appears that the issue is probably that one of the fonts on your system is returning a value from `get_font_count()` for which `get_font()` returns a null pointer and the assertion in that function is triggered, terminating wezterm.

There's not really anything wezterm can do about that.

I wonder if you have a corrupt font installed?

If you set `WEZTERM_LOG=wezterm_font::locator::gdi=trace,info` in the environment before you run `wezterm ls-fonts --list-system`, it may give you some clues about which font correlates with this.
