### ISSUE TITLE
Maximize window key assigment

### ISSUE THREAD

**Issue by ckt114** [wez/wezterm#3123]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a `MaximizeWindow` key assignment to be used with key binding.

**Describe alternatives you've considered**
I've tried to code it using the `keys` binding but was not able to.

**Additional context**
N/A

**Comment by wez** [comment]
This is possible using https://wezfurlong.org/wezterm/config/lua/window/maximize.html together with https://wezfurlong.org/wezterm/config/lua/wezterm/action_callback.html

Something like:

```lua
local wezterm = require 'wezterm'

return {
  keys = {
    {
      mods = 'ALT',
      key = 'm',
      action = wezterm.action_callback(function(win, pane)
        win:maximize()
      end),
    },
  },
}

```

**Comment by ckt114** [comment]
That works beautifully. Thanks, @wez.
