### ISSUE TITLE
Keycodes being printed when holding shift in neovim terminal

### ISSUE THREAD

**Issue by hgaiser** [wez/wezterm#3124]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Gnome

### WezTerm version

wezterm 20230217-120342-3b39aa55

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When in a terminal in neovim, pressing Shift + Backspace, Enter, Escape (and probably others) prints sequences like `7;2u` for `Shift + Backspace`. This doesn't happen outside of neovim. 

### To Reproduce

```
nvim --clean
:terminal
Shift + Backspace
```

### Configuration

no config

### Expected Behavior

No keycodes being printed.

### Anything else?

The issue seems similar to https://github.com/wez/wezterm/issues/2671 , however I don't have `enable_csi_u_key_encoding` enabled. It is probably related to CSI U encodings though, but I couldn't find if the issue was with wezterm or with neovim. It's possible wezterm isn't doing anything out of the ordinary, however the "bug" does not appear on tilix and alacritty, which is why I'm trying to report the issue here :).

Also, I have `TERM=wezterm` set in my environment.

As a side note, thanks for this terminal, loving it so far!

**Comment by wez** [comment]
Does the behavior change when you set `TERM=xterm-256color`?

It sounds like this is related to [modifyOtherKeys](https://wezfurlong.org/wezterm/config/key-encoding.html#xterm-modifyotherkeys) mode.

Please enable [debug_key_events](https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html) and share the logs from you pressing that key combination so that we can see what is being sent to the terminal.

**Comment by hgaiser** [comment]
> Does the behavior change when you set `TERM=xterm-256color`?
> 
> It sounds like this is related to [modifyOtherKeys](https://wezfurlong.org/wezterm/config/key-encoding.html#xterm-modifyotherkeys) mode.
> 
> Please enable [debug_key_events](https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html) and share the logs from you pressing that key combination so that we can see what is being sent to the terminal.

Thanks for the quick reply. The behavior is the same with `TERM=xterm-256color`, no change there. I added `debug_key_events`, here are the logs:

```
16:37:45.603  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:37:45.603  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Shift, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:37:45.603  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Shift mods=NONE
16:37:46.227  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(Backspace), modifiers: SHIFT, phys_code: Some(Backspace), raw_code: 22, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:37:46.227  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('\u{8}'), modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Backspace), modifiers: SHIFT, phys_code: Some(Backspace), raw_code: 22, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
16:37:46.227  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Backspace mods=SHIFT
16:37:46.227  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[27;2;127~", Backspace SHIFT
16:37:46.298  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('\u{8}'), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Backspace), modifiers: SHIFT, phys_code: Some(Backspace), raw_code: 22, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:37:46.299  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Backspace mods=SHIFT
16:37:46.387  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Shift, modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
16:37:46.387  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Shift mods=SHIFT
```

**Comment by gagbo** [comment]
I have the same issue when using Emacs in a terminal window (`emacs -q -nw`).

I actually use an alternate, custom layout on MacOS that maps the numbers to shift+number (within other changes that shouldn't matter).

When I hit "Shift + =" (that's supposed to be `8`), I expect Emacs to see `8` and treat that for the next command.
Instead, I see `∼ is undefined`. Here is the log of the keyevents:

```
11:19:16.108  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('8'), modifiers: SHIFT, phys_code: Some(K8), raw_code: 28, repeat_count: 1, key_is_down: true, handled: Handled(false) }
11:19:16.108  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('8'), modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Char('8'), modifiers: SHIFT, phys_code: Some(K8), raw_code: 28, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
11:19:16.108  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('8') mods=SHIFT
11:19:16.108  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[27;2;56~", Char('8') SHIFT
11:19:16.162  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('8'), modifiers: SHIFT, phys_code: Some(K8), raw_code: 28, repeat_count: 1, key_is_down: false, handled: Handled(false) }
11:19:16.162  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('8'), modifiers: SHIFT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('8'), modifiers: SHIFT, phys_code: Some(K8), raw_code: 28, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
11:19:16.162  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('8') mods=SHIFT
```

Note that I can't reproduce that bug in most other setups:
- Neovim in wezterm works (I see "8" when I type the key in insert mode), so you'd think it's an Emacs-only matter, but:
- Emacs in Kitty, Alacritty works (I see "8" being processed as part of a prefix-argument, which is what I expect)
- In raw wezterm window, "8" works (I can type "8" in the command line)

So there are probably specifics around how Emacs handles the events that the terminal sends to it (and probably the same with neovim built-in terminal), but there might be a trick that works for all of those, that other terminal figured out.

Note: I didn't try to change the `TERM` variable, I assumed that the brew install both added a terminfo entry and set the TERM for Wezterm to a matching value.

**Comment by wez** [comment]
Finally got around to looking at this, and ran through the same steps in xterm, which is the terminal after which wezterm models its behavior, especially with regard to modifyOtherKeys, which originated and specified that functionality.

wezterm behaves the same as xterm here; here's xterm:

![image](https://user-images.githubusercontent.com/117777/230635540-56686674-9a52-4ce0-b3a6-2d6833cd35f6.png)

I'd classify this as an nvim implementation bug; it's not decoding these particular key sequences so the remainder spill out as junk input to the terminal.

**Comment by wez** [comment]
@gagbo please open a separate issue
