### ISSUE TITLE
AMD  iGPU + WebGpu + Wayland renders only when mouse move over the window

### ISSUE THREAD

**Issue by Guara92** [wez/wezterm#3126]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20230217-120342-3b39aa55

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm trying the `WebGpu` front end and is unusable on my system with wayland enabled, with wayland disabled runs really smooth.

```
> wezterm.gui.enumerate_gpus()
[
    {
        "backend": "Vulkan",
        "device": 5710,
        "device_type": "IntegratedGpu",
        "driver": "radv",
        "driver_info": "Mesa 23.1.0-devel",
        "name": "AMD Radeon Graphics (RADV GFX1036)",
        "vendor": 4098,
    },
    {
        "backend": "Vulkan",
        "device": 0,
        "device_type": "Cpu",
        "driver": "llvmpipe",
        "driver_info": "Mesa 23.1.0-devel (LLVM 15.0.7)",
        "name": "llvmpipe (LLVM 15.0.7, 256 bits)",
        "vendor": 65541,
    },
    {
        "backend": "Gl",
        "device": 0,
        "device_type": "Other",
        "name": "AMD Radeon Graphics (gfx1036, LLVM 15.0.7, DRM 3.49, 6.1.12-xm1.0e20221004.fc37.x86_64)",
        "vendor": 4098,
    },
]
```

### Configuration

```lua
enable_wayland = true,
front_end = "WebGpu",
```

**Comment by wez** [comment]
Please share the the `OpenGL version` line from the debug overlay on your system

**Comment by Guara92** [comment]
`OpenGL version: AMD Radeon Graphics (gfx1036, LLVM 15.0.7, DRM 3.49, 6.1.12-xm1.0e20221004.fc37.x86_64) 4.6 (Compatibility Profile) Mesa 23.1.0-devel`

**Comment by colemickens** [comment]
I'm seeing the same, even when the debug overlay says its using WebGPU+Vulkan:

```
OpenGL version: WebGPU: name=AMD Radeon Graphics (RADV REMBRANDT), device_type=IntegratedGpu, backend=Vulkan, driver=radv, driver_info=Mesa 22.3.5, vendor=4098, device=5761
```

I'm on NixOS as well, but I've patched the wezterm derivation to include vulkan-loader and I don't see any obvious errors.

**Comment by VarLad** [comment]
Can confirm here as well.
@wez Interestingly, it renders when I move the mouse cursor, not otherwise.
Any idea whats going on here?

**Comment by colemickens** [comment]
Hi @wez, I try the latest tip build every week or two. I've also done some work on OpenGL/Vulkan NixOS stuffs so I have a rough idea about some parts at least.I'm willing to sink a bit of time into debugging it. Can you give me some hints on what I can track down?

**Comment by wez** [comment]
There are two possible paths to follow:

* Is this a general wezterm/wayland issue where the window is repainted as often as it should?
* Is this a problem with the amd drivers?

For the former, it's possible that wezterm is not invalidating/paintain in all the right places, depending on the wayland compositor that is in use. I would suggest trying a couple of different compositors from different families to see if things work better.  It can be useful to set WAYLAND_DEBUG=1 in the environment when starting wezterm to see what is happening with the wayland protocol to see how the behavior differs and see if anything leaps out.  I don't have a ton of wisdom to share on this.

For the latter: not super sure how to proceed; An obvious thing would be to try connecting a different GPU and see if that works better.  Another option would be to reach out to the folks that maintain the AMD drivers and see what they have to suggest for troubleshooting.

It's important to note that wezterm doesn't change its behavior based on the driver; the only differences in wezterm are whether you are using EGL directly, or are using the WebGPU layer.  Below that point, the actual heavy lifting is done by the drivers installed on the system.

**Comment by VarLad** [comment]
@Guara92 Is your issue same as 
> it renders when I move the mouse cursor over wezterm, not otherwise

If so, it'd be nice to update the issue accordingly.

**Comment by jokeyrhyme** [comment]
This is happening for me in sway, and on both AMD and Intel GPUs, so not GNOME-specific

- I tried out `WAYLAND_DEBUG=1 wezterm --config='front_end="WebGPU"'`
- when I'm typing (and not seeing the output) the logs have entries like:

```
[  76172.959] wl_keyboard@14.key(21907, 42401238, 38, 1)
[  76173.037]  -> wl_pointer@16.set_cursor(0, nil, 0, 0)
[  76255.781] wl_keyboard@14.key(21908, 42401321, 38, 0)
[  76255.845]  -> wl_pointer@16.set_cursor(0, nil, 0, 0)
[  76483.950] wl_keyboard@14.key(21909, 42401549, 31, 1)
[  76484.028]  -> wl_pointer@16.set_cursor(0, nil, 0, 0)
[  76587.677] wl_keyboard@14.key(21910, 42401653, 31, 0)
[  76587.743]  -> wl_pointer@16.set_cursor(0, nil, 0, 0)
[  77422.957] wl_keyboard@14.key(21911, 42402488, 28, 1)
[  77423.039]  -> wl_pointer@16.set_cursor(0, nil, 0, 0)
[  77506.678] wl_keyboard@14.key(21912, 42402572, 28, 0)
[  77506.742]  -> wl_pointer@16.set_cursor(0, nil, 0, 0)
```

- and when I'm waving the mouse over the window

```
[ 176131.866] wl_pointer@28.enter(22289, wl_surface@21, 0.87890625, 419.77343750)
[ 176131.923]  -> wl_shm@4.create_pool(new id wl_shm_pool@46, fd 33, 1024)
[ 176132.109]  -> wl_shm_pool@46.resize(3328)
[ 176132.116]  -> wl_shm_pool@46.create_buffer(new id wl_buffer@44, 1024, 24, 24, 96, 0)
[ 176132.123]  -> wl_surface@27.set_buffer_scale(1)
[ 176132.126]  -> wl_surface@27.attach(wl_buffer@44, 0, 0)
[ 176132.129]  -> wl_surface@27.damage_buffer(0, 0, 24, 24)
[ 176132.132]  -> wl_surface@27.commit()
[ 176132.135]  -> wl_pointer@28.set_cursor(22289, wl_surface@27, 4, 4)
[ 176132.141] wl_pointer@28.frame()
[ 176132.143] wl_pointer@16.enter(22289, wl_surface@21, 0.87890625, 419.77343750)
[ 176132.149] wl_pointer@16.frame()
[ 176132.152] wl_pointer@28.frame()
[ 176132.153] wl_pointer@16.frame()
[ 176132.498] wl_buffer@44.release()
[ 176132.507] wl_surface@27.enter(wl_output@11)
[ 176135.877] wl_pointer@28.motion(42501201, 1.87890625, 419.77343750)
[ 176135.887] wl_pointer@16.motion(42501201, 1.87890625, 419.77343750)
[ 176135.895] wl_pointer@28.frame()
[ 176135.897] wl_pointer@16.frame()
[ 176135.929]  -> wl_surface@21.commit()
[ 176135.950]  -> wl_shm@4.create_pool(new id wl_shm_pool@41, fd 37, 1024)
[ 176136.089]  -> wl_shm_pool@41.resize(3328)
[ 176136.093]  -> wl_shm_pool@41.create_buffer(new id wl_buffer@57, 1024, 24, 24, 96, 0)
[ 176136.099]  -> wl_surface@17.set_buffer_scale(1)
[ 176136.102]  -> wl_surface@17.attach(wl_buffer@57, 0, 0)
[ 176136.105]  -> wl_surface@17.damage_buffer(0, 0, 24, 24)
[ 176136.107]  -> wl_surface@17.commit()
[ 176136.109]  -> wl_pointer@16.set_cursor(22289, wl_surface@17, 11, 12)
[ 176136.584] wl_buffer@57.release()
[ 176136.591] wl_surface@27.leave(wl_output@11)
[ 176136.597] wl_surface@17.enter(wl_output@11)
[ 176138.860] wl_pointer@28.motion(42501204, 2.87890625, 419.77343750)
[ 176138.870] wl_pointer@16.motion(42501204, 2.87890625, 419.77343750)
[ 176138.876] wl_pointer@28.frame()
[ 176138.878] wl_pointer@16.frame()
[ 176138.897]  -> wl_surface@21.commit()
[ 176138.906]  -> wl_surface@17.set_buffer_scale(1)
[ 176138.910]  -> wl_surface@17.attach(wl_buffer@57, 0, 0)
[ 176138.913]  -> wl_surface@17.damage_buffer(0, 0, 24, 24)
[ 176138.916]  -> wl_surface@17.commit()
[ 176138.919]  -> wl_pointer@16.set_cursor(22289, wl_surface@17, 11, 12)
[ 176139.432] wl_buffer@57.release()
```

- without really know much about what I'm talking about here, I _think_ it's the `damage_buffer()` calls that tell compositors that a surface needs to be re-rendered? maybe? or the other way around? :shrug:

**Comment by jdelkins** [comment]
Same issue for me under Gnome Wayland, sway, or hyprland with `amdvlk` WebGpu, so not limited to Gnome or iGPU. I am using an antique (polaris10) GPU though, so I often require workarounds for weird Wayland stuff. In my case, Gl driver works fine.

```
Debug Overlay
wezterm version: 20230320-124340-559cb7b0 x86_64-unknown-linux-gnu
Window Environment: Wayland
OpenGL version: WebGPU: name=AMD Radeon RX 480 Graphics, device_type=DiscreteGpu, backend=Vulkan, driver=AMD open-source driver, driver_info=2022.Q4.4 (LLPC), vendor=4098, device=26591
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
15:35:56.755 WARN wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 66, cols: 125 }) because window_state is MAXIMIZED
> wezterm.gui.enumerate_gpus()
[
    {
        "backend": "Vulkan",
        "device": 26591,
        "device_type": "DiscreteGpu",
        "driver": "AMD open-source driver",
        "driver_info": "2022.Q4.4 (LLPC)",
        "name": "AMD Radeon RX 480 Graphics",
        "vendor": 4098,
    },
    {
        "backend": "Gl",
        "device": 0,
        "device_type": "Other",
        "name": "AMD Radeon RX 480 Graphics (polaris10, LLVM 15.0.7, DRM 3.49, 6.2.8-zen1-1-zen)",
        "vendor": 4098,
    },
]
```

**Comment by develop7** [comment]
Confirming the issue for NVIDIA RTX 3080 in GNOME 44.0 on openSUSE Tumbleweed 20230405:

```
Debug Overlay
wezterm version: 20230326.111934.3666303c x86_64-unknown-linux-gnu
Window Environment: Wayland
OpenGL version: WebGPU: name=NVIDIA GeForce RTX 3080, device_type=DiscreteGpu, backend=Vulkan, driver=NVIDIA, driver_info=525.105.17, vendor=4318, device=8726
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
> wezterm.gui.enumerate_gpus()
[
    {
        "backend": "Vulkan",
        "device": 8726,
        "device_type": "DiscreteGpu",
        "driver": "NVIDIA",
        "driver_info": "525.105.17",
        "name": "NVIDIA GeForce RTX 3080",
        "vendor": 4318,
    },
    {
        "backend": "Vulkan",
        "device": 0,
        "device_type": "Cpu",
        "driver": "llvmpipe",
        "driver_info": "Mesa 23.0.1 (LLVM 16.0.0)",
        "name": "llvmpipe (LLVM 16.0.0, 256 bits)",
        "vendor": 65541,
    },
    {
        "backend": "Gl",
        "device": 0,
        "device_type": "Other",
        "name": "NVIDIA GeForce RTX 3080/PCIe/SSE2",
        "vendor": 4318,
    },
]
```

**Comment by jokeyrhyme** [comment]
Okay, I finally took a look at the source code

I instrumented this [`WaylandWindowInner.invalidate()`](https://github.com/wez/wezterm/blob/56ae2fe27671640f1a1490201da7615b98b678e2/window/src/os/wayland/window.rs#L1100-L1106) function:
- called during keyboard input (typing whilst focused), does NOT call `do_paint()`
- called during mouse movement over the window, DOES call `do_paint()` (expected)
- called during mouse click in the window, does NOT call `do_paint()`
- called during resizing the window while focused, does NOT call `do_paint()`
- called whenever shell output changes (running `yes`), does NOT call `do_paint()`
- NOT called during resizing the window while not focused (expected, this is not the outer `WaylandWindow`?)

But, I short-circuited it so that it always sets `self.invalidated = true` and calls `do_paint()` and that still didn't fix it

After some more instrumentation, I _think_ the problem is that [this part of `do_paint()`](https://github.com/wez/wezterm/blob/56ae2fe27671640f1a1490201da7615b98b678e2/window/src/os/wayland/window.rs#L811-L814) doesn't run when we need it to

I removed the check at the top of `do_paint()`, and that does _seem_ to fix the issue, but focusing another window and then focusing wezterm again causes the issue to come back

**Comment by jokeyrhyme** [comment]
With direction from @wez , this seems to have fixed it, at least for me under sway(wlroots): 
https://github.com/wez/wezterm/commit/40bb0533cb9c0414da6a6841edd3ab336f6e6fc0

But, I'm not sure if this breaks anything else, and I'm not sure if doing this is a no-no according to the wayland specification, etc

**Comment by jokeyrhyme** [comment]
Okay, with more direction, trying wayland with the different `PresentMode`s https://docs.rs/wgpu/latest/wgpu/enum.PresentMode.html here https://github.com/wez/wezterm/blob/56ae2fe27671640f1a1490201da7615b98b678e2/wezterm-gui/src/termwindow/webgpu.rs#L323

- AutoVsync: bug
- AutoNoVsync: bug
- Fifo (current value in main branch): bug
- FifoRelaxed: `thread 'main' panicked at 'Error in Surface::configure: requested present mode FifoRelaxed is not in the list of supported present modes: [Mailbox, Fifo]'`
- Immediate: `thread 'main' panicked at 'Error in Surface::configure: requested present mode Immediate is not in the list of supported present modes: [Mailbox, Fifo]'`
- Mailbox: bug

**Comment by jokeyrhyme** [comment]
Okay, new patch up: https://github.com/jokeyrhyme/wezterm/commit/2574933ffca058a3f6b7ef55ed0896a6d49b77d5

I tried both with WebGPU and without, focused and not focused, switching to different workspaces and back, seems like the suggested patch has fixed it

**Comment by jokeyrhyme** [comment]
I've raised a PR: https://github.com/wez/wezterm/pull/3467

**Comment by jokeyrhyme** [comment]
Haha, I'll drop the PR :P

**Comment by wez** [comment]
Thanks for working through this @jokeyrhyme !
I just pushed a version of the commit with a bit more exposition in the comments

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by VarLad** [comment]
This does fix the issue, thanks!
On the other hand now, another issue I notice now is, continuous button presses are rather slow, in the webgpu frontend.

I think that needs its own issue though

**Comment by Guara92** [comment]
Thanks, fixed for me too!

**Comment by colemickens** [comment]
Wezterm has finally taken its throne as my daily driver under Sway with webgpu! Thanks @wez  and @jokeyrhyme!
