### ISSUE TITLE
Open web browser

### ISSUE THREAD

**Issue by ckt114** [wez/wezterm#3127]
**Is your feature request related to a problem? Please describe.**
I’m using the [Octo](https://github.com/pwntester/octo.nvim) neovim plugin and one of the mappings is to open a PR in a browser with `:Octo pr browser` and this works perfectly with Kitty and Alacritty but not with Wezterm.

**Describe the solution you'd like**
Able to open browser from Wezterm. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by wez** [comment]
I think this is more of a feature request for octo than for wezterm. Please file an issue over there and loop me in if something is needed from wezterm to support that.

**Comment by ckt114** [comment]
[Here's](https://github.com/pwntester/octo.nvim/blob/master/lua/octo/navigation.lua#L8) the implentation of that and it looks like it just calls the `gh` command so it looks like it's not terminal-specific?

**Comment by wez** [comment]
If you manually run the `gh` command that it would run, does it generate any error messages?

**Comment by ckt114** [comment]
So the command below which is what Octo executes to open the browser. I tried it in those 3 terminals and they all work but get error below in wezterm.

```
$ gh pr view --web -R MyOrg/MyRepo 24101
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-600 "procNotFound: no eligible process with specified descriptor" UserInfo={_LSLine=388, _LSFunction=_LSAnnotateAndSendAppleEventWithOptions}
exit status 1
```

**Comment by wez** [comment]
Please file an issue with the `gh` cli folks so they can help you figure out what exactly is happening, and then loop me in if something is needed from wezterm to support that.

**Comment by ckt114** [comment]
So I found [this issue](https://github.com/cli/cli/issues/6650) on gh issues' page and it suggested me reboot and I did an it's working fine with wezterm now. It's odd but it worked.
