### ISSUE TITLE
Wezterm unable to find glyphs in MesloLGS NF Font Set

### ISSUE THREAD

**Issue by miversen33** [wez/wezterm#3128]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 with Gnome Shell
> gnome-shell v: 43.2 driver: X: loaded: modesetting

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I open a file (an example, you can pull down my zshrc file found [here](https://github.com/miversen33/miversen-dotfiles/blob/master/shells/.shellrc) and scroll to line 108), I am presented with the following error

> 10:45:43.615  WARN   wezterm_font                > No fonts contain glyphs for these codepoints: \u{30c4}.
> Placeholder 'Last Resort' glyphs are being displayed instead.
> You may wish to install additional fonts, or adjust your
> configuration so that it can find them.
> https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
> Set warn_about_missing_glyphs=false to suppress this message

A side-by-side screenshot of the issue as well. The left half is the same file open in alacritty using "MesloLGS NF", and the right is wezterm using "MesloLGS NF"

![image](https://user-images.githubusercontent.com/2640668/219877907-f0ede89f-fa78-4fcd-869e-fdba55e5e50e.png)

### To Reproduce

Open a file that contains a glyph while using the ["MesloLGS NF"](https://github.com/romkatv/powerlevel10k#manual-font-installation) font family

### Configuration

```lua
return {
    font = require("wezterm").font('MesloLGS NF')
}
```

### Expected Behavior

I would expect Wezterm to be able to locate the glyphs as other terminal emulators do.

### Logs

10:52:46.711  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{30c4}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.

### Anything else?

I don't know if it matters, but I my OS info is below

> OS: Arch Linux x86_64
> Kernel: 6.1.11-arch1-1
> DE: GNOME 43.2
> WM: Mutter
> Shell: zsh 5.9
> GPU: Intel Alder Lake-P

Its possible that I am missing something here, I just don't quite know what. It is loading the MesloLGS font (_I think_?) it just seems to be struggling with non-english characters. It does handle emojis just fine (and in theory I could just update that string to not have the japanese characters that are displayed, but do I really want to be editing comments to account for the terminal that may be used to view them?)

I am just getting started with Wezterm so please forgive any ignorance/mistakes in my usage of it. Its a pretty slick emulator and if I can work through getting my configuration merged with Tmux and Alacritty, I love the idea of a true multiplatform terminal :)

**Comment by miversen33** [comment]
Note, I do _not_ experience this issue on my Windows 10 machine. I will try reinstalling the font on my arch machine and see if that corrects it.

**Comment by wez** [comment]
What does `fc-list ':charset=30c4'` output on your system(s)?
Are any of the fonts it lists monospace?

You can add `-v` to that command to get a lot of verbose details; the `spacing` field is used to determine if a font is monospace.

**Comment by wez** [comment]
For background: not all fonts contain all glyphs. When your listed fonts don't contain the glyphs you're using, wezterm asks the system to figure out which fonts might have it. On linux systems we use font-config; that `fc-list` command gives you an ad-hoc way to see more about font-config thinks.

**Comment by miversen33** [comment]
> What does `fc-list ':charset=30c4'` output on your system(s)? Are any of the fonts it lists monospace?

```bash
$ fc-list ':charset=30c4'
/usr/share/fonts/kanjistrokeorders/KanjiStrokeOrders.ttf: KanjiStrokeOrders:style=Medium
```

Also what its printing out for MesloLGS
```bash
$ fc-list | grep Meslo
/home/miversen/.fonts/m/MesloLGS_NF_Italic.ttf: MesloLGS NF:style=Italic
/home/miversen/.fonts/m/MesloLGS_NF_Regular.ttf: MesloLGS NF:style=Regular
/home/miversen/.fonts/m/MesloLGS_NF_Bold.ttf: MesloLGS NF:style=Bold
/home/miversen/.fonts/m/MesloLGS_NF_Bold_Italic.ttf: MesloLGS NF:style=Bold Italic
```

What has me most confused here is that other programs are able to use this font with the glyphs mentioned with no issues. EG, alacritty, tmux, vscode, etc.

I'm not really sure what to make of it :/

**Comment by wez** [comment]
They don't find that glyph in MesloLGS; they ask font config where to find it, and it tells them to use `KanjiStrokeOrders` based on that `fc-list` query result you shared.

Please run:

```
fc-list ':charset=30c4' -v > info.txt
```

and attach `info.txt` to this issue as an attached file

**Comment by miversen33** [comment]
[info.txt](https://github.com/wez/wezterm/files/10807831/info.txt)

Here ya go :) I appreciate your help! Im starting to wonder if I have installed the font wrong.

**Comment by wez** [comment]
is the output different on the system where you said it worked with wezterm?

**Comment by wez** [comment]
Ah, it's a windows machine? You can run `wezterm ls-fonts --codepoints 30c4` to show what it is using there

**Comment by miversen33** [comment]
The machine that is functional is a windows machine. 
Here is the output from that.

```
LeftToRight
 0 ツ    \u{30c4}     x_adv=12 cells=2  glyph=23761 wezterm.font("Yu Gothic UI", {weight="Regular", stretch="Normal", style="Normal"})
                                      C:\WINDOWS\FONTS\YUGOTHM.TTC index=1 variation=0, DirectWrite
                                      ```

**Comment by wez** [comment]
What I think is happening is that `KanjiStrokeOrders` is not a monospace font, so wezterm doesn't consider it usable as a terminal font.

You can explicitly add it to your fallback list using:

```lua
return {
    font = require("wezterm").font_with_fallback {'MesloLGS NF', 'KanjiStrokeOrders'}
}
```

However, if you can find another monospace font that contains that  glyph, then installing that should give you what you're looking for.  For example, on my linux box, that glyph is provided by:

```
; wezterm ls-fonts --codepoints 30c4
LeftToRight
 0 ツ    \u{30c4}     x_adv=13.328125 cells=2  glyph=147  wezterm.font("Droid Sans Japanese", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-droid-sans-fonts/DroidSansJapanese.ttf, FontConfig
```

**Comment by miversen33** [comment]
Your explicit fallback solves it! Do you recommend using the fallback as the "solution" here?

**Comment by wez** [comment]
You can go either route; I would personally recommend and prefer installing a proper monospace font to avoid weird spacing/alignment issues.
