### ISSUE TITLE
Import config from a separate file

### ISSUE THREAD

**Issue by ckt114** [wez/wezterm#3129]
**Is your feature request related to a problem? Please describe.**
I'm trying to read in a set of configuration from a separate file than `wezterm.lua` via require but unable to. I have a `theme.lua` from in the same folder as `wezterm.lua` with just `return "myfavtheme"` using require to import it and set to `color_scheme` but it's not working. Can this be supported?

**Describe the solution you'd like**
Import a another `.lua` file into `wezterm.lua`.

**Describe alternatives you've considered**
I've tried code below in `wezterm.lua` but it's not working.
```lua
local theme_ok, theme = pcall(require, "theme")
if theme_ok then
  return theme
end
```
Tried `wezterm.theme`, `user.theme`, `theme.lua` but still doesn't work.

**Additional context**
N/A

**Comment by wez** [comment]
It's not very clearly explained at https://wezfurlong.org/wezterm/config/files.html but additional modules are loaded from `~/.config/wezterm/`.

So if you place your theme file at `~/.config/wezterm/theme.lua`  then you should be able to use:

```lua
local theme = require 'theme'
```

**Comment by ckt114** [comment]
It's working now. Thanks.

**Comment by wez** [comment]
Let's keep this open until I write up some clearer docs on this

**Comment by ckt114** [comment]
Actually it is documented [here](https://wezfurlong.org/wezterm/config/lua/general.html) but as a user I wouldn’t have thought of looking there. If you could link/reference it in [this](https://wezfurlong.org/wezterm/config/files.html) page at the top I think it would be helpful.

**Comment by wez** [comment]
I recently moved this stuff around, and https://wezfurlong.org/wezterm/config/files.html#making-your-own-lua-modules is now a section on the main config files page
