### ISSUE TITLE
expand "~" in color_scheme_dirs to $HOME

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#313]
**Is your feature request related to a problem? Please describe.**

I used `color_scheme_dirs = {"~/.config/wezterm/themes"},` and put my them toml file into that directory, but wezterm didn't find it. If I used a full path, it worked. The problem is that I work on both linux and mac and both have different path so I cannot move my config between these two systems.

When I moved the themes to the `colors` subfolder, it also worked without specifying any `color_scheme_dirs` (because it is aded in wezterm itself: https://github.com/wez/wezterm/blob/7f82f333f135592ea0c84597e6397ebd65fa1520/config/src/lib.rs#L1067 -> thats my current solution

**Describe the solution you'd like**

* Allow for `~` to be expanded to the content of $HOME
* Document that the subfolder `colors` is automatically added to the search path
* Maybe: show the folders wezterm is configured to look in when printing the warning that a theme isn't found

**Describe alternatives you've considered**

Doing nothing :-)

**Comment by alexherbo2** [comment]
[mpv] also resolves `~~` to the mpv config dir.  It can be nice and because the config location can vary.

See [Paths] for a complete reference.

[mpv]: https://mpv.io
[Paths]: https://mpv.io/manual/master#paths

**Comment by bew** [comment]
I think this should be closed.
OP should use https://wezfurlong.org/wezterm/config/lua/wezterm/home_dir.html to get the home directory, so sth like:
```lua
local wezterm = require("wezterm")
return {
  color_scheme_dirs = {wezterm.home_dir .. "/.config/wezterm/themes"},
}
```

**Comment by bew** [comment]
@wez can we close this? Or do you want to do something for this?

**Comment by wez** [comment]
I'm going to close this without "fixing" it; tilde expansion is awkward to inject in every place where a path might be used (there is always potential for it to error) and `wezterm.home_dir` is provided for cases where you need to be dynamic.
