### ISSUE TITLE
question about Reverse Index

### ISSUE THREAD

**Issue by wangmings** [wez/wezterm#3133]
# ANSI escape is not supported for this terminal
ESC M | 0x8D | RI | Reverse Index | Move the cursor up one line. If the cursor is at the top margin, scroll the region down

echo -e "\e[5M"
print -P "\e[M"

After testing does not work, I do not know if I wrote it wrong, running it does not move the cursor to the previous line

**Comment by wez** [comment]
`ESC M` would be `echo -e '\eM'`.  It doesn't accept any parameters.

You may want to use the `CUU` sequence instead: `echo -e '\e[5A`
