### ISSUE TITLE
Get process name under WSL

### ISSUE THREAD

**Issue by cultab** [wez/wezterm#3137]
**Is your feature request related to a problem? Please describe.**
I trying to get keybinds that exhibit different behavior depending on the program in the current pane. I'm doing this in hopes of having behavior like [christoomey/vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) but for wezterm, aka seemless vim<=>wezterm pane navigation. The problem I'm having is that in WSL, [pane:get_foreground_process_name()](https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html#paneget_foreground_process_name) seems to always return `wslhost.exe`.

**Describe the solution you'd like**
I'd like a way to get the *actual* process running under wsl. Changing the behavior of [pane:get_foreground_process_name()](https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html#paneget_foreground_process_name) under WSL might not be the best idea, but maybe an additional optional argument could augment the behavior?

**Describe alternatives you've considered**
I can live without this feature as my use case for the feature isn't really *that* important **but** I'm sure being able to get the process name under WSL will be found useful by others.

**Additional context**
I have looked at the documentation and issues and I can't seem to find anything similar, if I missed something please let me know.
I have no idea how possible this would actually be to implement since wezterm would somehow have to look into the WSL virtual machine to get the proc info from outside the VM ¯\\\_(〇_ｏ)_/¯ ?

**Comment by wez** [comment]
This is essentially impossible to achieve.

For an alternative approach that will work regardless of whether the programs are running in WSL, docker or a remote SSH, I recommend using shell-integration; it sets some user-vars that contain information about the running process.

https://wezfurlong.org/wezterm/shell-integration.html#user-vars has more information about those user vars in particular.

Further up on the page has details on the shell integration script itself; you can either install the wezterm package inside WSL to get those, or just manually install the file somewhere and source it for yourself (perhaps from your own dotfiles, if you don't want to install it system-wide).

**Comment by cultab** [comment]
I will try that, thank you! Closing the issue as I'm pretty sure I can get it to work using this!

**Comment by ghry5** [comment]
@cultab Did you figure out how to use user-vars to allow proper vim <=> wezterm pane navigation? If so do you mind sharing for anyone else?

I added the shell-integration script to my wezterm config folder and added: `source ~/.config/wezterm/wezterm-shell-integration.sh` to my `.zshrc`.  This lets me call `__wezterm_set_user_var nvim 1` to set my custom user variable from the command line. I can also  call `pane:get_user_vars()` from my wezterm config to get that user variable.

I am currently missing the following two things to complete it:
1. set my user variable on vim start (could be done with an autocmd)
2. reset the user variable on vim quit (again autocmd)

When trying to call the `__wezterm_set_user_var` function from within neovim using `:!__wezterm_set_user_var nvim 1` I only get a zsh command not found. After further investigation it seems like neovim is executing commands in a non interactive shell and the shell-integration is only enabled for interactive shells. 

From the wezterm.sh script:
```
if [[ $- != *i* ]] ; then
  # Shell integration is only useful in interactive sessions
  return 0
fi`
``
Any Ideas how i can set the user variable from within neovim/lua?

Help would be greatly appreciated.

**Comment by cultab** [comment]
@ghry5 Yes, just a few minutes ago, I found [numToStr/Navigator.nvim](https://github.com/numToStr/Navigator.nvim) which supports vim <=> tmux and recently vim <=> wezterm and just works. But in case you want to do it yourself the following to can be used to change wezterm panes from neovim.

```lua
io.popen("wezterm.exe cli activate-pane-direction" .. direction)
```
