### ISSUE TITLE
Document that Implicit urls require https in the format field to open in a browser

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#3140]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230219-070657-23211fc8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I've added a rule to match urls without https
```lua
  { regex =[[\b[\w.-]+\.[a-z]{2,15}\S*\b]]
   ,format='$0', }, -- same without https
```

And these get underlined in the terminal
However, when I click on it, I get an error
` Error opening www.wezfurlong.org: Launcher failed with ExitStatus(unix_wait_status(256))` for a ` www.wezfurlong.org` link

### To Reproduce

- Replace your config with the one below
- launch WezTerm
- print the link `echo "www.wezfurlong.org"`
- click on it
- observe the error

### Configuration

```lua
return {
  hyperlink_rules = {
  { regex =[[\b\w+://[\w.-]+\.[a-z]{2,15}\S*\b]]
   ,format='$0', }, -- || Linkify things that look like URLs and the host has a TLD name.
  { regex =[[\b[\w.-]+\.[a-z]{2,15}\S*\b]]
   ,format='$0', }, -- same ↑ without https
}
```

### Expected Behavior

A browser should be able to open a link without https/www

**Comment by eugenesvk** [comment]
Oh, just had an idea right after filing this to add `https` explicitly to the format, and it works! I'd still would expect https not to be necessary, but maybe it's much simpler, so it's not really a bug, but just a documentation issue

**Comment by wez** [comment]
Would you mind taking a look over:
* https://wezfurlong.org/wezterm/hyperlinks.html
* https://wezfurlong.org/wezterm/config/lua/config/hyperlink_rules.html
and suggesting where you think this could be made clearer?
Those docs have fairly recently been changed, so perhaps we can just close this now?

**Comment by eugenesvk** [comment]
filed my suggestion, I think the issue was that the requirement for a protocol type is not explicitly mentioned
Maybe if more people are confused this could be moved "higher" in the docs to https://wezfurlong.org/wezterm/hyperlinks.html, but for now added it to https://wezfurlong.org/wezterm/config/lua/config/hyperlink_rules.html
