### ISSUE TITLE
attempt to get an unknown field 'get_pane_direction'

### ISSUE THREAD

**Issue by distek** [wez/wezterm#3141]
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

```
> sway --version
sway version 1.8.1
```

### WezTerm version

wezterm 20230219-070657-23211fc8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hello!

Setting up some keybindings and ran in to this:
```
12:18:26.060  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 51, cols: 57 }) because window_state is MAXIMIZED
12:18:32.498  ERROR  wezterm_gui::termwindow         > while processing user-defined-4 event: runtime error: attempt to get an unknown field 'get_pane_direction'
stack traceback:
        [C]: in upvalue 'error'
        [string "__mlua_index"]:22: in metamethod 'index'
        /home/distek/.config/wezterm/keybindings.lua:82: in function </home/distek/.config/wezterm/keybindings.lua:81>
```

when trying to call the following:
```lua
	{
		key = "H",
		mods = "ALT|SHIFT",
		action = wezterm.action_callback(function(win, pane)
			wezterm.log_info(pane:get_pane_direction("Left"))
		end),
	},
```

Is there something I'm doing wrong here? I can clearly see that get_pane_direction is defined in wezterm's source, so I'm not sure what I'm missing.

I also tried with `win:get_pane_direction` just to be sure.

### To Reproduce

- Use the keybinding snippet above
- start a new window with `wezterm start --always-new-process`
- Press Alt+Shift+H

### Configuration

wezterm.lua:

```lua
return {
...
	keys = require("keybindings"),
...
}
```

keybindings.lua:

```lua
return {
	{
		key = "H",
		mods = "ALT|SHIFT",
		action = wezterm.action_callback(function(win, pane)
			wezterm.log_info(win:get_pane_direction("Left"))
		end),
	},
}
```

### Expected Behavior

log the pane info in whichever direction

### Logs

12:18:26.060  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 51, cols: 57 }) because window_state is MAXIMIZED
12:18:32.498  ERROR  wezterm_gui::termwindow         > while processing user-defined-4 event: runtime error: attempt to get an unknown field 'get_pane_direction'
stack traceback:
        [C]: in upvalue 'error'
        [string "__mlua_index"]:22: in metamethod 'index'
        /home/distek/.config/wezterm/keybindings.lua:82: in function </home/distek/.config/wezterm/keybindings.lua:81>

### Anything else?

I appreciate the work that's been put in to this. It has _very_ quickly became my favorite terminal emulator!

**Comment by distek** [comment]
GOT IT. Though I don't know if it's implemented correctly?
The documentation leads me to believe that this should be available in a `MuxPane` object:
https://wezfurlong.org/wezterm/config/lua/pane/get_pane_direction.html

But I had to get the `MuxTab` object first:
```lua
			local tab = pane:tab()
			wezterm.log_info(tab:get_pane_direction("Left"))
```

Is this correct/expected?

Also not to continuously praise, but my god those docs are incredible.

**Comment by wez** [comment]
Ah, yeah, the docs landed in the wrong spot, should get fixed by the next doc push!

**Comment by distek** [comment]
Awesome! Should I close this then?
