### ISSUE TITLE
Can you monitor the input of the terminal by programming and obtain the input string or command in real time

### ISSUE THREAD

**Issue by wangmings** [wez/wezterm#3150]
# WezTerm
> WezTerm is a very good modern terminal, with many APIs and strong customization.

## My problem
1. problem
Can you monitor the input of the terminal by programming and obtain the input string or command in real time

2. problem
Can you set the environment variable of the currently running terminal by writing in Lua

**Comment by wez** [comment]
No to both. The second one is not possible on any operating system: you cannot inject environment variables into a process that has already started.
