### ISSUE TITLE
Github Sponsorship

### ISSUE THREAD

**Issue by matthias-Q** [wez/wezterm#3155]
**Is your feature request related to a problem? Please describe.**

I currently sponsor this awesome project via Github. However, Github does not accept PayPal as payment method anymore. Are there other ways to sponsor you? Neovim for example uses opencollective.com.

**Comment by wez** [comment]
Thanks for letting me know!
opencollective seems to be very heavyweight for an individual.
I set up https://ko-fi.com/wezfurlong just now; it uses stripe and paypal under the covers, so perhaps that will work for you?
