### ISSUE TITLE
Fancy Tab Bar has padding even though window padding is 0

### ISSUE THREAD

**Issue by miversen33** [wez/wezterm#3158]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 with Gnome Shell

    gnome-shell v: 43.2 driver: X: loaded: modesetting

### WezTerm version

20230219-070657-23211fc8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Fancy Tab Bar
![image](https://user-images.githubusercontent.com/2640668/221382805-1179e388-104c-45e2-ac85-80e0cdbdc67e.png)

Interestingly, the issue does not exist if you don't use Fancy Tab Bar. Its possible I am doing something wrong, looking at the various screenshots I see on the github, no one else seems to have this padding so I assume I am doing something wrong (though I have no idea what, there doesn't appear to be an extra padding setting for the tab bar specifically)

### To Reproduce

Open wezterm with the below configuration

### Configuration

```lua
-- wezterm.lua
return {
    use_fancy_tab_bar = true,
    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0
    }
}
```

### Expected Behavior

I would expect there to be no padding above the tab bar

### Logs

```
16:42:13.972  WARN   mux::localpane > unknown DeviceControlMode::Enter EnterDeviceControlMode(params: [], intermediates: [], byte: 't' 0x74, ignored_extra_intermediates=false)
16:42:13.972  WARN   mux::localpane > unhandled DeviceControlMode::Data 6d m
16:42:13.972  WARN   mux::localpane > unhandled DeviceControlMode::Data 75 u
16:42:13.972  WARN   mux::localpane > unhandled DeviceControlMode::Data 78 x
16:42:13.972  WARN   mux::localpane > unhandled DeviceControlMode::Data 3b ;
```

**Comment by wez** [comment]
Please annotate the screenshot (and make it much narrower, so that it is easier to see) with the are that you are referring to, to make sure I understand your question/request.

**Comment by miversen33** [comment]
![image](https://user-images.githubusercontent.com/2640668/222315390-fd8809a6-bb49-4252-aa31-4530bd7aa1ee.png)

Best I can do lol. I would expect that setting `window_padding.top` to `0` would mean that there is no padding at the top of the fancy bar.

**Comment by wez** [comment]
The grey area? That's not window padding, that's part of the tab bar background. There are no configuration options that control that; there is always a thin strip above the tab, so that you can see that it is a tab.

You might wish to use the retro tab bar instead if you really don't want to see that.

**Comment by miversen33** [comment]
That grey area is what I was thinking was the "padding". So its more "margin" it sounds like. 

Glad that was cleared up :) It would be pretty cool if we _could_ configure that (setting, removing, changing color, etc). But that is well outside the scope of this "bug".

I appreciate you clarifying that for me :)
