### ISSUE TITLE
How to use cmd and option keys on macOS in neovim keybindings?

### ISSUE THREAD

**Issue by xbladesub** [wez/wezterm#3160]
I use Neovide and it allows to use CMD and Option keys (for option I have to set exact character which is printed when I use option with specific key). How can I use these modifier keys in wezterm+neovim on macOS?

**Comment by gegoune** [comment]
Isn't Neovide standalone desktop application that runs outside of terminal?

**Comment by xbladesub** [comment]
Yes, terminals are useless for me then)

**Comment by gegoune** [comment]
I need to apologise. I did not read your question entirely. :) how did you try to map those keys in Wezterm?
