### ISSUE TITLE
Incorrect cursor position after drawing image (iTerm inline image protocol)

### ISSUE THREAD

**Issue by o2sh** [wez/wezterm#317]
## Describe the bug

While adding [support for iTerm inline image protocol](https://github.com/o2sh/onefetch/pull/305) to [onefetch](https://github.com/o2sh/onefetch), we stumbled upon an inconsistent behavior between iTerm2 and WezTerm.

iTerm2:

![97804886-eefa0680-1c95-11eb-9bb3-b1c85a1c2e78](https://user-images.githubusercontent.com/13710835/97894130-7006db80-1d32-11eb-9461-b6784e996179.png)

WezTerm:

![97865633-db11db80-1d4d-11eb-8b08-c8434ac5b490](https://user-images.githubusercontent.com/13710835/97894166-7bf29d80-1d32-11eb-8656-b7331ae1d11d.png)

The cursor position after drawing the image is at the bottom left hand corner (WezTerm) instead of near the lower right corner (iTerm2).

Indeed - after drawing the image -, if we do this
```rust
image_data.extend(format!("\x1B[{}A", image_rows as u32).as_bytes()); // move cursor to top-left corner
image_data.extend(format!("\x1B[{}C", image_columns as u32 + 1).as_bytes()); // move cursor to top-right corner of image
```
instead of that
```rust
image_data.extend(format!("\x1B[{}A", image_rows as u32 - 1).as_bytes()); // move cursor to start of image`
```
We get the correct output:

![iterm](https://user-images.githubusercontent.com/13710835/97873552-172a4980-1d18-11eb-8a88-6846400cd7f2.png)

However, this obviously breaks the output on iTerm2...

## Environment (please complete the following information):

 - OS: macOS
 - Version: wezterm 20200909-002054-4c9af461

## Expected behavior

Consistent behavior with iTerm2 which is the de-facto standard.

**Comment by wez** [comment]
Thanks for reporting this!  I've pushed a fix that seems to make the onefetch sixel and iterm2 backend behavior consistent with each other within wezterm, and consistently with sixel in xterm.

That'll be available in the "nightly" downloads within about an hour.

**Comment by o2sh** [comment]
Well done!

![wez](https://user-images.githubusercontent.com/13710835/98006627-c76c8080-1df2-11eb-8a8c-cb0cf531d487.png)
