### ISSUE TITLE
Activate scroll mode on Mac

### ISSUE THREAD

**Issue by ckt114** [wez/wezterm#3170]
**Is your feature request related to a problem? Please describe.**
By default using Shift-PageUp or Shift-PageDown to activate scroll mode but there's no PageUp/Down on Mac laptop keyboard.

**Describe the solution you'd like**
Another way to activate scroll mode w/o using mouse.

**Describe alternatives you've considered**
I tried the below key mappings but it doesn't work.
```
{ key = 'u', mods = 'CTRL', action = action.ScrollByPage(-1)
{ key = 'd', mods = 'CTRL', action = action.ScrollByPage(1) }
```

**Additional context**
N/A

**Comment by ckt114** [comment]
Actually it does work with the key bindings above if not inside a tmux sessions. Is there a way to send the keys into tmux session? I use tmux 100% of the time. Thanks.

**Comment by piechologist** [comment]
> but there's no PageUp/Down on Mac laptop keyboard.

Of course there is: fn-cursor keys for Home, PageUp/Down, End.

**Comment by wez** [comment]
I use FN-SHIFT-UP and FN-SHIFT-DOWN all the time for scrolling without the mouse on my mac

**Comment by ckt114** [comment]
@wez I have the following keys in my wezterm.lua and I can scroll up/down with Ctrl+u/d but it doesn't work inside of tmux. Do you know why? I have other key mappings and it work fine inside of tmux.

**Comment by wez** [comment]
`action.ScrollByPage(-1)` scrolls wezterm's scrollback.
tmux runs in the alternate screen which has no scrollback, so there's nothing for wezterm to scroll.
tmux emulates scrollback for itself, which is why you typically need to do something like this to scroll tmux:
https://superuser.com/questions/209437/how-do-i-scroll-in-tmux
