### ISSUE TITLE
`CSI 0 A` moves the cursor up one time

### ISSUE THREAD

**Issue by AnonymouX47** [wez/wezterm#3174]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin (KDE Window Manager)

### WezTerm version

20230206-204612-f6d8b309

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`CSI 0 A` (Cursor up **zero** times) moves the cursor up **one** time.

### To Reproduce

Type

```sh
echo -e "\e[0A##"
```
in a shell and hit `Enter`.

"##" appears at the beginning of the same line as the command.

### Configuration

"no config"

### Expected Behavior

`CSI 0 A` should move the cursor up **zero** times.

EDIT: Corrected `OCS` -> `CSI`

**Comment by wez** [comment]
The example you pasted isn't using CSI.  Do you mean `echo -e "\e[0A##"`; the `CUU` sequence?

wezterm behaves consistently with iterm2 and terminal.app on my mac (the machine I'm using at the moment).
Note that `0` is generally treated as "the default value" in CSI sequences and the default value for the `CUU` sequence is 1.

**Comment by AnonymouX47** [comment]
> The example you pasted isn't using CSI. Do you mean echo -e "\e[0A##"; the CUU sequence?

Yes, `\e[0A##`. Sorry about that.

> wezterm behaves consistently with iterm2 and terminal.app on my mac (the machine I'm using at the moment).
> Note that `0` is generally treated as "the default value" in CSI sequences and the default value for the `CUU` sequence is 1.

I see. I'll omit the sequence in such cases then.

Thanks.
