### ISSUE TITLE
Support parsing tokens in SSH config

### ISSUE THREAD

**Issue by alteriks** [wez/wezterm#3176]
**Is your feature request related to a problem? Please describe.**
Hi, I'm using ssh tokens in user config file, notably '%u' and '%L'.
I have few entries like `IdentityFile ~/.ssh/%u@%L_id_ed25519` which allow me to use one `.ssh/config` file for all hosts I manage and keep it in git repo. All identities I use are evaluated by ssh to:
```
alteriks@moar_id_ed25519.pub
alteriks@hal_id_ed25519.pub
alteriks@nebula_id_ed25519.pub
```
etc.

**Describe the solution you'd like**
1. Please fail in a graceful matter when parsing `.ssh/config` file.
For me as new wezterm user this error, doesn't say a lot
![image](https://user-images.githubusercontent.com/6512767/222131947-b8e51099-2743-4dd3-8eda-f86d9495e494.png)
 
2. Or ignore parsing `.ssh/config` options which wezterm doesn't support and warn user. A for now even overriding ssh option in wezterm config doesn't work.
```lua
  ssh_domains = {
    {
      name = 'hal',
      remote_address = 'hal',
      username = 'alteriks',
      ssh_option = {
        identityfile = '~/.ssh/alteriks@moar_id_ed25519',
      },
    },
  },
```
3. Add support for all [ssh tokens](https://man7.org/linux/man-pages/man5/ssh_config.5.html#TOKENS)
4. Option to disable parsing `.ssh/config` entirely

**Describe alternatives you've considered**
For me not using tokens is a no go. It simplifies my .ssh/config and allows me to manage only one file for all hosts
Similar request has already been fixed: https://github.com/wez/wezterm/issues/2448

**Comment by wez** [comment]
I've added the missing `%l` and `%L` tokens. There are several tokens that are potentially possible but that are not currently supported. Most tokens are not even supported by libssh, and the semantics of parsing and evaluating the config are a little bit different when not running in the `ssh` binary itself, so not all possible tokens are supportable.

I have added a warning when a token is used that isn't supported to make this a bit more discoverable.

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by alteriks** [comment]
Hi Wez, sorry for delay. I've just build wezterm from source and problem persists.
![image](https://user-images.githubusercontent.com/6512767/223653490-a90419f7-8c4d-4bce-9282-469300168917.png)
I tried something different - I've replaced `.ssh/config`
```
 IdentityFile ~/.ssh/%u@%L_id_ed25519
```
with:
```
 IdentityFile ~/.ssh/%u@%l_id_ed25519
```
And wezterm connected just fine.
Also I've tried this with `wezterm 20221119-145034-49b9839f` and it also parsed lowercase `%l` just fine.
In another test I've tried using imaginary token `%z`
![image](https://user-images.githubusercontent.com/6512767/223666732-e41cf33a-1b2a-4bc4-9df8-753285b534df.png)
And didn't see new warning - `log::warn!("Unsupported token {t} when evaluating `{orig_value}`");`
Maybe problem lies within `LibSsh` library?

**Comment by wez** [comment]
> In another test I've tried using imaginary token `%z`
> And didn't see new warning - `log::warn!("Unsupported token {t} when evaluating `{orig_value}`");`

The warning is only shown for tokens that are valid for a given option. Try it with `%C` and you'll see it.

> I've just build wezterm from source and problem persists.

I've pushed a commit that will include the computed config when you `wezterm ssh -v hal`, or when you add 'wezterm_ssh_verbose = "true"` to your ssh_option map and use `wezterm connect hal`.  That should let you see what is actually being used for the identityfile.

**Comment by alteriks** [comment]
> The warning is only shown for tokens that are valid for a given option. Try it with %C and you'll see it.

ok, I can verify that part works

As for my main issue:
![image](https://user-images.githubusercontent.com/6512767/223798920-62fb01dd-cb46-4209-b4ec-007e4b885bd2.png)

**Comment by alteriks** [comment]
I've checked libssh code and they only support %l

https://git.libssh.org/projects/libssh.git/tree/src/misc.c#n1212
