### ISSUE TITLE
Can't type the '@' character, 'ls' is executed instead.

### ISSUE THREAD

**Issue by apiening** [wez/wezterm#3178]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230226-223328-0ac1cbc4

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I type the `@` symbol (by typing `opt` + `l` on my german keyboard) it seems like the command `ls` is executed. I have not configured any keyboard mappings in `wezerm.lua`, is there some default mapping in place?

### To Reproduce

On a mac with german keyboard layout, type `opt` + `l`: 

### Configuration

no config

### Expected Behavior

I expect the `@` to appear, instead I get some `ls` output.

**Comment by wez** [comment]
Are you using the left or right option key?
Can you try enabling https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html and report what gets logged when you press that key combination?

**Comment by wez** [comment]
See also: https://wezfurlong.org/wezterm/config/keyboard-concepts.html#macos-left-and-right-option-key

**Comment by apiening** [comment]
Thank's a lot @wez!
The right option key + `l` does in fact show the `@` symbol. I haven't even tried this before because I mostly rely on using the left option key.

Since it is deeply integrated with my muscle memory, I added the option
```lua
return {
  send_composed_key_when_left_alt_is_pressed = true
}
```

to my config file, and now it works the way I prefer it.

Thanks again!
