### ISSUE TITLE
Modifying PATH env var on Windows

### ISSUE THREAD

**Issue by adriancostin6** [wez/wezterm#3182]
Hello, I was messing around with setting environment variables in the lua configuration today. I managed to add most of my env vars, but got stuck at appending some of them to PATH. I tried concatenating the table elements with a function and returning them in a PATH element inside the table, but that did not seem to work. Any tips? Can't find this in the docs 😄

**Comment by wez** [comment]
Please share what you tried, what you expected and what happened. There's not much to go on here.

**Comment by adriancostin6** [comment]
Sorry for the bad manners 🥇 Was in a rush yesterday. 

What I've tried (.wezterm.lua):

```
local wezterm = require'wezterm'
return {
    color_scheme = 'Catppuccin Mocha',
    font = wezterm.font('Iosevka NF', {weight = 'Light',}),
      window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
      },
    set_environment_variables = {
        EDITOR='nvim',

        PATH_A = 'C:/some/pathA',
        PATH_B = 'C:/some/pathB',
        PATH_C = 'C:/some/pathC',
        PATH_D = 'C:/some/pathD',

        PATH = function (self)
           return self.PATH_A .. self.PATH_B .. self.PATH_C .. self.PATH_D .. '%PATH' 
        end
    },
}
```
What I expected: Windows PATH environment variable to be modified.

What I got: 

> Error converting lua value returned by script C:\Users\adrianc\.wezterm.lua
> to Config struct: error converting Lua table to Config (error converting Lua
> table to value (while processing "set_environment_variables": error converting
> Lua function to value (while processing "PATH": error converting Lua function
> to wezterm_dynamic::Value)))
> 

I usually do this in a batch script call, when the terminal is started, this is the only way I figured with Windows Terminal, so when I saw your 'wezterm', configurable in Lua, my eyes lit up 😮 .
