### ISSUE TITLE
startup spawn tabs

### ISSUE THREAD

**Issue by pwsandoval** [wez/wezterm#3183]
Based on this [#674](https://github.com/wez/wezterm/issues/674)

In the same way, is there a way so that when starting there will be 2 tabs, each one with a different shell?

Something like mux.spawn_tab.

**Comment by wez** [comment]
Look at the examples on https://wezfurlong.org/wezterm/config/lua/gui-events/gui-startup.html

**Comment by pwsandoval** [comment]
> Look at the examples on https://wezfurlong.org/wezterm/config/lua/gui-events/gui-startup.html

Is that to launch multiple panels or windows, or am I missing something?

**Comment by wez** [comment]
You can use https://wezfurlong.org/wezterm/config/lua/mux-window/spawn_tab.html from that startup event.
