### ISSUE TITLE
Get_foreground_process_name always prints the previous process the 1st time

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#3186]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230301-184411-2d05f8f1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Trying to get the currently active process with `pane:get_foreground_process_name` after entering/exiting a terminal editor only works correctly on every SECOND+ attempt, the first attempt always prints the previous process (shell in an editor, editor in a shell)

### To Reproduce

- Replace your config with the one below
- launch wezterm from another terminal
- launch vim
- press <kbd>⇧</kbd><kbd>1</kbd>
- observe in the other terminal that your shell's full path is printed, not vim's
- press <kbd>⇧</kbd><kbd>1</kbd>
- observe in the other terminal that now vim's path is printed
- exit vim
- press <kbd>⇧</kbd><kbd>1</kbd>
- observe in the other terminal that your vim's path is printed, not shell's
- press <kbd>⇧</kbd><kbd>1</kbd>
- observe in the other terminal that now shell's path is printed

### Configuration

```lua
local wezterm	= require("wezterm")

return {
  keys = {
    {key="phys:1", mods="SHIFT", action=wezterm.action_callback(function(win,pane)
      wezterm.log_info('   1 proc ='..pane:get_foreground_process_name())
    end)},
  },
}
```

### Expected Behavior

Currently active process should always get printed

### Anything else?

Maybe I'm missing something simple about how his works, but didn't get it from reading callback/get_foreground_process_name docs and their limitations

**Comment by wez** [comment]
The value is cached because the function may be called very many times in quick succession when the mouse moves across the tabs, and it is an expensive OS call to retrieve system information. Because the OS doesn't provide a means to notify when the cache is invalidated, and we cannot afford the delay of querying the system for OS information while processing GUI events, we return a stale value an arrange to update it in the background.

I generally recommend using shell integration and user vars to cooperatively communicate information about the running process; https://wezfurlong.org/wezterm/shell-integration.html#user-vars lists some default vars that are set by recent versions of the shell integration.  user-vars don't need to be polled and will also work across eg: ssh connections.

**Comment by eugenesvk** [comment]
Oh, I'd love to use user vars! But that level of support for communication is even further away from being a reality for my purposes of term-editor integration

But that aside, in the this case that wouldn't help as no other process is involved to set any user vars. I've added a "wrapper" function for some pane/tab navigation commands to detect the process in the target pane and (change keybinds if it's an editor and change them back if it's not), so WezTerm is the only app that is aware of that activity!

The only alternative to the constantly-checking-process option I've come up with is being able to tie keybinds to a pane https://github.com/wez/wezterm/issues/1417#issuecomment-1001417261, then you at most need a proc check on launch/exit (or if the editor supported user vars, on exit it could tell WezTerm to "untie" the keybinds), but otherwise keybinds would automatically change on pane changes without any proc checks, but that was closed a while ago

The `[many continuous] moves across the tabs` performance issue is real here as well, but given that all the calls originate explicitly from the keybinds I change in my configs (as opposed to the mouse scroll integrations), I think this issue could instead be fixed by adding some global "debouncing" delay, so that when I hold my tab switching key and switch from tab1 to tab101, the proc check will only fire after 0.1 secs has passed since the last function call at tab100

So is there a way to manually signal to WezTerm to get non-cached value and knowingly suffer/deal with the performance penalty?

**Comment by wez** [comment]
33f25e9ce62d52c612c4e63cff21a64d6824cddd has context on the caching and the painful aggregate performance costs.
We simply cannot afford to query it immediately when the value is stale.

**Comment by eugenesvk** [comment]
But we wouldn't query it immediately, the lua config would wait until some time has passed since that last call to the function that needs to query the process and only ask wezterm for the process name once per all the tab changes (unlike the mouse hover that don't call any lua config functions and thus require wezterm code to deal with it)
Would this not be possible in lua (I mean, if the alternative "more expensive" call were available in wezterm)?

**Comment by wez** [comment]
The pane doesn't know whether it is being called by the gui or not, and that concept is several layers of abstraction removed from it, so no, it just doesn't work that way.

**Comment by eugenesvk** [comment]
> The pane doesn't know whether it is being called by the gui or not, and that concept is several layers of abstraction removed from it, so no, it just doesn't work that way.

Sorry, not sure what this is responding to
(if it's about some keytables being tied to a pane, than that info stays with the gui, not the pane, so the pane wouldn't need to know)

**Comment by eugenesvk** [comment]
So I've found a way to not run `pane:get_foreground_process_name` on every single callback function execution, but only after the last one (within a given period) in lua by using some timer lib 
- to delete old/create new timer on every callback function execution
- run `timer.update` (to clean the deleted/call the last expired timer) on every wezterm's call to `update-status` (which is ~1/sec, not terribly precise, but not very slow either)

So now there wouldn't be any performance hit in asking for the up-to-date value even if I hold my tab-switch button to switch through many tabs

**Comment by wez** [comment]
I believe that this was resolved by aa81a46d58205c5d1006590597ea4a5bb92d825a which is part of the latest stable release

**Comment by eugenesvk** [comment]
Thanks for the fix, the issue seems to be gone!

Though the commit states that it allows "specifying cache policy for process information", but I didn't see a way to toggle that policy in the https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html

**Comment by wez** [comment]
I didn't expose the policy all the way up to lua yet; was waiting to see if it was necessary. The process name is always fetched immediate when using pane:get_foreground_process_name, so I don't expect staleness to be an issue for that one
