### ISSUE TITLE
Startup position no working

### ISSUE THREAD

**Issue by pwsandoval** [wez/wezterm#3187]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm trying to set the initial position and size of the window, but for some reason it doesn't work.

The size seems to vary every time I open the terminal and the starting position is also different.

### To Reproduce

Use this min config.

### Configuration

I tried multiple configs, based on [256](https://github.com/wez/wezterm/issues/256), [2976](https://github.com/wez/wezterm/issues/2976) and [spawn window docs](https://wezfurlong.org/wezterm/config/lua/wezterm.mux/spawn_window.html#position)

```lua
wezterm.on("gui-startup", function(cmd)
   local tab, pane, window = wezterm.mux.spawn_window(cmd or {
      position = { x = 100, y = 100, },
   })
end)
```

```lua
wezterm.on("gui-startup", function(cmd)
   local tab, pane, window = wezterm.mux.spawn_window(cmd or {})
   window:gui_window():set_position(100, 100)
   window:gui_window():set_inner_size(1000, 750)
end)
```

Both config give me the same result, the window is located in any position every time I open it, the size seems to be fixed, but not the one I set.

These properties seem to work for width and height (but it's less flexible, I can't put value relative to 50%)
And I can't find another option like that for the starting position.

```lua
initial_rows = 35,
initial_cols = 110,
```

### Expected Behavior

Determine the initial position and size of the window using the properties in the gui-startup callback

**Comment by wez** [comment]
Please try the nightly build

**Comment by cd-a** [comment]
Works great for me. Thanks wez
