### ISSUE TITLE
Window frame changing to defaults in certain situations

### ISSUE THREAD

**Issue by elmehalawi** [wez/wezterm#3188]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm setting the window frame manually depending on whether the computer is in light mode or dark mode. It works but sometimes it reverts back to the default window frame. Here's a video showing wezterm reverting to the default window frame when I open spotlight repeatedly (using cmd+space):

https://user-images.githubusercontent.com/2058016/222774180-a15bad1a-52f8-43be-a5ab-330e742beb21.mov

Interestingly, when I switch tabs again, it sets the window frame to the white background (which is what it should be).

### To Reproduce

If you set the window frame as I have in the lua snippet below, open wezterm fresh, then open spotlight, it should reproduce the problem. 

### Configuration

```lua
local light_mode_window_frame = {
  active_titlebar_bg = 'white',
  font = wezterm.font {family = "Iosevka", weight = 'Bold'},
}

local dark_mode_window_frame = {
  active_titlebar_bg = 'rgb(26, 27, 38)',
  font = wezterm.font {family = "Iosevka", weight = 'Bold'},
}

function window_frame_for_appearance(appearance)
  if appearance:find('Dark') then
    return dark_mode_window_frame
  else
    return light_mode_window_frame
  end
end

wezterm.on('window-config-reloaded',
  function(window, pane)
    local overrides = window:get_config_overrides() or {}
    -- ...
    local window_frame = window_frame_for_appearance(appearance)
    if overrides.window_frame ~= window_frame then
      overrides.window_frame = window_frame
      window:set_config_overrides(overrides)
    end
  end
)
```

### Expected Behavior

The window frame should stay as the one set.

### Anything else?

This also happens in some other situations. For example, I use this tiling window manager called amethyst, and when I resize the window using amethyst, it also reverts the window frame to the default. And again, if I change tabs in wezterm, it sets it to the value set in the lua config.

**Comment by wez** [comment]
I couldn't reproduce this with the (incomplete!) config shared above.
I suspect that some other software on your system is influencing this, as wezterm doesn't actively change the appearance of the titlebar, it only reports it, or, if you are using `window_decorations`, removes it.
