### ISSUE TITLE
zooming/changing font size doesn't resize client (tmux)

### ISSUE THREAD

**Issue by crides** [wez/wezterm#3192]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Awesomewm

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

using the default keymap, `ctrl =` and `ctrl -` scales the font, but not the size of the terminal window, with the size of the actual window fixed (e.g. fullscreen)

### To Reproduce

1. start wezterm
2. launch tmux
3. resize (`ctrl -` or `ctrl =`)

### Configuration

no config

**Comment by wez** [comment]
You want to set https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html to false when using a tiling window manager
