### ISSUE TITLE
Incorrect display after clearing screen

### ISSUE THREAD

**Issue by vuanvin** [wez/wezterm#3198]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

WezTerm would drop some lines after clearing screens (pressing CTRL + L). The error display appeared on both PowerShell and zsh (WSL2).

### To Reproduce

just press `ls` and `CTRL + L` and then scroll back the screen with mouse.

### Configuration

both config and no config (command `wezterm -n`)

### Expected Behavior

The entire text should be displayed when we scroll back screens after cleaning screens by pressing CTRL+L.

**Comment by wez** [comment]
Please describe exactly what you are seeing, and exactly you expect to see

**Comment by bew** [comment]
> The entire text should be displayed when we scroll back screens after cleaning screens by pressing CTRL+L.

This makes me think you want ctrl+l to clear the screen while keeping all previous output. If I'm right, look at #2405 it should explain things.

**Comment by vuanvin** [comment]
> This makes me think you want ctrl+l to clear the screen while keeping all previous output. If I'm right, look at https://github.com/wez/wezterm/issues/2405 it should explain things.

I think this has sovled my confusion. Thank you for your reply.
