### ISSUE TITLE
Make Wezterm run on non-GPU capable hardware/software

### ISSUE THREAD

**Issue by elkarouh** [wez/wezterm#3199]
At work, i use Wezterm.
But when remote working, i make use of a vncviewer to access a vnc server.
When i run wezterm, i get
15:42:44.777  ERROR  wezterm_gui::frontend > Failed to create window: with_egl_lib failed: with_egl_lib(libEGL.so.1) failed: EGL CreateContext: BAD_MATCH 0x55555977fa10
EGL CreateContext: BAD_MATCH 0x555559781760
EGL CreateContext: BAD_MATCH 0x55555977fae0
....

This is not Wezterm's fault but it would be convenient to have a startup option to circumvent such issues.
Many thanks for the great work!

**Comment by wez** [comment]
Take a look at:
* https://wezfurlong.org/wezterm/config/lua/config/front_end.html

**Comment by elkarouh** [comment]
Hi,

I now get the following error at startup

`ERROR  wezterm_gui::frontend > Failed to create window: with_egl_lib failed: with_egl_lib(libEGL.so.1) failed: EGL CreateContext: BAD_MATCH 0x55555977fcf0
EGL CreateContext: BAD_MATCH 0x555559781a40
EGL CreateContext: BAD_MATCH 0x55555977fdc0`

**Comment by wez** [comment]
I'm closing this *enhancement* request because this is already supported. It sounds like you are having a different kind of issue where it would be more suitable to open a bug report issue using the bug report template. If you'd like to follow up, please do that!
