### ISSUE TITLE
Cedilla (ç) not rendering

### ISSUE THREAD

**Issue by andradei** [wez/wezterm#3201]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 with Gnome 43

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I have changed my system to use cedilla (ç) with <kbd>'</kbd>, <kbd>c</kbd> and all applications work except for wezterm.

But that didn't do the trick. It keeps printing `ć` instead of `ç`.

### To Reproduce

1. Change the Keyboard layout to `English US (alt. intl.)`
2. I've added the following to `/ect/environments` 
```
GTK_IM_MODULE=cedilla
QT_IM_MODULE=cedilla
```
3. And create this on my `~/.XCompose`
```
# UTF-8 (Unicode) compose sequences

include "%L"

# Override ć with ç:
<dead_acute> <c> : "ç" "ccedilla"
<dead_acute> <C> : "Ç" "Ccedilla"

# Support cedilla in applications that don't respect GTK or QT, like Alacritty and WezTerm
# (for lack of better explanation)
# See https://github.com/alacritty/alacritty/issues/4549
<Multi_key> <comma> <c> : "ç"
<Multi_key> <comma> <C> : "Ç"
<Multi_key> <cedilla> <c> : "ç"
<dead_cedilla> <c> : "ç"

<Multi_key> <c> <comma> : "ç"
<Multi_key> <cedilla> <c> : "ç"
<Multi_key> <acute> <c> : "ç"
<Multi_key> <apostrophe> <c> : "ç"
<Multi_key> <c> <apostrophe> : "ç"

 # Now run
 # `gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule': <'ibus'>}"`
 # and reboot
```
4. Run `gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule': <'ibus'>}"`
5. Reboot the system

### Configuration

Vanilla. No config at all.

### Expected Behavior

Do the same as other applications in the system, rendering `ç` instead of `ć` .

**Comment by wez** [comment]
wezterm is neither a GTK nor a QT application, so settings specific to those do not apply.
IME support is via the XIM protocol.

For ibus, you usually want to set `XMODIFIERS=@im=ibus`.

Do other XIM-based applications work with that IME configuration?

**Comment by andradei** [comment]
I added `export XMODIFIERS=@im=ibus` to my `.zshrc` and rebooted but no luck.

**Comment by andradei** [comment]
@wez Thank you, upon reading [the documentation](https://wezfurlong.org/wezterm/config/lua/config/use_ime.html), I realized I had to install `ibus` before XIM could do anything.

I'm my case I installed with `yay ibus`.
