### ISSUE TITLE
`win:perform_action` is not working in CopyMode

### ISSUE THREAD

**Issue by misumisumi** [wez/wezterm#3209]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

gnome

### WezTerm version

20230305-221833-55982436

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The following settings, which are expected to work as in `{ key = "Escape", mods = "NONE", action = act.CopyMode("Close") },`, cannot be used.
Other CopyMode actions other than Esc cannot be called in callback.
```
        copy_mode = {
            {
                key = "Escape",
                mods = "NONE",
                action = wezterm.action_callback(function(win, pane)
                    wezterm.log_info("escape")
                    win:perform_action(act.CopyMode("Close"), pane)
                end),
            },
```

### To Reproduce

1. Set `Configuration` to `wezterm.lua`.
2. Enter `CopyMode`.
3. Press "esc".

### Configuration

```lua
local wezterm = require 'wezterm'
local act = wezterm.action

local copy_mode = nil
if wezterm.gui then
  copy_mode = wezterm.gui.default_key_tables().copy_mode
  table.insert(
    copy_mode,
    { key = 'Backspace', mods = 'NONE', action = act.CopyMode 'MoveLeft' }
  )
end

return {
  key_tables = {
    copy_mode = copy_mode,
  },
}
```

### Expected Behavior

show `escape` to console and exit "CopyMode".

### Logs

21:06:05.355  INFO   logging > lua: escape

**Comment by wez** [comment]
The reason this doesn't work as expected is because copy mode is a special pane that is managed by the GUI, but the `win:perform_action` method only tries to resolve it via the mux.

Try this as an alternative:

```lua
  table.insert(
    copy_mode,
  {
    key = "Escape",
    mods = "NONE",
    action = act.Multiple {
      wezterm.action_callback(function(win, pane)
        wezterm.log_info("escape")
      end),
      act.CopyMode("Close")
    },
  })
```

Let's keep this issue open until this is resolved.

**Comment by Sumi-Sumi** [comment]
Thank you!
I'm closing this issue because it worked on `act.Multiple`.

**Comment by wez** [comment]
Keeping open until I fix the underlying issue

**Comment by Sumi-Sumi** [comment]
sorry.
I understand.
