### ISSUE TITLE
Activate `MuxTab` and `Pane` objects directly

### ISSUE THREAD

**Issue by musjj** [wez/wezterm#3217]
**Is your feature request related to a problem? Please describe.**
The only way to activate tabs and panes is through the `wezterm.action.ActivateTab` and `wezterm.action.ActivatePaneByIndex` functions. But these functions accept only indexes not ids. 

So if you have a `MuxTab` or `Pane` objects, you have no way of activating it directly, because they only provide id information.

Though for whatever reason, ids and indexes are basically the same for tabs (at least in my experience), but this isn't true for panes.

**Describe the solution you'd like**
A way to activate these objects directly. Something like `Pane:activate()` or `MuxTab:activate()`.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
