### ISSUE TITLE
move-pane-to-new-tab moving to a different window does not take effect until re-attaching to domain

### ISSUE THREAD

**Issue by mitchcapper** [wez/wezterm#3219]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

0230306-150040-c3286f1b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using `move-pane-to-new-tab`  to move a tab to a new or existing window has no effect until you re-attach to the domain.  You can see in the `cli list` command the window id is updated but it doesn't result in any changes until disconnect and re-attach.
ie:
`wezterm cli move-pane-to-new-tab --new-window --pane-id 1`
pane 1 stays in place.  Disconnect and reconnect and pane moves.

### Configuration

no config also reproduces

### Expected Behavior

the tab moves to the window when cli is run.

### Logs

nothing shows in debug pane or log file (other than domain connect/dc manually done)

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by junkblocker** [comment]
Is there a corresponding lua API? I want to bind tmux/screen like `Ctrl+a !` to detach the current pane to a new tab.

**Comment by wez** [comment]
Not at the moment, but you can use https://wezfurlong.org/wezterm/config/lua/wezterm/run_child_process.html:

```lua
wezterm.run_child_process { 'wezterm', 'cli', 'move-pane-to-new-tab', '--pane-id', tostring(pane:pane_id())}
```

**Comment by junkblocker** [comment]
Thanks, that works. However I am seeing issues with weird behavior if I randomly create splits detach using this - sometimes splits don't get created at all or tabs get created instead and tab navigation by number doesn't work correctly jumping to the wrong tab number.

**Comment by wez** [comment]
@junkblocker please don't hijack this essentially closed issue with a different issue, file a separate issue.

**Comment by junkblocker** [comment]
https://github.com/wez/wezterm/issues/3374
