### ISSUE TITLE
[Wayland + NVIDIA + WGPU]  Error in Surface::configure: parent device is lost

### ISSUE THREAD

**Issue by uncomfyhalomacro** [wez/wezterm#3225]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

WM: Wayland compositor RiverWM (Wlroots-based like SwayWM)
OS: openSUSE TumbleWeed

Also tested on Plasma Wayland. Same issue.

### WezTerm version

20221119.145034.49b9839f+g221

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below.

**No relevant commit that can fix it**

### Describe the bug

Crashes on Wayland. No Wezterm running.

### To Reproduce

1. Open a Wayland session -> In my instance, riverwm.
2. Segfaults

### Configuration

no config

### Expected Behavior

Runs normally.

### Logs

```
23:18:27.081  ERROR  wezterm_gui > running message loop: error during event_q.read_events protocol_error=Some(ProtocolError { code: 7, object_id: 0, object_interface: "<unknown>", message: "" }): Protocol error (os error 71); terminating
```

### Anything else?

Going to test this on Plasma Wayland. I will update later

**Comment by uncomfyhalomacro** [comment]
Updated. It crashes as well. It seems to have a problem with latest Wayland. Not just the wlroots implementation.

**Comment by uncomfyhalomacro** [comment]
Tried latest git master. Same issue.

**Comment by smokeythemonkey** [comment]
Happens for me on Pop os / Gnome with wayland enabled

**Comment by pdanpdan** [comment]
Set the `__EGL_VENDOR_LIBRARY_FILENAMES` env variable to `/usr/share/glvnd/egl_vendor.d/50_mesa.json` (at least for PopOS)

**Comment by uncomfyhalomacro** [comment]
> /usr/share/glvnd/egl_vendor.d/50_mesa.json

That works. This might mean this is an NVIDIA Wayland issue?

**Comment by wez** [comment]
I'd suggest trying webgpu to see if that behaves any better:
https://wezfurlong.org/wezterm/config/lua/config/front_end.html#webgpu

**Comment by carschandler** [comment]
> I'd suggest trying webgpu to see if that behaves any better:
> 
> https://wezfurlong.org/wezterm/config/lua/config/front_end.html#webgpu

Hi wez. We discovered that my issue #3244 is a duplicate of this and I've tried running with `WebGpu` on which allowed it to boot up but with extremely degraded performance and weird graphics errors. I've got some additional info over on that post.

**Comment by almereyda** [comment]
This is also being seen with the Flatpak on Ubuntu 23.04 in OpenGL mode. A window can still open, but doesn't hold for long, e.g. until a few keys are pressed. Opening a second instance instantly kills both.

Enabling WebGpu throws the error immediately here:

```
$ flatpak run org.wezfurlong.wezterm 
[destroyed object]: error 2: Buffer size (12x613) must be an integer multiple of the buffer_scale (2).
01:30:24.924  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=Some(ProtocolError { code: 2, object_id: 0, object_interface: "<unknown>", message: "" }): Protocol error (os error 71); terminating
$
```

**Comment by uncomfyhalomacro** [comment]
@wez I found out that this is not a wezterm issue, but a crate issue `wgpu`, Wayland library issue, specifically, wlroots and also NVIDIA issue.

It's an old issue as mentioned here https://github.com/gfx-rs/wgpu/issues/2519

I will keep this open until that side gets resolved.

**Comment by ymatsiuk** [comment]
Setting 👇🏻 
```
~ ❯ grep wezterm ~/.config/sway/config
bindsym Mod4+Return exec wezterm start --always-new-process
exec wezterm start --always-new-process
```
fixes this error for me (sway, intel tgl gt2, scaling factor 2) and wezterm is no longer crashing, although I still see bunch of warnings in the log

**Comment by uncomfyhalomacro** [comment]
Fixed on latest wezterm. Only issue now is to report for performance
