### ISSUE TITLE
wezterm terminfo duplicated/repeated leters

### ISSUE THREAD

**Issue by sandikata** [wez/wezterm#3228]
term = "wezterm", setting in wezterm.lua leads to repeating leters

tipped "ls" but on screen is visible something else

lsls               UU

with term = "xterm256color" it behaves as expected, no repeated symbols and leters

[wezterm-recording-SZ0AFD.cast.txt](https://github.com/wez/wezterm/files/10944032/wezterm-recording-SZ0AFD.cast.txt)

**Comment by wez** [comment]
There's not enough information in this report.  Note that changing the `term` value has no effect on the behavior of wezterm; it's just a key to a terminfo database used by other programs.
https://wezfurlong.org/wezterm/what-is-a-terminal.html#terminfo-and-termcap has more information about that.

I'm going to close this, but I encourage you to file a more detailed issue using the [Bug Report Form](https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml). Please include as much information as possible that might help to understand how to replicate the issue.
