### ISSUE TITLE
Add lua event(s) for mouse clicks on the new tab `+` button

### ISSUE THREAD

**Issue by alexherbo2** [wez/wezterm#323]

**Comment by wez** [comment]
Can you tell me a bit more about the use case for this?
In the gitter/matrix thread I think you said that you wanted to use the clipboard as the command to be executed, but here this sounds like you just want to show a tab with the clipboard contents.

If this is about running a command and putting that in a tab then the way I'm looking at this right now is similar to this example:

https://wezfurlong.org/wezterm/config/lua/wezterm/on.html#custom-events

So we could expose an event that allows processing mouse button events on the `+` button  and allow you to take the clipboard contents and then trigger a `SpawnCommandInNewTab` action.

**Comment by alexherbo2** [comment]
Yep it is to execute commands from the primary register.

For example, at https://github.com/mawww/kakoune#tldr, select the commands and middle-click on the `+` to install and run [Kakoune] in a new tab.

[Kakoune]: https://kakoune.org

**Comment by bew** [comment]
This sounds like dangerous, as you don't see the command you're executing before it's running..
Try copying `rm -rf ~` and open a new tab, you'll try to make sure you click the right button..

**Comment by wez** [comment]
Yeah; the danger of this is why I won't make it a first-class built-in, but exposing an event hook for someone to script it for themselves seems generally useful.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by bew** [comment]
Looking at the commiti, from a functionality point of view, why is the `default_action` optional?

**Comment by wez** [comment]
The hook allows you to define a middle button action, but wezterm doesn't define an action for the middle button -> we need a way to indicate that we would not take one.
