### ISSUE TITLE
SplitPane documentation incorrectly references "Top" and "Bottom"

### ISSUE THREAD

**Issue by jamesredwards** [wez/wezterm#3231]
Love Wezterm - thank you. While building out my config I was struggling to get SplitPane to work above or below.

[wezterm/docs/config/lua/keyassignment/SplitPane.md](https://github.com/wez/wezterm/blob/77b6870ff397d8a4fed7399e25b5fc3f80ebfd6d/docs/config/lua/keyassignment/SplitPane.md)

conflicts with

[wezterm/docs/config/lua/pane/split.md](https://github.com/wez/wezterm/blob/main/docs/config/lua/pane/split.md)

The latter refers to “Top” and “Bottom” where I believe it should be “Up” and “Down”. Couldn't get it to work with "Top" or "Bottom" so think it must be.

Happy to submit a PR if this makes sense.

thanks!

**Comment by wez** [comment]
Thanks; yeah, it wasn't right. Should be fixed now!
