### ISSUE TITLE
Add a `--class` option to define the window class or `app_id` on Linux

### ISSUE THREAD

**Issue by alexherbo2** [wez/wezterm#325]
### Option

```
--class <instance> | <instance>,<general>
```

### Example

Open [Kakoune] in [Sway] as a floating window:

``` sh
wezterm --class 'WezTerm · Floating' start -- kak
```

The window rule for Sway:

`~/.config/sway/config`

```
for_window [app_id="WezTerm · Floating"] floating enable
```

[Kakoune]: https://kakoune.org
[Sway]: https://swaywm.org

**Comment by mborejdo** [comment]
I talked about that with @wez on matrix some months ago. He was not opposed and would accept a PR. Unfortunately my Rust is not sufficient to tackle this myself

**Comment by mborejdo** [comment]
thanks for adding this @wez. I am wondering, if the flag also should be added to wezterm-gui,

**Comment by wez** [comment]
> I am wondering, if the flag also should be added to wezterm-gui,

It's in both `wezterm start` and `wezterm-gui start`; `wezterm start` delegates to `wezterm-gui start`

**Comment by aserowy** [comment]
Heho,

im currently on sway 1.6.1. When i set '--class' swaymsg -t get_tree shows that class is set instead of app_id. Do i have to configure something to get the implemented behavior?

Kind regards
Alexander

**Comment by aserowy** [comment]
Heho,

ty for the reply. I checked the runtime with xlsclients and wezterm should run native in wayland. Maybe its a bug in the dependent crate? Which crate are you using to render a window? Thus, i can go further down the dependency.

Kind regards
Alexander

**Comment by wez** [comment]
https://github.com/wez/wezterm/blob/main/window/src/os/wayland/window.rs#L291 is where the app_id is set. 
It calls into: https://docs.rs/smithay-client-toolkit/0.15.1/smithay_client_toolkit/window/struct.Window.html#method.set_app_id

**Comment by aserowy** [comment]
Ok, i have to admit. This looks fool proof :D
