### ISSUE TITLE
`imgcat`: panic with an animated WEBP image

### ISSUE THREAD

**Issue by AnonymouX47** [wez/wezterm#3250]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE Window Manager (KWin)

### WezTerm version

20230314-065822-fc656c03

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

```shell
wezterm imgcat gif-test-2.webp
```
causes a panic.

[gif-test-2.webp](https://we.tl/t-SUPVBjrJZV) (813092 B)

I tried other animated WEBP images, no other one caused a panic... though, only the first frame is drawn (no animation). Also, I don't think it's the size, since I've tested with larger-sized images.

### To Reproduce

```shell
wezterm imgcat gif-test-2.webp
```

[gif-test-2.webp](https://we.tl/t-SUPVBjrJZV) (813092 B)

### Configuration

no config

### Expected Behavior

At least the first frame should be drawn, even if the image isn't animated (that's a separate issue).

### Logs

CLI logs from `RUST_BACKTRACE=full wezterm-nighly -n`:
```
12:46:23.076  ERROR  env_bootstrap > panic at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.5/./src/codecs/webp/extended.rs:462:21 - !?
   0: <unknown>
   ... [all just <unknown>]
  27: <unknown>

thread '<unnamed>' panicked at 'source slice length (750000) does not match destination slice length (1000000)', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.5/./src/codecs/webp/extended.rs:462:21
stack backtrace:
   0:     0x5566748d0dfa - <unknown>
   ... [all just <unknown> with different addresses]
  33:     0x7f5630920d90 - <unknown>
  34:                0x0 - <unknown>
12:46:23.689  ERROR  mux           > read_pty failed to write to parser: pane 0 Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
```

**Comment by wez** [comment]
That link doesn't work for me. Can you attach the image directly to this issue?
This is likely an issue in the upstream image crate, and I think it would be good for you to open an issue over there:
https://github.com/image-rs/image

**Comment by AnonymouX47** [comment]
Sorry, just updated the link. Should work now.

Due to the fact that I don't write Rust, I don't think I would be able to provide any steps for reproduction (aside "run this command in wezterm"). Also, I don't know how wezterm utilizes the crate. It'd be kinda weird for me to open a bug report at `image-rs`.

**Comment by wez** [comment]
[git-test-2.zip](https://github.com/wez/wezterm/files/10983085/git-test-2.zip)

attaching image as zip

**Comment by AnonymouX47** [comment]
> [git-test-2.zip](https://github.com/wez/wezterm/files/10983085/git-test-2.zip)
> 
> attaching image as zip

Oh, thanks! That didn't come to mind. :facepalm:

**Comment by wez** [comment]
https://github.com/image-rs/image/issues/1775 is the upstream issue.
It's fixed in their mainline, but not yet released

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by AnonymouX47** [comment]
I see. I'll test it out as soon as I get the nightly build and let you know the result.

By the way, the "Nightly AppImage" button [here](https://wezfurlong.org/wezterm/install/linux.html#installing-on-linux-using-appimage) links to the Ubuntu 18.04 build which is listed as "No longer supported" (on the same page) and the version is actually not up-to-date. I noticed this earlier when I was about to report this issue but I guess it skipped my mind, I had to download twice due to this.

Thanks so much for your quick and apt response! 🙏🏾

**Comment by AnonymouX47** [comment]
I've tested the fix, the bug itself is fixed but there are a couple other new issues. Here are the results of my tests:

Using `wezterm imgcat <column-header-below> gif-test-2.webp`:

| --height=10 & --height=20 |  | --height=30 & --height=40 |
|:---:|:---:|:---:|
| https://user-images.githubusercontent.com/61663146/225426835-f05ae497-c78a-4c6a-b486-c7fd37028ffd.mp4 | https://user-images.githubusercontent.com/61663146/225427080-b1ad4dbe-10ad-4176-b455-e918de4ac3a6.mp4 | https://user-images.githubusercontent.com/61663146/225427238-e3c0b336-03f0-43c2-ae03-f9adb8454d30.mp4 |

1. Note the weirdness in the rendered animation.
2. The image is not animated if the rendered dimension is less than the original image dimension. Note that the same applies to `--width`. I also tested with a different tool that utilizes the native animation capabilities of the protocol, the results were the same.

**NB:** My cell size (pixels) might be different from yours, so the same height values my not give the same results.

* * *

Tested a couple other WebP animated images using `wezterm imgcat <image-file>`:

[webp-images.zip](https://github.com/wez/wezterm/files/10984227/webp-images.zip)

| cell_animation.webp: frames not rendered well | bored_animation.webp: frames rendered well |
|:---:|:---:|
| https://user-images.githubusercontent.com/61663146/225430954-c015fba4-66ba-4e11-adbc-6d4e6f7574d0.mp4 | https://user-images.githubusercontent.com/61663146/225431046-0d7503be-f941-4e33-8b54-554e8bdb84c1.mp4 |

The same issue of rendered dimension vs original dimension also applies to both images.

* * *

I tested the images with a different tool that animates the image by **drawing frame-by-frame**. The frame delay/duration might not be exactly as specified in the image metadata though (if actually specified), I tweaked it to something reasonable for each. This is what they looked like:

| gif-test-2.webp | cell_animation.webp | bored_animation.webp |
|:---:|:---:|:---:|
| https://user-images.githubusercontent.com/61663146/225431708-a427213d-4b93-42f5-bec4-f9c2fad4d3f6.mp4 | https://user-images.githubusercontent.com/61663146/225433062-3e603f19-6457-4079-8f72-53e92541fed9.mp4 | https://user-images.githubusercontent.com/61663146/225433160-0c4ee438-1be8-467c-903a-292dbefcc8cc.mp4 |

* * *

**NB:** Sorry, even though I knew the videos couldn't be played in-place within the tables, there's quite a number of them.

**Comment by AnonymouX47** [comment]
By the way, as far as I've tested, these issues (the initial panic and the new issues) only apply to WebP animated images, all APNGs and GIFs I've tested worked fine.

I guess this is worth mentioning also... I've got an 8.4MB, 2188-frame, 1354x768 GIF that causes wezterm to use up a lot of memory (endlessly on my 16GB RAM PC, I have to terminate the process). I personally think there should be a safe memory limit for decoding images. By the way, it's not an issue with `imgcat`, but probably decoding the image [frames] itself because the same occurs with a different tool.

**Comment by wez** [comment]
Please open an separate issue for each thing; I'd prefer to be more granular than to bundle too much together into a single issue, because the latter makes it harder to easily tell whether the overall state is resolved.

**Comment by AnonymouX47** [comment]
Ok, good.

Any comments on the result above?

**Comment by wez** [comment]
I haven't had time to look; can you file a separate issue for each thing that seems separate? I consider this particular issue to be resolved

**Comment by AnonymouX47** [comment]
Ok, no problem. Will do so later, kinda occupied right now.

**Comment by AnonymouX47** [comment]
I think I have hereby done justice to all the issues I mentioned. 😃

**Comment by wez** [comment]
Thank!

**Comment by AnonymouX47** [comment]
It's a pleasure.

I discovered all of these while developing https://github.com/AnonymouX47/term-image.

I recall reporting some issue with the kitty graphics protocol implementation sometime ago, though I'm not keen on that (i.e the implementation of that specific protocol in Wezterm).

If at any time in the future, you make changes to or add some features related to displaying images or graphics, I would be willing to help test it out as long as I have the time and expertise to do so. Feel free to tag me on such at any time.

Thanks.
