### ISSUE TITLE
iterm2 inline image protocol: Inconsistent behaviour when sizing animated WebP images

### ISSUE THREAD

**Issue by AnonymouX47** [wez/wezterm#3258]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

20230315-113447-2bfb29f1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

This is an aftermath of https://github.com/wez/wezterm/commit/2bfb29f1bee5dacd060202dcff71df4497eebaf7 fixing #3250.

The image is not animated if the rendered dimension is less than the original image dimension.

Using `wezterm imgcat <column-header-below> gif-test-2.webp`:

| --height=10 & --height=20 |  | --height=30 & --height=40 |
|:---:|:---:|:---:|
| https://user-images.githubusercontent.com/61663146/225426835-f05ae497-c78a-4c6a-b486-c7fd37028ffd.mp4 | https://user-images.githubusercontent.com/61663146/225427080-b1ad4dbe-10ad-4176-b455-e918de4ac3a6.mp4 | https://user-images.githubusercontent.com/61663146/225427238-e3c0b336-03f0-43c2-ae03-f9adb8454d30.mp4 |

[gif-test-2.zip](https://github.com/wez/wezterm/files/10989411/gif-test-2.zip)

I also tested with other WebP images and a different tool that utilizes the native animation capabilities of the protocol, the results were the same. Hence, the issue isn't with `imgcat` or the escape sequence emitted (I inspected it).

As far as I've tested, this issue only affects WebP animated images, all APNGs and GIFs I've tested worked fine.

**NB:**
* My cell size (pixels) might be different from yours, so the same height values may not give the same results.
* I believe the incorrect rendering of frames is due to a separate issue (#3260).

### To Reproduce

```shell
wezterm imgcat [--height=X] [--width=X] gif-test-2.webp
```
* without `--height` and `--width`
* with heights and/or widths resulting in a smaller image than the original
* with heights and/or widths resulting in a larger image than the original

### Configuration

no config

### Expected Behavior

The image should be animated irrespective of its size.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation/).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source/) then you may be able to try this out more quickly.

**Comment by AnonymouX47** [comment]
Fixed in https://github.com/wez/wezterm/commit/587ceca98e761941ca72c429e329df4681d0f4ee.

Tested with version `20230317-115730-a394735f`.
