### ISSUE TITLE
appimage-run is slow on NixOS

### ISSUE THREAD

**Issue by alexherbo2** [wez/wezterm#326]

**Comment by wez** [comment]
Please describe the problem area rather than what you have in mind as a solution.
Why do you consider static builds to be an enhancement?
Why is that a good trade off against overall binary size and using the system provided X/Wayland binaries?

**Comment by alexherbo2** [comment]
Currently I use the AppImage under NixOS with `appimage-run`.  The startup is noticeably slow and was wondering if static builds could enhance that.

**Comment by wez** [comment]
You can manually unpack and run the appimage like this:

```
mkdir /tmp/wezterm-unpacked
cd /tmp/wezterm-unpacked
/path/to/WezTerm-20201101-103216-403d002d-Ubuntu16.04.AppImage --appimage-extract
squashfs-root/usr/bin/wezterm
```

If that runs quickly then you can infer that launching AppImages is slow on your system.

**Comment by wez** [comment]
I'm going to close this out as it isn't directly a wezterm issue.
https://github.com/NixOS/nixpkgs/issues/90696 is tracking setting up proper packaging for nixos.
