### ISSUE TITLE
Can't remap CTRL + SHIFT + P

### ISSUE THREAD

**Issue by phallguy** [wez/wezterm#3262]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230316-000500-a22e6fa1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Can't disable the default mapping of CTRL+SHIFT+P to the command palette

Just switching from iTerm and heavy neovim user. I happen to have a keybinding in vim to <CS-p> that I use quite frequently. Still learning wezterm but that muscle is a bit too ingrained so I thought I'd remap the wezterm command palette to a different set of keys. Unfortunately using DisableDefaultAssignment doesn't seem to do the trick.

### To Reproduce

Add key mappings for CTRL+SHIFT+P and use the DisableDefaultAssignment action.

Press CTRL+SHIFT+P and the palette is still shown, preventing the underlying app (neovim in my case) from accepting the keys.

I've mapped the command palette to a different set of keys just to make sure the config was doing something and I can map it to CTRL+SHIFT+N and that works.

### Configuration

```lua
-- https://wezfurlong.org/wezterm/config/files.html
local wezterm = require("wezterm")

return {
	keys = {
		{
			key = "p",
			mods = "CTRL | SHIFT",
			action = wezterm.action.DisableDefaultAssignment,
		},
		{
			key = "P",
			mods = "CTRL | SHIFT",
			action = wezterm.action.DisableDefaultAssignment,
		},
		{
			key = "n",
			mods = "CTRL | SHIFT",
			action = wezterm.action.ActivateCommandPalette,
		}
	}
}
```

### Expected Behavior

Don't bind to CTRL+SHIFT+P so I can may that binding in vim

### Anything else?

Really loving everything else so far. Thanks for all the great work.

**Comment by wez** [comment]
I'd suggest looking at the `wezterm show-keys --lua` output to see what's actually being assigned and how

**Comment by phallguy** [comment]
Thanks for the tip - I did give that a shot before but forgot to mention it in the issue. With the config above this is still included (full output attached):

```lua
{ key = 'P', mods = 'SHIFT|CTRL', action = act.ActivateCommandPalette },
{ key = 'p', mods = 'SHIFT|CTRL', action = act.ActivateCommandPalette },
```

[keys.lua.zip](https://github.com/wez/wezterm/files/10996414/keys.lua.zip)

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by phallguy** [comment]
Amazing. Everything's working great now. Thanks for the quick fix!

Side note - I'm guessing the response is templated - with the updated docs (which are great BTW), the links don't point to the right destination anymore.

**Comment by wez** [comment]
Ah, thanks: yeah, I'll update my template!
