### ISSUE TITLE
iterm2 inline image protocol: Wezterm takes a lot of memory and time to display a large GIF

### ISSUE THREAD

**Issue by AnonymouX47** [wez/wezterm#3263]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

20230315-113447-2bfb29f1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I've got an 8.4MB, 2188-frame, 1354x768 GIF that causes wezterm to use up a lot of memory and time.

[clifm-test.zip](https://github.com/wez/wezterm/files/10992715/clifm-test.zip)

With `wezterm imgcat clifm-test.gif`, after about 16s, the memory usage reaches a peak, stays fairly constant for about another 16s and then displays and begins to animate the image... See the screencast attached below.

Other things to note:
1. Wezterm is completely on responsive until the image shows up, only an external signal can terminate the process.
2. The memory consumed isn't deallocated:
   * after decoding the image i.e during animation
   * after clearing the screen
   * after a reset (executing the `reset` command)
3. Executing the command to display the image again continues to use up more memory.

By the way, it's not an issue with `imgcat` itself because the same occurs when using a different tool that utilizes the protocol's animation feature.

For the record, I viewed the image with `gwenview` (KDE's Image Viewer) and it only used about 60MB of memory. I also tried a couple other tools for viewing images in terminal emulators (which handle the animation themselves, drawing frame-by-frame) and they only used up a couple MBs and started the animation almost instantly.

*For some insight, this was on a laptop with a Ryzen 4600H (6 cores, 12 threads @ 4GHz max) CPU and 16GBs of RAM, while plugged in. It also has an NVIDIA GPU but I've seen no reason to believe Wezterm utilizes it.*

### To Reproduce

```shell
wezterm imgcat clifm-test.gif
```

* Watch the time and memory usage.
* Check if Wezterm responds to anything at all.

### Configuration

no config

### Expected Behavior

1. I think there should be a safe memory limit for decoding images.
2. It would be advisable to decode images either in a separate thread or an entirely separate process that's being monitored by a thread of the main process.
   * this should help to keep wezterm responsive and able to handle the memory usage limit.
   * i believe iTerm2 uses a separate sandboxed process to overcome this (from conversations I've read)... though, I'm yet to test it out due to lack of access to a mac.
3. I expect Wezterm to either load frames the from the GIF file as needed (possibly a few frames ahead), while caching them to disk for loading on the next animation loop. In fact, keeping the 8.4 MB GIF file data along with a couple frames in memory per-time isn't too bad.
   * If caching, the GIF file data can be deallocated as soon as all frames have been loaded and cached.
4. Start the animation almost instantly. It shouldn't load all the frames first.

### Anything else?

Screencast:

https://user-images.githubusercontent.com/61663146/225689755-a7d8c80a-7fd3-4d2f-b606-b1891e795001.mp4

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation/).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source/) then you may be able to try this out more quickly.

**Comment by AnonymouX47** [comment]
Hmm... I have tested this with version `20230317-115730-a394735f` and I have to say, my results are no where near good.

As a matter of fact, https://github.com/wez/wezterm/commit/e090eb9eae1d0746dbed62d8a92edc0a64635213 introduced more bugs than it *supposedly* fixed. On the surface, it looks like the changes are doing what they *should* but it really isn't so.

As I go ahead to report and describe my test results, I'll personally advice that commit e090eb9 be reverted on main ASAP and the implementation of this fix be moved to a separate branch, possibly also with an open PR linked to this issue for tracking and then the branch can be merged into `main` when everything seems fine.
Though, it'll only affect nightly/source builds anyways. So, if you're okay with that, then it's all good keeping things on `main`.

Anyways, from what I've seen from my tests, the fix for this issue doesn't look like the one-commit kind.

Thanks.

**Comment by AnonymouX47** [comment]
By the way, is there any other way to get a previous nightly build aside build from source?

I need the build just before https://github.com/wez/wezterm/commit/e090eb9eae1d0746dbed62d8a92edc0a64635213 to precisely determine differences in behaviour... to know what exactly was introduced by this commit.

Thanks.

**Comment by AnonymouX47** [comment]
Ouch!... I guess my reports might take a little longer then, seeing the repository is not small in size.

I'll get back to you as soon as I get things in place.

A few pointers until then:

- Watch **cache** memory usage
- Separate thread spawned for every **different** image data
- All spawned threads stay alive, even for non-animated images
- Decoding error with **RGB** (without Alpha channel) **PNG** images
  - results in "decode thread terminated"
- "Error decoding image: InvalidCode" for some GIFs
  - Sometimes results in "decode thread terminated"
- "decode thread terminated" (or the error that caused it) renders the terminal unusable
- "Too many open files (os error 24)" after drawing many different images in succession (e.g with manual frame-by-frame animation)
  - Seems files are not being closed
- First loop of animations is broken
  - Probably while still decoding the frames
  - Wrong frame duration, it seems
- and more...
