### ISSUE TITLE
iterm2 inline image protocol: the screen is scrolled whenever an image (with`doNotMoveCursor=0`) reaches the last line

### ISSUE THREAD

**Issue by AnonymouX47** [wez/wezterm#3266]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

20230316-093132-88e53a5f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With `doNotMoveCursor=0`, the screen is scrolled if an image reaches the last line, even though the cursor has neither reached the last column nor advanced to the next line. This only occurs if the image reaches the last line of the screen.

This also occurs on the alternate screen/buffer and **messes up TUIs**, which is my major concern.

See the screencast attached below.

### To Reproduce

Emit an iterm2 inline image escape sequence to the terminal **without a trailing EOL (_newline_, "\n")**.

Sample sequence (all white image, 1x1 cells)
```
\x1b]1337;File=size=86;width=1;height=1;preserveAspectRatio=0;inline=1:iVBORw0KGgoAAAANSUhEUgAAAAoAAAAWCAIAAAB2RJoKAAAAHUlEQVR4XmP8//8/A27AhC6ACkalsYJRaayAMmkALcYDKZtUpxIAAAAASUVORK5CYII=\x1b\\
```

If in a shell or REPL, ensure you put the program to sleep for some seconds immediately after emitting the sequence **before an EOL is emitted**... without the sleep, this behaviour will not be evident.

Observe the behaviour when the image reaches the last screen line versus when it doesn't.

### Configuration

no config

### Expected Behavior

The screen should not be scrolled if the image's height doesn't require it i.e when the image ends exactly on last line of the screen.

If the image requires more lines than what is left on the screen, the screen shouldn't be scrolled any more than the image's height requires i.e no extra line.

### Anything else?

This doesn't occur with `doNotMoveCursor=1` but:
- there are concrete reasons why this argument can't work with my use case
- politely, this isn't an excuse for `doNotMoveCursor=0` to be broken

Screencast:

https://user-images.githubusercontent.com/61663146/225728821-bce6ada3-38b1-4055-9138-44feb840ef1b.mp4

Note that the cursor never advances to the next line until after the sleep nor does it reach the last column.

**Comment by wez** [comment]
Looks like this was "just" an off-by-one-line issue. I believe this to be resolved now; behavior appears consistent with iTerm2.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation/).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source/) then you may be able to try this out more quickly.

**Comment by AnonymouX47** [comment]
Fixed in https://github.com/wez/wezterm/commit/a115fc0df77091ada2497fde22bc5c013e860ecd.

Tested with version `20230317-115730-a394735f`.
