### ISSUE TITLE
new tab or new split pane doesn't respect current working directory or defaults to home directory when a program is actively running in the spawning tab.

### ISSUE THREAD

**Issue by suvarchal** [wez/wezterm#3267]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes

### Describe the bug

In my first tab i run a program like opening pdf  say using `evince doc.pdf` from a working directory that is not my home directory. Now I create a new tab and split the pane horizontally using shortcuts CTRL+SHIFT+T and CTRL+ALT+SHIFT+% respectively, the expectation was the new terminal uses working directory of first tab but it opens terminal at my home directory.  I think this is important feature even my gnome terminal takes into account. BTW if the opened program is sent to background using say ` evince doc.pdf &` everything works as expected. 

### To Reproduce

change from default working directory of wezterm to some directory say DIR and run a program, say open pdf document now start a new tab using CTRL + SHIFT + T, check if it is in DIR or not. This doesn't happen when program is opened in background like `evince doc.pdf &`. 

### Configuration

no-config

### Expected Behavior

I expect that any new spawned tab respects current working directory of spawning-source tab.

**Comment by wez** [comment]
Please try the nightly build

**Comment by suvarchal** [comment]
> Please try the nightly build

I tried nightly appimage from https://wezfurlong.org/wezterm/install/linux.html#installing-on-linux-using-appimage the issue persists.

**Comment by suvarchal** [comment]
To add to the issue, I cannot use shortcuts to switch to another tab when there is a active program like say vim in current tab. I am assuming this is a related issue. I see how this may have crept in trying to keep shortcut keys spaces separate so that the wez's shortcuts do not interleave with active program shortcuts.

if you think it is not related i could open another issue.

**Comment by wez** [comment]
What I think is happening is that evince chdir's to your home directory.  When wezterm goes to spawn a tab, because you don't have shell integration installed and nothing has set the OSC 7 current working directory, wezterm uses the working directory of evince, which is the foreground process in that tab.

If you install from rpm or deb you'll get the [shell integration](https://wezfurlong.org/wezterm/shell-integration.html) that should take care of that.  If you can't install one of those packages, you can install it manually; there's more information on that page.

For keys: see https://wezfurlong.org/wezterm/troubleshooting.html#debugging-keyboard-related-issues and file a separate issue if you need to follow up.

**Comment by suvarchal** [comment]
> To add to the issue, I cannot use shortcuts to switch to another tab when there is a active program like say vim in current tab. I am assuming this is a related issue. I see how this may have crept in trying to keep shortcut keys spaces separate so that the wez's shortcuts do not interleave with active program shortcuts.
> 
> if you think it is not related i could open another issue.

oh my bad this issue of switching tabs when a active program like VI editor is running works in nightly.

**Comment by suvarchal** [comment]
> What I think is happening is that evince chdir's to your home directory. When wezterm goes to spawn a tab, because you don't have shell integration installed and nothing has set the OSC 7 current working directory, wezterm uses the working directory of evince, which is the foreground process in that tab.
> 
> If you install from rpm or deb you'll get the [shell integration](https://wezfurlong.org/wezterm/shell-integration.html) that should take care of that. If you can't install one of those packages, you can install it manually; there's more information on that page.
> 
> For keys: see https://wezfurlong.org/wezterm/troubleshooting.html#debugging-keyboard-related-issues and file a separate issue if you need to follow up.

Thanks! 

I did install release version using apt-get so i guess i am getting a deb package, only for a nightly i used appimage.   I will check out shell integration meanwhile.

**Comment by wez** [comment]
I think there is nothing more for wezterm to do here, so I'm closing this!
