### ISSUE TITLE
Closing tabs pointing at ssh domains locks up wezterm

### ISSUE THREAD

**Issue by mjlbach** [wez/wezterm#3269]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230316-181330-c093b886

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Intermittently, wezterm becomes unresponsive clientside when closing/opening new tabs pointing to an ssh domain, especially if this is done quickly (100% reproducible for me)

### To Reproduce

1. open wezterm
2. create multiple new ssh domain tabs (cmd + t on mac)
3. close multiple ssh domain tabs (cmd + w on mac)

### Configuration

N/A, only add a remote ssh domain

### Logs

The only line I see is:
11:33:47.053  INFO   wezterm_client::client > going to run wezterm cli --prefer-mux proxy

But I can't access the debug overlay after wezterm freezes.

**Comment by wez** [comment]
I can't reproduce this. Please add more information about how to reliably reproduce it!

**Comment by mjlbach** [comment]
Hi wez! Thanks for looking, I updated to the latest release and can't reproduce it now but will let you know if it happens again! Thanks!
