### ISSUE TITLE
Open wezterm here no work

### ISSUE THREAD

**Issue by pwsandoval** [wez/wezterm#3270]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I can't get the **"Open Wezterm here"** context menu option to work with no local disk or folder, neither can I debug or read the log, because the window doesn't open and doesn't show any error code or message either.

A video showing what happens:

https://user-images.githubusercontent.com/15174704/226065235-c942960e-aee0-45bc-a549-cbf7bb579af9.mp4

### To Reproduce

With this minimal config this happens to me.

### Configuration

```lua
return {
   default_domain = "WSL:Ubuntu-20.04",
   wsl_domains = {
      {
         name = "WSL:Ubuntu-20.04",
         distribution = "Ubuntu-20.04",
         username = "pw",
         default_cwd = "/home/pw/Dev",
         default_prog = { "zsh" }
      }
   },
   launch_menu  = {
      {
         label = "wsl",
         args = { "wsl.exe" },
         domain = { DomainName = "local" },
         cwd = "\\\\wsl$\\Ubuntu-20.04\\home\\pw\\Dev"
      },
      {
         label = "pwsh",
         args = { os.getenv("LOCALAPPDATA") .. "\\Microsoft\\WindowsApps\\pwsh.exe", "-nologo" },
         domain = { DomainName = "local" },
         cwd = "D:\\Dev",
      }
   }
}
```

### Expected Behavior

Wezterm is started in the folder I select.

**Comment by wez** [comment]
I don't think it is compatible with using WSL as the default domain. Try commenting out the `default_domain` line.
