### ISSUE TITLE
Would like Wezterm SSH to open new panes in the directory where it was open, not in the home directory.

### ISSUE THREAD

**Issue by HidemaruOwO** [wez/wezterm#3281]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When I spawn a new pane in Wezterm normally, it opens a new pane in the directory where it was open, 
but when using Wezterm SSH, it opens a new pane in the home directory instead of the previously opened directory. 
**Describe alternatives you've considered**
Would like Wezterm SSH to open new panes in the directory where it was open, not in the home directory.

**Additional context**
This text has been machine translated.
I apologize for any mistakes.

**Comment by wez** [comment]
You need to install the [Shell Integration](https://wezfurlong.org/wezterm/shell-integration.html) on the remote host:
https://github.com/wez/wezterm/tree/main/assets/shell-integration

**Comment by HidemaruOwO** [comment]
thank you

**Comment by HidemaruOwO** [comment]
Can I use it with fish?

**Comment by HidemaruOwO** [comment]
hmm...
