### ISSUE TITLE
Subsecond-precision timer

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#3287]
**Is your feature request related to a problem? Please describe.**
I'd like to delay some expensive process computations on tab switching by adding a timer that only fires off after all the tab switches ended.
However, the minimum precision of the `wezterm.time.call_after(interval_seconds, function)` function I'm using for this is 1 second. Tried float numbers < 1, but it doesn't seem to have the desired effect, instead I get much higher precision, which is a waste, I need to have a small timer below the threshold I can notice, but not much smaller to waste on updates

For example, this is a self-calling function from [this issue](https://github.com/wez/wezterm/issues/3026)that has a `0.3` interval
```
"...59.475537" 9 0.3 second passed
"...59.476712" 8 0.3 second passed
"...59.477310" 7 0.3 second passed
"...59.477905" 6 0.3 second passed
"...59.478328" 5 0.3 second passed
"...59.478718" 4 0.3 second passed
"...59.479122" 3 0.3 second passed
"...59.479506" 2 0.3 second passed
"...59.480245" 1 0.3 second passed
```

**Describe the solution you'd like**
`wezterm.time.call_after(interval_seconds, function)` to accept fractional seconds

**Describe alternatives you've considered**
Don't know of any, tried to subscripte to status bar updates, but they are also updated once per second

**Additional context**
None

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by eugenesvk** [comment]
Thanks for such a quick fix, seems to be working nicely!
