### ISSUE TITLE
Clicking URLs now causes CMD.EXE window to briefly pop-up

### ISSUE THREAD

**Issue by pragma-** [wez/wezterm#3288]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

WezTerm-windows-20230317-153901-2d255c2d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Since updating to the newest nightly to try the `highlight` option, any time I click a URL a CMD.EXE window briefly pops up and then quickly disappears. This behavior was not present in previous nightlies.

### To Reproduce

Using Windows 10, start wezterm and click on a URL.

### Configuration

no config

### Expected Behavior

No CMD.EXE window should pop up when clicking URLs.

**Comment by wez** [comment]
This is a regression in the upstream `open` crate.
https://github.com/Byron/open-rs/pull/63

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
