### ISSUE TITLE
Add an action to change the background opacity of the current window

### ISSUE THREAD

**Issue by alexherbo2** [wez/wezterm#329]

**Comment by wez** [comment]
Updating the config will hot reload and apply an adjusted opacity.
Please provide more information on *why* you want this new behavior and why the existing configuration is insufficient.

**Comment by alexherbo2** [comment]
The changes will be applied to all terminals, not the current one.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html shows how you can configure an assignment to make whatever config changes you like; examples for ligatures and opacity are included
