### ISSUE TITLE
unavailable ActivateCommandPalette

### ISSUE THREAD

**Issue by wangmings** [wez/wezterm#3297]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

err

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

# set ActivateCommandPalette 

 keys = {

    {
      key = 'P',
      mods = 'CTRL',
      action = wezterm.action.ActivateCommandPalette,
    },
}

## Refer to the following connection and no solution was found
 https://github.com/wez/wezterm/issues/3262

##  Error message

callback error
stack traceback:
        [C]: in metamethod 'index'
        [string "/Users/mac/.wezterm.lua"]:765: in main chunk
caused by: `ActivateCommandPalette` is not a valid KeyAssignment
variant. Did you mean one of `ActivateCopyMode`, `ActivatePaneByIndex`,
`ActivateTabRelative`, `ActivateTab`, `ActivateKeyTable`,
`ActivatePaneDirection`, `ActivateLastTab`, `ActivateTabRelativeNoWrap`? There
are too many alternatives to list here; consult the documentation!

### To Reproduce

err

### Configuration

  keys = {

    {
      key = 'P',
      mods = 'CTRL',
      action = wezterm.action.ActivateCommandPalette,
    },
}

### Expected Behavior

err

### Logs

err

### Anything else?

err

**Comment by wez** [comment]
As the docs say, you need to be running the nightly build to use that function:
https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateCommandPalette.html

**Comment by wangmings** [comment]
I can't understand the meaning of "Since: nightly builds only" in the document ?

"Since: nightly builds only" means that it is necessary to compile the entire project from source code to support this feature
https://wezfurlong.org/wezterm/install/source.html

curl https://sh.rustup.rs -sSf | sh -s
curl -LO https://github.com/wez/wezterm/releases/download/20221119-145034-49b9839f/wezterm-20221119-145034-49b9839f-src.tar.gz
tar -xzf wezterm-20221119-145034-49b9839f-src.tar.gz
cd wezterm-20221119-145034-49b9839f
./get-deps
cargo build --release
cargo run --release --bin wezterm -- start
Alternatively, use the full git repo:

curl https://sh.rustup.rs -sSf | sh -s
git clone --depth=1 --branch=main --recursive https://github.com/wez/wezterm.git
cd wezterm
git submodule update --init --recursive
./get-deps
cargo build --release
cargo run --release --bin wezterm -- start

wezterm Terminal ActivateCommandPalette
Since: nightly builds only

**Comment by wez** [comment]
It means that the feature is only available starting in nightly builds.

You can download the nightly build for all platforms from the download pages:
https://wezfurlong.org/wezterm/install/macos.html

**Comment by wangmings** [comment]
Thanks for the reply, I understand.
