### ISSUE TITLE
Sudden Very High CPU Usage

### ISSUE THREAD

**Issue by sapi01** [wez/wezterm#330]
I'm on macOS 10.15.7
Version: wezterm 20201101-103216-403d002d

When I'm on my NeoVIM and editing files, I noticed WezTerm suddenly uses Very high CPU usage and everything gets hung and becomes non-responsive. I just tried WezTerm today and did a very minimal configuration. 

My Config:
```
return {
        default_cursor_style = "SteadyBar",
        send_composed_key_when_left_alt_is_pressed=false,
        send_composed_key_when_right_alt_is_pressed=true,
}
```
Video Capture of resource utilization of WezTerm: https://streamable.com/xkulzy

**Comment by sapi01** [comment]
just found out that, an issue was on my end.

**Comment by bew** [comment]
@sapi01 what kind of issue was it?
