### ISSUE TITLE
how to make neovim full size 

### ISSUE THREAD

**Issue by mas-wig** [wez/wezterm#3304]
noob question !!

![2023-03-21-11:16aaa:53-screenshot](https://user-images.githubusercontent.com/88357663/226516665-eb639a16-1a2d-4db8-a902-8596674e4eb1.png)

how to make neovim full size as per terminal without any gap like this

**Comment by wez** [comment]
terminals are built around fixed-size cells. wezterm can only show whole numbers (integers) of cells in the X and Y direction.

What you're seeing at the bottom is padding in your chosen terminal background color to fill out the "unusable" space.

It looks like you are using a vim theme that changes the background color attribute of cells while vim is running, which exaggerates this situation.

I recommend using `guibg=NONE ctermbg=NONE` to leave the background color to the terminal, then picking a terminal color scheme that has the appearance that you want for an edge-to-edge look.
