### ISSUE TITLE
ssh ProxyCommand option not parsed correctly with '=' character

### ISSUE THREAD

**Issue by schweikert** [wez/wezterm#3307]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20230320-124340-559cb7b0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The latest version 20230320-124340-559cb7b0 introduced a regression for me with the ProxyCommand handling and it doesn't work at all anymore. The problem is that I have a ProxyCommand setting that has a '=' character in it. Something like:

```
ProxyCommand /usr/bin/ssh-proxy-helper -oX=Y host 22
```

Looking at the output of wezterm ssh -v I see that this is parsed as follows:

```
08:27:52.212  INFO   mux::ssh > Using ssh config: {
     ...
    "proxycommand /usr/bin/ssh-proxy-helper -ox": "Y host 22",
    ...
}
```

Thus the ProxyCommand option is ignored and I can't connect.

This was working before I think because the ProxyCommand handling was implemented inside of libssh-rs.

### Configuration

no config

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by schweikert** [comment]
I can confirm that this works now. Thank you!
