### ISSUE TITLE
antialiasing "shadows" when fg == bg

### ISSUE THREAD

**Issue by dmfay** [wez/wezterm#331]
I have listchars set up so ❧ appears at the beginning of broken lines and ¶ at the end of a line. Both are colored identically to the background so they're only visible under the (brighter) cursor line.

```
hi NonText gui=NONE guifg=#3c3445 guibg=NONE
```

Here's termite again!

![1605502824](https://user-images.githubusercontent.com/3075455/99214677-d06c3300-279e-11eb-956a-0904e351d9d0.png)

In wezterm:
![1605502841](https://user-images.githubusercontent.com/3075455/99214684-d5c97d80-279e-11eb-962c-d28fcaf48804.png)

The opposite areas of the pilcrow are dark vs light, and the fleuron is rendered as a question mark, the latter handily explained by the current log:

```
 2020-11-16T04:37:41.213Z ERROR wezterm_font::shaper::harfbuzz > No more fallbacks while shaping \u{2767} for "❧"
 2020-11-16T04:37:41.213Z ERROR wezterm_font::shaper::harfbuzz > No more fallbacks while shaping \u{fffd} for "�"
```

So something's going on with my font setup, although I've got every font set up in wezterm.lua that I have for i3 or termite:

```
  font = wezterm.font_with_fallback({"Inconsolata-dz", "FontAwesome5Free", "DejaVuSans", "JoyPixels"}),
```

But more oddly, wezterm displays both symbols in a very dark gray, darker than anything I have configured:

```
  colors = {
    foreground = "#f5eff3",
    cursor_border = "#f5eff3",
    cursor_bg = "#f5eff3",
    cursor_fg = "#3c3445",
    background = "#3c3445",

    ansi = {
      "#3c3445",
      "#9c6b80",
      "#6e916e",
      "#9c8969",
      "#6582c7",
      "#a276b6",
      "#6698aa",
      "#cfc7cd"
    },
    brights = {
      "#604c60",
      "#dc98ac",
      "#96c497",
      "#d9bd8f",
      "#98b2fb",
      "#d6ade8",
      "#9ccbdd",
      "#f5eff3"
    }
  }
```

**Comment by wez** [comment]
Can you capture that screen using [wt-record](https://github.com/wez/wezterm/blob/master/wt-record) (which is really just a wrapper around `script`)?  That will help me reproduce what is on screen and help me trace what's happening without requiring me to completely reproduce your environment.

**Comment by dmfay** [comment]
Here's a recording. I resize the window and tab-complete to open `wezterm.head.log` in neovim; the file's three lines long and all lines wrap so you should have three question marks and three pilcrows.

[2020-11-16.zip](https://github.com/wez/wezterm/files/5550887/2020-11-16.zip)

**Comment by wez** [comment]
it took me a bit to parse the issue; neovim is specifying that the foreground be set to `#3c3445`, and that is what is being used in the terminal model.

The issue appears to be anti-aliasing artifacts from the font rendering stage.

On my screen they are almost invisible smudges, but if you make the font large enough they are a bit more prominent.  Varying `font_antialias` changes how visible they are; `None` makes them disappear, while `Greyscale` makes them very prominent and `Subpixel` makes them harder to see.

I could reproduce the coloring with this vim config:

```vimrc
hi NonText ctermfg=NONE gui=NONE guifg=#3c3445 guibg=NONE
hi SpecialKey ctermfg=NONE gui=NONE guifg=#3c3445 guibg=NONE
```

**Comment by wez** [comment]
I've pushed a commit that special-cases monochrome glyphs whose fg == bg to make them transparent.  It appears to resolve it for me!

**Comment by dmfay** [comment]
Shadows are gone here too. Thanks!
