### ISSUE TITLE
A transparent title bar appears with `window_decorations = "RESIZE|MACOS_FORCE_DISABLE_SHADOW"`

### ISSUE THREAD

**Issue by noefroidevaux** [wez/wezterm#3313]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

\-

### WezTerm version

20230320-124340-559cb7b0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

By adding `MACOS_FORCE_DISABLE_SHADOW` to `RESIZE` for `window_decorations` config, I have a transparent window bar.

With `window_decorations = "RESIZE|MACOS_FORCE_DISABLE_SHADOW"`:

<img width="499" alt="Screenshot 2023-03-21 at 18 06 29" src="https://user-images.githubusercontent.com/37739/226687543-362d919a-efa9-4bf8-b1c7-a29182a2fc9b.png">

With `window_decorations = "RESIZE"`:

<img width="445" alt="Screenshot 2023-03-21 at 18 06 11" src="https://user-images.githubusercontent.com/37739/226687580-ddf25e0a-5a8f-495d-8c78-74e9e3fdfa68.png">

Issue linked to this issue: https://github.com/wez/wezterm/issues/2669

### To Reproduce

Set the config `window_decorations = "RESIZE|MACOS_FORCE_DISABLE_SHADOW"` (on macOS)

### Configuration

```
local wezterm = require 'wezterm'
local mux = wezterm.mux

wezterm.on('gui-startup', function(cmd)
  local _, _, window = mux.spawn_window(cmd or {})
  window:gui_window():maximize()
end)

return {
  font = wezterm.font "IosevkaTerm Nerd Font Mono",
  font_size = 15,
  color_scheme = 'Dracula (Official)',
  window_decorations = "RESIZE|MACOS_FORCE_DISABLE_SHADOW",
  enable_tab_bar = false,
  initial_rows = 50,
  initial_cols = 200,
  audible_bell="Disabled",
  send_composed_key_when_left_alt_is_pressed=true,
}
```

### Expected Behavior

Not having a transparent window bar (like with the config `window_decorations = "RESIZE"`)

**Comment by wez** [comment]
I can't explain this behavior, but this should be equivalent and doesn't cause the titlebar to appear:

```lua
  window_decorations = "RESIZE",
  window_background_opacity = 0.999,
```

**Comment by noefroidevaux** [comment]
@wez Thank you for the workaround. Could it be linked to this condition? https://github.com/wez/wezterm/blob/3eede5c248e022ef30b604dcc254d13c632bf5d0/window/src/os/macos/window.rs#L1237 . I can try to fix it and make a PR if you want?

**Comment by noefroidevaux** [comment]
Thank you for your message @wez ! I tested the code you provided and it works great! 👍 I made a PR for this change (#3330).
