### ISSUE TITLE
For compatibility sake please add "-e" flag along "start" command.

### ISSUE THREAD

**Issue by grappas** [wez/wezterm#3314]
![obraz](https://user-images.githubusercontent.com/1036957/226724857-fdf112c5-796b-48d9-9996-be409c1dd6af.png)

Majority of terminal emulators has this feature and many apps are very dependent on -e (as execute) flag.

**Comment by wez** [comment]
Already implemented in the latest release, please upgrade.
* https://github.com/wez/wezterm/pull/2889
