### ISSUE TITLE
Support changing the default shell without %ComSpec%

### ISSUE THREAD

**Issue by EDToaster** [wez/wezterm#3317]
**Is your feature request related to a problem? Please describe.**

This feature request is a workaround related to windows bug (unconfirmed?) when setting ComSpec to powershell

Steps to reproduce the issue (not related to WezTerm):
1. Set ComSpec environment variable to powershell, like  `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`
2. Create a `.bat` file with contents `pause`
3. Try to run the `.bat` file by double clicking on it, you'll see that roughly 10 powershell instances are spawned every second, causing the system to eventually run out of memory. **Delete the bat file to kill all of the powershell instances before this happens**

Not sure what causes this behaviour but it is untenable to change ComSpec at this time.

**Describe the solution you'd like**

Provide a way to specify the default shell without the use of ComSpec, maybe something like WEZTERM_DEFAULT_SHELL as an environment variable.

Everywhere online seems to suggest that you shouldn't alter the value of ComSpec since a lot of programs will assume it points to cmd.

**Describe alternatives you've considered**

A quick workaround is to call `powershell` in CMD every time i open wezterm, but that is annoying.

**Additional context**

This is the only other report related to the same issue I've found 

https://github.com/sbt/sbt/issues/6643

**Comment by wez** [comment]
Please see: https://wezfurlong.org/wezterm/config/launch.html#changing-the-default-program

To change it just as a one-off, you can `wezterm --config "default_prog='powershell.exe'" start`

**Comment by EDToaster** [comment]
turns out i need to learn to read 👍 thanks!

**Comment by EDToaster** [comment]
for anyone reading this in the future -- `default_prog` is a vec, so the correct syntax is 

```
wezterm --config "default_prog={ 'program', 'args', 'args' }" start
```
