### ISSUE TITLE
Cannot open zathura properly

### ISSUE THREAD

**Issue by OmeletWithoutEgg** [wez/wezterm#3324]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

I'm using KDE plasma so it should be kwin.

### WezTerm version

wezterm 20230322-063603-f37c3ae5

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

zathura is a GTK pdf viewer app (I guess so), and when I execute `zathura some.pdf` in wezterm in my shell, the window opens normally but it appears under the wezterm window and didn't focus on it. It is raised (like `xdotool windowraise`) but not focused (like `xdotool windowactive`).
When using konsole, alacritty, it focuses on the pdf viewer normally.

### To Reproduce

Install zathura, and open any pdfs.
For example on Arch,
```
sudo pacman -S zathura zathura-pdf-mupdf
zathura some.pdf
```

### Configuration

With `wezterm -n`, the problem can still happens.

### Expected Behavior

Should focus on the pdf viewer.

### Logs

No error message there
```
Debug Overlay
wezterm version: 20230322-063603-f37c3ae5 x86_64-unknown-linux-gnu
Window Environment: X11 KWin
OpenGL version: Mesa Intel(R) Graphics (ADL GT2) 4.6 (Compatibility Profile) Mesa 23.0.0
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
```

**Comment by wez** [comment]
This has nothing to do with wezterm. Your shell is launching that program and the terminal has no idea, control or influence over things, especially gui programs, spawned by your shell.

**Comment by OmeletWithoutEgg** [comment]
I found that kitty will have this problem too.

Is there some properties that kitty and wezterm have but not alacritty, gnome terminal or konsole?

**Comment by wez** [comment]
Neither kitty nor wezterm use gui frameworks like GTK or KDE
