### ISSUE TITLE
macOS native menu bar keybinds/hotkeys override custom keybinds

### ISSUE THREAD

**Issue by datwaft** [wez/wezterm#3326]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230321-220914-f0a86602

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have mapped `CMD+[` and `CMD+]` to send `CTRL+b+n` and `CTRL+b+p` to be able to switch between TMUX windows but when I updated to the latest version (stable) I saw that those mappings were being overridden by the menu bar keybinds.

I am setting the mappings like this:

```lua
  { key = "{",          mods = "SHIFT|CMD", action = wezterm.action.SendString("\2p") },
  { key = "}",          mods = "SHIFT|CMD", action = wezterm.action.SendString("\2n") },
```

Curiously I also have other mappings that are also conflicting with the menu bar keybinds but in those cases they are not overridden, it's only with those mappings.

I already verified that the keybind codes are as expected:

```console
$ sed -n l
^B
\002$
```

### To Reproduce

1. Set keybinds like the following:

    ```lua
      { key = "{",          mods = "SHIFT|CMD", action = wezterm.action.SendString("\2p") },
      { key = "}",          mods = "SHIFT|CMD", action = wezterm.action.SendString("\2n") },
    ```
2. Execute `sed -n l` to check if any keybind is pressed.
3. Then try to use `CMD+[` or `CMD+]` to see if anything is being passed to `sed -n l`.

### Configuration

```lua
local wezterm = require("wezterm")
local keys = {
	{ key = "{", mods = "SHIFT|CMD", action = wezterm.action.SendString("\2p") },
	{ key = "}", mods = "SHIFT|CMD", action = wezterm.action.SendString("\2n") },
}
return {
	keys = keys,
}
```

### Expected Behavior

Something should be passed to `sed -n l`, even if it was the incorrect key code.

**Comment by wez** [comment]
I'm not at my mac at the moment, but if you look at `wezterm show-keys --lua` you'll probably see a couple of keys with curly braces; I see this on my linux box:

```
    { key = '{', mods = 'SUPER', action = act.ActivateTabRelative(-1) },
    { key = '{', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(-1) },
    { key = '}', mods = 'SUPER', action = act.ActivateTabRelative(1) },
    { key = '}', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(1) },
```

I think you should also replace all of those in your config and I think that will sort this out.

**Comment by datwaft** [comment]
I just tried with:

```lua
	{ key = "{", mods = "CMD", action = wezterm.action.SendString("\2p") },
	{ key = "{", mods = "SHIFT|CMD", action = wezterm.action.SendString("\2p") },
	{ key = "}", mods = "CMD", action = wezterm.action.SendString("\2n") },
	{ key = "}", mods = "SHIFT|CMD", action = wezterm.action.SendString("\2n") },
```

And it didn't work.

Also tried with [`Nop`](https://wezfurlong.org/wezterm/config/lua/keyassignment/Nop.html) and it also didn't work.

**Comment by datwaft** [comment]
```console
$ wezterm show-keys --lua | grep $'key = \'}\''
    { key = '}', mods = 'SUPER', action = act.SendString 'n' },
    { key = '}', mods = 'SHIFT|SUPER', action = act.SendString 'n' },
$ wezterm show-keys --lua | grep $'key = \'{\''
    { key = '{', mods = 'SUPER', action = act.SendString 'p' },
    { key = '{', mods = 'SHIFT|SUPER', action = act.SendString 'p' },
$ wezterm show-keys --lua | grep $'key = \'1\''
    { key = '1', mods = 'SHIFT|CTRL', action = act.ActivateTab(0) },
    { key = '1', mods = 'SUPER', action = act.SendString '1' },
```

Btw, there is an issue with how the keys are displayed in `show-keys --lua` as the `\2` escape code is not displayed but I already checked that it is being send with the `CMD+1` keybind:

```console
$ sed -n l
^B1
\0021$
```

I thought that could be the issue but it doesn't seem to be.

**Comment by wez** [comment]
This works:

```lua
	{ key = "[", mods = "SHIFT|CMD", action = wezterm.action.SendString("left") },
	{ key = "]", mods = "SHIFT|CMD", action = wezterm.action.SendString("right") },
	{ key = "{", mods = "SHIFT|CMD", action = wezterm.action.SendString("left") },
	{ key = "}", mods = "SHIFT|CMD", action = wezterm.action.SendString("right") },
	{ key = "{", mods = "CMD", action = wezterm.action.SendString("left") },
	{ key = "}", mods = "CMD", action = wezterm.action.SendString("right") },
```

what's up with all those variations? Those are all needed to cover the different slightly ambiguous ways to refer to those key presses.

If you (or a future reader) runs into something like this again, looking at the menubar to see what key is registered to the menu item will help nudge them in the right direction.
