### ISSUE TITLE
Text renders underneath bottom border until window resize.

### ISSUE THREAD

**Issue by davidspry** [wez/wezterm#3333]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230320-124340-559cb7b0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Text renders underneath the bottom border until the window is resized. It looks as though the bottom border isn't accounted for until a window-resize occurs.

Here's an example using borders on each side:
1. Prior to resizing the window (the cursor is underneath the bottom border):
![Screenshot 2023-03-23 at 7 00 35 pm](https://user-images.githubusercontent.com/45588554/227154334-7a743f02-0493-45a0-930d-5cdfd0970173.png)

2. After resizing the window:
![Screenshot 2023-03-23 at 7 00 45 pm](https://user-images.githubusercontent.com/45588554/227154313-217953cb-fbc3-4d3e-8fbc-6b1ada62bbfa.png)

Here's another example using only the bottom border:
1. Prior to resizing the window:
![Screenshot 2023-03-23 at 7 05 36 pm](https://user-images.githubusercontent.com/45588554/227155225-7be8a051-3148-4b8e-85ec-6f8f2a05138c.png)

2. After resizing the window:
![Screenshot 2023-03-23 at 7 05 39 pm](https://user-images.githubusercontent.com/45588554/227155236-9485a200-907c-43ab-99d0-1ef126a5ca89.png)

Here's a third example, using a minimal config (specifying only the border size, the border colour, and the window padding):
1. Prior to resizing the window:
![Screenshot 2023-03-23 at 7 13 00 pm](https://user-images.githubusercontent.com/45588554/227156746-3d8ab3b8-034d-471e-86b4-c2085338a1d6.png)

2. After resizing the window:
![Screenshot 2023-03-23 at 7 13 05 pm](https://user-images.githubusercontent.com/45588554/227156780-a0da6c63-4138-478b-af61-974e6ec36106.png)

### To Reproduce

The steps required to reproduce this are:

1. Specify a bottom border in the config file. This is the config that I used in the 'minimal' example above:

```lua
local wezterm = require 'wezterm'

return {
  window_frame = {
    border_left_width = '1cell',
    border_right_width = '1cell',
    border_bottom_height = '0.5cell',
    border_top_height = '0.5cell',
    
    border_left_color = '#444',
    border_right_color = '#444',
    border_bottom_color = '#444',
    border_top_color = '#444',
  },

  window_padding = {
    left = '1.5cell',
    right = '1.5cell',
    top = '0.5cell',
    bottom = '0.5cell',
  },
}
```

### Configuration

```lua
local wezterm = require 'wezterm'

return {
  window_frame = {
    border_left_width = '1cell',
    border_right_width = '1cell',
    border_bottom_height = '0.5cell',
    border_top_height = '0.5cell',
    
    border_left_color = '#444',
    border_right_color = '#444',
    border_bottom_color = '#444',
    border_top_color = '#444',
  },

  window_padding = {
    left = '1.5cell',
    right = '1.5cell',
    top = '0.5cell',
    bottom = '0.5cell',
  },
}
```

### Expected Behavior

I expected the bottom border to be accounted for when positioning the text (without needing to resize the window first).

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wez** [comment]
Thank you for the detailed report! It made it easy to understand and figure out!

**Comment by davidspry** [comment]
> Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

It works perfectly in the nightly build. Thanks!
