### ISSUE TITLE
Add action to quickly display a help overlay

### ISSUE THREAD

**Issue by alexruf** [wez/wezterm#3335]
Especially new users are often struggling to find the correct shortcut. It would be helpful to have an action that can be assigned to a key binding, which temporary brings up an overlay (similar to how the command palette is shown), that shows a cheat sheet of the currently effective key bindings.

By default, this could have some default shortcut assigned, like <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>?</kbd>.

**Comment by goyalyashpal** [comment]
umh, how about having different modes in the command palette itself?

inspired from vs code, where _typing_ `>` in prompt toggles command mode, `?` shows commands etc...

**Comment by alexruf** [comment]
> umh, how about having different modes in the command palette itself?
> 
> inspired from vs code, where _typing_ `>` in prompt toggles command mode, `?` shows commands etc...

Good idea. Didn't think of that. Would even be necessary to have different modes in the command palette, just showing the assigned shortcut for each command could also do the job.

**Comment by goyalyashpal** [comment]
> just showing the assigned shortcut for each command could also do the job.

> Another improvement for the palette could be to display hotkeys along side the results if they exist.
> \- @ icecreammatt at https://github.com/wez/wezterm/issues/1485#issuecomment-1407847073

**Comment by icecreammatt** [comment]
I started using Helix and Wezterm around the same time this year. A feature I love in Helix is the ability to trigger menus with hotkeys that then show all the other hotkeys for that action. Things like splitting panes, searching, copy mode could all benefit from this.

<img width="404" alt="Screen Shot 2023-03-24 at 10 32 50 PM" src="https://user-images.githubusercontent.com/1154569/227698423-aa765f98-de36-4c71-bad2-56e5eba7dac9.png">

An easy win though I think is to display the currently bound hotkey in the command pallet in search results.

**Comment by wez** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/117777/227701139-a6b2f720-b01d-409c-a5e2-1b851507ba7f.png">

Just pushed a first pass at showing the key assignments in the palette. This should be available in nightly builds in ~1 hour

**Comment by goyalyashpal** [comment]
> [img](https://user-images.githubusercontent.com/117777/227701139-a6b2f720-b01d-409c-a5e2-1b851507ba7f.png)
> \- @ wez at https://github.com/wez/wezterm/issues/3335#issuecomment-1483742034

hey, how about using shortcuts for "Shit" "Ctrl" "Alt" & "Opt" "Cmd" to save space?

**Comment by wez** [comment]
I tried using symbols but at the default font size for the palette, and even a bit larger, they render too small to be legible.
The emacs style S/C/M symbols are short, but there isn't a representation for Cmd/Super that is shorter than Cmd/Super.

I could potentially make the rendering for these symbols configurable, so if you've configured a large enough font size that the symbols might be more useful, then you could choose that.

**Comment by goyalyashpal** [comment]
yeah, the symbol for opt key `⌥` is indeed very small.. but the option for cmd seems to be quite big 🤔 : `⌘` <sup>[ref]</sup>

how common is "Super" key (the OS key right?) in wezterm?
one rendering can be: `⊞` - the windows one

😉  superset symbol: `⊃` (just kidding)


[ref]: https://bigtechquestion.com/2021/02/03/software/mac/how-do-i-type-the-mac-command-symbol-%E2%8C%98/


-----
P.S.:
found this awesome image for "Mac keyboard shortcuts symbol legend"

[<img src="https://i.pinimg.com/originals/ba/63/85/ba63854b2d8a9308c6b990849ffae06d.png" width=250px/>][ddg image]

[img link]: https://i.pinimg.com/originals/ba/63/85/ba63854b2d8a9308c6b990849ffae06d.png
[ddg image]: https://duckduckgo.com/?q=symbol+for+super+key+on+mac&iax=images&ia=images&iai=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Fba%2F63%2F85%2Fba63854b2d8a9308c6b990849ffae06d.png&t=vivaldi

**Comment by wez** [comment]
The commit I just pushed adds a config option to control this:

```lua
-- Super, Meta, Ctrl, Shift
config.ui_key_cap_rendering = 'UnixLong'

-- Super, M, C, S
config.ui_key_cap_rendering = 'Emacs'

-- Apple macOS style symbols
config.ui_key_cap_rendering = 'AppleSymbols'

-- Win, Alt, Ctrl, Shift
config.ui_key_cap_rendering = 'WindowsLong'

-- Like WindowsLong, but using a logo for the Win key
config.ui_key_cap_rendering = 'WindowsSymbols'
```

**Comment by goyalyashpal** [comment]
thanks a lot for the stable release. with command palette & shown shortcuts, i can finally use the panes, search and other features of wezterm which earlier i just couldn't remember & reinforce in memory

**Comment by goyalyashpal** [comment]
```console
$ wezterm --config ui_key_cap_rendering='Emacs'
ERROR  wezterm > runtime error: [string "--config ui_key_cap_rendering=Emacs"]:5: Emacs evaluated as nil. Check for missing quotes or other syntax issues
stack traceback:
        [C]: in ?
        [C]: in function 'error'
        [string "--config ui_key_cap_rendering=Emacs"]:5: in main chunk; terminating
```

i tried with appending `config.` as well, and also using 'AppleSymbols' instead of 'Emacs'

per the commit history for the release tag: [20230326-111934-3666303c], this commit is included in the release. so, something is wrong, either in my usage, or it's a bug i guess

[20230326-111934-3666303c]: https://github.com/wez/wezterm/commits/20230326-111934-3666303c

**Comment by wez** [comment]
As the error message suggests, you need to fix the quoting on the command line, because the shell tokenizer/parser has a stage called [Quote Removal](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_07) that strips out any unquoted quotes.

`wezterm --config "ui_key_cap_rendering='Emacs'"`
