### ISSUE TITLE
wezterm is quite slow to start

### ISSUE THREAD

**Issue by tuananh** [wez/wezterm#334]
using macOS (big sur).

wezterm is quite slow to start, in comparison to say, Terminal.app

**Comment by wez** [comment]
There's some discussion about this on #264

**Comment by wez** [comment]
Can you try a nightly build to see if this is still a concern?

**Comment by tuananh** [comment]
@wez it does feel faster. what was changed? I couldn't find it in the changelog. is it due to metal being used?

**Comment by wez** [comment]
This item in the changelog:

> macOS: we no longer use MetalANGLE to render the gui; it was short lived as macOS Big Sur now uses Metal in its CGL implementation. Support for using MetalANGLE is still present if the dylib is found on startup, but we no longer ship the dylib.

So we were using MetalANGLE to translate from OpenGL to Metal, but it wasn't as snappy as just using CGL (the Core Graphics OpenGL layer).  In Big Sur CGL now automatically translates to Metal in any case, so I just stopped shipping MetalANGLE with wezterm.
