### ISSUE TITLE
Issue while using Space Mono font in Windows 

### ISSUE THREAD

**Issue by Trid-collab** [wez/wezterm#3347]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

-

### WezTerm version

WezTerm-windows-20230323-214328-bc7acc18

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I trying to use the "Space Mono" font : I am getting following issue:

![image](https://user-images.githubusercontent.com/61322708/227469255-d5cb65e3-10bc-47dc-a90f-687056f533b9.png)

### To Reproduce

-

### Configuration

-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.font = wezterm.font 'Space Mono'
config.color_scheme = 'Alabaster'

-- and finally, return the configuration to wezterm
return config

### Expected Behavior

-

### Logs

---

### Anything else?

The problem doesn't occur while using other fonts like JetBrains Mono

**Comment by wez** [comment]
The font has slightly broken ligatures for `fi` that cause this. There are a handful of fonts with a similar issue.

You can disable the use of ligatures for that font using something like this:

```lua
config.font = wezterm.font {
    family = 'Space Mono',
    harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' },
}
```

See the bottom of https://wezfurlong.org/wezterm/config/lua/wezterm/font.html and the whole of https://wezfurlong.org/wezterm/config/font-shaping.html for more information about these font shaping parameters.

**Comment by Trid-collab** [comment]
Thank you. It worked
