### ISSUE TITLE
wezterm ssh does not remember host

### ISSUE THREAD

**Issue by stvhay** [wez/wezterm#3348]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230323-214328-bc7acc18

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

with both wezterm ssh and wezterm connect, host is not remembered and I have to reconfirm.

```
Using libssh-rs to connect to hays@st5ve.com:22
SSH-2.0-OpenSSH_8.4p1 Debian-5+deb11u1
SSH host st5ve.com:22 is not yet trusted.
Fingerprint: [redacted].
Trust and continue connecting?
Enter [y/n]>
```

### To Reproduce

Connect to host via wezterm ssh or wezterm connect.

### Configuration

```local wezterm = require 'wezterm'

local config = {}

if wezterm.config_builder then
    config = wezterm.config_builder()
end

config.keys = {
    -- Make Option-Left equivalent to Alt-b which many line editors interpret as backward-word
    { key="LeftArrow", mods="OPT", action=wezterm.action{SendString="\x1bb"} },
    -- Make Option-Right equivalent to Alt-f; forward-word
    { key="RightArrow", mods="OPT", action=wezterm.action{SendString="\x1bf"} },
}

config.font = wezterm.font 'Hack Nerd Font Mono'

config.color_scheme = 'Square'
config.color_scheme = 'lovelace'

config.ssh_domains = {
    {
        name = 'build-contabo',
        remote_address = 'xx.xx.xx.xx',
        username = 'hays',
    },
    {
        name = 'st5ve.com',
        remote_address = 'st5ve.com',
        username = 'hays',
    },
}

return config```

### Expected Behavior

Expect to remember the connection.

### Logs

No output

### Anything else?

I have an already-existing entry that seems fine, but the new entry is not getting remembered.

**Comment by wez** [comment]
Do you mean that there isn't an entry added to `~/.ssh/known_hosts`?
Updating that file is handled by the underlying `libssh` library.

Please take a look at the file for yourself and see if you can identify entries that it may have written for those hosts.

It can sometimes be helpful to delete those and try connecting again to see what happens; if you're up for trying that, I would suggest running `wezterm ssh -v st5ve.com` to have a more convenient way to directly see debug information about the connection attempt.

**Comment by stvhay** [comment]
```15:35:37.757  INFO   libssh::ssh_known_hosts_parse_line     > Failed to parse ssh-ed25519 key for entry: st5ve.com!```

looking at the file, it appears to be corrupted a bit. there are CR missing from many entries, and maybe OpenSSH can read this but I bet libssh can't.

Deleting the file fixes it. I'll file another bug if i can get to root cause.
