### ISSUE TITLE
hot key doesn't work reliably

### ISSUE THREAD

**Issue by tuananh** [wez/wezterm#335]
## Environment (please complete the following information):

 - OS: macOS big sur
 - Version: 20201031-154415-9614e117

## To Reproduce

```local wezterm = require 'wezterm'
return {
    font = wezterm.font_with_fallback({"Cascadia Code PL", "Operator Mono"},
                                      {bold = false}),
    font_size = 14.0,
    color_scheme = "ayu Light",
    hide_tab_bar_if_only_one_tab = false,
    disable_default_key_bindings = false,
    keys = {
        {key = "k", mods = "CMD", action = "ClearScrollback"},
        {key="w", mods="CMD",action=wezterm.action{CloseCurrentPane={ confirm=false}}},
	    {key="d", mods="CMD", action=wezterm.action{SplitVertical={ args={"top"}}}},
	    {key="d", mods="CMD|SHIFT", action=wezterm.action{SplitHorizontal={ args={"top"}}}}
    }
}

```

however, cmd+shift+d combo fails to work reliably. it works sometimes and most of the time, it doesn't

**Comment by wez** [comment]
Take shift out of the mods and uppercase the key like this:

`{key="D", mods="CMD",`

**Comment by tuananh** [comment]
@wez yeah it seems fine wih the hotkey now. however, when i do that, it will automatically launch `top` for no reason? do you know what did i do wrong here?

**Comment by tuananh** [comment]
Thank you!

**Comment by wez** [comment]
This part of the config:

```
SplitHorizontal={ args={"top"}}
```

tells wezterm to run `top` in the split.

I think you want just: `SplitHorizontal={}` if you want it to run the default program.  If it doesn't like the empty `{}` then you could try: `SplitHorizontal={Domain="CurrentPaneDomain"}`
