### ISSUE TITLE
Expose more of pane/tab management api in `wezterm cli`

### ISSUE THREAD

**Issue by cassepipe** [wez/wezterm#3352]
My wish is for `wezterm cli` to allow for complete pane/tab management on the command line.

Here are commands from the Lua API that needs be exposed to the CLI for that to be possible
```
CloseCurrentPane
CloseCurrentTab
ActivateTabRelative
ActivateTab
```
Proposals for the first three commands seems obvious, keeping the PascalCase to kebab-case translation already in place: 
```bash
wezterm cli close-current-pane
wezterm cli close-current-tab
wezterm cli activate-tab-relative (Next||Prev)
```

For the fourth command, ideally the following would meet users expectations
```bash
wezterm cli activate-tab 2 #Goes to tab number 2
```
But as far as I understand tabs ids are per session and don't match their actual order in the window so I don't know if it is feasible.

Not sure how useful would be a `wezterm cli activate-tab $real_tab_id` solution.

**Comment by cassepipe** [comment]
If there was a `enable_tab_cycling = false` option, we could imagine a dirty hack
```zsh
function gt()
{
    while wezterm cli activate-tab-relative "Prev"; do done

   repeat $1-1 wezterm cli activate-tab-relative "Next"
}
```

**Comment by wez** [comment]
The latest nightly has:

* https://wezfurlong.org/wezterm/cli/cli/activate-tab.html
* https://wezfurlong.org/wezterm/cli/cli/kill-pane.html
* https://wezfurlong.org/wezterm/cli/cli/activate-pane.html

There isn't a kill-tab operation defined in the mux at this time, so there isn't a CLI command for killing an entire tab right now either.  However, it is possible to script one using a combination of `kill-pane` and `list` if you really need it.

**Comment by wez** [comment]
It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by cassepipe** [comment]
Wow, can't believe how fast you implemented that. I'm in the process of testing it.

**Comment by cassepipe** [comment]
It works extremely and is a joy to use.
I have been dreaming about that workflow for some time.
Here are the aliases and the kill tab function I laboriously crafted :
```zsh
  #wezterm aliases (setopt histignorespace --> leading space prevents command going to history)
  # pane $direction
  alias pl="  wezterm cli activate-pane-direction left"
  alias pr="  wezterm cli activate-pane-direction right"
  alias pu="  wezterm cli activate-pane-direction up"
  alias pd="  wezterm cli activate-pane-direction down"
  alias pn="  wezterm cli activate-pane-direction next"
  alias pp="  wezterm cli activate-pane-direction previous"
  # new pane $direction
  alias npl=" wezterm cli split-pane --left"
  alias npr=" wezterm cli split-pane --right"
  alias npt=" wezterm cli split-pane --top"
  alias npb=" wezterm cli split-pane --bottom"
  # kill pane
  alias kp=" wezterm cli kill-pane"
  # new tab
  alias nt=" wezterm cli spawn"
  # tab $direction
  alias tl=" wezterm cli activate-tab --tab-relative -1"
  alias tr=" wezterm cli activate-tab --tab-relative 1"
  # tab $i
  alias t=" wezterm cli activate-tab --tab-index"
  # close tab
  function kt()
  {
      # Find the tab id the current pane belongs to
      local tab_id=$(nu -c '
          wezterm cli list --format=json |
              from json |
              where $it.pane_id == ($env.WEZTERM_PANE | into int) |
              get tab_id |
              first
          ' \
      )
      # Array of pane_ids to kill but the the current pane
      local to_kill=( $( nu -c "
          wezterm cli list --format=json |
              from json |
              where \$it.tab_id == $tab_id and \$it.pane_id != ( \$env.WEZTERM_PANE | into int) |
              get pane_id |
              to text
          " \
      ))

      # Kill them all but the current pane
      for pane in $to_kill
      do
          wezterm cli kill-pane --pane-id $pane
      done
      wezterm cli kill-pane
  }
  ```
It uses `nushell` because I like shiny new software and it's very nice to use but it is certainly not optimal.

Thanks again for making great software
