### ISSUE TITLE
Control Code ? Leakage

### ISSUE THREAD

**Issue by stvhay** [wez/wezterm#3357]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230323-214328-bc7acc18

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Some kind of ANSI control code ends up on my commandline when I log in

```λ ;672;1120t```

There is also some printing of codes prior to the commandline during login. Posted below.

### To Reproduce

Happens every time I log in.

### Configuration

local wezterm = require 'wezterm'

local config = {}

if wezterm.config_builder then
    config = wezterm.config_builder()
end

config.keys = {
    -- Make Option-Left equivalent to Alt-b which many line editors interpret as backward-word
    { key="LeftArrow", mods="OPT", action=wezterm.action{SendString="\x1bb"} },
    -- Make Option-Right equivalent to Alt-f; forward-word
    { key="RightArrow", mods="OPT", action=wezterm.action{SendString="\x1bf"} },
}

config.font = wezterm.font 'Hack Nerd Font Mono'

config.color_scheme = 'Square'
config.color_scheme = 'lovelace'

config.ssh_domains = {
    {
        name = 'build-contabo',
        remote_address = 'x.x.x.x',
        username = 'hays',
    },
    {
        name = 'st5ve.com',
        remote_address = 'st5ve.com',
        username = 'hays',
    },
}

return config

### Expected Behavior

log in with no extra characters on the screen

### Logs

No logs

### Anything else?

```
       _,met$$$$$gg.          hays@build-contabo
    ,g$$$$$$$$$$$$$$$P.       ------------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64
 ,$$P'              `$$$.     Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996)
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-21-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 20 hours, 20 mins
^[[4;672;1120t    ,    $$P                  Packages: 1402 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: zsh 5.8
 $$;      Y$b._   _,d$P'      Resolution: 1024x768
 Y$$.    `.`"Y$$$$P"'         Terminal: /dev/pts/2
 `$$b      "-.__              CPU: AMD EPYC 7282 (8) @ 2.794GHz
  `Y$$                        GPU: 00:02.0 Vendor 1234 Device 1111
   `Y$$.                      Memory: 428MiB / 30095MiB
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""


hays@build-contabo ~
λ ;672;1120t
```

**Comment by wez** [comment]
`^[[4;672;1120t` is a response from wezterm to a request (probably by your fetch program when it queries the screen resolution) for the terminal size in pixels.

It seems to me that whatever requested it didn't wait around long enough to read it, so the response shows up as the input to the shell when it starts up.

**Comment by stvhay** [comment]
The program doing this would be neofetch, and it seems to be OK with the screen resolution query, but does not like the --iterm2 .

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps; eg: run neofetch.
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by stvhay** [comment]
you should know that this made a lot of recordings when placed in my .zshrc file, and I typed "exit" about 10 times before giving up and ctrl-c on the client side...

<img width="727" alt="image" src="https://user-images.githubusercontent.com/1269071/227742468-3bdbc4c3-8689-478f-a24b-279488057183.png">

The files get bigger and bigger..  I'll attach the first few and then the biggest one. I think wezterm-record might be starting a new session so maybe this is expected behavior.

[wezterm-recording-SLUAuU.cast.txt](https://github.com/wez/wezterm/files/11070222/wezterm-recording-SLUAuU.cast.txt)

[wezterm-recording-nyNHVX.cast.txt](https://github.com/wez/wezterm/files/11070223/wezterm-recording-nyNHVX.cast.txt)

[wezterm-recording-enpRsH.cast.txt](https://github.com/wez/wezterm/files/11070227/wezterm-recording-enpRsH.cast.txt)

and the biggest

[wezterm-recording-XaqdUy.cast.txt](https://github.com/wez/wezterm/files/11070229/wezterm-recording-XaqdUy.cast.txt)

here's one if I just run wezterm-record once logged in with no attempt to put it in the .zshrc file

[wezterm-recording.cast.txt](https://github.com/wez/wezterm/files/11070250/wezterm-recording.cast.txt)

finally here is one where i am using `wezterm connect` vs `wezterm ssh`, which i don't get the extra characters on the screen.

[wezterm-recording-4S1ZrR.cast.txt](https://github.com/wez/wezterm/files/11070260/wezterm-recording-4S1ZrR.cast.txt)

**Comment by wez** [comment]
what version of neofetch is running on build-contabo ?

**Comment by wez** [comment]
re: recording from zshrc, I wouldn't put it there, because the recorder spawns a new shell, so you'll end up recursing forever :)

**Comment by wez** [comment]
Also, what parameters are you passing to neofetch?

**Comment by wez** [comment]
This is neofetch having a timeout that is too small when it probes the terminal size.

This line:

https://github.com/dylanaraps/neofetch/blob/master/neofetch#L4257

sets the timeout to 50ms which is close to the OS scheduling quantum.  I'd suggest bumping that up `0.1`:

```bash
    case $bash_version in
        4|5) IFS=';t' read -d t -t 0.1 -sra term_size ;;
        *)   IFS=';t' read -d t -t 1 -sra term_size ;;
    esac
```

**Comment by wez** [comment]
See:
* https://github.com/dylanaraps/neofetch/issues/2170

**Comment by stvhay** [comment]
- version 7.1.0
- noted
- `neofetch --iterm2 ~/debian.png`

I had to update it to 0.15 but it seems to have resolved. thank you.
