### ISSUE TITLE
Doesn't ask for microphone permission when needed

### ISSUE THREAD

**Issue by es183923** [wez/wezterm#3359]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230320-124340-559cb7b0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Basically the same problem as #2551, except for the microphone. It's also basically the same as #2242.
When launching something that needs to use the microphone, the terminal is supposed to ask for permission, launching a popup. But, WezTerm doesn't have the capability to launch this popup.

The fix is probably the same as the aforementioned two issues

Also, it might be possible to just stuff all the possible entitlements into the plist file.

### To Reproduce

open an app that uses the camera. I'm using cava as the example.

### Configuration

not relevant

### Expected Behavior

The popup asking for the microphone permission should appear.

**Comment by es183923** [comment]
Actually, could follow what VSCode did, and enable these entitlements only: 
```diff
 com.apple.security.automation.apple-events
 com.apple.security.device.camera
+com.apple.security.device.audio-input
```
https://github.com/microsoft/vscode/issues/119787#issuecomment-810484265

**Comment by es183923** [comment]
also fixes karlstav/cava#476

**Comment by wez** [comment]
> the terminal is supposed to ask for permission

I disagree: the terminal has nothing at all to do with this!

wezterm doesn't participate in the prompt, but macOS attributes the request of the app that you want to run with wezterm, which is only indirectly responsible for spawning it. wezterm doesn't care if you do or don't want to do that thing, and has no real say in the matter.

I'll add a couple more of these entitlements in to wezterm in any case, I just wanted to make it clear that this is a weirdness of macOS, and not wezterm's "fault".

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by es183923** [comment]
great! thanks for the extremely fast response!
