### ISSUE TITLE
Add setup variable to the actions

### ISSUE THREAD

**Issue by okuma10** [wez/wezterm#3361]
Hi, is it possible to add 
`hide_tab_bar_if_only_one_tab` or `window_decorations` as togglable actions, so we can map them to a hotkey?
I like the look achieved when the tab bar is hidden. It adds to a more zen like experience. However in the case of both these variables, when the tab bar is gone I cannot move the window. Would be nice to have them as togglable actions. So I can set the window to it's position and size and then turn off the tab bar. And later if I want to move that window again I'll just toggle the tab bar again and move the window.

**Comment by wez** [comment]
Take a look at the examples on https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html
You can define a key assignment that adjusts the configuration for the window using that technique.

**Comment by okuma10** [comment]
ok then is this setup correct?
![image](https://user-images.githubusercontent.com/44575116/227727387-7b75a32d-675d-4c31-86f6-f73477538e16.png)
![image](https://user-images.githubusercontent.com/44575116/227727400-56c6e9f6-a42e-4c7a-bcff-63c07fc3d213.png)

I'm using the suggested config builder setup.

**Comment by wez** [comment]
Note that I do not recommend removing `RESIZE` from window_decorations. See: https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html.

I would do something like:

```lua
wezterm.on('toggle-tab', function(window, pane)
  local overrides = window:get_config_overrides() or {}
  if not overrides.window_decorations then
    -- Disable the titlebar
    overrides.window_decorations = "RESIZE"
  else
    -- remove override and use globally configured value
    overrides.window_decorations = nil
  end
  window:set_config_overrides(overrides)
end)
```

**Comment by okuma10** [comment]
thanks @wez , it's working and toggling correctly now.
