### ISSUE TITLE
Update to latest JetBrains Mono Font

### ISSUE THREAD

**Issue by cd-a** [wez/wezterm#3362]
Love that the JetBrains Mono font is bundled.

I noticed it's not up to date though, they recently updated it, which you can notably see on the `J`, which doesn't have the slant anymore on top.

Bundled with wezterm:
<img width="143" alt="CleanShot 2023-03-25 at 11 54 36@2x" src="https://user-images.githubusercontent.com/75008413/227713010-3f1acb30-14e8-4bb1-aaa7-b42f5586b9de.png">

Latest from NerdFonts in kitty:
<img width="147" alt="CleanShot 2023-03-25 at 11 54 59@2x" src="https://user-images.githubusercontent.com/75008413/227713031-98c6e3e8-5d96-4a1c-bbb7-6970e5f9d0f2.png">

This is obviously low priority, just thought I'd mention it here.

**Comment by wez** [comment]
Done in 843b9e8fc4665d690fb5ff0c1e5c047e824b0ccf

This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wez** [comment]
... and 1531dd8471504fc027f35bd65584963ac0de9ea0

**Comment by cd-a** [comment]
Thanks @wez for the quick fix!

I checked the nightly, works like a charm. Very cool.
