### ISSUE TITLE
Freeze when closing tab with Cmd+W (zsh, macOS, ARM64)

### ISSUE THREAD

**Issue by bogem** [wez/wezterm#3365]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230325-111454-ca283c13

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

First of all, thanks a lot for WezTerm and your effort! I really like it!

Here is the issue:
When I have an open tab in a WezTerm window with multiple tabs for some time (3 minutes is enough) and tap Cmd+W, then the tab is frozen and does not close until I enter another key.

Further things I noticed:
* If you close the tab with clicking on `X` icon, it closes immediately as expected
* If there is only one tab in the window and you close it with Cmd+W, it it closes immediately as expected

### To Reproduce

1. Open WezTerm
2. Open multiple tabs
3. Wait for some time (3 minutes should be enough)
4. Close one of the tab with Cmd+W

### Configuration

wezterm.lua:
```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
-- Use config_builder for clearer error messages.
local config = wezterm.config_builder()

config.colors = {
  foreground = '#f1f1f1'
}
config.font = wezterm.font 'JetBrains Mono'
config.font_size = 14.0
config.initial_rows = 35
config.initial_cols = 90
config.keys = {
  {
    key = 'Backspace',
    mods = 'CMD',
    action = wezterm.action.SendKey {
      key = 'u',
      mods = 'CTRL'
    },
  },
  {
    key = 'Backspace',
    mods = 'OPT',
    action = wezterm.action.SendKey {
      key = 'Backspace',
      mods = 'CTRL'
    },
  },
}

return config
```

.zshrc:
```bash
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"

# Disable automatic updates
zstyle ':omz:update' mode disabled

ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  alias-finder
  common-aliases
  dirhistory
  gh
  git
  gitfast
  history-substring-search
  macos
  npm
  safe-paste
  vi-mode
  volta
  yarn
  zsh-autosuggestions
  zsh-syntax-highlighting
)

VI_MODE_SET_CURSOR=true

# Disable default "<<<" NORMAL mode indicator in right prompt.
export RPS1="%{$reset_color%}"

export EDITOR='vim'

ZSH_AUTOSUGGEST_STRATEGY=(history completion)

source $ZSH/oh-my-zsh.sh

eval "$(/opt/homebrew/bin/brew shellenv)"

### KEY BINDINGS ###

bindkey '^[[1;5C' autosuggest-execute # Ctrl+RightArrow to accept and execute autosugges
bindkey "^[[1;3D" backward-word # Option+LeftArrow for previous word
bindkey "^[[1;3C" forward-word # Option+RightArrow for next word
bindkey "^H" backward-delete-word # Option+Backspace to delete previous word in WezTerm
bindkey "^W" backward-delete-word # Option+Backspace to delete previous word in VSCode
bindkey "^[OD" vi-beginning-of-line # Cmd+LeftArrow to navigate to beginning of line in WezTerm
bindkey "^A" vi-beginning-of-line # Cmd+LeftArrow to navigate to beginning of line in VSCode
bindkey "^[OC" end-of-line # Cmd+RightArrow to navigate to end of line in WezTerm
bindkey "^E" end-of-line # Cmd+RightArrow to navigate to end of line in VSCode

### ALIASES ###

alias cat="bat --theme='Visual Studio Dark+' --style=grid,header"
alias fd="fd -E=node_modules -E=temp -E=.DS_Store --no-ignore-vcs"
alias rm="safe-rm"
alias sed="gsed"

alias ytu="yarn run test:unit"
alias ytw="yarn run test:watch"

alias npmRD="npm run dev"
alias npmtu="npm run test:unit"
alias npmtw="npm run test:watch"

alias gamend='git commit --amend --reuse-message=HEAD'
alias gd='git diff-index --quiet HEAD --; git diff --patch-with-stat'
alias gdstat='git diff --stat'
alias gmod='git merge origin/$(git_develop_branch)'

alias ghprvw="gh pr view --web"

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

alias reload="exec $SHELL -l"

### FUNCTIONS ###

# Create a new directory and enter it.
function mkd() {
	mkdir -p "$@" && cd "$_";
}

# Start an HTTP server from a directory, optionally specifying the port.
function server() {
	local port="${1:-8000}";
	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
	python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port";
}

# Run `dig` and display the most useful info.
function digga() {
	dig +nocmd "$1" any +multiline +noall +answer;
}

### IMPORTANT TO KEEP AT THE END ###

# ~/.extra can be used for other settings you don’t want to commit.
source ~/.extra.zsh
```

### Expected Behavior

I expect that a tab is closed immediately after I click on Cmd+W

### Logs

I didn't find any log in `$HOME/.local/share/wezterm` that could be relevant to this issue. I only have following:
```
20:31:39.192  INFO   wezterm_gui::termwindow > QuitApplication over here (window)
```

**Comment by bogem** [comment]
Here is the video of this issue:

https://user-images.githubusercontent.com/13235519/227738608-f1b850e2-7cb2-4852-8bb5-fe6243c1dc55.mp4

Unfortunately I can't set up any key logger, so let me explain what is happening here.
1. Right before I move my mouse in circles, I pressed Cmd+W. You can see that tab 1 was just frozen until I pressed 'a'
2. After I pressed 'a', the tab closed and focus moved to next tab
3. I reproduced the same with this tab and this issue was still there
4. But on the last tab I pressed Cmd+W and it immediately closed the window as I would expect

**Comment by bogem** [comment]
I saw similar issue (https://github.com/wez/wezterm/issues/558) and ran a trace log with `WEZTERM_LOG=trace wezterm 2> /tmp/wezterm.txt`. Here is the gist with this log: https://gist.githubusercontent.com/bogem/86a718bf96563f8d311f3c89b8917626/raw/a0a51073b45b8dd0de253eb28d83bb6780d93423/WezTerm%2520issue

The timeline of my interactions:
1. `21:06:46.516` - I pressed Cmd+W
2. `21:06:47.969` - I pressed Cmd+2
3. `21:06:49.362` - I pressed Cmd+W
4. `21:06:50.466` - I pressed Cmd+W

**Comment by wez** [comment]
I couldn't reproduce a hang, but I did notice that the window wasn't invalidated and repainted after the tab was closed.
The difference between pressing CMD-W and clicking the X button is that the former is sourced from the menubar on macOS, and didn't ensure that it invalidated the window after processing the event, whereas key and mouse events do do that.

I've pushed a commit that adds that invalidation, please try it out and let me know if this works for you.

I will take ~1 hour before that change is available to download in a nightly build.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by bogem** [comment]
I downloaded latest Nightly build (`wezterm 20230325-203323-59503034`) and I can't reproduce this issue anymore! Thank you for the fix 👍 

I still wonder why only me had this issue. It seems that this problem should be general for macos users 🤔
