### ISSUE TITLE
wezterm.gui.get_appearance():find 'Dark' not working on wayland

### ISSUE THREAD

**Issue by khuongduybui** [wez/wezterm#3375]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Zorin OS 16.2 Wayland

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I use the code snippet to determine which `color_scheme` to use, which works in Zorin X11 but not in Zorin Wayland.

### Configuration

```lua
local wezterm = require 'wezterm'
local gui = wezterm.gui
function scheme_for_appearance()
  local appearance = gui.get_appearance()
  if appearance:find 'Dark' then
    -- return "Ivory Dark (terminal.sexy)"
    -- return "nightfox"
    return "Catppuccin Mocha"
  else
    -- return "Ivory Light (terminal.sexy)"
    -- return "dayfox"
    return "Catppuccin Latte"
  end
end
```

**Comment by wez** [comment]
wezterm uses the [XDG Desktop Portal](https://flatpak.github.io/xdg-desktop-portal/) service to determine appearance.
If your environment doesn't support that, then wezterm cannot tell what the appearance should be under wayland, because there is no other defined specification for how to do that in a desktop-environment-agnostic manner.

When running under X11, wezterm can also determine the appearance using the [XSettings protocol](https://freedesktop.org/wiki/Specifications/xsettings-spec/).

XDG Desktop Portal is usually enabled on GNOME systems. Perhaps there is a package you need to install/enable for it to start up on Zorin?

**Comment by khuongduybui** [comment]
Is there a CLI tool that I can query the portal with to verify it's running or returning correct values?

**Comment by khuongduybui** [comment]
Is there a CLI tool that I can query the portal with to verify it's running or returning correct values?

**Comment by khuongduybui** [comment]
Is there a CLI tool that I can query the portal with to verify it's running or returning correct values?


Duy K. Bui,
+1 571 239 6002


On Sun, Mar 26, 2023 at 11:12 PM, Wez Furlong ***@***.******@***.***>> wrote:

wezterm uses the XDG Desktop Portal<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fflatpak.github.io%2Fxdg-desktop-portal%2F&data=05%7C01%7C%7C6e1da72e431340a432bf08db2e711124%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638154835376634129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Se4XBiUDldOAZt8Y%2FzheYe6dCcaq215aTeUiOmEvZJQ%3D&reserved=0> service to determine appearance.
If your environment doesn't support that, then wezterm cannot tell what the appearance should be under wayland, because there is no other defined specification for how to do that in a desktop-environment-agnostic manner.

When running under X11, wezterm can also determine the appearance using the XSettings protocol<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffreedesktop.org%2Fwiki%2FSpecifications%2Fxsettings-spec%2F&data=05%7C01%7C%7C6e1da72e431340a432bf08db2e711124%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638154835376634129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rSsLyc1E2GcBqD%2F9OptiP8za72AQx%2FGmROl1hcD6YKs%3D&reserved=0>.

XDG Desktop Portal is usually enabled on GNOME systems. Perhaps there is a package you need to install/enable for it to start up on Zorin?

**Comment by khuongduybui** [comment]
I no longer have access to a Zorin OS machine; my laptop had to be upgraded to Ubuntu 22.04 and I don't have time to test this is a VM right now. If you don't like leaving open issues hanging for a week or two you may close this.

**Comment by wez** [comment]
Let's close it; you're welcome to reopen (or file a new issue) if you're in a position to revisit this later.
