### ISSUE TITLE
Alt-Esc does not work

### ISSUE THREAD

**Issue by seqizz** [wez/wezterm#338]
## Describe the bug

> Hi there, this looks like a pretty solid terminal, thanks for the effort.

I realized one of my tmux keybindings (ALT-Esc) does not register under wezterm. It acts like it's ignoring the alt modifier key completely (since if I try it twice, another key binding of my shell, double-esc registers).

## Environment:

 - OS: NixOS Linux X11
 - Version: `wezterm 20201101-103216-403d002d-46-gddc4c1b6` (from a recent nightly appimage)

## To Reproduce

Should be reproducible with following lines on the tmux.conf:

```
unbind [
bind -n M-Escape copy-mode
```
And trying to press Alt-Esc while in tmux. Which works on other terminals like Konsole, Alacritty etc.

## Configuration

All of it:
```
local wezterm = require 'wezterm';
return {
    font = wezterm.font("Fira Code Light"),
    font_size = 14.0,
    dpi = 96.0,
    scrollback_lines = 20000,
    enable_tab_bar = false,
    harfbuzz_features = {"ss03", "ss08"},
    enable_wayland = false,
    color_scheme = "Afterglow",
}
```

## Session Recording

Attaching, but it is an input problem. But I am pressing Alt-Esc while recording so you can see what happens instead.
[20201123155335.zip](https://github.com/wez/wezterm/files/5584140/20201123155335.zip)

**Comment by bew** [comment]
I can reproduce, it's easily visible with `showkey -a`, pressing Alt-Esc sends `^[` only, instead of `^[^[`
