### ISSUE TITLE
cli activate-pane-direction in mux, from inside neovim, does not work reliably

### ISSUE THREAD

**Issue by lkhphuc** [wez/wezterm#3387]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230326-195053-5b511792

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The new feature from #2863 works great inside unix/ssh mux, with multiple panes.

However if the command was executed in a terminal inside neovim, it does not work reliably anymore. More specifically:
- `cli activate-pane-direction Up/Down/Left/Right` works only the first time (or two), such that it jump focus to a different wez's pane, after that it does not work anymore from inside neovim.
- `cli activate-pane-direction Prev` works every second time

### To Reproduce

1. wezterm connect unix
2. split panes in wezterm
3. Start vim/neovim in one pane
4. Start a terminal in vim/neovim
5. Execute `wezterm cli activate-pane-direction ...` might work once or twice

### Configuration

```lua
local wezterm = require("wezterm")

local config = {}
if wezterm.config_builder then
  config = wezterm.config_builder()
end

local function isViProcess(pane)
  local prog = pane:get_user_vars()["WEZTERM_PROG"]
  return prog:match("^nvim") or prog:match("^v")
end

local function conditionalActivatePane(window, pane, pane_direction, vim_direction)
  if isViProcess(pane) then
    window:perform_action(
      -- This should match the keybinds you set in Neovim.
      wezterm.action.SendKey({ key = vim_direction, mods = "CTRL" }),
      pane
    )
  else
    window:perform_action(wezterm.action.ActivatePaneDirection(pane_direction), pane)
  end
end

wezterm.on("ActivatePaneDirection-right", function(window, pane)
  conditionalActivatePane(window, pane, "Right", "l")
end)
wezterm.on("ActivatePaneDirection-left", function(window, pane)
  conditionalActivatePane(window, pane, "Left", "h")
end)
wezterm.on("ActivatePaneDirection-up", function(window, pane)
  conditionalActivatePane(window, pane, "Up", "k")
end)
wezterm.on("ActivatePaneDirection-down", function(window, pane)
  conditionalActivatePane(window, pane, "Down", "j")
end)

config.unix_domains = { { name = "unix" } }
config.keys = {
  { key = "h", mods = "CTRL", action = wezterm.action.EmitEvent("ActivatePaneDirection-left") },
  { key = "j", mods = "CTRL", action = wezterm.action.EmitEvent("ActivatePaneDirection-down") },
  { key = "k", mods = "CTRL", action = wezterm.action.EmitEvent("ActivatePaneDirection-up") },
  { key = "l", mods = "CTRL", action = wezterm.action.EmitEvent("ActivatePaneDirection-right") },
}
```

### Expected Behavior

Work just like without a mux domain.

### Anything else?
All commands work fine in other panes, that do not run vim.

Notably, `cli activate-pane --pand-id=x` works reliably every time inside neovim's terminal.

The reason for convoluted process of using terminal in neovim is just to emulate the usage of plugin for seamless neovim<->wezterm navigation like https://github.com/numToStr/Navigator.nvim 

Not using wezterm's mux, everything works beautifully though, including from inside neovim.

**Comment by wez** [comment]
Is `WEZTERM_PANE` set in the environment where you have problems? 
See: https://wezfurlong.org/wezterm/cli/cli/index.html#targeting-panes

If that environment variable isn't set accurately, then you will experience strange results if you don't explicitly pass the pane id to the CLI.

**Comment by lkhphuc** [comment]
Yes `WEZTERM_PANE` is set correctly in every pane. For all the terminal I spawned inside neovim, they all share the same WEZTERM_PANE, which is the one that was set before neovim is started.

I've been trying to make it reproducible but has not been able to so far. Sometime it works fine for the first 10 times or so, then it stop working, sometime it's not working when I use mapping from navigator.nvim plugin but works if I command `wezterm cli activate-pane-...` directly from terminal. Sometime neither options works.

This happens sporadically only when trying to get from pane with vim/neovim to other panes. The other direction from other panes to neovim's pane always works as far as I can tell.

**Comment by wez** [comment]
I'm not going to be able to make progress on this without a reliable reproduction scenario, and I'm not going to set up nvim and the other software you mentioned; I just don't have the time.

**Comment by craigmac** [comment]
Can't reproduce using your steps. I have been using wezterm/nvim combo with Navigator.nvim for awhile and haven't had this problem. Try using the exact suggested setup as explained [here](https://github.com/numToStr/Navigator.nvim/wiki/WezTerm-Integration).

**Comment by lkhphuc** [comment]
Thanks for checking out @craigmac. 
My only difference with the provided Navigator config is in the `isViProcess` function, which use `pane:get_foreground_process_name():find('n?vim')` that [does not work inside mux session](https://github.com/wez/wezterm/issues/3137#issuecomment-1437140268). This indeed works well for me too outside a mux session.

To get around that, I have setup [Shell Integration](https://wezfurlong.org/wezterm/shell-integration.html#user-vars) following the advice by Wez in the issue above. I have check that my `isViProcess` using WEZTERM_PROG variable can detect the currently running command correctly, even inside mux session.

**Comment by ian0371** [comment]
In my case, this bug occurs even without vim. How to reproduce:

- spawn a fresh `wezterm connect unix`
- split panes
- click the right pane and enter `wezterm cli activate-pane-direction left`; repeat a few times

As mentioned, `cli activate-pane --pand-id=x` will work fine, and `prev` direction will work every second time.

If this is only my case, you might wanna try spawning `vim` on the right and try typing `!wezterm cli activate-pane-direction left` a few times. Or, spawn a python REPL and try typing `import os; os.system("wezterm cli activate-pane-direction left")` a few times.

I get this message on the pane with `wezterm connect unix` running, which I'm not sure is relevant.

```
2023-03-31 00:11:13.199 wezterm-gui[67473:13772423] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
```

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by lkhphuc** [comment]
Thank a lot @wez. Everything works perfect now.
