### ISSUE TITLE
Window padding bottom doesn't takes effect when set below 1 cell

### ISSUE THREAD

**Issue by lucasrabiec** [wez/wezterm#3391]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230326-195053-5b511792

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Setting window_padding.bottom below 1cell (0.5cell on screenshot) or few pixels doesn't take effect. Setting it to 0 or above 1 works.

<img width="179" alt="CleanShot 2023-03-28 at 21 18 03@2x" src="https://user-images.githubusercontent.com/9741188/228345608-2220f345-dd7f-4741-82c3-0fdfeffac139.png">

### Configuration

```lua
config = {
	color_scheme = "Dracula (Official)",
	tab_bar_at_bottom = true,
	use_fancy_tab_bar = false,
	font = wezterm.font({
		family = "FiraCode Nerd Font",
	}),
	harfbuzz_features = { "calt=0", "clig=0", "liga=0" },
	front_end = "WebGpu",
	font_size = 12,
	window_padding = {
		left = 2,
		right = 2,
		top = 2,
		bottom = "0.5cell",
	},
	inactive_pane_hsb = {
		saturation = 0.7,
		brightness = 0.3,
	},
	keys = keys,
}
```

### Expected Behavior

Possibility to set bottom window_padding value between 0 and 1 (cell, px)

**Comment by wez** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/117777/228382528-8de38727-7916-456e-9ff0-1437ae831d8a.png">

Seems to work for me. When you set the tab bar at the bottom, the padding goes above the tab bar.
If you change the padding after the window is open, I recommend using CMD-+ to bump the font size, then CMD-0 to reset the dimensions to the default so that you can see the effect of the padding on the starting window size.

When you resize the window by pixels after it has opened, those pixels add to the padding until a whole cell is taken up and the terminal can be resized large to occupy that new space.

**Comment by lucasrabiec** [comment]
The hack with cmd-+ and cmd-0 works until I maximize the window. As I understand there will be always min 1 cell padding after resizing the window. Is that correct? Is there any option to preserve padding after resizing the window?

**Comment by lucasrabiec** [comment]
@wez even if I set bottom padding to 0 (window_decorations=`RESIZE`) the terminal always sets padding to 1

**Comment by wez** [comment]
I think the misunderstanding is this: wezterm doesn't snap the window size to conform to your padding when the window is sized externally, either by your hand, or by some other window management software on your system.

If you size the window, your padding will be the minimum padding used. wezterm has to add additional padding when the window size doesn't exactly conform to the geometry of the terminal + configured padding.

**Comment by lucasrabiec** [comment]
Why it was done like that? Is it a problem to always respect the padding which the user set? I'm just curious because I didn't face a similar issue in other terminals.

**Comment by wez** [comment]
It does respect the padding. The padding is a lower bound.
wezterm doesn't own the window size; the user and their window manager does; wezterm can ask for a specific size, but the window manager (eg: tiling, or the user maximizes the window, or full-screen's the window) may deny it, so we have to accommodate the window size not being precisely conforming to the config.

Why not simply try to snap the window during resize? Live resize is more complex than you might think, and it would be easy to end up with a janky experience.

So the situation right now is the the least effort, least bad implementation that I have time to produce and maintain in my spare time, for free, across 4 different windowing environments.

**Comment by lucasrabiec** [comment]
I appreciate and admire your work and I don't blame you. I understand the lack of time, I was just curious if there was a bigger idea behind it, a bug, or a lack of time because it is something more complicated. I get it. No offense.
