### ISSUE TITLE
wezterm.lua is ignored on MacOS

### ISSUE THREAD

**Issue by anta40** [wez/wezterm#3393]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm on MacOS Monterey, created a **wezterm.lua** on $HOME. 
The setting is pretty simple: to change to font and color theme. Wezterm ignored that.

If I rename the config into **.wezterm.lua**, like described in manual:
https://wezfurlong.org/wezterm/config/files.html

> The recommendation is to place your configuration file at $HOME/.wezterm.lua (%HOME%/.wezterm.lua on Windows) to get started.

Then I'll see this error:
```
runtime error: [string "/Users/andre/.wezterm.lua"]:17: attempt to index a nil
value (global 'contig')
stack traceback:
        [string "/Users/andre/.wezterm.lua"]:17: in main chunk
```

### Configuration

```
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.color_scheme = 'Fairy Floss (Gogh)'
contig.font = wezterm.font('JetBrains Mono', { weight = 'Bold', italic = true })
-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

The font displayed should be JetBrains Mono in bold and italic.
And the color theme should be [Fairy Floss](https://wezfurlong.org/wezterm/colorschemes/f/index.html), which is purple-ish

### Anything else?

![SCR-20230329-kwqe](https://user-images.githubusercontent.com/16976/228431665-51fc039b-d57d-4db6-b9a0-529d3d15e82e.png)

**Comment by wez** [comment]
You typo'd `config` as `contig`, which results in trying to index a `nil` value, as the error message clearly indicates
