### ISSUE TITLE
Different cursor style

### ISSUE THREAD

**Issue by pwsandoval** [wez/wezterm#3394]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With this configuration you would expect the cursor to always be a line and not a square. It works when the window is in focus:

![wez-1](https://user-images.githubusercontent.com/15174704/228437832-41a47669-9537-428a-b875-a491bcfb9bb5.png)

But when I remove the focus it becomes a rectangle/block and not a line, am I missing something?

![wez-2](https://user-images.githubusercontent.com/15174704/228437847-6b0405c5-48d7-48e6-9a4b-1e471786146d.png)

![wez-3](https://user-images.githubusercontent.com/15174704/228437853-53e3702b-300e-4a98-9093-7b3d2b955b54.png)

### Configuration

```lua
return {
   default_cursor_style = "BlinkingBar",
   cursor_thickness = "3"
}
```

### Expected Behavior

That the style is maintained even if the terminal window is not focused.

**Comment by wez** [comment]
The cursor changes to that style when the window is unfocused. That's how it works.
