### ISSUE TITLE
Revise hotkey defaults for Windows

### ISSUE THREAD

**Issue by wez** [wez/wezterm#34]
In particular, the tab related hotkeys don't work well on Windows systems because the use of the windows key as the modifier collides with higher precedence defaults in windows.

Suggestions:

* `WIN-\` for `SpawnTab`.  Rationale: `CTRL-T` would be an obvious choice, but would prevent sending that in eg: vim, which is bad. `\` is close to the `[` and `]` in qwerty keyboards and those keys have a default binding for navigating tabs
* `CTRL-0` for `ActivateTab`.  Don't have a solution in mind for this yet, but: `Win-0` (which would take you to the first tab) doesn't function on windows.  I'm not sure if we should use `CTRL-0` through `CTRL-9` for this in case it collides with something useful

**Comment by xiangpeng2008** [comment]
What's the solution on this ?
I may still have problem, for example `super + w` is the combination to close a pane, but `windows+w` won't do the job on Windows 10.

**Comment by wez** [comment]
Each of the default SUPER key assugnments also has a CTRL-SHIFT variant for Windows and Linux: 
https://wezfurlong.org/wezterm/config/default-keys.html

**Comment by mengyaoss77** [comment]
Ctrl+Shift+1 or 2  can't  switch to the tab but put the '1' / '@' on the screen.
