### ISSUE TITLE
Shell integration hooks registered multiple times

### ISSUE THREAD

**Issue by brandonchinn178** [wez/wezterm#3403]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Not bothering to test with nightly because no changes have been made to the shell-integration script in the [last 3 days](https://github.com/wez/wezterm/compare/20230326-111934-3666303c...b50a646b4fff9ffd3efad32b06b0f87d0dde8ae5).

In the course of debugging https://github.com/wez/wezterm/issues/3402, I noticed that the `__wezterm_osc7` hook runs multiple times every time I run `source ~/.zshrc`. This also exacerbates the problem in https://github.com/wez/wezterm/issues/3402, as it could take 2 seconds * number of times I ran `source ~/.zshrc` to show the prompt.

### Configuration

no config

**Comment by wez** [comment]
In general, shell startup files are not intended to be sourced multiple times. I wouldn't class this as a bug, but rather "probably don't do that!".  If you'd like to contribute a change to make it safe to source multiple times, then please go ahead!

**Comment by brandonchinn178** [comment]
I guess that's fair enough. Thanks!
