### ISSUE TITLE
Two panes are active if use ActivatePaneDirection twice on config

### ISSUE THREAD

**Issue by lucasvs** [wez/wezterm#3405]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

x11

### WezTerm version

20230329-223250-b50a646b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Two panes are active if use ActivatePaneDirection twice with this config:
```
wezterm.on('gui-startup', function(window)
  local tab, top_pane, window = mux.spawn_window(cmd or {})
  local gui_window = window:gui_window();
  local bottom_pane = top_pane:split { direction = 'Bottom' }
  local top_right_pane = top_pane:split { direction = 'Right' }
  local bottom_right_pane = bottom_pane:split { direction = 'Right' }
  gui_window:perform_action(wezterm.action.ActivatePaneDirection 'Up', top_pane)
  gui_window:perform_action(wezterm.action.AdjustPaneSize { 'Left', 40 }, top_right_pane)
  gui_window:perform_action(wezterm.action.ActivatePaneDirection 'Down', top_right_pane)
  gui_window:perform_action(wezterm.action.AdjustPaneSize { 'Left', 40 }, bottom_right_pane)
  gui_window:maximize()
end)
```
I removed the second ActivatePaneDirection and works normal, I think the problem is when you use two `ActivatePaneDirection` on gui-startup. the older version looks fine the problem is on `20230329-223250-b50a646b`

### Configuration

```
local wezterm = require 'wezterm'
local mux = wezterm.mux
local act = wezterm.action

wezterm.on('gui-startup', function(window)
  local tab, top_pane, window = mux.spawn_window(cmd or {})
  local gui_window = window:gui_window();
  local bottom_pane = top_pane:split { direction = 'Bottom' }
  local top_right_pane = top_pane:split { direction = 'Right' }
  local bottom_right_pane = bottom_pane:split { direction = 'Right' }
  gui_window:perform_action(wezterm.action.ActivatePaneDirection 'Up', top_pane)
  gui_window:perform_action(wezterm.action.AdjustPaneSize { 'Left', 40 }, top_right_pane)
  gui_window:perform_action(wezterm.action.ActivatePaneDirection 'Down', top_right_pane)
  gui_window:perform_action(wezterm.action.AdjustPaneSize { 'Left', 40 }, bottom_right_pane)
  gui_window:maximize()
end)

return {
    font = wezterm.font 'JetBrains Mono',
    enable_wayland = false, -- set true to test if wayland is ok
    warn_about_missing_glyphs = false,
    harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' },
    tab_bar_at_bottom = true,
    font_size = 10.5,
    use_fancy_tab_bar = false,
}

```

**Comment by lucasvs** [comment]
Thanks wez, i added `wezterm.sleep_ms(10)` before the second ActivatePaneDirection and works, i will try later with callbacks. you can close this issue if its a normal behavior.

**Comment by wez** [comment]
BTW, did you know that you can set the size at the time you split?

```lua
wezterm.on('gui-startup', function(window)
  local tab, top_pane, window = mux.spawn_window(cmd or {})
  local gui_window = window:gui_window();
  local bottom_pane = top_pane:split { direction = 'Bottom' }
  local top_right_pane = top_pane:split { direction = 'Right', size = 0.7 }
  local bottom_right_pane = bottom_pane:split { direction = 'Right', size = 0.7 }
  gui_window:maximize()
end)
```

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
