### ISSUE TITLE
key map not work

### ISSUE THREAD

**Issue by diucicd** [wez/wezterm#3407]
{key=";", mods="CMD", action=wezterm.action{SendString="// "}},
      {key="=", mods="CMD", action=wezterm.action{SendString=":="}},

the second config is now not working as before, version: latest nightly

**Comment by wez** [comment]
There's not enough information here for me to help you.

Please open a new issue using https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml with more information about your system, what you're trying to do and what the outcome is.
