### ISSUE TITLE
[Regression] icons from font awesome are not displayed

### ISSUE THREAD

**Issue by bew** [wez/wezterm#341]
## Describe the bug

Icons from fontawesome does not display anymore :confused: 

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: `20201101-103216-403d002d-52-g3bd8d8c8`

## To Reproduce

**fonts**:

Create a `fonts` dir next to the config, add the following fonts:
- iosevka term extended, from: https://github.com/be5invis/Iosevka/releases/tag/v3.6.2 (use the file `ttf/iosevka-term-extended.ttf` in the archive)
- font awesome 5 solid, from: https://fontawesome.com/download take the "free desktop version" (use the file `fontawesome-free-5.15.1-desktop/otfs/Font Awesome 5 Free-Solid-900.otf` from the archive)

**steps**:

Run `wezterm start -- sh -c "echo -n '    AB'; sleep 100"` with the config and observe.
(the icon does not render properly for me in the github interface, to copy-paste the icon, it's this one: https://fontawesome.com/icons/star)

## Configuration

```lua
local wezterm = require "wezterm"
return {
  font_size = 90.0, -- to see better :D
  font_dirs = {"fonts"},
  font = wezterm.font_with_fallback({
    "Iosevka Term Extended",
    "Font Awesome 5 Free Solid",
  })
}
```

## Screenshots

Using latest stable (20201101-103216-403d002d):
![wez-stable](https://user-images.githubusercontent.com/9730330/100019629-a76f2200-2dde-11eb-91f7-6c45c4ffb1d0.png)

Using nightly (20201101-103216-403d002d-52-g3bd8d8c8):
![wez-nightly](https://user-images.githubusercontent.com/9730330/100019669-b81f9800-2dde-11eb-833f-1bdda95be225.png)

**Comment by wez** [comment]
Thanks for reporting this!
