### ISSUE TITLE
Add CLI subcommand to determine mux layout, i.e. if a pane is zoomed, and whether a pane borders an edge

### ISSUE THREAD

**Issue by mrjones2014** [wez/wezterm#3413]
**Is your feature request related to a problem? Please describe.**
I'm the developer of [smart-splits.nvim](https://github.com/mrjones2014/smart-splits.nvim), and just added Wezterm multiplexer support. The issue is that the Wezterm integration is missing a couple features of the `tmux` integration because it uses some information that Wezterm CLI does not have a way to retrieve. The things I need are:

- A way to determine the current pane _from any pane_ via the CLI
- A way to determine if a pane is "zoomed" via the CLI

**Describe the solution you'd like**
A great way to solve it would be something like: `wezterm cli current-pane`, which could output similar to the way `wezterm cli list` outputs.

It would be nice if this also included something like `is_zoomed: true/false`. This can't be determined from the pane itself, because resizing a split pane adjusts the values of `$LINES` and `$COLUMNS`, so I can't use those to compare against the `size` field of `wezterm cli list` ouput.

**Describe alternatives you've considered**
Without the ability to determine this information via the CLI, I can't support the following two configs of `smart-splits.nvim`:

- `config.wrap_at_edge = false`
- `config.disable_multiplexer_nav_when_zoomed = true`

**Additional context**
I can't use the `$WEZTERM_PANE` environment variable because the Neovim checks run in a single pane, so when checking the pane from `smart-splits.nvim`, `$WEZTERM_PANE` will always be the pane that Neovim is running in.

If it's relevant, here's the code I'm recommending users use on the Wezterm config side to integrate with `smart-splits.nvim`:

```lua
local w = require('wezterm')

-- Equivalent to POSIX basename(3)
-- Given "/foo/bar" returns "bar"
-- Given "c:\\foo\\bar" returns "bar"
local function basename(s)
  return string.gsub(s, '(.*[/\\])(.*)', '%2')
end

local function is_vim(pane)
  local process_name = basename(pane:get_foreground_process_name())
  return process_name == 'nvim' or process_name == 'vim'
end

local direction_keys = {
  Left = 'h',
  Down = 'j',
  Up = 'k',
  Right = 'l',
  -- reverse lookup
  h = 'Left',
  j = 'Down',
  k = 'Up',
  l = 'Right',
}

local function split_nav(resize_or_move, key)
  return {
    key = key,
    mods = resize_or_move == 'resize' and 'META' or 'CTRL',
    action = w.action_callback(function(win, pane)
      if is_vim(pane) then
        -- pass the keys through to vim/nvim
        win:perform_action({
          SendKey = { key = key, mods = resize_or_move == 'resize' and 'META' or 'CTRL' },
        }, pane)
      else
        if resize_or_move == 'resize' then
          win:perform_action({ AdjustPaneSize = { direction_keys[key], 3 } }, pane)
        else
          win:perform_action({ ActivatePaneDirection = direction_keys[key] }, pane)
        end
      end
    end),
  }
end

return {
  keys = {
    -- move between split panes
    split_nav('move', 'h'),
    split_nav('move', 'j'),
    split_nav('move', 'k'),
    split_nav('move', 'l'),
    -- resize panes
    split_nav('resize', 'h'),
    split_nav('resize', 'j'),
    split_nav('resize', 'k'),
    split_nav('resize', 'l'),
  },
}
```

**Comment by wez** [comment]
The focused pane id is exposed as a per-client property which you can retrieve:

```console
$ wezterm cli list-clients
USER HOST      PID CONNECTED      IDLE      WORKSPACE FOCUS
wez  mba.lan 99666 370655.741603s 741.603ms default       0
```

or in json:

```console
$ wezterm cli list-clients --format=json
[
  {
    "username": "wez",
    "hostname": "mba.lan",
    "pid": 99666,
    "connection_elapsed": {
      "secs": 370676,
      "nanos": 281700000
    },
    "idle_time": {
      "secs": 0,
      "nanos": 281700000
    },
    "workspace": "default",
    "focused_pane_id": 0
  }
]
```

when multiple clients are connected, I would suggest sorting the list by idle time ascending, then taking the first result.

**Comment by mrjones2014** [comment]
Oh, not sure how I missed that, thanks!

**Comment by mrjones2014** [comment]
Is there a way to check if the pane is zoomed via the CLI?

**Comment by wez** [comment]
Not currently

**Comment by wez** [comment]
9b67a7148533b293bdf9807a9e3892ac58f3c022 adds `wezterm cli get-pane-direction`

**Comment by wez** [comment]
96f1585b103162b042e2593567884dfcbe32ca21 adds `is_active` and `is_zoomed` properties to `wezterm cli list --format=json` output.

Note that these are both scoped to the containing tab, so you can expect to see multiple panes with `is_active` when the user has multiple tabs open.  The currently focused pane is reported via `wezterm cli list-clients`

**Comment by mrjones2014** [comment]
Tested these as part of mrjones2014/smart-splits.nvim#53 and they work great. You can close this issue as resolved.

**Comment by mrjones2014** [comment]
Thanks a ton for all your help btw 🙏
