### ISSUE TITLE
Unpredictable keyboard latency when using mechanical keyboard to type faster than a human under wayland

### ISSUE THREAD

**Issue by adwaymalhotra** [wez/wezterm#3417]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland from HEAD. I don't think this is related to Wayland or Hyprland though.

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The behavior in Wezterm when using ZMK macros to print unicode characters is completely flaky. Sometimes the £ macro works as you'd expect, and sometimes it will output `🅰️`.

This bug is similar to the issues in ##2581.

### To Reproduce

I use macros in ZMK to input certain unicode symbols (mainly currency `₹, €, £`). 

A macro is defined as such in the ZMK config:     
`ZMK_MACRO(uc_gbp  , tap-ms=<40>; wait-ms=<40>; bindings = <&kp LC(LS(U))>, <&kp A &kp N3>, <&kp RET>;)`

The above snippet, when executed, will send Ctrl+Shift+U,A,3,RETURN.
The tap-ms governs the gap between the keys inside a <> block, and the wait-ms governs the gap between <> blocks. 

I've tried multiple combinations of the tap and wait times (between 0ms and 100ms). Unfortunately, the behavior in Wezterm is completely flaky. Sometimes the above macro works as you'd expect, and sometimes it will output `🅰️`.

This is only a problem in the unicode macros (e.g. a macro for :w,RETURN works flawlessly).

I believe it is a timing issue in the CharSelect overlay. It may work at a bigger tap/wait time, but I don't want to increase those in ZMK because the experience becomes progressively worse in other programs. E.g. when typing in foot, firefox and chrome, a 0ms setting for both tap and wait works, and instantaneously prints the desired character correctly.

Since I don't usually use the CharSelect menu, I would like an option where Wezterm doesn't spend cpu cycles displaying that, and reduces (if not eliminates) the need for wait/tap times.

### Configuration

i don't think there's any config option that pertains to this in my config.

### Expected Behavior

Wezterm should not require any sleeping between keys when typing macros using ZMK.

Wezterm should contain a setting to disable the unicode CharSelect menu when typing unicode chars.

**Comment by wez** [comment]
> Wezterm should contain a setting to disable the unicode CharSelect menu when typing unicode chars.

You can disable that key assignment using https://wezfurlong.org/wezterm/config/lua/keyassignment/DisableDefaultAssignment.html if you wish

**Comment by adwaymalhotra** [comment]
As far as I can tell, that also disables unicode input completely. Is there a different way to use ctrl+shift+u<unicode>?

**Comment by adwaymalhotra** [comment]
After some experimentation:

1. It works fine in Gnome if I disable the shortcut and have `use_ime=true`.
2. With Hyprland, I installed fcitx5 (I'm not really sure what it does tbh) and ran it on startup through an `exec-once` directive in my config. After this, I am able to input unicode symbols through the macros just fine.

I think we can close this bug.
