### ISSUE TITLE
Configuration to customize exit_behavior message

### ISSUE THREAD

**Issue by timlag1305** [wez/wezterm#3423]
**Is your feature request related to a problem? Please describe.**
I am using wezterm as a calendar pop-up for my `waybar` configuration. I invoke it as such: `wezterm --config exit_behavior=\"Hold\" start --class org.wezfurlong.wezterm.cal
 -- fish -c cal`

The issue with this is that this pops up more than just the calendar output, it also outputs the following text below the calendar. This is not what I want.

```
👍 Process "fish -c cal" in domain "local" completed.
This message is shown because exit_behavior="Hold"
```

**Describe the solution you'd like**
It would be nice if there was another configuration I could add to the invocation of wezterm to indicate either no message, or allowing me to customize the message to an empty string:

no_exit_hold_message=true
or 
exit_hold_message=""

**Describe alternatives you've considered**
Another alternative you shared in another thread is executing a sleep command. I think this is a reasonable workaround for now, but it does feel like a workaround.

**Additional context**
The issue is visualized below. The message pushes the `cal` output out of view.
![image](https://user-images.githubusercontent.com/247823/229306504-05c41ef6-20e4-44d3-bf9b-00812f5a949e.png)

**Comment by wez** [comment]
I'm thinking of something like:

```lua
config.exit_behavior_messaging = "Verbose" -- the current default explanation
config.exit_behavior_messaging = "Brief" -- omits the "This message is shown because ..." text
config.exit_behavior_messaging = "Terse" -- show something like `[done]` for success, else `[terminated:<error>]`
config.exit_behavior_messaging = "None" -- don't show anything
```

**Comment by wez** [comment]
This should be resolved now in `main`; see: https://wezfurlong.org/wezterm/config/lua/config/exit_behavior_messaging.html

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by timlag1305** [comment]
Thanks, I just built from main and this works exactly as expected with the new configuration option.
