### ISSUE TITLE
permute_any_mods output is not recognized by wezterm (in nightly)

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#3434]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

none

### WezTerm version

wezterm 20230402-190554-d25dbdd8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I get an error that implies wezterm doesn't understand the modifier that are produced by the `permute_any_mods` function

Error
> Configuration Error: Error converting lua value returned by script wezterm.lua to Config struct: error converting Lua table to config::config::Config (Error processing mouse_bindings.mods.mods (types: Config, Mouse, MouseEventTriggerMods) invalid modifier name Modifiers(NONE in Modifiers(NONE | SUPER))

### To Reproduce

Replace your config with the one below and launch wezterm

### Configuration

```lua
local wezterm = require 'wezterm'

return {
  mouse_bindings = {
    table.unpack(wezterm.permute_any_mods {
      event = { Down = { streak = 1, button = 'Middle' } },
      action = 'PastePrimarySelection',
    }),
  },
}

```

### Expected Behavior

permute_any_mods to work like before

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by eugenesvk** [comment]
Thanks for a very prompt fix!
