### ISSUE TITLE
Unicode selector for "music note" shows U+F886, a non-existent character

### ISSUE THREAD

**Issue by pragma-** [wez/wezterm#3436]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230319-131220-060d0f1e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I used the CTRL+SHIFT+U Unicode selector menu to search for a "music note" character. It offered U+F886 as seen in this screenshot:

![](https://i.imgur.com/WvFuvlV.png)

Unfortunately, while it appeared to display fine in wezterm, everyone else reported only seeing a box. Looking into it, it turns out that U+F886 is not a valid Unicode character. The Unicode block E000..F8FF is "Private Use Area" and doesn't contain valid characters.

### To Reproduce

CTRL+SHIFT+U to bring up Unicode selector UI. Search for "music". U+F886 shows up as "mdi_music_note", but is actually not a valid Unicode character.

### Configuration

no config

### Expected Behavior

Only valid Unicode characters should appear.

**Comment by wez** [comment]
That's a glyph from the Nerd Font symbols font.
https://wezfurlong.org/wezterm/config/lua/wezterm/nerdfonts.html

This isn't a bug, that's how the author of that font implemented that font.

**Comment by wez** [comment]
The feature is called [Character Selection Mode](https://wezfurlong.org/wezterm/config/lua/keyassignment/CharSelect.html)
