### ISSUE TITLE
Mux server not starting on latest master

### ISSUE THREAD

**Issue by cd-a** [wez/wezterm#3438]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230403-074702-718397d0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

On latest release version (20230326-111934-3666303c), mux server works.

On latest master, it does not spawn.

### To Reproduce

**Release version:**

https://user-images.githubusercontent.com/75008413/229567384-1df29a92-e62e-4840-b84b-942395184ffd.mp4

Still from the mux server spawning successfully: 
<img width="573" alt="release mux spawn" src="https://user-images.githubusercontent.com/75008413/229567465-ba085372-a314-4deb-b8fa-b90bac3499c6.png">

Process running in activity monitor:
<img width="147" alt="process running" src="https://user-images.githubusercontent.com/75008413/229567524-e20c2456-b1ca-4769-ba25-0c2f69940664.png">

**Latest master:**

Spawning with `cargo run --release --bin wezterm -- start`

https://user-images.githubusercontent.com/75008413/229567583-c9ac1abf-6261-48cf-944e-472dbe30df3c.mp4

### Configuration

This is the minimal config used that works on release, but not on master:

```lua
local wezterm = require 'wezterm'
local config = {}

config.unix_domains = {
  {
    name = 'unix',
  },
}

config.default_gui_startup_args = { 'connect', 'unix' }

return config
```

### Expected Behavior

Mux server spawns and connects

### Logs

No log file generated on startup. Only on release, where the mux server start is logged

**Comment by wez** [comment]
Are you sure it didn't start?
Please run `env | grep WEZTERM` in the spawned shell.
`WEZTERM_EXECUTABLE` will be the path to `wezterm-mux-server` if you are running in the mux.

**Comment by wez** [comment]
Oh, you're running `cargo run --release --bin wezterm -- start` which is the same as running `wezterm start`.  When you explicitly use the `start` subcommand, that takes precedence over `default_gui_startup_args`.

Just use `cargo run --release --bin wezterm` to start it up.

**Comment by cd-a** [comment]
Using `cargo run --release --bin wezterm` it did indeed start.

Didn't know about the `-- start` overriding the args, I was following the build from source instructions.

Thanks a lot wez for the quick help. And I'm stoked to report that now only does the mux server start up, the performance inside neovim is flying now. Amazing! I will add more info in the related issue.
