### ISSUE TITLE
record/replay: add options to get raw byte stream from the cast file

### ISSUE THREAD

**Issue by ECon65** [wez/wezterm#3446]
**Is your feature request related to a problem? Please describe.**
Possibility to either capture transcript using `wezterm record` without any metadata or to convert the resulting cast file to such a raw format - [see discussion #3210](https://github.com/wez/wezterm/discussions/3210)

**Describe the solution you'd like**
Having one of the options similar to asciinema :
-  `asciinema rec --raw` to record the output without metadata - [see link](https://asciinema.org/docs/usage#:~:text=%2D%2Draw%20%2D%20Save%20raw%20STDOUT%20output%2C%20without%20timing%20information%20or%20other%20metadata)
-  `asciinema cat existing.cast >output.txt` converts previously captured transcript into raw format without metadata - [see link](https://asciinema.org/docs/usage#:~:text=asciinema%20cat%20existing.cast%20%3Eoutput.txt%20gives%20the%20same%20result%20as%20recording%20via%20asciinema%20rec%20%2D%2Draw%20output.txt.)

**Comment by wez** [comment]
I added `wezterm replay --cat CASTFILE` to `main`.
I don't plan to add similar options to record, as I'd prefer to keep that "high fidelity" and leave it to `replay` to transform it.

**Comment by wez** [comment]
This should be resolved now in `main`, and is available in the latest nightly downloads.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
