### ISSUE TITLE
cli activate-pane-direction issues with ssh domain

### ISSUE THREAD

**Issue by joshuarubin** [wez/wezterm#3448]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230403-224617-8ddd0d98

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When connected to an ssh domain, my normal keycode relative pane activation works fine. However, if I use `wezterm cli activate-pane-direction <DIR>` it seems it can get confused under some circumstances and panes don't activate properly.

### To Reproduce

1. connect to an ssh domain
2. open 2 panes side by side
3. in the left pane, open `vim`
4. in `vim` execute `:!wezterm cli activate-pane-direction Right`
5. nothing happens
6. in `vim` execute `:!wezterm cli activate-pane-direction Left`
7. nothing happens
8. in `vim` execute `:!wezterm cli activate-pane-direction Right`
9. Right pane activates

### Configuration

no config

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by joshuarubin** [comment]
Confirmed working, thanks for addressing this.
