### ISSUE TITLE
Transparent tab bar background behavior is not the same when tab is split

### ISSUE THREAD

**Issue by ozwaldorf** [wez/wezterm#3450]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

20230306-150040-c3286f1b

### Describe the bug

When the old-style tab bar background is configured to be transparent, the behavior is different from a single buffer tab to a tab that's split.

One buffer in tab:
> The tab bar inherits the terminal background

![image](https://user-images.githubusercontent.com/8976745/229954282-8d224c63-91d3-4c50-903e-d9b0110a60a4.png)

Split buffers in tab:
> The tab bar does not inherit the terminal background

![image](https://user-images.githubusercontent.com/8976745/229954255-4ce849b1-6f97-4e7c-a521-41a8e8c39d55.png)

### To Reproduce

- Set colors.tab_bar.background to a fully transparent rgba value
- open 2 tabs, one with a single buffer, and another with 2 split buffers

### Configuration

```lua
return {
  use_fancy_tab_bar = false,
  window_background_opacity = 0.9,
  colors = {
    tab_bar = {
      background = 'rgba(0,0,0,0)'
    }
  }
}
```

### Expected Behavior

The behavior should be the same between a single buffer tab and a split tab.

This could be adjusted to:
- additive over the background color for both. When in a vsplit, the background could be 2 colors (one side tinted)
- Make the tab bar background nonadditive all the time. Whatever a user configures it to, it will always be

**Comment by wez** [comment]
Please include the smallest exact configuration file used to reproduce this

**Comment by ozwaldorf** [comment]
@wez fixed

**Comment by wez** [comment]
I went with option 2:

> Make the tab bar background nonadditive all the time. Whatever a user configures it to, it will always be

This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by ozwaldorf** [comment]
Hey @wez, thanks for the quick fix. I tested via compiling from source and working as expected now!

**Comment by wez** [comment]
Great!
