### ISSUE TITLE
Set wezterm.action to return `nil` if an object isn't available instead of throwing an error

### ISSUE THREAD

**Issue by miversen33** [wez/wezterm#3454]
Wezterm is a quick moving project with new features coming all the time. This is fantastic, but it makes it tough for those of us that want to use it cross platform with different versions of Wezterm installed. 

#### This is **not** an ask to slow down development, more so to provide us with a way to check if a feature exists (this might already be a thing but I couldn't find it when searching), as opposed to throwing an error.

A great example of this is the new [PromptInputLine](https://wezfurlong.org/wezterm/config/lua/keyassignment/PromptInputLine.html?h=prompt+input+line) feature that was added to nightly. Using this, I can now provide a way to rename your current workspace within Wezterm. That's awesome!

However I can't put that in my dotfiles because attempting to access this attribute on any wezterm instance that is _not_ on or after the nightly that is in throws an error 
```
callback error
stack traceback:
        [C]: in metamethod 'index'
        [string "repl"]:1: in main chunk
caused by: `PromptInputLine` is not a valid KeyAssignment variant.  There are too many alternatives to list here; consult the documentation!
```

There appears to be no way to "safeguard" against this kind of behavior in configurations. If that is the case, it means I can't experiment with new features because I can't protect my config against them exploding when used.

IMO, lua userdata objects should return `nil` if something is accessed that doesn't exist (as that is how lua tables are meant to work). That doesn't necessarily mean something can't also be logged, but it would provide the configuration an opportunity to `nil check` for a feature before use (or config compilation) and allow users to more safely play with new features that are released.

If something like this exists already, please point me in that direction so I can close this out :)

**Comment by miversen33** [comment]
Note, I suppose I _could_ use `pcall` to protect against an exploding function, but that feels dirty (like abusing try/catch as opposed to proactively checking if something can be done)

**Comment by wez** [comment]
The purpose of `wezterm.action.something` is to raise an error when you're trying to access something that isn't supported, because it can be difficult to nail down the source of an error otherwise, so having it return nil in that case is not super desirable.

You have a couple of options here, but none of them are especially ergonomic:

1. `pcall` is exactly the tool to use to protect a call and act on the error

```lua
function nil_on_error(closure)
   local status, result = pcall(closure)
   if status then
      return result
   end
end
```

2. You could use actual version gates:

```lua
function nil_until_vers(version, closure)
   if wezterm.version >= version then
      return closure()
   end
end

nil_until_vers('20230405-070049-9b67a714', function()
   return wezterm.action.PromptInputLine { ... }
end)
```

3. You can use the raw underlying shape of the data.  Open the debug overlay and type in:

```console
> wezterm.action.PromptInputLine { description = "hello", action = wezterm.action_callback(print) }
{
    "PromptInputLine": {
        "action": {
            "EmitEvent": "user-defined-0",
        },
        "description": "hello",
    },
}
```

Now in your config you can write it out like that:

```lua
config.keys = {
  ...
  -- Using raw syntax for backwards compatibility
  action = {PromptInputLine = {
        action = wezterm.action_callback(...),
        description = "my description"
  }},
}
```

**Comment by wez** [comment]
Sounds reasonable. I added `wezterm.has_action('PromptInputLine')` for this
