### ISSUE TITLE
Error when connecting to windows host via ssh_domain 

### ISSUE THREAD

**Issue by Drllap** [wez/wezterm#3455]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm on a Windows 10 machine and want to connect to my work machine (also a Windows 10) via:
`wezterm connect work`
but I get the following error:
```
>> wezterm connect work
16:43:27.510  INFO   wezterm_client::client > going to run wezterm cli --prefer-mux proxy
16:43:29.786  ERROR  wezterm_client::client > Error while decoding response pdu: decoding a PDU: decode_raw: Corrupt Response
16:43:29.792  ERROR  wezterm_gui            > Please install the same version of wezterm on both the client and server! The server reported error 'Error while decoding response pdu: decoding a PDU: decode_raw: Corrupt Response' while being asked for its version.  This likely means that the server is older than the client.
; terminating
16:43:29.792  ERROR  mux::connui            > while running ConnectionUI loop: recv_timeout: channel is empty and disconnected
16:43:29.793  ERROR  wezterm_client::client > wezterm cli --prefer-mux proxy: Exited with code 1
```

### Configuration

```
config.ssh_domains = {
  {
    name = 'work',
    remote_address = '<work ip>',
    username = '<work domain\\username>',
  }
}
```

### Logs

Debug Overlay
wezterm version: 20230326-111934-3666303c x86_64-pc-windows-msvc
Window Environment: Windows
OpenGL version: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 4.5.0 NVIDIA 516.94
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>

No logging info when running wezterm from command line

### Anything else?

I ran wezterm -V both locally and on the remote but got the same output.

I didn't try this on nightly, I don't have access to it and not sure how to.

I get the error message after I have supplied the password SSH window that appears

**Comment by Drllap** [comment]
Is there any configuration that I need to do on the remote host?

**Comment by wez** [comment]
The important thing there is `decode_raw: Corrupt Response`

On a unix system at least, if the output is being corrupted, the most likely cause is something in your shell startup that outputs something to stdout unconditionally before running the program you intend.  You can test for that kind of thing by doing something like `ssh workip wezterm --version`.  If you see more lines of output than just the `wezterm VERSION` output, then that is probably what is happening.

**Comment by Drllap** [comment]
You were correct, there was a print statement in my powershell profile on the remote.
But when I remove it I get the following error:
```
17:21:01.567  INFO   wezterm_client::client > going to run wezterm cli --prefer-mux proxy
17:21:02.822  ERROR  wezterm_client::client > ssh stderr: 17:19:21.782  WARN   wezterm_client::client > While connecting to Socket("C:\\Users\\palli\\.local/share/wezterm\\sock"): connecting to C:\Users\palli\.local/share/wezterm\sock.  Will try spawning the server.

17:21:02.824  ERROR  wezterm_client::client > ssh stderr: 17:19:21.783  WARN   wezterm_client::client > Running: "C:\\Program Files\\WezTerm\\wezterm-mux-server.exe" "--daemonize"

17:21:03.560  ERROR  wezterm_client::client > ssh stderr: 17:19:22.518  ERROR  wezterm                > (after spawning server) failed to connect to Socket("C:\\Users\\palli\\.local/share/wezterm\\sock"): connecting to C:\Users\palli\.local/share/wezterm\sock: No connection could be made because the target machine actively refused it. (os error 10061); terminating

17:21:03.587  ERROR  wezterm_client::client > wezterm cli --prefer-mux proxy: Exited with code 1
17:21:03.587  ERROR  wezterm_client::client > Error while decoding response pdu: decoding a PDU: reading PDU length: EOF while reading leb128 encoded value
17:21:03.590  ERROR  mux::connui            > while running ConnectionUI loop: recv_timeout: channel is empty and disconnected
17:21:03.590  ERROR  wezterm_gui            > Please install the same version of wezterm on both the client and server! The server reported error 'Error while decoding response pdu: decoding a PDU: reading PDU length: EOF while reading leb128 encoded value' while being asked for its version.  This likely means that the server is older than the client.
; terminating
```

It looks like it is trying to using UNIX socket on Windows? Is that going to work, is there some configuration that I need to do?

**Comment by wez** [comment]
Try running it again? I recently increased the timeout for that initial connection after spawning case (https://github.com/wez/wezterm/commit/ec85c243e9a31e9ab21f7abb48f395fb6e5380d7)

I would recommend updating to the nightly build on both the client and the server, as numerous fixes and improvements have been made to multiplexing support since the last release, including that fix. Use the nightly download button on https://wezfurlong.org/wezterm/install/windows.html to get it.

**Comment by Drllap** [comment]
Updated to nightly I get some error:

```
wezterm connect work
17:44:37.823  ERROR  wezterm_client::client > ssh stderr: 17:42:56.719  WARN   wezterm_client::client > While connecting to Socket("C:\\Users\\palli\\.local/share/wezterm\\sock"): connecting to C:\Users\palli\.local/share/wezterm\sock.  Will try spawning the server.

17:44:37.825  ERROR  wezterm_client::client > ssh stderr: 17:42:56.719  WARN   wezterm_client::client > Running: "C:\\Program Files\\WezTerm\\wezterm-mux-server.exe" "--daemonize"
```

But I guess I'm just getting these because I didn't have wezterm open on the remote after the update?

But anyway it appears to be working, I'm able to connect.

Thank you so much @wez, you are a legend
