### ISSUE TITLE
macos log spam when hiding/showing menubar

### ISSUE THREAD

**Issue by lrvdijk** [wez/wezterm#3463]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230402-190554-d25dbdd8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When connecting to a remote session using `wezterm connect`, I get the following stack traces:

<img width="2032" alt="Screenshot 2023-04-07 at 10 10 35 AM" src="https://user-images.githubusercontent.com/24530/230624251-74e8660d-20f6-4b30-b5b1-772d83858783.png">
<img width="2032" alt="Screenshot 2023-04-07 at 10 10 19 AM" src="https://user-images.githubusercontent.com/24530/230624260-79789f9a-9062-4aca-8bef-9578bbd29ada.png">

Everything works as expected though, so I'm not sure what the cause of these are?

### To Reproduce

On macOS, simply run `wezterm connect` to a server of interest.

### Configuration

```lua
return {
    { name = 'dsp-lrma-lvd', remote_address = '---', username = 'user',
      local_echo_threshold_ms = 1000 }
}
```

### Expected Behavior

No stack trace

**Comment by wez** [comment]
That's log spam generated on macOS that I've only seen when switching in and out of full screen mode (really, I think it correlates with the menubar being hidden).  AFAICT, it is harmless.  Annoying for sure!

It's possible that changing https://wezfurlong.org/wezterm/config/lua/config/native_macos_fullscreen_mode.html may influence this, but I haven't tried it.

I'd recommend using the command palette (CTRL-SHIFT-P) to initiate the connection from inside a running wezterm and then you won't see the log spam.

**Comment by lrvdijk** [comment]
Yea running it full screen so it's probably related to that. Tried with both native_macos.. to true and false, but in both cases the log spam happens.

Anyway, no high priority as everything works as expected, this report was just to let you know.

**Comment by lrvdijk** [comment]
I don't know which commit changed it, but since updating to the latest nightly this doesn't happen anymore!
