### ISSUE TITLE
`tab_bar_at_bottom` breaks active/inactive titlebar coloring

### ISSUE THREAD

**Issue by duclos-cavalcanti** [wez/wezterm#3464]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

AwesomeWM w/ Picom

### WezTerm version

20230405-172209-e3e9821c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using `tab_bar_at_bottom` w/ or w/o `use_fancy_tab_bar` breaks coloring of the titlebar's background and foreground.

I've seen a similar _bug_ [here](https://github.com/wez/wezterm/issues/3113), if it's simply the case of me not having the latest fixed build, I apologize and will consider building from source. 

However, currently I'm running the nightly 22.04 Ubuntu version following the instructions from the [downloads page](https://wezfurlong.org/wezterm/install/linux.html#installing-on-linux-via-flathub), which I assumed would have the corrected functionality. Again, apologize if that's a wrong presumption. 

Amazing tool BTW :) 

### Configuration

```lua 
return {
    window_frame = {
        active_titlebar_bg = '#333333',
        inactive_titlebar_bg = '#FFFFFF',
    },
    use_fancy_tab_bar = false,
    tab_bar_at_bottom  = true,
}
```

**Comment by wez** [comment]
Are you sure you're running X11? The `window_frame` settings don't affect the OS titlebar on X11.
I think there's some information missing here.
Can you describe in more detail what you mean by broken?
What are you trying, what is happening? What did you expect to happen?

**Comment by duclos-cavalcanti** [comment]
>Are you sure you're running X11? 

Yup, I'm pretty sure. This is a server `.iso` that I installed X11 and my tools on top of. So wayland is not even in the system at all.

>The window_frame settings don't affect the OS titlebar on X11.

I'm aware, I'm not speaking about the OS/WM titlebars, which in my case are managed by awesome.

>Can you describe in more detail what you mean by broken?
Sure! So, the colors are simply ignored _(from what I understand at least)_.

With this  config: 
```lua
local config_test = {
    -- ui
    use_fancy_tab_bar = false,
    tab_bar_at_bottom  = true,

    window_frame = {
        inactive_titlebar_bg = '#FF0000',
        active_titlebar_bg = '#FF0000',
    },
}

return config_test

````

I get this result:
![example](https://user-images.githubusercontent.com/62443350/230661225-8651838e-84c1-4258-b9b4-48d85c23a6ef.png)

I assumed that the titlebar background should become bright red given the config and these settings. It however does not. Have I misunderstood something?

**Comment by wez** [comment]
That's the tab bar rather than the title bar; when using the retro tab bar, the following options affect its appearance:
https://wezfurlong.org/wezterm/config/appearance.html#retro-tab-bar-appearance

**Comment by duclos-cavalcanti** [comment]
oh, my bad, youre right
