### ISSUE TITLE
can not distinguish keyup and keydown in kitty extended keyboard mode

### ISSUE THREAD

**Issue by unxed** [wez/wezterm#3473]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Muffin

### WezTerm version

wezterm 20230330-214948-d1c2257b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With kitty keyboard mode enabled (wezterm --config enable_kitty_keyboard=true --config disable_default_key_bindings=true), if I enable progressive enhancements flags with the value 15, on pressing F1 I see double "ESC OP" escape sequences in WezTerm. First is probably a keydown event, and second is probably keyup event. But there is no way do know what one is keydown and what one is keyup so my app just interprets them as double key down and behaves incorrectly.

kitty itself sends keydowns for F1 as ESC P and keyups for F1 as ESC[1;1:3P in the same mode.

Same with F2, F3, F4.

Can you please bring Wezterm behavior in kitty mode closer to kitty's behavior so keyups and keydowns can be distinguished? Thanks!

### To Reproduce

I use the following app to see what esc sequences are actually received from terminal on key presses. It enables kitty extended keyboard mode (flags are set to 15) and prints all received sequences:
```
#include <termios.h> 
#include <stdio.h> 
#include <unistd.h> 

int main()
{
    struct termios _ts = {};
	int _ts_r = tcgetattr(1, &_ts);
	if (_ts_r == 0) {
		struct termios ts_ne = _ts;
		//ts_ne.c_lflag &= ~(ECHO | ECHONL);
		cfmakeraw(&ts_ne);
		if (tcsetattr(1, TCSADRAIN, &ts_ne ) != 0) {
			perror("TTYBackend: tcsetattr");
		}
	}


	fprintf(stderr, "\x1b[?1049h");
	fprintf(stderr, "\x1b[?1000h");
	fprintf(stderr, "\x1b[?1001h");
	fprintf(stderr, "\x1b[?1002h");

    fprintf(stderr, "\x1b[=15u");

	for (;;) {
		char ch = 0;
		if (read(0, &ch, 1) <= 0) break;
		if (ch <= 0x20 || ch == 0x7f) {
			if (ch == 0x1b) fprintf(stderr, " ");
			fprintf(stderr, "\\x%02x", (unsigned int)(unsigned char)ch);
		} else {
			fprintf(stderr, "%c", ch);
		}
		if (ch == 0x0d) break;
    	if (ch == 0x0a) break;
	}
	fprintf(stderr, "\x1b[?1049l");
    fprintf(stderr, "\x1b[?1000l");
	fprintf(stderr, "\x1b[?1001l");
	fprintf(stderr, "\x1b[?1002l");

    fprintf(stderr, "\x1b[=0u");

    if (tcsetattr(1, TCSADRAIN, &_ts ) != 0) {
    	perror("TTYBackend: tcsetattr");
    }
}
```

### Configuration

no config

**Comment by wez** [comment]
Possibly a duplicate of:
* https://github.com/wez/wezterm/issues/3220

**Comment by unxed** [comment]
Probably its a different one. It is actual only for F1..F4 keys, and #3220 is about char keys as far as I can see.

FYI: I recently [added](https://github.com/elfmz/far2l/pull/1593) kitty's protocol support to the Linux port of FAR Manager so it can benefit from high fidelity keyboard input. In kitty everything works fine, but where are several bugs in WezTerm. Some of them probably could be solved on our side, but this one not.

**Comment by wez** [comment]
I opted to use the "longer" form for F1-F4, consistent with F5-F12.  That appears to be allowed by the protocol spec, and it's simpler to just use the same encoding for each of these keys.

**Comment by wez** [comment]
This should be resolved now in `main`.

I pushed a couple of fixed for kitty encoding:

https://github.com/wez/wezterm/commit/0540301121fc66854e261c0b0395951520dc63df
https://github.com/wez/wezterm/commit/8bb39bd6f3044d2ab42ef76d3667569cf0cfef43
https://github.com/wez/wezterm/commit/d239e65e64ee5f68264b50408d6d7850e8b8cc2e

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by unxed** [comment]
The problem is resolved. Thank you very much!
