### ISSUE TITLE
chars are sent instead of their codes in kitty keyboard mode if caps lock is on

### ISSUE THREAD

**Issue by unxed** [wez/wezterm#3474]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Muffin

### WezTerm version

wezterm 20230330-214948-d1c2257b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With kitty keyboard mode enabled (wezterm --config enable_kitty_keyboard=true --config disable_default_key_bindings=true), if I enable progressive enhancements flags with the value 15, if Caps Lock is on, escape sequences (press and release) for "a" key looks like:
```
\x1b[a:A:a;1u\x1b[a:A:a;3u
```
but it actually should be 
```
\x1b[97:65:97;1u\x1b[97:65:97;3u
```
as kitty does. Without Caps Lock everything works fine.

Sample app to inspect esc sequences generated on each key press/release event can be found in #3473

### Configuration

no config

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by unxed** [comment]
The problem is resolved. Thank you very much!

**Comment by unxed** [comment]
One minor note about Caps Lock: both Shift and Caps Lock should produce lowercase char. But now in WizTerm in kitty mode if Caps Lock is on and Shift is also held case of chars are still upper. Not a big problem, but I thought it might still be worth reporting it. Not sure if it worth a separate issue or not.

**Comment by wez** [comment]
Please file a separate issue for that so I can follow up on it, thanks!

**Comment by unxed** [comment]
👌 #3475
