### ISSUE TITLE
Caps Lock + Shift problem in kitty keyboard mode

### ISSUE THREAD

**Issue by unxed** [wez/wezterm#3475]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Muffin

### WezTerm version

wezterm 20230408-200110-397593be

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Currently in WizTerm in kitty keyboard mode if Caps Lock is on and Shift is also held case of chars is upper, but it should be lower. Not a big problem, but I thought it might still be worth reporting it. Not sure if it worth a separate issue or not.

I also performed the same test then kitty mode is off, and it looks like Shift state is also ignored if Caps Lock is on. Even in classic input mode.

### To Reproduce

Open WizTerm, ensure Caps Lock is on, hold Shift and press and character key. Also try with is kitty enhanced keyboard mode, a sample app that enables kitty mode and shows terminal escape sequences on each key press/release is available in #3473 

### Configuration

no config

### Expected Behavior

If Shift key is held then Caps Lock is on, case of chars should be lower.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by unxed** [comment]
Not reproduces any more. Thanks a lot!
