### ISSUE TITLE
modifier key press/release generate no events in kitty ehanced mode

### ISSUE THREAD

**Issue by unxed** [wez/wezterm#3476]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Muffin

### WezTerm version

wezterm 20230408-200110-397593be

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Pressing Ctrl key in kitty keyboard mode (with flags set to 15) should generate `\x1b[57442u` and key release should generate `\x1b[57442;1:3u` — as it works in kitty itselft. In WezTerm there is no reaction on separate Ctrl key presses/releases.

Same issue with Shift, Alt and Win (Super) keys.

Please remember that left and right modifier keys should generate different codes in kitty mode. For example, 57442 for left Ctrl and 57448 for right Ctrl.

### To Reproduce

Sample test app from #3473 may be used to view escape sequences generated in terminal on key press/release event. Run it under WezTerm and press Ctrl, Shift, Alt, Win (Super) keys separately.

### Configuration

no config

### Expected Behavior

Modifier key press/release should generate their on escape sequences in kitty mode.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by unxed** [comment]
Now fixed. Thanks!
