### ISSUE TITLE
numpad misbehavior in kitty keyboard mode

### ISSUE THREAD

**Issue by unxed** [wez/wezterm#3478]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Muffin

### WezTerm version

wezterm 20230408-200110-397593be

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Some keys work differently from mainline kitty in kitty keyboard mode (with flags set to 15). For example, Numpad "5" key send no events at all if NumLock is off, and sends `\x1b53;1u` if NumLock is on. Kittys behavior for comparation: `\x1b[E` with NumLock off and `\x1b[57404;129u` with NumLock on. Same with key release events. Behavior of other numpad keys (other digits, `*`, etc) also differs. Another example: numpad `*` sends `\x1b[57411;129u` in kitty and `\x1b[41;1u` in WezTerm.

### To Reproduce

Run test app from #3473 in WezTerm and try pressing all numpad keys both with on and off state of NumLock. Compare results with mainline kitty's behavior.

### Configuration

no config

### Expected Behavior

Escape sequences should be the same across different kitty's protocol implementations if mode flags are set to the same value (15 in our case).

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by unxed** [comment]
Most of numpad numeric keys are now working as I expected, thanks!

Still were are problems with `5`, `/`, `*`, `-` and `+` numpad keys.

In **kitty**, progressive enhancement flags 15, **NumLock On**, whose keys generate:
```
\x1b[57404;129u \x1b[57404;129:3u
\x1b[57410;129u \x1b[57410;129:3u
\x1b[57410;129u \x1b[57410;129:3u
\x1b[57411;129u \x1b[57411;129:3u
\x1b[57412;129u \x1b[57412;129:3u
```

In **kitty**, progressive enhancement flags 15, **NumLock Off**, whose keys generate:
```
\x1b[E \x1b[1;1:3E
\x1b[57410u \x1b[57410;1:3u
\x1b[57410u \x1b[57410;1:3u
\x1b[57411u \x1b[57411;1:3u
\x1b[57412u \x1b[57412;1:3u
```

In **WezTerm**, progressive enhancement flags 15, **NumLock On**, whose keys generate:
```
\x1b[53;129u \x1b[53;129:3u
\x1b[47;129u \x1b[47;129:3u
\x1b[42;129u \x1b[42;129:3u
\x1b[45;129u \x1b[45;129:3u
\x1b[43;129u \x1b[43;129:3u
```

In **WezTerm**, progressive enhancement flags 15, **NumLock Off**, whose keys generate:
```
\x1b[57427;1u \x1b[57410;1:3u
\x1b[47;1u \x1b[47;1:3u
\x1b[42;1u \x1b[42;1:3u
\x1b[45;1u \x1b[45;1:3u
\x1b[43;1u \x1b[43;1:3u
```

**Comment by wez** [comment]
I think this is better now in `main`.
Note that `5` is always encoded in the `57427 u` form to avoid a frustrating special case. This appears to be OK based on https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions although there is shows `57427 ~` which I assume to be a typo.

**Comment by unxed** [comment]
Reported possible typo to kitty. Maintaining spec quality is important thing.
https://github.com/kovidgoyal/kitty/issues/6172

Waiting for nightly package to rebuild.

**Comment by unxed** [comment]
Now all listed keys behave exactly as required in farl. Thank you very much!

**Comment by unxed** [comment]
About potential typo in kitty. Kovid Goyal replied:

> It's not a typo. If you look at the table carefully, you will notice
that all keys that have a legacy letter encoding have an alternate
encoding with CSI ~

> This was done because there already exist terminals that use these forms
for these keys, so using the same encoding for basic events in the kitty
protocol allows programs that support these encodings to work
automatically.

**Comment by wez** [comment]
So, is the wezterm behavior wrong?
Is the behavior in your app wrong for recognizing it? :-/

**Comment by wez** [comment]
I've updated `main` to make numpad 5 behave (more?) like kitty

**Comment by unxed** [comment]
Now everything is all right. Thank you!
