### ISSUE TITLE
alternate key reporting feature of kitty keyboard protocol not working as expected

### ISSUE THREAD

**Issue by unxed** [wez/wezterm#3479]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Muffin

### WezTerm version

wezterm 20230408-200110-397593be

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Kitty's `alternate key reporting` feature allows us to implement hotkeys working in keyboard layout independent way. Unfortunately, WezTerm is currently unable to send corresponding English (`base layout` as it is called in kitty's spec) letters for Ctrl+Cyrillic_letter or Alt+Cyrillic_letter keystrokes. For example, `Ctrl`+`ф` (the same key as `a` in Russian keyboard layout).
In kitty (mode flags 15):
`\x1b[1092::97;133u` Ctrl+ф press
`\x1b[1092:1060:97;134u` Ctrl+Shift+ф press
1092 is unicode char for `ф`, 1060 is its shifted version `Ф`, and 97 is `base layout` char `a`.
In WezTerm:
`\x1b[1092;5u` Ctrl+ф press
`\x1b[1060;6u` Ctrl+Shift+ф press

Also, as you can see, WezTerm does not follow spec here which says what unicode key (first number) should always be in lower case, so `\x1b[1060;6u` actually should be `\x1b[1092:1060;6u`, and with base layout char reporting — `\x1b[1092:1060:97;6u`.

And also, as you can see, WezTerm ignores NumLock modifier state that should increase last number by 128 (Caps Lock is also ignored).

### To Reproduce

Sample test app from #3473 may be used to view escape sequences generated in terminal on key press/release event. Install Russian keyboard layout system wide, run this app under WezTerm, switch to Russian layout and try pressing Ctrl with `a`/`ф` key (both together with shift and without it). Compare generated escape sequences with mainline kitty behavior. Also try this with Alt+`a`/`ф` and Win+`a`/`ф` key combinations.

### Configuration

no config

### Expected Behavior

Generated escape sequences should be consistent with the ones generated by mainline kitty for the same key events.

**Comment by unxed** [comment]
Getting such "base layout key" on Unix-like systems is not an intuitive task as English keyboard layout may be even not installed in system. I recently solved the same problem for wxWidgets cross platform UI toolkit. You may look at this [commit](https://github.com/wxWidgets/wxWidgets/commit/2c0f6a2aa0c8d0650d1f856aa279ce7495925c17) as a reference, hope it helps.

**Comment by wez** [comment]
This should be working now in `main`, with a caveat: un-shifting punctuation such as `!` -> `1` currently always assumes a US keyboard layout.  That needs some additional plumbing on the various systems to handle correctly.

**Comment by unxed** [comment]
Works as I expected, thanks a lot!
