### ISSUE TITLE
256 color palette is darker than most terminals

### ISSUE THREAD

**Issue by bew** [wez/wezterm#348]
This is not a full bug report, but I wanted to make an issue for it, so we don't forget about it!

There has been some discussion on gitter about it (with screenshots):
https://gitter.im/wezterm/Lobby?at=5edd5eec2c49c45f5acb9a10
and
https://gitter.im/wezterm/Lobby?at=5eea33125833b0624bd5bb87

Some screenshots of the differences:

(from me, left: wezterm, right: urxvt, the colors are more saturated on wezterm)
![image](https://user-images.githubusercontent.com/9730330/100028995-844d6e00-2df0-11eb-8dae-2b7793a83c18.png)

/cc @dbdr

**Comment by wez** [comment]
@bew: could you take a look at this in the nightly builds when you have a chance?
