### ISSUE TITLE
kitty's "Report associated text" mode not working

### ISSUE THREAD

**Issue by unxed** [wez/wezterm#3484]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Muffin

### WezTerm version

wezterm 20230409-122830-f4995511

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

One of so called progressive enhancements of kitty's keyboard protocol is "Report associated text" mode (flag 0b10000 or 16). I can't manage to get it work in WezTerm. For example, if I enable kitty keyboard mode with flags 31 (all flags enabled), I see the following on key press of Russian `ф` key (same key as latin `a`) in kitty:
```
\x1b[1092::97;129;1092u \x1b[1092::97;129:3u
```
"1092u" here is text-as-codepoints value as described in spec:
```
CSI unicode-key-code:alternate-key-codes ; modifiers:event-type ; text-as-codepoints u
```

But in WezTerm in the same mode 31 for the same key I get:
```
\x1b[1092;129u \x1b[1092;129:3u
```

So there are two problems:
1. text-as-codepoints value is empty
2. "shifted key" and "base layout key" fields are empty (that issue is reported as #3479)

### To Reproduce

Use test app from #3473. Modify its source code to enable mode 31 instead of mode 15:
```
    fprintf(stderr, "\x1b[=15u");
```
should be changed to
```
    fprintf(stderr, "\x1b[=31u");
```

Open it in WezTerm, press some character keys in different keyboard layouts, and compare app output with what kitty does in the same conditions.

### Configuration

no config

### Expected Behavior

Generated esc sequences should be the same as in kitty for the same keys in the same mode.

**Comment by wez** [comment]
I think this is resolved in `main`, please give it a try and let me know!

**Comment by unxed** [comment]
You are right, thanks! Closing.
