### ISSUE TITLE
Should implement cell by cell resizing

### ISSUE THREAD

**Issue by rfc1036** [wez/wezterm#3496]
**Is your feature request related to a problem? Please describe.**

When resizing a rezterm window (on Linux with X11 and fvwm) it is resized pixel by pixel. The effect is that it is very hard to precisely match the cell size and there will be a black area between the last cell and the edge of the window.

**Describe the solution you'd like**

With terminals like xterm and gnome-terminal the windows are resized cell by cell.

**Comment by rfc1036** [comment]
Yes, I have just found it but it does not work for me. My test minimal config file is:

```
local wezterm = require 'wezterm'
local config = {}
if wezterm.config_builder then
  config = wezterm.config_builder()
end
config.use_resize_increments = true
return config
```

**Comment by wez** [comment]
This was improved in a recent release
