### ISSUE TITLE
The maximize button function on Windows 11 does not meet expectations.

### ISSUE THREAD

**Issue by vagreargnatry** [wez/wezterm#3499]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230410-204717-fa0f538d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I click the maximize button, a floating window appears in Windows 11, but the terminal window does not maximize. At this point, when I move the mouse up and down, the text inside the terminal is selected.
In addition, when I double-click the title bar, the terminal window can be maximized/restored.

### To Reproduce

Click the maximize button in the upper right corner.

### Configuration

no config

### Expected Behavior

After clicking the maximize button in the upper right corner, the terminal window maximizes.

### Logs

Debug Overlay
wezterm version: 20230410-204717-fa0f538d x86_64-pc-windows-msvc
Window Environment: Windows
OpenGL version: Intel(R) UHD Graphics 630 4.5.0 - Build 27.20.100.8476
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

### Anything else?

When hovering over the maximize button and when clicking the maximize button.
![1](https://user-images.githubusercontent.com/104709852/231083795-2293c8dd-20b6-41e2-be67-9d74506996c1.png)
After clicking the maximize button, when the mouse moves downward, some text is selected. In addition, the window does not maximize.
![2](https://user-images.githubusercontent.com/104709852/231083802-6a839718-c11d-4f5c-bead-4c137bde693a.png)

**Comment by netherstar** [comment]
i have same issue

**Comment by scottmcnab** [comment]
I can confirm having this same issue with the 20230408-112425-69ae8472 build.

Reverting to the previous version I had installed (20230320-124340-559cb7b0) does not exhibit this behaviour (i.e. the maximise button works as expected).

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
