### ISSUE TITLE
Improve hyperlink detection when using tmux

### ISSUE THREAD

**Issue by jonashaag** [wez/wezterm#3500]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If there is a hyperlink that's too long for a single line, wezterm will detect the end of the hyperlink as the end of the line, even though the hyperlink continues on the next line. Note that this is inside a tmux session.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/175722/231153243-f800e6a8-a024-4535-8b67-b3a0ee84e8aa.png">

<img width="908" alt="image" src="https://user-images.githubusercontent.com/175722/231153640-5853cc0c-8ece-4f7d-91fd-06d1219cf63a.png">

### Configuration

no config

**Comment by wez** [comment]
wezterm matches by logical line only. In this scenario, tmux (possibly as editorialized by the Windows conpty layer) is outputting two distinct, unrelated physical lines, so it will not match.

**Comment by jonashaag** [comment]
I understand that! Just letting you know that it works differently in other terminal emulators.
