### ISSUE TITLE
Exiting search mode doesn't leave the currently selected text selected, scrolls back to prompt

### ISSUE THREAD

**Issue by LeszekSwirski** [wez/wezterm#3502]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

20230408-112425-69ae8472 / nightly: 20230410-204717-fa0f538d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

According to https://wezfurlong.org/wezterm/scrollback.html#searching-the-scrollback, exiting search mode with Escape should leave the scrollback scrolled to the selected text. However, since search mode became a facet of copy mode, Escape performs `act.CopyMode 'Close'`, which scrolls back to the prompt, and there's no `Close` equivalent which leaves the scrollback alone.

Search mode was broken on nightly so I didn't confirm there.

### To Reproduce

* Have text out of view in scroll back
* Search it with search mode (ctrl-shift-F)
* Exit search mode (esc)

### Configuration

no config

### Expected Behavior

Scrollback should stay scrolled.

**Comment by aorith** [comment]
Testing this with an empty config (Linux X11):

Works:
* 20220408-101518-b908e2dd

Doesn't work:
* 20220624-141144-bd1b7c5d
* 20220807-113146-c2fee766
* 20220903-194523-3bb1ed61
* 20220905-102802-7d4b8249

**Comment by LeszekSwirski** [comment]
That lines up with search mode being merged into copy mode (https://github.com/wez/wezterm/commit/2710cefb3e79bda07e86d91c27225bb0586ac0d5, May 5 2022).

**Comment by LeszekSwirski** [comment]
Looking at that commit, search mode's [close method](https://github.com/wez/wezterm/commit/2710cefb3e79bda07e86d91c27225bb0586ac0d5#diff-612bbd927fdc6bea075f0069da74adfd8db735c3c625db791e6a7aa709d6716fL378) just calls `schedule_cancel_overlay_for_pane`, while copy mode's [close method](https://github.com/wez/wezterm/blob/6b21e6ffde46d1345fdfc5a1437054fa8d964e7c/wezterm-gui/src/overlay/copy.rs#L560) also calls `set_viewport(None)`. Probably there should be a separate `CloseWithoutClearingPosition` or similar.

**Comment by LeszekSwirski** [comment]
Yeah, adding something like that locally fixes it for me.
