### ISSUE TITLE
font size is zoomed and/or window is empty when first launched on a secondary monitor on macos

### ISSUE THREAD

**Issue by brandonchinn178** [wez/wezterm#3503]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230410-204717-fa0f538d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When initially opening Wezterm, the window is zoomed in (you even have to press enter a few times to get text to start showing in the window). It stays that way until you resize the window. This started happening after upgrading to the 20230408 release.

On open:
![Screenshot 2023-04-11 at 9 29 53 AM](https://user-images.githubusercontent.com/6827922/231228975-298bfc8b-5840-4a55-8e24-73ed4623a179.png)

After barely resizing:
![Screenshot 2023-04-11 at 9 30 00 AM](https://user-images.githubusercontent.com/6827922/231228978-151d4360-da38-4555-bb65-f442394a21c1.png)

### To Reproduce

1. `wezterm -n`
2. See window in zoomed state
3. Resize window
4. Window is back to normal

### Configuration

no config: also happens with `wezterm -n`

### Expected Behavior

Window should have normal font size + show full screen on initialization

**Comment by yerke** [comment]
I have the same issue on macOS 13.3.1.

**Comment by wez** [comment]
This doesn't reproduce for me, and there's no useful information on how to reproduce it; not even the basic information requested by the issue template is present here.

What does zoomed really mean? Is the font size too large?  Do the window contents not fit the window? If you run `vim` or some other full screen terminal app, does it fit the screen?

Please share more information about your system(s).  Is this on a laptop retina display? Is this a multi-monitor system?
Is there a different in DPI between the monitors?

Please share the output from running:

https://wezfurlong.org/wezterm/config/lua/wezterm.gui/enumerate_gpus.html
and
https://wezfurlong.org/wezterm/config/lua/wezterm.gui/screens.html

in the debug overlay (CTRL-SHIFT-L)

**Comment by yerke** [comment]
Hmm, the issue is gone for me now. I am not sure why. The only difference is that right now my MBP is not connected to the external monitor. I don't have it nearby in order to test it.

What I experienced: when I started wezterm, the initial prompt would be hidden at the top of the screen (window contents didn't fit the window). I had to resize the window in order for the prompt to show up. wezterm was on my external monitor at the time. I believe the DPI between my laptop screen and external monitor are different.

I am on ﻿﻿﻿20230408-112425-69ae8472 version of wezterm.

I will update this comment once I get back home and connect it to the external monitor again.

**Comment by brandonchinn178** [comment]
huh ok it doesn't happen on my personal laptop (MacOS 12.6.3) either on its own or connected to an external monitor, but it happens on my work laptop (MacOS 13.3.1) only when connected to an external monitor.

Opening vim in the "zoomed" state only shows the bottom left part of it:
![Screenshot 2023-04-11 at 8 24 42 PM](https://user-images.githubusercontent.com/6827922/231340886-91902dac-a153-4870-b897-c48323101b90.png)

So it's both font size (both in the body + in the title bar) and crops out the screen. The debug overlay does show a warning:
```
wezterm version: 20230408-112425-69ae8472 aarch64-apple-darwin
Window Environment: macOS 13.3.1 (22E261)
OpenGL version: Apple M1 Max 4.1 Metal - 83.1
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
20:23:52.561 WARN wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 24, cols: 80 }) because window_state is MAXIMIZED
```
The message is interesting, because the window is not maximized (unless it means something else).

Running the above commands shows the following, whether the screen is "zoomed" or not:
```
> wezterm.gui.screens()
{
    "active": {
        "height": 1080,
        "max_fps": 60,
        "name": "LEN P27u-10",
        "scale": 1,
        "width": 1920,
        "x": 0,
        "y": 0,
    },
    "by_name": {
        "Built-in Retina Display": {
            "height": 1934,
            "max_fps": 120,
            "name": "Built-in Retina Display",
            "scale": 1,
            "width": 2992,
            "x": 3840,
            "y": 86,
        },
        "LEN P27u-10": {
            "height": 1080,
            "max_fps": 60,
            "name": "LEN P27u-10",
            "scale": 1,
            "width": 1920,
            "x": 0,
            "y": 0,
        },
    },
    "main": {
        "height": 1080,
        "max_fps": 60,
        "name": "LEN P27u-10",
        "scale": 1,
        "width": 1920,
        "x": 0,
        "y": 0,
    },
    "origin_x": 0,
    "origin_y": 0,
    "virtual_height": 2020,
    "virtual_width": 6832,
}

> wezterm.gui.enumerate_gpus()
[
    {
        "backend": "Metal",
        "device": 0,
        "device_type": "IntegratedGpu",
        "name": "Apple M1 Max",
        "vendor": 0,
    },
]
```

**Comment by jpasquier** [comment]
Hi,

I have the same issue on macOS 12.6.3 connected to an external monitor (scaled). The issue appears only if wezterm windows opens on the external monitor. Everything is normal if wezterm window opens on the laptop screen.

**Comment by ThorstenRhau** [comment]
I have the same issue on macOS 13.3.1 MacBook Air with M1 that is company managed. At home I have a macMini with the same macOS 13.3.1 and M2 SoC, there the error does not occur.  The M2 at home is connected to a Studio Display and the work machine is connected to a 1440p, low-dpi, display.

I have the same configuration, Fonts etc on both machines. 

Please find my configuration below. I have tried different 'front_end', 'freeype_load_targets', and 'initial_*' settings. None of these solved the problem.

`~ cat .config/wezterm/wezterm.lua
local wezterm = require("wezterm")

-- https://wezfurlong.org/wezterm/colorschemes/index.html
local function scheme_for_appearance(appearance)
  if appearance:find("Dark") then
    -- Dark theme
    return "Zenbones_dark"
  else
    -- Light theme
    return "Zenbones_light"
  end
end

return {
  front_end = "WebGpu", -- Render with Metal on macOS
  freetype_load_target = "Light",
  color_scheme_dirs = { "~/.config/wezterm/colors" },
  color_scheme = scheme_for_appearance(wezterm.gui.get_appearance()),
  font = wezterm.font_with_fallback({
    "MonoLisa Fancy",
    "Symbols Nerd Font Mono",
  }),
  font_size = 13.0,
  initial_rows = 40,
  initial_cols = 110,
  scrollback_lines = 5000,
  adjust_window_size_when_changing_font_size = false,
  hide_tab_bar_if_only_one_tab = true,
  tab_bar_at_bottom = true,
  audible_bell = "Disabled",
  -- Tab bar configuration
  window_frame = {
    font = wezterm.font({ family = "MonoLisa Fancy", weight = "Medium" }),
    font_size = 10.0,
  },
}
~`

**Comment by ThorstenRhau** [comment]
> Hi,
> 
> I have the same issue on macOS 12.6.3 connected to an external monitor (scaled). The issue appears only if wezterm windows opens on the external monitor. Everything is normal if wezterm window opens on the laptop screen.

I can confirm this behaviour on macOS 13.3.1 on a M1 MacBook Air that is connected to a Dell 27" 1440p display via USB-C.

When launching wezterm on the 1440p display the terminal is zoomed (font size 50?) and the correct font size is established as soon as the window is resized.

If wezterm is launched on the MacBook air internal screen there is no problem.

**Comment by michaelrommel** [comment]
Are HiDPI displays involved?

**Comment by yerke** [comment]
I confirmed that the issue is only happening with my external monitor.

This is how it looks when I open wezterm and run vim without resizing.
![Screenshot 2023-04-12 at 2 04 22 PM](https://user-images.githubusercontent.com/5137691/231584876-6004b07f-3eba-4fa2-a0a7-3ddae7d64f2e.png)

That font size you see in the screenshot above is not what I specified in the config.

```
Debug Overlay
wezterm version: 20230408-112425-69ae8472 aarch64-apple-darwin
Window Environment: macOS 13.3.1 (22E261)
OpenGL version: Apple M1 Max 4.1 Metal - 83.1
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
14:06:25.234 WARN wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 24, cols: 80 }) because window_state is MAXIMIZED
14:06:32.573 INFO wezterm_gui::termwindow > QuitApplication over here (window)
> wezterm.gui.enumerate_gpus()
[
    {
        "backend": "Metal",
        "device": 0,
        "device_type": "IntegratedGpu",
        "name": "Apple M1 Max",
        "vendor": 0,
    },
]
> wezterm.gui.screens()
{
    "active": {
        "height": 1440,
        "max_fps": 60,
        "name": "DELL U2722DE",
        "scale": 1,
        "width": 2560,
        "x": 0,
        "y": 0,
    },
    "by_name": {
        "Built-in Retina Display": {
            "height": 2234,
            "max_fps": 120,
            "name": "Built-in Retina Display",
            "scale": 1,
            "width": 3456,
            "x": 880,
            "y": -2234,
        },
        "DELL U2722DE": {
            "height": 1440,
            "max_fps": 60,
            "name": "DELL U2722DE",
            "scale": 1,
            "width": 2560,
            "x": 0,
            "y": 0,
        },
    },
    "main": {
        "height": 1440,
        "max_fps": 60,
        "name": "DELL U2722DE",
        "scale": 1,
        "width": 2560,
        "x": 0,
        "y": 0,
    },
    "origin_x": 0,
    "origin_y": -2234,
    "virtual_height": 3674,
    "virtual_width": 4336,
}
>
```

**Comment by ThorstenRhau** [comment]
Here is the debug output from when my machines (M1 MB Air) is connected to an external display and the "zoomed window" bug is present.


```
Debug Overlay
wezterm version: 20230408-112425-69ae8472 aarch64-apple-darwin
Window Environment: macOS 13.3.1 (22E261)
OpenGL version: WebGPU: name=Apple M1, device_type=IntegratedGpu, backend=Metal, vendor=0, device=0
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
10:54:44.252 WARN wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 40, cols: 110 }) because window_state is MAXIMIZED

> wezterm.gui.enumerate_gpus()
[
    {
        "backend": "Metal",
        "device": 0,
        "device_type": "IntegratedGpu",
        "name": "Apple M1",
        "vendor": 0,
    },
]
>

> wezterm.gui.screens()
{
    "active": {
        "height": 1440,
        "max_fps": 60,
        "name": "DELL U2719DC",
        "scale": 1,
        "width": 2560,
        "x": 0,
        "y": 0,
    },
    "by_name": {
        "Built-in Retina Display": {
            "height": 1800,
            "max_fps": 60,
            "name": "Built-in Retina Display",
            "scale": 1,
            "width": 2880,
            "x": 5120,
            "y": 328,
        },
        "DELL U2719DC": {
            "height": 1440,
            "max_fps": 60,
            "name": "DELL U2719DC",
            "scale": 1,
            "width": 2560,
            "x": 0,
            "y": 0,
        },
    },
    "main": {
        "height": 1440,
        "max_fps": 60,
        "name": "DELL U2719DC",
        "scale": 1,
        "width": 2560,
        "x": 0,
        "y": 0,
    },
    "origin_x": 0,
    "origin_y": 0,
    "virtual_height": 2128,
    "virtual_width": 8000,
}
>
```

**Comment by ThorstenRhau** [comment]
Here is a video that hopefully shows the bug.


https://user-images.githubusercontent.com/17708199/231720370-ded2e4ca-08ef-4b56-9112-c69f72fb9f09.mov

**Comment by fnicastri** [comment]
I can confirm the issue with an external monitor

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by brandonchinn178** [comment]
Works! Thanks @wez!
