### ISSUE TITLE
macOS copy/paste does not work in about box

### ISSUE THREAD

**Issue by eproxus** [wez/wezterm#3507]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230411-221643-c8b8e811

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When trying the copy the version number from the About WezTerm box, copy/paste didn't work.

### To Reproduce

1. Open WezTerm on macOS
2. Go to WezTerm -> About WezTerm
3. Select text
4. Press ⌘C

### Configuration

no config

### Expected Behavior

The selected text is copied.

**Comment by wez** [comment]
FWIW, copying from there isn't something I'd planned to support explicitly.
Other ways to get the version number:

* `wezterm --version`
* Open the debug overlay (CTRL-SHIFT-L), which includes more and more useful information if you're planning on filing a bug report

**Comment by craigmac** [comment]
For me on macOS with nightly it just hangs the app until I have to force close it. It's been a couple months though, I'll try again.

**Comment by quantonganh** [comment]
- version: 20230421-075330-e0a92c73

Even with:

```
$ WEZTERM_LOG=debug ./wezterm
```

I only got this:

```
fish: Job 1, 'WEZTERM_LOG=debug ./wezterm' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

The debug logs: [wezterm.log](https://github.com/wez/wezterm/files/11303048/wezterm.log)
