### ISSUE TITLE
Num Lock/Caps Lock breaks F1-4 keys

### ISSUE THREAD

**Issue by AThePeanut4** [wez/wezterm#3517]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20230413-101024-9f9e330d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When Num Lock or Caps Lock is enabled, the keycodes sent by the F1-4 keys change, which for me is breaking `byobu`'s navigation which uses them heavily.

I also just noticed a likely related bug that typing in the Debug Overlay while Num Lock or Caps Lock is enabled doesn't work at all - the only thing that works is ESC to exit, CTRL-D doesn't work either. I can make a separate issue for that if you'd like.

### To Reproduce

Run `showkey -a` and press the F1-4 keys with either Num Lock or Caps Lock enabled.

Without Num Lock/Caps Lock (this is the expected/previous behaviour):
F1: ^[OP (0x1b 0x4f 0x50)
F2: ^[OQ (0x1b 0x4f 0x51)
F3: ^[OR (0x1b 0x4f 0x52)
F4: ^[OS (0x1b, 0x4f, 0x53)

With Num Lock and/or Caps Lock:
F1: ^[[1;1P (0x1b 0x5b 0x31 0x3b 0x31 0x50)
F2: ^[[1;1Q (0x1b 0x5b 0x31 0x3b 0x31 0x51)
F3: ^[[1;1R (0x1b 0x5b 0x31 0x3b 0x31 0x52)
F4: ^[[1;1S (0x1b 0x5b 0x31 0x3b 0x31 0x53)

### Configuration

no config (also occurs with `wezterm -n`)

### Expected Behavior

The keycodes sent by the F-keys should not change if Num Lock or Caps Lock is enabled.

### Anything else?

I did a bisect and 2dcf7ad98dde802bb92cbf78a98662ea7224842a seems to be the first commit where the issue appears.

**Comment by wez** [comment]
Should be resolved in `main`!
