### ISSUE TITLE
Wezterm freezes (accepts no input) in quick select mode

### ISSUE THREAD

**Issue by ohle** [wez/wezterm#3519]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE (kwin)

### WezTerm version

20230413-142547-36d9e13c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When entering Quick Select Mode, matching strings are highlighted and the prompt appears, but no keyboard input is accepted. I can neither accept an option by typing the prefix, nor can I leave Quick Select Mode with Escape.

I am forced to close the wezterm window.

### To Reproduce

Enter quick select mode with ctrl+shift+space

### Configuration

no config

### Logs

```
Debug Overlay
wezterm version: 20230413-142547-36d9e13c x86_64-unknown-linux-gnu
Window Environment: X11 KWin
OpenGL version: NVIDIA GeForce GTX 1050/PCIe/SSE2 4.6.0 NVIDIA 470.182.03
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
```
(apparently CTRL-SHIFT-L still works)

### Anything else?

I've tried to bisect this, but had to skip a block of commits because CTRL-SHIFT-SPACE to enter Quick Select did not work at all (and neither did CTRL-SHIFT-X for Copy Mode):

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
70a8af479d18aafe4ddddfc724ac710082f08056
54a65a5401a86bab5c56751abca7de438c408b4a
a9165ae4c4a95e84b5b1347c3d8a9194a90cb4a5
b704ec6d700c6ead7f1b7e48208768980cc2e618
e241ea58bec4363c3c1d0c796e2fcd86ae9dae5f
0eeca6c2c52b626fc9d4c9ccf22ee72330e2106a
f4995511e2bf77ce42f17ce441df45f68be1d43e
a58baacdef09352b500410f320e5bbd882e558b5
b646c36e349b3f66237b596ab4ed78e442debd74
2dcf7ad98dde802bb92cbf78a98662ea7224842a
b0ceebbc2d11698a594f966e3d712ce44014ac14
eaab3d08aefd3eff92a49499d903586c316f83a8
We cannot bisect more!
```

**Comment by wez** [comment]
We had a brief rough patch in `main` with key handling when caps lock or num lock were active.

This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
