### ISSUE TITLE
Num Lock/Caps Lock breaks the Debug Overlay

### ISSUE THREAD

**Issue by AThePeanut4** [wez/wezterm#3523]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20230413-142547-36d9e13c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Typing in the Debug Overlay while Num Lock or Caps Lock is enabled doesn't work at all - the only thing that works is ESC to exit, CTRL-D doesn't work either.

### Configuration

None (issue occurs using `wezterm -n`)

**Comment by wez** [comment]
Fixed in `main`
