### ISSUE TITLE
user-var-changed event is shared between windows underneath the same parent process

### ISSUE THREAD

**Issue by DrKGD** [wez/wezterm#3524]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

arch, awesomewm, picom

### WezTerm version

wezterm 20230413-101024-9f9e330d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The provided [shell-integration](https://wezfurlong.org/wezterm/shell-integration.html) script automatically defines escape sequences to setup hooks upon running a cli program (such as nvim), I would like to alter the specific window properties for common known programs.

Using the wezterm event [user-var-changed](https://wezfurlong.org/wezterm/config/lua/window-events/user-var-changed.html), it should be possible to detect these changes at a local (per-pane) scope, thus only applying changes to the window currently owning that specific pane.

However, it _seems_ (take what I am saying here with a grain of salt) that each and every spawned instance of wezterm underneath the same parent process is sharing the same environment variables, so that `user-var-changed` event is fired for each one of them.

In fact a possible workaround would consist of running each and every wezterm instance in its own process (`wezterm start --always-new-process`).

### To Reproduce

Copy and paste the following in the configuration

```
require('wezterm').on('user-var-changed', function(window, pane, name, value)
	if name == 'WEZTERM_PROG' then
		wezterm.log_info(window, pane, name, value)
		local overrides = window:get_config_overrides() or { }
		if value == 'nvim' then
			overrides.window_background_opacity = 0.0
		else
			overrides.window_background_opacity = nil
		end

		window:set_config_overrides(overrides)
	end
end)
```

### Configuration

No configuration is required to reproduce the bug, aside from the code presented above. 

### Expected Behavior

Only the affected window (the one containing the pane which is running a nvim instance) should be updated instead.

### Logs

```
18:12:31.433 INFO logging > lua: "GuiWin(mux_window_id:0, pid:2843)" "MuxPane(pane_id:2, pid:2843)" WEZTERM_PROG nvim
18:12:31.433 INFO logging > lua: "GuiWin(mux_window_id:1, pid:2843)" "MuxPane(pane_id:2, pid:2843)" WEZTERM_PROG nvim
18:12:31.433 INFO logging > lua: "GuiWin(mux_window_id:3, pid:2843)" "MuxPane(pane_id:2, pid:2843)" WEZTERM_PROG nvim
18:12:31.433 INFO logging > lua: "GuiWin(mux_window_id:2, pid:2843)" "MuxPane(pane_id:2, pid:2843)" WEZTERM_PROG nvim
```

### Anything else?

https://user-images.githubusercontent.com/44092476/232106935-4ca850a6-5bc6-4df4-a644-5b313fcb57b8.mp4

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
