### ISSUE TITLE
conpty: With shell integration enabled, the last line of each output immediately disappears until the screen is filled

### ISSUE THREAD

**Issue by antoineco** [wez/wezterm#3531]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230415-235902-6ec11393

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With shell integration enabled in a Z shell (ZSH 5.9) inside WSL (Ubuntu 22.10 from the Windows store), the last line of each output of shell commands immediately disappears after being printed, until an entire screen is filled.

After the screen has been filled for the first time, entire outputs remain on screen.

- If the screen is cleared again (e.g. with `CTRL-L`), the issue occurs until the screen is filled again, and so on.
- The issue does not occur in Bash (5.2) with shell integration.
- The issue does not occur when shell integration isn't enabled.

Below is a video recording which demonstrates the issue:

https://user-images.githubusercontent.com/3299086/232287157-f7a5dc1b-1ecf-4601-b22e-73b6043787c5.mp4

Another recording showing the issue happening randomly (apparently), this time with ZSH's defaults instead of a multi-line prompt:

https://user-images.githubusercontent.com/3299086/232289589-a92e5b4e-a669-486b-bee7-a6e13c45bec8.mp4

### To Reproduce

1. Configure `zsh` as the user shell:
    ```sh
    sudo chsh -s /usr/bin/zsh ${USER}
    ```
1. Download the shell integration enablement script to `${HOME}/wezterm.sh`:
    ```sh
    cd
    curl -LO https://raw.githubusercontent.com/wez/wezterm/main/assets/shell-integration/wezterm.sh
    ```
1. Create an _empty_ `~/.zshrc` file containing:
   ```zsh
   [[ -s ${HOME}/wezterm.sh ]] && . ${HOME}/wezterm.sh
   ```
1. Open a new shell (open a new tab or window)
1. Issue commands which print at least one line of output, until the screen is filled, and observe that the last line of outputs do not remain on screen. Then, observe that outputs do remain on screen.

### Configuration

no config

> **Note**
> Although the video demonstration was recorded _with_ customizations for both WezTerm and the ZSH prompt, the issue occurs _without_ any customization.
> For instance, I can reproduce the issue with no `.wezterm.lua` / `.config/wezterm/wezterm.lua` at all, and with ZSH's default prompt (`PS1=%m%#` on Ubuntu) and no module.

**Comment by wez** [comment]
Please capture a terminal session recording for each of the cases you described.

* Launch wezterm into either CMD or PWSH.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session; it will spawn a nested command prompt.
* Now enter your WSL environment and run through your reproduction steps
* Then exit the WSL environment and exit the record session.
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by antoineco** [comment]
Attached is a recording performed with the following config:

```lua
local config = require 'wezterm'.config_builder()

config.term = 'wezterm'

config.default_domain = 'WSL:Ubuntu'

config.launch_menu = {{
  label = 'PowerShell',
  args = { 'pwsh.exe' },
  domain = { DomainName = 'local' }
}}

return config
```

`wezterm record` without argument drops me into `cmd.exe` instead of the WSL domain, so I created the recording with `wezterm record -- wsl.exe -d Ubuntu --cd ~`.

While doing this I observed something slightly different, with a seemingly blank line before each output, but the issue should be visible in the recording:

![image](https://user-images.githubusercontent.com/3299086/232320465-925daa0d-4ff2-4660-bafc-c97ded10a240.png)

[wezterm-recording-Kafb7c.cast.txt](https://github.com/wez/wezterm/files/11242524/wezterm-recording-Kafb7c.cast.txt)

**Comment by antoineco** [comment]
The same experiment, this time without shell integration and only 3 consecutive shell commands (because the issue doesn't occur at all anyway).

[wezterm-recording-XgE0C6.cast.txt](https://github.com/wez/wezterm/files/11242530/wezterm-recording-XgE0C6.cast.txt)

**Comment by wez** [comment]
Haven't dug into your recording yet, but I remembered this issue while I was out walking my dog this morning:
* https://github.com/microsoft/terminal/issues/13710

I'd suggest trying to use `wezterm ssh` to get into your wsl environment; that will bypass the conpty layer and likely eliminate this issue.

In the latest release and current nightly builds, if you add the ssh details for your wsl environment to your (windows) `~/.ssh/config` file, wezterm will pre-create `SSH:` and `SSHMUX:` domains for that host, and you can attach to one of those (or make it the default domain), rather than having to manually run `wezterm ssh`.

**Comment by antoineco** [comment]
Thanks for the reference, much appreciated 👍

I will try running an OpenSSH server in my WSL distribution and use the corresponding domain.

I see that bypassing ConPTY should also [make undercurl work](https://github.com/wez/wezterm/blob/6ec11393d5ae33c87b4a6ce7fe5f257dffd00021/docs/faq.md?plain=1#L249-L253), so that would solve two problems at once. The only drawback I see with that approach is that the WSL instance needs to be started manually for the SSH server to become available.

**Comment by antoineco** [comment]
This is fixed for me in the latest nightly: https://github.com/microsoft/terminal/issues/13710#issuecomment-1566290653
Cheers Wez!
