### ISSUE TITLE
Raw Linux binary install link isn't substituted

### ISSUE THREAD

**Issue by garymoon** [wez/wezterm#3536]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

N/A

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

On the [download page](https://wezfurlong.org/wezterm/install/linux.html) the `Raw Linux Binary` link doesn't seem to be substituted from the [source](https://github.com/wez/wezterm/blob/4ba653c716ec69164c7cf8ce28f7874b95942333/docs/install/linux.md?plain=1#L186) - the href is `{{ linux_raw_bin_stable }}`.

### Configuration

N/A

### Anything else?

A new issue template for reports not directly related to the software itself could be handy.

**Comment by wez** [comment]
Thanks for the report! I'll add a doc issue template as well.
