### ISSUE TITLE
Can't select text on first line via mouse

### ISSUE THREAD

**Issue by seqizz** [wez/wezterm#354]
## Describe the bug

If there is something on the scrollback buffer, it's not easy to select text from first line (or even second line) via mouse. Click + drag triggers scroll, even if you don't drag upwards.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: `UNKNOWN` (master commit eee40f7d from 2 days ago)

## To Reproduce

- Print something long so you have something to scroll up
- Try to select one word from the first visible line via mouse

## Expected behavior

Scroll shouldn't be triggered unless mouse moves upwards

**Comment by bew** [comment]
Yes! I also wanted to make an issue for this for some time :smiley: 

Double clicking to select works, but as soon as you have to move the mouse.... the whole terminal window scrolls to infinity...

On urxvt for example it scrolls the terminal only when the mouse is moved ouside of the window (while clicking)

**Comment by wez** [comment]
This is a consequence of making the mouse bindings assignable; what's happening is that the mouse move event is being recognized as being within the pane and is then routed to the action that extends the selection based on the mouse position.  There is a heuristic to scroll based on how close to the top or bottom the mouse is.

The main problem here is that if the mouse moves when it is outside of the pane, we don't currently know to route the event into the pane.

**Comment by seqizz** [comment]
> The main problem here is that if the mouse moves when it is outside of the pane, we don't currently know to route the event into the pane.

If I understood correctly, is the following possible?

- If the selection starts somewhere which is not close to the edge (e.g. first-last 3 lines), current behavior applies.
- If the selection starts near the edge, move ~5x slower, unless mouse actually moves outside of the pane. Once mouse leaves the pane from the edge, scroll normally. 

Of course this will work only if it's possible to detect whether the mouse is still being dragged or not, outside the pane.
