### ISSUE TITLE
wezterm crashes after pressing some numpad keys

### ISSUE THREAD

**Issue by data-man** [wez/wezterm#3543]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin (X11).

### WezTerm version

20230416-203745-f3ee5e57

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Crashes after pressing some keys.

### To Reproduce

Start wezterm and press `Home` or `End` or `PgUp` with or without key modifiers.

### Configuration

No config.

### Expected Behavior

Don't crash.

**Comment by wez** [comment]
I can't reproduce this. Where are your logs? See the logs section of the template https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml for more information on locating them and sharing them.

If there is nothing useful in the log, please run wezterm-gui under gdb and collect a stack trace.

**Comment by data-man** [comment]
> I can't reproduce this. 

It's strange!

Also `20230408-112425-69ae8472` build is ok.

> See the logs section

I'll do!

**Comment by data-man** [comment]
I update wezterm to `20230417-063302-163dfd7d`.

```
19:37:28.452  ERROR  env_bootstrap > panic at termwiz/src/input.rs:414:26 - internal error: entered unreachable code
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  27: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:381:3
  28: <unknown>
```

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by data-man** [comment]
Fixed, thank you very much for your work!
