### ISSUE TITLE
Unable to use ^ keys for Neovim binding, eventhough I had set dead keys to false in my config. 

### ISSUE THREAD

**Issue by jeffreylean** [wez/wezterm#3544]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I used to use Ctrl+^ to go to alternate files in Vim/NeoVim. However, I realize in Wezterm this key binding doesn't work because Wezterm treats ^ as the dead key. So I set dead keys to false in my config, `config.use_dead_keys = false` as instructed by the documentation. But the issues still persist, the key binding still doesn't work, not sure what happened there. 

### Configuration

-- Disable dead key, because Vi need `^` single keypress
config.use_dead_keys = false

### Expected Behavior

I expect after turning dead key off, I should able to use ^ key as normal output.

**Comment by wez** [comment]
To clarify, wezterm respects the keyboard layout you have configured in your OS. So if your keyboard layout says that `^` is a dead key, wezterm will honor that. If you are not using such a layout, then `^` is not a dead key and the dead key option has no bearing on what that key does.  Different layouts have different dead keys; `^` is not always a dead key in every european layout.

I'd suggest working through: https://wezfurlong.org/wezterm/troubleshooting.html#debugging-keyboard-related-issues

to get a better handle on what key is being pressed and what is being sent to the program running in the terminal. Please share the logs from `debug_key_events`.
