### ISSUE TITLE
wrong color of last char of starship-prompt when using fish-shell

### ISSUE THREAD

**Issue by apettel** [wez/wezterm#3548]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230417-063302-163dfd7d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using wezterm and zsh the last char of the starship prompt looks good, when using wezterm and fish, the color of the last char is wrong. When using kitty, there are no problems with the color.

The relevant configuration of the last segment of the starship prompt:

```toml
[time]
disabled = false
format = '[](fg:white bg:black)[  $time ](fg:black bg:white)'
time_format = "%T"
```

wezterm screenshot (zsh/fish/fish selected)
<img width="1015" alt="Bild 2023-04-17 at 16 45 42" src="https://user-images.githubusercontent.com/62218880/232525558-3c904a08-0345-4373-a567-2f55d13f1188.png">

kitty screenshot (zsh/fish/fish selected)
<img width="1029" alt="Bild 2023-04-17 at 16 47 13" src="https://user-images.githubusercontent.com/62218880/232525647-eb838fc7-8086-48fc-8e1b-f90e2f6b4da3.png">

### Configuration

no config

### Expected Behavior

starship prompt should look the same when using fish

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by apettel** [comment]
[wezterm-recording-KZrMZh.cast.txt](https://github.com/wez/wezterm/files/11252376/wezterm-recording-KZrMZh.cast.txt)

**Comment by apettel** [comment]
When i do the replay in a 80x24 terminal, the color of the last char is wrong. When the width of the terminal is greater than 80 chars, the replay looks as it should.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by apettel** [comment]
Works perfectly. Thanks a lot!
