### ISSUE TITLE
Fonts: Reduce default skew factor and/or permit user-specified skew factor

### ISSUE THREAD

**Issue by rozbb** [wez/wezterm#3555]
## Is your feature request related to a problem? Please describe.

When a font doesn't have built-in italics, wezterm (and most terminals) will approximate an italic variant by simply _skewing_ the letters. Currently, the skew factor is [fixed at 20%](https://github.com/wez/wezterm/blob/87cd9c5f6cc26809527344a9713aff19227dc243/wezterm-font/src/rasterizer/mod.rs#L25), and it doesn't look great. Here is a side by side. First image is wezterm, second is iTerm2, both using Fira Code Medium:
<img width="1091" alt="Screenshot 2023-04-18 at 01 17 59" src="https://user-images.githubusercontent.com/752802/232679455-bc754a73-8619-4d37-8dc4-0a03bbe33c41.png">
<img width="1032" alt="Screenshot 2023-04-18 at 01 18 02" src="https://user-images.githubusercontent.com/752802/232679467-7058a677-42ad-4ea5-b4a0-bc9cc820486a.png">

In fact, the letters are so skewed, that the cursor highlights portions of adjacent letters sometimes:
<img width="815" alt="Screenshot 2023-04-18 at 01 29 22" src="https://user-images.githubusercontent.com/752802/232679753-4e59dad0-dbc8-4daa-9a2c-c8eb40f00f0f.png">

### Describe the solution you'd like

Two fixes, both of which can happen independently:

1. I think the default skew factor should be reduced.  I haven't played with the values so I don't have a concrete recommendation for a number
2. In addition, make the skew factor configurable. E.g.,
```lua
config.font = wezterm.font("Fira Code", { weight="Medium", skew_factor = 0.10 })
```

### Describe alternatives you've considered

Looked at other font options. There's nothing rn that addresses this.

**Comment by wez** [comment]
I'll accept PR(s) for either/both of these

**Comment by rozbb** [comment]
Update: I'm now thinking that there might be a bug. Looks like wezterm is skewing _in addition_ to doing italics. Here's a side by side of `factor = 0.0` and `factor = 0.2`. Will investigate further.
<img width="768" alt="Screenshot 2023-04-18 at 02 20 47" src="https://user-images.githubusercontent.com/752802/232689132-977459d4-dfb2-4eb6-b93a-55a35bfe8cc0.png">
<img width="768" alt="Screenshot 2023-04-18 at 02 21 20" src="https://user-images.githubusercontent.com/752802/232689138-89aea679-16a8-4b66-8db0-267881ff3dfd.png">

**Comment by rozbb** [comment]
Aha, it looks like it's double-skewing. [This line](https://github.com/wez/wezterm/blob/1e8fd7a95ba84e45ebf5349b48cdb27bfac95a38/wezterm-font/src/rasterizer/freetype.rs#L319) already sets the skew to 20% for the face.

Question: what should the change look like here? Should `rasterize_glyph()` do any skewing at all, given that this transform is done for all `synthesize_italic` fonts? Lmk
