### ISSUE TITLE
ssh multiplexing bug: lines are not rendered correctly

### ISSUE THREAD

**Issue by zjp-CN** [wez/wezterm#3558]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230417-080429-040a079b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Thank you for the great tool! I just use WezTerm today, and it's awesome!

I noticed lines are flushed incorrectly in ssh multiplexing:

![bug](https://user-images.githubusercontent.com/25300418/232836764-0894576a-ae18-4b7f-b3df-7ba5507efe80.gif)

It all works fine in ssh command line connection:

![working](https://user-images.githubusercontent.com/25300418/232836794-e67f1011-8007-4fcb-b658-c9fce1b1d92a.gif)

### To Reproduce

It can be reproduced as follows:
* `wezterm connect my.server` to connect to the remote server
* open neovim and `:Neogit` (this command is from  [neogit](https://github.com/TimUntersberger/neogit) ) to view unstaged files, then stroke `Tab` to toggle the unstaged contents three times or so and you'll see the incorrect rendering at least one time

### Configuration

```lua
local wezterm = require 'wezterm'
local config = {}

config.ssh_domains = {
  {
    name = 'my.server',
    remote_address = 'xx',
    username = 'xx',
    timeout = 60,
  },
}

return config
```

### Expected Behavior

Normal and smooth rendering like via ssh command line connection.

### Logs

These are logged when quitting instead of rendering. And only there logging lines are found.

```shell
00:22:53.840  INFO   mux > detaching domain
00:22:53.845  INFO   wezterm_client::domain > detached domain 2
00:22:53.848  INFO   mux                    > domain detached panes: [1]
00:22:53.860  ERROR  wezterm_client::client > wezterm cli --prefer-mux proxy: Exited with code 1
00:22:53.885  INFO   wezterm_client::domain > detached domain 2
00:22:53.889  INFO   mux                    > domain detached panes: []
```

**Comment by wez** [comment]
Might possibly be the same underlying issue as https://github.com/wez/wezterm/issues/3503
If you create a vsplit, does the issue go away?

**Comment by zjp-CN** [comment]
> If you create a vsplit, does the issue go away?

Thanks for the reply. But the issue still exists in vsplit pane. 

https://user-images.githubusercontent.com/25300418/232947951-7a447a17-01be-42f5-bbac-cdd754b5c57c.mp4

I found it might be relevant to the scale, like it might work well after zooming in (the picture below shows no issue occurs when hitting Tab 54 times in a row)
![ok](https://user-images.githubusercontent.com/25300418/232948663-d1800f13-db85-47c0-bba3-6d9ecce27e15.png)

or worse when frequently zooming:


https://user-images.githubusercontent.com/25300418/232952450-d6050c43-4eed-4981-9f1f-2bf23cdcd9db.mp4

**Comment by Lenbok** [comment]
This sounds kind of similar to #4607, which may be recently fixed according to https://github.com/wez/wezterm/issues/4607#issuecomment-2334641784 
Can you try a nightly and see if the issue is still present?

**Comment by zjp-CN** [comment]
Thanks for the issue links!

I tried an old wezterm version, which was installed a year ago or so, before the PR , since I rarely update wezterm, I can't reproduce the problem any more.

And I just updated wezterm to the nightly, glad to see neovim works as expected.

So I'm gonna close this.
