### ISSUE TITLE
The shell integration is slow in WSL

### ISSUE THREAD

**Issue by Frojdholm** [wez/wezterm#3562]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Sourcing the shell integration in WSL on windows causes noticeable slow-downs when redrawing `PS1`.

I didn't test the latest nightly since no change since the latest release seemed related to the shell integration. Seems related to #3402.

### To Reproduce

1. Run wezterm on windows in the WSL domain (Ubuntu 22.04).
2. Source the shell integration (`wezterm.sh`). 

There's a noticeable delay when redrawing the prompt.

### Configuration

no config

### Expected Behavior

The prompt shouldn't be noticeably slower.

**Comment by wez** [comment]
If you use `wezterm ssh` to ssh into the WSL instance, do you still observe the slowdown?
Using `wezterm ssh` bypasses conpty.
conpty has some issues with the family of escape sequences used in shell integration:
* https://github.com/microsoft/terminal/issues/13710

**Comment by Frojdholm** [comment]
I didn't have an SSH server setup in WSL and I don't have the time right now to figure out how to set it up, sorry.

Since I mostly wanted new tabs to open in the same directory as the focused tab I got around this by creating a bash function that prints the escape sequence whenever I `cd`.

```bash
function cd() {
    builtin cd "$@"
    printf "\033]7;file://%s%s\033\\" "${HOSTNAME}" "${PWD}"
}
```

This works okay for me for now (no delay), with the drawback that you have to `cd` at least once for it to trigger.
