### ISSUE TITLE
Sometimes scrolling with touchpad leads to crashes

### ISSUE THREAD

**Issue by devmatteini** [wez/wezterm#3564]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

I'm using Ubuntu 22.10 with GNOME X11

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Sometimes scrolling with touchpad leads to crashes.
From my tests using the keyboard shortcuts to scroll up/down doesn't lead to crashes.

### To Reproduce

1. Open wezterm and run `wezterm start --always-new-process &` to start a new wezterm window in the background
2. Close the wezterm window that executed the previous command
3. In the second wezterm window run this bash script to create output to scroll:
    ```bash
    for i in {1..5000}; do echo "Iteration $i"; done
    ```
4. Try to scroll up and down with touchpad for a couple of seconds
5. wezterm crashes

### Configuration

https://github.com/devmatteini/dotfiles/blob/main/config/wezterm/wezterm.lua

### Expected Behavior

Wezterm shouldn't crash

### Logs

Logs from `$XDG_RUNTIME_DIR/wezterm`:

```
22:32:38.721  ERROR  env_bootstrap > panic at library/std/src/io/stdio.rs:1008:9 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  19: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:381:3
  20: <unknown>
```

Looking at [stdio.rs:1008:9](https://github.com/rust-lang/rust/blob/df0d9b492da81a647eedf17210cf55b86a44888c/library/std/src/io/stdio.rs#L1008) in rust standard library, it seems it panics trying to print something.

### Anything else?

If I run the same reproduce steps without step 2 the second wezterm doesn't crash.
In the first wezterm I can see this printed to stdout:

```
button 7 is not implemented
button 6 is not implemented
```
These two lines are repeated several times.

**Comment by wez** [comment]
Please try building from source from git, without `--release`, so that the stack trace is meaningful.
You can find instructions here:

https://wezfurlong.org/wezterm/install/source.html

but modify the last couple of lines to:

```console
$ cargo build
$ cargo run --bin wezterm -- start --always-new-process
```

**Comment by wez** [comment]
Have you redirected stderr to a device that has no disk space remaining?

**Comment by wez** [comment]
I've replaced the `eprintln` invocations with `log::trace` in `main`

**Comment by devmatteini** [comment]
> Have you redirected stderr to a device that has no disk space remaining?

No, I don't think so.

The problem might be that since I close the original wezterm that run `cargo run --bin wezterm -- start --always-new-process &` there's no more a valid stderr?

**Comment by devmatteini** [comment]
> I've replaced the `eprintln` invocations with `log::trace` in `main`

I've done a couple of tests, and it seems to fix the crashes...nice work!

**Comment by wez** [comment]
FWIW, my theory is that due to the imprecise nature of hand movement, your vertical scrolling had a good amount of horizontal movement which tickled that unhandled case.  After sufficient quantity of logging to stderr, some pipe buffer somewhere got filled up and rust's default is to panic rather than silently allow writing to a broken pipe or filled output stream.

**Comment by devmatteini** [comment]
Oh that's interesting! Thanks for sharing this :smile:

**Comment by wez** [comment]
Let's call this done!
