### ISSUE TITLE
fails to start due to non-conformant vulkan implementation in virtualbox

### ISSUE THREAD

**Issue by damanis** [wez/wezterm#3565]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

WindowMaker 0.95.9

### WezTerm version

20230419-105547-e204f8ba

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm didn't start with the error:
```
07:51:03.657  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
libEGL warning: DRI2: failed to authenticate
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
07:51:03.782  ERROR  env_bootstrap               > panic at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.15.1/src/backend/direct.rs:316:9 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: __libc_start_main
             at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  23: <unknown>

thread 'main' panicked at 'Error in Surface::configure: Downlevel flags SURFACE_VIEW_FORMATS are required but not supported on the device.
This is not an invalid use of WebGPU: the underlying API or device does not support enough features to be a fully compliant implementation. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to work around this issue, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.15.1/src/backend/direct.rs:316:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### To Reproduce

Use nightly version of 18-19 Apr 2023.

### Configuration

no config

### Expected Behavior

Wezterm  just should run.

### Anything else?

Version `20230408-112425-69ae8472` works properly in same environment:
```
VirtualBox 7.0.6
Ubuntu 20.04
WindowMaker 0.95.9 (or XFCE 4.14)
```

**Comment by wez** [comment]
FWIW, you should expect limited results when running in a virtual machine with no real GPU.

I've pushed a change that may allow wezterm to make progress.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes. 

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by damanis** [comment]
Tested `20230419-232850-fc7f203b` from `https://github.com/wez/wezterm/actions/runs/4751234702`
On image:
- bottom-right is urxvt from where wezterm started
- top-left - wezterm: window shown partially, does not respond
![image](https://user-images.githubusercontent.com/65733488/233288948-d50f21e2-74e9-4872-bedb-6f4a7cdddbe1.png)

**Comment by damanis** [comment]
I taken same build as above (`20230419-232850-fc7f203b`), added `front_end = "OpenGL"` to `wezterm.lua` and run `WezTerm-nightly-Ubuntu20.04.AppImage`.
The image works. The is an output on konsole wezterm run from:
```
ubuntu20.04 λ ./WezTerm-nightly-Ubuntu20.04.AppImage 
18:46:19.618  ERROR  wezterm_client::client > IncompatibleVersionError { version: "20230408-112425-69ae8472", codec_vers: 41 }
18:46:19.827  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
libEGL warning: DRI2: failed to authenticate
```

**Comment by CharlesChiuGit** [comment]
Have same issue when compiled from source which I just cloned (commit: ff153a92374fd8c2dce694dd3f6726a457628464)

OS: Ubuntu 22.04.2 (real machine)
GPU: Nvidia GTX 1650 
WM: bspwm

error log:
```log
Running `target/release/wezterm start`
15:24:33.646  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
15:24:33.826  ERROR  wezterm_gui                 > running message loop: process_queued_xcb: poll_for_queued_event: X(Match(RequestError { response_type: 0, error_code: 8, sequence: 276, bad_value: 31457289, minor_opcode: 4, major_opcode: 149, pad: 1 }), None); terminating
```

Screenshot:
![圖片](https://user-images.githubusercontent.com/32497323/233572822-669f028d-854e-4c09-ba08-8c6fe850ac52.png)

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit those logs don't seem obviously connected to this issue. Are you saying that setting `front_end='OpenGL'` resolved that for you?

sorry, plz ignore the log about compiling. the below part it's about xdg_protal thingy error while opening wezterm.

sorry, i'm new to wezterm, where should i set "front_end=opengl"? in the config file or during compiling?

**Comment by wez** [comment]
@CharlesChiuGit please file a separate issue, as it doesn't sound like this is the same issue

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit those logs don't seem obviously connected to this issue. Are you saying that setting `front_end='OpenGL'` resolved that for you?

Actually this did the trick! I guess nvidia gpu is part of the issue.

**Comment by CharlesChiuGit** [comment]
> I taken same build as above (`20230419-232850-fc7f203b`), added `front_end = "OpenGL"` to `wezterm.lua` and run `WezTerm-nightly-Ubuntu20.04.AppImage`. The image works. The is an output on konsole wezterm run from:
> 
> ```
> ubuntu20.04 λ ./WezTerm-nightly-Ubuntu20.04.AppImage 
> 18:46:19.618  ERROR  wezterm_client::client > IncompatibleVersionError { version: "20230408-112425-69ae8472", codec_vers: 41 }
> 18:46:19.827  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
> libEGL warning: DRI2: failed to authenticate
> ```

Try `sudo apt install xdg-desktop-portal-gnome` or [install other portals](https://github.com/flatpak/xdg-desktop-portal#using-portals).

**Comment by wez** [comment]
Resolved by using opengl
