### ISSUE TITLE
Update frame

### ISSUE THREAD

**Issue by BIKA-C** [wez/wezterm#3566]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The update frequency doesn't respect the config.

### To Reproduce

Sample C program that updates the screen every 100 micro seconds
```C
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>

int main() {
    int a = 0;
    setvbuf(stdout, NULL, _IOFBF, 0);
    while(a <= 100000){
        printf("\r%0.4f sec\x1B[K", a / 10000.0);
        fflush(stdout);
        usleep(100);
        a++;
    }
}
```

## WezTerm output

https://user-images.githubusercontent.com/50717946/233266420-422ebf04-20a2-4216-8093-7d7d81f98ee5.mov

## Terminal.app

https://user-images.githubusercontent.com/50717946/233266763-da200749-e18d-4a71-92fc-951d607a2a21.mov

## Kitty

https://user-images.githubusercontent.com/50717946/233266959-8ab0a698-0109-469c-a74b-ba936105daee.mov

### Configuration

```lua
local wez = require("wezterm")

return {
    color_scheme = "BlulocoDark",
    font = wez.font_with_fallback({"FiraCode Nerd Font"}),
    font_size = 22,
    freetype_load_target = "Normal",
    window_background_opacity = 0.77,
    window_decorations = "RESIZE | MACOS_FORCE_DISABLE_SHADOW",
    front_end = "OpenGL",
    macos_window_background_blur = 100000,
    enable_tab_bar = true,
    cursor_blink_rate = 570,
    animation_fps = 60,
    cursor_blink_ease_in = "EaseIn",
    cursor_blink_ease_out = "Linear",
    bold_brightens_ansi_colors = "BrightAndBold",
    skip_close_confirmation_for_processes_named = {
        "bash",
        "sh",
        "zsh",
    },
    window_padding = {
        left = 40,
        right = 40,
        top = 50,
        bottom = 30,
    },
    initial_cols = 150,
    initial_rows = 45,
    window_close_confirmation = "NeverPrompt",
    exit_behavior = "Close",
    native_macos_fullscreen_mode = true,
    hide_tab_bar_if_only_one_tab = true,
    cursor_thickness = "0.066cell",

    max_fps = 255
}

```

### Expected Behavior

The output should be updated just as Terminal.app or Kitty.

### Anything else?

Changing the `max_fps` produces no significant difference. The text still updates every 0.9 seconds ish. If increase the output interval to 10000 micro seconds or higher the issue goes away.

**Comment by wez** [comment]
`max_fps` is a throttle that sets the upper bound on the frame rate.
It is used to compute the delay between painting frames so that the frame rate cannot exceed the maximum configured value.
Making it overly large will not accelerate other areas of wezterm.

You may want to try setting `mux_output_parser_coalesce_delay_ms` to something smaller than its default value of `3`, perhaps setting it to 0, to remove the coalescing delay in the output processing layer. That may come at the cost of increased flickering or tearing.

**Comment by BIKA-C** [comment]
Wow, didn't know this setting exist! This fixes the issue. Thank you!
