### ISSUE TITLE
Mouse cursor hide-on-type is too eager

### ISSUE THREAD

**Issue by lnicola** [wez/wezterm#3570]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME Shell

### WezTerm version

wezterm-20230419_232850_fc7f203b-1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Compared to GNOME Terminal, the cursor hiding is less nice:

 - pressing `Ctrl` or `Shift` (to copy or paste something) hides the cursor in WezTerm, but not in GNOME Terminal
 - GNOME Terminal doesn't hide the cursor even after pressing `Ctrl-Shift-C` or `V`
 - I'll update if I notice any differences

### Configuration

no config

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by lnicola** [comment]
I can confirm it's fixed, but the Fedora 38 build failed (because of GitHub throttling?).
