### ISSUE TITLE
Alternative wheel scrolling method

### ISSUE THREAD

**Issue by Felixoid** [wez/wezterm#3571]
Hello

**Is your feature request related to a problem? Please describe.**
As I see in #432, the scroll speed is already configurable. But what about implementing an alternative scrolling method by a modifier?

**Describe the solution you'd like**
[terminator](https://github.com/gnome-terminator/terminator) terminal emulator allows scrolling through the output quickly by using `shift+scroll_wheel`. It scrolls by pages then, instead of lines.

The configurable modifier looks even better, IMHO.

**Comment by wez** [comment]
I think you should be able to configure this for yourself; take a look at:
https://wezfurlong.org/wezterm/config/mouse.html#configuring-mouse-assignments

you'd want to set the action to [ScrollByPage](https://wezfurlong.org/wezterm/config/lua/keyassignment/ScrollByPage.html)
