### ISSUE TITLE
[Feature] Show all panes when using action PaneSelect in a zoomed-in pane

### ISSUE THREAD

**Issue by protiumx** [wez/wezterm#3573]
**Is your feature request related to a problem? Please describe.**
When in `zoom` mode, the action `PaneSelect` only shows the current zoomed panel as option.

**Describe the solution you'd like**
When calling `PaneSelect` all panes should be shown, meaning that the zoom mode must be toggled off if one pane has it activated. This will allow to easily jump to any other pane from a zoomed one.

As the zoom mode must be toggled off to show all panes, there will be 2 possible resolutions
- Toggle zoom mode on the pane selected by the user
- Do nothing. This would be similar to toggling the zoom mode off and changing the focus to the selected pane.

That could be resolved with a new configuration entry if needed.

**Describe alternatives you've considered**
None. At the moment if I want to chose a pane I need to toggle the zoom mode off.

**Comment by wez** [comment]
Oh, I hadn't thought of this. I just pushed a commit that will unzoom prior to showing the pane selector, and then reset the zoom state to the prior value when the action is processed.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the change and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by protiumx** [comment]
Hi @wez, that's awesome!
I just tested the windows nightly, works like a charm 🚀
