### ISSUE TITLE
Windows: progress bar are rendered incorrectly (CR+LF issues?)

### ISSUE THREAD

**Issue by keltia** [wez/wezterm#3576]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

CR+LF lines are rendering incorrectly, probably because there is only LF :)

![3_3  C__windows_System32_WindowsPowerShell_v1 0_powershell exe 21_04_2023 09_15_42](https://user-images.githubusercontent.com/142030/233567935-09cea089-56a2-4a3f-8914-a7549a44a18a.png)
### 

### To Reproduce

Run `rustup update` after any upgrade to the Rust toolchain.

### Configuration

no config

### Expected Behavior

One line with the progress bar updated correctly.

### Anything else?

Thanks for wezterm, I love it.

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.
