### ISSUE TITLE
When switched to greek keyboard layout, shortcuts with `Alt` modifier do not work if `RightAlt` is pressed

### ISSUE THREAD

**Issue by Ernest0x** [wez/wezterm#3578]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Kwin

### WezTerm version

20230419-232850-fc7f203b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

This happens because in Greek layout there is a distinction between `Alt` and `AltGr`, with the `LeftAlt` key being registered as `Alt` while the `RightAlt` is registered as `AltGr`. So, for example, in Greek layout, the shortcut for horizontal split is not working when pressing `RightCtrl + RightShift + RightAlt + %`, whereas the combination `RightCtrl + RightShift + LeftAlt + %` will work. This is also the case with simpler shortcuts like `Alt + Enter` for toggling full screen mode: when switched to Greek keyboard layout, `RightAlt + Enter` does nothing, although `LeftAlt + Enter` works right.

Maybe this kind of issues arise with other keyboard layouts too, if they register any modifier keys used in shortcuts differently than in the common English layouts.

### To Reproduce

Swith to Greek keyboard layout and try to trigger the full-screen mode pressing the `RightAlt + Enter` combination.

### Configuration

```
return {
  scrollback_lines = 20000,
  use_ime = false,
  ssh_domains = {
    {
      name = '****',
      remote_address = '****',
      username = '****',
    },
  },
}
```

### Expected Behavior

Shortcuts that include the `Alt` modifier key should work when pressing either the `LeftAlt` or the `RighAlt` key, no matter what keyboard layout is active. Or, perhaps, `AltGr`, in the context of shortcuts, should be treated as `Alt`.

**Comment by wez** [comment]
I looked at this a bit tonight, am I'm not sure how to proceed. The issue is that xkb doesn't tell us that AltGr is pressed at all, so we have no idea.  I had a go at trying to second guess it by tracking the modifier state in parallel against the new `default_state` but that also does not report the modifier state in the way that I'd expect.

The upshot of this is that without the ability to know that AltGr is pressed we can't reroute the key event handling away from the compose layer.

**Comment by Ernest0x** [comment]
Turning on debug logs, what I notice is that the `RightAlt + Enter` combination does not produce a `KeyEvent` log for the pressing of the `RightAlt` key, although a `RawKeyEvent` log is produced. On the other hand, the `LeftAlt + Enter` combination produces both a `RawKeyEvent` and a `KeyEvent` for the pressing of `LeftAlt`.

`LeftAlt + Enter` combination logs:
``` 
19:13:26.720  DEBUG  wezterm_gui::termwindow                > RawKeyEvent(RawKeyEvent { key: Physical(LeftAlt), modifiers: NONE, phys_code: Some(LeftAlt), raw_code: 64, repeat_count: 1, key_is_down: true, handled: Handled(false) })
19:13:26.720  DEBUG  wezterm_gui::termwindow                > KeyEvent(KeyEvent { key: Alt, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftAlt), modifiers: NONE, phys_code: Some(LeftAlt), raw_code: 64, repeat_count: 1, key_is_down: true, handled: Handled(false) }) })
19:13:33.637  DEBUG  wezterm_gui::termwindow                > RawKeyEvent(RawKeyEvent { key: Physical(Return), modifiers: ALT, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: true, handled: Handled(false) })
19:13:33.637  DEBUG  wezterm_gui::termwindow                > KeyEvent(KeyEvent { key: Char('\r'), modifiers: ALT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: ALT, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: true, handled: Handled(false) }) })
19:13:33.756  DEBUG  wezterm_gui::termwindow                > KeyEvent(KeyEvent { key: Char('\r'), modifiers: ALT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: ALT, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: false, handled: Handled(false) }) })
```

`RightAlt + Enter` combination logs:
```
19:12:19.008  DEBUG  wezterm_gui::termwindow                > RawKeyEvent(RawKeyEvent { key: Physical(RightAlt), modifiers: NONE, phys_code: Some(RightAlt), raw_code: 108, repeat_count: 1, key_is_down: true, handled: Handled(false) })
19:12:19.170  DEBUG  wezterm_gui::termwindow                > RawKeyEvent(RawKeyEvent { key: Physical(Return), modifiers: NONE, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: true, handled: Handled(false) })
19:12:19.170  DEBUG  wezterm_gui::termwindow                > KeyEvent(KeyEvent { key: Char('\r'), modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: NONE, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: true, handled: Handled(false) }) })
19:12:19.328  DEBUG  wezterm_gui::termwindow                > KeyEvent(KeyEvent { key: Char('\r'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: NONE, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: false, handled: Handled(false) }) })
```

Is this missing `KeyEvent` for the pressing of `RightAlt` in the `RightAlt + Enter` combination  what you mean by saying  "xkb doesn't tell us that AltGr is pressed at all"?

Also, I am not sure where the `RawKeyEvent` events come from and where the `KeyEvent` events come from. Are these type of events coming from two different levels (a lower level and a higher level)? 

Is it possible that there is some unwanted filtering in place on what `KeyEvent` events is the WezTerm application listening to? 

Or, if the WezTerm application cannot control the `KeyEvent` events that reach it, could a possible solution be based on taking into account the `RawKeyEvent` events which seem to be always emitted and not depend solely (if that is what is happening now) on the `KeyEvent` events?

**Comment by wez** [comment]
Could you try this with the latest `main`? f09992f70 resolves https://github.com/wez/wezterm/issues/3610 and may impact this.  I haven't looked again at this issue since creating that fix.
