### ISSUE TITLE
Alpha chennel not work on fancy tab bar `titlebar_bg`

### ISSUE THREAD

**Issue by leonasdev** [wez/wezterm#3580]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230420-215610-ff153a92

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When setting the `active_titlebar_bg` property to `rgb(0 0 0 0)` in the `window_frame`, the alpha channel does not seem to have any effect. The fancy tab bar remains opaque, despite the alpha value being set to 0.
![image](https://user-images.githubusercontent.com/39915562/233676703-529de218-c9b0-46d2-b957-61fb6c5c3c6a.png)

### Configuration

```lua
local wezterm = require("wezterm")

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

local customOneHalfDark = wezterm.color.get_builtin_schemes()["OneHalfDark"]
customOneHalfDark.background = "#101010"
config.color_schemes = { ["customOneHalfDark"] = customOneHalfDark }
config.color_scheme = 'customOneHalfDark'
config.window_background_opacity = 0
config.win32_system_backdrop = 'Mica'
config.window_decorations = "INTEGRATED_BUTTONS | RESIZE"

config.window_frame = {
  active_titlebar_bg = "rgba(0 0 0 0)",
}

return config
```

### Expected Behavior

Setting the `active_titlebar_bg` property to `rgb(0 0 0 0)` should make the fancy tab bar transparent, with the alpha channel value of 0.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by leonasdev** [comment]
> This should be resolved now in `main`.
> 
> It typically takes about an hour before commits are available as nightly builds for all platforms. Linux builds are the fastest to build and are often available within about 20 minutes. Windows and macOS builds take a bit longer.
> 
> Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).
> 
> If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.
> 
> If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

I can confirm this issue is fixed.

Thanks for your effort!
