### ISSUE TITLE
Increase padding between undercurl and characters

### ISSUE THREAD

**Issue by JeanMertz** [wez/wezterm#3583]
This is arguably a subjective request, but I find it visually unpleasing that the undercurl in Wezterm touches (and in the case of the underscore, or `g`, overflows) the characters:

<img width="488" alt="Screenshot 2023-04-21 at 21 50 33" src="https://user-images.githubusercontent.com/383250/233722982-302e2208-ff69-4fea-89af-4ffa92177486.png">

It would be great if either (a) the padding was increased a tiny bit, or (b) allow the padding to be configurable (within reason).

If this is technically not possible (e.g. because of the limits of the drawing area on each line), or not desired due to an increase in configurability for something that is a pure cosmetic change) then feel free to close the issue, but I wanted to bring this to your attention and see what your thoughts were.

**Comment by wez** [comment]
See also: https://github.com/wez/wezterm/issues/3157

**Comment by JeanMertz** [comment]
Ah, thanks. Not sure how I could have missed those two options.

Playing around with those settings does make it a bit better, but unfortunately there isn't enough room in the cell to go low enough and still see an actual curly line, instead of a straight line.

Here's with the default settings:

<img width="477" alt="Screenshot 2023-04-21 at 23 59 07" src="https://user-images.githubusercontent.com/383250/233741115-eace9bc6-f203-495e-90de-c5e8693aebdd.png">

Here's with `underline_thickness = "200%"` and `underline_position = -5`:

<img width="471" alt="Screenshot 2023-04-21 at 23 59 31" src="https://user-images.githubusercontent.com/383250/233741201-89d03189-df21-4695-8b5e-8f2070a6d2f5.png">

And here's with`underline_thickness = "200%"` and `underline_position = -10`:

<img width="484" alt="Screenshot 2023-04-21 at 23 59 54" src="https://user-images.githubusercontent.com/383250/233741232-a8b8304e-9a72-46ff-9c6a-9898a23a8721.png">

In terms of distance from the glyphs, the third version is best, as there's a clear separation between the underline and the text, but given the limited space in the cell, the undercurl becomes a straight line, unfortunately.

Either way, I'm much more happy with the compromise in the middle, and given the hard limitations of room within a cell, I'll close this PR, as it appears there is a solution that's as satisfying as it can be in this case.
