### ISSUE TITLE
Tapping with two fingers (right-clicking the mouse) button to open the context menu on the version is causing Wezterm to hang.

### ISSUE THREAD

**Issue by maxim-uvarov** [wez/wezterm#3585]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I tap using two fingers on the version info in Wez-term's about window to open a context menu, the app hangs up.

https://user-images.githubusercontent.com/4896754/233758974-6e06b393-180a-4247-a393-e2c0395de0fb.mp4

I guess there was some functionality on this action before, but now it is broken. In case you are interseted...

### Configuration

```
local wezterm = require 'wezterm'

-- Allow working with both the current release and the nightly
local config = {}
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.default_prog = { '/Users/user/.cargo/bin/nu', '-l'}
config.font = wezterm.font { family = 'JetBrains Mono' }
config.font_size = 16.0
config.initial_cols = 120
config.initial_rows = 120
config.skip_close_confirmation_for_processes_named = {
  'bash',
  'sh',
  'zsh',
  'fish',
  'tmux',
  'nu',
}
config.scrollback_lines = 10000
config.keys = {
  {
    key = 'Enter',
    mods = 'ALT',
    action = wezterm.action.DisableDefaultAssignment,
  },
}
config.mouse_wheel_scrolls_tabs = false
config.quick_select_patterns = {
  "[0-9A-F]{64}",
}
config.debug_key_events = true     
return config
```

**Comment by wez** [comment]
"Fixed" by removing the about dialog in dc2cd706dcd630dcca1d0bae23b73f9ae65ec121
Instead you can click on the menu item that replaces it to copy the version number, if desired.
