### ISSUE TITLE
Background is not dynamically reloaded

### ISSUE THREAD

**Issue by mpasa** [wez/wezterm#3592]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230421-075330-e0a92c73

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The window background color is not updated dynamically either using `automatically_reload_config`, calling `wezterm.action.ReloadConfiguration` manually. A new window is needed for the update to take place.

This also doesn't work using Dynamic Color Escape Sequences as shown in the [docs](https://wezfurlong.org/wezterm/config/appearance.html#dynamic-color-escape-sequences). In this case, text color changes but not the background.

### To Reproduce

Start with a basic configuration:

```
local wezterm = require 'wezterm'

return {
  colors = {
    background = '#ff2d2d',
  },
  keys = {
    {
      key = 'r',
      mods = 'CMD|SHIFT',
      action = wezterm.action.ReloadConfiguration,
    },
  }
}
```

Then, change `colors.background` to any value and reload the configuration with `cmd+shift+r`. No background changes will apply. Finally, create a new window with `cmd+n` to see the changes.

### Configuration

```
local wezterm = require 'wezterm'

return {
  colors = {
    background = '#ff2d2d',
  },
  keys = {
    {
      key = 'r',
      mods = 'CMD|SHIFT',
      action = wezterm.action.ReloadConfiguration,
    },
  }
}
```

### Expected Behavior

The background should be updated dynamically.

**Comment by wez** [comment]
I can't reproduce this with the steps you shared; changing the config file will immediately change the colors.

Note that if you use escape sequences to modify the color palette, the current color palette is "forked" and frozen at the time the first escape sequence is used and ownership of the color palette then belongs to the terminal emulator until the color palette is reset to its default state (either via a full reset or via `OSC 104` `\e]104\e\\`), at which time the configured color scheme will apply again.

**Comment by mpasa** [comment]
@wez Thank you. You're right. It seems this only happens when `tmux` is attached. I'm using version 3.3a without any customizations. My `$TERM` was `wezterm` but I get the same behavior with `screen-256color`. I suppose this is outside of the scope of wezterm, so feel free to close.
