### ISSUE TITLE
Custom actions/commands for the Command Palette (without key binding)

### ISSUE THREAD

**Issue by JoshuaWebb** [wez/wezterm#3595]
**Is your feature request related to a problem? Please describe.**
With the recent introduction of the command palette, it would be nice to be able to register actions without requiring a specific key binding for them; for actions that I do rarely enough to not warrant wasting a unique key binding on.

**Describe the solution you'd like**
A config section to register arbitrary actions like the current `keys` section but that doesn't require a key binding for the entries, I'd like to be able to give the action a label/name/description to customize what appears in the palette (also impacts the filtering/searching). Alternatively, allow them to be defined in the same `keys` section but without a binding (or a special "None" binding which allows duplicates); this would probably make it easier for users to enable/disable a key binding for the action.

e.g.
```lua
custom_actions = {
    { description = 'Rename tab',
      action = act.PromptInputLine {
        description = 'Enter new name for tab',
        action = wezterm.action_callback(function(window, pane, line)
          if line then
            window:active_tab():set_title(line)
          end
        end),
      },
    },
}
```
or
```lua
keys = {
  { key = wezterm.NoKeyBinding,
    description = 'Rename tab',
    action = act.PromptInputLine {
      description = 'Enter new name for tab',
      action = wezterm.action_callback(function(window, pane, line)
        if line then
          window:active_tab():set_title(line)
        end
      end),
    },
  },
}
```

**Describe alternatives you've considered**
At the moment I just assign a ridiculous unused key binding for the commands I want to use, and thankfully the command palette filters by the 'description' field of the `PromptInputLine` action, but it doesn't display this description in the palette.

![image](https://user-images.githubusercontent.com/6722399/233263309-e64a2b10-faa1-4925-b5ce-1fed7d154a56.png)
![image](https://user-images.githubusercontent.com/6722399/233264921-cf252af0-26fb-4ae7-b1bb-4d5ccae2f03e.png)

**Additional context**
Example setup for using the current work around
```lua
keys = {
    { key = 'F24',
      mods = 'ALT|CTRL|SHIFT',
      action = act.PromptInputLine {
        description = 'Rename tab',
        action = wezterm.action_callback(function(window, pane, line)
          if line then
            window:active_tab():set_title(line)
          end
        end),
      },
    },
    { key = 'F23',
      mods = 'ALT|CTRL|SHIFT',
      action = act.PromptInputLine {
        description = 'Some other command',
        action = wezterm.action_callback(function(window, pane, line)
          if line then
            wezterm.log_info(line);
          end
        end),
      },
    },
}
```

**Comment by wez** [comment]
What I have in mind for this is an event that will be passed the current window and pane and returns a set of actions that should be added to the palette.
That would allow context sensitive/dependent actions to be produced.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/window-events/augment-command-palette.html is now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by joshua-webb-dns** [comment]
The up/down arrow keys in the command palette don't seem to work for me in the latest nightly (`wezterm 20230423-174840-5c2e3fe8`) even when staring with `--skip-config`

**Comment by JoshuaWebb** [comment]
Seems to work as advertised (separate up/down arrow keys bug notwithstanding #3617), although if you don't register anything for the new event, you get a warning every time you open the command palette.

```
16:29:02.641 WARN wezterm_gui::termwindow::palette > augment-command-palette: error converting Lua nil to Rust Type (Cannot convert `Null` to `Vec`)
```

**Comment by wez** [comment]
The warning should now be resolved in `main`
