### ISSUE TITLE
Build macos app to "build" folder and add mac app build instruction to web page

### ISSUE THREAD

**Issue by erf** [wez/wezterm#360]
**Is your feature request related to a problem? Please describe.**

I noticed when i call `./ci/deploy.sh` the build is in the current folder, making the project dir messy.

I also noticed the `./ci/deploy.sh` call is missing in the [Build from source](https://wezfurlong.org/wezterm/install/source.html) doc.

**Describe the solution you'd like**

Add the macos app builds to a "build" folder.

Add the `./ci/deploy.sh` call to the [Build from source](https://wezfurlong.org/wezterm/install/source.html) doc?

**Comment by erf** [comment]
BTW maybe it would be helpful to add a `INSTALL.md` file to the repo?

**Comment by wez** [comment]
I'm not sure that I want to change anything here; I don't want to go to a lot of effort for something that is a temporary workaround until rust 1.49, and the installation instructions in the docs on the website are detailed enough that I think having another copy of the same thing will just generate more work and/or drift and become stale.
