### ISSUE TITLE
Strikethrough and under-curl not rendering

### ISSUE THREAD

**Issue by knmac** [wez/wezterm#3602]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Strikethrough and under-curl are not rendering correctly, using [JetBrainsMono Nerd Font](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/JetBrainsMono.zip). I am putting a comparison between Kitty (left) a Wezterm (right) here for an example.

![font_render](https://user-images.githubusercontent.com/9382409/233866168-46a49fc6-9320-42e1-9ffe-27ae6f690be6.png)

### Configuration

```lua
config.font = wezterm.font_with_fallback {
    'JetBrainsMono Nerd Font',  -- custom font
    'JetBrains Mono',  -- built-in font
}
```

**Comment by wez** [comment]
See:
* https://wezfurlong.org/wezterm/faq.html#how-do-i-enable-undercurl-curly-underlines

**Comment by knmac** [comment]
Silly me. Thanks!
