### ISSUE TITLE
Up/Down arrow keys no longer work in Command Palette on Windows in latest Nightly

### ISSUE THREAD

**Issue by JoshuaWebb** [wez/wezterm#3617]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230424-221350-2f0bcb3c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Pressing the up and down arrow keys in the Command Palette no longer changes the selection.

NOTE: Using the arrow keys on the numpad with num lock OFF, however, does still work as expected in the effected versions.

### To Reproduce

1. Press `Ctrl + Shift + P` to open the command palette
2. Press the down arrow key

### Configuration

no config

### Expected Behavior

The selected item should change when the arrow keys are pressed.

### Anything else?

I compiled from source and ran `git bisect` and narrowed down the version where this behaviour first stopped working:

2dcf7ad98dde802bb92cbf78a98662ea7224842a was the commit that appears to have broken the arrow keys (with 397593be5cbe045530843ca525191c6e52ccf7db being the last commit where they worked).

```bash
10:47:53 [6.580s] {(397593be5...)|BISECTING} /d/Projects/contrib/wezterm$ git bisect log
git bisect start
# bad: [154dfae9b9e81db6d046e15cd317bbd22b106e69] docs: changelog for #3555 #3613
git bisect bad 154dfae9b9e81db6d046e15cd317bbd22b106e69
# good: [69ae847273aa2b0a64bdb07cf19d3f6fbaaa6b71] windows: fix: mess up full screen mode on config reload
git bisect good 69ae847273aa2b0a64bdb07cf19d3f6fbaaa6b71
# bad: [f627d6d704c56017ff4ec80dc11be16cd9a9011b] windows: improve hit test for integrated max button
git bisect bad f627d6d704c56017ff4ec80dc11be16cd9a9011b
# bad: [119036ab2a03a4ac2505df644950d78ba2001d61] Do not wait indefinitely when being drip fed input.
git bisect bad 119036ab2a03a4ac2505df644950d78ba2001d61
# bad: [a9165ae4c4a95e84b5b1347c3d8a9194a90cb4a5] kitty keeb: fixup tests
git bisect bad a9165ae4c4a95e84b5b1347c3d8a9194a90cb4a5
# good: [8bb39bd6f3044d2ab42ef76d3667569cf0cfef43] fixup kitty keyup events for alphabetical keys
git bisect good 8bb39bd6f3044d2ab42ef76d3667569cf0cfef43
# bad: [2dcf7ad98dde802bb92cbf78a98662ea7224842a] keyboard: plumb more modifier+state information through
git bisect bad 2dcf7ad98dde802bb92cbf78a98662ea7224842a
# good: [397593be5cbe045530843ca525191c6e52ccf7db] kitty keeb: fixup shifted character encoding
git bisect good 397593be5cbe045530843ca525191c6e52ccf7db
# first bad commit: [2dcf7ad98dde802bb92cbf78a98662ea7224842a] keyboard: plumb more modifier+state information through
```

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
