### ISSUE TITLE
conpty: Images rendered by imgcat is cut off by cmd.exe or wsl prompts

### ISSUE THREAD

**Issue by nhat-vo** [wez/wezterm#3624]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230424-110818-dc2cd706

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

It seems that in Windows, `wezterm imgcat` is cutoff by the prompt of `cmd.exe` or in `wsl`.
![image](https://user-images.githubusercontent.com/30724347/234560055-b01b1114-59b9-46bb-a89d-b0e69fc6f4ef.png)
![image](https://user-images.githubusercontent.com/30724347/234561024-420f779b-ab97-4554-b972-06f2c8608ac0.png)

### To Reproduce

On windows, open wezterm in `cmd.exe` or `wsl`. Then run `wezterm imgcat` on a relatively large image.

### Configuration

No config.

### Expected Behavior

The prompt should be printed below the image instead of cutting it.

**Comment by nhat-vo** [comment]
Thanks for the reply. I am trying to connect using `wezterm ssh` to the server running in wsl environment, but when I do `wezterm imgcat image`, it gives me a blank space like this
![image](https://user-images.githubusercontent.com/30724347/234787240-a077a676-7c3c-40b2-b5b6-62b8e9e2cdb1.png).

The log give the error
```
ERROR  wezterm_gui::glyphcache > Unable to move file data to blob manager: Storage has not been initialized
```
Do you know what might have happened?

**Comment by wez** [comment]
Ah, yes; that's a bug that I have now fixed, and that will be available to download within the next hour or so.

**Comment by wez** [comment]
To clarify, that fix will be in a nightly download available from https://wezfurlong.org/wezterm/install/windows.html

**Comment by adelarsq** [comment]
Hello @wez. I have confirmed that its working on nightly for PowerShell:

![image](https://github.com/wez/wezterm/assets/430272/cb6d1823-98ec-4a63-a7ed-d8967c41eb53)

For [clink](https://github.com/chrisant996/clink) shows like this:

![image](https://github.com/wez/wezterm/assets/430272/4e775ab1-f656-4e90-9aaa-4304d43482be)

I will follow this issue to help on the tests.

**Comment by wez** [comment]
@adelarsq I just pushed a commit that I think might help with the presentation you saw with clink.

It typically takes about an hour before commits are available as nightly builds for all platforms. 

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (a `.zip` file on Windows) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

**Comment by adelarsq** [comment]
@wez Thanks for looking into that.  I did some tests with nightly.

With clink/cmd shows the same behaviour:

<img width="944" alt="image" src="https://github.com/wez/wezterm/assets/430272/67615d6f-1359-4749-8ec5-24c735cc60cb">

But there is some odd behaviour with PowerShell. Calling imgcat on the first line shows like this:

<img width="949" alt="image" src="https://github.com/wez/wezterm/assets/430272/997c3504-7545-4bef-963c-bea5a3ca3df2">

**Environment:**
- Clink
   - Clink v1.5.1.1e9e51
- PowerShell

| Name                       |   Value                      |
|----------------------------|------------------------------|
| PSVersion                  | 7.3.6                        |
| PSEdition                  | Core                         |
| GitCommitId                | 7.3.6                        |
| OS                         | Microsoft Windows 10.0.22621 |
| Platform                   | Win32NT                      |
| PSCompatibleVersions       | {1.0, 2.0, 3.0, 4.0…}        |
| PSRemotingProtocolVersion  | 2.3                          |
| SerializationVersion       | 1.1.0.1                      |
| WSManStackVersion          | 3.0                          |

**Comment by wez** [comment]
@adelarsq Thanks! Please confirm the wezterm version you're using; open the debug overlay (CTRL-SHIFT-L) and share the version info from there

**Comment by wez** [comment]
For pwsh, if you scroll up, does the scrollback look correct and fully intact?

**Comment by adelarsq** [comment]
> For pwsh, if you scroll up, does the scrollback look correct and fully intact?

Yes. It shows right:

<img width="684" alt="image" src="https://github.com/wez/wezterm/assets/430272/49c08159-5a91-4704-a9b1-27d77198c8a8">

The scroll is being done using the previous amout of lines. So for 4 lines:

<img width="580" alt="image" src="https://github.com/wez/wezterm/assets/430272/04c7df89-f907-4561-9ea1-29865a0231ee">

Shows like this:

<img width="617" alt="image" src="https://github.com/wez/wezterm/assets/430272/266fd233-e4d0-4bcc-b7c5-d9460e8e6cbd">

The picture height is exactly the previous 4 lines.

**Comment by wez** [comment]
Thanks for confirming! Let's close this!
