### ISSUE TITLE
Readability issues when cursor is on current cell with Snazzy and Snazzy (Gogh) themes

### ISSUE THREAD

**Issue by devmatteini** [wez/wezterm#3627]
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

I'm on Ubuntu 22.04/22.10 with X11/Wayland.

### WezTerm version

wezterm 20230425-083942-6686adba

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using the default `Snazzy` theme, you can't read the character under the cursor.

In this example, I typed `ll`, but you can't really read the second `l`. 
![image](https://user-images.githubusercontent.com/48568026/234712638-39a4a33f-5831-4da4-b669-5123c6144ab3.png)

The same using `Snazzy (Gogh)`:
![image](https://user-images.githubusercontent.com/48568026/234712974-3907be51-900b-482a-9bc0-756324b5e6e9.png)

### To Reproduce

1. Set `color_scheme = "Snazzy"` in wezterm.lua
2. Open a terminal and type any words
3. Move the cursor over a character
4. You cannot read that character

### Configuration

https://github.com/devmatteini/dotfiles/blob/main/config/wezterm/wezterm.lua

### Expected Behavior

When moving the cursor, you should be able to read the character under the cursor

### Anything else?

I did some tests in wezterm.lua to try to fix this:

```lua
  color_scheme = "Snazzy",
  colors = {
    cursor_fg = "#1e1f29" -- same as background
    -- https://github.com/wez/wezterm/blob/6686adba044b5ece57a3285a14f93df01493c888/assets/colors/Snazzy.toml#L12
  },
```
This is the result:
![image](https://user-images.githubusercontent.com/48568026/234713586-2d674074-d503-4d00-829c-f8fec39488f8.png)

Instead, for `Snazzy (Gogh)`:

```lua
  color_scheme = "Snazzy (Gogh)",
  colors = {
    cursor_bg = '#eff0eb', -- same as foreground
    cursor_fg = '#282a36', -- same as background
  },
-- https://github.com/wez/wezterm/blob/6686adba044b5ece57a3285a14f93df01493c888/assets/colors/gogh/Snazzy%20(Gogh).toml
```
![image](https://user-images.githubusercontent.com/48568026/234714162-8ff48fe0-288c-4a83-b6ae-4459fc7b13d1.png)

If you think these changes are fine, I can submit a PR

**Comment by wez** [comment]
That scheme comes from https://gogh-co.github.io/Gogh/ so if you feel like it needs to be changed, please submit those changes there and we can re-sync them once they have been accepted.

**Comment by devmatteini** [comment]
I'm using the `Snazzy (Gogh)` on Gnome Terminal, but I have no issues with the cursor.
I'm not sure this issue is on their side

**Comment by wez** [comment]
You may want to enable:
* https://wezfurlong.org/wezterm/config/lua/config/force_reverse_video_cursor.html

**Comment by devmatteini** [comment]
Yes, this solves the issues with both themes.Thanks for the help!
