### ISSUE TITLE
Focus on 'Zen Mode' , but Windows 11 Clipboard content could not paste.

### ISSUE THREAD

**Issue by ndzuki** [wez/wezterm#3629]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

System Env: Windows 11 wsl2 
Linux Distro: Ubuntu-22.04
Issue:
When Focus on 'Zen Mode'， my clipboard content could not paste in terminal.
But switch noarml mode, clipboard content can paste in.

### Configuration

local wezterm = require("wezterm")

local wsl_domains = wezterm.default_wsl_domains()

for _, domain in ipairs(wsl_domains) do
        if domain.name == "WSL:Ubuntu-22.04" then
                domain.default_prog = { "zsh", "-l" }
        end
end

wezterm.on("gui-startup", function(cwd)
        local _, _, window = wezterm.mux.spawn_window(cwd or {})
        window:gui_window():maximize()
end)

return {
  automatically_reload_config = true,
        adjust_window_size_when_changing_font_size = false,
        audible_bell = "Disabled",
        -- colors = {
        --      foreground = "#C0C5CE",
        --      background = "#2B303B",
        --
        --      ansi = {
        --              "#4C4C4C", -- black
        --              "#FF3C3C", -- red
        --              "#0DBC79", -- green
        --              "#E5E510", -- yellow
        --              "#3B8EEA", -- blue
        --              "#BC3FBC", -- magenta
        --              "#11A8CD", -- cyan
        --              "#E5E5E5", -- whitei = {
        --      },
        --      brights = {
        --              "#666666", -- black
        --              "#F14C4C", -- red
        --              "#23D18B", -- green
        --              "#F5F543", -- yellow
        --              "#3B8EEA", -- blue
        --              "#D670D6", -- magenta
        --              "#29B8DB", -- cyan
        --              "#E5E5E5", -- white
        --      },
        -- },
        -- background = {
        --      {
        --              source = {
        --                      File = "C:\\Users\\28124\\OneDrive\\鍥剧墖\\wp4674097.webp",
        --              },
        --              horizontal_align = "Center",
        --              vertical_align = "Middle",
        --              height = "Contain",
        --              width = "Contain",
        --              repeat_x = "NoRepeat",
        --              repeat_y = "NoRepeat",
        --              opacity = 0.5,
        --      },
        -- },
        color_scheme = "duckbones",
  window_background_opacity = 0.85,
        exit_behavior = "Close",
        font = wezterm.font({
                family = "mononoki NF",
                weight = "Bold",
                stretch = "Normal",
                style = "Italic",
        }),
        font_size = 14,
  bold_brightens_ansi_colors = true,
        force_reverse_video_cursor = true,
        hide_tab_bar_if_only_one_tab = true,
        -- disable_default_key_bindings = true,
        -- keys = {
        --      { action = wezterm.action.CopyTo("Clipboard"), mods = "CTRL|SHIFT", key = "C" },
        --      { action = wezterm.action.DecreaseFontSize, mods = "CTRL", key = "-" },
        --      { action = wezterm.action.IncreaseFontSize, mods = "CTRL", key = "=" },
        --      { action = wezterm.action.Nop, mods = "ALT", key = "Enter" },
        --      { action = wezterm.action.PasteFrom("Clipboard"), mods = "CTRL|SHIFT", key = "V" },
        --      { action = wezterm.action.ResetFontSize, mods = "CTRL", key = "0" },
        --      { action = wezterm.action.ToggleFullScreen, key = "F11" },
        -- },
        scrollback_lines = 10000,
        show_update_window = true,
        use_dead_keys = false,
        unicode_version = 13,
        window_close_confirmation = "NeverPrompt",
        window_padding = {
                left = 0,
                right = 0,
                top = "0.2cell",
                bottom = 0,
        },
        wsl_domains = wsl_domains,
        -- reference: https://github.com/wez/wezterm/issues/1242
        default_domain = "WSL:Ubuntu-22.04",
}

**Comment by wez** [comment]
Could you explain what you mean by zen mode?
