### ISSUE TITLE
A configurable list of symbols that are or aren't considered as a part of word for Word selecting

### ISSUE THREAD

**Issue by Felixoid** [wez/wezterm#3631]
Hello, couldn't find the answer in docs, issues or discussions.

**Is your feature request related to a problem? Please describe.**
The other terminals, for example terminator, has a configuration to chose which symbols are and which aren't suppose to be selected by double click, see the screenshot
![image](https://user-images.githubusercontent.com/3025537/234906875-47b1626d-8658-45f2-96a5-135a08e9c40e.png)

**Describe the solution you'd like**
It would be nice to have a similar setting and/or documentation for it.

**Comment by wez** [comment]
we have https://wezfurlong.org/wezterm/config/lua/config/selection_word_boundary.html which is similar in purpose, but operates on boundaries rather inclusions.

**Comment by Felixoid** [comment]
That's exactly what I've been looking for. THere's no word `symbol` on the page, I guess it's why I couldn't find it.

Thank you!
