### ISSUE TITLE
Font scaling has no effect on some glyphs

### ISSUE THREAD

**Issue by cusxio** [wez/wezterm#3632]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

![CleanShot 2023-04-27 at 23 12 07](https://user-images.githubusercontent.com/6487613/234906983-8d107cc7-7176-4aa4-8c4f-8ccf1fe7fff4.png)

As you can see in the image, the `Close` button on the bufferline and the `Git Add` button on the statusline did not become smaller as a scale of `0.5` was used. You can also see that the other icons like `Folder` do become smaller.

### To Reproduce

Add a scale of `0.5` to `Symbols Nerd Font Mono` and some glyphs will not scale accordingly.

### Configuration

```lua
local wezterm = require("wezterm")

local fontFamily = "JetBrains Mono"
local fontWeight = "Medium"

return {
  font = wezterm.font_with_fallback({
    {
      family = fontFamily,
      weight = fontWeight,
    },
    {
      family = "Symbols Nerd Font Mono",
      scale = 0.5,
    },
  }),
  font_rules = {
    {
      -- italic
      intensity = "Normal",
      italic = true,
      font = wezterm.font({
        family = fontFamily,
        weight = fontWeight,
        italic = false,
      }),
    },
    {
      -- bold
      intensity = "Bold",
      italic = false,
      font = wezterm.font({
        family = fontFamily,
        weight = fontWeight,
      }),
    },
    {
      -- italic bold
      intensity = "Bold",
      italic = true,
      font = wezterm.font({
        family = fontFamily,
        weight = fontWeight,
        italic = false,
      }),
    },
  },
  font_size = 15.0,
  --
  hide_tab_bar_if_only_one_tab = true,
  use_fancy_tab_bar = false,
  window_padding = {
    top = 0,
    right = 0,
    bottom = 0,
    left = 0,
  },
  -- force_reverse_video_cursor = true,
  color_scheme = "kanagawa",
  window_decorations = "RESIZE",
  -- allow_square_glyphs_to_overflow_width = "Never",
}

```

### Expected Behavior

All glyphs should scale.

### Anything else?

Problematic glyphs

```bash
 ϟ wezterm ls-fonts --text ''
LeftToRight
 0     \u{f658}     x_adv=8  cells=1  glyph=close-circle,2461 wezterm.font("Symbols Nerd Font Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/x/Library/Fonts/Symbols-1000-em Nerd Font Complete Mono.ttf, CoreText

 ϟ wezterm ls-fonts --text ''
LeftToRight
 0     \u{f0fe}     x_adv=8  cells=1  glyph=f0fe,1447 wezterm.font("Symbols Nerd Font Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/x/Library/Fonts/Symbols-1000-em Nerd Font Complete Mono.ttf, CoreText
```

Working glyphs

```bash
 ϟ wezterm ls-fonts --text ''
LeftToRight
 0     \u{e5fe}     x_adv=8  cells=1  glyph=i_custom_folder_open,461  wezterm.font("Symbols Nerd Font Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/x/Library/Fonts/Symbols-1000-em Nerd Font Complete Mono.ttf, CoreText

 ϟ wezterm ls-fonts --text ''
LeftToRight
 0     \u{e5ff}     x_adv=8  cells=1  glyph=i_custom_folder,462  wezterm.font("Symbols Nerd Font Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/x/Library/Fonts/Symbols-1000-em Nerd Font Complete Mono.ttf, CoreText
```

**Comment by wez** [comment]
Take a look at:
* https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html

**Comment by cusxio** [comment]
I've actually tried that config before, as you can see in the last line of my `wezterm.lua`.

However, after using `allow_square_glyphs_to_overflow_width = "Never"`, the `scale` still does not have an effect on some glyphs.

**Comment by cusxio** [comment]
Closed, not a `wezterm` issue, upon further debugging, it's due to [bold and italic](https://github.com/AstroNvim/AstroNvim/blob/08a57a6c80b8397d24f0d98c421c58124cf937c4/lua/astronvim/utils/status.lua#L85-L91) attributes in `heirline`.
