### ISSUE TITLE
Unexpeced characters '½N½N½N½N½N½N½N½' are input when scoll the mouse

### ISSUE THREAD

**Issue by peng530** [wez/wezterm#3638]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230427-063511-9bc7de70

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When scoll the mouse wheel or click mouse, some unexpected characters are input.
![image](https://user-images.githubusercontent.com/6337311/235045123-4185f35f-0343-4b14-a1fe-c7c74e938436.png)

### To Reproduce

1. ssh to a remote PC
2. open VIM and open a file for edit
3. make a team call and minimize the team call window, a small square meeting window will be always on top.
4. scoll the mouse wheel and move between wezterm and team meeting small window

Issue can be easily duplicated with steps above. It can also be observed in some other cases.

An easy way to duplicate this issue:
1. ssh to a remote PC
2. open VIM and press ':' to enter into command mode
3. Scroll mouse wheel and move mouse between wezterm and system task bar.

### Configuration

no config

**Comment by wez** [comment]
What OS is running on the remote PC?
Try setting: https://wezfurlong.org/wezterm/config/lua/config/allow_win32_input_mode.html to false

**Comment by peng530** [comment]
SSH version: OpenSSH_for_Windows_9.2p1, LibreSSL 3.6.1, from powershell.
And remote shell is tcsh.
Is there a way to diable mouse reporting and focus tracking?

**Comment by peng530** [comment]
> What OS is running on the remote PC? Try setting: https://wezfurlong.org/wezterm/config/lua/config/allow_win32_input_mode.html to false

Thanks for suggestion. Issue still can be duplicated with allow_win32_input_mode=false

**Comment by wez** [comment]
> Is there a way to diable mouse reporting and focus tracking?

https://vi.stackexchange.com/a/18161

**Comment by peng530** [comment]
> > Is there a way to diable mouse reporting and focus tracking?
> 
> https://vi.stackexchange.com/a/18161

If disable as the guide, issue cannot be duplicated. But the mouse behavior is changed. It looks like wezterm has different implementation on the mouse reporting. If disable mouse reporting and focus tracking at vim, it is still able to scroll in vim from wezterm while it is not able to from putty.

**Comment by peng530** [comment]
The issue is related to ttymouse setting in VIM. The default setting of ttymouse is xterm, which causes this issue. If I change ttymouse to sgr, issue cannot be reproduced.
