### ISSUE TITLE
[low priority] Nightly build release every 1 or two days

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#364]
Is it possible to release nightly build every 1-2 days or every 3-5 commits? Currently, I am using Linux and have a limited storage capacity. So I would like to not install rust toolchain if possible. To prevent space wastage in Github. keeping only 2 or 3 latest nightly builds are enough. Thanks a lot and keep up the good work! :-)

Edit: I am really sorry about the label. This wasn't a bug or issue and I select the third one. I probably should have selected "blank issue".

Edit-2: I am using Arch Linux, btw.

**Comment by wez** [comment]
Despite the name, nightly is actually built and published hourly.  Are you asking for more or less frequent nightly builds?

**Comment by wez** [comment]
I'm also unclear on how to the build frequency affects your local storage; presumably you can pull at a frequency that works for you?

**Comment by MuhammedZakir** [comment]
> Despite the name, nightly is actually built and published hourly. Are you asking for more or less frequent nightly builds?
I presume `wezterm-nighly-bin` (AUR) downloads artifacts from here [1], but it was released many months ago. Maybe I misunderstood something?

[1] https://github.com/wez/wezterm/releases/nightly

> I'm also unclear on how to the build frequency affects your local storage; presumably you can pull at a frequency that works for you?

I was talking about building from source. The one I am using currently has a low spec, so I don't want to install any build tools (or anything that uses a lot of space) unless necessary.

**Comment by MuhammedZakir** [comment]
> > Despite the name, nightly is actually built and published hourly. Are you asking for more or less frequent nightly builds?
> 
> I presume `wezterm-nighly-bin` (AUR) downloads artifacts from here [1], but it was released many months ago. Maybe I misunderstood something?
> 
> [1] https://github.com/wez/wezterm/releases/nightly
>  _--snip--_

Is this the up-to-date version or is nightly published elsewhere?

**Comment by wez** [comment]
CI updates the `nightly` release on github continuously (currently: hourly).
The `wezterm-nightly-bin` AUR always installs the current nightly release at the time it is installed.

**Comment by MuhammedZakir** [comment]
> CI updates the `nightly` release on github continuously (currently: hourly).
> The `wezterm-nightly-bin` AUR always installs the current nightly release at the time it is installed.

Okay! Thanks! I was confused when I saw release date `Jun 27, 2019`. Closing this.
