### ISSUE TITLE
Background color different when running neovim inside tmux

### ISSUE THREAD

**Issue by JoyceBabu** [wez/wezterm#3649]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230427-063511-9bc7de70

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

My neovim theme background color is different when running vim inside `tmux`. This does not happen with iTerm2 or Kitty. But the issue happens on macOs built-in Terminal too.

WezTerm -> nvim

<img width="900" alt="image" src="https://user-images.githubusercontent.com/502942/235362761-6c358004-b24d-4f2d-be45-e342e0b5be22.png">

WezTerm -> tmux -> nvim

<img width="884" alt="image" src="https://user-images.githubusercontent.com/502942/235362851-86c89b2d-5806-44c6-824b-9daab0f4cbed.png">

Kitty -> tmux -> nvim

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/502942/235363008-eace8b36-b238-41d3-bf7b-d0e772127f4c.png">

iTerm2 -> tmux -> nvim

<img width="953" alt="image" src="https://user-images.githubusercontent.com/502942/235363090-16a35cf8-22b2-4133-bf17-46190b5594ba.png">

### Configuration

no config

**Comment by wez** [comment]
https://stackoverflow.com/a/41786092/149111
