### ISSUE TITLE
Debian Bookworm/Sid - libssl1.1 - dependency depreciated/removed from repo

### ISSUE THREAD

**Issue by bladecoates** [wez/wezterm#3682]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

I run Debian Testing/Unstable. I decided to do a fresh install with the latest iso bypassing the upgrade from stable path that I normally take. 

Attempted to install with both the normal and nightly Debian 11 *.deb downloads listed on the site of today.

It seems that libssl1.1 has been depreciated/removed as of Dec 2022 from the testing/unstable repo and is no longer being built. 

Dependencies will need to be updated to accommodate this for bookworm and future releases of Debian and Debian derivatives.

Excerpt from [removals-2022.txt](https://ftp-master.debian.org/removals-2022.txt)

```
[Date: Sat, 31 Dec 2022 16:10:17 -0000] [ftpmaster: Scott Kitterman]
Removed the following packages from unstable:

libcrypto1.1-udeb |   1.1.1o-1 | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
libssl1.1-udeb |   1.1.1o-1 | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x

------------------- Reason -------------------
[auto-cruft] NBS (no longer built by openssl)
----------------------------------------------
=========================================================================
=========================================================================
[Date: Sat, 31 Dec 2022 16:10:56 -0000] [ftpmaster: Scott Kitterman]
Removed the following packages from unstable:

 libssl1.1 |   1.1.1o-1 | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x

------------------- Reason -------------------
[auto-cruft] NBS (no longer built by openssl)
----------------------------------------------
```

### WezTerm version

N/A - Latest release and nightly for Debian 11 as of 2023-05-04

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Unable to install due to the dependency libssl1.1 being removed from bookwork/sid repo/archive as of Dec 2022

### To Reproduce

Install latest Debian Bookworm in VM with the latest weekly/daily testing iso. Attempt to install release or nightly deb listed on main website. 

### Configuration

N/A

### Expected Behavior

N/A

**Comment by wez** [comment]
Does the nightly build of the .deb install successfully?

**Comment by bladecoates** [comment]
> 

Only if I use the latest Ubuntu installer wezterm-nightly.Ubuntu22.04.deb, expected as it would be based on Debian somewhere between Bullseye and now. This is more of a documentation issue or needing a Debian 12 spot. I guess since I did a clean install to Bookworm/sid directly instead of the upgrade from bullseye dance this time, I didn't have an old version of libssl1.1 hanging around as normally, the Debian 11 *.deb worked fine

**Comment by wez** [comment]
OK, so the issue is that the version built for the historical tag no longer operates on the current version of Debian 11.
The resolution is: use the nightly build of wezterm until the next version of wezterm is tagged.
