### ISSUE TITLE
Pasting large amounts of text causes issues with Helix

### ISSUE THREAD

**Issue by davidarmstronglewis** [wez/wezterm#3683]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If you paste a long enough section of text into the Helix editor using Wezterm you will see the text has been scrambled. Using other terminal emulators (I've tested Terminal.app, iTerm.app, and Alacritty) you will not see this issue presented.

### To Reproduce

Open the latest stable Helix editor and paste the following into it using WezTerm:

```
1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
2. Massa ultricies mi quis hendrerit dolor magna eget est lorem
3. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl.
4. Et netus et malesuada fames ac turpis egestas.
5. Nisi scelerisque eu ultrices vitae.
6. A diam sollicitudin tempor id eu nisl nunc mi ipsum.
7. In aliquam sem fringilla ut morbi tincidunt augue.
8. Rutrum quisque non tellus orci ac auctor.
10. Vulputate mi sit amet mauris commodo quis imperdiet.
11. Ut sem viverra aliquet eget sit.
12. Eros donec ac odio tempor orci dapibus ultrices in.
13. Scelerisque purus semper eget duis.
14. Sed cras ornare arcu dui.
15. Vel quam elementum pulvinar etiam non quam lacus.
16. Non sodales neque sodales ut etiam sit amet nisl.
17. Integer quis auctor elit sed
18. Viverra maecenas accumsan lacus vel facilisis.
19. Ut consequat semper viverra nam libero.
20. Commodo sed egestas egestas fringilla.
21. In egestas erat imperdiet sed euismod nisi porta.
22. Sed augue lacus viverra vitae congue eu consequat.
23. Elit duis tristique sollicitudin nibh sit amet.
24. Mauris nunc congue nisi vitae suscipit.
25. Varius quam quisque id diam vel quam.
26. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin.
27. Consequat nisl vel pretium lectus.
28. Lacus suspendisse faucibus interdum posuere lorem ipsum.
29. Sit amet cursus sit amet dictum sit amet.
30. In dictum non consectetur a erat nam at.
31. Dui accumsan sit amet nulla facilisi morbi tempus.
32. Sit amet nisl purus in.
33. Feugiat pretium nibh ipsum consequat nisl.
34. Eget felis eget nunc lobortis mattis aliquam.
35. Vitae semper quis lectus nulla.
36. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum.
37. Risus in hendrerit gravida rutrum quisque.
38. Semper risus in hendrerit gravida rutrum quisque.
39. Tellus rutrum tellus pellentesque eu.
40. Duis at tellus at urna condimentum.
41. Non curabitur gravida arcu ac tortor dignissim convallis aenean et.
42. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel.
43. At varius vel pharetra vel turpis nunc eget lorem dolor.
44. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi
45. Quis imperdiet massa tincidunt nunc pulvinar
46. At ultrices mi tempus imperdiet nulla malesuada
47. Mi tempus imperdiet nulla malesuada pellentesque elit
48. At augue eget arcu dictum varius duis at
49. Id leo in vitae turpis massa sed
50. Sed odio morbi quis commodo
51. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque
52. Justo laoreet sit amet cursus sit amet dictum
53. Eu turpis egestas pretium aenean pharetra magna
54. Ut enim blandit volutpat maecenas
55. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi
56. Massa enim nec dui nunc.
57. Arcu felis bibendum ut tristique et egestas
58. Elementum curabitur vitae nunc sed
59. A diam maecenas sed enim ut sem viverra
60. Ac tincidunt vitae semper quis
61. Aenean et tortor at risus viverra
62. Scelerisque eu ultrices vitae auctor eu augue ut
63. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam
64. Neque aliquam vestibulum morbi blandit
65. Feugiat sed lectus vestibulum mattis ullamcorper velit
66. Dolor purus non enim praesent elementum facilisis leo vel
67. Curabitur gravida arcu ac tortor dignissim convallis aenean
68. Vel turpis nunc eget lorem dolor
69. Commodo odio aenean sed adipiscing diam donec
70. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor
71. Et pharetra pharetra massa massa ultricies
72. Ut enim blandit volutpat maecenas volutpat
73. Erat pellentesque adipiscing commodo elit at imperdiet
74. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum
75. Ut tellus elementum sagittis vitae et leo duis ut diam
76. Habitant morbi tristique senectus et netus et malesuada fames ac.
```

You can attempt the same with other terminal editors to see how behavior differs.

### Configuration

-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

-- Add config folder to watchlist for config reloads.
local wezterm = require 'wezterm';
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)

local config = {}
config.font = wezterm.font('JetBrainsMono Nerd Font', {weight=700})
config.font_size = 14
config.line_height = 1.400000
config.color_scheme = 'Gruvbox Light'
config.hide_tab_bar_if_only_one_tab = true
config.tab_bar_at_bottom = true
return config

### Expected Behavior

The text should be pasted with lines in the correct order.

### Anything else?

Love the application; this is the first bug I've seen after using it for a couple months.

**Comment by wez** [comment]
I've pushed a speculative change to `main` that may resolve this.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by alxpettit** [comment]
I have experienced this problem a LOT. I can confirm that it doesn't seem to occur on 9a24f61. (Although sadly on one of my machines there is a bizarre crashing problem, so I can't exactly use that build).

**Comment by davidarmstronglewis** [comment]
Sorry for the silence, I can confirm that the latest nightly has definitely fixed this issue for me.
