### ISSUE TITLE
Diacritics using left option is not working

### ISSUE THREAD

**Issue by robsonpeixoto** [wez/wezterm#3689]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The left/right `option` is useful to add diacritics, for example:

```
option-e + a =>  á
option-n + a =>  ã
option-i + a =>  â
option-` + a =>  à
option-c => ç 
```

But on wezterm the left option, that is more comfortable to use, is not working.

### Configuration

no config

**Comment by wez** [comment]
See: https://wezfurlong.org/wezterm/config/keyboard-concepts.html#macos-left-and-right-option-key

**Comment by robsonpeixoto** [comment]
Sorry for the false issue report. I should have read the documentation before.
Thanks @wez, `config.send_composed_key_when_left_alt_is_pressed=true` works really well.
