### ISSUE TITLE
Wezterm refuses to run under WebGPU, but not on community build

### ISSUE THREAD

**Issue by Korbaux** [wez/wezterm#3691]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

20230501-084619-d0e9a034

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

It seems that some change has caused wezterm to not run under the WebGPU frontend, as the community version seems to run perfectly under it.

### To Reproduce

1. Build from source
2. wezterm -n --config "front_end='WebGpu'"

### Configuration

```lua
local wezterm = require 'wezterm'
c = {
  color_scheme_dirs = { '$HOME/.config/wezterm/colors' },
  color_scheme = "Catppuccin Mocha", -- or Macchiato, Frappe, Latte
  font = wezterm.font 'JetBrains Mono',
  harfbuzz_features = {"zero" , "calt", "ss02", "ss20", "cv01", "cv14", "cv18"},
  term = "wezterm"
}
require("bar").apply_to_config(c)
return c
```

### Expected Behavior

Wezterm not crashing upon being run

### Logs

Debug Overlay (OpenGL):

```
14:19:35.979 WARN window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files`
```

Log (WebGPU):

```
14:19:33.680  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
14:19:33.728  WARN   wezterm_gui::termwindow::webgpu > Attempting to use adapter: AdapterInfo { name: "NV134", vendor: 65541, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl } which has capabilities: SurfaceCapabilities { formats: [Rgba8UnormSrgb, Bgra8UnormSrgb, Rgba8Unorm, Bgra8Unorm, Rgba16Float], present_modes: [Fifo], alpha_modes: [Opaque] } and downlevel capabilities: DownlevelCapabilities { flags: DownlevelFlags(COMPUTE_SHADERS | FRAGMENT_WRITABLE_STORAGE | INDIRECT_EXECUTION | BASE_VERTEX | NON_POWER_OF_TWO_MIPMAPPED_TEXTURES | CUBE_ARRAY_TEXTURES | COMPARISON_SAMPLERS | INDEPENDENT_BLEND | VERTEX_STORAGE | FRAGMENT_STORAGE | MULTISAMPLED_SHADING | BUFFER_BINDINGS_NOT_16_BYTE_ALIGNED | UNRESTRICTED_INDEX_BUFFER | UNRESTRICTED_EXTERNAL_TEXTURE_COPIES), limits: DownlevelLimits, shader_model: Sm5 }. SURFACE_VIEW_FORMATS is required but not supported
14:19:33.761  ERROR  wezterm_gui::frontend           > Failed to create window: wgpu reports that SURFACE_VIEW_FORMATS is not supported. Please try a different adapter or setting front_end='OpenGL'
```

**Comment by wez** [comment]
What do you mean by "the community version"?

From the logs you shared, it looks like WebGPU is falling back to its own internal GL implementation, which is not sufficient to run in full webgpu mode.

Please start wezterm with the OpenGL frontend enabled, then open the debug overlay and type in:

```
wezterm.gui.enumerate_gpus()
```

and share the output.

**Comment by Korbaux** [comment]
1. I mean [the version of wezterm in the community repository.](https://archlinux.org/packages/community/x86_64/wezterm/)
2. `> wezterm.gui.enumerate_gpus()
[
    {
        "backend": "Gl",
        "device": 0,
        "device_type": "Other",
        "name": "NV134",
        "vendor": 65541,
    },
]`

**Comment by wez** [comment]
I see; the difference between them is that the community repo is using the current release, rather than the nightly build.
In the nightly build the front_end now defaults to WebGPU, and there were some additional constraints added to WebGPU as part of #3565 

I've adjusted those constraints now in `main`, so the Gl backend of WebGPU should hopefully be able to run for you now.
Please give it a try and let me know!

**Comment by Korbaux** [comment]
Yep! it works now, thanks!
