### ISSUE TITLE
Large background gifs take a very long time to load

### ISSUE THREAD

**Issue by tqwewe** [wez/wezterm#3693]
**Is your feature request related to a problem? Please describe.**
I converted an MP4 to a gif and set it as my background image in wezterm, but it takes over a minute for the gif to display.

The gif's final size was over 100 MB, I'm in the process of halving the resolution, though programs like Firefox are able to display the gif just fine immediately.

**Describe the solution you'd like**
Displaying large gifs should be fast like Firefox.

**Describe alternatives you've considered**
Down scaling the gif.

**Additional context**

**Comment by tqwewe** [comment]
Is it possible to load mp4 files? And even have the audio work?
I'd love to get this looping video in the background:
<https://moewalls.com/anime/anime-girl-drinking-while-its-raining-outside-live-wallpaper/>

**Comment by wez** [comment]
Please try the nightly build.

The set of supported formats is documented here:
https://wezfurlong.org/wezterm/config/appearance.html?h=tiff#window-background-image

**Comment by tqwewe** [comment]
Thanks I'll give nightly a try

Are there any plans for mp4 videos which loop in the background with audio?

**Comment by wez** [comment]
I have no current plans to support full-on audio-video formats.
I'm going to close this issue, as the nightly does already have a number of changes to support incremental loading and rendering for animated images.
