### ISSUE TITLE
Support maximize on the tab bar

### ISSUE THREAD

**Issue by junnplus** [wez/wezterm#3698]
**Is your feature request related to a problem? Please describe.**

When the window_decorations are configured as `'INTEGRATED_BUTTONS|RESIZE'`, it is not possible to maximize the window by double-clicking on the tab bar.

**Describe the solution you'd like**

Support maximizing the window by double-clicking on the tab bar

**Describe alternatives you've considered**

**Additional context**

**Comment by d0zingcat** [comment]
need it 😆
