### ISSUE TITLE
CloseCurrentPane and CloseCurrentTab have the same KeyAssignment?

### ISSUE THREAD

**Issue by rafo** [wez/wezterm#3700]
**What page or section of the docs have an issue?**
1. [Close current Pane](https://wezfurlong.org/wezterm/config/lua/keyassignment/CloseCurrentPane.html)
2. [Close current tab](https://wezfurlong.org/wezterm/config/lua/keyassignment/CloseCurrentTab.html)

**Describe the issue**
Both have the same Keys SUPER+w

**How to close a _multiplex pane_?**
like those created with C-S-A % is not documented at [default keys](https://wezfurlong.org/wezterm/config/default-keys.html)

**Comment by junnplus** [comment]
I don't think they have the same key assignments. The document only shows the configuration method. You can find their default key assignments at https://wezfurlong.org/wezterm/config/default-keys.html?h=keys

**Comment by rafo** [comment]
There is no default key assigned for closing a pane. But no matter how you look at it, I would not list a key combination as an example in the documentation, which is already assigned in the defaults (the link to which I had already given in my problem description).

**Comment by wez** [comment]
> But no matter how you look at it, I would not list a key combination as an example in the documentation, which is already assigned in the defaults

That sort of thinking makes it difficult to document an example of using a feature that isn't the default.

It's not possible to assign every action a useful and meaningful key combination without it getting in the way of something for someone.
