### ISSUE TITLE
Lazygit not rendering CJK fonts in windows

### ISSUE THREAD

**Issue by dragove** [wez/wezterm#3705]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

Windows 11 Professional 22H2(22621.1702)

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

lazygit does not renders CJK fonts (It renders when I'm resizing window, but disappears after resizing is done)

The screenshot shows that Lazygit runs well on windows terminal (right side) and corrupted on wezterm (left side)

![QQ截图20230511115349](https://github.com/wez/wezterm/assets/24190403/2ae4b947-bcaa-4457-b918-96036d5163a9)

An interesting thing is that if I switch branch in lazygit, it will renders correctly, but if I move my mouse, it immediately corrupts.

![a](https://github.com/wez/wezterm/assets/24190403/9fd84339-7a1c-4710-bec7-419f9a8f07e3)

### To Reproduce

config lazygit to use Chinese as its language

```yml
gui:
  language: zh
```

open lazygit in wezterm in a git project

### Configuration

local wezterm = require("wezterm")
return {
    default_prog = { 'nu' },
    font = wezterm.font("FiraCode Nerd Font"),
    font_size = 18,
    hide_tab_bar_if_only_one_tab = true,
    window_padding = {
        left = 4,
        right = 4,
        top = 4,
        bottom = 4,
    },
    window_decorations = "RESIZE",
    color_scheme = "Catppuccin Frappe",
}

-- I also tried remove everything in config and got the same result.

### Expected Behavior

CJK Fonts renders correctly

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage. Do not resize the window during recording!
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by dragove** [comment]
It behaves more abnormal when it is in `wezterm record`.

[wezterm-recording-zMsxtl.cast.txt](https://github.com/wez/wezterm/files/11451185/wezterm-recording-zMsxtl.cast.txt)

Note: I haven't press any key when I'm moving my mouse.

![b](https://github.com/wez/wezterm/assets/24190403/a319aed3-8122-41df-bfc8-1143cd7d7d0f)
