### ISSUE TITLE
Mouse cursor permanently invisible after pressing mod keys

### ISSUE THREAD

**Issue by rodolf0** [wez/wezterm#3707]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

* Fedora 38
* Gnome 44.1
* Wayland
* Linux 6.2.14-300.fc38.x86_64

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When pressing a keyboard modifier (alt / shift / ctrl) the mouse cursor goes invisble. I'd expect this for other keys but not for key mods.

Moving the mouse cursor doesn't make it visible again until the terminal window loses focus.

### To Reproduce

1. Hover with mouse over terminal window. 
2. Press ctrl or shift or alt key mods.

Cursor becomes unexpectedly invisible never to appear again unless the window loses focus.

### Configuration

no config

**Comment by rodolf0** [comment]
Actually I tried today's nightly app image and have noticed that this bug doesn't repro so seems to be fixed. Although nightly seems to have other font rendering problems for me so wondering if worth keeping this bug open for a backport of the fix to current stable version?

**Comment by wez** [comment]
Closing because this is fixed in nightly.
There is no stable branch; there are no backports.
If you have other issues in the nightly, please file issues for them!
