### ISSUE TITLE
Ctrl+Shift+u unicode input on Linux with macro-capable keyboard

### ISSUE THREAD

**Issue by szilu** [wez/wezterm#3714]
**Is your feature request related to a problem? Please describe.**
Wezterm implements ctrl+shift+u unicode character feature with a fuzzy search GUI, but it is not compatible with the standard key sequences that other programs use.

**Describe the solution you'd like**
It would be nice to have an other handler that I can bind to ctrl+shift+u and it would simply interpret [ctrl+shift+u  hexcode  space] key sequences as unicode charecters.

**Describe alternatives you've considered**
An alternative solution could be to add some timeout (around 100ms) in the character selector gui for the menu to pop up. If the hexcode starts to arrive before the timeout then the selector doesn't pop up.

**Additional context**
The feature is needed if someone uses a macro-capable keyboard with unicode character macros. With the "standard" sequences it works in almost any program, but wezterm is among the few exceptions. I just tryed out wezterm and it seems to be a pretty good software, but this feature is a must have for me, so I cannot consider changing without it.

**Comment by wez** [comment]
See also:
* https://github.com/wez/wezterm/issues/3417

**Comment by szilu** [comment]
Sorry, I couldn't find that one, but I tried to search for a while :)
However, in my system it is not about latency. When I press a macro button than the hexcode is correctly inserted into the fuzzy finder with a space at the end.
There are multiple problems with the fuzzy search in my case:

- QMK sends 4 digit unicode hexcodes with leading zeros, which causes fuzzy search not working
- The standard uses space as the closing character, not enter, so the character is not inserted, but the search UI stays on screen.
- The fuzzy search is a bit slow, which is fine if I am searching for a character, but it is not a usable solution if you type a lot of unicode characters.

So I think the preferred solution would be to eliminate the search in this case and simply insert the decoded character.

**Comment by szilu** [comment]
I am sorry, my eye somehow missed the use_ime option as a solution. For some reason it does not work for me yet, but I investigate further.
