### ISSUE TITLE
iterm2 image protocol: Partially blacked-out frames with frame-by-frame animation

### ISSUE THREAD

**Issue by AnonymouX47** [wez/wezterm#3715]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

20230510-062945-6d8e2666

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When displaying an animation by its frames "manually" (i.e not transmitting animated image (e.g GIF) file data but transmitting each frame as a separate image (e.g PNG)), some upper portion of (and at times, entire) frames are simply displayed as black pixels... but this only occurs the first time each frame are transmitted, any subsequent transmission of the same frame (with the exact same image data) is displayed correctly.

I first noticed this after the changes in response to https://github.com/wez/wezterm/issues/3263. This doesn't occur in version `20221119-145034-49b9839f`. Also, it doesn't occur with kitty or sixel graphics.

See the screencasts attached later on.

### To Reproduce

Sample images:
[bday-541.gif](https://github.com/wez/wezterm/assets/61663146/10ed9cdc-3a6a-4f35-b4f6-cb93a545beb9)
[clifm-test.gif](https://github.com/wez/wezterm/assets/61663146/f9aba154-659d-459a-bb00-13100a6be8fd)

- Run `chafa -f iterm2 <image-file>`

**NOTE:** The same also occurs with similar tools other than `chafa`, even with a tool that utilizes [synchronized output](https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036).

### Configuration

no config

### Expected Behavior

The frames should be displayed correctly.

### Logs

NONE

### Anything else?

On version `20221119-145034-49b9839f` (before the bug):

https://github.com/wez/wezterm/assets/61663146/903d264c-a6a8-4a85-bd1b-af69a241cf3f

On version `20230510-062945-6d8e2666`:

https://github.com/wez/wezterm/assets/61663146/92774a4f-fbd2-44ef-948f-e531f834f1ab

On version `20230510-062945-6d8e2666` (but with **kitty** graphics, same also applies to sixels):

https://github.com/wez/wezterm/assets/61663146/728b4b7b-1cd1-4f25-b143-f2899302c5fb

For a clearer perception of what's going on (on version `20230510-062945-6d8e2666`, with `0.1` window transparency and a longer-running animation):

https://github.com/wez/wezterm/assets/61663146/f4c4899d-62fe-4b70-bc03-861179df1f43

**Comment by wez** [comment]
96f5c2b562e5ab683278c8c99ff73d65ca874fdc fixed an issue with the initial frame being blacked out.
Can you try the latest `main` to see if that was the same underlying problem as this one?

**Comment by AnonymouX47** [comment]
Yes, it's fixed now!

Thanks.
