### ISSUE TITLE
Option to tweak bundled Nerdfont scale

### ISSUE THREAD

**Issue by mikl** [wez/wezterm#3717]
It’s great to have Nerdfont bundled with Wezterm (added in #1521 ), but when using NeoVim (with LazyVim), the icons are a bit too big:

<img width="207" alt="Screenshot 2023-05-14 at 13 10 02@2x" src="https://github.com/wez/wezterm/assets/10263/bdb1f7dc-44f5-4cfa-8392-c394a030edab">
<img width="281" alt="Screenshot 2023-05-14 at 13 10 25@2x" src="https://github.com/wez/wezterm/assets/10263/71b8793e-d951-4a45-a2b0-10f942031c6e">

I can work around this by adding my own Nerdfont, but for a better out-of-the-box experience, it might be worth considering either scaling down the built-in Nerdfont by default, or documenting how this scaling can be tweaked in the [Nerdfont documentation](https://wezfurlong.org/wezterm/config/lua/wezterm/nerdfonts.html).

**Comment by wez** [comment]
See: https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html#manual-fallback-scaling
