### ISSUE TITLE
Copy action only working when selected with mouse and not with copy mode

### ISSUE THREAD

**Issue by LordMZTE** [wez/wezterm#372]
## Describe the bug

When the `Copy` action is activated via a keybind, text which has been selected with the mouse is copied as expected. However, when selecting the text using the copy mode, the text is highlighted but the same copy keybind does nothing.

## Environment (please complete the following information):

 - OS: Windows 10
 - Version: wezterm 20201101-103216-403d002d

## To Reproduce

1. Use this key configuration:
```lua
keys = {
    {
        key = "F3",
        action = "ShowLauncher",
    },
    {
        key = "y",
        mods = "CTRL|SHIFT",
        action = "Copy",
    },       
    {
        key = "c",
        mods = "CTRL|SHIFT",
        action = "DisableDefaultAssignment",
    },
    {
        key = " ",
        mods = "CTRL|SHIFT",
        action = "ActivateCopyMode",
    },
    {
        key = "9",
        mods = "ALT",
        action = "DisableDefaultAssignment",
    },
}
```
2. Press Ctrl+Shift+Space to activate copy mode, press v to select some text
3. Press Ctr+Shift+y which should copy the selected text, but does not
4. Select some text with the mouse, repeat step 3. This time the text will be copied

## Configuration

Keybindings above in step 1

## Expected behavior
The text is copied when selected with copy mode just as it is when selected with the mouse

**Comment by wez** [comment]
In more recent versions of wezterm, the SHIFT key gets normalized into the `key` component; in other words, I think you want:

```lua
{
        key = "Y",  -- Shift-y is Y
        mods = "CTRL", -- no SHIFT here
        action = "Copy",
},       
```

and similarly for your CTRL-SHIFT-c assignment.

**Comment by LordMZTE** [comment]
That fixed my issue, but it's still strange that it still works when using the mouse isn't it?

**Comment by wez** [comment]
The [default mouse assignments](https://wezfurlong.org/wezterm/config/keys.html#default-mouse-assignments) for manipulating the selection implicitly perform `Copy` after selecting or extending the selection, which would explain why the key press appeared to work in that case.
