### ISSUE TITLE
suppress the notification made from OSC777 when the window is focused

### ISSUE THREAD

**Issue by catdevnull** [wez/wezterm#3727]
**Is your feature request related to a problem? Please describe.**
 make it possible for wezterm dismiss the notification made from OSC777 when focused

foot does this: https://codeberg.org/dnkl/foot/issues/328

it's nice because you can set it up to send notifications when long commands are finished and when focused they disappear

for use with things like https://github.com/franciscolourenco/done (if it used OSC 777; i have a mod that does)

**Comment by wez** [comment]
My reading of that foot issue is that it suppresses notifications when the associated window has the focus, rather than dismissing them when the window gains focus.

**Comment by catdevnull** [comment]
uh, sure, i don't know what the difference is :)

i mean something similar to this i guess: https://github.com/FiloSottile/yubikey-agent/pull/141

**Comment by wez** [comment]
The foot behavior is that if the window has focus when the notification is generated, it doesn't show the notification at all.
What you described and what you just linked to is automatically dismissing notification(s) when focusing the window.

**Comment by catdevnull** [comment]
oops, yes, you're right. i think what foot does is a good first step, and would like to also be able to make it remove the notification when focusing the window that produced it.

**Comment by cpick** [comment]
I had a similar desire to get notifications when a command in an unfocused window+tab+pane took "long enough" to complete.  After a [chat on Matrix](https://matrix.to/#/!PirwUBcuIlTXwNveYz:matrix.org/$OV1ThY5mHHZrBs3qg2x-njziSsyoK5_u4DuSSGtfYjo?via=matrix.org&via=kde.org&via=tchncs.de), I came up with [this implementation](https://github.com/marzocchi/zsh-notify/pull/99) for `zsh-notify`.

It boils down to using `zsh`s `preexec` and `precmd` hooks to detect completion of a long-running command, then having it call:
```zsh
__wezterm_set_user_var NOTIFICATION "$(jq \
  -nc \
  --arg title "$title" \
  --arg message "$message" \
  --argjson check_focus "$check_focus" \
  --argjson timeout_milliseconds "$expire_time" \
  '{
    title: $title,
    message: $message,
    check_focus: $check_focus,
    timeout_milliseconds: $timeout_milliseconds
  }' \
)"
```

Which is handled by this hook in `.wezterm.lua`:
```lua
local wezterm = require 'wezterm'
local config = {}

wezterm.on('user-var-changed', function(window, pane, name, value)
  if name ~= "NOTIFICATION" then
    return
  end

  local notification = wezterm.json_parse(value)

  if notification.check_focus
    and window:is_focused()
    and window:active_pane():pane_id() == pane:pane_id()
  then
    return
  end

  if not notification.timeout_milliseconds then
    notification.timeout_milliseconds = nil
  end

  window:toast_notification(notification.title, notification.message,
    nil, notification.timeout_milliseconds)
end)

return config
```

**Comment by wez** [comment]
This should be resolved now in `main`.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wez** [comment]
See docs for new setting at: https://wezfurlong.org/wezterm/config/lua/config/notification_handling.html

**Comment by catdevnull** [comment]
hmm. this partially works, but it doesn't show a notification (with `SuppressFromFocusedTab`) when the window is unfocused (but the tab focused). in gnome wayland

this checks out because as far as i can tell it only checks if the tab is focused, not if the window is focused

**Comment by catdevnull** [comment]
I see that there's more options now, tysm!
