### ISSUE TITLE
[draft] Retrieved semantic zone text is sometimes incomplete with `get_text_from_semantic_zone()`.

### ISSUE THREAD

**Issue by follower** [wez/wezterm#3729]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter(?) on Elementary.

### WezTerm version

wezterm 20230408-112425-69ae8472 (via AppImage)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below[0]

### Describe the bug

Retrieved semantic zone text is (sometimes) incomplete/incorrect(?) when using `get_text_from_semantic_zone()`.

When using `get_text_from_semantic_zone()` to retrieve semantic zone text content, certain zone sizes and/or zone start+end positions result in missing/partial/truncated/incorrect(?) text when compared to the current terminal state.

### To Reproduce

See "Logs" section below.

Raw draft investigation / repro notes + recording + logs (in case I don't copy everything relevant into this issue directly):

 * <https://gitlab.com/RancidBacon/floss-various-contribs/-/tree/main/wezterm/issue-semantic-zone-text-repro>

### Configuration

N/A?

### Expected Behavior

Retrieved zone text matches current terminal state, even when the zone starts and/or ends in the middle of a line. 

### Logs

 * Repro setup steps (perform before running the lua repro script):

   *Note:* No enter after `hello`.

<ul>
<ul><li>

<details>
<summary>click to show repro setup steps</summary>

```bash
# assume `source /<path>/wezterm.sh`

export PS1="\$ "

mkdir /tmp/issue-repro
pushd /tmp/issue-repro

touch file1.dat
touch file2.dat

clear

ls
ls -go
#hello
```

</details>

</li></ul>
</ul>

 * The terminal pane should look somewhat like this after the above setup:

<ul>
<ul><li>

<details>
<summary>click to show approximate repro terminal pane state</summary>

```bash
$ ls
file1.dat  file2.dat
$ ls -go
total 0
-rw-rw-r-- 1 0 Mar 23 18:43 file1.dat
-rw-rw-r-- 1 0 Mar 23 18:43 file2.dat
$ #hello
```

</details>

</li></ul>
</ul>

 * lua script to reproduce issue:
 
   * via: <https://gitlab.com/RancidBacon/floss-various-contribs/-/blob/main/wezterm/issue-semantic-zone-text-repro/print-zone-text-comparison.lua>

<ul>
<ul><li>

<details>
<summary>click to show repro lua script</summary>

```lua
--
-- Code that, for each semantic zone in the pane, (1st) shows default
-- `get_semantic_zones()` output versus (2nd) the output after the
-- `end_y` value of each zone has been increased by one.
--
-- It can be seen that, by default, certain sizes and/or start+end
-- positions of zones result in missing/partial/trunctated results.
--
-- (IIRC the revised output may still be incorrect in some situations
-- due to the `+1` just being a crude hack to help demonstrate the
-- issue not fix it. :) )
--
-- See accompanying log output as generated via this code posted
-- into the WezTerm debug overlay.
--
-- Note: For reasons (which I have not investigated) only part of
--       the output appeared in the debug overlay, I needed to
--       retrieve the full output from the system logs.
--

t1p1 = wezterm.mux.get_pane(21) -- change `21` to appropriate pane id e.g. via `$WEZTERM_PANE`

for i,z in pairs(t1p1:get_semantic_zones()) do print("\n" .. i, z, "\n\n" .. t1p1:get_text_from_semantic_zone(z) .. "\n----------\n") z.end_y = z.end_y + 1 print("\n", z, "\n\n" .. t1p1:get_text_from_semantic_zone(z) .. "\n=============\n")  end
```

</details>

</li></ul>
</ul>

 * asciicast recording of repro setup:

   * <https://gitlab.com/RancidBacon/floss-various-contribs/-/blob/main/wezterm/issue-semantic-zone-text-repro/wezterm-recording--truncated-semantic-zones-issue--LUrnnP.cast.edited.trimmed.txt>

   * file attachment: [`wezterm-recording--truncated-semantic-zones-issue--LUrnnP.cast.edited.trimmed.txt`](https://github.com/wez/wezterm/files/11493849/wezterm-recording--truncated-semantic-zones-issue--LUrnnP.cast.edited.trimmed.txt)

 * log output:

    * via:  <https://gitlab.com/RancidBacon/floss-various-contribs/-/blob/main/wezterm/issue-semantic-zone-text-repro/trimmed-log-output1.txt> 

<ul>
<ul><li>

<details>
<summary>click to show log</summary>

```
: 05:27:01.515  INFO   logging                     > lua:
: 1 {
:     "end_x": 1,
:     "end_y": 30,
:     "semantic_type": "Prompt",
:     "start_x": 0,
:     "start_y": 30,
: }
: ----------
: 05:27:01.515  INFO   logging                     > lua:
:  {
:     "end_x": 1,
:     "end_y": 31,
:     "semantic_type": "Prompt",
:     "start_x": 0,
:     "start_y": 30,
: }
: $ ls
: =============
: 05:27:01.515  INFO   logging                     > lua:
: 2 {
:     "end_x": 3,
:     "end_y": 30,
:     "semantic_type": "Input",
:     "start_x": 2,
:     "start_y": 30,
: }
: ----------
: 05:27:01.515  INFO   logging                     > lua:
:  {
:     "end_x": 3,
:     "end_y": 31,
:     "semantic_type": "Input",
:     "start_x": 2,
:     "start_y": 30,
: }
: ls
: =============
: 05:27:01.515  INFO   logging                     > lua:
: 3 {
:     "end_x": 19,
:     "end_y": 31,
:     "semantic_type": "Output",
:     "start_x": 0,
:     "start_y": 31,
: }
: ----------
: 05:27:01.515  INFO   logging                     > lua:
:  {
:     "end_x": 19,
:     "end_y": 32,
:     "semantic_type": "Output",
:     "start_x": 0,
:     "start_y": 31,
: }
: file1.dat  file2.dat
: =============
: 05:27:01.516  INFO   logging                     > lua:
: 4 {
:     "end_x": 1,
:     "end_y": 32,
:     "semantic_type": "Prompt",
:     "start_x": 0,
:     "start_y": 32,
: }
: ----------
: 05:27:01.516  INFO   logging                     > lua:
:  {
:     "end_x": 1,
:     "end_y": 33,
:     "semantic_type": "Prompt",
:     "start_x": 0,
:     "start_y": 32,
: }
: $ ls -go
: =============
: 05:27:01.516  INFO   logging                     > lua:
: 5 {
:     "end_x": 7,
:     "end_y": 32,
:     "semantic_type": "Input",
:     "start_x": 2,
:     "start_y": 32,
: }
: ----------
: 05:27:01.516  INFO   logging                     > lua:
:  {
:     "end_x": 7,
:     "end_y": 33,
:     "semantic_type": "Input",
:     "start_x": 2,
:     "start_y": 32,
: }
: ls -go
: =============
: 05:27:01.516  INFO   logging                     > lua:
: 6 {
:     "end_x": 36,
:     "end_y": 35,
:     "semantic_type": "Output",
:     "start_x": 0,
:     "start_y": 33,
: }
: total 0
: -rw-rw-r-- 1 0 Apr 20 05:12 file1.dat
: ----------
: 05:27:01.516  INFO   logging                     > lua:
:  {
:     "end_x": 36,
:     "end_y": 36,
:     "semantic_type": "Output",
:     "start_x": 0,
:     "start_y": 33,
: }
: total 0
: -rw-rw-r-- 1 0 Apr 20 05:12 file1.dat
: -rw-rw-r-- 1 0 Apr 20 05:13 file2.dat
: =============
: 05:27:01.517  INFO   logging                     > lua:
: 7 {
:     "end_x": 1,
:     "end_y": 36,
:     "semantic_type": "Prompt",
:     "start_x": 0,
:     "start_y": 36,
: }
: ----------
: 05:27:01.517  INFO   logging                     > lua:
:  {
:     "end_x": 1,
:     "end_y": 37,
:     "semantic_type": "Prompt",
:     "start_x": 0,
:     "start_y": 36,
: }
: $ #hello
: =============
: 05:27:01.517  INFO   logging                     > lua:
: 8 {
:     "end_x": 7,
:     "end_y": 36,
:     "semantic_type": "Input",
:     "start_x": 2,
:     "start_y": 36,
: }
: ----------
: 05:27:01.517  INFO   logging                     > lua:
:  {
:     "end_x": 7,
:     "end_y": 37,
:     "semantic_type": "Input",
:     "start_x": 2,
:     "start_y": 36,
: }
: #hello
: =============
: 05:27:01.518  INFO   logging                     > lua:
: 9 {
:     "end_x": 94,
:     "end_y": 73,
:     "semantic_type": "Output",
:     "start_x": 0,
:     "start_y": 37,
: }
: ----------
: 05:27:01.518  INFO   logging                     > lua:
:  {
:     "end_x": 94,
:     "end_y": 74,
:     "semantic_type": "Output",
:     "start_x": 0,
:     "start_y": 37,
: }
: =============
```

</details>

</li></ul>
</ul>

#### Related issues

 * https://github.com/wez/wezterm/issues/2968#issuecomment-1399327659

   > "_I can't get `pane:get_text_from_region()` to extract just a part of a single line._"

----

#### "...below[0]"

[_Apologies for the substandard/incomplete bug report but I'm hoping it's "better than nothing", given I've had the repro script + logs + investigation notes sitting around for months but haven't managed to actually open a bug report before now._

_(Yay, ADHD perfectionism... :/ )_

_Hope to update this issue with further details & a pointer to where I think the issue might be arising from._]

P.S. Thanks for all the development effort you've put into `wezterm`, I really appreciate it. It's a cool example to demonstrate that terminals don't have to stagnate & we haven't reached their limits as a UX paradigm & that there's still opportunity for innovation/exploration in the space. :)

**Comment by follower** [comment]
### Possible cause?

Quoting from my commit message for some investigation notes ([via](https://gitlab.com/RancidBacon/floss-various-contribs/-/commit/e404e1b64a2cd1a7911d8589913c2a1acdd9c50e)):

> Initial impression suggests that the logic in this line bears further
investigation as a possible cause of (some) symptoms:
>
> ```rust
>      if this_row >= first_row && this_row < last_row {
> ```
>
> Should `last_row` actually be `(last_row + 1)` and/or should the comparison
be `this_row <= last_row` (in which case is it redundant?) and/or is there
a logical vs physical lines related issue?

_[TODO: Summarise other notes.]_

**Comment by follower** [comment]
**Current issue status:** _Probably not going to get to adding further details at this stage._

Hopefully what I've provided is enough to reproduce & maybe point in the direction of a solution for anyone investigating further.

_Apologies in advance for future delayed or non-existent replies&mdash;it's not that I don't care. :/_

**Comment by wez** [comment]
Thanks for pulling together a lot of information.
Would you mind highlighting the first part of the lua output that isn't what you expect it to be?
That would make it easier to understand where the discrepancy is coming from!
