### ISSUE TITLE
How to use cmd key on macOS in neovim keybindings?

### ISSUE THREAD

**Issue by zohar-soul** [wez/wezterm#3731]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230515-073311-76406e84

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

neovim doesn't receive <D-w> when I press cmd + w

### To Reproduce

1. open neovim 
2. : ctrl + k
3. type cmd + w

### Configuration

config.disable_default_key_bindings = true
--config.enable_kitty_keyboard = true
config.enable_csi_u_key_encoding = true
config.use_dead_keys = false
config.debug_key_events = true

### Expected Behavior

neovim can receive <D-w>

### Logs

```
11:46:28.494  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Char('w'), modifiers: SUPER, leds: (empty), phys_code: Some(W), raw_code: 13, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:46:28.494  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('w'), modifiers: SUPER, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Char('w'), modifiers: SUPER, leds: (empty), phys_code: Some(W), raw_code: 13, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:46:28.494  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('w') mods=SUPER
11:46:28.494  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[119;1u", Char('w') SUPER
11:46:28.694  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('w'), modifiers: NONE, leds: (empty), phys_code: Some(W), raw_code: 13, repeat_count: 1, key_is_down: false, handled: Handled(false) } 
11:46:28.694  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('w'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('w'), modifiers: NONE, leds: (empty), phys_code: Some(W), raw_code: 13, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:46:28.694  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('w') mods=NONE
```

**Comment by wez** [comment]
I'd recommend using the kitty keyboard protocol over the csi-u protocol:

```lua
config.enable_kitty_keyboard = true
config.enable_csi_u_key_encoding = false
```

then it is up to neovim to be configured to handle those key presses. I don't use neovim so I can't be much more help than this.

**Comment by zohar-soul** [comment]
> I'd recommend using the kitty keyboard protocol over the csi-u protocol:
> 
> ```lua
> config.enable_kitty_keyboard = true
> config.enable_csi_u_key_encoding = false
> ```
> 
> then it is up to neovim to be configured to handle those key presses. I don't use neovim so I can't be much more help than this.

@wez 
thanks.
but, I have tried both configurations, the result is the same.

**Comment by wez** [comment]
I'd suggest asking the neovim folks how to bind to the Cmd key; what does neovim look for in order for that to work and so on.

**Comment by Qyriad** [comment]
Relevant Neovim issue on the Kitty keyboard protocol: neovim/neovim#14400

**Comment by zohar-soul** [comment]
Thank you very much, I will try it.

**Comment by wez** [comment]
From the linked issue, it sounds like this is a neovim issue and not a wezterm issue, so I'm going to close this.

**Comment by towry** [comment]
Here is a working solution:

For example we want to map `<CMD-s>` in neovim to save the buffer.
First in neovim, set the below keymap:

```
  vim.keymap.set('n', '<Char-0xAA>', '<cmd>write<cr>', {
    desc = 'N: Save current file by <command-s>',
  })
```

Then in wezterm, we need to rebind `<cmd-s>` to send char '0xAA` to neovim.

```
local function is_vim(pane)
	local is_vim_env = pane:get_user_vars().IS_NVIM == 'true'
	if is_vim_env == true then return true end
	-- This gsub is equivalent to POSIX basename(3)
	-- Given "/foo/bar" returns "bar"
	-- Given "c:\\foo\\bar" returns "bar"
	local process_name = string.gsub(pane:get_foreground_process_name(), '(.*[/\\])(.*)', '%2')
	return process_name == 'nvim' or process_name == 'vim'
end

--- cmd+keys that we want to send to neovim.
local super_vim_keys_map = {
	s = utf8.char(0xAA),
	x = utf8.char(0xAB),
	b = utf8.char(0xAC),
	['.'] = utf8.char(0xAD),
	o = utf8.char(0xAF),
}

local function bind_super_key_to_vim(key)
	return {
		key = key,
		mods = 'CMD',
		action = wezterm.action_callback(function(win, pane)
			local char = super_vim_keys_map[key]
			if char and is_vim(pane) then
				-- pass the keys through to vim/nvim
				win:perform_action({
					SendKey = { key = char, mods = nil },
				}, pane)
			else
				win:perform_action({
					SendKey = {
						key = key,
						mods = 'CMD'
					}
				}, pane)
			end
		end)
	}
end

--- in your wezterm keys config, use it like:
keys = {
   bind_super_key_to_vim('s'),
  --- others....
}
```
