### ISSUE TITLE
when $HOME/.wezterm.lua is a symbol link, configuration won't work

### ISSUE THREAD

**Issue by stonewell** [wez/wezterm#3734]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

dwl

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

when $HOME/.wezterm.lua is a symbol link, configuration won't work, only regular file .wezterm.lua works

### Configuration

no config

**Comment by wez** [comment]
Can you clarify what you mean by not working?
wezterm should be able to read the config just fine, but automatic reloading likely will not function.

**Comment by stonewell** [comment]
it is not reading the config file. even I use --config-file flag to point to the symbol link file, it said unable to read the config
