### ISSUE TITLE
act.CopyMode("EditPattern") should pop the copy_mode keytable when it transitions to search_mode

### ISSUE THREAD

**Issue by happenslol** [wez/wezterm#3746]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Sway/Hyprland

### WezTerm version

main (4ae176dd8a019eeaf955cc947e3789995edbed07), version 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When editing the search pattern in copy mode, any keys that are bound for copy mode will execute their binding instead of updating the search pattern.

### To Reproduce

I've been able to reproduce the behavior with the minimal config posted below. Enter copy mode by pressing `CTRL+v`, and then `/` to start editing the pattern.

`w` will not update the search pattern but instead start selecting until the next word, while pressing `/` again does not have any effect.

### Configuration

```lua
local w = require("wezterm")
local act = w.action

local config = w.config_builder()

config.keys = {
	{ key = "v", mods = "CTRL", action = act.ActivateCopyMode },
}

config.key_tables = {
	copy_mode = {
		{ key = "w", action = act.CopyMode("MoveForwardWord") },
		{ key = "/", action = act.CopyMode("EditPattern") },
		{ key = "Escape", action = act.CopyMode("Close") },
	},
}

return config
```

### Expected Behavior

All inputs except `escape` and mappings using the `ctrl` modifier should update the search pattern while editing it. Otherwise, it's not possible to both have bindings for a key in copy mode, and search for a pattern including that key.

### Anything else?

I've had a look at the code that handles key events. I would've come with a fix prepared, but I'm unsure how you want to handle this. It seems like bindings found in the current key table will always "swallow" the input and take preference (`keyevent.rs#292`), and only if no binding is found and we fall through to calling `overlay::copy::key_down`, the state of `render.editing_search` is checked.

There would need to be a check for `editing_search` before any bindings are read, so that all input can be redirected. Not sure what the best way to do that is.

**Comment by wez** [comment]
The gist of the issue is that the transition to `editing_search = true` should be accompanied by popping `copy_mode` from the key table stack and pushing `search_mode`.  Similarly, transitioning out of `editing_search` should do the inverse: pop `search_mode` and push `copy_mode`.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by happenslol** [comment]
Oh damn, that was really quick! Thanks so much! That's a much cleaner solution, since I can now also add custom bindings just for search mode.
