### ISSUE TITLE
Display error with nerd font v3 symbols on Windows (not happen in macOS)

### ISSUE THREAD

**Issue by milanglacier** [wez/wezterm#3748]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

This is the status bar of tmux displayed in wezterm, where I used nerd font v3 symbols:

![image](https://github.com/wez/wezterm/assets/45728125/c6abe3c5-ca41-40e9-954b-8bac4bdabebe)

### To Reproduce

Just running `tmux` on WSL/remote ssh where tmux is installed in the host.

### Configuration

No config for wezterm.

This is the tmux configuration:

```tmux
set -g status-interval 5
set -g status-left '#[fg=magenta,bg=default]#[bg=magenta,fg=default]󰍹 #{session_name}#[fg=magenta,bg=default]#[fg=yellow,bg=default]'
set -g status-left-length 100
set -g status-right-length 150
set -g status-justify centre
set -g status-bg cyan

setw -g window-status-activity-style curly-underscore
setw -g window-status-bell-style blink,strikethrough
setw -g window-status-current-style italics

setw -g window-status-format '#[fg=yellow,bg=default]#[bg=yellow,fg=default] #I:#W#F#[fg=yellow,bg=default]'
setw -g window-status-current-format '#[fg=magenta,bg=default]#[fg=default,bg=magenta] #I:#W#F#[fg=magenta,bg=default]'

set -g status-right '#[fg=yellow,bg=default]#[fg=default,bg=yellow] #(whoami) 󰴕 #H#[fg=yellow,bg=default]#[fg=magenta,bg=default]#[fg=default,bg=magenta] %m/%d/%y %H:%M#[fg=magenta,bg=default]'


```

### Expected Behavior

The tmux status bar should be displayed correctly.

Note that this is a common problem on windows, I have tried several terminal emulators, including alacritty, windows terminal, vscode builtin terminal, they all have the same display problems.

(see the mirror issue on alacritty: https://github.com/alacritty/alacritty/issues/6936)

This is the screenshot of the tmux statusbar on macos wezterm (it is displayed correctly),

<img width="1440" alt="Screenshot 2023-05-20 at 15 54 23" src="https://github.com/alacritty/alacritty/assets/45728125/3cf6c980-4e2b-4468-9420-51bcd4fb84cd">

And this is the screenshot of the tmux statusbar on windows terminal preview (it is displayed correctly, and it is the only terminal emulators on Windows that can display those symbols correctly on Windows)

![image](https://github.com/alacritty/alacritty/assets/45728125/11bef7a0-7663-46ed-9fd6-8da73da909c6)

**Comment by wez** [comment]
Please try with the latest nightly build and let me know if it behaves any better; that has a newer version of conpty included.

**Comment by wez** [comment]
Yes, binaries for all platforms are available from the download page:
https://wezfurlong.org/wezterm/install/windows.html

**Comment by TheSast** [comment]
I have the same issue with the latest stable release, the nightly build does not have that specific issue on my end.

**Comment by milanglacier** [comment]
I can confirm wezterm nightly fixes the renderer problem
