### ISSUE TITLE
Cycle panes with a single bind

### ISSUE THREAD

**Issue by sigzegv** [wez/wezterm#3764]
**Is your feature request related to a problem? Please describe.**
Like in tmux or kitty, cycling panes with a single key bind can be simpler than using up/down/left/right binds

**Describe the solution you'd like**
A single bind to cycle through every pane in a splited layout.

**Comment by lost22git** [comment]
You can try this key binding, it may be what you need

```lua
{
    key = 'Enter',
    mods = 'CTRL',
    action = wzt.action_callback(function(win, pane)
      local mux_tab = pane:tab()
      local panes = mux_tab:panes()
      if #panes == 1 then
        return
      end
      local cur_pane_found = false
      for _, p in ipairs(panes) do
        if cur_pane_found then
          p:activate()
          return
        end
        if p:pane_id() == pane:pane_id() then
          cur_pane_found = true
        end
      end
      panes[1]:activate()
    end),
}
```

![cc](https://github.com/wez/wezterm/assets/65008815/f0acebc3-7788-416e-8ed2-7462c04d9742)

**Comment by wez** [comment]
You can use `Next` and `Prev` to cycle through panes; see https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivatePaneDirection.html

```lua
act.ActivatePaneDirection 'Next'
```
