### ISSUE TITLE
window_background_opacity cannot work on wayland

### ISSUE THREAD

**Issue by Freed-Wu** [wez/wezterm#3766]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

gnome wayland

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I set `window_background_opacity = 0.75,` and on gnome X11, it works, but on gnome wayland, it does nothing.

### To Reproduce

run gnome wayland

### Configuration

```lua
local wezterm = require 'wezterm'
local hostname = wezterm.hostname()
local font_size
if hostname == 'desktop' then -- 2560x2880
    font_size = 16
elseif hostname == 'laptop' then -- 3120x2080
    font_size = 12
else
    font_size = 12
end
local act = wezterm.action
local mux = wezterm.mux
wezterm.on('gui-startup', function(cmd)
    local tab, pane, window = mux.spawn_window(cmd or {})
    window:gui_window():toggle_fullscreen()
end)
return {
    font = wezterm.font_with_fallback {
        'JetBrainsMono Nerd Font Mono', -- 
        'WenQuanYi Zen Hei Mono', -- ①
        'WenQuanYi Micro Hei Mono' -- ⇡
    },
    window_background_opacity = 0.75,
    hide_tab_bar_if_only_one_tab = true,
    font_size = font_size,
    window_padding = {left = 0, right = 0, top = 0, bottom = 0},
    keys = {
        {key = 'Enter', mods = 'ALT', action = 'DisableDefaultAssignment'},
        {key = '-', mods = 'CTRL', action = 'DisableDefaultAssignment'},
        {key = '=', mods = 'CTRL', action = 'DisableDefaultAssignment'},
        {key = '0', mods = 'CTRL', action = 'DisableDefaultAssignment'},
        {key = 'Backspace', mods = 'SHIFT|CTRL', action = act.ToggleFullScreen},
        {key = 'Enter', mods = 'SHIFT', action = act.SendString '\x1b[13;2u'},
        {key = 'Enter', mods = 'CTRL', action = act.SendString '\x1b[13;5u'}
    }
}
```

### Expected Behavior

I hope gnome wayland has same behaviour with gnome X11

### Logs

```
11:53:33.408  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 47, cols: 156 }) because window_state is FULL_SCREEN
```

**Comment by Freed-Wu** [comment]
I found it only happened on fullscreen. same as: https://github.com/alacritty/alacritty/issues/4070

OS: linux 6.5.4
DE: gnome on Wayland

**Comment by kchibisov** [comment]
Idk why this issue is open. This is done on Wayland by design of the `xdg_shell` protocol. Nothing applications can do about it.

**Comment by Freed-Wu** [comment]
> This is done on Wayland by design of the xdg_shell protocol. Nothing applications can do about it.

I see. Thanks for explanation.
