### ISSUE TITLE
A Project Manager or Projectile like interface would be superb.

### ISSUE THREAD

**Issue by theherk** [wez/wezterm#3768]
**Is your feature request related to a problem? Please describe.**
No. It is more a workflow improvement, that may not belong in the editor, but would be very handy nevertheless.

**Describe the solution you'd like**
I would like to have a key combination open a list of all git projects within a configured directory, then create if not already created and switch to a workspace for that project.

**Describe alternatives you've considered**
It can be done using fzf or skim within a new workspace, but the steps are:

1. Determine if desired workspace exists using command palette.
2. Create new manually named workspace using [this function](https://github.com/theherk/commons/blob/main/.config/wezterm/wezterm.lua#L180).
3. Use external project switcher.

That isn't horrible, but it isn't ideal. There is probably some feature I can do on the command line to, given a project directory, check if a matching workspace exists in the current instant of wezterm, and if not create or if so create and switch, but I'm not sure.

I completely understand if you close this immediately, but I at least would like to know if others have thought about or implemented solutions for this workflow.

**Comment by wez** [comment]
You should be able to implement this for yourself using https://wezfurlong.org/wezterm/config/lua/keyassignment/InputSelector.html

**Comment by theherk** [comment]
It is working okay with this:

```lua
  {
    key = "P",
    mods = "LEADER",
    action = wezterm.action_callback(function(window, pane)
      local choices = {}
      for _, v in pairs(util.file_lines(os.getenv("HOME") .. "/.projects")) do
        table.insert(choices, { label = v })
      end

      window:perform_action(
        act.InputSelector {
          action = wezterm.action_callback(function(window, pane, id, label)
            if not id and not label then
              wezterm.log_info "cancelled"
            else
              window:perform_action(
                act.SwitchToWorkspace({ name = label }),
                pane
              )
            end
          end),
          title = "Select Project",
          choices = choices,
        },
        pane
      )
    end),
  },
```

But I'm wondering how I can set `ShowLauncherArgs` here so I can pass the `FUZZY` flag.

**Comment by theherk** [comment]
Also, if I switch to:

```lua
              window:perform_action(
                act.SwitchToWorkspace {
                  name = label,
                  spawn = {
                    args = { 'cd', label },
                  },
                },
                pane
              )
```

It doesn't do anything, and logs nothing in debug either. Should I be able to spawn in this way?

**Comment by theherk** [comment]
Oh actually, I found there is a fuzzy argument via a debug error I got. This works perfectly.

```lua
  {
    key = "P",
    mods = "LEADER",
    action = wezterm.action_callback(function(window, pane)
      local choices = {}
      for _, v in pairs(util.file_lines(os.getenv("HOME") .. "/.projects")) do
        table.insert(choices, { label = v })
      end

      window:perform_action(
        act.InputSelector {
          action = wezterm.action_callback(function(window, pane, id, label)
            if not id and not label then
              wezterm.log_info "cancelled"
            else
              window:perform_action(
                act.SwitchToWorkspace {
                  name = label,
                  spawn = {
                    cwd = label,
                  },
                },
                pane
              )
            end
          end),
          fuzzy = true,
          title = "Select Project",
          choices = choices,
        },
        pane
      )
    end),
  },
```

But that argument doesn't seem to be listed in [the docs](https://wezfurlong.org/wezterm/config/lua/keyassignment/InputSelector.html?h=input+se). Am I looking in the wrong place. Anyway, very happy with this. Thanks as always, @wez.

**Comment by theherk** [comment]
https://github.com/wez/wezterm/assets/3605078/9f3c43e8-64e6-46b1-8264-841c51d3554f

This is actually such a nice workflow. I'm loving it. This terminal emulator just gets better and better. Anybody that wants to peruse the setup for this switching, it can be found [here](https://github.com/theherk/commons/blob/main/.config/wezterm/control.lua), but the primary bits are:

```lua
if wezterm.GLOBAL.prev_workspace == nil then
  wezterm.GLOBAL.prev_workspace = 'default'
end

wezterm.on('switch-workspace-default', function(window, pane)
  local cur = wezterm.mux.get_active_workspace()
  window:perform_action(
    act.SwitchToWorkspace { name = 'default' },
    pane
  )
  if cur ~= 'default' then
    wezterm.GLOBAL.prev_workspace = cur
  end
  wezterm.log_info("prev_workspace: " .. wezterm.GLOBAL.prev_workspace)
end)

wezterm.on('switch-workspace-prev', function(window, pane)
  local cur = wezterm.mux.get_active_workspace()
  window:perform_action(
    act.SwitchToWorkspace { name = wezterm.GLOBAL.prev_workspace },
    pane
  )
  wezterm.GLOBAL.prev_workspace = cur
  wezterm.log_info("prev_workspace: " .. wezterm.GLOBAL.prev_workspace)
end)

local action_project_switcher = wezterm.action_callback(function(window, pane)
  local choices = {}
  for _, v in pairs(util.file_lines(os.getenv("HOME") .. "/.projects")) do
    fmt_label = wezterm.format {
      { Foreground = { Color = theme.colors.hl_1 } },
      { Text = v },
    }
    table.insert(choices, { id = v, label = fmt_label })
  end

  window:perform_action(
    act.InputSelector {
      action = wezterm.action_callback(function(window, pane, id, label)
        if not id and not label then
          wezterm.log_info "cancelled"
        else
          local cur = wezterm.mux.get_active_workspace()
          window:perform_action(
            act.SwitchToWorkspace {
              name = id,
              spawn = {
                cwd = id,
              },
            },
            pane
          )
          wezterm.GLOBAL.prev_workspace = cur
          wezterm.log_info("prev_workspace: " .. wezterm.GLOBAL.prev_workspace)
        end
      end),
      choices = choices,
      fuzzy = true,
    },
    pane
  )
end)
```

Then you can set keys like:

```lua
  { key = "d",  mods = "LEADER",      action = act.EmitEvent 'switch-workspace-default' },
  { key = "p",  mods = "SUPER",       action = action_project_switcher, },
  { key = "P",  mods = "LEADER",      action = action_project_switcher, },
  { key = "\t", mods = "LEADER",      action = act.EmitEvent 'switch-workspace-prev' },

  {
    key = "W",
    mods = "LEADER",
    action = act.PromptInputLine {
      description = wezterm.format {
        { Foreground = { Color = theme.colors.active_fg } },
        { Text = "New workspace name:" },
      },
      action = wezterm.action_callback(function(window, pane, line)
        if line then
          window:perform_action(
            act.SwitchToWorkspace {
              name = line,
            },
            pane
          )
        end
      end),
    },
  },
```

This requires the `~/.projects` file being built with something like:

```zsh
fd -HI -d 5 "^\.git\$" $P | xargs dirname 2>/dev/null > $HOME/.projects
```

And that file ends up looking like:

```
/Users/h4s/projects/bitbucket.org/theherk/bfg-test
/Users/h4s/projects/github.com/theherk/aidews
/Users/h4s/projects/github.com/theherk/figgypy
/Users/h4s/projects/github.com/theherk/rustlings
/Users/h4s/projects/github.com/theherk/viper
```

The last thing that would be nice, but wouldn't actually improve the workflow at all, would be if one could use the command palette interface in cases where you would otherwise use `InputSelector` with `fuzzy = true`. Ergonomics would be exactly the same, but I think it would be a tiny bit nicer. Not the actual command palette, but the same overlay it uses. Anyway, all good.

**Comment by invisibleaxm** [comment]
@theherk  just wanted to give you a shout-out for sharing this. I was looking for quite a similar workflow and wez pointed me to this issue. Looking at the comments, I was able to follow your sample configuration to achieve pretty much the outcome i was looking for. 

Cheers!
