### ISSUE TITLE
WebGpu makes a wallpapered background completely transparent

### ISSUE THREAD

**Issue by junkblocker** [wez/wezterm#3773]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Whatever is default for Fedora 38 KDE/Plasma on Wayland

### WezTerm version

20230522-115955-bb23d046

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

1. With front_end = "WebGpu" the wezterm window with a wallpaper becomes transparent. Only the text is opaque.
2. With front_end = "OpenGL" the same setup works correctly.
3. Without a wallpaper, the WebGpu rendering is properly black and opaque

### To Reproduce

Switch the front_end between WebGpu and OpenGL. Most of the time it requires killing wezterm and relaunching it after the configuration switch.

### Configuration

``` lua
local wezterm = require "wezterm"
local config = wezterm.config_builder() -- {}
local home = wezterm.home_dir

if true then
    config.enable_wayland = true
    config.enable_kitty_graphics = true
    config.front_end = "OpenGL"
    config.front_end = "WebGpu"
    config.background = {
       -- This is the deepest/back-most layer. It will be rendered first
       {
           source = {
              File = home .. "/Pictures/Wallpapers/1419340005673-2560x1440.jpg", -- replace with any image
        },
         -- The texture tiles vertically but not horizontally.
            -- When we repeat it, mirror it so that it appears "more seamless".
            -- An alternative to this is to set `width = "100%"` and have
            -- it stretch across the display
            repeat_x = 'NoRepeat',
            hsb = { brightness = 0.05},
            -- When the viewport scrolls, move this layer 10% of the number of
             -- pixels moved by the main viewport. This makes it appear to be
             -- further behind the text.
             attachment = "Fixed",
             horizontal_align = 'Center',
             vertical_align = 'Middle',
             horizontal_offset = 0,
             vertical_offset = 0,
             height = "Cover",
         },
     }
    return config
end
```

### Expected Behavior

WebGpu should hopefully work correctly just like OpenGL does.

### Logs

```
Debug Overlay
wezterm version: 20230522-115955-bb23d046 x86_64-unknown-linux-gnu
Window Environment: Wayland
WebGPU: name=Intel(R) Xe Graphics (TGL GT2), device_type=IntegratedGpu, backend=Vulkan, driver=Intel open-source Mesa driver, driver_info=Mesa 23.0.3, vendor=32902, device=39497
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>
20:56:07.635 INFO wezterm_gui::termwindow::render::paint > Not enough texture space (texture dimensions 4096x4096 exceeed the max dimension 2048 supported by your GPU); will retry render with Scale(2)
20:56:07.783 INFO wezterm_gui::termwindow::render::paint > Not enough texture space (texture dimensions 4096x4096 exceeed the max dimension 2048 supported by your GPU); will retry render with Scale(2)
20:56:07.828 INFO wezterm_gui::termwindow::render::paint > Not enough texture space (texture dimensions 4096x4096 exceeed the max dimension 2048 supported by your GPU); will retry render with Scale(2)
>
```

### Anything else?

`mesa-vulkan-drivers` package is installed. I have no problem with playing any videos with graphics acc. or otherwise.

**Comment by wez** [comment]
The issue here is that your vulkan implementation (enabled by WebGPU) has a smaller max texture size than your OpenGL implementation; then, we'd incorrectly skip painting the background layer after deciding that we should scale it down to fit in the texture space.

That should be fixed now in `main`.

**Comment by junkblocker** [comment]
Thanks, working perfectly now.
