### ISSUE TITLE
The term  and nvim display icons differently

### ISSUE THREAD

**Issue by xaotag** [wez/wezterm#3778]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

wayland

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

https://github.com/wez/wezterm/assets/40427877/edc3c1ce-6e88-446e-9160-43eb2e4c1acd

### Configuration
```lua
local wezterm = require 'wezterm'
local config = {}
config.font_size = 18.0
config.font = wezterm.font_with_fallback({
  {family = 'JetBrains Mono', weight = 'Medium'}, {family = 'Twemoji Mozilla'},
  {family = 'JetBrainsMono Nerd Font', stretch = "Normal", italic = false},
  "WenQuanYi Micro Hei"
})
config.allow_square_glyphs_to_overflow_width = "Always"
config.color_scheme = 'tokyonight_storm'
config.window_background_opacity = 0.90
config.enable_tab_bar = false
config.colors = {foreground = '#c5c8c6', background = '1d1f21'}
config.window_padding = {left = 2, right = 0, top = 5, bottom = 0}
config.adjust_window_size_when_changing_font_size = false
config.enable_wayland = true
config.freetype_load_flags = "FORCE_AUTOHINT"
config.custom_block_glyphs = false
return config

```

**Comment by wez** [comment]
Sounds like nvim is doing something to the emoji flag sequences when it opens the file. I think this is a question for nvim folks to find out why.

**Comment by xaotag** [comment]
but kitty....

https://github.com/wez/wezterm/assets/40427877/d8653f7c-6335-4e47-ae3b-e3ac2e00b3e7

**Comment by xaotag** [comment]
```lua
vim.api.nvim_command("call setcellwidths([[0x1f1e6, 0x1f1ff, 1]])")
```
![image](https://github.com/wez/wezterm/assets/40427877/3d85b1f9-0313-4c7c-b662-c067e900815a)

fix_bug
