### ISSUE TITLE
Add horizontal scrolling to WezTerm

### ISSUE THREAD

**Issue by TylerBarnes** [wez/wezterm#3786]
In some TUI apps like (N)VIM text can spill outside the horizontal boundaries of the screen.
I mostly use a trackpad when I'm browsing a codebase or reviewing a PR, and being able to horizontal scroll makes this much more comfortable.

Horizontal scroll was added to termwiz but WezTerm doesn't utilize it yet (see https://github.com/wez/wezterm/discussions/3749#discussioncomment-5962204)

I'm currently in the process of switching from kitty to WezTerm and this is the only thing stopping me from 100% switching over so I'd love to see this implemented!

If I knew Rust I would help 😅 but I unfortunately do not

**Comment by wez** [comment]
Please try the nightly build; https://github.com/wez/wezterm/pull/3856 was just merged to allow for horizontal wheel events.
