### ISSUE TITLE
Add option for setting tab bar height

### ISSUE THREAD

**Issue by seasonedfish** [wez/wezterm#3789]
**Is your feature request related to a problem? Please describe.**
The tab bar is quite short by default, especially with `INTEGRATED_BUTTONS` set in `window_decorations`. It feels a little cramped. Compare wezterm and chrome, which has window decoration buttons integrated in its tab bar as well:
<img width="343" alt="image" src="https://github.com/wez/wezterm/assets/29507110/346b60b6-6a5c-43bd-9453-0a755a9dc68a">
<img width="344" alt="image" src="https://github.com/wez/wezterm/assets/29507110/3987ab94-d83d-4a45-b228-05f67ec7f118">

In wezterm, there is much less space around the window decoration buttons due to the shorter tab bar height.

**Describe the solution you'd like**
It would be great to have a config option to set the height of the tab bar. Setting a larger tab bar height would make the UI feel less cramped.

**Describe alternatives you've considered**
Alternatives:
- Don't provide config option, but change default tab bar height

**Additional context**
N/A

**Comment by wez** [comment]
You can set the font size for the tab bar to increase its height. See:
https://wezfurlong.org/wezterm/config/appearance.html#native-fancy-tab-bar-appearance

**Comment by seasonedfish** [comment]
That makes things better, thanks!
