### ISSUE TITLE
Slow start on Linux

### ISSUE THREAD

**Issue by seqizz** [wez/wezterm#379]
## Describe the bug

My muscle memory triggers terminal shortcut and immediately writes "ssh" every morning. Since I've been using wezterm, I realized I've been writing "sh" a lot, since first key is lost while wezterm was loading.

Here is a small comparison:

Wezterm, triggered 2nd time from a running wezterm:
```
$ time -v wezterm start echo ok
...
        User time (seconds): 0.23
        System time (seconds): 0.16
...
```

Alacritty, triggered 2nd time from a running alacritty:
```
$ time -v alacritty -e echo ok
...
        User time (seconds): 0.11
        System time (seconds): 0.03
...
```

Not sure if this is a sane way to benchmark, but it definitely reflects how it feels like.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: Unknown (built from one of the latest commits: 2603f9d4)

## Configuration

Not sure if this is the factor but here is full config:
```
local wezterm = require 'wezterm';
return {
    font = wezterm.font_with_fallback({"Fira Code", "Inconsolata"}),
    font_size = 17.0,
    font_antialias = 'Subpixel',
    dpi = 96.0,
    scrollback_lines = 20000,
    enable_tab_bar = false,
    harfbuzz_features = {"ss03", "ss08"},
    enable_wayland = false,
    color_scheme = "Afterglow",
    mouse_bindings = {
    -- Change the default click behavior so that it only selects
    -- text and doesn't open hyperlinks
    {
      event={Up={streak=1, button="Left"}},
      mods="NONE",
      action="CompleteSelection",
    },

    -- and make CTRL-Click open hyperlinks
    {
      event={Up={streak=1, button="Left"}},
      mods="CTRL",
      action="OpenLinkAtMouseCursor",
    },
  },
  keys = {
    -- Turn off the default action example
    {key="=", mods="CTRL", action="DisableDefaultAssignment"},
    {key="RightArrow", mods="CTRL|SHIFT", action="DisableDefaultAssignment"},
    {key="LeftArrow", mods="CTRL|SHIFT", action="DisableDefaultAssignment"},

    {key="+", mods="CTRL", action="IncreaseFontSize"},
    {key="4", mods="CTRL", action="IncreaseFontSize"},
    {key="-", mods="CTRL", action="DecreaseFontSize"},
    {key="0", mods="CTRL", action="ResetFontSize"},
  }
}
```

Can provide more information if it'd help. There were other semi-similar "slow start" tickets which I didn't want to re-animate but sorry if this is a duplicate.

**Comment by wez** [comment]
Do you have a sense for whether you're starting to type before or after the window is mapped on the display?  That will help focus where to look for slowdowns.

**Comment by wez** [comment]
Please also run: `RUST_LOG=trace wezterm 2>& /tmp/startup.log` and attach `/tmp/startup.log` to this issue.

**Comment by seqizz** [comment]
It feels like mapping the window is taking the time, shell populates fast enough afterwards.
Attaching the log, I've terminated the run with an alt-tab and ctrl-c after terminal was loaded.
[startup.log](https://github.com/wez/wezterm/files/5691649/startup.log)

**Comment by wez** [comment]
There's a 0.2 interval here in the logging; that second line is output after wezterm has resolved your font selection and then parsed the fonts to compute the font metrics that are needed to determine the initial window size:

```
 2020-12-14T21:20:48.152Z TRACE async_io::driver            > block_on: sleep until notification
 2020-12-14T21:20:48.344Z TRACE wezterm_font::shaper::harfbuzz > [OnDisk { path: "/nix/store/samvcq5lbl4pva0ri43j1lm6yzpgwnpn-fira-code-5.2/share/fonts/truetype/FiraCode-Regular.ttf", index: 0 }, OnDisk { path: "/nix/store/ffq5816pg9lnv9sfmvdgly6dwhb86hwm-inconsolata-2019-07-14/share/fonts/truetype/inconsolata/Inconsolata-Regular.ttf", index: 0 }, OnDisk { path: "/nix/store/3xiw8x4kwr1llxgjxmdwws7nsz92ddwk-noto-fonts-emoji-unstable-2020-08-20/share/fonts/noto/NotoColorEmoji.ttf", index: 0 }, Memory
{ name: "../../assets/fonts/JetBrainsMono-Regular.ttf", data_len: 140776, index: 0 }, Memory { name: "../../assets/fonts/LastResortHE-Regular.ttf", data_len: 502504, index: 0 }]
```

I think the most likely thing consuming time here is processing the font-config results.  I think I can see a case where we can avoid some work, so I'll push that up in a new commit, and add some more trace debugging to see if we can get a bit more insight if that doesn't resolve this.

**Comment by seqizz** [comment]
With this one, indeed it got faster as predicted:

```
User time (seconds): 0.20
System time (seconds): 0.13
```

**Comment by wez** [comment]
I shaved off a bit more fontconfig related time in the commit I just pushed.  If things are still not quite fast enough, please share an updated trace so that we can see where the time is going.

**Comment by wez** [comment]
There aren't any obvious low hanging fruits to go after now, so I'm inclined to call this good enough; the personal rewards for shaving off more milliseconds from the startup on linux aren't worth the amount of time I'd need to spend to find them.

If you, or someone else discovering this issue, are feeling motivated and want to perform some profiling and discuss the results and then work on improving it, I'd be happy to help steer you in the right direction.

But for now: I'm going to close this out!
