### ISSUE TITLE
Add the posibility to have opacity background color in tabs

### ISSUE THREAD

**Issue by AesthetiCoder** [wez/wezterm#3802]
there is a diferences in colors in my terminal with the background opacity and the background color of the tabs it will be nice if we can use opacity or change the colors with rgba i already try rgba but not working

![image](https://github.com/wez/wezterm/assets/70770072/f5ad3c1b-9b0b-49cf-9085-248863629a76)

**Comment by wez** [comment]
This should already work; you need to set the tab bar itself to be transparent as well as the tabs.
See the configuration in:
* https://github.com/wez/wezterm/issues/3450
