### ISSUE TITLE
Can't map CTRL + SHIFT + J

### ISSUE THREAD

**Issue by VictorLemosR** [wez/wezterm#3813]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230530-062729-95e44f21

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm on windows 10. 
Tried to map CTRL + SHIFT + J and couldn't. Tried more than one function to it. Also tried key_map_preference = "Physical" and no success.

"CTRL + SHIFT + K" and "CTRL + SHIFT + DownArrow" work normal.

That's the output of "wezterm show-keys --lua":
```
return {
  keys = {
    { key = ',', mods = 'CTRL', action = act.SplitVertical{ domain =  'CurrentPaneDomain' } },
    { key = 'J', mods = 'CTRL', action = act.AdjustPaneSize{ 'Down', 2 } },
    { key = 'K', mods = 'CTRL', action = act.AdjustPaneSize{ 'Up', 2 } },
    { key = 'DownArrow', mods = 'SHIFT|CTRL', action = act.AdjustPaneSize{ 'Down', 2 } },
  },
```

### Configuration

```
local wezterm = require 'wezterm'
local act = wezterm.action

local size_adjust = 2

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.front_end = "Software"

config.disable_default_key_bindings = true

config.keys = {
  { key = ',', mods = 'CTRL', action = act.SplitVertical { domain = 'CurrentPaneDomain' }, },

  { key = 'J', mods = 'CTRL|SHIFT', action = act.AdjustPaneSize { 'Down', size_adjust } },
  { key = 'DownArrow', mods = 'CTRL|SHIFT', action = act.AdjustPaneSize { 'Down', size_adjust } },
  { key = 'K', mods = 'CTRL|SHIFT', action = act.AdjustPaneSize { 'Up', size_adjust } },

}
return config

```

**Comment by wez** [comment]
Please run through https://wezfurlong.org/wezterm/troubleshooting.html#debugging-keyboard-related-issues and report back

**Comment by VictorLemosR** [comment]
After the log, I was able to confirm "J" was not being pressed down.
Used some generic keyboard test online and it was not pressed there either, also used another keyboard and the same happened.
I've already searched for that hotkey and no success.

This looks like not a problem from wezterm and I'll close it now
