### ISSUE TITLE
Mention of %COMSPEC% can lead Windows users to change the variable

### ISSUE THREAD

**Issue by debashisbiswas** [wez/wezterm#3816]
**What page or section of the docs have an issue?**
https://wezfurlong.org/wezterm/config/launch.html

**Describe the issue**
On this page, the Windows setup page mentions that the shell will be determined by the value of the `%COMSPEC%` environment variable if it is set. This implies that one method of changing the shell is to change this variable. However, this is not recommended on Windows, as it seems to break many programs which assume the variable will be pointing to `cmd.exe`.

I had initially changed my `%COMSPEC%` variable to point to PowerShell, and it took me a while to figure out why some of my tools stopped working. I'd like to help other users avoid the same situation. Would it make sense to add a warning of some kind to the docs to make it clear that this variable is not meant to be changed? I see another user was confused by the same thing: https://github.com/wez/wezterm/issues/3317

**Comment by ulyssesdotcodes** [comment]
I ran into this too. By changing COMSPEC, whenever pwsh runs a .cmd file (e.g. npm, but tons of others too) instead of just running the file with cmd, it starts pwsh to run cmd to run the file, which, instead of running cmd directly, runs pwsh, which.... etc.

This is a huge error in the documentation as it causes an issue that's not obvious and very difficult to track down.

**Comment by requizm** [comment]
@ulyssesdotcodes I agree.

I run into [the same issue](https://www.reddit.com/r/PowerShell/comments/161v6gr/powershell_creates_infinite_child_processes/). It should be mentioned in the documentation as a warning. Huge issue.

**Comment by wez** [comment]
This is how the docs have looked for the past week:

![image](https://github.com/wez/wezterm/assets/117777/c1b40983-151a-4543-8c53-6b36be7c74c2)

It's not going to get much better than this.

**Comment by requizm** [comment]
@wez Thank you for the note. But..

Shouldn't we give a warning on the installation page? It is literally breaking PowerShell CMD execution. As a user, If I'm going to install wezterm, should I read the launch page? I thought it was enough to read the installation page for installing wezterm, without breaking PowerShell.

Let's think this way. I installed wezterm. I haven't used it much, but suddenly PowerShell broke. I suspected wezterm was doing something and deleted it but nothing changed. Upon further inspection, I found out(reddit actually) that it changed ComSpec.

**Comment by wez** [comment]
wezterm does not change comspec.
Can you share what steps you took to install wezterm?

**Comment by wez** [comment]
To clarify: wezterm does not, has never and will never change COMSPEC. If it is changed on your system, something else did it.

**Comment by requizm** [comment]
@wez That's interesting. Sorry for the misunderstanding. I installed it with choco. Nothing specific.

However, I couldn't find the infinity process problem anywhere else except this repo.
