### ISSUE TITLE
Sync color schemes and add hardhacker

### ISSUE THREAD

**Issue by wez** [wez/wezterm#3831]
There's been some changes around tokynight in the upstreams that need careful review,

then add this repo to the sync machinery:

https://github.com/hardhackerlabs/theme-wezterm/blob/master/hardhacker.toml

https://github.com/hardhackerlabs/theme-wezterm/issues/2

Also add this one while looking at this:
* https://github.com/ribru17/bamboo.nvim/issues/4

**Comment by skoowoo** [comment]
Thanks for your work and wezterm. 

I am the maintainer of hardhacker, if you have any questions you can send me an issue directly.

thanks again.

**Comment by wez** [comment]
This is done and hardhacker and bamboo will be available in nightly builds within about an hour.
