### ISSUE TITLE
Nightly builds does not render GUI on Windows, unless front_end='OpenGL' is explicitly set

### ISSUE THREAD

**Issue by p4thie** [wez/wezterm#3834]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230530-062729-95e44f21

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

launching `wezterm.exe` results in the Windows dialog saying "wezterm.exe stopped working", and launching `wezterm-gui.exe` does nothing (no window or whatsoever showsup), unless `front_end='OpenGL'` is set. This is not an expected behavior since nightly should work out of the box.

### To Reproduce

1. download / install 20230530-062729-95e44f21
2. launch a. `wezterm.exe` or b. `wezterm-gui.exe`
3. a. you should get the Windows dialog saying "wezterm.exe stopped working", b. no window or whatsoever shows up.

> Unhandled exception at 0x00007FFDE96BC9F0 (igc64.dll) in wezterm-gui.exe: 0xC0000005: Access violation reading location 0x0000015A0000011A.

### Configuration

if `front_end='OpenGL'` is not set, you should run into this issue.

### Expected Behavior

Nightly version should launch itself out of the box.

### Anything else?

Originally reported as a question here
https://github.com/wez/wezterm/discussions/3833

**Comment by wez** [comment]
we switched back to OpenGL by default
