### ISSUE TITLE
[bug] copy mode on wayland

### ISSUE THREAD

**Issue by justchokingaround** [wez/wezterm#3843]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20230530-062729-95e44f21

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Copying using `Copy Mode`, with the `CTRL-SHIFT-X` keybind on wayland does not work.

Note: it does work properly if an input was copied prior to using `Copy Mode`, using the mouse, in the same window.

### To Reproduce

1. Open a fresh wezterm window
2. Run any command
3. Try copying using `Copy Mode` with either `y` or `CTRL-SHIFT-C` (both don't work)

### Configuration

no config

### Expected Behavior

Copying should work without needing to use the mouse, not even once.

**Comment by osandov** [comment]
I've been hitting this bug, too. I think I fixed it in #3929.

**Comment by justchokingaround** [comment]
tested, and can confirm that it fixes my bug <3
