### ISSUE TITLE
CTRL + "+" or CTRL + "-" also increases the window size 

### ISSUE THREAD

**Issue by hensou** [wez/wezterm#3844]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

awesomewm 4.3

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Whenever i try to increase the font size with the default **CTRL+"+"** and **CTRL+"-"** shortcuts it also increases the window size. 

I've recorded a video of the behavior.

https://github.com/wez/wezterm/assets/1756077/2fd375de-9eb5-4127-aacf-bd768624ae1e

### To Reproduce

**CTRL+"+"** and **CTRL+"-"** and the window changes the size with the font size

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
	config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

local custom_theme = wezterm.get_builtin_color_schemes()["Belafonte Day"]
config.color_schemes = {
	["My theme"] = custom_theme,
}
config.color_scheme = "My theme"

-- Spawn a fish shell in login mode
config.default_prog = { "/usr/bin/fish", "-l" }

config.font = wezterm.font("JetBrains Mono")

config.keys = {
	-- This will create a new split and run your default program inside it
	{
		key = '"',
		mods = "CTRL|SHIFT|ALT",
		action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }),
	},
}

-- and finally, return the configuration to wezterm
return config

```

### Expected Behavior

I expected it to only resize the font size.

### Logs

Debug Overlay
wezterm version: 20230408-112425-69ae8472 x86_64-unknown-linux-gnu
Window Environment: X11 awesome
OpenGL version: AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.49, 6.1.32-1-lts) 4.6 (Compatibility Profile) Mesa 23.1.1
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
09:54:04.193 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
09:57:19.781 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
09:57:54.986 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
09:58:15.636 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
10:00:10.748 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)

**Comment by wez** [comment]
See: https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html
