### ISSUE TITLE
It appears `augment-command-palette` event does not fire on nightly

### ISSUE THREAD

**Issue by miversen33** [wez/wezterm#3853]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 KWin

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Following [the doc example for `augment-command-palette`](https://wezfurlong.org/wezterm/config/lua/window-events/augment-command-palette.html?h=augment#adding-a-rename-tab-entry-to-the-palette), it appears that the callback function is not being called. Which leads me to believe that the `augment-command-palette` event is not being triggered when calling `ActivateCommandPalette`

### To Reproduce

Open wezterm, execute the `ActivateCommandPalette` command (I believe the default keys are `CTRL+P`) and observe that the entry `Rename tab` is not available in the palette, nor is the line `"Hello from augment event!"` logged.

### Configuration

```lua
local wezterm = require 'wezterm'
local act = wezterm.action

local config = wezterm.config_builder()

wezterm.on('augment-command-palette', function(window, pane)
  wezterm.log_info("Hello from augment event!")
  return {
    {
      brief = 'Rename tab',
      icon = 'md_rename_box',

      action = act.PromptInputLine {
        description = 'Enter new name for tab',
        action = wezterm.action_callback(function(window, pane, line)
          if line then
            window:active_tab():set_title(line)
          end
        end),
      },
    },
  }
end)

return config
```

### Expected Behavior

I would expect the augment-command-palette event to be caught, however this issue is most likely an issue on my part.

### Logs

```
Debug Overlay
wezterm version: 20230408-112425-69ae8472 x86_64-unknown-linux-gnu
Window Environment: X11 KWin
OpenGL version: Mesa Intel(R) Graphics (ADL GT2) 4.6 (Compatibility Profile) Mesa 23.1.2
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
> 
```

There is nothing of substance in the logs when executing this event

### Anything else?

I fully believe I am misunderstanding something but I am not really sure what :/

**Comment by wez** [comment]
the version shown in the debug overlay output you shared is not a nightly build; it's the last stable release: `20230408-112425-69ae8472`!

**Comment by miversen33** [comment]
You are absolutely right. I was under the impression that that was the latest nightly build. I seem to have forgotten how wezterm nightlys work lol. Disregard :)
