### ISSUE TITLE
Emacs term mode with bash shell and zsh shell, opens with weird prompt

### ISSUE THREAD

**Issue by utkarsh-singh1** [wez/wezterm#3862]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

x11 

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Emacs term mode with bash or zsh shell, shows weird behavior on prompt -

With ZSH - 

![Screenshot_20230616_120206](https://github.com/wez/wezterm/assets/96516301/96ca3896-8295-4908-80a3-595d655ee823)

With Bash -

![Screenshot_20230616_120429](https://github.com/wez/wezterm/assets/96516301/e9053f61-bbc1-4755-be79-50f7b7799511)

### Configuration

```lua
local wezterm = require 'wezterm'
local config = {}

--- Colorscheme

-- config.color_scheme = 'Dracula'
config.color_scheme = 'Horizon Dark (base16)'

--- Font Config

config.font = wezterm.font('Lilex Nerd Font Propo',{ weight = 'Regular',})

config.font_size = 13.5

return config
```

**Comment by bew** [comment]
Emacs term mode is something in Emacs?

If you're having rendering issues, did you try in another terminal?
If it works in other terminals, I'd suggest giving an exact record of what happens by using [`wezterm record ..`](https://wezfurlong.org/wezterm/cli/record.html) and uploading the generated file.
This will help identify exactly what the program is doing / is sending to the terminal.

**Comment by utkarsh-singh1** [comment]
Hi @bew, 

`wezterm record ..`
 o/p -->>

```log
fatal runtime error: assertion failed: output.write(&bytes).is_ok()
Child status: Some(ExitStatus { code: 1, signal: Some("Aborted") })
*** Finished recording to /tmp/wezterm-recording-ZRqKo5.cast.txt
```

**Comment by wez** [comment]
The `Ptmux` stuff in the screenshot leads me to believe that your shell/terminal setup is confused about the terminal in which it is running; that's a quoting escape intended to pass data through tmux to the outside terminal emulator. It sounds to me like you have a triply-nested terminal situation going on; "emacs term mode" inside tmux inside wezterm.

There's a very high chance that this is specific to your configuration inside each of those inner layers that results in the shell integration escapes being mangled in the intervening layers.

That's something for you to dig into and debug.

Alternatively, if you cannot find the source of the mangling, you may wish to disable some or all of the shell integration features; see:

https://github.com/wez/wezterm/blob/baf9d970816e015bee41ed5eb9186ef7f71c454c/assets/shell-integration/wezterm.sh#L3-L15
