### ISSUE TITLE
Flashing after changing displays multiple times

### ISSUE THREAD

**Issue by wild-endeavor** [wez/wezterm#3880]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

could you take a look at the video when you get a chance and see if this is something that you already know about?  if not, i'll fill in the rest of this form more completely.

I can't repro this, it just happens randomly after moving between a couple different external monitors at home and the office over the course of a couple weeks.

https://github.com/wez/wezterm/assets/2896568/c18da62a-ba21-48a0-9a4f-ba589e450870

### Configuration

nothing major, will fill in later.

**Comment by wez** [comment]
Possibly related to:
* https://github.com/wez/wezterm/issues/3396

I'd suggest maybe trying webgpu instead of opengl and see if that is any better:
https://wezfurlong.org/wezterm/config/lua/config/front_end.html?h=front#webgpu

`front_end = "WebGpu"`

**Comment by wild-endeavor** [comment]
closing for now.  will reopen if it becomes more repro able and less easily corrected.  minimizing/changing displays/triggering yabai actions seem to resolve the issue satisfactorily.
