### ISSUE TITLE
Slow startup on macOS when using "Iosevka Term" font (about 9 seconds)

### ISSUE THREAD

**Issue by globau** [wez/wezterm#3890]
### What Operating System(s) are you seeing this problem on?

macOS 13.4.1

### WezTerm version

20230619-104421-c1f49509

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After switching wezterm's default font to [Iosevka Term](https://github.com/be5invis/Iosevka), startup times increases to approx 9 seconds.

### To Reproduce

1. Install the latest `super-ttc-iosevka-` font from https://github.com/be5invis/Iosevka/releases
2. `config.font = wezterm.font('Iosevka Term')`
3. Open on macOS

### Configuration

```
config.font = wezterm.font('Iosevka Term')
config.font_size = 13
```

### Expected Behavior

Nearly instant launch

### Logs

Edited log; mostly font config removed (full log is 102MB): [wezterm.log](https://github.com/wez/wezterm/files/11832613/wezterm.log) 

Here's the lines that took longer than 100ms (duration is the first number):
```
 168 17:35:39.673  TRACE  wezterm_gui            > failed to connect to Socket("/Users/byron/.local/share/wezterm/gui-sock-6217"): connecting to /Users/byron/.local/share/wezterm/gui-sock-6217
 340 17:35:39.902  TRACE  wezterm_gui::frontend          > Creating TermWindow for mux_window_id=0
1474 17:35:40.259  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Mode(SetDecPrivateMode(Code(BracketedPaste))))
4108 17:35:41.733  TRACE  wezterm_font::locator::core_text       > core text matched FontAttributes { family: "Iosevka Term", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: false, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None } to [
1751 17:35:45.858  TRACE  wezterm_font::locator::core_text       > best match from core text is ParsedFont { names: Names { full_name: "Roboto Bold", family: "Roboto", sub_family: Some("Bold"), postscript_name: Some("Roboto-Bold"), aliases: [] }, weight: FontWeight(700), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "/Users/byron/Library/Fonts/Roboto/Roboto-Bold.ttf" }, index: 0, variation: 0, origin: CoreText, coverage: None }, cap_height: Some(0.7109375), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }
4117 17:35:47.609  TRACE  wezterm_font::locator::core_text       > core text matched FontAttributes { family: "Iosevka Term", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None } to [
1920 17:35:51.755  TRACE  wezterm_gui::termwindow::resize        > dpi_changed=true, font_scale_changed=false scale_changed=true simple_dpi_change=true
4054 17:35:53.675  TRACE  wezterm_font::locator::core_text       > core text matched FontAttributes { family: "Iosevka Term", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: false, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None } to [
1943 17:35:57.737  TRACE  wezterm_font::locator::core_text       > best match from core text is ParsedFont { names: Names { full_name: "Roboto Bold", family: "Roboto", sub_family: Some("Bold"), postscript_name: Some("Roboto-Bold"), aliases: [] }, weight: FontWeight(700), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "/Users/byron/Library/Fonts/Roboto/Roboto-Bold.ttf" }, index: 0, variation: 0, origin: CoreText, coverage: None }, cap_height: Some(0.7109375), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }
4040 17:35:59.680  TRACE  wezterm_font::locator::core_text       > core text matched FontAttributes { family: "Iosevka Term", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None } to [
2039 17:36:03.958  TRACE  wezterm_gui::termwindow::render::paint > quad map elapsed 3.6µs
4093 17:36:05.997  TRACE  wezterm_font::locator::core_text       > core text matched FontAttributes { family: "Iosevka Term", weight: FontWeight(600), stretch: Normal, style: Normal, is_fallback: false, is_synthetic: true, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None } to [
 750 17:36:10.261  TRACE  polling::kqueue                        > wait: kqueue_fd=5, timeout=Some(866.230431ms)
 362 17:36:11.129  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
```

Note the startup time of the logged run was much longer (32 seconds) likely due to the overhead of writing the log (1,797,834 lines).

**Comment by hkrutzer** [comment]
I also had this issue, but only with the TTC version, so I installed the TTF files instead.

**Comment by wez** [comment]
Opening the ttc font in fontbook runs my mac out of memory. I think that font is cursed on the mac

**Comment by globau** [comment]
> Opening the ttc font in fontbook runs my mac out of memory. I think that font is cursed on the mac

I have no problems opening it in fontbook, or any other application (with one exception of course).

**Comment by wez** [comment]
After hard rebooting, I face the same problem: fontbook consumes all physical memory (I have 8GB) and my system hangs and has to be restarted before I is usable again.

I think that font file is too gnarly for the mac to handle.  May be another variation on:
* https://github.com/be5invis/Iosevka/issues/1377

I would recommend not using that super ttc file.

**Comment by wez** [comment]
FWIW, that font works fine on linux; loads instantly.

**Comment by regexPattern** [comment]
I'm having the same issue here. It only happens with Iosevka.

**Comment by wez** [comment]
AFAICT, this is a macOS issue. As mentioned above, I can't even install it on my macbook air: it hard crashes my system by exhausting all memory. If you have more memory, perhaps you can get past that, but that font is hitting some bottleneck in macOS.

Use a different version of the font; avoid the super ttc, it is too much for macOS to handle.

**Comment by hkrutzer** [comment]
I've filed a MacOS issue via Feedback Assistant. Generally nothing comes of those but 🤷‍♂️

**Comment by globau** [comment]
You can install any font by dropping it into ~/Library/Fonts, including this one.  Font Book isn't required.

No other application, including iTerm2, have problems with this font (iTerm2 starts instantly).
Once wezterm has started it works fine, it just takes longer than expected to startup.

In any event looks like this won't be addressed; closing.
