### ISSUE TITLE
Add inject_output in wezterm cli

### ISSUE THREAD

**Issue by Abdillah** [wez/wezterm#3891]
**Is your feature request related to a problem? Please describe.**
Zellij allow us to send text and key that can be used to remote control the workspace. Wezterm has send_text, however it doesn't support escape code as I understand it.

The initial reason of my research is to enable text editor (e.g. neovim) opening file by the command from other pane (e.g. broot tree navigation). Remote controlling the other pane can't be done except using wezterm cli.

**Describe the solution you'd like**
Add `inject-output` to wezterm cli interface.

**Describe alternatives you've considered**
- Add send-key to wezterm cli
- Add more complex custom command or custom lua execution from cli.

**Comment by wez** [comment]
Can you explain in more detail what you're trying to do? I'm not sure I understand this request

**Comment by Abdillah** [comment]
My main goal is to programmatically send text **and keypress** to a Pane of wezterm.

In my scenario, I have two panes a file manager **broot** and a text editor **helix**.
I want to select file in broot and open it in helix / neovim. That is by sending a `send-text` request.

```
wezterm cli send-text ":open $somefileToOpen\n"
```

However, the `\n` or enter doesn't get interpreted as carriage return or pressing <kbd>Enter</kbd>.
After researching, there is `inject_output` command which able to interpret this escape, however not added into the CLI.

The inspiration come from snippet from this issue https://github.com/helix-editor/helix/issues/2177, where zellij able to make text editor open file.

I hope it makes thing clearer.

**Comment by wez** [comment]
Try:

```console
$ wezterm cli send-text --no-paste ":open $somefileToOpen\n"
```

**Comment by Abdillah** [comment]
Oh awesome. 

Rather than `"\n"` I should use "\r":

```
$ wezterm cli send-text --no-paste ":open $somefileToOpen\r"
```

This should be in discussion, thank you!
