### ISSUE TITLE
Initial font size is wrong when launched on external display

### ISSUE THREAD

**Issue by zasdaym** [wez/wezterm#3900]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The initial font size is wrong when launching on an external display (27 inches, 2K resolution). After doing one of these actions the font size is corrected:
1. Resizing the window
2. Changing the font size via keyboard shortcut

### To Reproduce

1. Use the configuration provided below
2. Open on a external display
3. The font size will be too big
4. Try resizing the window, the font size will be corrected

### Configuration

```lua
local wezterm = require 'wezterm'

return {
  font = wezterm.font("Berkeley Mono"),
  font_size = 14,
  front_end = "WebGpu",
  hide_tab_bar_if_only_one_tab = true,
  initial_cols = 180,
  initial_rows = 50,
}
```

### Expected Behavior

The font size is correct when launched on an external display.

**Comment by wez** [comment]
Please try the latest nightly build and let me know if this is still an issue!
