### ISSUE TITLE
when terminal require password the lock icon no display 

### ISSUE THREAD

**Issue by ystyle** [wez/wezterm#3902]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

```shell
Operating System: Arch Linux 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.9-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-10710U CPU @ 1.10GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Dell Inc.
Product Name: XPS 13 7390
````

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

the password icon not display
![image](https://github.com/wez/wezterm/assets/4478635/b7344bdb-0dab-418d-a6f5-e1ba91f3fb43)

### To Reproduce

i don't know

### Configuration

```lua
local wezterm = require 'wezterm'
local mykeys = {
  { key = 'p', mods = 'CTRL|SHIFT', action = wezterm.action.ShowLauncher },
  { key = 'UpArrow', mods = 'CTRL', action = wezterm.action.PaneSelect },
  { key = 'DownArrow', mods = 'CTRL', action = wezterm.action.SplitVertical { domain = 'CurrentPaneDomain' }},
  { key = 'RightArrow', mods = 'CTRL', action = wezterm.action.SplitHorizontal { domain = 'CurrentPaneDomain' }},
  { key = 'w', mods = 'CTRL', action = wezterm.action.CloseCurrentPane { confirm = true }},
}

for i = 1, 8 do
  -- CTRL+ALT + number to move to that position
  table.insert(mykeys, {
    key = tostring(i),
    mods = 'ALT',
    action = wezterm.action.ActivateTab(i - 1),
  })
end

return {
  window_background_opacity = 0.4,
  window_background_image = '/home/ystyle/Pictures/壁纸/gamersky_018origin_035_2015741845474.jpg',
  window_background_image_hsb = {
    brightness = 0.5,
  },
  initial_cols = 120,
  hide_tab_bar_if_only_one_tab = true,
  tab_max_width = 40,
  font = wezterm.font_with_fallback({
    -- /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf, FontConfig
    "JetBrains Mono",

    -- /usr/share/fonts/noto/NotoColorEmoji.ttf, FontConfig
    -- Assumed to have Emoji Presentation
    -- Pixel sizes: [128]
    "Noto Color Emoji",
  }),
  -- color_scheme = "AdventureTime",
  color_scheme = 'AlienBlood',
  default_cursor_style = 'BlinkingBar',
  -- window_decorations = "NONE",
  warn_about_missing_glyphs = false,
  keys = mykeys 
}
```

### Expected Behavior

How to make the icon display normally

### Logs

Debug Overlay
wezterm version: 20230408-112425-69ae8472 x86_64-unknown-linux-gnu
Window Environment: X11 KWin
OpenGL version: Mesa Intel(R) UHD Graphics (CML GT2) 4.6 (Compatibility Profile) Mesa 23.1.3
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
15:23:51.150 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
>

### Anything else?
![image](https://github.com/wez/wezterm/assets/4478635/5eb35625-fef3-46db-8352-429e412dbd46)

_No response_

**Comment by wez** [comment]
See https://matrix.to/#/!PirwUBcuIlTXwNveYz:matrix.org/$i3a5Mn4Hb694M-XUoUw-ckUmAQgGWjP-VR0GsM8Uh_s?via=matrix.org&via=kde.org&via=tchncs.de for more context.

Recommendation is to try the nightly build of wezterm.

**Comment by ystyle** [comment]
Solution: Just reinstall
