### ISSUE TITLE
Latest version has crash on both X11 & Wayland, Kwin

### ISSUE THREAD

**Issue by alxpettit** [wez/wezterm#3904]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Kwin

### WezTerm version

9a24f61c22eb2216acc4c483afdcee1c235b96fe

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Opened wezterm. It crashes and immediately closes. No other symptoms.

### Configuration

```lua
-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

-- Add config folder to watchlist for config reloads.
local wezterm = require 'wezterm';
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)

-- TODO: nicole profile needs bigger default font
local wezterm = require 'wezterm'
local config = {}
local act = wezterm.action

config.keys = {
  { key = 'UpArrow', mods = 'SHIFT', action = act.ScrollByLine(-1) },
  { key = 'DownArrow', mods = 'SHIFT', action = act.ScrollByLine(1) },
  { key = 'v', mods = 'CTRL', action = act.PasteFrom("Clipboard") },
}

config.font_size = 10

-- I think it erroneously hides mouse cursor sometimes, so let's disable that
config.hide_mouse_cursor_when_typing = false
-- OSC yank seems not to work unless I do this
-- so I guess it doesn't work on Wayland?
config.enable_wayland = false
config.enable_scroll_bar = true
return config
```

### Logs

running message loop: process_queued_xcb: poll_for_queued_event: X(Match(RequestError { response_type: 0, error_code: 8, sequence: 278, bad_value: 67108873, minor_opcode: 4, major_opcode: 149, pad: 1 }), None)

**Comment by miversen33** [comment]
I can't provide any code assistance but I can say that I use kwin and X11 and I am not able to reproduce this. For curiosity sake, do you know which version of kwin you are running? And what OS are you on?

**Comment by licosanchez** [comment]
I'm having this issue as well on my laptop.  I have 3 other computers working fine with kde, all pretty much set up exactly the same.  If I start a plasma session, kwin crashes as soon as I open a window.  I don't know what logs to even look at for this though, I'm not seeing anything in any of the logs I've looked at.  
All of my computers are AMD and I'm running Arch on all of these, this started for me a month or two ago.

**Comment by daniel-vainsencher** [comment]
#4290 is possibly a duplicate

I am on pop_os, also using nvidia. Eliding some cruft:

```
(base) danielv@pop-os:~/Software/wezterm$ nvidia-smi
Thu Sep 28 11:03:21 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|   0  NVIDIA GeForce RTX 3080        Off | 00000000:01:00.0  On |                  N/A |
```

**Comment by jbsolomon** [comment]
Same as of updating to Ubuntu 23.10 today.  AMD64, NVidia 4090 driver 535

```
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
```

**Comment by daniel-vainsencher** [comment]
I just rebuild from bc99181, still reproduce the error message of this bug:
```     Running `target/release/wezterm`
11:18:46.053  ERROR  wezterm_gui > 
running message loop: process_queued_xcb: poll_for_queued_event: X(Match(RequestError { response_type: 0, error_code: 8, sequence: 287, bad_value: 113246217, minor_opcode: 4, major_opcode: 149, pad: 1 }), None); terminating
```

**Comment by daniel-vainsencher** [comment]
Workaround that works for me: `cargo run --release --bin wezterm -- --config 'front_end = "OpenGL"'` ("Software" also works, but presumably is slower.

@alxpettit does the above (or something else!) work for you?

**Comment by jonboh** [comment]
I was having the same problem on 05eadb7cb, using `cargo run --bin wezterm -- --config 'front_end = "OpenGL"'` solved it, thanks!

**Comment by alxpettit** [comment]
I think this is totally resolve for me at this point. Thanks @daniel-vainsencher, and sorry for not seeing your message until now.

**Comment by daniel-vainsencher** [comment]
@alxpettit no problem, have a good one :)
