### ISSUE TITLE
Wezterm Remote: Open local web browser

### ISSUE THREAD

**Issue by quodlibetor** [wez/wezterm#3914]
**Is your feature request related to a problem? Please describe.**

I was recently surprised to learn that VS Code remote terminals will open a local web browser when a subcommand attempts to open one (e.g. `python -m webbrowser http://example.com`). This is super convenient.

I don't know of any other terminals that do this, but it is super convenient.

**Describe the solution you'd like**

When a process tries to open a webbrowser in a wezterm remote session, wezterm should either open it blindly or do the VS Code thing where it creates some sort of modal and asks for confirmation before opening it locally.

**Describe alternatives you've considered**

I have looked around to see if there was an obvious configuration setting or plugin I could use.

**Comment by wez** [comment]
FWIW, automatically opening, unprompted, a URL from a remote host sounds like a CVE waiting to happen; I can imagine someone copying and pasting a malicious payload from somewhere on the internet into what is ostensibly an isolated remote machine and suddenly compromising the local system.

I have no plans to build something like this into wezterm; it would require installing some kind of integration on the remote host to capture attempts to open the browser (which is out of scope of wezterm's form/function), as well as plumbing in some logic in wezterm to know that that happened and show the browser.

You can build this sort of thing for yourself if you like; https://wezfurlong.org/wezterm/recipes/passing-data.html explains how to propagate user vars and trigger events in wezterm.

**Comment by quodlibetor** [comment]
That reasoning makes sense, thanks!
