### ISSUE TITLE
Minimum supported version is currently Rust 1.70

### ISSUE THREAD

**Issue by belak** [wez/wezterm#3915]
## Build Environment (please complete the following information):

 - OS: Linux Wayland
 - Linux: NixOS 23.05
   ```
   $ lsb_release -a
   Distributor ID:	NixOS
   Description:	NixOS 23.05 (Stoat)
   Release:	23.05
   Codename:	stoat
   ```
 - Compiler: are you using `clang`, `gcc`, `Microsoft Visual Studio` or something else?  Which version?
 - Rust version: 1.69.0 - I'm using a nix shell to explicitly install 1.69.0, as that's the latest official package in Nix.

## Dependencies

Did you run the `get-deps` script to install required system dependencies?
Was it successful?

No, but I have dependencies installed via a nix shell and it seems to work fine.

If building from the git repo, did you update the submodules?  Not doing this
is a common source of problems; see the information at
<https://wezfurlong.org/wezterm/install/source.html> for more information.

Yes

## The build output

Please include the output from running the build command:

```
$ cargo build --release
error: package `half v2.3.1` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0
Either upgrade to rustc 1.70 or newer, or use
cargo update -p half@2.3.1 --precise ver
where `ver` is the latest version of `half` supporting rustc 1.69.0
```

## Notes

I ran into this because I was trying to build the latest git version to see if it solves my issue with cursors (it does). The nightly is broken on Nix, but that's to be expected because there's a bit of path hackery.

As expected, based on the output, updating to Rust 1.70 fixes this issue. 1.69.0 is one stable release of Rust behind, so I'd personally expect it to work, but if wezterm is now requiring the latest stable version, that works too and the docs should be updated. There are a number of places (note that when I went looking I could only find the one but I could have sworn I saw more) where the supported Rust version is listed as much lower. The [Build From Source](https://wezfurlong.org/wezterm/install/source.html) page comes to mind as it currently lists Rust 1.56.

Maybe the docs there just need to be updated?

**Comment by wez** [comment]
As mentioned in the matrix chat:

There's no specific effort to maintain compatibility with a minimum rust version. The docs are a bit stale, and because there is a large dependency tree, it is difficult to know when one of the deps uses features from more recent versions of rust.  I, and the CI, typically use the latest stable version of rust day to day, so that is usually a safe bet.

For the specific error with `half`, that is some indirect indirect dependency that recently got updated, perhaps because of this sort of thing?

**Comment by wez** [comment]
I'm able to build nightly on rust 1.68.2 on my windows box, so I'm going to close this.
