### ISSUE TITLE
Kitty protocol: Sending a sequence of PNG images shows only the last

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#3918]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Kwin

### WezTerm version

wezterm 20230629-080200-f376468f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Sending a sequence of PNG encoded in [kitty image format](https://sw.kovidgoyal.net/kitty/graphics-protocol/#png-data) with direct placement `<ESC>_Ga=T,f=100` seems to write them out but then immediately blank once the next image is received. Only the last image stays.

### To Reproduce

`zcat` the following file on the terminal. It contains three images, but only the last one is shown (the previous ones are briefly flickering(

[sample-kitty-sequence.terminal.gz](https://github.com/wez/wezterm/files/11924593/sample-kitty-sequence.terminal.gz)

(attempt the same in kitty or Konsole and you get all images)

Wezterm | Kitty
--------------|--------
![wezterm-output](https://github.com/wez/wezterm/assets/140937/5069004b-fc51-46bd-9873-76c820671b0b) | ![kitty-output](https://github.com/wez/wezterm/assets/140937/da5c508b-7423-4b4e-9c08-67179c44f611)

### Configuration

no config

### Expected Behavior

All images are shown

### Logs

```
wezterm version: 20230629-080200-f376468f x86_64-unknown-linux-gnu
Window Environment: X11 KWin
WebGPU: name=NVIDIA GeForce RTX 2080, device_type=DiscreteGpu, backend=Vulkan, driver=NVIDIA, driver_info=535.54.03, vendor=4318, device=7810
```

### Anything else?

I am maintaining `timg` and because of strong flickering of animations with the iterm2 protocol ( #3882 ) I now attempted to just use the Kitty protocol by default on wezterm; kitty works well with animations.
But then I found that an image sequence is not displayed...

**Comment by kovidgoyal** [comment]
See the first item here: https://github.com/wez/wezterm/issues/986#issuecomment-1120622597  to workaround you will need to send the images with ids or numbers (dont recall if weztem supports image numbers or not, if not then ids).

**Comment by hzeller** [comment]
Thanks @kovidgoyal , I now worked around it with IDs in [timg](https://timg.sh/).
I had to be careful handing them out in e.g. animations as wezterm seems to store all images in GPU textures which filled up quickly. So for animations I'll just use two IDs that are used as flip buffers.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by arodland** [comment]
Confirmed:

![image](https://github.com/wez/wezterm/assets/6380/41d19b69-859c-4c93-8cdd-bc642f858dd7)
