### ISSUE TITLE
Panic: attempt to divide by zero while resizing pane

### ISSUE THREAD

**Issue by jonboh** [wez/wezterm#3921]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If you have several vertical panes and try to resize them with the mouse to the point that one would have a size of 0 wezterm panics.

### To Reproduce

Split Horizontally 4 times
Increase the size of the left most pane (draging to the right), when the right most pane gets to size 0 wezterm crashes

### Configuration

no config.

I can reproduce it using wezterm --skip-config

### Expected Behavior

Either the pane gets hidden or is assigned a minimum size, but wezterm should not crash

### Logs
```
20:22:19.383  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{f68e}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
^C

20:25:27.733  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{f68e}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
20:25:53.121  ERROR  env_bootstrap > panic at mux/src/tab.rs:1180:26 - attempt to divide by zero
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: __libc_start_main
  26: <unknown>

thread 'main' panicked at 'attempt to divide by zero', mux/src/tab.rs:1180:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                 %
```
### Anything else?

![image](https://github.com/wez/wezterm/assets/31407988/c639d423-e337-4106-8712-4f3182723ea2)
Pane arragement that will panic

![image](https://github.com/wez/wezterm/assets/31407988/26a46708-f7f8-46fe-a815-b30c5ba4ec7d)

**Comment by wez** [comment]
Please try the nightly build

**Comment by jonboh** [comment]
In the nightly (wezterm 20230629-080200-f376468f) it also happens
![image](https://github.com/wez/wezterm/assets/31407988/f3e03958-5fb0-46d4-a619-ed5e5224c9c0)
![image](https://github.com/wez/wezterm/assets/31407988/06eaebc4-5f0b-433c-9d59-a8c49e9d76e2)

sorry I had intended to use the nightly version when reporting, I didn't realize that yay (the pkg manager for the AUR had failed to install the proper version, now it should be correct).

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jonboh** [comment]
solved! thanks for your work Wez, loving wezterm!
