### ISSUE TITLE
Some characters are rendered as text with width 1, but with 0xFE0F variation selector (16, emoji) 

### ISSUE THREAD

**Issue by erf** [wez/wezterm#3923]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230530-062729-95e44f21

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

My program prints the following characters and they show as a single width text character and not as a double width emoji character even if they have the 0xFE0F variation selector (16) as the last part : ☧️ ☨️ ☩️ 

### To Reproduce

Given the following emoji characters:

☮️ ✝️ ☪️ 🕉 ☸️ ✡️ 🔯 🕎 ☯️ ☢️ ☣️ ⚛️ ☦️ ☧️ ☨️ ☩️ 

These characters are drawn with 2 in length except the last 3: 

☧️ ☨️ ☩️ 

You can try to paste these and step through them or select them in the terminal and see they only take up one size.

☧️ has the following unicode code points: 0x2627 0xFE0F

### Configuration

I have a config file set with:﻿ ﻿m.unicode_version = 15

### Expected Behavior

I would expect these to take up two widths as they should have an emoji presentation.

**Comment by wez** [comment]
codepoint 2627 isn't included in https://www.unicode.org/emoji/charts/emoji-variants.html so the emoji variation selector is not considered to be valid when used with it. I'm not sure about the others; I don't have enough time to figure out which codepoints those are, but I suspect that they are also not listed there
