### ISSUE TITLE
Leader key bindings which require a shifted key do not trigger the bound action

### ISSUE THREAD

**Issue by cxiao** [wez/wezterm#394]
## Describe the bug

When a key binding which uses the leader key as its modifier (i.e. just `LEADER`) and a shifted key is used, the bound action is not triggered. A "shifted" key here refers to a key which requires the SHIFT key to also be pressed for it to be entered. For example, on a standard keyboard, I would need to press SHIFT+\\ in order to enter the '|' character.

If I change the modifer to `LEADER|SHIFT`, i.e. require entering the shift key after the leader key for the binding, the binding works.

I'm not sure if this is a bug, or if this is intended behaviour and I misread the documentation on how to set up modifiers. I did just copy and paste the leader key configuration example from the documentation and it did not do what I expect, so the documentation may be incorrect or misleading.

## Environment

 - OS: Linux Wayland (running under XWayland, `enable_wayland = false`)
 - Version: wezterm 20201101-103216-403d002d

## To Reproduce

1. Set the following in the configuration file - note that this is just the example from the book on how to configure the leader key (https://wezfurlong.org/wezterm/config/keys.html?#leader-key)

```
local wezterm = require 'wezterm';

return {
  -- timeout_milliseconds defaults to 1000 and can be omitted
  leader = { key="a", mods="CTRL", timeout_milliseconds=1000 },
  keys = {
    {key="|", mods="LEADER", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    -- Send "CTRL-A" to the terminal when pressing CTRL-A, CTRL-A
    {key="a", mods="LEADER|CTRL", action=wezterm.action{SendString="\x01"}},
  }
}
```
2. Reload the configuration (i.e. press CTRL+SHIFT+r) and press CTRL+a, then '|' (i.e. SHIFT+\ on a standard keyboard).
3. Observe that nothing happens.
4. Go back to the configuration file, and change the keybinding to include the SHIFT modifier as well in the `mods` field for that binding:
```
local wezterm = require 'wezterm';

return {
  -- timeout_milliseconds defaults to 1000 and can be omitted
  leader = { key="a", mods="CTRL", timeout_milliseconds=1000 },
  keys = {
    {key="|", mods="LEADER|SHIFT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    -- Send "CTRL-A" to the terminal when pressing CTRL-A, CTRL-A
    {key="a", mods="LEADER|CTRL", action=wezterm.action{SendString="\x01"}},
  }
}
```
5. Reload the configuration and press CTRL+a, then '|' (i.e. SHIFT+\\). A horizontal pane split successfully appears.

## Configuration

See above. The included snippet is the entirety of my configuration file.

## Expected behavior

I would expect in the first case above that pressing CTRL+a, then |, would trigger the bound action and split the pane, with just `LEADER` in the `mods` field of that keybinding, and not have to use `LEADER|SHIFT`.

**Comment by wez** [comment]
The issue here is that we don't really *know* from the provided X11 apis whether SHIFT is factored into the keypress.
From what I can see though, if we get a unicode character result then those seem to always factor in SHIFT, so I've pushed a commit that filters it out in that case.

That'll show up in the nightly builds within the next 1-2 hours.

**Comment by cxiao** [comment]
Grabbed the nightly build and that configuration is working as I expect now, thanks very much!
