### ISSUE TITLE
[MacOS] the behavior of cmd+k differs from Terminal

### ISSUE THREAD

**Issue by dakaii** [wez/wezterm#3940]
I just discovered this project and I'm absolutely loving it so far; however, I did notice one thing.

**Is your feature request related to a problem? Please describe.**
I'm mainly a MacOS user and have been using Terminal for the past so many years. On Terminal, cmd+k clears the scrollback buffer as well as the terminal screen, whereas, on Wezterm, it only clears the scrollback. I wasn't sure if it was intended, so I decided to create a feature request.

**Describe the solution you'd like**
Ideally, I'd love it to act the same way Terminal does. I feel as though cmd+k should clear the Wezterm screen as well

**Additional context**
I apologize in advance if there is already another issue for this, or if this behavior is intended. I'd love to take a crack at it if it's a bug, but let me know what you guys think.

**Comment by wez** [comment]
You can rebind that key assignment to have that behavior if you like; see: https://wezfurlong.org/wezterm/config/lua/keyassignment/ClearScrollback.html for more information

**Comment by dakaii** [comment]
@wez Perfect! thank you for the quick response!

**Comment by dakaii** [comment]
@wez I should probably look into this on my own, but I'd greatly appreciate it if you could help me.
This is what I currently have in my .wezterm.lua, and it's working fine. But if I change the mods value to CMD or SUPER or add another entry with the mods value set to CMD or SUPER, it won't work. I'd ideally wanna bind cmd+k with the clear screen action, but am I doing something wrong...?
```
local wezterm = require 'wezterm'
local act = wezterm.action

local config = {}
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.keys = {
 -- THIS IS WORKING CORRECTLY
  {
    key = 'K',
    mods = 'CTRL|SHIFT',
    action = act.Multiple {
      act.ClearScrollback 'ScrollbackAndViewport',
      act.SendKey { key = 'L', mods = 'CTRL' },
    },
  },
   -- THIS WON'T WORK
  {
    key = 'K',
    mods = 'CMD',
    action = act.Multiple {
      act.ClearScrollback 'ScrollbackAndViewport',
      act.SendKey { key = 'L', mods = 'CTRL' },
    },
  },
}
return config
```

**Comment by wez** [comment]
Try enabling key debugging; see: https://wezfurlong.org/wezterm/troubleshooting.html#debugging-keyboard-related-issues

**Comment by dakaii** [comment]
@wez Thanks! cmd+k isn't getting logged out for some reason, but maybe I'll look into it when I get a chance.
