### ISSUE TITLE
Unable to find command in PATH when using SpawnCommandInNewWindow set_environment_variables to edit the PATH

### ISSUE THREAD

**Issue by protiumx** [wez/wezterm#3950]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230706-140733-18e4b9ba

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I want to spawn a command in a new window but it fails to find the command in the `PATH` even though I have attached it

```lua
  {
    key = 'l',
    mods = 'CTRL|' .. key_mod_panes,
    action = act.PromptInputLine {
      description = 'Launch',
      action = wezterm.action_callback(function(window, pane, line)
        if line then
          window:perform_action(act.SpawnCommandInNewWindow {
            args = wezterm.shell_split(line),
            set_environment_variables = {
              PATH = '/Users/brian/.go/current/bin:' .. os.getenv('PATH')
            },
          }, pane)
        end
      end),
    },
  }
```

The following error can be seen the in the debug overlay
```
ERROR wezterm_gui::spawn > Failed to spawn: spawn_tab_or_window: Spawning in domain `local`: TerminalSize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384, dpi: 72 } command=Some(CommandBuilder { args: ["go", "test", "-v", "."], envs: 
...
"PATH": EnvEntry { is_from_base_env: false, preferred_key: "PATH", value: "/Users/brian/.go/current/bin/:/usr/bin:/bin:/usr/sbin:/sbin" }, 
spawn: Unable to spawn go because it doesn't exist on the filesystem and was not found in PATH
```

Same result for any other command that is not in `/usr/bin:/bin:/usr/sbin:/sbin`

### To Reproduce

Set a keymap
```lua
  {
    key = 'l',
    mods = 'CTRL|' .. key_mod_panes,
    action = act.PromptInputLine {
      description = 'Launch',
      action = wezterm.action_callback(function(window, pane, line)
        if line then
          window:perform_action(act.SpawnCommandInNewWindow {
            args = wezterm.shell_split(line),
            set_environment_variables = {
              PATH = <go-path>/current/bin:' .. os.getenv('PATH')
            },
          }, pane)
        end
      end),
    },
  }
```
use any `go` command for the `PromptInput`

### Configuration

no config

### Expected Behavior

It should find any command in the env `PATH` that was added with  `set_environment_variables` config.

### Logs

```
ERROR wezterm_gui::spawn > Failed to spawn: spawn_tab_or_window: Spawning in domain `local`: TerminalSize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384, dpi: 72 } command=Some(CommandBuilder { args: ["go", "test", "-v", "."], envs: 
...
"PATH": EnvEntry { is_from_base_env: false, preferred_key: "PATH", value: "/Users/brian/.go/current/bin/:/usr/bin:/bin:/usr/sbin:/sbin" }, 
spawn: Unable to spawn go because it doesn't exist on the filesystem and was not found in PATH
```

### Anything else?

I have also tried to set `set_environment_variables` in the global config but had the same error

**Comment by wez** [comment]
The logic in wezterm is to check for executable files in the path:
https://github.com/wez/wezterm/blob/f09992f70436f3fb80d585fa132f3481db7d96ea/pty/src/cmdbuilder.rs#L425

if the `access` syscall doesn't indicate that the candiate is executable, then it will be skipped and we'll end up at:
https://github.com/wez/wezterm/blob/f09992f70436f3fb80d585fa132f3481db7d96ea/pty/src/cmdbuilder.rs#L430-L434

Can you `ls -l /Users/brian/.go/current/bin/go` and share what it outputs?

**Comment by wez** [comment]
FWIW, `main` now shows more user friendly information in the case where the default_prog is not spawnable; see:
* https://github.com/wez/wezterm/issues/3928
for more info about that.

**Comment by protiumx** [comment]
@wez I tried adding `/opt/homebrew/bin` and trying to run `btm`, where `btm` is 
```
lrwxr-xr-x@ 1 brian  admin  30 Jun 26 11:19 /opt/homebrew/bin/btm@ -> ../Cellar/bottom
/0.9.3/bin/btm
```
but it also fails if I add 
```
PATH = '/opt/homebrew/Cellar/bottom/0.9.3/bin:' .. os.getenv('PATH')
```
and `btm` is 
```
-r-xr-xr-x@ 1 brian  admin  3371864 Jun 25 06:31 /opt/homebrew/Cellar/bottom/0.9.3/bin/btm*
```

**Comment by wez** [comment]
Can you try that with the nightly build so that we can see what wezterm reports with the improved error messaging?

**Comment by protiumx** [comment]
I tried on last nightly
```
wezterm version: 20230712-072601-f4abf8fd aarch64-apple-darwin
Window Environment: macOS 13.4.1 (22F82)
OpenGL: Apple M1 Max 4.1 Metal - 83.1
```
It seems the issue is related to `set_environment_variables`.
This is the keymap

```lua
{
    key = 'l',
    mods = 'CTRL|' .. key_mod_panes,
    action = act.PromptInputLine {
      description = 'Launch',
      action = wezterm.action_callback(function(window, pane, line)
        if line then
          window:perform_action(act.SpawnCommandInNewWindow {
            args = wezterm.shell_split(line),
            set_environment_variables = {
              PATH = '/opt/homebrew/bin:' .. os.getenv('PATH')
            },
          }, pane)
        end
      end),
    },
  },
```

### Cases

- Setting `set_environment_variables` in global config only, works
```lua
...
window:perform_action(act.SpawnCommandInNewWindow {
            args = wezterm.shell_split(line),
          }, pane)
        end
...
config  = {
  set_environment_variables = {
    EDITOR = 'nvim',
    PATH = '/opt/homebrew/bin:' .. os.getenv('PATH')
  },
}
```

- Setting `set_environment_variables`  in `SpawnCommandInNewWindow`, fails.
```lua
...
window:perform_action(act.SpawnCommandInNewWindow {
            args = wezterm.shell_split(line),
            set_environment_variables = {
              PATH = '/opt/homebrew/bin:' .. os.getenv('PATH')
            },
          }, pane)
        end
...
config  = {
  set_environment_variables = {
    EDITOR = 'nvim',
  },
}
```
Message
```
Unable to spawn btm because:
No viable candidates found in PATH "/usr/bin:/bin:/usr/sbin:/sbin"
⚠️  Process "btm" in domain "local" didn't exit cleanly
Exited with code 1.
This message is shown because exit_behavior="CloseOnCleanExit"
```

**Comment by wez** [comment]
I can't trivially reproduce this.  Can you reduce the config to the smallest self-contained config that triggers this?

**Comment by protiumx** [comment]
This should be enough to reproduce the error
```lua
return {
keys =  {
    key = 'l',
    mods = 'CTRL|ALT',
    action = act.PromptInputLine {
      description = 'Launch',
      action = wezterm.action_callback(function(window, pane, line)
        if line then
          window:perform_action(act.SpawnCommandInNewWindow {
            args = wezterm.shell_split(line),
            set_environment_variables = {
              PATH = '/opt/homebrew/bin:' .. os.getenv('PATH')
            },
          }, pane)
        end
      end),
    },
  },
set_environment_variables = {
    EDITOR = 'nvim',
  },
}
```

**Comment by wez** [comment]
That config snippet isn't valid.  I fixed it up, and I still cannot reproduce this.
If I launch wezterm like this:

```console
$ PATH=/bin /Applications/WezTerm.app/Contents/MacOS/wezterm --config-file /tmp/3950.lua
```

then when I try to input `woot`, an invalid executable, I see a new window with:

```
Unable to spawn woot because:
No viable candidates found in PATH "/opt/homebrew/bin:/bin"
⚠️  Process "woot" in domain "local" didn't exit cleanly
Exited with code 1.
This message is shown because exit_behavior="CloseOnCleanExit"
```

If I try to spawn `vim`, which is in `/opt/homebrew/bin/vim`, then it launches successfully.

**Comment by hustcer** [comment]
I got a similar error with the following config while pressing `Cmd + Shift + N` to spawn `nu` in `~/.cargo/bin` directory:
```lua
local wezterm = require 'wezterm';
local act = wezterm.action;

local set_environment_variables = {
  PATH = '~/.cargo/bin:' .. os.getenv('PATH')
}

local is_mac = wezterm.target_triple:find('darwin')

return {
  initial_rows = 25,
  initial_cols = 100,
  font_size = is_mac and 20 or 15,
  window_background_opacity = 1,
  native_macos_fullscreen_mode = false,
  window_decorations = is_mac and "RESIZE" or "INTEGRATED_BUTTONS|RESIZE",

  color_scheme = 'Desert',
  colors = {
    -- 被选中的内容的背景色
    selection_bg = '#7F7180'
  },

  -- Font settings
  font = wezterm.font_with_fallback {
    'Fira Code',
    'JetBrains Mono',
    'Source Code Pro',
    'Cascadia Code',
  },

  set_environment_variables = set_environment_variables,

  keys = {
    { key = 'N', mods = 'CMD|SHIFT', action = act.SpawnCommandInNewTab { args = { 'nu' } } },
  },
}

```
Output:
```
Unable to spawn nu because:
No viable candidates found in PATH "~/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin"
⚠️  Process "nu" in domain "local" didn't exit cleanly
Exited with code 1.
This message is shown because exit_behavior="CloseOnCleanExit"
```

**Comment by wez** [comment]
`~` is not a valid character for `PATH`, on any OS. It must be expanded before being placed into the environment variable.

I'd suggest using:

```lua
local set_environment_variables = {
  PATH = wezterm.home_dir .. '/.cargo/bin:' .. os.getenv('PATH')
}
```

**Comment by hustcer** [comment]
Oh, Thanks, that works for me.

> 
> I'd suggest using:
> 
> ```lua
> local set_environment_variables = {
>   PATH = wezterm.home_dir .. '/.cargo/bin:' .. os.getenv('PATH')
> }
> ```

**Comment by protiumx** [comment]
hi @wez, sorry for the delay. 
Setting `set_environment_variables ` in the global config works for me.
I haven't had any other issues with it. I'm closing this. Thanks!

**Comment by ratmav** [comment]
@wez:

first, thanks for your awesome terminal emulator. second, i apologize for the zombie comment on a closed issue. i ran into this issue yesterday myself, and noticed a few things that may be useful.

if i start wezterm from another terminal emulator with a shell call, and the `default_prog` isn't in `/usr/bin:/bin:/usr/sbin:/sbin`, wez fires right up. however, if i pin wezterm to the macos dock and use the icon to start wezterm, i get the failure.  for example, in my config i use nvim as the default program if it's present. on macos, i install neovim with homebrew, so the nvim binary is in `/usr/local/bin`. starting wezterm from the default macos terminal works; using the dock icon does not. i tried `set_environment_variables`, but no luck yet.

i suspect there's something about how the dock icon is loading the path, but that's speculative. i have tried just using a script as a pseudo-launcher for wezterm, and that works too. the issue does not occur on windows. i haven't tested a linux host yet, but i doubt the issue will present there.

**Comment by ratmav** [comment]
just in case anyone else hits this, my setup uses neovim as the default program. on macos, i was using homebrew to install neovim, and i had to prepend homebrew's directories to `$PATH` so that wezterm could find the homebrew version of neovim on startup:

```lua
function detect_host_os()
  -- package.config:sub(1,1) returns '\' for windows and '/' for *nix.
  if package.config:sub(1,1) == '\\' then
    return 'windows'
  else
    -- uname should be available on *nix systems.
    local check = io.popen('uname -s')
    local result = check:read('*l'); check:close()

    if result == 'Darwin' then
      return 'macos'
    else
      return 'linux'
    end
  end
end

local host_os     = detect_host_os()

if host_os == 'macos' then
  -- check homebrew binary symlinks on startup.
  config.set_environment_variables = {
    PATH = '/usr/local/bin/:' .. os.getenv('PATH')
  }
end
```

host os detection is probably naive, but should be good enough.
