### ISSUE TITLE
Possibility to download the documentation for offline browsing

### ISSUE THREAD

**Issue by j-xella** [wez/wezterm#3964]
The online documentation is very impressive, but sometimes it would be great to access it when no internet is available.... Yes, it can become outdated this way quickly, but when you want to look up that one option, offline documentation, even outdated, is waaaay better than no documentation at all.

Personally, I would prefer the download to be one file.

* PDF ?
* epub ?
* HTML ?

**Comment by j-xella** [comment]
Would it make sense to create a "build target" that would:

1. run this script,
2. zip the `gh_pages` folder into "html_docs.zip" or similar
3. add the archive as one of the artefacts for each new release and nightly builds

**Comment by wez** [comment]
I have no plans to do the work to maintain that, nor do I want to commit CI or hosting resources to it.
I want the online docs to be used as they can be the most current docs and I can have them updated within a few minutes of amending them.

If you want offline docs, you can use the sources in the repo or build it for yourself.
