### ISSUE TITLE
Setting LEADER to LeftAlt or RightAlt does not work as expected

### ISSUE THREAD

**Issue by justinsgithub** [wez/wezterm#3969]
I would like to have my leader be a single key press, like vim behavior. 

Right now I cannot get just Alt to work on its own as a leader no matter what I've tried. I have to assign Alt + another key, which results in more key presses and kind of defeats the purpose. 

I would like to be able to just press Alt as my leader, without having to combine it with another key.

**Comment by wez** [comment]
You can use `LeftAlt` or `RightAlt`:

```lua
local wezterm = require 'wezterm'

wezterm.on('update-right-status', function(window, pane)
  local leader = ''
  if window:leader_is_active() then
    leader = 'LEADER'
  end
  window:set_right_status(leader)
end)

return {
  leader = { key = 'LeftAlt', mods = 'NONE' },
  colors = {
    compose_cursor = 'orange',
  },
}
```

Run `wezterm --config debug_key_events=true` to have wezterm show which keys are being pressed if you want to discover more.

**Comment by justinsgithub** [comment]
Got it, Thanks a ton!

**Comment by wez** [comment]
I just saw your YT video about this; did the Alt vs. Insert thing work out for you in the end? I would love to see your debug output for that without your insert key remapping trick to make sure that this isn't a weird knock-on from some of the ctrl/alt key issues that were recently fixed in the nightly and latest release!

**Comment by justinsgithub** [comment]
I found the quirk.
I am using latest nightly release. 
Was able to get it working without the INSERT work around :smile: 
I am using [**PopOS!**](https://pop.system76.com/)  by system76 (Ubuntu derivative).

- It looks like Wezterm registers 3 key events when a key is pressed
- In the first event (key is down), modifiers = ALT
- In the second and third event, modifiers = NONE
---

In the first picture, LEADER is not working as expected

---
![wezterm-leader-issue1](https://github.com/wez/wezterm/assets/74565194/1bad5484-0499-425c-a97b-f6098703f54e)
---

In the second picture, LEADER is working as expected, just had to set `mods = 'ALT'`

---
![wezterm-leader-issue2](https://github.com/wez/wezterm/assets/74565194/eea775a9-9f8b-44c7-8afe-35e49801942d)

**Comment by wez** [comment]
I've lost the thread here: is this all working correctly for you now? And in the latest release?

**Comment by justinsgithub** [comment]
Yes it is working, in the latest release I did have to change the config a bit. But it is now working how I believe it was expected to work originally.

Had to change from 

`config.leader = { key = "RightAlt", mods = "ALT" }`

to

`config.leader = { key = "RightAlt", mods = "NONE" }`

Thanks a ton!

**Comment by wez** [comment]
Great, let's close this then!
