### ISSUE TITLE
WIndows full screen maximize and padding problem

### ISSUE THREAD

**Issue by bsong0** [wez/wezterm#3970]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230711-102730-523660c1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

There's always a padding on the bottom line of my terminal when full screened, the padding works good at non-full screen mode, but have a 1 line padding when at full screen mode.

### Configuration
```lua
local wezterm = require 'wezterm'
local config = {}

config.font = wezterm.font 'ComicCodeLigatures Nerd Font'
config.default_domain = 'WSL:ubuntu2004'
config.color_scheme = 'nord'
config.keys = {
    {key="LeftArrow", mods="OPT", action=wezterm.action{SendString="\x1bb"}},
    {key="RightArrow", mods="OPT", action=wezterm.action{SendString="\x1bf"}},
    {key="Backspace", mods="OPT", action=wezterm.action{SendString="\x1b\x7f"}},
}
config.window_close_confirmation = "NeverPrompt"
config.font_size = 9
config.hide_tab_bar_if_only_one_tab = true
config.freetype_load_target = "HorizontalLcd"
config.window_padding = {
  left = '0px',
  right = '0px',
  top = '0px',
  bottom = '0px',
}
return config
```

**Comment by wez** [comment]
That is expected. See https://github.com/wez/wezterm/issues/3391#issuecomment-1492248423 for more discussion

**Comment by bsong0** [comment]
This is from wezterm
![image](https://github.com/wez/wezterm/assets/85090456/4d0d53ba-dba4-493f-8c74-dc602b3df239)
This is from alacritty
![image](https://github.com/wez/wezterm/assets/85090456/b1e3b66c-a0ed-438a-b34e-2ac989bc449f)

**Comment by bsong0** [comment]
Thanks for the fast reply, but there's a whole line of padding, is that also expected?

**Comment by wez** [comment]
looks like less than the cursor height to me, which makes it unusable for text, so it becomes padding
