### ISSUE TITLE
wezterm panics on X11

### ISSUE THREAD

**Issue by ovidiu-ionescu** [wez/wezterm#3972]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Debian/Gnome

### WezTerm version

master

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

> thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x7ffde80989ef', /home/ovidiu/3party/wezterm/fork/wezterm/target/debug/build/xcb-742adc88e75b2c36/out/xproto.rs:8103:13
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 16:57:25.086  ERROR  env_bootstrap > panic at library/core/src/panicking.rs:126:5 - panic in a function that cannot unwind

This is the failing code in xproto.rs:
```rust
    pub fn serialize(&self, wire_buf: &mut [u8]) -> usize {
        debug_assert!(wire_buf.len() >= 4);
        unsafe {
            *(wire_buf.as_mut_ptr() as *mut u32) = self.resource_id();
        }
        4
    }
```

### To Reproduce

Start wezterm and use it a bit.
This seems to only happen in master. The xproto code was transpiled years ago, if it was the culprit I would expect it to happen more often but `wezterm 20230703-132344-9459f64c` runs on the same machine without crashing.

### Configuration

WEZTERM_LOG=info RUST_BACKTRACE=full cargo run --bin wezterm -- -n --config enable_kitty_keyboard=true --config disable_default_key_bindings=true

**Comment by wez** [comment]
There is no `master` branch or version. What version are you actually running? If you built from source, what is the git hash?

**Comment by ovidiu-ionescu** [comment]
Sorry, main not master.

69bb69b9ca30edb82e134a5835fcefadf8830fcc

**Comment by wez** [comment]
Update to at least fd1d614f293efe03ce7e74977d8ca9c1c7a5f43c
