### ISSUE TITLE
Can not install in Debian 12

### ISSUE THREAD

**Issue by y61759h** [wez/wezterm#3973]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Debian 12 Kde X11

### WezTerm version

wezterm-20230712-072601-f4abf8fd.Debian11

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Note, selecting 'wezterm' instead of './wezterm-20230712-072601-f4abf8fd.Debian11.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wezterm : Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

### Configuration

no config

### Expected Behavior

Cound you please package for Debian 12?

**Comment by wez** [comment]
You can now find Debian 12 nightly packages at:
https://wezfurlong.org/wezterm/install/linux.html#installing-on-ubuntu-and-debian-based-systems

Stable Debian 12 packages will be available when we next make a release of wezterm.

**Comment by y61759h** [comment]
Thanks.
