### ISSUE TITLE
Windows Defender detected Trojan:Win32/Randet.A!plock in latest build

### ISSUE THREAD

**Issue by darkliquid** [wez/wezterm#3980]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Using the latest version from the scoop extras bucket, windows defender detects Trojan:Win32/Randet.A!plock and quarantines the file.

### To Reproduce

simply try and install the latest wezterm with scoop on windows

### Configuration

no config

### Expected Behavior

no detected malware

### Logs

![image](https://github.com/wez/wezterm/assets/31256/81a92896-2f23-4fba-afef-f6e9713dc458)

**Comment by wez** [comment]
I can't reproduce any threats detected when I locally download these files and scan them with Windows Defender.
This sounds like it may be an issue that is local to your system!

**Comment by wez** [comment]
Woah, spoke too soon; a threat suddenly popped up after extracting the zip and scanning it and claiming it was clear.
Then the threat cleared itself again.

**Comment by wez** [comment]
I'm like 99% certain this has to be a false positive; the hash produced by CI verifies OK, so the only way this is legit is if GH CI is infected by a trojan from 2017, which seems unlikely.
Now, the question is, how to flag this with Defender without telling people to do something unsafe with their security settings.

**Comment by wez** [comment]
I've submitted a false positive report to Defender; it's id is  17a8f4d0-a7b6-43ac-9802-1dc82b985843.
We'll see what they say about it.

**Comment by wez** [comment]
I got this response:

At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender

2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”

3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

**Comment by julian7** [comment]
I'm not sure, maybe the scan result flagged both mac and windows downloads, both return with zero bytes if I try to download WezTerm-macos-20230712-072601-f4abf8fd.zip or WezTerm-windows-20230712-072601-f4abf8fd.zip:

![image](https://github.com/wez/wezterm/assets/68158/01e32e7c-e8f0-41b8-a6b9-d4e2ea5a5c9e)
