### ISSUE TITLE
`window:perform_action` stopped working

### ISSUE THREAD

**Issue by loqusion** [wez/wezterm#3981]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20230712-141508-4924fd51

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Some of my keybinds which call `window:perform_action` no longer work, and throw errors in the logs.

### Configuration

The following snippet handles some boilerplate for keybind definitions:

```lua
local w = require 'wezterm'

local function split_nav(resize_or_move, key)
  local mods = resize_or_move == 'resize' and 'META|SHIFT' or 'CTRL'
  return {
    key = key,
    mods = mods,
    action = w.action_callback(function(win, pane)
      if is_vim(pane) then
        -- pass the keys through to vim/nvim
        win:perform_action(w.action.SendKey { key = key, mods = mods })
      else
        if resize_or_move == 'resize' then
          win:perform_action(w.action.AdjustPaneSize { direction_keys[key], 3 }, pane)
        else
          win:perform_action(w.action.ActivatePaneDirection(direction_keys[key]), pane)
        end
      end
    end),
  }
end
```

### Logs

```
07:14:17.458 ERROR wezterm_gui::termwindow > while processing user-defined-3 event: bad argument #2 to `GuiWin.perform_action`: error converting Lua table to userdata (expected userdata of type config::keyassignment::KeyAssignment)
stack traceback:
        [C]: in local 'poll'
        [string "?"]:5: in method 'perform_action'
        /home/loqusion/.config/wezterm/smart-splits.lua:50: in function </home/loqusion/.config/wezterm/smart-splits.lua:42>
```

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
