### ISSUE TITLE
Visual bugs when `config.window_decorations = "NONE"`

### ISSUE THREAD

**Issue by sourproton** [wez/wezterm#3982]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Vanilla Gnome Wayland.

Bug doesn't happen on X11.

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

If I set `window_decorations` to `"NONE"` in `~/.config/wezterm/wezterm.lua`, and maximize the window, the terminal presents various visual glitches:

1) The terminal window doesn't look like it has the right size when in the "activities" view, and is completely out of center, unlike normal maximized windows.

![Screenshot from 2023-07-13 11-52-41](https://github.com/wez/wezterm/assets/66533348/9fb14998-58e2-40b1-98e2-67d1a946b7d3)

2) I get lots of visual bugs when editing text with neovim. I can't figure out or reproduce every trigger with consistency, but one of the most consistent ways to bug the terminal is simply deleting a line with `dd`. What happens is that the window seems to un-maximize itself, except that maximizing it doesn't do anything. I have to minimize it and re-maximize the window for it to be back to normal, until I delete another line with `dd`. Yanking a line with `yy` pretty consistenly trigger the same bug.

![Screenshot from 2023-07-13 16-10-17](https://github.com/wez/wezterm/assets/66533348/92ff9956-3170-4d0b-ad7c-3778a0902bd1)

The image above shows the terminal after deleting a line in neovim. It looks like it's just a normal small window, but it was actually maximized before deleting the line, and trying to maximize the window doesn't do anything.

### To Reproduce

1)  launch Gnome on wayland
2) set `config.window_decorations = "NONE"`
3) press win key to switch to "activities view" and one of the bugs
4) open neovim and delete or yank a line and see the other bug

### Configuration

`config.window_decorations = "NONE"`

### Expected Behavior

Not have any visual bugs, i.e. have the window display maximized and centered in activities view and don't have the window ghostly change its size when editing text in neovim.

### Logs

Debug Overlay
wezterm version: 20230408-112425-69ae8472 x86_64-unknown-linux-gnu
Window Environment: Wayland
OpenGL version: Mesa Intel(R) Graphics (RPL-P) 4.6 (Compatibility Profile) Mesa 23.1.3
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
16:03:09.924 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
16:09:56.323 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
16:15:09.029 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)

### Anything else?

Tried installing nightly but couldn't build from source without dependency errors with rust and rustup.

**Comment by theotheroracle** [comment]
another issue is when the windows is resized below a certain point, strange bars show on the side
![image](https://github.com/wez/wezterm/assets/20211219/39da3f53-af0b-40fd-8e9b-73dedff52d34)
wezterm 20230712-072601-f4abf8fd
gnome 44.3

**Comment by wez** [comment]
Please try with the latest nightly build
