### ISSUE TITLE
Open File With WezTerm

### ISSUE THREAD

**Issue by danielneubert** [wez/wezterm#3990]
I switched recently from iTerm to WezTerm and I'm super happy about the switch. I just miss one feature I think that is somehow slightly described within the documentation. Yet I'm unable to get what I search for.

**Is your feature request related to a problem? Please describe.**
I'd like to be able to choose a file (e.g. "example.cpp") within any app (e.g. Finder) and select `Open with WezTerm`. WezTerm should open a new window and run `vim example.cpp` or, even better, detect whether there is a vim session running and if so, simply make `:tabnew` followed by `:e example.cpp`.

For iTerm I wrote a Apple script that was build to an .app that did this described behavior.

**Describe the solution you'd like**
The most optimal solution would be that this is already possible with the given toolset of WezTerm and I'm just to stupid to use it :P

I almoust certain this could be possible with the possibilities given within the [WezTerm Documentation: Launching Programs](https://wezfurlong.org/wezterm/config/launch.html) - but wasn't able to even accomplish something remotely. 

**Describe alternatives you've considered**
Since my Apple Script already contains some commands to simulate keystrokes, I could parse the Application Title of WezTerm, try to find out if it's running an vim instance and do everything as described above with simulated keystrokes. — Yet it's not even close to as comfortable as a build-in solution for file-handling would be.

**Additional context**
Not sure if helpful, but here is my iTerm Apple Script:

```applescript
on appIsRunning(appName)
	tell application "System Events" to (name of processes) contains appName
end appIsRunning

on run {input, parameters}
	if input is {} then
		if appIsRunning("iTerm") or appIsRunning("iTerm2") then
			tell application "System Events"
				key code 53
			end tell
		else
			run script "
				on run {}
					tell application \":Applications:iTerm.app\"
						activate
						try
							select first window
						on error
							create window with default profile
							select first window
						end try
						tell the first window
							tell current session to write text \"nvim\"
						end tell
					end tell
				end run
			" with parameters {}
		end if
	else
		set myPath to POSIX path of input
		set q to "nvim " & quote & myPath & quote
		set qa to ":tabnew"
		set qb to ":e " & myPath
		
		if appIsRunning("iTerm") or appIsRunning("iTerm2") then
			tell application "System Events"
				key code 53
			end tell
			run script "
					tell application \":Applications:iTerm.app\"
						activate
						tell the first window
							tell current session to write text \"nvim\"
						end tell
					end tell
				end run
			"
			tell application "System Events"
				key code 53
			end tell
			run script "
				on run {qa, qb}
					tell application \":Applications:iTerm.app\"
						tell the first window
							tell current session to write text qa
							tell current session to write text qb
						end tell
					end tell
				end run
			" with parameters {qa, qb}
		else
			run script "
				on run {q}
					tell application \":Applications:iTerm.app\"
						activate
						try
							select first window
						on error
							create window with default profile
							select first window
						end try
						tell the first window
							tell current session to write text q
						end tell
					end tell
				end run
			" with parameters {q}
		end if
	end if
	
end run
```

**Comment by wez** [comment]
This sounds very complicated and involved to build as a built-in feature.
It's not really the kind of thing that I would build into wezterm, as it feels a bit over-specialized and difficult to compose.

The CLI provides a reasonable amount of flexibility for scripting.

I'd suggest having your apple script run something like `wezterm start -- vim example.cpp` as a first step.

If you want to get fancy with re-using vim tabs, you can look at https://wezfurlong.org/wezterm/cli/cli/list.html to to try figure out which pane is running vim, then use https://wezfurlong.org/wezterm/cli/cli/send-text.html to send input to it.

Explore the docs for the CLI to see what is possible. https://wezfurlong.org/wezterm/cli/cli/index.html

**Comment by danielneubert** [comment]
Alright, thank you for your response and at least the confirmation that I'm (maybe) not to stupid for the documentation.

Keep up your great work with WezTerm :-) Regardless this minor topic I love it. Have a nice weekend.

**Comment by danielneubert** [comment]
Hello there.

For future visitors that are interested into this: I build a updated applescript with the desired behavior of opening files with (Neo)Vim in WezTerm and if a vim-instance is already running attaching a new tab to it rather than opening a new window.

It works fine for me now yet it was hacked together very quick-and-dirty in combination with PHP for now. Since I hope to update it in the near future to something different, here are the most up-to-date files for the "Open with Vim" solution: https://github.com/danielneubert/dotfiles/tree/main/.config/wezterm
