### ISSUE TITLE
Add "ActivatePaneRelative" to cycle through panes in a window quickly

### ISSUE THREAD

**Issue by gotlougit** [wez/wezterm#3993]
**Is your feature request related to a problem? Please describe.**

Since Wezterm allows `ActivateTabRelative` which allows cycling through tabs, it'd be nice to have something similar for cycling through panes in a window quickly.

The only problem could be that while it is easy to sort tabs for cycling through them, panes would be a bit harder, unless we define some order in which the panes cycle through (like, clockwise or anti-clockwise).

**Comment by wez** [comment]
You can use https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivatePaneDirection.html with `Next` and `Prev` for this
