### ISSUE TITLE
WezTerm doesn't start in Plasma 6 

### ISSUE THREAD

**Issue by hexchain** [wez/wezterm#3996]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin 5.27.80 (upcoming Plasma 6)

### WezTerm version

20230713-174400-115e629e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm fails to start with the following error:

```
interface 'wl_surface' has no event 2
01:15:04.275  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating
```

### Configuration

no config

### Anything else?

This is probably an issue in smithay-client-toolkit v0.16, because its examples fail with the same error in Plasma 6. Those examples in v0.17 work just fine.

**Comment by wez** [comment]
I'd believe that upgrading will resolve this.

I've spent some time looking at updating this dependency; the changes are significant (and positive), but migrating to sctk 0.17 is effectively a rewrite of wayland support in wezterm and I don't currently have the time for this.

**Comment by sevz17** [comment]
See https://github.com/djpohly/dwl/issues/467#issuecomment-1684675968

**Comment by colemickens** [comment]
Hi @wez, I am experiencing various issues with a number of Rust apps with SCTK <=0.17. I asked about this in  `#sway` and one of the SCTK devs opened this:

* https://github.com/Smithay/client-toolkit/pull/406

I tested this by cloning `wezterm` and running `cargo update -p smithay-client-toolkit`.

**I can confirm that `wezterm` is now working again under Sway tip.**

I think this means that you could unblock some Wayland users now without needing to fully move to `smithay-client-toolkit@0.17`. If I'm not mistaken, this will resolve this particular issue.

**Comment by hexchain** [comment]
Thanks for the heads up! I've opened #4322 to bump the dependency version. For me, it successfully starts in Plasma 6 now. It would be nice if someone using another compositor could confirm.
