### ISSUE TITLE
Debug Overlay couldn't enter symbols.

### ISSUE THREAD

**Issue by Pagliacii** [wez/wezterm#3999]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230714-110839-b54b0ce4

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Pressing `CTRL-SHIFT-L` to activate the debug overlay, but it couldn't accept symbols, e.g. `(` or `"`. And `CTRL-D` couldn't exit the overlay.

![image](https://github.com/wez/wezterm/assets/12871143/4d12890c-d1f3-45e1-9113-4e4db71a1c59)

Previous version:

![image](https://github.com/wez/wezterm/assets/12871143/aa0d2c42-0587-4a5d-9be6-1db7a7839ef4)

Nightly version:

![image](https://github.com/wez/wezterm/assets/12871143/45aaadf9-ef38-4608-84e3-f974a9f367b4)

### To Reproduce

Run `wezterm --skip-config`

### Configuration

no config

**Comment by wez** [comment]
What keyboard layout do you have active when typing that?
Is it only the debug overlay where you cannot type those characters?

**Comment by Pagliacii** [comment]
Same qwerty layout when I was typing in the debug overlay of both versions.

And yep, this issue only occurs inside the debug overlay.

**Comment by j-xella** [comment]
Same for me. It seems as if wezterm is trying to do some command completion or someting with the command I type, even before I press `enter`. I wonder if this causes the issue. For example, if I enter `wezterm.`, 3 dots appear below, as if wezterm is trying to produce a list of fields/methods to complete.  And if I type `wez-`, I get "syntax error near '-' " message.

As a temporary workaround, I type the commands in notepad and then paste them in the debug window for the moment.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by Pagliacii** [comment]
Yep, fixed in nightly version
