### ISSUE TITLE
Invalid parameter name in `wezterm.mux.get_tab` method

### ISSUE THREAD

**Issue by outofthere** [wez/wezterm#4006]
In the file [wez/wezterm/docs/config/lua/wezterm.mux/get_tab.md](https://github.com/wez/wezterm/blob/360247fe8dff71993d83108b94c47f0705d388c6/docs/config/lua/wezterm.mux/get_tab.md?plain=1#L1C1-L1C1), the method parameter is specified by `WINDOW_ID`, and should be `TAB_ID`.

```md
# `wezterm.mux.get_tab(WINDOW_ID)`

...

Given a tab ID, verifies that the ID...
```

**Comment by wez** [comment]
Thanks; fixed!
