### ISSUE TITLE
Option to exclude hyperlink_rules from activating on single clicks

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#4014]
**Is your feature request related to a problem? Please describe.**
Given the arbitrary nature of paths, regexes can't handle all of the cases correctly in the absense of some more advanced filtering system, so when trying to double-click to copy a path I sometimes bump into a sequence of that path recognized as `hyperlink_rules`, so I end up opening that invalid path in a browser or a file manager 

**Describe the solution you'd like**
Have an option to exclude`hyperlink_rules` from activating on single clicks, so I could only open with an explicit ctrl-click (other hints like mouseover cursor changes should remain as an indicator of what wezterm thinks a path is)

**Describe alternatives you've considered**
I've looked through mouse bindings section (and my current mouse rules) as it seems to be quite advanced with allowing you to do down/up events, but then couldn't figure out how to __exclude__ link activation, if I disable click down completely via `act.Nop` then it can't cancel selection 

Sorry if I missed some existing way to ignore links

**Additional context**

**Comment by bew** [comment]
The default action for single click is
`wezterm.action.CompleteSelectionOrOpenLinkAtMouseCursor("ClipboardAndPrimarySelection")`

To only stop it from opening links you can set it to:
`wezterm.action.CompleteSelection("ClipboardAndPrimarySelection")`

**Comment by eugenesvk** [comment]
Thanks, and orry about missing that obvious, was confused by all the "Down" defaults
