### ISSUE TITLE
Unable to mouse-select text in Wayland intermittently

### ISSUE THREAD

**Issue by foundObjects** [wez/wezterm#4028]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME/Mutter

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After switching from X11 to Wayland I'm frequently unable to use the mouse to select text. If I click Wezterm highlights that entire line and I'm unable to use the mouse to select any particular piece of text. The bug is present without any mouse configuration settings and with settings.

### To Reproduce

Use Wezterm as normal, this seems random so far.

### Configuration

no config

### Expected Behavior

Text selection should work as normal

### Logs

I'm unable to select text to copy anything at the moment.

### Anything else?

Text selection is broken for me as I write this report but was working last night before bed during the same session. I suspect this could have something to do with suspend/resume? I'll try to verify this theory later today when I have a chance to reboot.

**Comment by wez** [comment]
It's possible that the last_serial needs to be updated/cleared out after suspend resume, or more accurately, a seat change.

Maybe this bit of code:

https://github.com/wez/wezterm/blob/94ab049637c4463595fc2f14abfee24b304a80b4/window/src/os/wayland/connection.rs#L176-L181

should do something like: `*conn.last_serial.borrow_mut() = 0;`

I'm not in a position to try that, but maybe it'll set you in a good direction to poke at it?

**Comment by Fingel** [comment]
I think I am having the same issue. At some point I'm only able to select entire lines via the mouse. Also running wayland Gnome.

**Comment by winter-again** [comment]
I'm also potentially having the same issue, though mine always seems to be triggered when I resume from suspend. For example, if I open a file in Neovim, suspend, and then resume, a single click on a line selects the entire line and sends me to Visual mode. Killing and restarting Wezterm brings back normal behavior. I'm on Wayland (Sway).

**Comment by Fingel** [comment]
I noticed when Wezterm is in this state, clicking the new tab button opens several tabs, almost as if there are multiple mouse clicks being registered. This would be consistent with the behavior of clicking the terminal and only being able to select entire lines as if it were doing a triple click each time.

https://github.com/user-attachments/assets/65eb4f16-ddf5-41f2-9bcd-d7094d474004

**Comment by wez** [comment]
Please try with the latest nightly build
