### ISSUE TITLE
CloseCurrentPane kills shell but pane itself not closing

### ISSUE THREAD

**Issue by Lakroft** [wez/wezterm#4030]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm using latest brew version. 
In configs I've got a key binding:
`{ key = 'w', mods = mod.SUPER, action = act.CloseCurrentPane { confirm = false } },`
When I do 'COMMAND + W' or press 'Close current Pane' in Shell menu, pane's shell stops responding to any input but the pane is still there, it's not closing.
The only error message in logs I've got if I switch to alive pane and then back to 'closed' one. The message says:
`12:41:39.297  ERROR  wezterm_gui::frontend                  > Error reconciling PaneFocused notification: pane 3 not found`

### To Reproduce

Add and load configuration.
Press 'COMMAND + W' or 'Close current Pane' in Shell menu

### Configuration

{ key = 'w', mods = mod.SUPER, action = act.CloseCurrentPane { confirm = false } },

### Expected Behavior

The pane is closed.

### Logs

12:41:39.297  ERROR  wezterm_gui::frontend                  > Error reconciling PaneFocused notification: pane 3 not found

**Comment by paul-hansen** [comment]
This happens for me if I have `CloseOnCleanExit` set in my config:
```lua
config.exit_behavior = "CloseOnCleanExit"
```
With that line I get a similar error:
```
ERROR  wezterm_gui::frontend       > Error reconciling PaneFocused notification: pane 8 not found
```

Commenting the line out makes it work again. Not a great solution because I did want to have CloseOnCleanExit set, but hopefully will help track it down.
