### ISSUE TITLE
Running in an Alpine container fails with Failed to create window: failed to get font metrics!?: FcResultNoMatch

### ISSUE THREAD

**Issue by voltagex** [wez/wezterm#4033]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 / OpenBox / VNC

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

On starting wezterm I get `ERROR  wezterm_gui::frontend > Failed to create window: failed to get font metrics!?: FcResultNoMatch`

I've only tried the version in your first build instructions, will try the nightly later.

I am trying to run WezTerm in a Docker image from https://github.com/jlesage/docker-baseimage-gui
Yes I know this is an odd setup.  I suspect I'm missing fonts or some other dependency but I thought the error message was obscure enough to report.

This image is based on Alpine 3.18 and I have installed the following dependencies:
`libgcc libxkbcommon xcb-util-image xcb-util libxcb libxkbcommon-x11 libx11 fontconfig wayland-libs-egl wayland-libs-client`

### To Reproduce

```Dockerfile
FROM alpine:3.18 as builder
RUN apk update && apk add curl

RUN curl -LO https://github.com/wez/wezterm/releases/download/20230712-072601-f4abf8fd/wezterm-20230712-072601-f4abf8fd-src.tar.gz
RUN tar -xzf wezterm-20230712-072601-f4abf8fd-src.tar.gz
RUN cd wezterm-20230712-072601-f4abf8fd && ./get-deps && cargo build --release

FROM jlesage/baseimage-gui:alpine-3.18-v4

RUN add-pkg libgcc libxkbcommon xcb-util-image xcb-util libxcb libxkbcommon-x11 libx11 fontconfig wayland-libs-egl wayland-libs-client

# Copy the start script.
COPY startapp.sh /startapp.sh

ENV HOME=/config
COPY --from=builder /wezterm-20230712-072601-f4abf8fd/target/release/wezterm /usr/bin/wezterm
COPY --from=builder /wezterm-20230712-072601-f4abf8fd/target/release/wezterm-gui /usr/bin/wezterm-gui
```

startapp.sh is just `exec /usr/bin/wezterm`

### Configuration

no config

### Expected Behavior

wezterm runs... slowly.

### Logs

N/A

### Anything else?

N/A

**Comment by wez** [comment]
Sounds like a font problem in that environment.
See: https://wezfurlong.org/wezterm/troubleshooting.html#debugging-font-display
