### ISSUE TITLE
cannot open two neovim processes

### ISSUE THREAD

**Issue by nbittich** [wez/wezterm#4046]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

20230408-112425-69ae8472 but I tried with the most recent one as well

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

If I open nvim in two different tabs, the new instance is opened in the same tab.

https://github.com/AstroNvim/AstroNvim/assets/3816305/cc04c9a7-a5dc-453c-83ca-5a4c2dc4d955

### To Reproduce

    run nvim
    run nvim again in a different tabs

### Configuration

https://github.com/nbittich/weztetm_config/

### Expected Behavior

it should open two tabs

**Comment by gegoune** [comment]
It's most likely something that astronvim does for you.

**Comment by nbittich** [comment]
@gegoune  no, If I uninstall / reinstall wezterm, things goes back to normal. So I suspect either a bug or some kind of keyboard shortcut I hit by mistake that toggle this behavior ... or something else.
I also opened an issue on wezterm, they say it's not on their end: https://github.com/AstroNvim/AstroNvim/issues/2150

**Comment by gegoune** [comment]
Try `nvim --clean` twice then to make sure it's not coming from you Neovim's configuration.

**Comment by nbittich** [comment]
with nvim --clean, it works as expected. But could you explain me why if I do the same thing on another emulator e.g tilix, there is no issue?

https://github.com/wez/wezterm/assets/3816305/a73db238-9fc9-4e1b-b1a8-c1dd65d33f73

**Comment by gegoune** [comment]
I have no idea, sorry, perhaps your nvim configuration is aware of Wezterm and knows how to check other panes for running processes, but has no such ability for other terminal emulators. Try disabling plugins, etc to try to narrow it down.

**Comment by nbittich** [comment]
thanks, after disabling some plugins, it seems now ok
