### ISSUE TITLE
charselect recency list is not persisted across reboots

### ISSUE THREAD

**Issue by lanceschi** [wez/wezterm#4047]
**Is your feature request related to a problem? Please describe.**
I use emojis in git commit messages. It's really handy to have a recent list when you hit CTRL+SHIFT+U. My problem is that the recent list disappears every time I close WezTerm. I need a way to keep the list from disappearing. Is there a way to configure WezTerm to save the recent list?

**Describe the solution you'd like**
A user-customizable preset of emojis would be great. Having that list editable from the config file would be awesome. This preset would save users time and energy when looking for the right emoji.

**Comment by wez** [comment]
wezterm does save the list.  What platform are you on? How did you install wezterm?

**Comment by lanceschi** [comment]
Thanks for reaching out @wez,

> What platform are you on?

Daily driver is `Linux 5.15.0-76-generic #83~20.04.1-Ubuntu`

> How did you install wezterm?

I downloaded the AppImage, made it executable, renamed it and moved it to a PATH folder

**Comment by lanceschi** [comment]
> My problem is that the recent list disappears every time I close WezTerm

I'm sorry, that was incorrect. Please accept my apologies. When I restart the computer and open WezTerm, the recent list is empty.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

@MLFlexer: heads up! This moves the plugin repos from the runtime dir to the data dir, which may affect your manual installation instructions fro https://github.com/wez/wezterm/discussions/4040

**Comment by lanceschi** [comment]
I can confirm that the fix addresses and solves the issue. I tested the nightly AppImage build for Linux. Thank you @wez

**Comment by lanceschi** [comment]
Issue can be closed

**Comment by MLFlexer** [comment]
> This should be resolved now in `main`.
> 
> It typically takes about an hour before commits are available as nightly builds for all platforms. Linux builds are the fastest to build and are often available within about 20 minutes. Windows and macOS builds take a bit longer.
> 
> Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).
> 
> If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.
> 
> If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
> 
> @MLFlexer: heads up! This moves the plugin repos from the runtime dir to the data dir, which may affect your manual installation instructions for #4040

Thanks for the heads up, appreciate it! I does not seem to change anything :smile:
