### ISSUE TITLE
Configurable word separators

### ISSUE THREAD

**Issue by seqizz** [wez/wezterm#405]
Hi again :wave: 

This time I have a small improvement idea.

When we have something like "test:1212" on the terminal and we double-click on it, wezterm selects (by default) "test:1212", since that's a "word" separated by spaces.

If I remember correctly, most terminals regards some characters as separators. For example a quick test with alacritty: depending on where you double-click, either "test", "1212" or (if you double-clicked on colon itself) "test:1212" is selected.

I couldn't find a configuration option to set this on Wezterm. Digging a bit, I've found `word_around` function which looks like it just cares about spaces (sorry if I missed something clear).

**Comment by wez** [comment]
Yeah, you're close to the right area; I've been meaning to get around to doing this TODO:

https://github.com/wez/wezterm/blob/master/wezterm-gui/src/gui/selection.rs#L54-L64

**Comment by wez** [comment]
This is implemented now in the nightly builds:

```lua
return {
   selection_word_boundary = " \t\n{[}]()\"'",
}
```

**Comment by seqizz** [comment]
Ah, that was fast. Considering fixed so closing the issue, thanks. :tada: 

A small note, (not that someone would depend on this behavior but still): Depending on where you click on a boundary itself, it selects a bit weird.

Consider we have set colon as boundary:

![image](https://user-images.githubusercontent.com/307899/103269264-c2bce680-49b5-11eb-895e-69c2221d5b70.png)
Clicking here causes it to select `t:`

![image](https://user-images.githubusercontent.com/307899/103269367-f861cf80-49b5-11eb-86b6-d42cee1743f4.png)
And clicking here causes it to select `1212` :smile: I guess this is somehow related with #350 .
