### ISSUE TITLE
How do I delete a selection? 

### ISSUE THREAD

**Issue by bzm3r** [wez/wezterm#4063]
**What page or section of the docs have an issue?**
Not sure exactly where this should go (probably under "Default Keybindings"?). 

**Describe the issue**
I find myself needing to sometimes select what I have entered, and delete it.

Copy Mode's selection scheme lets me exit copy-mode without de-selecting, which is nice. But then I am not sure how to go about deleting it. 

Perhaps this doesn't have default keybindings, and is something that we have to configure ourselves? If so, a comment along those lines would suffice in the documentation.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/keyassignment/ClearSelection.html
