### ISSUE TITLE
`force_reverse_video_curor` is not a valid Palette field

### ISSUE THREAD

**Issue by a9iniVb905Q05p3EG693** [wez/wezterm#4070]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME

### WezTerm version

20230722-103103-a07ab883

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

ERROR  mux::connui > Configuration Error: `force_reverse_video_curor` is not a valid Palette field.  There are too many alternatives to list here; consult the documentation!
libEGL warning: DRI2: failed to authenticate

### To Reproduce

wezterm --config "front_end='OpenGL'"

### Configuration

  local wezterm = require 'wezterm'
  config = wezterm.config_builder()
  
  config.colors = {
    foreground = '#000000',
    background = '#ffffff',
    force_reverse_video_cursor = true,
  }
  config.enable_tab_bar = false
  config.font = wezterm.font 'Fira Code Retina'
  
  return config

### Expected Behavior

start

**Comment by wez** [comment]
It's not a bug. You want `config.force_reverse_video_cursor = true` instead.
