### ISSUE TITLE
support multiline implicit hyperlinks

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#408]
## Describe the bug

If the link wraps into the next line only the first line that contains `https://` is supported.

## Environment (please complete the following information):

 - OS: [e.g. Linux X11, Linux Wayland, macOS, Windows]
 - Version: please run `wezterm -V` and include its output here

```
wezterm 20201101-103216-403d002d-210-ga9eaf557
```

## To Reproduce

Steps to reproduce the behavior.

Add a long url and notice how only the first line is underlined. clicking it will cause invalid link.

## Configuration

Be sure to include the relevant section(s) of your `wezterm.lua` configuration file.

## Expected behavior
Should open the link properly in browser when clicking.

## Screenshots

![image](https://user-images.githubusercontent.com/287744/103329648-6a680200-4a12-11eb-88c1-220391fb40f0.png)

**Comment by wez** [comment]
This is intentionally how it works today.

It's a bit tricky to make this work: to avoid recomputing hyperlinks on each character output, the links are deferred until render time.  Rendering only considers changed lines in the terminal model.  To handle something like this case we'd need to look ahead (and backwards) by a potentially arbitrary number of lines (consider a very narrow terminal) off the top and bottom of the viewport to correctly deal with wrapped hyperlinks.

I'm not saying that it can't or won't be made to work, just giving a bit of context on the current state.

**Comment by prabirshrestha** [comment]
That makes sense. It doesn't bug me since I can still copy paste and I barely use links. When  I do want to click links, it is usually local host urls that the server starts and does fit within a line. 

Feel free to close this bug as won't fix if there are no plans. I wouldn't mind.

**Comment by ssoriche** [comment]
As a possible faster/easier implement solution, would it be possible if I have the multiline URL highlighted and click the portion of the URL that's clickable, the whole highlighted URL is opened?

Highlight, copy, switch to web browser, open new tab, cmd+l, cmd+v, is a lot of work :)
