### ISSUE TITLE
Option to disable default quick select patterns 

### ISSUE THREAD

**Issue by Minyus** [wez/wezterm#4086]
**Is your feature request related to a problem? Please describe.**

Default quick select catches lots of unwanted text such as  "11:59" (time is common in shell output), which often requires 2 characters to select text actually wanted.

**Describe the solution you'd like**

Support config.quick_select_patterns_override or config.disable_default_quick_select_patterns

**Describe alternatives you've considered**

**Additional context**

**Comment by wez** [comment]
it already exists: https://wezfurlong.org/wezterm/config/lua/config/disable_default_quick_select_patterns.html

**Comment by Minyus** [comment]
Yes, it works. Thank you!
