### ISSUE TITLE
wezterm-ssh Session  low ability to write files concurrently

### ISSUE THREAD

**Issue by baoyachi** [wez/wezterm#4088]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

with wezterm-ssh:0.4.0 version

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Concurrent write at the same time, limited to 8 count.

At present, it seems that the reason for this is：https://github.com/wez/wezterm/blob/main/wezterm-ssh/src/session.rs#L89-L90

```diff
impl Session {
    pub fn connect(config: ConfigMap) -> anyhow::Result<(Self, Receiver<SessionEvent>)> {
+        let (tx_event, rx_event) = bounded(8);
+        let (tx_req, rx_req) = bounded(8);
...
    }
)
```

### Configuration

-

**Comment by wez** [comment]
What would the ideal value be?

**Comment by wez** [comment]
This request is originally from https://github.com/chipsenkbeil/distant/issues/227
