### ISSUE TITLE
hide_tab_bar_if_only_one_tab = false doesn't work

### ISSUE THREAD

**Issue by dodalovicgran** [wez/wezterm#4092]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

don't know

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`hide_tab_bar_if_only_one_tab = false` doesn't work

![image](https://github.com/wez/wezterm/assets/116893230/96fe3e03-bb94-4b45-88f4-2a4928f54807)

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'
-- This table will hold the configuration.
local config = {}
-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.color_scheme = 'Catppuccin Mocha'

hide_tab_bar_if_only_one_tab = false

config.font = wezterm.font 'M PLUS 1 Code'

config.font_size = 9.0

config.default_cursor_style = 'BlinkingBar'

config.window_decorations = "NONE"

-- and finally, return the configuration to wezterm
config.keys = {
  {
    key = 'h',
    mods = 'ALT',
    action = wezterm.action.SplitHorizontal { domain = 'CurrentPaneDomain' },
  },
  {
    key = 'v',
    mods = 'ALT',
    action = wezterm.action.SplitVertical { domain = 'CurrentPaneDomain' },
  },
}
return config
```

**Comment by dodalovicgran** [comment]
`Pop!_OS 22.04 LTS`

**Comment by wez** [comment]
You're missing `config.` in front. There are no global variables in wezterm's lua.

**Comment by dodalovicgran** [comment]
With or without it - it doesn't work.

![image](https://github.com/wez/wezterm/assets/116893230/1cf31b51-2719-456d-aee2-2edd9e7239d9)
