### ISSUE TITLE
"Return right" ('⮑', U+2B91) char doesn't render as expected.

### ISSUE THREAD

**Issue by cstrahan** [wez/wezterm#4099]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

N/A (macOS 11.7.8 Big Sur)

### WezTerm version

20230802-190652-a7c6ea8c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The following character renders with the placeholder/missing glyph:

| | |
|---|--|
| Symbol | ⮑ |  
| Name | Return right |
| Unicode number | U+2B91 |
| UTF-8 (hex) | 0xE2 0xAE 0x91 |

Here's wezterm using Monaco as the font (this also happens with no user config):

<img width="717" alt="wezterm" src="https://github.com/wez/wezterm/assets/143982/28e2ccfb-54e5-43ba-88a3-020c80bc2952">

Here's iTerm2 with Monaco as the font:

<img width="612" alt="iterm" src="https://github.com/wez/wezterm/assets/143982/5eff11b3-efda-4da8-b461-afd9ac3d1c75">

The character also renders correctly in Firefox and Safari.

(I'll dig through the docs again to see if I'm missing anything)

### To Reproduce

Copy and paste the `⮑` character into the terminal, or run `printf '\xE2\xAE\x91\n'`.

### Configuration

no config

### Expected Behavior

The `⮑` character should render as expected.

### Logs

```
Debug Overlay
wezterm version: 20230802-190652-a7c6ea8c x86_64-apple-darwin
Window Environment: macOS 11.7.8 (20G1351)
WebGPU: name=Intel Iris Pro Graphics, device_type=IntegratedGpu, backend=Metal, vendor=0, device=0
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
14:45:17.775 WARN wezterm_font > No fonts contain glyphs for these codepoints: \u{2b91}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
```

**Comment by cstrahan** [comment]
So I opened the `Font Book` app, click the "Switch to custom preview mode" button, pasted in the `⮑`, and proceeded to manually walk through all the font previews to see which, if any, fonts on my system include the glyph. Unless I overlooked something, it looks like it's only "Helvetica Neue Regular" and ""Helvetica Neue Bold" that contain this glyph.

And if I squint, it looks like that's what iTerm2 is using, despite being configured to use Monaco. I tried googling "iterm helvetica", "iterm font fallback", etc, presuming that there's some sort of fallback that could explain why rendering works there, but no luck.

At any rate, this config does the trick:

```lua
-- use of JetBrains Mono isn't important, of course;
-- I only used Monaco early to try to rule things out, given that iTerm2 defaulted to Monaco.
config.font = wezterm.font_with_fallback { 'JetBrains Mono', 'Helvetica Neue' }
```

<img width="574" alt="wezterm_fized" src="https://github.com/wez/wezterm/assets/143982/b712f2e4-fe94-4b1e-a3f1-0c344dd69977">

---

Somewhat off topic, but for anyone curious:

I stumbled across this while trying out [`vimv`](https://github.com/dmulholl/vimv), " A command line utility for batch-renaming files. "

It uses this character like so:

```
~/tmp on master [!]
% vimv *
Renaming 1_a
      ⮑  foo
Renaming 1_c
      ⮑  bar
```

Seeing `⮑` is a lot less distracting than seeing something along the lines of `�` 😆

**Comment by cstrahan** [comment]
Since I have my config working, I think I'll go ahead and close this.

**Comment by cstrahan** [comment]
Actually, not quite completely resolved, so I'm going to reopen for further discussion.

I went to add a comment to my `wezterm.lua`, so future-me would know why I added Helvetica Neue as a fallback. I opened the config file in neovim to add the comment -- which I currently have configured to make comments italic -- and when I pasted the `⮑`, it displayed the missing glyph again. Which kind of makes sense, given what I said earlier: the only font/weight that has this glyph is "Helvetica Neue" ("Regular" and "Bold" weights).

Is there a way to configure the font fallbacks such that, when looking for e.g. an italic glyph where there is none, it'll attempt to use a non-italic glyph? I checked again in iTerm and it happily renders the non-italic "return right" amid my otherwise italic comment text.

**Comment by cstrahan** [comment]
Pictures re my [last comment](https://github.com/wez/wezterm/issues/4099#issuecomment-1666600103):

WezTerm:

<img width="787" alt="wezterm" src="https://github.com/wez/wezterm/assets/143982/10401db7-7513-4b82-8b7f-a95a4bd7b62a">

iTerm:

<img width="714" alt="iterm" src="https://github.com/wez/wezterm/assets/143982/09410350-2aa2-465b-8f04-df7eda6cca3a">

You can see iTerm has its own quirks, in that the `⮑` overlaps the `;`, but at least its visible -- and leveraging WezTerm's scaling abality, could _maybe_(?) be made to work pretty well, if I could get the regular glyph to be used as a fallback where an italic one isn't available.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by cstrahan** [comment]
Just switched to latest nightly (20230806-104044-211bce50) and I can confirm that this works! Thanks @wez!
