### ISSUE TITLE
Can't write ~ in wezterm on mac (german layout)

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#410]
## Describe the bug

When I input ~ on my german keyboard (option + n), wezterm does not insert the character. I can write in other terminals (iterm2, terminal.app) and I can copy and paste it into wezterm.

## Environment (please complete the following information):

 - OS: macOS Catalina 10.15.7
 - Version: wezterm 20201101-103216-403d002d-213-gb8cabc50
  

## To Reproduce

Have a mac with a German keyboard? I noticed that since a few weeks, never really investiagted until today...

## Configuration

```lua
-- https://wezfurlong.org/wezterm/config/
local wezterm = require 'wezterm';


-- some host specific stuff
-- See also https://wezfurlong.org/wezterm/config/lua/wezterm/hostname.html
local font_size;
if wezterm.target_triple == "x86_64-apple-darwin" then
  -- apple laptop at work
  font_size=12.0
else
  -- private laptop...
  font_size=11.0
end

return {
  -- font = wezterm.font_with_fallback({"JetBrains Mono Semi Light", "Noto Color Emoji"}),
  font_size = font_size,
  -- dpi = 96.0,
  -- font_antialias = "Subpixel", -- None, Greyscale, Subpixel
  font_antialias = "Greyscale", -- None, Greyscale, Subpixel
  font_hinting = "Full",  -- None, Vertical, VerticalSubpixel, Full

  -- this disables ligatures
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},


  -- Use a adjusted tango theme -> in colors subfolder
  color_scheme = "TangoDarkAdjusted",
  --color_scheme = "Builtin Tango Dark",

  -- don't ask the macOS IME/text services to compose input
  use_ime = false,

  keys = {
  	-- from https://github.com/wez/wezterm/issues/253
    -- Make Option-Left equivalent to Alt-b which many line editors interpret as backward-word
    {key="LeftArrow", mods="OPT", action=wezterm.action{SendString="\x1bb"}},
    -- Make Option-Right equivalent to Alt-f; forward-word
    {key="RightArrow", mods="OPT", action=wezterm.action{SendString="\x1bf"}},
  },
}
```

I also tried commenting out `use_ime = false,`but this didn't change it (even after a restart)

## Expected behavior

I get a ~ when I press option+n :-)

**Comment by wez** [comment]
You'll need to set `use_ime = true` for this to work.  Currently that makes some keys have broken key repeat though :-/

**Comment by jankatins** [comment]
I now added `{key="n", mods="OPT", action=wezterm.action{SendString="~"}},` and this gives me back the ~, but it feels strange to configure this...

**Comment by jankatins** [comment]
`use_ime = true,` gives me back the ~, but only after an additional space, not when I release the keys, :-(

Just realized that I also don't get "´"and "´" when I press the key. Oh well, seems I never use them in a terminal :-)

**Comment by wez** [comment]
I just pushed a couple of commits that should help here.  wezterm is now able to figure out whether a key press maps to a dead key without using the IME.  Its processing depends on these config options:

```lua
-- These are the defaults!
return {
  send_composed_key_when_left_alt_is_pressed = false,
  send_composed_key_when_right_alt_is_pressed = true,
  use_dead_keys = true,
}
```

In a US layout, `Left-Opt n` will produce `Alt N` and `Right-Opt n` will wait for a subsequent key press before generating an event; `Right-Opt n SPACE` will emit  `~` whereas `Right-Opt n n` will emit `ñ`.

If you prefer to avoid the hold-state after initiating the dead key press you can use:

```lua
return {
  use_dead_keys = false,
}
```

then the behavior of `Right-Opt n` will be to immediately emit `~` (in a US layout), and you won't be able to enter `ñ` via the keyboard.

**Comment by mbrgm** [comment]
@jankatins Did this solve the issue for you? If yes... do you have a working config you'd be willing to share?
