### ISSUE TITLE
Contribution guidelines for wezfurlong.org

### ISSUE THREAD

**Issue by HaleTom** [wez/wezterm#4100]
I would like to update the page:

https://wezfurlong.org/wezterm/config/lua/config/hyperlink_rules.html

with:

- https://docs.rs/fancy-regex/latest/fancy_regex/#syntax  (look ahead / behind, etc)
- Improved GitHub regex that's more selective and doesn't highlight surrounding whitespace
  - `  regex = [[(^|(?<=[\[(\s'"]))([0-9A-Za-z][-0-9A-Za-z]{0,38})/([A-Za-z0-9_.-]{1,100})((?=[])\s'"])|$)]]`

I couldn't work out how to do so, even after searching for the text on the page, and also looking at the [contributing page](https://wezfurlong.org/wezterm/config/lua/config/hyperlink_rules.html).

How do we go about updating wezfurlong.org?

**Comment by bew** [comment]
The documentation website is generated from markdown files in the `docs` folder in the repository.
In this case that page is this file: https://github.com/wez/wezterm/blob/main/docs/config/lua/config/hyperlink_rules.md (notice the similar path).

Contributing is the same as contributing code, with a pull request on this repository :)

**Comment by wez** [comment]
![image](https://github.com/wez/wezterm/assets/117777/ac67ca19-261b-43e2-a943-c7095f2dc18a)

Those two icons to the right of each page title take you to the source for the markdown page, and to an edit-in-github link that makes it very easy for you to edit and propose a change.

Thanks!

**Comment by ernstki** [comment]
> I couldn't work out how to do so, even after searching for the text on the page, and also looking at the [contributing page](https://wezfurlong.org/wezterm/config/lua/config/hyperlink_rules.html).

@wez I believe this can be closed, since 032d5b7b8b78b1af4479d7e5b933bcf8dab3305b added a section called ["Running the doc build yourself"](https://github.com/wez/wezterm/blob/main/CONTRIBUTING.md#contributing-documentation) to `CONTRIBUTING.md`, and that's how I figured out how to do a documentation PR.
