### ISSUE TITLE
cannot 'cd' to mapped drive when mixing administrator and regular user level tokens on Windows

### ISSUE THREAD

**Issue by iansebryk** [wez/wezterm#4123]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

pretty straightforward:  i can 'cd' into any mounted USB devices without problem, but any network mounted filesystems, it will not 'cd' into.  i can use the context menu to 'Open WezTerm Here', but it only opens a shell at the home directory, not the network folder i clicked in.

when trying to 'cd' over, it generates this error:  "The system cannot find the drive specified.".  however, when i run the same 'cd' from a basic cmd.exe shell, it works just fine, as expected.

furthermore, when checking the logs, it says the path is not readable.  which makes no sense as it is used frequently every day by multiple applications and permissions are identical to host system folders and file.  using baseline cmd produces no issues, nor using any other terminal application, like Console, ConEmu, or MobaXTerm.

any ideas what's going on?  

### To Reproduce

- have a network filesystem mounted
- in the shell, type 'cd <drive_letter>'  ie. 'cd Z:'
- error produced

### Configuration

no config

### Expected Behavior

when i 'cd' to the network mount point, it will change the cwd to the path specified.

### Logs

10:02:50.327  WARN   mux::domain > Directory "<PATH_REDACTED_FOR_SECURITY>" is not readable and will not be used for the command we are spawning: The system cannot find the path specified. (os error 3)

**Comment by iansebryk** [comment]
ignore this.  i am not a Windoze expert, and i did not realize the tokens for user resources are NOT shared with the Administrator.  so when the console is run with UAC enabled, none of the mounted resources are accessible.  to fix this idiocy, you have to change the registry by setting HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLinkedConnections DWORD value to 1 (one).   once this is done, you can run an elevated console and see the user's resources; in this case, a bloody mounted drive.  SMH.  sorry for the post.  remove if you like, but i think this is useful information.  we have to run elevated consoles for 'reasons', and it never occurred to me to check a normal instance.  :P

**Comment by wez** [comment]
We can keep the issue to aid others in the future; I've re-titled it to help clarify the scenario. Thanks for sharing your findings!
