### ISSUE TITLE
"WezTerm Update Available" notification won't stop

### ISSUE THREAD

**Issue by eater** [wez/wezterm#4124]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Ever since I upgraded to 20230712-072601-f4abf8fd, I keep getting systemwide notifications that a new version is available, and every time I launch Wezterm, it says "WezTerm Update Available Click to see what's new".

I believe I am running the most recent release though! 

In addition, it would be nice to have the option to suppress these notifications even if I were running an older release.

### To Reproduce

To reproduce: 
1. Download and install wezterm-20230712-072601-f4abf8fd.Ubuntu22.04.deb
2. Run wezterm.

### Configuration

no config necessary

### Expected Behavior

Notifications of new version should only be displayed when there is a newer release than the one currently running. Also, these notifications should be optional.

**Comment by wez** [comment]
Open the debug overlay to verify which version you are actually running. CTRL-SHIFT-L will show the overlay.

See also: https://wezfurlong.org/wezterm/config/lua/config/check_for_updates.html
