### ISSUE TITLE
Wezterm doesn't have a man page

### ISSUE THREAD

**Issue by Turmaxx** [wez/wezterm#4132]
As the title says, I already configured wezterm but was just curious as to why wezterm doesn't have a man page.
Alacritty does.

![image](https://github.com/wez/wezterm/assets/88465473/4fc52eca-e9ae-441e-8b19-98d4e05c2ee7)

## Steps to reproduce

1. install wezterm
2. open terminal
3. enter the command `man wezterm`

**Comment by wez** [comment]
Sure, here's a list of reasons:

* The manual is online at https://wezfurlong.org/wezterm/
* The manual doesn't work as a single plain text man page, without being written specifically as a man page, and I don't have time to build or maintain that. 
* There are currently more than 600 different markdown pages in the docs. I don't think anyone wants 600 different granular wezterm man pages
* As much as I love working in the terminal, it is a legacy output surface for help compared to a well-linked set of docs like we have online.
* You can use `wezterm --help` and drill down into the subcommands to get basic command line help if that's all you need.
* If you want to browse the docs offline, you can check out the git repo and run `./ci/build-docs.sh` and browse them locally

**Comment by Turmaxx** [comment]
Thanks for the response @wez . I love wezterm by the way. 

I was going to offer to add/maintain the man page for the terminal. But it seems that it is unnecessary, consider the immense well-documented documentation that it has online as you mentioned. kinda surprised when you said over 600 pages of granular documentation.

Cheers :+1:
