### ISSUE TITLE
`.deb` packages listed in docs don't work for `arm64` 

### ISSUE THREAD

**Issue by jinkjonks** [wez/wezterm#4134]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

n/a: remote TTy headless Linux

### WezTerm version

wezterm-20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

.deb packages listed in docs are not arm64 friendly
Applies to both Bookworm (12) and Bullseye (11)

### To Reproduce

`curl -LO https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly.Debian12.deb`
`sudo apt install ./wezterm-nightly.Debian12.deb`

### Configuration

no config

### Expected Behavior

Wezterm installs 

### Logs

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'wezterm:amd64' instead of './wezterm-nightly.Debian12.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wezterm:amd64 : Depends: libc6:amd64 (>= 2.35) but it is not installable
                 Depends: libfontconfig1:amd64 (>= 2.12.6) but it is not installable
                 Depends: libgcc-s1:amd64 (>= 4.2) but it is not installable
                 Depends: libssl3:amd64 (>= 3.0.0) but it is not installable
                 Depends: libwayland-client0:amd64 (>= 1.11.0) but it is not installable
                 Depends: libwayland-egl1:amd64 (>= 1.15.0) but it is not installable
                 Depends: libx11-6:amd64 but it is not installable
                 Depends: libx11-xcb1:amd64 (>= 2:1.8.4) but it is not installable
                 Depends: libxcb-image0:amd64 (>= 0.2.1) but it is not installable
                 Depends: libxcb-util1:amd64 (>= 0.4.0) but it is not installable
                 Depends: libxcb1:amd64 (>= 1.11.1) but it is not installable
                 Depends: libxkbcommon-x11-0:amd64 (>= 0.5.0) but it is not installable
                 Depends: libxkbcommon0:amd64 (>= 0.6.1) but it is not installable
                 Depends: zlib1g:amd64 (>= 1:1.1.4) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Anything else?

Building from source is fine: I'm happy to contribute to help enable arm64 builds  (whether it be just adding a note in the docs or contributing builds ) since (if I recall correctly) there aren't any arm64 Github-hosted runners.

**Comment by wez** [comment]
I suppose this is the spiritual successor to https://github.com/wez/wezterm/issues/1329

The only pre-built solution for arm64 linux is the flatpak, which has some nuance/limitations vs. running the native package.

GH still doesn't offer a workable solution for building for aarch64.
However, I think that [cirrus](https://cirrus-ci.org/guide/linux/), which we currently use only for freebsd, may be a viable option.

If you're interested in contributing some time looking into that I'd welcome that effort!

**Comment by wez** [comment]
Nightly downloads are now available for Debian 12 and Ubuntu 22 on arm64. Please give them a try!
