### ISSUE TITLE
display pane ids overlay

### ISSUE THREAD

**Issue by aleksandersumowski** [wez/wezterm#4147]
**Is your feature request related to a problem? Please describe.**
I'd like to easily identity pane ids for use in eg `wezterm cli move-pane-to-new-tab`

**Describe the solution you'd like**
An overlay that displays pane ids to quickly identify the pane ids

**Describe alternatives you've considered**
`wezterm cli list` lists all panes. But that still requires which pane has which id

**Additional context**
tmux has a similar feature called display-panes:
http://man.openbsd.org/OpenBSD-current/man1/tmux.1#displayp

**Comment by quantonganh** [comment]
I'm not sure what do you mean by "an overlay" but how about `echo $WEZTERM_PANE`?

**Comment by aleksandersumowski** [comment]
This is an example. The idea is to be able to see all ids in one go.
![image](https://github.com/wez/wezterm/assets/6926/8c86a021-049a-4896-88f3-b68959dabbbf)

**Comment by quantonganh** [comment]
I think you can write a simple shell script to do that:

```sh
#!/bin/sh

tty=$(tty)
tab_id=$(wezterm cli list --format json | jq --arg tty "$tty" -r '.[] | select(.tty_name == $tty) | .tab_id')
wezterm cli list --format json | jq --arg tab_id "$tab_id" -r '.[] | select(.tab_id == ($tab_id | tonumber)) | .pane_id' | while read pane_id; do echo 'echo $WEZTERM_PANE' | wezterm cli send-text --pane-id $pane_id --no-paste; done
```

**Comment by wez** [comment]
In `main`, you can now use [PaneSelect](https://wezfurlong.org/wezterm/config/lua/keyassignment/PaneSelect.html) in two new ways that are relevant to your request:

# Use PaneSelect directly to move panes to new tabs/windows

No need to feed the id into the CLI using this technique

```lua
local wezterm = require("wezterm")
return {
	keys = {
		{
			key = "I",
			mods = "CTRL",
			action = wezterm.action.PaneSelect({
				mode = "MoveToNewTab",
			}),
		},
		{
			key = "J",
			mods = "CTRL",
			action = wezterm.action.PaneSelect({
				mode = "MoveToNewWindow",
			}),
		},
	},
}
```

# Show pane ids alongside the labels

```lua
local wezterm = require("wezterm")
return {
	keys = {
		{
			key = "I",
			mods = "CTRL",
			action = wezterm.action.PaneSelect({
                             show_pane_ids = true,
			}),
		},
	},
}```

**Comment by wez** [comment]
Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by aleksandersumowski** [comment]
Sorry it took me a while to test it. The shortcut doesn't work to me - might be to my setup. But I could launch the functionality via right clicking '+'. The functionality is slightly different that what is in tmux and what I asked for, but my gut feeling is that this is a better way to implement the functionality. Thanks a lot!
