### ISSUE TITLE
wezterm Not Using System Installed "Noto Color Emoji" Fonts which are SVG/COLR and not bitmap fonts

### ISSUE THREAD

**Issue by rjkaes** [wez/wezterm#4148]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230806-225328-bf172634

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I noticed that new emojis characters are not displaying when using "Noto Color Emoji" as one of the fallback fonts.  Even after installing the [latest version](https://fonts.google.com/noto/specimen/Noto+Color+Emoji) wezterm continues to use the [bundled font](https://github.com/wez/wezterm/commit/3413bd97b9527fac0a9129cfed7d639592bf4f2c).

```
Primary font:
wezterm.font_with_fallback({
  -- /Users/rjk/Library/Fonts/JetBrainsMonoNerdFont-Regular.ttf, CoreText
  -- AKA: "JetBrainsMono NF"
  "JetBrainsMono Nerd Font",

  -- /System/Library/Fonts/Apple Color Emoji.ttc, CoreText
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [26, 34, 42, 52, 63, 68, 84, 126, 210]
  "Apple Color Emoji",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})
```

### Configuration

```lua
local wezterm = require 'wezterm'
config.font = wezterm.font_with_fallback {
    'JetBrainsMono Nerd Font',
    'Apple Color Emoji',
    'Noto Color Emoji',
}
```

### Expected Behavior

I would expect we'd use the system font as it's likely to be updated.

**Comment by wez** [comment]
Please run `wezterm ls-fonts --list-system | grep 'Noto Color Emoji'` and share the output

**Comment by rjkaes** [comment]
```
❯ wezterm ls-fonts --list-system | grep 'Noto Color Emoji'
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
  "Noto Color Emoji",
wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"}) -- <built-in>, BuiltIn pixel_sizes=[128]
wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"}) -- /Users/rjk/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
```

**Comment by wez** [comment]
Digging into this a bit, the issue is that we prefer the built-in font because it has bitmaps.

Adjusting the logic to not prefer bitmaps uncovers an issue where wezterm doesn't enable support for SVG rendering, so the glyphs end up blank.

So at the moment, the outcome is that you end up with *a* font that works, even though it isn't *the* font you wanted.

**Comment by wez** [comment]
I have an incomplete prototype of svg rendering in wezterm, but the noto font is a beast and highlights a performance problem in the rust svg crate:
* https://github.com/RazrFalcon/resvg/issues/634

**Comment by wez** [comment]
In `main`, the logic has been changed to not overly prioritize bitmap fonts which should allow you to use your installed font in this situation.

However, for that particular font, we will skip loading it because it uses svgs, and from what I've learned over the past 24 hours, SVG fonts are a nightmare to support.  While I do have some experimental code to render them, it is far from correct and it is disabled by default.

**Comment by rjkaes** [comment]
@wez Thank you for digging into this.  I didn't realize I'd open such a can of worms!

I can confirm that enabling:

```lua
config.experimental_svg_fonts = true
```

does use my locally installed font.  And yes, as you noted, watermelon does not render with Noto Color Emoji.

```
❯ wezterm ls-fonts --codepoints 1F349
LeftToRight
14:51:27.750  ERROR  wezterm_gui::glyphcache > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 132 0x84: bad argument. GlyphInfo { only_char: Some('🍉'), is_space: false, num_cells: 2, cluster: 0, font_idx: 1, glyph_pos: 3161, x_advance: 17.4375, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "JetBrainsMono Nerd Font", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: false, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }, FontAttributes { family: "Noto Color Emoji", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }], foreground: None }
 0 🍉    \u{1f349}    x_adv=0  cells=2  glyph=3161 wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /Users/rjk/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
```
