### ISSUE TITLE
Borderless window (without OS title bar)

### ISSUE THREAD

**Issue by gabyx** [wez/wezterm#4149]
Could it be possible to have borderless windows (macOS: no macOS window titlebar), not sure if possible on Windows)?
If shown where the windows is created I could maybe contribute.

Greate f***** terminal! Keep the good work.

**Comment by bew** [comment]
Did you try to use `window_decorations` ?
Ref: https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html

**Comment by gabyx** [comment]
Works really nice! (on macOS)
