### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by yoav-lavi** [wez/wezterm#4158]
Hey!

We talked on Mastodon regarding the privacy policy for WezTerm, thought it'd be a good idea to also have it on the website or in the repo.

**Is your feature request related to a problem? Please describe.**
As a new user it was hard for me to understand the privacy policy for WezTerm

**Describe the solution you'd like**
A new privacy policy in the website and / or in the repo

Thanks for your consideration!

**Comment by yoav-lavi** [comment]
This will also make it easier to publish WezTerm on platforms like https://privacyguides.org or similar

**Comment by wez** [comment]
I just added: https://github.com/wez/wezterm/blob/main/PRIVACY.md

**Comment by yoav-lavi** [comment]
That is awesome, thank you!
