### ISSUE TITLE
Characters in the command line after entering tmux

### ISSUE THREAD

**Issue by ziombo** [wez/wezterm#4167]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230712-072601-f4abf8fd and 20230817-092749-87a00992 (nightly)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm using wezterm on windows and use it with WSL2 Ubuntu. I upgraded wezterm to the latest version and since then whenever I enter tmux (with 'tmux' command) I get some characters insterted by default: 
![image](https://github.com/wez/wezterm/assets/15613606/548cf1a0-c232-45c1-8ded-aaccb8de471f)
61;6;7;22;23;24;28;32;42c

It's always the same characters and this doesn't happen when I run tmux within other terminals like Windows Terminal or standard command line.

### Configuration

No changes in configuration, only updated wezterm to the latest version (also checked if something changes with nightly, but it doesn't)

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by ferdinandyb** [comment]
[wezterm-recording-dtHqGH.cast.txt](https://github.com/wez/wezterm/files/12556742/wezterm-recording-dtHqGH.cast.txt)

I can repro a very similar issue, wezterm consistently prints it's current version number (20230712-072601-f4abf8fd) into the terminal with possibly some other non-printable characters. Reattaching to a tmux session with vim open is not fun :)

**Comment by wez** [comment]
@ferdinandyb see https://github.com/wez/wezterm/issues/2060

**Comment by ferdinandyb** [comment]
Hmm, I tried "reasonable" numbers, but even `set-option -g escape-time 10000` reproduces it.

**Comment by wez** [comment]
@ferdinandyb please open your own separate issue

**Comment by ferdinandyb** [comment]
Ok, I'll do that once I can install nightly (I just realized my local admin rights have been lost and this is the only windows machine I have access to).
