### ISSUE TITLE
Typo in documentation What is a Terminal

### ISSUE THREAD

**Issue by fmbarina** [wez/wezterm#4169]
At the end of the first paragraph of the following section, foresee is misspelled as forsee.

https://wezfurlong.org/wezterm/what-is-a-terminal.html?h=process#terminfo-and-termcap

Side note: CONTRIBUTING.md says corrections are welcome, but is this the usual way to inform contributors? Feels like you'd end up with many "fix typo" issues. I ask only because I'd rather avoid making a mess/causing unnecessary trouble.

**Comment by wez** [comment]
There's an "edit this page" icon to the right of the page title that will open an editor on github to make it easy to submit a PR:
