### ISSUE TITLE
IntegratedGPU not compatible with surface

### ISSUE THREAD

**Issue by tuanbass** [wez/wezterm#4170]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

I'm using `i3`

### WezTerm version

20230819-163109-fd9afa18

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Have `wezterm` use IntegratedGpu instead of DiscreteGpu 
and wezterm say the integrated gpu is not compatible with the surface. 

After a while, `wezterm` (and also my computer) become lagged, need to wait 100s ms for each keystroke.
(I'm not sure it relates to this issue, just guess `wezterm` use another gpu which has low performance.)

### To Reproduce

Just open wezterm , then open debug console

### Configuration

```
    config.webgpu_preferred_adapter = {
        backend = "Vulkan",
        device = 39876,
        device_type = "IntegratedGpu",
        driver = "Intel open-source Mesa driver",
        driver_info = "Mesa 22.2.5",
        name = "Intel(R) UHD Graphics (CML GT2)",
        vendor = 32902,
    }
```

### Expected Behavior

IntegratedGpu should also worked.

### Logs

```
Debug Overlay
wezterm version: 20230819-163109-fd9afa18 x86_64-unknown-linux-gnu
Window Environment: X11 i3
WebGPU: name=Mesa Intel(R) UHD Graphics (CML GT2), device_type=IntegratedGpu, backend=Gl, vendor=32902, device=0
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
14:26:18.597 WARN wezterm_gui::termwindow::webgpu > name=Intel(R) UHD Graphics (CML GT2), device_type=IntegratedGpu, backend=Vulkan, driver=Intel open-source Mesa driver, driver_info=Mesa 22.2.5, vendor=32902, device=39876 is not compatible with surface
14:26:18.607 WARN wezterm_gui::termwindow::webgpu > Your webgpu preferred adapter 'name=Intel(R) UHD Graphics (CML GT2), device_type=IntegratedGpu, backend=Vulkan, driver=Intel open-source Mesa driver, driver_info=Mesa 22.2.5, vendor=32902, device=39876' was either not found or is not compatible with your display. Available:
name=Intel(R) UHD Graphics (CML GT2), device_type=IntegratedGpu, backend=Vulkan, driver=Intel open-source Mesa driver, driver_info=Mesa 22.2.5, vendor=32902, device=39876, compatible=NO
name=NVIDIA GeForce RTX 3060 Laptop GPU, device_type=DiscreteGpu, backend=Vulkan, driver=NVIDIA, driver_info=525.125.06, vendor=4318, device=9504, compatible=yes
name=llvmpipe (LLVM 15.0.6, 256 bits), device_type=Cpu, backend=Vulkan, driver=llvmpipe, driver_info=Mesa 22.2.5 (LLVM 15.0.6), vendor=65541, device=0, compatible=yes
name=Mesa Intel(R) UHD Graphics (CML GT2), device_type=IntegratedGpu, backend=Gl, vendor=32902, device=0, compatible=yes
> wezterm.gui.enumerate_gpus()
[
    {
        backend: Vulkan,
        device: 39876,
        device_type: IntegratedGpu,
        driver: Intel open-source Mesa driver,
        driver_info: Mesa 22.2.5,
        name: Intel(R) UHD Graphics (CML GT2),
        vendor: 32902,
    },
    {
        backend: Vulkan,
        device: 9504,
        device_type: DiscreteGpu,
        driver: NVIDIA,
        driver_info: 525.125.06,
        name: NVIDIA GeForce RTX 3060 Laptop GPU,
        vendor: 4318,
    },
    {
        backend: Vulkan,
        device: 0,
        device_type: Cpu,
        driver: llvmpipe,
        driver_info: Mesa 22.2.5 (LLVM 15.0.6),
        name: llvmpipe (LLVM 15.0.6, 256 bits),
        vendor: 65541,
    },
    {
        backend: Gl,
        device: 0,
        device_type: IntegratedGpu,
        name: Mesa Intel(R) UHD Graphics (CML GT2),
        vendor: 32902,
    },
]
```

**Comment by wez** [comment]
Not sure what to say here: wezterm is telling you that there is an incompatibility and the solution is to configure it differently.

**Comment by tuanbass** [comment]
I'm sorry if I could not explain the problem clearly, as English is not my native. 
What I means is: 
I would like to use my IntegratedGPU: 
```
   {
        backend: Vulkan,
        device: 39876,
        device_type: IntegratedGpu,
        driver: Intel open-source Mesa driver,
        driver_info: Mesa 22.2.5,
        name: Intel(R) UHD Graphics (CML GT2),
        vendor: 32902,
    },
```
But `wezterm` does not allow me to do so, because of (some) incompatibilities. 
Is there anyway I can do to figure out what is the incompatibility, so I can fix and use my Vulka IntegratedGPU? Or OpenGL backend is the only way if I want to use my IntegratedGpu?

**Comment by wez** [comment]
wezterm uses either https://github.com/gfx-rs/wgpu or OpenGL EGL to talk to the graphics drivers on your system, depending on your configuration.

The message about incompatibility for the configuration you tried comes from https://github.com/gfx-rs/wgpu
That library is deciding that that configuration is not compatible.
wezterm doesn't have a way to see into why that is, so I don't know what's up.

Different GPUs and different drivers have varying quality and sometimes don't work in certain combinations.
It's possible that the issue is a driver issue, or an issue in wgpu, or one of the libraries that it uses.

Given that wezterm works when you use your discrete GPU it sounds like the underlying issue is either in wgpu or the drivers for your integrated gpu.

So the solution in the meantime is to not use the configuration that doesn't work.

Maybe your distro will update a driver, or maybe the next release of wgpu will fix an issue; there's not obviously something that I can fix in wezterm for this.

**Comment by tuanbass** [comment]
> wezterm uses either https://github.com/gfx-rs/wgpu or OpenGL EGL to talk to the graphics drivers on your system, depending on your configuration.
> 
> The message about incompatibility for the configuration you tried comes from https://github.com/gfx-rs/wgpu That library is deciding that that configuration is not compatible. wezterm doesn't have a way to see into why that is, so I don't know what's up.
> 
> Different GPUs and different drivers have varying quality and sometimes don't work in certain combinations. It's possible that the issue is a driver issue, or an issue in wgpu, or one of the libraries that it uses.
> 
> Given that wezterm works when you use your discrete GPU it sounds like the underlying issue is either in wgpu or the drivers for your integrated gpu.
> 
> So the solution in the meantime is to not use the configuration that doesn't work.
> 
> Maybe your distro will update a driver, or maybe the next release of wgpu will fix an issue; there's not obviously something that I can fix in wezterm for this.

Thanks for the response, I could understand the situation. 
And thanks for the excellent terminal emu. 

Just move into `wezterm` from `alacritty` for few days, and I really love how `weterm` organized, built-in multiplex, ssh, quick-select mode ... and  especially for Lua configuration  and Lua debug console (yes, killer feature for a neovim user).  

My only concern is about the performance, in my box (Intel i7-10750H, 32GB RAM, Nvidia GTX 3060, 2 external monitor), after using for a while with some sleep/wakeup become really lags, takes up to 3-5 seconds  to spawn a new term window, and other apps (Chrome) also lagged (CPU, memory, and GPU usage is not very high). Afterward, I have to either kill `wezterm-gui` or restart my display manager to get my box return normal. Using IntegratedGpu seems reduce lags probability considerably, so I tried to use it in best way.

Anyway, I'm new to `wezterm`, and didnt figure out the "lagging" pattern. Will try to identify it and come back later.
