### ISSUE TITLE
Refuses to launch on Asahi Linux Wayland (Hyprland)

### ISSUE THREAD

**Issue by ZaheenJ** [wez/wezterm#4171]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

20230819-163109-fd9afa18

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Does not launch at all, no window opens.

### To Reproduce

Attempt to launch wezterm on an M1 Mac running Hyprland on Fedora Asahi Remix.

### Configuration

no config

### Expected Behavior

It to open

### Logs

Output of `WEZTERM_LOG=debug wezterm`:
```
02:40:01.172  DEBUG  config > Reloaded configuration! generation=1
02:40:01.173  DEBUG  window::os::wayland::inputhandler > created ZwpTextInputV3 38 1
02:40:01.174  DEBUG  window::os::x_and_wayland         > Using wayland connection!
02:40:01.179  DEBUG  config                            > Reloaded configuration! generation=2
02:40:01.188  DEBUG  wezterm_gui::frontend             > workspace is default, fixup windows
02:40:01.192  DEBUG  wezterm_font::ftwrap              > set_char_size computing 12 dpi=96 (pixel height=16)
02:40:01.195  DEBUG  wezterm_font::ftwrap              > set_char_size computing 12 dpi=96 (pixel height=16)
02:40:01.195  DEBUG  window::os::wayland::output       > zwlr_head_info: {}
02:40:01.195  DEBUG  window::os::wayland::window       > Config: self.window_state=None, states:(empty) []
02:40:01.195  DEBUG  window::os::wayland::window       > dispatch_pending_event self.window_state=(empty) pending:(empty)
02:40:01.229  ERROR  wgpu::backend::direct             > Error in Adapter::request_device: Limit 'max_compute_workgroups_per_dimension' value 65535 is better than allowed 0
02:40:01.230  ERROR  wezterm_gui::frontend             > Failed to create window: Requesting a device failed
02:40:01.230  DEBUG  mux                               > remove_window_internal 0
02:40:01.230  DEBUG  mux                               > remove_tab_internal tab 0
02:40:01.230  DEBUG  mux                               > panes to remove: [0]
02:40:01.230  DEBUG  mux                               > removing pane 0
02:40:01.230  DEBUG  mux                               > killing pane 0
02:40:01.230  DEBUG  mux::localpane                    > killing process in pane 0, state is Running { child_waiter: Receiver { .. }, pid: Some(9305), signaller: ProcessSignaller { pid: Some(9305) }, killed: false }
02:40:01.230  DEBUG  wezterm_gui::frontend             > workspace is default, fixup windows
02:40:01.230  DEBUG  wezterm_gui::frontend             > workspace is default, fixup windows
warning: queue 0xaaaaff751080 destroyed while proxies still attached:
  xdg_wm_base@22 still attached
  wl_surface@21 still attached
  wl_data_device@18 still attached
  wl_pointer@16 still attached
  zwp_text_input_v3@15 still attached
  wl_keyboard@14 still attached
  zwp_primary_selection_device_v1@13 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@12 still attached
  wl_output@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
```

### Anything else?

When running with `front_end = "OpenGL"`, it runs normally.

**Comment by wez** [comment]
Sounds like an issue with https://github.com/gfx-rs/wgpu.
Please consider reproducing it and filing it there

**Comment by krshrimali** [comment]
Hi, thanks for creating this issue. I was looking at it as well when trying to build wezterm from source on WSL2 and launch wezterm, had the following error show up:

```bash
06:24:10.342  ERROR  wezterm_gui::frontend > Failed to create window: Limit 'max_compute_workgroups_per_dimension' value 65535 is better than allowed 0
```

Looking at the wgpu code, webgl2 has default set to `0` for `max_compute_workgroups_per_dimension`. So, probably, we would like to use WebGL2 here? I'm not an expert here, so could be wrong but @wez - is there a way to force use WebGL2? Please feel free to point out if it's not a wezterm thing and I could ask this on wgpu repo.

Thanks again!

**Comment by wez** [comment]
This issue is not a wezterm issue, but a wgpu issue. If you have suggestions that would help resolve it, please raise them with the wgpu folks!

In wezterm, you can workaround this issue by using opengl as it indicated in the OP above.

**Comment by wez** [comment]
Please try with the latest nightly build

**Comment by ZaheenJ** [comment]
I have not had this issue for a while, even before 2 weeks ago. Everything works perfectly! Sorry for not closing it sooner.
