### ISSUE TITLE
Wezterm does not resepct "automatically hide and show menu bar" setting

### ISSUE THREAD

**Issue by sohnryang** [wez/wezterm#4183]
### What Operating System(s) are you seeing this problem on?

macOS 13.5.1

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I set macOS's "Automatically hide and show menu bar" setting to "Never", but wezterm hides menu bar regardless of the setting.

### To Reproduce

0. Set "Automatically hide and show menu bar" to "Never".
1. Open wezterm and enter fullscreen.
2. Initially, the menu bar is shown as expected, but switching from wezterm to other full-screened app or workspace and back to wezterm triggers the bug.

### Configuration

No config.

### Expected Behavior

The menu bar should be shown in fullscreen mode, with the said "automatically hide and show menu bar" set to "never".

### Logs

Running wezterm in command line did not produce any logs.

**Comment by wez** [comment]
That setting sounds like it pertains to the macOS specific full screen mode.
By default, wezterm doesn't use that.
See: https://wezfurlong.org/wezterm/config/lua/config/native_macos_fullscreen_mode.html

**Comment by sohnryang** [comment]
The issue goes away when `native_macos_fullscreen_mode` set to `true`. Thanks!
