### ISSUE TITLE
Error processing Config::tab_bar_style: `active_tab_left` is not a valid TabBarStyle field.

### ISSUE THREAD

**Issue by robsonpeixoto** [wez/wezterm#4191]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I try to configure `tab_bar_style` using this(https://wezfurlong.org/wezterm/config/lua/config/tab_bar_style.html) code sample, I get the error:

```
09:20:29.105  ERROR  mux::connui > Configuration Error: error converting Lua table to Config (Config::from_dynamic: Error processing Config::tab_bar_style: `active_tab_left` is not a valid TabBarStyle field.  There are too many alternatives to list here; consult the documentation!)
stack traceback:
        [C]: in metamethod 'newindex'
        [string "wezterm.lua"]:32: in main chunk
```

### Configuration

local wezterm = require("wezterm")

local config = wezterm.config_builder()

-- The filled in variant of the < symbol
local SOLID_LEFT_ARROW = wezterm.nerdfonts.pl_right_hard_divider

-- The filled in variant of the > symbol
local SOLID_RIGHT_ARROW = wezterm.nerdfonts.pl_left_hard_divider

config.tab_bar_style = {
  active_tab_left = wezterm.format({
    { Background = { Color = "#0b0022" } },
    { Foreground = { Color = "#2b2042" } },
    { Text = SOLID_LEFT_ARROW },
  }),
  active_tab_right = wezterm.format({
    { Background = { Color = "#0b0022" } },
    { Foreground = { Color = "#2b2042" } },
    { Text = SOLID_RIGHT_ARROW },
  }),
  inactive_tab_left = wezterm.format({
    { Background = { Color = "#0b0022" } },
    { Foreground = { Color = "#1b1032" } },
    { Text = SOLID_LEFT_ARROW },
  }),
  inactive_tab_right = wezterm.format({
    { Background = { Color = "#0b0022" } },
    { Foreground = { Color = "#1b1032" } },
    { Text = SOLID_RIGHT_ARROW },
  }),
}

### Logs

❯ ./WezTerm-macos-20230822-233408-c91e124f/WezTerm.app/Contents/MacOS/wezterm --config-file=wezterm.lua
09:24:31.594  ERROR  mux::connui > Configuration Error: error converting Lua table to Config (Config::from_dynamic: Error processing Config::tab_bar_style: `active_tab_left` is not a valid TabBarStyle field.  There are too many alternatives to list here; consult the documentation!)
stack traceback:
        [C]: in metamethod 'newindex'
        [string "wezterm.lua"]:32: in main chunk

**Comment by GnuoyedC** [comment]
Also experiencing this on **macOS Ventura 13.5**

**WezTerm Version**
20230712-072601-f4abf8fd

**Configuration**
**_$HOME/.config/wezterm/modules/tabs.lua_**
```lua
local wezterm = require('wezterm')
local tabs_module = {}

function tabs_module.apply_to_config(config)
  -- The filled in variant of the < symbol

  local SOLID_LEFT_ARROW = wezterm.nerdfonts.pl_right_hard_divider

  -- The filled in variant of the > symbol
  local SOLID_RIGHT_ARROW = wezterm.nerdfonts.pl_left_hard_divider

  config.tab_bar_style = {
    active_tab_left = wezterm.format {
      { Background = { Color = '#0b0022' } },
      { Foreground = { Color = '#2b2042' } },
      { Text = SOLID_LEFT_ARROW },
    },
    active_tab_right = wezterm.format {
      { Background = { Color = '#0b0022' } },
      { Foreground = { Color = '#2b2042' } },
      { Text = SOLID_RIGHT_ARROW },
    },
    inactive_tab_left = wezterm.format {
      { Background = { Color = '#0b0022' } },
      { Foreground = { Color = '#1b1032' } },
      { Text = SOLID_LEFT_ARROW },
    },
    inactive_tab_right = wezterm.format {
      { Background = { Color = '#0b0022' } },
      { Foreground = { Color = '#1b1032' } },
      { Text = SOLID_RIGHT_ARROW },
    },
  }
end

return tabs_module
```

**_$HOME/.config/wezterm/wezterm.lua_**
```lua
local wezterm = require 'wezterm'
local config = {}
local tabs_module = require('modules.tabs')
config.font = wezterm.font 'Envy Code R'
config.font_size = 13.0
config.color_scheme = 'Tokyo Night Storm'
config.term = "wezterm"
tabs_module.apply_to_config(config)
return config
```

**Log**
12:50:17.062  ERROR  mux::connui > Configuration Error: `active_tab_left` is not a valid TabBarStyle field.  There are too many alternatives to list here; consult the documentation!
`active_tab_right` is not a valid TabBarStyle field.  There are too many alternatives to list here; consult the documentation!
`inactive_tab_left` is not a valid TabBarStyle field.  There are too many alternatives to list here; consult the documentation!
`inactive_tab_right` is not a valid TabBarStyle field.  There are too many alternatives to list here; consult the documentation!
12:53:21.573  INFO   wezterm_gui::termwindow > QuitApplication over here (window)

**Comment by wez** [comment]
The second paragraph of the linked docs (https://wezfurlong.org/wezterm/config/lua/config/tab_bar_style.html?h=removed) says:

> Since: Version 20210502-154244-3f7122cb: active_tab_left, active_tab_right, inactive_tab_left, inactive_tab_right, inactive_tab_hover_left, inactive_tab_hover_right have been removed and replaced by the more flexible [format-tab-title](https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html) event.

Those options were removed 2 years ago; you should use the newer `format-tab-title` event.
