### ISSUE TITLE
WezTerm + Komorebi + Neovim

### ISSUE THREAD

**Issue by jo-project** [wez/wezterm#4197]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

Komorebi

### WezTerm version

 WezTerm-20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Why when I use komorebi change window(?) (using alt + number), my neovim will automatically change to visual and select one line or sometimes an entire document, but it only happens on WezTerm and works normally using Windows Terminal? How to fix it? Thank you!

https://github.com/wez/wezterm/assets/122333339/e563583d-bb30-49c9-9f07-9d87c9d58129

https://github.com/wez/wezterm/assets/122333339/fd40d191-f984-47df-bf70-a16ab05dc51d

Note:
- First video is using Windows Terminal
- Second video is using WezTerm

### Configuration

no config

### Expected Behavior

I don't want it to automatically change neovim to visual and select a line or more like how it is when using Windows Terminal

**Comment by wez** [comment]
From your comments on Element, it sounds like you figured this out.
