### ISSUE TITLE
Background not showing

### ISSUE THREAD

**Issue by ZichengWangdrzz** [wez/wezterm#4201]
### What Operating System(s) are you seeing this problem on?

Windows, Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

I am running Ubuntu22.04, wsl version1 as the default domain by Wezterm.

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I followed instructions on the doc. But the window background does not show up.

### To Reproduce

my configuration file is in $HOME/.wezterm.lua. I followed the instruction on the page of backgound in official doc and the page did not show up.

### Configuration

```-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
	config = wezterm.config_builder()
end

--background
config.window_background_image = '/mnt/d/Wallpapers/windows-linux-wallpaper-sucks-penguin-images-2210.jpeg'

config.window_background_image_hsb = {
        -- Darken the b:q
  --ackground image by reducing it to 1/3rd
        brightness = 0.30,

        -- You can adjust the hue by scaling its value.
        -- a multiplier of 1.0 leaves the value unchanged.
        hue = 1.0,

        -- You can adjust the saturation also.
        saturation = 1.0,
}

config.default_domain = "WSL:Ubuntu-22.04"
config.font_size = wezterm.font_size

return config
````

### Expected Behavior

The backgound image should appear.

### Logs

20:56:37.838  ERROR  wezterm_gui::termwindow::background > Failed to load background: getting metadata for /mnt/d/Wallpapers/purple2.jpg: The system cannot find the path specified. (os error 3)
20:59:20.333  ERROR  wezterm_gui::termwindow::background > Failed to load background: getting metadata for /mnt/d/Wallpapers/windows-linux-wallpaper-sucks-penguin-images-2210.jpeg: The system cannot find the path specified. (os error 3)

**Comment by wez** [comment]
The error message seems clear: the path you specified cannot be found.
Check the spelling!
If you are running the gui process on windows, the background path must be a path accessible to windows.
If you are running the flatpak version of wezterm, note that flatpaks run in an isolated container and that can cause some issues with file access.

**Comment by ZichengWangdrzz** [comment]
I tried `D:\Wallpapers\purple2.jpeg`. This is a legit path for windows, but it complains about wrong escape sign. This may not be right.
