### ISSUE TITLE
Switchable quick_select_patterns

### ISSUE THREAD

**Issue by Minyus** [wez/wezterm#4219]
**Is your feature request related to a problem? Please describe.**

I often want to copy a whole line (Linefeed-separated) quickly in quick select mode while I often copy a word (whitespace-separated) configured by `config.quick_select_patterns`, which supports a single set of quick select patterns.

**Describe the solution you'd like**

Allow setting multiple quick_select_patterns in `config.quick_select_patterns` with the keys to switch, for example:

```
config.quick_select_patterns = {
  DEFAULT = {'[0-9a-f]{7,40}'},
  w = {'\\S{6,}'},
  l = {'.{6,100}'},
}
```

**Comment by wez** [comment]
You have several existing options to achieve this:

* Define a key assignment for https://wezfurlong.org/wezterm/config/lua/keyassignment/QuickSelectArgs.html to launch with the set of patterns that you want. You can define an assignment for each different pattern.
* If you don't want to remember different key assignments, you can use https://wezfurlong.org/wezterm/config/lua/window-events/augment-command-palette.html to add entries for those patterns to the command palette 
* If you prefer a modal approach, you can use https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html to change the `quick_select_patterns` configuration dynamically.

**Comment by Minyus** [comment]
Yes, key assignment for QuickSelectArgs worked like a charm! Thank your for the awesome tool!
