### ISSUE TITLE
Keyboard cursor fails to show on Wezterm startup

### ISSUE THREAD

**Issue by xzcxzcyy** [wez/wezterm#4224]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin version: 5.27.7

### WezTerm version

20230828-220414-99c96139

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

**Keyboard** cursor does not show up when wezterm is started by KDE Plasma, despite any input

![image](https://github.com/wez/wezterm/assets/29204347/f0a9a98d-fcf8-4043-9581-55438651f605)

![image](https://github.com/wez/wezterm/assets/29204347/d824ec0e-84f4-475d-85ee-229e462bd01a)

After executing any command (or Ctrl + C, or pressing ENTER on an empty line), it shows up again. Alternatively, double-click the terminal using a mouse can make the cursor appear.

![image](https://github.com/wez/wezterm/assets/29204347/d7a46d3b-5805-4b8e-ac1f-8bf62441067a)

I am using zsh, but Konsole does not reproduce this problem. This is confusing because when editting the command being input, I cannot see where the cursor is.

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  font = wezterm.font_with_fallback({
    "MesloLGS NF",
    "Source Han Sans SC"
  }),
  color_scheme = "Molokai",
  font_size = 11,
  initial_cols = 120,
  initial_rows = 34,
  leader = { key="a", mods="CTRL", timeout_milliseconds=1000 },
  keys = {
    { key = "9", mods = "LEADER", action = wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    { key = "0", mods = "LEADER", action = wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
    { key = "c", mods = "LEADER", action = wezterm.action{SpawnTab="CurrentPaneDomain"}},
    { key = "l", mods = "LEADER", action = wezterm.action{SpawnTab={DomainName="local"}}},
    -- { key = "d", mods = "LEADER", action = wezterm.action{SpawnTab={DomainName="devbox"}}},
    { key = "1", mods = "LEADER", action = wezterm.action{ActivateTab=0}},
    { key = "2", mods = "LEADER", action = wezterm.action{ActivateTab=1}},
    { key = "3", mods = "LEADER", action = wezterm.action{ActivateTab=2}},
    { key = "4", mods = "LEADER", action = wezterm.action{ActivateTab=3}},
    { key = "5", mods = "LEADER", action = wezterm.action{ActivateTab=4}},
    { key = "6", mods = "LEADER", action = wezterm.action{ActivateTab=5}},
    { key = "7", mods = "LEADER", action = wezterm.action{ActivateTab=6}},
    { key = "8", mods = "LEADER", action = wezterm.action{ActivateTab=7}},
    { key = "[", mods = "LEADER", action = wezterm.action{ActivateTabRelative=-1}},
    { key = "]", mods = "LEADER", action = wezterm.action{ActivateTabRelative=1}},
    { key = "LeftArrow", mods = "LEADER", action = wezterm.action{ActivatePaneDirection="Left"}},
    { key = "RightArrow", mods = "LEADER", action = wezterm.action{ActivatePaneDirection="Right"}},
    { key = "UpArrow", mods = "LEADER", action = wezterm.action{ActivatePaneDirection="Up"}},
    { key = "DownArrow", mods = "LEADER", action = wezterm.action{ActivatePaneDirection="Down"}},
  },
  default_prog = { '/bin/zsh', '-l' },
}
```

### Anything else?

Wezterm window does has the focus during the process, since I am actually inputting characters into the terminal, and the cursor still does not show up unless ENTER is pressed

**Comment by GnuoyedC** [comment]
Is the behaviour still the same if you load just a basic configuration file?

i.e. rename your current wezterm.lua to something like wezterm.lua.bk and then try the following bare-bones wezterm.lua configuration file:

```lua
local wezterm = require 'wezterm'
local config = wezterm.config_builder()
return config
```

**Comment by cbr9** [comment]
I have the following config, and it also happens. In my case it's only when opacity < 1.0.

```lua
local wezterm = require 'wezterm';
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)

local config = {}

config.keys = {
  { key = '=', mods = 'CTRL', action = wezterm.action.IncreaseFontSize },
  { key = '_', mods = 'CTRL', action = wezterm.action.DecreaseFontSize },
}

config.tiling_desktop_environments = {
  "X11 awesome"
}

config.color_scheme = 'Gruvbox dark, hard (base16)'
config.cursor_thickness = 2
config.enable_kitty_keyboard = true
config.font_size = 15
config.hide_tab_bar_if_only_one_tab = true
config.window_background_opacity = 0.9
config.font = wezterm.font('JetBrains Mono', { weight = 'Medium', italic = false })

return config
```

**Comment by xzcxzcyy** [comment]
> Is the behaviour still the same if you load just a basic configuration file?
> 
> i.e. rename your current wezterm.lua to something like wezterm.lua.bk and then try the following bare-bones wezterm.lua configuration file:
> 
> ```lua
> local wezterm = require 'wezterm'
> local config = wezterm.config_builder()
> return config
> ```

The problem does NOT reproduce on this default config file.

**Comment by xzcxzcyy** [comment]
> 
Quite the opposite in my case.

In my case, when setting window_background_opacity to below 1.0 (in your case 0.9), the issue does not reproduce. When setting to 1.0, the issue reproduces.

**Comment by xzcxzcyy** [comment]
> I have the following config, and it also happens. In my case it's only when opacity < 1.0.
> 
> ```lua
> local wezterm = require 'wezterm';
> wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
> 
> local config = {}
> 
> config.keys = {
>   { key = '=', mods = 'CTRL', action = wezterm.action.IncreaseFontSize },
>   { key = '_', mods = 'CTRL', action = wezterm.action.DecreaseFontSize },
> }
> 
> config.tiling_desktop_environments = {
>   "X11 awesome"
> }
> 
> config.color_scheme = 'Gruvbox dark, hard (base16)'
> config.cursor_thickness = 2
> config.enable_kitty_keyboard = true
> config.font_size = 15
> config.hide_tab_bar_if_only_one_tab = true
> config.window_background_opacity = 0.9
> config.font = wezterm.font('JetBrains Mono', { weight = 'Medium', italic = false })
> 
> return config
> ```

Quite the opposite in my case.

In my case, when setting window_background_opacity to below 1.0 (in your case 0.9), the issue does not reproduce. When setting to 1.0, the issue reproduces.

**Comment by cbr9** [comment]
It might be worth noting that I am using the latest stable release.

**Comment by wez** [comment]
Does this still occur on the latest release?
