### ISSUE TITLE
Expose pen/cell attributes of termwiz TerminalState

### ISSUE THREAD

**Issue by sullivan-sean** [wez/wezterm#4230]
**Is your feature request related to a problem? Please describe.**
I'm building an application that draws a surface over a terminal. I'd like to restore the original cursor attributes from the terminal after drawing the surface, but right now there is no way to access the current cursor attributes of the `TerminalState` object in termwiz. I can restore the cursor position by creating a `Change::CursorPosition` and the `cursor_pos` method of `TerminalState`, but cannot restore cell attributes.

**Describe the solution you'd like**
A method on `TerminalState` similar to `cursor_pos` that exposes the internal `pen` state.

**Describe alternatives you've considered**
It may be possible to parse the input to the terminal separately and maintain the current pen state outside of `TerminalState`, but this would require re-implementing a lot of the logic inside of `TerminalState` in the client application.

**Additional context**
N/A

Happy to make a PR adding a method on `TerminalState` for this!

**Comment by wez** [comment]
`TerminalState` is part of `wezterm-term` and probably isn't what you want if you're targeting drawing via `termwiz`.

I think what you really want is to expose the attributes from the `Surface` type:

https://github.com/wez/wezterm/blob/99c9613966a73d5388344fd0df68d5977b493c7c/termwiz/src/surface/mod.rs#L105-L109

assuming that what you need, then yes, I'll accept a PR for that!

**Comment by sullivan-sean** [comment]
I'm running my program in between a "parent" terminal emulator and a shell, intercepting the input/output between the two and mostly passing it through.

I'm using a `wezterm_term` `Terminal` to approximate the internal state of the parent terminal. I convert the `Terminal` to a `Surface`, but the `Surface` does not fully represent the terminal because it can't initialize the attributes the same way as the current pen state.

```rust
fn get_surface_for_term(term: &Terminal) -> Surface {
    let screen = term.screen();
    let mut parent = Surface::new(screen.physical_cols, screen.physical_rows);

    let num_rows = screen.scrollback_rows();
    let range = Range { start: num_rows - screen.physical_rows, end: num_rows };
    screen.with_phys_lines(range, |lines| {
        parent.add_changes(parent.diff_lines(lines.to_vec()));
    });

    let cursor_pos = term.cursor_pos();
    parent.add_changes(vec![
        Change::CursorPosition {
            x: surface::Position::Absolute(cursor_pos.x),
            y: surface::Position::Absolute(cursor_pos.y.abs().try_into().unwrap())
        },
        Change::CursorVisibility(cursor_pos.visibility),
        Change::CursorShape(cursor_pos.shape),
        // Ideally could do this:
        // Change::AllAttributes(term.pen().clone())
    ]);

    parent
}
```

If your open to it, exposing a function on `Terminal` or `TerminalState` that returns a full `Surface` representing the terminal would be even more convenient as there might be other changes besides cursor position, cursor shape, pen attributes, etc. I've missed that belong in this function as well.

**Comment by sullivan-sean** [comment]
@wez what are your thoughts on this?
