### ISSUE TITLE
Bad image output when using kitty protocol with width and height specified

### ISSUE THREAD

**Issue by CarterLi** [wez/wezterm#4233]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20230828-220414-99c96139

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

![image](https://github.com/wez/wezterm/assets/6134068/ca08a2d2-6df8-4a0d-b381-7013d0465cca)

### To Reproduce

```
echo -e "\e_Ga=T,f=100,t=f,c=20,r=10;$(realpath ./OpenSuse.png | tr -d '\n' | base64)\e\\"
```

Image used: ![x](https://media.discordapp.net/attachments/877406812566069299/1146179709412057088/OpenSuse.png?width=702&height=702)

### Configuration

no config

### Expected Behavior

Works like kitty

![image](https://github.com/wez/wezterm/assets/6134068/41e2b182-590b-4ffa-9e97-c0adc1777806)

### Anything else?

Specifying width and height does work fine with iterm image protocol

**Comment by CarterLi** [comment]
Another issue: if you display an image file multiple times, the next image hides the previous one.

Real:

![image](https://github.com/wez/wezterm/assets/6134068/28d6fc87-51e2-484c-b3e7-2b0cc2dbd18f)

Expected:

![image](https://github.com/wez/wezterm/assets/6134068/73c6ae32-6d8d-43c5-bff1-64596a73dab8)

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by CarterLi** [comment]
I can confirm the fix. Thanks.
