### ISSUE TITLE
cmd+shift+] doesn't work

### ISSUE THREAD

**Issue by joshmedeski** [wez/wezterm#4251]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm unable to setup the keybinding `cmd+shift+]` on macOS.

### To Reproduce

I've added the appropriate config.key table entry for configuring the mapping.

### Configuration

I've tried the following in the keys section.

```lua
		{
			mods = "CMD",
			key = "}",
			action = act.Multiple({
				act.SendKey({ mods = "CTRL", key = "b" }),
				act.SendKey({ key = "n" }),
			}),
		},
```

I've also tried this:

```lua
		{
			mods = "CMD|SHIFT",
			key = "]",
			action = act.Multiple({
				act.SendKey({ mods = "CTRL", key = "b" }),
				act.SendKey({ key = "n" }),
			}),
		},
```

### Expected Behavior

I expect the binding to be honored and run the defined action.

### Anything else?

- I have tried binding to just `cmd+]` and everything works as expected. It's when I try to bind to `}` (`shift+]`) that it does not work.
- In the debug overlay, I can see `CMD+]` `CTRL+SHIFT+]` but when I switch it for `CMD` or `HYPER` the program never registers the key event.

**Comment by kaddkaka** [comment]
Have you tried binding it to `CTRL+SHIFT+}`?

**Comment by joshmedeski** [comment]
Yes, I've tried every variation I could think of.

**Comment by rochacbruno** [comment]
I had the same issue today trying to map { + Ctrl

**Comment by joshmedeski** [comment]
I built from source and I had no luck getting the keybinding to work. I tried multiple variations of the configuration.

**Comment by joshmedeski** [comment]
`ALT|SHIFT` and `CTRL|SHIFT` worked, but `CMD|SHIFT` and `SUPER|SHIFT` do not.

```lua
{
			mods = "ALT|SHIFT",
			key = "}",
			action = act.Multiple({
				act.SendKey({ mods = "CTRL", key = "b" }),
				act.SendKey({ key = "n" }),
			}),
		}
```

**Comment by rochacbruno** [comment]
Run wezterm with `wezterm --config debug_key_events=true` and then see if wez is getting the key combo you are typing

**Comment by joshmedeski** [comment]
As mentioned previously:

> In the debug overlay, I can see CMD+] CTRL+SHIFT+] but when I switch it for CMD or HYPER the program never registers the key event.

Nothing gets shown on the logs when I trigger the keybinding I'm hoping to configure 😢

**Comment by wez** [comment]
Take a look at:

```console
$ wezterm show-keys --lua | grep TabRelative | grep CMD
```

I'm on linux at the moment, so it looks a little different for me:

```console
$ wezterm show-keys --lua | grep TabRelative | grep SUPER
    { key = '[', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(-1) },
    { key = ']', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(1) },
    { key = '{', mods = 'SUPER', action = act.ActivateTabRelative(-1) },
    { key = '{', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(-1) },
    { key = '}', mods = 'SUPER', action = act.ActivateTabRelative(1) },
    { key = '}', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(1) },
```

I think you need to hit all of those combos otherwise macos will prioritize the menubar shortcut, which happens before wezterm has a chance to process the key combination.

**Comment by joshmedeski** [comment]
That was it @wez!

I ended up overwriting the app shortcut to something else so I can use `CMD+}` for tmux.

<img width="768" alt="SCR-20230913-nhek" src="https://github.com/wez/wezterm/assets/2036594/c016e2b7-8710-4561-aee0-01b4b2cee810">
