### ISSUE TITLE
None of Gogh color schemes inverts cursor foreground color

### ISSUE THREAD

**Issue by madjxatw** [wez/wezterm#4257]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

20230828-220414-99c96139

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Cursor foreground not inverted for all Gogh color schemes, e.g. `Zenburn (Gogh)` as show below:

![zenburn-gogh-cursor-fg](https://github.com/wez/wezterm/assets/6035833/1dbf18d7-a1a1-411f-916f-6d2e2e58d926)

### Configuration

```lua
local wezterm = require('wezterm')

if wezterm.config_builder then
  config = wezterm.config_builder()
end

return {
  color_scheme = 'Zenburn (Gogh)'
  font = wezterm.font_with_fallback({
    'Iosevka Comfy',
    'Sarasa Term SC',
  }),
  dpi = 192,
  font_size = 10.0,
}
```

### Expected Behavior

This is what `tokyonight_storm` (non-Gogh scheme) displays:

![image](https://github.com/wez/wezterm/assets/6035833/f7fa8bc2-a161-4098-a504-e27056e61d9b)

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by madjxatw** [comment]
Thanks @wez, I believe this issue has been fixed!

**Comment by stessaris** [comment]
Until the fix will be in the upcoming release, the following configuration snippet should cover arbitrary schemata:

```lua
config.color_scheme = 'Everforest Light (Gogh)'

local scheme = wezterm.color.get_builtin_schemes()[config.color_scheme]
scheme.cursor_fg = scheme.background
config.color_schemes = {
  [config.color_scheme] = scheme
}
```
