### ISSUE TITLE
vim set mouse="" dont work

### ISSUE THREAD

**Issue by Kurt-Shiwz** [wez/wezterm#4262]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

13.5.2

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

On `.vimrc` file config `set mouse=""`, but dont work in wezTerm(it work on iterm2).

wezTerm:
![20230910-173435](https://github.com/wez/wezterm/assets/7554917/e76526d8-ca0f-4a45-83f0-3eefa5605eb2)

item2:
![20230910-174630](https://github.com/wez/wezterm/assets/7554917/f36e9372-275c-4860-85f7-b949037c6f42)

### Configuration

```
local config = {
    -- initial_rows = 40,
    -- initial_cols = 80,

    check_for_updates = false,
    switch_to_last_active_tab_when_closing_tab = false,
    enable_scroll_bar = true,
    alt_screen = false,

    -- Window
    native_macos_fullscreen_mode = false,
    adjust_window_size_when_changing_font_size = false,
    window_background_opacity = 0.95, -- 如果设置为1.0会明显卡顿
    window_padding = {
        left = 5,
        right = 5,
        top = 5,
        bottom = 5
    },
    window_background_image_hsb = {
        brightness = 0.8,
        hue = 1.0,
        saturation = 1.0
    },
    window_close_confirmation = "NeverPrompt",

    -- Font
    --font = wezterm.font_with_fallback({"JetBrains Mono"}),
    font = wezterm.font_with_fallback({ "Menlo" }),
    -- font_size = 22,

    -- Tab bar
    enable_tab_bar = true,
    hide_tab_bar_if_only_one_tab = false,
    show_tab_index_in_tab_bar = false,
    tab_max_width = 25,
    scrollback_lines = 99999,
    -- tab_bar_at_bottom = true,
    -- use_fancy_tab_bar = false,

    -- Keys
    disable_default_key_bindings = false,
    -- Allow using ^ with single key press.
    use_dead_keys = false,
    keys = keyBind(),

    -- 主题
    color_scheme = 'Gruvbox Dark',
    --    colors = {
    --        -- 被选中的内容的背景色
    --        selection_bg = '#D0AB52'
    --    },

    inactive_pane_hsb = {
        hue = 1.0,
        saturation = 1.0,
        brightness = 1.0
    },

    mouse_bindings = { -- Paste on right-click
        {
            event = {
                Down = {
                    streak = 1,
                    button = 'Right'
                }
            },
            mods = 'NONE',
            action = wezterm.action {
                PasteFrom = 'Clipboard'
            }
        }, -- Change the default click behavior so that it only selects
        -- text and doesn't open hyperlinks
        {
            event = {
                Up = {
                    streak = 1,
                    button = 'Left'
                }
            },
            mods = 'NONE',
            action = wezterm.action {
                CompleteSelection = 'PrimarySelection'
            }
        }, -- CTRL-Click open hyperlinks
        {
            event = {
                Up = {
                    streak = 1,
                    button = 'Left'
                }
            },
            mods = 'CMD',
            action = 'OpenLinkAtMouseCursor'
        } },

    default_prog = default_prog,
    set_environment_variables = set_environment_variables,
    launch_menu = launch_menu
}
```

### Logs

Debug Overlay
wezterm version: 20230712-072601-f4abf8fd aarch64-apple-darwin
Window Environment: macOS 13.5.2 (22G91)
OpenGL: Apple M1 Pro 4.1 Metal - 83.1
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>

**Comment by wez** [comment]
Please describe in more detail what you mean by "doesn't work".  It's impossible to intuit what problem you are facing from a lightning fast gif with tiny text and no explanation.

Check to see what you have set `ttymouse` to in your vimrc.  `sgr` is the best option.

**Comment by Kurt-Shiwz** [comment]
> Please describe in more detail what you mean by "doesn't work". It's impossible to intuit what problem you are facing from a lightning fast gif with tiny text and no explanation.
> 
> Check to see what you have set `ttymouse` to in your vimrc. `sgr` is the best option.

On macOS, when opening a file with vi in iTerm2 and doing a double-finger swipe on the touchpad, the content shown in the terminal goes back to the content before executing the vi command (like `ls`). 
while in Wezterm, the touchpad scroll will scroll the file contents like using the` UpArrow/DownArrow/LeftArrow/RightArrow `keys.

in .vimrc `set ttymouse= sgr`

**Comment by wez** [comment]
I, and many other users, use mouse mode in vim all the time on macos. There must be something else about your configuration that is affecting this.  It's up to you to dig in and try to reduce your vim configuration to find out what it is.

**Comment by Kurt-Shiwz** [comment]
> I, and many other users, use mouse mode in vim all the time on macos. There must be something else about your configuration that is affecting this. It's up to you to dig in and try to reduce your vim configuration to find out what it is.

i remove all config in .vimrc, the same problem.
i remove all config and keep `set mouse=` , the same problem

**Comment by Kurt-Shiwz** [comment]
> I, and many other users, use mouse mode in vim all the time on macos. There must be something else about your configuration that is affecting this. It's up to you to dig in and try to reduce your vim configuration to find out what it is.

My mistake. 
I tried "set mouse=" on the default Terminal app in macOS, but it didn't work. It seems to only work on iTerm2.
