### ISSUE TITLE
slow shell integration script

### ISSUE THREAD

**Issue by kaddkaka** [wez/wezterm#4263]
### Environment:
- Linux X11/Wayland, Ubuntu 22.04
- wezterm version: 20230806-225328-bf172634
  - Tried newest shell integration script

### Describe the bug
Sourcing `shell-integration/wezterm.sh` in bashrc gives long startup time. Also the prompt is slow to appear which is seen when holding down `enter` key in bash.

Just by commenting one line the prompt and startup is fast again (https://github.com/wez/wezterm/blob/main/assets/shell-integration/wezterm.sh#L415). Using the printf version is fast (`printf "\033]7;file://%s%s\033\\" "${HOSTNAME}" "${PWD}"`)

My bash startup  goes from 500 ms down to 100 ms as measured by `hyperfine 'bash -i'`

```console
$ hyperfine 'bash -i' --warmup=2  # untouched wezterm.sh
Benchmark 1: bash -i
  Time (mean ± σ):     561.5 ms ±   3.5 ms    [User: 154.0 ms, System: 67.0 ms]
  Range (min … max):   557.2 ms … 566.2 ms    10 runs
 
$ hyperfine 'bash -i' --warmup=2  # line 415 commented out.
Benchmark 1: bash -i
  Time (mean ± σ):     109.8 ms ±   0.6 ms    [User: 87.3 ms, System: 26.0 ms]
  Range (min … max):   108.5 ms … 111.5 ms    27 runs

$ hyperfine 'bash -i' --warmup=2  # whole file commented out.
Benchmark 1: bash -i
  Time (mean ± σ):     102.5 ms ±   0.9 ms    [User: 80.5 ms, System: 25.3 ms]
  Range (min … max):   101.4 ms … 104.9 ms    29 runs
```

This is the culprit code:
```bash
 __wezterm_osc7() {
  if hash wezterm 2>/dev/null ; then
    wezterm set-working-directory 2>/dev/null && return 0
    # If the command failed (perhaps the installed wezterm
    # is too old?) then fall back to the simple version below.
  fi
  printf "\033]7;file://%s%s\033\\" "${HOSTNAME}" "${PWD}"
}
```
It seems like `wezterm set-working-directory` might be slow, but hyperfine estimate that command to ~60 ms:

```bash
$ hyperfine 'wezterm set-working-directory 2>/dev/null && return 0'
Benchmark 1: wezterm set-working-directory 2>/dev/null && return 0
  Time (mean ± σ):      64.5 ms ±   0.4 ms    [User: 3.1 ms, System: 3.8 ms]
  Range (min … max):    63.8 ms …  65.8 ms    46 runs
```

My bash startup takes the lower branch in this if statement (NOT BLE) version.
```bash
if [[ -z "${WEZTERM_SHELL_SKIP_CWD}" ]] ; then
  if [[ -n "$BLE_VERSION" ]]; then
    blehook PRECMD+=__wezterm_osc7
  else
    precmd_functions+=(__wezterm_osc7)
  fi
fi
```

**Comment by kaddkaka** [comment]
Commenting out `precmd_functions+=(__wezterm_user_vars_precmd)` shaves of another 40 ms.

**Comment by wez** [comment]
See also: https://github.com/wez/wezterm/issues/3402 wherein the performance was previously in question and resolved.

Is `wezterm` an alias or something in your environment?  Is your `PATH` very large?
What if you use the full path to `wezterm` on that line instead of allowing bash to search the path?

Are there other bash-specific things that might be influencing this?
