### ISSUE TITLE
Drag and Drop not working in Flatpak

### ISSUE THREAD

**Issue by peterlobster** [wez/wezterm#4276]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter
Fedora 38

### WezTerm version

wezterm 20230712-072601-f4abf8fd (Flatpak)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Dragging and dropping files into WezTerm does not seem to work. The files are not copied or opened within WezTerm when dropped.

### To Reproduce

-  Launch WezTerm
-  Open a terminal window
-  Drag a file from Finder/File Explorer into the WezTerm window

### Configuration

_no config_

### Expected Behavior

The file path should be copied within the terminal when dropped into WezTerm.

### Logs

$ cat  $XDG_RUNTIME_DIR/wezterm
cat: /run/user/1000/wezterm: No such file or directory

**Comment by wez** [comment]
Drag and drop is not supported on X11 yet. See:
* https://github.com/wez/wezterm/issues/640
