### ISSUE TITLE
wezterm nightly crashes on Windows 11 when using WebGpu DX12

### ISSUE THREAD

**Issue by castiel652** [wez/wezterm#4279]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230911-075810-70931f58

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

wezterm crashes after a short period of time.
Did some research and found that there's a possible fix of this issue on upstream wgpu so I guess we just need to wait til the new relase.
https://github.com/gfx-rs/wgpu/pull/4106

### To Reproduce

OS: Windows 11 

### Configuration

config.webgpu_preferred_adapter = {
	backend= 'Dx12',
	device = 18064,
	device_type = 'IntegratedGpu',
	name = 'Intel(R) UHD Graphics 770',
	vendor = 32902,
}
config.front_end = 'WebGpu'

### Logs

```
15:53:08.118  ERROR  wgpu_hal::dx12 > ResizeBuffers failed: 0x887A0001
15:53:08.120  ERROR  wgpu_core::device::global > surface configuration failed: window is in use
15:53:08.136  ERROR  env_bootstrap             > panic at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.17.0\src\backend\direct.rs:771:18 - !?
   0: cairo_font_options_get_variations
   1: cairo_font_options_get_variations
   2: <unknown>
   3: git_filter_source_mode
   4: git_filter_source_mode
   5: git_filter_source_mode
   6: git_filter_source_mode
   7: cairo_raster_source_pattern_set_snapshot
   8: git_index_checksum
   9: git_index_checksum
  10: git_index_checksum
  11: git_index_checksum
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: cairo_font_options_get_variations
  16: cairo_font_options_get_variations
  17: cairo_font_options_get_variations
  18: cairo_font_options_get_variations
  19: DispatchMessageW
  20: DispatchMessageW
  21: TranslateAcceleratorW
  22: KiUserCallbackDispatcher
  23: NtUserPeekMessage
  24: PeekMessageW
  25: PeekMessageW
  26: cairo_font_options_get_variations
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: git_filter_source_mode
  32: <unknown>
  33: cairo_raster_source_pattern_set_snapshot
  34: BaseThreadInitThunk
  35: RtlUserThreadStart

thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Invalid surface
', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.17.0\src\backend\direct.rs:771:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
15:53:08.138  ERROR  window::os::windows::window > caught Any { .. }
```

**Comment by wez** [comment]
Yeah, we'll have to wait for a wgpu release and see if that helps

**Comment by castiel652** [comment]
New release is out
https://github.com/gfx-rs/wgpu/releases/tag/v0.17.1

**Comment by wez** [comment]
ded7f673f43f90bbde20b554cd3abb735eb8e27d should have that update included

**Comment by castiel652** [comment]
Thanks will try it when I am back to the office!

**Comment by castiel652** [comment]
No more crash.
Thanks!
