### ISSUE TITLE
App crashes when increasing/decreasing font size

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#428]
## Describe the bug

App crashes if you hold down `Ctrl` + `=`(IncreaseFontSize) or `Ctrl` + `-` (DecreaseFontSize) shortcut.

## Environment (please complete the following information):

 - OS: Manjaro (X11)
 - Version: wezterm 20201101-103216-403d002d-235-gbd614b5e

## To Reproduce

1. Open wezterm
2. Hold down `Ctrl` and `=` or `-`
3. App will crash after it exceeds certain limit.

## Configuration

Default config.

## Expected behavior

App should not crash.

## Additional context

Last logged msg when crashing if `Ctrl` + `=` is held down is

```
thread 'main' panicked at 'failed to recreate atlas: Texture Size exceeded, need Some(512)', wezterm-gui/src/gui/termwindow.rs:2139:14
```

and if it is `Ctrl` + `-`, then

```
thread 'main' panicked at 'failed to get font metrics!?: unable to load font idx 3!?', wezterm-gui/src/gui/utilsprites.rs:25:14
```

---

Another thing I have note is that, window size changes when increasing/decreasing font size. This should not happen, right?

**Comment by wez** [comment]
Thanks for reporting this!  I've improved the error handling around both these "extreme" sizing cases in master.

> Another thing I have note is that, window size changes when increasing/decreasing font size. This should not happen, right?

Changing the font scale intentionally resizes the window so that the number of rows and columns are preserved.

**Comment by MuhammedZakir** [comment]
> Thanks for reporting this! I've improved the error handling around both these "extreme" sizing cases in master.

You're welcome! :-)

> Changing the font scale intentionally resizes the window so that the number of rows and columns are preserved.

Two problems with this -

1. Increase font size until wezterm window fills up the entire screen, and then increase a little more. Now, if you decrease font size, font size will be much larger than expected.
    * If you increase font size a lot after wezterm is "full screen", then we will get a small screen with a huge font size.
    * `ResetFontSize` does not work. It does not revert to original value. Based on my observation, It looks like it is resetting font based on current value?

2. When using (t)wm, this creates problem with layout.
    * Can this be made optional?

**Comment by wez** [comment]
I'm going to close this issue as the crash has been resolved.

Please open a [feature request](https://github.com/wez/wezterm/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) that describes the behavior change that you'd like to see around changing the font size.
