### ISSUE TITLE
Disable Multi_key/Shift_L/etc. notification

### ISSUE THREAD

**Issue by alopatindev** [wez/wezterm#4297]
Is there any way to disable this? At least to me it's very annoying and not helpful.
![Screenshot-20230917-011335_wezterm-gui](https://github.com/wez/wezterm/assets/415408/40727ff7-dea8-460c-b179-2be8e789abbf)
Thanks.

**Comment by wez** [comment]
I've no idea what that is, it doesn't come from wezterm.
