### ISSUE TITLE
When changing font size, don't change window size or make it optional

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#431]
**Is your feature request related to a problem? Please describe.**

Currently, when changing font size, window size changes too. This creates additional problems if you use a (tiling) window manager.

**Describe the solution you'd like**

Is it possible to remove it, or make it optional?

**Describe alternatives you've considered**

NIL.

**Additional context**

I've also encountered another problem with this. If this is not the place to say this or if this belongs to a bug report, I can open another issue. Please do say so if that's the case.

To reproduce the issue -

Increase font size until wezterm window fills up the entire screen, and then increase a little more. Now, if you decrease font size, font size will be much larger than expected.
- If you increase font size a lot after wezterm is "full screen", then when decreasing, we will get a small screen with a huge font size.
- `ResetFontSize` does not work. It does not revert to original value. Based on my observation, It looks like it is resetting font based on current value?

**Comment by wez** [comment]
When the next nightly is built (in the next hour or so), you'll be able to use this in your `wezterm.lua`:

```lua
return {
   adjust_window_size_when_changing_font_size = false,
}
```

to make font size changes scale the number of rows/cols rather than the window dimensions.
