### ISSUE TITLE
Font fallback fails on Linux/X11 for "づ⚆"

### ISSUE THREAD

**Issue by kappa** [wez/wezterm#4310]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME Shell 43

### WezTerm version

20230911-075810-70931f58

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm cannot find fallback glyphs for these two characters when they printed one after the other:
づ⚆

```
$ wezterm ls-fonts --text 'づ⚆'
20:35:18.738  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{2686}\u{3065}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
LeftToRight
 0 づ    \u{3065}     x_adv=10 cells=2  glyph=.notdef,0    wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
 3 ⚆    \u{2686}     x_adv=10 cells=1  glyph=.notdef,0    wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
```

Separating them with a space enables the FontConfig fallback for both:
```
$ wezterm ls-fonts --text 'づ ⚆'
LeftToRight
 0 づ    \u{3065}     x_adv=16 cells=2  glyph=1496 wezterm.font("Noto Sans CJK TC", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-cjk/NotoSansCJK-Regular.ttc index=3 variation=0, FontConfig
 3      \u{20}       x_adv=10 cells=1  glyph=space,958  wezterm.font("JetBrains Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
LeftToRight
 0 ⚆    \u{2686}     x_adv=16.346153846153847 cells=1  glyph=uni2686,2398 wezterm.font("STIX Two Math", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/stix-fonts/STIXTwoMath-Regular.otf, FontConfig

```

### Configuration

no config

**Comment by wez** [comment]
What's happening here is that font-config can't find any fonts that have both of those codepoints together.  When separated by space, wezterm treats them as independent clusters and tries to resolve each codepoint separately, which then succeeds.

I'll adjust the logic to query each individual codepoint separately for font-config.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by kappa** [comment]
I have just tried it with the nightly AppImage and the problem is gone. Thank you!
