### ISSUE TITLE
Configurable wheel scrolling speed

### ISSUE THREAD

**Issue by wez** [wez/wezterm#432]
Regarding: Cursor Up/Down key presses generated by mouse wheel scrolling in Alt Screen:

> When compared to other terminals (e.g. Konsole, Yakuake), scrolling is slow. Is there anything I can do to increase scrolling speed?

_Originally posted by @MuhammedZakir in https://github.com/wez/wezterm/issues/429#issuecomment-762240587_

**Comment by MuhammedZakir** [comment]
Were you able to reproduce this? Is there anything I can do to help you on this?

**Comment by wez** [comment]
I haven't had time to look at this to see if we need to do something at eg: the X11 mouse layer for everyone, or just add a configurable artificial multiplier where the events get dispatched inside the terminalstate layer.

**Comment by MuhammedZakir** [comment]
> I haven't had time to look at this to see if we need to do something at eg: the X11 mouse layer for everyone, or just add a configurable artificial multiplier where the events get dispatched inside the terminalstate layer.

Later option is more flexible, but I am fine with simpler option. Regardless, I think **default** scrolling speed will need to be increase a bit. Current one feels slow. 

P.S. I have enabled mouse in Vim in `insert` and `visual` mode. In those modes, I am getting expected scrolling speed. But in `normal` mode in Vim, or in pagers like `less` or `most`, scrolling speed slow.
