### ISSUE TITLE
Escape code for cursor location in grapheme cluster space

### ISSUE THREAD

**Issue by erf** [wez/wezterm#4321]
**Is your feature request related to a problem? Please describe.**

When i want to set the cursor at a user perceived character position, given that some emojis or east asian characters take up two column spaces, i have to do this calculation on the application side. 

For example in the following text if i want to place the cursor at the fire emoji, i have to set the location at column **5**. What i rather would like to do is to say place the cursor at position **3** in grapheme cluster space.

“🐶😃🔥”

Which can be a difficult and error prone job for the application developer.

**Describe the solution you'd like**

A possible solution could be to add an extra character to the end of the escape code to implicate we want the cursor to be set in grapheme cluster space, e.g. 

“ESC [ y ; x ; g”

The terminal would handle iterating the user perceived character correctly based on the chosen Unicode standard.

This additional “g” could also be added for other cursor movement methods like moving the cursor to the left or right by a count 

“ESC [ n C ; g” // Move cursor right by n columns
“ESC [ n D ; g” // Move cursor left by n columns

I belive this is a new concept. Would it make sense to implement something like this?

**Describe alternatives you've considered**

Do it on the application side, but this makes things easier.

I saw there was a recent similar issue #4320 linking to a spec and i also saw this mentioned in the Ghostty discord channel here: https://discord.gg/ghostty

**Additional context**

**Comment by wez** [comment]
That discord link doesn't work for me. Can you link to something open and public?

There's more complexity here (there's always more complexity with text!) because calculating the perceived position is an `O(n)` cost where `n` is the `x` coordinate.  It's complicated a bit further by presentation options at the GUI layer (not the terminal emulator layer) such as [allow_square_glyphs_to_overflow_width](https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html).

I'm not sure about building out this functionality: I think this is likely more efficiently served by having a bit more intelligence in the application, and the result is probably less complex overall.

**Comment by erf** [comment]
I updated the Discord URL. I joined it after watching this Zig showtime talk on Ghostty: https://www.youtube.com/watch?v=l_qY2p0OH9A

Yes it's more costly, but these calculations has to be done on either the application level or the terminal level, and it could be made optional, so i was thinking it could hide some complexity from the application developer. That being said, i do also have to calculate display width regards to when to break a line, so that's a different but similar issue. Also the guy who wrote the spec mentioned in #4320 commented that my idea would break a syntax rule. So maybe i will just close this and perhaps you could look into that spec or join the Discord server if you feel like it. There might be some fruitful discussions there.

**Comment by bew** [comment]
Readind this, it sounds to me like whqt would really help is to export the text-width calculations to the terminal for everything, but that would be quite inefficient I think, and could break everything as soon as 2 different terminals try to display the same information..

**Comment by wez** [comment]
> it could hide some complexity from the application developer

speaking from long experience: attempts to hide complexity in one layer often result in more complexity in other layers.  The trick is in recognizing when that trade off is worthwhile in the long term.

In this case: the application always has better semantic understanding of what it put on the screen than the terminal, which makes it cheaper and easier for the application to reason about how it should manage incremental screen updates.

**Comment by erf** [comment]
i understand but i just feel like unicode / grapheme clusters such a vital part of the terminal / text rendering that it could have more support
