### ISSUE TITLE
Missing glyph on Ubuntu 22.04

### ISSUE THREAD

**Issue by daqwes** [wez/wezterm#4332]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

This is not a wezterm bug per se, however you may have a better idea than I do on how to proceed. When I have less than 10% battery on Ubuntu 22.04, there is a missing emoji in terminal (U+F582). It does not seem to come in any of the fonts that come prepackaged with wezterm (Jetbrains Mono/Nerd font symbols/Noto color emoji), any idea which font/font pack to install to get it?  

### To Reproduce

Open wezterm when less than 10% battery on Ubuntu 22.04.

### Configuration

no config

### Logs

14:34:12.118  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{f582}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.

**Comment by wez** [comment]
Try the nightly build. This sounds like the NF 2.0->3.0 breakage issue that's been fixed in `main` for a while.

**Comment by daqwes** [comment]
Unfortunately it does not, just tried with the latest version (`20231002-075348-a61cc8eb`) and it still produces the same error

**Comment by wez** [comment]
I think this is a local font installation issue.

based on what is installed my system, it looks like Font Awesome is probably the font you want:

```console
$ fc-list ':charset=F582'
/home/wez/.fonts/PragmataProR_0821.ttf: PragmataPro:style=Regular
/home/wez/.fonts/Font Awesome 5 Free-Solid-900.otf: Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid
/home/wez/.fonts/PragmataPro_Mono_R_0821.ttf: PragmataPro Mono:style=Regular
```

**Comment by daqwes** [comment]
You are right, this seems to have fixed it. Many thanks!
