### ISSUE TITLE
wezterm record launch in cwd

### ISSUE THREAD

**Issue by jalil-salame** [wez/wezterm#4333]
**Is your feature request related to a problem? Please describe.**
It's slightly unexpected that `wezterm record` will spawn the default shell in `~` instead of the current working directory.

**Describe the solution you'd like**
I'd like `wezterm record` to spawn the shell in the CWD

**Describe alternatives you've considered**
- Have an option to set the CWD of the spawned shell
- use `wezterm record -- sh -c "cd '$PWD' && exec '$SHELL'"`

**Additional context**
This is helpful as then the first line typed isn't `cd myproject`

**Comment by wez** [comment]
wezterm record spawns the default_prog with the default_cwd the same way that wezterm does.
I'm not going to change the default, but I did add the ability to `--cwd .` in 5e0fd1a06e10d23e2a61696d0b0ebdacffecb661

**Comment by jalil-salame** [comment]
> wezterm record spawns the default_prog with the default_cwd the same way that wezterm does.
> I'm not going to change the default, but I did add the ability to `--cwd .` in 5e0fd1a06e10d23e2a61696d0b0ebdacffecb661

Thanks!
