### ISSUE TITLE
Can't see top panel on MacOS

### ISSUE THREAD

**Issue by IvanProg00** [wez/wezterm#4335]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

On the mac (Ventura) I can't see top panel, when I'm in full screen mode. In other apps I can see, but in mac is black.
<img width="1720" alt="Screenshot 2023-09-24 at 11 03 19" src="https://github.com/wez/wezterm/assets/53527534/e9cb1058-50c6-485b-800b-f1ab0b6665e9">

### To Reproduce

1. Open app in full screen.
2. Click on any symbol from the top bar (For example, clock).

### Configuration

```lua
local wezterm = require("wezterm")
local config = {}

if wezterm.config_builder then
        config = wezterm.config_builder()
end

--- Colors ---
config.color_scheme = "Bamboo"

--- Fonts ---
config.font_size = 11.5

--- Other ---
config.window_close_confirmation = "NeverPrompt"

return config
```

### Expected Behavior

I want to see top panel all the time.

**Comment by Snoupix** [comment]
Yes, to clarify, it works when you put Wezterm in full screen (you can access the top menu bar by hovering on the top of the screen), you can switch fullscreen apps and it will still works.
But once you switch to the default screen with the dock and "desktop" and you go back to the fullscreen Wezterm app, you can't get the top bar anymore.

**Comment by IvanProg00** [comment]
Yes, but also when I click to any app in the top bar, the top bar becomes black.

**Comment by Snoupix** [comment]
Interesting, I don't have that issue.
Running MacOS Ventura 13.5 (22G74) with a MBPro 2019 intel

**Comment by IvanProg00** [comment]
I have this problem in MBPro m2.

**Comment by bezlant** [comment]
I have the same problem

**Comment by Snoupix** [comment]
Oh yes, my bad, you're right. This issue can be closed then @IvanProg00 

[native_macos_fullscreen_mode](https://wezfurlong.org/wezterm/config/lua/config/native_macos_fullscreen_mode.html?h=native)

**Comment by IvanProg00** [comment]
Thanks @bezlant & @Snoupix,
It  helped me to solve the problem!!! 👍
