### ISSUE TITLE
Wezterm uses 100% CPU. Possibly race condition

### ISSUE THREAD

**Issue by tuanbass** [wez/wezterm#4346]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

I3wm

### WezTerm version

20230819-163109-fd9afa18

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

## Description

Sometimes, wezterm eats 100% of my CPU when launching. It takes high CPU in about 1-2 minutes, then everything back to normal. 
![image](https://github.com/wez/wezterm/assets/9334023/10099328-3029-4d19-a9f2-442322272403)

In process list, there are 2 `wezterm-gui` instances occurs which should not. 
After a while, 1 process gone, and every thing back to normal.
So I guess there is condition race and/or deadlock somewhere.
![image](https://github.com/wez/wezterm/assets/9334023/8c057cb2-3aca-4eaf-a32d-d09f34557193)
 
The issue occurs randomly, about 3-4 days each, and more frequently when my laptop wakeup from a standby. 

## Why I didnt use the nightly build  for the report.
As the bug occurs randomly and less frequency, I dont think it's an effective way to check if the issue gone or not. 
Anyway, I will build the nightly release, and watch for it.

**Updated: error still occurred with `wezterm 20230922-143151-0f894d79`**. 
But the behavior changes: after 15min, 2 process `wezterm-gui` still coexisted, and one of them (the older one) still keep 100% CPU. I have to kill it manually

### To Reproduce

TBH, I didnt find an effective way to reproduce it. 
Is there anything I can collect when the issue occurs to help the debug? 

### Configuration

Not sure which section of the config relates to the issue. Uploaded the config as attachment.

**Comment by tuanbass** [comment]
[config.zip](https://github.com/wez/wezterm/files/12734279/config.zip)

**Comment by tuanbass** [comment]
![image](https://github.com/wez/wezterm/assets/9334023/b55930e5-4011-4076-ae75-b8e77967bb87)

trying to use `gdb` attach to `the wezterm-gui` process, break it , then print the stacktrace reveal that it was stucked at vkCreateDevice() of libvulkan.

**Comment by LinArcX** [comment]
I also saw high CPU usage on ram usage both on Linux and windows lots of times.

**Comment by wez** [comment]
@tuanbass sounds like a wgpu/vulkan issue. I'd suggest using `front_end="OpenGL"`.  That is the default in current versions of wezterm.

**Comment by tuanbass** [comment]
> @tuanbass sounds like a wgpu/vulkan issue. I'd suggest using `front_end="OpenGL"`. That is the default in current versions of wezterm.

Thanks for having a look into the problem. 

I'm not sure whether it's root cause or not. I have switched to OpenGL for a while (for dealing with #4652 ). The problem occurred less frequently, but still sometime.
