### ISSUE TITLE
Support touchable screen

### ISSUE THREAD

**Issue by Freed-Wu** [wez/wezterm#4347]
**Is your feature request related to a problem? Please describe.**
Support touchable screen:

1. one finger to scroll
2. two finger to scale up/down font size

I have tested many terminal emulator. Seem:

- alacritty support it <https://github.com/alacritty/alacritty/pull/6695>
- kitty doesn't support it <https://github.com/kovidgoyal/kitty/issues/5432>

Related post: https://www.reddit.com/r/linux/comments/4cyexp/any_terminal_emulators_support_touchscreens/

**Comment by bew** [comment]
I think this is a duplicate of #792

**Comment by Freed-Wu** [comment]
Aha, Sorry for duplication. :cry:
