### ISSUE TITLE
Option key combinations not working as expected on UK Mac keyboard keys with 3 chars

### ISSUE THREAD

**Issue by chrisbellboy** [wez/wezterm#4353]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hey there, I'm really enjoying my switch to Wezterm, it's been great!

However, did run into one hiccup on a UK Mac keyboard as two of the keys have 3 characters on them:

<img width="536" alt="image" src="https://github.com/wez/wezterm/assets/92119512/e89d5791-d30f-4f1f-918e-afc87d9faa07">

Key 2 can output `2`, `@` (shift + 2) and `€` (option + 2)
Key 3 can output `3`, `£` (shift + 3) and `#` (option + 3)

In Wezterm, the third characters (those accessed with option + x) don't output or seem to do anything. I've checked other terminals, and they work as expected there.

I've looked through the documentation but couldn't find any explanation or solution to this issue. Is this something that's ever been mentioned before, and is there a workaround available?

### To Reproduce

On a UK Mac Keyboard type Option + 2 or 3

### Configuration

No config

### Expected Behavior

Option + 2 should output `€`
Option + 3 should output `#`

**Comment by chrisbellboy** [comment]
Quick follow up, I was able to get around it by using the `SendString` action I just discovered 👌  

```
config.keys = {
	{
		key = "2",
		mods = "OPT",
		action = wezterm.action.SendString("€"),
	},
        {
		key = "3",
		mods = "OPT",
		action = wezterm.action.SendString("#"),
	},
}
```

I'm not sure if this is a workaround to an unwanted bug though, so leaving the issue open just in case.

P.s I did also try disabling any default assignments via the below, but it didn't work:

```
config.keys = {
	{
		key = "3",
		mods = "OPT",
		action = wezterm.action.DisableDefaultAssignment,
	},
}
```

**Comment by kkkrist** [comment]
Can you type # and € symbols with the right option (after disabling your workarounds?). 

I ran into similar issues. Turns out by default only the right option key performs composition effects (mimicking the Alt/AltGr setup on windows keyboards). This is rather unintuitive for Mac users. Fortunately there's the [`send_composed_key_when_left_alt_is_pressed`](https://wezfurlong.org/wezterm/config/keyboard-concepts.html?h=send_composed_key_when_left_alt_is_pressed#macos-left-and-right-option-key) config to turn the left option key into a composition key too.

**Comment by chrisbellboy** [comment]
@kkkrist Amazing info, thank you! You're absolutely right and `send_composed_key_when_left_alt_is_pressed` is the correct fix for this. 

Thanks again 🙇
