### ISSUE TITLE
Focus/Select buttons in prompts using keyboard

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#436]
**Is your feature request related to a problem? Please describe.**

Currently, we have to use mouse to select buttons in prompts.

**Describe the solution you'd like**

Usually, focus of buttons in prompts can be changed using `Tab` and `Shift+Tab` and selected using `Space` and/or `Enter`. Please support this in wezterm.

**Describe alternatives you've considered**

NIL.

**Additional context**

NIL.

---

Thanks for all quick responses and fixes. I really appreciate it! Keep up the good work! :-) I didn't want to bump a closed thread, so showing my gratitude here. :-)

**Comment by wez** [comment]
What prompts are you referring to?

**Comment by MuhammedZakir** [comment]
> What prompts are you referring to?

Prompt shown when quitting.

**Comment by wez** [comment]
For now, you can use `Escape` to cancel and `Enter` to confirm the close dialogs.

**Comment by MuhammedZakir** [comment]
> For now, you can use `Escape` to cancel and `Enter` to confirm the close dialogs.

`Escape` is working, but `Enter` does nothing.

**Comment by wez** [comment]
It's really Y and N for Yes and No, with Escape also acting as No.  I've made it a bit clearer:

![image](https://user-images.githubusercontent.com/117777/106545465-463e8b80-64be-11eb-8e84-00e593c8174d.png)
