### ISSUE TITLE
Using codicons as fall back font stretches out my fonts

### ISSUE THREAD

**Issue by esn89** [wez/wezterm#4363]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I have this set for fonts:

```lua
config.font = wezterm.font('PragmataPro Mono Liga', { weight = 'Regular' })
config.font = wezterm.font_with_fallback({
    -- { family = 'codicon', weight = 'Regular', stretch = 'Normal', style = 'Normal' },
    'PragmataProMonoLiga Nerd Font Mono',
})
config.font_size = 15.0
config.cell_width = 0.9
``` 

and things are great and look the way they should.  Minus a few cool glyphs.  
However, when I uncomment the part with `codicon`, like so:

```lua
config.font = wezterm.font('PragmataPro Mono Liga', { weight = 'Regular' })
config.font = wezterm.font_with_fallback({
    { family = 'codicon', weight = 'Regular', stretch = 'Normal', style = 'Normal' },
    'PragmataProMonoLiga Nerd Font Mono',
})
config.font_size = 15.0
config.cell_width = 0.9
```

all hell breaks loose, omnious music starts playing, demons gets summoned, children sacrificed and my terminal looks like this:

[image of broken term ](https://imgur.com/a/efVrj0q)

However, if I uncomment `codicons` again, it becomes usable again:

[image](https://imgur.com/a/Y2c8yfH)

I got the codicons.ttf here:
https://github.com/microsoft/vscode-codicons/tree/main/dist

### To Reproduce

```lua
config.font = wezterm.font('PragmataPro Mono Liga', { weight = 'Regular' })
config.font = wezterm.font_with_fallback({
    { family = 'codicon', weight = 'Regular', stretch = 'Normal', style = 'Normal' },
    'PragmataProMonoLiga Nerd Font Mono',
})
config.font_size = 15.0
config.cell_width = 0.9
```

I got the codicons here:
https://github.com/microsoft/vscode-codicons/tree/main/dist

### Configuration

```lua
config.font = wezterm.font('PragmataPro Mono Liga', { weight = 'Regular' })
config.font = wezterm.font_with_fallback({
    { family = 'codicon', weight = 'Regular', stretch = 'Normal', style = 'Normal' },
    'PragmataProMonoLiga Nerd Font Mono',
})
config.font_size = 15.0
config.cell_width = 0.9
```

### Expected Behavior

Font gets normal rendering and spacing.

**Comment by bew** [comment]
Try this:
```lua
config.font = wezterm.font_with_fallback({
    { family = 'PragmataPro Mono Liga', weight = 'Regular' },
    { family = 'codicon', weight = 'Regular', stretch = 'Normal', style = 'Normal' },
})
config.font_size = 15.0
config.cell_width = 0.9
```
Basically you first line was useless because you were changing `config.font` on the 2nd line, loosing what you did in the 1st line.

And with `font_with_fallback`, iirc the first font you give sets the cell size, so if you use a text font it oooks like text, but if your first font is an icon font it looks weird..
Use icons fonts as fallback only, and a real text font first!

About the nerd font fallback, you shouldn't need it because Wezterm already has all nerd font symbols built-in ;)

**Comment by esn89** [comment]
Thank you, that got rid of the craziness.

However, there are still some glyphs missing and/or mis-rendered:

```00:09:14.735  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{f718}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
```

I think in this case, the glyph (EB61) that I want actually exists in the Pragmata Pro, so it doesn't look into Codicons.

Is there anyway to force a particular to get handled by Codicons?

**Comment by bew** [comment]
Pragmata font is first in the fallback list, so it is used first if the glyph is present in this font. If you get this popup it means it's not 🤷‍♂️

You might want to checkout [`wezterm ls-fonts`](https://wezfurlong.org/wezterm/cli/ls-fonts.html) to help understand how the font is selected for some text or codepoints. 

(I'm on a phone right now, can't help much more than that)

**Comment by wez** [comment]
Try a current nightly build; 085e8da478d95566e5ad37c77cb19cb5daa5bdde uses an alternative strategy for finding fallback fonts that might resolve this.

See also:
* https://github.com/wez/wezterm/issues/4099

**Comment by esn89** [comment]
Great, will give it a shot.  Thank you.

**Comment by esn89** [comment]
Can't seem to get it to work.  I think it may be an issue with my fonts itself.
