### ISSUE TITLE
Copied text, copies spaces instead of tabs

### ISSUE THREAD

**Issue by ygaeon** [wez/wezterm#4367]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3wm, picom

### WezTerm version

wezterm 20230408-112425-69ae8472-gentoo

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When select-copy-paste text, spaces are copied instead of tabs.

### To Reproduce

1) `cat` a text file with tabs
2) Select the text
3) Middle-mouse click paste into neovim/gedit etc.
4) Spaces are pasted, not tabs

### Configuration

None that I think is applicable

### Expected Behavior

Tabs are preserved

**Comment by wez** [comment]
Tabs are a control sequence and don't actually exist in the terminal display model; they are expanded based on the tab stops that were set at the time the tab sequence was emitted to the terminal.

If you want to preserve tabs, don't do it via cat.  For example, use `:r filename` to directly read in the file in vim/nvim.

**Comment by ygaeon** [comment]
I'm sorry @wez but that was not a fully satisfactory response. I'm trying to migrate from `urxvt` where this is the actual behaviour, Tabs *are* preserved.

1) Open `urxvt` and `cat` a text file with tabs
2) Select the text
3) Middle-mouse click paste into neovim/gedit etc.
4) Voilà .. tabs are preserved.

Actually, you can see tabs being selected when selecting ..
