### ISSUE TITLE
scrollback buffer do not update cursor position

### ISSUE THREAD

**Issue by JE-Amouel** [wez/wezterm#4368]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20230806-225328-bf172634

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

the value return by wezterm.action.get_cursor_position(), is not updated when called wezterm.action.clearscrollback(),
for the position " x " and " y ", the field " y ",is decremented,

### To Reproduce

after opening wezterm-gui, which open for me my shell (zsh), I press ALT-SHIFT-k , as per my wezterm.lua will  print into the debug overlay, a table which contain the current cursor position that i can see by entering in debug overlay, then after running several command, which dump lot of data in the terminal buffer (i.e: ls Directory_with_lo_of_content/; cat My_config_file_with_lot_of_lines; etc... ) then i check again my cursor position by pressing ALT-SHIFT-k, and my cursor position is updated, the most intresting is on the table return by get_cursor_position is the field "y", which show the total amount of lines present in the scrollback buffer, up to now evrething is fine , but if a clear my scroll back buffer with my key binding ALT-SHIFT-c, all the the content off the buffer is deleted but if check again the cursor position the field "y" is not  became renitialized to zero but instead is continusly update from the value precedent the scrollback's clearing operation,
is there any reason to that? ,  

### Configuration

```lua
local config={}
local act=wezterm.action
config.keys={
  {
    key = 'C',
    mods = 'ALT',
    action = act.ClearScrollback 'ScrollbackAndViewport',
  },
  { key = 'K', 
   mods = 'ALT',  
   action = wezterm.action_callback( function(window, pane)wezterm.log_info (pane:get_cursor_position())  end) 
  },
}
```

### Expected Behavior

it would be good if after clearing the buffer the cursor position " y ", show the exact position of the cursor like there is no any scrollabel  content it should show is position relative to the viewport, and restart update is value from there.

### Logs

in the debug overlay: when i start my wezterm-gui and hit ALT-SHIFT-k, then check log info in debug-overlay:

```
15:31:16.370 INFO logging > lua: {
    shape: Default,
    visibility: Visible,
    x: 2,
    y: 6,                                                  <------------------------------
}
-----------------------------------------------------------------------------------------------------
```

after running several commands :

```
15:34:34.225 INFO logging > lua: {
    shape: Default,
    visibility: Visible,
    x: 2,
    y: 181,                                              <----------------------------
}
----------------------------------------------------------------------------------------------------
```

after clearing the scroll back buffer :

```
15:37:38.367 INFO logging > lua: {
    shape: Default,
    visibility: Visible,
    x: 2,
    y: 137,          <-----------------------------   if showing less then before because the clearing function do a CTRL-L, i think   
}
```

### Anything else?

that all, thank you.

**Comment by wez** [comment]
The `y` value is a `StableRowIndex`:

https://github.com/wez/wezterm/blob/5e0fd1a06e10d23e2a61696d0b0ebdacffecb661/term/src/lib.rs#L69-L81

https://wezfurlong.org/wezterm/config/lua/pane/get_dimensions.html returns a dimensions object that can be used to determine the position within the physical, non-scrollback, portion of the terminal display:

```lua
pane:get_cursor_position().y - pane:get_dimensions().physical_top 
```

**Comment by JE-Amouel** [comment]
Suppose I want to check the position of my cursor after clearing the backward buffer, and I would like to have the exact value depending on the fact that there is no more content in the backward buffer (a reset value).
Is there a function that could help me?, or should I determine a callback function that would keep a local variable up to date when I press my keyboard shortcuts to clear the scroll buffers?, I'm just looking a clean way to do it.

**Comment by JE-Amouel** [comment]
Suppose I want to check the position of my cursor after clearing the backward buffer, and I would like to have the exact value depending on the fact that there is no more content in the backward buffer (a reset value).
Is there a function that could help me?, or should I determine a callback function that would keep a local variable up to date when I press my keyboard shortcuts to clear the scroll buffers?, I'm just looking a clean way to do it.
