### ISSUE TITLE
Clear text from region

### ISSUE THREAD

**Issue by JE-Amouel** [wez/wezterm#4369]
we almost have function to get content from the scroll-back buffer,such as 
get_semantic_zone_at,
get_semantic_zones,
get_text_from_region,
get_text_from_semantic_zone.

is there any trick to use those function to clear content from a specific region?
a sort of functions like '' clear_semantic_zone_at," "clear_text_from_region," !?
thanks.

**Comment by wez** [comment]
If the region is in the main screen display, you can use https://wezfurlong.org/wezterm/config/lua/pane/inject_output.html to output something over the top.
Aside from clearing the entire scrollback, regions of scrollback are immutable.

**Comment by JE-Amouel** [comment]
that works fine, thanks.

**Comment by JE-Amouel** [comment]
that works fine, thanks.
