### ISSUE TITLE
Preview hyperlinks when hovering

### ISSUE THREAD

**Issue by fabian-thomas** [wez/wezterm#4370]
**Is your feature request related to a problem? Please describe.**
When clicking on hyperlinks you don't know where it might redirect you. While this is mainly a convenience issue, it can also be a security issue if you click on a specially crafted link.

**Describe the solution you'd like**
All major browsers and at least alacritty do preview the hyperlink somewhere in the bottom of the window.
This is what it looks like on alacritty:
![image](https://github.com/wez/wezterm/assets/4995833/9079b057-2976-43ce-886e-4bf84d0e82c4)

This could also be implemented for the quick menu type hyperlinks (`config.hyperlink_rules`) and could then preview the link that is crafted from the visible text so that you know there as well what might happen if you click.

Also, it would be nice to have this exposed via lua as well so that one can, e.g., show is tardy information even when the tab bar is hidden.

**Comment by wez** [comment]
Duplicate of https://github.com/wez/wezterm/issues/4
