### ISSUE TITLE
Complelty disable mux

### ISSUE THREAD

**Issue by exoess** [wez/wezterm#4373]
Wondering if it'd be possible to add a config option that completly disables wezterm multiplexing, not just hide the bar but disable the function entirely, idk if this is kinda a dumb request. 

P.S. Thanks for making wezterm, it's amazing

**Comment by Snoupix** [comment]
I don't know if you're talking about the tab bar for the wezterm multiplexing beacause you can disable it with `config.enable_tab_bar = false`

**Comment by wez** [comment]
No, it cannot be disabled. You can simply choose not to spawn new windows, tabs, panes, and disable the associated key assignments if you wish.

**Comment by exoess** [comment]
does wezterm treat a new instance of a terminal as a single tab, because i have some startup time issues with wezterm and that's the only big difference i can see between wezterm and other terminals

**Comment by wez** [comment]
it sounds like you're trying to solve a specific problem; please open an issue for that problem so that we can figure out the right solution
