### ISSUE TITLE
Add action HidePane and ShowPane

### ISSUE THREAD

**Issue by likern** [wez/wezterm#4380]
Action `HideCurrentPane` should hide (but do not close) current active pane, while `HidePane` should do the same,
but for provided `pane_id`.

Action `ShowPane` should restore it's original position and dimension (height, wight) if tab was not closed.
If tab was closed provide option `tab_id` to restore pane on another tab (probably current active tab).

**Comment by darg2012** [comment]
I was looking for the same functionality and found out that the [`TogglePaneZoomState`](https://wezfurlong.org/wezterm/config/lua/keyassignment/TogglePaneZoomState.html) option referenced [here](https://github.com/wez/wezterm/issues/578#issuecomment-808479909) serve my purposes.

**Comment by wez** [comment]
I have no plans for something like this; there's already a LOT of functionality around panes, tabs and windows.
Hiding them introduces additional UI and UX headaches that I just don't think are necessary, and are not worth it to me in terms of the time to build and the overhead of maintaining it.
