### ISSUE TITLE
Native macOS tabs

### ISSUE THREAD

**Issue by nikolay** [wez/wezterm#4381]
**Is your feature request related to a problem? Please describe.**
The current tabs on macOS look unnatural. Both Rio and iTerm offer native experience.

**Describe the solution you'd like**
Just regular native tabs would make Wez more pleasing to the macOS user base.

**Comment by wez** [comment]
wezterm is a cross-platform application and does not and will not support macOS native tabs. If you prefer that look, then you will need to find it in another terminal emulator

**Comment by nikolay** [comment]
@wez I love the attitude! Good luck!

**Comment by wez** [comment]
I understand that you don't like my factual statement of how things are and will be. You should know that your own attitude will limit your future more than you realize.

You will not find what you are looking for here, I'm at peace with it, and you will need to make your own peace with it.

**Comment by nikolay** [comment]
@wez Shortsightedness is not peace; it's a medical condition.
