### ISSUE TITLE
QEMU - macOS Ventura - failed to create NSOpenGLPixelFormat

### ISSUE THREAD

**Issue by RichardFevrier** [wez/wezterm#4387]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Running macOS `Ventura` thru `QEMU` gives this error:
```
 ERROR  wezterm_gui::frontend > Failed to create window: failed to create NSOpenGLPixelFormat
```

I've found [this](https://github.com/wez/wezterm/issues/1819) related to this problem so I have tried to add the latest version of MetalANGLE dylib alongside to the `wezterm-gui` without success.

Opened to try more stuff =)

### Configuration

no config

**Comment by wez** [comment]
You could perhaps try using the WebGpu front end.
See: https://wezfurlong.org/wezterm/config/lua/config/front_end.html

**Comment by RichardFevrier** [comment]
Doing so I have the following error:
 ```
 16:33:45.269  ERROR  wezterm_gui::frontend > Failed to create window: no compatible adapter found. Available:
 
 ```
 And using `Software` value resulting in the same error as  using `OpenGL` (also included `.dylib` related to `metalANGLE`)
 ### WezTerm version
20231003-224105-009b71f1

**Comment by wez** [comment]
There's not much we can do here: wezterm needs a working GPU and what is present in a VM is often not a full implementation.

I generally recommend running wezterm on the host system and then using eg: SSH or multiplexing to log in to the target environment.

**Comment by RichardFevrier** [comment]
Yeah you're probably right, I wish I had a second GPU to try with PCI passthrough but... 😕
Nevertheless using `Wezterm` on `Linux` and real `macOS`, just want to say dope job! 🤩
