### ISSUE TITLE
Scrolling doesn't work

### ISSUE THREAD

**Issue by evoshy** [wez/wezterm#4388]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When I try to scroll in my terminal to see my outputs further up, instead of scrolling, it goes through my entered commands (history) on the input line???

### Configuration

```lua
local wezterm = require "wezterm"

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.window_close_confirmation = "NeverPrompt"
config.default_prog = { "/opt/homebrew/bin/zellij" }
config.color_scheme = "GruvboxDark"
config.font = wezterm.font "FiraCode Nerd Font"
config.font_size = 14
config.enable_tab_bar = false

config.harfbuzz_features = { "calt=0" }

config.window_padding = {
  left = 0,
  right = 0,
  top = 0,
  bottom = 0,
}

return config
```

### Expected Behavior

To actually scroll

**Comment by wez** [comment]
Some possibilities:

* You may be in alternate screen mode where there is no scrollback and where the mouse wheel is remapped to the cursor up/down keys.  This can happen if a program crashes out without exiting alt screen mode.
* The application you are running has mouse reporting enabled, and remaps mouse events to navigating history.  If you hold down SHIFT (or whatever you may have configured for https://wezfurlong.org/wezterm/config/lua/config/bypass_mouse_reporting_modifiers.html) while scrolling, you should be able to scroll the scrollback in wezterm
