### ISSUE TITLE
More building options

### ISSUE THREAD

**Issue by JE-Amouel** [wez/wezterm#4389]
Good evening! I am always on the lookout for the slightest update of the terminal, I find it rich in possibilities and very elaborate, however the compilation options are very limited, would it be possible to have more control during compilation?
suppose that I am already used to terminal multiplexing with tmux but that I greatly appreciate the fact that the terminal offers solutions for displaying images even through tmux, it would still be nice to have a compilation option like " --desable-mux_server" (and leave pane and tab support to tmux), or suppose I want just want to have the lightest executable while keeping only hand-picked options.
 just have options to be also more customizable during compilation,
thank you.

**Comment by wez** [comment]
I won't be making the build and maintenance of the software more complicated for this; you can simply not use the features that you don't want to use.
