### ISSUE TITLE
Primary selection paste not working with non-utf8

### ISSUE THREAD

**Issue by tpoliaw** [wez/wezterm#4402]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3 version 4.22 (2023-01-02)

### WezTerm version

wezterm 20231002-222603-79ae543b (built from 11dec45f0 this morning)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am using an application that copies text to the primary clipboard (via a button rather than selecting text). Middle clicking elsewhere then (usually) pastes it as normal. When trying to do the same in wezterm I am getting `bracketed-paste-magic:zle:47: not enough arguments for -U`. If I try the same in a bash shell instead of zsh, I get no output (and nothing pasted).

Running the same the steps in gnome-terminal or kitty works as expected.

### To Reproduce

~~I'm not sure how to inspect what ends up in the primary selection clipboard but the wezterm recording (`wezterm record`, `shift`-`insert` to paste text, `ctrl-d` to exit) gives the following.~~
<details><summary>Recording</summary>
<pre>
{"version":2,"width":54,"height":61,"timestamp":1696590118,"env":{"WEZTERM_TARGET_TRIPLE":"x86_64-unknown-linux-gnu","LANG":"en_GB.UTF-8","TERM":"wezterm","WEZTERM_VERSION":"20231002-222603-79ae543b"},"theme":{"fg":"#ebdbb2","bg":"#282828","palette":"#282828:#cc241d:#98971a:#d79921:#458588:#b16286:#689d6a:#a89984:#928374:#fb4934:#b8bb26:#fabd2f:#83a598:#d3869b:#8ec07c:#ebdbb2"}}
[0.9305338,"o","\u001b[1m\u001b[7m%\u001b[27m\u001b[1m\u001b[0m                                                     \r \r"]
[1.0450671,"o","\r\u001b[0m\u001b[27m\u001b[24m\u001b[J\u001b[1;33m(\u001b[0m\u001b[1;33m⇅ \u001b[0m\u001b[1;33m6\u001b[0m\u001b[1;33m) \u001b[0m\u001b[34m~\u001b[0m \r\n\u001b[35m❯\u001b[0m \u001b[K"]
[1.0451295,"o","\u001b[?1h\u001b="]
[1.0451719,"o","\u001b[?2004h"]
[1.6814997,"o","\r\r\nbracketed-paste-magic:zle:47: not enough arguments for -U\r\n"]
[1.7902882,"o","\u001b[0m\u001b[27m\u001b[24m\u001b[J\u001b[1;33m(\u001b[0m\u001b[1;33m⇅ \u001b[0m\u001b[1;33m6\u001b[0m\u001b[1;33m) \u001b[0m\u001b[34m~\u001b[0m \r\n\u001b[35m❯\u001b[0m \u001b[K"]
[3.3885853,"o","\u001b[?2004l"]
[3.3885934,"o","\r\r\n"]
[3.4385164,"o","\u001b[H\u001b[2J"]
</pre>
</details> 

The text that should be pasted is something like `BL22I-EA-TEMPC-05:RAMPRATE:SET`

### Configuration

No config, running with `wezterm-gui --skip-config` gives the same bug

### Expected Behavior

The text from the primary clipboard should be pasted as normal

### Logs

```
Debug Overlay
wezterm version: 20231004-113117-11dec45f x86_64-unknown-linux-gnu
Window Environment: X11 i3
WebGPU: name=Quadro P2000, device_type=DiscreteGpu, backend=Vulkan, driver=NVIDIA, driver_info=535.104.05, vendor=4318, device=7216
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
12:01:39.213 WARN window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: get_appearance.read_setting: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.portal.Error.NotFound: Requested setting not found
```

### Anything else?

`alacritty` has the same problem. Are they sharing the same paste handling libraries?

**Comment by tpoliaw** [comment]
Trying to make sense of the recording, I don't think it actually contains the data from the clipboard in any form

**Comment by tpoliaw** [comment]
Digging into this a bit more using the [`arboard`](https://github.com/1Password/arboard) crate to inspect the clipboard, it looks like 'normal' text is copied as `UTF_STRING`, whereas the application I'm using is copying things as `STRING`. I'm not sure I follow the logic of how X11 atoms work but these are the names `arboard` has given them.

Enabling trace logging for `window::os::x11` gives the following two sections (first for a normal string) and second for the non-utf8 strings this issue relates to

## normal string
```
14:19:54.467  TRACE  window::os::x11::window     > SEL: window_id=Window { res_id: 79691779 } Window::get_clipboard PrimarySelection called
14:19:54.467  DEBUG  window::os::x11::window     > SEL: window_id=Window { res_id: 79691779 } Window::get_clipboard: PrimarySelection, prepare promise, time=176632847
14:19:54.467  TRACE  window::os::x11::window     > PropertyNotifyEvent XSEL_DATA
14:19:54.467  TRACE  window::os::x11::window     > SEL: window_id=Window { res_id: 79691779 } SELECTION_NOTIFY received SelectionNotifyEvent { response_type: 159, pad: 1, sequence: 461, time: 176632847, requestor: Window { res_id: 79691779 }, selection: Atom { res_id: 1 }, target: Atom { res_id: 314 }, property: Atom { res_id: 451 } } selection.selection=PRIMARY selection.target=UTF8_STRING
14:19:54.467  TRACE  window::os::x11::window     > SEL: window_id=Window { res_id: 79691779 } requesting selection from window Window { res_id: 79691779 }
14:19:54.468  TRACE  window::os::x11::window     > PropertyNotifyEvent XSEL_DATA
```
## weird string
```
14:20:12.297  TRACE  window::os::x11::window     > SEL: window_id=Window { res_id: 79691779 } Window::get_clipboard PrimarySelection called
14:20:12.297  DEBUG  window::os::x11::window     > SEL: window_id=Window { res_id: 79691779 } Window::get_clipboard: PrimarySelection, prepare promise, time=176650677
14:20:12.322  TRACE  window::os::x11::window     > SEL: window_id=Window { res_id: 79691779 } SELECTION_NOTIFY received SelectionNotifyEvent { response_type: 159, pad: 1, sequence: 512, time: 176650677, requestor: Window { res_id: 79691779 }, selection: Atom { res_id: 1 }, target: Atom { res_id: 314 }, property: Atom { res_id: 0 } } selection.selection=PRIMARY selection.target=UTF8_STRING
14:20:12.322  TRACE  window::os::x11::window     > SEL: window_id=Window { res_id: 79691779 } weird state, fulfil promise with empty string
```
I'm guessing the `weird state, fulfil promise with empty string` isn't a good sign

**Comment by tpoliaw** [comment]
I don't think I know enough about X11 to keep digging in to this. Let me know if there is anything I can do to help debug anything.

**Comment by tpoliaw** [comment]
Workaround in #4425 works for now

**Comment by ninjalj** [comment]
FWIW, the ICCCM specifies STRING as Latin-1 (excluding C0 and C1, but including TAB and newline), so it should be trivial to convert a STRING to utf-8, **assuming** legacy X11 clients respected the spec.

https://tronche.com/gui/x/icccm/sec-2.html#s-2.7.1

> STRING as a type or a target specifies the ISO Latin-1 character set plus the control characters TAB (octal 11) and NEWLINE (octal 12). The spacing interpretation of TAB is context dependent. Other ASCII control characters are explicitly not included in STRING at the present time.

**Comment by wez** [comment]
I've pushed a very targeted fix for this to `main`. I have no way to test it, so please give it a try and let me know if it isn't working!

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by wez** [comment]
Please try with 750b7ae84 and let me know!

**Comment by tpoliaw** [comment]
That looks like it's done it. :tada:

Thanks. Looking forward to removing my hacky workaround in the next release.
