### ISSUE TITLE
Wezterm's bash-preeexec copypasta messes with starship prompt

### ISSUE THREAD

**Issue by armagidon-exception** [wez/wezterm#4406]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

AwesomeWM 4.3 - window manager
Picom - compositor

### WezTerm version

20231004-113117-11dec45f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I set up [starship prompt](https://starship.rs/), but it did not work with wezterm, the prompt would not set. After a bit of digging I found out that it was something to do with the way wezterm spawns a login shell, after a bit more of digging I found that wezterm has a shell script in profile.d that contains old copypasta of bash-preexec that messes with the prompt.
So setting WEZTERM_SHELL_SKIP_ALL to 1 in /etc/environment fixes the prompt.

### To Reproduce

1. Install starship prompt
2. Install wezterm
3. Setup starship in bashrc
4. Open wezterm
5. See that prompt was not changed
6. Open another terminal
7. See that the prompt did change.

### Configuration

no config

### Expected Behavior

Prompt should be set upon opening a terminal

**Comment by whoizit** [comment]
setting WEZTERM_SHELL_SKIP_ALL to 1 in /etc/environment not helps to me. Same with ~/.bash_profile

CachyOS Linux (ArchLinux-based)

**Comment by whoizit** [comment]
removing /etc/profile.d/wezterm.sh also not helps to me

**Comment by Drllap** [comment]
@armagidon-exception I ran into the same problem. I thought this was a starship issue so I created this: https://github.com/starship/starship/issues/5686
With the recent changes to the wezterm.sh integration script this issue has been mostly fixed for me. See the starship issue.

**Comment by Drllap** [comment]
Interestingly, by replacing the embedded preexec script with the original one from [bash-preexec](https://github.com/rcaloras/bash-preexec/blob/master/bash-preexec.sh) the problem completely disappears, but obviously I don't the the shell integration anymore.

**Comment by wez** [comment]
FWIW, here's the relevant root-cause upstream issue in bash-preexec
* https://github.com/rcaloras/bash-preexec/issues/146

I worked around this (probably, assuming that your other software is all running the newer version), by updating the embedded version in wezterm in 0dedc7684df1db96583249b6ed14dcaefe994532

Those changes are available in both recent nightly builds and the new release of wezterm that shipped today.
