### ISSUE TITLE
CloseCurrentPane({ confirm = false }) not working in MUX window and causes the tab to freeze

### ISSUE THREAD

**Issue by aur3l14no** [wez/wezterm#4418]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

CloseCurrentPane({ confirm = false }) not working in MUX window and causes the tab to freeze.

### To Reproduce

Set this in config
```
	{
		key = "w",
		mods = "SUPER",
		action = act.CloseCurrentPane({ confirm = false }),
	},

```

`wezterm connect unix`

Press `SUPER+w` and notice that the tab freeze without any prompt. Subsequent actions are ignored in this tab as well.

### Configuration

```
	{
		key = "w",
		mods = "SUPER",
		action = act.CloseCurrentPane({ confirm = false }),
	},
```

### Expected Behavior

The pane closes and since it's the last pane in this tab, the tab also closes.

### Logs

16:40:11.979  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Char('w'), modifiers: SUPER, leds: (empty), phys_code: Some(W), raw_code: 13, repeat_count: 1, key_is_down: true, handled: Handled(false) }
16:40:11.981  INFO   wezterm_gui::termwindow::keyevent > Char('w') SUPER -> perform CloseCurrentPane { confirm: false }

**Comment by quantonganh** [comment]
> 20230712-072601-f4abf8fd

Looks like you are not using the latest [nightly build](https://wezfurlong.org/wezterm/install/macos.html):

```
WezTerm-macos-20231004-113117-11dec45f
```
