### ISSUE TITLE
`wezterm connect` times out

### ISSUE THREAD

**Issue by viveksjain** [wez/wezterm#4428]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm-mux-server 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Trying to connect from Wezterm app running on macOS to a Linux remote machine. `wezterm ssh <myhost.url.com>` works, but `wezterm connect <myhost>` fails with
```
ERROR  wezterm_gui > Timed out while parsing the response from the server. This may be due to network connectivity issues; terminating
```
Any pointers to debug further?

Let me know if I should try nightly.

### To Reproduce

The macOS app was downloaded from the website, on Linux I followed the instructions to build from source `cargo build --release --bin wezterm-mux-server`.

### Configuration

```
local config = {}
config.ssh_domains = {
  {
    -- This name identifies the domain
    name = 'myhost',
    -- The hostname or address to connect to. Will be used to match settings
    -- from your ssh config file
    remote_address = 'myhost.url.com',
  },
}

return config
```

### Logs

Logs in the newly created window on macOS
```
Connecting to <myhost.url.com> using SSH
Using libssh-rs to connect to vivek. jain@<myhost.url.com>
SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
SSH host <myhost.url.com>:22 is not yet trusted.
Fingerprint: <...>
Trust and continue connecting?
Enter [y/n]> y
Running: wezterm cli --prefer-mux proxy
Checking server version
```
and eventually it closes, with the original window saying
```
ERROR  wezterm_gui > Timed out while parsing the response from the server. This may be due to network connectivity issues; terminating
```

I don't see any logs on Linux under `/run/user/1000/wezterm/`, and on macOS there are no logs beyond the timeout.

### Anything else?

I don't know if it's because of some nonstandard SSH server configuration, but looking for ways to debug further and fix it

**Comment by tjex** [comment]
are you sure you don't need to build any of the other binaries? i.e. `wezterm` `assets/open-wezterm-here`. 

Also, does your remote machine really have the address `myhost.url.com`?
You are also missing the username for the remote machine. Which is included in the multiplexing example:

https://wezfurlong.org/wezterm/multiplexing.html#multiplexing

I wrote a blog post about setting this up too. Perhaps it gives a further hint, if the above didn't help.
https://tjex.net/hacks/installing-wezterm-on-a-raspberry-pi-or-linux-server/

**Comment by viveksjain** [comment]
I'm not sure what changed but this works in latest version, thanks for the help!
