### ISSUE TITLE
Check marks and other characters rendering as question marks

### ISSUE THREAD

**Issue by theAndrewCline** [wez/wezterm#444]
Hello,

Not sure if this a bug or an issue with my config, so mostly looking for help.

Certain characters render correctly in alacrity and gnome-terminal, but not in wezterm

- wezterm version
`wezterm 20201101-103216-403d002d`

- OS: PopOS

## Steps to Reproduce

- render checkmark with some cli

## Configuration

```lua
local wezterm = require 'wezterm'

return {
 color_scheme = "ayu",
 font = wezterm.font("Dank Mono"),
 font_size = 11.5,
 enable_tab_bar = false,
 window_padding = {
   left = 20,
   right = 20,
   top = 20,
   bottom = 20,
 },
}
```

## Expected behavior
Checkmarks should render correctly.

## Screenshots

Wezterm: - (font Dank Mono)
![Screenshot from 2021-01-29 09-51-05](https://user-images.githubusercontent.com/25731865/106297950-e7a4b380-6218-11eb-98b4-acd60273d693.png)

Alacritty - (font Dank Mono)
![Screenshot from 2021-01-29 09-51-33](https://user-images.githubusercontent.com/25731865/106297910-db205b00-6218-11eb-89d3-3db8b55e6976.png)

**Comment by wez** [comment]
Please try the nightly build!

**Comment by theAndrewCline** [comment]
It works thanks!
