### ISSUE TITLE
Not using emojis of font CozetteVector

### ISSUE THREAD

**Issue by erf** [wez/wezterm#4453]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

11dec45f0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm using the [CozetteVector](https://github.com/slavfox/Cozette/releases/tag/v.1.22.2) font and noticed the emojis part of the font is not used, i wonder if it's similar to this issue.

In wezterm:
<img width="103" alt="Screenshot 2023-10-17 at 16 34 39" src="https://github.com/wez/wezterm/assets/1562523/e5eaa942-f8c1-4ec6-8c80-c178b802d51e">

In ghostty:
<img width="103" alt="Screenshot 2023-10-17 at 16 34 21" src="https://github.com/wez/wezterm/assets/1562523/88aaa5ab-452f-4f13-aa05-2ed38b461d68">

Maybe related to #4148

### To Reproduce

1. Install the  [CozetteVector](https://github.com/slavfox/Cozette/releases/tag/v.1.22.2) font
2. Configure to use the font
3. `cat` test content

Test content:
```
aabbcc
❤️❤️❤️
😃😃😃
👩‍👩‍👦‍👦👩‍👩‍👦‍👦👩‍👩‍👦‍👦
🪼🪼🪼
❤️‍🔥❤️‍🔥❤️‍🔥
👽👽👽
🦀🦀🦀
🦌🦌🦌
🦊🦊🦊
😈😈😈
😊😊😊
😎😎😎
```

### Configuration

local wezterm = require 'wezterm'

local m = {}

m.unicode_version = 15
m.font_size = 21
m.font = wezterm.font('CozetteVector')

return m

### Expected Behavior

I expected the emojis as part of the font to be rendered.

**Comment by wez** [comment]
I think this is an emoji presentation issue.

```
; wezterm --config 'font_dirs = {"/home/wez/Downloads/cozette"}' --config 'font=wezterm.font{family="CozetteVector",assume_emoji_presentation=true}' ls-fonts --text 🔒
LeftToRight
 0 🔒    \u{1f512}    x_adv=12.296875 cells=2  glyph=u1F512,3046 wezterm.font("CozetteVector", {weight="Medium", stretch="Normal", style="Normal"})
                                      /home/wez/Downloads/cozette/CozetteVector.ttf, FontDirs
```

so try this in your config:

```
m.font = wezterm.font{family="CozetteVector", assume_emoji_presentation=true}
```

also, the font doesn't have all possible emoji, so you'll still see some from the Noto font:

```
; wezterm --config 'font_dirs = {"/home/wez/Downloads/cozette"}' --config 'font=wezterm.font{family="CozetteVector",assume_emoji_presentation=true}' ls-fonts --text 👻
LeftToRight
 0 👻    \u{1f47b}    x_adv=14.131847381591797 cells=2  glyph=615  wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/google-noto-emoji/NotoColorEmoji.ttf, FontConfig
```

**Comment by erf** [comment]
If i add the suggested config:
```
m.font = wezterm.font{family="CozetteVector", assume_emoji_presentation=true}
```
The font is no longer `CozetteVector`, but the default i assume, however now the emojis from CozetteVector shows up.

I did notice that the emoji `😎` only takes up a single column.

I also noticed (a bit off topic) that `🪼` is missing (only a question mark is there) part of Unicode 15

**Comment by wez** [comment]
Hmm, try this then:

```lua
wezterm.font_with_fallback{
    "CozetteVector",
    {family="CozetteVector",assume_emoji_presentation=true}
}
```

**Comment by erf** [comment]
Great that works ! Showing both correct font and emojis. The '😎' is also 2 cols now. 

Still missing the '🪼' emoji, but that is another isssue..
