### ISSUE TITLE
prompt does't render properly in wezterm.

### ISSUE THREAD

**Issue by akashdiphazra** [wez/wezterm#4454]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Wayland

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I am using ohmybash agnoster theme. The theme does render properly  on gnome-terminal but on wezterm it shows extra useless setting icon on the prompt. 

#### Gnome Terminal
![Screenshot from 2023-10-17 15-27-36](https://github.com/wez/wezterm/assets/61003681/b42a87d3-6ddb-4f29-9c7b-fa77697ef1a3)

#### Wezterm Terminal
![Screenshot from 2023-10-17 15-27-03](https://github.com/wez/wezterm/assets/61003681/46302d02-c46f-4c18-b35e-5215f27376eb)

### To Reproduce

Just use ohmybash and use agnoster theme.

### Configuration

```lua
local wezterm = require "wezterm"

-- This table will hold the configuration.
local config = {}

-- help provide clearer error messages
if wezterm.config_builder then
    config = wezterm.config_builder()
end

config.audible_bell = "SystemBeep"

-- Fonts Settings
config.colors = {
    foreground = "#d9fa02",
}
config.color_scheme = "Afterglow"
-- config.font = wezterm.font_with_fallback { "SauceCodePro NFM SemiBold Italic", "Symbols Nerd Font", "Noto Color Emoji", }
config.font = wezterm.font("SauceCodePro NFP SemiBold", { weight = 'Medium', italic = true })


config.font_size = 13
config.window_background_opacity = 0.95
config.window_decorations = "RESIZE"
config.scrollback_lines = 100000
config.enable_scroll_bar = true
config.enable_tab_bar = true
config.tab_bar_at_bottom = false
config.show_tabs_in_tab_bar = true

-- Initial Windows
config.initial_rows = 27
config.initial_cols = 93

return config
```

**Comment by fredricocalamari** [comment]
Font compatibility may not be identical between gnome-terminal and wezterm, so it's possible that it's not rendering the glyph for this particular font because of that. Have you tried seeing if a different font produces the same issue or is it isolated to this one particular font?

**Comment by akashdiphazra** [comment]
@fredricocalamari I tried with SpaceMono Nerd Fonts but, the issue remains the same.

**Comment by wez** [comment]
Probably more of a question for the ohmybash agnoster theme folks; it seems to me as though it is outputting something quite different
