### ISSUE TITLE
Mouse scroll speed insanly fast

### ISSUE THREAD

**Issue by exoess** [wez/wezterm#4455]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20231004-113117-11dec45f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I barely touch the mouse and it'll jump to the bottom or top of the buffer in an instant, I already adjusted the `alternate_buffer_wheel_scroll_speed` and it changed nothing

### Configuration

`config.alternate_buffer_wheel_scroll_speed = 1`

### Expected Behavior

normal scrolling like any other terminal

**Comment by bew** [comment]
Are you using a separate mouse or a touchpad?

**Comment by exoess** [comment]
no, I'm using my laptops touchpad

**Comment by bew** [comment]
This might be a duplicate of #3142 then

**Comment by exoess** [comment]
oh, okay

**Comment by exoess** [comment]
is there a fix yet?

**Comment by bew** [comment]
Doesn't seem like it, I don't use Wayland personally.

I'd recommend you to close this issue as a duplicate.

**Comment by exoess** [comment]
okay
