### ISSUE TITLE
Wezterm fails to start

### ISSUE THREAD

**Issue by jacobrreed** [wez/wezterm#4458]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

20231017-091526-fec90ae0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

  Fails to start on Hyprland/Wayland/Arch. I tried stable and nightly packages

### To Reproduce

simply try starting wezterm

### Configuration

```
   1   │ local wezterm = require("wezterm")
   2   │ local config = wezterm.config_builder()
   3   │ 
   4   │ config.color_scheme = "Dracula (Official)"
   5   │ config.font_size = 16
   6   │ config.font = wezterm.font({
   7   │     family = "JetBrains Mono",
   8   │     weight = "Medium",
   9   │ })
  10   │ 
  11   │ config.keys = {
  12   │     {
  13   │         key = "d",
  14   │         mods = "CTRL",
  15   │         action = wezterm.action.DisableDefaultAssi
       │ gnment,
  16   │         -- This key conflicts with spamming Ctrl +
       │  d in vim, and will cause terminal to close
  17   │     },
  18   │ }
  19   │ 
  20   │ config.window_decorations = "RESIZE"
  21   │ config.automatically_reload_config = true
  22   │ 
  23   │ return config
  ```

### Expected Behavior

I would expect Wezterm to start

### Logs

```
```
17:21:21.794  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 24, cols: 80 }) because window_state is MAXIMIZED
17:21:21.809  ERROR  wezterm_gui                     > running message loop: Error while flushing display: Broken pipe (os error 32); terminating
warning: queue 0x55935be992f0 destroyed while proxies still attached:
  wl_buffer@60 still attached
  wl_buffer@59 still attached
  wl_buffer@58 still attached
  wl_buffer@57 still attached
  wl_buffer@56 still attached
  wl_buffer@55 still attached
  wl_buffer@54 still attached
  wl_buffer@35 still attached
  wl_buffer@34 still attached
  zwp_primary_selection_offer_v1@4278190085 still attached
  wl_data_offer@4278190081 still attached
  wl_data_offer@4278190080 still attached
  wl_subsurface@49 still attached
  wl_surface@48 still attached
  wl_subsurface@47 still attached
  wl_surface@46 still attached
  wl_subsurface@45 still attached
  wl_surface@44 still attached
  wl_subsurface@43 still attached
  wl_surface@42 still attached
  wl_subsurface@41 still attached
  wl_surface@40 still attached
  xdg_wm_base@22 still attached
  wl_surface@21 still attached
  wl_data_device@18 still attached
  wl_pointer@16 still attached
  zwp_text_input_v3@15 still attached
  wl_keyboard@14 still attached
  zwp_primary_selection_device_v1@13 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@12 still attached
  wl_output@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
  ```
  
  

### Anything else?

_No response_

**Comment by Thiago-Assis-T** [comment]
I'm having almost the same problem on nixos and hyprland, just the error is different, and I have tryed the nightly build. 

`ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating`

I found a problem with the same error as mine, however it was months old and marked as solved. would it be pertinent to open a new issue or bring more details on this thread?

**Comment by bew** [comment]
> I'm having almost the same problem on nixos and hyprland, just the error is different, and I have tryed the nightly build.
> 
> `ERROR wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating`
> 
> I found a problem with the same error as mine, however it was months old and marked as solved. would it be pertinent to open a new issue or bring more details on this thread?

OP's issue is a `Broken pipe` error, your is very different, I'd suggest opening a new issue, following the issue template.

**Comment by Mange** [comment]
> I'm having almost the same problem on nixos and hyprland, just the error is different, and I have tryed the nightly build.

I've reported this as #4483.

**Comment by jacobrreed** [comment]
any updates on this? or startpoint for debugging?

**Comment by sjcobb2022** [comment]
> Just to report, this was happening on Hyprland and after I set my monitor stuff in hyprland.conf instead of using xrandr it works now. Not sure why

@jacobrreed  Which monitor stuff? As in like this: `monitor=DP-1,1920x1080@144,0x0,1`? or more specific?
