### ISSUE TITLE
Split terminal view in two-page layout

### ISSUE THREAD

**Issue by bphd** [wez/wezterm#4465]
**Is your feature request related to a problem? Please describe.**
I often face challenges when trying to find specific files in our document management system. The current search functionality is limited, and it's challenging to quickly locate files, especially when working on larger projects with many documents.

**Describe the solution you'd like**
I would like to request an enhanced search feature for our document management system. The enhanced search should include the following:

1. **Full-Text Search:** Implement full-text search capabilities to search within the content of documents, not just the titles or metadata.

2. **Advanced Filters:** Provide advanced search filters that allow users to narrow down search results based on file type, date, author, and other attributes.

3. **Search Suggestions:** Include real-time search suggestions as users type their queries to help them find files faster.

4. **Saved Searches:** Allow users to save and name their frequent search queries for easy access.

5. **Boolean Operators:** Enable the use of Boolean operators (AND, OR, NOT) in search queries for more precise results.

**Describe alternatives you've considered**
One alternative could be to rely on external search tools, but having these advanced search capabilities directly within our document management system would streamline the user experience and eliminate the need to switch between applications.

**Additional context**
The addition of these enhanced search features is crucial for improving productivity and making our document management system more efficient. Users often need to locate specific documents quickly, and these enhancements would significantly enhance the usability of the system.

**Comment by gegoune** [comment]
Did you accidentally post it in wrong repository?

**Comment by bphd** [comment]
> Did you accidentally post it in wrong repository?

Not at all, I really want to know if WezTerm have a function to split terminal view in two-page layout, or is willing to develop one

**Comment by gegoune** [comment]
You mean panes? Of course it does. Look up default key binds.

**Comment by bphd** [comment]
> You mean panes? Of course it does. Look up default key binds.

I don't mean having multiple terminals like tMux or smth, I want the same terminal, output, shell, idk, but on a two page view, to see more of it on the same screen

**Comment by gegoune** [comment]
Multi column output wrapping? Never came across that in any terminal emulator.

**Comment by bphd** [comment]
> Multi column output wrapping? Never came across that in any terminal emulator.

It's something to work on, I've heard that tail, multitail, pr, subl, emacs, vim, screen, tcvt and some other do that two column thing more or less. But it's a nice function to see more at once

**Comment by wez** [comment]
This issue sounds like it is talking about application specific internal document search functionality that is way out of scope for wezterm.
If your application wants to crate splits for itself, it can use the wezterm cli to control that.
There's nothing more that wezterm can reasonably do for this use case.
