### ISSUE TITLE
GDM doesn't start with wezerm installed if /bin/sh is a link to dash

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#447]
## Describe the bug

After an upgrade of my debian unstable system it seems that my `/bin/sh` link was changed to dash and after a restart, I couldn't login anymore. In the log appeared:

``` 
Jan 30 20:45:43 littlebottom2 /usr/libexec/gdm-x-session[1770]: /etc/gdm3/Xsession: 13: /etc/profile.d/wezterm.sh: [[: not found
Jan 30 20:45:43 littlebottom2 /usr/libexec/gdm-x-session[1770]: /etc/gdm3/Xsession: 17: /etc/profile.d/wezterm.sh: [[: not found
Jan 30 20:45:43 littlebottom2 /usr/libexec/gdm-x-session[1770]: /etc/gdm3/Xsession: 22: /etc/profile.d/wezterm.sh: [[: not found
Jan 30 20:45:43 littlebottom2 /usr/libexec/gdm-x-session[1770]: /etc/gdm3/Xsession: 88: /etc/profile.d/wezterm.sh: Syntax error: "(" unexpected (expecting "}")
```

After changing /bin/sh to bash, I could login again.

## Environment (please complete the following information):

 - OS: debian unstable, upgraded to whatever was available at this moment (ran a update in the console, just to see if this fixed it...)
 - Version: wezterm 20201101-103216-403d002d-290-gd10f7bbb

`checkbashisms /etc/profile.d/wezterm.sh` reports quite a view problems, but my guess the first two `[[`:

I tried the below version of `/etc/profile.d/wezterm.sh` with dash as /bin/sh and this also let me login:

```sh 
if [ "${WEZTERM_SHELL_SKIP_ALL}" = "1" ] ; then
  return 0
fi

if [ -z "${BASH_VERSION}" ] && [  -z "${ZSH_NAME}" ] ; then
  # Only for bash or zsh
  return 0
fi
```

**Comment by wez** [comment]
Ouch!  Thanks for reporting this!  I've pushed a slightly different fix from your proposal, but yes: the `[[` can't be used for that bit.

**Comment by jankatins** [comment]
Verified by installing the nightly
