### ISSUE TITLE
Expose a wezterm.file_exists (or similar)

### ISSUE THREAD

**Issue by aarondill** [wez/wezterm#4482]
**Is your feature request related to a problem? Please describe.**
There's currently no way to determine if a given file path exists without opening it or abuse of other methods.

**Describe the solution you'd like**
A simple `wezterm.file_exists` function that returns a boolean if the file path exists.

**Describe alternatives you've considered**
Open the file in lua to determine if it exists:
```lua
local f = io.open("filename.txt", "r")
if f then f:close() end
return not not f
```
Cons: This can only determine if a user has read permissions to a file AND requires the file be opened for reading.

Use the `wezterm.glob` function to monkey-patch a check (what I'm currently doing):
```lua
local wezterm = require("wezterm")
local function escape(file) ---@param file string
  return file:gsub("[{*\\?]", "\\%1")
end
---checks if a file exists on the filesystem
---Abuses wezterm.glob.
---@param name string? path to the file (relative to CWD)
---@return boolean exists
local function file_exists(name)
  if not name then return false end
  local res = wezterm.glob(escape(name)) ---@type string[]
  return res[1] == name
end
```
Cons: this requires escaping (which is difficult to do properly and could break in future releases of filenamegen), forces file globbing when a simple file check would be sufficient, returns array which needs to be cleaned up.

**Comment by aarondill** [comment]
This could be implemented simply with `Path::try_exists()` https://doc.rust-lang.org/std/path/struct.Path.html#method.try_exists

Other useful utils `wezterm.file_is_{dir,file,symlink}` could be implemented with corresponding `Path` meothods.

**Comment by Danielkonge** [comment]
I already have most of this implemented in this pull request: #4343

You can use `wezterm.to_path()` to make a string into a `Path` object, where you can then call methods like `:try_exists()` and many others. 

If you notice anything that you think should work differently, please let me know. Or if you want, feel free to test the code and let me know if you experience any problems. 

Also note that this will probably be moved to another pull request at some point. It covers quite a bit more than what was the original plan for this pull request.

**Comment by aarondill** [comment]
Awesome! I didn't see that PR (because nothing in it's description/title refers to paths, only read_dir), but that looks like exactly what I want!

I'm going to close this issue as you already have an implementation "planned", but feel free to reopen if you'd like.

**Comment by Danielkonge** [comment]
> Awesome! I didn't see that PR (because nothing in it's description/title refers to paths, only read_dir), but that looks like exactly what I want!

Yeah, as mentioned I will rename it and make another better named and structure pull request soon. 

> 
> Edit: whoops, thought you were wez himself. Just let me know if you think I should reopen this, but your PR seems to cover all my usecases. Hopefully it's merged soon 😄

I don't think it makes much difference. I have already talked about this idea with wez in the matrix chat, and he also seems to support the idea, so I think it is just a question of time before it will be ready. (It seems that wez is pretty busy currently though.)
