### ISSUE TITLE
Wezterm fails to start, emits Resource temporarily unavailable

### ISSUE THREAD

**Issue by Mange** [wez/wezterm#4483]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland nightly (built from commit 015664eb4cde5ab93cfacbfd8c2e831eeb876634). Current Nixos unstable version on 2023-10-23.

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm fails to start and a notification is sent with this error:

```
ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating
```

### To Reproduce

Try to run: `wezterm --skip-config`

### Configuration

no config

### Expected Behavior

Wezterm window starts like normal.

### Logs

No output is produced when starting from a shell.

### Anything else?

```
Linux 6.5.7 #1-NixOS SMP PREEMPT_DYNAMIC Tue Oct 10 20:03:06 UTC 2023 x86_64 GNU/Linux
```

Using AMD GPU for graphics. It's working with acceleration and similar.

This happened when bumping my lockfiles for nixos and installed the latest version of everything. Hyprland jumped from around the 0.29 release and into [0.31](https://github.com/hyprwm/Hyprland/releases/tag/v0.31.0), essentially.

RE: Wezterm I'm unsure how it moved version-wise, but perhaps I could find out if that would help. I'll jump back to my previous build for now in order to be productive today, so I can update which version I actually used before.

**Comment by Mange** [comment]
Restored to last version. Now it's working again.

```
wezterm 20230712-072601-f4abf8fd
Hyprland, built from branch  at commit 772c7d1d3cc7b3dd38450edf0ac1152419ef9eb1  ().
Linux 6.5.5 #1-NixOS SMP PREEMPT_DYNAMIC Sat Sep 23 09:14:39 UTC 2023 x86_64 GNU/Linux
```

**Comment by khaneliman** [comment]
Same issue here with Nixos-unstable, Hyprland latest, AMD graphics.

**Comment by 0a00** [comment]
![图片](https://github.com/wez/wezterm/assets/59482058/c6e79fe6-b440-4296-a6a2-4636e9190329)
I have the same problem and cannot start

**Comment by johnae** [comment]
Same here. Can confirm that this Hyprland commit has the issue:
https://github.com/hyprwm/Hyprland/commit/015664eb4cde5ab93cfacbfd8c2e831eeb876634

This (from the day before) doesn't:
https://github.com/hyprwm/Hyprland/commit/d0367d8560653eafdcce14778b2f44e6c6ddf707

There are only 5 commits that could introduce this (not necessarily saying it's Hyprland's fault) so should be fairly easy to find. I don't have time myself right now.

**Comment by Mange** [comment]
Here's the diff view of the above commits: https://github.com/hyprwm/Hyprland/compare/d0367d8560653eafdcce14778b2f44e6c6ddf707...015664eb4cde5ab93cfacbfd8c2e831eeb876634

@johnae Have you confirmed that the error appears/disappears just when you switch version of Hyprland?
I upgraded both Hyprland and Wezterm at the same time so it was harder to tell where to look for a cause.

**Comment by johnae** [comment]
@Mange Yeah. I'm also on NixOS and I track unstable fairly closely. Wezterm in unstable is still the latest release from sometime this summer and that's the version I use. Hyprland however is from the flake in the Hyprland-repo which is more or less tracking Hyprland git.

**Comment by psobiech** [comment]
Hi, 
it seems it was not a direct Hyprland change that broke wezterm, but updating wlroots from 3406c1b17a4a7e6d4e2a7d9c1176affa72bce1bc (which is the version used in https://github.com/hyprwm/Hyprland/commit/d0367d8560653eafdcce14778b2f44e6c6ddf707), it seems github is not showing submodule changes in diffs.

**Comment by psobiech** [comment]
I identified this commit https://github.com/hyprwm/Hyprland/commit/59f27e7f570170783ac01fb46a0ff90e14de53e6 as the culprit, commit before wezterm works, with this change, it no longer launches.

**Comment by psobiech** [comment]
This patch/revert fixes wezterm, but I assume would break https://github.com/hyprwm/Hyprland/issues/3635

```From fe1e3b102973764906cd2fb5c1de981015291fe3 Mon Sep 17 00:00:00 2001
From: Piotr Sobiech <piotr@sobie.ch>
Date: Wed, 25 Oct 2023 09:55:54 +0200
Subject: [PATCH] wezterm

---
 src/Window.cpp         | 3 +--
 src/events/Windows.cpp | 3 +--
 2 files changed, 2 insertions(+), 4 deletions(-)

diff --git a/src/Window.cpp b/src/Window.cpp
index 7825e7d3..34ecaa33 100644
--- a/src/Window.cpp
+++ b/src/Window.cpp
@@ -325,8 +325,7 @@ void CWindow::updateSurfaceOutputs() {
         m_pWLSurface.wlr(),
         [](wlr_surface* surf, int x, int y, void* data) {
             const auto PMONITOR = g_pCompositor->getMonitorFromID(((CWindow*)data)->m_iMonitorID);
-            g_pCompositor->setPreferredScaleForSurface(surf, PMONITOR ? PMONITOR->scale : 1.f);
-            g_pCompositor->setPreferredTransformForSurface(surf, PMONITOR->transform);
+            g_pProtocolManager->m_pFractionalScaleProtocolManager->setPreferredScaleForSurface(surf, PMONITOR ? PMONITOR->scale : 1.f);
         },
         this);
 }
diff --git a/src/events/Windows.cpp b/src/events/Windows.cpp
index 89b327b0..df8475d2 100644
--- a/src/events/Windows.cpp
+++ b/src/events/Windows.cpp
@@ -646,8 +646,7 @@ void Events::listener_mapWindow(void* owner, void* data) {
     if (PWORKSPACE->m_bHasFullscreenWindow && !PWINDOW->m_bIsFullscreen && !PWINDOW->m_bIsFloating)
         PWINDOW->m_fAlpha.setValueAndWarp(0.f);
 
-    g_pCompositor->setPreferredScaleForSurface(PWINDOW->m_pWLSurface.wlr(), PMONITOR->scale);
-    g_pCompositor->setPreferredTransformForSurface(PWINDOW->m_pWLSurface.wlr(), PMONITOR->transform);
+    g_pProtocolManager->m_pFractionalScaleProtocolManager->setPreferredScaleForSurface(PWINDOW->m_pWLSurface.wlr(), PMONITOR->scale);
 }
 
 void Events::listener_unmapWindow(void* owner, void* data) {
-- 
2.42.0

```

When `wlr_surface_set_preferred_buffer_scale(pSurface, scale);` or `wlr_surface_set_preferred_buffer_transform(pSurface, transform);` is invoked from these two places, wezterm crashes. Sadly I dont know more about wlroots about this to proceed.

**Comment by sjcobb2022** [comment]
Can confirm that this is an issue. I am on NixOS, using wezterm stable and hyprland latest.

https://github.com/hyprwm/Hyprland/commit/d0367d8560653eafdcce14778b2f44e6c6ddf707

Can also confirm that hyprland at this commit is the first commit where this bug:
https://github.com/hyprwm/Hyprland/commit/59f27e7f570170783ac01fb46a0ff90e14de53e6

Additionally, I am on an Nvidia GPU which could also be causing this issue. However I doubt this is the case as it seems more like a scaling wlroots issue.

My theory is that it is something to do with [this hunk](https://github.com/wez/wezterm/blob/fec90ae04bf448d4b1475ba1d0ba1392846a70d6/window/src/os/wayland/window.rs#L718C1-L734), however I am not very familar with the codebase. I belioeve that the error originates from somewhere in  [this handler](https://github.com/wez/wezterm/blob/fec90ae04bf448d4b1475ba1d0ba1392846a70d6/window/src/os/wayland/window.rs#L625) though.

**Comment by ke1satsu** [comment]
I am also on NixOS unstable, using wezterm and Hyprland from unstable. AMD GPU here.

**Comment by dantefromhell** [comment]
+1 affected NixOS user, on
-  hyprland https://github.com/hyprwm/Hyprland/commit/ab5497a0c9e9269b1036a0bede42cbd0bbfd94b9
-  wezterm 20230712-072601-f4abf8fd 
- Intel Tiger Lake GPU

**Comment by wez** [comment]
Does this happen with the latest nightly wezterm?

**Comment by ke1satsu** [comment]
I compiled from the current main and it appears that the crash does not occur anymore. With the caveat that I've no clue what I'm doing, I threw together a quick flake and patched for the libvulkan dependency, mirroring what nixpkgs appears to do with it.

There is however a new error when exiting wezterm:
warning: queue 0x55555a9bc490 destroyed while proxies still attached:
  wl_callback@51 still attached
  zwp_primary_selection_offer_v1@4278190089 still attached
  wl_data_offer@4278190082 still attached
  wl_data_offer@4278190083 still attached
  wl_shm_pool@53 still attached
  wl_shm_pool@50 still attached
  wl_data_offer@4278190080 still attached
  xdg_wm_base@23 still attached
  wl_surface@22 still attached
  wl_data_device@19 still attached
  wl_pointer@17 still attached
  zwp_text_input_v3@16 still attached
  wl_keyboard@15 still attached
  zwp_primary_selection_device_v1@14 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@13 still attached
  wl_output@12 still attached
  wl_output@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

And while using wezterm the terminal I spawned it from spams this error:

17:31:13.742  ERROR  window::os::wayland::pointer > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found

But wezterm does start just fine and it doesn't crash so it's a step in the right direction!

**Comment by wez** [comment]
Then this sounds as though it is resolved in the nightly. Please open a separate issue for the "still attached" warnings.

The cursor issue sounds like: https://github.com/wez/wezterm/issues/3751

**Comment by SuperSandro2000** [comment]
Does someone know which patch fixed this issue?

Also wez, would you mind doing another release, please?

**Comment by johnae** [comment]
@SuperSandro2000 see here for more on this: https://github.com/wez/wezterm/issues/4504

Basically, upgrading smithay client toolkit to 0.16.1 is what fixed the issue. Unfortunately, there are other issues with that version. There's no obvious other way to fix those without upgrading sctk to 0.17 or 0.18 (and that's a big undertaking as the api:s changed significantly - so, need a full rewrite of the wayland support in wezterm).

Unfortunately it means wayland support in wezterm is quite bad at the moment.

**Comment by johnae** [comment]
@SuperSandro2000 - the specific commit that fixed startup on newer compositors (i.e this issue) would be https://github.com/wez/wezterm/commit/44c914c230be1d7388333e385013a111e8bbb883

That comes with a different issue however as noted above.

**Comment by SuperSandro2000** [comment]
Big oof

**Comment by RobWalt** [comment]
For a temporary fix, citing wez:

> For the least overall pain, I recommend setting `enable_wayland = false` (https://wezfurlong.org/wezterm/config/lua/config/enable_wayland.html) and using XWayland.

That worked quiet well for me for the moment. I guess, for full wayland support on newer versions we'll have to wait for some friendly soul who has enough experience and/or is willing to learn wayland to fix the issue.

**Comment by deadeyesky** [comment]
wezterm 20230712-072601-f4abf8fd suffers from the same issue mentioned above. It will not open unless wayland is set to false on the lua config file.

**Comment by johnae** [comment]
@deadeyesky That's the version noted in this issue. See the issue description.

**Comment by r4c3** [comment]
Found a fix for me that doesn't involve `config.enable_wayland = false`.
System: Fedora 39, wezterm 20230712-072601-f4abf8fd, Nvidia GPU.

1 - Uninstall WezTerm in the Software app
2 - Install NVIDIA 470xx Linux Graphics Driver in Software app
3 - Download Wezterm with dnf [link](https://wezfurlong.org/wezterm/install/linux.html#installing-on-fedora-and-rpm-based-systems-via-copr)

If this doesn't work, `config.enable_wayland = false` but I didn't like the gnome window header at the top, this fixes that. GL

**Comment by MobSenpai** [comment]
Man I am frustrated with this for a while now. This started when I switched to 23.11 stable release. I use flake and home-manager for managing my nixos install, the release of both nixpkgs and home-manager has been pinned to 23.11.

Details:
WM: Hyprland (I don't know version but its the latest from 23.11 nixos branch)
Term: Wezterm (wezterm 20230712-072601-f4abf8fd)

Error:- (ran wezterm using wezterm --skip-config)
```
interface 'wl_surface' has no event 2
14:23:48.901  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating
warning: queue 0x55d19991b290 destroyed while proxies still attached:
  wl_callback@34 still attached
  xdg_wm_base@22 still attached
  wl_surface@21 still attached
  wl_data_device@18 still attached
  wl_pointer@16 still attached
  zwp_text_input_v3@15 still attached
  wl_keyboard@14 still attached
  zwp_primary_selection_device_v1@13 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@12 still attached
  wl_output@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
```

Does anyone have any idea to fix this. I don't want to revert back to previous release nor want to use the unstable branch or wezterm's nightly version.
I don't know if it will help but this is my dotfiles ![dots](https://github.com/MobSenpai/dotfiles)

--------------------- @wez ------------------------------------------

**Comment by johnae** [comment]
@MobSenpai There's no good workaround today for this problem. See: https://github.com/wez/wezterm/issues/4504

You can probably get around the problem by disabling wayland support in wezterm and rely on the X11 implementation. That's the workaround in nightly/main as well as there's an issue even when resolving this one by updating sctk to 0.16.1.

**Comment by csdvrx** [comment]
Until them, is it not possible to [do like the BSD solution](
https://cgit.freebsd.org/ports/diff/x11/wezterm/files/patch-sctk?id=5c9692ca786cc9e0c9c9ff9c67cab97cb68b422b) and simply ignore the  wl_surface::Event::preferred_buffer_scale?
   
    Backport https://github.com/Smithay/client-toolkit/commit/5cfd95021c05
    to ignore wl_surface::Event::preferred_buffer_scale after
    https://invent.kde.org/plasma/kwin/-/commit/d2b0ed0c5a1e
    https://github.com/swaywm/sway/commit/fc16fb65491b
    
    --- cargo-crates/smithay-client-toolkit-0.16.0/src/environment.rs.orig	1970-01-01 00:00:00 UTC
    +++ cargo-crates/smithay-client-toolkit-0.16.0/src/environment.rs
    @@ -283,6 +283,7 @@ impl<I: Interface + Clone + From<Proxy<I>> + AsRef<Pro
             version: u32,
             _: DispatchData,
         ) {
    +        let version = I::VERSION.min(version);
             self.global = Some((*registry.bind::<I>(version, id)).clone())
         }
         fn get(&self) -> Option<Attached<I>> {

**Comment by mostafaqanbaryan** [comment]
> @MobSenpai There's no good workaround today for this problem. See: #4504
> 
> You can probably get around the problem by disabling wayland support in wezterm and rely on the X11 implementation. That's the workaround in nightly/main as well as there's an issue even when resolving this one by updating sctk to 0.16.1.

Disabling Wayland support introduces new problems.
If I open 2 wezterm windows, the first one becomes very laggy until the second one gets closed.
(This happens when you would do something like `tail -f some.log` on the second one)
So basically, this could work temporarily, but it's not a good solution.

**Comment by MobSenpai** [comment]
@wez This is not closed. Kindly Reopen this issue. I don't know how many are affected with this but this should be worked upon by the developers. There has not been any update on this issue here by any main developer. 
Thank you

**Comment by wez** [comment]
> this should be worked upon by the developers. There has not been any update on this issue here by any main developer.

I'm not sure if you are aware of how entitled this sounds.

As I've mentioned elsewhere in the issue tracker, wayland support in wezterm is not in good shape currently and requires significant effort to get into better shape because the wayland ecosystem crates dramatically changed their API.

I do not have time or inclination to do this work, but if sufficient sponsorship materializes to fund it, then I will consider making time for it. I would appreciate a set of PRs that do this work.

Regarding the status of this issue: the issue reported by the OP was resolved for the OP at the time it was evaluated.
If you are having an issue, and it doesn't appear to be covered by an existing open issue, then you are encouraged to open a new one with all relevant information.

**Comment by sjcobb2022** [comment]
On NixOS, I rebuilt wezterm with the most up to date Cargo.lock and updated the hashes and this got it to work. On Hyprland latest btw.

For NixOS users, perhaps when #4649 and #4286 are merged eventually it should be able to build without much issue. 

I understand that there are some deeper issues with wayland + wezterm, but nightly deps seem to work fine.

I am using the Cargo.lock from 721fbdf5dc39aaeacc0517e0422d06f0cf81561b with the hashes of xcb and xcb-imdkit as: 

```nix
"xcb-imdkit-0.2.0" = "sha256-L+NKD0rsCk9bFABQF4FZi9YoqBHr4VAZeKAWgsaAegw=";
"xcb-1.2.1" = "sha256-zkuW5ATix3WXBAj2hzum1MJ5JTX3+uVQ01R1vL6F1rY=";
```

Can post full pkg definition if anyone would like

**Comment by johnae** [comment]
@sjcobb2022 Are you saying you don't see duplicate characters input spuriously on Hyprland latest and wezterm latest (using the wayland impl)? I.e https://github.com/wez/wezterm/issues/4504

Because that is the issue with 0.16.1 sctk which wezterm uses (and upgrading to > 0.16 means a complete rewrite of the wezterm wayland impl which is a large undertaking).

**Comment by sjcobb2022** [comment]
@johnae I have not had that issue. I can play around with it a bit if you would like. I have a very minimal wezterm config so it could be something to do with that?

I can use the config that is in #4504 at some point this week and see if I get the same behavior.

Literally just:
```lua
-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm';

return {
  font = wezterm.font("FiraCode Nerd Font"),
  font_size = 12.0,
  color_scheme = "tokyo-city-terminal-dark",
  hide_tab_bar_if_only_one_tab = true,
  window_close_confirmation = "NeverPrompt",
  set_environment_variables = {
    TERM = 'wezterm',
  },
}
```

**Comment by NovaViper** [comment]
> On NixOS, I rebuilt wezterm with the most up to date Cargo.lock and updated the hashes and this got it to work. On Hyprland latest btw.
> 
> For NixOS users, perhaps when #4649 and #4286 are merged eventually it should be able to build without much issue.
> 
> I understand that there are some deeper issues with wayland + wezterm, but nightly deps seem to work fine.
> 
> I am using the Cargo.lock from [721fbdf](https://github.com/wez/wezterm/commit/721fbdf5dc39aaeacc0517e0422d06f0cf81561b) with the hashes of xcb and xcb-imdkit as:
> 
> ```nix
> "xcb-imdkit-0.2.0" = "sha256-L+NKD0rsCk9bFABQF4FZi9YoqBHr4VAZeKAWgsaAegw=";
> "xcb-1.2.1" = "sha256-zkuW5ATix3WXBAj2hzum1MJ5JTX3+uVQ01R1vL6F1rY=";
> ```
> 
> Can post full pkg definition if anyone would like

Hey how did you build wezterm nightly on NixOS? Can you show what exactly you have for building the package?

**Comment by sjcobb2022** [comment]
> Hey how did you build wezterm nightly on NixOS? Can you show what exactly you have for building the package?

Here ya go! https://github.com/sjcobb2022/nixos-config/blob/main/pkgs/wezterm-nightly/default.nix

**Comment by NovaViper** [comment]
@sjcobb2022 Thank you! I'm going to give this a test later tomorrow

**Comment by NovaViper** [comment]
I gave the nightly build a test but I notice one really big issue, it doesn't seem to update the statusline anymore unless I have it open a prompt (like the confirmation prompt for when you close the terminal). Ended up switching back to the version that's currently available on nixpkgs.

**Comment by sjcobb2022** [comment]
> I gave the nightly build a test but I notice one really big issue, it doesn't seem to update the statusline anymore unless I have it open a prompt (like the confirmation prompt for when you close the terminal). Ended up switching back to the version that's currently available on nixpkgs.

Huh strange. I don't really use the status line much, but I can see how that would be an issue.

Honestly it looks like wez is alright with merging a flake into nixos, and there are currently 2 pull requests open, one for the flake and another for CI to update the flake.

My nightly build was just a quick fix whilst we wait for that to get merged.

**Comment by MobSenpai** [comment]
Sorry my previous comment was a false alarm. Actually disabling wayland support does work now, idk why it didn't when I tried it before.  Now hopefully we see some progress making it possible to use natively.
