### ISSUE TITLE
wezterm carries over GIO_USE_VFS from flatpak

### ISSUE THREAD

**Issue by ittayd** [wez/wezterm#4487]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

???

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm using the flatpak installation of wezterm. This is why I can't do `wezterm -v` or use the nightly.
I'm on Ubuntu 22.04
For some reason, flatpak is started with GIO_USE_VFS=local in its environment (appears in /etc/profile.d/flatpak.sh  and /etc/X11/Xsession.d/20flatpak).
Wezterm inherits this and passes to the shell it is running.
This makes `gio` not work for remote volumes. Unfortunately, the error is obscure ("volume doesn’t implement mount" in `gio mount`), so not trivial to identify.
I'm not sure the rules of environemnt variables passing, but maybe there should be a blacklist of those that shouldn't be passed because of weird cases such as the above. 

### Configuration

.

**Comment by wez** [comment]
To clarify: if you `unset GIO_USE_VFS` in your shell, things will start to work?
If so, would you mind submitting a PR to remove that env var in the same way that we do over here:
https://github.com/wez/wezterm/blob/2a022399bb0b6037f06b6ad3175dd98beb0aa7b2/env-bootstrap/src/lib.rs#L232-L235
