### ISSUE TITLE
docs: some leftover emojis

### ISSUE THREAD

**Issue by jaredg** [wez/wezterm#4489]
**What page or section of the docs have an issue?**
/docs/install

**Describe the issue**
The download page for each of the platforms did use the emoji plugin you deprecated with fec90ae. 

<img width="688" alt="Screenshot 2023-10-25 at 12 55 00" src="https://github.com/wez/wezterm/assets/4268/2e637178-5932-475c-a9a0-190cea158903">

**Comment by pzmarzly** [comment]
Also https://wezfurlong.org/wezterm/ has a `Download :material-tray-arrow-down:` label
