### ISSUE TITLE
`tab_bar_at_bottom` and `window_decorations` shift tab bar

### ISSUE THREAD

**Issue by 0xdead10cd** [wez/wezterm#4495]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Placing the tab bar at the bottom of the window and removing the title bar but keeping the integrated buttons results in the tabs being shifted right instead of being fully left aligned:
<img width="574" alt="Screenshot 2023-10-26 at 10 18 41 PM" src="https://github.com/wez/wezterm/assets/93291476/6554fdd4-5fad-41c8-9328-23653d56c0b0">

Removing the integrated buttons results in the tabs actually being fully left aligned:
<img width="574" alt="Screenshot 2023-10-26 at 10 25 53 PM" src="https://github.com/wez/wezterm/assets/93291476/7e51a388-4cd9-4ad0-97ec-357817ed2765">

My guess is that the empty space is somehow being reserved for the integrated buttons even though the tab bar is at the bottom of the window.

### To Reproduce

Just open the terminal with the config shared. The tabs are shifted right.

### Configuration

```lua
local wezterm = require 'wezterm'

local config = {}

if wezterm.config_builder then
	config = wezterm.config_builder()
end

config.tab_bar_at_bottom = true
config.window_decorations = "INTEGRATED_BUTTONS|RESIZE"

return config
```

### Expected Behavior

The tabs are left aligned within the tab bar.

**Comment by benbooth493** [comment]
I'm facing this exact same issue

**Comment by wez** [comment]
Fixed in https://github.com/wez/wezterm/pull/4505 and in recent releases
