### ISSUE TITLE
Parsing of ProxyCommand doesn't use Hostname with %h

### ISSUE THREAD

**Issue by oceanusxiv** [wez/wezterm#4503]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When wezterm reads the SSH config file's ProxyCommand, it substitutes `%h` with the host, instead of the host name specified by the `HostName` field of the config. For particularly exotic proxy commands this can cause issues.

I believe the relevant line is 
https://github.com/wez/wezterm/blob/fec90ae04bf448d4b1475ba1d0ba1392846a70d6/wezterm-ssh/src/config.rs#L535

### To Reproduce

Run wezterm in verbose `wezterm ssh -v username@host` with some config file setup in `~/.ssh/config` like such

```
Host host
    ProxyCommand sh -c "some_command %h"
    HostName different_name
    User ubuntu
```

and observe the resulting proxy command being issued, which would most likely be
`sh -c "some_command host"` instead of the more correct `sh -c "some_command different_name"`.

### Configuration

no config

### Expected Behavior

The substitution of `%h` should use the `HostName` specified in the config file for that target (if it was specified).

**Comment by wheatdog** [comment]
References:

https://github.com/openssh/openssh-portable/blob/88351eca17dcc55189991ba60e50819b6d4193c1/ssh.c#L1215-L1221

https://github.com/openssh/openssh-portable/blob/88351eca17dcc55189991ba60e50819b6d4193c1/ssh.c#L1432

https://github.com/openssh/openssh-portable/blob/master/sshconnect.h#L63
