### ISSUE TITLE
Font displays differently with identical wezterm.font and wezterm.font_with_fallback

### ISSUE THREAD

**Issue by tj-moody** [wez/wezterm#4506]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20231017-091526-fec90ae0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using `wezterm.font_with_fallback` for the `font` field of config displays text differently than using `wezterm.font`.
As you can see [here](https://imgur.com/a/6oVqBjC), changing between the two changes the text, without modifying any other options, despite the font configurations being identical.

### To Reproduce

Switch between using font_with_fallback and font in the config below.

### Configuration

```lua
return {
    -- font = wezterm.font_with_fallback(
    --     {
    --         family = 'FiraCode NFM',
    --         weight = 'Medium',
    --     }
    -- )
    font = wezterm.font(
        'FiraCode NFM',
        {
            weight = 'Medium',
        }
    )
}
```

### Expected Behavior

Wezterm should render text the same way with both options

### Logs

The only log produced by performing the same actions as in the linked video:
20:44:12.038  INFO   wezterm_gui::termwindow > QuitApplication over here (window)

**Comment by wez** [comment]
You can use `wezterm ls-fonts` to explain the font fallback in each of those cases.
