### ISSUE TITLE
Moving WezTerm between monitors results in GNOME crash

### ISSUE THREAD

**Issue by aral** [wez/wezterm#4510]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter via latest GNOME on Fedora Silverblue.

### WezTerm version

20230904-133103-914f18b1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No.

### Describe the bug

Moving WezTerm between monitors can cause WezTerm to crash, taking down the GNOME session with it and dropping you at the login screen.

### To Reproduce

1. On a GNOME system running under Wayland, launch WezTerm.
2. Using your mouse, move the window between two monitors.
3. Wiggle your mouse until WezTerm crashes, taking down your GNOME session with it.

### Configuration

no config

### Expected Behavior

It should not crash :)

**Comment by aral** [comment]
Initial lines in the debug overlay:

```
wezterm version: 20230904-133103-914f18b1 x86_64-unknown-linux-gnu
Window Environment: Wayland
WebGPU: name=AMD Radeon Graphics (RADV RENOIR), device_type=IntegratedGpu, backend=Vulkan, driver=radv, driver_info=Mesa 23.1.8, vendor=4098, device=5688
```

**Comment by wez** [comment]
Note: If gnome crashes, that is a gnome bug. No program should be able to crash the compositor.

**Comment by aral** [comment]
Well, WezTerm crashes too :) (Sometimes it brings down GNOME, sometimes it doesn’t. I haven’t yet encountered another app that exhibits this behaviour.)

**Comment by aral** [comment]
Also opened issue on GNOME Shell regarding the shell crash:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7176

**Comment by Pajn** [comment]
I was able to workaround both the gnome and wezterm crashes with:
```lua
config.front_end = "OpenGL"
config.adjust_window_size_when_changing_font_size = true
```

**Comment by wez** [comment]
Please try with the latest nightly build
