### ISSUE TITLE
please add option to disable composition state shown at cursor

### ISSUE THREAD

**Issue by jettero** [wez/wezterm#4511]
I'd like to re-open or re-discuss issue #4297 ... to either add an option to disable this, or maybe help me figure out why it's happening to me.

              I've no idea what that is, it doesn't come from wezterm.

_Originally posted by @wez in https://github.com/wez/wezterm/issues/4297#issuecomment-1722279662_
            
No, it definitely does. Though, in my case, it may be an exotic or old input configuration. I've been using my compose key this way for roughly 20 years and I've noticed various new things would rather I switch to something else (xim or ime or whatever). I like the way my boring old-fashioned compose key works though and Archlinux seems to leave me a alone about it.

But it's exactly as @alopatindev says in his original issue... it shows each key I type as an annoying white on gray text. It disappears as soon as I complete the compose-key combo and my glyph shows up in its place.

This only happens in wezterm, not in xfce4-terminal or in xterm ... and not in my browser when I type "űber" or "sí" or something -- only wezterm.

It has a left-over-debug-print feel too it, except that it neatly disappears when I'm done with the compose-key sequence (or it fails to match or whatever). I could accept that it's xorg doing it, except that it appears/disappears exactly in the right place in the terminal -- so wezterm pretty much has to know where that is to -- at the very least -- direct [font] traffic.

I wish I could describe my compose-key setup helpfully... best I can do is to say I'm using this xorg settings. I don't think this is xim or ime or whatever, but I just don't know.

```
Section "InputClass"                                                                                                       
        Identifier "system-keyboard"                                                                                       
        MatchIsKeyboard "on"                                                                                               
        Option "XkbOptions" "ctrl:nocaps,compose:lctrl"
EndSection
```

**Comment by alopatindev** [comment]
Thanks for elaborating, I couldn't find time for that.

My config:
```ini
Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "us,ru"
    Option "XkbOptions" "grp:caps_toggle,lv3:rwin_switch,compose:ralt,grp_led:caps,compose:rwin,shift:breaks_caps"
EndSection
```
Pressing right alt reproduces the issue in my case.

**Comment by wez** [comment]
Can you share a screenshot of what this notification looks like?
I still don't understand what you are seeing!

**Comment by wez** [comment]
Did you find and try this option?
https://wezfurlong.org/wezterm/config/lua/config/ime_preedit_rendering.html

**Comment by alopatindev** [comment]
Changing `config.ime_preedit_rendering` and relaunching wezterm has no effect to me, issue still reproduces.

Also
```lua
config.colors = {
  ...
  compose_cursor = 'black',
  ...
}
```

turns the notification to black rectangle (also text cursor disappears), which is a bit better than orange rectangle.

**Comment by alopatindev** [comment]
> Can you share a screenshot of what this notification looks like?

Here's demo, I press `RAlt - - - RAlt . . RAlt LShift RShift LControl`

https://github.com/wez/wezterm/assets/415408/8b4f57b3-9ccc-4d4c-9725-e1161e736f57

**Comment by jettero** [comment]
> Did you find and try this option? https://wezfurlong.org/wezterm/config/lua/config/ime_preedit_rendering.html

No, I hadn't previously tried that one. I just did though. I tried both setting it to 'System' and then to "Builtin" (the default), but neither had any effect at all.

**Comment by jettero** [comment]
It took me a sec to find a way to get screenshots... but it looks sorta like this
![2023-11-16-110839_964x602_scrot](https://github.com/wez/wezterm/assets/54520/a1b2cf58-7315-4293-a67e-4f668e54a2b4)
![2023-11-16-110845_964x602_scrot](https://github.com/wez/wezterm/assets/54520/0c485fed-23e8-47d0-996a-931a3f52acb0)
![2023-11-16-110851_964x602_scrot](https://github.com/wez/wezterm/assets/54520/a84567dd-b005-4840-a766-fa62a9d8392e)

**Comment by wez** [comment]
Thanks, between this and https://github.com/wez/wezterm/issues/4497 I understand that this is referring to the compose cursor.
I've pushed a commit that avoids including the keysym name in the composing state.  That should show up in nightly builds within the next half hour or so.
