### ISSUE TITLE
Focus shifted randomly around panes

### ISSUE THREAD

**Issue by crides** [wez/wezterm#4517]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

Edit: I didn't because I have a big session, and since it's not really possible to save the pane contents now, I don't want to lose them and restore the processes.

### Describe the bug

A weird state where the focus would jump around all of the panes in the current tab randomly. It seems like each key/mouse event will trigger a random pane focus. For example, when holding `e` for a while, each pane will get some amount of `e`, but the amounts are different.

It's also not possible to switch to other tabs, as any attempts to do so will just focus back to the current pane.

Edit: It's not possible to get rid of the issue until all but one of the panes are closed within one tab 

### To Reproduce

 I'm not sure how this was caused in the first place, but maybe I'll run into it again and I'll see

Edit: it happened again. one thing that is common between the 2 occurrences is that wezterm hangs briefly before things went bad. One of the unfocused panes was producing a lot of output, and wezterm stopped updating that pane for 5~10 seconds, and then when it seem to have recovered, the focusing shifting happens.

### Configuration

https://github.com/crides/dotfiles/blob/d03c95f3c6ae79fa555b8aaf9b332f68613c12e8/config/wezterm/wezterm.lua

### Anything else?

No logs in the debug window

**Comment by wez** [comment]
I can't do much with this without a small and reproducible set of instructions.
