### ISSUE TITLE
ActivateRecentTab: Action to activate recent tabs in a LIFO manner

### ISSUE THREAD

**Issue by adamency** [wez/wezterm#4518]
**Is your feature request related to a problem? Please describe.**
This is basically the feature that most browsers (ex: Ctrl+Tab on Firefox) and OSes (Alt+Tab on Windows) have that allows focusing the last focused window/tab/etc.. with the given shortcut and focusing the Nth last one by pressing Tab N-1 times (while holding the modifier) after pressing the shortcut

Would it be possible to implement this in Wezterm ?

**Describe the solution you'd like**
Simply an action `ActivateRecentTab`, maybe an option to set the maximum number of remembered tabs if this costs a lot (but I don't see why it would)

**Comment by wez** [comment]
We have https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateLastTab.html which can be used to toggle the prior tab and back.

**Comment by adamency** [comment]
I know, I already use it but I'm talking about remember more than one recent tab, as described in the issue. Having more than two tabs is quite common if you use tabs.
