### ISSUE TITLE
Tabs are not being background highlighted

### ISSUE THREAD

**Issue by crides** [wez/wezterm#4520]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

tab characters aren't highlighted the same as spaces

### To Reproduce

`echo -e '\e[43m \t \e[0m'`

### Configuration

https://github.com/crides/dotfiles/blob/d03c95f3c6ae79fa555b8aaf9b332f68613c12e8/config/wezterm/wezterm.lua

### Expected Behavior

the tab and the spaces should show as rectangles filled with yellow

### Anything else?

<img width="380" alt="Screenshot 2023-11-02 at 10 53 08" src="https://github.com/wez/wezterm/assets/15631555/ff78becb-32df-432c-a4ab-d73c740c1abd">

**Comment by wez** [comment]
Tab isn't a renderable character in a terminal; it is an escape sequence that moves the cursor to the next tab stop.
The screenshot you shared is how wezterm, kitty and gnome terminal all render the `echo` command that you shared.
