### ISSUE TITLE
Have `wezterm -e` start with `--always-new-process`

### ISSUE THREAD

**Issue by Ram-Z** [wez/wezterm#4523]
This is a follow up of https://github.com/wez/wezterm/issues/2782.

Most terminals will not attach to a running instance of a daemon and therefore are blocking when invoked with `-e`. Some tools rely on waiting for the spawned program to terminate.

In my case I had qutebrowsers external editor command set to `$TERMINAL -e vim {file}`. qutebrowser would create `file` and wait for `vim` to finish before reading and deleting it. With `TERMINAL=wezterm` this didn't work as the file got deleted immediately.

**Describe the solution you'd like**
`wezterm -e` should behave as if `wezterm start --always-new-process`.

**Describe alternatives you've considered**
I now handle `TERMINAL==wezterm` specially and start it as a new process, but I'd rather it just worked with `-e`.

**Comment by vimpostor** [comment]
I agree, `-e` should start a blocking wezterm for compatibility reasons.

I think `wezterm start` should still **not** use `--always-new-process` by default, only the `-e` alias should star a new process by default. I can send in a patch later. I don't have a strong opinion though, so if @wez wants `start` and `-e` to be always consistent, then that's fine with me too.

**Comment by Ram-Z** [comment]
> I think `wezterm start` should still **not** use `--always-new-process` by default.

I agree.

> I don't have a strong opinion though, so if @wez wants `start` and `-e` to be always consistent, then that's fine with me too.

Yeah, and if that means that `-e` continues to behave the way it does now, that's fine too.

**Comment by wez** [comment]
I think this request makes sense, but I'm not sure whether the `clap` library can make it work that way. If you'd like to look into how to make that work, I'd be happy to review a PR for it!

**Comment by vimpostor** [comment]
> but I'm not sure whether the `clap` library can make it work that way

There is no way to implement it while keeping it as a simple clap alias, because [clap uses a bijective mapping model](https://github.com/clap-rs/clap/issues/1820#issuecomment-615547678), so there is no way to have different behaviour between different aliases: All aliases are the same element to clap and you can't determine which alias was used.

However that's no proble, it is easy to fake this with only a few lines of code.
