### ISSUE TITLE
Ubuntu Mono "weight" option does not work as it should be.

### ISSUE THREAD

**Issue by rempas** [wez/wezterm#4524]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Gnome's Wayland WM

### WezTerm version

wezterm 20231030-074559-75909682

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I don't know if I'm doing something wrong, but the "weight" option for the Ubuntu Mono font does not work as expected.

The options: **Thin** through **Book** look the same. And not only that, but they also make it look like a black "filter" has been applied to the screen and made the text less visible (I don't know how to explain it better).
The options: **Regular** and **Medium** all look the same.
The options: **DemiBold* through *ExtraBlack* all look the same

In short, it only has 3 different, real options in which, the less bold one is broken... 

### To Reproduce

Use Ubuntu Mono and try the different "weight" options.

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.color_scheme = 'Hybrid'
config.font = wezterm.font('Ubuntu Mono', { weight = 'Regular' })
config.font_size = 16

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

I expected all the options to make the font look differently. I also expected the thinner options to just make the text thinner.

### Logs

```
Debug Overlay
wezterm version: 20230712-072601-f4abf8fd x86_64-unknown-linux-gnu
Window Environment: Wayland
OpenGL: AMD Radeon RX 460 Graphics (polaris11, LLVM 16.0.6, DRM 3.54, 6.5.9-arch2-1) 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
```

**Comment by wez** [comment]
The behavior is dependent upon the fonts that you have installed.  Sometimes, only a subset of a font is installed and you may need to install additional font files for the different weights to be usable.

You can use `wezterm ls-fonts` to have wezterm explain which fonts are used for different styles.

You can use `wezterm ls-fonts --list-system | grep "Ubuntu Mono"` to show the available variants of that font on your system.

**Comment by rempas** [comment]
Thank you for the reply! Using `wezterm ls-fonts --list-system | grep "Ubuntu Mono"` prints, the following list:

```
"Ubuntu Mono",
  {family="Ubuntu Mono", style="Italic"},
  "Ubuntu Mono",
  {family="Ubuntu Mono", weight="Bold"},
  {family="Ubuntu Mono", weight="Bold", style="Italic"},
  {family="Ubuntu Mono", style="Italic"},
  "Ubuntu Mono",
wezterm.font("Ubuntu Mono", {weight="Regular", stretch="Normal", style="Normal"}) -- /usr/share/fonts/ubuntu/UbuntuMono-R.ttf, FontConfig
wezterm.font("Ubuntu Mono", {weight="Regular", stretch="Normal", style="Italic"}) -- /usr/share/fonts/ubuntu/UbuntuMono-RI.ttf, FontConfig
wezterm.font("Ubuntu Mono", {weight="Bold", stretch="Normal", style="Normal"}) -- /usr/share/fonts/ubuntu/UbuntuMono-B.ttf, FontConfig
wezterm.font("Ubuntu Mono", {weight="Bold", stretch="Normal", style="Italic"}) -- /usr/share/fonts/ubuntu/UbuntuMono-BI.ttf, FontConfig
```

Based on that, I do understand that there is only the "Regular" and "Bold" types available. It is very weird, tho, as "foot" and "gnome-terminal" render them in a more light tone. 

Aren't there any other settings or "hacks" to achieve that?

**Comment by wez** [comment]
Yes, wezterm will synthesize some display properties if certain weights are missing. `wezterm ls-fonts` should explain when that is happening.  Here's an example from mine, for half-intensity text; note the `will synthesize dim` annotation:

```
When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- /home/wez/.fonts/OperatorMonoSSmLig-BookItalic.otf, FontDirs
  -- AKA: "Operator Mono SSm Lig Book"
  {family="Operator Mono SSm Lig", weight=325, style="Italic"},

  -- /home/wez/.fonts/Vazir-Code-WOL.ttf, FontDirs
  -- Will synthesize italics
  -- Will synthesize dim
  "Vazir Code WOL",
```

The logic to enable that can be found here:

https://github.com/wez/wezterm/blob/d6809533215e273ca23e52614c886929ad702715/wezterm-font/src/parser.rs#L785-L791

**Comment by rempas** [comment]
Ok! Thanks for the help and for your work! I will close this issue now, as there is nothing more to be done here. Have a beautiful Sunday!
