### ISSUE TITLE
Wezterm throws error upon exit in Hyprland

### ISSUE THREAD

**Issue by ke1satsu** [wez/wezterm#4532]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyyprland

### WezTerm version

Current main (wezterm -V returns "someone forgot to call assign_version_info)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When exiting wezterm after spawning it from another terminal this error is thrown:

warning: queue 0x55555a9bc490 destroyed while proxies still attached:
wl_callback@51 still attached
zwp_primary_selection_offer_v1@4278190089 still attached
wl_data_offer@4278190082 still attached
wl_data_offer@4278190083 still attached
wl_shm_pool@53 still attached
wl_shm_pool@50 still attached
wl_data_offer@4278190080 still attached
xdg_wm_base@23 still attached
wl_surface@22 still attached
wl_data_device@19 still attached
wl_pointer@17 still attached
zwp_text_input_v3@16 still attached
wl_keyboard@15 still attached
zwp_primary_selection_device_v1@14 still attached
zwp_primary_selection_device_manager_v1@3 still attached
wl_data_device@13 still attached
wl_output@12 still attached
wl_output@11 still attached
zwp_text_input_manager_v3@10 still attached
zxdg_decoration_manager_v1@9 still attached
wl_seat@8 still attached
wl_data_device_manager@7 still attached
wl_subcompositor@6 still attached
wl_compositor@5 still attached
wl_shm@4 still attached
wl_registry@2 still attached

### To Reproduce

1. Build current main.
2. Spawn wezterm-gui from another terminal (alacritty) in Hyprland.
3. Run exit command in wezterm
4. Observe error in the previous terminal window

### Configuration

no config

### Expected Behavior

A clean exit with no error.

**Comment by wez** [comment]
I have no idea what version is being used here, but I suggest that you try the latest nightly build and open a new issue if it persists with the nightly
