### ISSUE TITLE
Characters not rendering in the correct position with double-space characters in prompt

### ISSUE THREAD

**Issue by Ktoks** [wez/wezterm#4540]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Nushell -> WSL on Windows or Nushell -> ssh remote linux

### WezTerm version

20231104-094153-d6809533

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using a prompt with double-width characters - when scrolling back or pasting in - the characters don't line up.
Sometimes they leave artifacts, and when one scrolls left to delete and/or type over things - upon pressing enter - where I had edited is off by 1-2 characters. I assume Wezterm isn't accounting for the double-sized characters.

### To Reproduce

Using bash with bash prompt or starship prompt, zsh with zsh prompt or starship prompt, or nu with starship prompt - 
on the same line as the cursor (in the prompt) - put a double-width character.
Run a command such as `ls`. 
Hit the up arrow to invoke scroll-back until artifact(s) are noticed. Sometimes this is more noticeable on larger commands.
One can also attempt to edit the line by scrolling left and typing something - to see that the cursor doesn't align with the space the actual characters one is typing exist in.

### Configuration

config.default_prog = { 'C:\\Users\\<user>\\.cargo\\bin\\nu' }

### Expected Behavior

Normal prompt behavior - no mis-aligned characters, no artifacts, etc....

### Logs

Debug Overlay
wezterm version: 20230911-075810-70931f58 x86_64-pc-windows-msvc
Window Environment: Windows
WebGPU: name=Intel(R) UHD Graphics 620, device_type=IntegratedGpu, backend=Vulkan, driver=Intel Corporation, driver_info=Intel driver, vendor=32902, device=16032
Enter lua statements or expressions and hit Enter.

### Anything else?

This is less of an issue, but still happens when using this configuration - upon using Nushell as the login shell - the prompt starts at the bottom of the page instead of the top.
![image](https://github.com/wez/wezterm/assets/36412717/6af0ccfa-0af0-4c4a-9ea8-eca848a4f5a3)
Note in the image - I ran kali, then hit the up arrow - to go back twice, the last command was `echo` and the 2nd back was `ls`.

**Comment by Ktoks** [comment]
Also worth noting - Nushell doesn't do this with Alacritty or Putty.

**Comment by abhbh** [comment]
I can reproduce this. It happens when I press `Up` to traverse history or `Ctrl+R` to search.

![Screenshot 2024-01-12 014755](https://github.com/wez/wezterm/assets/131632391/e2fb34eb-9bd3-4b43-a8cc-887d40c11ee5)

Last command was `git --version`. After pressing `Up`, `gi` got stuck and cannot be deleted. Any subsequent command from the history will be prefixed with `gi`. If I press `Enter`, the unmodified command will execute though.

Wezterm latest (on Windows 11 22H2, Nvidia driver 546.33). Git Bash 2.43 with Starship 0.17.1 prompt. Alacritty and Windows Terminal work fine.

**Comment by wez** [comment]
Sounds like a unicode version mismatch. See: https://wezfurlong.org/wezterm/config/lua/config/unicode_version.html

Also worth noting that nushell has a history of weird history, placement and readline glitches, especially on Windows, that often get reported against wezterm, and this may be another one of those.

**Comment by abhbh** [comment]
Weirdly for me, it happens when using bash but not nushell.

**Comment by wez** [comment]
Things for you to look at include:
* https://wezfurlong.org/wezterm/config/lua/config/unicode_version.html
* https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html

Please play around and report back with some more concrete information on what is being output and how it is being rendered
