### ISSUE TITLE
Unicode Hex Input Problems (macOS)

### ISSUE THREAD

**Issue by invisible1988** [wez/wezterm#4542]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm using the 'Unicode HEX Input' Keyboard Layout on MacOS. Badly it's not working to enter unicode characters. 

I've tried a lot of configuration options that I found. Nothing changed the behavior. 

### To Reproduce

1. Select as System Keyboard Layout 'Unicode HEX Input'
2. Open wezterm
3. Hold `alt` and type `00e4` 
4. The character `ä` should appear

### Configuration
`
local wezterm = require("wezterm")

local config = {}

if wezterm.config_builder then
        config = wezterm.config_builder()
end

config.color_scheme = "Night Owl (Gogh)"
config.font = wezterm.font("Hack Nerd Font")
config.window_decorations = "RESIZE"
config.enable_tab_bar = false

return config
`

**Comment by azerbe** [comment]
+1

I'm using unicode characters to write german symbols with a US layout (software). Wezterm seems to be blocking/ignoring this, even when AltGr or dead_key options are toggled.

**Comment by invisible1988** [comment]
@azerbe I've switched to kitty. Works pretty well.
