### ISSUE TITLE
wezterm resizes vertically when being unfocused

### ISSUE THREAD

**Issue by ndfsa** [wez/wezterm#4547]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter (Version: 45.1) (gnome)

### WezTerm version

wezterm 20231107-082518-f0e3eecb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When losing focus, wezterm resizes vertically by about one column, this happens with any window, even clicking on the pannel.

https://github.com/wez/wezterm/assets/25588077/fd81b026-aa7e-493c-bfd8-6bdfdc40a48d

### To Reproduce

1. launch another application (I used calculator)
2. launch wezterm without activating the gnome overview (by this stage, wezterm should be the application with focus)
3. click on the other application that is currently open

### Configuration

```lua
local config = {
    use_fancy_tab_bar = false,
    initial_rows = 36,
    initial_cols = 120,
}
return config
```

### Expected Behavior

When losing focus, keep current size.

### Anything else?

I tried disabling all gnome extensions and got the same behavior.

One thing I noticed is that when launching wezterm from the gnome overview (pressing the windows 
 key), the bug goes away. This only happens when launching it from the dock (dash-to-dock extension) or with a custom shortcut.

This bug also does not produce any output on stderr when launching it from another terminal, or with the Debug Overlay.

**Comment by ndfsa** [comment]
Some additional info, I noticed the same behavior when clicking the border of a wezterm window (when the cursor is in the resize state).

**Comment by wez** [comment]
Please try the latest nightly build

**Comment by ndfsa** [comment]
Thanks for getting back, I tried the nightly version and building it from source:

- wezterm 20240922-105555-6a12dd1a (nightly)
- wezterm 20240922-105911-de0ecc60 (from source)

in both versions, the problem seems to be gone, it no longer resizes vertically.

I must mention that in both versions, window decorations seem to be gone, with the same config above.

![Screenshot From 2024-09-22 15-11-40](https://github.com/user-attachments/assets/9e4cc143-8ac2-46c2-bd99-266ab53b13be)

That may be another issue, but still worth mentioning here.

Thank you very much!

**Comment by wez** [comment]
Thanks for confirming!
I think the missing decorations may be this issue:
* https://github.com/wez/wezterm/issues/4962

**Comment by ndfsa** [comment]
Yes, that is it, feel free to close this issue, thank you for your amazing work.
