### ISSUE TITLE
Paste with Shift+Insert doesn't work

### ISSUE THREAD

**Issue by jabbalaci** [wez/wezterm#4550]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

XFCE

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Pasting with Shift+Insert doesn't work.

## with vim
- Open vim, type in a text, select it and yank it.
- Open gedit, press Ctrl-v (works), then press Shift+Insert (should also work).
- Go back to vim, and press `p` in normal mode (paste). It should work. Go to insert mode and press Ctrl-Shift-v : also works. In insert mode press Shift+Insert : nothing happens.

## with micro
It's simpler than vim. 
- Write in a text, select it and press Ctrl-c . Go to a new line and press Ctrl-v : works. Press Shift-Insert : you don't get the same text.
- Start gedit. There pasting with Ctrl-v and Shift-Insert work.

### Configuration

I renamed my config file and launched wezterm with zero configuration.

### Expected Behavior

With Ctrl-v and Shift-Insert I would like to paste the same text. If Ctrl-v works, Shift-Insert should also work.

### Logs

Debug Overlay
wezterm version: 20230712-072601-f4abf8fd x86_64-unknown-linux-gnu
Window Environment: X11 Xfwm4
OpenGL: Mesa Intel(R) HD Graphics 4600 (HSW GT2) 4.6 (Compatibility Profile) Mesa 23.1.9-manjaro1.1

### Anything else?

I'm trying to move from Konsole to wezterm. I tried it in Konsole, there it works well.

**Comment by bew** [comment]
On X11 there is the clipboard buffer (usually controlled through Ctrl-c/v/x), and there is the primary selection (and less used, the secondary selection).
The X11 primary selection is normally automatically filled when you select some text in an application, and then Shift-Insert is used to paste from that primary selection.

If you want to paste from the Clipboard when you do Shift-Insert, you'll need to configure the Shift-Insert keybind in your config using the [`PasteFrom` action](https://wezfurlong.org/wezterm/config/lua/keyassignment/PasteFrom.html)

**Comment by jabbalaci** [comment]
Thank you! After adding the following line it works as I expected:

    { key = "Insert", mods = "SHIFT", action = act.PasteFrom("Clipboard") },
