### ISSUE TITLE
Cursor hides character underneath it

### ISSUE THREAD

**Issue by ctron** [wez/wezterm#4551]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

kwin

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

On `konsole` (and other terminal emulators I used so far) the cursor inverts the color scheme of the current character. In wezterm it overrides it. This makes it impossible to see what character is underneath the cursor

### To Reproduce

In wezterm:

![image](https://github.com/wez/wezterm/assets/202474/3e8d7b57-7097-474e-a87d-21d9846b7dec)

In konsole:

![image](https://github.com/wez/wezterm/assets/202474/0b272cb8-5367-4278-b200-d19b48231daa)

Using konsole, I can still see the character underneath the cursor. Where in wezterm, I need to navigate away the cursor to do so.

### Configuration

```lua
local wezterm = require 'wezterm'

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.font = wezterm.font 'DejaVu Sans Mono'
config.color_scheme = 'Breeze (Gogh)'

config.hide_tab_bar_if_only_one_tab = true

return config

```

### Expected Behavior

I would want to be able to select a cursor mode where the cursor inverts fg with bg instead of applying a static color.

### Anything else?

Maybe there's is something in the configuration. I saw it mentioning "cursor block mode", but I couldn't find anything relating to that.

**Comment by alexesba** [comment]
@ctron This is not an issue. There is a config flag you can use to fix it. 
```
force_reverse_video_cursor = true,
```

**Comment by ctron** [comment]
Ah, indeed. That solves it!

Would be great to have this mentioned in https://wezfurlong.org/wezterm/config/appearance.html
