### ISSUE TITLE
Specify window size as percent of screen size

### ISSUE THREAD

**Issue by pcause** [wez/wezterm#4555]
**Is your feature request related to a problem? Please describe.**

I use the same config file on different systems and the monitors are different screen sizes.  One is 1920x1080 another is 2560x1080 and the other is 4K.   When I start I always needs to resize the terminal.

**Describe the solution you'd like**
I'd like to be able to specify cols/rows as percent of screen size, or perhaps just s single percent that is applied against both columns and rows.  For example, pecifying col=80% would make the terminal use 80% of the width of the screen.

**Describe alternatives you've considered**
none

**Comment by wez** [comment]
You can script this for yourself:
* https://wezfurlong.org/wezterm/config/lua/wezterm.gui/screens.html
* https://wezfurlong.org/wezterm/config/lua/gui-events/gui-startup.html
