### ISSUE TITLE
Wezterm takes half of screen when entering overview mode on GNOME

### ISSUE THREAD

**Issue by Naadiyaar** [wez/wezterm#4569]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME Mutter 44.6

### WezTerm version

20231107-082518-f0e3eecb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When full screen and entering overview mode on gnome wezterm occupies most of screen
[Screencast from 2023-11-12 18-09-09.webm](https://github.com/wez/wezterm/assets/106643149/d91e9b8e-de43-483f-acba-96bc1b3bb46e)

### To Reproduce

open wezterm
make it full-screen
enter overview mode

### Configuration

THIS IS FULL CONFIG
```lua
local cfg = {
	window_close_confirmation = "NeverPrompt",
	check_for_updates = false,

	-- Avoid unexpected config breakage
	automatically_reload_config = false,

	exit_behavior = "Close",

	-- Disable all noises
	audible_bell = "Disabled",

	-- remove terminal top bar
	window_decorations = "NONE",

	-- setup color theme
	color_scheme = "Solarized Light (Gogh)",
}
cfg.hide_tab_bar_if_only_one_tab = true

cfg.window_padding = {
	left = 3,
	right = 3,
	top = 3,
	bottom = 3,
}

cfg.inactive_pane_hsb = {
	saturation = 0.9,
	brightness = 0.6,
}

-- set cursor shape to a Blinking Bar
cfg.default_cursor_style = "BlinkingBar"
cfg.animation_fps = 1
cfg.cursor_blink_ease_in = "Constant"
cfg.cursor_blink_ease_out = "Constant"

return cfg
```
plus some things about font

### Expected Behavior

Stay in the workspace area

### Anything else?

It's not happening with no configuration

**Comment by Naadiyaar** [comment]
If it helps to solve the problem, also moving the terminal window to another workspace fixes the problem.
Like 
opening the terminal
make it full screen
move it to another workspace

**Comment by Naadiyaar** [comment]
same thing here https://github.com/wez/wezterm/issues/4568#issuecomment-1824204151

**Comment by jokeyrhyme** [comment]
I'm on Arch Linux, GNOME 45.1 (wayland), wezterm 20230712-072601-f4abf8fd and I can't reproduce this, so I wonder if this has been fixed on the GNOME side? Are you able to boot GNOME OS or some other live USB with a newer GNOME to check?

**Comment by ricog** [comment]
If it helps, setting [enable_wayland](https://wezfurlong.org/wezterm/config/lua/config/enable_wayland.html) to `false` is a workaround that resolves the issue for me.

**Comment by B1kku** [comment]
> I'm on Arch Linux, GNOME 45.1 (wayland), wezterm 20230712-072601-f4abf8fd and I can't reproduce this, so I wonder if this has been fixed on the GNOME side? Are you able to boot GNOME OS or some other live USB with a newer GNOME to check?

Using NixOS 24.05.0b8e7a1, Gnome 46.2 (wayland), wezterm 20240203-110809-5046fc22, this still happens.

> If it helps, setting [enable_wayland](https://wezfurlong.org/wezterm/config/lua/config/enable_wayland.html) to false is a workaround that resolves the issue for me.

This also works as a workaround for [#4568](https://github.com/wez/wezterm/issues/4568), I assume they're probably the same issue.

**Comment by wez** [comment]
Please try the latest nightly build
