### ISSUE TITLE
Corrupted cursor when focus is regained in macos native fullscreen mode

### ISSUE THREAD

**Issue by psych3r** [wez/wezterm#4581]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

when wezterm loses focus and regains it ( cmd + tab ) while in native macos fullscreen mode, the cursor is corrupted!
normal cursor:
<img width="493" alt="normal cursor" src="https://github.com/wez/wezterm/assets/1480725/5066e17f-9181-455e-a754-c7d78adb01d8">
after switching to another app and regaining focus:
<img width="551" alt="corrupted cursor" src="https://github.com/wez/wezterm/assets/1480725/e2961064-0aa3-4ed1-8011-1ce23c4b03c2">

### To Reproduce

1. native_macos_fullscreen_mode = true 
2. open wezterm and toggle fullscreen
3. switch to another window with command + tab
4. switch back to wezterm with command + tab

### Configuration

return { native_macos_fullscreen_mode = true }

### Expected Behavior

cursor does not change when switching to another window and returning to wezterm

**Comment by wez** [comment]
Please try the latest release
