### ISSUE TITLE
error: could not compile `wezterm-version` (build script) due to previous error

### ISSUE THREAD

**Issue by TinsFox** [wez/wezterm#4594]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

commit: 600652583594e9f6195a6427

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I downloaded the source code for wezterm and would like to read the source code and try to add some small features, but I didn't find a detailed contribution guide. When I open it with vs code , rust-analyzer gives me error: `could not compile `wezterm-version` (build script) due to previous error`

I seem to get the same error when I run the command cargo build --release. Here is the full error message

<details>
<summary>
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: linking with `cc` failed: exit status: 1
</summary>
  |
  = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/username/Library/pnpm:/Users/username/.nvm/versions/node/v18.15.0/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/username/.cargo/bin:/Users/username/.orbstack/bin:/opt/local/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "arm64" "/var/folders/99/vbhch70s6bl81smmjth8jbmr0000gn/T/rustclsd8pb/symbols.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.14c0tz9aye0mxf99.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.18dvrgucbx2eykv5.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.1sjdya3wef7t2udw.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.20xtji5f8hcis1c2.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.2467mhdquwlqp7rr.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.2m4ned6b4p3x53hb.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.2qhfurvhjhkydeag.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.323pe0fr1d5opb8q.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.37cyd66i6rt8m2k2.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.38fhwxjrpiiqbtcf.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.3lfjmz2hm44x5hjc.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.3msmhez16agfvxgj.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.3ozxvepx6skb4l3l.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.3qzptc7g20qrw1u0.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.40zfsue9xtqvcwcn.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.42696ymj4fv5idte.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.4hacrh4hzqg8sz1j.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.4nivppicqj7416xb.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.4qg9resn91fnenlv.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.53i7hou99omryn1e.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.5cpri2rdooe7k1jg.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.5d0i3xbtz7d6l5hi.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.5eody6j7ghn2x8bi.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.5f70xomym949ijv.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.tzhna41ixnmh50w.rcgu.o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423.2q9vcmfnqx4wcq4f.rcgu.o" "-L" "/Users/username/workspace/oss/wezterm/target/debug/deps" "-L" "/Users/username/workspace/oss/wezterm/target/debug/build/libgit2-sys-20be39339f19925b/out/build" "-L" "/opt/local/lib" "-L" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libgit2-bb78579ff2a865d3.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/liburl-f0771174b786ee83.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libidna-962694083af0fb28.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libunicode_normalization-1bffa803166a8ec8.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libtinyvec-e6313b1b3108145d.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libtinyvec_macros-e9fbbca065cdc522.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libunicode_bidi-b088a217c26b86c1.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libform_urlencoded-5956d76f45500cf5.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libpercent_encoding-7ba09450c7b30529.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/liblog-8bdb6bf9649d880f.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/liblibgit2_sys-6a0dfc23036af55f.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/liblibz_sys-269644e6639184ea.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/liblibc-122608ba5e4f8ade.rlib" "/Users/username/workspace/oss/wezterm/target/debug/deps/libbitflags-539d3bab652e6d62.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-5563368f93f04a18.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-56e96ebffd3d9808.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-68ad5facd2da3c54.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-ed648c021defb5b4.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-815db56da00be265.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-5186709c031b65af.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-7cb2a31ae866e369.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-c39e8cee81fb9ad0.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-b8aeb6382a15b7e5.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-152de6c346c443c1.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-274e1083efe4f227.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libadler-519dc439ccb69841.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-24c437e0616b2003.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-70eb1def4bb8ab07.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-9c748d96a757609c.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-7543628317133907.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-8af68f47e6f26d40.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-a60a966a64bff48d.rlib" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-eeccd9f755247d6f.rlib" "-liconv" "-framework" "Security" "-framework" "CoreFoundation" "-lz" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/Users/username/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/username/workspace/oss/wezterm/target/debug/build/wezterm-version-f17310c261470423/build_script_build-f17310c261470423" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: warning: ignoring duplicate libraries: '-liconv'
          ld: Undefined symbols:
            _iconv, referenced from:
                _git_fs_path_iconv in liblibgit2_sys-6a0dfc23036af55f.rlib[114](fs_path.o)
            _iconv_close, referenced from:
                _git_fs_path_iconv_clear in liblibgit2_sys-6a0dfc23036af55f.rlib[114](fs_path.o)
            _iconv_open, referenced from:
                _git_fs_path_iconv_init_precompose in liblibgit2_sys-6a0dfc23036af55f.rlib[114](fs_path.o)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile `wezterm-version` (build script) due to 2 previous errors

</details>

### Configuration

none

### Expected Behavior

none

### Logs

none

### Anything else?

rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.74.0 (79e9716c9 2023-11-13)`

system: macOS@14.1.1 (23B81) Apple M2

**Comment by TinsFox** [comment]
By the way, where can I find the contribution guide? For example, how to run the project, etc., I don’t seem to have found any relevant documentation.

**Comment by uncomfyhalomacro** [comment]
I am not sure what the log is about. it looks like a rust-analyzer error??

for building wezterm on macos, you can check out https://github.com/wez/wezterm/blob/main/.github/workflows/gen_macos_continuous.yml. you can find relevant steps there to build it. such as the `get-deps` script before running `cargo build --release`. and also you should check if you had run the `git clone` properly with `git submodule`

**Comment by TinsFox** [comment]
1. This is not just a rust-analyzer error, the same error occurs in cargo build --release as well

2. The following message appears when I execute get-deps
<img width="598" alt="image" src="https://github.com/wez/wezterm/assets/33956589/e1dc17e4-e44f-49bb-b1fd-55a262010b4f">

3. submodule should be complete
<img width="241" alt="image" src="https://github.com/wez/wezterm/assets/33956589/7556a165-908f-4971-b58f-09b2030e0828">

**Comment by TinsFox** [comment]
When I use M1, I don't have to do anything for the build to succeed.

I found a [similar problem](https://github.com/rust-lang/rust/issues/117739), but I failed to follow the [method](https://github.com/rust-lang/rust/issues/117739#issuecomment-1805020307)

**Comment by wez** [comment]
this is the supported way to build from source: https://wezfurlong.org/wezterm/install/source.html
