### ISSUE TITLE
math fonts rendering problem

### ISSUE THREAD

**Issue by mathjiajia** [wez/wezterm#4600]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20231117-151105-60065258

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Left: wezterm; Right: kitty
<img width="240" alt="Screenshot 2023-11-20 at 10 02 28 PM" src="https://github.com/wez/wezterm/assets/35106942/0b4f6763-2e53-4442-a312-c9415f0732cf">

<img width="248" alt="Screenshot 2023-11-20 at 10 03 35 PM" src="https://github.com/wez/wezterm/assets/35106942/ed3e005c-7503-4383-a789-881610e4cb9d">

### Configuration

no config

**Comment by wez** [comment]
please try the current release

**Comment by mathjiajia** [comment]
thanks, it works well now.
