### ISSUE TITLE
SHIFT|OPT modifier not working

### ISSUE THREAD

**Issue by mgpinf** [wez/wezterm#4609]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20231120-164150-fde92672

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`SHIFT|OPT` modifier combined with any key doesn't do anything. Since OPT acts as ALT, ideally `SHIFT|OPT` should act as `SHIFT|ALT`, but it doesn't.

`SHIFT|CMD` or `OPT` work normally

### To Reproduce

Enter `SHIFT|OPT` with any key

### Configuration

Ideally this should work without configuring this. But this doesn't work for me even after adding the below code snippet.
```lua
{
    key = 'k',
    mods = 'SHIFT|OPT',
    action = act.SendKey { key = 'k', mods = 'SHIFT|ALT' }
}
```

### Expected Behavior

`SHIFT|ALT` should be sent

**Comment by gabyx** [comment]
Is `OPT` really a defined name in this `mods` table?

**Comment by bew** [comment]
> Is `OPT` really a defined name in this `mods` table?

Yes: https://wezfurlong.org/wezterm/config/keys.html#configuring-key-assignments

I think your issue is with `SHIFT` and the key, not with `OPT`, try using `K` instead of `k` (the shifted/uppercase version of the letter)

**Comment by mgpinf** [comment]
This doesn't work either for me. I feel `SHIFT|OPT` + `key` doesn't seem to be identified at all
```lua
{
    key = 'K',
    mods = 'OPT',
    action = act.SendKey { key = 'k', mods = 'SHIFT|ALT' }
}
```

**Comment by gabyx** [comment]
@mgpinf : Can you enable: https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html
and post the output what is actually detected when you press `Cmd+K` or `Cmd+k`.

**Comment by bew** [comment]
I think @gabyx meant "when you press opt+shift+k`, not when you press cmd+k since that works already.

**Comment by mgpinf** [comment]
Ok, I tried `SHIFT|OPT` with `k` , nothing is logged.

**Comment by mgpinf** [comment]
Nvm, I disabled `karabiner-elements` but had forgotten to disable `amethyst`. Works normally after disabling it. Really sorry. Closing the issue. Love `wezterm`

**Comment by gabyx** [comment]
Haha ok , goog that I asked its a hassle to know where keypresaea get eaten up etc. good that it works
