### ISSUE TITLE
Update to Nerd Fonts v3.1

### ISSUE THREAD

**Issue by nanyaDev** [wez/wezterm#4613]
Nerd fonts v3.1 was recently released and includes some new icons that I'd like to use. It would be nice if the default fallback for Nerd Fonts could be updated from v3.0 to v3.1.

Thanks for the fantastic project! Recently switched and have been loving it :)

**Comment by wez** [comment]
This should be resolved now in `main`: 5e9688bd4ebfc662507a247252e30cc6b4257251

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
