### ISSUE TITLE
Toggle tab bar visibility key binding

### ISSUE THREAD

**Issue by zd-dalibor** [wez/wezterm#4625]
Is it possible to assign key binding to toggle tab bar visibility.

<img width="720" alt="image" src="https://github.com/wez/wezterm/assets/226822/281df954-43a6-4858-965b-5f75d3ea3aac">

Ther is configuration option to disable tab bar `enable_tab_bar = false`. It will be nice if there is an action for toggling tab bar visibility, so we can attach key binding or if there is command pallet action for this.

**Comment by ElectronSutra** [comment]
There is not an available key assignment that toggles the tab bar. In my experience the most consistent way to do this is to write a `settings.json` file somewhere (I use `wezterm.config_dir`), and then source an argument from there. You can see several examples of this in my dots: https://git.sr.ht/~zpm/wezterm.

I do not have a visibility toggle but I do have one to toggle the fancy/retro setting. You can use similar logic to handle the tab bar visibility:
```lua
local function toggle_tab_bar_visible()
	local settings = read_settings_file()

	-- I personally find the ternary `x and y or z` confusing when booleans are
	-- involved, so I prefer to check the nil-ness directly
	local tab_bar_is_visible = settings.tab_bar_is_visible
	if tab_bar_is_visible == nil then
		tab_bar_is_visible = true -- This is the default
	end

	settings.tab_bar_is_visible = not tab_bar_is_visible
	write_settings_file(settings)
end
```

Then you can wrap this function with `wezterm.action_callback` and bind it to a keymap:
```lua
local config = require("wezterm").config_builder()

config.keys = {
	{ key = ";", mods = "CTRL|ALT", action = wezterm.action_callback(toggle_tab_bar_visible) },
}
```

Hope this helps!

**Comment by zd-dalibor** [comment]
Thanks @ElectronSutra.

This looks nice.
Functions `read_settings_file` and `write_settings_file` should read and write configuration from some external sorce, e.g. from json file like you did in your dot files.

**Comment by ChaitanyaPTank** [comment]
First of all, loved wezterm and way you engage/respond with community.

@wez Current approach works but feels little bit slow. any chances this can be done in native way (like opening windows / panes or toggling full screen. Probably a wezterm action ?)

I am not familiar with rust but if it's simple, I am willing to contribute to this one. Please let me know if I can.

Thanks

**Comment by marty-oehme** [comment]
Just to perhaps provide a different implementation, the way I handle this currently is with a simple 'toggle taskbar' wezterm event which gets called with a key bind.

We set up the event:

```lua
wezterm.on("toggle-tabbar", function(window, _)
	local overrides = window:get_config_overrides() or {}
	if overrides.enable_tab_bar == false then
		wezterm.log_info("tab bar shown")
		overrides.enable_tab_bar = true
	else
		wezterm.log_info("tab bar hidden")
		overrides.enable_tab_bar = false
	end
	window:set_config_overrides(overrides)
end)
```

and then just connect the event to a key:

```lua
config.keys = {
	{ key = "T", mods = "CTRL", action = act.EmitEvent("toggle-tabbar") },
}
```

Like this I can toggle the statusbar on and off per window with `Shift+Ctrl+T`.

For my use case I actually prefer that the default state is on and I selectively toggle it off per window.
There might be other drawbacks to this that I am not aware of, of course.
