### ISSUE TITLE
installing wezterm-nightly-bin in archlinux fails

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#464]
```
yay -Sy wezterm-nightly-bin
```

```
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/wez/wezterm/raw/master/LICENSE.md
    Aborting...
error downloading sources: wezterm-nightly-bin
```

license url should be `https://raw.githubusercontent.com/wez/wezterm/main/LICENSE.md` instead.

Might be worth create a CI task to avoid regression. You should be ale to use archlinux docker and use curl to download `yay` binaries from https://github.com/Jguer/yay/releases.  Then you should be able to do something similar to `yay -Sy wezterm-nightly-bin` and verify using `wezterm --version`.

**Comment by wez** [comment]
I've pushed a commit to the wezterm-nightly-aur that should fix this.
I don't have time to setup arch CI; I don't use arch myself so it's always high friction for me.
I'd welcome a PR that makes things better!

**Comment by prabirshrestha** [comment]
Now I get a different error. Seems like missing `.md`

```
==> Starting package()...
install: cannot stat 'LICENSE': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error making: wezterm-nightly-bin
```

**Comment by wez** [comment]
bleh.  I pushed another commit.

**Comment by prabirshrestha** [comment]
Works now. Thanks for the quickfix.
