### ISSUE TITLE
Toggle fullscreen making westerm disappear on macOS when "stage manager" feature is on

### ISSUE THREAD

**Issue by huibosa** [wez/wezterm#4642]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After update to latest macOS (Sonoma 14.1.2), I found when the "stage manager" feature is on, the wezterm window would just disappear once toggle to full screen, which only reappear after turning off the "stage manager". Both the stable release build and nightly build has the same bug.

### To Reproduce

1. Update to macOS (Sonoma 14.1.2)
2. Turn on "stage manager"
3. Open wezterm in window mode
4. Toggle full screen (OPTION + ENTER in my case)
5. wezterm disappear, even if hitting toggle key again
6. Turn off "stage manager", window reappear.

### Configuration

local wezterm = require("wezterm")

local window_padding = {
	left = "0.2cell",
	right = "0.1cell",
	top = "0.2cell",
	bottom = "0cell",
}

local mouse_bindings = {
	-- Change the default click behavior so that it only selects
	-- text and doesn't open hyperlinks
	{
		event = { Up = { streak = 1, button = "Left" } },
		mods = "NONE",
		action = wezterm.action({ CompleteSelection = "PrimarySelection" }),
	},
	-- and make CTRL-Click open hyperlinks
	{
		event = { Up = { streak = 1, button = "Left" } },
		mods = "SUPER",
		action = "OpenLinkAtMouseCursor",
	},
}

wezterm.on("toggle-ligature", function(window, _)
	local overrides = window:get_config_overrides() or {}
	if not overrides.harfbuzz_features then
		-- If we haven't overridden it yet, then override with ligatures disabled
		overrides.harfbuzz_features = { "calt=0", "clig=0", "liga=0" }
	else
		-- else we did already, and we should disable out override now
		overrides.harfbuzz_features = nil
	end
	window:set_config_overrides(overrides)
end)

local keys = {
	{ key = "=", mods = "SUPER", action = "IncreaseFontSize" },
	{ key = "-", mods = "SUPER", action = "DecreaseFontSize" },
	{ key = "0", mods = "SUPER", action = "ResetFontSize" },
	{ key = "X", mods = "SUPER|SHIFT", action = "ActivateCopyMode" },
	{ key = "N", mods = "SUPER|SHIFT", action = "SpawnWindow" },
	{ key = "Enter", mods = "ALT", action = "ToggleFullScreen" },
	{ key = " ", mods = "SUPER|SHIFT", action = "QuickSelect" },
	-- { key = "F", mods = "SUPER|SHIFT", action = wezterm.action({ Search = { CaseSensitiveString = "" } }) },
	{ key = "W", mods = "SUPER|SHIFT", action = wezterm.action({ CloseCurrentTab = { confirm = true } }) },
	{ key = "T", mods = "SUPER|SHIFT", action = wezterm.action({ SpawnTab = "CurrentPaneDomain" }) },
	{ key = "Tab", mods = "CTRL", action = wezterm.action({ ActivateTabRelative = 1 }) },
	{ key = "Tab", mods = "CTRL|SHIFT", action = wezterm.action({ ActivateTabRelative = -1 }) },
	{ key = "c", mods = "SUPER", action = wezterm.action({ CopyTo = "Clipboard" }) },
	{ key = "v", mods = "SUPER", action = wezterm.action({ PasteFrom = "Clipboard" }) },
	{ key = "E", mods = "SUPER|SHIFT", action = wezterm.action.EmitEvent("toggle-ligature") },
}

local everforest_colors = {
	foreground = "#d3c6aa",
	-- background = "#2b3339",
	background = "#272e33",
	selection_bg = "#3B5360",
	scrollbar_thumb = "#222222",
	ansi = { "#4b565c", "#e67e80", "#a7c080", "#dbbc7f", "#7fbbb3", "#d699b6", "#83c092", "#d3c6aa" },
	brights = { "#4b565c", "#e67e80", "#a7c080", "#dbbc7f", "#7fbbb3", "#d699b6", "#83c092", "#d3c6aa" },
}

local config = wezterm.config_builder()

config.window_padding = window_padding
-- window_decorations = "NONE"
config.window_background_opacity = 1.0
config.adjust_window_size_when_changing_font_size = false

config.mouse_bindings = mouse_bindings
config.disable_default_key_bindings = true
config.keys = keys

config.force_reverse_video_cursor = true
config.enable_tab_bar = false

config.colors = everforest_colors
-- config.color_scheme = "Gruvbox Material (Gogh)"
config.font = wezterm.font_with_fallback({ family = "JetBrains Mono" })
config.font_size = 14.6
config.use_ime = false

return config

**Comment by zjr** [comment]
@huibosa did you figure out a fix for this? or is it fixed in a nightly?

**Comment by huibosa** [comment]
> @huibosa did you figure out a fix for this? or is it fixed in a nightly?

Try this setting:

```

native_macos_fullscreen_mode = true

```

https://wezfurlong.org/wezterm/config/lua/config/native_macos_fullscreen_mode.html

**Comment by ryanhuanli** [comment]
> > @huibosa did you figure out a fix for this? or is it fixed in a nightly?
> 
> Try this setting:
> 
> ```
> 
> native_macos_fullscreen_mode = true
> ```
> 
> https://wezfurlong.org/wezterm/config/lua/config/native_macos_fullscreen_mode.html

I have same problem, this is not fixing the problem, simply workaround it by using macos native fullscreen mode, 
which is not really what I want, I prefer default (false) as stated right in the link:

"The default is false which will simply (and very quickly!) toggle between a window that covers the full screen, with no decorations and a regularly sized window."

**Comment by zjr** [comment]
Same here, I don’t love the native fullscreen. One thing you can try, though, is command tabbing back and forth after you go fullscreen. I noticed that if I go to another program then back to Wezterm it shows back up. A little annoying but not as annoying as native fullscreen. On Feb 27, 2024, at 5:44 PM, Ryan ***@***.***> wrote:﻿


@huibosa did you figure out a fix for this? or is it fixed in a nightly?

Try this setting:

native_macos_fullscreen_mode = true

https://wezfurlong.org/wezterm/config/lua/config/native_macos_fullscreen_mode.html

I have same problem, this is not fixing the problem, simply workaround it by using macos native fullscreen mode,
which is not really what I want, I prefer default (false) as stated right in the link:
"The default is false which will simply (and very quickly!) toggle between a window that covers the full screen, with no decorations and a regularly sized window."
