### ISSUE TITLE
how to require('wezterm') in normal lua file

### ISSUE THREAD

**Issue by front-end-captain** [wez/wezterm#4646]
**What page or section of the docs have an issue?**
Please include a link

**Describe the issue**
A clear and concise description of what you were looking for, couldn't find, or
the where things were misleading etc.

**Comment by bew** [comment]
What's your use case? 🤔
Please actually fill the issue template

**Comment by front-end-captain** [comment]
@bew Thanks for your reply. I want to change wezterm color scheme in neovim, For example, in a neovim lua configuration filefile:
`
local wezterm = require('wezterm')
local function change_scheme(args)
  local scheme = args.args
  wezterm.action.EmitEvent("toggle-colorscheme")
end

vim.api.nvim_create_user_command("ChangeScheme", change_scheme, {
  nargs = 1,
  complete = function()
    return { "foo", "bar" }
  end,
})
`

and in my wezterm config file:
`
wezterm.on("toggle-colorscheme", function(window, pane)
  local overrides = window:get_config_overrides() or {}

  overrides.color_scheme = "foo"

  window:set_config_overrides(overrides)
end)
`

**Comment by jankatins** [comment]
I don't think (never tried, no from knowledge, just my understanding how lua in wezterm works) you can use the wezterm module outside of wezterm: I think it's backed by functionality of wezterm itself and only exposed when run via wezterm.

What you might be able to do is using [user var](https://wezfurlong.org/wezterm/config/lua/pane/get_user_vars.html): E.g. I use this to pass in two variables which are then used by my format-tab-title:

```shell
__jasc_toolbox_wezterm_precmd() {
  # makes this available in the pane info of wezterm
  #printf "\e]1337;SetUserVar=%s=%s\a" in_toolbox $(echo -n ${IN_TOOLBOX} | base64)
  __wezterm_set_user_var in_toolbox ${IN_TOOLBOX};
  __wezterm_set_user_var title_symbol ${TITLE_SYMBOL};
}
autoload -U add-zsh-hook
add-zsh-hook precmd __jasc_toolbox_wezterm_precmd
```

My guess is that you could use code in your code to output that (it's hidden).

```lua
wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  local title_symbol = tab.active_pane.user_vars.title_symbol
...
end)
```

**Comment by wez** [comment]
I can confirm that the wezterm module only exists in the wezterm executables; it cannot be used from outside.
