### ISSUE TITLE
WezTerm crashes when system is suspended 

### ISSUE THREAD

**Issue by Drllap** [wez/wezterm#4652]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

wezterm 20231203-124028-e3cd2e93

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm crashes when my PC goes into sleep mode

### To Reproduce

* Start WezTerm
* Go into the terminal and execute `systemctl suspend`
* crash

### Configuration

-n

### Expected Behavior

For WezTerm not to crash

### Logs

   0: env_bootstrap::register_panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:735:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
   4: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   5: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   6: wgpu::backend::direct::Context::handle_error_fatal
   7: <wgpu::backend::direct::Context as wgpu::context::Context>::surface_get_current_texture
   8: <T as wgpu::context::DynContext>::surface_get_current_texture
   9: wgpu::Surface::get_current_texture
  10: wezterm_gui::termwindow::render::paint::<impl wezterm_gui::termwindow::TermWindow>::paint_impl
  11: wezterm_gui::termwindow::TermWindow::dispatch_window_event
  12: wezterm_gui::termwindow::TermWindow::new_window::{{closure}}::{{closure}}
  13: window::WindowEventSender::dispatch
  14: window::os::x11::window::XWindowInner::dispatch_pending_events
  15: <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop
  16: wezterm_gui::run_terminal_gui
  17: wezterm_gui::main
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: std::rt::lang_start::{{closure}}
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
      std::panicking::try
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
      std::panicking::try
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
  21: main
  22: <unknown>
  23: __libc_start_main
  24: _start

**Comment by tuanbass** [comment]
I also run into the same issue, with error information: 

```
15:48:38.620  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: get_appearance.read_setting: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
15:48:38.658  WARN   wezterm_gui::termwindow::webgpu > name=Intel(R) UHD Graphics (CML GT2), device_type=IntegratedGpu, backend=Vulkan, driver=Intel open-source Mesa driver, driver_info=Mesa 23.0.4-0ubuntu1~22.04.1, vendor=32902, device=39876 is not compatible with surface
15:48:41.840  WARN   wezterm_gui::termwindow::webgpu > name=Intel(R) UHD Graphics (CML GT2), device_type=IntegratedGpu, backend=Vulkan, driver=Intel open-source Mesa driver, driver_info=Mesa 23.0.4-0ubuntu1~22.04.1, vendor=32902, device=39876 is not compatible with surface
15:48:41.897  ERROR  wezterm_mux_server_impl::local  > writing pdu data buffer: Broken pipe (os error 32)
15:48:48.765  ERROR  env_bootstrap                   > panic at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.2/src/backend/direct.rs:778:30 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  23: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  24: <unknown>

thread 'main' panicked at 'Error in Surface::get_current_texture_view: Validation Error

Caused by:
    Parent device is lost
', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.2/src/backend/direct.rs:778:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wez** [comment]
Seems like a wgpu driver issue. Try setting `front_end = "OpenGL"`

**Comment by Drllap** [comment]
That fixes it for me, thx
