### ISSUE TITLE
`disable_default_key_bindings` does not affect some of the behaviors of Ctrl+C (keybinding appears to be hardcoded)

### ISSUE THREAD

**Issue by alxpettit** [wez/wezterm#4666]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

kwin 5.27.9

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

(Nightly is prohibitively difficult, as Wezterm does not currently have a supported Nix flake. That said, I'm reasonably confident this behavior is likely to have not changed recently.)

Ctrl+C moves the view down to the bottom of the window. Ordinarily, this is desirable behavior, as most 

### To Reproduce

1) Setup config disabling default key bindings
2) fill the terminal with test text (e.g., `for i in 0..1000 { echo $i }` if you are using Nushell)
3) scroll up and hit Ctrl+C

### Configuration

```lua
local config = {}
config.disable_default_key_bindings = true;
return config
```

### Expected Behavior

Expected Wezterm to _not react_ to Ctrl+C, when default keybindings are disabled. Ctrl+C response should be an explicit keybinding, and not hardcoded or 'invisible'.

**Comment by bew** [comment]
This behavior is not specific ti Ctrl-c, all keys will scroll to the end.
Try to set `scroll_to_bottom_on_input = false`, although it won't scroll it will still send those keys but you won't see them
ref: https://wezfurlong.org/wezterm/config/lua/config/scroll_to_bottom_on_input.html

**Comment by alxpettit** [comment]
@bew 

Woah! But Ctrl+Shift+C doesn't do it. I guess it's special behavior of the shift key, then? I should look at the code for input processing.

Also, I didn't know nushell had `seq` like Bash & Fish do. Thanks for the tip :D

**Comment by bew** [comment]
Yeah using `wezterm.action.ScrollToBottom` should do it
Ref: https://wezfurlong.org/wezterm/config/lua/keyassignment/ScrollToBottom.html

**Comment by alxpettit** [comment]
Oh, awesome! Is there a way of binding some code to a keybinding _without_ intercepting the keybinding? When I do `{ key = 'q', mods = 'CTRL', action = act.ScrollToBottom },` it eats Ctrl+Q and the terminal stack can't respond to the keypress.

**Comment by bew** [comment]
Well the simplest solution here would be to use a `act.Multiple` action, to call `act.ScrollToBottom` then `act.SendKey` with the key you want to send.

Check these additional docs:
- https://wezfurlong.org/wezterm/config/lua/keyassignment/Multiple.html
- https://wezfurlong.org/wezterm/config/lua/keyassignment/SendKey.html

**Comment by alxpettit** [comment]
`{ key = 'q', mods = 'CTRL', action = act.Multiple { act.ScrollToBottom, act.SendKey { key = 'q', mods = 'CTRL' } } }` worked, thanks! :)
