### ISSUE TITLE
Geist Mono Variable font not working properly

### ISSUE THREAD

**Issue by TiLopes** [wez/wezterm#4668]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With the following font: [Geist Mono Variable](https://vercel.com/font/mono)

The font weight is broken. By default it should choose Regular however it renders as Thin, to get near the Regular weight even ExtraBlack is not enough.

Wezterm:
![image](https://github.com/wez/wezterm/assets/106965010/9101b8b6-6643-49e4-8c40-77280261d3ab)

Windows Terminal:
![image](https://github.com/wez/wezterm/assets/106965010/27c410e9-48c2-4627-9063-9078f573c611)

### To Reproduce

Set Geist Mono Variable font.

### Configuration

config.font = wezterm.font("Geist Mono Variable")

### Expected Behavior

The font should have the regular weight.

**Comment by wez** [comment]
What does `wezterm ls-fonts` output?

**Comment by TiLopes** [comment]
The font maker has fixed the problem. It was an issue on their end as it happened in other programs as well.
