### ISSUE TITLE
Cant start under hyprland v0.33

### ISSUE THREAD

**Issue by Keloran** [wez/wezterm#4672]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland 0.33

### WezTerm version

2030712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Cant launch at all

### To Reproduce

> wezterm

### Configuration

local wezterm = require 'wezterm'

local config = {
  color_scheme = 'Dracula',
  font_size = 9.0,
  automatically_reload_config = true,
  hide_tab_bar_if_only_one_tab = true,
  enable_scroll_bar = true,
  max_fps = 120,

  window_frame = {
    font_size = 10.0
  },

  keys = {
    {
      key = 'w',
      mods = 'CMD',
      action = wezterm.action.CloseCurrentPane {
        confirm = false
      }
    }
  }
}

-- if wezterm.config_builder then
--   config = wezterm.config_builder()
-- end

return config

### Expected Behavior

wezterm launches

### Logs

> wezterm                                                                                                              

interface 'wl_surface' has no event 2
09:50:40.990  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating
warning: queue 0x562a0ccdf9d0 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190085 still attached
  zwp_primary_selection_offer_v1@4278190084 still attached
  zwp_primary_selection_offer_v1@4278190083 still attached
  zwp_primary_selection_offer_v1@4278190082 still attached
  wl_data_offer@4278190081 still attached
  wl_data_offer@4278190080 still attached
  wl_callback@34 still attached
  xdg_wm_base@22 still attached
  wl_surface@21 still attached
  wl_data_device@18 still attached
  wl_pointer@16 still attached
  zwp_text_input_v3@15 still attached
  wl_keyboard@14 still attached
  zwp_primary_selection_device_v1@13 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@12 still attached
  wl_output@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

**Comment by woojiq** [comment]
https://github.com/wez/wezterm/issues/4483

**Comment by Keloran** [comment]
yeah this is fixed in the latest commit
