### ISSUE TITLE
add a marker to indicate the "current tab is in pane maximized" state.

### ISSUE THREAD

**Issue by daishengdong** [wez/wezterm#4676]
When triggering TogglePaneZoomState to maximize the current pane in Wezterm, there are no indicators to show that the current tab is in a state where "a pane is maximized". 

This can be confusing at times, making it seem as though there is only one pane open in the current tab. 

It is suggested to add a status indicator on the tab itself. 

A practical suggestion would be to prepend a characteristic character to the current tab's name, similar to how in my tmux setup, a tab name would include "*Z" to denote such a state:
![image](https://github.com/wez/wezterm/assets/4813738/dee9cbeb-c74f-4f41-a539-aad121761386)

**Comment by Danielkonge** [comment]
You can already set something like this up. For example I have a `+` to indicate zoom state via the following code:

```lua
function tab_bar.on_format_tab_title(tab, _tabs, _panes, _config, _hover, _max_width)
    local zoomed = ''
    local index = tab.tab_index + 1
    local title = tab_title(tab)
    if tab.active_pane.is_zoomed then
        zoomed = '+'
    end
    return {
        { Text = string.format(' %d %s%s ', index, title, zoomed) }
    }
end

wezterm.on('format-tab-title', tab_bar.on_format_tab_title)
```

**Comment by daishengdong** [comment]
@Danielkonge 
hi, the configuration you provided does indeed result in the expected changes to the tab's title in the given scenario, but it also introduces a new issue.

I have adopted the method from https://github.com/wez/wezterm/issues/522 to set up a shortcut key for renaming tabs. I've found that with your configuration in place, I am unable to complete the action of renaming a tab; in other words, after I attempt to rename it, the tab's title remains unchanged:
![image](https://github.com/wez/wezterm/assets/4813738/c52af4ad-ce38-40a2-b85d-1c4756e1ccba)
![image](https://github.com/wez/wezterm/assets/4813738/f8764d8b-ea3c-4097-8a2b-8653737e1776)
![image](https://github.com/wez/wezterm/assets/4813738/18e220e7-aa8c-4aea-bb18-6928b91ce8ba)


I tried modifying your configuration as follows, only to discover that the effect of appending a "+" to the tab's title no longer works, and the tab can once again be renamed normally:
![image](https://github.com/wez/wezterm/assets/4813738/1a33dabe-147c-4f9c-be9a-c836eb623d4d)

As I'm not very familiar with WezTerm's API yet, could you help analyze what might be the problem?

**Comment by Danielkonge** [comment]
> I have adopted the method from #522 to set up a shortcut key for renaming tabs. I've found that with your configuration in place, I am unable to complete the action of renaming a tab; in other words, after I attempt to rename it, the tab's title remains unchanged

I actually simplified my setup because I thought not a lot of people used the tab renaming. Here is what I have for myself:

```lua
-- This function returns the suggested title for a tab.
-- It prefers the title that was set via `tab:set_title()`
-- or `wezterm cli set-tab-title`, but falls back to the
-- title of the active pane in that tab.
local function tab_title(tab_info)
    local title = tab_info.tab_title
    -- if the tab title is explicitly set, take that
    if title and #title > 0 then
        return title
    end
    -- Otherwise, use the title from the active pane
    -- in that tab
    return tab_info.active_pane.title
end

function tab_bar.on_format_tab_title(tab, _tabs, _panes, _config, _hover, _max_width)
    local zoomed = ''
    local index = tab.tab_index + 1
    local title = tab_title(tab)
    if tab.active_pane.is_zoomed then
        zoomed = '+'
    end
    return {
        { Text = string.format(' %d %s%s ', index, title, zoomed) }
    }
end

wezterm.on('format-tab-title', tab_bar.on_format_tab_title)
```
Does this work as you expected with the tab naming? (This is similar to what you can find here: https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html)

> I tried modifying your configuration as follows, only to discover that the effect of appending a "+" to the tab's title no longer works, and the tab can once again be renamed normally: ![image](https://private-user-images.githubusercontent.com/4813738/290707715-1a33dabe-147c-4f9c-be9a-c836eb623d4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDAzMzgsIm5iZiI6MTcwMjY0MDAzOCwicGF0aCI6Ii80ODEzNzM4LzI5MDcwNzcxNS0xYTMzZGFiZS0xNDdjLTRmOWMtYmU5YS1jODM2ZWI2MjNkNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTEzMzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQ2NWJjYWE1OGRjZjdiNWFmZDY5MGUwOWI5Y2FiMTc5MWM2MzQ2NjRhNmExNzBmMThhOGFhN2EzNGEzNzU4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N0APVTkakIQJuveOUnWm4ZDCWX3O60R9HFzR2I3EWps)
> 
> As I'm not very familiar with WezTerm's API yet, could you help analyze what might be the problem?

I think you want `tab.tab_title` and not `tab.title`, see: https://wezfurlong.org/wezterm/config/lua/TabInformation.html

In general the function used in `wezterm.on('format-tab-title', <function>)` is described here: https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html

You can then check what information you have available in each of the objects listed on that page to write your function.

**Comment by daishengdong** [comment]
@Danielkonge 
Thank you so much! After adopting your "complete form" patch, everything goes according to my expectations!

**Comment by wez** [comment]
FWIW, the default *window* title does get updated with a [Z] marker when a pane in the current tab is zoomed:
<img width="152" alt="image" src="https://github.com/wez/wezterm/assets/117777/a4e9278f-06ea-4327-bfee-9819a1f5034b">

This doesn't happen in the tab title because those are more space constrained.

https://wezfurlong.org/wezterm/config/lua/window-events/format-window-title.html shows the equivalent logic to the default window title.

As Danielkonge has shown above, you can script adding it to the tab for yourself if you wish.

**Comment by reverendpaco** [comment]
Just wanted to show another technique for this that I've adopted that uses the _right status_, which I find a bit more "in your face" -- a quality I wanted for myself. YMMV.

```lua
wezterm.on("update-status", function(window, pane)
    local our_tab = pane:tab()
    local is_zoomed = false
    if our_tab ~= nil then
        for _, pane_attributes in pairs(our_tab:panes_with_info()) do
            is_zoomed = pane_attributes['is_zoomed'] or is_zoomed
        end
    end
    if is_zoomed then
        window:set_right_status(wezterm.format {
            {Attribute = {Underline = 'Single'}}, {Attribute = {Italic = true}},
            { Background = { Color = 'hsla(0, 0, 0, .05)'}},
            { Foreground = { Color = 'yellow'}},
            {Text = ' 🌀 Zoomed 🍁         '}
        })
        -- the below assumes you have written a handler that forces tabs to be open
        -- I do this aggressively to force my UI to remind me that I am zoomed
        wezterm.emit("force-tabs-shown", window, pane)
    else
        window:set_right_status("")
    end

   --- whatever else you want to do with your update-status
end
```

<img width="714" alt="image" src="https://github.com/wez/wezterm/assets/273927/a14900d3-e538-4e31-875b-050610abed56">

**Comment by wez** [comment]
Thanks folks; I'm going to close this as I don't think there is something that needs to be changed in wezterm itself to accommodate this!
