### ISSUE TITLE
built-in "global summon" feature

### ISSUE THREAD

**Issue by daishengdong** [wez/wezterm#4679]
In Tabby, you can set a "global summon" hotkey (such as ctrl + space), which means that no matter which window you are currently in, pressing the hotkey will immediately switch the focus back to Tabby.

It seems that Wezterm does not have this feature, and although I can replicate this functionality on Windows using third-party tools like AutoHotkey, having it as a built-in feature would be more user-friendly.

**Comment by wez** [comment]
Essentially a duplicate of https://github.com/wez/wezterm/issues/1751
