### ISSUE TITLE
Using 'wezterm ssh', new tab button & actions are inconsistent

### ISSUE THREAD

**Issue by bew** [wez/wezterm#468]
## Describe the bug

Using `wezterm ssh user@host -- some-command`, on the new window (after login):

- left click on new tab button connects to the server, BUT does not run `some-command` again
- in the launch menu, clicking on a local entry (not on the remote server) does not work: the tab opens then immediately closes, no error message in the log (except a `setenv WEZTERM_PANE=N failed` but I also have it on the normal

See section `To Reproduce` section for details

## Environment (please complete the following information):

 - OS: Windows
 - Version: `20210203-095643-70a364eb-24-g005b492a` (latest nightly at time of writing)

## Configuration

```lua
local wezterm = require("wezterm")
local config = {}
local msys2_start_args = {
    "C:\\some\\path\\to\\msys2_install\\usr\\bin\\env.exe",
    "MSYS=enable_pcon", -- Enable pseudo console API for msys (maybe not needed under wezterm?)
    "MSYSTEM=MSYS",
    "/bin/bash", "--login",
}
config.default_prog = msys2_start_args
config.launch_menu = {
    {
      label = "msys2 bash",
      args = msys2_start_args,
    },
    {
      label = "DevVM via some server",
      args = {
          wezterm.executable_dir .. "/wezterm",
          "ssh", "my-user@some-server", "--", "vim", -- run vim for the example
      },
    },
}
return config
```

## To Reproduce

(init 1) Open wezterm, will launch the default local prog (msys2's bash in this case).
(init 2) With the launch menu (right click on new tab), select entry `DevVM via some server`, this opens the ssh session to the remote server (and login). Then **vim is automatically started**.

Now on the new window (ssh session):

1. left click on new tab, a new tab opens, it connects to the remote server, BUT **does _not_ run vim automatically**.
2. right click on new tab, select entry `msys2 bash`, a new tab opens, then immediately closes, no special error message.. I think it tries to connect to the ssh session and run the command there.. Is it intentional?
3. right click on new tab, select entry `DevVM via some server`, same behavior: new tab opens then immediately closes.
4. right click on new tab, select entry ``New Tab (domain `SSH to my-user@some-server`)`` (I guess it is the default behavior of left click on new tab?): **does absolutely nothing**.

## Expected behavior

Step 1:  vim should be started automatically, or I should be able to configure what the default 'new tab' action does (which can be to run the same command)

Step 2 & 3 (& 4 ?): by default the commands should not be sent to the remote server, it doesn't make sense IMO.
The idea is good, but there should be maybe a separate section of program launchers, that would run on the same domain as the current one?

**Comment by wez** [comment]
When you run `wezterm ssh`, wezterm runs in a mode where the default domain is set to an ad-hoc ssh client domain, rather than a domain that spawns commands locally.

In the launch menu, the SpawnCommand objects default to `domain = "CurrentPaneDomain"` which will generally be that ssh domain (unless you've attached some other domain and activated that).

What that means is that your "wezterm ssh ..." command is executed in the context of the remote ssh session, rather than on your local machine.  Since there is no way to forward the X11 display (and that is impossible with Wayland in any case), you'll never see the wezterm gui program open.

I think it's a reasonable request to make these ad-hoc ssh domains a bit easier to mix and match with local domains; then you'd be able to specify `domain = "local"` in that entry to have it work, but right now, there isn't a `local` domain when started in ssh mode.

**Comment by wez** [comment]
PS: `exit_behavior = "CloseOnCleanExit"` can make it easier to troubleshoot rapidly exiting programs!  I think I should make that the default!

**Comment by bew** [comment]
That's what I suspected, thank you for the details.
I see this behavior / issue also when opening links, it doesn't work when using `wezterm ssh` probably due to the same reason

**Comment by bew** [comment]
FTR, message from @wez related to this issue on Matrix tchat:
https://matrix.to/#/!PirwUBcuIlTXwNveYz:matrix.org/$D4itvPFLKP_bPVgjekH_jSOBSv3QaXwAg_NwN5bo6B8?via=matrix.org

> what I(wez)'ve got in mind is:
> - Improve the ssh2/pty mappings that we have currently because there are some potential issues with multiple channels being active at once
> - When starting wezterm in ssh or serial mode, also always start a local domain
>
>   This would make it so that you could explicitly spawn local commands rather than in the remote ssh domain of the active pane.  That was part of problem on the issue that you raised: it was trying to run the wezterm gui on the remote host
>
> - Allow dynamically starting a new ssh domain so that you can start one even when not running in ssh mode (both via key assignments, and via the cli)
> - Do something smart with the Pane that is setup by the ssh domain so that it can run a little termwiz app to manage prompting and show connection status rather than popping up a separate window for that. Once the session is connected, the termwiz applet thingy would get out of the way and you'd just be talking to the ssh session

**Comment by wez** [comment]
In the nightly builds, you can now do:

```
```lua
return {
  launch_menu = {
    {
      label = "Ssh somewhere",
      args = {wezterm.executable_dir .. "/wezterm", "ssh", "somewhere"},
      domain = {DomainName="local"},
    },
  }
}
```

**Comment by bew** [comment]
Using `domain = {DomainName="local"}` on my launch items works great, I tested all combinations I could think of based on the my initial post, this is now resolved in nightly 😃

**Comment by bew** [comment]
Hmm I'm thinking about link opening, could you make it work locally always?
I don't see a usecase for link opening to be run on the ssh domain and not locally: the browser is mostly local, not remote!
And if needed, custom logic can be done with `open-uri` event to open a remote terminal-ui browser like w3m or others.

What do you think?

**Comment by wez** [comment]
What do you mean by link opening? Clicking on hyperlinks?  That is always local.  What are you trying and seeing?

**Comment by bew** [comment]
You're right, I forgot that if the application enables mouse reporting I have to use shift...
I'd really like to bypass this.. My link mouse-binding is Ctrl-Click, and I don't use that anywhere in my programs.
I'd welcome a new option on mous bindings to bypass mouse reporting and always do the wezterm action.

NOTE: this has nothing to do with this issue about ssh & tabs, I'll make a new one for this.
