### ISSUE TITLE
Seemingly unable to use bitmap font instead of Nerd Font

### ISSUE THREAD

**Issue by korbough** [wez/wezterm#4688]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin

### WezTerm version

20231203-124028-e3cd2e93

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I try to use Cozette in Wezterm, it seems to favor the built-in Nerd Font symbols instead of the ones in Cozette, seemingly at random (see image).

### To Reproduce

1. Install Cozette font
2. Set font to Cozette in Wezterm
3. Display characters U+E0B6 and U+F303, the arch logo will be pixelated (like in Cozette), unlike the semi-circle.

### Configuration

```lua
font = wezterm.font_with_fallback {"CozetteHiDpi", "Twitter Color Emoji"},
```

### Expected Behavior

Both the Arch logo and the semi-circle should be in the Cozette font.

### Logs

```
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
```

### Anything else?

![image](https://github.com/wez/wezterm/assets/47117026/6ca4e8a7-6ac4-4f0b-bb37-a0899da60e4e)

**Comment by piec** [comment]
Hi @korbough, can this issue help you https://github.com/wez/wezterm/issues/4256?

**Comment by korbough** [comment]
No, it definitely loads the font, because everything else is Cozette (see screenshot, arch logo is pixelated).

**Comment by korbough** [comment]
Update: it has to be something with WezTerm, it seems to render Nerd Font characters with Cozette in every other program.

**Comment by wez** [comment]
There's not enough detail here to understand or reproduce this issue; I don't understand what you are trying, what your expectations are, or what the outcome is.

I would suggest that you try running `wezterm ls-fonts --text "something"` to get wezterm to show how "something" will render. Replace "something" with the text you're actually trying to render, or if you know the codepoints, you can use the `--codepoints` flag instead.  See `wezterm ls-fonts --help` for more info.

**Comment by korbough** [comment]
Turns out i needed to look more closely, setting `custom_block_glyphs` to `true` makes everything work! Sorry for being a bit hard to understand.
