### ISSUE TITLE
Provide an API to change the window icon

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#4696]
**Is your feature request related to a problem? Please describe.**
I run *Neovim* in a *WezTerm* window. This shows the *WezTerm* icon.

**Describe the solution you'd like**
It'll be great to have an API to change the window icon, so I can change it to that of *Neovim*'s.

**Describe alternatives you've considered**
I tried the following in *X11*, but it didn't do anything, despite it saying that the window icon got changed:

```python
>>> from ewmh import EWMH
... 
... ewmh = EWMH()
... # Code to find the window
... nvim_window = ...
... nvim_window.set_wm_icon_name('nvim')
... nvim_window.get_wm_icon_name()
'nvim'
```

**Additional context**

**Comment by wez** [comment]
This stuff is made complicated by the various different window environments:

* X11 - supports per-window icon information in the protocol, but some environments ignore this and use either an icon based on the window class, or based on the .desktop file that spawned it
* Wayland - icons are derived from the application name/class and/or .desktop file
* Windows - icon is compiled into the binary. There may be a way to report a different icon through windows messages or COM or something
* macOS - icon is defined by the application plist file and there is no API for changing this dynamically

So there's no guaranteed way to manipulate the icon programmatically in any of these environments.
If there was such a thing, it would enable https://github.com/wez/wezterm/discussions/2396#discussioncomment-6441691

**Comment by stevenxxiu** [comment]
Thanks for the reply. Seems like it's not always possible, so I'll close this issue.
