### ISSUE TITLE
Gnome shell crashes on opening wezterm with wezterms fancy tab bar disabled

### ISSUE THREAD

**Issue by dani162** [wez/wezterm#4701]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20231218_012406_4f97ff8f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

My Gnome shell crashes every time I open the "WezTerminal" on my primary 3840x2160 monitor with the following configuration wezterm configuration (fancy tab bar disabled).
My Primary Monitor has fractional Scaling enabled (150%)
If Wezterm opens on my secondary monitor it just works fine (100%) 1920x1080

I created a bug on the mutter side, but their is probably also an bug in wezterm (see: https://gitlab.gnome.org/GNOME/mutter/-/issues/3211)

### To Reproduce

1. Setting use_fancy_tab_bar to false (see above)
(2. Close Wezterm if open)
3. Opening Wezterm on Monitor with 150% Scaling
3. Crash - Thrown on login screen

### Configuration

```lua
local wezterm = require("wezterm")
local config = {}
if wezterm.config_builder then
	config = wezterm.config_builder()
end
config.use_fancy_tab_bar = false
return config
```

### Expected Behavior

Should not crash

### Anything else?

gdb of the gnome shell crash - idk if this is helpful or not
[gdb.txt](https://github.com/wez/wezterm/files/13718826/gdb.txt)

**Comment by dani162** [comment]
Maybe related to https://github.com/wez/wezterm/issues/4510 ?

**Comment by cstrahan** [comment]
Response from https://gitlab.gnome.org/GNOME/mutter/-/issues/3211:


>[Michel Dänzer](https://gitlab.gnome.org/daenzer) [@daenzer](https://gitlab.gnome.org/daenzer):
>
>[!3463 (merged)](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3463) should fix this.
>
>Note that it was triggered by a client-side bug, which should be reported there. With the fix, wezterm may die due to a Wayland protocol error with the same reproduction steps.


>[dani162](https://gitlab.gnome.org/dani162):
>
>https://github.com/wez/wezterm/issues/4701


>[Charles Strahan](https://gitlab.gnome.org/cstrahan) [@cstrahan](https://gitlab.gnome.org/cstrahan) 
>> Note that it was triggered by a client-side bug
>
>[@daenzer](https://gitlab.gnome.org/daenzer) Could you provide some details, even if brief/high level? I'd be happy to relate the details to Wez, if I knew what to share.

>[Michel Dänzer](https://gitlab.gnome.org/daenzer) [@daenzer](https://gitlab.gnome.org/daenzer):
>
>The protocol spec says that the width & height of the wl_buffer attached to a wl_surface must be a multiple of the buffer scale set via wl_surface_set_buffer_scale. (Even if the buffer scale is changed without attaching a new buffer)

**Comment by flexagoon** [comment]
I'm having the same issue. Setting `config.front_end = "OpenGL"` fixes it for me, but it does seem to introduce some minor visual artifacts when opening or resizing wezterm.

**Comment by jayadamsmorgan** [comment]
Having the same issue here too, I noticed it only happens to me when I am not connected to the internet, not sure how it might work this way... (latest nightly + 6.6.0-1003-apple-arm kernel)

**Comment by flexagoon** [comment]
@dani162 seems like the issue is now fixed on GNOME's side. I tried removing the `front_end` setting from my config and Gnome Shell no longer crashes.

**Comment by dani162** [comment]
Seems to be working properly now, don't see any further problems from the Wezterm side.
I am using the current release `wezterm 20240203-110809-5046fc22` on `GNOME Shell 45.4`
