### ISSUE TITLE
Sudden crash on MacOS

### ISSUE THREAD

**Issue by crides** [wez/wezterm#4702]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20231003-071306-0700a6b1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

A sudden crash. I'm not sure what is the problem, but this session does have a large number of tabs (>15) and panes (>60 probably), and a lot of panes do have a lot of output history. I don't have much to provide other than the log dumped by Mac below

### Configuration

https://github.com/crides/dotfiles/blob/master/config/wezterm/wezterm.lua

### Logs

[wezterm-crash.log](https://github.com/wez/wezterm/files/13721048/wezterm-crash.log)

**Comment by wez** [comment]
If you can get it to reproduce then I'd suggest building a debug build and looking into this some more, but otherwise, there's not a huge amount to go on here; the crash log isn't super useful for a release build.
