### ISSUE TITLE
Pane disappears unprompted after 15 minutes

### ISSUE THREAD

**Issue by jasperandrew** [wez/wezterm#4705]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

According to the output of `wmctrl -m`, it is "GNOME Shell"

### WezTerm version

20231203-124028-e3cd2e93

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After precisely 15 minutes, the first (0th) pane disappears without any other prompting.

### To Reproduce

- Open wezterm
- Wait 15 minutes

### Configuration

no config

### Expected Behavior

The pane does not go away unprompted after 15 minutes

### Logs

Debug Overlay
```
wezterm version: 20231203-124028-e3cd2e93 x86_64-unknown-linux-gnu
Window Environment: Wayland
WebGPU: name=Intel(R) Graphics (RPL-S), device_type=IntegratedGpu, backend=Vulkan, driver=Intel open-source Mesa driver, driver_info=Mesa 23.0.4-0ubuntu1~22.04.1, vendor=32902, device=42888
```

Seemingly Relevant Debug Log Output
```
09:55:49.810  DEBUG  config > Reloaded configuration! generation=1
09:55:49.811  DEBUG  window::os::wayland::inputhandler > created ZwpTextInputV3 25 1
09:55:49.811  DEBUG  window::os::x_and_wayland         > Using wayland connection!
09:55:49.815  DEBUG  config                            > Reloaded configuration! generation=2
09:55:49.824  DEBUG  wezterm_gui::frontend             > workspace is default, fixup windows
09:55:49.831  DEBUG  wezterm_font::ftwrap              > set_char_size computing 12 dpi=96 (pixel height=16)
09:55:49.836  DEBUG  wezterm_font::ftwrap              > set_char_size computing 12 dpi=96 (pixel height=16)
09:55:49.836  DEBUG  window::os::wayland::output       > zwlr_head_info: {}
...
10:10:49.911  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Mode(ResetDecPrivateMode(Code(BracketedPaste))))
10:10:49.912  DEBUG  wezterm_term::terminalstate::performer > perform Control(CarriageReturn)
10:10:49.912  DEBUG  mux                                    > removing pane 0
10:10:49.912  DEBUG  mux                                    > killing pane 0
10:10:49.912  DEBUG  wezterm_term::terminalstate::performer > perform Control(Bell)
10:10:49.912  DEBUG  mux::localpane                         > killing process in pane 0, state is Running { child_waiter: Receiver { .. }, pid: Some(253053), signaller: ProcessSignaller { pid: Some(253053) }, killed: false }
10:10:49.912  DEBUG  mux::localpane                         > child terminated, new state is Dead
10:10:49.912  DEBUG  wezterm_term::terminalstate::performer > perform PrintString("timed out waiting for input: auto-logout")
10:10:49.912  DEBUG  mux                                    > remove_tab_internal tab 0
10:10:49.912  DEBUG  wezterm_term::terminalstate::performer > perform Control(CarriageReturn)
10:10:49.912  DEBUG  wezterm_term::terminalstate::performer > perform Control(LineFeed)
10:10:49.912  DEBUG  mux                                    > panes to remove: []
10:10:49.912  DEBUG  mux                                    > remove_window_internal 0
10:10:49.912  DEBUG  mux                                    > removing pane 0
10:10:49.913  DEBUG  wezterm_gui::frontend                  > workspace is default, fixup windows
10:10:49.913  DEBUG  wezterm_gui::frontend                  > workspace is default, fixup windows
```

Complete Debug Log Output
[wezterm-gui-log-253049.txt](https://github.com/wez/wezterm/files/13729098/wezterm-gui-log-253049.txt)

**Comment by jasperandrew** [comment]
> Do you have the `TMOUT` variable set in your shell?
> 
> ref: [cyberciti.biz/faq/linux-tmout-shell-autologout-variable](https://www.cyberciti.biz/faq/linux-tmout-shell-autologout-variable/)

Well, that's interesting. It's not set when I open GNOME Terminal, but when I open wezterm it is set to 900.

**Comment by jasperandrew** [comment]
I found the source of the TMOUT, it's a work computer so there's a centrally-managed `/etc/profile` that sets it. I'm not a linux expert, is there a particular reason that wezterm uses `/etc/profile` when GNOME Terminal doesn't?

**Comment by bew** [comment]
Yes it's expected, and documented in:
https://wezfurlong.org/wezterm/config/launch.html#launching-programs

Either you launch it like you said, another option is to simply override the value with `TMOUT=0` (or `unset TMOUT` if you're confident nothing will force-enable it again if unset)

**Comment by jasperandrew** [comment]
Gotcha. Thanks for the help! Closing issue.
