### ISSUE TITLE
Wrapped long line copy under tmux

### ISSUE THREAD

**Issue by piec** [wez/wezterm#4706]
First thank you for your work on wezterm which I find great and full of features.

**Is your feature request related to a problem? Please describe.**
When using tmux in wezterm, wezterm interprets long wrapped lines as multiple lines (of terminal width length) instead of a single wrapped line.
This means that:
* If I tripple click a particular block of text it will only select a single line (not a issue to me, but it helps to understand the situation). I am not using semantic prompt.
* If I copy/paste a long wrapped line, it will be pasted wrapped as rendered in wezterm.

Triple click in wezterm without tmux - OK:
![image](https://github.com/wez/wezterm/assets/781471/bd5d7065-8df0-4939-a106-3d5cb3b357a5)
Triple click (or [shift]+triple click if you use tmux with mouse support on) - BAD:
![image](https://github.com/wez/wezterm/assets/781471/4c5f08c0-8285-4c9f-80cd-993bf749d62a)

![image](https://github.com/wez/wezterm/assets/781471/676947ce-8989-4754-9a71-28a7a4817301)

I suppose it's related to how tmux renders these lines on screen and how wezterm interprets them. I have looked for options in tmux to configure its behavior related to newlines but didn't find anything.

**Describe the solution you'd like**
Have the selection and copy-paste work the same when in tmux.
Many terminals work as I expected with tmux (triple click and copy/paster): uxterm, gnome-terminal, alacritty. 

**Describe alternatives you've considered**
Use tmux copy/paste support with mouse, for example with https://github.com/tmux-plugins/tmux-yank. But it's not always practical.

**Additional context**
* wezterm uses `TERM=xterm-256color`
* wezterm 20230712-072601-f4abf8fd
* tmux 3.3a
* Default conf for bash and tmux
* Arch Linux

**Comment by wez** [comment]
tmux outputs several disconnected lines, so wezterm doesn't know that they are a single logical line.
This will not be solved in wezterm.

Note that wezterm has native UI for tabs and panes and has many of the same features as tmux.
