### ISSUE TITLE
portable-pty doesn't report EOF when the proccess is exit, which cause reader thread never returned.

### ISSUE THREAD

**Issue by Tnze** [wez/wezterm#4718]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

None

### WezTerm version

None, I'm using portable-pty directly

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I expect the `reader` object returning an `EOF` error when calling the `read()` method, when the process is alread exit.

### To Reproduce

```rust
use std::io::Write;

use portable_pty::{native_pty_system, CommandBuilder, PtySize};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let pty_system = native_pty_system();

    let pair = pty_system.openpty(PtySize {
        rows: 24,
        cols: 80,
        pixel_width: 0,
        pixel_height: 0,
    })?;

    let cmd = CommandBuilder::new("powershell.exe");
    let _child = pair.slave.spawn_command(cmd)?;

    let mut reader = pair.master.try_clone_reader()?;
    writeln!(pair.master.take_writer()?, "exit\r\n")?;

    let mut buf = [0u8; 1024];
    loop {
        let n = reader.read(&mut buf)?;
        std::io::stdout().write_all(&buf[..n])?;
    }
}
```

In this code, the `exit` command for powershell is issued. So the `powershell.exe` will exit. And the loop should quit. But actually this program hangs up.

### Configuration

no config

### Expected Behavior

Reading from an exited child returning an EOF error.

**Comment by MCOfficer** [comment]
Same problem here. It seems like ReadFile is blocking indefinitely:

https://github.com/wez/wezterm/blob/ff2743748c238e5cdd6e7cb4ed19517d08dd511f/filedescriptor/src/windows.rs#L352-L360

This is really where my windows-fu ends, but google spits out a surprising number of results: https://stackoverflow.com/questions/593175/breaking-readfile-blocking-named-pipe-windows-api

---

Anyways, in the meantime, here's a terrible, terrible workaround:

```rust
   let pty_system = native_pty_system();

    let pair = pty_system.openpty(PtySize {
        rows: 24,
        cols: 80,
        pixel_width: 0,
        pixel_height: 0,
    })?;

    let cmd = CommandBuilder::new("powershell.exe");
    let mut child = pair.slave.spawn_command(cmd)?;

    let mut reader = pair.master.try_clone_reader()?;
    writeln!(
        pair.master.take_writer()?,
        "start-sleep -seconds 3;\r\nexit\r\n"
    )?;

    // Only read 1 byte at a time, just to be sure
    let mut buf = [0u8; 1];
    loop {
        thread::sleep(Duration::from_millis(1));
        // After every byte, check the exit code. The thread::sleep makes 
        // it *likely* that we catch the exit code before the pipe stalls
        // (but deadlocks are still theoretically possible)
        if child.try_wait()?.is_some() {
            break;
        }
        let n = reader.read(&mut buf)?;
        std::io::stdout().write_all(&buf[..n])?;
    }

    Ok(())
```

Since this stops reading as soon as our child process is done, you will likely lose your last line(s) of output. You can pevent this by finishing any commands with a `start-sleep -seconds 1` or similar.

**Comment by MCOfficer** [comment]
Thanks for your reply, I had in fact missed that. Unfortunately, properly dropping the slave doesn't seem to fix @Tnze 's example, it's still stalling on my system.

Code for postery:

```rs
#[test]
fn test_portable_pty() -> Result<(), Box<dyn std::error::Error>> {
    let pty_system = native_pty_system();

    let pair = pty_system.openpty(PtySize {
        rows: 24,
        cols: 80,
        pixel_width: 0,
        pixel_height: 0,
    })?;

    let cmd = CommandBuilder::new("powershell.exe");
    let _child = pair.slave.spawn_command(cmd)?;
    drop(pair.slave);

    let mut reader = pair.master.try_clone_reader()?;
    writeln!(pair.master.take_writer()?, "exit\r\n")?;

    let mut buf = [0u8; 1024];
    loop {
        let n = reader.read(&mut buf)?;
        std::io::stdout().write_all(&buf[..n])?;
    }
}
```

Just in case, i also tried explicitly dropping the writer as soon as possible (after `writeln!`), because the example puts it into a scope of its own. No luck :/

**Comment by Tnze** [comment]
> Unfortunately, properly dropping the slave doesn't seem to fix @Tnze 's example, it's still stalling on my system.

@MCOfficer 
After learning the document of `std::io::Read`, the reason why my example doesn't exit is that the `read()` method doesn't report an EOF as an `Err` but `Ok(0)`. So we need to check if the `n` equals `0` after read is performed.

@wez 
Thanks for answering. I tested the solution, it turns out that is required to drop the entire `pair` (or separately drop both slave and master) for receiving the EOF. My problem is solved but I want to ensure if this behavior is intended.

**Comment by wez** [comment]
> ... if this behavior is intended.

it's how that particular OS behaves; it's not something that the pty crate can control directly, at least, not without building a much heavier weight abstraction that might introduce other issues.

So, yes, you can expect to have to take great care with the ownership and order of operations on the various handles associated with a pty.

I'm sorry that this isn't easier and less of a headache, but that is how this stuff works :-/
