### ISSUE TITLE
Can I get a Ctrl-[ in the Launcher to close it ?

### ISSUE THREAD

**Issue by aristidebm** [wez/wezterm#4722]
**Describe the solution you'd like**

First of all, I want to thank you a lot for all you are doing, you have produced an amazing piece of software.

Since Escape key is located far from the homerow in tarditional keyboard, I used to hit <Ctrl-[> to produce the same result as Escape key, it works often by default in lots of apps that I use, if it doesn't I almost always have the possibility
to bind <Ctrl-[> to what I want, but it seems not to work with wezterm.

 I looked for a way in the documentation to bind <Ctrl-[> to close the launcher, but I found nothing in that direction, when I hit <Ctrl-[> in the launcher, it produced <[>.

In the mean time, can you please add the possiblity to close the launcher using <Ctrl-[> ? It will be nice if there is an action lets say \<CloseLauncher\> that we can bind keys to to close the launcher. Is that even possible ? Excuse my english, I am not a native speacker ?

**Describe alternatives you've considered**

Currently I am hitting either Escape or <Crl-g> as mention in this related issue https://github.com/wez/wezterm/issues/1977
but it doesn't fill natural and I don't want to rebind my escape to capslock, my capslock is already used as MultiKey.

**Comment by wez** [comment]
This is implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by aristidebm** [comment]
Thanks a lot wez.
