### ISSUE TITLE
Remapping Cmd + K is not reflected on Command Palette

### ISSUE THREAD

**Issue by codingskynet** [wez/wezterm#4724]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20231221-214626-84ae00c8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Remapping Cmd + k does not remove command palettes default mapping 'Clear Scrollback'.
<img width="1046" alt="image" src="https://github.com/wez/wezterm/assets/8104782/305233dd-f4ed-4b24-8ec5-a645f6cf48a2">

### Configuration

```lua
local config = {}

local wezterm = require 'wezterm'
local act = wezterm.action

config.disable_default_key_bindings = true
config.keys = {
  { mods = 'CMD', key = 'k', action = act.SendKey({ mods = 'CTRL', key = 'u' }) },  -- example of remapping
}

return config
```

### Expected Behavior

On command palette, `Cmd + K` should be removed on 'Clear Scrollback'.

**Comment by wez** [comment]
Does the key mapping respect what you configured? Is this just a display issue in the command palette?

**Comment by codingskynet** [comment]
Yes, I think it is just a display issue.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by codingskynet** [comment]
Thank you! It is working well.
