### ISSUE TITLE
Option to disable shadow on Linux

### ISSUE THREAD

**Issue by flexagoon** [wez/wezterm#4725]
**Is your feature request related to a problem? Please describe.**
I'm using Wezterm on Gnome with the [Rounded Window Corners](https://github.com/yilozt/rounded-window-corners) extension which rounds window corners and adds a shadow to all windows. However, Wezterm seems to draw its own shadow, so the extension can't correctly calculate the window size and apply the effect.

**Describe the solution you'd like**
An option to disable the built-in shadow, like there is for macOS.

**Describe alternatives you've considered**
Rounded Window Corners hardcodes custom clipping values for kitty terminal which has the same problem. I can modify the extension and add this workaround for Wezterm as well, but this is a huge hack.

**Additional context**
[Here](https://github.com/yilozt/rounded-window-corners/issues/47) is the screenshot of what it looks like for Kitty, it's pretty much the same with Wezterm.

**Comment by wez** [comment]
wezterm doesn't draw any shadows, this is not a wezterm bug.
