### ISSUE TITLE
Stops Responding After Maximized

### ISSUE THREAD

**Issue by nvim-ftw** [wez/wezterm#4726]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

3dwm

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When full-screening WezTerm, the fullscreen instance no longer allows me to type. I can scroll, but not type. No matter what is done afterwards, functionality cannot be restored. While I could not find a nightly install (I'm probably just stupid and missed it), I did build from source and that solved my problem, so I'm not sure whether that's just because building from source got me a more platform-specific build or whether it was fixed. Was running from AppImage, not flatpak.

### To Reproduce

1. Install WezTerm v. 20230712-072601-f4abf8fd
2. Run on X11 3dwn Ubuntu 22.04
3. Maximize window
4. Observe the bug

### Configuration

no config

### Expected Behavior

WezTerm acts the same when after made fullscreen as it does when not full-screen.

**Comment by wez** [comment]
Please try the latest nightly build to see if this is still happening.
Please also try it with another window manager to see if it is specific to the one you are currently using.
