### ISSUE TITLE
Windows: ~ and backtick sends Alt-~ and Alt-backtick in FRA layout when use_dead_keys=false

### ISSUE THREAD

**Issue by bew** [wez/wezterm#473]
## Describe the bug

TSIA

## Environment (please complete the following information):

 - OS: Windows
 - Version: 20210203-095643-70a364eb-26-g9bf419eb

## Configuration

```lua
return {
  use_dead_keys = false
}
```

## To Reproduce

1. Open an ssh connection to a (linux) server
   _(local shells are also broken w.r.t keys, but I think it's another topic since other terminals have the same behavior)_
2. Open cat
3. Type `` ` `` followed by space or `~` followed by space

## Expected behavior

For `` ` ``: observe the output `` ^[` `` then after the space ``` ^[`` ```
For `~`: observe the output `^[~` then after the space `^[~~`

---
## NOTE

This is low priority for me, as I'm using some hackery with AutoHotKey (disabled for these tests above) to disable the dead key behavior of windows in every programs, which works well in wezterm as well, as if dead keys didn't exist 😛.

**Comment by wez** [comment]
What is the actual behavior you observe?  Which keyboard layout is active?

**Comment by bew** [comment]
French (sorry, didn't mention)

**Comment by wez** [comment]
*shakes fist at whatever markdown thing runs for issue titles*

**Comment by wez** [comment]
Could you give this a try with the nightly and let me know if this is now better?

**Comment by bew** [comment]
Re markdown in title, this should have worked..... it didn't x)
``` Windows: `~` and `` ` `` sends `Alt-~` and ``Alt-` `` ```
👉 Windows: `~` and `` ` `` sends `Alt-~` and ``Alt-` ``

---
More seriously, will try

**Comment by wez** [comment]
I've confirmed that this is still an issue.

`Alt-2` produces `~` in the FRA layout.  When dead keys are disabled, wezterm doesn't know that the `Alt` modifier should be elided from the key event.

There's a similar issue when dead keys are turned on: pressing `Alt-2` `Alt-2` will yield `Alt-~ Alt-~`.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
