### ISSUE TITLE
Fails to build on 32-bit architecture

### ISSUE THREAD

**Issue by jbeich** [wez/wezterm#474]
## Build Environment

 - OS: FreeBSD 11.4/12.2/13.0 i386
 - Compiler: Clang 10
 - Rust version: 1.49.0 packaged downstream

## Dependencies

I've used [downstream package](https://www.freshports.org/x11/wezterm) which [builds fine](http://beefy9.nyi.freebsd.org/data/114amd64-default/564920/logs/wezterm-20210203.095643.70.a364.e.log) at least on amd64.

## The build output

From [error](http://beefy10.nyi.freebsd.org/data/114i386-default/564920/logs/errors/wezterm-20210203.095643.70.a364.e.log) [log](http://beefy15.nyi.freebsd.org/data/130releng-i386-default/564920/logs/errors/wezterm-20210203.095643.70.a364.e.log):
```rust
error: literal out of range for usize
   --> termwiz/src/cell.rs:371:17
    |
371 |                 0x7f000000_00000000
    |                 ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(overflowing_literals)]` on by default
    = note: the literal `0x7f000000_00000000` (decimal `9151314442816847872`) does not fit into the type `usize` and will become `0usize`
```
```
$ rustc --print cfg
debug_assertions
target_arch="x86"
target_endian="little"
target_env=""
target_family="unix"
target_os="freebsd"
target_pointer_width="32"
target_vendor="unknown"
unix
```

**Comment by wez** [comment]
Thanks for adding the wezterm port!

re: 32-bit: supporting it hasn't been an active goal thus far, but I don't believe that there have been any deliberate choices that prevent it from working (except perhaps on Windows where the PTY stuff requires additional binaries to work).

what's curious is that the line in that error message is in the target_pointer_width=64 case of some code that should in theory be doing the right thing for 32-bit systems:

```rust
            if cfg!(target_pointer_width = "64") {
                0x7f000000_00000000
            } else if cfg!(target_pointer_width = "32") {
                0x7f000000
            } else if cfg!(target_pointer_width = "16") {
                0x7f00
            } else {
                panic!("unsupported target");
            }
```

https://github.com/wez/wezterm/blob/main/termwiz/src/cell.rs#L370-L378

I won't have time to investigate this further for a few days.

**Comment by unrelentingtech** [comment]
Oh.. well that's not correct!

Plain `if cfg!(..)` will **still compile all branches on all cfg's**, and only eliminate branches in the optimization phase (because the values are constants).

Use the [cfg_if macro](https://docs.rs/cfg-if).

**Comment by jbeich** [comment]
[Confirmed](https://github.com/wez/wezterm/files/5973623/wezterm-20210203.095643.70.a364.e.log) and [applied](https://svnweb.freebsd.org/changeset/ports/565042) the fix downstream.
