### ISSUE TITLE
Swap Horizontal and Vertical

### ISSUE THREAD

**Issue by burhan** [wez/wezterm#4740]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm not sure if this is always been this way but when I click on split window horizontally (top and bottom), it splits it vertically (left and right).

I'm used to horizontal splitting:

```

     Horizontal           Vertical

  ┌───────────────┐   ┌───────┬────────┐
  │               │   │       │        │
  │               │   │       │        │
  │     Top       │   │       │        │
  │               │   │       │        │
  │               │   │       │        │
  ├───────────────┤   │ Left  │  Right │
  │               │   │       │        │
  │               │   │       │        │
  │    Bottom     │   │       │        │
  │               │   │       │        │
  │               │   │       │        │
  │               │   │       │        │
  └───────────────┘   └───────┴────────┘


```

<img width="438" alt="image" src="https://github.com/wez/wezterm/assets/603112/f1c596b3-624e-4053-8fc2-4930bd2981bc">

Is there a way to modify the menu text? I've already swapped the keyboard shortcuts in the configuration.

### Configuration

no config

**Comment by wez** [comment]
The terminology was borrowed from tmux (or was it iterm? I forget now) and is now well-ingrained into various configs, making it awkward to change without breaking folks.

The Left/Right, Top/Bottom portion of the display name describes where the panes will end up.
