### ISSUE TITLE
Command with some lines 

### ISSUE THREAD

**Issue by badnotes** [wez/wezterm#4747]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

![image](https://github.com/wez/wezterm/assets/3199446/2dc3fbf9-014e-4297-8f53-6dad531e7acd)

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I paste this shell and got the error :

```bash
sh a.sh \
-p 1

```

### Configuration

nothing

**Comment by wez** [comment]
There's not enough information here to understand what you're trying or why you think it is a wezterm issue. Please expand with more details.

**Comment by badnotes** [comment]
Please paste my shell to try it
