### ISSUE TITLE
autoshift with qmk is not usable with ime

### ISSUE THREAD

**Issue by koopa1338** [wez/wezterm#4755]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

bspwm

### WezTerm version

wezterm 20240103-143005-4921f139

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

using autoshift on a qmk keyboard leads to inconsistent capital letters in the terminal when `use_ime` is active. A workaround is to disable `use_ime` like mentioned in #2829, which is not possible in my case as I need ime with fcitx for japanese inputs.

### To Reproduce

1. set `use_ime` to true
2. use a keyboard with qmk firmware and `auto shift` enabled
3. try writing capital letters by holding the key for at least the configured timeout (qmk)

### Configuration

```lua
local wezterm = require("wezterm")

local config = {}

if wezterm.config_builder then
	config = wezterm.config_builder()
end

config.use_ime = true
config.use_dead_keys = false
config.xim_im_name = 'fcitx'
```

### Expected Behavior

using auto shift shouldn't be a problem, it works with `use_ime` disabled and should also work with it enabled.

### Logs

This is just the logs from a failed auto shift

```log
00:57:56.238  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftShift, modifiers: SHIFT, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
00:57:56.238  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=LeftShift mods=SHIFT
00:57:56.238  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(A), modifiers: NONE, leds: (empty), phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }
00:57:56.238  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('a'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, leds: (empty), phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
00:57:56.238  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('a') mods=NONE
00:57:56.239  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "a", Char('a') NONE
00:57:56.239  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('a'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, leds: (empty), phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
00:57:56.239  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('a') mods=NONE
00:57:56.239  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: LeftShift, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
00:57:56.239  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=LeftShift mods=NONE
```

### Anything else?

I checked also my fcitx config and tried to tweak some settings there, especially timeout and delay option as the issue mentioned above assumes a timing issue between the keys, but that didn't help with this issue.

**Comment by wez** [comment]
Try a more recent nightly? Wondering if https://github.com/wez/wezterm/commit/0466898af7b347ff8c81efd57ed7d8da8eace27e may have improved this for you

**Comment by koopa1338** [comment]
I tried the latest commit and the issues seems resolved. I tried as hard as I can to trigger the described behavior but the autoshift never failed.
