### ISSUE TITLE
Bracketed Paste vulnerability, end sequence in payload not escaped

### ISSUE THREAD

**Issue by krishjainx** [wez/wezterm#4765]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20240108_014745_654622dc-0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If the text you're pasting happens to contain the same sequence of characters that the terminal uses to signify the end of a paste operation, it might prematurely signal the end of the paste. This could cause the remaining part of the pasted text to be interpreted as if it were manually typed, leading to unexpected behavior.

See the second payload here: https://thejh.net/misc/website-terminal-copy-paste from Jann Horn (@thejh) of Google's Project Zero

### To Reproduce

https://thejh.net/misc/website-terminal-copy-paste

Payload that is problematic:
- 2nd in link 

### Configuration

no config

### Expected Behavior

The expected behavior of the terminal is to escape the end sequences in the payload, so that bash will not interpret those as the actual end sequence .

### Anything else?

gnome-terminal isn't vulnerable to this issue.

**Comment by wez** [comment]
This should be resolved now in `main`. Thanks for reporting it!

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
