### ISSUE TITLE
Mistype when processing control+letter sequences?

### ISSUE THREAD

**Issue by qtfkwk** [wez/wezterm#4776]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Gnome 45

### WezTerm version

wezterm 20240111-065451-9a5af153

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Control+characters sequences like ctrl+f (autocomplete), ctrl+a (home), ctrl+e (end) type `f`, `a`, `e`, respectively if *typing too fast* and don't deliberately *pause* when typing the keystroke.

It seems to occur precisely when I release the ctrl key before the character key. It does not occur if I'm careful to release the character key first.

I'm using zsh btw. This doesn't happen using other terminals and the same shell.

### To Reproduce

It seems non-existent in the nightly appimage but is present if I use the regular appimage (WezTerm-20230712-072601-f4abf8fd-Ubuntu20.04.AppImage) or build from source (wezterm gpg: Signature made Mon 08 Jan 2024 08:23:29 PM EST) and type a partial command and then type ctrl+f, ctrl+a, or ctrl+e. Not sure what that would be (?).

### Configuration

n/a

### Expected Behavior

Don't type the letter(s) and do the correct thing, e.g. ctrl+f should do the autocomplete, ctrl+a should go to home, ctrl+e should go to end.

**Comment by wez** [comment]
Potentially relevant: 0466898af7b347ff8c81efd57ed7d8da8eace27e cc: @bew

**Comment by qtfkwk** [comment]
> Is this a recent change in behavior, or are you just trying this and finding that you don't like it?

I'm new to wezterm so I can't say if it's a recent change, just that it was the first thing I don't like.

**Comment by wez** [comment]
@qtfkwk if you can spare the time, could you build from source and compare the behavior of 90d8feaf6da13a24bb4098657d306920b3637712 and 0466898af7b347ff8c81efd57ed7d8da8eace27e to see if this is a regression introduced today, or whether it has always been this way?

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by qtfkwk** [comment]
Built from source just now from [30d6c6d](https://github.com/wez/wezterm/commit/30d6c6d9c0b70e5ade88918dd13457a099fbe567) and the behavior is gone!

Much appreciated!
