### ISSUE TITLE
Nightly Build not working

### ISSUE THREAD

**Issue by jacoboneill** [wez/wezterm#4779]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Nightly build via homebrew is not installable.

### To Reproduce

```zsh
> brew tap homebrew/cask-versions
> brew install --cask wezterm-nightly

==> Tapping homebrew/cask-versions
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions'...
remote: Enumerating objects: 271645, done.
remote: Counting objects: 100% (9860/9860), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 271645 (delta 9651), reused 9793 (delta 9621), pack-reused 261785
Receiving objects: 100% (271645/271645), 67.66 MiB | 11.05 MiB/s, done.
Resolving deltas: 100% (188880/188880), done.
Tapped 250 casks (285 files, 76.4MB).
Error: Cask 'wezterm-nightly' conflicts with 'wezterm'.

> brew upgrade --cask wezterm-nightly --no-quarantine --greedy-latest

Error: Cask 'wezterm-nightly' is not installed.
```

### Configuration

no config

### Expected Behavior

For the nightly build to be installed.

**Comment by wez** [comment]
The error message seems clear: you already have the stable version of wezterm installed, which conflicts with the nightly version of wezterm. You need to pick one or the other.

**Comment by jacoboneill** [comment]
@wez is there documentation on how to upgrade from the standard build to the nightly build? If not can this fact be added or the fact you can't upgrade also be added?
Love the terminal btw!

**Comment by wez** [comment]
respectfully, I think that's more of a "how do I use `brew`?" question.
Probably `brew rm wezterm` before trying to install `wezterm-nightly`

**Comment by jacoboneill** [comment]
Understandable, however it isn't entirely clear in the documentation in my opinion. Nonetheless does seem a lot of effort for not a lot of gain so I can understand why you wouldn't want to do it. 👍🏻

**Comment by wez** [comment]
If I document that for brew, then I should document that for all of the other package managers for all the other operating systems, and there are a LOT of them.  There's a point at which the user needs to know how to use the package management features they chose to use on their operating system and I don't think the responsibility for educating about third party software falls to wezterm's docs.
