### ISSUE TITLE
pane:get_raw_lines_as_text([nlines])

### ISSUE THREAD

**Issue by thiagokokada** [wez/wezterm#4780]
**Is your feature request related to a problem? Please describe.**
In Kitty I can set the scrollback buffer to an external program and it would fill this program with the contents of the terminal as-is, including the escape codes.

So I decided to do something similar with WezTerm, as described here: https://wezfurlong.org/wezterm/config/lua/wezterm/on.html#custom-events.

The issue is that the function that is used to get the text, `pane:get_lines_as_text()`, returns the text without the escape codes, as described in the https://wezfurlong.org/wezterm/config/lua/pane/get_lines_as_text.html:

> Returns the textual representation (not including color or other attributes) of the physical lines of text in the viewport as a string.

This is not what I want, because I use https://github.com/I60R/page to interpret the escape codes as normal and get full color (and even complex terminal programs like neovim window) inside neovim.

**Describe the solution you'd like**
A function that returns the text as-is including escape codes.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by wez** [comment]
This is now implemented in `main`.

See: https://wezfurlong.org/wezterm/config/lua/pane/get_lines_as_escapes.html

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by thiagokokada** [comment]
Sorry @wez, just got to testing it now.

For some reason https://github.com/I60R/page is not understanding the escape codes. I am not sure if it is an issue with `page` or how WezTerm is exporting the data. `less` (in the example in the documentation) works though.

**Comment by thiagokokada** [comment]
Oh, nevermind. It works when the text is piped, e.g.: `cat output.log | page`.

The whole code if someone is interested:

```sh
#!/usr/bin/env bash
# This is the scrollback-buffer-viewer.sh script
cleanup() { rm -f "$1"; }
trap cleanup EXIT
cat "$1" | page
```

```lua
wezterm.on('trigger-editor-with-visible-text', function(window, pane)
  -- Retrieve the current viewport's text.
  --
  -- Note: You could also pass an optional number of lines (eg: 2000) to
  -- retrieve that number of lines starting from the bottom of the viewport.
  local viewport_text = pane:get_lines_as_escapes(scrollback_lines)

  -- Create a temporary file to pass to vim
  local name = os.tmpname()
  local f = io.open(name, 'w+')
  f:write(viewport_text)
  f:flush()
  f:close()

  -- Open a new tab running editor and tell it to open the file
  window:perform_action(
    act.SpawnCommandInNewTab {
      args = { 'scrollback-buffer-viewer.sh', name },
    },
    pane
  )
end)

```
