### ISSUE TITLE
osc52 stops working after a while

### ISSUE THREAD

**Issue by pescobar** [wez/wezterm#4791]
I am hitting again the same problem I already reported in https://github.com/wez/wezterm/issues/1790

I launch tmux in a remote machine with mouse integration enabled and osc52 works fine for a while (I can copy&paste) but after a while it stops working and whatever I select in the tmux session is not copied to my desktop clipboard. The only workaround I found is to completely close wezterm, open wezterm again, login to the remote machine and reattach to the running tmux session and then osc52 integration works again.

My desktop computer is `linux mint 21.2 (based on ubuntu 22.04)` with `wezterm 20240108-182319-1c090195`.  I launch tmux in a remote machine running ubuntu 22.04 and `tmux 3.2a` 

Trying to find a workaround I tried to reset wezterm as described in https://wezfurlong.org/wezterm/config/lua/keyassignment/ResetTerminal.html but I cannot manage to reset wezterm. I guess I am doing something wrong. Can anyone describe like I am five how to reset wezterm?

**Comment by wez** [comment]
There's not enough information here about how wezterm is configured or being used, and I don't have the bandwidth to read an old long issue to try and figure it out. Please provide more information on how to trigger this.
