### ISSUE TITLE
Wezterm blank after kernel update

### ISSUE THREAD

**Issue by kenderipa** [wez/wezterm#4793]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

JWM

### WezTerm version

20240111-073635-6c36a4dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hello,

after updating kernel to 6.6.11 Wezterm is blank, meaning it doesn't show neither tabs nor their content. Following warning is seen, if started from another terminal. Any suggestions?

WARN   window::os::x11::connection > Unable to resolve appearance
using xdg-desktop-portal: get_appearance.read_setting: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

### To Reproduce

Update kernel to 6.6.11

### Configuration

Configuration unchanged.

### Expected Behavior

Should work as normal.

### Logs

 23:33:24.343  ERROR  wezterm > failed to connect to Socket("/run/user/1000/wezterm/gui-sock-5174"): connecting to /run/user/1000/wezterm/gui-sock-5174;
terminating

**Comment by wez** [comment]
Likely a local GPU driver related issue.  There's not enough information here to provide additional suggestions; if wezterm didn't change but your kernel did, then it is likely that you need to do something with your kernel/driver situation to resolve this.
