### ISSUE TITLE
Window border issue on macOS with Stage Manager 

### ISSUE THREAD

**Issue by hiql** [wez/wezterm#4798]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The right bottom corner :

<img width="739" alt="截屏2024-01-17 09 09 17" src="https://github.com/wez/wezterm/assets/17871109/34bf1462-ac18-4f94-9c9e-d83dd36b3167">

### Configuration

use default configuration

**Comment by wez** [comment]
There's not enough information here about what is happening

**Comment by hiql** [comment]
Alacritty has the same problem

**Comment by wez** [comment]
FWIW, the rounded corners are not drawn by wezterm, they are part of macOS.
I don't think there's anything for me to do here.
