### ISSUE TITLE
Add ResetFontAndWindowSize key assignment

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#480]
## Describe the bug

See "To Reproduce" section. My main issue with this problem is that the current window becomes unusable because of "large font size in small window" and I have to close the current one and open a new Wezterm window.

## Environment (please complete the following information):

 - OS: Manjaro (X11)
 - Version: 20210203-095643-70a364eb-26-g9bf419eb

## To Reproduce

Note: make sure `adjust_window_size_when_changing_font_size` is not set to `false`.

1. Increase font size until window takes up entire screen/viewport.
2. Increase font size a little more (3-5 times is enough).
3. Now, decrease font size.

Because window size is also reduced,
* font size becomes larger than expected.
* `ResetFontSize` indeed resets font size to default size, but Wezterm's window size will be very small.

Window becomes unusable because of "large font size in small window".

## Configuration

Default config.

## Expected behavior

In cases like this, when decreasing font size, Wezterm should first try to decrease font size before decreasing window size.

**Comment by MuhammedZakir** [comment]
> My main issue with this problem is that the current window becomes unusable because of "large font size in small window" and I have to close the current one and open a new Wezterm window.

A temp fix: set `adjust_window_size_when_changing_font_size` to `true`, reload config and reset font size. This (temporarily) solves my problem about window becoming unusable.

**Comment by wez** [comment]
This is working as design, but the wrinkle is that when the window is larger than the screen, the window environment also resizes the window, so that when you eventually reduce the font size, there are fewer rows.

If there was a `ResetFontAndWindowSize` action that reset both the font size and the number of rows/columns to the default, would that satisfy your need?

**Comment by MuhammedZakir** [comment]
`ResetFontAndWindowSize` will suffice. Thanks! :-)
