### ISSUE TITLE
Chinese font very small 

### ISSUE THREAD

**Issue by imkratos** [wez/wezterm#4808]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

MacOS 14.2.1

### WezTerm version

wezterm-nightly

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

<img width="401" alt="image" src="https://github.com/wez/wezterm/assets/3302461/3b8c52f9-d0e3-4663-b5f7-5787b06525d1">

chinese very small 

### Configuration

```lua
config.color_scheme = "Tokyo Night"
config.font = wezterm.font_with_fallback({
	{ family = "JetBrains Mono", scale = 1.24, weight = "Bold" },
	{ family = "JetBrains Mono Nerd Font", scale = 1.2 },
})

```

**Comment by wez** [comment]
Consider making the font_size larger.
https://wezfurlong.org/wezterm/config/lua/config/font_size.html

**Comment by joshuali925** [comment]
i had the same issue upgrading from 20230712 to nightly, you might want 
```lua
config.font = wezterm.font_with_fallback({ { family = "JetBrainsMono Nerd Font", weight = "Medium" }, "PingFang HK" })
```

I'm not sure why but
```sh
❯ ~/Downloads/WezTerm-macos-20230712-072601-f4abf8fd/WezTerm.app/Contents/MacOS/wezterm ls-fonts --text "啊"
LeftToRight
 0 啊    \u{554a}     x_adv=14 cells=2  glyph=2081 wezterm.font(".PingFang HK", {weight="Regular", stretch="Normal", style="Normal"})
                                      /System/Library/Fonts/PingFang.ttc index=18 variation=0, CoreText
```

where as in after 20240127 the output is almost the same except `weight` became `Thin` and `index` changed:
```sh
❯ wezterm ls-fonts --text "啊"
LeftToRight
 0 啊    \u{554a}     x_adv=14 cells=2  glyph=2081 wezterm.font(".PingFang HK", {weight="Thin", stretch="Normal", style="Normal"})
                                      /System/Library/Fonts/PingFang.ttc index=33 variation=0, CoreText
```

**Comment by wez** [comment]
@joshuali925 ah, thanks for sharing that information.  I've pushed a commit that should address that.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by joshuali925** [comment]
thanks, i can confirm it's fixed on my side on current nightly

**Comment by imkratos** [comment]
current nightly look this 
<img width="270" alt="image" src="https://github.com/wez/wezterm/assets/3302461/2725dc25-7c85-4116-ab46-84645363446f">
not perfect but it's working

**Comment by wez** [comment]
You cannot map codepoints to specific fonts in wezterm, but you can list your preferred and order list of fonts by listing them out in https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html in your order of preference.

**Comment by yanxiang-wang** [comment]
> You cannot map codepoints to specific fonts in wezterm, but you can list your preferred and ordered list of fonts by listing them out in https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html in your order of preference.

thanks, I know what to do.
