### ISSUE TITLE
The working directory of new tabs changes whenever any tab closes

### ISSUE THREAD

**Issue by slashbeast** [wez/wezterm#4811]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

N/A, MacOS.

### WezTerm version

wezterm 20230712-072601-f4abf8fd
wezterm 20240118-061239-9181d010

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The working directory of new tab seems to be updated whenever tab is closed to the previous tab. if I enter for example `/opt` in a tab, and start new tab, the new tab will default to home directory, however the moment I close this tab, and wezterm automatically jump to the tab in `/opt` all new tabs will then have working directory set to `/opt` instead. The new tab working directory do not follow whatever current working directory is in the tab from which I opened new one, and only ever gets updated on closing tab

### To Reproduce

1. Start WezTerm
2. go to /etc
3. Open new tab
4. See that you are (by default) in your home directory
5. Close tab
6. open another tab
7. Now your tab started in /etc instead

### Configuration

local wezterm = require 'wezterm';

return {
  front_end = "WebGpu",
  font = wezterm.font("JetBrains Mono"),
  font_size = 16.0,
  initial_cols = 90,
  initial_rows = 20,
  hide_tab_bar_if_only_one_tab = true,

  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},

  color_scheme = 'Abernathy',
}

### Expected Behavior

I would expect the working directory to either always follow working directory of the tab I currently have open and from which I spawn new tab or always default to home directory

**Comment by cstrahan** [comment]
Without the wezterm shell integration (by setting `WEZTERM_SHELL_SKIP_ALL=1` in my `~/.zshrc`) I can also reproduce this.

For what it's worth: if you're happy with new tabs always following opening in the current directory of the currently focused pane/tab, the [shell integration](https://wezfurlong.org/wezterm/shell-integration.html) does work.

Additionally, I've created a dedicated [zimfw](https://zimfw.sh/) plugin, if you happen to be using that to manage your ZSH config/plugins: https://github.com/cstrahan/zim-wezterm

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by slashbeast** [comment]
Thank you for looking into it. I can confirm that running 20240203-110809-5046fc22 always open new tab in the current working directory of the tab that was active when new tab action was called.
