### ISSUE TITLE
Opening a new tab in Wezterm does not show correct tab name

### ISSUE THREAD

**Issue by erik96** [wez/wezterm#4817]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20240115_022152_843724ba

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If I open wezterm normally just with the command:
`wezterm` then the tab name and window title are only `bash` , the current working directory along with user@host is not displayed.

If I open Wezterm with the following command:
`wezterm start -- bash`

Then the issue is no longer reproduced. The window (and tab) title are properly displayed. (user@host and then the current working directory).

However, if I open a new tab in weezterm, this second tab still has the bug, only `bash` is displayed in the title.
If I run the command `bash` in this new tab to get into a new shell, then the window title and  tab title are correct again.

### To Reproduce

Fedora 39 Workstation Edition, X11, Nvidia Driver.
Install latest available Wezterm (for F39 only nightly version is available at the moment).
Start wezterm with the command `wezterm` -> observe the window title and tab title.
Start wezterm with the command `wezterm start -- bash` -> observe proper window and tab title.
Open a new tab -> observe window and tab title are wrong again.

### Configuration

no config

### Expected Behavior

When opening a new tab, the current working directory along with user@host should be displayed in the Window title and in the Tab Title without entering in a sub bash shell.

### Anything else?

![image](https://github.com/wez/wezterm/assets/3287261/0a08c7fb-1dea-4731-a6c4-0a9c49aa2260)
![image](https://github.com/wez/wezterm/assets/3287261/2610854e-9abf-4dcb-92ca-5dfc0abe9359)

**Comment by wez** [comment]
wezterm launches the shell as a login shell by default. It sounds like your shell configuration is set up to skip sending escape sequences to update the title/pwd when run as a login shell.
This is a local-to-you issue.

https://wezfurlong.org/wezterm/config/launch.html?h=login#launching-programs 
has a bit more information on this.

If you don't want to fix your shell dotfiles, you may want to set your `default_prog = {'bash'}` to explicitly *not* run a login shell.
