### ISSUE TITLE
Pane zoom cuts text from screen when SSHed into Busybox (OpenWRT)

### ISSUE THREAD

**Issue by Tomiyou** [wez/wezterm#4828]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20240119-150447-237e44d7 (Built on my machine with 2 cherry-picked PRs, but the same bug occurs on official release)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I think it is easiest to explain via images. This is what terminal looks like without any pane being zoomed:
![Screenshot from 2024-01-21 15-11-35](https://github.com/wez/wezterm/assets/1957558/71600a2e-55e3-4951-a1d0-fdb08e89b049)
This is how it looks like after zooming the left pane using Ctrl + Shift + X (notice how text is cut at where the pane split used to be):
![Screenshot from 2024-01-21 15-11-42](https://github.com/wez/wezterm/assets/1957558/b1948acb-010f-4113-8f05-20c10954ab21)

So far this only happens when using Busybox (probably related to the weird/old implementations of terminal emulation Busbox uses). Note that the characters are still there, they are just not rendered properly.

I did some debugging and the issue occurs because shaping caching uses the old, unzoomed-pane line to render (which should be linebroken), instead of the new zoomed-pane line (which should NOT be linebroken). It seems that for some reason, when SSHed into Busybox, line shape cache is not cleared correctly when zooming in:
```
        let shaped = if let Some(shaped) = shaped { // <-------- After zooming in, shaped hash points to the line-broken shape instead of the non line-broken shape
            shaped
        } else {
```

I would debug this further, but unfortunately I don't have enough knowledge or skill to make any progress.

### Configuration

no config

**Comment by wez** [comment]
how are you sshing in to the remote host? Running `ssh`, `wezterm ssh`, or using an ssh domain or something else?

Which PRs have you cherry picked into your wezterm build?

**Comment by Tomiyou** [comment]
I am simply running `ssh root@192.168.1.1` (to SSH into openwrt), so I am not using `wezterm ssh`. Here are the pictures of the same bug using Nightly Appimage without any `.wezterm.lua` config at all.
Unzoomed:
![Screenshot from 2024-01-22 11-58-54](https://github.com/wez/wezterm/assets/71773685/32cbe548-700b-4459-9758-ce12f4b36300)
Zoomed:
![Screenshot from 2024-01-22 11-59-02](https://github.com/wez/wezterm/assets/71773685/e94cefcf-b2f4-447a-b477-cb4276056e18)

I'm not sure if it helps, but I did do some more debugging. I added a log print to `pub fn clear_appdata(&self) {` which prints all the visible cells text, whenever that function gets called. Here is what the log says:
```
# Logs when the pane is not zoomed
clear_appdata() called for: root@OpenWrt:~# This is a line too long for a single vertical pane and will cause issues when
clear_appdata() called for: zooming the pane

# For some reason the `clear_appdata()` is not called for these 2 lines when zooming the pane.
```
As far as I can tell from the code, this `clear_appdata()` is the function which should clear the line cache, causing the whole thing to be re-rendered.

**Comment by wez** [comment]
Could you try running with this patch:

```diff
diff --git a/termwiz/src/surface/line/line.rs b/termwiz/src/surface/line/line.rs
index a6f3c1a0c..e1a7fef7b 100644
--- a/termwiz/src/surface/line/line.rs
+++ b/termwiz/src/surface/line/line.rs
@@ -183,6 +183,7 @@ impl Line {
         }
         self.update_last_change_seqno(seqno);
         self.invalidate_zones();
+        self.clear_appdata();
         self.bits = LineBits::NONE;
     }

@@ -190,6 +191,7 @@ impl Line {
         self.coerce_vec_storage().resize_with(width, Cell::blank);
         self.update_last_change_seqno(seqno);
         self.invalidate_zones();
+        self.clear_appdata();
     }

     /// Wrap the line so that it fits within the provided width.
```

**Comment by wez** [comment]
I'm not sure if the one above is 100% correct.
Here's an alternative approach:

```diff
diff --git a/term/src/screen.rs b/term/src/screen.rs
index 4ca3ff8a1..c45f35026 100644
--- a/term/src/screen.rs
+++ b/term/src/screen.rs
@@ -109,6 +109,7 @@ impl Screen {

         for (phys_idx, mut line) in self.lines.drain(..).enumerate() {
             line.update_last_change_seqno(seqno);
+            line.clear_appdata();
             let was_wrapped = line.last_cell_was_wrapped();

             if was_wrapped {
```

Please try them independently from each other and let me know how you get on!

**Comment by Tomiyou** [comment]
> I'm not sure if the one above is 100% correct. Here's an alternative approach:
> 
> ```diff
> diff --git a/term/src/screen.rs b/term/src/screen.rs
> index 4ca3ff8a1..c45f35026 100644
> --- a/term/src/screen.rs
> +++ b/term/src/screen.rs
> @@ -109,6 +109,7 @@ impl Screen {
> 
>          for (phys_idx, mut line) in self.lines.drain(..).enumerate() {
>              line.update_last_change_seqno(seqno);
> +            line.clear_appdata();
>              let was_wrapped = line.last_cell_was_wrapped();
> 
>              if was_wrapped {
> ```
> 
> Please try them independently from each other and let me know how you get on!

This 2nd patch does indeed fix the issue.

I see that with this fix, all lines now re-rendered when zooming/unzooming a pane, regardless if they were wrapped or not. I assume this is not a long-term fix?

**Comment by wez** [comment]
Thanks for confirming. What I think is happening here is that the `seqno` there is not actually changing as part of the resize so the cached value isn't considered to be stale by this logic:

https://github.com/wez/wezterm/blob/f6aba4b0d632962425b273a7815adec46b3b64af/wezterm-gui/src/termwindow/render/mod.rs#L821-L826

I think the proper fix for this is to increment the seqno on resize (8f74e1c8486d66f40bd1d11cd01160774df64b07); that might actually resolve a couple of other issues around resizing and panes when using the multiplexer.

Re-rendering is what we want in this case. It would be nice to avoid re-rendering unchanged lines, but it's not the end of the world if there is a bit of over-computation here, because it should then get cached and reused immediately afterwards.

I've pushed 8f74e1c8486d66f40bd1d11cd01160774df64b07 and would appreciate it if you could try it and confirm whether that resolves the issue that you're seeing!

**Comment by Tomiyou** [comment]
The latest commits (516add5) do indeed solve this issue. Thank you for the quick fix :)

I will let you close this issue.
