### ISSUE TITLE
Bad rendering of some unicode characters. 

### ISSUE THREAD

**Issue by iojea** [wez/wezterm#4829]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240120-211320-b4c5dc74

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hi!
I don't know if this can be considered a bug, but it is the only thing that is giving some trouble with Wezterm, which is otherwise quite awesome. 

I am programming in Julia, where unicode characters can be inserted by typing some latexish code and then pressing tab. For example: `\_t` + `tab` should produce a subindex `t`. However, Wezterm is not rendering some of these characters properly. In particular, I have problems with subindices: they are too narrow. For example: this is a capture of a subindex `t` followed by a subindex `n` on Wezterm:
 
<img width="94" alt="Captura de pantalla 2024-01-21 a la(s) 14 56 14" src="https://github.com/wez/wezterm/assets/13087110/2b09a39b-aedd-4d95-a0e7-85fdc618e66f">

And this is the same thing, but in Mac's Terminal App: 

<img width="105" alt="Captura de pantalla 2024-01-21 a la(s) 14 57 47" src="https://github.com/wez/wezterm/assets/13087110/a3b881d4-219e-49e1-98f7-3202259458bb">

This only happens with letters: number subindices are fine. 

Also, there are some characters that Wezterm cannot render, like `\frakD`, or superindices like `\^t`, `\^n`, etc. : 
Wezterm:
<img width="99" alt="Captura de pantalla 2024-01-21 a la(s) 14 59 41" src="https://github.com/wez/wezterm/assets/13087110/dacb6bf5-c99d-47c2-8fce-d580935266ec">
Terminal:
<img width="102" alt="Captura de pantalla 2024-01-21 a la(s) 14 59 01" src="https://github.com/wez/wezterm/assets/13087110/eef9eafa-a10a-4e73-8a5c-2b6b403e0901">

I had this issue with the regular version of Wezterm (installed via brew), I changed it for the nightly build (also installed with brew). With this change, I got some improvement: some characters that were not rendered before were now available. But subindices remained too narrow, and some characters still didn't work. Today, something weirder happened: Yesterday, I left an open session of Helix with some Julia code, where I had some `\frakD`s that looked fine. Today, when I opened the macbook, the `\frakD`s had turned into question marks... I don't know how is that possible. 

I prefer Monaco font, but I tried Fira Code, Hack, Cousine, CommitMono and some others, with the same result. I also tried removing my config file in order to test Wezterm's default behaviour, but nothing changed. In fact, subindices do not seem to change at all on Wezterm. On Terminal, on the other hand, they seem to be rendered in the selected font, at least when possible. 

In any case, if something can be done about this (maybe I need to configure some alternative font... but I don't know which one), it would be great. 

Thanks!

P.S.: I tried some emojis, and all of them worked correctly. 

### To Reproduce

You can copy/paste some random symbols from this link:
https://docs.julialang.org/en/v1/manual/unicode-input/
There are a lot of symbols that Wezterm does not render at all (inserting a question mark instead). I couldn't find anyone that fails on Terminal. However, copy/paste also gives a question mark for subindices. In order to obtain the too-narrow subindices... I suppose that you will need to install Julia and try on a Julia REPL. 

### Configuration

This is the content of my config file (however, the issue is the same with no config file at all): 

-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

local wezterm = require 'wezterm'
local mux = wezterm.mux

wezterm.on("gui-startup", function()
  local tab, pane, window = mux.spawn_window{}
  window:gui_window():maximize()
end)
-- This is where you actually apply your config choices

-- For example, changing the color scheme:
--config.color_scheme = 'Dracula'
-- config.font = wezterm.font_with_fallback {
--  'Monaco',
--  'CommitMono Nerd Font Mono',
--  'Fira Code',
--}
config.font = wezterm.font 'CommitMono Nerd Font Mono'
config.window_decorations = "RESIZE"
config.window_background_opacity = 0.8
config.enable_tab_bar = false
config.font_size = 18

-- config.disable_default_key_bindings = true

-- Keybindings

local act = wezterm.action

config.keys = {

{ key = "-",        
  mods = "CMD",  
  action = act.SplitVertical{domain="CurrentPaneDomain"} },

{ key = "|",       
  mods = "CMD",  
  action = act.SplitHorizontal{domain="CurrentPaneDomain"} },

{ key = "x",
  mods = "CMD",
  action = act.CloseCurrentPane {confirm = true} },
   

{ key = "h",
  mods = "SHIFT|CMD",
  action = act.AdjustPaneSize { "Left" , 2} },

{ key = "l",
  mods = "SHIFT|CMD",
  action = act.AdjustPaneSize { "Right" , 2} },

{ key = "j",
  mods = "SHIFT|CMD",
  action = act.AdjustPaneSize { "Down" , 2} },

{ key = "k",
  mods = "SHIFT|CMD",
  action = act.AdjustPaneSize { "Up" , 2} },

{ key = 'h',
  mods = 'CMD',
  action = act.ActivatePaneDirection 'Left', },
  
{ key = 'l',
  mods = 'CMD',
  action = act.ActivatePaneDirection 'Right', },

{ key = 'k',
  mods = 'CMD',
  action = act.ActivatePaneDirection 'Up', },

{ key = 'j',
  mods = 'CMD',
  action = act.ActivatePaneDirection 'Down', },

}-- and finally, return the configuration to wezterm
return config

### Expected Behavior

Render all symbols properly. 

### Anything else?

I don't think so. Thank you very much. As I said, Wezterm is awesome.

**Comment by wez** [comment]
Please reduce the reproduction scenario down to something like an `echo` or `printf` command invocation that outputs the character(s) in question; I do not have the bandwidth to install or learn how to use julia.

**Comment by iojea** [comment]
Good point. 
For example: `echo -e \U03B1'` produces (correctly) a greek alpha.
On the other hand, `echo -e '\U209C'` should produce a `t` in subindex position, but gives the question mark surrounded by a square. The same happens for example, with `\U1D43` which should give an `a` as superindex, `\U2135` (aleph), `\U2112` (script L), and many others. All of these work fine on Terminal. 
As I mentioned before, for some reason in the Julia REPL `\_t` + `tab` produces the correct output (subindex `t`) but very narrow. I cannot reproduce this using `echo` nor `printf`, which give just the question mark.  
Thanks!

**Comment by wez** [comment]
Can you feed those codepoints into `wezterm ls-fonts --codepoints`? See example below:

```console
$ wezterm ls-fonts --codepoints 209C
LeftToRight
 0 ₜ    \u{209c}     x_adv=8  cells=1  glyph=uni209C,2583 wezterm.font("Noto Sans Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf, FontConfig
```

that should show the rendering plan, including which font was found to contain the glyph.

**Comment by iojea** [comment]
Ok! Something is wrong there:

```
$ wezterm ls-fonts --codepoints 209C
 LeftToRight  0 ₜ    \u{209c}     x_adv=1  cells=1  glyph=t.subs,1761 wezterm.font("System Font", {weight=31,      
 stretch="ExtraCondensed", style="Normal"})  /System/Library/Fonts/SFNS.ttf index=0 variation=1, CoreText 
```

I don't know why it was going to "System Font", "ExtraCondensed"...

I defined `wezterm.font_with_fallback`, setting Noto Sans Mono as fallback, and now I get things like `\U209C` correctly. That's a great improvement. 

There is still problems, though. For example, `\U1D507`: 

```
$ wezterm ls-fonts --codepoints 1D507
LeftToRight  0 𝔇    \u{1d507}    x_adv=16.041666666666664 cells=1  glyph=lastresorttemplate,4    wezterm.font(".LastResort", {weight="Regular", stretch="Normal", style="Normal"})   /System/Library/Fonts/LastResort.otf, CoreText
```

(Note that the symbols are rendered correctly when I paste the output here, but in my Wezterm instance I only see the question mark).

Thanks!

**Comment by wez** [comment]
For that last one, that suggests that the system was not able to resolve that codepoint to a font, and that the core text layer tells us to use the built-in last resort font.
I don't know if there is more we can do to figure out the font for that if apple's APIs are not returning it.
In the meantime, I would suggest figuring out which font has that symbol and explicitly adding it to your config.

**Comment by iojea** [comment]
Excellent. That shouldn't be too difficult. 
Thanks a lot!
