### ISSUE TITLE
WezTerm not able to detect fonts by "Full name"

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#483]
## Describe the bug

I recently installed JetBrainsMonoNerd fonts from [nerd-fonts repository](https://github.com/ryanoasis/nerd-fonts). They have an [issue](https://github.com/ryanoasis/nerd-fonts/issues/579) where PostScript names of some fonts within family has name-clash, **though** the "Full Name" is unique... WezTerm is not able to detect any of their fonts with "Full Name" (even ones which do not have any name clash). Open FontBook in macOS to see what is "Full Name" vs "PostScript Name" vs "Family Name"; I use these terms in this bug often.

## Environment:
```
>> wezterm --version
wezterm 20210203-095643-70a364eb-26-g9bf419eb
```
```
>> neofetch
                   'c.           reportaman@Mac-mini.local
                 ,xNMM.          ------------------------------
               .OMMMMo           OS: macOS 11.2 20D64 arm64
               OMMM0,            Host: Macmini9,1
     .;loddo:' loolloddol;.      Kernel: 20.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 3840x2160
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: WezTerm
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 1909MiB / 16384MiB
       .cooc,.    .,coo:.
```

## To Reproduce

1. Install JetBrainsMonoNerd fonts from [nerd-fonts repository](https://github.com/ryanoasis/nerd-fonts). Note: Their repo is several GBs, so download just their a subfolder from the repo [here](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono). I use the ``svn checkout`` method detailed [here](https://stackoverflow.com/a/18194523/15087532)

2. Run ``>>wezterm`` from another terminal emulator (to read decorated error messages at launch) or open WezTerm.app

## Configuration
```lua
local wezterm = require 'wezterm';

return {
  -- doesn't work: (this is the "Full Name" of italic font)
  font = wezterm.font("JetBrains Mono Italic Nerd Font Complete"),
  -- only name that works is "Family Name", and not "Full name", it selects regular style from the family
  -- font = wezterm.font("JetBrainsMono Nerd Font"),
  font_size = 19.0
}
```

## Expected behavior
WezTerm should allow selecting font using "Full Name", irrespective of clash in PostScript names.

## Screenshots
Run ``>>wezterm`` from another terminal emulator, and it will print these errors in the parent terminal emulator. Here I am using the "Full Name" of the Italic weight of the font.

![Screen Shot 2021-02-12 at 11 58 53 PM](https://user-images.githubusercontent.com/71736629/107845195-9820c480-6d8e-11eb-8778-9778aebf4636.png)

**Comment by wez** [comment]
There was an issue in wezterm's core-text font resolution that got fixed here: https://github.com/wez/wezterm/commit/4e276076158899b36c63b11905ea613ad9bc87df
You also mentioned that you had worked around this, so I'm going to close this out
