### ISSUE TITLE
Error in handling extremely fast typing

### ISSUE THREAD

**Issue by aghriss** [wez/wezterm#4837]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 KDE with i3 WM and SDDM login window

### WezTerm version

wezterm 20230712-072601-f4abf8fd-gentoo

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

This is not specific to Wezterm. I have found similar problem with alacritty as well.

When a series of characters is typed with a delay less than 8ms, the upper case and key combinations are handled randomly.
For instance, typing "AghrIss$2024" with less than 8ms delay produces "aghrIss42024" or sometimes "aghRiss$2024".

The problem occurs with programmable keyboards when I activate ibus (IME for Japanese). When `use_ime` is set to false, this doesn't occur.

The workaround is to add delay between the characters in the keyboard macro, but this only happens inside Wezterm and (occasionally in Alacritty).

### To Reproduce

- Activate `use_ime` in the config (default).
- Add launch ibus before starting the terminal
- Open 2 instances of the terminal
- In the first instance, run:
```bash
sleep 2 && xdotool type --delay 5 "AghrIss\$2024"
````
- Before the 2 seconds elapse, activate the second terminal

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
-- if wezterm.config_builder then
  -- config = wezterm.config_builder()
-- end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
-- config.color_scheme = "AdventureTime"

config.font = wezterm.font("JetBrains Mono Nerd Font")
-- config.use_ime = false

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

Output the same string "AghrIss$2024"

**Comment by aghriss** [comment]
This is related to #4615

**Comment by wez** [comment]
Please try the latest nightly; there have been some changes with handling the modifier masks on x11 that may help here
