### ISSUE TITLE
Use `label` attribute of `SpawnCommandInNewTab` as tab `title`.

### ISSUE THREAD

**Issue by theherk** [wez/wezterm#4845]
**Is your feature request related to a problem? Please describe.**

I use some keymaps to directly spawn some commands. For example, lazygit.

```lua
{ key = "g", mods = "LEADER", action = wezterm.action.SpawnCommandInNewTab({ args = { os.getenv("SHELL"), "-c", "lazygit" }, label = "lazygit" }) },
```

It is done as a shell command to pick up my shell's environment. However, when I do, the tab title is "fish".

**Describe the solution you'd like**

It would be very nice if the `label` attribute which works for the command palette were also used as `tab.active_pane.title`.

**Describe alternatives you've considered**

This can nearly be accomplished by appending the paths to these applications to the environment in which Wezterm is running. Then I could spawn the application and the title would be set from the first arg of the command, which would be correct. But then I don't get my full shell's environment.

Just seems like a nice-to-have since this `label` field is available.

**Comment by theherk** [comment]
Actually, I tried another method, and it seems like it will be a solution but I'm missing something. What I did was provide a utility function to build a `Multiple` action, like this:

```lua
function module.launch(args)
  return wezterm.action.Multiple({
    wezterm.action.SpawnCommandInNewTab({ args = { os.getenv("SHELL"), "-c", table.unpack(args) } }),
    wezterm.action_callback(function(window, _)
      local title = args[1]
      window:active_tab():set_title(title)
    end),
  })
end
```

Then set the binding with:

```lua
{ key = "f", mods = "LEADER", action = util.launch({ "xplr" }) }
```

This allows me to launch everything in the context of my shell and gives me a variable I could use as the title for the new tab. However, setting it didn't work as I had hoped. I'm guessing `window:active_tab()` in this context is the active tab when the action is taken rather than as a result of the action taken. I must look into this further. If you have any wisdom @wez, let me know. Would that be __wezdom__?

**Comment by wez** [comment]
key assignments launched via perform_action (or directly in response to a key binding) that initiate asynchronous operations do no wait for those operations to complete, so `window:active_tab()` will likely see the tab that was active at the start of the key event.

What I'd suggest instead is to use `action_callback` and `mux` module to spawn things more directly; these functions do await the asynchronous parts:

```lua
{ key = "f", mods = "LEADER", action = wezterm.action_callback(function(window, pane)
     local tab, pane, window = window:mux_window():spawn_tab {
        args = { .... }
     }
     tab:set_title("my title")
end)},
```

See:
* https://wezfurlong.org/wezterm/config/lua/wezterm/action_callback.html
* https://wezfurlong.org/wezterm/config/lua/window/mux_window.html
* https://wezfurlong.org/wezterm/config/lua/mux-window/spawn_tab.html

**Comment by theherk** [comment]
Okay, I updated the launch method to:

```lua
function module.launch(args)
  return wezterm.action_callback(function(window, _)
    local tab, _, _ = window:mux_window():spawn_tab({
      args = { os.getenv("SHELL"), "-c", table.unpack(args) },
    })
    wezterm.log_info(args[1])
    tab:set_title(args[1])
  end)
end
```

But the new tab which correctly logs the title is still called "fish".

Log shows:

```
ᐅ wezterm
20:14:08.006  INFO   logging > lua: xplr
```

**Comment by wez** [comment]
do you have a custom https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html event handler?

**Comment by theherk** [comment]
Yes, sorry @wez. I did. I was fixing that right as you commented... as you can probably see above. I was using pane title only. This should probably be closed as such, since the solution is so simple.
