### ISSUE TITLE
Build error: undefined reference to `sd_listen_fds'

### ISSUE THREAD

**Issue by christianparpart** [wez/wezterm#485]
Hey, I was receiving this error since quite a while, and since it's not auto-fixing by waiting, I thought I'd give it a note here in this ticket system. Maybe something's wrong on my side, but I couldn't figure out what, if so.

## Build Environment

 - OS: Ubuntu 20.10 / X11
 - Linux: x84-64
 - Compiler: GCC 10.2.0
 - Rust version: rustc 1.49.0

## Dependencies

Did you run the `get-deps` script to install required system dependencies?
Was it successful? - YES

If building from the git repo, did you update the submodules?  Not doing this
is a common source of problems; see the information at
<https://wezfurlong.org/wezterm/install/source.html> for more information. - HELL YEAH

## The build output

```
....
  = note: /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): in function `_dbus_listen_systemd_sockets':
          (.text+0x201e): undefined reference to `sd_listen_fds'
          /usr/bin/ld: (.text+0x205f): undefined reference to `sd_is_socket'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error
error: could not compile `wezterm-gui`
```

**Comment by wez** [comment]
I think you need `sudo apt install libsystemd-dev` for this (and this should get added to `get-deps`)

**Comment by christianparpart** [comment]
Hey, I was almost to say fixed and close this ticket. Yes, your new dependency includes a man-page for this symbol and a pkg-config file that will include `libsystemd.so`, however, that file (checked with `nm`) does not export any symbols, so I wonder what might be wrong here. (I deleted the whole wezterm repo, did `rustup update`, then `git clone URL --recursive` followed by a `cargo build --release`. But the same error occurs.

**Comment by wez** [comment]
I don't have ubuntu 20 handy, but I do have ubuntu 18.  It says:

```
$ strings /lib/x86_64-linux-gnu/libsystemd.so.0.21.0 | grep listen
sd_listen_fds
sd_listen_fds_with_names
$ dpkg-query -S /lib/x86_64-linux-gnu/libsystemd.so.0.21.0
libsystemd0:amd64: /lib/x86_64-linux-gnu/libsystemd.so.0.21.0
```

So I'd suggest `sudo apt install libsystemd0`
