### ISSUE TITLE
Some glyphs need a cell-width greater than 1 to be fully visible

### ISSUE THREAD

**Issue by andreicorpo** [wez/wezterm#4852]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

-

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Some of the symbols for legacy computing (1FB70 - 1FB7F), are not displayed correctly if `cell_width` is 1 or less, depending on the font, it actually has to be greater.

### To Reproduce

With `cell_width = 0.8`:
![CleanShot 2024-01-25 at 12 36 41](https://github.com/wez/wezterm/assets/12585256/c9848531-f365-4fea-b21d-b16687427708)
With `cell_width = 1.2`:
![CleanShot 2024-01-25 at 12 38 17](https://github.com/wez/wezterm/assets/12585256/74f7abfd-d1ad-4201-8195-76ba25ca9775)
You can see the difference clearly for the last two symbols.

### Configuration

```lua
config.cell_width = 0.8
config.font = wezterm.font_with_fallback({
	{ family = "JetBrainsMonoNL Nerd Font" },
})
config.font_size = 11.3
```

### Expected Behavior

Glyphs should be visible correctly no matter what value is set for `cell_width`.

**Comment by wez** [comment]
Using any value of `cell_width` other than 1.0 will cause rendering problems because it works against the instructions defined in your chosen font.
I do not recommend using it.
The documentation warns that it can have undesirable effects, and what you are experiencing is one of them.

**Comment by andreicorpo** [comment]
I can understand that, but the glyphs are not displayed correctly even with `cell_width` set to the default value.
