### ISSUE TITLE
Improve Mouse/Selection behaviour

### ISSUE THREAD

**Issue by DaveWK** [wez/wezterm#4856]
**Is your feature request related to a problem? Please describe.**
The problem is the copy/paste and mouse selection seems to be inconsistent and broken at times. I suspect there are multiple problems going on, including wayland vs xorg and copy/pasting from one to the other, making a mouse selection in the window but having it "skip" or jump to a new location and not copy/pasting, or whether the mouse is "controlling" things within the terminal UI or if it is copy/pasting. Another issue is at times it seems to be ambiguous if highlighting something is enough to copy it to clipboard, or if right clicking is necessary.

**Describe the solution you'd like**
If wezterm opened a pop-up menu when right clicking that had copy/paste items it would be helpful. Additionally, it would be nice if there was some kind of visual feedback when a selection is copied to clipboard, and  also when a paste is attempted with an empty clipboard.

**Describe alternatives you've considered**
It may be possible to make some convoluted rules engine in the wezterm config to define the behaviour, but ultimately without some visual interaction/popup it is tedious to debug.

**Additional context**
I am not sure what the current expected behaviour is, but it seems like selection/highlighting with the mouse is somewhat broken. My usual flow is to highlight with a mouse, then either press control + c (or control + shift +c  if its konsole) to copy, or to right click and have it copy the highlighted text. Then to paste I either right click when I have no text selected or hit control + v/(control + shift + v for konsole). The problem is that if it has some kind of "enhanced terminal" or whatever causes the mouse to be able to interact with menus/text in things like vim, then it is not clear how to select text and paste.

**Comment by wez** [comment]
This sounds like a bug report in the guise of a feature request and the result is, unfortunately, not especially actionable for either purpose.
If something isn't working, please file a new bug report and include all the information necessary to reproduce it.
If you have a feature request, please open a new one with concrete information on what exactly the feature is or does.

Thanks!
