### ISSUE TITLE
Make shell configurable

### ISSUE THREAD

**Issue by rovf** [wez/wezterm#4865]
**Is your feature request related to a problem? Please describe.**
When I start wezterm, I always get a bash shell. I would like to configure the shell which is started inside the terminal. 

**Describe the solution you'd like**
This could be a configuration option in the .wezterm.lua file.

**Comment by gegoune** [comment]
1. you can change shell for your user (what OS are you using?)
2. set it via https://wezfurlong.org/wezterm/config/lua/config/default_prog.html

**Comment by wez** [comment]
This is covered plainly in the docs: https://wezfurlong.org/wezterm/config/launch.html
