### ISSUE TITLE
Cannot display Chinese characters correctly

### ISSUE THREAD

**Issue by yanxiang-wang** [wez/wezterm#4877]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240127-113634-bbcac864

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, it is the same

### Describe the bug

<img width="655" alt="image" src="https://github.com/wez/wezterm/assets/64343197/58f93464-1d50-42a9-b4fd-34c34afbbf58">

### Configuration

```
local wezterm = require 'wezterm';

local config = {}
config.font_size = 14
config.font = wezterm.font_with_fallback({
  {family="JetBrainsMonoNL Nerd Font", weight="Bold"},
  {family="FiraCode Nerd Font Mono", weight="Bold"},
})
config.window_padding = {
  left = 12,
  right = 12,
  top = 12,
  bottom = 12,
}
config.hide_mouse_cursor_when_typing = true
config.initial_cols = 120
config.initial_rows = 30
config.scrollback_lines = 100000
config.window_decorations = "RESIZE"
config.window_background_opacity = 1.0
config.enable_tab_bar = true
config.color_scheme = "Dracula (Official)"
config.tab_bar_at_bottom = false
config.use_fancy_tab_bar = true
config.keys = {
  -- CMD-t starts a new tab
  {
    key = 't',
    mods = 'CMD',
    action = wezterm.action.SpawnCommandInNewTab {
      -- args = { 'top' }, # add args here
    },
  },
}

return config
```

**Comment by yanxiang-wang** [comment]
The screenshots show the comparison between the previous version (left) and the latest version (right).

**Comment by wez** [comment]
Please share the logs; CTRL-SHIFT-L top open the debug overlay

**Comment by yanxiang-wang** [comment]
> Please share the logs; CTRL-SHIFT-L top open the debug overlay

Okay, opened, what should I do or type next?
The configurations are listed above. The bugs appears when I upgrade the wezterm to the latest version.

**Comment by wez** [comment]
I would expect there to be some error messages about not being able to find the right font.
If you're not seeing those, then as an alternative, try running:

```console
$ wezterm ls-fonts --text "PASTE THOSE TWO CHINESE CHARACTERS HERE"
```

wezterm will explain its plan for rendering the text.

**Comment by yanxiang-wang** [comment]
``` 
wezterm ls-fonts --text "你好"
LeftToRight
 0 你    \u{4f60}     x_adv=14 cells=2  glyph=1446 wezterm.font(".PingFang HK", {weight="Thin", stretch="Normal", style="Normal"})
                                      /System/Library/Fonts/PingFang.ttc index=33 variation=0, CoreText
 3 好    \u{597d}     x_adv=14 cells=2  glyph=2437 wezterm.font(".PingFang HK", {weight="Thin", stretch="Normal", style="Normal"})
                                      /System/Library/Fonts/PingFang.ttc index=33 variation=0, CoreText
```
two versions show the same results.

**Comment by yanxiang-wang** [comment]
Also, the nerd font is not displaying correctly. You can see the `icon` before `Python` is `?` for the latest version.

**Comment by wez** [comment]
the ls-fonts output is what I'd expect to see, and is what I see here on my mac.
I can't reproduce what you're seeing in wezterm itself though.

Can you run `wezterm -n` (that skips loading your config) and see if the Chinese characters render correctly when you paste them into the terminal?

**Comment by wez** [comment]
I wanted to note that in your screenshot, the problematic text has a different color and style.  The characters do display when styled normally in that line that says "command not found".

**Comment by wez** [comment]
Compare the output from `env` when you run it in the latest version vs. the prior version; I suspect that the problem is actually that your shell is responsible for this somehow based on the environment.

**Comment by wez** [comment]
what might also be interesting is to copy the ?? characters out of the new version and paste them here to see what glyphs they actually represent

**Comment by yanxiang-wang** [comment]
> what might also be interesting is to copy the ?? characters out of the new version and paste them here to see what glyphs they actually represent
```
wezterm ls-fonts --text "🅒"
LeftToRight
 0 🅒    \u{1f152}    x_adv=11.428571428571429 cells=1  glyph=lastresorttemplate,4    wezterm.font(".LastResort", {weight="Regular", stretch="Normal", style="Normal"})
                                      /System/Library/Fonts/LastResort.otf, CoreText
```

**Comment by yanxiang-wang** [comment]
> the ls-fonts output is what I'd expect to see, and is what I see here on my mac. I can't reproduce what you're seeing in wezterm itself though.
> 
> Can you run `wezterm -n` (that skips loading your config) and see if the Chinese characters render correctly when you paste them into the terminal?

<img width="574" alt="image" src="https://github.com/wez/wezterm/assets/64343197/b1b27a43-f7fa-4f93-a20f-54c7818c3395">

**Comment by wez** [comment]
Please capture a terminal recording, so that I can capture exactly what is being output to your terminal.

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by yanxiang-wang** [comment]
[wezterm-recording-hf6CcC.cast.txt](https://github.com/wez/wezterm/files/14075088/wezterm-recording-hf6CcC.cast.txt)

**Comment by yanxiang-wang** [comment]
the problem may be related to my zsh config where I use the starship. When I comment it, it can show the characters correctly. Although I don't why it can works in the version of July 2023, it should not be discussed as a bug of this year's release.

**Comment by wez** [comment]
With your recording I can reproduce this issue; the system LastResort font is being suggested by core text in preference to other more suitable fonts, but only when using bold text! I have a fix ready here.

**Comment by yanxiang-wang** [comment]
> With your recording I can reproduce this issue; the system LastResort font is being suggested by core text in preference to other more suitable fonts, but only when using bold text! I have a fix ready here.

Wow! Great!

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by yanxiang-wang** [comment]
[wezterm-recording-00Qfbm.cast.txt](https://github.com/wez/wezterm/files/14075282/wezterm-recording-00Qfbm.cast.txt)
```
➜ wezterm -n
18:30:35.565  WARN   wezterm_font > No fonts contain glyphs for these codepoints: \u{1f152}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
```

**Comment by wez** [comment]
It's telling you that you don't have a font with that glyph. You can follow the instructions in the message to resolve it; either find and install a font that has it, or disable that warning.

**Comment by wez** [comment]
I realized that that is the same codepoint that we were seeing earlier, so I looked into this a bit more.
It seems as though macOS won't tell us which fonts contains U+1f152 when asked about it.
Digging into things a bit more, https://github.com/wez/wezterm/issues/3546 is a similar issue on Windows.
In there it was discovered that the PingFang font has that codepoint, and that happens to be the same font that macOS will tell wezterm to use when rendering the Chinese characters from your example.

I don't know how to get macOS to return the same result for this particular codepoint, but what you can do to workaround that is to add PingFang to your `font_with_fallback` list explicitly.

**Comment by wez** [comment]
OK, I went back to look at some older logic that we used prior to fixing https://github.com/wez/wezterm/issues/4099 and found that it could produce a matching font for this codepoint, so I've added that fallback logic as a fallback for this fallback logic(!) and it seems to do the job for your scenario.

**Comment by wez** [comment]
That should show up in the nightly builds within the next hour

**Comment by yanxiang-wang** [comment]
The lastest nightly version works well now.
