### ISSUE TITLE
Tabs in fancy bar take time to update after closing a tab

### ISSUE THREAD

**Issue by lokesh-krishna** [wez/wezterm#4880]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20240127-131129-6de7c604

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Creating a new tab immediately updates the fancy tab bar but upon closing a tab, it takes the bar a second or two to update. I can get it to update instantly by creating a new tab again. 

### To Reproduce

Create a new tab.
Exit/quit the tab.
Tab bar continues to show the closed tab for a second or two.

### Configuration

```
config.use_fancy_tab_bar = true
```

### Expected Behavior

Quitting a tab instantly updates the tab bar, the same way that creating one instantly updates it.

**Comment by bakageddy** [comment]
Same Occurs for me in X11 too.
Version: 20240127-131129-6de7c604

**Comment by gegoune** [comment]
Same observed with `use_fancy_tab_bar = false` on `wezterm 20240127-125307-11c1dd65`.

**Comment by jankatins** [comment]
Can also confirm on mac (don't set use_fancy_tab_bar, so probably false). 

Probably related to https://github.com/wez/wezterm/commit/7f3a8355486b578405b96a5157ebfdab8d39f015 ? So probably another place/state when to call `self.update_title_post_status();` ?

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by kerjes** [comment]
Tested "nightly build, version: "wezterm 20240128-080125-0b2b85d5" and the delay is gone, works perfectly :100:
