### ISSUE TITLE
Add space between modifiers and key in CommandPalette

### ISSUE THREAD

**Issue by szinn** [wez/wezterm#4885]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240127-113634-bbcac864

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In CommandPalette, using FiraCode Nerd Font, the key modifiers and key are very close together, could use a space there
<img width="503" alt="Screenshot 2024-01-28 at 8 25 38 AM" src="https://github.com/wez/wezterm/assets/449824/3407105d-4152-494f-ba56-fa91147a2a6d">

### To Reproduce

Show command palette

### Configuration

```
config.font = wezterm.font {
    family = 'FiraCode Nerd Font',
    weight = 'Regular',
    harfbuzz_features = { 'calt=1', 'clig=1', 'liga=1' },
}
config.font_size = 11.0
config.line_height = 1.0

config.window_background_opacity = 1.0
config.window_decorations = "RESIZE"
config.window_close_confirmation = "AlwaysPrompt"
config.scrollback_lines = 3000
config.default_workspace = "main"
```

### Expected Behavior

A small space-gap between modifier and key

**Comment by szinn** [comment]
Could use a small gap between the modifier elements too - very packed together!

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by szinn** [comment]
Built it from source and LGTM - was happy to see that it built without extra goo like many projects seem to need.
