### ISSUE TITLE
Unwanted transparency

### ISSUE THREAD

**Issue by BlackCherryCat** [wez/wezterm#4886]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240127-113634-bbcac864

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I updated to version 20240127-113634-bbcac864 the wezterm interface began to have transparency, and I don't know how to set it opaque

### To Reproduce

Update from '20230712-072601-f4abf8fd' to '20240127-113634-bbcac864' in Windows

### Configuration

-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
	config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

config.font = wezterm.font("FiraCode Nerd Font Ret")

-- For example, changing the color scheme:
config.color_scheme = "Laser"
config.default_prog = { "D:/Scoop/apps/pwsh/current/pwsh.exe" }
-- and finally, return the configuration to wezterm
return config

### Expected Behavior

Have the same opacity as before

**Before updating:**
![Captura de pantalla 2024-01-28 164456](https://github.com/wez/wezterm/assets/68470515/5943ff1a-3a62-4b0e-bc5f-1051b1c084d3)

**After updating:**
![Captura de pantalla 2024-01-28 164822](https://github.com/wez/wezterm/assets/68470515/486a314e-ad3e-4a32-8f21-b483fb0d6449)

**Comment by wez** [comment]
try setting `config.front_end = 'OpenGL'`

**Comment by BlackCherryCat** [comment]
that solves my problem, but, at the cost of changing the rendering API? I will guess that the WebGpu rendering API comes with more personalization and styling, but using wezterm with OpenGL will not make it perform worse? and, It's impossible to change transparency settings with WebGpu enabled?

**Comment by wez** [comment]
The level of WebGpu support varies on different platforms and hardware combinations. For yours it sounds broken and incomplete, and that that you should therefore use OpenGL instead.
The primary difference between them is that webgpu will tend to use vulkan by default. In theory, vulkan applications can achieve higher performance and throughput than opengl, but in the case of wezterm, the performance difference is unlikely to be noticeable to a human anyway.

**Comment by BlackCherryCat** [comment]
Okay, thanks for your information and for solving my problem. Will see if in the future the WebGpu API is better implemented
