### ISSUE TITLE
Toast Notifications

### ISSUE THREAD

**Issue by wez** [wez/wezterm#489]
This issue tracks the state of toast notification support.

## OS level support

Whether we can actually show a notification in the desktop environment.

|OS               | Basic Notification  | Click Handling  |
| --------------|------------|-------------|
|Linux           | Yes         |  Yes         |
|*BSD     | Yes, in nightly | <-- |
|macOS       | Yes          | Yes         |
|Windows    | Yes          | Yes  |

## Escape sequence support

Do we have plumbing to allow an app to show a notification.

|Sequence | Implemented | Reference |
|--------------|--------------------|---------------|
| OSC 9     | 20210314-114017-04b7cedd | `printf "\e]9;%s\e\\" "hello there"`  from original [iTerm](https://iterm2.com/documentation-escape-codes.html). Note that this conflicts with [ConEmu](https://conemu.github.io/en/AnsiEscapeCodes.html#ConEmu_specific_OSC) |
| OSC 99  | No                   | `printf "\e]99;;%s\e\\" "hello there"` [kitty spec](https://github.com/kovidgoyal/kitty/blob/master/docs/protocol-extensions.rst#desktop-notifications) |
| OSC 777 | 20210314-114017-04b7cedd | `printf "\e]777;notify;%s;%s\e\\" "title" "body"` [rxvt - call perl extension named "notify"](https://manpages.debian.org/testing/rxvt-unicode/urxvt.7.en.html) |

## Multiplexer support

Whether notifications can traverse multiplexer boundaries

|Protocol | Supported |
|-----------|----------------|
|wezterm mux codec | Nightly |
|tmux CC | No |

**Comment by bew** [comment]
NOTE: OSC99 is not only kitty's spec, it is based on an ongoing work to properly define a spec for desktop notifications available here: https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/13

**Comment by bew** [comment]
Could we have an option to configure the urgency of the raised notification? Currently it is ALWAYS at the `critical` level.
I can't find a way to configure this in the OSC's documentation so I guess the terminal should have that.

An option like `notification_urgency = "normal"`

On linux `notify-send` can specify urgency with `-u URGENCY`, like: `notify-send -u normal Hello!`

The urgency levels are: low, normal, critical (see https://developer.gnome.org/notification-spec/#urgency-levels)
It is passed in the hints dict: `"urgency" | byte | The urgency level`

**Comment by wez** [comment]
I'm not opposed to adding an option, provided that it has meaningful effect to balance out the additional complexity/maintenance cost for that concept in the code.   I can't see a noticeable difference between the urgency levels with notify-send.
The urgency concept appears to be an optional unix specific thing that doesn't do anything on eg: GNOME.

**Comment by Logarithmus** [comment]
What's the hell is a toast notification? And how can notifications be useful in a terminal emulator? We already have `dbus` for that.

**Comment by wez** [comment]
Please be mindful of the tone of your comments!

See https://ux.stackexchange.com/a/12000

Support for this is present in wezterm because there are at least 3 different broadly used escape sequences as prior art in other terminal emulators that map to this concept.

On unix systems, wezterm uses dbus to trigger them.

**Comment by Logarithmus** [comment]
> Please be mindful of the tone of your comments!
> 
> See https://ux.stackexchange.com/a/12000
> 
> Support for this is present in wezterm because there are at least 3 different broadly used escape sequences as prior art in other terminal emulators that map to this concept.
> 
> On unix systems, wezterm uses dbus to trigger them.

Sorry for for a bit harsh tone, didn't want to offend you

**Comment by mborejdo** [comment]
fwiw: currently the windows notifications do not work for me. If I substitute the appid "org.wezfurlong.wezterm" with ""{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WindowsPowerShell\\v1.0\\powershell.exe" (in wezterm-toast-notification\src\windows.rs) I am getting back alerts.

**Comment by wez** [comment]
@mborejdo did you install using the setup.exe installer?
