### ISSUE TITLE
Catppuccin color schemes incorrect color

### ISSUE THREAD

**Issue by mangkoran** [wez/wezterm#4894]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240127-113634-bbcac864

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Catppuccin color schemes seems have incorrect color applied.

![image](https://github.com/wez/wezterm/assets/57625126/77d9b9a7-752f-443a-a684-5005344e3aaa)

### To Reproduce

1. set color_scheme = "Catppuccin Mocha"

### Configuration

```
return { color_scheme = "Catppuccin Mocha" }
```
### Expected Behavior

Color scheme works as normal

`20230712-072601-f4abf8fd`
![image](https://github.com/wez/wezterm/assets/57625126/0f3840ae-a9e5-4098-a027-9559538decd2)

### Anything else?

It seems it also affects several other color schemes

**Comment by wez** [comment]
![image](https://github.com/wez/wezterm/assets/117777/97dfcb5f-deb7-450d-a7bd-d7105f7adc88)

Seems to work fine here; I suspect that something else is going wrong for you.
Where are your logs?
Please try running without the rest of your config like this:

```console
$ wezterm -n --config "color_scheme='Catppuccin Mocha'"
```

**Comment by mangkoran** [comment]
It is still the same.

![image](https://github.com/wez/wezterm/assets/57625126/fbad3bbe-cba4-4020-a193-faf389a62fd3)

**Comment by wez** [comment]
Try setting: `front_end = "OpenGL"`

**Comment by mangkoran** [comment]
Just in time I saw your [recent commit](https://github.com/wez/wezterm/commit/1e552d764349522dabffeb240feb5b2728eff3d8), I tried using OpenGL and now it works as expected.

![image](https://github.com/wez/wezterm/assets/57625126/ced14f51-b807-4ccf-8201-c2a0e35afcd6)

Thank you very much!
