### ISSUE TITLE
How to set default TerminalSize?

### ISSUE THREAD

**Issue by QiutianDog** [wez/wezterm#4895]
**Background**
When I open the WezTerm, it's terminal size is small.
I want to set default terminal size, but i couldn't find any configuration in docs.
I just find some font size configuration.

I can run `wezterm` in console to check the terminal size.
```bash
$ wezterm
16:23:14.213  INFO   wezterm_gui > Spawned your command via the existing GUI instance. Use wezterm start --always-new-process if you do not want this behavior. Result=SpawnResponse { tab_id: 2, pane_id: 2, window_id: 2, size: TerminalSize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384, dpi: 0 } }
```

This was manually adjusted by me,I like this terminal size, but when I open the weterm, I have to manually adjust it every time.
`TerminalSize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384, dpi: 0 }`

**So how do I set the default size of the terminal?**

this is my wezterm.lua
```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {
  
  font_size = 12,
  font = wezterm.font("JetBrainsMonoNL Nerd Font", { weight = "Regular" }), 

  color_scheme = "Catppuccin Mocha",
  
  use_fancy_tab_bar = false,
  hide_tab_bar_if_only_one_tab = true,
  window_decorations = "RESIZE",
  show_new_tab_button_in_tab_bar = false,
  window_background_opacity = 0.9,
  macos_window_background_blur = 70,
  text_background_opacity = 0.9,
  adjust_window_size_when_changing_font_size = false,

  window_padding = {
    left = 5,
    right = 5,
    top = 20,
    bottom = 5,
  }
}

-- and finally, return the configuration to wezterm
return config
```

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/config/initial_cols.html
https://wezfurlong.org/wezterm/config/lua/config/initial_rows.html

**Comment by QiutianDog** [comment]
Thank you very much！
