### ISSUE TITLE
Getting "Update Available" after building from source

### ISSUE THREAD

**Issue by sommerper** [wez/wezterm#4896]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

PopOS tiling

### WezTerm version

20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After building from source the installed version is `20240128-202157-1e552d76` and I get `WezTerm Update Available` message when opening a new tab.

Clicking on the link i'm directed to the changelog page where the latest release is `20240127-113634-bbcac864`.

So I'm guessing my currently installed version is one day newer?

### To Reproduce

1. Build and install from source.
2. Open new tab an see `WezTerm Update Available` info text.

### Configuration

no config

### Expected Behavior

There should be no `WezTerm Update Available` text.

**Comment by GZLiew** [comment]
same here my current version is 20240128-202157-1e552d76

**Comment by wez** [comment]
Please share the logs! CTRL-SHIFT-L will open the debug overlay and may show some additional information

**Comment by LvanderGoten** [comment]
After a reboot the message disappeared in my case

**Comment by sommerper** [comment]
I'm doing a
```
git pull
cargo run --release --bin wezterm
```
on the `main` branch to update.

Running your command gives the following output:
```
❯ cat .tag
$ git "-c" "core.abbrev=8" "show" "-s" "--format=%cd-%h" "--date=format:%Y%m%d-%H%M%S"
$ cat .git/refs/heads/main
[bat error]: '.tag': No such file or directory (os error 2)
zsh: command not found: $
zsh: command not found: $
```

And checking the files it is indeed missing the `.tag` file.

**Comment by sommerper** [comment]
ouh! you're right. I was too much in a hurry.

```
wezterm --version
wezterm 20221221-003158-4b3660d1
```

```
git "-c" "core.abbrev=8" "show" "-s" "--format=%cd-%h" "--date=format:%Y%m%d-%H%M%S"
20221221-003158-4b3660d1
```

```
cat .git/refs/heads/main
4b3660d166196025d45d97fa29af8e9405b830b5
```

**Comment by wez** [comment]
You're building and running 4b3660d1
You should use `git pull --rebase` to pull and rebase on the current version.

**Comment by wez** [comment]
also: that version is not consistent with what you told me earlier. It's possible you have multiple different versions of wezterm installed and things are getting confused.

**Comment by sommerper** [comment]
Sorry, I pull the latest version daily so that's why the version number changed.

Here is what I just did:
```
❯ wezterm --version
wezterm 20221221-003158-4b3660d1
```

```
❯ git reset HEAD --hard
❯ git pull --rebase
❯ cargo build --release --bin wezterm
```

```
❯ git "-c" "core.abbrev=8" "show" "-s" "--format=%cd-%h" "--date=format:%Y%m%d-%H%M%S"
20240202-193942-c3d37f9e

❯ cat .git/refs/heads/main
c3d37f9edae6951bbb564197a62bb433a289ff4f

❯ wezterm --version
wezterm 20240202-193942-c3d37f9e
```

I hope that's a better report than before.

**Comment by wez** [comment]
with that version now being up to date, you should no longer see the "update available" message.

**Comment by sommerper** [comment]
Hmm.. but I do. But I've turned off the new version message with `check_for_updates = false`
and I don't get it anymore. Which is fine for me because I update pretty often anyway.

But thanks for trying to help! Wezterm is the best there is =)
