### ISSUE TITLE
Unable to launch WezTerm installed via flatpak

### ISSUE THREAD

**Issue by TraceyC77** [wez/wezterm#4900]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE Plasma Version: 5.27.10

### WezTerm version

20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

After installing WezTerm via flatpak, it fails to launch from the menu icon or terminal

### To Reproduce

Install WezTerm via flatpak
Click the menu icon

### Configuration

no config

### Expected Behavior

WezTerm launches

### Logs

When launching from command line, using the invocation from the menu item:

```bash
❯ flatpak run --branch=stable --arch=x86_64 --command=wezterm org.wezfurlong.wezterm start --cwd .
15:54:30.951  ERROR  wezterm_gui::frontend > Failed to create window: with_egl_lib failed: with_egl_lib(libEGL.so.1) failed: egl GetDisplay: BAD_PARAMETER, libEGL.so: libEGL.so: cannot open shared object file: No such file or directory, with_egl_lib(libEGL.so.1) failed: egl GetDisplay: BAD_PARAMETER, libEGL.so: libEGL.so: cannot open shared object file: No such file or directory
```

On my system, `$XDG_RUNTIME_DIR/wezterm` does not exist. The flatpak creates this:
`/run/user/1000/.flatpak/org.wezfurlong.wezterm/`

The logs are actually in
`/run/user/1000/.flatpak/org.wezfurlong.wezterm/xdg-run/wezterm/wezterm-gui-log-2.txt `
That only has the same error I saw when trying to launch on command line.

### Anything else?

From the error, it seems like a needed library is not packaged in the flatpak
I haven't tried to reproduce with a nightly build, I don't think there's a nightly version of the flatpak

## System Information:
Operating System: Solus 4.5
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.6.12-271.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

I'm happy to help provide other information or do other troubleshoot to help out.

**Comment by wez** [comment]
I can't reproduce this error with the current flatpak version `20240128-202157-1e552d76`.
I wonder if this is somehow satisfied implicitly on my system?

do you see Mesa show up in `flatpak list`?

If not, try `flatpak install org.freedesktop.Platform.GL.default` and see if maybe that helps.

**Comment by julianskartor** [comment]
Hello, I got the same error since I updated to latest version. I'm also using wezterm installed via flatpak.

**Comment by julianskartor** [comment]
Mesa does show up in my `flatpak list` output:

```
Mesa                            org.freedesktop.Platform.GL.default             23.3.0                              22.08                  system
```

**Comment by julianskartor** [comment]
Found there was a pending update to "Freedesktop Platform", installing that solved the issue for me!
