### ISSUE TITLE
Switch to NO_HINTING degrades font quality

### ISSUE THREAD

**Issue by nathanchance** [wez/wezterm#4902]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240128-202157-616b218e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After the switch to `NO_HINTING` in https://github.com/wez/wezterm/commit/616b218e328dd47e859beddc251c1980c49358a9, my font looks noticeably worse (left is prior to that change, right is with):

![Screenshot 2024-01-29 at 19 17 00](https://github.com/wez/wezterm/assets/11478138/4279645f-2885-4b8f-8b84-b7b22d70f4d6)

I do not necessarily mind the default change based on the reasoning in the commit message but as far as I can tell, there is no way to undo this and go back to the previous default, would it be possible to add some way to do this so I can get back to the way my font used to look?

### Configuration

```lua
local wezterm = require 'wezterm';
return {
  color_scheme = "Snazzy",
  debug_key_events = true,
  default_prog = {"/opt/homebrew/bin/fish", "-l"},
  default_cursor_style = 'BlinkingUnderline',
  font = wezterm.font_with_fallback({"Iosevka Term SS08", "SF Mono Regular"}),
  font_size = '14.0',
  initial_cols = 238,
  initial_rows = 51,
  keys = {
     {key="LeftArrow", mods="CMD", action={SendKey={key="Home"}}},
     {key="RightArrow", mods="CMD", action={SendKey={key="End"}}},
     {key="UpArrow", mods="CMD", action={SendKey={key="PageUp"}}},
     {key="DownArrow", mods="CMD", action={SendKey={key="PageDown"}}},
     {key="Enter", mods="ALT", action="DisableDefaultAssignment"},
     {key="t", mods="ALT", action=wezterm.action.ShowTabNavigator},
  },
  window_padding = {
    left = 10,
    right = 10,
    top = 5,
    bottom = 5,
  },
  visual_bell = {
    fade_in_function = 'EaseIn',
    fade_in_duration_ms = 150,
    fade_out_function = 'EaseOut',
    fade_out_duration_ms = 150,
  }
}
```

**Comment by hyperpuncher** [comment]
I think you can set `freetype_load_flags = "DEFAULT"` to go back to the previous config.
https://wezfurlong.org/wezterm/config/lua/config/freetype_load_flags.html

**Comment by nathanchance** [comment]
Based on my understanding of the code in question, I don't think that suggestion will work because the values in the `freetype_load_flags` config basically get bitwise OR'd against the default flags, so there is no way to mask out `NO_HINTING`.

https://github.com/wez/wezterm/blob/c4f16fe3391b3b447725c10226679a6b47b5e972/config/src/font.rs#L323-L347

If it were possible to do something like `freetype_load_flags = "~NO_HINTING"` or whatever other syntax would be more suitable for that task, that would be sufficient for me.

**Comment by wez** [comment]
Ah, good catch with the `::default()` thing. 47f647cadcaa0f06df107999221c661a0ff5017d should let you assign `DEFAULT`.  That should be available in a nightly build within about an hour.

I'm curious what it is you see as different between the two settings, as I can't easily discern an obvious difference from your screen shot.  Would you mind annotating it to call out where you see the the divergence?

**Comment by nathanchance** [comment]
I suppose it is kind of hard to see with it side by side. Perhaps two separate images that can be easily flipped between would help?

<details>
<summary>Full screenshots between DEFAULT and NO_HINTING change</summary>

![Screenshot 2024-01-29 at 22 57 20](https://github.com/wez/wezterm/assets/11478138/2d20e2eb-029b-4d6f-aa5a-253d3c2e7d7b)

![Screenshot 2024-01-29 at 22 57 29](https://github.com/wez/wezterm/assets/11478138/32602449-00d1-4c8a-9eb4-391e1ee9e812)

</details>

It is somewhat hard to me to describe but it seems like the font does not "pop" as much with `NO_HINTING` and it seems like the font gets squished down slightly. It is quite minor when I flip back and forth between it on the images but it just does not look good to me.

I can confirm that I can switch back to `DEFAULT` now. Just doing that alone did not restore how my font looked before though, it seems like the change to OpenGL appears to affect it as well?

<details>
<summary>Screenshots between OpenGL and WebGpu</summary>

![Screenshot 2024-01-29 at 22 57 38](https://github.com/wez/wezterm/assets/11478138/ceec535b-5860-49f8-bd39-75744f3065a1)

![Screenshot 2024-01-29 at 22 59 01](https://github.com/wez/wezterm/assets/11478138/00b87376-0e89-4c84-b429-197510f9219d)

</details>

Going back to `WebGpu` seems to look better to me, so I think we are all good here? I'll close this up, feel free to reopen if you feel it necessary.
