### ISSUE TITLE
Font rendering changed with latest version

### ISSUE THREAD

**Issue by giann** [wez/wezterm#4908]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Font rendering suddenly got worse:

Before (20230712-072601-f4abf8fd):
![Screenshot 2024-01-30 at 13 41 51](https://github.com/wez/wezterm/assets/584398/d31330c5-a945-46e9-8a43-3a0903ad72db)

Now (20240128-202157-1e552d76):
![Screenshot 2024-01-30 at 13 40 32](https://github.com/wez/wezterm/assets/584398/9efb01ba-cf1d-42cd-ab29-34fb018610f2)

I tried playing with some font related config with no success.

### Configuration

```lua
local wezterm = require("wezterm")

local function schemeForAppearance(appearance)
        if appearance:find("Dark") then
                return "ayu-dark"
        else
                return "ayu-light"
        end
end

return {
        font = wezterm.font("Iosevka Term SS04"),
        color_scheme = schemeForAppearance(wezterm.gui.get_appearance()),
        enable_tab_bar = true,
        hide_tab_bar_if_only_one_tab = true,
        initial_cols = 120,
        initial_rows = 39,
        audible_bell = "Disabled",
        line_height = 1.02,
        automatically_reload_config = true,
        enable_tab_bar = false,
}
```

**Comment by lukasbindreiter** [comment]
I encountered the same issue - with the latest version the font seems very blurry and not sharp.

I think it is somehow related to Monitor DPI scaling, because for me it only was like this on my external monitor, for the built-in Mac display it looked the same as before.

Downgrading to the latest 2023 version resolved the issue again.

I tried setting `config.dpi = 144`, with that setting it looked sharp again, but on the built-in display it is way too large then so that's also not really an option. 😅

**Comment by hyperpuncher** [comment]
You can set `freetype_load_flags = "DEFAULT"` to get back previous font sharpness. It's mostly needed on low PPI displays (e.g., <100)

**Comment by wez** [comment]
The default behavior for `freetype_load_flags` in nightly builds is to use `NO_HINTING` when the dpi is >= 100, otherwise `DEFAULT`

**Comment by ericuni** [comment]
I have the same issue too.
It can not display Chinese rightly.
<img width="566" alt="image" src="https://github.com/wez/wezterm/assets/2225088/dff446b3-2a2d-409b-afe3-b686f1f8138b">

environment
```plain
Debug Overlay
wezterm version: 20240128-202157-1e552d76 x86_64-apple-darwin
Window Environment: macOS 13.4 (22F66)
OpenGL: AMD Radeon Pro 555X OpenGL Engine 4.1 ATI-4.12.7
```

**Comment by wez** [comment]
@ericuni please file a separate issue
