### ISSUE TITLE
Colors are very different after update

### ISSUE THREAD

**Issue by duarteocarmo** [wez/wezterm#4909]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

macos

### WezTerm version

20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After updating to 20240128-202157-1552d76 from 20230712-072601-f4abf8fd, colors look noticeably different. 

![image](https://github.com/wez/wezterm/assets/26342344/f2a36255-e00b-4f11-b90d-4bdb995033c5)
![image](https://github.com/wez/wezterm/assets/26342344/77bd57d6-d522-4b75-9c37-b2a65c2ebaf1)

### To Reproduce

Use the config provided on macos and see differences

### Configuration

```lua

local wezterm = require 'wezterm'

local config = {}


if wezterm.config_builder then
  config = wezterm.config_builder()
end


function scheme_for_appearance(appearance)
  if appearance:find 'Dark' then
 
    return 'Modus-Vivendi'
  else
 
    return 'Modus-Operandi'
 
  end
end

wezterm.on('window-config-reloaded', function(window, pane)
  local overrides = window:get_config_overrides() or {}
  local appearance = window:get_appearance()
  local scheme = scheme_for_appearance(appearance)
  if overrides.color_scheme ~= scheme then
    overrides.color_scheme = scheme
    window:set_config_overrides(overrides)
  end
end)


config.hide_tab_bar_if_only_one_tab = true

config.window_close_confirmation = 'NeverPrompt'
config.freetype_load_flags = 'NO_HINTING'



-- font
config.font = wezterm.font 'Noto Sans Mono'
-- In newer versions of wezterm, use the config_builder which will
-- config.font =
--   wezterm.font('Noto Sans Mono', { weight = 'Bold', italic = false })
config.hyperlink_rules = wezterm.default_hyperlink_rules()

-- make task numbers clickable
-- the first matched regex group is captured in $1.
table.insert(config.hyperlink_rules, {
  regex = [[\b[tt](\d+)\b]],
  format = 'https://example.com/tasks/?t=$1',
})

-- make username/project paths clickable. this implies paths like the following are for github.
-- ( "nvim-treesitter/nvim-treesitter" | wbthomason/packer.nvim | wez/wezterm | "wez/wezterm.git" )
-- as long as a full url hyperlink regex exists above this it should not match a full url to
-- github or gitlab / bitbucket (i.e. https://gitlab.com/user/project.git is still a whole clickable url)
table.insert(config.hyperlink_rules, {
  regex = [[["]?([\w\d]{1}[-\w\d]+)(/){1}([-\w\d\.]+)["]?]],
  format = 'https://www.github.com/$1/$3',
})


config.keys = {
  { key = "LeftArrow",  mods = "OPT", action = wezterm.action { SendString = "\x1bb" } },
  { key = "RightArrow", mods = "OPT", action = wezterm.action { SendString = "\x1bf" } },
}

config.audible_bell = "Disabled"
-- config.front_end = "OpenGL"

return config

```

### Expected Behavior

No change on colors after update

### Anything else?

Thanks for this great work!

**Comment by jankatins** [comment]
This seems to have happend with a them sync from upstream: https://github.com/wez/wezterm/commit/bbcac86436fe31c98ad411ae880886619512fe94

So I guess if you want to keep the old colors, you have to fork the upstream theme.

**Comment by duarteocarmo** [comment]
@jankatins  - not sure what you mean. You mean the theme got an update and it's not an issue with wezterm?

**Comment by wez** [comment]
Note that `front_end = "OpenGL"` vs. `front_end = "WebGpu"` can change the appearance of colors on some OS/hardware combinations, so it's possible that this issue is related to the change of that default; it was accidentally set to WebGpu in the release a few days ago (I've had the nightly defaulting to WebGpu for some time to flush out problems), but the latest release and nightly now both default to OpenGL.

Another thing that may be a factor (although unlikely with latin text) is fallback font selection on macos could select thinner variants of fonts than you might expect.  You can confirm this by running `wezterm ls-fonts` and checking to see which fonts are returned.  That particular issue has a solution in nightly builds.

**Comment by jankatins** [comment]
@duarteocarmo Yes, there are changes to the themes, e.g. this is Modus-Operandi: https://github.com/wez/wezterm/commit/bbcac86436fe31c98ad411ae880886619512fe94#diff-762569dc9e5f2beabffe341688027d0afe4a86737f3ef6d3bf657ccc532f8c71L22505-L22541

![image](https://github.com/wez/wezterm/assets/890156/8b961b68-01d3-496b-bc65-a3e1437c5670)

I didn't really check the colors and what difference these changes made, but given that the numbers changed quite a lot, I can imagine that it looks different. E.g. the third color (some green) changed from 005e00 to 00663f.

**Comment by duarteocarmo** [comment]
Alright perfect! Thanks for letting me know!
