### ISSUE TITLE
Raster/Render issue

### ISSUE THREAD

**Issue by wez** [wez/wezterm#491]
The ongoing saga; for context see #331, #413, #470
The current issue is this:

```glsl
vec4 colorize_hsv(vec4 glyph, vec4 color) {
  vec3 hsv = rgb2hsv(color.rgb);
  hsv.b *= glyph.a;
  return vec4(hsv2rgb(hsv) / glyph.a, glyph.a);
}
```

When converting hsv -> rgb, the code above is dividing by the alpha to compensate for the implied alpha-multiplication that results from setting the alpha value on the returned pixel.

The purpose of that is to prevent the darker anti-aliasing pixels from being too dark, which is what resulted in the darker pixel border/fringes that are visible with red on cyan background.

However, it over-corrects: the resultant text can appear to be a lot more bold and potentially "less curvy" as a result (as reported by @p00f)

The simplest thing to do is remove the ` / glyph.a` portion to fix the intensity of the text, but that will mean that the dark borders that @dmfay wanted to eliminate are back!

So, something else needs to be done here.  I think that doing some kind of manual gamma correction might be a path through this.

**Comment by wez** [comment]
![image](https://user-images.githubusercontent.com/117777/108613386-56070c80-73a6-11eb-9f30-0cf7f9acf8d5.png)
Left: 08b60431, Right: 82fc53d736226f8baa3e8fe097a596257afbb29e

@dmfay maybe this is finally it? :-)

**Comment by dmfay** [comment]
I don't want to jinx it but it's definitely looking right for me, out of the box:

![1613875253](https://user-images.githubusercontent.com/3075455/108614125-22d47580-73c6-11eb-94d1-eb86b5d48ef7.png)

I noticed the heavier font when I reset my settings the other day, but you'd already opened this. Everything looks correct now (wezterm left, termite right):

![1613876711](https://user-images.githubusercontent.com/3075455/108614352-c96d4600-73c7-11eb-9c43-008306c92b76.png)
