### ISSUE TITLE
Never load .bashrc when start wezterm and spawn a new tab

### ISSUE THREAD

**Issue by zw963** [wez/wezterm#4914]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME 45

### WezTerm version

20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When start a new wezterm session, it start immediately without load the $HOME/.bashrc.

if run it manually use `source ~/.bashrc`, it work.

this issue happen when i pressing `Ctrl + Shift + T` to spawn a new tab too.

Thanks.

### To Reproduce

No config

### Configuration

No config.

### Expected Behavior

Load .bashrc when start a new session or spawn a new tab

**Comment by wez** [comment]
wezterm launches a login shell by default. It is your responsibility to configure your shell startup to work appropriately for both the login and non-login cases.
If you'd rather not use a login shell, the documentation has information on how to change what wezterm launches:
https://wezfurlong.org/wezterm/config/launch.html#launching-programs

**Comment by zw963** [comment]
> wezterm launches a login shell by default. It is your responsibility to configure your shell startup to work appropriately for both the login and non-login cases.

Thanks for you answer, I tested it, wezterm will load `~/.profile` by default, so, if I understand correctly, are you saying that I can solve this issue with `source ~/. bashrc` in the `~/.profile`?

**Comment by wez** [comment]
You can either:
* Fix your shell startup so that it behaves the way you expect/require when `bash -l` is run
* Change your wezterm `default_prog = {'bash'}` to run a non-login shell

**Comment by zw963** [comment]
> You can either:
> 
>     * Fix your shell startup so that it behaves the way you expect/require when `bash -l` is run
> 
>     * Change your wezterm `default_prog = {'bash'}` to run a non-login shell

Thanks for you answer, both of them works! i selected latter.
