### ISSUE TITLE
Document WezTerm's Lua version (Lua 5.4)

### ISSUE THREAD

**Issue by bbkane** [wez/wezterm#4917]
**What page or section of the docs have an issue?**
The whole doc? I couldn't find it with a search at least.

![image](https://github.com/wez/wezterm/assets/6081085/d88862d8-be28-4d22-9d6e-c0fb0311eb3f)

**Describe the issue**

I couldn't find the Lua version Wezterm uses in the docs or in `wezterm --version`. I WAS able to find it via typing the debug overlay:

```
Debug Overlay
wezterm version: 20240128-202157-1e552d76 x86_64-apple-darwin
Window Environment: macOS 14.2.1 (23C71)
OpenGL: AMD Radeon Pro 560X OpenGL Engine 4.1 ATI-5.2.4
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
> _VERSION
"Lua 5.4"
```

Ideally I'd like to be able to find this in the docs and maybe in the output of `wezterm --version` or one of the lines printed out when you run the `Debug Overlay` (similar to "Window Environment: macOS 14.2.1 (23C71)").

**Comment by bbkane** [comment]
Also, if you don't mind me asking, what prompted you to choose Lua 5.4 over LuaJIT, which seems to be the popular choice? Standards compliance? Easy Rust integration?

Thanks for WezTerm, the Lua integration is letting me try wacky things like generating tab color based on current running process :D

**Comment by wez** [comment]
re: why not LuaJIT: I was burned by it in the past in a long running program with a large address space. The allocation strategy used in LuaJIT at that time (and perhaps still today) required that allocations from the OS fall within a 32-bit addressable range. If all of the lower pages in memory were occupied, it wouldn't be able to use any additional memory and would be subsequently unusable for the remaining lifetime of the process.
wezterm allocates many discrete lua contexts over its lifetime and this outcome would be an unacceptable runtime error that would prevent it from operating once encountered.

The main advantage of the JIT in LuaJIT is to improve performance of the lua code, but with the way that wezterm's integration is structured, most of the lua code is glue code and isn't performance critical in and of itself, so there isn't such a massive upside to having a JIT.

re: exposing the version, I think showing it in the debug overlay is reasonable.  Where would you like to see it in the docs?

**Comment by bbkane** [comment]
Thanks for the context on LuaJIT! Very informative.

Maybe a sentence at the beginning of the Lua reference, though I don't know
how to slot it in so it flows with the rest of the page -
https://wezfurlong.org/wezterm/config/lua/general.html

**Comment by willothy** [comment]
Totally understandable (and interesting!) reasons to not go with LuaJIT, but seeing this issue made me curious and I built Wezterm from source with the `luajit52` feature of `mlua` and it seems to work fine (assuming the user doesn't try to run non-5.1-compatible code).

Not suggesting switching to LuaJIT or anything of course, just thought it was interesting.

**Comment by wez** [comment]
@willothy you won't hit the problem I mentioned immediately; you need to let things run long enough that the 32-bit address range becomes too fragmented for luajit to consider it usable, then at that point you cannot create any more lua contexts.

**Comment by willothy** [comment]
> @willothy you won't hit the problem I mentioned immediately; you need to let things run long enough that the 32-bit address range becomes too fragmented for luajit to consider it usable, then at that point you cannot create any more lua contexts.

Oh yeah, that makes sense, thanks for clarifying! I meant more just in the way that the code is generally compatible and will at least build properly. I'm not going go be using the luajit build, just wanted to see if it would work at all out of curiosity.

Also, no noticeable performance difference (as expected) if anyone is interested in that.

**Comment by khvzak** [comment]
> re: why not LuaJIT: I was burned by it in the past in a long running program with a large address space. The allocation strategy used in LuaJIT at that time (and perhaps still today) required that allocations from the OS fall within a 32-bit addressable range. If all of the lower pages in memory were occupied, it wouldn't be able to use any additional memory and would be subsequently unusable for the remaining lifetime of the process. wezterm allocates many discrete lua contexts over its lifetime and this outcome would be an unacceptable runtime error that would prevent it from operating once encountered.
> 
> The main advantage of the JIT in LuaJIT is to improve performance of the lua code, but with the way that wezterm's integration is structured, most of the lua code is glue code and isn't performance critical in and of itself, so there isn't such a massive upside to having a JIT.
> 
> re: exposing the version, I think showing it in the debug overlay is reasonable. Where would you like to see it in the docs?

Not today apparently, the recent luajit (emedded to mlua `vendored`) uses Rust default global [allocator](https://github.com/mlua-rs/mlua/blob/1754226c7440ec6c194d2d678ec083b621d46ceb/src/memory.rs#L83) and cannot control from what address space allocate memory.
