### ISSUE TITLE
Cannot set font_size for bitmap font "Cozette"

### ISSUE THREAD

**Issue by erf** [wez/wezterm#4919]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I can't seem to be able to set the `font_size` for the [Cozette](https://github.com/slavfox/Cozette/releases) bitmap font. It's always the default size.

### To Reproduce

Just download the font and try my configuration.

### Configuration

```
local wezterm = require 'wezterm'

local m = {}

m.font = wezterm.font 'Cozette'

m.font_size = 23.0

return m
```

### Expected Behavior

I'd expect to see a upscaled font

**Comment by wez** [comment]
bitmap fonts are never scaled by wezterm. you can run `wezterm ls-fonts`  to see which sizes are available in a bitmap font. Please share what it shows for you.

**Comment by erf** [comment]
why can't you scale bitmap fonts in Wezterm? 

Here is a screenshot if i try to use Cozette vector. It becomes very tiny.

<img width="358" alt="Screenshot 2024-01-31 at 23 41 19" src="https://github.com/wez/wezterm/assets/1562523/3c08e475-a8fe-49bf-ba06-6a026e86ee49">

```
/Applications/WezTerm.app/Contents/MacOS/wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /Users/erlend/Library/Fonts/cozette.dfont, CoreText
  -- Pixel sizes: [13]
  {family="Cozette", weight=0, stretch="UltraCondensed"},

  -- /Users/erlend/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
~ % /Applications/WezTerm.app/Contents/MacOS/wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /Users/erlend/Library/Fonts/cozette.dfont, CoreText
  -- Pixel sizes: [13]
  {family="Cozette", weight=0, stretch="UltraCondensed"},

  -- /Users/erlend/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/erlend/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- /Users/erlend/Library/Fonts/cozette.dfont, CoreText
  -- Will synthesize italics
  -- Pixel sizes: [13]
  {family="Cozette", weight=0, stretch="UltraCondensed"},

  -- /Users/erlend/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/erlend/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- /Users/erlend/Library/Fonts/cozette.dfont, CoreText
  -- Pixel sizes: [13]
  {family="Cozette", weight=0, stretch="UltraCondensed"},

  -- /Users/erlend/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/erlend/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /Users/erlend/Library/Fonts/cozette.dfont, CoreText
  -- Will synthesize bold
  -- Pixel sizes: [13]
  {family="Cozette", weight=0, stretch="UltraCondensed"},

  -- /Users/erlend/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/erlend/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- /Users/erlend/Library/Fonts/cozette.dfont, CoreText
  -- Will synthesize italics
  -- Will synthesize bold
  -- Pixel sizes: [13]
  {family="Cozette", weight=0, stretch="UltraCondensed"},

  -- /Users/erlend/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/erlend/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- /Users/erlend/Library/Fonts/cozette.dfont, CoreText
  -- Will synthesize italics
  -- Pixel sizes: [13]
  {family="Cozette", weight=0, stretch="UltraCondensed"},

  -- /Users/erlend/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/erlend/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})

Title font:
wezterm.font_with_fallback({
  -- <built-in>, BuiltIn
  {family="Roboto", weight="Bold"},

  -- /Users/erlend/Library/Fonts/cozette.dfont, CoreText
  -- Pixel sizes: [13]
  {family="Cozette", weight=0, stretch="UltraCondensed"},

  -- /Users/erlend/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/erlend/Library/Fonts/NotoColorEmoji-Regular.ttf, CoreText
  -- Assumed to have Emoji Presentation
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",

})
```

**Comment by wez** [comment]
we don't scale bitmap fonts because they are intended to be displayed at the bitmap strike size; we restrict the available sizes to those defined in the font.  Arbitrarily scaling the bitmaps will make them look terrible, and folks that want bitmap fonts tend to want them because they want pixel perfect presentation.

It looks like there is a hidpi version of the font available for download; perhaps you want to use that one?

**Comment by erf** [comment]
actually there is a 'CozetteVector' that i can scale .. i'm just curious if there isn't a way to scale the fonts so they still remain the same shape e.g. by the power of two so that they still look good, or to use a nearest filtering so they still remain the same shape or something like that . various other terminals seem to support scaling of bitmap fonts but there are artifacts , although in some scales they seem to look okay

**Comment by erf** [comment]
I do off course respect your choice to not support this. Just curious if there wouldn't be possible to support this in some way that makes sense. E.g. could scale by doubling the size. But will close now as you said, you don't support it. Sorry for the noise.

**Comment by wez** [comment]
I think supporting powers of 2 is reasonable as a request, but there are complexities involved with that, because scaling bitmaps is not something that is handled by freetype and there would need to be logic expand out the hypothetical scaled bitmap sizes and address that in several different places.

There's a decent amount of work there and it is somewhat at odds with what most bitmap font users want: the bitmap to render at the pixel sizes defined by the designer.

I have no plans to work on this, but am open to a well-designed PR to do so.

**Comment by erf** [comment]
This could not be handled in the GPU layer? Yeah it sounds quite complex, and not something I'll prioritize working on in the near future, but a good reference for any takers!

**Comment by wez** [comment]
the actual resampling could be done in the GPU, but there is logic that happens at the font layer to resolve the font, realize that it is a bitmap, determine the candidate sizes and constrain the effective font size selected by the config and the keybindings that manipulate the active font scale, that all needs to happen ahead of even rasterizing the correct bitmap strike.

There is actually already logic to downscale large bitmaps (eg: Noto Color Emoji ships with 128x128 pixel bitmaps that need to be downsized before we put them into a texture atlas) so there may not be much work required for the actual resizing.  The hard parts are all around those earlier policy checks and constraints.

**Comment by erf** [comment]
I imagine there could also be some complexities regarding handling the bitmap font scaling in a different way than with vector fonts.
