### ISSUE TITLE
Bad key sequence with wezterm ssh on WSL2

### ISSUE THREAD

**Issue by rachartier** [wez/wezterm#4921]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20240131-075510-21af10e0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Hello,

I'm trying to configure ssh to connect to my local WSL2 session.
So far so good, I'm running the command `wezterm ssh -oPort=2222 <username>@localhost`

Once connected, it's impossible to enter the keys 1, 2, 3... or combinations such as CTRL+C.
For example, for 1, the key sequence ";2;49~" is printed, for CTRL+C it's "5;99~"...
My $TERM is xterm-256color, I've tried with others but without success.

I think it's important to point out that I'm on an AZERTY keyboard, and that to do 1, for example, you actually have to press "SHIFT+&".

I tried fiddling with the "enable_kitty_keyboard", "allow_win32_input_mode", "enable_csi_u_key_encoding" and "use_ime" parameters, but nothing helped.
And also by changing the LANG variables... but same problem.

On the other hand, as soon as I'm in TMUX, CTRL+C works, but 1, 2, 3... doesn't display anything.

What's more, if I open wezterm without using wezterm ssh, and connect to the session using ssh, there's no problem.

Thanks in advance.

### To Reproduce

Open wezterm with `wezterm ssh <username>localhost` to connect to a WSL2 session.

### Configuration

local wezterm = require("wezterm")
local config = {}

config.automatically_reload_config = true
config.default_domain = "WSL:Ubuntu"

config.font = wezterm.font_with_fallback({ "Cascadia Code", "Symbols Nerd Font" })

config.font_size = 14

config.harfbuzz_features = { "calt=1", "ss01=1", "liga=1", "clig=1" }
config.line_height = 1
config.underline_thickness = "2pt"
config.enable_kitty_graphics = true
config.allow_square_glyphs_to_overflow_width = "Always"
config.bold_brightens_ansi_colors = "BrightAndBold"

config.hide_tab_bar_if_only_one_tab = true
config.adjust_window_size_when_changing_font_size = false
config.selection_word_boundary = " \t\n{}[]()\"'`,;:│=&!%"
config.win32_system_backdrop = "Mica"
config.window_background_opacity = 0.0

config.window_close_confirmation = "NeverPrompt"

return config

### Expected Behavior

When I type CTRL+C, is to process CTRL+C as a good key sequence.
When I type a number, is to print it, not the key sequence.

**Comment by wez** [comment]
Please run through https://wezfurlong.org/wezterm/troubleshooting.html#debugging-keyboard-related-issues and share the debug information you collect.

**Comment by rachartier** [comment]
Hello,

Thanks for your response.

With `debug_keys_event`:
For "1"
```
23:43:00.476  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:43:00.477  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event KeyEvent { key: LeftShift, modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: true, handled: Handled(false) }), win32_uni_char: Some('\0') }
23:43:00.478  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > send to pane DOWN key=LeftShift mods=SHIFT | LEFT_SHIFT
23:43:00.532  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event RawKeyEvent { key: Physical(K1), modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, phys_code: Some(K1), raw_code: 49, scan_code: 2, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:43:00.533  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event KeyEvent { key: Char('1'), modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(K1), modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, phys_code: Some(K1), raw_code: 49, scan_code: 2, repeat_count: 1, key_is_down: true, handled: Handled(false) }), win32_uni_char: Some('1') }
23:43:00.534  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > send to pane DOWN key=Char('1') mods=SHIFT | LEFT_SHIFT
23:43:00.534  ←[32mINFO  ←[0m ←[1mwezterm_term::terminalstate::keyboard←[0m > key_down: sending "\u{1b}[27;2;49~", Char('1') SHIFT | LEFT_SHIFT
23:43:00.587  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event RawKeyEvent { key: Physical(K1), modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, phys_code: Some(K1), raw_code: 49, scan_code: 2, repeat_count: 1, key_is_down: false, handled: Handled(false) }
23:43:00.588  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event KeyEvent { key: Char('1'), modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(K1), modifiers: SHIFT | LEFT_SHIFT, leds: NUM_LOCK, phys_code: Some(K1), raw_code: 49, scan_code: 2, repeat_count: 1, key_is_down: false, handled: Handled(false) }), win32_uni_char: Some('1') }
23:43:00.588  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > send to pane UP key=Char('1') mods=SHIFT | LEFT_SHIFT
23:43:00.599  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: false, handled: Handled(false) }
23:43:00.600  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event KeyEvent { key: LeftShift, modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(LeftShift), raw_code: 16, scan_code: 42, repeat_count: 1, key_is_down: false, handled: Handled(false) }), win32_uni_char: Some('\0') }
23:43:00.601  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > send to pane UP key=LeftShift mods=NONE
```

For "CTRL+C":
```
23:44:25.746  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event KeyEvent { key: LeftControl, modifiers: CTRL | LEFT_CTRL, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL | LEFT_CTRL, leds: NUM_LOCK, phys_code: Some(LeftControl), raw_code: 17, scan_code: 29, repeat_count: 1, key_is_down: true, handled: Handled(false) }), win32_uni_char: Some('\0') }
23:44:25.747  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > send to pane DOWN key=LeftControl mods=CTRL | LEFT_CTRL
23:44:25.822  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event RawKeyEvent { key: Physical(C), modifiers: CTRL | LEFT_CTRL, leds: NUM_LOCK, phys_code: Some(C), raw_code: 67, scan_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }
23:44:25.823  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event KeyEvent { key: Char('c'), modifiers: CTRL | LEFT_CTRL, leds: NUM_LOCK, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(C), modifiers: CTRL | LEFT_CTRL, leds: NUM_LOCK, phys_code: Some(C), raw_code: 67, scan_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }), win32_uni_char: Some('\u{3}') }
23:44:25.825  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > send to pane DOWN key=Char('c') mods=CTRL | LEFT_CTRL
23:44:25.826  ←[32mINFO  ←[0m ←[1mwezterm_term::terminalstate::keyboard←[0m > key_down: sending "\u{1b}[27;5;99~", Char('c') CTRL | LEFT_CTRL
23:44:25.865  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(LeftControl), raw_code: 17, scan_code: 29, repeat_count: 1, key_is_down: false, handled: Handled(false) }
23:44:25.866  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event KeyEvent { key: LeftControl, modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(LeftControl), raw_code: 17, scan_code: 29, repeat_count: 1, key_is_down: false, handled: Handled(false) }), win32_uni_char: Some('\0') }
23:44:25.868  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > send to pane UP key=LeftControl mods=NONE
23:44:25.900  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event RawKeyEvent { key: Physical(C), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(C), raw_code: 67, scan_code: 46, repeat_count: 1, key_is_down: false, handled: Handled(false) }
23:44:25.901  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > key_event KeyEvent { key: Char('c'), modifiers: NONE, leds: NUM_LOCK, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(C), modifiers: NONE, leds: NUM_LOCK, phys_code: Some(C), raw_code: 67, scan_code: 46, repeat_count: 1, key_is_down: false, handled: Handled(false) }), win32_uni_char: Some('c') }
23:44:25.902  ←[32mINFO  ←[0m ←[1mwezterm_gui::termwindow::keyevent    ←[0m > send to pane UP key=Char('c') mods=NONE
```

For `wezterm show-keys --lua`, I do not have keybinds in my config, so it's all by default.

With `use_ime=true` same result as without.

Finally, I do not have any special program that can intercept keys or anything.

**Comment by wez** [comment]
`\u{1b}[27;2;49~` is the [modifyOtherKeys](https://invisible-island.net/xterm/modified-keys.html) encoding for `SHIFT-1`.

That mode is activated by an application emitting an escape sequence, and deactivated when the application emits a different escape sequence to turn it off.  It sounds like it has been turned on, but the shell doesn't fully support the mode, or alternatively, that wezterm is incorrectly encoding this key press in this way.  The latter is certainly possible!  I haven't heard of this issue in this context before; I have had one or two people mention that they had problems with `modifyOtherKeys` when running `emacs`.

What shell are you using? I wonder if that is a feature of the line editor in your shell?  Is it something you can try to disable?

Does your shell startup launch something that might turn it on, that terminates without turning it off?

I'd like to understand what is turning on this mode so that we can figure out where the miscommunication is happening and resolve it.

As a targeted workaround: try pressing CTRL-SHIFT-P to open the command palette, and then selecting the "Reset the terminal emulation state in the current pane" option. That should cancel that mode. If the application that is enabling the mode is the shell line editor, it is possible that it will just turn it back on again the next time it prompts for input.

**Comment by rachartier** [comment]
Yes, it's surprising! I had seen the issues with modifyOtherKeys and emacs, but I didn't think the problem might be related!

 I use zsh, but the problem persists with bash and sh.

bash (same as when I set it with `chsh`):
![image](https://github.com/wez/wezterm/assets/2057541/baf8a46b-992e-4f69-a170-bea8127c4323)

sh (same as when I set it with `chsh`):
![image](https://github.com/wez/wezterm/assets/2057541/8b408d46-68e2-4eba-83c7-9865e1fb74d7)

I did try to completely turn off my zsh config with:
![image](https://github.com/wez/wezterm/assets/2057541/1e2ced2c-2bf2-4087-a1a5-125fcce152c6)
But as you can see, the result is the same.

Without `starship` (the line editor):
![image](https://github.com/wez/wezterm/assets/2057541/05b02c8a-1086-49b4-8022-5f706fae24fb)

And finally, when I select "Reset the terminal emulation state in the current pane", same as all above :( 
![image](https://github.com/wez/wezterm/assets/2057541/3b44e309-1656-42d1-bd4b-cb33bc728905)

**Comment by rachartier** [comment]
Oh... I actually found it thanks to your suggestions...

It was "termium", a Codeium new thing that I've installed some times ago, which is launched automatically at each shell startup.
What a weird thing !

Sorry for taking up your time. Have a nice day/evening.

**Comment by wez** [comment]
ah, interesting! Perhaps this is worth filing an issue with the codeium folks, because that particular escape sequence is not good to leave activated!

You can use `wezterm record` to start a recording session, launch termium, then exit termium, and then exit the recording session.  An asciicast file will be written out.

You can then use `wezterm replay --explain-only` on that recording to see the various escape sequences emitted in a slightly more readable form.  I'm assuming that you'll see `modifyOtherKeys` being turned on, but not off.

**Comment by rachartier** [comment]
Yeah sure! I'll try to fill an issue to their repo.

Oh nice! I didn't know about `wezterm record`, it's a handy thing to have.

Thanks a lot!
