### ISSUE TITLE
Insert `act.Search` action into config.keys dynamically not work.

### ISSUE THREAD

**Issue by zw963** [wez/wezterm#4930]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME 45 + Wayland

### WezTerm version

20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Please check following code:

What i want to do is, add `{ key = 'w', mods = 'ALT', action = act.CopyTo 'Clipboard' }` and ` { key = 's', mods = 'CTRL', action = act.Search 'CurrentSelectionOrEmptyString' }` only if current process name is not `dte`, because i want use editor(dte) builtin feature of `Copy` and `Search`.

```lua
config.keys = {
 -- ...
}

key_index = #config.keys

wezterm.on(
  'update-right-status',
  function(window, pane)
    local info = pane:get_foreground_process_info()

    if info ~= nil and info.name ~= 'dte' then
      new_key = { key = 'w', mods = 'ALT', action = act.CopyTo 'Clipboard' }
      last_key = config.keys[key_index+1]

      if last_key ~= nil and last_key.key == 'w' and last_key.mods == 'ALT' then
        return
      end
      
      table.insert(config.keys, new_key)
      table.insert(config.keys, { key = 's', mods = 'CTRL', action = act.Search 'CurrentSelectionOrEmptyString' })
    end
  end
)
```

 The behavior of `Alt + w Copy to clipboard` is correct,  but, if add  `Ctrl + s act.Search` dynamically, when i pressing `Ctrl + s`, just can't input anything, the only thing i can do is pressing `Ctrl + c` to quit that state.

I tested, this is not a table.insert order issue.

### Configuration

check above

**Comment by wez** [comment]
You need to use https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html to make changes to the configuration dynamically

**Comment by zw963** [comment]
> You need to use https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html to make changes to the configuration dynamically

Sorry, I didn't really understand what you meant.

I tried following code, but it not work.

```lua
wezterm.on(
  'copy_to_hack',
  function(window, pane)
    local info = pane:get_foreground_process_info()
    local overrides = window:get_config_overrides() or {}

    if info ~= nil and info.name ~= 'dte' then
      window:perform_action(act.CopyTo 'Clipboard', pane)
    end

    window:set_config_overrides(overrides)
  end
)

config.keys = {
  -- ...
  { key = 'w', mods = 'ALT', action = act.EmitEvent 'copy_to_hack' },
}
```

What i expected is when i open `dte`, wezterm will release the control of `Alt + w`, instead,  give this keybinding to `dte` to manage。

But for current case, even `copy_to_hack` not perform any action, dte still cannot take over control of it, pressing `Alt + w` within `dte` just noop.

Thanks

**Comment by wez** [comment]
Sounds like you should use https://wezfurlong.org/wezterm/config/lua/keyassignment/SendKey.html to send Alt-W in the `else` case, instead of changing the config

**Comment by zw963** [comment]
> Sounds like you should use https://wezfurlong.org/wezterm/config/lua/keyassignment/SendKey.html to send Alt-W in the `else` case, instead of changing the config

Awesome! it works! Thanks very much!

```lua
wezterm.on(
  'search_hack_for_dte',
  function(window, pane)
    local info = pane:get_foreground_process_info()

    if info ~= nil and info.name ~= 'dte' then
      window:perform_action(act.Search 'CurrentSelectionOrEmptyString', pane)
    else
      window:perform_action(act.SendKey { key = 's', mods = 'CTRL' }, pane)
    end
  end
)

config.keys = {
  --- ...
  
  { key = 's', mods = 'CTRL', action = act.EmitEvent 'search_hack_for_dte' },
}
```

It seem like no `, window:set_config_overrides(overrides)`, it just work, so, that is unnecessary, right?

**Comment by zw963** [comment]
BTW, one more question, is there possible pass a argument in this way? 

e.g. i want hack ScrollByPage(page) this way.

```
wezterm.on(
  'ScrollByPagePlusHack',
  function(window, pane, page)
    local info = pane:get_foreground_process_info()

    if info ~= nil and info.name ~= 'dte' then
      window:perform_action(act.ScrollByPage, pane, page)
    else
      window:perform_action(act.SendKey { key = 'v', mods = 'CTRL' }, pane)
    end
  end
)
```

Then

```
  { key = 'v', mods = 'CTRL', action = act.EmitEvent 'ScrollByPagePlusHack', 1 },
```

As above, i want to pass number `1` into callback as `page` argument, but above code not work.

Thanks

**Comment by wez** [comment]
Look at: https://wezfurlong.org/wezterm/config/lua/wezterm/action_callback.html

**Comment by zw963** [comment]
> Look at: https://wezfurlong.org/wezterm/config/lua/wezterm/action_callback.html

Hi, checked, and no clue for me(a newbile for use lua), it's look like there is no way to pass extra args into callback?

**Comment by wez** [comment]
```lua
function scroll_by_page_plus_hack(window, pane, page)
    local info = pane:get_foreground_process_info()

    if info ~= nil and info.name ~= 'dte' then
      window:perform_action(act.ScrollByPage(page), pane)
    else
      window:perform_action(act.SendKey { key = 'v', mods = 'CTRL' }, pane)
    end
end
```

```lua
{ key = 'v', mods = 'CTRL', action = wezterm.action_callback(function(window, pane)
        scroll_by_page_plus_hack(window, pane, 1)
end)
}
```

**Comment by zw963** [comment]
Thanks a lot,  not aware of the `action_callback` can be directly used as an action, it works like a charm!
