### ISSUE TITLE
wezterm ssh does not support forwarding

### ISSUE THREAD

**Issue by npajkovsky** [wez/wezterm#4937]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

I'm on MacOS.

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

```
->% wezterm ssh nikola@work.pajkovsky.io
-> % ssh-add -l
Could not open a connection to your authentication agent.
```

Therefore, forwarding does not work, which complicates everything.

### Configuration

      local act = wezterm.action
      local config = wezterm.config_builder()

      config.font = wezterm.font_with_fallback({
                { family = "Monaco", weight = "Regular", italic = false },
      })
      config.font_rules = {
        {
          intensity = "Normal",
          italic = true,
          font = wezterm.font_with_fallback({
            { family = "Monaco", weight = "Regular", italic = false },
          }),
        },
        {
          intensity = "Bold",
          italic = true,
          font = wezterm.font_with_fallback({
                  { family = "Monaco", weight = "Bold", italic = false },
          }),
        },
      }

--      config.send_composed_key_when_left_alt_is_pressed = false
--      config.send_composed_key_when_right_alt_is_pressed = false

      config.keys = {
        -- disable DecreaseFontSize and Increase  FontSize
        { key = '-', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '-', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '-', mods = 'SUPER', action = act.DisableDefaultAssignment },
        { key = '_', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '_', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '+', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '+', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '=', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '=', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '=', mods = 'SUPER', action = act.DisableDefaultAssignment },
      }

      config.dpi = 144.0
      config.font_size = 12.0
      config.freetype_load_target = "HorizontalLcd"
      config.line_height = 0.9

      config.ssh_backend = "Ssh2"
      config.ssh_domains = {
        {
          name = 'work',
          remote_address = 'work.pajkovsky.io',
          username = 'nikola',
          remote_wezterm_path = "/home/nikola/.nix-profile/bin/wezterm",
        },
      }

      config.color_scheme = 'Gruvbox dark, pale (base16)'

      return config

**Comment by wez** [comment]
forwarding is not fully supported in the underlying ssh libraries at this time

**Comment by npajkovsky** [comment]
Ah, that's sad.
