### ISSUE TITLE
Wrong output of wezterm set-working-directory in tmux

### ISSUE THREAD

**Issue by stepanzak** [wez/wezterm#4940]
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin on KDE Plasma on both Wayland and  X11

### WezTerm version

wezterm 20240202-105940-8536d131

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Output of `wezterm set-working-directory` run in tmux is the following on my computer:
`$'\033Ptmux;\033\033]7;file://stepikuv-laptop/home/stepka/\033\\\033\\\033]7;file://stepikuv-laptop/home/stepka/\033\\'`
It should be this:
`\033Ptmux;\033\033]7;file://stepikuv-laptop/home/stepka/\033\033\\\033\\\033]7;file://stepikuv-laptop/home/stepka/\033\\`

### To Reproduce

Open wezterm
Run tmux
In tmux, run `print -r -- ${(qqqq):-"$(wezterm set-working-directory)"}`

### Configuration

```
-- This is my Wezterm config created with Tmux in mind
-- github.com/stepanzak/dotfiles
-- use it, modify it, do whatever you want with it. No credit needed (but appreciated)

local wezterm = require("wezterm")
local mux = wezterm.mux
local config = wezterm.config_builder()

-- set tmux as default program. This means that when you open a wezterm window,
-- command "tmux" runs. If tmux server isn't running, first wezterm window will
-- start it and if you have tmux-continuum with automatic restore, it will restore
-- your previous sessions. Every new window launched when tmux server is running will
-- create a new tmux session and attach to it. It's the same behavior as running "tmux" command.
-- You can switch sessions or create new and all that stuff, but when tmux program exits
-- (if you detach from tmux or when you kill the session you are in), the wezterm window closes.
config.default_prog = { 'tmux' }
config.color_scheme = 'Sakura'
if wezterm.gui.get_appearance():find 'Light' then
  config.color_scheme = 'Gruvbox (Gogh)'
else
  -- My "Sunset" color scheme (Gruvbox but with gold as a main color)
  config.color_scheme = "GruvboxDarkHard"
  config.colors = {
    foreground = '#d79921'
  }
end

-- Broot font for icons in Broot TUI
config.font = wezterm.font_with_fallback({ "FiraCode Nerd Font", "Broot Icons Visual Studio Code" })
config.font_size = 13

-- disable tab bar (tabs are handled by tmux)
config.enable_tab_bar = false

-- Unfortunately, this hacky way is the only way to start Wezterm maximized (not fullscreen)
-- I have tried other ways, but all of them was ugly and with visible resizing on window launch
-- Customize the values to fit your screen size exactly.
-- If you know about any other way to do that, please create an issuse at github.com/stepanzak/dotfiles.
-- config.initial_rows = 36
-- config.initial_cols = 146
-- UPDATE: setting window rule to maximize wezterm window both horizontally and vertically in KDE Plasma now works for me.
-- It's not ideal though

-- disable most of the keybindings because tmux can do that.
-- in fact, I'm disabling all of them here and just allowing the few I want
config.disable_default_key_bindings = true

local act = wezterm.action
config.keys = {
  { key = "-",        mods = "CTRL",  action = act.DecreaseFontSize },
  { key = "=",        mods = "CTRL",  action = act.IncreaseFontSize },
  { key = "P",        mods = "CTRL",  action = act.ActivateCommandPalette },
  { key = "V",        mods = "CTRL",  action = act.PasteFrom("Clipboard") },
  { key = "Copy",     mods = "NONE",  action = act.CopyTo("Clipboard") },
  { key = "Paste",    mods = "NONE",  action = act.PasteFrom("Clipboard") },
  { key = "F11",      mods = "NONE",  action = act.ToggleFullScreen },
}

return config
```

### Expected Behavior

According to @romkatv , the output should be `\033Ptmux;\033\033]7;file://stepikuv-laptop/home/stepka/\033\033\\\033\\\033]7;file://stepikuv-laptop/home/stepka/\033\\`

### Logs

Debug Overlay
wezterm version: 20240128-202157-1e552d76 x86_64-unknown-linux-gnu
Window Environment: X11 KWin
OpenGL: Mesa Intel(R) HD Graphics 5500 (BDW GT2) 4.6 (Compatibility Profile) Mesa 23.3.5-arch1.1
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
20:01:43.525 ERROR wezterm_gui::termwindow::palette > Error while saving recents: No such file or directory (os error 2)

### Anything else?

This issue:
https://github.com/romkatv/powerlevel10k/issues/2551
seems to be caused by this.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by stepanzak** [comment]
Yes, I compiled using the wezterm-git AUR package and now I'm unable to reproduce the issue, so I think it's fixed.
Thank you for your amazing app and quick response with fix.
