### ISSUE TITLE
Tab title not updating upon renaming tab unless a key is pressed after renaming the tab

### ISSUE THREAD

**Issue by mgpinf** [wez/wezterm#4941]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240202-105940-8536d131

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Tab title not updating upon renaming tab unless a key is pressed after renaming the tab.

### To Reproduce

Add below mentioned record in `config.keys` or `config.key_tables` to rename tab.
Rename tab with the specified key.
Observe the tab not getting renamed immediately.
Enter any key (except `ESC`)
Tab gets renamed

### Configuration

To rename tab
```lua
config.keys = {
  {
    key = 'r',
    action = act.PromptInputLine {
      description = describe.describe('Rename tab'),
      action = act_cb(function(window, pane, line)
        if not line then return end
        local tab_title
        if #line > 0 then
          tab_title = title.title(string.gsub(line, '%s+', '-'))
        else
          tab_title = ''
        end
        window:active_tab():set_title(tab_title)
      end),
    },
  },
}
```

Event action callback:
```lua
wezterm.on(
  'format-tab-title',
  function(tab, tabs, panes, config, hover, max_width)
    local left_indicator, right_indicator, index_color
    local workspace_bracket_color = 'Navy'
    if tab.is_active then
      left_indicator, right_indicator, index_color = '[', ']', 'Aqua'
    else
      left_indicator, right_indicator, index_color = ' ', ' ', 'Teal'
    end
    return {
      { Foreground = { AnsiColor = workspace_bracket_color, }, },
      { Text = ' ' .. left_indicator, },
      { Foreground = { AnsiColor = index_color, } },
      { Text = tostring(tab.tab_index + 1), },
      { Text = tab.tab_title, },
      { Foreground = { AnsiColor = workspace_bracket_color, }, },
      { Text = right_indicator, },
    }
  end
)
```

### Expected Behavior

Tab should be renamed immediately

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
