### ISSUE TITLE
nightly: wayland: Strange Window Border after latest update

### ISSUE THREAD

**Issue by unlux** [wez/wezterm#4963]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20240203-232629-2c5fa359

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After the latest update from Arch AUR, a strange title bar has appeared, which has also shifted the main window out of the window border. Please take a look at the image I've attached. Also, closing the terminal by pressing Ctrl+D also closes all the other windows.

![image](https://github.com/wez/wezterm/assets/92749166/3688ee6f-97f0-4036-a4b5-64ff2dacb319)
,

### To Reproduce

simply opening the terminal.

### Configuration

-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
	config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.color_scheme = "Tokyo Night"
config.window_background_opacity = 0.9
config.window_decorations = "RESIZE"
config.enable_wayland = true
config.use_fancy_tab_bar = false
-- config.hide_tab_bar_if_only_one_tab = true

wezterm.on("update-right-status", function(window, pane)
	-- Get the formatted date string
	local date = wezterm.strftime("%a | %b %-d")

	-- Color palette for the background of the cell
	local colors = { "#3c1361" }

	-- Foreground color for the text
	local text_fg = "#c0c0c0"

	-- Elements to be formatted
	local elements = {
		{ Foreground = { Color = text_fg } },
		{ Background = { Color = colors[1] } },
		{ Text = " " .. date .. " " },
	}

	-- Set the right status
	window:set_right_status(wezterm.format(elements))
end)

-- and finally, return the configuration to wezterm
return config

### Expected Behavior

There is no title bar and the working area must remain within the window borders.,

### Logs

Debug Overlay
wezterm version: 20240203-232629-2c5fa359 x86_64-unknown-linux-gnu
Window Environment: Wayland
Lua Version: Lua 5.4
OpenGL: AMD Radeon Graphics (radeonsi, renoir, LLVM 16.0.6, DRM 3.57, 6.7.3-zen1-2-zen) 4.6 (Compatibility Profile) Mesa 23.3.5-arch1.1
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>
> fastfetch
18:01:48.984 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:51.283 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:51.468 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:51.519 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:51.643 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:52.159 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:52.245 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:52.376 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:52.590 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:52.666 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:01:52.776 ERROR window::os::wayland::window > set_cursor: Cursor not found
> nvim
18:03:48.490 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:04:03.003 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:04:03.137 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:04:03.192 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:04:03.253 ERROR window::os::wayland::window > set_cursor: Cursor not found
18:04:03.506 ERROR window::os::wayland::window > set_cursor: Cursor not found
>

**Comment by Kindlewing** [comment]
I'm also having this problem. I've even got window_decorations = 'resize' per the documentation. Still the issue persists

**Comment by wez** [comment]
Wayland support is currently being re-implemented in `main`, this is an outstanding issue around that

**Comment by luben** [comment]
Same here with `window_decorations = "INTEGRATED_BUTTONS|RESIZE"`

**Comment by x4m3** [comment]
I also have strange behavior with `window_decorations` unset, I do not have the default `TITLE | RESIZE`

**Comment by mystilleef** [comment]
Setting `window_decorations` to  `NONE` is a workaround for those who don't care for window decorations on Wayland. I use a tiling manager to manage windows so YMMV.

**Comment by kindaLakshay** [comment]
> Setting `window_decorations` to `NONE` is a workaround for those who don't care for window decorations on Wayland. I use a tiling manager to manage windows so YMMV.

I can confirm that this works, but being a GNOME user, it is unusable due to there being no way to resize the window to a custom dimension or move it around without using the super+hold method.

**Comment by mystilleef** [comment]
> > Setting `window_decorations` to `NONE` is a workaround for those who don't care for window decorations on Wayland. I use a tiling manager to manage windows so YMMV.
> 
> I can confirm that this works, but being a GNOME user, it is unusable due to there being no way to resize the window to a custom dimension or move it around without using the super+hold method.

I figured this might be an issue for non-tiling window managers. On GNOME, I use PaperWM (a tiling window manager for GNOME Shell), which handles the resizing issues. So for those who don't mind trying something new, give tiling managers a try to possibly workaround resizing issues. Forge is another good tiling manager for GNOME.

**Comment by temefleet** [comment]
Any updates on this?

**Comment by ComixHe** [comment]
same issue, ArchLinux + GNOME

**Comment by gtirloni** [comment]
Confirmed on Fedora 40 + GNOME 46.3.1 + weztern-nightly

```
wezterm version: 20240701_070926_69686f45 x86_64-unknown-linux-gnu
Window Environment: Wayland
Lua Version: Lua 5.4
OpenGL: Mesa Intel(R) Graphics (RPL-S) 4.6 (Compatibility Profile) Mesa 24.1.2
```

![image](https://github.com/wez/wezterm/assets/5902830/f0178c6c-fad6-4914-9b0e-fc3aba2425aa)

**Comment by 64-bitman** [comment]
is still still being worked on?

**Comment by groner** [comment]
This is especially an issue with full screen terminals, because the bottom line is off the screen.

wezterm 20240812-215703-30345b36
Gnome 46 on Ubuntu 24.04 w/ wayland.

**Comment by zijizhu** [comment]
Hi, I'm experiencing the same issue with Gnome 46 on Fedora 40. I'm also wondering if this is still being worked on.

**Comment by luben** [comment]
at nightly de0ecc60eb5073015c4ccfe301e7895bb7bdf8ee :  
- NONE works
- RESIZE makes a title bar to show
- INTEGRATED_BUTTONS makes a title bar to show with duplicate buttons
