### ISSUE TITLE
Scroll by a configurable amount of lines

### ISSUE THREAD

**Issue by carmelopellegrino** [wez/wezterm#497]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a feature I'm missing :)

**Describe the solution you'd like**
I'd like to have the possibility to bind keyboard shortcuts to scroll back and forth one or more lines.

**Describe alternatives you've considered**
Scroll by a page is useful but on a daily basis I find myself willing to scroll just few lines instead of an entire page without using the mouse. I've searched in the config documentation but didn't find how to do. I also use ScrollToPrompt but still, from time to time, it's not what I need.

Let me use this issue also to thank you for your good work!

**Comment by wez** [comment]
I'm surprised that we didn't already have, but we do now have it in nightly: https://wezfurlong.org/wezterm/config/lua/keyassignment/ScrollByLine.html
