### ISSUE TITLE
Cursor shape changing to Block when leader key active when default cursor shape is not set to Block

### ISSUE THREAD

**Issue by mgpinf** [wez/wezterm#4971]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240205-070437-39d2b6ca

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Cursor shape changing to Block when leader key active when default cursor shape is not set to Block

### To Reproduce

Enter leader key, watch the cursor shape change

### Configuration

```lua
local M = wezterm.config_builder()
M.default_cursor_style = 'SteadyBar'
return M
```

### Expected Behavior

Cursor shape should remain same

**Comment by wez** [comment]
The leader key is treated similar to a composition effect, and what you are seeing sounds like it is the compose cursor updating to let you know that composition is in progress.

You can't disable the cursor change, but you can configure its color.

https://wezfurlong.org/wezterm/config/lua/window/leader_is_active.html is a related bit of documentation around this.
