### ISSUE TITLE
Lock glyph for password inputs does not render

### ISSUE THREAD

**Issue by Ennea** [wez/wezterm#4976]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE Plasma 5.27.10

### WezTerm version

20240203.110809.5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I have not tried this in nightly as I currently do not have the time to do that, but wanted to write a ticket regardless. This bug was also already present in version 20230712-072601-f4abf8fd.

When Wezterm detects a password input and wants to render the "lock" glyph, the error message for missing glyphs pops up instead:
```
No fonts contain glyphs for these codepoints: \u{f023}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust
your configuration so that it can find them.
Set warn_about_missing_glyphs=false to suppress this
message. 
``` 

I've tested this in an instance of Wezterm running with the default config via: `wezterm -n -e`

I feel like this may perhaps be a packaging issue, so if this is of relevance: I'm running Arch Linux and getting Wezterm via the official package from the repository.

### To Reproduce

1. Open Wezterm
2. Invoke a password prompt, for example via `sudo echo foo`

### Configuration

no config

### Expected Behavior

Lock glyph should render correctly.

**Comment by wez** [comment]
The glyph comes from `Symbols Nerd Font Mono` which is included in wezterm as a fallback when packaged by our CI.
Some distributions choose to unbundle that font, which means that you will need to perform some distro-specific steps that are unknown to me to install that font and for things to work as I originally intended.

**Comment by Ennea** [comment]
Oh.. yup. The correct package is `ttf-nerd-fonts-symbols-mono`. And here I thought that WezTerm comes with this glyph by itself. The codepoint looked to be inside one of the "private use areas" of Unicode, but perhaps I misunderstood that. It also worked before the 2023-07 release if I recall correctly.

Much appreciated!

**Comment by wez** [comment]
I've updated the installation docs to mention this package
