### ISSUE TITLE
a flag to keep a window open even though the child process has exited

### ISSUE THREAD

**Issue by sanga** [wez/wezterm#499]
**Is your feature request related to a problem? Please describe.**
Analogous to Alacritty's 'hold' flag (see: https://github.com/alacritty/alacritty/blob/34435ed776988e765d9327dcedfe909e440e6bf8/extra/completions/alacritty.fish#L32). My usecase for this is I have set up a link handler that may for example dump out some json to stdout from an api call. However when that command exits, the window closes before I had a chance to read the json. There are plenty of ways for me to work around this of course but none of them would be as convenient as adding such an option.

**Describe the solution you'd like**
To have such a flag.

**Describe alternatives you've considered**
There are definitely ways I could work around this, they are just a little bit clunky.

**Comment by wez** [comment]
It's not quite what you asked for, but I just pushed a commit that enables a new [exit_behavior](https://wezfurlong.org/wezterm/config/lua/config/exit_behavior.html) option.

There isn't a way to override this via CLI options just yet; that's dependent on some plumbing described in the "bonus points" section of https://github.com/wez/wezterm/issues/469#issuecomment-776108913

**Comment by wez** [comment]
With the latest commit on master you can now do: `wezterm --config 'exit_behavior = "Hold"'`

**Comment by sanga** [comment]
Looks perfect. Thanks Wez!
