### ISSUE TITLE
Doesn't recognize if wezterm.lua is a symbolic link

### ISSUE THREAD

**Issue by fowlie** [wez/wezterm#5008]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

I'm using PopOS! so I guess Gnome, or...

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I was moving all of my dotfiles to a git repo under ~/dotfiles using GNU Stow, which will move all managed config files to that directory and then use symbolic links to that repo inside ~/.config. So when ~/.config/wezterm/wezterm.lua is a symbolic link to ~/dotfiles/.config/wezterm/wezterm.lua, it acts as if there was no config file at all.

### Configuration

Not relevant

**Comment by wez** [comment]
I use symbolic links for my dotfiles and I have no problems. wezterm doesn't care about the symlinks; that is handled by the kernel. I suspect something else is happening.
My suggestion would be to run:

```
WEZTERM_LOG=config=trace,info strace -e trace=file wezterm show-keys
```

and see what gets logged.

**Comment by fowlie** [comment]
Thanks, that was useful. I think I found the root cause now. When Stow creates symbolic links, it only uses relative paths. Confirmed that by using absolute paths in the symbolic link, it picked up the config as expected. But doing an `ls -la` command, it shows what Stow is doing:

```
❯ ls -l
lrwxrwxrwx 1 mats mats 42 feb.  15 20:00 wezterm.lua -> ../../dotfiles/.config/wezterm/wezterm.lua
```

**Comment by wez** [comment]
Is that a broken link? eg: does `cat ~/.config/wezterm/wezterm.lua` show the file contents?

**Comment by wez** [comment]
Can you share the logs from strace when wezterm tried to open that file?

**Comment by fowlie** [comment]
These commands works just fine:

```
cat wezterm.lua
cat ~/.config/wezterm/wezterm.lua
cat ../../config/wezterm/wezterm.lua
```

I've attached the complete strace output here: [wezterm-5008.log](https://github.com/wez/wezterm/files/14302984/wezterm-5008.log)

**Comment by wez** [comment]
are you running the flatpak version of wezterm?
In a flatpak, the XDG environment is setup to redirect to an alternative location, which you can see in the log output:

```
23:13:30.318  TRACE  config::config > consider config: /home/mats/.wezterm.lua
23:13:30.318  TRACE  config::config > consider config: /home/mats/.var/app/org.wezfurlong.wezterm/config/wezterm/wezterm.lua
23:13:30.318  TRACE  config::config > consider config: /app/etc/xdg/wezterm/wezterm.lua
23:13:30.318  TRACE  config::config > consider config: /etc/xdg/wezterm/wezterm.lua
```

There are two resolutions:

* Teach your symlinking stuff to also setup a symlink in the `.var/app/org.wezfurlong.wezterm` directory
* Switch to using a native package of wezterm to avoid the flatpak sandboxing and redirection

**Comment by fowlie** [comment]
Yeah, I installed it via flatpak since I'm such a lazy person. At least when I'm just trying out stuff for the first time. Just read your note about not recommending flatpak other than for trying it out the first time in the installation pages, so... :) 

Thanks for helping me out here. Just re-installed it from the APT repo, and now it works as expected. :+1:
