### ISSUE TITLE
multiple packages with binaries found: codegen, generate-bidi, strip-ansi-escapes, sync-color-schemes, termwiz-fuzz, wezterm, wezterm-gui, wezterm-mux-server.

### ISSUE THREAD

**Issue by ket000** [wez/wezterm#5047]
Windows 11

when trying to build wezterm using cargo
cargo install --git https://github.com/wez/wezterm.git

I see the message

multiple packages with binaries found: codegen, generate-bidi, strip-ansi-escapes, sync-color-schemes, termwiz-fuzz, wezterm, wezterm-gui, wezterm-mux-server.

Please specify which package I should built and what each one does. 
wezterm or wezterm-gui

**Comment by wez** [comment]
`cargo install` is not a supported way to install wezterm.

On Windows you can install by following either:
* https://wezfurlong.org/wezterm/install/windows.html
* https://wezfurlong.org/wezterm/install/source.html
