### ISSUE TITLE
VIM Cursor Movement Latency on macOS

### ISSUE THREAD

**Issue by rrpolanco** [wez/wezterm#506]
## Describe the bug

When I open a 200 line text file with `nvim`, and hold down h/j/k/l to move the cursor over extended number of character/lines, the cursor movement lags and even stops momentarily before proceeding again; this continues repeating until the j/k keys are depressed. I tried the same thing under Kitty and Tmux, and the scrolling/cursor movement is smooth w/o such lag. Overall, there just seems to be general slow response from key inputs in `nvim`.

## Environment (please complete the following information):

 - OS: MacOS 10.15.7
 - Version: `wezterm 20210203-095643-70a364eb-131-g1415e9ce`
 - NVIM v0.4.3

## To Reproduce

- Open a text file with at least 50 lines using `nvim`
- Press and hold `j` or `k` to move the cursor up or down
- After a couple of lines, there should be a distinct latency in the scrolling/cursor movement.

## Expected behavior

Expect smooth cursor/scrolling when using VIM within wezterm.

## Screenshots

N/A

## Session Recording

In `nvim`, holding down `j (down)`.
![wezterm_slow_vim_issue506](https://user-images.githubusercontent.com/6497491/109667628-f3e0a100-7b35-11eb-9bbd-6c8e2247b4f6.gif)

**Comment by wez** [comment]
I can't reproduce this; is there something else about your setup that might be applicable?
Do you have a very high key repeat rate for example?
How large is the wezterm window?
You mentioned both vim and nvim; I tried both but don't experience lagging behavior. (I don't have any nvim configuration; I'm a vim user).
Is there possibly something about your vim/nvim configuration that might be a factor in reproducing this?

**Comment by rrpolanco** [comment]
> I can't reproduce this; is there something else about your setup that might be applicable?
> Do you have a very high key repeat rate for example?
> How large is the wezterm window?
> You mentioned both vim and nvim; I tried both but don't experience lagging behavior. (I don't have any nvim configuration; I'm a vim user).
> Is there possibly something about your vim/nvim configuration that might be a factor in reproducing this?

Hi @wez I added a screen recording which shows my cursor movement noticeably slowing down around line 170.
My wezterm window by default opens at 40x180. I'm not sure whether I have a high key repeat rate.

**Comment by wez** [comment]
I tried to reproduce this with a really long file and a window the same size as you mentioned above, but could not.  Is there something in your nvim config that might be a contributing factor?  Is there a way for you to launch nvim with the default configuration so we can zero in on how I can repro this?

**Comment by rrpolanco** [comment]
I have an amalgam of configurations on my system that makes things a bit difficult to debug. However, I used the built-in vim [profiler](https://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow) and the issue seems to stemming from the [vim-airline](https://github.com/vim-airline/vim-airline) plugin. As soon as I disable it, my scrolling is back to being fast again.

**Comment by wez** [comment]
Ah, interesting.  I wonder what it is doing!  Would you mind capturing a session recording for me: https://github.com/wez/wezterm/blob/main/.github/ISSUE_TEMPLATE/bug_report.md#session-recording
that should allow me to replay the same output stream and hopefully see the same slowdown, but otherwise see exactly what the terminal input and output looks like.
Please make a note of the terminal size to make it easier to reproduce/replay.

**Comment by wez** [comment]
Not sure if it is related, but while looking at image protocol parsing performance I made some changes that can impact the rate at which output with no newlines is processed and I'm wondering if that might coincidentally help here?  Could you try with an up to date nightly?

My plan is to tag the current state of `main` this weekend and it'd be great to understand and ideally resolve this issue before then, if we can!

**Comment by rrpolanco** [comment]
Latest nightly (`20210314-114017-04b7cedd-5-g2ea09317`) did not resolve the issue. However, I did capture the output stream and attached it to this message. Looks like the terminal cannot map specific vim-airline symbols every time I move the cursor (`h/j/k/l`). As a result, every movement/action is delayed due to the font errors below.

While holding down `j`:
```sh
./wt-record          
20210315144000
 2021-03-15T14:40:01.153Z INFO  wezterm_mux_server_impl::local > setting up /Users/rrpolanco/.local/share/wezterm/gui-sock-14524
 2021-03-15T14:40:01.347Z INFO  wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon Pro 560 OpenGL Engine 4.1 ATI-3.10.18 is_context_loss_possible=false wezterm version: 20210314-114017-04b7cedd-5-g2ea09317
 2021-03-15T14:40:21.389Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:21.947Z ERROR wezterm_font                   > No fonts have glyphs for ⠋, even though fallback suggested some.
 2021-03-15T14:40:35.100Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:51.116Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:51.669Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:52.239Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:52.791Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:53.334Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:53.884Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:54.404Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:54.955Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:55.488Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:56.045Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:56.634Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:57.185Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
 2021-03-15T14:40:57.746Z ERROR wezterm_font                   > No fonts have glyphs for ☰, even though fallback suggested some.
<errors repeat>
```
(Window size is 40x180)


Is there an option in `wezterm`  to map symbols for a particular font a la [kitty symbol_map](https://sw.kovidgoyal.net/kitty/conf.html?highlight=symbol#opt-kitty.symbol_map)? This could help alleviate the latency.

I cannot attache `tgz` files to Github issues. Will upload it somewhere in a bit.

**Comment by wez** [comment]
https://github.com/wez/wezterm/issues/508 is related.

What you can do in the meantime is add the font that contains those symbols to your font configuration in wezterm; you don't need a symbol map, it just needs that font to be listed in the fallback:

```lua
  font = wezterm.font_with_fallback({"JetBrains Mono", "The font with those symbols"})
```

**Comment by wez** [comment]
Two action items for wezterm:

* Make sure that we land on a glyph from the last-resort font in this case so that we avoid repeated expensive font fallback lookup
* Understand why the fallback isn't finding these glyphs

**Comment by frdrkolsson** [comment]
I also experienced this problem and found this thread. 
To help others which are struggling with this, the fonts `Apple Symbols` and `Arial Unicode MS` both contain the symbol which in this case was causing the input lag.
I bet both those fonts contain more symbols which some fonts does not have themselves.

**Comment by rrpolanco** [comment]
> I also experienced this problem and found this thread.
> To help others which are struggling with this, the fonts `Apple Symbols` and `Arial Unicode MS` both contain the symbol which in this case was causing the input lag.
> I bet both those fonts contain more symbols which some fonts does not have themselves.

Even with these fonts set in `wezterm.font_with_fallback()`, `wezterm` can't find the glyphs.

**Comment by frdrkolsson** [comment]
> Even with these fonts set in `wezterm.font_with_fallback()`, `wezterm` still can't find the glyphs in my config.

One of those fonts, or equivalent needs to be installed, and I had both those on my macOS computer, which might not be the case for everyone or every OS. 

The ☰ character seems to be a unicode symbol, so a font with the miscellaneous symbols would suffice. 
The ⠋ character looks like some kind of braille. On macOS it is included in Apple Symbols but does not seem to be part of Arial Unicode MS. Try to find a braille font and use that as fallback.

**Comment by wez** [comment]
I looked into this this evening. The gist of it is that the system fallback list can return a handful of fonts that don't exist on disk.  Presumably this is to prevent font piracy, but what it means is that freetype can load and render those.  One of those is `.AppleSymbolsFB`.

I've pushed a commit that explicitly adds `Apple Symbols` (which is presumably a similar but not identical font) to the fallback list.

With that change, I can run:

```
wezterm -n --config initial_rows=4 --config initial_cols=40 --config font_size=48.0 --config 'exit_behavior="Hold"' start echo '☰'
```

and it will render the glyph.

**Comment by wez** [comment]
I also confirmed that we do end up with a last-resort glyph in the case where we hit the `No fonts have glyphs for ☰, even though fallback suggested some` message.  On macOS, that messaging is a little inaccurate: macOS doesn't return a list of fonts with matching glyphs, just a list of potential fallback fonts. I'll do something to improve the wording.

**Comment by wez** [comment]
Would you mind trying the latest nightly when you have a few moments?   #559 uncovered some extra overheads with fallback fonts that I think may also have been a contributor to this issue, and those should now also be resolved.

**Comment by rrpolanco** [comment]
> Would you mind trying the latest nightly when you have a few moments? #559 uncovered some extra overheads with fallback fonts that I think may also have been a contributor to this issue, and those should now also be resolved.

With the latest nightly, the latency problem has definitely gone away and I'm not noticing any glyphs failing to load. However, orthogonal to this issue, I'm seeing a noticeable rendering difference for `echo -e '\u24e9'` compared to iTerm and Kitty but I'll open a separate issue for that.

Thank you for the follow up and prompt resolution 🏅 
Slowly but surely, `wezterm` is becoming my daily driver 😁

**Comment by wez** [comment]
Good to hear!  I'll keep this open for a little bit to remind myself to summarize it for the changelog!
