### ISSUE TITLE
OTF Font is never rendered Bold

### ISSUE THREAD

**Issue by raimundomartins** [wez/wezterm#5064]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

dwm

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

On not trying Nightly: I use voidlinux and no flatpak. It's not clear what branch is nightly so I can build from source.

Fonts are never rendered in bold. Changing `bold_brightens_ansi_colors` to any other setting has no effect.

### To Reproduce

Open wezterm and run `echo -e '\033[0;31mHello\033[1;31mHello\033[0m'`

### Configuration

```
local wezterm = require 'wezterm'

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.bold_brightens_ansi_colors = "No"

return config
```

### Expected Behavior

Font should be rendered bold

### Logs

```
Debug Overlay
wezterm version: 20240203-110809-5046fc22 x86_64-unknown-linux-gnu
Window Environment: X11 dwm
Lua Version: Lua 5.4
OpenGL: AMD Radeon RX 6500 XT (radeonsi, navi24, LLVM 17.0.6, DRM 3.54, 6.6.17_1) 4.6 (Compatibility Profile) Mesa 23.3.5
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
10:29:06.799 WARN window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: get_appearance.read_setting: I/O error: No such file or directory (os error 2): No such file or directory (os error 2)
```

### Anything else?

![unbold](https://github.com/wez/wezterm/assets/4508664/4e629f09-39fa-4547-929c-70099a5b0f0a)

**Comment by raimundomartins** [comment]
I just realized that wezterm can render bold fonts using the default fonts, but it was using the settings in fontconfig so it picked (correctly) this one [inconsolata.otf.tar.gz](https://github.com/wez/wezterm/files/14384502/inconsolata.otf.tar.gz).
I don't know why bold doesn't work with it, but here's a picture of the same font being rendered correctly in alacritty:
![bold](https://github.com/wez/wezterm/assets/4508664/9b002f8e-46d9-4be5-bad6-6f6cd630b516)

**Comment by wez** [comment]
Please run `wezterm ls-fonts` and share the output here. (see also: https://wezfurlong.org/wezterm/troubleshooting.html#debugging-font-display)

**Comment by wez** [comment]
Where does the choice of `monospace` font come from? Is that something that voidlinux is imposing on the config?
The config you shared has no font specified; the default in "official" wezterm should be `JetBrains Mono`.

I do not recommend using `monospace` or other similar fontconfig aliases, as it removes control of this sort of font styling from wezterm.

**Comment by raimundomartins** [comment]
It probably comes from my `.config/fontconfig/fonts.conf`:

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
    <alias>
        <family>monospace</family>
        <prefer>
                <family>InconsolataGo Nerd Font</family>
                <family>Inconsolata</family>
                <family>Liberation Mono</family>
        </prefer>
    </alias>
</fontconfig>
```
I thought this meant that when an app asks for monospace it gets those fonts in that order. What I do to switch between the OTF and TTF is obviously swap their respective lines here.

**Comment by wez** [comment]
I'd recommend that you use https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html to explicitly configure the fonts used by wezterm

**Comment by oOosys** [comment]
It seems that the default font (both: if not specified or if specified as 'JetBrains Mono' in the configuration) does not support bold glyphs: 

SCREENSHOT with default font specified (or without specification): 
![_o--wezterm--_oo--ISSUE--_O--Terminal-defaultFont-failsToRenderBold-1of2-defaultFont--_oo0](https://github.com/wez/wezterm/assets/143121714/bf67a43f-160e-4fa3-b87a-2669a1c4aa29)

SCREENSHOT with "B612 Mono" as font
![_o--wezterm--_oo--ISSUE--_O--Terminal-defaultFont-failsToRenderBold-2of2-B612_Mono--_oo0](https://github.com/wez/wezterm/assets/143121714/aff13aed-e777-49ad-97f7-99fc438c9d98)
