### ISSUE TITLE
Cursor hiding on broken on Wayland

### ISSUE THREAD

**Issue by abatkin** [wez/wezterm#5071]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE/Plasma

### WezTerm version

20240221_075452_95581d86

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Cursor hiding does not work.

In addition, every keypress generates the following log entry:

> ERROR  window::os::wayland::window > set_cursor: Cursor not found

Disabling cursor hiding makes the error go away.

### To Reproduce

Run Wezterm, press a key

### Configuration

This happens with an empty configuration.

### Anything else?

This is from a freshly installed Wezterm from the COPR on Fedora 39. KDE/Plasma, AMD graphics card, Wayland.

#4948 looks interesting (since it's the only open issue I can find that mentions the same log entry) so maybe this is a dupe and I'm lucky that it doesn't panic?

Anyway, happy to help debug if I can.

**Comment by timon-schelling** [comment]
Same problem for me.
Wezterm is also really unresponsive until I move the mouse, sometimes it freezes completion

**Workaround**: The error disappears if `hide_mouse_cursor_when_typing` is et to `false`.

I'm using a option of my Wayland compositor (Hyprland) that hides the mouse cursor after a some time (cursor_inactive_timeout = 3).

As i understand it, when the compositor hides the cursor wezterm is unable to grab it to set it as hidden. https://github.com/wez/wezterm/blob/95581d8697f3749f84ccb1402ac94ea6582b227f/window/src/os/wayland/window.rs#L897L920

**Comment by wez** [comment]
Fixed by https://github.com/wez/wezterm/pull/5276
