### ISSUE TITLE
Wezterm crashes on suspend on wayland

### ISSUE THREAD

**Issue by sjcobb2022** [wez/wezterm#5079]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

95581d8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

On suspend, wezterm crashes with an unimplemented error.

### To Reproduce

- Hyprland, built from branch main at commit af0c8e299bbbf1726cecfde683137cfd4a6b8642
- Wezterm 95581d8
- Start wezterm
- Suspend system

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("FiraCode Nerd Font"),
  font_size = 12.0,
  color_scheme = 'tokyo-city-terminal-dark',
  hide_tab_bar_if_only_one_tab = true,
  window_close_confirmation = "NeverPrompt",
  check_for_updates = false,
  term='wezterm'
}
```

### Expected Behavior

It does not crash.

### Logs

09:55:33.945  ERROR  env_bootstrap                   > panic at window/src/os/wayland/seat.rs:70:9 - not yet implemented
   0: env_bootstrap::register_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: <window::os::wayland::state::WaylandState as wayland_client::event_queue::Dispatch<wayland_client::protocol::wl_seat::WlSeat,smithay_client_toolkit::seat::SeatData>>::event
   8: wayland_client::event_queue::queue_callback
   9: wayland_client::event_queue::EventQueue<State>::dispatching_impl
  10: <window::os::wayland::connection::WaylandConnection as window::connection::ConnectionOps>::run_message_loop
  11: wezterm_gui::run_terminal_gui
  12: wezterm_gui::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: std::rt::lang_start::{{closure}}
  15: std::rt::lang_start_internal
  16: std::rt::lang_start
  17: __libc_start_call_main
  18: __libc_start_main@GLIBC_2.2.5
  19: _start

### Anything else?

I am unsure whether this is being worked on, as this has been left unimplemented after the tzx wayland rewrite.

Specifically it is the function.

```rust
    fn remove_capability(
        &mut self,
        _conn: &Connection,
        _qh: &QueueHandle<Self>,
        _seat: WlSeat,
        _capability: smithay_client_toolkit::seat::Capability,
    ) {
        todo!()
    }
```

**Comment by cjearls** [comment]
I'm seeing the same behavior on Sway, and it appears that https://github.com/wez/wezterm/issues/5154 is due to the same `todo!`

**Comment by wez** [comment]
Fixed by https://github.com/wez/wezterm/pull/5276
