### ISSUE TITLE
Mark the scroll position of every prompt 

### ISSUE THREAD

**Issue by 0xjairo** [wez/wezterm#5090]
I'm always frustrated when I run a the same command repeatedly but the command also produces a lot of output (think compiling software with verbose output, many warnings, and errors) and I find myself looking for the beginning of the output, i.e. the first few lines after running the command. Depending on the format of your prompt, it may be difficult to spot the beginning.

The solution I envision would involve saving the scroll position each time the user is presented with a prompt and additionally Wezterm has an action and key binding to allow you to jump backwards/forwards in time to each of the prompts.

**Comment by mwaitzman** [comment]
https://wezfurlong.org/wezterm/config/lua/keyassignment/ScrollToPrompt.html

**Comment by 0xjairo** [comment]
Additional reference on OSC 133 https://wezfurlong.org/wezterm/shell-integration.html
