### ISSUE TITLE
CloseCurrentPane and CloseCurrentTab confirmation prompts do not work in tmux

### ISSUE THREAD

**Issue by pbnj-dragon** [wez/wezterm#5095]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When closing wezterm pane/tab while in tmux session, there is no confirmation prompt, despite wezterm configuration to prompt for confirmation.

### To Reproduce

Outside of tmux:

1. Set CloseCurrentPane and CloseCurrentTab to prompt for confirmation
2. Close tab/pane with cmd+w (confirmation prompt appears; select "No")

Start tmux in current shell session:

1. Close tab/pane with cmd+w (no confirmation; wezterm terminates)

### Configuration

```lua
local wezterm = require("wezterm")

return {
  enable_scroll_bar = false,
  hide_tab_bar_if_only_one_tab = true,
  window_decorations = "RESIZE",
  keys = {
    {
      key = "w",
      mods = "CMD",
      action = wezterm.action.CloseCurrentPane({ confirm = true }),
    },
    {
      key = "w",
      mods = "CMD",
      action = wezterm.action.CloseCurrentTab({ confirm = true }),
    },
  },
}
```

### Expected Behavior

Confirmation prompt appears when closing wezterm pane/tab while in tmux sessions

**Comment by RevinderDev** [comment]
Isn't this related to https://wezfurlong.org/wezterm/config/lua/config/skip_close_confirmation_for_processes_named.html ?

Try maybe excluding tmux from the list, or getting rid of it entirely

```
config.skip_close_confirmation_for_processes_named = {}
```

**Comment by wez** [comment]
This is intentional; there is no prompt to kill tmux because it is safely to kill it; you can re-attach later.
