### ISSUE TITLE
WezTerm killing tmux window when closed

### ISSUE THREAD

**Issue by sandorex** [wez/wezterm#5101]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE Plasma 5.27.5

### WezTerm version

20240226-174525-22424c32 (Appimage)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm kills tmux window when it is closed, i think it has to do with the signal it sends

Kitty and Konsole terminals do not experience this issue

### To Reproduce

- Open wezterm
- Start tmux `tmux new-session -s $USER`
- (optional) Run `tmux ls` to see the session and you should get the output like below
```
% tmux ls                                                     ~
sandorex: 1 windows (created Sat Mar  2 12:04:52 2024) (attached)
```

- Close the terminal by clicking the X button
- Run `tmux ls` in another terminal and you get `no server running on /tmp/tmux-1000/default` cause it killed it

### Configuration

It is intermittent, i tried without config and still happens when it wants

### Expected Behavior

As it happens on Konsole and Kitty terminals the sessions should still be present but just detached
```
% tmux ls                                                     ~
sandorex: 1 windows (created Sat Mar  2 12:04:04 2024)
```

### Logs

_There is no output to copy_

### Anything else?

It seems to be due to signals sent, for example when closed wezterm sends SIGHUP to zsh shell
```
% strace -e 'trace=!all' -p 602832                            ~
strace: Process 602832 attached
--- SIGHUP {si_signo=SIGHUP, si_code=SI_USER, si_pid=602824, si_uid=1000} ---
+++ exited with 1 +++
```

But tmux gets something else, but im still digging to see why this happens as it does not happen every time
```
% strace -e 'trace=!all' -p 602958                            ~
strace: Process 602958 attached
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=602959, si_uid=1000, si_status=0, si_utime=3 /* 0.03 s */, si_stime=4 /* 0.04 s */} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=603595, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
+++ exited with 0 +++
```

**Comment by sandorex** [comment]
Even if i run zsh with `systemd-run --scope --user tmux new-session -s $USER` it still gets killed for some reason, which is weird

**Comment by sandorex** [comment]
Im gonna guess this is the culprit
https://github.com/wez/wezterm/blob/22424c3280cb21af43317cb58ef7bc34a8cbcc91/pty/src/lib.rs#L372

**Comment by ashleysommer** [comment]
Can confirm, does the same for me (even with systemd-run too). Odd, I've never noticed this behavior until you pointed it out.

**Comment by sandorex** [comment]
> Can confirm, does the same for me (even with systemd-run too).

Interesting, now suddenly i cannot reproduce it

**Comment by ashleysommer** [comment]
My colleague last week was telling me of an issue he had with TMUX over SSH.
He would ssh into a remote server, create a tmux session on the server, detach the tmux, then end the SSH connection.
Then when reconnecting over SSH, the tmux session is gone.
He fixed it with this suggestion using loginctl to enable "linger".
https://unix.stackexchange.com/a/599211
I wonder if there is something similar going on here.

**Comment by sandorex** [comment]
I have played a lot with linger and i realized some apps sometimes were killed while i sometimes had nvim running in background cause i did not kill it explicitly and now honestly im even more confused what is the expected behaviour and what is not

**Comment by notnmeyer** [comment]
sounds like the same thing that was being reported here https://github.com/wez/wezterm/issues/4562

i can consistently replicate on mac os and weztem 20240203-110809-5046fc22.

it seems like its only the active tmux window  that's getting killed when wezterm closes. so if there's only a single window, the entire session is gone, otherwise the session survives but the previous active window is missing.

<img width="610" alt="Screenshot 2024-03-13 at 07 47 28" src="https://github.com/wez/wezterm/assets/672246/92821a0b-6b36-46a0-8248-25563629e5b2">

then if i close (without detaching tmux) and relaunch wezterm,

<img width="738" alt="Screenshot 2024-03-13 at 07 48 30" src="https://github.com/wez/wezterm/assets/672246/8ff8bcfa-7eec-4739-b51d-a8ddee79a804">

**Comment by notnmeyer** [comment]
did some more testing—the tmux window is only killed if there's nothing running _and_ its the active window when wezterm exits.

if i start nvim, htop, or just run `sleep 120` and then exit wezterm the window survives.

**Comment by sandorex** [comment]
> the tmux window is only killed if there's nothing running and its the active window when wezterm exits.

You're probably right about this but as i cannot reproduce the behavior at the beginning reliably (_tmux itself was getting killed no matter how many windows or programs running in it_) anymore i am gonna close this
