### ISSUE TITLE
RIS doesn't clear scrollback

### ISSUE THREAD

**Issue by nabajour** [wez/wezterm#511]
**Is your feature request related to a problem? Please describe.**
I usually use the "reset" command in other terminals (uxterm, kitty...), to clear the view and the scrollback buffer to start afresh and be able to scroll back to the beginning of the suite of commands and outputs of what I ran. 

In wezterm, the "reset" command does not clear the scrollback buffer.

**Describe the solution you'd like**
when typing the "reset" command, also clear the scrollback buffer. 

**Describe alternatives you've considered**
I can clear the scrollback buffer with the default key-binding CTRL-CHIFT-K. 

But with this behaviour, I need to type the command to clear the visible part and press the key-binding to clear the scrollback buffer.

**Comment by wez** [comment]
This is a bug; thanks for reporting it!
The [RIS](https://vt100.net/docs/vt510-rm/RIS) sequence is documented as:

> Clears the screen and all off-screen page memory.

so we need to conform to this.
