### ISSUE TITLE
Not able to remap mouse bindings

### ISSUE THREAD

**Issue by sainad2222** [wez/wezterm#5130]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The default mouse binding for opening link under cursor seems to be CTRL+CLICK. [ref](https://github.com/wez/wezterm/blob/main/docs/config/lua/keyassignment/OpenLinkAtMouseCursor.md#L1) But in my mac without any config change it is SHIFT+CLICK. I tried remapping them to CTRL/SUPER but this doesn't seem to have any effect on the bindings. Probably my keyboard is sending wrong modifiers. I use QWERTY/ENGLISH keyboard(M1 Mac)

### To Reproduce

Nothing happens on CTRL+CLICK. SHIFT+CLICK opens hyperlink

### Configuration
```
local wezterm = require("wezterm")
local config = wezterm.config_builder()

config.font_size = 16
config.enable_tab_bar = false
config.window_padding = {
	left = 0,
	right = 0,
	top = 0,
	bottom = 0,
}
config.default_prog = {
	"/opt/homebrew/bin/tmux",
	"attach-session",
	"-t",
	"default",
}

return config

```
### Expected Behavior

CTRL+CLICK to open links

### Logs

No specific logs. Just
20:12:06.415  INFO   wezterm_gui::termwindow > clicking https://google.com

### Anything else?

Is there a way I can record keystrokes and see what the wezterm is getting?

**Comment by bew** [comment]
No the default to open links is Click (without modifiers).
Here I believe you are using tmux (as per your config), and you probably enabled mouse support in tmux, so now tmux is getting all the mouse inputs like normal clicks.

In wezterm there is a way to bypass sending clicks to tmux (or the current program asking for mouse events) which is the Shift key by default.
See: https://wezfurlong.org/wezterm/config/lua/config/bypass_mouse_reporting_modifiers.html

**Comment by sainad2222** [comment]
That makes sense. Thanks

**Comment by sainad2222** [comment]
Thanks just adding mouse_reporting=true for my new binding worked in this case. I'll check if there are any other side effects and probably disable the mouse mode in tmux since I only use it for resizing panes. Is there a way wezterm gets the mouse events first then send it to processes in pane after(tmux, vim etc)? But I am guessing its not possible since tmux is layered on top of wezterm

**Comment by bew** [comment]
Well wezterm will always get the input events first (from your desktop manager, like X11), then it decides if the config has a binding to it and must be called or if it has to encode the event and send it to the current program running in the terminal.

In your config you could have a binding to capture the even and decide for yourself if you want to forward it to the pane using [`win:perform_action(action, pane)`](https://wezfurlong.org/wezterm/config/lua/window/perform_action.html).
I know this is possible for key events using the [`SendKey`](https://wezfurlong.org/wezterm/config/lua/keyassignment/SendKey.html) action.
❌ But at the moment there is no action to send a mouse event 👀
