### ISSUE TITLE
Issue to install  wezterm-nightly on Ubuntu

### ISSUE THREAD

**Issue by joaothallis** [wez/wezterm#5131]
## Build Environment (please complete the following information):

 - OS:
```bash
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
``` 
 - Linux: `Linux brrioln037642 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

## The install output

Please include the output from running the build command:

```bash
$ curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *

$ sudo apt install wezterm-nightly
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package wezterm-nightly
```

I am having the same problem with `sudo apt install wezterm`

**Comment by sommerper** [comment]
Just tried this and am having the same problem.

**Comment by DennisTheMenace780** [comment]
Similar problem here for me too.

**Comment by arodland** [comment]
It doesn't look like you did `apt update`? So the list file you added hasn't been read yet.

**Comment by wez** [comment]
Please run `sudo apt update ; sudo apt install wezterm-nightly`
