### ISSUE TITLE
Cannot bind `Shift + Enter`

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#516]
## Describe the bug
Cannot rebind `Shift + Enter`.

## Environment (please complete the following information):
 - OS: Linux X11
 - Version: wezterm 20210203-095643-70a364eb
 - The active keyboard layout name: ENG

## To Reproduce
Press `Shift + Enter`.

## Configuration

```lua
local wezterm = require 'wezterm';

return {
  keys = {
    -- {key="Enter", mods="SHIFT", action=wezterm.action{SendString="\033[\015;2u"}},
    {key="Enter", mods="SHIFT", action="Nop"}
  }
}
```

## Expected behavior
The second item of the `keys` array does not cancel the key stroke `Shift + Enter`. Instead it appears that the `Enter` key is pressed, as the terminal shows that I entered an empty command.

The first item is my desired behavior. If uncommented, it does not rebind `Shift + Enter`.

## Screenshots
N/A.

## Session Recording
I think the above is enough info to reproduce the bug.

## Additional context
N/A.

**Comment by wez** [comment]
Ah, I think the docs have drifted from an implementation detail.  You can set `debug_key_events=true` in your config file to have wezterm log the key events that it is receiving on its stderr.  On my mac I see this:

```
2021-03-08T05:30:00.847Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\r'), modifiers: SHIFT, raw_key: None, raw_modifiers: NONE, raw_code: Some(36), repeat_count: 1, key_is_down: true }
```

The `Enter` key is reported `\r`.  That's correct; `Enter` is something that isn't generated any more.

So I think you want:

```lua
   {key="\r", mods="SHIFT", action=wezterm.action{SendString="\033[\015;2u"}},
```

**Comment by stevenxxiu** [comment]
I tried that line. I get the log:

    2021-03-08T05:53:19.142Z INFO  wezterm_gui::gui::termwindow   > key_event KeyEvent { key: Char('\r'), modifiers: NONE, raw_key: None, raw_modifiers: SHIFT, raw_code: Some(36), repeat_count: 1, key_is_down: true }

The key code I get is just `Enter` like I didn't hold `Shift` though:

```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^M       13 0015 0x0d
```

**Comment by wez** [comment]
I was just poking around and saw that `Enter` is an alias for `\r`, and this does work on the mac.
I think this is a linux specific issue; looks like the SHIFT is being removed.

I'll get this fixed, but for now, you should be able bind to the raw event:

```
{key="raw:36", mods="SHIFT", action=wezterm.action{SendString="\033[\015;2u"}},
```

https://wezfurlong.org/wezterm/config/keys.html#using-rawscan-codes-for-key-bindings has some more info on this.

**Comment by stevenxxiu** [comment]
Ah whoops for octal I should've typed `\o` instead of `\0`, but thanks, the above raw fixes the issue for now.

**Comment by stevenxxiu** [comment]
Yup works for me now. Thanks! Sorry for the late reply, didn't have time to test it earlier.
