### ISSUE TITLE
Strange highlighted colors

### ISSUE THREAD

**Issue by adschem** [wez/wezterm#5160]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Pop-shell, gnome varient

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When running pre-commit the text behind highlights is unreadable. 

![image](https://github.com/wez/wezterm/assets/14344249/e3662e73-928b-4e68-96d0-e9112d2ad31a)

If i highlight the region i can't read it
![image](https://github.com/wez/wezterm/assets/14344249/0d940254-8ff9-4e8e-a62d-e641442f501a)

### Configuration

The only change to colours I have made is to make my bg slightly off black using the follow: 

```
config.colors = {}
config.colors.background = "#111111"
```

I have also tried several of the in built colour schemes all with the same issue unfortunately. 

### Anything else?

I have looked how to change these highlights and maybe missing it, if so I apologise in advance!! Love the project, thank you!

**Comment by oOosys** [comment]
I suggest to stop looking for the reason outside of you and check the very details of your vision. You may need eventually special color combinations in the theme to overcome color perception problems.

**Comment by wez** [comment]
If the default colors don't work for you, there are literally hundreds (just shy of 1000!) of other options and the ability to customize all colors very precisely.

https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors has details on colors in general.
https://wezfurlong.org/wezterm/colorschemes/index.html has the list of available color schemes.
