### ISSUE TITLE
Kitty keyboard: AltGr (ISO Level 3 Shift) and RCtrl (Compose) keys don't work

### ISSUE THREAD

**Issue by LunarLambda** [wez/wezterm#5167]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Debian 12/sid with GNOME 

### WezTerm version

20240226-174525-22424c32

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I use the following setxkbmap settings:
```
rules:      evdev
model:      pc105
layout:     us,us
variant:    altgr-intl,
options:    compose:rctrl,caps:escape
```

When running neovim, which supports the kitty keyboard protocol, I cannot type characters such as ß (AltGr+S) or ü (AltGr+y). In Kitty this does work, and typing the characters into neovim works too. Disabling `enable_kitty_keyboard` also restores functionality.

output of `kitten show_key -m kitty` when pressing AltGr+s
```
ISO_LEVEL3_SHIFT PRESS 
CSI 57453 u

ß PRESS ß
CSI 223 :  : 115 ;  ; 223 u
Alternate key: s 

ß RELEASE 
CSI 223 :  : 115 ; 1 : 3 u
Alternate key: s 

ISO_LEVEL3_SHIFT RELEASE 
CSI 57453 ; 1 : 3 u
```

### To Reproduce

1. Set `enable_kitty_keyboard = true` in config
2. `setxkbmap us altgr-intl`
3. Open neovim (ideally latest nightly appimage)
4. Enter insert mode and press keys while holding AltGr (none of them work). Same thing happens with the compose-key (right ctrl)

### Configuration

```lua
local w = require 'wezterm'

return {
    audible_bell = 'Disabled',
    color_scheme = 'tokyonight_moon',
    enable_kitty_keyboard = true,
    font = w.font_with_fallback {
        {
            family = 'Berkeley Mono',
            harfbuzz_features = { 'calt=0' },
        },
        {
            family = 'FiraCode Retina',
            harfbuzz_features = { 'calt=0', 'ss03', 'ss05' }
        },
    },
    font_size = 15,
    force_reverse_video_cursor = true,
    freetype_load_target = 'Light',
    freetype_render_target = 'HorizontalLcd',
    hide_tab_bar_if_only_one_tab = true,
    initial_cols = 100,
    initial_rows = 32,
    use_fancy_tab_bar = false,
    window_background_opacity = 0.975,
    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
    }
}
```

### Expected Behavior

AltGr keys should work as they do in kitty

### Logs

No logs found

### Anything else?

This issue has been very inconsistent for me. Previously (either due to wezterm or system updates) it would work, or type the wrong key (AltGr+y would enter u, not ü, or type ü but not work with shift to produce Ü).

**Comment by oOosys** [comment]
Try intl. with AltGr dead keys ...

**Comment by LunarLambda** [comment]
That's exactly what the altgr-intl variant is. It's listed as "intl. with AltGr dead keys".

**Comment by LunarLambda** [comment]
I tried compose-key just now (rctrl).
Exact same thing. Works completely fine without `enable_kitty_keyboard`, completely ceases to work at all when enabled.

Have also updated to the latest wezterm-nightly before trying the above.

**Comment by LunarLambda** [comment]
Update: it works fine on wayland. It also works fine on X11 if I use `setxkbmap us alt-intl-unicode` instead of `setxkbmap us alt-intl`.

It still reproduces as described in the original issue however. Unsure whether to close or not.
