### ISSUE TITLE
Single, double, curly, dotted and dashed underlines are literally all the same

### ISSUE THREAD

**Issue by hrqmonteiro** [wez/wezterm#5195]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Wayland with Kwin (Plasma 6)

### WezTerm version

wezterm 20240203.110809.5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

![Screenshot_20240320_151437](https://github.com/wez/wezterm/assets/17055027/c50a2ad0-07d2-4dcf-ac2b-b58073f4e1e7)

```
 printf "\x1b[58:2::255:0:0m\x1b[4:1msingle\x1b[4:2mdouble\x1b[4:3mcurly\x1b[4:4mdotted\x1b[4:5mdashed\x1b[0m\n"
singledoublecurlydotteddashed
```

### To Reproduce

```
 printf "\x1b[58:2::255:0:0m\x1b[4:1msingle\x1b[4:2mdouble\x1b[4:3mcurly\x1b[4:4mdotted\x1b[4:5mdashed\x1b[0m\n"
singledoublecurlydotteddashed
```

### Configuration

Default, only put `enable_tab_bar = false`

### Expected Behavior

To show it differently?

**Comment by wez** [comment]
Can't reproduce. Try running the `underlines.sh` script from the repo:

```console
; bash ./test-data/underlines.sh
```

![image](https://github.com/user-attachments/assets/1319fab9-84fe-4064-8547-babd2dd75cef)
