### ISSUE TITLE
Make/allow to config baskscape key to send ^?

### ISSUE THREAD

**Issue by fanzeyi** [wez/wezterm#52]
It seems other terminals (Terminal.app, iTerm2, Alacritty are the ones I surveyed) by default will send `^? 0x7F DEL` for backspace keys but WezTerm sends `^H 0x08 BS` for backspace instead. This is causing an issue for my tmux configuration (see christoomey/vim-tmux-navigator#59).

iTerm2 made this behavior configurable:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/409951/67655694-c7e45880-f90e-11e9-9f99-2ffab1054894.png">

This isn't really directly configurable with current keybindings. It seems WezTerm doesn't allow to configure a keybinding without modifier. :( 

----

Options:

1. Making keybindings without modifier customizable (sounds kinda bizarre).
2. Adding an option to just change how backspace works. (I think it's probably better to switch to `^?` as default?)

**Comment by wez** [comment]
Hmm, interestingly, fd8738ea0e8a8ea3569edde6c22c89167836b8d4 just did the opposite of this in the new frontend on macos because it was breaking delete for me in vim when I switched it to be the default frontend.

I agree that this should be subject to a config setting that normalizes the to either `bs` or `del`

**Comment by wez** [comment]
Also: part of the problem here is that mac keyboards have a bit of a weird design choice: the delete key is in the place of the backspace key, with backspace provided via cmd-delete

**Comment by wez** [comment]
* The glutin frontend used to remap del -> bs
* The newer gui frontend correctly sent del, but the terminalstate processing would remap that to `<ESC>[3~` when in application cursor key mode (eg: in vim)
* That led me to fd8738ea0e8a8ea3569edde6c22c89167836b8d4 as a hackaround before I had a chance to dig in and understand things

This should now be resolved in master:

* The glutin frontend has been removed
* The gui frontend now avoids the application cursor sequence as of d80169ceff37f910721454d78bf5143b7e25d7d4

So you should have the behavior you expect by default now!

**Comment by wez** [comment]
I'm inclined to punt on making this configurable now that we have the right behavior by default, so I'm going to close this issue for now!
