### ISSUE TITLE
support for server-side cursors(i.e. hyprcursor)

### ISSUE THREAD

**Issue by deviantsemicolon** [wez/wezterm#5209]
**Is your feature request related to a problem? Please describe.**
I like my cursor on my system to be themed uniformly, and that doesn't seem to work with Wezterm, at least with Wayland disabled.

**Describe the solution you'd like**
I would like Wezterm to work with hyprcursor, as well as other future server-side cursor things.

**Describe alternatives you've considered**
An alternative could be making WezTerm work with xcursor or gtk theming

**Additional context**
https://blog.vaxry.net/articles/2024-cursors

**Comment by wez** [comment]
Presumed fixed in `main` by https://github.com/wez/wezterm/pull/5276
Please re-open if it isn't.
