### ISSUE TITLE
Names for function keys in key bindings

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#521]
**Is your feature request related to a problem? Please describe.**
It'll be nice to have have function key names for key bindings.

**Describe the solution you'd like**
Instead of `raw:67` I can use `F1`.

**Describe alternatives you've considered**
 I'm currently using the following for F1-F12 which works:

        {key="raw:67", mods="CTRL", action=wezterm.action{SendString="\x1b[1;5P"}},             -- `Ctrl + F1`
        {key="raw:68", mods="CTRL", action=wezterm.action{SendString="\x1b[1;5Q"}},             -- `Ctrl + F2`
        {key="raw:69", mods="CTRL", action=wezterm.action{SendString="\x1b[1;5R"}},             -- `Ctrl + F3`
        {key="raw:70", mods="CTRL", action=wezterm.action{SendString="\x1b[1;5S"}},             -- `Ctrl + F4`
        {key="raw:71", mods="CTRL", action=wezterm.action{SendString="\x1b[15;5~"}},            -- `Ctrl + F5`
        {key="raw:72", mods="CTRL", action=wezterm.action{SendString="\x1b[17;5~"}},            -- `Ctrl + F6`
        {key="raw:73", mods="CTRL", action=wezterm.action{SendString="\x1b[18;5~"}},            -- `Ctrl + F7`
        {key="raw:74", mods="CTRL", action=wezterm.action{SendString="\x1b[19;5~"}},            -- `Ctrl + F8`
        {key="raw:75", mods="CTRL", action=wezterm.action{SendString="\x1b[20;5~"}},            -- `Ctrl + F9`
        {key="raw:76", mods="CTRL", action=wezterm.action{SendString="\x1b[21;5~"}},            -- `Ctrl + F10`
        {key="raw:95", mods="CTRL", action=wezterm.action{SendString="\x1b[23;5~"}},            -- `Ctrl + F11`
        {key="raw:96", mods="CTRL", action=wezterm.action{SendString="\x1b[24;5~"}},            -- `Ctrl + F12`

**Additional context**
N/A

**Comment by wez** [comment]
It's not documented but you can use `F1` through `F24` to map the function keys.

```lua
local wezterm = require 'wezterm';

return {
  keys = {
    {key="F1", mods="NONE", action=wezterm.action{SendString="F1"}},
  },
  debug_key_events = true,
}
```

**Comment by wez** [comment]
keeping this open until I've clarified things in the docs
