### ISSUE TITLE
Feature request to rename a tab manually

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#522]
**Is your feature request related to a problem? Please describe.**
It is sometimes convenient to give a tab a manual label, so it is clear at a glance what we aim to do in that tab.

**Describe the solution you'd like**
The ability to rename a tab manually by clicking on it. In my previous terminal emulator I just double clicked to create an input box, then I entered the text I wanted to set.

Setting it with an empty name restores the title set by the terminal for that tab.

**Describe alternatives you've considered**
For idle tabs we can set it's title through terminal commands. But this is impossible for a long running command, e.g. when we're in `ssh`, or a command that's doing some compute.

**Additional context**
N/A

**Comment by im-n1** [comment]
Feature highly anticipated :) Once you work with many tabs it's hard to remmeber what is where.

**Comment by kar1** [comment]
Wezterm comes with a lot of features and a powerful scripting language. The way to communicate with the terminal is via terminal escape codes.

```
┌──────────┐ escape codes ┌──────────┐           ┌──────────┐
│ Terminal │ -----------> │   Shell  │ --------> │    OS    │
│          │ <----------- │          │ <-------- │          │
└──────────┘              └──────────┘           └──────────┘
```

So if one could set a variable from the shell and change the tab title in the terminal based on that variable one could change the tab title ad hoc. Wezterm has the building blocks for that:

**pane:get_user_vars**
https://wezfurlong.org/wezterm/config/lua/pane/get_user_vars.html?highlight=user#paneget_user_vars

and

**format-tab-title**
https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html?highlight=tab#format-tab-title

So one could make a shell function that sets a variable named fx `panetitle`:

```sh
# First and only argument is the desired term title
function rename_wezterm_title {
  echo "\x1b]1337;SetUserVar=panetitle=$(echo -n $1 | base64)\x07"
}
```

And set the pane/tab title based on that variable in the Wezterm configuration file:

```lua
local wezterm = require 'wezterm';

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  local pane_title = tab.active_pane.title
  local user_title = tab.active_pane.user_vars.panetitle

  if user_title ~= nil and #user_title > 0 then
    pane_title = user_title
  end

  return {
    {Background={Color="blue"}},
    {Foreground={Color="white"}},
    {Text=" " .. pane_title .. " "},
  }
end)

return {}
```

To set the tab title name from the shell:

```sh
rename_wezterm_title "My ad hoc name"
```

And to get the default name scheme for the title back:

```sh
rename_wezterm_title ""
```

I hope this help solve your feature request. For a more elaborate feature request, one could maybe wish for per pane background and gradient settings, i.e. red gradient for production and green for test etc. Or company logo background image on company servers and something else for local shell.

**Comment by wez** [comment]
Thanks @kar1 :)  FWIW, I think there is a legit use case raised in the OP, which is renaming a tab while a long running program is active inside it, but aside from that, the recommendation is to use escape sequences to manage the tab names.

**Comment by Tobbe** [comment]
Just wanted to link my Discussion topic, as I think it has some additional context (and also mentions long running processes) https://github.com/wez/wezterm/discussions/1048

**Comment by Mattwmaster58** [comment]
This is what I do, maybe it will help someone. I use this with multiple different shells on windows, and only care about the label:

```lua
function get_file_name(path)
    local start, finish = path:find('[%w%s!-={-|]+[_%.].+')
    pcall(function(...)
        return path:sub(start,#path)
    end)
end


wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
    local lbl
	for shlindex = 1, #custom_shells do
		if tab.active_pane.title:match(custom_shells[shlindex].args[1], 1, true) then
			lbl = custom_shells[shlindex].label
			break
		end
	end
	return string.format(" %-15s ", lbl or get_file_name(tab.active_pane.title) or tab.active_pane.title);
end)
```

Where `custom_shells` is the value for `launch_menu`. Looks like this:
![image](https://user-images.githubusercontent.com/26337069/146098084-95b810f9-ff1d-4700-92e7-04b1b3aa0568.png)


Does it peg a whole core when you mouse over the tabs? Yes
Do I care? No

**Comment by nicolasbrailo** [comment]
@kar1's is a good idea, but it sets the title of the tab per pane. In a tab with multiple panes, the title displayed depends on the current pane focus. Is there a way to set a user var per tab, instead of doing it per pane?

I tried to set the title by iterating through all the panes, but confusingly this sets the title of ALL tabs:

```
wt.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  -- local title = tab.active_pane.user_vars.panetitle
  local title = "Terminal"

  for i = 1,#panes do
    local t = panes[i].user_vars.panetitle
    if t ~= nil and #t > 0 then
      title = t
    end
  end

  return {
    {Text="  " .. title .. "  "},
  }
end)
```

**Comment by wez** [comment]
I'd like to keep this issue focused: it's about manually changing the title via the UI.
The topic seems to have diverged into programmatically changing the title: I'd be happy to discuss that, but please open a separate issue or discussion thread so that we can keep things focused!

**Comment by atreidesend** [comment]
>it's about manually changing the title via the UI

would be cool if it could be tied into a keybinding as well -- if that falls under the same concept as UI-driven

**Comment by pergamomo** [comment]
`echo "\x1b]1337;SetUserVar=panetitle=$(echo -n "My tab new name" | base64)\x07"`

On MacOS I can't get this to work when inside tmux.

Do I need to escape it somehow?

**Comment by activaigor** [comment]
if somebody is looking for a solution of having a title name being set to the current open dir's name you can set this function in your zshrc
```
function chpwd {
    echo "\x1b]1337;SetUserVar=panetitle=$(echo -n $(basename $(pwd)) | base64)\x07"
}
```

**Comment by MikePresman** [comment]
Any updates to this? Can we expect something out of the box?

**Comment by MikePresman** [comment]
> Wezterm comes with a lot of features and a powerful scripting language. The way to communicate with the terminal is via terminal escape codes.
> 
> ```
> ┌──────────┐              ┌──────────┐           ┌──────────┐
> │ Terminal │ -----------> │   Shell  │ --------> │    OS    │
> │          │ <----------- │          │ <-------- │          │
> └──────────┘ escape codes └──────────┘           └──────────┘
> ```
> 
> So if one could set a variable from the shell and change the tab title in the terminal based on that variable one could change the tab title ad hoc. Wezterm has the building blocks for that:
> 
> **pane:get_user_vars** https://wezfurlong.org/wezterm/config/lua/pane/get_user_vars.html
> 
> and
> 
> **format-tab-title** https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html
> 
> So one could make a shell function that sets a variable named fx `panetitle`:
> 
> ```shell
> # First and only argument is the desired term title
> function rename_wezterm_title {
>   echo "\x1b]1337;SetUserVar=panetitle=$(echo -n $1 | base64)\x07"
> }
> ```
> 
> And set the pane/tab title based on that variable in the Wezterm configuration file:
> 
> ```lua
> local wezterm = require 'wezterm';
> 
> wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
>   local pane_title = tab.active_pane.title
>   local user_title = tab.active_pane.user_vars.panetitle
> 
>   if user_title ~= nil and #user_title > 0 then
>     pane_title = user_title
>   end
> 
>   return {
>     {Background={Color="blue"}},
>     {Foreground={Color="white"}},
>     {Text=" " .. pane_title .. " "},
>   }
> end)
> 
> return {}
> ```
> 
> To set the tab title name from the shell:
> 
> ```shell
> rename_wezterm_title "My ad hoc name"
> ```
> 
> And to get the default name scheme for the title back:
> 
> ```shell
> rename_wezterm_title ""
> ```
> 
> I hope this help solve your feature request. For a more elaborate feature request, one could maybe wish for per pane background and gradient settings, i.e. red gradient for production and green for test etc. Or company logo background image on company servers and something else for local shell.

How can I make the active pane a different color? Thanks for the workaround !

**Comment by Rodrigo-NH** [comment]
I'm not used to Windows prompt. It took me a while to make @kar1 solution to work alongside Powershell.
The working function that goes in Powershell profile:
```cpp
function rename_wezterm_title($title) {
  echo "$([char]27)]1337;SetUserVar=panetitle=$([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($title)))$([char]7)"
}
```

Thanks for WezTerm the best option I've found so far to bring some terminal sanity while on Windows.

**Comment by ShivamJoker** [comment]
Is there any keyboard shortcut for this?
This feature is very important for those who work with many tabs.

**Comment by eleijonmarck** [comment]
just want to expand for anyone that wants to make this part of their daily routine.

https://github.com/wez/wezterm/issues/522#issuecomment-902203635

this works by:
1. add this to your wezterm configuration `vim ~/.wezterm.lua`
```lua
local wezterm = require 'wezterm';

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  local pane_title = tab.active_pane.title
  local user_title = tab.active_pane.user_vars.panetitle

  if user_title ~= nil and #user_title > 0 then
    pane_title = user_title
  end

  return {
    {Background={Color="blue"}},
    {Foreground={Color="white"}},
    {Text=" " .. pane_title .. " "},
  }
end)

return {}
```
2. update your shell .bashrc / .zshrc (initiation of  your shell)
```bash
# First and only argument is the desired term title
function rename_wezterm_title {
  echo "\x1b]1337;SetUserVar=panetitle=$(echo -n $1 | base64)\x07"
}
```
3. source your shell or exit and reopen your shell
4. type `rename_wezterm_title "my new tab title"`

**Comment by ShivamJoker** [comment]
@eleijonmarck how can we execute this with a keyboard shortcut?

**Comment by eleijonmarck** [comment]
@ShivamJoker not sure exactly, you would have to ask for input on the command. But the way to do is to use `bind` in your shell

**Comment by eleijonmarck** [comment]
see zsh docs for binding a key - https://jdhao.github.io/2019/06/13/zsh_bind_keys/

**Comment by ShivamJoker** [comment]
ohh okay thanks

**Comment by jyemeier** [comment]
I've just started looking at using Wezterm, coming from Kitty.  This is a feature Kitty has (I use a shortcut key for it) that I use for all my tabs.  Many of my tabs have multiple panes, so the included work around is cool, but isn't very useful when the pane count > 1

**Comment by wez** [comment]
Over in #1598, I just pushed some changes:

* make the multiplexer aware of tab and window title changes
* added some shortcuts so that you can do something like this via the debug overlay as a one-liner:

```
window:active_tab():set_title("w00t!")
```

without having to write a complicated alias function.

* made the default `format-tab-title` logic take the tab title if it is non-empty, so you shouldn't need to write your own event just for tab titles.

Still missing is a proper UI for setting the title, but the debug overlay snippet above is kinda close.

**Comment by wez** [comment]
And now there is `wezterm cli set-tab-title` for setting via the CLI

**Comment by wez** [comment]
@damanis 

* [tab:get_title()](https://wezfurlong.org/wezterm/config/lua/MuxTab/get_title.html)
* [TabInformation.tab_title](https://wezfurlong.org/wezterm/config/lua/TabInformation.html)

**Comment by wez** [comment]
`main` lets you do activate an overlay prompt. It's not quite the same as click tab title to edit, but it is composable with other actions.  Here's an example of renaming the current tab:

```lua
local wezterm = require 'wezterm'
local act = wezterm.action

local config = wezterm.config_builder()
config.keys = {
  {
    key = 'E',
    mods = 'CTRL|SHIFT',
    action = act.PromptInputLine {
      description = 'Enter new name for tab',
      action = wezterm.action_callback(function(window, pane, line)
        -- line will be `nil` if they hit escape without entering anything
        -- An empty string if they just hit enter
        -- Or the actual line of text they wrote
        if line then
          window:active_tab():set_title(line)
        end
      end),
    },
  },
}

return config
```

**Comment by cd-a** [comment]
@wez I tried this on latest `main`, the prompt shows, but after pressing enter it falls back to the `zsh` prompt, using the exact snippet you pasted above:


https://user-images.githubusercontent.com/75008413/229996712-b6baab41-94be-463e-a6d0-0f3c47190c55.mp4

**Comment by cd-a** [comment]
Thank you, @wez, that was it. I removed the event handler, not needed anymore. 

Works great now!
