### ISSUE TITLE
Gui not opening when size manually set in compositor

### ISSUE THREAD

**Issue by Bryntet** [wez/wezterm#5243]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

hyprland (tag: v0.37.1-85-g6fb8f502)

### WezTerm version

20240325-093507-e5ac32f2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

No terminal window appears

### To Reproduce

in my .config/hypr/hyprland.conf
put the line

`windowrule=size x y,title:^(wezterm)$`
where x and y can be any x and y value (i have checked for many different values, including the default wezterm values of 820x 550y (at least on my system with 1440p 16:10 screen, scaling:1)

### Configuration

bug happens even with no config.

### Expected Behavior

A terminal window should appear

### Logs

i did `$env.WEZTERM_LOG = debug; werterm start --always-new-process` (i use nushell as my shell, which is why the way to declare an ENV var looks a bit different)

15:07:51.111  DEBUG  config > Reloaded configuration! generation=1
15:07:51.111  DEBUG  sctk   > Bound new global [50] wl_output v4
15:07:51.111  DEBUG  sctk   > Bound new global [49] zxdg_output_manager_v1 v3
15:07:51.111  DEBUG  sctk   > Bound new global [14] wl_seat v7
15:07:51.111  DEBUG  window::os::x_and_wayland > Using wayland connection!
15:07:51.128  DEBUG  config                    > Reloaded configuration! generation=2
15:07:51.137  DEBUG  wezterm_font::ftwrap      > set_char_size computing 12 dpi=96 (pixel height=16)
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Argb8888
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Xrgb8888
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Xbgr8888
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Abgr8888
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Bgr888
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Rgbx4444
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Rgba4444
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Rgbx5551
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Rgba5551
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Rgb565
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Xbgr2101010
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Abgr2101010
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Xbgr16161616f
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Abgr16161616f
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Xbgr16161616
15:07:51.140  DEBUG  sctk                      > supported wl_shm format Abgr16161616
15:07:51.140  DEBUG  wezterm_gui::frontend     > workspace is default, fixup windows
15:07:51.146  DEBUG  wezterm_font::ftwrap      > set_char_size computing 12 dpi=96 (pixel height=16)
15:07:51.148  DEBUG  window::os::wayland::window > Config: self.window_state=None, states: (empty) (empty)
15:07:51.148  DEBUG  window::os::wayland::window > dispatch_pending_event self.window_state=(empty), pending:(empty)
15:07:51.148  DEBUG  wezterm_gui::termwindow     > NeedRepaint
15:07:51.148  DEBUG  window::os::wayland::window > Had configured an event
15:07:51.176  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Mode(SetDecPrivateMode(Code(BracketedPaste))))
15:07:51.176  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Cursor(RequestActivePositionReport))
15:07:51.179  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Cursor(RequestActivePositionReport))
15:07:51.182  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Mode(ResetDecPrivateMode(Code(ShowCursor))))
15:07:51.182  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Cursor(Position { line: OneBased { value: 1 }, col: OneBased { value: 1 } }))
15:07:51.182  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Edit(EraseInDisplay(EraseToEndOfDisplay)))
15:07:51.182  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(10))))
15:07:51.182  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(10))
15:07:51.182  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(FinalTermSemanticPrompt(FreshLineAndStartPrompt { aid: None, cl: None }))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(StringTerminator))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Intensity(Bold)))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Intensity(Bold)
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(2))))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(2))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Print('~')
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(FinalTermSemanticPrompt(MarkEndOfPromptAndStartOfInputUntilNextMarker))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(StringTerminator))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(14))))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(14))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform PrintString("> ")
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(5))))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(5))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(DecSaveCursorPosition))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > saving cursor SavedCursor { position: CursorPosition { x: 3, y: 0, shape: Default, visibility: Visible, seqno: 4 }, wrap_next: false, pen: CellAttributes { attributes: 8193, intensity: Bold, underline: None, blink: None, italic: false, reverse: false, strikethrough: false, invisible: false, wrapped: false, overline: false, semantic_type: Input, foreground: PaletteIndex(5), background: Default, fat: None }, dec_origin_mode: false, g0_charset: Ascii, g1_charset: Ascii } is_alt=false
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Cursor(Position { line: OneBased { value: 1 }, col: OneBased { value: 61 } }))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Print(' ')
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Reset
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(5))))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(5))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform PrintString("2024-03-31 15")
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(2))))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(2))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Print(':')
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(5))))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(5))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform PrintString("07")
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(2))))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(2))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Print(':')
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(5))))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(5))
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform PrintString("51")
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(DecRestoreCursorPosition))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > restore cursor SavedCursor { position: CursorPosition { x: 3, y: 0, shape: Default, visibility: Visible, seqno: 4 }, wrap_next: false, pen: CellAttributes { attributes: 8193, intensity: Bold, underline: None, blink: None, italic: false, reverse: false, strikethrough: false, invisible: false, wrapped: false, overline: false, semantic_type: Input, foreground: PaletteIndex(5), background: Default, fat: None }, dec_origin_mode: false, g0_charset: Ascii, g1_charset: Ascii } is_alt=false
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Reset
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Reset
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(DecSaveCursorPosition))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > saving cursor SavedCursor { position: CursorPosition { x: 3, y: 0, shape: Default, visibility: Visible, seqno: 4 }, wrap_next: false, pen: CellAttributes { attributes: 8192, intensity: Normal, underline: None, blink: None, italic: false, reverse: false, strikethrough: false, invisible: false, wrapped: false, overline: false, semantic_type: Input, foreground: Default, background: Default, fat: None }, dec_origin_mode: false, g0_charset: Ascii, g1_charset: Ascii } is_alt=false
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(DecRestoreCursorPosition))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > restore cursor SavedCursor { position: CursorPosition { x: 3, y: 0, shape: Default, visibility: Visible, seqno: 4 }, wrap_next: false, pen: CellAttributes { attributes: 8192, intensity: Normal, underline: None, blink: None, italic: false, reverse: false, strikethrough: false, invisible: false, wrapped: false, overline: false, semantic_type: Input, foreground: Default, background: Default, fat: None }, dec_origin_mode: false, g0_charset: Ascii, g1_charset: Ascii } is_alt=false
15:07:51.183  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Cursor(CursorStyle(SteadyBar)))
15:07:51.183  DEBUG  wezterm_term::terminalstate            > Cursor shape is now SteadyBar
15:07:51.184  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Mode(SetDecPrivateMode(Code(ShowCursor))))
15:07:51.187  DEBUG  wezterm_gui::termwindow                > OpenGL initialized! OpenGL: AMD Radeon Graphics (radeonsi, raphael_mendocino, LLVM 17.0.6, DRM 3.57, 6.8.2-arch2-1) 4.6 (Compatibility Profile) Mesa 24.0.3-arch1.2 wezterm version: 20240325-093507-e5ac32f2
15:07:51.187  DEBUG  wezterm_gui::frontend                  > workspace is default, fixup windows
15:07:51.188  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
15:07:51.188  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
15:07:51.188  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
15:07:51.188  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. }) 

### Anything else?

I'd love to help with debugging/fixing this issue if I could get some pointers as to where it might be located I could probably take a look to see if I could fix it and submit a PR, though of course it might just be easier for you to fix it depending on how complex the issue is. Thank you for making such a great terminal emulator! :)

**Comment by wez** [comment]
Could you try the latest nightly build?
