### ISSUE TITLE
”\r\n“ not processed under windows

### ISSUE THREAD

**Issue by vamoosebbf** [wez/wezterm#5247]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

SSH linux terminal be an extra blank line between each line while paste from the windows clipboard

wezterm-client\src\pane\clientpane.rs
```python
function send_paste() 
  let data = text.to_owned();
  # let data = text.replace("\r\n", "\r").replace("\n", "\r").to_owned();
```
reference: https://github.com/alacritty/alacritty/blob/d4f2f8577f763df059653dfab733dfe6ddc06913/alacritty/src/event.rs#L851

### Configuration

none

**Comment by wez** [comment]
See https://wezfurlong.org/wezterm/config/lua/config/canonicalize_pasted_newlines.html
