### ISSUE TITLE
`wezterm cli list` hangs indefinitely from an SSH session

### ISSUE THREAD

**Issue by adamency** [wez/wezterm#5251]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I want to know the list of running wezterm windows, tabs and the programs running inside from an SSH session. Unless I misunderstood the functionality of `wezterm cli` (is it supposed to only work from inside a wezterm window ?), this should work right ? There is one and only one `wezterm-gui` process running without issues in the system.

### To Reproduce

Have an SSH-accessible system with Linux, X headless (with `xorg-xf86-dummy`) and i3 on it. Run `wezterm`, open some tabs and then connect via SSH from another machine and run `wezterm cli list`.

### Configuration

default

### Expected Behavior

have the command return successfully

**Comment by wez** [comment]
This works for me. I suspect there is something else happening in that environment. It might be interesting to strace the wezterm cli process and see what it is getting stuck on, and/or running `WEZTERM_LOG=trace wezterm cli list`
