### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by pronebird** [wez/wezterm#5256]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Debian 12

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No

### Describe the bug

I noticed that wezterm silently disappears from my debian VM from time to time and I swear I don't close it myself. Does wezterm write crash logs somewhere so I can prove that I am not crazy and perhaps help find the cause of this?

### Configuration

```lua
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.color_scheme = 'AdventureTime'
config.font_size = 14

return config
```

**Comment by RomanAverin** [comment]
This is a wayland implementation problem. A temporary solution is to use XWayland.
`config.enable_wayland = false`

**Comment by wez** [comment]
Please try the latest nightly build
