### ISSUE TITLE
"Open WezTerm here" (when right click at file explorer's background) in WIN10 context menu have no effect when in root directory, with a weird solution.

### ISSUE THREAD

**Issue by flyxyz123** [wez/wezterm#526]
Please see the following link for details of the bug and its solution.\
<https://github.com/alacritty/alacritty/issues/4882#issue-825561096>

I realized I might put the issue in the wrong place after keep trying to fix the bug. I think I can't delete the issue so I just put the link here.

**Comment by flyxyz123** [comment]
It looks like .iss is different than .reg. I'm not sure how to change line 69 to achieve the solution.
<https://github.com/wez/wezterm/blob/3f91e30719d5fd30d808fe3af99c4dc509546a90/ci/windows-installer.iss#L63-L72>

I'm not sure what this code `""%V\\"""`  from line 69 should be change to to let the final key value shown as `"%V` after installation process. 

```
Root: HKA; Subkey: "Software\Classes\Directory\Background\shell\Open WezTerm here\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" start --no-auto-connect --cwd ""%V\\"""; Flags: uninsdeletekey;
```

I use ` \"%V"` in my gist .reg file to assign `"%V` as final key value. It looks like .iss and .reg have different syntax. So I'm not sure if the same code will have the effect.\
<https://gist.github.com/flyxyz123/53ac952fe94a14482565f1d96e5704d5>

I'll try to build it to test the result if I have time. It's a very minor bug tho.

**Comment by wez** [comment]
Thanks for investigating!  Would you mind contributing a `.reg` file that demonstrates this working in all three cases?
That would help answer https://github.com/wez/wezterm/issues/486 and from there I can figure out how to apply it to the installer script so that we can resolve https://github.com/wez/wezterm/issues/451

**Comment by flyxyz123** [comment]
I shared a gist link to the `.reg` file that demonstrates this working in all three cases on the second comment in this issue. However, It is for Alacritty that downloaded by Scoop. You might need to change the directory a little bit for this to work for Wezterm. I'll try to make a new .reg file for Wezterm if have time.\
<https://gist.github.com/flyxyz123/53ac952fe94a14482565f1d96e5704d5>
