### ISSUE TITLE
WezTerm is eating my keyboard shortcut?

### ISSUE THREAD

**Issue by s4my** [wez/wezterm#5285]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Gnome 42.9

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have setup a keyboard shortcut in nvim to comment out code using the [comment.nvim](https://github.com/numToStr/Comment.nvim) plugin which does not work on WezTerm, but works on all other terminal emulators I tried (i.e., Gnome Terminal, tilda, konsole, terminator).
For reference I have the shortcut setup  in my nvim config like so:
```vim
vim.keymap.set('n', '<c-_>', '<Plug>(comment_toggle_linewise_current)')
vim.keymap.set('x', '<c-_>', '<Plug>(comment_toggle_linewise_visual)')
```

 The keyboard shortcut is `CTRL+/` but in AZERTY keyboards I have to hit `CTRL+SHIFT+:`. When I hit this keyboard shortcut WezTerm treats it as if i just type `/`. nvim switches to COMMAND mode (i.e., activate the search functionality) as you can see below.

![output](https://github.com/wez/wezterm/assets/16526701/21bb5f7d-a844-4861-94c2-1982d4c464ef)

### Configuration

```lua
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.debug_key_events = true
config.keys = {
    {
        key="d",
        mods="SHIFT|CTRL",
        action="ShowDebugOverlay"
    },
}

return config
```

### Logs

06:53:22.623 INFO wezterm_gui::termwindow::keyevent > send to pane UP key=LeftShift mods=SHIFT
06:53:24.351 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }
06:53:24.351 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftShift, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
06:53:24.351 INFO wezterm_gui::termwindow::keyevent > send to pane DOWN key=LeftShift mods=NONE
06:53:24.457 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: SHIFT, leds: (empty), phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }
06:53:24.457 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftControl, modifiers: SHIFT, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: SHIFT, leds: (empty), phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
06:53:24.457 INFO wezterm_gui::termwindow::keyevent > send to pane DOWN key=LeftControl mods=SHIFT
06:53:24.673 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(D), modifiers: SHIFT | CTRL, leds: (empty), phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) }
06:53:24.674 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('D'), modifiers: CTRL, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(D), modifiers: SHIFT | CTRL, leds: (empty), phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
06:53:24.674 INFO wezterm_gui::termwindow::keyevent > Char('D') CTRL -> perform ShowDebugOverlay

**Comment by bluss** [comment]
Note that on "less advanced" terminals, <c-_> and <c-/> overlap (literally the same control code byte), but wezterm enables the kitty keyboard protocol and neovim supports it. In this new protocol, <c-_> and <c-/> don't overlap anymore, they are different!

Because of that in wezterm you need to map <c-/> in neovim if you think of the mapping as <c-/>.

**Comment by s4my** [comment]
@bluss thank you for the help, you're correct 👍🏻 .

**Comment by bluss** [comment]
Great, have fun

This table is a reference for the legacy mapping - you can find some surprising overlaps (Ctrl 5 is the same as Ctrl ] and so on.)

https://sw.kovidgoyal.net/kitty/keyboard-protocol/#legacy-ctrl-mapping-of-ascii-keys

On wezterm you can enjoy that Ctrl+i and Tab are now separate in neovim.
