### ISSUE TITLE
wezterm starts 32 background threads with a cpu load from 30% - 60%

### ISSUE THREAD

**Issue by elfenpiff** [wez/wezterm#5287]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

awesome

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Start wezterm and there are 32 threads started - the same amount as my CPU core count. Every thread has a CPU load between 20 - 60%. Curiously, every thread has the identical CPU load.

### To Reproduce

Start wezterm. CPU load goes up when something like neovim is started and the cursor moves.

### Configuration

no config

### Expected Behavior

* No 32 background threads
* Low CPU load, not up to 60%

### Logs

Debug Overlay
wezterm version: 20240203-110809-5046fc22 x86_64-unknown-linux-gnu
Window Environment: X11 awesome
Lua Version: Lua 5.4
OpenGL: llvmpipe (LLVM 17.0.6, 256 bits) 4.5 (Compatibility Profile) Mesa 24.0.3-arch1.2
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
10:27:53.914 WARN window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: get_appearance.read_setting: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
10:37:44.997 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)

**Comment by elfenpiff** [comment]
Seems like it is connected to #5234

**Comment by wez** [comment]
Can you build from source with debug symbols and get stack traces from those threads?
