### ISSUE TITLE
Crash when using wezterm cli to run shell file wo executable permissions

### ISSUE THREAD

**Issue by thomasaarholt** [wez/wezterm#5290]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240405-180910-cce0706b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I discovered the following bug while using wezterm to create a script integration for the [helix](https://helix-editor.com/) (vim-like) text editor. I call a wezterm cli function in order to split the pane, and then run a shell script in that window.

### To Reproduce

Create a file called `test.sh` in your current terminal directory containing:
```bash
echo hello
read
```
Do not alter its permissions. This script should print "hello", and prevent the bash instance from closing until the user presses enter.

Call `wezterm cli split-pane -- test.sh` in order to create a separate pane, running `test.sh` in it.
Wezterm becomes unresponsive, requiring a force quit.

Now, change the permissions to allow the shell script to be executable via a command like `chmod +x test.sh`. Rerunning `wezterm cli split-pane -- test.sh` now succeeds.

### Configuration

no config

### Expected Behavior

No crashes, possibly an error message like `zsh: permission denied: ./test.sh`

### Logs
```
# There is only one file with this single line - I deleted all log files, then tried triggering the bug again
15:35:27.003  INFO   wezterm_gui::termwindow > QuitApplication over here (window)
```

**Comment by wez** [comment]
I can't reproduce this; this is what I see:

<img width="686" alt="Screenshot 2024-05-05 at 17 16 10" src="https://github.com/wez/wezterm/assets/117777/40f8514e-f4a9-4e9b-9233-4a62f91c9ac2">

is there something else in your config or environment that might be influencing this?

**Comment by thomasaarholt** [comment]
Curious! I can no longer reproduce the error, and I do get the same behaviour that you describe. Before testing now, I ran `brew install wezterm`, found no error, and then tried the nightly version with the same result.

I suggest we just close this, and if I can reproduce in the future then we can have another look. Thanks for checking, and for writing a great terminal emulator!
