### ISSUE TITLE
nightly builds

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#530]
we used to be able to download nightly builds by going through the commit and being able to download.

seems like it is no longer possible now.

would it be possible to have a special nightly tag that gets updated every day or so? similar to how neovim does it?
https://github.com/neovim/neovim/releases/tag/nightly

**Comment by wez** [comment]
The nightly download links on the website all link to builds under the nightly release: https://github.com/wez/wezterm/releases/nightly

**Comment by prabirshrestha** [comment]
Release mentions 2019. 

Does this get updated every day or so? If that is the case I’m hood with it.

**Comment by wez** [comment]
It's updated by every commit to master

**Comment by prabirshrestha** [comment]
Awesome. I'm closing then.

Might be should update the descript to `[Last updated: Date/Commit hash]`?
