### ISSUE TITLE
Colorscheme "alacritty" is broken

### ISSUE THREAD

**Issue by chrisgrieser** [wez/wezterm#5307]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The colorscheme "alacritty" does nothing.

### To Reproduce

Set `colors_scheme = "alacritty"` in the wezterm config.

### Configuration

`colors_scheme = "alacritty"`

### Expected Behavior

color scheme to be working / including the necessary information

### Logs

In the console running `wezterm.color.get_builtin_schemes().alacritty` outputs only this:
```lua
{
    "indexed": [],
}
```

### Anything else?

I noticed this, since it broke my theme cycler: https://github.com/wez/wezterm/discussions/3426

**Comment by wez** [comment]
Fixed in 7f35aac7a96c645b6537c49492b679f7ec4e9a2e
