### ISSUE TITLE
Missing debug.traceback?

### ISSUE THREAD

**Issue by jaidetree** [wez/wezterm#5323]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When I learned about Wezterm I jumped at the opportunity to load in fennel to write my config. This is also consistent with neovim and hammerspoon.

After exploring working with macros it turns out https://git.sr.ht/~technomancy/fennel/tree/main/item/src/fennel/compiler.fnl#L446 refers to an expected lua global debug.traceback. It exists in Hammerspoon and Neovim, but not in Wezterm

### To Reproduce

1. Download fennel.lua into your wezterm directory
2. Create a basic fennel file like the following perhaps named macro-test.fnl (as below)
4. Load fennel into wezterm.lua and require the macro-test.fnl file (as below)
5. Reload wezterm config

### Configuration

macro-test.fnl
```fennel
(macro postfix3 [x1 x2 x3]
  (list x3 x2 x1))

(postfix3 "world" "hello" print)
```

wezterm.lua
```lua
fennel = dofile(configdir .. '/vendor/fennel.lua')
fennel.install()

require("macro-test.fnl")
```

### Expected Behavior

The macro should get compiled at require time and eval to `(print "hello" "world")` which logs to the debug window.

### Logs

```
12:18:10.877 ERROR wezterm_gui::termwindow > Failed to apply config overrides to window: runtime error: /Users/j/.config/wezterm/vendor/fennel.lua:2871: attempt to index a nil value (global 'debug')
stack traceback:
        /Users/j/.config/wezterm/vendor/fennel.lua:2871: in local '_342_'
        /Users/j/.config/wezterm/vendor/fennel.lua:2874: in function 'fennel.compiler.macroexpand'
        /Users/j/.config/wezterm/vendor/fennel.lua:3065: in function 'fennel.compiler.compile1'
        /Users/j/.config/wezterm/vendor/fennel.lua:3332: in function 'fennel.compiler.compile-stream'
        (...tail calls...)
        /Users/j/.config/wezterm/vendor/fennel.lua:5372: in function </Users/j/.config/wezterm/vendor/fennel.lua:5369>
        (...tail calls...)
        [C]: in function 'require'
        [string "/Users/j/.config/wezterm/wezterm.lua"]:25: in main chunk: nil
```

### Anything else?

If you run a lua script directly against the lua binary that uses the same code, it works as expected, same if ran in neovim or hammerspoon.

I get that fennel support is not a high priority, but is it unreasonable that a library or plugin might want to use `debug.traceback` or similar apis?

**Comment by wez** [comment]
The lua `debug` module is not safe and it is not initialized in the lua runtime that is embedded into wezterm.
This is working as intended.

**Comment by jaidetree** [comment]
Unfortunate but thanks for your response!
