### ISSUE TITLE
Startup Crash - Gnome 46 w/ Scaling

### ISSUE THREAD

**Issue by peteigel** [wez/wezterm#5340]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter (Gnome 46)

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

I tried building from source. It launches fine at any scale, but doesn't show window decorations. I _think_ I had built it successfully from source before.

### Describe the bug

Wezterm Flatpak crashes on Gnome 46 display scale is not 100%.

I used wezterm with 125% scaling daily in Fedora 39, and it won't start on Fedora 40. I was able to reproduce at both 125% and 200% scale.

### To Reproduce

- Install WezTerm flatpack on Fedora 40
- Set display scale to a value other than 100%
- Launch WezTerm

### Configuration

no config

### Expected Behavior

App launches properly

### Logs

```
wl_surface@44: error 2: Buffer size (12x575) must be an integer multiple of the buffer_scale (2).
```

**Comment by l-c-g** [comment]
I see the same thing, Gnome 46 on Fedora 40, with 2x scaling on my laptop display (fractional scaling is enabled, though, to run in 1.5x docked):
```sh
wl_surface@44: error 2: Buffer size (12x613) must be an integer multiple of the buffer_scale (2).
```

**Comment by farmerbb** [comment]
Disabling Wayland in my config allows WezTerm to start for me on Gnome 46:

```
config.enable_wayland = false
```

**Comment by 4ndv** [comment]
Same issue for me on Hyprland. Starting on non-scaled display is fine, but not on scaled. Moving wezterm window from non-scaled display to a scaled one also causes crash.

Logs:

```
03:13:41.298  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 47, cols: 82 }) because window_state is MAXIMIZED
xdg_surface@27: error 3: xdg_surface has never been configured
Protocol error 3 on object xdg_surface@27: 
03:13:41.333  ERROR  wezterm_gui                     > running message loop: Protocol error 3 on object xdg_surface@27: ; terminating
```

**Comment by wez** [comment]
Please try with the very latest nightly build, as a lot of wayland changes have recently been merged

**Comment by l-c-g** [comment]
I tested the AppImage nightly downloaded today and version wezterm-20240505_232355_e6db4408-0.x86_64 from the [COPR repo](https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/). Both start on my Fedora 40/Gnome 46 installation with 200% scaling, so my issue with Gnome 46 appears to be fixed.

**Comment by broizter** [comment]
> Please try with the very latest nightly build, as a lot of wayland changes have recently been merged

Nightly AppImage fixes the issue.

**Comment by peteigel** [comment]
In the latest main scaling is fixed, but window decorations missing. I've reproduced that both building from source and from the latest nightly in the COPR repo, I suppose I can open a separate issue for that if that would be helpful.

![image](https://github.com/wez/wezterm/assets/4098889/390fb4e2-ce78-4b6a-91d1-2e9ddf6f9043)

**Comment by peteigel** [comment]
I'm going to close this issue. The scaling problem has been resolved and the missing window decorations are tracked by #4962 .

Disabling wayland (with `config.enable_wayland = false`) is good workaround for affected users.
