### ISSUE TITLE
Character cell sometimes padded with an additional pixel.

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#535]
## Describe the bug

(note, could not be a bug but working-as-intended but see below in _Additional context_ why this can break things for a potential better way)

Reading the window size character cells and in pixels and pixels they consume can change when window size is changed.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: compiled from head: `20210203-095643-70a364eb-217-g9ddc2da6`

## To Reproduce

Read the window size:

```c
/* gcc -o winsize winsize.c */

#include <stdio.h>
#include <sys/ioctl.h>
#include <termios.h>
#include <unistd.h>

int main() {
  struct winsize w;
  if (ioctl(STDIN_FILENO, TIOCGWINSZ, &w) != 0) {
    printf("Can't determine window size\n");
    return 1;
  } else {
    printf("Cells: %d x %d\nWindow size:%dpx x %dpx\n"
	   "cell-size: %d/%d x %d/%d = %dpx x %dpx (modulo: %d, %d)\n",
	   w.ws_col, w.ws_row,  w.ws_xpixel, w.ws_ypixel,
	   w.ws_xpixel, w.ws_col, w.ws_ypixel, w.ws_row,
	   w.ws_xpixel / w.ws_col,  w.ws_ypixel / w.ws_row,
	   w.ws_xpixel % w.ws_col,  w.ws_ypixel % w.ws_row);
  }
  return 0;
}
```

Run this program, note the character cell size. Resize window and run again. In some settings the character cell size changes by a pixel. In the following example, between a resize, the size of a character cell changes from **10**_px_ **x 22**_px_ to **10**_px_ **x 23**_px_.

![wezterm-resize-pixels](https://user-images.githubusercontent.com/140937/111036715-7b9b9a80-83d5-11eb-8547-9d048f0473fd.png)

## Expected behavior

Expected would be that the cell-size (pixels / cell-count) is consistent and only a function of the font used, independent of the size of the window.

## Additional context

This might be _working-as-intended_ in an attempt to best use the space available in the window without creating an awkward border all around.

But I think it will create more trouble in situations where the assumption that a character fills the entire character cell will broken; because naturally the single pixel cell spacing now will have the background color.
So in all situations that uses graphical characters, such lines or blocks with use of foreground and background color will create different results depending on the size of the window and leave fine lines.

[timg](https://github.com/hzeller/timg) is an example. It has a workaround mode in which the user can choose if an upper or lower block should be used to [mask the issue](https://github.com/hzeller/timg#what-a-problematic-choice-of-block-looks-like), but that only works for half-sized blocks.

## Possible solution

So instead of adding inter-spacing between character cells, I suggest to just add the necessary padding just as a frame around the window. Even if it will mean that this is can be up to half a character cell of empty space around the window, it will leave a consistent character block experience.

**Comment by wez** [comment]
Good catch!  I think I found the spot and pushed a commit to make sure that we report pixel dimensions based on cell dimensions * font metrics.

**Comment by hzeller** [comment]
Confirmed, looks like the size is now stable.

If your font size is also 10x22 (which is the default out of a fresh compile on my machine, but that might as well really depend on what fonts I have available on my system I suppose), then the video-snippet from #534 should also not scroll anymore.

I think this can be closed.
