### ISSUE TITLE
Color display is inaccurate

### ISSUE THREAD

**Issue by shelken** [wez/wezterm#5358]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

WezTerm color display is inaccurate.

### To Reproduce

My color scheme is Catppuccin Macchiato.

https://github.com/wez/wezterm/blob/0184e88e97b6521df613df4ccdb2e896ce8b0ad0/docs/colorschemes/data.json#L6644

Its yellow color value is `#EED49F`.

You can get the yellow color value from the screenshot below. The left side shows it in Kitty, and the right side shows it in Wezterm.
Kitty displays it correctly (`#EED49F`), but Wezterm displays (`#F0D9A9`).

<img width="1911" alt="image" src="https://github.com/wez/wezterm/assets/33972006/d33344b5-41fa-4408-993b-3e467a18c5f2">

### Configuration

```lua
local wezterm = require("wezterm")
local config = {
	font_size = 18,
	font = wezterm.font("FiraCode Nerd Font Mono", { weight = "Medium" }),
	color_scheme = "Catppuccin Macchiato", -- or Mocha, Frappe, Latte, Macchiato

	use_fancy_tab_bar = false,
	hide_tab_bar_if_only_one_tab = true,
	window_decorations = "RESIZE",
	show_new_tab_button_in_tab_bar = false,
	window_background_opacity = 0.88,
	macos_window_background_blur = 64,
	adjust_window_size_when_changing_font_size = false,
	window_padding = {
		left = 10,
		right = 10,
		top = 12,
		bottom = 0,
	},
}

return config
```

### Expected Behavior

Display correct colors.

**Comment by wez** [comment]
Consider changing https://wezfurlong.org/wezterm/config/lua/config/front_end.html to WebGpu or OpenGL.
Use the debug overlay (CTRL-SHIFT-L) to see which front end is in use.

**Comment by shelken** [comment]
> WebGpu

It works when `front_end = "WebGpu"`. 

Problem solved, thank you very much.
