### ISSUE TITLE
U+258C Left half block does not fill entire left half of cell (maybe just font issue ?)

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#536]
## Describe the bug

Using the default configuration, block characters don't always fill the entire cell.

## Environment 

 - OS: Linux X11
 - Version: `20210203-095643-70a364eb-217-g9ddc2da6`
 
## Configuration

```lua
local wezterm = require 'wezterm';
return {
  font = wezterm.font("JetBrains Mono"),
}
```

## To Reproduce

Let's print a space followed by an inverse U+258C Left half block:

```
echo -e " \033[7m\u258c\033[0m"
```

![left-half-block-hairline](https://user-images.githubusercontent.com/140937/111040598-827fd880-83e8-11eb-9342-dca06e6a19c6.png)

The inverse printed left block shows that there is a single line of background color on the left side of the block, that should be flush all the way to the left of its cell.

### Maybe just a font issue

This might actually not be an issue in wezterm but just a problem in the font used. I don't really know how to inspect that though. If confirmed, we should file that with the JetBrains folks.

### Context
This creates artifacts when using `timg -pquarter <filename>` rendering. Notice the vetical line artifacts below in the 'Don't panic' text

![line-artifacts](https://user-images.githubusercontent.com/140937/111040819-d9d27880-83e9-11eb-8aae-a6a2a7473f10.png)

**Comment by wez** [comment]
I haven't looked deeply at this yet, but wanted to note that wezterm will compute block glyphs for itself by default; this is controlled by https://wezfurlong.org/wezterm/config/lua/config/custom_block_glyphs.html
This is to avoid a hinting bug in freetype with the font's native block glyphs.

**Comment by hzeller** [comment]
Confirmed, this looks good now!

![no-line-artifact-anymore](https://user-images.githubusercontent.com/140937/111042191-0047e200-83f1-11eb-8cf4-ab89f9c93436.png)

Thanks!

**Comment by wez** [comment]
Thanks for catching this! It was invisible to a simple visual inspection via https://github.com/wez/wezterm/blob/main/test-data/blocks.py
