### ISSUE TITLE
Crash when system colour scheme changes in GNOME 46 with Wayland

### ISSUE THREAD

**Issue by aral** [wez/wezterm#5364]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Following error when colour scheme changes (sometimes, not every time).

![image](https://github.com/wez/wezterm/assets/41798/68b630a7-be4f-45fd-9728-163b9f30eaf8)

### To Reproduce

Keep flipping between the dark and light colour schemes until it happens.

### Configuration

n/a

**Comment by wez** [comment]
Please try the most recently nightly build

**Comment by aral** [comment]
Hey @wez, just tested with the latest nightly AppImage and it no longer crashes.

With multiple windows open, I see that some of the windows react slower than others (is it now polling?) and if I very quickly switch back and forth between dark and light mode, it does take quite a while for the windows to finally catch up but they are eventually consistent. (That’s an edge case and nothing to worry about, really.) I’m happy to mark this as resolved from my end – thank you :)
