### ISSUE TITLE
imgcat shows black image instead of an image

### ISSUE THREAD

**Issue by adelarsq** [wez/wezterm#5365]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240429-102818-0184e88e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

For some reason imgcat shows a black image instead:

<img width="660" alt="Captura de Tela 2024-05-02 às 21 18 24" src="https://github.com/wez/wezterm/assets/430272/f49bed53-f0a6-48eb-8685-a367cabcdcd2">

This was the image used:

![8cd747ff56496debdbe8c8d8e90ec61e](https://github.com/wez/wezterm/assets/430272/73be11d3-feca-47a3-a0d7-9a231dc60650)

And this is the metadata:

```bash
$ file 8cd747ff56496debdbe8c8d8e90ec61e.jpg
8cd747ff56496debdbe8c8d8e90ec61e.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 100", baseline, precision 8, 1280x800, components 3
```

### To Reproduce

Can be reproduced by using the provided image.

### Configuration

 no config

### Expected Behavior

To show the image

### Logs

Debug Overlay
wezterm version: 20240429-102818-0184e88e x86_64-apple-darwin
Window Environment: Mac OS X 10.15.7 (19H2026)
Lua Version: Lua 5.4
OpenGL: Intel HD Graphics 4000 OpenGL Engine 4.1 INTEL-14.7.28
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
21:24:57.901 WARN wezterm_gui::glyphcache > image decoder thread terminated
21:24:57.901 ERROR wezterm_gui::glyphcache > Error decoding image: decode image: failed to fill whole buffer

**Comment by wez** [comment]
That error message comes from the upstream image and jpeg decoder crates.
I believe that the input image is subtly corrupt and the consequence is that it fails to decode at all because the jpeg decoder has no error recovery logic.
I've updated to a newer version of the image crate which now uses a different jpeg decoder, and this issue is now resolved for me.

**Comment by wez** [comment]
The fix should be available in a nightly build within about an hour from now

**Comment by adelarsq** [comment]
@wez Fix confirmed. Thanks a lot!
