### ISSUE TITLE
Improve performance of Graphics mode

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#537]
**The graphics mode is pretty slow currently**

Watching videos with `timg` on WezTerm is very slow for moderate sized videos; usually a framerate of 24 can not be reached.

For instance, sending 620x360ish size frames I get on my machine about **10fps** with WezTerm compared to  **43fps** with [Kitty](https://sw.kovidgoyal.net/kitty/) (using their protocol; but similarly to what I send to WezTerm this is essentially uncompressed RGB encoded as base64).

**Describe the solution you'd like**

I suspect there are some low-hanging performance fruits to be picked. The image data in particular sent via the protocol is a simple P6 netpbm, so it contains all the RGB data already in plain sequence, hence should be fast to convert to an internal RGB representation without any decoding or decompression needed. Or it is the base64 decoding ?

You might be able to quickly drill down to the problematic places.

**Additional context**
I've now added [auto-detection of WezTerm](https://github.com/hzeller/timg/commit/e62409fd2c1875d6d7f14d52d6e4aeeb3b3c3b83) in timg, so the full graphics mode is automatically chosen when running in a WezTerm.
However, I am worried that the user-experience might not be optimal.

**To reproduce**

I suggest to 'pre-record' a output with timg with a pre-set number of frames, then it is easy to replay simply with `cat` and note the time it took and use that as a baseline for future improvements.

```
timg some-movie.mp4 -pi --frames=1000 > /tmp/frames.out
time cat /tmp/frames.out
real    1m38.988s
```

**Comment by wez** [comment]
I think the current state is much improved; I'd appreciate your feedback to confirm!

**Comment by hzeller** [comment]
Nice, the raw throughput is now much improved, it can play videos now almost in realtime!

The 'cat' frame benchmark from above in fact now looks pretty comparable to the other terminal I was comparing it to.

However, the motion is jerky. It looks like the frames are not evenly spaced in time, probably some bunched up at once, then a little gap. 

The CPU use of the wezterm process is 105% on my machine, which could indicate that there is not enough headroom yet to receive, process, display, wait for next frame (The same video on the Kitty terminal looks smooth; that terminal emulator uses about 40% CPU).

The previous wezTerm was maxing out at 135% CPU, and could not keep up. Now we're down to 105% CPU and it sort of keeps up. Probably only another 2x improvement step away. Or one order of magnitude as we'd say in binary :)

Overall a good improvement so far! Let me know if there are things that I should run/compare/profile on my machine.

**Comment by wez** [comment]
Alright, I think I got that 2x with the latest changes!

**Comment by hzeller** [comment]
Oh, very nice. Yes, this now reduced the CPU use in this case to 75%, and things look 'smoother'.

It is still visually more jerky movement compared to Kitty, but it is less noticeable than before.
It feels like some images are 'swallowed' in the process; maybe some GPU pipeline thing where it tries to coalesce small changes and doesn't bother updating a region ? I don't know GPU programming, is there something that flushes what is pending ?

Fun fact: am currently experimenting sending PNG encoded images instead. While `timg` uses more CPU, it reduces the CPU-use in wezTerm by about 10 percent points to about 65%-ish. So even though you have to do PNG decompressing, things are faster. That indicates that the base64 decoding might be the relative expensive part, as now the data to base64-decode is much less.

**Comment by hzeller** [comment]
If you want to play with it: I've pushed the version of `timg` that allows to optionally compress the pixels being transferred in the image protocol. If you add the `--compress-pixel` option, the image content is PNG compressed before sending over; without, the regular `P6` netpbm format is sent.
(option not documented yet in manpage or README; currently I consider it experimental)

**Comment by wez** [comment]
Well, it's interesting what a profiler can show you.  The bottleneck was actually in uploading textures to the GPU.  There was some long-forgotten code that did gamma and byte swapping adjustments which would allocate an intermediate buffer in paths that were not deemed to be hot for normal terminal operation, but that are very hot when used with timg.

The current state of `main` now runs at about 50-60% CPU utilization for me on both linux and mac, and the profiler shows that the majority of the effort is in accumulating the very large OSC buffers.  Base64 and image decoding are insignificant percentages in the profile.  I didn't notice a significant impact for `--compress-pixel` with the upload bottleneck removed.  My theory is that the impact you saw was due to fewer GPU synchronization blips and/or uploads due to the changed timing and shape of the incoming data.

I also ran my test scenario (250 frames of a sample video at 25fps, which should take 10 seconds to playback) on iTerm2; it's performance isn't great for this workload: it took 37s to playback that data.

I don't think there are any immediately low hanging fruits remaining: the hottest parts in the profile are now in code in the Rust standard library that are already well optimized.  I suspect the next step function optimization would be to use a different protocol for this.

**Comment by wez** [comment]
Speaking of alternate protocols: have you considered encoding as animated gifs (or perhaps animated png?) for `-pi`?  I wonder if eg: converting a few seconds of video at a time to animated gif/png at a time and sending that to the terminal would result in better overall CPU and throughput?

**Comment by hzeller** [comment]
Wonderful, I just tested the latest changes, and it is very smooth now. I think you reached what can be done.

w.r.t to accumulating buffers: I send everything in a single big write() call with all the data. So if it helps, reading things in a larger buffer before parsing might save a few system calls (with `strace` I see that WezTerm does reads into relatively small 4kiB buffers).

Animated gifs or pngs: this might indeed be an option. `timg` started out as a program that does Unicode block-encoding, so there the framebuffer had to be converted one-by-one to block-graphics, and the notion of changed content was entirely driven by the thing that reads the images and provides one or a sequence of framebuffers.

It works currently the traditional way as the iTerm2 or Kitty protocols are just a quick first implementation, because the infrastructure inside `timg` delivering sequences of framebuffers to 'terminal canvases' was already there; then just sending it almost verbatim in base64 encoding was straightforward. The [initial implementation](https://github.com/hzeller/timg/commit/963ed22cf9ef5925426b8a564e6d311c1ba05843) of the iTerm2 protocol was in fact just a quick hack in a lunch break, when someone told me about the graphics protocol on Friday morning.

But now, with `-pi` established, there is a potential to actually re-encode sequences of pictures in one data-blob that represents the entire animation (it might need some special casing and only work in some circumstances; e.g. animations with a limited number of frames is ok, videos would need to be sent 'traditionally' as sequence of frames).
(Kitty has its own implementation of animations, so that might need a slightly different approach).

I don't have access to an iTerm2 (no Mac around), so can't really test it (in fact I only could implement iTerm2 support because I could test on your wezterm!). I am sure that author was also not necessarily prepared for someone blasting image content in that way :)
I need to ask around for people I know who use a Mac to test and possibly file feature requests with iTerm2.

Anyway, I think this feature request has been thoroughly and successfully addressed. Thank you!
Ready  to close :)

**Comment by wez** [comment]
> w.r.t to accumulating buffers: I send everything in a single big write() call with all the data. So if it helps, reading things in a larger buffer before parsing might save a few system calls (with strace I see that WezTerm does reads into relatively small 4kiB buffers).

Yeah, I did experiment with increasing the buffer size: it doesn't have any noticeable impact so I kept it at 4k.  In general, I like big buffers!

>  I am sure that author was also not necessarily prepared for someone blasting image content in that way :)

It is a very punishing workload for a terminal emulator!
