### ISSUE TITLE
Version error connecting to linux multiplexer after automated windows wezterm update

### ISSUE THREAD

**Issue by Capri205** [wez/wezterm#5380]
### What Operating System(s) are you seeing this problem on?

Windows, Linux (Oracle Linux 8.9 - formerly Centos8)

### Which Wayland compositor or X11 Window manager(s) are you using?

none. headless linux dev server

### WezTerm version

20240203_110809_5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, tried multiple nightly builds including the latest.

### Describe the bug

Windows version was updated to 20240203_110809_5046fc22 overnight, so I updated to the same version on Centos8, however I keep getting the same multiplexer version mismatch error when executing 'wezterm connect dev1', despite both being on the same version. I've tried uninstalling and reinstalling on both platforms (and rebooted both to clear any lingering processes), tried the nightly builds also, but get the same error. I can see the wezterm-mux-server process starting up fine on the centos8 (oracle linux 8.9) server. No errors in its log.

Windows
>wezterm --version
wezterm 20240203-110809-5046fc22

>wezterm-mux-server --version
wezterm-mux-server 20240203-110809-5046fc22

Centos8
>wezterm --version
wezterm 20240203-110809-5046fc22

>wezterm-mux-server --version
wezterm-mux-server 20240203-110809-5046fc22

>wezterm connect dev1
10:46:21.407  ←[31mERROR ←[0m ←[1mwezterm_client::client←[0m > Error while decoding response pdu: decoding a PDU: decode_raw: Corrupt Response
10:46:21.411  ←[31mERROR ←[0m ←[1mmux::connui           ←[0m > while running ConnectionUI loop: recv_timeout: channel is empty and disconnected
10:46:21.411  ←[31mERROR ←[0m ←[1mwezterm_client::client←[0m > wezterm cli --prefer-mux proxy: Exited with code 1
10:46:21.411  ←[31mERROR ←[0m ←[1mwezterm_gui           ←[0m > Please install the same version of wezterm on both the client and server! The server reported error 'Error while decoding response pdu: decoding a PDU: decode_raw: Corrupt Response' while being asked for its version.  This likely means that the server is older than the client.
; terminating

centos8 mux server log:
>cat /run/user/11331/wezterm/wezterm-log-3154698.txt
11:24:55.191  WARN   wezterm_client::client > While connecting to Socket("/run/user/11331/wezterm/sock"): connecting to /run/user/11331/wezterm/sock.  Will try spawning the server.
11:24:55.191  WARN   wezterm_client::client > Running: "/usr/bin/wezterm-mux-server" "--daemonize"

If you have any ideas on where to possibly clean up any files on Windows or Linux, or what other information you need or troubleshooting steps I could take, let me know.

### Configuration

Windows:

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
--config.color_scheme = 'AdventureTime'
--config.color_scheme = 'Panels (terminal.sexy)'
config.color_scheme = 'Pulp (terminal.sexy)'
config.font = wezterm.font('JetBrains Mono')
config.window_background_opacity = 0.975
config.font_size = 10
config.enable_scroll_bar = true
config.use_fancy_tab_bar = true
config.initial_cols = 120
config.initial_rows = 48
config.enable_scroll_bar = true

config.ssh_domains = {
  {
    -- This name identifies the domain
    name = 'dev1',
    -- The hostname or address to connect to. Will be used to match settings
    -- from your ssh config file
    remote_address = '#host#',
    -- The username to use on the remote host
    username = '#user#',
  },
}

-- and finally, return the configuration to wezterm
return config
```

Linux:

```lua
return {
    config.enable_scroll_bar=true
}

```

**Comment by wez** [comment]
Please include the configuration

**Comment by Capri205** [comment]
Hi. These are the wezterm.lua files for each (redacted user and host). I can ssh over fine using the .ssh/config entry for the Linux host.

Windows:
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
--config.color_scheme = 'AdventureTime'
--config.color_scheme = 'Panels (terminal.sexy)'
config.color_scheme = 'Pulp (terminal.sexy)'
config.font = wezterm.font('JetBrains Mono')
config.window_background_opacity = 0.975
config.font_size = 10
config.enable_scroll_bar = true
config.use_fancy_tab_bar = true
config.initial_cols = 120
config.initial_rows = 48
config.enable_scroll_bar = true

config.ssh_domains = {
  {
    -- This name identifies the domain
    name = 'dev1',
    -- The hostname or address to connect to. Will be used to match settings
    -- from your ssh config file
    remote_address = '***',
    -- The username to use on the remote host
    username = '***',
  },
}

-- and finally, return the configuration to wezterm
return config

Linux:

return {
    config.enable_scroll_bar=true
}
