### ISSUE TITLE
Support Character Variants (cvXX)

### ISSUE THREAD

**Issue by chtenb** [wez/wezterm#5381]
It seems that wezterm currently does not support character variants?
https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae#cv01-cv99

**Reproduction**
I tried to install the monaspace font and enable cv60. The normal stylistic sets work fine, but the character variants seem to do nothing.
See also https://github.com/githubnext/monaspace/issues/207

**Comment by gegoune** [comment]
It does, have a look at https://wezfurlong.org/wezterm/config/font-shaping.html.

**Comment by chtenb** [comment]
What am I overlooking? I don't see any mention of character variants on the page you linked.

**Comment by chtenb** [comment]
It doesn't work for me, but I installed another application to test, and that doesn't seem to work either. So the problem is likely not with wezterm. Closing until evidence suggests otherwise.
