### ISSUE TITLE
Path length limited to 59 characters

### ISSUE THREAD

**Issue by rorric** [wez/wezterm#5391]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Not sure if this is intended design but an error prompts: "Path to Calibre Portable ([Path here]) too long. It must be less than 59 characters" when I try to install Calibre portable via Scoop in Wezterm with a slighted deeper path. The installation cannot be finished.

Tried with combinations of Nushell/Powershell with Wezterm/WindowsTerminal. It looks like this error only prompts in wezterm.

### To Reproduce

Scoop install path set in a deeper path.

scoop install calibre in any shell (tried nushell or pwsh) in wezterm

### Configuration

no config

### Expected Behavior

No error. Successful installation

**Comment by wez** [comment]
The information here is vague and incomplete; there's no action I can take with this.

**Comment by burhan** [comment]
This is a [known issue](https://github.com/ScoopInstaller/Extras/issues/1765) and is not related to wezterm.
