### ISSUE TITLE
Unfocused Wezterm window content doesn't get drawn until "damage" occurs

### ISSUE THREAD

**Issue by cbirchinger** [wez/wezterm#5405]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Xfce4 4.18 / Xorg 21.1.13

### WezTerm version

20240509-223025-91a16e52

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When switching to a virtual desktop unfocused Wezterm windows don't get drawn until some sort of "damage" (mouse over, focusing, etc.) occurs.

![wezterm-unfocused](https://github.com/wez/wezterm/assets/4973300/4f098bb2-409e-43fb-bb33-32d7f33ae429)

This happens with or without an active compositor.
Default or front_end = "OpenGL" makes no difference either

### To Reproduce

Switch away and back to a virtual desktop that has unfocused Wezterm windows on it.

### Configuration

no config

Tested with:  WEZTERM_CONFIG_FILE=/dev/null wezterm

### Expected Behavior

Windows should get drawn as soon as they become visible

### Anything else?

Commit 0184e88 (29. April 2024) works fine. This issue started happening after that release.

**Comment by jknockel** [comment]
I'm guessing this is another regression from 809bcc55.  I can reproduce with xfwm4 4.18.0, so I will investigate further.
