### ISSUE TITLE
Can't copy anything from `gdb`

### ISSUE THREAD

**Issue by tgross35** [wez/wezterm#5409]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

MacOS

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

In the GDB TUI mode, it is not possible to select or copy anything in any of the boxes. I think this is similar to the microsoft terminal issue at https://github.com/microsoft/terminal/issues/14336.

### To Reproduce

Launch gdb and enter tui via e.g. `layout reg`. It will pull up a view similar to this:

<img width="859" alt="image" src="https://github.com/wez/wezterm/assets/13724985/efceb6a8-ea53-45f5-af16-8b48a8b08ffd">

And nothing will be selectable

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.keys = {
  {
    key = 'LeftArrow',
    mods = 'ALT',
    action = wezterm.action.SendKey {
      key = 'b',
      mods = 'ALT',
    },
  },
  {
    key = 'RightArrow',
    mods = 'ALT',
    action = wezterm.action.SendKey {
      key = 'f',
      mods = 'ALT',
    },
  }
}

config.window_padding = {
  left = 4,
  right = 4,
  top = 4,
  bottom = 4,
}

config.inactive_pane_hsb = {
  saturation = 1.0,
  brightness = 1.0,
}

config.initial_cols = 120
config.initial_rows = 30

config.native_macos_fullscreen_mode = true

return config
```

### Expected Behavior

Selections should work

**Comment by bew** [comment]
Try to select with Shift

**Comment by tgross35** [comment]
Never knew about that, thanks! Problem solved.
