### ISSUE TITLE
Alpha blending: needs to be done in linear space

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#544]
( version 20210314-114017-04b7cedd-5-g2ea09317 )

This is probably even a bug, but more an cosmetic one.

Looking at image output of transparent images, it looks like alpha blending with the background is done in the gamma-compressed space, not in linear space. So essentially it looks like it takes the average of the 8-bit values without first expanding them with x^2.4 or whatever gamma there is, then averaging and then re-gamma.

Let's look at the follwing PNG with a gradient
![gradient](https://user-images.githubusercontent.com/140937/111245144-66835f00-85c1-11eb-948e-454f1bbb5aa2.png)

If we take that and merge with a white background in gimp (which I refer the authority of how to deal with transparency to. I am not), it looks like this
![gimp-screenshot](https://user-images.githubusercontent.com/140937/111245232-8f0b5900-85c1-11eb-9e75-a760f909e2e6.png)

If we display the same thing with [`timg`](http://timg.sh) with `-bauto` mode, it takes the background color of the terminal and does local alpha blending (internally, it approximates the process with an exponent of 2, so R' = sqrt(R₁²+R₂²) for simplicity). Then send the resulting PNG to the terminal
![timg-alpha-blending](https://user-images.githubusercontent.com/140937/111245403-d265c780-85c1-11eb-94ce-aa57d28651e1.png)

If we we use `-tnone`, then timg sends the transparent image as-is to the terminal, which then does the merging of the colors locally, which then looks like this
![wezterm-alpha-blending](https://user-images.githubusercontent.com/140937/111245640-2ffa1400-85c2-11eb-9d7e-b2162414a7be.png)

It looks like that the `timg` alpha-blended form is a lot closer to the output of gimp than the transparent merging in the terminal.
(and funnily, in my Chrome-Browser the original image look like somewhere in the middle of these, though still closer to gimp).

So someone other than me who actually knows how to deal with color should probably be able to better comment on how things _should_ be done. There is also this classic https://www.youtube.com/watch?v=LKnqECcg6Gw

**Comment by d-miketa** [comment]
My issue [#716](https://github.com/wez/wezterm/issues/716) was fixed, possibly with https://github.com/wez/wezterm/commit/c10288bd25db5496b40378ba155e190c190fc237 – many thanks Wez! :) Others may find their related issues similarly resolved.

**Comment by wez** [comment]
This issue is still open; `-bauto` and `-bnone` still look pretty different.  What did get changed recently was #1000 and #653.
I was hoping to reconcile this alpha issue, but it's been driving me crazy trying to wrangle this with the `glium` crate across platforms.
I think the path forward is to look at `wgpu` which targets newer APIs where RGB vs SRGB isn't an after-thought.

**Comment by wez** [comment]
I think this is now resolved on all platforms; could you give it a try and let me know what you think?

**Comment by hzeller** [comment]
So `-tnone` is now transparent and shows the background of the terminal, is that a new feature ?
To compare, it would be best for the transparent parts just shine the background  color of the terminal; is that a setting I can do ?

**Comment by wez** [comment]
Hmm, on my mac `-bnone` makes the window transparent for the transparent regions in your png.   That's not the intent; it is actually layering the png over the terminal background color, but somehow when it renders the alpha seems to punch all the way through the window instead of just over that layer.  I might have to break the render into separate draw passes for that to work as intended.

**Comment by wez** [comment]
That aside: the blending is all now linear, so that's progress! :)

**Comment by hzeller** [comment]
Ok, so you see the same as I do on Linux, punching the transparent parts of the PNG through the terminal backing.
But yes, the rendering looks like it would be correct if the background is white.

**Comment by wez** [comment]
The weird punch-through alpha effect is no more, so I'm calling this done!
