### ISSUE TITLE
Startup failure on Windows

### ISSUE THREAD

**Issue by clin1234** [wez/wezterm#5448]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20240520-084532-da2d0ad2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Typing `wezterm` got the following error:
```
13:56:29.390  ERROR  wezterm > The system cannot find the file specified. (os error 2); terminating
```

Tried adding `--no-config`, didn't work either

### Configuration

no config

**Comment by wez** [comment]
Sounds like an incomplete installation, and/or broken PATH, but there's nowhere near enough information here to say more.
