### ISSUE TITLE
`Ctrl + Shift + Backspace`/`Ctrl + Shift + Delete` not working

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#545]
## Describe the bug
`Ctrl + Shift + Backspace`/`Ctrl + Shift + Delete` cannot be bound.

## Environment (please complete the following information):
 - OS: Linux X11
 - Version: wezterm 20210203-095643-70a364eb
 - The active keyboard layout name: ENG

## To Reproduce
Run `showkey -a` to look at the escape sequences. Press `Ctrl + Shift + Backspace`/`Ctrl + Shift + Delete`. Instead of the assigned key sequences, they show:

- `Ctrl + Shift + Backspace`: `^_       31 0037 0x1f`
- `Ctrl + Shift + Delete`: `^[[3;5~          27 0033 0x1b`

## Configuration
```
local wezterm = require 'wezterm';

return {
    keys = {
        {key='Backspace', mods='CTRL|SHIFT', action=wezterm.action{SendString='\x1b[\7f;6u'}},
        {key='Delete', mods='CTRL|SHIFT', action=wezterm.action{SendString='\x1b[3;6~'}},
    }
}
```

## Expected behavior
The specified escape sequence gets shown.

## Screenshots
N/A

## Session Recording
I think the above is enough info to reproduce the bug.

## Additional context
N/A.

**Comment by wez** [comment]
Ah, this is another variation on https://github.com/wez/wezterm/issues/516
I just pushed a fix!
