### ISSUE TITLE
Very slow when typing

### ISSUE THREAD

**Issue by octavz** [wez/wezterm#546]
Trying to use it in Windows 10, and I have for comparison Alacritty and Windows Terminal. 

WezTerm seems to be fast enough when rendering and everything seems fine overall, a lot of features which makes it a very interesting choice on Windows and not only, given it's documentation, Lua configuration and a lot of other things.

However when I am typing there is quite a delay compared with others which makes it feel sluggish.

I don't have steps to reproduce, can't say if it is the same on other OSes, just typing everywhere seems to be delayed, tried it with different front_end, is the same, though I could see rendering being faster with OpenGL compared to Software.
 
Is there a settings that could affect the delay between key up and showing the character on the screen?

Thank you

**Comment by mborejdo** [comment]
I am also on windows and also really love wezterms featureset and capabilites. Definitely (one of) the best terminal emulators on windows. Considering your problem, I cannot reproduce this on windows 10. I once experienced this problem, running some scripts in the "update-right-status" event-handler, which spawned a lot of processes and also had this very sluggish typing feeling. Fixing that, solved the problem

**Comment by wez** [comment]
Could you provide more details that will help reproduce this?  For keyboard related things, the following information can be helpful:

* The keymap/language you have active
* Your key repeat rate
* Which key(s) you notice as slow
* Whether you have any other programs installed that might change how keyboard input is processed (eg: autohotkey?)

You mentioned a delay after key up; wezterm generates key events when the key is pressed rather than released, so I wonder if this might be latency with repaint/invalidation rather than input recognition.

Something else you may wish to try is changing https://wezfurlong.org/wezterm/config/lua/config/prefer_egl.html to false to see if that makes a difference.

**Comment by alexherbo2** [comment]
I also feel like the typing is slow, running on [NixOS] with [Sway].

[NixOS]: https://nixos.org
[Sway]: https://swaywm.org

- Keyboard layout: QWERTY (US)

**Comment by wez** [comment]
> The typing feels slow, but not very slow; just enough for me to notice. On the [Kakoune Discord](https://discord.com/invite/uzZZG2X), we had others complaining about the slowness.

@alexherbo2 I tried to find those mentions on discord, but didn't find any matches when searching for wezterm

**Comment by octavz** [comment]
- I am on English-Colemak, 
- repeat rate is the maximum in Win10, both slides are at the end
- typing in general is slow not specific keys
- yes I am using Autohotkey, but I disabled it and nothing changed
- `prefer_egl` didn't change anything about typing, it changed my colors

Also I am comparing same setup with Alacritty and Windows Terminal, Alacritty is very fast with everything, Windows Terminal is so so, Wezterm unfortunately is the slowest of these. 
Using it with Neovim with heavy colored files and scrolling back and forth also causing "screen tearing", is not always smooth

You can close this, I don't consider this a bug, but for me the speed is a game changer, since I use terminal to edit text faster :) otherwise would just use some desktop app.

Thank you

**Comment by wez** [comment]
@octavz would you mind trying the prior release and see if it feels better?

**Comment by octavz** [comment]
I tried it, unfortunately is not better. Like I said might be something local here, is just strange that the rest are faster.

**Comment by octavz** [comment]
Also I recorded, to see the difference for rendering on my computer, on the right is windows terminal:

Hope you can see it:


https://user-images.githubusercontent.com/23629302/111585772-791bb500-87c8-11eb-86bc-f95603aeb148.mp4

**Comment by wez** [comment]
Please give the latest nightly build a try when you have a few moments!

**Comment by octavz** [comment]
I downloaded from the site "Nightly Build" but it appears is a 14 march commit, where exactly do I get the nightly build from? Thanks.

**Comment by wez** [comment]
The "Nightly" download buttons are what you want: https://wezfurlong.org/wezterm/install/windows.html
The version number reported by wezterm comes from `git describe --tags` and references the last release tag, along with the number of commits since that tag, and the git hash.

**Comment by octavz** [comment]
btw, checking my resource usage I observed that same setup, same file, same coloring, same everything, scrolling in vim with weztem eats a core 100% by comparison scrolling in Windows Terminal is negligible, might be related ?

**Comment by azarashi2931** [comment]
When using WezTerm on Windows 10, I too find the typing to be slower than with Alacritty or Windows Terminal.
+ keymap: jp106/language: Japanese
+ repeat rate: maximum
+ Which keys: all
+ other programs: no

**Comment by wez** [comment]
@azarashi2931 please also share `wezterm --version`

**Comment by azarashi2931** [comment]
`wezterm --version` outputs:
```
wezterm 20210314-114017-04b7cedd-141-gd7b78b41
```

**Comment by wez** [comment]
I've had a couple of users report slowness in vim when using airline.  We traced this down to fallback font resolution and a number of improvements have been made in that area recently.

Please try the latest nightly build when you have a few moments and let me know how things feel!

**Comment by octavz** [comment]
Hey,

Just tried it for a few mins and it seems indeed better, will get back to you next week after I will spend some time with it.

Thanks

**Comment by azarashi2931** [comment]
I just updated and tried it, and it seems to have solved this problem in my environment!
Thanks!
`wezterm --version` outputs:
```cmd
wezterm 20210501-232335-6a1d14b2
```

**Comment by carlosonrails** [comment]
Don't know how the improvements are, but updating:
The slow typing is happening yet with Neovim with Lualine installed. 
Made the same attempts with same files with vim and neovim without lualine and the typing was smoooth

**Comment by egolep** [comment]
I got the same problem with any colorscheme I use. If I don't use a colorscheme everything is smooth, independently from any other plugin and setup

**Comment by wez** [comment]
Please file a new separate issue of your own if you are experiencing problems!
