### ISSUE TITLE
arch aur terminfo conflict

### ISSUE THREAD

**Issue by conree** [wez/wezterm#5464]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Version
=======
KWin version: 6.0.4
Qt Version: 6.7.0
Qt compile version: 6.7.0
XCB compile version: 1.17.0

Operation Mode: Xwayland

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

error: failed to commit transaction (conflicting files)
ncurses: /usr/share/terminfo/w/wezterm exists in filesystem (owned by wezterm-terminfo)
Errors occurred, no packages were upgraded.

### To Reproduce

sudo pacman -Syu

### Configuration

local wezterm = require('wezterm')
local config = {}
        term = "wezterm"
        config.color_scheme = 'Blueberry Banana'
        config.window_background_opacity = 0.7
        config.font = wezterm.font 'Comic Code'
        config.font_size = 12.0
        config.enable_scroll_bar = true
        config.check_for_updates = true
        config.check_for_updates_interval_seconds = 86400
return config

### Expected Behavior

Full system update with no errors.

### Logs

17:39:21.988  ERROR  config::config > Your configuration specifies color_scheme="Blueberry Banana" but that scheme was not found
17:39:21.993  INFO   wezterm_gui    > Spawned your command via the existing GUI instance. Use wezterm start --always-new-process if you do not want this behavior. Result=SpawnResponse { tab_id: 1, pane_id: 1, window_id: 1, size: TerminalSize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384, dpi: 0 } }

### Anything else?
If I delete wezterm and restart, I can update my system with pacman -Syu. Then if I try to reinstall wezterm I get:
➤ paru -S wezterm
[sudo] password for si:
resolving dependencies...
looking for conflicting packages...

Package (5)                                 New Version                   Net Change

extra/ttf-jetbrains-mono                    2.304-1                         7.44 MiB
extra/ttf-roboto                            2.138-4                         5.16 MiB
cachyos-extra-v3/wezterm-shell-integration  20240203.110809.5046fc22-1.1    0.02 MiB
cachyos-extra-v3/wezterm-terminfo           20240203.110809.5046fc22-1.1    0.00 MiB
cachyos-extra-v3/wezterm                    20240203.110809.5046fc22-1.1  110.32 MiB

Total Installed Size:  122.94 MiB

:: Proceed with installation? [Y/n] y
(5/5) checking keys in keyring                         [----------------------------] 100%
(5/5) checking package integrity                       [----------------------------] 100%
(5/5) loading package files                            [----------------------------] 100%
(5/5) checking for file conflicts                      [----------------------------] 100%
error: failed to commit transaction (conflicting files)
wezterm-terminfo: /usr/share/terminfo/w/wezterm exists in filesystem (owned by ncurses)
Errors occurred, no packages were upgraded.

_No response_

**Comment by Dacheng-Wang** [comment]
Same issue. I believe this is related:
https://gitlab.archlinux.org/archlinux/packaging/packages/wezterm/-/issues/2

**Comment by fioncat** [comment]
Same, is seems that ncurses provided terminfo file in the new release?

**Comment by 1nikolas** [comment]
The issue was [fixed](https://gitlab.archlinux.org/archlinux/packaging/packages/wezterm/-/merge_requests/1) for the wezterm package in arch but there is still an issue in the [aur git package](https://aur.archlinux.org/packages/wezterm-git) which seems to be maintained by @wez

**Comment by Dacheng-Wang** [comment]
For anyone looking for a temporary solution: If you have wezterm installed already, go ahead and delete /usr/share/terminfo/w/wezterm (with sudo), and then update ncurses.

**Comment by BigJayToDaIzo** [comment]
> The issue was [fixed](https://gitlab.archlinux.org/archlinux/packaging/packages/wezterm/-/merge_requests/1) for the wezterm package in arch but there is still an issue in the [aur git package](https://aur.archlinux.org/packages/wezterm-git) which seems to be maintained by @wez

Have their been any updates to this?  I've tried to install `wezterm-git` monthly since May and continue to be rejected by this AUR package issue.  Would really love to use wezterm instead of foot or kitty but the non-git package refuses to load and of course somehow registers as a dependency of ncurses.

**Comment by wez** [comment]
I'll accept a patch for this. I don't use arch. I do find it irritating that there doesn't seem be a way to handle PRs for this sort of package in arch, because right now I am the bottleneck and there is no good submission process as far as I'm aware.

**Comment by BigJayToDaIzo** [comment]
> I'll accept a patch for this. I don't use arch. I do find it irritating that there doesn't seem be a way to handle PRs for this sort of package in arch, because right now I am the bottleneck and there is no good submission process as far as I'm aware.

Thanks for the update.  I know the AUR is a rocky place for those who don't specifically use it, (and many of us who do).  I'll dip my proverbial toes into trying to be a good arch user and see if I can bridge this gap for us in the coming days.  Again thank you for the update.  I SO enjoy using it on Nix, and this is  the reason I want it so badly on arch (daily driver) too now that nvidia is largely behaving over here.  Thanks for the ultra awesome term emulator!  I'm not exaggerating when I say I've played with nearly ALL of them and when wezterm first lit up on my screen it was dazzling.  I was literally entranced by how clean and fast it was.

**Comment by vandalt** [comment]
Hi @wez,

For me it seems that removing the two lines that setup/create terminfo fixed installation (I did have to force a rebuild with `--rebuild` when using paru for this to work.

Here is a patch (I'm not sure I did this correctly, I'm not used to creating patches this way):

```
diff --git a/PKGBUILD b/PKGBUILD_FIX
index bb63443..71d32fa 100644
--- a/PKGBUILD
+++ b/PKGBUILD_FIX
@@ -52,7 +52,6 @@ build() {
   cd "$srcdir/wezterm" || exit 1
   bash ci/check-rust-version.sh
   cargo build --frozen --release
-  tic -x -o "$srcdir/terminfo" "$srcdir/wezterm/termwiz/data/wezterm.terminfo"
 }
 
 package() {
@@ -67,7 +66,6 @@ package() {
   install -Dm644 assets/wezterm.desktop "$pkgdir/usr/share/applications/org.wezfurlong.wezterm.desktop"
   install -Dm644 assets/wezterm.appdata.xml "$pkgdir/usr/share/metainfo/org.wezfurlong.wezterm.appdata.xml"
   install -Dm644 assets/wezterm-nautilus.py "$pkgdir/usr/share/nautilus-python/extensions/wezterm-nautilus.py"
-  install -Dm644 ../terminfo/w/wezterm "$pkgdir/usr/share/terminfo/w/wezterm"
 
   install -Dm644 assets/shell-integration/wezterm.sh "$pkgdir/etc/profile.d/wezterm.sh"
   install -Dm644 assets/shell-completion/bash "$pkgdir/usr/share/bash-completion/completions/wezterm"
                                                                                                                                                                
~
```

**Comment by wez** [comment]
I think this has now been resolved, please try and let me know

**Comment by winter-again** [comment]
New pkgbuild works for me.
