### ISSUE TITLE
`wezterm-nightly` was renamed to `wezterm@nightly`

### ISSUE THREAD

**Issue by RoyRao2333** [wez/wezterm#5466]
**What page or section of the docs have an issue?**

https://wezfurlong.org/wezterm/install/macos.html#homebrew

**Describe the issue**

I was using `wezterm-nightly --greedy-latest` to upgrade my WezTerm all along. But I'm getting this warning now:

<img width="601" alt="image" src="https://github.com/wez/wezterm/assets/31413093/9311765d-ecb0-4b52-bfda-8a9a15aebaa2">

So should I use `wezterm@nightly` instead of `wezterm-nightly`? If do, is `--greedy-latest` flag still needed? Thanks.

**Comment by wez** [comment]
I'm not sure; I don't run wezterm in that configuration, so I need feedback from folks that do to suggest how the docs should get updated.

**Comment by RoyRao2333** [comment]
@wez 

Thanks for the reply!

`wezterm@nightly` works fine in HomeBrew, so maybe it's a good idea updating the doc in case someone else is wondering this issue.

**Comment by wez** [comment]
Would love a PR that took care of this and the related #5805 together at the same time
