### ISSUE TITLE
get_current_working_dir returns nil when sourcing wezterm.sh at the end of .zshrc

### ISSUE THREAD

**Issue by marchyman** [wez/wezterm#5490]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240520-135708-b8f94c47

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using zsh AND sourcing wezterm.sh the function get_current_working_dir(), called from wezterm_on("update-status") runs 5 times after the last keystroke.  The last time it runs it returns nil.

That behavior does not occur before sourcing wezterm.sh.

### To Reproduce

Open a new window with the above test config using `wezterm --config-file ~/.config/wezterm/test.lua start &`
.zshrc should NOT source wezterm.sh (which I renamed .wezterm.sh)
The status bar is correct.

![Screenshot 2024-05-28 at 11 54 43 AM](https://github.com/wez/wezterm/assets/784627/4c285a54-b3ba-4b82-9eb2-a20f1d18b188)

At the prompt enter `source .wezterm.sh` and hit return.  The status bar is no longer correct.

![Screenshot 2024-05-28 at 11 55 17 AM](https://github.com/wez/wezterm/assets/784627/321af2d6-5e33-4931-b524-3985b0bfc3e5)

The log output shows that "update-status" is triggered every keystroke.  I didn't expect that.  On the last keystroke (the <return> key I see this:

```
12:46:12.594  INFO   logging > lua: marc
12:46:12.600  INFO   logging > lua: marc
12:46:12.604  INFO   logging > lua: marc
12:46:12.610  INFO   logging > lua: marc
12:46:12.618  INFO   logging > lua:
```

The request for cwd occurs 5 times, the last time returning nothing.  Before .wezterm.sh was sourced multiple invocations of update-status did not occur when the return key is hit.

### Configuration

```lua
local wezterm = require("wezterm")

local config = {}
-- Use config builder object if possible
if wezterm.config_builder then config = wezterm.config_builder() end

config.initial_cols = 60
config.initial_rows = 20

config.use_fancy_tab_bar = false
config.status_update_interval = 10000 -- long update period
config.tab_bar_at_bottom = false
wezterm.on("update-status", function(window, pane)

  local basename = function(s)
    -- Nothing a little regex can't fix
    return string.gsub(s, "(.*[/\\])(.*)", "%2")
  end

  local cwd = pane:get_current_working_dir()
  cwd = cwd and basename(cwd.file_path) or ""
  wezterm.log_info(cwd)
  local cmd = pane:get_foreground_process_name()
  cmd = cmd and basename(cmd) or ""

  window:set_right_status(wezterm.format({
    { Text = wezterm.nerdfonts.md_folder .. "  " .. cwd },
    { Text = " | " },
    { Foreground = { Color = "#e0af68" } },
    { Text = wezterm.nerdfonts.fa_code .. "  " .. cmd .. " " },
    "ResetAttributes",
  }))

end)

return config
```

### Expected Behavior

wezterm should return the cwd when possible.

**Comment by gmdevz** [comment]
having the same problem here as well. I'm using windows 11

**Comment by marchyman** [comment]
Workaround discovered.  Comment out the lines in wezterm.sh that call `wezterm set-working-directory`.  After making the function `__wezterm_osc7()` look like this:

```bash
__wezterm_osc7() {
  # if hash wezterm 2>/dev/null ; then
  #   wezterm set-working-directory 2>/dev/null && return 0
  #   # If the command failed (perhaps the installed wezterm
  #   # is too old?) then fall back to the simple version below.
  # fi
  printf "\033]7;file://%s%s\033\\" "${HOSTNAME}" "${PWD}"
}
```

The cwd is set as expected.

**Comment by gmdevz** [comment]
do I have to build wezterm from source to make this change?

**Comment by marchyman** [comment]
That is in the optional file named `wezterm.sh` that I copied to my home directory and sourced at the bottom of my .zshrc file.   I do not know windows and have no clue if it uses anything similar.

**Comment by gmdevz** [comment]
I don't have that `wezterm.sh` on my windows machine. Hope they get to fix it for windows as well.

**Comment by wez** [comment]
There's no bug in wezterm here, the problem is with your regex.
If you move your logging statement up ahead of calling basename you'll see that it is returning a [URL object](https://wezfurlong.org/wezterm/config/lua/wezterm.url/Url.html).

**Comment by marchyman** [comment]
Yes.   It is returning a URL object.  And I'm running the regex over the "file_path" of the returned URL object.  Is that not something that should match the regex?
