### ISSUE TITLE
There is empty space at the bottom when increase line height

### ISSUE THREAD

**Issue by anaetrezve** [wez/wezterm#5493]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I increase the line height there is always a space at the bottom. 

<img width="1680" alt="image" src="https://github.com/wez/wezterm/assets/25753490/3f16146d-2b37-4144-8f05-99a262b6e3ae">

### Configuration

```lua
local wezterm = require("wezterm")

return {
	color_scheme = "Catppuccin Mocha",

	font = wezterm.font({
		family = "JetBrains Mono",
	}),

	font_size = 16,
	enable_tab_bar = false,
	line_height = 1.5,
	window_decorations = "RESIZE",
	native_macos_fullscreen_mode = true,
	window_padding = {
		bottom = 0,
		top = 0,
		left = 0,
		right = 0,
	},
	keys = {
		{
			key = "m",
			mods = "CTRL",
			action = wezterm.action.ToggleFullScreen,
		},
	},
}

```

### Expected Behavior

There should not be any space at the bottom

**Comment by tk-chaos** [comment]
https://github.com/wez/wezterm/issues/5488#issuecomment-2153651734

**Comment by wez** [comment]
Try setting https://wezfurlong.org/wezterm/config/lua/config/use_resize_increments.html

But note that if you are full screen/maximized, then wezterm has to fill in any unusable space (that isn't a precise multiple of your configured terminal font cell size) with something, which can result in padding like this.
