### ISSUE TITLE
`wezterm.home_dir` doesn't adapt to sshmux domains

### ISSUE THREAD

**Issue by simonmandlik** [wez/wezterm#5497]
I'm using `wezterm.home_dir` to modify tab titles. My home dir is different on my MacOS machine and Linux server. But `wezterm.home_dir` always returns home dir on my machine even when I'm muxing into the Linux server.

I don't know which settings are exactly shared with remote client when sshmuxing. But I noticed that `wezterm.gui` is `nil` when connecting, which led me into believing that `wezterm.home_dir` may give correct answer as well.

**Comment by wez** [comment]
`wezterm.home_dir` returns the home directory on the machine where the wezterm GUI process is running.
There is not a terminal/pane primitive that conveys the home directory for a pane.
I would suggest that you look into using User Vars to pass this back; see https://wezfurlong.org/wezterm/recipes/passing-data.html
