### ISSUE TITLE
`CaseInSensitiveString` is not a valid Pattern variant

### ISSUE THREAD

**Issue by matiasgarciaisaia** [wez/wezterm#5519]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm new to wezterm, and trying to make the window search function (`CMD+F` in macOS) be case-insensitive by default.

I was able to change the `CMD+K` mapping to clear the scrollback AND viewport, but I get this weird error message when changing this other action:

```
`CaseInSensitiveString` is not a valid Pattern variant. Did you mean one
of `CaseInSensitiveString`, `CaseSensitiveString`? Other alternatives are
`CurrentSelectionOrEmptyString`, `Regex`
stack traceback:
        [C]: in field 'Search'
        [string "/Users/mgarcia/.wezterm.lua"]:15: in main chunk
```

Weirdest part is that it suggests me to use the same setting that I'm trying to set. Also tried `CaseSensitiveString` with the same results.

### To Reproduce

Just launch wezterm with the custom `~/.wezterm.lua` file, and two wezterm windows will open - one with a new bash session, another with the quoted error.
![Screenshot 2024-06-05 at 6 37 11 PM](https://github.com/wez/wezterm/assets/5470539/47113e29-928f-4fe7-ae49-942c73b7b79b)

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This will hold the configuration.
local config = wezterm.config_builder()
local act = wezterm.action

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
-- config.color_scheme = 'AdventureTime'
--
config.keys = {
	{ key = "k", mods = "CMD", action = act.ClearScrollback("ScrollbackAndViewport") },
	{ key = "f", mods = "CMD", action = act.Search("CaseInSensitiveString") }
}

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

I'd expect my search to become case-insensitive.

**Comment by kenchou** [comment]
https://wezfurlong.org/wezterm/config/lua/keyassignment/Search.html

You can use the following 4 forms of configuration：

- act.Search { Regex = "" }
- act.Search { CaseInSensitiveString = "" }
- act.Search { CaseSensitiveString = "" }
- **act.Search("CurrentSelectionOrEmptyString")**

**Comment by matiasgarciaisaia** [comment]
Thanks!

I've changed the config to this, and it worked:

```lua
config.keys = {
	{ key = "k", mods = "CMD", action = act.ClearScrollback("ScrollbackAndViewport") },
	{ key = "f", mods = "CMD", action = act.Search({ CaseInSensitiveString = "" }) },
}
```
