### ISSUE TITLE
Window Opacity showing solid color instead of transparency.

### ISSUE THREAD

**Issue by Ktufuathama** [wez/wezterm#553]
## Describe the bug

When setting the configuration "window_background_opacity" to anything other than 1.0, it shifts to a different solid color instead of becoming more transparent.

## Environment:

 - OS: Window Version 2004 (OS Build 19041.867)
 - Version: wezterm 20210314-114017-04b7cedd
 - Keyboard Layout: ENG

## To Reproduce

Change the opacity in the ".\wezterm.lua" configuration settings to any float below 1.0.

## Configuration

...
color_scheme = "Hardcore",
window_background_opacity = 0.8,
...

## Expected behavior

The expected behavior is the window should decrease the opacity (become more transparent) as the configuration is set lower.

### Opacity Set To 1.0
![OpacitySetTo_1 0](https://user-images.githubusercontent.com/31010254/111728096-c2ecb580-8831-11eb-8fd0-e5ff576361ad.png)
### Opacity Set To 0.8
![OpacitySetTo_0 8](https://user-images.githubusercontent.com/31010254/111728095-c2541f00-8831-11eb-995b-32575bd52bcb.png)

**Comment by wez** [comment]
@mborejdo mentioned that he was also seeing something like this. I wonder if this might be related in part to https://github.com/wez/wezterm/issues/544 and potentially https://github.com/wez/wezterm/commit/09081d21898568df66e74189c144d88bf1778612 changing part of the render process.

**Comment by SuperSandro2000** [comment]
I can confirm that this issue is fixed on nightly! thanks ❤️
