### ISSUE TITLE
Improve matching of CharSelect

### ISSUE THREAD

**Issue by al1-ce** [wez/wezterm#5532]
**Is your feature request related to a problem? Please describe.**
When I'm trying to get unicode characters it's extremely frustrating that results are completely unrelated to search. Example:

![image](https://github.com/wez/wezterm/assets/60989682/75645d58-3eb1-4649-b284-a26b7f8732f1)

On top is `kitten unicode-input`, on bottom wezterm's CharSelect. Top results are fairly close to what I need (and to be honest look way better), bottom are absolutely not what I want to find

**Describe the solution you'd like**
Fuzzy search instead of what it's right now

**Describe alternatives you've considered**
Using kitty's char select which doesn't work with wezterm, i.e can't select characters or backspace to delete typed term

**Comment by wez** [comment]
FWIW, the results you are seeing right now *are* fuzzy matches, produced by https://crates.io/crates/fuzzy-matcher
It just so happens that `line` is fuzzy matching closer to `linux` than `low line` with its algorithm.

**Comment by al1-ce** [comment]
Strange, it should matching line related things first instead of linux then...

Maybe it's worth implementing something like https://dlang.org/library/std/numeric/gap_weighted_similarity_normalized.html ? In my experience it does very good matching.

**Comment by bew** [comment]
Maybe we could replace the use of the fuzzy-matcher crate with [nucleo](https://github.com/helix-editor/nucleo), which is both much faster and uses the same scoring system as fzf 🤔

**Comment by al1-ce** [comment]
Imo nucleo looks good and if they're right about similar matching to fzf it'd certainly be better choice

**Comment by wez** [comment]
FWIW, I did a quick test with the nucleo-matcher and I'm not convinced this is what you want either:

![image](https://github.com/user-attachments/assets/16d61465-fa80-44e9-a48a-8101f1babbf6)

**Comment by al1-ce** [comment]
Tbh looks better then before

What if to trick it by adding spaces before and after input string? Should probably trick matcher..?

I would've tested some things myself (namely trying to implement gap weight similarity algorithm), but I'm very unfamiliar with rust and didn't really liked it when I tried

**Comment by wez** [comment]
I've switched this to nucleo in `main`. I have low interest in trying to actively game the algorithm. I think that matching `linear...` before `low line` is totally reasonable in this situation.

Note that once you select `low line` once, it will appear in the recent list making it quicker to reuse again.

**Comment by al1-ce** [comment]
That is fair, it's way better then it was before and personally I'm ok with that, so, close when ready
