### ISSUE TITLE
Control+K Shortcut for Katakana Conversion Not Working on WezTerm

### ISSUE THREAD

**Issue by doraemonk775** [wez/wezterm#5533]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I am experiencing an issue with the Control+K shortcut for Katakana conversion when using Kotoeri (Japanese IME) in WezTerm. This shortcut is supposed to convert Hiragana text to Katakana, but it does not seem to work in WezTerm.

### To Reproduce

1. Open WezTerm on macOS.
2. Set the input source to Kotoeri (Japanese IME).
3. Type some Hiragana text.
4. Press Control+K to convert the text to Katakana.

### Configuration

```lua
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.color_scheme = 'carbonfox'
config.disable_default_key_bindings = true
config.font = wezterm.font('UDEV Gothic NFLG', { weight = 'Bold' })
config.font_size = 12
config.hide_tab_bar_if_only_one_tab = true
config.initial_cols = 160
config.initial_rows = 48
config.macos_forward_to_ime_modifier_mask = 'SHIFT|CTRL'
config.tab_bar_at_bottom = true
config.use_ime = true
config.window_background_opacity = 0.8

return config
```

### Expected Behavior
The selected Hiragana text should be converted to Katakana.

### Actual Behavior
The Control+K shortcut does not perform the conversion, and the Hiragana text remains unchanged.

### Anything else?

- The Control+K shortcut works correctly in other applications such as Terminal and iTerm2.
- I have tried adding the following configuration to `wezterm.lua` but it did not resolve the issue:
  ```lua
  local wezterm = require 'wezterm';

  local config = {}

  config.keys = {
    {key="K", mods="CTRL", action=wezterm.action.SendKey{key="k", mods="CTRL"}},
  }

  return config

**Comment by akthe-at** [comment]
Doesn't your second "k" need to be an upper case k as well? right now wezterm would be sending a ctrl+k when you hit ctrl+K instead of sending ctrl+K...

**Comment by mikuta0407** [comment]
I am having the same problem.
By adding the following settings to Karabiner-elements, I can use Ctrl+K to convert katakana, but it does not work like iTerm2 or standard terminal apps. (In iTerm2 and standard terminal apps, Ctrl+K is purely sent to the terminal when there is no input even if the IME is on, but with the following settings, Ctrl+K always replaces F7 when the IME is on)

If WezTerm is used on Windows (Google IME/MS IME) or Linux (fcitx-mozc) with key bindings set to Ctrl+K to katakana, the user's expected behavior (the same behavior as iTerm2 or standard terminal apps) will occur, so this This problem is only for the macOS version.
I would appreciate it if you could improve this, as the behavior in the macOS version appears to be that WezTerm has absorbed all the key bindings that the IME requires.

```json
{
    "description": "Ctrl-k to Katakana on Wezterm",
    "manipulators": [
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "^com\\.github\\.wez\\.wezterm"
                    ],
                    "type": "frontmost_application_if"
                },
                {
                    "input_sources": [
                        {
                            "language": "ja"
                        }
                    ],
                    "type": "input_source_if"
                }
            ],
            "from": {
                "key_code": "k",
                "modifiers": {
                    "mandatory": [
                        "control"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "f7"
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by doraemonk775** [comment]
@mikuta0407
Thank you for your suggestion.
I followed the instructions you provided and it worked as expected behavior!

**Comment by doraemonk775** [comment]
@mikuta0407
Thank you for your suggestion.
I followed the instructions you provided and it worked as expected behavior!

**Comment by mikuta0407** [comment]
@wez 
The issue on GitHub has been closed, but it would be great if the WezTerm side could address the issues related to key bindings and IMEs using the Ctrl key fundamentally in the future. (It works fine on Windows and Linux, and I would like to use it comfortably on macOS as well.)

(I have recently tried several multi-platform terminal apps, and I consider WezTerm to be the easiest to use as long as there are no problems with conflicts with IMEs, so I look forward to one day being able to use it comfortably.)
