### ISSUE TITLE
default local_echo_threshold_ms 100 not set for default_ssh_domains() ?

### ISSUE THREAD

**Issue by sedlund** [wez/wezterm#5547]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The default for manually added `ssh_domains` sets `local_echo_threshold_ms = 100`  which leads to a nice experience on distant remotes.

although if I have a `~/.ssh/config` and let `default_ssh_domains()` generate the struct for me, it does not set `local_echo_threshold_ms` . 

Not sure if this is intended, as the experience isn't as nice.

I am using:

```lua
config.ssh_domains = wezterm.default_ssh_domains()
for _, dom in ipairs(config.ssh_domains) do
  dom.assume_shell = 'Posix'
  dom.local_echo_threshold_ms = 10
end
```

To add it without having to manually recreate my `~/.ssh/config` in the `wezterm.lua`

### Configuration

above

**Comment by wez** [comment]
Thanks for the report; this is now fixed in `main`!
