### ISSUE TITLE
env_logger

### ISSUE THREAD

**Issue by conree** [wez/wezterm#5550]
➤ cargo build --release
error: failed to select a version for `env_logger`.
    ... required by package `wezterm-bidi v0.2.3 (/home/si/wezterm/bidi)`
versions that meet the requirements `^0.11` (locked to 0.11.3) are: 0.11.3

the package `wezterm-bidi` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

failed to select a version for `env_logger` which could resolve this conflict

**Comment by wez** [comment]
Sounds like you're trying to build wezterm in a weird/unsupported way, but haven't provided enough information. The CI is running just fine, as is building locally here.
