### ISSUE TITLE
wezterm-gui uses 100% CPU

### ISSUE THREAD

**Issue by wilriker** [wez/wezterm#557]
## Describe the bug

`wezterm-gui` uses up 100% CPU (i.e. one CPU core) while being idle. Therefore it is very laggy accepting input as well as rendering output. Basically it's unusable this way.

## Environment (please complete the following information):

 - OS: ArchLinux X11 (using AUR `wezterm-bin` package)
 - Version: wezterm 20210314-114017-04b7cedd
 - The active keyboard layout name: GB

## To Reproduce

I just need to launch `wezterm`.

## Configuration

I don't have a `wezterm.lua` configuration file.

## Expected behavior
Being a usable terminal. ;-)

**Comment by wez** [comment]
I haven't seen behavior like this before.  What are you running inside the terminal?

Please run: `WEZTERM_LOG=trace wezterm 2> /tmp/log.txt` and let it run for ~30 seconds or so, then attach that log file to this issue.  That should show us roughly what is happening inside.

**Comment by wilriker** [comment]
It simply spawns an instance of `fish` and then does nothing.
[log.txt](https://github.com/wez/wezterm/files/6172059/log.txt)

**Comment by wez** [comment]
It appears as though there is a continual stream of events from your window manager about changing the selection and resizing, even though nothing is changing.  Which window manager are you using?

**Comment by wilriker** [comment]
I use [herbstluftwm](https://herbstluftwm.org) a tiling window-manager.

**Comment by wez** [comment]
Please give https://aur.archlinux.org/packages/wezterm-git/ a try when you have a few moments to see if the commit I just pushed helps!

**Comment by wilriker** [comment]
That seems to have fixed it! Thanks for the quick solution. Now I can continue evaluating wezterm. :+1:

**Comment by wilriker** [comment]
Maybe one last question: is there a way to generate a `wezterm.lua` to start from for customization?

**Comment by wez** [comment]
We have  https://github.com/wez/wezterm/issues/548 open to add some example-driven configs to the docs.  I don't think it is necessarily a great idea to have a big config with every possible thing in it, because it would be difficult to consume and difficult to maintain.  Having a base config with the most likely changed options in it feels reasonable though.
