### ISSUE TITLE
Title won't change with cd after setting it with set-tab-title

### ISSUE THREAD

**Issue by mfirhas** [wez/wezterm#5583]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Im not sure if it's actually a bug, or expected. 

When I set tab's title with `set-tab-title`, and then cd to somewhere else, the title won't change. 

### To Reproduce

- Set title with `wezterm cli set-tab-title anything`
- cd (another-path)

### Configuration

no config

### Expected Behavior

I expect the default behavior where it gives at least last 13 chars of title.

**Comment by TomByte** [comment]
I think this is intended behaviour. Same as how other terminal emulators do it.

**Comment by wez** [comment]
This is the intended behavior. You need to pick either setting the title manually or using escape sequences. If you have more complex logic than this, you can use the various title related events to format and display what you need.
