### ISSUE TITLE
CTRL-J on macOS

### ISSUE THREAD

**Issue by fanzeyi** [wez/wezterm#56]
Current Behavior: Pressing `<CTRL-V><CTRL-J>`, WezTerm will send `^M` to the terminal.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/409951/67814296-ec504a00-fa60-11e9-8fa1-9c3dc27d57cd.png">

Expected Behaivor: Pressing `<CTRL-V><CTRL-J>`, WezTerm should send `\n` to the terminal.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/409951/67814305-f07c6780-fa60-11e9-8dd3-f8054f941ce4.png">

**Comment by wez** [comment]
I fixed this and added basic support for IME on the `macime` branch; I'm going to run with that locally for a bit before I merge to master, but I don't really use the IME for anything real so I don't know how well it works for stuff beyond emoji :)
