### ISSUE TITLE
Documentation needed: Unclear how to specify XLFD font name

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#560]
The description how to name choose fonts

https://wezfurlong.org/wezterm/config/fonts.html

Leaves out how to rephrase the names of fonts in XLFD format. When I provide a fully qualified bitmap font name:

```lua
return {
   font_dirs = { "/usr/share/fonts/X11/misc" },
   font = wezterm.font("-misc-fixed-medium-r-normal--18-120-100-100-c-90-iso10646-1"),
}
```

Then wezterm complains that it can't load the font. Even when using a short name from the `fonts.alias` it will not pick it up. Is there a way to reformulate that so that the rasterizer knows how to find that font ?

**Additional context**
Blurry antialiased fonts are not kind to my presbyopic eyes, this is why I prefer to start at least with a crisp bitmap font before they are then spatially blurred by my vision system :)

**Comment by wez** [comment]
wezterm doesn't use X to resolve fonts; the system font locator on unix systems is font-config.

wezterm only supports truetype and opentype file formats, so when it reads font_dirs directly, it can only see those font types.

You may want to try the http://terminus-font.sourceforge.net/ font if you want truetype font with pre-rendered bitmap strikes.
Debian packages that font as `fonts-terminus` and the TTF font name is simply `Terminus`

**Comment by wez** [comment]
You may also wish to try setting `freetype_load_target = "Mono"` to disable anti-aliasing.

**Comment by hzeller** [comment]
I see, alright, will try the Terminus font.
I guess this is the kind of information that would be nice to have in the [documentation](https://wezfurlong.org/wezterm/config/fonts.html).

Should we leave this open for documentation update reminder purposes ?

**Comment by wez** [comment]
Yeah, I'll update the docs.  Keeping this open until then!

**Comment by hzeller** [comment]
So far no luck yet: installed the `fonts-terminus`, and I can use it in Konsole (where it shows up as selection `Terminus [xos4]`, `Termius [PfEd]` and `Terminus [DEC]`), and can be chosen, and look good and crisp.

But if I use
```
font = wezterm.font("Terminus"),
```
for wezterm, it just tells me that it couldn't find it and used a fallback.
`fc-list | grep Terminus` shows a bunch of matching fonts (various encodings and sizes, files like `/usr/share/fonts/X11/misc/ter-u22n_unicode.pcf.gz` ...)

I guess I have to dive more into fontconfig to understand how fonts are done these days...

**Comment by wez** [comment]
Hmm, maybe it's not packaged the same way on debian.  On my fedora system:

```
$ fc-match "Terminus"
ter-u12n.otb: "Terminus" "Regular"
$ locate ter-u12n.otb
/usr/share/fonts/terminus-fonts/ter-u12n.otb
$ rpm -qf /usr/share/fonts/terminus-fonts/ter-u12n.otb
terminus-fonts-4.49.1-12.fc33.noarch
$ file /usr/share/fonts/terminus-fonts/ter-u12n.otb
/usr/share/fonts/terminus-fonts/ter-u12n.otb: TrueType Font data, 12 tables, 1st "EBDT", 12 names, Unicode, Copyright (C) 2020 Dimitar Toshkov ZhekovTerminusRegularTerminus Regular bitmap height 12Terminu
```

**Comment by wez** [comment]
On my debian 18 image:

```
$ strings /usr/share/fonts/truetype/terminus/TerminusTTF-4.46.0.ttf | grep Terminus
Terminus (TTF)
FontForge 2.0 : Terminus (TTF) : 14-7-2017
Terminus (TTF)
TerminusTTF
```

So I'd suggest trying `font = wezterm.font("Terminus (TTF)")` or `font = wezterm.font("TerminusTTF")`

**Comment by hzeller** [comment]
And update so far: Installing `fonts-terminus` resulted in the TTF to be installed:
```
$ dpkg -L fonts-terminus | grep ttf
/usr/share/fonts/truetype/terminus/TerminusTTF-4.46.0.ttf
```

.. while the `xfonts-terminus` package from earlier contains PCF fonts, which sounds like old-school X-bitmap fonts ?
```
dpkg -L xfonts-terminus | grep pcf | wc -l
234
dpkg -L xfonts-terminus | grep ttf | wc -l
0
```

Just looking for `Terminus` with `fc-match` finds the PCF font, but I suspect these couldn't be picked up by the terminal because old-school X-font (problem from yesterday):
```
$ fc-match "Terminus"
ter-u12n_iso-8859-1.pcf.gz: "Terminus" "Regular
```

The `Terminus (TTF)` as you suggested is indeed found after I installed the `fonts-terminus` package:
```
$ fc-match "Terminus (TTF)"
TerminusTTF-4.46.0.ttf: "Terminus (TTF)" "Medium"
```

So using that results in the regular font look good. Unfortunately, that doesn't have a 'bold' font weight variant ? So I can't use bold yet because that would look ugly ... the `hzeller@bohr` part is the bold fallback font, while 'test' is the crisp `Terminus (TTF)` font.

![terminus-ttf-nobold](https://user-images.githubusercontent.com/140937/111879881-91750680-8965-11eb-904b-7a2fe32d2879.png)

There does seem to be an opentype package `fonts-terminus-otb` available
```
$ dpkg -L fonts-terminus-otb | grep "\.otb"
/usr/share/fonts/opentype/terminus/terminus-bold-oblique.otb
/usr/share/fonts/opentype/terminus/terminus-bold.otb
/usr/share/fonts/opentype/terminus/terminus-normal.otb
/usr/share/fonts/opentype/terminus/terminus-oblique.otb
```

... and that does seem to  contain a font that sounds useful
```
$ strings /usr/share/fonts/opentype/terminus/terminus-bold.otb | grep Termin
Terminus
FontForge 2.0 : Terminus Bold : 25-5-2020
Terminus Bold
TerminusBold
...
```

Yet it seems invisible to font config and is matched with a fallback font:

```
$ fc-match "Terminus Bold"
Vera.ttf: "Bitstream Vera Sans" "Roman"
$ fc-match "TerminusBold"
Vera.ttf: "Bitstream Vera Sans" "Roman
```

So for now, I exclude bold fonts and use the same font for that, but will have to go to the bottom of it

```lua
   -- temporary solution
   font_rules = {
      {
	 intensity = "Bold",
	 font = wezterm.font("Terminus (TTF)"),
      },
      {
	 font = wezterm.font("Terminus (TTF)"),
      }
   },
```

Either I understand why the opentype font is not picked up or have to make a ttf front from the pcf fonts that contains all the variants.

Font configuration on Linux in the 21st century: the last frontier :)

**Comment by wez** [comment]
> Font configuration on Linux in the 21st century: the last frontier :)

I had no idea that fonts would be this difficult when I started this project!

FWIW, this is the `fc-match` syntax for finding bold weight variants; this is from my Fedora system:

```
; fc-match "Terminus:weight=200"
ter-u12b.otb: "Terminus" "Bold"
```

**Comment by hzeller** [comment]
Interestingly, `fc-match` returns the otb font in that case:

```
$ fc-match "Terminus:weight=200"
terminus-bold.otb: "Terminus" "Bold"
```

While the regular Terminus query finds the PCF font:
```
$ fc-match "Terminus"
ter-u12n_iso-8859-1.pcf.gz: "Terminus" "Regular"
```

However, I can't use that in the configuration
```
	 font = wezterm.font("Terminus:weight=200"),
```

```
Unable to load a font matching one of your font_rules: wezterm.font('Terminus:weight=200', {bold=false, italic=false})...
```

So I suspect the search string for `fc-match` is not the same that your font resolver would do ?

**Comment by wez** [comment]
This:

```lua
font = wezterm.font("Terminus", {bold=true}),
```
(in the docs over here: https://wezfurlong.org/wezterm/config/lua/wezterm/font.html)

will translate to a font config query of `Terminus:weight=200` under the covers.

wezterm should be computing that for the default `font_rules`.

If you run `WEZTERM_LOG=wezterm_font=trace wezterm` then wezterm will log a lot of font related diagnostics that might be helpful!

**Comment by hzeller** [comment]
Interesting, with that it _does_ seem to find the font:

```lua
 font_rules = {
      {
	 intensity = "Bold",
	 font = wezterm.font("Terminus", {bold = true}),
      },
      {
	 font = wezterm.font("Terminus (TTF)"),
      }
   },
```

... however, it is invisible; Notice the empty prefix in front of `$` :)

![empty-bold](https://user-images.githubusercontent.com/140937/111882003-6ba12f00-8970-11eb-8a31-d4a9d40ef329.png)

It does seem to have a width. But entirely not visible.

Looking at the font-log, it looks like it finds the Terminus (TTF)
```
font::shaper::harfbuzz     > shaper wants 0 OnDisk { path: "/usr/share/fonts/truetype/terminus/TerminusTTF-4.46.0.ttf", index: 0 }
font::ftwrap               > Loading /usr/share/fonts/truetype/terminus/TerminusTTF-4.46.0.ttf for freetype!
font::ftwrap               > set_char_size computing 12 dpi=96
font::shaper::harfbuzz     > metrics: FontMetrics { cell_width: 8.0, cell_height: 17.440035343170166, descender: -3.0, underline_thickness: 0.8000016212463379, underline_position: -2.4000048637390137 }
```

So far so good; width 8 pixels, height, uhm, 17.4 pixel.

Later, it finds the terminus-bold, but ... with 8 pixesl width and uhm, *zero* height
```
font::shaper::harfbuzz     > shaper wants 0 OnDisk { path: "/usr/share/fonts/opentype/terminus/terminus-bold.otb", index: 0 }
font::ftwrap               > Loading /usr/share/fonts/opentype/terminus/terminus-bold.otb for freetype!
font::ftwrap               > set_char_size computing 12 dpi=96
font::shaper::harfbuzz     > metrics: FontMetrics { cell_width: 8.0, cell_height: 0.0, descender: -4.0, underline_thickness: 0.0, underline_position: 0.0 }
font::rasterizer::freetype > Rasterizier wants OnDisk { path: "/usr/share/fonts/opentype/terminus/terminus-bold.otb", index: 0 }
font::ftwrap               > Loading /usr/share/fonts/opentype/terminus/terminus-bold.otb for freetype!
font::ftwrap               > set_char_size computing 12 dpi=96
```
[fontlog.txt](https://github.com/wez/wezterm/files/6176179/fontlog.txt)

**Comment by wez** [comment]
would you mind attaching that terminus-bold.otb to this issue so I can take a look at it?  (That will save me from having to install a newer ubuntu!)

**Comment by hzeller** [comment]
Find it attached:

[terminus-bold.otb.gz](https://github.com/wez/wezterm/files/6176237/terminus-bold.otb.gz)

**Comment by wez** [comment]
The behavior in `main` with that font should now be improved!

**Comment by hzeller** [comment]
Confirmed fixed; it now uses the font (and it is also not antialias-blurred):

![bold-font-fixed](https://user-images.githubusercontent.com/140937/111884635-27b62600-8980-11eb-98c0-c8b9183ad3b5.png)

With
```lua
 font_rules = {
      {
	 intensity = "Bold",
	 font = wezterm.font("Terminus", {bold = true}),
      },
      {
 	 font = wezterm.font("Terminus (TTF)"),
      }
   },
```

Thanks!

**Comment by hzeller** [comment]
Ah, well, probably needs to be re-opened, as the original issue was about the documentation update...

**Comment by pinpox** [comment]
Question regarding font weights:
I'm trying to set `Source Code Pro` in `Semibold` weight as my default font. 
Fontconfig selects the weight correctly:

```
➜ fc-match "SauceCodePro Nerd Font:style=Semibold"
Sauce Code Pro Semibold Nerd Font Complete.ttf: "SauceCodePro Nerd Font" "Semibold"
```
I tried that the syntax in the config, but this gives me an error:
```lua
	font = wezterm.font("SauceCodePro Nerd Font:style=Semibold"),
```
The documentation shows syntax for bold being `wezterm.font("SauceCodePro Nerd Font", {bold=true})` but `{semibold=true}` does not work.

Could anyone clarify on what the correct syntax is to set e.g. `Semibold` or any other specific font weight for the default font?

**Comment by wez** [comment]
You'll need to use the full name for the font to match that; wezterm's weight matching is pretty anemic at the moment.
You probably want this:

```lua
font = wezterm.font("Sauce Code Pro Semibold Nerd Font Complete")
```

**Comment by wez** [comment]
For debugging this stuff, I find it helpful to set:

```lua
-- set this to the directory that contains the ttf you want to investigate:
font_dirs = {"/home/wez/Downloads/fonts"},
```

Then when you start wezterm:

```
WEZTERM_LOG=wezterm_font=trace wezterm
```

and you'll see a lot of diagnostics about the fonts in that directory, including the names that wezterm parses from those fonts.
