### ISSUE TITLE
"No OpenGL" Crash on Raspberry Pi 5 (Debian 12; ARM64)

### ISSUE THREAD

**Issue by abn0mad** [wez/wezterm#5612]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Gnome, Mutter

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Downloading and installing wez produces the following error:

```
16:56:55.159  ERROR  wezterm_gui::termwindow > failed to create RenderState: Failed to compile shaders: shader version: 330 core: Compilation error in vertex shader: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

shader version: 330: Compilation error in vertex shader: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

shader version: 320 es: Compilation error in vertex shader: 0:1(10): error: GLSL ES 3.20 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

shader version: 300 es: Compilation error in fragment shader: 0:4(12): warning: extension `GL_EXT_blend_func_extended' unsupported in fragment shader
0:15(26): error: index layout qualifier requires EXT_blend_func_extended

16:56:55.272  ERROR  env_bootstrap           > panic at wezterm-gui/src/termwindow/mod.rs:566:13 - No OpenGL
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  19: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  20: <unknown>

thread 'main' panicked at wezterm-gui/src/termwindow/mod.rs:566:13:
No OpenGL
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread panicked while processing panic. aborting.
Aborted
```

Despite having MESA installed and fully functional; i.e. glxinfo -B :

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: V3D 7.1 (0xffffffff)
    Version: 23.2.1
    Accelerated: yes
    Video memory: 7941MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.1
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Broadcom
OpenGL renderer string: V3D 7.1
OpenGL core profile version string: 3.1 Mesa 23.2.1-1~bpo12+rpt3
OpenGL core profile shading language version string: 1.40
OpenGL core profile context flags: (none)

OpenGL version string: 3.1 Mesa 23.2.1-1~bpo12+rpt3
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.2.1-1~bpo12+rpt3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

Both OpenGL and Vulkan function properly with any and all other apps.

### To Reproduce

run wezterm

### Configuration

no config

### Expected Behavior

Wezterm to start up. display a window and allow me to try it out.

**Comment by RoninTech** [comment]
What happens if you use WebGpu instead of OpenGL?

config.front_end = "WebGpu"

**Comment by bruno-garcia** [comment]
Having the same issue. Raspberry Pi OS on a Pi 5 64 bit:
_ 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux_

> What happens if you use WebGpu instead of OpenGL?
> config.front_end = "WebGpu"

Didn't work for me (did I pass the config right?)

```
$ wezterm --config config.front_end="WebGpu"
17:05:55.844  ERROR  wezterm_gui > common_init: set_config_overrides: apply_overrides_to: runtime error: [string "--config config.front_end=WebGpu"]:5: WebGpu evaluated as nil. Check for missing quotes or other syntax issues
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	[string "--config config.front_end=WebGpu"]:5: in main chunk; terminating
```

**Comment by RoninTech** [comment]
I usually just include the config line in my .config/wezterm/wezterm.lua file.  I believe to do it during invocation would need to look like:

`wezterm --config 'front_end="WebGpu"'`

if that gets you a wezterm on your Pi5 I'll be interested to hear if you see the same glitchy effects that I did in my [Pi5 issue (with a video showing what happens) here](https://github.com/wez/wezterm/issues/5442).

With regards to the OpenGL front-end I don't think our Pi's support the required version.  I had [the same problem](https://github.com/wez/wezterm/issues/4215) a while back and Wez prompted me to try the WebGPU front end instead and that worked.

**Comment by bruno-garcia** [comment]
`wezterm --config 'front_end="WebGpu"'` did spawn it, and it has similar glitches from your video.
Thanks for the pointer, I subscribed do that issue

**Comment by abn0mad** [comment]
It does indeed run with ```wezterm --config 'front_end="WebGpu"'```, but not in any useable way, as it glitches out a lot. Getting regular OpenGL ES mode up and running would be best... 

Perhaps the fact that the Pi has its GPU split into two device nodes (/dev/dri/card0 and /dev/dri/card1 for rendering and 3D respectively) has something to do with it - as observed in [Moonlight-QT](https://github.com/moonlight-stream/moonlight-qt/issues/1133) ?

**Comment by RoninTech** [comment]
Strangely I ran Wezterm in WebGpu front end mode on my Pi4 with no issues.  I'll dig it out and find out what version it was that worked and try it on my Pi5.

**Comment by abn0mad** [comment]
@RoninTech - Pi 4 on Wayland? In my own general testing I found that the Pi 4's GPU driver works fine on both X11 and Wayland, but with the Pi 5 only Wayland is useable without significant glitches. The Pi foundation has pretty much dropped support for X11 on the Pi moving forward. I'd still be on X11 otherwise.

**Comment by RoninTech** [comment]
No, Pi4 running wezterm webgpu with no issues doing webgpu in X.  If you run sudo raspi-config on your pi5 you can switch back to X very quickly after a reboot.  I didn't notice any video issues with my pi5 switched back to X.  Except in wezterm.  Alacritty is fine on my pi5 in either Wayland or X.

**Comment by abn0mad** [comment]
@RoninTech - Evidently, my writing style was unclear. As you vehemently assume lack of technical understanding on my part, as well as the matter being closed due to your deployment of Pi OS on a Pi 5 not showing signs of the same glitching, I shall do so as well and mark Wezterm as unusable and unrecommended moving forward.
