### ISSUE TITLE
Cell size calculation not settled on startup

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#563]
## Describe the bug

When first starting the terminal, the cells occcupy a particular size, as calculated from the number of columns and rows and pixel width/height from the screen ( `TIOCGWINSZ`). That size seems to be wrong/not settled yet. After a resize or reloading of the wezterm.lua, the correct font size is calculated.

This is maybe related to #535 ?

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: `20210314-114017-04b7cedd-16-ge5ae1d47`
 
## To Reproduce

With font config below, start terminal and query size.

Current [timg](http://timg.sh/) has a new `--verbose` that can be helpful.

Right after start-up, run a timg:
```
timg --verbose someimage.png
... (image, somewhat distorted as the scale factor is calculated by timg)
Terminal cells: 80x24  cell-pixels: 8x16
```

Now, force recalculation, either by resizing terminal or touching the configuration file

```
timg --verbose someimage.png
... (image, this time properly scaled)
Terminal cells: 80x24  cell-pixels: 10x22
```

## Configuration

Relevant font configuration
```lua
   font_rules = {
      {
	 intensity = "Bold",
	 font = wezterm.font("Terminus (TTF)"),
      },
      {
 	 font = wezterm.font("Terminus (TTF)"),
      }
   },
```

## Expected behavior

Font size is correct on start-up (in this case: 10x22).

**Comment by hzeller** [comment]
The font matched here is
[TerminusTTF-4.46.0.ttf.gz](https://github.com/wez/wezterm/files/6176245/TerminusTTF-4.46.0.ttf.gz)

**Comment by wez** [comment]
Another good catch!  Yes, very similar to that other issue.  Should be fixed now in `main`!

**Comment by hzeller** [comment]
Confirmed fixed!
Thanks!
