### ISSUE TITLE
'\u24e9' Renders Small Compared to Other Terminal Apps

### ISSUE THREAD

**Issue by rrpolanco** [wez/wezterm#565]
**Is your feature request related to a problem? Please describe.**

My `starship` prompt is configured like so:
`printf '%s' 'ⓩ sh'`

When this is rendered in `wezterm` the `U+24E9` character(circled latin small letter Z) is rendered very small:
![image](https://user-images.githubusercontent.com/6497491/111935134-ce89e780-8a90-11eb-83d3-15ed1233c27a.png)

On iTerm:
![image](https://user-images.githubusercontent.com/6497491/111935321-38a28c80-8a91-11eb-93b9-dc2bf1fe5156.png)

On Kitty (personally, this rendering looks the best):
![image](https://user-images.githubusercontent.com/6497491/111935350-48ba6c00-8a91-11eb-9ef7-a918e0e57ba4.png)

**Describe the solution you'd like**

Looks like for iTerm and Kitty, the ⓩ icon is rendered larger when there is a space before and/or after the character. Can `wezterm` implement something similar here?

**Describe alternatives you've considered**
none.

**Additional context**
n/a

**Environment**:
 - OS: macOS 10.15.7
 - Version: Nightly (`wezterm 20210314-114017-04b7cedd-36-ga0d39989`)
 - The active keyboard layout name: ENG (QWERTY)

**Comment by wez** [comment]
Try setting `allow_square_glyphs_to_overflow_width = "WhenFollowedBySpace"` (or `"Always"` if you prefer)

https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html

**Comment by reportaman** [comment]
@rrpolanco It looks the same on my machine irrespective of value of ``allow_square_glyphs_to_overflow_width``. I suspect this is because Kitty bypasses certain symbols built into user's font with its own using a default [symbol_map](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.symbol_map) at startup.

**Comment by bew** [comment]
Which font are you using for that symbol?

**Comment by rrpolanco** [comment]
Setting `allow_square_glyphs_to_overflow_width = "WhenFollowedBySpace"` doesn't seem to change the rendering at all.

>Which font are you using for that symbol?

I'm not sure which exact font `wezterm` is using for rendering but in my config I have:
`  font = wezterm.font_with_fallback({"JetBrains Mono", "FiraCode Nerd Font", "Hack Nerd Font", "IBM Plex Mono", "FuraCode Nerd Font"}),`

I know `kitty` is using `PingFang SC Regular` font for rendering the symbol:
```bash
❯ kitty --debug-font-fallback
[081 08:33:47.227864] Preloaded font faces:
[081 08:33:47.227894] normal face: /System/Library/Fonts/Menlo.ttc
[081 08:33:47.227905] bold face: /System/Library/Fonts/Menlo.ttc
[081 08:33:47.227914] italic face: /System/Library/Fonts/Menlo.ttc
[081 08:33:47.227923] bi face: /System/Library/Fonts/Menlo.ttc
U+24e9 Face(family=PingFang SC, full_name=PingFang SC Regular, postscript_name=PingFangSC-Regular, path=/System/Library/Fonts/PingFang.ttc, units_per_em=1000, ascent=27.6, descent=8.8, leading=0.0, point_sz=0.0, scaled_point_sz=26.0, underline_position=-3.9 underline_thickness=1.5) (new face)
```

**Comment by reportaman** [comment]
@rrpolanco Currently WezTerm picks a font for a glyph in serial order starting from main font, then ordered list of fallback fonts, and finally fonts on system. So whichever font it finds a glyph first in, it will pick that font's glyph for a unicode code-point. To be able to allow users to specify a mapping of unicode codepoint to font, WezTerm would need to implement something like [symbol_map](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.symbol_map) of Kitty term. I had a matrix chat with @wez yesterday, and it seems like a more complex task at present.

Given you are using macOS, you can open FontBook, select "Switch to custom preview mode" (show with a``T<suffix>`` symbol),  copy-paste this glyph in it, and select fonts you have as main font & fallback to see where WezTerm could be picking it from.

**Comment by rrpolanco** [comment]
I can confirm that @wez 22522dc39eef241c1aa354ef39b86b8f2d67ba53 commit has fixed this for me.
