### ISSUE TITLE
Wezterm Panic in Nightly Build

### ISSUE THREAD

**Issue by JavaCafe01** [wez/wezterm#566]
When trying to run the latest wezterm build either from nightly-builds or building from source, I get an internal error:

```
thread 'main' panicked at 'internal error: entered unreachable code', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.28.0/src/buffer/alloc.rs:1292:17
```

## Environment

 - OS: Arch Linux X11
 - Version: wezterm 20210314-114017-04b7cedd-36-ga0d39989
 - Keyboard: ENG

## To Reproduce

1. Install wezterm from the nightly builds or by building from source.
2. Run wezterm.

## Configuration

Default config.

## Expected behavior

Wezterm should open normally.

## Additional context

[Rust backtrace](http://0x0.st/-qo3.txt)
[Startup log](http://0x0.st/-qoY.txt)

**Comment by wez** [comment]
Sorry about this; fixed now in main
