### ISSUE TITLE
Scrollbar thumb 'jumps' when touched, then continues at an offset

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#568]
## Describe the bug

When grabbing the scrollbar-thumb with the mouse it seems to jump to an offset relative to the mouse-pointer (and with it the screen-content according to the _new_ thumb position), then operates relative to there. Looks like some sort of rounding error to what the initial distance calculation ?

## Environment

 - OS: Linux Debian sid
 - Version: `20210314-114017-04b7cedd-41-ga5f4803b`
 
## To Reproduce

Fill a terminal with a bit of scrollback text, then grab the thumb. It jumps as shown below in the screencast

(sorry had to gzip the mkv screencast, github does not allow that as a file-type to be uploaded)

[wezterm-scrollbar.mkv.gz](https://github.com/wez/wezterm/files/6179472/wezterm-scrollbar.mkv.gz)

### Configuration
Not sure if there is anything special. Using Terminus (TTF) font with filling the cell with 10x22 pixels.

**Comment by deflock** [comment]
I can confirm this on Win10. @wez have you reproduced this?

**Comment by wez** [comment]
I haven't looked into this yet
