### ISSUE TITLE
Accessing selected text in Lua

### ISSUE THREAD

**Issue by RauliL** [wez/wezterm#575]
There currently is no (at least that I am aware of) way of getting selected text in Lua scripts. Is this something that could be added to the Pane object? Such feature would be useful for implementing Plan 9 style plumbing.

**Comment by wez** [comment]
Yeah, that's a reasonable request.
It feels similar to https://github.com/wez/wezterm/issues/527#issuecomment-796861356 but that didn't call out the selection.

**Comment by wez** [comment]
https://github.com/wez/wezterm/blob/main/docs/config/lua/window/get_selection_text_for_pane.md is now available in main and will show up in the nightly builds within the hour
