### ISSUE TITLE
Home and End keys aren't mapped on macOS

### ISSUE THREAD

**Issue by pronebird** [wez/wezterm#5769]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Sorry but not yet.

### Describe the bug

Fn+arrow_left is mapped to Home key and Fn+arrow_right is mapped to End key on macbook running macOS. Wezterm does not seem to understand that and just makes a beeping noise.

### Configuration

local wezterm = require 'wezterm'
local config = wezterm.config_builder()
config.color_scheme = 'AdventureTime'
return config

**Comment by 1stvamp** [comment]
I had a similar issue and adding these mappings to `config.keys` worked for me:

```lua
configs.keys = {
     { mods='', key="Home", action=wezterm.action{SendString="\001"} },
     { mods='', key="End", action=wezterm.action{SendString="\005"} },
}
```

**Comment by lgrn** [comment]
@1stvamp it's `config` singular, not plural `configs`, but it works. Thanks.

**Comment by wez** [comment]
Please set `debug_key_events=true` and see [how to debug key events](https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html) to see and share the key event debug logs here!

On X11 and Wayland systems, for additional tracing, you may start wezterm like this:

```
WEZTERM_LOG=window::os::x11::keyboard=trace,info wezterm
```
