### ISSUE TITLE
error: failed to parse manifest at Cargo.toml

### ISSUE THREAD

**Issue by erf** [wez/wezterm#577]
I failed to build from source now on `0643e8b0` using `cargo build --release`.

## Build Environment (please complete the following information):

macOS

```
rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/erlend/.rustup

nightly-aarch64-apple-darwin (default)
rustc 1.50.0-nightly (3ff10e74a 2020-12-04)
```

## Dependencies

```
./get-deps
./get-deps: line 33: lsb_release: command not found
./get-deps: line 33: test: =: unary operator expected
```

## The build output

Please include the output from running the build command:

```
cargo build --release
error: failed to parse manifest at `/Users/erlend/projects/wezterm/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```

**Comment by wez** [comment]
rustup update

As you need the latest version of rust

**Comment by wez** [comment]
https://github.com/wez/wezterm/commit/dbd7fc28a5350b6f7a9f3a8d1d5571197df3ab80
is the relevant commit

**Comment by erf** [comment]
Solved after upgrading
