### ISSUE TITLE
run_child_process()

### ISSUE THREAD

**Issue by chilljalapeno** [wez/wezterm#5777]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

running wezterm.run_child_process() works only if I open wezterm from another terminal, but if I open it from macos with spotlight it does not

### Configuration

	{
		key = "2",
		mods = "CMD",
		action = wezterm.action_callback(function(window, pane)
			wezterm.run_child_process({
				"zellij",
				"-s",
				"joyous-triceratops",
				"action",
				"go-to-tab",
				"2",
			})
		end),
	},

### Expected Behavior

It is weird because if I run wezterm from another terminal it works perfectly fine, but not if I open it from spotlight.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/faq.html#im-on-macos-and-wezterm-cannot-find-things-in-my-path
