### ISSUE TITLE
Ability to Open Wezterm in a Specified Directory

### ISSUE THREAD

**Issue by atomic-kat** [wez/wezterm#5786]
Currently, when launching wezterm, it opens in the user's home directory (~/).

It would be beneficial to have an option or command-line parameter that allows

users to specify the directory in which wezterm should open upon launch.

Something like below ::

`wezterm --directory ~/backups`

or

`wezterm open ~/backups`

Also, is this feature already exists let me know. As i couldn't find it on help section or docs.

![image](https://github.com/wez/wezterm/assets/151607738/699e356d-846a-4cd2-a81d-fd31bee2402a)

**Comment by Funami580** [comment]
`wezterm start --cwd /tmp`

**Comment by atomic-kat** [comment]
Thanks for the help @Funami580
