### ISSUE TITLE
Neovim not taking the whole terminal screen in Wezterm terminal

### ISSUE THREAD

**Issue by 6H075T2** [wez/wezterm#5788]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Neovim in Wezterm Terminal has extra padding even though it's already set to 0 in the .wezterm.lua config file and I'm quite annoyed by its appearance since its very visible with my color scheme in neovim. Any help is much appreciated.

![image](https://github.com/wez/wezterm/assets/79183240/7ca23605-25e9-4ad8-93c5-32adbbd80bbf)

### Configuration

```
local wezterm = require 'wezterm'
local config = 
{
    window_padding = { left = 0, right= 0, top = 0, bottom = 0 },
}
return config
``
```

### Expected Behavior

Neovim taking the whole screen in Wezterm Terminal

**Comment by db48x** [comment]
Not a bug. Your window is not big enough to show an extra row or column of text. The extra space is simply unused. You could change your font size and font size so that the character cells are an integer factor of the width and height (less the height of the tab bar and title bar), or you could ignore it.

**Comment by wez** [comment]
As per the comment above, wezterm has to put some pixels in the unusable gaps. There's no bug here.

**Comment by 6H075T2** [comment]
Hello @wez, 
I spent a day finding a font and adjusting it, but I couldn't get the desired outcome I've looked into Alacritty but it seems it's not a problem there and didn't need such fiddling. I've used Monaspice Radon bold style font I've already tried anything adjusting size/line height but did not work maybe it's because it's platform specific? I'm using Windows 11.
