### ISSUE TITLE
Builtin {Z,X,Y}modem Support

### ISSUE THREAD

**Issue by septs** [wez/wezterm#5799]
**Is your feature request related to a problem? Please describe.**
Simplify small-size file transfer on shell channel (e.g: SSH, Telnet, Serial port, etc)

**Describe the solution you'd like**
Builtin {Z,X,Y}modem transfer file feature, Default by enabled

**Describe alternatives you've considered**
It is relatively complicated to embed this function into iTerm2, https://github.com/robberphex/iTerm2-zmodem

**Additional context**
- https://www.ohse.de/uwe/software/lrzsz.html

**Comment by wez** [comment]
See also: https://github.com/wez/wezterm/discussions/1450
