### ISSUE TITLE
Cask 'wezterm-nightly' is unavailable: No Cask with this name exists.

### ISSUE THREAD

**Issue by flczcy** [wez/wezterm#5805]
**What page or section of the docs have an issue?**
https://wezfurlong.org/wezterm/install/macos.html#macports

**Describe the issue**

```
brew tap homebrew/cask-versions
Error: homebrew/cask-versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
```

```
brew install --cask wezterm-nightly
Warning: Cask 'wezterm-nightly' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
==> Casks
wezterm@nightly

To install wezterm@nightly, run:
  brew install --cask wezterm@nightly
```

```
brew install --cask wezterm@nightly 
Error: Cask 'wezterm@nightly' conflicts with 'wezterm'.
```

**Comment by wez** [comment]
Please suggest an alternative working solution. I don't often use my mac and I don't use brew for wezterm there.
It seems like https://github.com/Homebrew/homebrew-cask may be where that recipe ended up.

**Comment by wez** [comment]
Possibly: https://github.com/wez/wezterm/issues/5466

**Comment by wez** [comment]
https://github.com/wez/wezterm/issues/5433 is part of the same stuff
