### ISSUE TITLE
Allow mouse bindings to bypass mouse-reporting

### ISSUE THREAD

**Issue by bew** [wez/wezterm#581]
**Is your feature request related to a problem? Please describe.**
My open-link mouse-binding is Ctrl-click on wezterm, I'd like to have the exact same bindings to work whenever the program activated mouse-reporting or not.
Otherwise I must know if it has, and press the additional Shift key to bypass mouse reporting.

**Describe the solution you'd like**
A new field for mouse bindings like `bypass_mouse_reporting` defaulting to false.

**Describe alternatives you've considered**
Using the shift key, but to me it's not always consistent because I must know if a program has it enabled or not..

_Edit: Another mouse binding I'd like to use like this is Middle mouse click to paste, so I can paste in tmux (or others) with bracketedpaste always the same way._

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
