### ISSUE TITLE
Possibility to use bash aliases as commands in args

### ISSUE THREAD

**Issue by masc-it** [wez/wezterm#5828]
Hey, first thing first thanks for your amazing terminal.

I was wondering if there was the possibility to use bash aliases (defined in bashrc) in the spawnCommandInNewTab, e.g.:

```
{
        key = '1',
        mods = 'CTRL',
        action = wezterm.action.SpawnCommandInNewTab {
            args = { 'ca', 'mypyenv' },
          cwd = 'myprojectpath'
        },
      },
```

where in this case `ca` is a bash alias defined like so:

```
ca(){
  conda activate $1
}
```

I mean, I'd love if I could reuse such aliases, rather than rewriting them for wezterm (I have tons of them).

**Comment by wez** [comment]
wezterm will never be able to do this directly, because it doesn't know anything about your bash aliases, however, you can explicitly launch bash and ask it to evaluate the command:

```lua
{
        key = '1',
        mods = 'CTRL',
        action = wezterm.action.SpawnCommandInNewTab {
            args = { 'bash', '-c', 'ca mypyenv' },
          cwd = 'myprojectpath'
        },
      },
```
