### ISSUE TITLE
Gaps around block drawing glyphs

### ISSUE THREAD

**Issue by JeanMertz** [wez/wezterm#584]
Using the [vertical bar](https://en.wikipedia.org/wiki/Vertical_bar) (`|`) together with `line_height` other than `1.0` causes spacing between two bars positioned above each other.

Technically, this makes perfect sense. But aesthetically, the use-case for a vertical bar is often to mimic a continuous line from top to bottom in a terminal. For example, in Vim, it's often used to draw a line between two splits.

I used Kitty before, and it renders vertical bars as "expected", even with increased line spacing:

<img width="214" alt="Screenshot 2021-03-29 at 22 20 17" src="https://user-images.githubusercontent.com/383250/112895117-002c2f80-90dd-11eb-8361-2da6f936d2d3.png">

While Wezterm does not:

<img width="265" alt="Screenshot 2021-03-29 at 22 20 29" src="https://user-images.githubusercontent.com/383250/112895126-03bfb680-90dd-11eb-9b8a-57cc10a2e002.png">

(there's also a difference in vertical text positioning between the two, but I filed #582 to track that)

I can see this being closed as "working as intended" because it really is, but I hope that you agree that this could potentially warrant a special case to cover the most common use-case for a character like this.

**Comment by wez** [comment]
Kitty has [special case logic for a variety of box drawing glyphs](https://github.com/kovidgoyal/kitty/blob/master/kitty/fonts/box_drawing.py#L768).  So far, wezterm only does that for the "Block Elements" unicode range (https://github.com/wez/wezterm/issues/433), but I think it is reasonable to expand the scope to some or all of https://unicode-table.com/en/blocks/box-drawing/

**Comment by JeanMertz** [comment]
> but I think it is reasonable to expand the scope to some or all of [unicode-table.com/en/blocks/box-drawing](https://unicode-table.com/en/blocks/box-drawing/)

Thanks for the pointer.

It appears the character in my use-case is the  [Box Drawings Light Vertical](https://unicode-table.com/en/2502/), so that would indeed be captured by special-casing the "box drawing" characters.

**Comment by GladOSkar** [comment]
The same applies to powerline characters btw.

Config for both `wezterm` and `kitty`:
```
font_size = 9
line_height = 1.4
```

`wezterm`:
![image](https://user-images.githubusercontent.com/9497832/113486373-a8157480-94b2-11eb-96f7-b90597653ea5.png)

`kitty`:
![image](https://user-images.githubusercontent.com/9497832/113486380-b19edc80-94b2-11eb-812b-a2e9fc2ea4d6.png)

So this would be great to have! :)

**Comment by bew** [comment]
I'd be interested in these chars, which are not part of standard Box Drawing chars:
```
🭽▔▔▔🭾
▏foo▕
🭼▁▁▁🭿
```
_github's monospace is broken :eyes:_
In wezterm it gives:
![wezterm-nice-borders](https://user-images.githubusercontent.com/9730330/115160202-4864bf00-a097-11eb-8660-396fef91ac97.png)


These are from the `Legacy Computing` unicode block: https://unicode-table.com/en/blocks/symbols-for-legacy-computing (that website is kinda broken to show the chars, you can still see them in the title of single-char pages).

---
The usecase is for this (from someone' nvim config seen on matrix):
![nice-borders](https://user-images.githubusercontent.com/9730330/115160222-62060680-a097-11eb-93ba-5fd8cb3bf6c3.png)

---
In the same manner, all chars in `Legacy Computing` do not line up to the top/bottom of the cell, as visible here:
![legacy_computing_wezterm](https://user-images.githubusercontent.com/9730330/115162077-a72f3600-a0a1-11eb-87fb-4aefc9aae7c7.png)

For box drawing chars, some chars do line up to the top/bottom and **some even overlap the cell above/below**, see:
![box_drawing_wezterm](https://user-images.githubusercontent.com/9730330/115162154-38061180-a0a2-11eb-9bad-7a1102c0275e.png)

**Comment by wez** [comment]
@GladOSkar: I just pushed a couple of commits that should help with the powerline triangle and curve glyphs with larger line height; should show up in the nightly builds in the next 30 minutes.

**Comment by GladOSkar** [comment]
Looks great! Thanks!

![image](https://user-images.githubusercontent.com/9497832/121868065-d7d9c780-cd00-11eb-8751-29366a708112.png)

**Comment by Anomalocaridid** [comment]
There's still a minor issue with rendering powerline glyphs.
![2021-09-06T21:51:49,120973441-04:00](https://user-images.githubusercontent.com/29845794/132272229-0a1dfbad-16a4-490c-9c17-345f2f553d0b.png)


As you can see, the half-rectangle triangles (\uE0BA and \uE0BC in Nerd Fonts) on each end are a tad wonky. They look like they take up two cells each, with the one on the left even appearing to overlap with the non-empty cell after it. And the chevron next to the cursor (❯) at the start of the left line is significantly smaller than it should be. It should be around the entire height of the cell.

**Comment by wez** [comment]
@Anomalocaridid please open a separate issue so that we have all the information we need to understand and resolve it!
