### ISSUE TITLE
Terminal displays UTF graphemes 👩‍🚒 as 👩<200d>🚒

### ISSUE THREAD

**Issue by shaozi** [wez/wezterm#5857]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240715-080945-c9116830

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

copy and paste this 👩‍🚒 into wezterm. it cannot display it correctly, instead, it displays 👩<200d>🚒

### To Reproduce

copy and paste this 👩‍🚒 into wezterm. it cannot display it correctly, instead, it displays 👩<200d>🚒

### Configuration

no config

### Expected Behavior

should intemperate utf combination correctly

**Comment by monomere** [comment]
maybe this is to do with the unicode version? see `unicode_version` in the config

**Comment by monomere** [comment]
sorry for commenting twice, but might be an issue with `zsh`: https://wezfurlong.org/wezterm/faq.html#pasting-or-entering-unicode-in-zsh-looks-broken

**Comment by shaozi** [comment]
It is not zsh. I tried in iTerm and it displays it correctly. It is about handling utf8 graphemes, <200d> is a joiner. Here is an explanation from the [Elixir Guide](https://hexdocs.pm/elixir/binaries-strings-and-charlists.html)

> Besides defining characters, UTF-8 also provides a notion of graphemes. Graphemes may consist of multiple characters  that are often perceived as one. For example, the [woman firefighter emoji](https://emojipedia.org/woman-firefighter/) is represented as the combination of three characters: the woman emoji (👩), a hidden zero-width joiner, and the fire engine emoji (🚒):
> ```elixir
> String.codepoints("👩‍🚒")
> ["👩", "‍", "🚒"]
> String.graphemes("👩‍🚒")
> ["👩‍🚒"]
> ```

**Comment by shaozi** [comment]
Tried again with bash and it works. So it indeed is zsh's issue.

**Comment by wez** [comment]
This is a zsh issue, as is discussed in the FAQ, along with the remedy: https://wezfurlong.org/wezterm/faq.html#pasting-or-entering-unicode-in-zsh-looks-broken
