### ISSUE TITLE
cursor display error in fishshell vim mode

### ISSUE THREAD

**Issue by jsenjobs** [wez/wezterm#5864]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

macOs + fish + tmux-256color

fish config
`set -g fish_key_bindings fish_vi_key_bindings
# cursor
set -g fish_cursor_default block
set -g fish_cursor_insert line
set -g fish_cursor_visual underscore
`

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

can not display cursor correct (insert mode with SteadyBar, normal mode with SteadyBlock).

<img width="788" alt="image" src="https://github.com/user-attachments/assets/11894a31-2467-4a1d-9724-39391348ce98">

in tmux:
<img width="729" alt="image" src="https://github.com/user-attachments/assets/5f253fc9-404f-47d4-a560-6ac7008f49d3">

in tmux + tmux-256color is correct.
in iterm2 + tmux-256color is correct.
in kitty + xterm-kitty is correct.

### Configuration

`-- Pull in the wezterm API
local wezterm = require("wezterm")
local act = wezterm.action

local nvim_command = function(command)
	local actions = {}
	table.insert(actions, act.SendKey({ key = "Escape" }))

	if type(command) == "string" then
		for c in command:gmatch(".") do
			table.insert(actions, act.SendKey({ key = c }))
		end
	elseif type(command) == "table" then
		for _, c in ipairs(command) do
			table.insert(actions, act.SendKey(c))
		end
	else
	end

	return act.Multiple(actions)
end
local wez_key = function(mods, key, command)
	return {
		key = key,
		mods = mods,
		action = nvim_command(command),
	}
end

return {
	term = "tmux-256color",
	default_cursor_style = "SteadyBar",
	-- cursor_blink_ease_out = "Linear",
	-- cursor_thickness = 2,
	font = wezterm.font("JetBrainsMono Nerd Font Mono", { weight = "Regular" }),
	font_size = 18,
	color_scheme = "Catppuccin Mocha",
	use_fancy_tab_bar = false,
	hide_tab_bar_if_only_one_tab = true,
	adjust_window_size_when_changing_font_size = false,
	window_decorations = "RESIZE",
	show_new_tab_button_in_tab_bar = false,
	macos_window_background_blur = 64,
	window_background_opacity = 0.7,
	text_background_opacity = 1,
	window_padding = {
		left = 20,
		right = 20,
		top = 20,
		bottom = 5,
	},
	keys = {
		--  idea vim key mapping start
		--  file search
		wez_key("CMD", "k", " fC"),
		wez_key("CMD", "o", " ff"),
		wez_key("CMD", "e", " fo"),
		wez_key("CMD|CTRL", "o", " e"),
		wez_key("CMD", "F", " fw"),
		wez_key("CMD", "f", " f/"),
		wez_key("CMD", "w", " c"),
		--  idea jump keymap
		wez_key("CMD|ALT", "LeftArrow", { mods = "CTRL", key = "o" }),
		wez_key("CMD|ALT", "RightArrow", { mods = "CTRL", key = "i" }),
		wez_key("CMD", "b", "gd"),
		wez_key("CMD|CTRL", "b", "grr"),
		wez_key("CMD", "u", "gD"),
		wez_key("CMD|ALT", "b", "gI"),
		wez_key("ALT", "Enter", " la"),
		wez_key("CMD|ALT", "6", " lr"),
		wez_key("CMD", "p", "gK"),
		-- ## idea debug keymap
		wez_key("CMD|ALT", "r", " dc"),
		wez_key("", "F2", " lD"),
		wez_key("CMD", "2", " tf"),
		-- # idea vim key mapping end
	},
	colors = require("colors")(),
}
`

**Comment by Plonq** [comment]
Why is this closed? Is there a solution? I am getting the same problem, also with fish shell on macOS. The cursor always stays the default cursor. If the default is block and I enter insert mode it stays a block. Here's a video demonstrating. You can see the actual mode by the direction of the chevron.

https://github.com/user-attachments/assets/f8bb1608-2013-476d-baed-95953559b922

This happens with the default config, but here's the config from the video:

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This will hold the configuration.
local config = wezterm.config_builder()

-- This is where you actually apply your config choices

config.font = wezterm.font 'JetBrains Mono'
config.font_size = 13
config.color_scheme = 'OneDark (base16)'
-- config.default_cursor_style = 'SteadyBar'

-- and finally, return the configuration to wezterm
return config
```
