### ISSUE TITLE
font/emoji sizing issues using `Allsorts`

### ISSUE THREAD

**Issue by JeanMertz** [wez/wezterm#587]
It appears on my Mac, that emoji characters are scaled disproportionally. If I were to take a guess, I'd say they are drawn at their original pixel size, instead of accounting for HiDPI scaling, maybe?

I also, by happenstance hovered over my open tabs at the top and noticed that the number also scales disproportionally. I can't be sure if this is as intended, but my guess is that it isn't.

It appears to only happen if I set the font shaper to `Allsorts`, perhaps this is already captured in #66?

 - OS: macOS
 - Version: wezterm 20210314-114017-04b7cedd-116-g1af47804

<img width="276" alt="Screenshot 2021-03-30 at 09 02 12" src="https://user-images.githubusercontent.com/383250/112947654-5c23a200-9137-11eb-8ce0-1f6f6ec60d54.png">

Note that if I do disable `AllSorts`, there's still an issue with hovering the tabs, so it appears that might be a separate bug?

(see the non-matching and differently sized numbers)

<img width="374" alt="Screenshot 2021-03-30 at 09 08 25" src="https://user-images.githubusercontent.com/383250/112947798-8c6b4080-9137-11eb-82ee-87bc2c64ec06.png">

<img width="348" alt="Screenshot 2021-03-30 at 09 08 31" src="https://user-images.githubusercontent.com/383250/112947829-912ff480-9137-11eb-881c-155678758f4b.png">

**Comment by wez** [comment]
Yeah, Allsorts isn't quite ready to use right now.  I'm fine keeping this issue open as a reminder of this specific aspect.

When numbers start picking up emoji, it typically points to an issue with the order in which you've specified the font fallback in your configuration.  eg: you've listed the emoji font ahead of the baseline font, *or*, the bold/italic variants of the font that get computed for the default `font_rules` (https://wezfurlong.org/wezterm/config/fonts.html) either don't exist or don't have those glyphs so the fallback moves on to the emoji font and finds them there.

**Comment by wez** [comment]
Running `WEZTERM_LOG=wezterm_font=trace wezterm` can reveal helpful troubleshooting information about fonts!
