### ISSUE TITLE
Change config options such as opacity with a keymap

### ISSUE THREAD

**Issue by bragadzilla** [wez/wezterm#5880]
I've been scrolling through documentation and issues for a few days trying to find a way to do this, but I couldn't. All I want is to be able to change config options (specifically window_background_opacity) with a keymap. Is this possible ?

I've tried the following, it does not work.
(I apologize in advance for my poor understanding of lua)
```lua
        {
            key = "o",
            mods = "CTRL|SHIFT",
            action = wezterm.action_callback(function()
                wezterm.config.window_background_opacity = 1
            end)
        },
```

**Comment by bew** [comment]
Take a look at `window:set_config_overrides`:
https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html

**Comment by bragadzilla** [comment]
> Take a look at `window:set_config_overrides(...)` method: https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html

This is exactly what I was looking for. Thanks a lot!
