### ISSUE TITLE
Text gets underlined randomly when in tmux

### ISSUE THREAD

**Issue by farico** [wez/wezterm#5891]
### What Operating System(s) are you seeing this problem on?

Linux Wayland, macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE

### WezTerm version

20240730-082727-56a27e93

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When launched in tmux and moving mouse over the text sometimes wezterm underlines everything (all text). I don't understand what causes it and how to get out of this "mode". Detaching from tmux session and re-attaching usually helps. It happens on MacOs and Linux. See attached gif:
![Screen Recording 2024-08-02 at 10 52 41](https://github.com/user-attachments/assets/1b846ca2-eb96-4efb-b1d3-e0d9e7b14aab)

### To Reproduce

Run wezterm
Run tmux
Spend some time working with the system

### Configuration

```-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This will hold the configuration.
local config = wezterm.config_builder()

config.color_scheme = "Bamboo"
config.font_size = 13.0
config.line_height = 1.3
config.enable_tab_bar = false
config.window_padding = {
        left = 4,
        right = 1,
        top = 0,
        bottom = 0,
}
config.scrollback_lines = 100000
local dimmer = { brightness = 0.1 }

config.window_background_image =
        "/Users/user/Documents/Wallpapers/179428810-69b440d1-7107-49f2-ab2b-aaab1c449cce.jpeg"
config.window_background_image_hsb = dimmer
-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

No random underlining of all text

### Logs

```
Debug Overlay
wezterm version: 20240730-082727-56a27e93 aarch64-apple-darwin
Window Environment: macOS 14.5 (23F79)
Lua Version: Lua 5.4
OpenGL: Apple M2 Pro 4.1 Metal - 88.1
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>
```

### Anything else?

I would like to blame this on my usage of tmux, but I did not experience this issue in iTerm2.

**Comment by farico** [comment]
Tried config to disable all hyperlinks:
```
config.hyperlink_rules = {}
```
problem still persists.

**Comment by fanzeyi** [comment]
Seeing the same issue. Suspecting tmux 3.4 OSC 8 support is related to this issue.

It doesn't reproduce in Alacritty.

**Comment by fanzeyi** [comment]
In my `tmux.conf` I used to have this for forcing hyperlink support:

```
set -as terminal-overrides ',*:Hls=\E]8;id=%p1%s;%p2%s\E\\:Hlr=\E]8;;\E\\'
```

I removed this and replaced it with

```
set -ag terminal-features "*:hyperlinks"
```

This seems to resolved the issue, but I am not 100% certain. Will try running with this a bit longer and report back.

**Comment by farico** [comment]
Good catch! I also have it as terminal-overrides. I've changed it as well - will report back after some usage.

**Comment by fanzeyi** [comment]
@farico Yes. I have not observed this issue again for the past week.

**Comment by farico** [comment]
I confirm it fixes the issue.
