### ISSUE TITLE
Inactive tab stays hovered when moving the mouse from the tab back to terminal

### ISSUE THREAD

**Issue by durka** [wez/wezterm#591]
## Describe the bug

An inactive tab becomes highlighted when the mouse moves over it. If you then move the mouse to another tab, it reverts to inactive. However, if you move the mouse from the inactive tab to the window titlebar or the terminal, the inactive tab remains highlighted.

## Environment (please complete the following information):

 - OS: Linux X11 (Ubuntu 20.04)
 - Version: wezterm 20210314-114017-04b7cedd
 - The active keyboard layout name ENG

## To Reproduce

1. Open a Wezterm session with more than one tab.
2. Hover the mouse over an inactive tab.
3. Move the mouse straight down, to the terminal, not passing over the active tab

## Configuration

The bug still occurs when I remove all configuration.

## Expected behavior

The inactive tab should revert to regular un-highlighted state.

## Screenshots

Screenshots corresponding to steps in "To Reproduce":

1. ![image](https://user-images.githubusercontent.com/47007/113079373-e6edb680-91a2-11eb-81d1-a9350ad34c86.png)
2. ![image](https://user-images.githubusercontent.com/47007/113079418-fb31b380-91a2-11eb-878a-305b32d93f2d.png)
3. ![image](https://user-images.githubusercontent.com/47007/113079458-113f7400-91a3-11eb-9c70-ed1ba6638645.png)

**Comment by durka** [comment]
Looks good! I guess the `window` library would need to add handling for "mouse pointer enter/leave" events to fix the rest of the corner cases?

**Comment by wez** [comment]
Yeah, there are a couple of cases: mouse outside of window bounds while focused, and window losing focus, that would need to be factored in.

**Comment by durka** [comment]
Oh yeah, I normally use focus-follows-mouse so I forgot those were separate cases.
