### ISSUE TITLE
Background color does not cover entire character in some fonts

### ISSUE THREAD

**Issue by durka** [wez/wezterm#592]
## Describe the bug

The background color sometimes doesn't reach to the bottom of the line, depending on the font and the size. I have observed the issue with Ubuntu Mono at sizes near 12.

## Environment (please complete the following information):

 - Linux X11 (Ubuntu 20.10)
 - Version: 20210314-114017-04b7cedd
 - The active keyboard layout name: ENG

## To Reproduce

`echo -e '\033[48;5;88;38;5;15m[test]\033[0m'`

## Configuration

Results shown below for a custom font and the regular font, both size 12. Antialiasing and hinting don't matter.

## Screenshots

Ubuntu Mono:
![image](https://user-images.githubusercontent.com/47007/113080915-b6f3e280-91a5-11eb-857b-52aa1c31dac0.png)

Default font:
![image](https://user-images.githubusercontent.com/47007/113080960-c96e1c00-91a5-11eb-9ca1-96161844c795.png)

**Comment by wez** [comment]
I think that's just differences in how those fonts are designed; different fonts have different ascent, descent and linegap values (https://www.freetype.org/freetype2/docs/glyphs/glyphs-3.html).

wezterm uses the full computed cell dimensions for the background, so the background is always 100% in the right place by definition.

How does that compare to eg: gnome terminal (which also uses freetype under the covers) with the same fonts?

**Comment by durka** [comment]
I thought it might be a bug for two reasons:

1. At smaller and larger font sizes the inconsistensy goes away
2. I'm comparing to kitty with the same font and size: 
![image](https://user-images.githubusercontent.com/47007/113085596-279efd00-91ae-11eb-9501-6aa72339434c.png)

**Comment by durka** [comment]
Gnome-terminal looks the same as wezterm, however.

**Comment by wez** [comment]
Regarding anti-aliasing settings, were you using [font_antialias](https://wezfurlong.org/wezterm/config/lua/config/font_antialias.html)? 
 if so, note that it was replaced by [freetype_load_target](https://wezfurlong.org/wezterm/config/lua/config/freetype_load_target.html) in the most recent release.  I don't know if all of the docs reflect that change yet!

**Comment by durka** [comment]
I was also playing with freetype_load_target, which did have an effect but
it seems like kitty is still using a different mode.

The screenshot below (kitty on the right) looks *almost* the same. This is
with

    font = wezterm.font("Ubuntu Mono with Numderline"),
    font_size = 12.0,
    freetype_load_target = "Light",
    freetype_load_flags = "FORCE_AUTOHINT|NO_AUTOHINT",
    color_scheme = "UnderTheSea",

[image: image.png]

To be clear I think wezterm looks good. Just really not sure what kitty is
doing slightly differently, if there is some freetype flag that Wezterm is
not exposing. Also, kitty doesn't seem to support bolding (or it's disabled
by default).

**Comment by durka** [comment]
Sorry here's the zoomed in screenshot I was trying to share. 
![image](https://user-images.githubusercontent.com/47007/113163896-99a72e80-920e-11eb-9969-2cd5ac5b38c3.png)

**Comment by wez** [comment]
I think we explained the original issue as a font design thing rather than a wezterm bug.  Regarding rendering, it sounds like you are happy with how it looks, so I'm going to close this.  If you have further questions, please open a new issue or start a new discussion.  Thanks!
