### ISSUE TITLE
WezTerm-20240203-110809-5046fc22-setup.exe appears to be flagged by hash on VirusTotal

### ISSUE THREAD

**Issue by zerowaitstate** [wez/wezterm#5948]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The setup.exe for Windows appears to be flagged on VirusTotal (https://www.virustotal.com/gui/file/35a6ec0eff7aa65e3987f14223bfb9df831eaab2964eb441ed6cad4356d252ff)

hash 35a6ec0eff7aa65e3987f14223bfb9df831eaab2964eb441ed6cad4356d252ff

### Configuration

no config

**Comment by NonlinearFruit** [comment]
Similar to #5074

[Wez's comment](https://github.com/wez/wezterm/issues/5074#issuecomment-1974922875) over there might apply:

> These sorts of false positives pop up from time to time; you can see from searching in this repo the prior events. They are outside of my control and sort themselves out after someone reports the false positive.
>
> You might have better luck with the nightly build.
> 
> | _I'm a little concerned that this has not been acknowledged yet. Wezterm is otherwise trustworthy right? I haven't used it before this issue._
> 
> Everything in wezterm is open source, and the CI is also open source. You can see exactly what has gone into a build and verify that there is nothing nefarious happening here, to the binaries that you download from this github repository.
> 
> If you are installing via some external aggregator/distro then the chain of trust is less clear.
> 
> It is currently "too difficult" for an independent OSS maintainer to automate code signing for windows executables; it's a ludicrous endeavor: I would need to found an LLC, have it independently verified, then fund annual book keeping for the LLC, its tax returns and status, just to get a code signing certificate that doesn't result in a scary prompt for the user. In addition, I have yet to find a certificate provider that will integrate nicely with GH actions in a fully automated way (most require some kind of USB hardware device or cloud call that requires a presence check in order to sign), so that implies that I therefore also need to procure and maintain a dedicated windows build system to produce these binaries and keep pressing a button on each build run.
> 
> I would love for this situation to be different!
> 
> https://fosstodon.org/@voltagex@aus.social/111819639907704896 is a thread with more context.
```

**Comment by zerowaitstate** [comment]
Yeah, I just noticed this is a dup of a closed issue on same release version.
