### ISSUE TITLE
show_close_tab_button_in_tabs not work

### ISSUE THREAD

**Issue by hyawara** [wez/wezterm#5956]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

windows 11

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

![image](https://github.com/user-attachments/assets/441cae13-4dcd-4cf6-a7e6-1dcb727e9066)
![image](https://github.com/user-attachments/assets/eb212e5e-12ba-456b-a829-123bc1bc8568)

I set this property but it doesn t take effect the picture above is my configuration

### Configuration

![image](https://github.com/user-attachments/assets/441cae13-4dcd-4cf6-a7e6-1dcb727e9066)
![image](https://github.com/user-attachments/assets/eb212e5e-12ba-456b-a829-123bc1bc8568)

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/config/show_close_tab_button_in_tabs.html indicates that this feature is available only in nightly builds, and you are not running a nightly build
