### ISSUE TITLE
Invalid reported terminal size at startup

### ISSUE THREAD

**Issue by SkwalExe** [wez/wezterm#5958]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

My .zshrc adds some nice eye candy when I open a shell session, running fastfetch. It works perfectly across all terminals I've used so far. Recently, I switched to WezTerm, and I'm really enjoying it! But I've run into a minor issue.

It seems like the terminal size reported to programs is incorrect for the first second after startup. This causes fastfetch to truncate its output to fit the wrong detected size. If I add a sleep 1 command before running fastfetch in my `.zshrc`, it gives enough time for the correct size to be reported, and the problem goes away. I know the size is incorrect because if I add `tput cols` at the beginning of my `.zshrc`, it always returns `80`, even when the terminal opens full-screen, etc.

I realize I can adjust the `initial_cols` and `initial_rows` parameters in WezTerm, but that’s not a real solution since the actual terminal size isn’t predictable. If `initial_cols` is too small, the output gets truncated, and if it’s too large, lines get awkwardly wrapped.

Other terminals report the correct size right at startup. Is there any way to fix this in WezTerm?

![image](https://github.com/user-attachments/assets/07b5f824-ed91-4ca9-b3d9-373bc6283aa6)

### To Reproduce

1. In `.bashrc` add `tput cols` at the beginning.
2. Run `bash` with wezterm, and see the wrong terminal size detected.

### Configuration

```lua
local wezterm = require 'wezterm'
local act = wezterm.action
local config = {}

config.color_scheme = 'Cloud (terminal.sexy)'

-- Terminal Font
config.font = wezterm.font 'JetBrains Mono'

-- Window padding
local wp = 25
config.window_padding = {
    left = wp,
    right = wp,
    top = wp,
    bottom = wp,
}

-- Background opacity
config.window_background_opacity = 0.5

-- Start tmux on new session
---------- This is not a problem with tmux, I have the same issue when changing this line to `zsh`
config.default_prog = { 'tmux' }

-- Hide the tab bar
config.enable_tab_bar = false

return config
```

### Expected Behavior

WezTerm should retrieve and report the correct terminal size before starting a shell session.

### Anything else?

This may be related to #695

**Comment by wez** [comment]
Your tiling window manager is racing to resize the window while your shell startup is racing to query its size.
You can add a short sleep before running your fetch program to resolve the race.
