### ISSUE TITLE
Mouse events show up as characters in the terminal instead of being handled

### ISSUE THREAD

**Issue by knl** [wez/wezterm#5993]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I have been noticing this bug for a while. I have long running ssh sessions (using regular ssh, not the one integrated in wezterm) when I'm at work. Then, I close my laptop, and head to the train station. When I board the train, I open the laptop and it tethers with my phone. Naturally, this causes the ssh connection to break, so I redo ssh to the same host. This is when the issue start.

If I try to scroll up/down via the trackpad on Mac (two finger scroll) instead of scrolling, the current line fills with symbols like:

```
`B`B`BBaBaBa
```

The worst is, I can't even select the text with the mouse (as I'm used to), as that just emits:

```
 U#U
```

### Configuration

My config is here: https://github.com/knl/dotskel/tree/main/configs/wezterm/config

### Logs

17:37:23.682 ERROR termwiz::escape::parser > impossible C0/C1 control code '\u{80}' 0x80 was dropped
17:37:23.876 ERROR termwiz::escape::parser > impossible C0/C1 control code '\u{80}' 0x80 was dropped
17:39:44.455 WARN wezterm_gui::tabbar > format-tab-title: runtime error: ...rs/nknezevi1/.config/wezterm/events/format-tab-title.lua:63: attempt to index a nil value (global 'wezterm')
stack traceback:
        [C]: in metamethod 'index'
        ...rs/nknezevi1/.config/wezterm/events/format-tab-title.lua:63: in function <...rs/nknezevi1/.config/wezterm/events/format-tab-title.lua:9>

**Comment by wez** [comment]
Mouse events remain on until turned off by the application.
You can use the command palette to reset the terminal emulator state to recover from this.
It is not a bug in wezterm; the same would apply to any terminal.

**Comment by tot-ra** [comment]
@wez can you elaborate on `command palette to reset the terminal emulator` ?
I also have issue with mouse events generating characters sometimes, maybe after mac goes to sleep.
And yes, I had same issues sometimes in iTerm.
It disappears on new tab.

https://github.com/user-attachments/assets/de65ce93-c69b-4d55-af02-c9d0685836b2

My wezterm config - https://github.com/tot-ra/workstation/blob/main/.config/wezterm/wezterm.lua

**Comment by tot-ra** [comment]
Running `reset` command helps
