### ISSUE TITLE
add option for focus to follow mouse when using multiple panes

### ISSUE THREAD

**Issue by junguler** [wez/wezterm#600]
please add the option for focus to follow mouse when using multiple panes, i only need this behavior in my terminal emulator so setting it os wide is no ideal.

thank you for your amazing project, it's exactly what i needed as alacritty doesn't support tabs/panes and kitty doesn't let me use custom mouse key-binds.

**Comment by wez** [comment]
https://github.com/wez/wezterm/commit/d705886b53101d408c3cc022809d278c8e79b1d9#diff-cd65356612d630f0423fef99fdb3564ba5925eca46ecbb4c7b8d291efc2aad64 has the docs for this option; you can find it in the next nightly build (~30 minutes from now)

**Comment by junguler** [comment]
amazing work, thank you.
