### ISSUE TITLE
macos modifier normalization issue

### ISSUE THREAD

**Issue by manithree** [wez/wezterm#601]
## Describe the bug

In linux (awesomewm, dunno if that's required, tho) the SUPER+SHIFT+[ and SUPER+SHIFT+] default keybindings don't work as documented.

## Environment (please complete the following information):

 - OS: Fedora 33, X11, awesomewm
 - Version: please run `wezterm -V` and include its output here
 - wezterm 20210314-114017-04b7cedd-119-gd45bbed3
 - The active keyboard layout name
 - localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us

## To Reproduce

Run wezterm, create some tabs, hit SHIFT+SUPER+[ or SHIFT+SUPER+]

## Configuration

default configuration from fedora rpm

## Expected behavior
I expected the keys to change the active tab. Instead { or } get sent to the program running in the current tab

## Additional context

From matrix/element:
Anybody using wezterm in Awesomewm? A WHOLE bunch of the default keybindings don't work for me, and I'm wondering if that's my issue. I can't get any ActivateTab or ActivateTabRelative keybindings (even the ones that don't seem to overlap with awesome bindings) to work.

wez
manithree: I'd suggest running wezterm --config debug_key_events=true to launch a wezterm that will log key events to stderr to see if the WM is letting them get to wezterm. Almost all of the key assignments are mapped to both SUPER+<something> and CTRL+SHIFT+<something> which should give you a couple of options to get them to trigger. Mutter/gnome swallows the SUPER assignments for me, and Windows swallows those under Windows, so I use the CTRL+SHIFT variant on those systems
manithree
2021-04-01T01:34:01.892Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('{'), modifiers: SUPER, raw_key: None, raw_modifiers: SHIFT | SUPER, raw_code: Some(34), repeat_count: 1, key_is_down: true }
 2021-04-01T01:34:02.292Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('}'), modifiers: SUPER, raw_key: None, raw_modifiers: SHIFT | SUPER, raw_code: Some(35), repeat_count: 1, key_is_down: true }
I get { and } on the CLI instead of what I was expecting (changing tabs).
wez
hmm, I think that might be a SHIFT normalization problem. Can you try adding {key="{", mods="SUPER", action=wezterm.action{ActivateTabRelative=-1}}, and the equivalent for } ?
in the code that key is registered as SUPER+SHIFT+{  but it looks like the shift is normalizing away and so the key event isn't matching.  That key assignment works on macOs, so this might be a linux specific shift state normalization problem
manithree
With     {key="{", mods="SUPER", action=wezterm.action{ActivateTabRelative=-1}},
    {key="}", mods="SUPER", action=wezterm.action{ActivateTabRelative=1}},
in my config, it works as I was expecting. Thanks!

**Comment by manithree** [comment]
I can confirm that the issue exists in GNOME 38 on X11 and Wayland. It doesn't appear to be an awesomewm issue.

**Comment by wez** [comment]
it turns out that this was really an issue with macos.  I've tactically fixed the issue for this particular key assignment, but I think there may still be issues with eg: DEU where the unmodified and processed versions of `ü` appear to be flipped to me.

@mborejdo: I recall that you use DEU layout on windows, so I assume you are better versed in German than my basic understanding; this key event comes from pressing CMD+SHIFT+[ on a US physical keyboard set to DEU layout (on macOS).  My expectation is that `key` should report the uppercase `Ü` rather than the lowercase `ü`; it seems to me that the `raw_key` and `key` values are swapped?

```
    key_event KeyEvent { key: Char('ü'), modifiers: NONE,
            raw_key: Some(Char('Ü')),
            raw_modifiers: SHIFT | SUPER,
            raw_code: Some(33),
            repeat_count: 1, key_is_down: true }
```

**Comment by mborejdo** [comment]
@wez I am not usre I understand the question. 

This is what I see on windows, using the dedicated Ü-Key:
```
2021-04-03T13:48:18.621Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('ü'), modifiers: NONE, raw_key: None, raw_modifiers: NONE, raw_code: Some(186), repeat_count: 1, key_is_down: true }
2021-04-03T13:48:22.155Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('Ü'), modifiers: SHIFT, raw_key: None, raw_modifiers: SHIFT, raw_code: Some(186), repeat_count: 1, key_is_down: true }
```

**Comment by wez** [comment]
Thanks to the groundwork laid in https://github.com/wez/wezterm/issues/1483 I just pushed a commit that fixes this issue for me.  It will show up in the nightly downloads within an hour.
