### ISSUE TITLE
pane:get_foreground_process_info() return nil in multiplexing or ssh mode

### ISSUE THREAD

**Issue by gauthierc** [wez/wezterm#6027]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland 0.42.0

### WezTerm version

20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The result of the function pane:get_foreground_process_info() is different in multiplexing or ssh mode than in local mode.
It is not possible to retrieve information about the process running in the pane in multiplexing mode.

### To Reproduce

To reproduce the bug, display the process name in the right bar and note that it does not appear in multiplexing mode.
❯ wezterm-mux-server --daemonize
❯ wezterm connect unix

### Configuration

local wezterm = require "wezterm"
local act = wezterm.action
return {
  hide_tab_bar_if_only_one_tab = false,
  check_for_updates = false,
  adjust_window_size_when_changing_font_size = false,
  unix_domains = {
    {
      name = 'unix',
    },
  },
  wezterm.on('update-right-status', function(window, pane)
    local info = pane:get_foreground_process_info()
    if info then
      window:set_right_status(
        tostring(info.name)
      )
    else
      window:set_right_status 'ERROR'
    end
  end)
}

### Logs

18:28:16.111  ERROR  wezterm_gui::termwindow         > while processing update-right-status event: pane id 0 not found in mux
stack traceback:
    [C]: in method 'get_foreground_process_info'
    [string "/home/gauthier/.config/wezterm/wezterm.lua"]:13: in function <[string "/home/gauthier/.config/wezterm/wezterm.lua"]:12>

**Comment by wez** [comment]
Working as documented and designed: https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_info.html
