### ISSUE TITLE
Unable to mux into WSL from windows, wezterm-mux-server seems to ignore all config options

### ISSUE THREAD

**Issue by gnur** [wez/wezterm#604]
## Describe the bug

No matter the combination of commandline flags and config files, the wezterm-mux-server always starts its socket at `~/.local/share/wezterm/sock`. 

## Environment (please complete the following information):

 - OS: windows 10 with wsl debian
 - Version: `wezterm 20210314-114017-04b7cedd-120-g217dbfb9`

## To Reproduce

Steps to reproduce the behavior.

Follow the docs on https://wezfurlong.org/wezterm/multiplexing.html#connecting-into-windows-subsystem-for-linux 

## Configuration

wsl config
```
erwin@ARGUO:~$ cat .config/wezterm/wezterm.lua
return {
  unix_domains = {
    {
      name = "wsl"
      -- Override the default path to match the default on the host win32
      -- filesystem.  This will allow the host to connect into the WSL
      -- container.
      socket_path = "/mnt/c/Users/Erwin/.local/share/wezterm/sock",
      -- NTFS permissions will always be "wrong", so skip that check
      skip_permissions_check = true,
    }
  }
}
```

windows side config:
```
local wezterm = require 'wezterm';
return {
  font = wezterm.font("Cascadia Code PL"),
  color_scheme = "N0tch2k",
  unix_domains = {
    {
      name = "wsl",
      connect_automatically = true,
      serve_command = {"wsl", "wezterm-mux-server", "--daemonize"},
    }
  }
}
```

## Expected behavior

Expect to get a wezterm window with a shell of my wsl debian install.

## Screenshots

```
erwin@ARGUO:~$ wezterm-mux-server --config-file .config/wezterm/wezterm.lua
 2021-04-01T08:34:35.331Z INFO  wezterm_mux_server_impl::local > setting up /home/erwin/.local/share/wezterm/soc
```

![2021-04-01 (2)](https://user-images.githubusercontent.com/722329/113266873-09ccb780-92d6-11eb-81e1-408fc404bf6b.png)

**Comment by wez** [comment]
inside wsl, please run:

```
WEZTERM_LOG=trace wezterm-mux-server 2> /tmp/server.txt
```

and attach `/tmp/server.txt` to this issue; that should show some diagnostics and help to understand what the server is up to.

**Comment by gnur** [comment]
[server.txt](https://github.com/wez/wezterm/files/6262865/server.txt)

I've added the server.txt file.

**Comment by markhagemann** [comment]
Your config is missing a `,` after `name = "wsl"`

**Comment by markhagemann** [comment]
![socket path](https://user-images.githubusercontent.com/21050889/118573767-8a803e00-b7c6-11eb-961c-2b52bdc7bd99.png)

Using the socket path provided in the wiki:

```
      socket_path = "/mnt/c/Users/mhagemann/.local/share/wezterm/sock",
```

The path is correct but the way it is forming it seems to be wrong with the alternating forward and back slashes?

**Comment by wez** [comment]
If you're using wsl2, then I don't think this will work using unix domain sockets: https://github.com/microsoft/WSL/issues/5961

**Comment by wez** [comment]
Please confirm whether you're running WSL 1 or WSL 2; WSL 2 doesn't currently support unix domain socket interop.
