### ISSUE TITLE
Option + Select does not work

### ISSUE THREAD

**Issue by konsalex** [wez/wezterm#6044]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

Just MacOS

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Lazydocker requires Option+Dragging to select the text to be copied. This works in iTerm but not in Wezterm

### To Reproduce

Run lazydocker and try to copy logs

### Configuration

no config

### Expected Behavior

Press option + drag the mouse cursor to copy the test

### Anything else?

![CleanShot 2024-08-27 at 09 18 28@2x](https://github.com/user-attachments/assets/0e3f5a8a-d03b-49f5-b626-df8db11cc848)

**Comment by bew** [comment]
Wezterm uses `Shift` by default to bypass mouse reporting, allowing you to select arbitrary text.

You can change it to `Option` if you want with the [`bypass_mouse_reporting_modifiers`](https://wezfurlong.org/wezterm/config/lua/config/bypass_mouse_reporting_modifiers.html) config ;)

Something like this in your own config should do the trick:
```lua
config.bypass_mouse_reporting_modifiers = "OPT"
```

**Comment by bew** [comment]
Does it also happen with default setting (using shift) ?

I don't know much about macOS so won't be able to help you on that.

**Comment by konsalex** [comment]
@bew yes it happens with the default

**Comment by wez** [comment]
if the region holding the selection is re-drawn by the application, the selection is cleared.
If the program you are using is constantly updating the output, you won't be able to select the text in that region until it stops (or you stop it using CTRL-S/CTRL-Q to stop/resume the program. Your stty settings control those key assignments).
