### ISSUE TITLE
Text appears below the last line when maximized

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#605]
## Describe the bug
Text appears and flickers below the last line of input, when the WezTerm window is maximized, and all rows of the terminal are filled up with text.

## Environment (please complete the following information):
 - OS: Linux X11
 - Version: wezterm 20210314-114017-04b7cedd-120-g217dbfb9
 - The active keyboard layout name ENG

## To Reproduce
Fill up all rows of the terminal with text until a scrollbar appears.

Scroll up and down with mouse. Text will flicker below the last line of input.

## Configuration
I'm using a 1920x1080 display.

```lua
    font = wezterm.font_with_fallback({
        'Noto Sans Mono',
        'Noto Sans Mono CJK SC',
        'Symbola',
    }),
    font_size = 10.0,
    line_height = 0.9,

    initial_rows = 60,
    initial_cols = 238,

    enable_scroll_bar = true,
```

## Expected behavior
Nothing appears below the line of input.

## Screenshots
![Screenshot_2021-04-01_19-59-44](https://user-images.githubusercontent.com/2058940/113270154-ebda7380-9324-11eb-9cd6-68b0c171ae0a.png)

## Session Recording
N/A

## Additional context
N/A

**Comment by jankatins** [comment]
I'm seeing the same.

**Comment by wez** [comment]
Probably the same underlying issue as https://github.com/wez/wezterm/issues/589
I've also seen this once, but I haven't been able to reproduce it on demand so far.

**Comment by mborejdo** [comment]
I am able to reproduce the "ghost text below last line" constantly on windows, once the scrollbackbuffer gets long, then these artifacts show
