### ISSUE TITLE
Error: The OpenGL implementation is too old to work with glium

### ISSUE THREAD

**Issue by FrostyNick** [wez/wezterm#6053]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I try to run Wezterm, it doesn't run in any cases in this VM and I see this error everytime:

ERROR	wezterm_gui::frontend > Failed to create window: The OpenGL implementation is too old to work with glium

### To Reproduce

This is a fresh Windows 11 install inside QEMU virtual machine. I just run it in the terminal "wezterm" if scoop is installed or double click either wezterm-gui.exe or wezterm.exe directly and it doesn't run. Doesn't run in the background.

### Configuration

no config

### Expected Behavior

Should run

### Logs

ERROR	wezterm_gui::frontend > Failed to create window: The OpenGL implementation is too old to work with glium

### Anything else?

- Neovim 0.10.1, browsers and other programs I've installed seem to work fine so far, except for alacritty. Just once there was an error in alacritty that led me to install `scoop install vcredist` which didn't fix anything.
- I've tested this with wezterm, wezterm-nightly (using scoop) and manually installing the recent setup .exe file and a older .exe from 2022.. same result.

**Comment by loops** [comment]
As per bug #1813, can you try:

wezterm.exe --config "prefer_egl=true"

**Comment by FrostyNick** [comment]
Thanks, it does successfully launch with that config flag.
