### ISSUE TITLE
Ligatures stop rendering in (neo)vim with cursorcolumn set

### ISSUE THREAD

**Issue by thorerik** [wez/wezterm#6058]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When a cursor in neovim is in the same column as a ligature, the ligature stops rendering.
Example how it should look:
<img width="98" alt="image" src="https://github.com/user-attachments/assets/073e66b4-83fc-416c-a0d3-099d019c939d">

Example when cursor is in same column with cursorcolumn enabled:
<img width="69" alt="image" src="https://github.com/user-attachments/assets/6230aab5-1ee8-4e39-9534-4ce03f8cf5a0">

### To Reproduce

 1. Pick a font in wezterm that has ligatures, such as Cascadia Code.
 2. In your vim config or neovim init.vim add `set cursorcolumn`
 3. put your cursor in the same column as the ligature

### Configuration

init.vim: https://github.com/thorerik/dotFiles/blob/e0de7df35ac6b0cbaaf7df823e918bc1bed243d8/config/nvim/init.vim#L55-L56

wezterm.lua:
```lua
local wezterm = require 'wezterm'

local config = {}

config.font = wezterm.font {
    family = 'Cascadia Code NF',
    harfbuzz_features = {
        'liga=1',
        'zero=1',
        'ss02=1',
        'ss19=1'
    }
}

return config
```

**Comment by thorerik** [comment]
Neither kitty nor iterm2 does this though and as a user I would expect that behavior.

**Comment by wez** [comment]
Working as intended
