### ISSUE TITLE
current bash input mangled after pasting

### ISSUE THREAD

**Issue by antoson** [wez/wezterm#6064]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Sway v1.7

### WezTerm version

20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

when pasting a URL, the current bash command gets mangled, when adding more characters or moving cursor, after pasting. (see video 1)

other issue, which may or may not be related, is that the current bash command gets overwritten, including the prompt, when writing a multi-line command. (see video 2)

### To Reproduce

1. open new terminal window
2. paste any URL
3. continue adding input or press left or right arrow key
4. the current command gets mangled

### Configuration

```lua
local wezterm = require 'wezterm'

local config = wezterm.config_builder()

config.color_scheme = 'Tokyo Night'
config.font_size = 12.0
config.font = wezterm.font 'Comic Code'

config.audible_bell = 'Disabled'

config.enable_tab_bar = false

config.window_decorations = 'RESIZE'

config.window_background_opacity = 0.95

return config
```

### Logs

Debug Overlay
wezterm version: 20240812-215703-30345b36 x86_64-unknown-linux-gnu
Window Environment: Wayland
Lua Version: Lua 5.4
OpenGL: Mesa Intel(R) UHD Graphics 630 (CFL GT2) 4.6 (Compatibility Profile) Mesa 22.3.6
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>

### Anything else?

The problem only occurs when pasting a URL, not regular text.

https://github.com/user-attachments/assets/fd3e3efb-dab6-4eae-8bf2-c4b969c1068f

https://github.com/user-attachments/assets/2bba35a7-eab5-4703-aa09-1eed244af5f0

<details>
<summary>my .bashrc</summary>

```bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=9000
HISTFILESIZE=9000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# XDG
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}"
export XDG_CONFIG_DIRS="${XDG_CONFIG_DIRS:-/etc/xdg}"

# ENV vars
export EDITOR=nvim
export VISUAL=nvim
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export GOPATH="$HOME/.go"
export PATH="$PATH:$GOPATH/bin"
export PS1="\e[1;34m\u@\h:\w\$\e[m "

# Aliases
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

bind 'set completion-ignore-case on'

eval $(keychain --eval --quiet [redacted])

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

. "$HOME/.cargo/env"

/usr/games/fortune -s | cowsay
echo ""
```

</details>

OS: Debian 12
shell: GNU bash, version 5.2.15(1)-release

I really like wezterm, thank you for your work. Please let me know if I made a mistake in the bug report, if it's user error, or if you need more information :blush: .

**Comment by antoson** [comment]
I tried pasting non-URL and it also made the problem occur. Could it be caused by pasting content with trailing newline?

I also noticed that after the mangling, the pasted content cannot be deleted (visible in the 5th bash command in the video).


https://github.com/user-attachments/assets/4bbe9e24-a3ae-468b-b493-ee2d7a00b29c

**Comment by loops** [comment]
Hi Antoson,

Is there any chance you could apply the single commit from this PR:   https://github.com/wez/wezterm/pull/5981

And see if the problem persists??

**Comment by antoson** [comment]
Hi Sean,
thanks for your assistance.

I applied #5981 and both issues persist.

I also tried running wezterm without config `cargo run --release --bin wezterm -- --skip-config start`, both issues persist.

Then I tried reproducing this in foot terminal, and it has the same problem. Could it be unrelated to wezterm and caused by bash/readline/wayland or something else?


https://github.com/user-attachments/assets/5b83f670-877a-4df9-90ea-4ad593d69508

**Comment by loops** [comment]
Yeah, that's pretty conclusively not a Wezterm issue then.  It would be nice to understand where the problem is creeping in though.  Could it be that there are some stray characters in the prompt?   perhaps try setting  the PS1 variable and see if that affects the problem:    PS1=@

Otherwise, digging into readline would seem the place to start, perhaps temporarily setting the following variables in your ~/.inputrc and restarting bash, might reveal some info:

     set enable-bracketed-paste off
     set enable-active-region off

**Comment by antoson** [comment]
Both issues were caused by unescaped color sequences in my prompt:
`export PS1="\e[1;34m\u@\h:\w\$\e[0m "`
fixed by wrapping color sequences in `\[ ... \]` like this:
`export PS1="\[\e[1;34m\]\u@\h:\w\$\[\e[0m\] "`

Thanks for your time Sean, have a good day :)
