### ISSUE TITLE
Running exa display wrong icon size

### ISSUE THREAD

**Issue by Armaldio** [wez/wezterm#607]
## Describe the bug

When running `exa --icons`, the icons are too big.

## Environment (please complete the following information):

 - OS: Manjaro/Arch
 - Version: 20210314-114017-04b7cedd
 - FR

## To Reproduce

`exa --icons`

Fonts come from [nerd-fonts](https://www.nerdfonts.com/)
[exa](https://github.com/ogham/exa)

## Configuration

Dracula theme, that's all

## Expected behavior
Icons to be sized correctly

## Screenshots

![image](https://user-images.githubusercontent.com/3089715/113290166-86b95a80-92f1-11eb-98d4-0542127d6578.png)

## Additional context

Terminal looks great :clap:

**Comment by wez** [comment]
Please try a nightly build?  There have been some adjustments that might help with this

**Comment by Armaldio** [comment]
Clearly better, but still to big
Wezterm on the right
![image](https://user-images.githubusercontent.com/3089715/113326071-82089c80-9319-11eb-9ce0-4b8b29828d13.png)

**Comment by wez** [comment]
OK, you can control that via https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html

Try: `wezterm --config 'allow_square_glyphs_to_overflow_width="Never"'`

**Comment by Armaldio** [comment]
Oops

![image](https://user-images.githubusercontent.com/3089715/113328304-6783f280-931c-11eb-8695-b78f236ad330.png)

**Comment by wez** [comment]
Alright, sounds like I'll need to dig into this a bit more! :)

**Comment by wez** [comment]
Can you tell me exactly which font you are using?  I couldn't reproduce this with `Inconsolata Nerd Font Complete Mono.otf
`

**Comment by Armaldio** [comment]
Could you tell me how to get the default font used by wezterm ?

It seems that if I change manually the font to the same one as on my previous terminal, the size of the icons is correct
```
font = wezterm.font("JetBrainsMono Nerd Font Mono"),
```

**Comment by wez** [comment]
If you go back to the configuration where the icons have the wrong size, please then run:

```
WEZTERM_LOG=wezterm_font=trace wezterm 2> /tmp/wezterm.txt
```

and trigger the display of the wrong icon size.  Then attach `/tmp/wezterm.txt` to this issue.

That should include diagnostics that will tell me which font file is in use.  I suspect that font-config on your system is providing a fallback font for those icons.  That in itself should be fine, but I suspect that whatever font that is has
something confusing in its font metrics that results in the weird size.

**Comment by Armaldio** [comment]
Here it is:
[wezterm.txt](https://github.com/wez/wezterm/files/6248145/wezterm.txt)

**Comment by wez** [comment]
Thanks for that; I can't directly reproduce this because I can't replicate your local font-config and installed fonts.  I think I know which bit of code is involved so I've added some improved diagnostics.  If you wouldn't mind repeating that same scenario with the next nightly build (in about an hour from now), that might help me nail this issue.

In the meantime, directly specifying the nerd font should get things working for you if you'd rather just get on with using the terminal!

**Comment by Armaldio** [comment]
Sorry for the delay !

[wezterm.txt](https://github.com/wez/wezterm/files/6262841/wezterm.txt)

**Comment by wez** [comment]
I believe that this issue is the same as https://github.com/wez/wezterm/issues/624 and some progress has been made over there on making this better.  Please try the current nightly build and see let me know how it goes!

**Comment by Armaldio** [comment]
Doesn't seems to help unfortunately

Built from sources
[wezterm.txt](https://github.com/wez/wezterm/files/6312818/wezterm.txt)

**Comment by wez** [comment]
@Armaldio looks like it is selecting this font for those glyphs:

```
2021-04-14T18:02:19.161Z TRACE wezterm_font                       > Fallback fonts that match \u{f115} before sorting are: [
    ParsedFont {
        names: Names {
            full_name: "FontAwesome Regular",
            family: "FontAwesome",
            sub_family: Some(
                "Regular",
            ),
            postscript_name: Some(
                "FontAwesome",
            ),
        },
        weight: Regular,
        stretch: Normal,
        italic: false,
        handle: FontDataHandle {
            source: OnDisk {
                path: "/usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.ttf",
            },
            index: 0,
            variation: 0,
            origin: FontConfig,
        },
        cap_height: None,
    },
```

That font doesn't have `cap_height` specified, so the glyph appears over-sized.

`JetBrainsMono Nerd Font Mono` does have cap_height set so you could use that font as your primary if you wish,
but if you'd like to be able to use any font and have the nerd font icons as a fallback, I'd suggest that you obtain this font:

https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-2048-em%20Nerd%20Font%20Complete.ttf

which is just the nerd font symbols, and then you can use a config like this:

```lua
  font = wezterm.font_with_fallback({"JetBrains Mono", "Symbols"}),
```

If you don't want to install that font system wide, you can put it in eg: `~/.fonts` then tell wezterm to look there:

```lua
  -- assuming that your config file is at ~/.wezterm.lua, `.fonts` resolves to `~/.fonts`
  font_dirs = ".fonts",
```
