### ISSUE TITLE
wezterm does not open a bash interactive shell by default at startup

### ISSUE THREAD

**Issue by giulianopz** [wez/wezterm#6072]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Xorg

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

wezterm should open a login shell by default, as said in the doc: https://wezfurlong.org/wezterm/config/launch.html#launching-programs
But this just does not happen: when I launch wezterm, `.bashrc` is not sourced.

### To Reproduce

Install the above-said version on Debian:
`sudo apt install -f ./wezterm-20240203-110809-5046fc22.Debian12.deb`

Then, just launch wezterm and try to use an alias or a function declared in .bashrc.

### Configuration

no config, but I tried also changing the default config as suggested [here](https://wezfurlong.org/wezterm/config/launch.html#changing-the-default-program).

### Expected Behavior

When I launch wezterm, I want to be in a login shell. This is what happen when GNOME terminal, konsole, contour, etc.

### Anything else?

The issue https://github.com/wez/wezterm/issues/4914 should be probably reopened.

**Comment by loops** [comment]
Hi giulianopz,

You seem to have misread the Bash documentation, as .bashrc  is only read for NON-login shells.  From the Bash
documentation:

  "When an interactive shell that is NOT a login shell is started, bash reads and executes commands
   from ~/.bashrc, if that file exists.  This may be inhibited by using the --norc option."

If you can confirm that is indeed the case, please close this bug report.

**Comment by giulianopz** [comment]
Hi @loops ,

yeah, you are right: I got confused mistaking "login shell" for "interactive shell".

Creating a config file (`.config/wezterm/wezterm.lua`) where  bash is launched as an interactive shell fixed my problem:
` config.default_prog = { 'bash', '-i' }`

But, why does this happen? I don't need any configuration with contour or other TEs to launch bash in this mode.
Shouldn't it be the default also for wezterm?

**Comment by loops** [comment]
Hey giulianopz,

Your fix works, because that means that bash is no longer being launched as a login shell   (so .bashrc will be read).

It seems some TEs have this default, and some don't.  You can read this short message from Wez, about why Wezterm works the way it does:   https://github.com/wez/wezterm/discussions/4544#discussioncomment-7500394

Fortunately, you have a solution that works!
Cheers

**Comment by giulianopz** [comment]
> Hey giulianopz,
> 
> Your fix works, because that means that bash is no longer being launched as a login shell (so .bashrc will be read).
> 
> It seems some TEs have this default, and some don't. You can read this short message from Wez, about why Wezterm works the way it does: [#4544 (comment)](https://github.com/wez/wezterm/discussions/4544#discussioncomment-7500394)
> 
> Fortunately, you have a solution that works! Cheers

Thanks for pointing me to that comment of Wez. I will close this issue since this seems to be the intended behavior.
