### ISSUE TITLE
wezterm not getting recognized by yabai

### ISSUE THREAD

**Issue by AlJohri** [wez/wezterm#6075]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

```
❯ yabai --version
yabai-v7.1.2
```

### WezTerm version

20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When running `wezterm` with yabai and opening the application via the CLI by typing `wezterm`, it sometimes doesn't get recognized as an application with a window in yabai.

https://github.com/user-attachments/assets/c6e51752-0cb2-4229-aa76-00582f6c9f40

### To Reproduce

To reproduce, just run `wezterm` in any other Terminal to open up Wezterm and within 1 or 2 tries you will likely see the issue.

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This will hold the configuration.
local config = wezterm.config_builder()

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.color_scheme = 'Catppuccin Frappe'
config.window_close_confirmation = 'NeverPrompt'
-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

I expect it to get tiled like any other window regardless of how the application is opened (via CLI or Spotlight/GUI).

### Anything else?

Running this command, I see the following entries for `wezterm` after opening and closing it:

```
while true; do yabai -m query --windows | jq '.[] | {app, title, role, subrole}'; echo "-----"; sleep 1; done
```

```
{
  "app": "wezterm-gui",
  "title": "zsh",
  "role": "AXWindow",
  "subrole": "AXStandardWindow"
}
```

```
{
  "app": "wezterm-gui",
  "title": "",
  "role": "",
  "subrole": ""
}
```

Anecdotally, as you may also be able to see in the video, it seems like when yabai didn't "catch" the window, the title/role/subrole are empty.

**Comment by loops** [comment]
This sounds like a bug in Yabai, since there are a few other programs that also exhibit the same issue with Yabai.   I see that you found a workaround, to make it work.  Do you still think there is something wrong with Wezterm, or are you going to close this issue?

**Comment by wez** [comment]
Not a wezterm issue
