### ISSUE TITLE
delay when closing shell before closing terminal

### ISSUE THREAD

**Issue by umanwizard** [wez/wezterm#608]
## Describe the bug

when I close the shell (using ^D), there is sometimes a delay, seems like about several hundred ms, before the terminal window is closed.

## Environment (please complete the following information):

 - OS: Ubuntu 20.10
 - Version: wezterm 20210314-114017-04b7cedd-119-gd45bbed3
- The active keyboard layout name: (I don't know what this is. I use a typical en_US keyboard and default bindings in wezterm).

## To Reproduce

open wezterm, hit ^D.

## Configuration

none

## Expected behavior

Terminal window should close instantly
## Additional context

Shell is zsh with prezto

**Comment by umanwizard** [comment]
Screencast comparing wezterm to gnome-terminal:


https://user-images.githubusercontent.com/1893159/113296502-8efca000-92c7-11eb-9071-2eb2a53694f3.mp4

**Comment by zhou13** [comment]
I have the same problem.

**Comment by wez** [comment]
Have you considered setting [exit_behavior = "Close"](https://wezfurlong.org/wezterm/config/lua/config/exit_behavior.html)?
The default behavior is to consider the exit status and defer pane closure until after EOF is detected.  If you want to optimize the close performance, then you can disable that functionality.

**Comment by zhou13** [comment]
The `exit_behavior` setting works for me. Thank you!
