### ISSUE TITLE
"Command not found: --" and "Bad assignment" errors.

### ISSUE THREAD

**Issue by politicus** [wez/wezterm#6085]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

On a fresh Wezterm install via Homebrew. I wanted to change my key bindings. 

I opened my ~/.wezterm.lua file, added a few new settings copied from the Wezterm documemtation. 
I sourced the settings file using source ~/.wezterm.lua. From there, I always got two errors: 

/Users/Uesss/.wezterm.lua:1: command not found: --
/Users/Uesss/.wezterm.lua:2: bad assignment

I uninstalled wezterm and reinstalled it via Homebrew. 

Got the same two error messages after sourcing my settings file.

### To Reproduce

Follow the steps above described.

### Configuration

Here is the content of my config file.

-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This will hold the configuration.
local config = wezterm.config_builder()

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.color_scheme = 'Aardvark Blue'

-- and finally, return the configuration to wezterm

return config

### Expected Behavior

(New shell user) I expected no error. 
Made sure Lua is install on my Mac .

### Logs

wezterm version: 20240203-110809-5046fc22 aarch64-apple-darwin
Window Environment: macOS 14.6.1 (23G93)
Lua Version: Lua 5.4
OpenGL: Apple M2 Pro 4.1 

### Anything else?

No.

**Comment by loops** [comment]
Hello politicus,

You don't need to "source" your Wezterm configuration file.   It is written in Lua, and will just confuse your shell anyway (ie. the command not found error).   Instead, it will be automatically read when you start Wezterm.

But I don't use a Mac, and am not sure if ~/.wezterm.lua is the correct location.  If it doesn't seem to work, you could always pass it explicitly, when starting Wezterm: 

wezterm --config-file ~/.wezterm.lua

**Comment by neogeographica** [comment]
FWIW on macOS I use `.config/wezterm/wezterm.lua` for that file's location. The [docs indicate](https://wezfurlong.org/wezterm/config/files.html#configuration-files) tho that `$HOME/.wezterm.lua` should also work.

**Comment by politicus** [comment]
Thank you for your answers @loops @neogeographica. 

It feels like I chose to test my "shiny" new config with maybe the only command that would create a confusion in the mind of the newbie I am. 

I preferred asking a question now rather than waiting for months, adding more and more settings, and ending having to deal with a real problem 👍
