### ISSUE TITLE
`default_gui_startup_args` doesn't work with open-terminal-here helper

### ISSUE THREAD

**Issue by mahdi739** [wez/wezterm#6090]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Xfwm4 (on xfce)

### WezTerm version

20240203.110809.5046fc22-2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When I use the `open-terminal-here` helper file to run WezTerm, it ignores the arguments that I defined in the default_gui_startup_args config.

### To Reproduce

Instead of `wezterm` , run the command `open-wezterm-here`

### Configuration

```l
config.default_gui_startup_args = { 'start', '--position', '100,100' }
```

### Anything else?

I know the position can be set on the `gui-startup` callback but I thought1 it could be a more general problem.

---

I checked the file open-wezterm-here and it is like this:
```
#!/bin/sh
# This script is a helper that starts a new terminal window
# in the cwd of the calling process, rather than using the
# default cwd which is usually the home directory.
exec $(wezterm start --cwd "$PWD" -- "$@")
```
I'm learning bash, is it because `--` after the arguments? So it doesn't parse the "$@" parameters as the wezterm arguments.

**Comment by loops** [comment]
Hey mahdi739,

The docs at https://wezfurlong.org/wezterm/config/lua/config/default_gui_startup_args.html mention:

     Specifying subcommand arguments on the command line is NOT additive with
     this config; the command line arguments always take precedence.

So the moment you give any sub commands, on the command line to wezterm, that config setting
is ignored.

And, you're correct about the "--" mark, it tells wezterm to stop looking for any more arguments,
and  consider everything that follows as part of the command to execute.

**Comment by mahdi739** [comment]
> Hey mahdi739,
> 
> The docs at https://wezfurlong.org/wezterm/config/lua/config/default_gui_startup_args.html mention:
> 
> ```
>  Specifying subcommand arguments on the command line is NOT additive with
>  this config; the command line arguments always take precedence.
> ```
> 
> So the moment you give any sub commands, on the command line to wezterm, that config setting is ignored.
> 
> And, you're correct about the "--" mark, it tells wezterm to stop looking for any more arguments, and consider everything that follows as part of the command to execute.


Thanks. I just thought maybe if the open-terminal-here script were written in a way that behaves almost the same as the wezterm command itself, it would be better. Otherwise, if it’s an intentional decision, it is not a bug.
