### ISSUE TITLE
Weird behaviour with the OPTION key.

### ISSUE THREAD

**Issue by politicus** [wez/wezterm#6092]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Can't write | using OPT+SHIFT+l keyboard shortcut. French keyboard. 
Can't write ~ using the OPT key.

Don't have any of these two problems in iTerm.

### To Reproduce

Hit  OPT+SHIFT+l keys (| is l).
Hit OPT+n keys

### Configuration

```
local wezterm = require 'wezterm'
local config = {}

config.font = wezterm.font 'JetBrains Mono'
config.color_scheme = 'Batman'

-- This will hold the configuration.
local 	config	= wezterm.config_builder()

config.font = wezterm.font("MesloLGS Nerd Font Mono")
config.font_size = 16

config.color_scheme = "Batman"

-- my coolnight colorscheme:
config.colors = {
	foreground = "#CBE0F0",
	background = "#011423",
	cursor_bg = "#47FF9C",
	cursor_border = "#47FF9C",
	cursor_fg = "#011423",
	selection_bg = "#033259",
	selection_fg = "#CBE0F0",
	ansi = { "#214969", "#E52E2E", "#44FFB1", "#FFE073", "#0FC5ED", "#a277ff", "#24EAF7", "#24EAF7" },
	brights = { "#214969", "#E52E2E", "#44FFB1", "#FFE073", "#A277FF", "#a277ff", "#24EAF7", "#24EAF7" },
}

-- Sets default folder to ~/Downloads:
config.default_cwd = wezterm.home_dir .. "/Downloads"

-- Key bindings:
local act = wezterm.action
config.keys = {
	{ mods = "OPT", key = "LeftArrow", action = act.SendKey({ mods = "ALT", key = "b" }) },
	{ mods = "OPT", key = "RightArrow", action = act.SendKey({ mods = "ALT", key = "f" }) },
	{ mods = "CMD", key = "LeftArrow", action = act.SendKey({ mods = "CTRL", key = "a" }) },
	{ mods = "CMD", key = "RightArrow", action = act.SendKey({ mods = "CTRL", key = "e" }) },
	{ mods = "CMD", key = "Backspace", action = act.SendKey({ mods = "CTRL", key = "u" }) },
	{ mods = "CMD|OPT", key = "LeftArrow", action = act.ActivateTabRelative(-1) },
	{ mods = "CMD|OPT", key = "RightArrow", action = act.ActivateTabRelative(1) },
	{ mods = "CMD|SHIFT", key = "LeftArrow", action = act.ActivateTabRelative(-1) },
	{ mods = "CMD|SHIFT", key = "RightArrow", action = act.ActivateTabRelative(1) },
}

return config
```

### Expected Behavior

-  A vertical bar like this | should be typed.
- A ~ should be typed.

### Logs

wezterm version: 20240203-110809-5046fc22 aarch64-apple-darwin
Window Environment: macOS 14.6.1 (23G93)
Lua Version: Lua 5.4
OpenGL: Apple M2 Pro 4.1

**Comment by neogeographica** [comment]
Did you try the right option key, or just the left option key? Cf. this: https://wezfurlong.org/wezterm/config/keyboard-concepts.html#macos-left-and-right-option-key

**Comment by politicus** [comment]
@neogeographica No. I didn't (for info, I could type "~" and "|" using the right alt/option key ).

Added this code to my settings:

```
config.send_composed_key_when_left_alt_is_pressed = true
config.send_composed_key_when_right_alt_is_pressed = true
```

And now it works !

Thank you!
