### ISSUE TITLE
wezterm ssh does not support ProxyUseFdPass

### ISSUE THREAD

**Issue by cpuguy83** [wez/wezterm#6093]
**Is your feature request related to a problem? Please describe.**

I use a custom proxy command to ssh into my machines to handle things like make sure the VPN is connected, make sure the machine is started, etc.
I always had some issues with the setup until I found `ProxyUseFdPass` in ssh.

`ProxyUseFdPass` tells ssh that the command is going to pass back a file descriptor to SSH to use rather than keeping the proxy command alive.
In this case stdout of the proxy process is wired up to a unix socket, which is used to pass back the file descriptor for the ssh connection.

Unfortunately the ssh implementation wezterm uses does not support this and even ignores the ssh config option erroring out with a message (after a long timeout it complains that the proxy process exited) that took me a bit to put the two things together.

**Describe the solution you'd like**

It would be great if wezterm ssh could support this option.

**Describe alternatives you've considered**

Only thing I can do here is go back to the more error prone case I had before using `ProxyUseFdPass`... or just not use wezterm's ssh implementation.

**Additional context**

**Comment by wez** [comment]
This is implemented in current nightly builds

**Comment by cpuguy83** [comment]
Thank you!
