### ISSUE TITLE
Scaling up and down will cause truncation

### ISSUE THREAD

**Issue by jutbin** [wez/wezterm#6096]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Scaling up and down will cause truncation
![image](https://github.com/user-attachments/assets/6ed8414c-bb9e-433f-8a5d-d58c8b1ba1f5)
![image](https://github.com/user-attachments/assets/f61e8cda-1f80-4281-9263-d115f6c09c91)

### Configuration

默认配置

**Comment by loops** [comment]
Hi jutbin,

    You mentioned using a "default" configuration.  Does that mean you didn't have a wezterm.lua file?

    Also, could you explain a little about what you expected to see, and what you saw instead?   Someone else
might understand just from your pictures, but I am not sure.

**Comment by jutbin** [comment]
![image](https://github.com/user-attachments/assets/813c6c67-d03a-4764-bd16-b390eae5acab)
![image](https://github.com/user-attachments/assets/f133328e-1345-435d-bc5f-956417c103cf)

like this

**Comment by jutbin** [comment]
Appears when the interface is scaled

**Comment by jutbin** [comment]
Not continuous

**Comment by jutbin** [comment]
I don't know if I made myself clear.

**Comment by jutbin** [comment]
yes ,  i didn't have a wezterm.lua file

**Comment by jutbin** [comment]
Normal should be like this
![image](https://github.com/user-attachments/assets/1da7018d-0b70-4fea-8b73-4d6d79d6065d)

**Comment by jutbin** [comment]
@loops

**Comment by wez** [comment]
I don't understand what the pictures are conveying. Did you blur one of them? Or are the square color regions the issue that you are reporting? If so, that sounds like a texture issue with the gpu/graphics drivers.
It might be worth trying the nightly build, and changing the https://wezfurlong.org/wezterm/config/lua/config/front_end.html configuration.

**Comment by jutbin** [comment]
@wez have the same problem with #5843

**Comment by wez** [comment]
I'm sorry, but that issue is also very unclear to me. Neither that or this one describe the actions taken, the effect that occurs or how it is different from your expectations. A static screen shot with no other commentary isn't sufficient for me to understand these things.
