### ISSUE TITLE
Terminal size of horizontal pane is too small for btop

### ISSUE THREAD

**Issue by ccaneke** [wez/wezterm#6101]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20240903_224638_b578d298

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

[btop](https://github.com/aristocratos/btop) is not displayed in a horizontal split pane due to the terminal size too small error.

### To Reproduce

* Install btop
* Create a horizontal split pane in wezterm
* Run btop

Result:
![Screenshot from 2024-09-07 21-13-29](https://github.com/user-attachments/assets/d93334e7-ee0c-42b0-a0b4-b2931675fad9)

### Configuration

-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This will hold the configuration.
local config = wezterm.config_builder()

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
-- config.color_scheme = 'Batman'

-- and finally, return the configuration to wezterm
return config

### Expected Behavior

wezterm should display btop in a horizontal split pane like in kitty below:
![Screenshot from 2024-09-07 21-12-54](https://github.com/user-attachments/assets/dfb63ec3-3557-488f-9e24-29ce9545fcbc)

**Comment by bew** [comment]
This message about terminal size is shown by btop, I'm not sure what wezterm can do about it..
To increase the number of visible cells you could try to reduce font size?

**Comment by ccaneke** [comment]
> This message about terminal size is shown by btop, I'm not sure what wezterm can do about it.. To increase the number of visible cells you could try to reduce font size?

Good point but why can't wez use a default terminal height of 24 and where it configured?

**Comment by bew** [comment]
Terminal height also depends on the used font, if you configure it wezterm to use the same font as kitty (which may have smaller line height?) you might get more cells 🤔
By default wezterm uses Jetbrains Mono (built-in font).

**Comment by ccaneke** [comment]
> Terminal height also depends on the used font, if you configure it wezterm to use the same font as kitty (which may have smaller line height?) you might get more cells 🤔 By default wezterm uses Jetbrains Mono (built-in font).

wezterms default font is much better than kitty's. I don't think that's an option. I guess this means btop will have to be in its own window

**Comment by wez** [comment]
You can also make your split taller by resizing it. I don't think there is anything to fix inside wezterm here, so I'm closing this out.
