### ISSUE TITLE
Window does not maximize

### ISSUE THREAD

**Issue by ccaneke** [wez/wezterm#6108]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20240903_224638_b578d298

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If you switch from another app to a minimised wezterm and then press the gnome shortcut keys to maximum a window, wezterm doesn't maximise. In order to maximise, you have to minimise and then maximise wezterm.

Result:
![Screenshot from 2024-09-08 21-36-35](https://github.com/user-attachments/assets/e2fe8a47-79d5-4a65-8180-ab3e073edadc)

### To Reproduce

* switch from another app to a minimised wezterm
* press the gnome shortcut keys to maximum wezterm, wezterm doesn't maximise
* in order to maximise wezterm, you must minimise and then maximise wezterm, i.e. Super+Down followed by Super+Up

### Configuration

If you switch from another app to a minimised wezterm and then press the gnome shortcut keys to maximum a window, wezterm doesn't maximise. In order to maximise, you have to minimise and then maximise wezterm.

### Expected Behavior

Wezterm should maximise

**Comment by aliaksandr-trush** [comment]
Fixed in https://github.com/wez/wezterm/pull/5897

**Comment by ccaneke** [comment]
Great. Closing.

**Comment by aliaksandr-trush** [comment]
But it's not merged yet :)
