### ISSUE TITLE
Character size changes depending on whether it is followed by another character

### ISSUE THREAD

**Issue by dhruvkb** [wez/wezterm#6119]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I have a Nerd Font character followed by some text. If there is a space after the character, it appears larger. If there isn't, it appears smaller.

### To Reproduce

- Enter a Nerd Font icon like "" (book, from the screenshot).
- Enter a space after the icon, see that its size does not change. Press <kbd>Backspace</kbd>.
- Enter a character after the icon like a period or a letter. See that the icon shrinks a little bit.

### Configuration

I am using the font families

```lua
config.font = wezterm.font_with_fallback({
  'Monaspace Neon',
  'Symbols Nerd Font',
})
```

### Expected Behavior

The character size should be the same regardless of whether it is followed by another character or space.

### Anything else?

<img width="1354" alt="Screenshot 2024-09-11 at 9 02 47 AM" src="https://github.com/user-attachments/assets/ee83ac59-58bc-4ba6-a1c3-bd254f755bec">

**Comment by bew** [comment]
You can change this default behavior using this config:
https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html

**Comment by dhruvkb** [comment]
Thank you @bew! This is exactly what I needed.
