### ISSUE TITLE
Relatively High Memory Usage

### ISSUE THREAD

**Issue by qingxiang-jia** [wez/wezterm#612]
## Describe the bug

I don't know if this counts as a bug because nothing really goes wrong.
1. Started with around 124 MB RSS.
2. `ls`  a directory with only ASCII characters, the RSS bumps to 135 MB.
3. `ls`  a directory with Non-ASCII characters, in my case, CJK characters, the RSS increases to 199 MB.
4. Opening a new tab and close the first one, the RSS doesn't go down.

Do the same with a similar terminal emulator (e.g. Kitty), the values are:
1. 107 MB.
2. 107 MB.
3. 113 MB.

## Environment (please complete the following information):

 - OS: Arch Linux X11
 - Version: wezterm 20210314-114017-04b7cedd
 - The active keyboard layout name: ENG

## To Reproduce

Please see the first section.

## Configuration

I am using the default configuration.

## Expected behavior
To be fair, the RAM usage isn't too drastic but it's about twice as the other GPU-based terminal emulator and is similar to the RAM usage of gnome-shell. It's a bit too much for me. But I do understand that these days this usage isn't a big deal. I guess it's caching the CJK glyphs but can we achieve that without less memory usage? Maybe this should be an enhancement.

**Great app, interesting project!** :tada:	:tada: :tada:

**Comment by wez** [comment]
Please try the nightly build and see also https://github.com/wez/wezterm/issues/559

**Comment by hasahmad** [comment]
I've just tried the latest nightly and it seems the RAM usage is much better (<100MB) than in the stable release (> 1GB) on my macOS. This is a significant difference.

**Comment by qingxiang-jia** [comment]
@wez Thanks for the help!

I just tried the latest nightly build on my machine and like @hasahmad said, the RAM usage is much reduced. For me, it was around 100 MB (start up with no operations) and 125 MB after several `cd` and `ls` with files that contains CJK characters. I consider this problem solved and I will close the issue.
