### ISSUE TITLE
3 minute startup time windows 11

### ISSUE THREAD

**Issue by AlexAvilov** [wez/wezterm#6120]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

No matter how I install, with installer or scoop, stable version or nightly build the startup time is 3 minutes. When I do trace I see 3 distinct places where app is timing out for 1 minute before continuing to the next startup step. Looking at trace I can't figure out what exactly wezterm is waiting for. My config is super simple, just font and theme. but i tried with the basic config from Getting Started page with the same result

In the trace below I copied only portion where it times out and marked the 1 min timeout (see time stamp) with
**<<------ 1 minute timeout**

I had zero issues with wezterm until i decided to reinstall windows. after fresh windows install I am having that issue. Would appreciate any pointers as I exhausted my search capabilities with zero relevant resalts

### Configuration

local wezterm = require 'wezterm'
wezterm.log_error 'Started config'
local mux = wezterm.mux
--front_end="OpenGL"

local config = wezterm.config_builder()

config.default_prog = { 'pwsh.exe' }
config.color_scheme = 'Kanagawa (Gogh)'
config.font = wezterm.font 'Maple Mono NF'

config.colors = {
  tab_bar = {
    -- The color of the inactive tab bar edge/divider
    inactive_tab_edge = '#575757',
  },
}

config.inactive_pane_hsb = {
  saturation = 0.6,
  brightness = 0.5,
}

config.hide_tab_bar_if_only_one_tab = true
config.use_fancy_tab_bar = false

config.font_size = 11.0

config.initial_cols = 143
config.initial_rows = 48

wezterm.log_error 'Ended config'

return config

### Logs

23:45:07.516  TRACE  config::config > consider config: C:\Users\alexa\scoop\apps\wezterm-nightly\current\wezterm.lua
23:45:07.517  TRACE  config::config > consider config: C:\Users\alexa\.wezterm.lua
23:45:07.518  ERROR  logging        > lua: Started config
23:45:07.559  ERROR  logging        > lua: Ended config
23:45:07.589  DEBUG  config         > Reloaded configuration! generation=1
23:45:07.595  TRACE  wezterm_gui    > Using configuration: ConfigHandle {
    config: Config {
..........

opts: Opt {
    skip_config: false,
    config_file: None,
    config_override: [],
    attach_parent_console: true,
    cmd: None,
}

**.<<<------- 1 minute timeout**

}

23:46:08.372  TRACE  wezterm_gui    > NoConnectButPublish
23:46:08.374  TRACE  config::config > Note: WEZTERM_CONFIG_FILE is set in the environment
23:46:08.375  TRACE  config::config > consider config: C:\Users\alexa\.wezterm.lua
23:46:08.375  ERROR  logging        > lua: Started config
23:46:08.412  ERROR  logging        > lua: Ended config
23:46:08.418  DEBUG  config         > Reloaded configuration! generation=2
23:46:08.420  TRACE  wezterm_mux_server_impl::local > setting up C:\Users\alexa\.local/share/wezterm\gui-sock-30260
23:46:08.422  DEBUG  wezterm_client::discovery::windows > published gui path as gui-sock-30260
23:46:08.424  DEBUG  wezterm_font::locator::gdi         > Maple Mono NF -> C:\WINDOWS\FONTS\MAPLEMONO-NF-REGULAR.TTF
23:46:08.425  DEBUG  wezterm_font::locator::gdi         > Got ParsedFont { names: Names { full_name: "Maple Mono NF Regular", family: "Maple Mono NF", sub_family: Some("Regular"), postscript_name: Some("MapleMono-NF-Regular"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "C:\\WINDOWS\\FONTS\\MAPLEMONO-NF-REGULAR.TTF" }, index: 0, variation: 0, origin: DirectWrite, coverage: None }, cap_height: Some(0.73), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } from dwrote
23:46:08.426  DEBUG  wezterm_font::locator::gdi         > dwrote couldn't resolve FontAttributes { family: "JetBrains Mono", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }
23:46:08.428  DEBUG  wezterm_font::locator::gdi         > Got ParsedFont { names: Names { full_name: "Courier New Regular", family: "Courier New", sub_family: Some("Regular"), postscript_name: Some("CourierNewPSMT"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: Memory { name: "JetBrains Mono", data_len: 828760 }, index: 0, variation: 0, origin: Gdi, coverage: None }, cap_height: Some(0.5712890625), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [4, 6, 7, 8, 8, 12, 12, 14, 15, 16, 17, 17, 18, 20, 20, 20, 22, 23], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } from gdi
23:46:08.428  DEBUG  wezterm_font::locator::gdi         > parsed ParsedFont { names: Names { full_name: "Courier New Regular", family: "Courier New", sub_family: Some("Regular"), postscript_name: Some("CourierNewPSMT"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: Memory { name: "JetBrains Mono", data_len: 828760 }, index: 0, variation: 0, origin: Gdi, coverage: None }, cap_height: Some(0.5712890625), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [4, 6, 7, 8, 8, 12, 12, 14, 15, 16, 17, 17, 18, 20, 20, 20, 22, 23], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } doesn't match FontAttributes { family: "JetBrains Mono", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }
23:46:08.429  DEBUG  wezterm_font::locator::gdi         > dwrote couldn't resolve FontAttributes { family: "Noto Color Emoji", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }
23:46:08.430  DEBUG  wezterm_font::locator::gdi         > Got ParsedFont { names: Names { full_name: "Courier New Regular", family: "Courier New", sub_family: Some("Regular"), postscript_name: Some("CourierNewPSMT"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: Memory { name: "Noto Color Emoji", data_len: 828760 }, index: 0, variation: 0, origin: Gdi, coverage: None }, cap_height: Some(0.5712890625), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [4, 6, 7, 8, 8, 12, 12, 14, 15, 16, 17, 17, 18, 20, 20, 20, 22, 23], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } from gdi
23:46:08.430  DEBUG  wezterm_font::locator::gdi         > parsed ParsedFont { names: Names { full_name: "Courier New Regular", family: "Courier New", sub_family: Some("Regular"), postscript_name: Some("CourierNewPSMT"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: Memory { name: "Noto Color Emoji", data_len: 828760 }, index: 0, variation: 0, origin: Gdi, coverage: None }, cap_height: Some(0.5712890625), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [4, 6, 7, 8, 8, 12, 12, 14, 15, 16, 17, 17, 18, 20, 20, 20, 22, 23], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } doesn't match FontAttributes { family: "Noto Color Emoji", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }
23:46:08.431  DEBUG  wezterm_font::locator::gdi         > Symbols Nerd Font Mono -> C:\WINDOWS\FONTS\SYMBOLSNERDFONTMONO-REGULAR.TTF
23:46:08.431  DEBUG  wezterm_font::locator::gdi         > Got ParsedFont { names: Names { full_name: "Symbols Nerd Font Mono Regular", family: "Symbols Nerd Font Mono", sub_family: Some("Regular"), postscript_name: Some("SymbolsNFM"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "C:\\WINDOWS\\FONTS\\SYMBOLSNERDFONTMONO-REGULAR.TTF" }, index: 0, variation: 0, origin: DirectWrite, coverage: None }, cap_height: None, synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } from dwrote
23:46:08.432  TRACE  wezterm_font::shaper::harfbuzz     > compute metrics across these handles for size=11, dpi=96,
             theoretical pixel height 14.666666666666666: [ParsedFont { names: Names { full_name: "Maple Mono NF Regular", family: "Maple Mono NF", sub_family: Some("Regular"), postscript_name: Some("MapleMono-NF-Regular"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "C:\\WINDOWS\\FONTS\\MAPLEMONO-NF-REGULAR.TTF" }, index: 0, variation: 0, origin: DirectWrite, coverage: None }, cap_height: Some(0.73), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }, ParsedFont { names: Names { full_name: "JetBrains Mono Regular", family: "JetBrains Mono", sub_family: Some("Regular"), postscript_name: Some("JetBrainsMono-Regular"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: BuiltIn { name: "../../assets/fonts/JetBrainsMono-Regular.ttf" }, index: 0, variation: 0, origin: BuiltIn, coverage: None }, cap_height: Some(0.73), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }, ParsedFont { names: Names { full_name: "Noto Color Emoji Regular", family: "Noto Color Emoji", sub_family: Some("Regular"), postscript_name: Some("NotoColorEmoji"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: BuiltIn { name: "../../assets/fonts/NotoColorEmoji.ttf" }, index: 0, variation: 0, origin: BuiltIn, coverage: None }, cap_height: Some(0.7001953125), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: true, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }, ParsedFont { names: Names { full_name: "Symbols Nerd Font Mono Regular", family: "Symbols Nerd Font Mono", sub_family: Some("Regular"), postscript_name: Some("SymbolsNFM"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "C:\\WINDOWS\\FONTS\\SYMBOLSNERDFONTMONO-REGULAR.TTF" }, index: 0, variation: 0, origin: DirectWrite, coverage: None }, cap_height: None, synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }]
23:46:08.432  TRACE  wezterm_font::shaper::harfbuzz     > shaper wants 0 ParsedFont { names: Names { full_name: "Maple Mono NF Regular", family: "Maple Mono NF", sub_family: Some("Regular"), postscript_name: Some("MapleMono-NF-Regular"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "C:\\WINDOWS\\FONTS\\MAPLEMONO-NF-REGULAR.TTF" }, index: 0, variation: 0, origin: DirectWrite, coverage: None }, cap_height: Some(0.73), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }
23:46:08.433  DEBUG  wezterm_font::ftwrap               > set_char_size computing 11 dpi=96 (pixel height=14.666666666666666)
23:46:08.434  TRACE  wezterm_font::shaper::harfbuzz     > idx 0 cell_height is 19.366779327392578, which is 4.700112660725912 away from theoretical
                     height (factor 0.32046222686767584). Seems good enough
23:46:08.434  TRACE  wezterm_font::shaper::harfbuzz     > metrics_for_idx=0, size=11, dpi=96 -> FontMetrics { cell_width: 9.0, cell_height: 19.366779327392578, descender: -5.0, underline_thickness: 0.7335901260375977, underline_position: -2.6409244537353516, cap_height_ratio: Some(0.4647133035315947), cap_height: Some(9.0), is_scaled: true, presentation: Text, force_y_adjust: 0.0 }

**<<------- 1 minute timeout**

23:47:09.322  TRACE  portable_pty::cmdbuilder           > adding SYS env: "ComSpec" "C:\\WINDOWS\\system32\\cmd.exe"
23:47:09.324  TRACE  portable_pty::cmdbuilder           > adding SYS env: "DriverData" "C:\\Windows\\System32\\Drivers\\DriverData"
23:47:09.325  TRACE  portable_pty::cmdbuilder           > adding SYS env: "OS" "Windows_NT"
23:47:09.326  TRACE  portable_pty::cmdbuilder           > adding SYS env: "Path" "C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PowerShell\\7-preview;C:\\Program Files\\Tailscale\\;C:\\Program Files\\dotnet\\"
23:47:09.326  TRACE  portable_pty::cmdbuilder           > adding SYS env: "PATHEXT" ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
23:47:09.327  TRACE  portable_pty::cmdbuilder           > adding SYS env: "PROCESSOR_ARCHITECTURE" "AMD64"
23:47:09.327  TRACE  portable_pty::cmdbuilder           > adding SYS env: "PSModulePath" "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules"
23:47:09.328  TRACE  portable_pty::cmdbuilder           > adding SYS env: "TEMP" "C:\\WINDOWS\\TEMP"
23:47:09.328  TRACE  portable_pty::cmdbuilder           > adding SYS env: "TMP" "C:\\WINDOWS\\TEMP"
23:47:09.329  TRACE  portable_pty::cmdbuilder           > adding SYS env: "windir" "C:\\WINDOWS"
23:47:09.329  TRACE  portable_pty::cmdbuilder           > adding SYS env: "NUMBER_OF_PROCESSORS" "32"
23:47:09.329  TRACE  portable_pty::cmdbuilder           > adding SYS env: "PROCESSOR_LEVEL" "6"
23:47:09.330  TRACE  portable_pty::cmdbuilder           > adding SYS env: "PROCESSOR_IDENTIFIER" "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel"
23:47:09.330  TRACE  portable_pty::cmdbuilder           > adding SYS env: "PROCESSOR_REVISION" "b701"
23:47:09.331  TRACE  portable_pty::cmdbuilder           > adding SYS env: "ZES_ENABLE_SYSMAN" "1"
23:47:09.331  TRACE  portable_pty::cmdbuilder           > adding SYS env: "POWERSHELL_DISTRIBUTION_CHANNEL" "MSI:Windows 10 Pro"
23:47:09.332  TRACE  portable_pty::cmdbuilder           > adding USER env: "Path" "C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PowerShell\\7-preview;C:\\Program Files\\Tailscale\\;C:\\Program Files\\dotnet\\;C:\\Users\\alexa\\scoop\\shims;C:\\Users\\alexa\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\alexa\\AppData\\Local\\Programs\\oh-my-posh\\bin"
23:47:09.332  TRACE  portable_pty::cmdbuilder           > adding USER env: "TEMP" "C:\\Users\\alexa\\AppData\\Local\\Temp"
23:47:09.333  TRACE  portable_pty::cmdbuilder           > adding USER env: "TMP" "C:\\Users\\alexa\\AppData\\Local\\Temp"
23:47:09.333  TRACE  portable_pty::cmdbuilder           > adding USER env: "OneDrive" "C:\\Users\\alexa\\OneDrive"
23:47:09.334  TRACE  portable_pty::cmdbuilder           > adding USER env: "RIPGREP_CONFIG_PATH" "C:\\Users\\alexa\\AppData\\Local\\ripgrep\\.ripgreprc"
23:47:09.334  TRACE  portable_pty::cmdbuilder           > adding USER env: "POSH_THEMES_PATH" "C:\\Users\\alexa\\AppData\\Local\\Programs\\oh-my-posh\\themes"
23:47:09.335  TRACE  portable_pty::cmdbuilder           > adding USER env: "POSH_INSTALLER" "scoop"

<<------ 1 minute timeout

23:48:10.184  DEBUG  wezterm_gui::frontend              > workspace is default, fixup windows
23:48:10.188  TRACE  wezterm_gui::frontend              > reconcile: windows -> {}
23:48:10.189  TRACE  mux::tab                           > prune_dead_panes: pane_id=0 dead=false in_mux=true
23:48:10.192  TRACE  mux                                > prune_dead_windows: not empty
23:48:10.195  TRACE  mux::tab                           > prune_dead_panes: pane_id=0 dead=false in_mux=true
23:48:10.196  TRACE  mux                                > prune_dead_windows: not empty
23:48:10.197  TRACE  wezterm_gui::frontend              > Creating TermWindow for mux_window_id=0
23:48:10.198  DEBUG  wezterm_font::locator::gdi         > Maple Mono NF -> C:\WINDOWS\FONTS\MAPLEMONO-NF-REGULAR.TTF
23:48:10.199  DEBUG  wezterm_font::locator::gdi         > Got ParsedFont { names: Names { full_name: "Maple Mono NF Regular", family: "Maple Mono NF", sub_family: Some("Regular"), postscript_name: Some("MapleMono-NF-Regular"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "C:\\WINDOWS\\FONTS\\MAPLEMONO-NF-REGULAR.TTF" }, index: 0, variation: 0, origin: DirectWrite, coverage: None }, cap_height: Some(0.73), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } from dwrote
23:48:10.199  DEBUG  wezterm_font::locator::gdi         > dwrote couldn't resolve FontAttributes { family: "JetBrains Mono", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }
23:48:10.200  DEBUG  wezterm_font::locator::gdi         > Got ParsedFont { names: Names { full_name: "Courier New Regular", family: "Courier New", sub_family: Some("Regular"), postscript_name: Some("CourierNewPSMT"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: Memory { name: "JetBrains Mono", data_len: 828760 }, index: 0, variation: 0, origin: Gdi, coverage: None }, cap_height: Some(0.5712890625), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [4, 6, 7, 8, 8, 12, 12, 14, 15, 16, 17, 17, 18, 20, 20, 20, 22, 23], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } from gdi
23:48:10.201  DEBUG  wezterm_font::locator::gdi         > parsed ParsedFont { names: Names { full_name: "Courier New Regular", family: "Courier New", sub_family: Some("Regular"), postscript_name: Some("CourierNewPSMT"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: Memory { name: "JetBrains Mono", data_len: 828760 }, index: 0, variation: 0, origin: Gdi, coverage: None }, cap_height: Some(0.5712890625), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [4, 6, 7, 8, 8, 12, 12, 14, 15, 16, 17, 17, 18, 20, 20, 20, 22, 23], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } doesn't match FontAttributes { family: "JetBrains Mono", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }
23:48:10.202  DEBUG  wezterm_font::locator::gdi         > dwrote couldn't resolve FontAttributes { family: "Noto Color Emoji", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }
23:48:10.202  DEBUG  wezterm_font::locator::gdi         > Got ParsedFont { names: Names { full_name: "Courier New Regular", family: "Courier New", sub_family: Some("Regular"), postscript_name: Some("CourierNewPSMT"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: Memory { name: "Noto Color Emoji", data_len: 828760 }, index: 0, variation: 0, origin: Gdi, coverage: None }, cap_height: Some(0.5712890625), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [4, 6, 7, 8, 8, 12, 12, 14, 15, 16, 17, 17, 18, 20, 20, 20, 22, 23], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } from gdi
23:48:10.203  DEBUG  wezterm_font::locator::gdi         > parsed ParsedFont { names: Names { full_name: "Courier New Regular", family: "Courier New", sub_family: Some("Regular"), postscript_name: Some("CourierNewPSMT"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: Memory { name: "Noto Color Emoji", data_len: 828760 }, index: 0, variation: 0, origin: Gdi, coverage: None }, cap_height: Some(0.5712890625), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [4, 6, 7, 8, 8, 12, 12, 14, 15, 16, 17, 17, 18, 20, 20, 20, 22, 23], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } doesn't match FontAttributes { family: "Noto Color Emoji", weight: FontWeight(400), stretch: Normal, style: Normal, is_fallback: true, is_synthetic: false, harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None, assume_emoji_presentation: None }
23:48:10.204  DEBUG  wezterm_font::locator::gdi         > Symbols Nerd Font Mono -> C:\WINDOWS\FONTS\SYMBOLSNERDFONTMONO-REGULAR.TTF
23:48:10.204  DEBUG  wezterm_font::locator::gdi         > Got ParsedFont { names: Names { full_name: "Symbols Nerd Font Mono Regular", family: "Symbols Nerd Font Mono", sub_family: Some("Regular"), postscript_name: Some("SymbolsNFM"), aliases: [] }, weight: FontWeight(400), stretch: Normal, style: Normal, handle: FontDataHandle { source: OnDisk { path: "C:\\WINDOWS\\FONTS\\SYMBOLSNERDFONTMONO-REGULAR.TTF" }, index: 0, variation: 0, origin: DirectWrite, coverage: None }, cap_height: None, synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None } from dwrote
23:48:10.205  TRACE  wezterm_font::shaper::harfbuzz     > compute metrics across these handles for size=11, dpi=96,
.........

### Anything else?

[wezterm-gui.exe-log-30260.txt](https://github.com/user-attachments/files/16957800/wezterm-gui.exe-log-30260.txt)

**Comment by wez** [comment]
If you run `wezterm ls-fonts` does that also take a long time to output anything?

**Comment by AlexAvilov** [comment]
Hi Wez, Thank you for checking my issue. If I run that command, the output is instantaneous

I did suspect that it might be related to fonts, so I checked that none of fonts is missing and i ran that command too

quick question, is there a problem that my fonts are installed system wide and not only for my user? I was thinking to try to reinstall fonts tomorrow

**Comment by AlexAvilov** [comment]
i am going to reinstall windows and am closing that issue as one off
