### ISSUE TITLE
Hangs when closing tabs on macOS (Big Sur 11.2.3, M1 Mac, Fish shell)

### ISSUE THREAD

**Issue by bjornlll** [wez/wezterm#613]
## Describe the bug

When I close a tab wezterm hangs. Symptoms include Apple's spinning beachball wezterm is marked "Not responding" in Activity Monitor.

## Environment (please complete the following information):

 - OS: macOS Big Sur 11.2.3
 - Version: macOS release version - downloaded today (Apr 2, 2020)
 - The active keyboard layout name: US English
 - Shell: Fish using OMF
 - Machine: M1 MBP, 16GB RAM, everything else standard

## To Reproduce

Steps to reproduce the behavior.

1. **Open wezterm**
2. **CMD+Y to open close tab prompt, or, CTRL+D to exit shell process**
3. **Press Y**
  This is is where it hangs. Not consistently but ~50% of the time

Edit: Had made an incorrect observation reg. how tabs are closed in (2) - corrected

**Comment by wez** [comment]
Please try the nightly build!

**Comment by bjornlll** [comment]
@wez works like a charm - thanks!

Out of curiosity: What was the underlying problem?

**Comment by wez** [comment]
It's something... fishy(!) with fish, but it was causing wezterm to wait forever: https://github.com/wez/wezterm/issues/558

**Comment by bjornlll** [comment]
Hehe wonderful. Thanks for helping out @wez !
