### ISSUE TITLE
wezterm ssh Exited with code 1.

### ISSUE THREAD

**Issue by jcyongqin** [wez/wezterm#6131]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

```
Using libssh-rs to connect to ABC@relay.ABC.com:22
Error: Connecting to relay.ABC.com:22: Fatal: kex error : no match for method server host key algo: server [ssh-rsa,ssh-dss], client [rsa-sha2-512,rsa-sha2-256,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com]

⚠️  Process RemoteSshDomain didn't exit cleanly
Exited with code 1.
This message is shown because exit_behavior="CloseOnCleanExit"
```

### Configuration

no config

### Logs

no log

**Comment by bew** [comment]
This error:
```
Error: Connecting to relay.ABC.com:22:
Fatal: kex error : 
no match for method server host key algo:
server [ssh-rsa,ssh-dss],
client [rsa-sha2-512,rsa-sha2-256,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com]
```
Means the server only supports security checks using ssh-rsa, or ssh-dss, which the client doesn't support.

The default ssh backend in wezterm is better suited for recent protocols.
If you need to connect to a server that only support older protocols, you can try to add this config:
```lua
config.ssh_backend = "Ssh2"
```
ref: https://wezfurlong.org/wezterm/config/lua/config/ssh_backend.html
