### ISSUE TITLE
Wide CJK chars have random 1px vertical splits in the middle

### ISSUE THREAD

**Issue by achimnol** [wez/wezterm#614]
## Describe the bug

Please check out the screenshot.
![image](https://user-images.githubusercontent.com/555156/113427905-d5a9e180-9410-11eb-8dae-0345df8dae82.png)

I suspect that this might be some floating-point errors when calculating the pixel coordinates of each character cells on the screen.

## Environment (please complete the following information):

 - OS: macOS
 - Version: wezterm 20210314-114017-04b7cedd-120-g217dbfb9
 - The active keyboard layout name (eg: ENG, DEU and so on): ENG

## To Reproduce

Just print some text that include Hangul (Korean) characters.

## Configuration

```lua
local wezterm = require 'wezterm';

return {
    use_ime = true,
    color_scheme = "Andromeda",
    font = wezterm.font_with_fallback({
        "JetBrains Mono",
        "Menlo",
        "NanumBarunGothic",
    }),
}
```
You can download the NanumBarunGothic font from [here](https://hangeul.naver.com/api/nanum/font/NanumFontSetup_TTF_BARUNGOTHIC.zip).
You can just copy-and-paste the following text into the terminal using any text editor, though the exact locations of 1px vertical splits may differ.

```text
> git st
현재 브랜치 20.09
브랜치가 'origin/20.09'에 맞게 업데이트된 상태입니다.

커밋할 변경 사항:
  (use "git restore --staged <file>..." to unstage)
        수정함:        CHANGELOG.md
        삭제함:        changes/416.fix
```

## Expected behavior
The wide CJK characters should have no 1px splits in the middle of them.

## Screenshots

It's already included above.

**Comment by wez** [comment]
This reproduces with the default configuration on macOS (no need to specify the the font you mentioned).

I agree: this looks like a floating point/rounding issue.  I haven't looked deep enough to know if this is happening during shaping (eg: a ligatured sequence composed of two glyphs with imprecise spacing), or during rendering (where we artificially slice a double-wide glyph across multiple cells).

You might find that tweaking the `font_size` and/or `dpi` values with precise fractional components (eg: `font_size = 11.9`) can help to produce cell widths that work out to be precise integer widths and that may help to workaround this.  It is a pain to have to do so; I only suggest this if you're motivated enough to want to find a workaround before I get a chance to dig in further.

Running `WEZTERM_LOG=wezterm_font=trace wezterm` will cause wezterm to output font related diagnostics to stderr and may help you to dial in those metrics if that is something you'd like to pursue.

**Comment by achimnol** [comment]
Changing font size and dpi didn't work for me.
After some observation, it continuously happens with a fixed set of specific characters instead of screen positions, meaning that glyph size calculation may be the source of problem.

![image](https://user-images.githubusercontent.com/555156/113467699-b9915900-947f-11eb-8265-8e69b28d987b.png)
Maybe this small screenshot would be help you to debug. The 1px vertical margin is included in the left-half cell.

**Comment by bew** [comment]
It may be related, using tmux I can see 1px vertical split between tmux's horizontal lines.
Tmux is using the char 0x2500 (─)

Here is an example:
![border](https://user-images.githubusercontent.com/9730330/113505088-fa9b7300-953c-11eb-91c9-796bd33cfd95.png)

OS: Linux X11 (Arch)

**Comment by wez** [comment]
> It may be related, using tmux I can see 1px vertical split between tmux's horizontal lines.
> Tmux is using the char 0x2500 (─)

That's a different issue: https://github.com/wez/wezterm/issues/584

**Comment by wez** [comment]
@achimnol I believe that I've fixed this in the nightly build, which should be ready to download within ~15 minutes from now!

**Comment by achimnol** [comment]
Yes, I confirm that it's fixed! 👍🏼 🙏🏼
