### ISSUE TITLE
Can't create local terminal window (like PS or cmd) if set the default_domain is wsl.

### ISSUE THREAD

**Issue by cg1937** [wez/wezterm#6147]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When the configuration sets default_domain = 'WSL:Ubuntu-22.04', using the shortcut (Ctrl+F6) to trigger the launcher interface to create PowerShell and CMD instances (in launch_menu config)does not successfully create the corresponding terminal windows. Instead, a tab quickly appears and then disappears. When I comment out the default_domain line and restart wezterm, this bug does not occur.

Additional information: I observed that the briefly appearing and disappearing tab has a title showing the string "wsl.exe". I suspect that the default_domain setting changes how wezterm opens local terminals, leading to the inability to create them properly.

### To Reproduce

same as "Describe the bug"

### Configuration

```lua
local wezterm = require("wezterm")
return {
  check_for_updates = false,
  keys = {
    { key = "F6", mods = "CTRL", action = wezterm.action.ShowLauncher },
  },
  launch_menu = {
    {
      label = "PowerShell",
      args = { "powershell.exe", "-NoLogo" },
    },
    {
      label = "CMD",
      args = { "cmd.exe", "-NoLogo" },
    },
  },
  default_domain = 'WSL:Ubuntu-22.04', --this line can toggle the bug
}
```

### Logs

This behavior cannot print any log in the log file.

**Comment by wez** [comment]
Take a look at: https://github.com/wez/wezterm/discussions/5421#discussioncomment-9434369
