### ISSUE TITLE
When non-English IME is active, keyboard shortcuts are also interpreted by IME

### ISSUE THREAD

**Issue by achimnol** [wez/wezterm#615]
## Describe the bug

*Regardless of* `use_ime` configuration, when the system IME switches to a non-English keyboard layout (e.g., [Korean Sebeolsik](https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:KB_Sebeolsik_Flnal.svg)), all keyboard shortcuts becomes unusable because IME intercepts them.

Maybe related with #318, though IME is highly platform-specific one.

## Environment (please complete the following information):

 - OS: macOS
 - Version: wezterm 20210314-114017-04b7cedd-120-g217dbfb9
 - The active keyboard layout name (eg: ENG, DEU and so on): ENG / Korean Sebeolsik

## To Reproduce

Switch the system IME to a non-English layout and try to use keyboard shortcuts that have different key mappings in that layout.
For example, Cmd+1 to switch to the first tab should work regardless of the IME state, but in the Korean Sebulsik (3-beolsik) layout, "1" becomes "ᇂ" and the shortcut does not work.

## Configuration

```lua
local wezterm = require 'wezterm';

return {
    use_ime = true,  -- the bug is reproducible with false as well!
    color_scheme = "Andromeda",
    font = wezterm.font_with_fallback({
        "JetBrains Mono",
        "Menlo",
        "NanumBarunGothic",
    }),
}
```

## Expected behavior

Normally, keyboard shortcuts should bypass the IME and interpreted as-is.

**Comment by achimnol** [comment]
Another related issue found: Alt key as modifier does not work with `use_ime = true`.

**Comment by achimnol** [comment]
Function keys (F1, F2, ..., F12) do not work when `use_ime=true`.
I could workaround this by mapping `Shift + Fx` to xterm function key sequences, `{key="F1", mods="SHIFT", action=wezterm.action{SendString="\x1bOP"}}`, but I'd like to use the function keys without disabling IME and without extra modifiers.

**Comment by wez** [comment]
Some of what you've described sounds similar to https://github.com/wez/wezterm/issues/1409 for which I pushed a fix just now, so hopefully things are now slightly better.  There are still a number of things to work out with the IME on macOS; it's slow going because the IME APIs aren't really intended to be used outside of standard macOS text input, and that is at-odds with the text input functionality that terminal users desire!

**Comment by achimnol** [comment]
I commented out temporary workaround configs, and now the nightly version works as expected, including on-the-spot text composition and functions keys without modifiers! (with just `use_ime=true` and appropriate fallback font configs)
I can close the issue now. 😄

**Comment by wez** [comment]
I'm very interested to hear your opinion on whether we can set `use_ime=true` by default on macOS after you've worked with the nightly for a couple of days and had a chance to trip over any remaining issues :-)
