### ISSUE TITLE
current_working_dir.file_path returns partial result for paths with '#' in the name

### ISSUE THREAD

**Issue by Syntaxheld** [wez/wezterm#6158]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240915-153243-2d0c5cdd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When the current working directory name contains a hash ('#'), the result of `tab.active_pane.current_working_dir.file_path` ends before that hash.

### To Reproduce

- use supplied config
- `mkdir 'folder with #tag'`
-  `cd 'folder with #tag'`
- look at debug overlay

The `current_working_dir` result will include the whole name, but the `current_working_dir.file_path` representation will end before the `#`.

### Configuration

```lua
wezterm.on('format-window-title', function(tab, pane, tabs, panes, config)
	local cwd = tab.active_pane.current_working_dir
	if not cwd then
		return "W?"
	end

	wezterm.log_info(string.format("%s %s", "CWD:", tab.active_pane.current_working_dir))
	wezterm.log_info(string.format("%s %s", " FP:", tab.active_pane.current_working_dir.file_path))
	
    return cwd.file_path or "W??"
end)
```

### Expected Behavior

`file_path` should include the hash and the rest of the path name.

### Logs

```
00:32:14.521 INFO logging > lua: CWD: file:///Users/guest/Desktop/path%20#%20slupu
00:32:14.521 INFO logging > lua:  FP: /Users/guest/Desktop/path
```

**Comment by loops** [comment]
Hi Syntaxheld,

The URL parser treats anything after '#' as a fragment.  And the same thing happens with everything after '?' being treated as a query.

This could be fixed.  But, since the current working directory should always return a nil file_path, what are you trying to do by using  .file_path in the first place?   What is the situation where this bug is a problem for you?

**Comment by Syntaxheld** [comment]
@loops I stumbled over this as part of a workaround for https://github.com/wez/wezterm/issues/6154 ... I wanted the window title to show the working directory of the current tab (/ active pane).

This bug is not a problem for me, since by now I am using user variables to do what I need.

> [...] current working directory should always return a nil file_path
Why?  [Docs](https://wezfurlong.org/wezterm/config/lua/pane/get_current_working_dir.html) say cwd is a URL object, and [URL docs](https://wezfurlong.org/wezterm/config/lua/wezterm.url/Url.html) say "`file_path` - decodes the path field and interprets it as a file path".

**Comment by wez** [comment]
Sounds like we should avoid using the Url::parse constructor for paths and find a different way to create a url for a path, because there is no reason that this shouldn't work

**Comment by wez** [comment]
perhaps https://docs.rs/url/latest/url/struct.Url.html#method.from_file_path
I don't have time to look at this right now, but if someone wanted to jump in, that's probably the direction to go in.
