### ISSUE TITLE
Previous Prompts in Nushell are New-Lined With Every Key-Press

### ISSUE THREAD

**Issue by lzned** [wez/wezterm#6175]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When using the nushell terminal, every time I type, previous prompts scroll up.

https://github.com/user-attachments/assets/da6d320c-b187-4a7a-b0fa-70529f655c41

### To Reproduce

Open a nushell terminal with `nu`. 
On every key press, previous prompts should be scrolled up to the top of the screen

### Configuration

no config

### Expected Behavior

Previous prompts should stay where they are unless cleared.

### Logs

wezterm version: 20240203-110809-5046fc22 x86_64-pc-windows-msvc
Window Environment: Windows
Lua Version: Lua 5.4
OpenGL: Intel(R) HD Graphics 620 4.5.0 - Build 31.0.101.2115

### Anything else?

Other terminals (I've only tested it on Windows Terminal) don't share this behaviour.

**Comment by loops** [comment]
Hi Izned,

This looks very similar to https://github.com/nushell/nushell/issues/5585   
Does setting "shell_integration: false" in your config.nu make the problem
go away?

**Comment by lzned** [comment]
> Hi Izned,
> 
> This looks very similar to [nushell/nushell#5585](https://github.com/nushell/nushell/issues/5585) Does setting "shell_integration: false" in your config.nu make the problem go away?

I would have done that, if It weren't for the fact that, since whenever, the `shell_integration` variable isn't a boolean anymore.
For the record, this is what `shell_integration` now looks like 
        
```
# osc2 abbreviates the path if in the home_dir, sets the tab/window title, shows the running command in the tab/window title
        osc2: true
        # osc7 is a way to communicate the path to the terminal, this is helpful for spawning new tabs in the same directory
        osc7: true
        # osc8 is also implemented as the deprecated setting ls.show_clickable_links, it shows clickable links in ls output if your terminal supports it. show_clickable_links is deprecated in favor of osc8
        osc8: true
        # osc9_9 is from ConEmu and is starting to get wider support. It's similar to osc7 in that it communicates the path to the terminal
        osc9_9: false
        # osc133 is several escapes invented by Final Term which include the supported ones below.
        # 133;A - Mark prompt start
        # 133;B - Mark prompt end
        # 133;C - Mark pre-execution
        # 133;D;exit - Mark execution finished with exit code
        # This is used to enable terminals to know where the prompt is, the command is, where the command finishes, and where the output of the command is
        osc133: true
        # osc633 is closely related to osc133 but only exists in visual studio code (vscode) and supports their shell integration features
        # 633;A - Mark prompt start
        # 633;B - Mark prompt end
        # 633;C - Mark pre-execution
        # 633;D;exit - Mark execution finished with exit code
        # 633;E - Explicitly set the command line with an optional nonce
        # 633;P;Cwd=<path> - Mark the current working directory and communicate it to the terminal
        # and also helps with the run recent menu in vscode
        osc633: true
        # reset_application_mode is escape \x1b[?1l and was added to help ssh work better
        reset_application_mode: true


```

**Comment by loops** [comment]
Ah, okay.   Wez mentioned in that Issue, that the suspect escape is 133, and i'd disable 633 for good measure. So:

osc133: false
osc633: false

**Comment by lzned** [comment]
That actually worked! Thanks.
