### ISSUE TITLE
Hide mouse cursor when typing

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#618]
Hide the mouse cursor if no movement and type a character in wezterm.

**Comment by gwww** [comment]
I have tested and works as expected. Thank you!

**Comment by SuperSandro2000** [comment]
Can this be turned off? I always loose my cursor when it is hidden.

**Comment by gwww** [comment]
I'm finding this functionality buggy. I have not been able to pinpoint it but what happens is that the cursor turns off and will not turn back on until I click outside of wezterm window. Moving the mouse, inside or outside, of wezterm does not turn it on. Clicking inside of wezterm does not turn it on. Only clicking outside of wezterm will get it to turn back on.

This happens multiple times per day but I have found "the" sequence to make it always happen.

**Comment by wez** [comment]
@gwww are you on macOS?

**Comment by gwww** [comment]
Yes, macOS, 11.1

**Comment by SuperSandro2000** [comment]
I also noticed that when selecting text through tmux the cursor disappears and reappears every time I hold shift and move my cursor.

**Comment by gwww** [comment]
I'm using the nightly with this fix and it is working properly so far.

**Comment by ram02z** [comment]
Has this been implemented on wayland?

**Comment by wez** [comment]
@ram02z not yet. Wayland support is difficult because it is incompatible with my nvidia hardware.  If you're in a position to have a go at implementing this feature on Wayland, I'd be happy to take a PR for it!
