### ISSUE TITLE
Show an indicator when config is reloaded

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#619]
It would be nice to have some indicator that a reload has happened. It is not clear when I do a save of the config as to whether a reload has happened or not.

**Comment by gwww** [comment]
Suggestion: don't automatically show a notification on reload. Add an action for displaying a notification. The last line of the config file could have something such as `wezterm.notify("Configuration loaded! Ain't that cool")`

**Comment by gwww** [comment]
While I'd still like notifications, this is what I've implemented to start:
```
wt.on("window-config-reloaded", function(window, pane)
  window:set_right_status(wt.format({
    {Attribute={Intensity="Bold"}},
    {Text="Configuration reloaded. "},
  }))
  wt.sleep_ms(3000)
  window:set_right_status("")
end)
```

**Comment by wez** [comment]
I've pushed a basic [window:toast_notification](https://wezfurlong.org/wezterm/config/lua/window/toast_notification.html) method.

Our notification implementation doesn't have auto-dismiss capability today.  If you (or some other future reader) like to take a stab at contributing that, the code can be found at: https://github.com/wez/wezterm/tree/main/wezterm-toast-notification/src

**Comment by gwww** [comment]
Thank you for this!

The simplest, perhaps best, approach I can think of to solving the dismissal is two prong. First is implementing something such as:
```
toast = window:toast_notification(...)
...
toast:dismiss_notification()
```
Second is:
```
wezterm.timer.doAfter( time, function )
```
I wish I understood the code base better or I would take a kick... (I'm on a learning Rust path now).

Related to this would it be useful to have Lua library code, written in Lua. Then with the two primitives of `dismiss_notification` and `doAfter` something like this could be written, quite simply:
```
function wezterm.notify(window, title, text, url, time)
  toast = window:toast_notification(title, text, url)
  if time then
    wezterm.timer.doAfter( time, function() toast:dismiss_notification() end )
  end
end
```
(I'd make it part of the `window` class rather than pass in window... I think you see where I'm going with this)

**Comment by wez** [comment]
I think it will be simpler to pass in an `Option<Duration>` to the underlying toast notification function so that it can auto-dismiss itself after a specified time period.

Returning a handle to the notification itself is doable, but care needs to be taken to reason about the lifetime of the associated notification and what happens if the handle gets garbage collected/dropped.  In addition, we don't have a general timer utility available in lua today.

**Comment by wez** [comment]
All the pieces are now present on macos: https://wezfurlong.org/wezterm/config/lua/window/toast_notification.html

**Comment by gwww** [comment]
Looks great. I've tested it a couple of times and works well! Thank you!
