### ISSUE TITLE
wezterm often loses text selection on mouse-drag-against-border

### ISSUE THREAD

**Issue by nh2** [wez/wezterm#621]
## Describe the bug

After initiation mouse-drag based text selection, wezterm often starts selecting text correctly, but then frequently truncates the starting end of the selection to a much shorter region.

## Environment

 - OS: Linux X11
 - Version: Latest release `20210314-114017-04b7cedd`
 - The active keyboard layout name GB (UK English)

## To Reproduce

This video demonstates it:

https://user-images.githubusercontent.com/399535/113465353-9a6cda00-9433-11eb-8f91-1f605a66749c.mp4

## Configuration

```lua
return {
  -- Enable the scrollbar.
  -- It will occupy the right window padding space.
  -- If right padding is set to 0 then it will be increased
  -- to a single cell width
  enable_scroll_bar = true,
}
```

## Expected behavior

The selection continues and does not truncate.

**Comment by wez** [comment]
I can't reproduce this on my linux/x11 system :-/
Is there something else that might contribute?
Is it possible that your mouse has a flaky left button, or is there some other software running that might influence the input events?

**Comment by nh2** [comment]
>  Is it possible that your mouse has a flaky left button, or is there some other software running that might influence the input events?

I don't think that is possible:

In the video it can be seen that wezterm starts a new selection while I drag, and when that happens, the mouse cursor is over the window title. If a new left-click event was issued to Xorg, then that left-click would hit the window title, and thus no more mouse move events would go to wezterm. That means scrolling would stop completely, but it doesn't.

Also it works as expected in `urxvt`, `gnome-terminal`, and `xfce4-terminal`.

> I can't reproduce this on my linux/x11 system :-/

@wez On which window manager are you using it? I'm going to try with yours.

Also, what happens for you, does it happily continue scrolling, or does it not scroll at all?

Thanks!

**Comment by wez** [comment]
I use mutter/gnome on Linux.  It also works consistently for me on macOS and Windows.

What might be helpful is capturing some trace output; launch wezterm like this:

```
WEZTERM_LOG=trace wezterm 2> /tmp/trace.txt
```

Then trigger the issue and attach that trace file to this issue
