### ISSUE TITLE
windows: consider config file under %APPDATA%

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#622]
**Is your feature request related to a problem? Please describe.**

If wezterm is installed into the global program directory users cannot change the config easily.

**Describe the solution you'd like**

wezterm should look at config files under ``%APPDATA%/wzterm/wzterm.lua``

**Describe alternatives you've considered**

Putting the config file under ``C:\Programs``.

**Comment by wez** [comment]
Both `%HOME%/.config/wezterm/wezterm.lua` and `%HOME%/.wezterm.lua` are possible locations for the config file on windows; are those not sufficient?  Or perhaps https://wezfurlong.org/wezterm/config/files.html makes it sound like we only look in the executable directory on windows?

**Comment by wez** [comment]
(`%HOME%` isn't literally used, but rather, the home directory for the user)

**Comment by SuperSandro2000** [comment]
> Both %HOME%/.config/wezterm/wezterm.lua and %HOME%/.wezterm.lua are possible locations for the config file on windows; are those not sufficient?

I didn't know they work under windows because the doc didn't tell it to me and it isn't obvious that those pats work on windows.

I searched the code quickly for APPDATA but it didn't return any results so I thought it isn't supported.

I think if you clarify the docs this issue can be closed.
