### ISSUE TITLE
Can we have transparent background support

### ISSUE THREAD

**Issue by Eragonfr** [wez/wezterm#626]
On my actual terminal emulator, kitty, I have a semi-transparent background.
And I want a similar feature on wezterm, it's one of the two reason of why I'm not switching to it.

I use that to match my global theme.

Also it can be cool to have transparent background with blur or background pictures support but that's an other request.

**Comment by mborejdo** [comment]
have a look at `window_background_image` and ` window_background_opacity` config options. also you can tweak soem colors with `window_background_image_hsb`

**Comment by wez** [comment]
https://www.reddit.com/r/unixporn/comments/m5bwp8/wezterm_a_highly_configurable_cross_platform/ demonstrates some of the fancier styling features in wezterm
