### ISSUE TITLE
Shortcuts with `Shift` + another modifier + `3` will be ignored when default keybindings are disabled

### ISSUE THREAD

**Issue by FlenkerDLR** [wez/wezterm#6294]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 with KWin (5.18.6)

### WezTerm version

20241015-083151-9ddca7bd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I want to create a shortcut `Shift+Ctrl+3` to switch to the third tab. But instead the character `#` is emitted and my config is ignored.
This also happens with `Shift+Super+3` and `Shift+Ctrl+Super+3`. No matter, if I use the left or right `Shift` or `Super` key. With `Ctrl_R` or `Alt_R` other charcters apper (£, ³ and §), but this should be the correct behaviour as I use a german layout.

Nevertheless, I want to create my own shortcut on e.g. `Shift+Ctrl+3` and this will be ignored.

I figured out so far, that this only occurs, when I disable default key bindings with `config.disable_default_key_bindings = true`. When I remove this line, my mapping works fine.

### To Reproduce

Just put the `config.disable_default_key_bindings = true` to the config and use e.g. `Shift+Ctrl+3`. This emits the `#`.

### Configuration
```
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

-- Keybindings
config.disable_default_key_bindings = true

-- it does not matter if here are own keybindings or not e.g.:
-- config.keys = { { key = '3', mods = 'SHIFT|CTRL', action = act.ActivateTab(2) },  -- for numpad 3 (works fine)
--                            { key = '§', mods = 'SHIFT|CTRL', action = act.ActivateTab(2) }}  -- for other 3 (with § in german layout)

return config
```

### Expected Behavior

Switch to the third tab when I type `Shift+Ctrl+3`

**Comment by bew** [comment]
Please try to run wezterm from wezterm (or another terminal), with [`config.debug_key_events = true`](https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html), to check what Wezterm detects when you press those keys

**Comment by FlenkerDLR** [comment]
```
Debug Overlay
wezterm version: 20241015-083151-9ddca7bd x86_64-unknown-linux-gnu
Window Environment: X11 KWin
Lua Version: Lua 5.4
OpenGL: Mesa Intel(R) Graphics (ADL GT2) 4.6 (Compatibility Profile) Mesa 21.2.6
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
13:50:40.720 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftControl, modifiers: SHIFT, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: SHIFT, leds: (empty), phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:50:40.720 INFO wezterm_gui::termwindow::keyevent > send to pane DOWN key=LeftControl mods=SHIFT
13:50:40.824 INFO wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(L), modifiers: SHIFT | CTRL, leds: (empty), phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:50:40.825 INFO wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('L'), modifiers: CTRL, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(L), modifiers: SHIFT | CTRL, leds: (empty), phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:50:40.825 INFO wezterm_gui::termwindow::keyevent > Char('L') CTRL -> perform ShowDebugOverlay
>
```

**Comment by bew** [comment]
It looks like the same problem as in my (old) issue #4259, where the down event is wrong (taking the char from QWERTY layout) but the up event is correct (taking the char from your layout).

To workaround this you can try to bind to the `raw_code`, like this:
```lua
{ key = 'raw:12', mods = 'SHIFT|CTRL', action = act.ActivateTab(2) }}
```

---
Q: You mention in the title `when default keybindings are disabled`, does it work with the default config?

**Comment by FlenkerDLR** [comment]
Hey,

When I remove `config.disable_default_key_bindings = true` it works fine. With this line in my config, I have the issues.

Your workaround worked for me (with default key findings on or off).

Thank you.

**Comment by bew** [comment]
I'm suspecting that default keybinds for numbers actually bind to the raw keys, that would explain why it works _all the time by default_.
