### ISSUE TITLE
CTRL + Tab not working

### ISSUE THREAD

**Issue by hasahmad** [wez/wezterm#630]
## Describe the bug

I am trying add a custom key for moving to tab on right, but I can't get it to work.
I have the following in mykeys array and reload config, opened a few tab and tried the key combination (CTRL + Tab), but nothing happened.
```
table.insert(mykeys, {
  mods="CTRL",
  key="Tab",
  action=wezterm.action{ActivateTabRelative=1},
})
```
I also set `debug_key_events = true` and tried the key combination, but it showing nothing in logs.
I tried replacing `key="Tab"` with `key="q"` and it worked with (CTRL + q)
Am I missing anything?

## Environment (please complete the following information):

 - OS: macOS
 - Version: wezterm 20210314-114017-04b7cedd
 - The active keyboard layout name: ENG

## Configuration

```lua
local wezterm = require 'wezterm';
local mykeys = {}
table.insert(mykeys, {
  mods="CTRL",
  key="Tab",
  action=wezterm.action{ActivateTabRelative=1},
})
return {
  keys = mykeys,
  debug_key_events = true,
}
```

**Comment by wez** [comment]
In about an hour, the nightly release (see https://wezfurlong.org/wezterm/install/macos.html) will have a fix for this!

**Comment by hasahmad** [comment]
Working fine in the latest nightly
