### ISSUE TITLE
Feature request: Command to save scrollback to a file

### ISSUE THREAD

**Issue by mirekdlugosz** [wez/wezterm#6300]
**Is your feature request related to a problem? Please describe.**

It doesn't happen often, but it does happen that I run a command that produces very long output and I need to find something specific in that output. Usually Search in scrollback gets the job done. 

But sometimes Search finds many instances, and I still want very specific one, or I want to check something in the context of the instance. In these cases it's super useful to write entire scrollback content to a file and use a separate editor.

Konsole has a feature like that.

**Describe the solution you'd like**

A terminal command. It doesn't even need a default keybinding.

It would be great if it could ask for a path where file should be saved, but initial implementation may save under single well-known path. You can copy that file if you want to keep it.

**Comment by bew** [comment]
This is something you can implement yourself in your config, see the example in:
https://wezfurlong.org/wezterm/config/lua/pane/get_lines_as_text.html

**Comment by mirekdlugosz** [comment]
@bew thanks, I missed that. This will work.
