### ISSUE TITLE
Use syntax highlighting in the docs 

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#632]
**Is your feature request related to a problem? Please describe.**
I find it hard to read the lua examples on https://wezfurlong.org/wezterm.

**Describe the solution you'd like**
Replace
```
return {
  -- This tells wezterm to look first for fonts in the directory named
  -- `fonts` that is found alongside your `wezterm.toml` file.
  -- As this option is an array, you may list multiple locations if
  -- you wish.
  font_dirs = {"fonts"},
}
```
with
```lua
return {
  -- This tells wezterm to look first for fonts in the directory named
  -- `fonts` that is found alongside your `wezterm.toml` file.
  -- As this option is an array, you may list multiple locations if
  -- you wish.
  font_dirs = {"fonts"},
}
```
which would make the docs a lot easier to read for me.

**Describe alternatives you've considered**
Keep it like it is.

**Additional context**

**Comment by wez** [comment]
The docs do use syntax highlighting.  Is there a particular section where you don't see it?  Please share links to the specific page(s)

**Comment by SuperSandro2000** [comment]
🤦🏼 maybe I should enable js. Without it all the codeblocks are white on white.
