### ISSUE TITLE
Increasing and decreasing font size through keybinds changes window size.

### ISSUE THREAD

**Issue by NoobJsPerson** [wez/wezterm#6322]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20241015-083151-9ddca7bd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When you use keybinds to decrease or increase the font size. it increases or decreases the window size respectively.

### To Reproduce

- Open wezterm
- Press the keybinds to increase or decrease font size
The window size changes too!

### Configuration

no config

### Expected Behavior

The font size should change but the window size should stay the same.

### Anything else?

https://github.com/user-attachments/assets/942129c4-1799-4f6e-8479-62fce263ca46

this is a video showcasing the bug.

**Comment by bew** [comment]
Add this to your config:
```lua
config.adjust_window_size_when_changing_font_size = false
```
ref: https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html
