### ISSUE TITLE
100% fullscreen

### ISSUE THREAD

**Issue by ekg** [wez/wezterm#6326]
Wezterm looks awesome! But, I'd like to be able to open wezterm in 100% fullscreen, so that there is no header, footer, or visible space outside the terminal window. For instance, you can do this with gnome terminal using F11, and kitty with control+shift+F11. What is the recommended way to do this?

**Comment by bew** [comment]
You can toggle fullscreen with the `ToggleFullScreen` action
ref: https://wezfurlong.org/wezterm/config/lua/keyassignment/ToggleFullScreen.html

This is bound by default to `Alt+Enter`

**Comment by ekg** [comment]
Thank you! I can toggle fullscreen with `Alt+Enter`, but there is still a bar at the top with tabs. I would need to remove or hide this too to be 100% fullscreen. How can I do so?

**Comment by bew** [comment]
To hide the tab bar you can use one of these config options:
- [`hide_tab_bar_if_only_one_tab`](https://wezfurlong.org/wezterm/config/lua/config/hide_tab_bar_if_only_one_tab.html) to configure when to hide it
- [`enable_tab_bar`](https://wezfurlong.org/wezterm/config/lua/config/enable_tab_bar.html) to completely disable the tab bar

**Comment by ekg** [comment]
Wonderful. I set this in my `~/.wezterm.lua`:

```lua
config.hide_tab_bar_if_only_one_tab = true
```
