### ISSUE TITLE
Allow switching between cmd and wsl easily

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#633]
**Is your feature request related to a problem? Please describe.**

Windows Terminal allows you to open powershell, cmd, wsl and custom configs of those with a dropdown menu. wezterm does not allow easy switching of shells that I know of.

**Describe the solution you'd like**

When right clicking the new tab I would like to choose between cmd and wsl.

**Describe alternatives you've considered**

Switching the config around or using another terminal emulator alongside.

**Additional context**

![image](https://user-images.githubusercontent.com/7258858/113495962-61953980-94f5-11eb-953e-c18fc2d75eab.png)

**Comment by cxiao** [comment]
There is a launcher menu built in, which opens when you right-click on the new tab button. You can also add custom entries to it, such as listing all your shells. It is documented here: https://wezfurlong.org/wezterm/config/launch.html#the-launcher-menu

**Comment by SuperSandro2000** [comment]
Damn. The doc is just to large and I am searching the wrong stuff. Thanks!
