### ISSUE TITLE
Wezterm is unable to load the configuration file on Windows

### ISSUE THREAD

**Issue by jhonGriGi** [wez/wezterm#6357]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20241031-235112-0983ae90

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

![image](https://github.com/user-attachments/assets/cdc6e566-30f4-425a-bd55-4aa889227c54)

The error occurs even if my configuration simply returns the config directly without making any changes. It seems that the issue is related to the file path itself and not something within the configuration of the config_builder.

Windows Version:
![image](https://github.com/user-attachments/assets/5ef2a3d7-3cbc-43a8-a622-25806e091f8b)

### Configuration

```Lua
local wezterm = require("wezterm")

local config = wezterm.config_builder()

config.default_prog = { 'C:\\Users\\Darwin Grisales\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe' }
config.font = wezterm.font("SFMono Nerd Font")
config.font_size = 16
config.line_height = 1.4

config.enable_tab_bar = false
config.window_decorations = "TITLE | RESIZE"

config.colors = {
	foreground = "#CBE0F0",
	background = "001B26",
	cursor_bg = "#47FF9C",
	cursor_border = "#47FF9C",
	cursor_fg = "#011423",
	selection_bg = "#033259",
	selection_fg = "#CBE0F0",
	ansi = { "#214969", "#E52E2E", "#44FFB1", "#FFE073", "#0FC5ED", "#a277ff", "#24EAF7", "#24EAF7" },
	brights = { "#214969", "#E52E2E", "#44FFB1", "#FFE073", "#A277FF", "#a277ff", "#24EAF7", "#24EAF7" },
}

config.window_background_opacity = 0.9
config.macos_window_background_blur = 10

return config

```

**Comment by gzmorell** [comment]
I cannot reproduce this failure on Windows 10 22H2.
The message of the failure tells that "C:\\Users...." is interpreted as escape sequence \U which do not happen in my system. 
If pwsh is in your Path you can use just "pwsh", you can try also "/Users/..." instead of double 
"\\Users...".

**Comment by jhonGriGi** [comment]
> I cannot reproduce this issue on Windows 10 22H2. The error message indicates that "C:\Users..." is being interpreted as the escape sequence \U, which does not happen on my system. If pwsh is in your PATH, you can simply use "pwsh". You can also try using "/Users/..." instead of double "\\Users...".

The error occurs even without this line:

```lua
config.default_prog = { 'C:\\Users\\Darwin Grisales\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe' }
```
It seems like WezTerm is unable to correctly read the path of the config file on Windows 11.

**Comment by KevinSilvester** [comment]
This is sort of a janky workaround, but try adding the path to `pwsh` to the `Path` environment variable from the system properties.

Typing env in the taskbar search should show "Edit the System environment variable"
<img width="589" alt="image" src="https://github.com/user-attachments/assets/6dfb470c-ef60-4172-9fb0-976148dbf053">

Launch the application then
1. Click the `Environment Variables` button
2. Scroll down on the variable until you find `Path`
3. Select `Path` and then the `Edit` button
4. Add a new path to `C:\Users\Darwin Grisales\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe`
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/e7e92af4-46e6-455b-b6c2-1106003bb435">

**Comment by jhonGriGi** [comment]
The issue is resolved.

Solution: The installer did not automatically add the executable path to the environment variables. I added the path manually and changed this line:

```lua
config.default_prog = { 'C:\\Users\\Darwin Grisales\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe' }
```

to the following:
```lua
config.default_prog = { "pwsh.exe" }
```
