### ISSUE TITLE
Will NvimDark and NvimLight colorschemes be included in the next stable release?

### ISSUE THREAD

**Issue by heygarrett** [wez/wezterm#6362]
**Is your feature request related to a problem? Please describe.**  
I'd like to use the NvimDark colorscheme.

**Describe the solution you'd like**  
NvimDark is included in the next stable release

**Describe alternatives you've considered**  
I've switched to the nightly build for now.

**Additional context**  
https://github.com/wez/wezterm/blob/main/docs/colorschemes/data.json#L26917

**Comment by heygarrett** [comment]
@bew Thanks! The file I linked to hadn't been updated in four months, so I wasn't sure if those colorschemes had been skipped over for stable releases. But I didn't realize, looking now, that the most recent stable release was nine months ago. 😅

**Comment by bew** [comment]
@heygarrett I see ^^ a stable release should happen soon-ish, you can follow #6341 (and maybe even participate in testings 😉)
