### ISSUE TITLE
webp images are missing color channel

### ISSUE THREAD

**Issue by bew** [wez/wezterm#638]
## Describe the bug

When using the `webp` image format, and displaying one with `wezterm imgcat` (or similar), the image is displayed in black & white, instead of colors.

## Environment

 - OS: Linux X11
 - Version: wezterm 20210314-114017-04b7cedd
 - The active keyboard layout name: N/A

## To Reproduce

Download these pictures:
[pics.zip](https://github.com/wez/wezterm/files/6254376/pics.zip)

Result: (first the PNG version, then the WEBP version)
![webp-wezterm-no-color](https://user-images.githubusercontent.com/9730330/113506265-03dc0e00-9544-11eb-8939-1855a7102fbd.png)

**Comment by wez** [comment]
The underlying `image` crate only supports decoding the luma channel in webp images.
https://github.com/image-rs/image/pull/952 appears to be a stalled PR to enable colors for this format.

**Comment by bew** [comment]
I see, not much to be done then for now.
It's really a "nice-to-have", nothing blocking for me

Thanks for the info, https://github.com/image-rs/image/issues/939 seems the issue to keep track of (in case the mentioned PR above is never completed)

**Comment by wez** [comment]
I'm going to close this: wezterm doesn't claim to support webp, and it's not something that I can directly control.  If/when support shows up in the image crate we'll be able to pick it up then.

**Comment by bew** [comment]
No problem 👍
