### ISSUE TITLE
Drag & Drop files/folders

### ISSUE THREAD

**Issue by hasahmad** [wez/wezterm#640]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it is sometimes easier to cd into folder by dragging and dropping it or paste the path of file by dragging and dropping into the terminal.

**Describe the solution you'd like**
Drag & Drop file/folders, like in the regular terminal, once you drag something it copies the path of file/folder.

**Comment by wez** [comment]
In nightly builds, this is implemented for macOS and Windows:
https://wezfurlong.org/wezterm/config/lua/config/quote_dropped_files.html

**Comment by Mattwmaster58** [comment]
@wez great to see this added, thank you. I noticed that on Windows the terminal window isn't focused after a drag & drop -  should I open a separate issue to track that?

**Comment by wez** [comment]
@Mattwmaster58 you can thank @datasone for making this work on Windows.
Yes, please open a separate issue for what you're seeing.

**Comment by mrienstra** [comment]
Should this be closed as "completed"? Or is it still open because it's not supported on X11 yet?

**Comment by wez** [comment]
It's still open because it is not supported on X11 yet

**Comment by haoming-li-ling** [comment]
What about the reverse? Dragging a filename from within wezterm so the path can be used elsewhere?

**Comment by Grueslayer** [comment]
@wez Hi, thank you for this feature. May we've a lua callback with an array of filenames we can "quote" as we like. VIM needs some "special" treatment (no double quotes in windows, but escaping spaces and furthermore escaping exclamation marks etc.). So my idea is I can check if current process is vim and nvim and do the escaping in ly by myself, if not I leave this to your defualt.
