### ISSUE TITLE
Custom color scheme not recognised unless defined inside `config` table in `wezterm.lua`

### ISSUE THREAD

**Issue by prateektade** [wez/wezterm#6421]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

I am using Gentoo on WSL inside WezTerm

### WezTerm version

20241119-101432-4050072d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I wanted to define tab bar colors for the pre-installed Rosé Pine colorscheme (set using `config.color_scheme = 'rose-pine').

I started with the `wezterm.color.get_builtin_schemes()` function, following the example on [this](https://wezfurlong.org/wezterm/config/lua/wezterm/get_builtin_color_schemes.html) page. The colors got disturbed completely.

Then I removed those lines of code, created a separate TOML file with all the colors including the added tab bar colors, defined the path using `config.color_scheme_dirs` and then set the name inside the TOML file as the value for `config.color_scheme`. That disturbed the colors again, same as earlier.

### Configuration

```lua
local wezterm = require 'wezterm'

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

local rose_pine_main = wezterm.color.get_builtin_schemes()['rose-pine']

rose_pine_main = {
  tab_bar = {
    background = 'hsl: 249 22 12',
    inactive_tab_edge = 'hsl: 249 12 47',
    active_tab = {
      bg_color = 'hsl: 248 25 18',
      fg_color = 'hsl: 245 50 91',
    },
    inactive_tab = {
      bg_color = 'hsl: 249 22 12',
      fg_color = 'hsl: 249 12 47',
    },
    inactive_tab_hover = {
      bg_color = 'hsl: 248 25 18',
      fg_color = 'hsl: 245 50 91',
    },
    new_tab = {
      bg_color = 'hsl: 249 22 12',
      fg_color = 'hsl: 249 12 47',
    },
    new_tab_hover = {
      bg_color = 'hsl: 248 25 18',
      fg_color = 'hsl: 245 50 91',
    },
  },
}

return {
  color_scheme_dirs = '/home/prateektade' -- created the rose-pine-main.toml file here
  color_schemes = {
    ['rose-pine'] = rose_pine_main,
  },
  color_scheme = 'rose-pine',
  --tried to set the colorscheme defined in the rose-pine-main.toml as follows
  --color_scheme = 'rose-pine-main',
}
```

**Comment by prateektade** [comment]
@bew Makes sense! Tried this and it works! Thank you.

What might be the issue with the colors from the `toml` config file not getting applied? The name doesn't clash with an existing color scheme name. I specified all the colors too.

**Comment by prateektade** [comment]
Yes, I got an error saying that read `Your configuration specifies color_scheme="rose-pine-toml" but that scheme was not found`. It only recognised the file when I placed it in the `%HOME%/.config/wezterm/colors` directory. The `color_scheme_dirs` config option doesn't work I guess.

**Comment by bew** [comment]
Ah according to [the docs](https://wezfurlong.org/wezterm/config/appearance.html?h=color_scheme_dirs#defining-a-color-scheme-in-a-separate-file) it should be a list (not sure why it didn't tell you the type was incorrect)

Try setting it with:
```lua
config.color_scheme_dirs = { '/home/prateektade' }
config.color_scheme = 'rose-pine-toml'
-- ...
return config
```
