### ISSUE TITLE
wezterm process_queued_xcb X11 connection is broken exceeded requeset length that the server accepts

### ISSUE THREAD

**Issue by MohamedOsman1998** [wez/wezterm#6468]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

using X11 and I3_wm

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm crashes on start with the following error: 01:55:08.261  ERROR  wezterm_gui                 > running message loop: process_queued_xcb: X11 connection is broken: xcb connection error: Connection closed, exceeded request length that server accepts.
only happens on my ultrawide monitor, and only when set to full xrandr scaling, only when maximized.
 

### To Reproduce

set high resolution on the display and xrandr --scale 1x1
maximized window on start

### Configuration

no config

### Logs

01:56:30.522  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: get_appearance.read_setting: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.portal.Error.NotFound: Requested setting not found
libEGL warning: DRI2: failed to authenticate
01:56:30.742  ERROR  wezterm_gui                 > running message loop: process_queued_xcb: X11 connection is broken: xcb connection error: Connection closed, exceeded request length that server accepts.; terminating

**Comment by vimpostor** [comment]
> only happens on my ultrawide monitor, and only when set to full xrandr scaling

What is the resolution of your monitor?

**Comment by MohamedOsman1998** [comment]
3440x1440
________________________________

**Comment by vimpostor** [comment]
What is your version of Mesa? I believe this might be a duplicate of #249 and as such may be already resolved upstream with Mesa >=22.2.0 with https://gitlab.freedesktop.org/mesa/mesa/-/issues/6483

**Comment by MohamedOsman1998** [comment]
This fixed it thank you!
