### ISSUE TITLE
text just goes up whenever i type

### ISSUE THREAD

**Issue by niceEli** [wez/wezterm#6491]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

whenever i type text everything (but the place where id be typing) just goes up

### To Reproduce

nushell
wezterm latest (scoop)
windows (it may happen on different platforms)
oh-my-posh amro theme

### Configuration

-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This will hold the configuration.
local config = wezterm.config_builder()

config.default_prog = { "nu" }
config.font = wezterm.font_with_fallback {
  {
    family = 'JetBrainsMono NFM Medium',
    weight = 'Medium',
  },
  { family = 'Terminus', weight = 'Bold' },
  'Noto Color Emoji',
}
config.font_size = 14.0
config.enable_tab_bar = false
config.color_scheme = 'Vice Dark (base16)'
config.enable_kitty_keyboard = true
config.enable_scroll_bar = true

config.initial_rows = 32
config.initial_cols = 120

-- and finally, return the configuration to wezterm
return config

### Expected Behavior

the text should not go up

### Logs

theres no lines

### Anything else?

cant really show it buggy though images, heres a video instead
[https://youtu.be/LyTVON_bCzI](https://youtu.be/LyTVON_bCzI)

**Comment by niceEli** [comment]
it happens with any theme that uses a multi line entrance prompt (like atomic or chips or cloud-context for example)

**Comment by niceEli** [comment]
after some testing this bug **DOES NOT** happen on Linux (Linux6 Fedora41 Kinoite(UBlue))

**Comment by bew** [comment]
Does it happen in other terminals as well?
If so it might be an issue with nushell then

**Comment by niceEli** [comment]
> Does it happen in other terminals as well? It might be an issue with nushell, the readline impl is known to have a few bugs in this regards

no, as shown in the video it does not happen in alacritty, it also doesnt happen in windows terminal but i didnt show that

**Comment by niceEli** [comment]
wait
just realized that yes it is a nushell bug, https://github.com/nushell/nushell/issues/5585

**Comment by bew** [comment]
Oh 'good', I didn't know that bug looked like this on nushell nowadays 😅
