### ISSUE TITLE
Built-in API document

### ISSUE THREAD

**Issue by brianhuster** [wez/wezterm#6507]
**Is your feature request related to a problem? Please describe.**
Wezterm comes with quite many Lua configuration options, but unfortunately I have to look for them online

**Describe the solution you'd like**
I would love wezterm to have Lua configuration documentation that I can access offline similar to Vim's built-in `help` documents. Maybe this document can be access via command line as `wezterm help`?  

**Describe alternatives you've considered**
The only alternative I know is the help in [wezfurlong.org](https://wezfurlong.org/wezterm). It's good, but sometimes my internet connection is bad, so I would like an offline alternative

**Comment by bew** [comment]
Did you take a look at existing issues about this?
A quick search for `offline documentation` gave me #4132 & #3964.

**Comment by brianhuster** [comment]
Sorry for my careless. I'll close this
