### ISSUE TITLE
Right Angle(>) followed by minus (-) sign doesn't look as expected

### ISSUE THREAD

**Issue by rrpolanco** [wez/wezterm#654]
## Describe the bug

When browsing a `yaml` file, I noticed that the following contiguous characters `>-` don't look as expected when compared to `kitty` terminal.

## Environment (please complete the following information):

 - OS: macOS 10.15.7
 - Version: `wezterm 20210404-112810-b63a949d-3-g97d4de80`
 - The active keyboard layout name: ENG

## To Reproduce

`echo ">-"`

## Expected behavior

I expect there to be a visible space between `>` and `-`.

## Screenshots

`kitty`
![image](https://user-images.githubusercontent.com/6497491/113757436-36b70b00-96d8-11eb-88cd-1ca4df013ac6.png)

`wezterm`
![image](https://user-images.githubusercontent.com/6497491/113757584-6239f580-96d8-11eb-97e2-677403124213.png)

**Comment by rrpolanco** [comment]
I noticed that when typing `>` followed by the minus sign(`-`) `wezterm` automatically converts/renders the symbol:
![right-angle-minus-render](https://user-images.githubusercontent.com/6497491/113758327-5569d180-96d9-11eb-838e-232ae1929684.gif)

Is this a config setting that can be tuned?

**Comment by wez** [comment]
That's a ligature defined by the font.  You can disable the use of ligatures if you prefer; this section in the docs has more information:
https://wezfurlong.org/wezterm/config/font-shaping.html

**Comment by gwww** [comment]
I wonder if there would be less bugs generated if the default is ligatures turned off. That would make people turn them on and see the difference. Just a thought.

**Comment by rrpolanco** [comment]
Thanks @wez ! Disabling the ligature for the font is what I was expecting.
