### ISSUE TITLE
Add action to cycle through panes

### ISSUE THREAD

**Issue by nicoulaj** [wez/wezterm#659]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to have a command that cycles through panes (eg `ActivatePaneRelative`) like the one for tabs (`ActivateTabRelative`). It is easier for me to just hit the same shortcut regardless of the current active pane rather than having to think of the direction I want to go to.

**Describe alternatives you've considered**
None

**Additional context**
Ordering of panes could be simply defined by creation order I guess ?

**Comment by wez** [comment]
Implemented in 225d15c which should be available in the nightly downloads within an hour.
(See also https://github.com/wez/wezterm/issues/976)

**Comment by nicoulaj** [comment]
Awesome, thank you !
