### ISSUE TITLE
Consider integrating the allsorts shaper

### ISSUE THREAD

**Issue by wez** [wez/wezterm#66]
Allsorts is a new  font shaper implemented purely in Rust.
It's still a bit young with some features to be fleshed out, notably:

* they mention that emoji are not yet supported, but I'm not super sure what that means
* shaping is handled by code outside of the crate at the moment, but it is possible to call a number of functions to do it yourself (see https://github.com/yeslogic/allsorts/issues/8)

It may (should!) be possible to get sane font metrics from this crate, too.

**Comment by wezm** [comment]
> they mention that emoji are not yet supported, but I'm not super sure what that means

Emoji requires parsing and reading the the tables where the emoji images live. And then shaping requires using these and applying ZWJ sequenses to produce single emoji like :family_man_woman_girl_boy:. We don't handle that yet.

**Comment by wez** [comment]
@wezm: I updated to the current master of allsorts and am pleased to say that I'm having generally really good results vs. harfbuzz!  The combining sequences generally seem to work better than harfbuzz!

One case that doesn't seem to work as well as harfbuzz is for keycap sequences from this table:

```
keycap
№       Code     CLDR Short Name
1462    U+0023 U+FE0F U+20E3    #️⃣       keycap: #
1463    U+002A U+FE0F U+20E3    *️⃣       keycap: *
1464    U+0030 U+FE0F U+20E3    0️⃣      keycap: 0
1465    U+0031 U+FE0F U+20E3    1️⃣      keycap: 1
1466    U+0032 U+FE0F U+20E3    2️⃣      keycap: 2
1467    U+0033 U+FE0F U+20E3    3️⃣      keycap: 3
1468    U+0034 U+FE0F U+20E3    4️⃣      keycap: 4
1469    U+0035 U+FE0F U+20E3    5️⃣      keycap: 5
1470    U+0036 U+FE0F U+20E3    6️⃣       keycap: 6
1471    U+0037 U+FE0F U+20E3    7️⃣       keycap: 7
1472    U+0038 U+FE0F U+20E3    8️⃣      keycap: 8
1473    U+0039 U+FE0F U+20E3    9️⃣      keycap: 9
1474    U+1F51F         🔟     keycap: 10
```

wezterm first resolves the glyph via `cmap_subtable.map_glyph` in a regular monospace font, and then falls back to Noto Color Emoji if it isn't found.  I think the lookup is succeeding before we get to the emoji font; you can see in the picture below that the top window (running allsorts) just shows normal numerals for these, but the bottom window (running harfbuzz) shows the keycap glyphs:

![top-allsorts-bottom-harfbuzz-keycaps](https://user-images.githubusercontent.com/117777/99863599-c1490480-2b53-11eb-940b-126cf5eeec6d.png)

Is there something special that I should be doing for this lookup?

I think my `VariationSelector` [logic](https://github.com/wez/wezterm/blob/master/wezterm-font/src/parser.rs#L350) is likely wonky; the way I handle that right now is to see if a failed glyph lookup resolves to a `VariationSelector` and if so, set each RawGlyph in the current run to that variation.
However, I didn't see what was actually reading the variation in the allsorts crate, so I wonder if that might be a red herring!

**Comment by wezm** [comment]
>  I updated to the current master of allsorts and am pleased to say that I'm having generally really good results vs. harfbuzz! The combining sequences generally seem to work better than harfbuzz!

That's great to hear. 

> One case that didn't seem to work as well as harfbuzz (but is fixed as of ddc4c1b) is for keycap sequences from this table

Sounds like you have been able to get it to work with that commit. Is that right?

Nonetheless I think we do need a bit more test coverage for the keycap sequences to ensure they're working as expected. I'll try to circle back to that when I wrap up some improvements to the `gsub` API that I'm working on at the moment.

**Comment by wez** [comment]
> > I updated to the current master of allsorts and am pleased to say that I'm having generally really good results vs. harfbuzz! The combining sequences generally seem to work better than harfbuzz!
> 
> That's great to hear.

The gaps in the harfbuzz implementation were my fault, and I spent some time fix that up.  At least things now appear to be consistent between the two shapers in master!

> > One case that didn't seem to work as well as harfbuzz (but is fixed as of [ddc4c1b](https://github.com/wez/wezterm/commit/ddc4c1b624aea69dc8abc7d29252ac51f2cca6af)) is for keycap sequences from this table
> 
> Sounds like you have been able to get it to work with that commit. Is that right?

That correct; there's some slightly awkward code to deal with this case, and it would be great to eliminate it in the future :)

**Comment by ImportTaste** [comment]
Can I ask what still needs to be done? Allsorts looks a bit more crisp than Harfbuzz, which I like.

**Comment by wez** [comment]
The shaper doesn't impact rendering quality: all rendering is carried out by freetype.
The purpose of the shaper is to resolve text (including ligatures and emoji) to sequences of glyphs with positioning information.

The allsorts integration in wezterm doesn't handle sizing for fallback fonts (such as emoji) correctly (#587).

allsorts doesn't support as many font formats as freetype which means that it is possible for a font to be selected that allsorts cannot shape.

**Comment by ImportTaste** [comment]
> The shaper doesn't impact rendering quality: all rendering is carried out by freetype.
> The purpose of the shaper is to resolve text (including ligatures and emoji) to sequences of glyphs with positioning information.
> 
> The allsorts integration in wezterm doesn't handle sizing for fallback fonts (such as emoji) correctly (#587).
> 
> allsorts doesn't support as many font formats as freetype which means that it is possible for a font to be selected that allsorts cannot shape.

I guess it's just my imagination then, because it does seem to impact the font size. I tried to make the Allsorts and Harfbuzz configs have the same size of text by giving them different font sizes, but maybe the very slight difference made Allsorts seem better.
