### ISSUE TITLE
Iosevka font rendering broken for some font sizes in recent builds

### ISSUE THREAD

**Issue by jdknezek** [wez/wezterm#661]
## Describe the bug

Since 20210404, on Windows, the font I've been using (Iosevka) renders incorrectly at some point sizes (9, 12 which I use normally)

## Environment (please complete the following information):

 - OS: Windows 10
 - Version:
   - wezterm 20210404-112810-b63a949d
   - wezterm 20210405-110924-a5bb5be8
 - The active keyboard layout name: English-Dvorak

## To Reproduce

Use [Iosevka v5.2.1](https://typeof.net/Iosevka) on Windows, at font size 9 or 12

## Configuration

```lua
        font = wez.font('Iosevka Term Light'),
        font_size = 12,
        font_rules = {
                {
                        intensity = 'Bold',
                        font = wez.font('Iosevka Term Medium'),
                },
        },
```

## Expected behavior

Font rendering to remain consistent at all point sizes

## Screenshots

20210314 @ 13 / 12:
![image](https://user-images.githubusercontent.com/1338/113961460-b1247f80-97eb-11eb-8f27-efcc0a02756b.png) ![image](https://user-images.githubusercontent.com/1338/113961467-b8e42400-97eb-11eb-867f-5fab2f5c2c70.png)

20210404 @ 13 / 12:
![image](https://user-images.githubusercontent.com/1338/113961485-bf729b80-97eb-11eb-9b1c-4e929183c1a9.png) ![image](https://user-images.githubusercontent.com/1338/113961518-cef1e480-97eb-11eb-8bd4-debad32a3491.png)

20210405 @ 13 / 12:
![image](https://user-images.githubusercontent.com/1338/113961536-d7e2b600-97eb-11eb-939a-c94982b0d341.png) ![image](https://user-images.githubusercontent.com/1338/113961554-dc0ed380-97eb-11eb-86e9-13ea76e955aa.png)

## Additional comments

I do use a custom style of Iosevka, but the same font works fine in 20210314 but is incorrect in both 202104 releases.

Thank you!

**Comment by wez** [comment]
Weirdly, this only manifested on Windows with this font, although the problem could have applied to any OS/font combination.

I've pushed a fix for this; when you see a green checkmark next to the commit referenced above, the nightly download will include that fix!

**Comment by jdknezek** [comment]
Thanks for the super quick fix, and everything you put into this project! I'll verify on the next nightly then close.
