### ISSUE TITLE
Launcher Menu/Tab Navigator Fuzzy Find

### ISSUE THREAD

**Issue by jaredramirez** [wez/wezterm#664]
**Is your feature request related to a problem? Please describe.**
Not exactly, maybe a problem of convenience

**Describe the solution you'd like**
It would be really convenient if WezTerm had the ability fuzzy find which tab or launch option you want, rather than using arrow keys/jk to select. (In the case of tabs, https://github.com/wez/wezterm/issues/522 seems relevant)

**Describe alternatives you've considered**
Using arrow keys/jk in those menus.

**Additional context**
This is something that [tab-rs](https://github.com/austinjones/tab-rs) does that I found really useful!

**Comment by wez** [comment]
Closing in favor of https://github.com/wez/wezterm/issues/1485 - the command palette concept discussed there will have fuzzy and frecency
