### ISSUE TITLE
Keyboard repeat rate / delay on wayland does not respect system settings

### ISSUE THREAD

**Issue by yiding** [wez/wezterm#669]
## Describe the bug

Keyboard repeat rate and delay does not respect what's configured in the desktop environment.

## Environment (please complete the following information):

- OS: Linux Wayland 
- Version: ezterm 20210405-110924-a5bb5be8
 
## To Reproduce

Run wezterm on gnome wayland.
Play with different repeat rate/speeds in gnome settings > accessibility > repeat keys.

## Expected behavior
Keyboard repeat in wezterm respect the settings / behave the same way as other apps.

**Comment by gwww** [comment]
I have something similar on MacOS, although I don't know if its wezterm being slow or keyboard repeat rate.

When in `vim`, on say `iTerm2`, and I hold down the `j` key then it moves through the file extremely quick (at what would appear to be my keyboard repeat rate). Same scenario in `wezterm` the movement is very slow, along with lines of a standard keyboard repeat rate.

I don't know how to isolate further. Is it repeat rate? Screen redraw? Something else?

**Comment by wez** [comment]
On Wayland wezterm is currently deliberately ignoring the system repeat rate because the client library that handles that goes into a busy loop.

On macOS wezterm generates key events at the same rate that macos delivers them to wezterm.
