### ISSUE TITLE
Non-ASCII symbols mangled in window title

### ISSUE THREAD

**Issue by koterpillar** [wez/wezterm#673]
## Describe the bug

When the window title contains non-ASCII characters, it is mangled when seen the window manager (in decorations and window switcher).

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Version: wezterm 20210405-110924-a5bb5be8
 - The active keyboard layout name: US English

## To Reproduce

Run: `echo -ne "\033]0;♦\007"; cat` and observe the Wezterm window title (on window decorations or in window switcher).

## Configuration

The behavior occurs with default configuration.

## Expected behavior

Window title is `♦` as set by the escape sequence (and correctly reported in the tab bar). Note that Gnome Terminal does show the diamond.

## Screenshots

Mangled title in window decorations:
![mangled window title in decorations](https://user-images.githubusercontent.com/140276/114267788-1e7d1e00-9a41-11eb-86f0-4a9bed644cf3.png)

Mangled title in window switcher:
![mangled window title in window switcher](https://user-images.githubusercontent.com/140276/114267695-87b06180-9a40-11eb-9e94-82db61dcab39.png)

Gnome Terminal with correct window title:
![Gnome Terminal with correct window title](https://user-images.githubusercontent.com/140276/114267826-55ebca80-9a41-11eb-8465-e3ba6d79f6a8.png)

**Comment by wez** [comment]
Are you running under XWayland?  That's the default unless you've set `enable_wayland=true` (not recommended!)

**Comment by wez** [comment]
Reproduced and resolved, thanks for your report!
