### ISSUE TITLE
Incorrect hit targets (off by half a character box) on the tab bar

### ISSUE THREAD

**Issue by koterpillar** [wez/wezterm#677]
## Describe the bug

Hit targets on tabs (inactive tabs and the new tab button) are shifted half a character to the left, and the new tab button _hover_ doesn't take into account the `tab_bar_style.new_tab_hover_right`.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Version: wezterm 20210405-110924-a5bb5be8
 - The active keyboard layout name: US International

## To Reproduce

* Open a few tabs and hover and click around the right border of an inactive tab.
* Add a few characters to `new_tab_left` and `new_tab_right` in `tab_bar_style` and hover around the right border of the new tab button.

## Configuration

The colors are only to clearly see when the hover kicks in.

```
return {
  colors = { tab_bar = { inactive_tab_hover = {
        bg_color = "red",
        fg_color = "white"
  } } },
  tab_bar_style = {
    new_tab_left = "<<<",
    new_tab_right = ">>>",
    new_tab_hover_left = "<<<",
    new_tab_hover_right = ">>>",
  },
}
```

## Expected behavior

* Increase the font size (Ctrl-Shift-+ by default) to make the problem more evident.
* Moving mouse anywhere into the area of each tab (and the new tab button) should hover it (and not a different tab).
* Clicking mouse anywhere in the area taken by each tab should switch to it

## Screenshots

Mouse in tab 1, tab 2 highlighted (and will activate if clicked):
![wrong-hover-1](https://user-images.githubusercontent.com/140276/114294858-b08a3280-9ae4-11eb-9ca3-4443ed4c6ec2.png)

Mouse in tab 3, new tab button highlighted (and will activate if clicked):
![wrong-hover-2](https://user-images.githubusercontent.com/140276/114294861-b1bb5f80-9ae4-11eb-806e-e2195b906074.png)

Mouse in new tab button, nothing highlighted:
![wrong-hover-3](https://user-images.githubusercontent.com/140276/114294863-b3852300-9ae4-11eb-9507-93dfc32d868e.png)

Note that _clicking_ for the new tab button works OK, except, again, the right part of the rightmost character it takes up.

**Comment by koterpillar** [comment]
This 3 feels suspicious:

https://github.com/wez/wezterm/blob/1097f329cf797401884031e55c0a6a4037547f3c/wezterm-gui/src/tabbar.rs#L225

**Comment by koterpillar** [comment]
And the "half a character off" seems to be from:

https://github.com/wez/wezterm/blob/1097f329cf797401884031e55c0a6a4037547f3c/wezterm-gui/src/termwindow/mouseevent.rs#L38

Introduced here:

https://github.com/wez/wezterm/commit/94ca16d9870c937e07d9f646cf60d8bec3e6d828

I would suggest keeping the mouse coordinates as floats and only rounding (with `round()`) when selecting, but comparing as is when determining hover and click targets.

**Comment by wez** [comment]
Thanks for the report.  I've fixed the hover calculation and will think a bit more about the rounding issue.

**Comment by koterpillar** [comment]
There is ample potential to shoot oneself in the foot by providing _different length_ strings for `_left` and `_hover_left` and others too, but I don't have a good solution there.
