### ISSUE TITLE
[macOS] Can't minimize with shortcuts when window_decorations = false 

### ISSUE THREAD

**Issue by davidgm0** [wez/wezterm#679]
## Describe the bug

You can't minimize or maximize using shortcuts if you have set `window_decorations = "NONE",

## Environment (please complete the following information):

 - OS: macOS Big Sur
 - Version: wezterm 20210405-110924-a5bb5be8-75-g88e9ce8f
 - The active keyboard layout name ENG

## To Reproduce

Without `  window_decorations = "NONE",` type `CMD + m`. Wezterm should minimize normally.
Update the configuration and set `  window_decorations = "NONE",`. Typing `CMD + m` should minimize wezterm, but it doesn't.
The same happens if you have shortcuts set for maximize or full screen.

I would expect that you are able to still use the shortcuts, even if the title bar is not there (with alacritty I could do so, so I imagine it is possible).

## Configuration

```
local wezterm = require 'wezterm';
return {
  default_prog = {"/usr/local/bin/zsh", "-l"},
  font_size = 12,
  hide_tab_bar_if_only_one_tab = true,
  window_decorations = "NONE",
}
```

**Comment by wez** [comment]
This is fixed in aea4fd5020e79932663d659e45f384367a5bf126 and should show in the nightly builds in 20-30 minutes!

**Comment by eugenesvk** [comment]
@wez while testing WezTerm on macOS I've encountered a similar issue — with `window_decorations = "NONE",` I can't **resize** the window via a **window manager**. Before you say "duh, you have no resize border", I can still resize without a resize border on Windows.
Is this just a dumb **macOS limitation** where resize border is required for you to be able to resize a window?
Or is this something WezTerm can further tweak and allow without enabling the border (I don't like the cursor changes on the border and am never using the tiny border to resize as there are more convenient ways)
Thanks!

**Comment by wez** [comment]
That's just how it works on macOS
