### ISSUE TITLE
Use cp -R instead of cp -r

### ISSUE THREAD

**Issue by ryandesign** [wez/wezterm#680]
ci/deploy.sh uses `cp -r`. The `-r` flag is obsolete. Per the cp(1) manpage,

> Historic versions of the cp utility had a -r option.  This implementation supports that option; however, its use is strongly discouraged, as it does not correctly copy special files, symbolic links, or fifo's.

Use `-R` instead.

**Comment by wez** [comment]
I'm not especially motivated to change this; `-r` has been part of `cp` forever and isn't going away, and wezterm doesn't deploy special files, symbolic links or fifos.

**Comment by ryandesign** [comment]
How stupid.

**Comment by wez** [comment]
Ryan, you're welcome to disagree with me on technical points, but please keep your behavior and communication civil and respectful of others.

**Comment by SuperSandro2000** [comment]
My manpage treats them equally. 

```
       -R, -r, --recursive
              copy directories recursively
```

**Comment by nclements** [comment]
> My manpage treats them equally.
> 
> ```
>        -R, -r, --recursive
>               copy directories recursively
> ```

For information only, it looks like a Linux vs. MacOS difference. My MacOS box says it's deprecated, my Linux boxes say otherwise.

**Comment by SuperSandro2000** [comment]
MacOS has really old coreutils and bash versions.
