### ISSUE TITLE
Text rendering differences between iTerm and WezTerm

### ISSUE THREAD

**Issue by Jarred-Sumner** [wez/wezterm#681]
## Text rendering differences between iTerm and WezTerm

Continuing from https://github.com/wez/wezterm/issues/639#issuecomment-817391807

I set both color schemes to `3024 Night`. These are using the same base font. 

Left:  WezTerm
Right: iTerm
<img src="https://user-images.githubusercontent.com/709451/114325694-4b374100-9ae6-11eb-81eb-7fb7acd4ec1d.png" height=420 /> <img src="https://user-images.githubusercontent.com/709451/114325676-38247100-9ae6-11eb-9d90-77d2d988a5a9.png" height=420 />

Honestly, I'm not sure what precisely makes the iTerm text rendering here look better. It feels like it's something to do with line height, font weight, and/or vertical text alignment. I haven't manually set the bold font on either WezTerm or iTerm, though both are set to the same regular/base font. It is interesting that the nerd font glyphs have a smaller size in iTerm, but I don't think that's the main difference.

Do you have any ideas?

Zoomed in WezTerm:
![image](https://user-images.githubusercontent.com/709451/114326023-b2a1c080-9ae7-11eb-9e78-f5bb552f7730.png)

Zoomed in iTerm:
![image](https://user-images.githubusercontent.com/709451/114326035-bcc3bf00-9ae7-11eb-86eb-9abd80e9ea1a.png)

## Environment (please complete the following information):

 - OS: macOS
 - Version: `wezterm 20210405-110924-a5bb5be8-77-g903c7a47`

**Comment by wez** [comment]
Is this the config you're using?

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("MesloLGSDZ Nerd Font"),
  foreground_text_hsb = {
      hue = 1.0,
      saturation = 1.0,
      brightness = 0.9,  -- default is 1.0
  },
  font_size = 12,
  freetype_load_target = "Light",
  freetype_render_target = "HorizontalLcd",
}
```

iTerm2 uses the mac font rasterizer, and I don't think that uses subpixel AA (which is what is enabled by `HorizontalLcd`).  A more similar configuration for comparison purposes would be this:

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("MesloLGSDZ Nerd Font"),
  font_size = 12,
}
```

Would you mind sharing some zoomed in screenshots comparing that against your iTerm2?

**Comment by Jarred-Sumner** [comment]
With the WezTerm config set as this:
```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("MesloLGSDZ Nerd Font"),
  color_scheme = "3024 Night",
  font_size = 12,
}
```


**iTerm**:
![image](https://user-images.githubusercontent.com/709451/114344841-6b322900-9b15-11eb-8dab-959fad45a35a.png)

**WezTerm**:
![image](https://user-images.githubusercontent.com/709451/114344862-738a6400-9b15-11eb-82e1-5f6305432c00.png)

**iTerm**:
![image](https://user-images.githubusercontent.com/709451/114345305-4ee2bc00-9b16-11eb-8bf0-e1df6506b06d.png)


**WezTerm**:
![image](https://user-images.githubusercontent.com/709451/114345261-412d3680-9b16-11eb-8d96-7ae09043d63e.png)


One thing that's interesting about iTerm's config -- you can set a minimum contrast and to automatically brighten bold text:
![image](https://user-images.githubusercontent.com/709451/114344990-bba98680-9b15-11eb-9c7b-05f87140e07f.png)

I do think the cause here is something related to vertical text alignment, `line-height`, `letter-spacing` or a combination thereof.

Does that help?

**Comment by wez** [comment]
TBH, I can't really spot much difference between those screen shots!  I think the glyphs appear to be rendered about the same now - no subpixel AA and they appear to have very similar AA if you zoom in on your zoomed in shots.

Settings you may want to experiment with:

* https://wezfurlong.org/wezterm/config/lua/config/allow_square_glyphs_to_overflow_width.html - `allow_square_glyphs_to_overflow_width = "Never"` if you don't want the file icons to be so large
* https://wezfurlong.org/wezterm/config/appearance.html#window-padding to add window border padding
* https://wezfurlong.org/wezterm/config/lua/config/line_height.html to adjust the line-height
* https://wezfurlong.org/wezterm/config/lua/config/bold_brightens_ansi_colors.html is the equivalent to the "Brighten bold text" option, which is also enabled by default in wezterm
