### ISSUE TITLE
Can't get Bold font to work.

### ISSUE THREAD

**Issue by 0neGal** [wez/wezterm#684]
## Describe the bug

This is not so much as much as me being a doofus not knowing how the whole config works.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: 20210405-110924-a5bb5be8
 - The active keyboard layout name: US

## To Reproduce

Trying to get **RobotoMono Nerd Font Medium** to work I tried doing the following:
```lua
font = w.font_with_fallback({
	"RobotoMono Nerd Font Medium",
	"Roboto Mono",
	"Noto Sans Mono",
	"Cantarell",
}),
```

And that doesn't work, it errors out complaining it doesn't exist while **Roboto Mono Medium** does exist (the non-nerd font version), and the font is supposed to say **RobotoMono** without a space in the nerd font, which is weird but that's how it is.

The name I put in the config is the exact one found from `fc-list` so I can't really find out how it works, it's likely some inner workings of how fonts work that I don't understand, so please help if you can :p

## Configuration

See above, nothing else here should be relevant as that's the only font related settings I have.

## Expected behavior
Roboto Mono with Nerd Font is displayed in bold or medium

**Comment by wez** [comment]
I'd suggest trying the nightly build: a number of changes have been made to make resolving fonts with different weights better in the nightly, and there are now expanded docs on how to specify fonts over here:
https://wezfurlong.org/wezterm/config/lua/wezterm/font.html

I suspect that you want to use this for your font config:

```lua
font = w.font_with_fallback({
	"RobotoMono Nerd Font",
	"Roboto Mono",
	"Noto Sans Mono",
	"Cantarell",
}, {weight="Medium"}),
```

**Comment by 0neGal** [comment]
It works!

On an unrelated note now that I have you, is there any way to change the color of the text selection and turn off the auto unselect, it's been bugging me real good. After that you can close the issue...

**Comment by wez** [comment]
You can configure the selection text using this:

```lua
return colors = {
   selection_fg = "black",
   selection_bg = "#fffacd"
}
```

I'm not sure what you mean by auto-unselect; can you expand on what you're seeing?

**Comment by 0neGal** [comment]
More or less every few seconds it unselect everything, it happens mid selection or if I hold my selection, been a real pain selecting anything.

I presume from your reaction this isn't intentional...

**Comment by wez** [comment]
No! Please open a separate issue describing how to reproduce that!
I'll close this one out as we've addressed the original question.
