### ISSUE TITLE
Support indicator for when leader key is active and awaiting input

### ISSUE THREAD

**Issue by EpocSquadron** [wez/wezterm#686]
It would be nice to have visual indication when the leader key is active.

In tmux I was able to query the leader state and display an icon/glyph in the status area which would act as visual indication of the leader state being active, which would disappear otherwise. It would be nice to be able to do much the same from configuration for the right status area. Likely this would just be a method accessible from lua, although perhaps there might need to be some event emitted?

**Comment by wez** [comment]
I just pushed a couple of commits that allow this:

```lua
local wezterm = require 'wezterm';

wezterm.on("update-right-status", function(window, pane)
  local leader = ""
  if window:leader_is_active() then
    leader = "LEADER"
  end
  local dead = ""
  if window:dead_key_active() then
    dead = "DEAD"
  end
  window:set_right_status(leader .. " " .. dead)
end);

return {
  leader = { key="a", mods="CTRL" },
  colors = {
    dead_key_cursor = "orange",
  },
}
```
