### ISSUE TITLE
Process exiting in inactive tab causes the whole window to disappear

### ISSUE THREAD

**Issue by koterpillar** [wez/wezterm#690]
## Describe the bug

When a process exits (cleanly) in an inactive tab, the whole WezTerm window disappears and takes mouse cursor with it.

## Environment (please complete the following information):

 - OS: macOS
 - Version: wezterm 20210405-110924-a5bb5be8
 - The active keyboard layout name: Australian English

## To Reproduce

* Run `exec sleep 3` in the shell.
* Quickly create a new tab.
* Wait for 3 seconds.

## Configuration

Happens with default configuration.

## Expected behavior

The inactive tab should disappear, leaving the new tab as the only one.

## Actual behavior

The whole WezTerm window disappears. The mouse cursor also disappears. The way out is to Alt-Tab to a different program, right click WezTerm in the Dock and Quit it.

**Comment by wez** [comment]
Can you try this in the nightly build?

**Comment by koterpillar** [comment]
Same behavior with `wezterm 20210405-110924-a5bb5be8-86-g776aedf9`.

**Comment by wez** [comment]
oh weird, I can reproduce this too!

**Comment by wez** [comment]
I've pushed a fix; it should show up in the nightly downloads within the next 20 minutes or so
