### ISSUE TITLE
Hardware acceleration not used on Intel GPU (lag, high CPU usage)

### ISSUE THREAD

**Issue by pinpox** [wez/wezterm#691]
## Describe the bug

Using a reasonably modern `Intel(R) Core(TM) i7-8550U CPU` with integrated graphics, wezterm is very laggy and shows very high CPU usage, which leads me to the assumption, that it's not using the GPU's hardware acceleration, but instead rendering everything on the CPU with software. 

The exact GPU is: `00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)`

- To clarify, other terminals with GPU acceleration (i.e. alacritty) don't show this issue at all on the same hardware.
- The same wezterm build on different hardware (desktop PC, also linux, but with an AMD Ryzen + Nvidia GPU) does not have the problem. 

I could only reproduce this issue on this notebook, as I don't have other hardware with intel GPU to try it on.

To reproduce, just let wezterm render something, e.g. by holding down one key. 

Here is a screenshot, showing `htop`  and `intel-gpu-top` while holding down a key in wezterm
![image](https://user-images.githubusercontent.com/1719781/114540606-07634980-9c56-11eb-94e1-b5bb048dfd55.png)

`intel-gpu-top` does show higher usage when typing in wezterm compared with just having it open:
![image](https://user-images.githubusercontent.com/1719781/114540843-4d201200-9c56-11eb-816e-246911dd8e95.png)
![image](https://user-images.githubusercontent.com/1719781/114540885-57daa700-9c56-11eb-90cc-3c9fabad92ab.png)
The `Render/3D/0` value is not very steady though, so it's a bit hard to pin down the exact usage precentage wezterm produces.

To make sure that the system actually *can* use hardware acceleration, I did a benchmark with `glxgears`. It fully utilizes the GPU and gives me around 300 fps:
![image](https://user-images.githubusercontent.com/1719781/114541277-c91a5a00-9c56-11eb-92a7-b29ecbace8ec.png)

When starting wezterm, I get the following output:
```
  wezterm
 2021-04-13T10:50:23.065Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-376325
 2021-04-13T10:50:23.196Z INFO  wezterm_gui::termwindow        > OpenGL initialized! llvmpipe (LLVM 11.1.0, 256 bits) OpenGL ES 3.2 Mesa 21.0.1 is_context_loss_possible=false wezterm version: 20210405-110924-a5bb5be8-86-g776aedf9
```

## Environment:

 - OS: Linux X11
 - Version: wezterm 20210405-110924-a5bb5be8-86-g776aedf9
 - The active keyboard layout name: colemak
 - 
## To Reproduce

Steps to reproduce the behavior.

Run wezterm on this hardware.

## Configuration

My full configuration is here: https://gist.github.com/pinpox/2638b113f4f377abe7557178ff8c82a5

## Expected behavior
Higher GPU usage, lower CPU usage, no lags and input delay when typing.

## Screenshots

see above.

## Additional context
Hardware:
```
System:
  Kernel: 5.10.27 x86_64 bits: 64 Desktop: N/A
  Distro: NixOS 21.05.20210410.a73020b (Okapi)
Machine:
  Type: Laptop System: LENOVO product: 20L7CTO1WW
  v: ThinkPad T480s serial: <filter>
  Mobo: LENOVO model: 20L7CTO1WW
  v: SDK0J40697 WIN serial: <filter> UEFI: LENOVO
  v: N22ET49W (1.26 ) date: 09/13/2018
Battery:
  ID-1: BAT0 charge: 47.8 Wh (98.8%)
  condition: 48.4/57.0 Wh (84.9%)
CPU:
  Info: Quad Core model: Intel Core i7-8550U
  bits: 64 type: MT MCP cache: L2: 8 MiB
  Speed: 4000 MHz min/max: 400/4000 MHz
  Core speeds (MHz): 1: 4000 2: 3860 3: 3988
  4: 4001 5: 3701 6: 3820 7: 3977 8: 4000
Graphics:
  Message: No Device data found.
  Device-1: SunplusIT Integrated Camera type: USB
  driver: uvcvideo
  Display: server: X.org 1.20.10 driver:
  loaded: ati,modesetting
  unloaded: amdgpu,fbdev,nouveau
  resolution: <missing: xdpyinfo>
  Message: Unable to show advanced data. Required
  tool glxinfo missing.
Audio:
  Device-1: HDA Intel PCH driver: HDA-Intel
  Sound Server-1: ALSA v: k5.10.27 running: yes
  Sound Server-2: PulseAudio
  v: 14.2-rebootstrapped running: yes
Network:
  Message: No Device data found.
  Device-1: Realtek USB 10/100/1000 LAN type: USB
  driver: r8152
  IF: enp0s20f0u4u1u1 state: up speed: 1000 Mbps
  duplex: full mac: <filter>
  IF-ID-1: docker0 state: down mac: <filter>
  IF-ID-2: enp0s31f6 state: down mac: <filter>
  IF-ID-3: vboxnet0 state: down mac: <filter>
  IF-ID-4: wg0 state: unknown speed: N/A
  duplex: N/A mac: N/A
  IF-ID-5: wlp61s0 state: up mac: <filter>
Bluetooth:
  Device-1: CSR8510 A10 type: USB driver: btusb
  Report: This feature requires one of these
  tools: hciconfig/bt-adapter
  Device-2: N/A type: USB driver: btusb
Drives:
  Local Storage: total: 465.76 GiB
  used: 94.66 GiB (20.3%)
  ID-1: /dev/nvme0n1 vendor: Samsung
  model: SSD 970 EVO 500GB size: 465.76 GiB
Partition:
  ID-1: / size: 449.08 GiB
  used: 94.59 GiB (21.1%) fs: ext4 dev: /dev/dm-2
  ID-2: /boot size: 499 MiB
  used: 71.8 MiB (14.4%) fs: vfat
  dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: partition size: 8 GiB
  used: 0 KiB (0.0%) dev: /dev/dm-1
Sensors:
  System Temperatures: cpu: 43.0 C mobo: N/A
  Fan Speeds (RPM): cpu: 0
Info:
  Processes: 204 Uptime: 13h 26m
  Memory: 23.26 GiB used: 2.23 GiB (9.6%)
  Shell: Zsh inxi: 3.3.03
 ```

`about:support` from firefox (shows more GPU related stuff)
![image](https://user-images.githubusercontent.com/1719781/114542649-75a90b80-9c58-11eb-9bae-0577847a34ea.png)

**Comment by gwww** [comment]
I was just collecting data on the same bug. I did not conclude that the GPU is not being used, but it does appear to a highly probable cause.

I have a `wt-record` log running the second scenario. How to best share it, as github won't let me attach a `.tgz` file to an issue?

I also have two screen recordings. Both running `vim` and holding down the `j` key to scroll through a file. On `iTerm2` it scrolls through about 120 lines in ~2 seconds. On `wezterm` its more like 12 seconds.

https://user-images.githubusercontent.com/3060128/114565338-2b676080-9c3f-11eb-94f8-d23dd7fd0ef5.mov

https://user-images.githubusercontent.com/3060128/114565356-2efae780-9c3f-11eb-992d-b88495469263.mov

**Comment by pinpox** [comment]
@gwww While looking for a solution I stumbeld across `vainfo`, which should be able to tell if the driver is correctly working. For me the output looks like this:
```
vainfo


error: XDG_RUNTIME_DIR not set in the environment.
libva info: VA-API version 1.11.0
libva info: Trying to open /run/opengl-driver/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.11 (libva 2.11.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      ```
      
I'm not sure that command exists on macOS,  is there something comparable? Firefox seems to have it's own problems with hardware acceleration on linux and I'm looking for a definite way of figuring out whether the acceleration does at all work on my system. Not sure how much this helps, I was expecting glxgears to be way worse if only software rendering is working.

**Comment by pinpox** [comment]
I have found the problem, it was a misconfiguration on my side and not related to wezterm. 

This was still set, from an old workaroud I had needed for a broken alacritty which I was previously using.
```
echo $LIBGL_ALWAYS_SOFTWARE
1
```

Removing the line solved the issue for me. I no longer see any noticiable CPU usage when typing in wezterm and the input lag is not present. @gwww I'll close this as the original issue is solved, feel free to reopen if the problem is a different one for you.
