### ISSUE TITLE
Typo in Documentation of SpawnCommandInNewTab

### ISSUE THREAD

**Issue by odrevet** [wez/wezterm#700]
In the  SpawnCommandInNewTab documentation the example configuration call SpawnCommandInNewWindow

https://wezfurlong.org/wezterm/config/lua/keyassignment/SpawnCommandInNewTab.html

**Comment by bew** [comment]
Feel free to fix the typo yourself by editing the files in https://github.com/wez/wezterm/blob/main/docs/config/lua/keyassignment/SpawnCommandInNewTab.md and making a PR to suggest your changes :smiley:
