### ISSUE TITLE
Feature Request: Swapping the foreground color and the background color

### ISSUE THREAD

**Issue by zhou13** [wez/wezterm#706]
**Is your feature request related to a problem? Please describe.**
Many terminals support to swap the fg and bg color as the color under the cursor. However, I search through the document and I cannot find an example of this feature. Such a method is better than hardcode the cursor color as it is able to reflect the original color under the cursor.

**Describe the solution you'd like**
In alacritty, I am able to configure like this:
````
  cursor:
    text: CellBackground
    cursor: CellForeground
````

In wezterm, I hope I will be able to do things like
````
return {
  colors = {
      cursor_bg = "fg",
      cursor_fg = "bg",
  }
}
````
**Describe alternatives you've considered**
N./A.
**Additional context**
N./A.

**Comment by wez** [comment]
Are you looking specifically for the ability to configure colors in terms of the foreground/background, or would you be satisfied with a separate option that overrides the cursor color setting and forces it into reverse video mode?

**Comment by zhou13** [comment]
It would be the latter one, as in the reverse video mode.

**Comment by wez** [comment]
in the next nightly build (in about 20-30 mins), you can set `force_reverse_video_cursor = true`

**Comment by zhou13** [comment]
It seems that `force_reverse_video_cursor` no longer works for me.

**Comment by wez** [comment]
It works for me with a quick test here; could you open a new bug issue with all the information needed to reproduce the issue?

**Comment by zhou13** [comment]
I take a look at the code. When the setting is enabled, it simply uses `palette.background` to replace `palette.cursor_fg`. This is not useful, as I can directly set `palette.cursor_fg` to be the color in `palette.background`. The intended results should be swaping the fg and bg color of the character under the cursor, rather than choosing from a predetermined palette.

Alacritty result:
![image](https://user-images.githubusercontent.com/576382/123038677-d6726400-d3be-11eb-88c1-8812710105fe.png)

wezterm result:
![image](https://user-images.githubusercontent.com/576382/123038609-bcd11c80-d3be-11eb-9d52-f56e50506c40.png)

**Comment by AtifChy** [comment]
@zhou13 how do you enable dynamic cursor color on wezterm?

**Comment by wez** [comment]
I just pushed a fix for this; it should show up in the nightly builds in ~30 minutes.

@AtifChy https://wezfurlong.org/wezterm/config/lua/config/force_reverse_video_cursor.html

**Comment by zhou13** [comment]
Looks like it works correctly. Thank you!
