### ISSUE TITLE
Add option to swallow click event when the click focuses a pane

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#724]
**Is your feature request related to a problem? Please describe.**
"I'm frustrated when" I click on a pane to focus and I'm in an editor (oh, say vim) and my position in the editor moves to where I just clicked.

**Describe the solution you'd like**
When a pane is not focused and I click on the pane the click is not passed through to the terminal. When I am focused on the pane clicks pass through to the terminal.

**Describe alternatives you've considered**
None really, other than don't click to focus.

**Comment by wez** [comment]
This is related (in that its in the same area of code) to https://github.com/wez/wezterm/issues/600

**Comment by gwww** [comment]
Tested and works. Thank you! This is a nice quality of use feature!
