### ISSUE TITLE
Sarasa-Gothic fonts not being recognized in nightly or latest commit

### ISSUE THREAD

**Issue by JavaCafe01** [wez/wezterm#726]
I had this as a discussion, but I'll transfer it over to a bug report.

## Describe the bug

Wezterm does not recognize the `Sarasa Mono K` font from [Sarasa-Gothic](https://github.com/be5invis/Sarasa-Gothic). Wezterm stable, however, works perfectly fine with this font.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: Latest Commit
 - ENG

## To Reproduce

* Use the latest commit of wezterm
* Set `Sarasa Mono K` as font

## Configuration/Logs

[config](http://0x0.st/-AoQ.txt)
[stdout](http://0x0.st/-AXu.txt)
[stdin](http://0x0.st/-AXQ.txt)
[`fc-match -v "Sarasa Mono K"`](http://0x0.st/-AX2.txt)

## Expected behavior
The font should be used and no error should appear.

**Comment by wez** [comment]
@JavaCafe01 I think this is because that font doesn't define a `spacing` value in the fontconfig output.  I've pushed a change that might help; please give the next nightly build a try (~20 minutes), or update and then build from source if you're already doing that.

**Comment by JavaCafe01** [comment]
Thanks @wez! The font works perfectly now. Gonna close this as it's solved, and I will also close the discussion.
