### ISSUE TITLE
Can't run wezterm on Amazon Linux

### ISSUE THREAD

**Issue by d5ve** [wez/wezterm#728]
Wezterm looks great. I'm trying to install the server end on an AWS EC2 instance running Amazon Linux, but it won't start due a glibc issue. 

Below is a three-command reproduction using the appimage.

```
$ curl -sLO https://github.com/wez/wezterm/releases/download/20210405-110924-a5bb5be8/WezTerm-20210405-110924-a5bb5be8-Ubuntu16.04.AppImage
$ chmod +x WezTerm-20210405-110924-a5bb5be8-Ubuntu16.04.AppImage 

$ ./WezTerm-20210405-110924-a5bb5be8-Ubuntu16.04.AppImage

./WezTerm-20210405-110924-a5bb5be8-Ubuntu16.04.AppImage: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./WezTerm-20210405-110924-a5bb5be8-Ubuntu16.04.AppImage
```

The OS is Amazon Linux AMI 2018.03.

```
$ cat /etc/os-release | grep PRETTY
PRETTY_NAME="Amazon Linux AMI 2018.03"

$ uname -a
Linux ip-172-31-5-206 4.14.203-116.332.amzn1.x86_64 #1 SMP Fri Oct 30 18:56:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I have also tried using `linuxbrew`, but that shows the same error.

I thought that an appimage would contain its own glibc etc, but I must have misunderstood.

Has anyone had success installing wezterm on Amazon Linux?

**Comment by wez** [comment]
the appimage is built for and targets an older debian style distribution.  Are any of the other deb or rpm packages options for installation in that environment?  If not, then I'd suggest building from source.

**Comment by d5ve** [comment]
I tried the EL7 and EL8 RPMs, but they both had dependencies that are not easily available in Amazon Linux.

I'll try building from source, thanks.

**Comment by d5ve** [comment]
The system rust and cargo are too old for a source compile.

```
$ sudo yum install -y rust cargo
$ curl -LO https://github.com/wez/wezterm/releases/download/20210405-110924-a5bb5be8/wezterm-20210405-110924-a5bb5be8-src.tar.gz
$ tar -xzf wezterm-20210405-110924-a5bb5be8-src.tar.gz
$ cd wezterm-20210405-110924-a5bb5be8
$ ./get-deps
Installed rustc version 1.38.0 is less than required 1.51.0
```

The rustup method installs a modern-enough rustc, but `get-deps` failed for a missing `lsb_release`

I got `lsb_release` release installed by installing `redhat-lsb` (which nearly filled up the root partition), then `get-deps` failed as it didn't know how to install the deps for Amazon Linux.

```sh
$ sudo yum remove -y rust cargo
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ ./get-deps
Please contribute the commands to install the deps
For "Amazon Linux AMI release 2018.03"
```

I'll see if I can find equivalents for for the required dependencies in Amazon Linux.

**Comment by d5ve** [comment]
I was unable to find all the dependencies, as Amazon Linux is missing some of the GUI ones.

**Is it possible to build just the server component of wezterm?**

My usecase is connecting from a macos machine to a headless Amazon Linux box. The linux box won't ever be running the client components, just the server end. I'm trying to replace my current setup of mosh + GNU screen.

```
$ sudo yum install $(cat wezterm_build_dependencies.txt) 2>&1 | grep 'No package'
No package perl-FindBin available.            # <-- Already installed with system perl.
No package perl-File-Compare available.       # <-- Already installed with system perl.
No package python3 available.                 # <-- python36 available.
No package libxkbcommon-devel available.      # <-- Not available.
No package libxkbcommon-x11-devel available.  # <-- Not available.
No package wayland-devel available.           # <-- Not available.
```

**Comment by jankatins** [comment]
Rust allows you to compile a complete static build with musl instead of a dynamically linked glibc. So you could compile that on why linux computer and then copy that over (assuming wezterm compile in that setting).

**Comment by wez** [comment]
You can do this:

```
cd $WEZTERM    # the wezterm git repo
cd wezterm-mux-server
cargo build --release
```

to build just the multiplexer server.  That has no gui dependencies.  The compiled binary can then be found in `$WEZTERM/target/release/wezterm-mux-server`, and you can manually install that to eg: `/usr/local/bin`.

```
; ldd ./target/release/wezterm-mux-server
        linux-vdso.so.1 (0x00007fffe01e0000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f53e39cd000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f53e36e0000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f53e36c6000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f53e34fb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f53e46c4000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f53e34e0000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f53e34db000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f53e34b7000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f53e3371000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f53e336a000)
```

**Comment by d5ve** [comment]
Great, that worked thanks!

The full steps are below. The server I was compiling on seemed to already have all the required packages to compile the server. I didn't have to install anything from the list in the `get-deps` script. The server has been running for a few years now, though and I may have installed some in the past.

```sh
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ source $HOME/.cargo/env
$ curl -LO https://github.com/wez/wezterm/releases/download/20210405-110924-a5bb5be8/wezterm-20210405-110924-a5bb5be8-src.tar.gz
$ tar -xzf wezterm-20210405-110924-a5bb5be8-src.tar.gz
$ cd wezterm-20210405-110924-a5bb5be8
$ cd wezterm-mux-server
$ cargo build --release
$ sudo cp ../target/release/wezterm-mux-server /usr/local/bin
$ wezterm-mux-server --help
wezterm-mux-server 20210405-110924-a5bb5be8
Wez's Terminal Emulator
http://github.com/wez/wezterm

USAGE:
    wezterm-mux-server [FLAGS] [OPTIONS] [--] [prog]...

FLAGS:
        --daemonize    Detach from the foreground and become a background process
    -h, --help         Prints help information
    -n                 Skip loading wezterm.lua
    -V, --version      Prints version information

OPTIONS:
        --config-file <config-file>    Specify the configuration file to use, overrides the normal configuration file
                                       resolution
        --cwd <cwd>                    Specify the current working directory for the initially spawned program
        --config <name=value>...       Override specific configuration values

ARGS:
    <prog>...    Instead of executing your shell, run PROG. For example: `wezterm start -- bash -l` will spawn bash
                 as if it were a login shell
```
