### ISSUE TITLE
~/.ssh/config parsing doesn't support expansion of ~/

### ISSUE THREAD

**Issue by d5ve** [wez/wezterm#729]
The new SSH config file parsing doesn't seem to support expansion of `~/`

I share my ~/.ssh/config between a macos and a linux machine. I was unable to use `wezterm ssh` until I replaced `IdentityFile ~/.ssh/id_rsa-my-server` with `IdentityFile /Users/d5ve/.ssh/id_rsa-my-server` on the macos machine.

Would it be possible to support expansion of  `~/`in the config parsing?

```
$ wezterm -V
wezterm 20210405-110924-a5bb5be8

# Non-working IdentifyFile
$ cat ~/.ssh/config
Host my-server
    Hostname 1.2.3.4
    User d5ve
    IdentityFile ~/.ssh/id_rsa-my-server
$ wezterm ssh my-server
SH-2.0-OpenSSH_7.4
Error: authentication: [Session(-13)] Failed getting response

# Working IdentityFile
$ cat ~/.ssh/config
Host my-server
    Hostname 1.2.3.4
    User d5ve
    IdentityFile /Users/d5ve/.ssh/id_rsa-my-server
$ wezterm ssh my-server
SSH-2.0-OpenSSH_7.4
Last login: Sun Apr 25 10:43:52 2021 from 6.7.8.9
```

**Comment by wez** [comment]
That's a reasonable request.  In the meantime, you should be able to use `%d` or `${HOME}` in place of the hard-coded home directory in your ssh config file.
