### ISSUE TITLE
[REQUEST] Checking wezterm.exe folder for wezterm.toml

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#73]
Wow, I've been looking for something like this for quite some time. I'd really like to use this on a thumbstick so I can use it instead of command prompt, only problem is, I'd have to put a config file on the computer I'm working on.

Could you make wezterm check its own directory for its toml file before it checks the $HOME locations? (After all, on the off-chance that someone else is using it as well, I'd want my own configuration to take priority.)

**Comment by wez** [comment]
Thanks for the suggestion!

I've pushed a commit that implements this behavior; a build should show up in the artifacts download section of this GH action run when it completes: https://github.com/wez/wezterm/runs/338534011, and it will show up in the nightly build when that next kicks off.

**Comment by ImportTaste** [comment]
It works great! Thanks so much!

**Comment by ImportTaste** [comment]
@wez Hm, actually a thought just occurred to me, and I hesitate to ask because it's not really a big deal and this change on its own is all I really needed.

Could it be allowed to load fonts stored in the portable config directory? Again, it's somewhat trivial since I doubt anyone would care if I installed my [font of choice](https://github.com/microsoft/cascadia-code/releases) to their machine, but it would be convenient. The check could be reserved for when it's loaded from a portable config, and it would make sense for the "portable font" to take precedence since fonts do get updated with more frequency these days.

**Comment by wez** [comment]
@ImportTaste I like that idea too; would you mind opening a separate issue for it?  It's a bit more involved to make that change because font loading has a different implementation on each platform and it might need to get done after some other work I'm considering for the font subsystem.  That said, the loader on Windows is the easiest to change, so I may be able to squeak that without too much fuss.

**Comment by ImportTaste** [comment]
@wez Just got home from work, I would've opened an issue but it looks like you already implemented it if I'm reading correctly. Appreciate it! 👍
