### ISSUE TITLE
Do SSH Domains support ~/.ssh/config and IdentityFile?

### ISSUE THREAD

**Issue by d5ve** [wez/wezterm#730]
I can connect to a remote host with `wezterm ssh my-server` and it uses the Hostname, User, and IdentityFile settings from my `~/.ssh/config`.

However, I can't see how to use those settings when setting up a SSH Domain. And then running `wezterm connect my-server` fails to connect as `my-server` is set up to only use SSH keys.

`/var/log/secure` shows lines like the following for the failed connection.
```
sshd[31660]: error: maximum authentication attempts exceeded for d5ve from 6.7.8.9 port 27550 ssh2 [preauth]
sshd[31660]: Disconnecting: Too many authentication failures [preauth]
```

My wezterm config file on the client end looks like:
```
$ cat ~/.config/wezterm/wezterm.lua
local wezterm = require 'wezterm';
return {
    ssh_domains = {
        {
            name = "my-server",
            remote_address = "1.2.3.4",
            username = "d5ve",
        }
    }
}
```

```
$ wezterm -V
wezterm 20210405-110924-a5bb5be8
```

I've tried blindly adding extra config to `wezterm.lua`, but it only handles the following keys:

```
Ignoring unknown field `identityfile` in struct of type `SshDomain`. Possible fields are `connect_automatically`, `name`, `no_agent_auth`, `remote_address`, `remote_wezterm_path`, `timeout`, `username`.
```

Is it intended that the wezterm will support parsing values from `~/.ssh/config`? Or will extra keys be added to `wezterm.lua`? I know that the SSH features are pretty new, sorry!

**Comment by wez** [comment]
It doesn't today, but it should be taught to also at the very least support parsing the .ssh/config file, and probably also support a way to override ad-hoc config items, perhaps using something like:

```
   ssh_options = {
      identityfile = "/some/thing",
   }
```

**Comment by wez** [comment]
Hmm, looking at this a bit more closely, it *should* be picking up from the ssh_config already, but I think the critical piece is the `remote_address = "1.2.3.4"` in your domain settings rather than `remote_address = "my-server"`.  I'm assuming that your `~/.ssh/config` matches based on `my-server` rather than its IP address, in which case it may not pick up everything that you wanted from the config.

**Comment by wez** [comment]
I've pushed a commit that makes the logic a bit cleaner in the code, and will let you config things a little more tersely; username can now be omitted if you want to use the usual ssh default:

```lua
local wezterm = require 'wezterm';
return {
    ssh_domains = {
        {
            name = "my-server",
            remote_address = "my-server",
        }
    }
}
```

**Comment by d5ve** [comment]
Many thanks Wez!

I changed it so that `remote_address` in `wezterm.lua` exactly matched the `Host` field in `~/.ssh/config`, and the SSH connection started using the correct ssh key.
