### ISSUE TITLE
Add letter hints for selecting instances of saved searches

### ISSUE THREAD

**Issue by rodolf0** [wez/wezterm#732]
Would it be feasible to provide letter hints while doing scrollback search for easier selection of snippets?

- Tmux has a similar plugin to this https://github.com/Morantron/tmux-fingers. 
- Vim plugin easymotion has a related feature for jumping around too https://github.com/easymotion/vim-easymotion

How would this work?
1. When triggering a pre-configured search (as in https://wezfurlong.org/wezterm/scrollback.html#configuring-saved-searches), each highlight would be prefixed by an alphanumeric char. Example `[a-z0-9]-<search-result>`. 
2. Pressing the keyboard key for that char/hint would copy the instance of the search result directly. (Possibly exiting search mode and pasting it too)

**Comment by wez** [comment]
someone previously mentioned https://github.com/fcsonline/tmux-thumbs and I think it would be great to have something like this integrated in our search functionality

**Comment by wez** [comment]
I just pushed the first draft at this kind of feature; it will show up in the nightly builds in about 20-30 minutes depending on the platform.

To activate, press: <kbd>CTRL</kbd><kbd>SHIFT</kbd><kbd>SPACE</kbd>

TODO:

* [ ] Configurable alphabet
* [ ] Configurable patterns
* [ ] docs
