### ISSUE TITLE
numpad Enter key sends ^C on mac

### ISSUE THREAD

**Issue by JoyceBabu** [wez/wezterm#739]
## Describe the bug

I have a magic keyboard with a <kbd>return</kbd> key and an <kbd>enter</kbd> key below the number pad. If I press the <kbd>enter</kbd>, it is sending a <kbd>ctrl-c</kbd> sequence, causing the running program to quit.

But this does not happen on `Terminal`, `iTerm` or `Kitty`.

## Environment (please complete the following information):

 - OS:  macOS
 - Version: wezterm 20210405-110924-a5bb5be8
 - English US

## To Reproduce

Run any program, for example `tail -f /dev/null` and press the <kbd>enter</kbd> key.

```
joyce@mbp ~ % tail -f /dev/null
^C
```

## Configuration

```lua
local wezterm = require 'wezterm';
local function font_with_sym_fallback(font_family, options)
    return wezterm.font_with_fallback({
        font_family,
        "MesloLGS NF",
        "PowerlineSymbols",
        "Noto Color Emoji", 
    }, options)
end
local env = {}
local launch_menu = {}
if wezterm.target_triple == "x86_64-pc-windows-msvc" then
    default_prog = {"powershell.exe", "-NoLogo"}
else
    table.insert(launch_menu, { label = "bash", args = {"bash", "-l"} })
    table.insert(launch_menu, { label = "fish", args = {"fish", "-l"} })
end
return {
    color_scheme = "JetBrains Darcula",
    font = font_with_sym_fallback("JetBrains Mono",{foreground="#b0b0b0"}),
    font_size = 11.0,
    dpi = 96.0,
    enable_scroll_bar = true,
    scrollback_lines = 100000,
    launch_menu = launch_menu,
    default_cursor_style = "BlinkingBar",
    font_shaper = "Harfbuzz",
    harfbuzz_features = {"kern", "liga", "clig", "calt"},
    font_antialias = "Greyscale",
    font_hinting = "Vertical",
    keys = {
        {key="1", mods="ALT", action=wezterm.action{ActivateTab=0}},
        {key="q", mods="CMD", action=wezterm.action{CloseCurrentTab={confirm=true}}},
        {key="s", mods="CMD", action="Nop"},
    }
}
```

## Expected behavior

The key should send `<CR>` instead of `CTRL-C`.

**Comment by wez** [comment]
if you run `wezterm --config debug_key_events=true` and press enter, what gets logged to stderr?

https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html

**Comment by JoyceBabu** [comment]
<kbd>return</kbd> reports the following event

```
 2021-04-27T07:23:04.118Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\r'), modifiers: NONE, raw_key: None, raw_modifiers: NONE, raw_code: Some(36), repeat_count: 1, key_is_down: true }
```

whereas <kbd>enter</kbd> reports the a different key code

```
 2021-04-27T07:23:08.533Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\u{3}'), modifiers: NONE, raw_key: None, raw_modifiers: NONE, raw_code: Some(76), repeat_count: 1, key_is_down: true }

```

**Comment by wez** [comment]
That ctrl code is coming from macOS itself; I don't know why it maps it to ctrl-c.  I've pushed a commit that works around that, and it should show up in the next nightly build (~30 minutes)
