### ISSUE TITLE
[FEATURE] Flexible Font Loader

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#74]
Initially from https://github.com/wez/wezterm/issues/73#issuecomment-562967942

While this has already been implemented on Windows per my initial request, @wez has expressed interest in making the font loader more flexible for all platforms and asked me to open an issue.

The Windows implementation is here https://github.com/wez/wezterm/commit/1e9d3571ba2d4afc085486e675e459b137786f19 and consists of using the following configuration:
```
font_system = "FontKitAndFreeType"
font_dir = ["fonts"]
```
This expands into a relative path and loads in a font from the `fonts` subdirectory. The Linux and MacOS versions of wezterm could be afforded a similar option.

**Comment by wez** [comment]
This is done, present in today's stable build and docs have been added and pushed, so I'm closing this out.
