### ISSUE TITLE
mac character/emoji picker keyboard shortcut

### ISSUE THREAD

**Issue by spinscale** [wez/wezterm#743]
## Describe the bug

First, thanks a ton for wezterm, installed it over the weekend and like it a lot so far!

## Environment (please complete the following information):

 - OS: macOS
 - Version: `20210405-110924-a5bb5be8`
 - ENG keyboard layout

## To Reproduce

Try hitting `CTRL+CMD+SPACE` under any app. This will show the character viewer to select emojis. However this won't work under wezterm. 

## Configuration

Empty `wezterm.lua` config is sufficient to reproduce.

## Expected behavior

The character viewer should be opened, so that I can insert emojis in the terminal.

**Comment by wez** [comment]
This is a variation on https://github.com/wez/wezterm/issues/162
In the meantime, if you have "Show Input menu bar" enabled under `System Preferences > Keyboard > Input Sources`, the "Show Emoji & Symbols" menubar option will allow showing the emoji picker.  It's not as convenient, but at least it works!

**Comment by spinscale** [comment]
if you're an alfred user, you could use one of the emoji workflows in the meantime as well.. for example https://github.com/jsumners/alfred-emoji

**Comment by wez** [comment]
Nightly builds now have a native macOS menubar which enables this functionality.

You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

**Comment by spinscale** [comment]
Just tested and looks great - Thank you!

![image](https://user-images.githubusercontent.com/667544/212275737-1854e2c7-c615-4705-987d-afbcb6f1a345.png)

**Comment by khiet** [comment]
Thank you for addressing this issue 🙇‍♂️
Migrated from [alacritty due to the same issue](https://github.com/alacritty/alacritty/issues/1895) 🚀
