### ISSUE TITLE
wezterm window losing focus should release mouse grab

### ISSUE THREAD

**Issue by rodolf0** [wez/wezterm#744]
## Describe the bug

Clicking on a hyperlink that triggers `OpenLinkAtMouseCursor` action which changes focus to a different window isn't properly releasing the mouse.

I've only seen this problem when interacting with TMUX. I see this happening in 2 different scenarios (see steps to repro).

## Relevant config snippet
```
  mouse_bindings = {
    -- Change the default click behavior to only selects text, not to open hyperlinks
    {
      event={Up={streak=1, button="Left"}},
      mods="NONE",
      action=wezterm.action{CompleteSelection="PrimarySelection"},
    },
    -- and make CTRL-Click open hyperlinks
    {event={Up={streak=1, button="Left"}}, mods="CTRL", action="OpenLinkAtMouseCursor"},
  },
```

## Steps to reproduce

Scenario 1:
1. With the above config, "Ctrl + Click" on a wezterm hyperlink.
2. Browser (or other handler app) will open the link taking focus away from wezterm.
3. Going back to Wezterm, start tmux, move mouse. This will change tmux visual text selection on mouse move without buttons being held down.

Scenario 2: (pretty similar)
1. Open tmux first. Opening a hyperlink now requires "Shift + Ctrl + Click" (not sure why opening hyperlinks doesn't work without Shift in the mix while using tmux).
2. Browser takes focus away from wezterm.
3. Going back to wezterm and moving mouse affects tmux selection.

## Expected behavior
When focus is taken away from wezterm as a result of browser handling `OpenLinkAtMouseCursor`, mouse state should be cleared so when going back to wezterm, mouse moves don't affect tmux selection.

## Environment (please complete the following information):
 - OS: Linux + Wayland, Fedora 33
 - Version: wezterm 20210405-110924-a5bb5be8

**Comment by wez** [comment]
Thanks for the report! I've pushed a fix for this!

**Comment by rodolf0** [comment]
Not sure what the protocol for closing the bug is. Should I keep this open until it hits a stable release? (I don't mind if its closed now)

**Comment by bew** [comment]
Thanks for this issue I was experiencing this as well!

About `not sure why opening hyperlinks doesn't work without Shift in the mix while using tmux`, this is because when the active program have enabled mousd reporting (to be able to detect mouse clicks, scrolls,. ..) moise bindings now require shift to do their normal actions. 
So click &  drag is sent to the active program, and is not used to select the text in wezterm' pane as it usually is.

I've suggested #581 to have a few bindings work unconditionally the same, maybe you're interested in this as well?

**Comment by wez** [comment]
> Not sure what the protocol for closing the bug is. Should I keep this open until it hits a stable release? (I don't mind if its closed now)

Sometimes I keep it open for a bit if I anticipate there might be further dialog, and similarly, if I haven't written up a changelog item I'll keep it open to remind myself.  I'll close this now :)
