### ISSUE TITLE
MSYS2 Bash - Ctrl-C in (failed reverse-i-search) may cause terminal freeze

### ISSUE THREAD

**Issue by sdbbs** [wez/wezterm#747]
## Describe the bug

I am trying to use MSYS2 bash in Wezterm on Windows 10; this is my `wezterm.lua`:

```
-- [Using 'wezterm ssh', new tab button & actions are inconsistent · Issue #468 · wez/wezterm](https://github.com/wez/wezterm/issues/468)

local wezterm = require("wezterm")
local config = {
      -- https://wezfurlong.org/wezterm/config/files.html
      -- [Can't write ~ in wezterm on mac (german layout) · Issue #410 · wez/wezterm](https://github.com/wez/wezterm/issues/410)

      -- The font size, measured in points
      font_size = 10.0,

      -- (available starting in version 20210203-095643-70a364eb)
      -- Scale the effective cell height.
      -- The cell height is computed based on your selected font_size
      -- and dpi and then multiplied by line_height.  Setting it to
      -- eg: 1.2 will result in the spacing between lines being 20%
      -- larger than the distance specified by the font author.
      -- Setting it to eg: 0.9 will make it 10% smaller.
      line_height = 1.0,
}
local msys2_start_args = {
    "C:\\msys64\\usr\\bin\\env.exe",
    "MSYS=enable_pcon", -- Enable pseudo console API for msys (maybe not needed under wezterm?) Actually, needed - without it, Ctrl-D does not close the terminal!
    "MSYSTEM=MSYS",
    "/bin/bash", "--login",
}
config.default_prog = msys2_start_args
config.launch_menu = {
    {
      label = "msys2 bash",
      args = msys2_start_args,
    },
    {
      label = "DevVM via some server",
      args = {
          wezterm.executable_dir .. "/wezterm",
          "ssh", "my-user@some-server", "--", "vim", -- run vim for the example
      },
    },
}
return config
```

Everything start fine - except ... first this smaller problem, as it might be related:

* `bash` starts
* Hit Ctrl-C - most other shells will just give a new shell prompt line; not here - here we remain on old line
* Hit Ctrl-C again - *now* we get a new shell prompt line

Now, for my actual problem - starting Wezterm fresh again:

* `bash` starts
* Hit Ctrl-R to start "reverse-i-search"
* Type random letters, so we get `(failed reverse-i-search)`
* Now I typically want to exit - and I typically hit Ctrl-C, which on most shells gives me a new prompt line; here, however, nothing happens
    * If right after this first Ctrl-C, I click a letter, I will get a new prompt line which is fine
    * If right after this first Ctrl-C, I hit Ctrl-C again, either I will get a new line, or nothing happens
    * If right after this first Ctrl-C, I hit Ctrl-C again, then Ctrl-R, then letter, -- shell *freezes completely, and I have to shut down the window*

If it doesn't freeze at first attempt, it will freeze at second - and it seems related to how long the first recalled command from history was (i.e. if it spans several lines in terminal).

## Environment (please complete the following information):

 - OS: [e.g. Linux X11, Linux Wayland, macOS, Windows]

```
$ systeminfo

OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

 - Version: please run `wezterm -V` and include its output here

```
$ ./wezterm.exe -V
wezterm 20210405-110924-a5bb5be8
```

(have also seen the same behavior on WezTerm-windows-20210314-114017-04b7cedd)

 - The active keyboard layout name (eg: ENG, DEU and so on)

ENG

## To Reproduce

See above

## Configuration

`wezterm.lua` configuration file included above

## Expected behavior

When I hit Ctrl-C in `bash` terminal - even if I'm in `(failed reverse-i-search)`, - it should interrupt everything, and give me a new shell prompt.

**Comment by wez** [comment]
This isn't a wezterm bug; the same behavior happens for me when running this in Windows Terminal Preview:

`C:\msys64\usr\bin\env.exe MSYS=enable_pcon MSYSTEM=MSYS /bin/bash --login`

Ctrl-C isn't actually a special thing in the terminal emulator itself; the behavior you're seeing is happening at the msys tty layer.

From https://github.com/msys2/MSYS2-packages/issues/1684 it sounds like there are lots of issues around msys's conpty handling :-(

**Comment by wez** [comment]
I'm closing this as there isn't anything to do in wezterm to resolve this, but I'd love to hear if things get resolved in msys itself!
