### ISSUE TITLE
Using `wezterm connect my.sever` causes wonky colors

### ISSUE THREAD

**Issue by jaredramirez** [wez/wezterm#748]
## Describe the bug

When connecting to a server with `wezterm connect my.server`, the colors when launching the text editor [kakoune](https://github.com/mawww/kakoune) are really wonky. Whenever connecting to the server with `wezterm ssh user@host`, the colors display correctly.

### Local
 - OS: MacOS Big Sur
 - Version: `wezterm 20210407-nightly`

### Remote
 - OS: NixOS
 - Version: `wezterm 20210407-nightly`

## To Reproduce

Connect to a remote machine with `wezterm connect`, open kakoune, and use any colorscheme other than the default

## Configuration

```
    ssh_domains = {
        {
            name = "home.server",
            remote_address = "...",
            username = "jared",
        }
    },
```

## Expected behavior

I expect the colors to be unaltered & display normally.

## Screenshots

When running kakoune in wezterm locally:
<img width="912" alt="Screen Shot 2021-04-29 at 9 43 53 AM" src="https://user-images.githubusercontent.com/8095741/116587727-95366a00-a8cf-11eb-853e-ae327fcea23a.png">

When running kakoune on remote with `wezterm connect home.server`:
<img width="912" alt="Screen Shot 2021-04-29 at 9 44 14 AM" src="https://user-images.githubusercontent.com/8095741/116587813-a97a6700-a8cf-11eb-8ca4-ad117aa42698.png">

When running kakoune on remote with `wezterm ssh jared@...`:
<img width="912" alt="Screen Shot 2021-04-29 at 9 44 35 AM" src="https://user-images.githubusercontent.com/8095741/116587832-b1d2a200-a8cf-11eb-8cbf-970e4c4e0d3a.png">

## Additional context

**Comment by wez** [comment]
Do you have the same colorscheme configured in both the server and the client wezterm configs?

**Comment by jaredramirez** [comment]
Yup, using the same `kakrc` and nix config. My entire config is [here](https://github.com/jaredramirez/dotfiles) if it's needed!

**Comment by wez** [comment]
Nightly builds now know how to pass the remote color palette to the client; you'll need to update both the client and the server side for this to work.
Please give it a try and let know how it goes!
