### ISSUE TITLE
wezterm crash when edit cmdline in a remote ssh host

### ISSUE THREAD

**Issue by keliwang** [wez/wezterm#749]
## Describe the bug

wezterm crash when edit cmdline in a remote ssh host

## Environment

 - OS: macOS
 - Version: wezterm 20210405-110924-a5bb5be8-158-g7de7bf6b

## To Reproduce

1. login into a remote host using `ssh`
2. type `ls`
3. try delete letter `l`: move cursor to the position after `l`, use backspace to delete `l`
4. wezterm crash

## Configuration

```
local wezterm = require 'wezterm';

return {
	use_ime = true,
	color_scheme = "AtomOneLight",
	font = wezterm.font_with_fallback({
		"Menlo",
		"Hiragino Sans GB",
	}),
	harfbuzz_features = {"calt=0", "clig=0", "liga=0"},
	window_padding = {
		left = 5,
	},
	window_close_confirmation = "NeverPrompt",
	allow_square_glyphs_to_overflow_width = "Always"
}
```

## Additional context

Crash Report: [crash.txt](https://github.com/wez/wezterm/files/6402834/crash.txt)
Stack Trace: [stacktrace.txt](https://github.com/wez/wezterm/files/6402845/stacktrace.txt)

**Comment by wez** [comment]
Can you try the latest nightly build?  A couple of commits have gone in since the version you're running and I think this has been resolved!

**Comment by keliwang** [comment]
I tried the latest nightly build and I can confirm this bug is fixed in nightly build.  Thanks very much.
