### ISSUE TITLE
unhandled DecPrivateMode {1005, 7727} on wsl2

### ISSUE THREAD

**Issue by kcking** [wez/wezterm#750]
## Describe the bug
2 Unhandled DecPrivateModes reported to error log:

```
2021-04-30T17:50:35.629Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode 1005
2021-04-30T17:50:35.630Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode 7727
```

## Environment (please complete the following information):

 - WSL2 (windows 10 20H2)
 - Version: wezterm 20210405-110924-a5bb5be8
 - The active keyboard layout name ENG

## To Reproduce

Open wezterm with default_prog set to wsl.exe

## Configuration
occurs with only: 
```
    default_prog = {"wsl.exe"}
```

## Expected behavior

No warnings :) I also dont see a way to hide the log in the case that these may be benign warnings.

## Additional context
It appears 1005 is [Xterm's UTF8 encoding for mouse positions](https://github.com/mintty/mintty/blob/master/src/termout.c#L2318) and 7727 is [some sort of escape key](https://github.com/mintty/mintty/blob/master/src/termout.c#L2350)

Thank you for wezterm, I'm really enjoying using it! :)

**Comment by wez** [comment]
This isn't a bug; unhandled sequences are logged at warning level so that it is easier to see if something isn't hooked up.

I think it is reasonable to suppress logging 1005 which we intentionally do not and will not support (it's obsoleted by a better encoding scheme that we do support).

I'm sort of of the fence about whether to offer an option to suppress logging unknown/unhandled sequences.
Most people never see this logging in any case.

**Comment by kcking** [comment]
Thank you for the reply! Logs show up in a separate window that causes an annoying UX on windows where I can't just click the Wezterm logo in my launchbar to focus its window anymore. Closing this window also terminates wezterm x.x 

I couldn't find any way to prevent the logging window from opening. Is there some configuration I'm missing to do that?

**Comment by wez** [comment]
You're probably running `wezterm.exe` which is the CLI, a console-mode application, which in turn launches `wezterm-gui.exe`.

On Windows, the start menu icon setup by the installer launches `wezterm-gui.exe` directly, and I'd recommend that you do that too!

Are you using the zip file to manually install wezterm?  The docs should probably call this out for windows users!

**Comment by kcking** [comment]
Ah that totally fixed it! I was running `~/scoop/shims/wezterm.exe` (there's no wezterm-gui.exe in that folder). Just switched to `~/scoop/apps/wezterm/current/wezterm-gui.exe`, and no more logging window :)

I was stuck on an earlier version (I think because of some path issue) and had been messing around with my launch shortcuts, so I'll assume it was something incorrect I did and not a fault of any common installation method.

Thanks for the help!
