### ISSUE TITLE
Wezterm send ^M to Neovim when pressing Ctrl-Enter.

### ISSUE THREAD

**Issue by levirs565** [wez/wezterm#752]
## Describe the bug

Wezterm send ^M to Neovim when pressing Ctrl-Enter.

## Environment (please complete the following information):

 - OS: Windows 10 1909
 - Version: wezterm 20210405-110924-a5bb5be8
 - The active keyboard layout name US

## To Reproduce

- Open wezterm
- Open neovim
- Create empty buffer
- Go to insert mode by pressing `i`
- Press `C-v` then press `Ctrl-Enter`

## Expected behavior

Neovim should show `<C-CR>` instead of `^M`

**Comment by wez** [comment]
wezterm is xterm compatible by default.  The enter key is represented by CTRL-M, and that encoding scheme doesn't have a way to represent CTRL-CTRL-M.

You can set `enable_csi_u_key_encoding=true` in your configuration to enable an alternate encoding scheme that can represent that combination.  Note that CSI-u encoding can lead to some gotchas especially if you are like me and are lazy about releasing the shift key.

https://wezfurlong.org/wezterm/config/lua/config/enable_csi_u_key_encoding.html has more information!
