### ISSUE TITLE
not properly works with nushell

### ISSUE THREAD

**Issue by whoizit** [wez/wezterm#753]
Void Linux updated
wezterm builded from source
wayland-1.19.0
nushell-0.30.0 as default shell

nushell works with urxvt and kitty terminals
```
> rustc -V
rustc 1.53.0-nightly (4ae0a8e41 2021-04-30)
> echo $nu.env.SHELL
/usr/bin/nu
> rg ^user /etc/passwd
5:user:x:1000:1000::/home/user:/usr/bin/nu
```
```
/home/user/build/wezterm(main)> cargo run --release --bin wezterm -- start
warning: field is never read: `cursor_color`
   --> termwiz/src/surface/mod.rs:113:5
    |
113 |     cursor_color: ColorAttribute,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted

warning: field is never read: `dec_ansi_mode`
   --> term/src/terminalstate.rs:250:5
    |
250 |     dec_ansi_mode: bool,
    |     ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: field is never read: `sixel_scrolling`
   --> term/src/terminalstate.rs:254:5
    |
254 |     sixel_scrolling: bool,
    |     ^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `application_keypad`
   --> term/src/terminalstate.rs:262:5
    |
262 |     application_keypad: bool,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^

warning: 3 warnings emitted

    Finished release [optimized] target(s) in 0.46s
     Running `target/release/wezterm start`
 2021-05-01T08:02:23.772Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-5763
 2021-05-01T08:02:24.015Z INFO  wezterm_gui::termwindow        > OpenGL initialized! AMD Radeon HD 7700 Series (VERDE, DRM 3.40.0, 5.11.17_1, LLVM 11.0.0) OpenGL ES 3.2 Mesa 21.0.3 is_context_loss_possible=false wezterm version: 20210430-103006-49b0ef23
^C
```
![image](https://user-images.githubusercontent.com/359276/116775782-8b4a6d80-aa6d-11eb-960a-56092a17aabe.png)

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/launch.html#on-posix-systems

Describes how wezterm runs your shell with the widely used `-l` option to start it as a login shell.

Nushell is the first shell to not support that option.

I'll think about how to deal with that, but for now you can set `default_prog = {"nu"}` to run it without passing that argument.

https://wezfurlong.org/wezterm/config/launch.html#changing-the-default-program

**Comment by whoizit** [comment]
I'm sorry, I already found another terminal that fully meets my needs: 
- lightweight and simple
- replacement for urxvt (client/server mode)
- wayland support
it's `foot` https://codeberg.org/dnkl/foot

**Comment by wez** [comment]
Thanks for reporting this; it's now resolved!

**Comment by CGMossa** [comment]
Thanks! This works fine for me:

```lua
return {
    default_prog = {"nu"},
}
```

If I need to do anything else, please do tell.
