### ISSUE TITLE
Add offset and glyph_offset to render powerline fonts better.

### ISSUE THREAD

**Issue by zhou13** [wez/wezterm#758]
**Is your feature request related to a problem? Please describe.**
Currently, the wezterm has some minor issues in rendering powerline fonts. If you look closely enough you'll see that each found is sorrounded by very thin lines - almost like the glyph is misaligned in some way. This is especially obvious when LCDFiltering is enabled (Tested in ArchLinux):

`font = wezterm.font("Fantasque Sans Mono")`
![image](https://user-images.githubusercontent.com/576382/116944836-390f7500-ac44-11eb-829b-a43a094f6b78.png)
![image](https://user-images.githubusercontent.com/576382/116944765-1d0bd380-ac44-11eb-963e-c4e5d073e664.png)

`font = wezterm.font("Fantasque Sans Mono"), freetype_render_target = "HorizontalLcd"`:
![image](https://user-images.githubusercontent.com/576382/116944842-3ca2fc00-ac44-11eb-84ad-2eeac8fcb3e4.png)
![image](https://user-images.githubusercontent.com/576382/116944854-4298dd00-ac44-11eb-8335-01d40e820f2a.png)

`font = wezterm.font("FantasqueSansMono Nerd Font")`
![image](https://user-images.githubusercontent.com/576382/116944685-f64d9d00-ac43-11eb-8485-72704dc05eac.png)
![image](https://user-images.githubusercontent.com/576382/116944695-fb125100-ac43-11eb-9abb-19cf56e22907.png)

**Describe the solution you'd like**
The rendering of powerline fonts is tricky. The common way to work around the problem is to add some offsets to the glyph. For example, in Alacritty, users can control the offsets of glyph through four options: https://github.com/alacritty/alacritty/blob/8f4b752a988c80e27c06582363f6ebbf55ddbfca/alacritty.yml#L158-L167

Here, `offset.x`, `offset.y` control spacing between chars (similar to the `line_height` in wezterm, but in the unit of pixels), and `glyph_offset.x` and `glyph_offset.y` control the offsets of chars.

**Additional context**
The related topic was discussed at https://github.com/alacritty/alacritty/issues/2693.

**Comment by zhou13** [comment]
This is also probably related to https://github.com/wez/wezterm/issues/584.

**Comment by wez** [comment]
I'm going to close this in favor of https://github.com/wez/wezterm/pull/588 which is the path toward solving this (as referenced from #584).
I'm not super keen on adding font/glyph specific overrides: that feels like the wrong level of customization to me.
