### ISSUE TITLE
Add doc how to get raw scan codes under macOS

### ISSUE THREAD

**Issue by gaydenko** [wez/wezterm#763]
I'd want to use scan codes both under Linux and macOS. There isn't any problems to find this or that way for Linux to get scancodes to use in keyboard configuration. And I was not able to find a way for macOS (probably because I'm too new with macOS, I see). I guess, some hint and/or ref how to deal with raw scan codes under macOS would be helpful addition to documentation.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/keys.html#using-rawscan-codes-for-key-bindings has information about this.
The key part is the link to https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html

You can run `wezterm --config debugg_key_events=true` and wezterm will log the events along with the raw code values as you press keys.

**Comment by gaydenko** [comment]
Oh... Sorry, have missed it!
