### ISSUE TITLE
OSC 52 does not work in SSH domain

### ISSUE THREAD

**Issue by Mic92** [wez/wezterm#764]
## Describe the bug

The following works locally (or locally in tmux):

```
printf '\033]52;c;%s\a' Ki5zcWwKKi50YWdzKgoqLmdlbXRhZ3MqCioudG1wKgoqLm1pbi5qcwoqLm1pbi5jc3MKKi5wbGlzdAoqLnBkZgoqLmEKY29tcGlsZV9jb21tYW5kcy5qc29uCnRhZ3MK
```

and result in the following text in the clipboard:

```
*.sql
*.tags*
*.gemtags*
*.tmp*
*.min.js
*.min.css
*.plist
*.pdf
*.a
compile_commands.json
tags
```

When using `wezterm connect` + zsh to connect to a machine via ssh, clipboard is not updated.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210502-nightly
 - The active keyboard layout name: us-international

## To Reproduce

see bug description

## Configuration

Default except for ssh config:

```lua
return {
  color_scheme = "Dracula",
  ssh_domains = {
    {
      -- This name identifies the domain
      name = "eve",
      -- The address to connect to
      remote_address = "eve.thalheim.io",
    }
  },
}
```

## Expected behavior

clipboard is updated

## Screenshots

-

## Session Recording

-

## Additional context

-

**Comment by bew** [comment]
Just a note for @wez around ssh and OSC52: it _does_ work when using `wezterm ssh`

**Comment by Mic92** [comment]
Interesting! Yes. I can confirm this is working for me too.

**Comment by Mic92** [comment]
So it is the multiplexer that does not forward it?

**Comment by wez** [comment]
This only affects the initially spawned pane in the multiplexer: subsequently spawned tabs/panes do have working clipboard

**Comment by Mic92** [comment]
Thanks a lot!
