### ISSUE TITLE
First character ignored when starting in ssh mode

### ISSUE THREAD

**Issue by kaddkaka** [wez/wezterm#771]
## Describe the bug
When starting wezterm-gui.exe on Windows with `ssh`: `wezterm-gui.exe ssh user@remote_linux_machine:port` and after entering the password and seeing the prompt, the first keypress is ignored. (No matter if a regular character or Enter for example)

This does not happen when starting `wezterm-gui.exe` and then running the `ssh` command inside the terminal.

## Environment (please complete the following information):

 - OS: Windows 10 Enterprise 1809
 - Version: wezterm 20210503-220535-d64b7852
 - Swedish (Sweden) and/or English (UK)

## Configuration
Empty configuration file

## Expected behavior
The first character should not be ignored.

**Comment by bew** [comment]
@wez I have that too since you made the new ssh authent' system.
(sorry I didn't report it properly earlier, wasn't _too_ blocking)

**Comment by bew** [comment]
Yes, I confirm it's working, thank you!
