### ISSUE TITLE
Very slow closing of fish tabs on Mac M1.

### ISSUE THREAD

**Issue by hedefalk** [wez/wezterm#774]
## Describe the bug

I'm closing tabs with cmd-w and I accidentally double close two tabs a lot because the feedback that my first close is actually happening is too slow. I found other issues that might be related with infinite beach ball's that are fixed - but maybe the fix was to force-close after a timeout? 

I would really need to find the issue with fish instead because it's still just too slow for me…?

## Environment (please complete the following information):

 - OS: macOS
 - Version: wezterm 20210502-154244-3f7122cb

## To Reproduce
M1 air, just using fish, close tab. takes around 2 seconds before it happens.

## Configuration
local wezterm = require 'wezterm';
return {
  default_prog = {"/Users/viktor/.nix-profile/bin/fish", "-l"}, 
  font = wezterm.font("JetBrains Mono"),
  color_scheme = "Batman"
}

## Expected behavior
Faster close of the tab

**Comment by wez** [comment]
Fish (and only fish!) does something... fishy.
Previously: https://github.com/wez/wezterm/issues/558

Is there a fish setting that might influence this behavior?

**Comment by wez** [comment]
Please give the next nightly build a try (in ~30 minutes from now)
