### ISSUE TITLE
[sixel] incorrect handling of HLS colors

### ISSUE THREAD

**Issue by dnkl** [wez/wezterm#775]
I was testing sixels in the HLS color space in several terminal emulators and noticed that wezterm doesn't handle them correctly:

![wezterm](https://user-images.githubusercontent.com/14031526/117581679-70779900-b0fe-11eb-93c2-d73b90bb2e4a.png)

## Environment

- Linux Wayland
-  wezterm 20210502-154244-3f7122cb

## To Reproduce

Run `img2sixel -t hls <image>`. Compare with `img2sixel -t rgb <same image>`.

## Expected behavior

![foot](https://user-images.githubusercontent.com/14031526/117581740-a9b00900-b0fe-11eb-80f9-f692c005311c.png)

## Additional context

In Sixels, the primary color hues are:

*  blue:  0°
*  red:   120°
*  green: 240°

I suspect wezterm uses

* red: 0°
* green: 120°
* blue: 240°

See https://archive.org/details/bitsavers_decstandar0VideoSystemsReferenceManualDec91_74264381/page/n927/mode/2up, or/and https://vt100.net/docs/vt3xx-gp/chapter2.html#S2.4.2 (scroll down to _"Table 2-3 VT340 Default Color Map"_)

Also worth noting is that XTerm's implementation has issues too, but e.g. mlterm works as expected.

**Comment by wez** [comment]
Thanks for the report!  I've pushed a change that fixes this for me!

**Comment by dnkl** [comment]
Works as far as I can tell. Thanks for the super quick fix!
