### ISSUE TITLE
Multiplexer: Out-of-sync pane_id with TLSDomain

### ISSUE THREAD

**Issue by mjonuschat** [wez/wezterm#781]
## Describe the bug

After prolonged disconnection the pane ids between the local and the remote end seem to get out of sync, commands like `SplitVertical={domain="CurrentPaneDomain"}` and `{SplitHorizontal={domain="CurrentPaneDomain"}` fail to create new panes. The log for the connections shows the following message(s) at the time:

```
2021-05-10T14:45:07.174Z ERROR wezterm_gui::termwindow::spawn > Failed to spawn: unexpected response Ok(ErrorResponse(ErrorResponse { reason: "Error: pane_id 0 invalid" }))
```

## Environment (please complete the following information):

 - OS: MacOS Big Sur 11.3.1 (Intel)
 - Version: wezterm 20210502-154244-3f7122cb
 - The active keyboard layout name: U.S.

## To Reproduce

Steps to reproduce the behavior.

1. Connect to a remote multiplexer with TLSdomain
2. Disconnect the network/power down laptop for some time (sometimes 10+ minutes, definitely after 6+ hours)
3. Reconnect the network, see existing panes still work and accept input/output
4. Try to create a new pane by splitting
5. No pane is being created (screen sometimes blinks once)
6. Check log for connection, see message about invalid pane_id

## Configuration

```
return {
	leader = { key="b", mods="CTRL" },
	keys = {
		{ key = "\"", mods = "LEADER|SHIFT",       action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
		{ key = "%", mods = "LEADER|SHIFT",        action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
		{ key = "x", mods = "LEADER",              action=wezterm.action{CloseCurrentPane={confirm=true}}},
		{ key = "z", mods = "LEADER",              action="TogglePaneZoomState"},
	},
	tls_clients = {
		{
			name = "devvm",
			remote_address = "some.other.host:8080",
			bootstrap_via_ssh = "some.other.host",
			remote_wezterm_path = "/home/mjonuschat/.bin/wezterm",
		},
	},
}
```

## Expected behavior

A new pane to be created

**Comment by wez** [comment]
I didn't actually sit down and reproduce this with the steps you provided (I'm being a bit lazy!), but I did find a silly typo that looks like a plausible smoking gun.

This particular issue is in the client side, but I'd recommend updating both client and server as nightly has a number of changes around window invalidations and improving idle power usage that work best with a server side change 257d323062d0df041d72ea46834487f4271a0ef7

**Comment by mjonuschat** [comment]
This seems to have been fixed in the nightlies, I haven't been able to reproduce for more than a week since upgrading.
