### ISSUE TITLE
CJK char in font Sarasa Gothic becomes small after upgrading to 20210502-154244

### ISSUE THREAD

**Issue by laggardkernel** [wez/wezterm#782]
## Describe the bug

[Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) is an open source monospace font with CJK support.

After upgrading from `20210405-110924` to `20210502-154244`, CJK characters rendered by this very font become small.

## Environment (please complete the following information):

 - OS: macOS 10.14.6
 - Version: 20210502-154244
 - The active keyboard layout name: ENG

## Configuration

Be sure to include the relevant section(s) of your `wezterm.lua` configuration file.

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font_with_fallback({
    "Sarasa Term SC", "Apple Color Emoji", "Noto Color Emoji"
  }),
  font_size = 15,
}
```

Sarasa Gothic is a monospace font with CJK characters. Fallback with macOS built-in CJK font has no problem.

```lua
  -- CJK font is ok with following fallback
  font = wezterm.font_with_fallback({
    "Menlo", "Sonti SC", "Apple Color Emoji", "Noto Color Emoji"
  }),
```

Searching from the issue list, there seems be a font size fix introduced in `20210502-154244`. Maybe it's related with this fix.

## Session Recording

If the issue is with the way that escape sequences are processed it can be helpful
to capture the terminal output using the [`wt-record`](https://github.com/wez/wezterm/blob/master/wt-record)
script to run `wezterm` and record a transcript.  This requires the `script` utility
to be installed on your system (this is part of macOS and available in the `util-linux`
package on linux systems).

In the example below a file named `20180225161026.tgz` is produced.  Please attach that
file to this issue, or if it contains private or sensitive issue that you don't want the
public to see on GitHub, please find some other way to get that file to a project
contributor (perhaps Dropbox or email?).

```
$ ./wt-record
Transcript recorded in 20180225161026.tgz
```

You can use `wt-replay 20180225161026.tgz` to replay that file.

`wt-record` can only record the terminal output; it cannot record the input events going
in to the terminal, so if you are having an issue with input, please be sure to describe
it below!

**Comment by wez** [comment]
Please try a nightly build; https://github.com/wez/wezterm/commit/f4e96689529168cc52f022e3867c73a9495fce75 recently landed to address a scaling issue that sounds similar!

**Comment by laggardkernel** [comment]
@wez Thanks, I just tried `20210511-192024-a59e9b17`, seems the problem is fixed.
