### ISSUE TITLE
Multiplexer: Splitting panes causes height miscalcutations for neighboring panes

### ISSUE THREAD

**Issue by mjonuschat** [wez/wezterm#783]
## Describe the bug

Splitting panes sometimes seems to affect the height of neighboring panes, leading to display and scroll side effects.

## Environment (please complete the following information):

 - OS: MacOS Big Sur 11.3.1 (Intel)
 - Version: wezterm 20210502-154244-3f7122cb
 - The active keyboard layout name: U.S.

## To Reproduce

This seems to be happening by splitting panes in the following order, at least when connected via remote tls domain

1. Create enough output in the tab to have a bit of scrollback
2. Split tab horizontally to create two panes with a 50/50 split
3. Create some output in the right hand pane to have a bit of scrollback
4. Split the right hand pane, this time vertically
5. Create some output in the new pane to have some scrollback
6. Activate the left hand (full height) pane
7. Scroll back, there should be display artifacts looking like it treats the pane as half height, leading to display and scroll issues.

This can be worked around by toggling the pane to full zoom and back, making me believe it's mostly state / recalculation issue

## Expected behavior

The left hand pane should be unaffected by changes/split to other panes

**Comment by wez** [comment]
Do you see this only with a remote multiplexer?
Is it possible that you're seeing https://github.com/wez/wezterm/issues/797 ?

**Comment by mjonuschat** [comment]
I've only seen it with a remote multiplexer but that's what I'm using almost exclusively with panes.
I'll update to the latest nightly and try again I suspect it's something different as I have the tab bar at the top.

**Comment by wez** [comment]
I don't know if I reproduced exactly what you saw, but I did notice that, in nightly, scrolling a pane wouldn't paint lines that were newly fetched from the server (scrollback is fetched on demand in the mux protocol).

Please try the nightly build when you have a chance and let me know if this has improved.  If not, I'd appreciate seeing a screenshot of the bad state to see if it gives me some clues!

**Comment by mjonuschat** [comment]
Nightlies have definitely improved the situation, I only encountered a similar issue once after closing a pane. I made a screenshot but I'll need to blur some things out before sharing as it has some work related information.

**Comment by mhanberg** [comment]
I installed the nightly last night and noticed this as well.

- I open vim and toggle my fuzzy finder and is correctly centered in the window.
- create a new split pane
- close the pane (for some reason the confirmation dialog is not visible)
- toggle my fuzzy finder and _observe that it it no longer centered_.
- resize the whole window with the mouse
- toggle my fuzzy finder and observe that it is now centered.

https://user-images.githubusercontent.com/5523984/141800188-95cd7956-9b5c-43e0-a510-da58fa0ab006.mov

<details>
  <summary>Current config</summary>
  <pre>
 local wezterm = require("wezterm")

local move_around = function(window, pane, direction_wez, direction_nvim)
  -- if pane:get_title():sub(-4) == "NVIM" then
  -- 	window:perform_action(wezterm.action({ SendString = "^" .. direction_nvim }), pane)
  -- else
  window:perform_action(wezterm.action({ ActivatePaneDirection = direction_wez }), pane)
  -- end
end

wezterm.on("move-left", function(window, pane)
  move_around(window, pane, "Left", "h")
end)

wezterm.on("move-right", function(window, pane)
  move_around(window, pane, "Right", "l")
end)

wezterm.on("move-up", function(window, pane)
  move_around(window, pane, "Up", "k")
end)

wezterm.on("move-down", function(window, pane)
  move_around(window, pane, "Down", "j")
end)

return {
  unix_domains = {
    {
      name = "default",
      connect_automatically = true,
    },
  },
  font = wezterm.font("JetBrainsMono Nerd Font Mono"),
  font_size = 14.0,
  skip_close_confirmation_for_processes_named = { "" },
  leader = { key = "s", mods = "CTRL", timeout_milliseconds = 1000 },
  keys = {
    { key = "c", mods = "LEADER", action = wezterm.action({ SpawnTab = "CurrentPaneDomain" }) },
    { key = "j", mods = "LEADER", action = wezterm.action({ SpawnTab = { DomainName = "dotfiles" } }) },
    { key = "l", mods = "LEADER", action = "ShowLauncher" },
    { key = "n", mods = "LEADER", action = wezterm.action({ ActivateTabRelative = 1 }) },
    { key = "p", mods = "LEADER", action = wezterm.action({ ActivateTabRelative = -1 }) },
    { key = "\\", mods = "LEADER", action = wezterm.action({ SplitHorizontal = { domain = "CurrentPaneDomain" } }) },
    { key = "-", mods = "LEADER", action = wezterm.action({ SplitVertical = { domain = "CurrentPaneDomain" } }) },
    { key = "x", mods = "LEADER", action = wezterm.action({ CloseCurrentPane = { confirm = true } }) },
    { key = "h", mods = "CTRL", action = wezterm.action({ EmitEvent = "move-left" }) },
    { key = "l", mods = "CTRL", action = wezterm.action({ EmitEvent = "move-right" }) },
    { key = "k", mods = "CTRL", action = wezterm.action({ EmitEvent = "move-up" }) },
    { key = "j", mods = "CTRL", action = wezterm.action({ EmitEvent = "move-down" }) },
    { key = "l", mods = "CMD", action = "ShowDebugOverlay" },
  },
  colors = {
    -- The default text color
    foreground = "#d8caac",
    -- The default background color
    background = "#273433",

    -- Overrides the cell background color when the current cell is occupied by the
    -- cursor and the cursor style is set to Block
    cursor_bg = "#52ad70",
    -- Overrides the text color when the current cell is occupied by the cursor
    cursor_fg = "black",
    -- Specifies the border color of the cursor when the cursor style is set to Block,
    -- of the color of the vertical or horizontal bar when the cursor style is set to
    -- Bar or Underline.
    cursor_border = "#52ad70",

    -- the foreground color of selected text
    selection_fg = "black",
    -- the background color of selected text
    selection_bg = "#fffacd",

    -- The color of the scrollbar "thumb"; the portion that represents the current viewport
    scrollbar_thumb = "#222222",

    -- The color of the split lines between panes
    split = "#444444",

    ansi = { "#d8caac", "#e68183", "#a7c080", "#d9bb80", "#89beba", "#d3a0bc", "#87c095", "#868d80" },
    brights = { "#5f747f", "#e68183", "#a7c080", "#d9bb80", "#89beba", "#d3a0bc", "#87c095", "#868d80" },

    -- Arbitrary colors of the palette in the range from 16 to 255
    -- indexed = { [136] = "#af8700" },
    tab_bar = {

      -- The color of the strip that goes along the top of the window
      background = "#2b2042",

      -- The active tab is the one that has focus in the window
      active_tab = {
        -- The color of the background area for the tab
        bg_color = "#2b2042",
        -- The color of the text for the tab
        fg_color = "#c0c0c0",

        -- Specify whether you want "Half", "Normal" or "Bold" intensity for the
        -- label shown for this tab.
        -- The default is "Normal"
        intensity = "Normal",

        -- Specify whether you want "None", "Single" or "Double" underline for
        -- label shown for this tab.
        -- The default is "None"
        underline = "None",

        -- Specify whether you want the text to be italic (true) or not (false)
        -- for this tab.  The default is false.
        italic = false,

        -- Specify whether you want the text to be rendered with strikethrough (true)
        -- or not for this tab.  The default is false.
        strikethrough = false,
      },

      -- Inactive tabs are the tabs that do not have focus
      inactive_tab = {
        bg_color = "#1b1032",
        fg_color = "#808080",

        -- The same options that were listed under the `active_tab` section above
        -- can also be used for `inactive_tab`.
      },

      -- You can configure some alternate styling when the mouse pointer
      -- moves over inactive tabs
      inactive_tab_hover = {
        bg_color = "#3b3052",
        fg_color = "#909090",
        italic = true,

        -- The same options that were listed under the `active_tab` section above
        -- can also be used for `inactive_tab_hover`.
      },

      -- The new tab button that let you create new tabs
      new_tab = {
        bg_color = "#1b1032",
        fg_color = "#808080",

        -- The same options that were listed under the `active_tab` section above
        -- can also be used for `new_tab`.
      },

      -- You can configure some alternate styling when the mouse pointer
      -- moves over the new tab button
      new_tab_hover = {
        bg_color = "#3b3052",
        fg_color = "#909090",
        italic = true,

        -- The same options that were listed under the `active_tab` section above
        -- can also be used for `new_tab_hover`.
      },
    },
  },
}
</pre>
</details>

**Comment by wez** [comment]
I pushed a commit that resolves https://github.com/wez/wezterm/issues/1277 and which might be the same root cause as this one.  Would you mind giving it a try and letting me know?

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
