### ISSUE TITLE
Error outputting 24 bit color gradients

### ISSUE THREAD

**Issue by splitDEV** [wez/wezterm#785]
## Describe the bug

I stumbled upon wezterm and I really like it so far. Thank you for your work and time.
I tried some things and unfortunately displaying 24 bit color gradients resulted in nothing being shown, despite true color support seems to be working for normal text output using escape sequences:

![Working 24 bit](https://user-images.githubusercontent.com/7757191/117895221-3523c880-b2be-11eb-9bfb-c963b334b37b.png)

## Environment

 - OS: Archlinux
 - Version: wezterm 20210502-154244-3f7122cb
 - ENG

## To Reproduce

Run the following script in wezterm: https://github.com/csdvrx/sixel-testsuite/blob/master/24-bit-color.sh

## Configuration

--

## Expected behavior

Left terminal wezterm, right terminal kitty:

![Ouptut from wezterm and kitty](https://user-images.githubusercontent.com/7757191/117894529-c8f49500-b2bc-11eb-9f6d-f99c39af6ac9.png)

**Comment by wez** [comment]
That script uses a non-standard encoding for true color.  There's a complicated back story, but it boils down to
a sequence such as `^[38;2;<r>;<g>;<b>m` (where the `2` is the rgb color space, and the values are semicolon separated) as being the standard.  Some terminals mis-implemented that using `:` for a separator, and then again an implementation of that which omits the `2` (color space) parameter is floating out there.

The script is using `SEPARATOR=:` even though its comments use `;` at the top of the script.
If you change the script to set `SEPARATOR=;` on this line https://github.com/csdvrx/sixel-testsuite/blob/master/24-bit-color.sh#L11 it will render the color sequence correctly.

I've pushed 3d83a805ec76de70d7c99de9a6d5291bc282c137 which also allows recognizing the sequence used in that script.

**Comment by splitDEV** [comment]
Wow thank you for the quick response and fix :)

You're doing outstanding work!!
