### ISSUE TITLE
Filedescriptor crate to support dup2

### ISSUE THREAD

**Issue by robinbernon** [wez/wezterm#786]
Hi Wez. Am currently looking into tweaking the [gag](https://stebalien.github.io/gag-rs/gag/) crate so that it works cross platform and wanted to use your filedescriptor crate to do it. Was wandering whether your crate supports dup2? Need this feature in order to redirect stdout/stderr into file. Happy to submit a PR for this, although I don't do much low level stuff so might need a couple pointers here..

**Comment by wez** [comment]
There's no direct support for `dup2`, but it wouldn't be difficult to add; I'd be happy to accept a PR for that.

This is the code used for `dup`:
https://github.com/wez/wezterm/blob/main/filedescriptor/src/unix.rs#L107-L147

There are two flavors: one that atomically dup's with CLOEXEC set, and one that non-atomically does the same.
To add `dup2` you'll repeat that pattern but using [dup3](https://docs.rs/libc/0.2.94/libc/fn.dup3.html) (pass `O_CLOEXEC` as the third parameter) for the atomic case, and `dup2` for the non-atomic case.

I'd suggest making the method have an unsafe signature to represent that there is potential danger in re-assigning the fd:

```rust
#[cfg(unix)]
unsafe pub fn dup2<F: AsRawFileDescriptor>(f: &F, dest_fd: RawFd) -> Result<Self>;
```

If you wanted to portably redirect stdio streams on windows you can't literally use `dup2` there, but instead would need to look at using [SetStdHandle](https://docs.microsoft.com/en-us/windows/console/setstdhandle) and passing the result of calling https://docs.rs/filedescriptor/0.7.3/i686-pc-windows-msvc/filedescriptor/trait.IntoRawFileDescriptor.html to that API.

If you also wanted to add a portable API for that to filedescriptor I'm open to it; I think you'd need to add an enum representing stdin, stdout and stderr and then have it call the appropriate `dup2` or `SetStdHandle` call depending on the OS.

**Comment by robinbernon** [comment]
Thanks for the speedy reply :)

I'm having a little difficulty implementing the redirect of STDOUT to a tempfile. I have a small test fn for checking if the redirect works on windows: 

```
use tempfile::NamedTempFile;
use std::os::windows::io::IntoRawHandle;
use winapi::um::processenv::SetStdHandle;

fn run_trial(num: u32) -> Result<(), std::io::Error> {
    let mut tempfile = NamedTempFile::new()?;
    let inner = tempfile.reopen()?;
    let mut outer = tempfile.reopen()?;

    let handle = inner.into_raw_handle();

    unsafe {SetStdHandle(num, handle)};

    ::std::io::stderr().write_all(b"Hello world!\n").unwrap();

    let mut buf = String::new();
    outer.read_to_string(&mut buf).unwrap();

    if buf == "".to_string() {
        println!("It's not working!");
    } else {
        println!("It's working!");
    }

    Ok(())
}
```

Currently this is failing and I've tried a bunch of different numbers although none seem to get it to work properly. I can see from [windows.h](https://github.com/Leandros/WindowsHModular/blob/master/include/win32/windows.h#L2347) that I need to produce the value of (DWORD)-11 although I'm not sure what this value actually is. (I've tried the obvious checks of "num" and "U32::max-num" for a bunch of numbers but no difference is made here. Do you have any idea what I'm doing wrong here?

**Comment by robinbernon** [comment]
I've opened up a premature PR with only windows directs supported for now: https://github.com/wez/wezterm/pull/788
Are these sorts of changes what you had in mind? (Gonna now work on the unix equivalent methods)

**Comment by wez** [comment]
I'd suggest something like:

```rust
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum StdioDescriptor {
   Stdin,
   Stdout,
   Stderr,
}

impl FileDescriptor {
   /// Duplicates the descriptor representing `stdio`, then re-assigns that descriptor
   /// by duplicating `f`.
   /// Returns the original decriptor.
   pub fn redirect_stdio<F: AsRawFileDescriptor>(f: &F, stdio: StdioDescriptor) -> Result<Self>;
}
```

Under the covers that would use `FileDescriptor::dup` to get the original stream, the use `dup2` on unix, or `SetStdHandle` on windows to assign it.

I'd prefer not to include the restore-on-drop functionality in this crate; `gag` could cleanly and portably implement that functionality on top of this interface:

```rust
struct TemporaryRedirection {
   stdio: StdioDescriptor,
   fd: FileDescriptor
}

impl TemporaryRedirection {
  pub fn new<F: AsRawFileDescriptor>(f: &F, stdio: StdioDescriptor) -> Result<Self> {
    let fd = FileDescriptor::redirect_stdio(f, stdio)?;
    Ok(Self { fd, stdio }}
  }
}

impl Drop for TemporaryRedirection {
   fn drop(&mut self) {
      let _ = FileDescriptor::redirect_stdio(self.fd, self.stdio);
   }
}
```

**Comment by robinbernon** [comment]
Sounds good - will just return the original file descriptor in the redirect_stdio method like you mentioned above then 👍
(will aim to submit a finalised PR by the end of tomorrow then)

**Comment by robinbernon** [comment]
Hi Wez. Am currently making changes to the gag crate based on my active branch. Realised there's an issue with the std file descriptor - It get's returned on redirect_stdio although needs to be used again on termination to put back things to their original state. As the fields for FileDescriptor are private it's not possible to reshape it to being compatible with T: AsRawFileDescriptor, therefore it can't be put back into the redirect method. I'd like the downgrade redirect_stdio, dup and dup2 to accept RawFileDescriptor instead of F: AsRawFileDescriptor, is this ok for me to do?

**Comment by robinbernon** [comment]
@wez have also made a PR for the gag crate now: https://github.com/Stebalien/gag-rs/pull/7
