### ISSUE TITLE
Add drop shadow support in X11

### ISSUE THREAD

**Issue by vianpl** [wez/wezterm#791]
Adding drop shadow support in X11 is a purely cosmetic enhancement, but nice to have. I see it's already supported in macos, so I won't go into details on what it is and how it should look (but will be happy to provide more info if needed). 

Thanks for wezterm!

**Comment by wez** [comment]
Please clarify what you mean by drop shadow support!

**Comment by vianpl** [comment]
Of course,
here's a wezterm window sitting on top of a google chrome window (running Fedora 34 + Gnome 40).

![wezterm-no-shadow](https://user-images.githubusercontent.com/3706469/118140198-6f997c80-b408-11eb-8379-827394851848.png)


Here's the same setup but running kitty:

![kitty-shadow](https://user-images.githubusercontent.com/3706469/118140195-6f00e600-b408-11eb-816f-b4dab38ef522.png)

As you can see kitty's window has a drop shadow. IMO it looks nicer.

That said, I now realize that using `window_decorations = "RESIZE"` instead of `"NONE"` achieves the look I want. Sorry for the noise.
