### ISSUE TITLE
Could a proper 1.0 or .1 release be release

### ISSUE THREAD

**Issue by caughtquick** [wez/wezterm#793]
**Is your feature request related to a problem? Please describe.**
When writing void-packages templates for this project it is much harder to build as the install script doesn't accept dashes in the name and it automatically trying to build from the build directory of the version stated which is not able to be set the the latest version tag.

**Describe the solution you'd like**
A proper release that could be used for distro's to packages rather than the slightly more arbitrary release tags currently

**Additional context**
This is a feature that I have experienced specifically with void that makes it much harder to maintain a template for.

**Comment by wez** [comment]
I'd suggest transforming the `-` to `.` in the packaging machinery for that distro.
I have no plans to change the versioning scheme and automation that I use.
