### ISSUE TITLE
Mouse scroll the hovered pane

### ISSUE THREAD

**Issue by sclu1034** [wez/wezterm#798]
**Is your feature request related to a problem? Please describe.**
With regular application windows it is possible to scroll any window with the mouse by hovering it, without having to switch keyboard focus. The same is possible with panes in Tmux. However, WezTerm will always send scroll events to whatever pane has keyboard focus, even if I intentionally hover over a different pane.

**Describe the solution you'd like**
Send mouse scroll events to the pane that the mouse cursor is hovering.

**Comment by wez** [comment]
Take a look at: https://wezfurlong.org/wezterm/config/lua/config/pane_focus_follows_mouse.html

**Comment by sclu1034** [comment]
While that option does remove the need for clicking, it does not separate keyboard focus from mouse focus.
I don't actually want to change the pane that keyboard events are sent to or the one that is dimmed by `inactive_pane_hsb`, just the one that mouse events are sent to.

**Comment by wez** [comment]
This is fixed in the latest nightly!

**Comment by zhangyoufu** [comment]
Hi, I'm using `20220807-113146-c2fee766` and I cannot scroll hovered inactive panes using mouse.

Is this the expected behavior (controlled by some configuration?) or a regression?

**Comment by wez** [comment]
@zhangyoufu please file a new issue

**Comment by zhangyoufu** [comment]
> @zhangyoufu please file a new issue

@wez Same as #2373
