### ISSUE TITLE
Embed wezterm within other applications

### ISSUE THREAD

**Issue by onelittlehope** [wez/wezterm#802]
**Is your feature request related to a problem? Please describe.**
I would like to embed wezterm into an application in a similar way to xterm's `-into windowid` feature:

```
-into windowId
    Given an X window identifier (a decimal integer), xterm will reparent its top-level shell widget to that window. This is used to embed xterm within other applications. 
```

**Describe the solution you'd like**
wezterm will have a command line parameter called `--embed` which allows me to specify the parent's X11 window id as a decimal integer. wezterm will then use code similar to this:

* https://github.com/alacritty/alacritty/blob/master/alacritty/src/display/window.rs#L201-L207
* https://github.com/alacritty/alacritty/blob/master/alacritty/src/display/window.rs#L460-L492

to embed itself into the specified parent.

I fully understand/accept that this may not work in Windows / OS X since its an X11 thing. However, it would be super nice if it was a cross platform feature.

**Describe alternatives you've considered**
Carry on using xterm.

**Additional context**

Example code:
```
import sys
from PyQt5 import QtCore, QtWidgets


class EmbTerminal(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(EmbTerminal, self).__init__(parent)
        self.process = QtCore.QProcess(self)
        self.terminal = QtWidgets.QWidget(self)
        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(self.terminal)
        self.process.start('xterm', ['-into', str(int(self.winId()))])
        #self.setFixedSize(640, 480)


class mainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(mainWindow, self).__init__(parent)

        central_widget = QtWidgets.QWidget()
        lay = QtWidgets.QVBoxLayout(central_widget)
        self.setCentralWidget(central_widget)

        tab_widget = QtWidgets.QTabWidget()
        lay.addWidget(tab_widget)

        tab_widget.addTab(EmbTerminal(), "EmbTerminal")
        tab_widget.addTab(QtWidgets.QTextEdit(), "QTextEdit")
        tab_widget.addTab(QtWidgets.QMdiArea(), "QMdiArea")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    main = mainWindow()
    main.show()
    sys.exit(app.exec_())
```

Result of saving the above into a file called xterm_test.py and running it with `python3 xterm_test.py`:
![image](https://user-images.githubusercontent.com/3677874/118383582-180d3380-b5f7-11eb-8937-5d003ee48427.png)

**Comment by wez** [comment]
I don't have plans to do this myself, but I'm open to it.

If you'd like to submit a PR for it, you'll need to add an appropriate option to the command line arguments in the `wezterm-gui-subcommands` crate, and then add a way to set that window id for the `window` crate to use for the first window that it creates.
