### ISSUE TITLE
Unable to compile freetype error

### ISSUE THREAD

**Issue by SevereOverfl0w** [wez/wezterm#81]
## Is it a build problem?

```
   Compiling freetype v0.1.0 (/builddir/wezterm-20191218-101156-bf35707/deps/freetype)
error: failed to run custom build command for `freetype v0.1.0 (/builddir/wezterm-20191218-101156-bf35707/deps/freetype)`

Caused by:
  process didn't exit successfully: `/builddir/wezterm-20191218-101156-bf35707/target/release/build/freetype-2592e6c7ec0b4511/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = Some("-fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   ")
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-fstack-clash-protection" "-D_FORTIFY_SOURCE=2" "-mtune=generic" "-O2" "-pipe" "-I" "zlib" "-DHAVE_SYS_TYPES_H" "-DHAVE_STDINT_H" "-DHAVE_STDDEF_H" "-D_LARGEFILE64_SOURCE=1" "-o" "/builddir/wezterm-20191218-101156-bf35707/target/x86_64-unknown-linux-gnu/release/build/freetype-f0a65fb7ff931d73/out/zlib-build/zlib/adler32.o" "-c" "zlib/adler32.c"
cargo:warning=cc: error: zlib/adler32.c: No such file or directory
cargo:warning=cc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-fstack-clash-protection" "-D_FORTIFY_SOURCE=2" "-mtune=generic" "-O2" "-pipe" "-I" "zlib" "-DHAVE_SYS_TYPES_H" "-DHAVE_STDINT_H" "-DHAVE_STDDEF_H" "-D_LARGEFILE64_SOURCE=1" "-o" "/builddir/wezterm-20191218-101156-bf35707/target/x86_64-unknown-linux-gnu/release/build/freetype-f0a65fb7ff931d73/out/zlib-build/zlib/compress.o" "-c" "zlib/compress.c"
cargo:warning=cc: error: zlib/compress.c: No such file or directory
cargo:warning=cc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1

--- stderr


error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-fstack-clash-protection" "-D_FORTIFY_SOURCE=2" "-mtune=generic" "-O2" "-pipe" "-I" "zlib" "-DHAVE_SYS_TYPES_H" "-DHAVE_STDINT_H" "-DHAVE_STDDEF_H" "-D_LARGEFILE64_SOURCE=1" "-o" "/builddir/wezterm-20191218-101156-bf35707/target/x86_64-unknown-linux-gnu/release/build/freetype-f0a65fb7ff931d73/out/zlib-build/zlib/adler32.o" "-c" "zlib/adler32.c" with args "cc" did not execute successfully (status code exit code: 1).
```

### What did you try?

Building the project from source, using the xbps/void linux build system.

### What did you expect to happen?

A successful build

### What actually happened?

Build failed with log above ^

**Comment by wez** [comment]
Can you share the exact set of commands used to clone the repo and start the build in that environment?

This link shows how to build from source:
https://wezfurlong.org/wezterm/installation.html#-installing-from-source

**Comment by wez** [comment]
(FWIW, that error sounds like the git sub modules were not set up successfully)

**Comment by SevereOverfl0w** [comment]
Looking at it, I think it's because I'm building from the release, which isn't in git.

**Comment by wez** [comment]
Ah, yeah: can you get it to build using git and the tag from that release instead?

**Comment by SevereOverfl0w** [comment]
I've gotten past this error using git instead of the release. I slightly prefer to use the tar.gz from the releases as it can be checksum'd and easily picked up for updated versions.

**Comment by wez** [comment]
I suppose we could teach the CI to upload the effective source tarball to the release as part of the binary publishing step without too much trouble

**Comment by SevereOverfl0w** [comment]
That would be cool. Leaving this open in case you want to use it to track, but feel free to close.

I have a working voidlinux package now! I'll likely contribute it upstream to voidlinux soon.

**Comment by wez** [comment]
I pushed a commit that should end up uploading a source tarball to the nightly release:
https://github.com/wez/wezterm/releases/tag/nightly
I'll check back on that a bit later (still needs to build out).
Assuming that works out, when I next cut a tag you'll be able to use that source tarball instead!

**Comment by wez** [comment]
(The "nightly" actually runs hourly, starting at 10 minutes after the hour.  It takes ~30 minutes to build out everything, so I expect to see the updated artifacts show up at around 10:40 pacific time)

**Comment by wez** [comment]
Looks like this worked, so closing out!

**Comment by SevereOverfl0w** [comment]
Great! I'll have a go with it today!
