### ISSUE TITLE
Hex color codes for WezTerm don't produce the same results as on other terminals

### ISSUE THREAD

**Issue by chipbuster** [wez/wezterm#811]
## Describe the bug

I'm trying to create a [Rigel scheme](https://github.com/Rigellute/rigel) for WezTerm, but the color does not match what I see from other terminal emulators.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: 20210502-154244-3f7122cb
 - The active keyboard layout name: ENG

## To Reproduce

Plug config in to Wezterm, compare rendered color against other color samples (e.g. as shown by other terminal emulators, web browsers).

## Configuration

```
local wezterm = require 'wezterm';

return {
    colors = {
        foreground = "#e6e6dc",
        background = "#002653",
    },
    --color_scheme = "Rigel",
    window_background_opacity = 1.0,
    font = wezterm.font("SauceCodePro Nerd Font Mono")
}
```

`Rigel.toml` used to exist in `~/.config/wezterm/colors/` but has been deleted at time of bug report.

## Expected behavior

My understanding is that hex codes are supposed to be unambiguous specifications of a color, so I should see identical colors across terminal emulators. However, my understanding of color in computing is atrocious, so maybe this is not true.

## Screenshots

The color hex I'm using for the background displayed on the web in Firefox, with four terminal emulators surrounding it:

- Top left: konsole
- Top right: kitty
- Bottom left: alacritty (with transparency)
- Bottom right: wezterm

![image](https://user-images.githubusercontent.com/4605384/119047632-cd3b4500-b983-11eb-8fc6-685899d431fc.png)

## Additional context

At some point, I deleted `term = "xterm-256color"` from my wezterm.lua and I thought I saw the color switch to what I expected. However, I have been unable to replicate this at all, even by adding and removing that line from my config.

The color picker from Gcolor2 tells me that the color used in Wezterm is the correct color (`#002653`), but the color displayed in the color picker looks different than in Wezterm.

**Comment by chipbuster** [comment]
An interesting thing I just discovered: I have the Rigel colorscheme set in vim. When I use vim from WezTerm, the color does actually look correct. According to gcolor2, both background colors on these two terminal windows are the same!

![image](https://user-images.githubusercontent.com/4605384/119064525-22d21a80-b9a1-11eb-8938-9e9a5d64d156.png)

**Comment by wez** [comment]
Note that the config you shared uses `#002653` but the screenshot in the background appears to be `#002635` which is greener than the former.  Is this a typo in your config?

![Screen Shot 2021-05-21 at 10 20 37](https://user-images.githubusercontent.com/117777/119175067-3d96a480-ba1e-11eb-991f-a6554673ba41.png)

![Screen Shot 2021-05-21 at 10 26 42](https://user-images.githubusercontent.com/117777/119175741-11c7ee80-ba1f-11eb-975a-733c662cb502.png)

**Comment by chipbuster** [comment]
Well don't I feel like a dunce now.

I'm sorry, I didn't bother checking for typos because I thought I created the color config by using text processing tools on my Alacritty config, but clearly at some point I went and messed with it manually and forgot that I had done so.

Sorry for the noise.
