### ISSUE TITLE
Set current dir doesn’t work if it include space

### ISSUE THREAD

**Issue by sanpii** [wez/wezterm#814]
## Describe the bug

Keep current dir in new tab/pane doesn’t work if the directory contains space.

## Environment (please complete the following information):

 - Linux X11
 - Version: wezterm 20210502-154244-3f7122cb
 - The active keyboard layout name: fr,bepo

## To Reproduce

```
$ cd 'Dir with space'
$ wezterm cli spawn
$ pwd
/home/sanpi
```

## Expected behavior

cwd should be "Dir with space" instead.

**Comment by wez** [comment]
This was fixed in https://github.com/wez/wezterm/pull/799 - please try the nightly download!
