### ISSUE TITLE
Spurious indents when using Zinit

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#822]
## Describe the bug

Running ``>>git status -uno`` in a git repo from WezTerm using zsh & zinit produces spurious indents on each line. This problem does not happen with iTerm2. Not sure if this is a zinit issue, have posted this as a bug on their repo too: https://github.com/zdharma/zinit/issues/514

## Environment (please complete the following information):

 - OS: macOS 11.3 ARM64
 - Version: wezterm 20210511-192024-a59e9b17
 - The active keyboard layout name: U.S.

## To Reproduce

1) Install [zinit](https://github.com/zdharma/zinit). It will add following lines to your ``.zshrc``:
```zsh
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk
```

2) Manually add few more lines after these lines:
```zsh
# Two regular plugins loaded without investigating.
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma/fast-syntax-highlighting

# Plugin history-search-multi-word loaded with investigating.
zinit load zdharma/history-search-multi-word

# Load the pure theme, with zsh-async library that's bundled with it.
zinit ice pick"async.zsh" src"pure.zsh"
zinit light sindresorhus/pure
```

3. Open new tab, cd to a git repo, and run ``>>git status -uno``

## Screenshots

![Screen Shot 2021-05-25 at 2 09 36 AM](https://user-images.githubusercontent.com/71736629/119473809-5f36ab00-bd00-11eb-82de-8ca104a86045.png)

**Comment by reportaman** [comment]
Nevermind, this does not always happen. Not sure why it happened then...

**Comment by wez** [comment]
Looks like something is changing the stty `ocrnl` or other output settings which impacts how CR is processed at the kernel level.

Most likely something in your shell setup is manipulating `stty`.
https://github.com/zdharma/zinit/search?q=stty shows that zinit does something with stty but I don't really want to learn what zinit is or does :)

I'd suggest reading through issues like this one:
https://github.com/containers/podman/issues/3179
to get a sense of what is happening.

You'll also want to look at `man stty` and `stty -a` to see what mode the tty is in.

**Comment by wez** [comment]
I'm closing this out as it doesn't appear to be a wezterm issue, but an issue with the tty settings.
