### ISSUE TITLE
Parse "include" directive in ssh configs

### ISSUE THREAD

**Issue by matthewstrasiotto** [wez/wezterm#824]
**Is your feature request related to a problem? Please describe.**

My dotfiles are setup to have the following structure:

```tree
.ssh
├── config
├── config.d
│   ├── aws
│   ├── control.01.usyd -> /home/matty/.config/dotfiles/private-dotfiles/tools/ssh/config.d/control.01.usyd
│   ├── control.99.common -> /home/matty/projects/bash_bindings/bootstrap/tools/ssh/config.d/control.99.common
│   ├── cronnit -> /home/matty/.config/dotfiles/private-dotfiles/tools/ssh/config.d/cronnit
│   ├── server_connect -> /home/matty/.config/dotfiles/private-dotfiles/tools/ssh/config.d/server_connect
│   ├── server_ports -> /home/matty/.config/dotfiles/private-dotfiles/tools/ssh/config.d/server_ports
│   ├── usyd_config -> /home/matty/.config/dotfiles/private-dotfiles/tools/ssh/config.d/usyd_config
│   └── windows_ports -> /home/matty/.config/dotfiles/private-dotfiles/tools/ssh/config.d/windows_ports
```

`~/.ssh/config` has the following:

```ssh_config
Include config.d/*
```

Everything in config.d is included. 

Presently, wezterm doesn't touch anything but `.ssh/config`, as it doesn't handle the "Include". This means my ssh config isn't used properly.

**Describe the solution you'd like**

Please allow `Include` to be used

**Comment by matthewstrasiotto** [comment]
Nvm, just misspelled the hostname in config lmao

**Comment by matthewstrasiotto** [comment]
I'm not clear on which parts of ssh config actually get used - is Host & Hostname matched?

**Comment by wez** [comment]
The supported config items are listed in the docs: https://wezfurlong.org/wezterm/ssh.html
I've just added `Include` handling in the nightly build!

**Comment by matthewstrasiotto** [comment]
Oh amazing!! I was getting ready to submit a PR (slowgoing bc Rust is new to me) but you beat me to the punch

I'm potentially still keen to request ProxyCommand/ProxyJump, so I'll save thay for another issue

**Comment by matthewstrasiotto** [comment]
Checked the docs, just saw proxycommand, i swear that wasn't there yesterday 🙏
Really excited to see how multiplexing goes on my remotes
