### ISSUE TITLE
Blinking cursor should always reset to visible on movement

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#83]
Please include as much information as possible that can help to reproduce and understand the issue;
some pointers and suggestions are included here in this template.  You are empowered to include
more or less information than is asked for here!

## Did something not work the way you expected?

When settings a blinking cursor mode, the cursor should always be visible after moving. The blinking is only relevant while it sits in one place in the window.

### What did you try?

Set `default_cursor_style = "BlinkingUnderline"`

### What did you expect to happen?

Cursor blinking while idle, but visible while typing.

### What actually happened?

Cursor blinking is independent of motion, and so is often invisible while typing.

**Comment by jsgf** [comment]
I'm having a go at fixing this.

**Comment by wez** [comment]
Thanks; I'm unbricking something unrelated to this atm!
I had envisioned adding a little state struct that tracked whether it is on or off and the time of the last transition, with a keypress event resetting it to `On(now)`.  That could allow for controlling the duration of `On` and `Off` separately.

**Comment by jsgf** [comment]
I made it purely a function of its position, rather than tying it to keypresses.
