### ISSUE TITLE
[Windows] Skip close confirmation when pane(s) are idle

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#843]
"Really kill this tab and all contained panes?" appears on every tab close, even if the shell is inactive and has no child processes. 

**Is your feature request related to a problem? Please describe.**
A solution was made for macOS and Linux here: https://github.com/wez/wezterm/issues/562. But, there's nothing yet for Windows.

**Describe the solution you'd like**
Through the ConPTY API, there might have a way to detect if cmd, ssh, pwsh, or powershell is inactive, maybe by checking to see if its ready to receive input.

**Comment by wez** [comment]
I looked into this today; the solution actually does work on windows, it's just that the default https://wezfurlong.org/wezterm/config/lua/config/skip_close_confirmation_for_processes_named.html doesn't include any windows shell proccesses.

I'm pushing a commit that adds `cmd.exe`, `pwsh.exe` and `powershell.exe` to that list.

I don't think `ssh.exe` is a safe thing to add by default, as there is no way to see inside the ssh session to tell if you would lose anything important, but you are welcome to set that config for yourself in your wezterm.lua
