### ISSUE TITLE
More specific quick select

### ISSUE THREAD

**Issue by mredaelli** [wez/wezterm#846]
**Is your feature request related to a problem? Please describe.**

As a user of kitty, one thing I miss (at least I think it's not possible) from wezterm is the ability to bind different keys to `quick select`-ing different patterns (one key for URLs, one for file paths, one for hashes, ...).

**Describe the solution you'd like**

Either
- add parameters to the `QuickSelect` action, or
- allow to update the current config programmatically in a custom event, so that we can set the parameters in the handler

**Comment by wez** [comment]
Thanks for the suggestion!

This is now available in `main` and will show up in the night build downloads within an hour.
Docs at: https://wezfurlong.org/wezterm/config/lua/keyassignment/QuickSelectArgs.html

**Comment by mredaelli** [comment]
Awesome, thank you! That was my last excuse not to adopt ;)
