### ISSUE TITLE
Change Titlebar Color

### ISSUE THREAD

**Issue by ironfish** [wez/wezterm#850]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to be able to change the color of the titlebar like in iTerm or Alacritty.

**Describe alternatives you've considered**
I checked the documentation and issues and did not find any information on this feature.

**Comment by wez** [comment]
Could you please be more specific about what behavior you want to see?
Do you mean the title bar of the Window that is provided by the OS?
Do you mean the tab bar that shows the tabs and status information?

The tab bar has configuration described here:
 https://wezfurlong.org/wezterm/config/appearance.html#tab-bar-appearance--colors
 https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html

The OS title bar can be disabled using:
 https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html

**Comment by ironfish** [comment]
Titlebar as in the one provided by the OS. https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html handles my needs so I will close the issue.

**Comment by rashil2000** [comment]
Is disabling the titlebar the only workaround? Titlebar on Windows is always black, irrespective of OS theme. Would prefer having a at least a light/dark toggle in the config file.

**Comment by wez** [comment]
> Is disabling the titlebar the only workaround? Titlebar on Windows is always black, irrespective of OS theme. Would prefer having a at least a light/dark toggle in the config file.

There are currently no options to control the OS titlebar colour.

**Comment by rashil2000** [comment]
Is it possible/planned?

**Comment by wez** [comment]
It varies by OS/desktop environment.  Making it fully configurable means essentially replacing the native UI which is a lot more complex than just turning it off, and it needs to be solved 4 times (one for each supported environment), which makes it extra time consuming. I'd like to end up with something that looks a bit like eg: Chrome's integrated title and tab bar.

Re: windows dark/light mode titlebar: please file an issue for that.  I made the opinionated choice of always forcing dark mode.  That part can be made configurable.

**Comment by rashil2000** [comment]
> Re: windows dark/light mode titlebar: please file an issue for that. I made the opinionated choice of always forcing dark mode. That part can be made configurable.

Done #894
