### ISSUE TITLE
Occasional crashing while using Kakoune and holding shift+x on long files

### ISSUE THREAD

**Issue by Anomalocaridid** [wez/wezterm#852]
## Describe the bug

On certain long files, such as my config files for zsh and Kakoune (a TUI text editor similar to Vim), if I open them in Kakoune and hold shift+x, Wezterm sometimes crashes after a few seconds. This does not appear to occur when I use another terminal such as Konsole. I was also able to reproduce this using bash instead of zsh as a shell and running a new instance of wezterm without my wezterm.lua with wezterm -n. Sometimes, this happens when I only highlight a few lines in the middle of the file with shift+x.

## Environment (please complete the following information):

 - OS: EndeavourOS Linux KDE
 - Version: wezterm 20210502-154244-3f7122cb
 - The active keyboard layout name: ENG (I think)

## To Reproduce

Steps to reproduce the behavior.

1. Open a long text file in Kakoune (maybe at least around 200 lines)
2. From any position with enough space from the bottom, hold down shift+x until it crashes.

## Configuration

Since I have been able to reproduce this with a different shell and without my wezterm config, I think that neither are related to this issue, but strangely, I have not been able to reproduce this without my Kakoune config (attached as kakrc.txt, rename it to kakrc and place it at ~/.config/kak/kakrc). 

[kakrc.txt](https://github.com/wez/wezterm/files/6605135/kakrc.txt)

## Expected behavior
I expected wezterm to not crash.

## Additional context

Even though I have not been able to reproduce the issue without my Kakoune config, I still think it is an issue with wezterm and not Kakoune because Kakoune has not had any releases since September 2020, while I have only been using wezterm since this April and have not had this issue with other shells.

**Comment by wez** [comment]
Please try the nightly build; there have been a couple of bug fixes that likely resolve this!
If the nightly doesn't make this better, then please include the panic output from wezterm; launch wezterm from a terminal to see its stderr output and include that as a comment on this issue.

**Comment by Anomalocaridid** [comment]
The nightly version seems to fix it. Thanks!
