### ISSUE TITLE
Tab title does not update automatically on macOS

### ISSUE THREAD

**Issue by kevinsjoberg** [wez/wezterm#862]
## Describe the bug

The tab title isn't updating at all. Instead, it always states `wezterm`.

## Environment (please complete the following information):

 - OS: macOS, 11.3.1
 - Version: wezterm 20210502-154244-3f7122cb
 - U.S.

## To Reproduce

I start WezTerm, open two tabs and start some interactive programs in both. Both tab's title state `wezterm`.

## Configuration

Be sure to include the relevant section(s) of your `wezterm.lua` configuration file.

## Expected behavior

I'd expect the title to update according to whatever process is currently running.

## Screenshots

If applicable, <img width="792" alt="Screenshot 2021-06-09 at 15 20 01" src="https://user-images.githubusercontent.com/503025/121362129-2ae50080-c936-11eb-84aa-fdfdb779c76a.png">

<img width="792" alt="Screenshot 2021-06-09 at 15 20 18" src="https://user-images.githubusercontent.com/503025/121362165-33d5d200-c936-11eb-9de8-41689bc8b60b.png">

**Comment by wez** [comment]
This isn't a bug. You need to use some kind of shell integration to emit escape sequences that change the title. That way the title will be updated even for sessions running remotely via ssh.

Many shells have prompt integrations that do something like that, but it can be done more simply by defining a `preexec` function that uses `OSC 0`, `OSC 1` or `OSC 2` to set the title.  The "Icon Name" is used to set the tab title.

https://wezfurlong.org/wezterm/escape-sequences.html#operating-system-command-sequences

```bash
printf "\e]0;%s\e\\" "the new title"
```

**Comment by kevinsjoberg** [comment]
@wez I see, that makes sense. Thanks for the clarification. 🙂
