### ISSUE TITLE
investigate large PDU size in multiplexer connections

### ISSUE THREAD

**Issue by Mic92** [wez/wezterm#867]
## Describe the bug

I saw that my local mux server is currently spending the majority of time doing zstd compression.
This seems wasteful if the result is transferred over a local unix socket.

**Comment by Mic92** [comment]
Potentially this can be also disabled when using ssh if the ssh layer is doing compression?

**Comment by wez** [comment]
FWIW, I think the visible use of compression in the profile is a symptom rather than a cause of issues.  There appears to be a fairly large chunk of data that is `O(screen-area)` being generated in response to eg: moving the cursor up in vim. I think that is the thing to focus on.

**Comment by Mic92** [comment]
Mosh uses the following diff algorithm to minimize data exchange between server and client:
https://github.com/mobile-shell/mosh/blob/03087e7a761df300c2d8cd6e072890f8e1059dfa/src/statesync/completeterminal.cc#L72
