### ISSUE TITLE
Terminal freezes when pasting text with mouse middle button 

### ISSUE THREAD

**Issue by rbelem** [wez/wezterm#87]
## Is it a build problem?

No

## Did something not work the way you expected?

Tried to paste a text using the mouse middle button and the terminal freezed. The close button was not working as well. I had to run `pkill wezterm` to kill the frozen instances. 

### What did you try?

Copied a text from firefox and tried to paste.

### What did you expect to happen?

Ability to paste a text into the terminal. 

### What actually happened?

It freezed.

**Comment by wez** [comment]
Please provide some more details:
* Roughly how much text were you copying and pasting?  (more than 1KB?)
* Does it reproduce if you try it again?
* Does the keyboard shortcut succeed? (shift+insert, or shift+ctrl+v)
* What operating system are you running wezterm on?  If Linux, are you running under Wayland or X11?

**Comment by rbelem** [comment]
1. A small text is enough to make it freeze
2. Every time
3. Nope. And looks like it cleans the clipboard.
4. Kde neon 5.17, xorg 7.7

**Comment by wez** [comment]
@rbelem I could reproduce the hang with the middle mouse button locally and I've pushed a fix for that.  Would you mind building that locally to confirm?  If you didn't build from source, that commit should show up in the nightly downloads in about 2 hours.

**Comment by rbelem** [comment]
Wow! That was quick! :-O Thanks
I will install the build deps now \o/

**Comment by rbelem** [comment]
The patch works!!! :-D
Thank you :relaxed:
