### ISSUE TITLE
Get process name in titlebar format

### ISSUE THREAD

**Issue by rbutoi** [wez/wezterm#876]
**Is your feature request related to a problem? Please describe.**
The general problem I'd like to solve is opening different wezterms for different purposes (bash, ssh, mosh) and identifying them by the process that was started through the title.

**Describe the solution you'd like**
An additional value in https://wezfurlong.org/wezterm/config/lua/PaneInformation.html for the process (and potentially full command line after `wezterm start -- ...`).

**Describe alternatives you've considered**
Using `title` or `user_vars` through OSC codes - too heavy handed. Just identifying the (original, starting) process is enough.

**Additional context**
Other terminal emulators seem to do this by default. I think it's a more useful default than "Wezterm" if no title was set.

**Comment by wez** [comment]
I just pushed a commit that allows this:

```lua
local wezterm = require 'wezterm'

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  local pane = tab.active_pane
  local title = pane.foreground_process_name
  local color = "navy"
  if tab.is_active then
    color = "blue"
  end
  return {
    {Background={Color=color}},
    {Text=" " .. title .. " "},
  }
end)

return {
}
```

this should be available in the nightly builds within an hour.

**Comment by wez** [comment]
Docs at https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html and https://wezfurlong.org/wezterm/config/lua/PaneInformation.html
