### ISSUE TITLE
key assignments should match before dead keys are expanded

### ISSUE THREAD

**Issue by bew** [wez/wezterm#877]
**Is your feature request related to a problem? Please describe.**
I have a keyboard (FR) with a few dead keys, the most notable one being `^` (that sits right next to `$`).

I would like to have `Alt-^` send `\x1b^` on the first press.
I have checked the debug key events when I press that `^` key:
```
key_event KeyEvent { key: Char('^'), modifiers: NONE, raw_key: None, raw_modifiers: NONE, raw_code: Some(34), repeat_count: 1, key_is_down: true }
```
I've tried to map the raw key with:
```lua
{
  keys = {
    {
      mods = "ALT",
      key = "raw:34",
      action = wezterm.action{SendString="\x1b^"}
    }
  }
}
```
I also tried sending the string `foo` to verify the sent string wasn't interfering.

MAYBE BUG?: actually I have a few more dead keys, like `` ` `` that is _never_ triggered as a dead key (but on windows it _is_ triggered as a dead key by default)
(OS: Linux X11, keyboard: FR, version: `20210502-154244-3f7122cb`, I'm using the default value for config `dead_keys`)

**Describe the solution you'd like**
1. Disable the dead keys system for keybindings that are mapped to actions (to not have to press the keys twice if al I want to do it send a string or switch tabs).
2. A way to specify an option for the action `SendString`, named something like: `ConsiderForDeadKey=bool`, to bypass/activate the dead key system regardless of the state of the config `dead_keys`.

I see 2 use cases:
- Have `dead_keys=true`, and map a few keybinds to force bypass the dead keys system (sending `` ` `` or `^` on the first keybind press).
- Have `dead_keys=false`, and map a few keybinds to force enable the dead keys system for the `SendString` action.

**Describe alternatives you've considered**
None..

---
This feature request is for 2 things on the same subject, I feel like they are close, but if you prefer I can split them up!
(regarding `Don't consider dead keys for keybindings`, is it a bug?)

**Comment by wez** [comment]
Today, dead key expansion is handled in the OS specific layer in the `window` crate before any key event information is generated.

We'd need to do some work to formally split the keyboard processing into phases so that the wezterm-gui layer knows whether we're dealing with dead key expansion or not.

That would help with the implementation of https://github.com/wez/wezterm/issues/688

If we can match the pre-dead-key state of a key in a key assignment, it feels like we'd probably always/only ever want to do that.
Can you think of cases where you'd want your key assignment to match after dead key processing?

**Comment by bew** [comment]
> Can you think of cases where you'd want your key assignment to match after dead key processing?

If I understand this correctly, you're asking if a multi key (with a dead one) like ^ + e => ê should trigger a key assignment with a trigger on ê ?
I don't think so

**Comment by wez** [comment]
I've re-titled this issue; ignoring other bugs(!) would that solve the heart of the issue?  I think yes, but want to make sure I'm not missing something!

**Comment by wez** [comment]
The current state of `main` is that you can use `raw:XXX` or `phys:XXX` in your key assignments and those will match raw key events before dead key processing is considered.

I think the remaining questions around this are best tackled in: https://github.com/wez/wezterm/issues/1483

**Comment by bew** [comment]
Yes I think it's good. I didn't test yet, but I will.

Re-reading my original issue and seeing how you reworked the input layer, my second usecase doesn't need really make sense and it doesn't need any work from you.
