### ISSUE TITLE
Mouse selection in neovim jumps from word to word instead of char to char

### ISSUE THREAD

**Issue by bew** [wez/wezterm#878]
## Describe the bug

When doing a mouse selection in neovim:

I cannot select a few letters in a word, as the cursor moves from word to word instead of char to char:
https://user-images.githubusercontent.com/9730330/122131933-41112600-ce3a-11eb-9557-1a1d6a2735b3.mp4

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: `wezterm 20210502-154244-3f7122cb`
 - The active keyboard layout: FR

## To Reproduce

Open `wezterm -n`.
Open neovim, activate the mouse for normal & visual mode with `:set mouse=nv`, then write a few words and try to select (a few chars like in the video) with simple click & drag.

## Configuration

Not needed.

## Expected behavior

The cursor should move from char to char, like in xterm:

https://user-images.githubusercontent.com/9730330/122132343-f348ed80-ce3a-11eb-854d-6579c5cdd809.mp4

**Comment by wez** [comment]
Presumably the same as #823 and fixed in the nightly by https://github.com/wez/wezterm/commit/2e924c9627fba2178155bdf2177eda84e1daf99a

**Comment by bew** [comment]
I confirm :ok_hand:
