### ISSUE TITLE
Open wezterm here does not use default_prog

### ISSUE THREAD

**Issue by phgmacedo** [wez/wezterm#885]
## Describe the bug

Open wezterm here does not use default_prog.

## Environment (please complete the following information):

 - OS: Windows
 - Version: wezterm 20210502-154244-3f7122cb
 - Keyboard: POR

## To Reproduce
On windows: 

Install with installer. 
Add to config `default_prog = {"wsl"},` for using wsl. 

1. On a directory, right click "open wezterm here". 
2. Wezterm does opens in powershell, instead of wsl
3. Type `wezterm`, which opens in wsl in the current dir

## Configuration

```
local wezterm = require 'wezterm'

return {
	color_scheme = "Monokai Remastered",
	window_background_opacity = 0.92,
	window_close_confirmation = "NeverPrompt",
	enable_scroll_bar = true,
	font_size = 10.5,
	window_decorations = "NONE",
	-- default_prog = {"powershell", "-NoLogo"},
	default_prog = {"wsl"},
}
```
## Expected behavior
Opening wezterm from right-click menu should use wsl, instead of powershell. 
The same as calling "wezterm" from a folder.

**Comment by wez** [comment]
I think this is already fixed in the nightly build; please give it a try!
