### ISSUE TITLE
Add the ability to focus a given pane given its id from the command line

### ISSUE THREAD

**Issue by Anomalocaridid** [wez/wezterm#886]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to be able to focus a given pane in WezTerm from the command line given its window, tab, and pane ids.

**Describe alternatives you've considered**
There are no alternatives that I am aware of that provide this.

**Additional context**
I created a plugin for the text editor Kakoune that aims to provide integration with WezTerm that is similar to the integration that Kakoune provides with other terminal emulators and terminal multiplexers by default. This would allow me to add functionality that is currently missing when compared with the default terminal integration.

**Comment by igorepst** [comment]
This would be very helpful indeed. For ex., it will give a possibility to spawn a new tab from TUI file manager with the selected directory and give the tab a focus.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
