### ISSUE TITLE
Add the ability to create a new wezterm window in the command line that is part of the same session as the terminal it is called from

### ISSUE THREAD

**Issue by Anomalocaridid** [wez/wezterm#887]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to be able to create a new wezterm window using the command line that is part of the same session.

**Describe alternatives you've considered**
Using the `wezterm start` command works fine, but since it opens a window in a new session, it may become problematic when used in conjunction with the features requested by issues #886 and #888. Using the keyboard shortcut for a new window works fine, but it is not a viable solution for use in a script.

**Additional context**
I created a plugin for the text editor Kakoune that aims to provide integration with WezTerm that is similar to the integration that Kakoune provides with other terminal emulators and terminal multiplexers by default. This would allow me to add functionality that is currently missing when compared with the default terminal integration.

**Comment by wez** [comment]
Did you try `wezterm cli spawn --help`?
(I think it may be missing a flag to actually allow a new window to spawn, but the intent is that it would allow that)

**Comment by Anomalocaridid** [comment]
Thank you!
