### ISSUE TITLE
Send text to a wezterm pane given its id from the command line

### ISSUE THREAD

**Issue by Anomalocaridid** [wez/wezterm#888]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like the ability to send text to a wezterm pane, given its window, tab, and pane ids, like a window created with `wezterm start` and running an interactive program like a shell in order to execute the text as a command or enter it as some other input.

**Describe alternatives you've considered**
I am unaware of any alternatives that give a similar functionality.

**Additional context**
I created a plugin for the text editor Kakoune that aims to provide integration with WezTerm that is similar to the integration that Kakoune provides with other terminal emulators and terminal multiplexers by default. This would allow me to add functionality that is currently missing when compared with the default terminal integration.

**Comment by xiangpeng2008** [comment]
so this is not yet supported, right

**Comment by wez** [comment]
In the nightly build available within 30 mins of this comment being posted, you can do:

```
wezterm cli send-text "hello"
```

or:

```
echo something | wezterm cli send-text
```

See `wezterm cli send-text --help` for more information.

**Comment by xiangpeng2008** [comment]
hi @wez 
how to get the `pane-id` ?
When I do `wezterm cli list`, I got only 1 record, is this expected ?
I opened 2 tabs and multiples panes.
![image](https://user-images.githubusercontent.com/15676035/167295558-1c0c38d3-b485-4f1c-84b7-21b6b001c8a9.png)

**Comment by xiangpeng2008** [comment]
When I tested without ssh on mac, I got 2 records by just opening a new tab.
<img width="503" alt="Screenshot 2022-05-08 at 10 08 17 PM" src="https://user-images.githubusercontent.com/15676035/167300231-cd9d216e-170a-4698-a151-dd40b822b044.png">

**Comment by wez** [comment]
@xiangpeng2008: please open a separate issue!

**Comment by xiangpeng2008** [comment]
btw, how could I send a `enter` or break-line key ?
for example, I want pane 0 to execute `echo hello`, but `wezterm cli send-text --pane-id 0 "echo hello\n"` doesn't do the job, it just shows
![image](https://user-images.githubusercontent.com/15676035/167360971-e492109c-d8bc-400e-a983-98795d084942.png)

**Comment by xiangpeng2008** [comment]
also is there an easy way to know the pane id of specific pane ?

**Comment by wez** [comment]
wezterm sets the `WEZTERM_PANE` environment variable to the pane id when it launches a pane.  The CLI will use that as the pane id if you don't explicitly specify it.

**Comment by xiangpeng2008** [comment]
> btw, how could I send a `enter` or break-line key ? for example, I want pane 0 to execute `echo hello`, but `wezterm cli send-text --pane-id 0 "echo hello\n"` doesn't do the job, it just shows ![image](https://user-images.githubusercontent.com/15676035/167360971-e492109c-d8bc-400e-a983-98795d084942.png)

hi @wez , do you have an idea to send an `enter` key ?

**Comment by xiangpeng2008** [comment]
btw, is it possible to get current wezterm window id , and wezterm pane id ? 
![image](https://user-images.githubusercontent.com/15676035/167794303-112b6a68-e24f-4c06-a4e7-6abd68dc9065.png)
I didn't seem to see them in the `env`

**Comment by xiangpeng2008** [comment]
> sorry when I said "enter" I wanted to let my command to be executed, but when I do
> 
> ```
> echo -e "echo hello\n" | wezterm cli send-text --pane-id 0
> ```
> 
> The command is not executed, but just have line break after. <img alt="Screenshot 2022-05-10 at 11 13 05 PM" width="366" src="https://user-images.githubusercontent.com/15676035/167662450-bf6c6060-564d-4c2a-bcae-f63bd7e380b6.png">

actually this only happens for mac, when I connect from windows 10 to centos 7, 
```
echo -e "echo hello\necho world" | wezterm cli send-text --pane-id 7
```
`\n` could serve as enter
![image](https://user-images.githubusercontent.com/15676035/167821764-3aa2a866-2622-4eeb-88a5-f5cc027ddbc8.png)

**Comment by wez** [comment]
385f3c99d3b2311fde1ed494d0d3d327ebdca28b adds a `--no-paste` flag to `wezterm cli send-text`
