### ISSUE TITLE
Double-click word select doesn't select on drag

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#89]
## Describe the bug

When using double-click to select a word, drag doesn't keep selecting words. It also only pastes the first word, not the whole selection.

## Environment (please complete the following information):

 - OS: Linux X11
 - Frontend:  OpenGLwezterm fsdsdf
 - Version: wezterm 20191218-101156-bf35707-50-ga42342c
![word-select](https://user-images.githubusercontent.com/147966/71550066-ef8e8600-297c-11ea-899d-a446f403ab47.gif)

## To Reproduce

1. double-click on a word to select word
2. drag to select more text
3. middle-click to paste

## Configuration

```
enable_scroll_bar = true
default_cursor_style = "BlinkingUnderline"

[window_padding]
left = 5
right = 5
top = 5
bottom = 2

[[keys]]
key = "PageUp"
mods = "CTRL"
action = "ActivateTabRelative"
arg = "1"

[[keys]]
key = "PageDown"
mods = "CTRL"
action = "ActivateTabRelative"
arg = "-1"
```

## Expected behavior

After the initial double-click to select a word, dragging to select more text should continue to select words rather than individual characters.

Middle-click should paste all the selected text, not just the initial word.

## Screenshots

![word-select](https://user-images.githubusercontent.com/147966/71550068-f7e6c100-297c-11ea-91e7-1c4a934fab88.gif)

**Comment by jsgf** [comment]
Also applies to triple-click line selection.

**Comment by wez** [comment]
The local selection changes in master haven't fixed this, but have rendered it differently broken: we now know when you are attempting a double or triple click drag and subsequently block the single click drag behavior that we used to have :-p  The good news is that we are now slightly better positioned to implement this.

**Comment by jsgf** [comment]
Yep, it nearly works. It doesn't repaint/clear the selection when switching tabs (is it maintained per-tab or for the window?).

**Comment by wez** [comment]
It used to be per tab but accidentally become per window.  I've just pushed a commit to scope it per tab again.
