### ISSUE TITLE
Closing the last pane in the second tab crashes wezterm

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#890]
## Describe the bug

When closing the last pane in a tab other than the first one, e.g. with:
```lua
    {key="q", mods="CTRL", action=wezterm.action{
      CloseCurrentPane={confirm=false}
    }},
```
Wezterm closes without actually exiting, and without any error message.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Version: wezterm 20210617-233305-618f77f2
 - DE

## To Reproduce

- Open a new Tab
- Press "CTRL+q"
- Enjoy
## Configuration
```lua
local wezterm = require 'wezterm';
return {
  keys = {
    {key="q", mods="CTRL", action=wezterm.action{
      CloseCurrentPane={confirm=false}
    }},
  }
}
```

## Expected behavior
It should only close the currently opened tab

**Comment by wez** [comment]
What does wezterm log to stderr when this happens?

**Comment by ModProg** [comment]
> What does wezterm log to stderr when this happens?

Nothing:
```sh
❯ wezterm
 2021-06-19T16:48:00.553Z INFO  wezterm_mux_server_impl::local
> setting up /run/user/1000/wezterm/gui-sock-58943
 2021-06-19T16:48:00.624Z INFO  wezterm_gui::termwindow
> OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL ES 3.2 Mesa 21.1.1 is_context_loss_possible=false wezterm version: 20210617-233305-618f77f2
^C⏎
~ took 15s
❯
```

**Comment by wez** [comment]
Interesting: it's not crashing (it's still running), but the window gets closed
