### ISSUE TITLE
Italic font being selected at random

### ISSUE THREAD

**Issue by klamonte** [wez/wezterm#893]
My wezterm.lua has:

```
  font = wezterm.font({ family="Terminus", weight="Bold", italic=false }),
```

Sometimes this font is selected.  Sometimes the italic version is selected.  There appears to be no rhyme or reason to it.

Besides fixing this bug, can italic be disabled for ALL fonts?  It drives me nuts when line-drawing characters fail to line up because the fallback font is italic.

**Comment by klamonte** [comment]
Looking at wezterm-font/src/locator/gdi.rs, an option to force lfItalic to 0 always would be lovely:

```
fn load_font(font_attr: &FontAttributes) -> anyhow::Result<ParsedFont> {
    let mut log_font = LOGFONTW {
        lfHeight: 0,
        lfWidth: 0,
        lfEscapement: 0,
        lfOrientation: 0,
        lfWeight: font_attr.weight.to_opentype_weight() as _,
        lfItalic: 0, // if font_attr.italic { 1 } else { 0 },
        lfUnderline: 0,
        lfStrikeOut: 0,
        lfCharSet: 0,
        lfOutPrecision: OUT_TT_ONLY_PRECIS as u8,
        lfClipPrecision: 0,
        lfQuality: 0,
        lfPitchAndFamily: FIXED_PITCH as u8,
        lfFaceName: [0u16; 32],
    };
```

**Comment by wez** [comment]
Hmm, the behavior should be deterministic:

https://github.com/wez/wezterm/blob/7afe539b0c3c9717ba55af89059320004abe12d1/wezterm-font/src/parser.rs#L391 is where we decide whether we should synthesize italics; that logic says "if the requested font attributes were italic and the matched font isn't, then synthesize italics at render time".

The [font_rules](https://wezfurlong.org/wezterm/config/lua/config/font_rules.html) config is used to map cell attributes to alternate font selections.  The default font_rules are derived from the main `font` configuration.  `wezterm ls-fonts` should show you which fonts are used for italics and whether those will use synthesized italic, bold or dim.  You could try setting some explicit rules that match italic to avoid that.
 
A possible source of non-determinism is that there's a discrepancy between the [PartialEq](https://github.com/wez/wezterm/blob/7afe539b0c3c9717ba55af89059320004abe12d1/wezterm-font/src/parser.rs#L61) and [Ord](https://github.com/wez/wezterm/blob/7afe539b0c3c9717ba55af89059320004abe12d1/wezterm-font/src/parser.rs#L70) implementations for ParsedFont (equality doesn't compare as many sub-fields as comparison).  I haven't seen that cause problems before, but that's a place that is possibly a bit wonky.

**Comment by klamonte** [comment]
I think I really just want to have an option to disable the implicit fallback font(s).  For example, make it possible to have exactly one font and unknown glyphs just become box or ? or whatever; or perhaps two fonts, but both named by the user and not any of those normally shipped.

I'm curious if that would speed up startup time.

**Comment by klamonte** [comment]
With the changes for #1162 , I am not seeing italic anymore where I do not expect it.

Closing this issue.
