### ISSUE TITLE
Follow OS theme for titlebar color

### ISSUE THREAD

**Issue by rashil2000** [wez/wezterm#894]
**Is your feature request related to a problem? Please describe.**
The dark system theme on Windows is quite half-assed, so I tend to avoid it as much as possible. So I use light theme everywhere, but wezterm's always-dark titlebar does not look very good with any light config theme (for example BlulocoLight in wezterm.lua).

**Describe the solution you'd like**
Ideally it should be configurable in the config file itself, but I understand that the implementation of this on all platforms might be a hassle. So a really simple way would be to just follow the OS (Windows here) and provide a white and black version for the titlebar.

**Describe alternatives you've considered**
I have considered hiding the titlebar altogether, but that's not really ideal (it hides the window title, and moving/minimizing/closing all require some keyboard shortcuts)

**Additional context**
None

**Comment by rashil2000** [comment]
Hi! 
Are there any plans for this?

**Comment by wez** [comment]
It's something that I want to see happen, but haven't had time to do myself.  If you wanted to take a crack at making this work on windows and submit a PR, the relevant things are:

* https://github.com/wez/wezterm/blob/main/window/src/os/windows/window.rs#L762 this bit of code is what forces the title bar into dark mode
* Some logic would need to be added to determine what the system theme is set to and then call the above to apply it.  Maybe https://stackoverflow.com/a/51336913/149111
* Some logic would need to be added to determine *when* the system theme changes and then do the above.  https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-wininichange is probably the thing to hook up in https://github.com/wez/wezterm/blob/main/window/src/os/windows/window.rs#L1873 
* Ideally there would a method on [WindowOps](https://github.com/wez/wezterm/blob/main/window/src/lib.rs#L128) to retrieve the current theme, and then expose that via the lua API to make it easy to do https://github.com/wez/wezterm/issues/806

**Comment by rashil2000** [comment]
Hey, thanks for the detailed overview.

I see that a registry query is already being used here https://github.com/wez/wezterm/blob/main/window/src/os/windows/window.rs#L1065, we can follow similar logic to get the theme.

However I would note that I have no experience with Rust. Though it's definitely on my list, I'll try to take a shot at it if it's still open by that time.

**Comment by rashil2000** [comment]
I have made tiny changes so that wezterm now follows OS theme. Note that it doesn't listen for any events, as such wezterm needs to be restarted if theme is changed. The diff is small enough to be pasted here:

```diff
diff --git a/window/src/os/windows/window.rs b/window/src/os/windows/window.rs
index 531572ee..d1c95c9d 100644
--- a/window/src/os/windows/window.rs
+++ b/window/src/os/windows/window.rs
@@ -420,7 +420,7 @@ impl Window {
             .events
             .assign_window(window_handle.clone());
 
-        enable_dark_mode(hwnd.0);
+        enable_theme(hwnd.0);
         enable_blur_behind(hwnd.0);
 
         Connection::get()
@@ -759,12 +759,18 @@ fn enable_blur_behind(hwnd: HWND) {
     }
 }
 
-fn enable_dark_mode(hwnd: HWND) {
-    // Prefer to run in dark mode. This could be made configurable without
-    // a huge amount of effort, but I think it's fine to just be always
-    // dark mode by default :-p
-    // Note that the MS terminal app uses the logic found here for this
-    // stuff:
+fn read_theme() -> io::Result<u32> {
+    let hkcu = RegKey::predef(HKEY_CURRENT_USER);
+    let theme = hkcu.open_subkey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize")?;
+
+    theme.get_value::<u32, _>("AppsUseLightTheme")
+}
+
+fn enable_theme(hwnd: HWND) {
+    // Check for OS app theme, and set window attributes accordingly.
+    // If the OS app theme changes, the wezterm window would have to be
+    // restarted for changes to reflect.
+    // Note that the MS terminal app uses the logic found here for this stuff:
     // https://github.com/microsoft/terminal/blob/9b92986b49bed8cc41fde4d6ef080921c41e6d9e/src/interactivity/win32/windowtheme.cpp#L62
     use winapi::um::dwmapi::DwmSetWindowAttribute;
     use winapi::um::uxtheme::SetWindowTheme;
@@ -787,13 +793,16 @@ fn enable_dark_mode(hwnd: HWND) {
 
     const DWMWA_USE_IMMERSIVE_DARK_MODE: DWORD = 19;
     unsafe {
+        let is_dark = if read_theme().unwrap_or(1) == 1 { 0 } else { 1 };
+        let theme_string = if is_dark == 1 { "DarkMode_Explorer" } else { "" };
+
         SetWindowTheme(
             hwnd as _,
-            wide_string("DarkMode_Explorer").as_slice().as_ptr(),
+            wide_string(theme_string).as_slice().as_ptr(),
             std::ptr::null_mut(),
         );
 
-        let mut enabled: BOOL = 1;
+        let mut enabled: BOOL = is_dark;
         DwmSetWindowAttribute(
             hwnd as _,
             DWMWA_USE_IMMERSIVE_DARK_MODE,
```

**Comment by rashil2000** [comment]
Is it Ok if I send a PR, or should we first wait for event listening to be implemented?

**Comment by wez** [comment]
Please send a PR!  Events can come in a follow up!

**Comment by rashil2000** [comment]
#951 :)

**Comment by rashil2000** [comment]
This can be closed now?

**Comment by wez** [comment]
Yeah; there's some more stuff around dark mode on Windows that I'll wrap up tomorrow, but the specific issue with the titlebar is done.
Thank you!
