### ISSUE TITLE
Mouse event sending is inefficient

### ISSUE THREAD

**Issue by r00ster91** [wez/wezterm#897]
**Is your feature request related to a problem? Please describe.**
I noticed that wezterm is a little bit inefficient in regard to the frequency of event sending when mouse capturing is enabled and the mouse pointer's position is transmitted. The problem is that wezterm sends a new mouse position event for every single pixel movement but this is not required.

**Describe the solution you'd like**
wezterm should only send another mouse position event when it actually makes sense and the mouse pointer has been moved by one cell (`█`) and the data changed. Terminals are based on these cells and if your mouse hovers one and you move your mouse just by one pixel and you are still on the same terminal cell, then the mouse position data obviously doesn't change and yet wezterm sends a new event for every pixel of movement despite the data not being different.
This inefficiency slows wezterm itself down as well as programs reading those events.

**Describe alternatives you've considered**
I can't quite think of alternatives.

**Additional context**
I've attached two screencasts comparing alacritty and wezterm. Closely watch where the mouse is and whether it crossed one cell and watch the `Flush count` on the top left. You will quickly notice that wezterm amounts to quite a lot more flush counts far quicker than alacritty because alacritty only sends a new mouse position event when the mouse crossed one cell, the smallest "unit of space" in a terminal. These cells are as accurate as mouse tracking in the terminal can get so it doesn't make sense that wezterm sends the same data over and over when the mouse was only moved by one pixel and hasn't even left the cell.
The `Flush count` in the top left in this program [yayagram](https://github.com/r00ster91/yayagram) represents the amount of mouse position events received.

https://user-images.githubusercontent.com/35064754/122974680-e3795e00-d392-11eb-9b4c-e84e1b4f9824.mp4

*wezterm quickly surpasses a flush count (i.e. mouse position event count) of >1000 due to them being sent every pixel movement*

https://user-images.githubusercontent.com/35064754/122974685-e4aa8b00-d392-11eb-94a7-0eb5f9e78e76.mp4

*alacritty's flush count increases slowly even on rapid mouse movement due to mouse position events only sent when actually needed. Notice how the flush count increased only by one when the mouse moved down by one grid cell*

**Comment by bew** [comment]
Can you try the nightly version of wezterm?
There was a change in https://github.com/wez/wezterm/commit/2e924c9627fba2178155bdf2177eda84e1daf99a related to this that might interest you!

**Comment by r00ster91** [comment]
Oh well, that is exactly what I needed! Thanks for telling me and it's nice to meet you here!
