### ISSUE TITLE
Mouse position events are inaccurate

### ISSUE THREAD

**Issue by r00ster91** [wez/wezterm#898]
## Describe the bug

In #859 I suspected the cause of the mouse position events being inaccurate to be due to the cursor's look, because it was a beam cursor at that time instead of an arrow. Now that I tested nightly which includes this patch, I notice that the mouse events still seem inaccurate. I particularly notice this when I move the mouse around on the grid of [yayagram](https://github.com/r00ster91/yayagram). Hovered cells are highlighted on that grid.
This is not (and can not) be an issue of yayagram itself because it's quite well tested in various other terminal emulators where I haven't had these issues.

You can see it here:

https://user-images.githubusercontent.com/35064754/122983255-14aa5c00-d39c-11eb-96c9-77e263c4f192.mp4

As you can see in this screencast, there exists an inaccuracy both horizontally (particularly) and vertically. Notice how the mouse pointer is frequently pointing outside of the highlighted area. This grid does not make use of half blocks, sixel or anything, it's all in cells (`█`). One cell of the grid of yayagram is made of two cells of the terminal (`██`).
Now compare this to, for instance, GNOME Terminal:

https://user-images.githubusercontent.com/35064754/122983609-78cd2000-d39c-11eb-8b94-848afc1236e9.mp4

This is accurate. This is how it's supposed to be. wezterm is rather far from pixel-perfect.
As far as I can remember, wezterm is the first terminal to behave this way.

You can also easily notice/reproduce this inaccuracy in wezterm's very own exit screen as I mentioned in this comment: https://github.com/wez/wezterm/issues/859#issuecomment-864016963

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210620-190654-07799d0a
 - The active keyboard layout name: `en`

## Configuration

I only changed `default_cwd`.

## Expected behavior

Accurate mouse events that report the mouse position correctly based on terminal cells (`█`).

**Comment by wez** [comment]
wezterm rounds the mouse coordinates to make text selection more forgiving, but doesn't need to do this when the mouse is grabbed; I've pushed a commit to that effect.  Let me know how that works for you!

**Comment by r00ster91** [comment]
I've just downloaded a new `wezterm-nightly.Ubuntu20.04.deb` from https://wezfurlong.org/wezterm/install/linux.html#installing-on-ubuntu-and-debian-based-systems which I suppose includes this patch?
I've tested it and I think it's better now except for some very small inaccuracy left. It looks negligible on the screenshot but it's still noticeable (also on these screenshots it looks like it's just 1 pixel off but it was actually a few more pixels than that but the screenshot tool altered that a bit)

![image](https://user-images.githubusercontent.com/35064754/123293081-f6676c00-d513-11eb-800f-b15224e7d739.png)

Oh, and there's still this quite noticeable example:

![image](https://user-images.githubusercontent.com/35064754/123293062-f23b4e80-d513-11eb-9d76-ecb9dea621c0.png)

I might be wrong and the patch isn't on nightly yet. I suppose I will try again tomorrow.

**Comment by wez** [comment]
The close confirmation issue was not related to this, but I pushed a fix.
What you're seeing as an inaccuracy isn't: mouse cursors have a "hotspot" position; for the arrow pointer it is the tip of the black inner arrow, rather than the white outline.
Turning on the gnome accessibility option to zoom the screen, you can see that the cell highlight matches this hotspot position.
If you repeat the same exercise with gnome terminal you'll see that it behaves the same way.
