### ISSUE TITLE
PaneInformation field equivalent to pane:get_current_working_dir()

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#915]
I want to do something like this so that the tab title is of the current directory the terminal is in, rather than the location of the terminal application. In my case, the tab title is `C:\WINDOWS\system32\cmd.exe`, which isn't very pretty or useful.

---

`wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)`
`  if tab.is_active then`
`    return {`
`      {Text=`**tab.active_pane.working_dir**`},`
`    }`
`  end`
`  return tab.active_pane.title`
`end)`

---

_Ideally, I'd also want to do this with the window title, but I'll cross that bridge when I get to it..._

If this isn't possible, could you help me with manipulating the string so that it says 'cmd' or 'cmd.exe' instead of that full path?

**Comment by wez** [comment]
If the cwd hasn't been set with OSC 7 then `pane:get_current_working_dir()` can incur some relatively heavy IPC, especially on Windows.  The pane information is intended to be cheap to collect in bulk, so I'd want to make sure that this doesn't slow things down before making this change.

In the meantime, I'd recommend configuring the prompt in CMD to emit OSC 7 as shown in https://wezfurlong.org/wezterm/shell-integration.html#osc-7-on-windows-with-cmdexe

If you're doing that, you might also want to go ahead and have the prompt also update the window title by emitting the escape sequence for that as well.  I'm not on a windows box right now so this is untested, but something like:

```lua
return {
  set_environment_variables = {
    prompt = "$E]7;file://localhost/$P$E\\$E]1;$P$E\\$E[32m$T$E[0m $E[35m$P$E[36m$_$G$E[0m ",
  }
}
```

`$E]1;$P$E\\` should set the tab title to the current drive and path


See https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/prompt for more info about cmd.exe prompts.

https://wezfurlong.org/wezterm/escape-sequences.html#operating-system-command-sequences has OSC sequences for updating the title; 0, 1 and 2 are the codes you want.

**Comment by wez** [comment]
I just pushed a commit that allows this:

```lua
local wezterm = require 'wezterm'

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  local pane = tab.active_pane
  local cwd = pane. current_working_dir
  local color = "navy"
  if tab.is_active then
    color = "blue"
  end
  return {
    {Background={Color=color}},
    {Text=" " .. cwd .. " "},
  }
end)

return {
}
```

this should be available in the nightly builds within an hour.
