### ISSUE TITLE
Each ssh domain session is by default a mirror clone, can't just close only one's own client session

### ISSUE THREAD

**Issue by hgkamath** [wez/wezterm#917]
## Describe the bug
This needs some thinking. this issue is also a feature, just surprising and has some unintended consequences, such as closing one multiplexed session closes all multiplexed sessions. 

Each fresh start-connected ssh domain session is by default a mirror/clone
What is typed or executed in one session is mirrored in a another.
Indeed, this is what multiplexing in it full glory means. I was only hoping to reap only disconnection-reconnection benefits.
This is not immediately obvious from a reading of 
https://wezfurlong.org/wezterm/multiplexing.html?highlight=ssh#ssh-domains 

Perhaps, this a desirable feature, and the problem is only that the way it is discovered is unexpected. It has its uses, such as tandem troubleshooting from multiple logins or from multiple machines/locations simultaneously/real-time. Maybe, when one wants a mirror-clone or reconnect to a disconnected session, one should explicitly connect to one by specifying a session-ID. There should be some indicator of how many mirror-clones are open and from where (ipaddress/client-machine). One should also be able to remote terminate other client-sessions, or terminate the session in immediate use without affecting others. Perhaps this is already doable from the wezterm-mux-server
I think permission/ownership/view/edit permissions are not required as this is not a security lapse as the user at every terminal already has ssh-login credentials. 

Perhaps when starting a session, there is an argument/prompt for specified session-ID as to whether one want to mirror-connect to an existing session or start a new one.

## Environment (please complete the following information):

 - OS: [e.g. Linux X11, Linux Wayland, macOS, Windows]
 ssh session from vbox VM linux fedora-34 guest to windows-10 host
 - Version: please run `wezterm -V` and include its output here
```
wezterm -V
wezterm 20210630-133255-ba42367f
```
- The active keyboard layout name (eg: ENG, DEU and so on)
 EN-US

## To Reproduce

Steps to reproduce the behavior.

Please include as much information as possible that can help to reproduce and
understand the issue; some pointers and suggestions are included here in this
template. You are empowered to include more or less information than is asked
for here!

* Closing one wezterm-ssh-domain-session-window closes all others
  *  Start a new wezterm ssh-window wezterm connect host-pc
  *  Start another new wezterm ssh-window wezterm connect host-pc , or from another local wezterm window-session, from its +button start a new wezterm ssh domain session which will open in a new tab
  *  Close any one of the wezterm ssh-domain windows
  *  In addition to the one window being closed, all open wezterm-ssh-domain-session-windows to that ssh-domain will be closed, but local tabs if any, may survive. If a local tab is present, only the ssh-tabs disapear, leaving the window open with only the local-tabs
  * The 'really kill this window' confirmation dialog, however, is shown on only the window in which close is initiated. There is no indication that other client sessions will be closed.

* Each open wezterm-ssh-domain-session-windows are multiplexed mirror-clones of one-another
  *  Enter a command and execute in any one window. The same command can be in real-time seen to be typed and executed in all other wezterm-ssh-domain-session-windows.
  *  Start a new ssh tab in one window, identical tab is created in the other wezterm-ssh-domain-session-windows. newly created local tabs are not mirrored this way
  *  I wonder what would happen if two different machines or logins initiated a wezterm-ssh-domain-session-window to the same use account on a machine, will all of them get mirror-clones. I expect that with this implementation, each machine/login will get a mirror of the same ssh domain session.

Strange effect wherein two mirror-clone ssh-domain-session-windows popup upon reconnection
* open a regular wezterm-local-window
* start a wezterm-ssh-domain-session-window
* from the regular wezterm-local-window, use the + button to start a ssh-domain-window
* confirm that both wezterm-ssh-domain-windows are now mirror-clones
* close one of the mirror-clones, both wezterm-ssh-domain-windows will close. In particular, the second wezterm process terminates.
* restart the wezterm-ssh-domain-session-window
* two mirror-clones appear, one from the restarted wezterm, one from the regular wezterm. 
It does not matter which mirror-clone is closed.
However, sometimes a window will have gone into a "x-seconds since last response mode" in which case it does not get closed.

In general, it is hard to know which wezterm-window belongs-to/child-window-of  which wezterm process. Inside the shell, there can only be a WEZTERM_PANE no. mirror-clone tabs all have the same WEZTERM_PANE nos. Hence, a tab/pane needs to be identified by clientmachine-process-window-session-tab-pane. 

Strange undefined effect involving orphanned tabs/windows
* open a regular wezterm-local-window
* start a wezterm-ssh-domain-session-window
* from the regular wezterm-local-window, use the + button to start a ssh-domain-window
* confirm that both wezterm-ssh-domain-windows are now mirror-clones
* as before close one of the mirror-clones, 
* as before restart the wezterm-ssh-domain-window, restarting both mirror-clones
* Start a new ssh-domain tab on the first regular-wezterm-local-window
Things can go really undefined from there, sometimes a new wezterm-ssh-domain-session-window is opened, at other times, nothing happens. fedora-gnome-shell notification may show that an process start attempt was made.
Sometimes, it can leave orphaned mirrored tabs, even weirder, the orphaned tab is mirrored to another tab in the same window

Maximizing a window/resizing a window can screw things up. 
* when one of the mirror-clone wezterm-ssh-domain-window is maximised or resized. The other mirror-clones do not resize themselves. It is hard to know what to do in other mirror clones or how to bring the mirror clones back to same size easily. In them, it can be seen that text alignment is lost.

## Configuration
As of today Jun 2021, issue #507 , requires that a wezterm-mux-server be running for ssh domain sessions to work

Be sure to include the relevant section(s) of your `wezterm.lua` configuration file.
```
  ssh_domains = {
    {
      name="host-pc",
      remote_address="10.20.30.2",
      username="gana",
    },
  },
```

## Expected behavior
* To make explicit whether one wants a mirror-session/reconnected-session or a fresh-session at session initiation time.
* If this is the default behavior, then this atypical behavior needs to be clear in the documentation. On the other hand if one wants behavior with minimal surprises, each new connection to ssh-domain-session must be to a fresh ssh-domain-session unless user explicitly requested to be connected to a pre-existing one, 
* Presently, closing one multiplexed session closes all multiplexed sessions. When closing a multiplexed session, the prompt should ask whether to only close the users client session, or terminate all other client sessions also. 
* resizing one mirror clone should resize all mirror-clones the same way.
* The ssh-sessions go into "seconds-since response" states quite often, especially when not foregrounded, occluded by other windows or not in focus. This can create orphaned windows/with orphaned tabs and extra ssh-domain windows with some tabs in one window and others elsewhere.

## Screenshots

If applicable, add screenshots to help explain your problem.  Screenshots are most
appropriate for rendering issues.

## Session Recording

If the issue is with the way that escape sequences are processed it can be helpful
to capture the terminal output using the [`wt-record`](https://github.com/wez/wezterm/blob/master/wt-record)
script to run `wezterm` and record a transcript.  This requires the `script` utility
to be installed on your system (this is part of macOS and available in the `util-linux`
package on linux systems).

In the example below a file named `20180225161026.tgz` is produced.  Please attach that
file to this issue, or if it contains private or sensitive issue that you don't want the
public to see on GitHub, please find some other way to get that file to a project
contributor (perhaps Dropbox or email?).

```
$ ./wt-record
Transcript recorded in 20180225161026.tgz
```

You can use `wt-replay 20180225161026.tgz` to replay that file.

`wt-record` can only record the terminal output; it cannot record the input events going
in to the terminal, so if you are having an issue with input, please be sure to describe
it below!

**Comment by wez** [comment]
The mirroring behavior is intentional.

I think the most problematic portion of this issue is already tracked in https://github.com/wez/wezterm/issues/848

The multiplexer doesn't have a session concept today, but it will need to grow one in order to support https://github.com/wez/wezterm/issues/336 and I think that will give you the control that you want to have over wether you attach to an existing session or start a new one.

I think it is reasonable to expose some domain related info in [PaneInformation](https://wezfurlong.org/wezterm/config/lua/PaneInformation.html) so that uses can add indication to their tabs/status lines about the domain.

**Comment by hgkamath** [comment]
yes, #848 introduces the attach/detach semantics and expresses the idea that user should be aware and client should have some way to allow user to choose between attach/detach-session and new/kill-session, 
and #336 will bring session management like tmux.

you can close this issue, if you think that issue is the same. 

just penning some thoughts

This is just the way it is in ```screen``` command and perhaps also ```tmux```. 
tmux and screen had only one ncurses-screen-buffer with swappable buffers and panes to manage. 
Each buffer is the equivalent of a tab
wezterm could potentially have an additional degrees of freedom. multiple windows that could be connected with a session,

That leaves what to do with resizes.

* one should also be able to choose whether one is attach/detach-ing a session (whole set of tabs) or just a tab
* If a tab has panes, then all panes in that tab need to be attach/detach-ed.
* if a window has tabs, which may also have panes, so all tabs with panes need to be attach/detach-ed.
* It seems to me, that as is currently implemented a session has only 1 window. but if the implementation were to allow multiple windows per session, then the set of windows need to be attach/detach-ed.
* multiplexer should be able to handle and user should be able to start a brand-new session with its own set of tabs. 
* user should be able to connect to any session. 
* If one client session resizes a window/tab/pane, and so also another one, the two clients could end up fighting, each one messing up the other's view. 
* perhaps size information should be percolated to other clients, so that, if one client resizes it, others are notified and can act on the information, either manually or automatically resize their windows/panes to how the first client had resized it. 

This feature, as you said, will need to grow incrementally.
