### ISSUE TITLE
[Bug] Getting wrong terminal size when spawning via cli

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#920]
## Describe the bug

I am getting wrong terminal size when creating tabs using cli. The size is always 80x24, regardless of window size (smaller/bigger than 80x24), or layout (float/tile). It works correctly if I use keyboard shortcut (`Ctrl+Shift+T`). 

## Environment (please complete the following information):

 - OS: Manjaro X11 with XMonad
 - Version: 20210630-133255-ba42367f
 - Keboard layout: ENG

## To Reproduce

```
$ wezterm cli spawn

# go to created tab
$ tput lines
24
$ tput cols
80
```

## Configuration

```
return {
   term = "wezterm",
   adjust_window_size_when_changing_font_size = true,
   enable_scroll_bar = true,
}
```

## Expected behavior

Should have same size as current window.

## Screenshots

![wezterm_spawn_window_error](https://user-images.githubusercontent.com/8190126/124231631-2626fd00-db2e-11eb-8f0d-7b890bb3eff0.png)

What you see on the bottom-right position is from the last used tab. Wezterm doesn't repaint portions outside 80x24.

## Session Recording

NIL.

## Additional context

Re. https://github.com/wez/wezterm/issues/695#issuecomment-872757241.

**Comment by MuhammedZakir** [comment]
It's fixed. Thanks! :+1:

**Comment by wez** [comment]
Thanks for confirming; I'll keep this open just a bit longer so that I can remember to write up the changelog!
