### ISSUE TITLE
Disable mapping for SHIFT+TAB

### ISSUE THREAD

**Issue by dkbhaskaran** [wez/wezterm#930]
Hi, 

Is there a way to disable default mapping for SHIFT+TAB? I have tried  setting the option 'disable_default_key_bindings' to true  but nothing happened and I also tried to disable key binding directly to none using  

{key="", mods="SHIFT|TAB", action="DisableDefaultAssignment"},

But this errors out. 

Thanks in advance for the help.
Dinesh

**Comment by wez** [comment]
There is no wezterm-specific key assignment for shift-tab; it generates the same sequence as for other terminal emulators. `\e[Z`.
What's your higher level problem/purpose?

**Comment by dkbhaskaran** [comment]
My primary use case is connecting to a Ubuntu 18.04 based server for work. I was using putty and now I am trying out wezterm. I have configured SHIFT+TAB as the key combination in VIM to circle through the available buffers in reverser order (and TAB for normal order). This was working fine in putty but in wezterm SHIFT+TAB produces no action. The server-side configurations are all same for both wezterm and putty. So I assume it is to do with the terminal configuration itself. 

Is there a way to understand what is happening here?

Thanks,
Dinesh

**Comment by wez** [comment]
The first thing I'd suggest is using `od -c` to print out how the keypresses are encoded.
The steps are:

* Run `od -c`
* Press `SHIFT-TAB`
* Observe the output.  I see:

```
; od -c
^[[Z
```

Do this in both wezterm and in putty to see if they are the same.
It can also be helpful to compare the $TERM value for both.

What did you use in your vim configuration to bind to shift-tab?

**Comment by dkbhaskaran** [comment]
I have a matching output for puttty but wezterm shows the below output with `od -c` command
```
^[[~
```
The $TERM is set to screen-256color. I think this is the problem. Is there a way to reconfigure this mapping to match putty's output? 

---------------------------------
vim settings 

```
nnoremap  <silent>   <tab>  :if &modifiable && !&readonly && &modified <CR> :write<CR> :endif<CR>:bnext<CR>
nnoremap  <silent> <s-tab>  :if &modifiable && !&readonly && &modified <CR> :write<CR> :endif<CR>:bprevious<CR>
```

Thanks,
Dinesh

**Comment by wez** [comment]
Hmm, from inside wezterm, run:

```
wezterm --config debug_key_events=true
```

then in the new wezterm window that is spawned, press SHIFT-TAB.
The first window should show what wezterm thinks is being pressed.
(See https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html for more information on this).

Please also share which keyboard layout you have active in your OS.

**Comment by dkbhaskaran** [comment]
This output seems to be as expected 

```
wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\t'), modifiers: SHIFT, raw_key: None, raw_modifiers: SHIFT, raw_code: Some(9), repeat_count: 1, key_is_down: true }
```

The keyboard is standard 104-key US QWERTY layout and the input language is English (United States) - US.

Thanks,
Diensh

**Comment by wez** [comment]
The key event diagnostics show that wezterm is recognizing the key correctly.
It's consistent with what I see on my windows system, however, I cannot reproduce what you're seeing on my Windows system.
Is there something else about your system and configuration that we haven't captured here?  Are you running something like tmux on the remote host?  If so, can you try running outside of tmux to confirm the behavior?

I noticed that you didn't follow the https://github.com/wez/wezterm/blob/main/.github/ISSUE_TEMPLATE/bug_report.md template; please take a few moments to go through that and include the environment and configuration here.

**Comment by dkbhaskaran** [comment]
Sorry for the delay in writing. I wasn't sure if this was indeed a bug or feature. Here are the details 
1. Environment details : Windows version Version 10.0.18363.1646, wezterm 20210707-172118-b08a6ab5.
2. Active keyboard name : ENG.
3. Problem Description and steps to reproduce : When I do ssh from wezterm to Ubuntu 18.04.5 LTS, the key press encoding for SHIFT+TAB changes to ^[[~ from ^[[Z. This issue is not seen when ssh is done from putty to the same user@machine. Please note that the user is created afresh and only inherits global system configuration.

The keypress encoding is fine when tried before ssh.

I have tried different shells on Unix machine-like zsh and bash, the results are the same. 

I also tried a different machine with Ubuntu 16.04.7 LTS, this issue is not reproducible. 

Expected behavior : Produce correct encoding of ^[[Z for SHIFT+TAB. 

Attaching my lua configuration.

**Comment by wez** [comment]
When you ssh into the remote host, are you using `wezterm ssh` or running an ssh command line program?  If so, which one? (cygwin, wsl, gitbash or something else?)

**Comment by dkbhaskaran** [comment]
I am using the default ssh program in Windows. I see that even from the windows command prompt this issue is replicable. Seems like the windows ssh related issue :(
