### ISSUE TITLE
Wezterm crashes when printing garbage

### ISSUE THREAD

**Issue by untoreh** [wez/wezterm#940]
## Describe the bug

Trying to print the output of this script makes wezterm crash

## Environment (please complete the following information):

 - OS: ``Microsoft Windows NT 10.0.22000.0``
 - Version: wezterm 20210502-154244-3f7122cb
 - ENG

## To Reproduce

```sh
#!/bin/sh

yes 10 | head -10000 | openssl aes128 -iter 10000 -kfile <(echo ok) -in /dev/stdin -out -
```

**Comment by wez** [comment]
Please try the nightly build; I think this has already been fixed

**Comment by untoreh** [comment]
seems like it, although some times in wezterm it turns the prompt into garbage
