### ISSUE TITLE
maintaining pixel color for P=1 Sixels would match widespread behavior

### ISSUE THREAD

**Issue by dankamongmen** [wez/wezterm#942]
## Describe the bug

It's probably not a bug, per se, but a P=1 Sixel drawn in WezTerm takes as its color the background color of the cell in which it is drawn. This is widely rumoured to be faithful behavior relative to the actual DEC VT line. With that said, it is unlike what at least XTerm, Alacritty (ayosec/graphics branch), and Contour do, which is to take on the existing color of the pixel (a no-op, essentially). This is clearly more powerful than the WezTerm behavior, as I can trivially coerce a cell to a background color, but I can hardly express even a cell's worth of pixel data in that same color.

Alacritty initially did what you're doing, and dug in heels for a bit about "not wanting to reproduce a bug of XTerm", but eventually came around. Transparency lets you do wonderful things. Adopting the background color lets you draw monotone rectangles.

I ask that you adopt this widespread deviation from the original Sixel protocol.

## To Reproduce

Fill a region with glyphs, and then move the cursor to the origin of said region. Draw a P=1 sixel. Notcurses will draw this whenever it detects even a single transparent pixel in the image. 

This can be done with `./notcurses-demo -p ../data i` from a Notcurses git checkout, built in a subdirectory of the checkout root. You'll see the orca with an ungainly black box, not wholly unsuggestive of the Sea World cages:

![2021-07-13-033021_919x986_scrot](https://user-images.githubusercontent.com/143473/125410205-ab11e200-e38a-11eb-9c29-9107dd853c48.png)

## Expected behavior

In other Sixel implementations, she's instead enveloped in the soft glow of glyphs:

![2021-07-13-033710_884x901_scrot](https://user-images.githubusercontent.com/143473/125411156-a4379f00-e38b-11eb-948e-5d3102bb4af6.png)

so magnificent!

**Comment by dankamongmen** [comment]
also, a note: if you're worried about performance impact (i have no idea whether there would be any) for sixels with no missing pixels, know that a good client implementation will pass P=0 for such a sixel, so you'll know at the beginning that composition is not necessary.

**Comment by wez** [comment]
I agree that what you're proposing looks superior!

It'll need a bit of thought to make it work: today, wezterm will either draw the graphic or the text into the cell.  To make this work it would need to render both, or to pre-render the composite and then render that as the graphic.  There are pros and cons to both of these.

**Comment by dankamongmen** [comment]
it occurs to me that, since you support iTerm2's graphics protocol, so long as transparency is honored within that scheme, you could continue to do "true" sixel, if that appeals to your sense of historical accuracy and conformance to standards. i just got on-the-fly PNG composition working in Notcurses last night, necessary for driving iTerm2, so i'll check out how that works with WezTerm, and maybe there's nothing needing doing here.

**Comment by wez** [comment]
It'll be broken in the same way: under the covers, sixel is remapped to the same scheme I use to model the iTerm2 image protocol!

**Comment by dankamongmen** [comment]
weakly confirmed, looks fantastic! i will put it through its full paces. you're a champ!
