### ISSUE TITLE
^C(sigint) does not work

### ISSUE THREAD

**Issue by komuw** [wez/wezterm#944]
## Describe the bug
- start wezterm
- run a long running command, eg; `sleep 120`
- send a sigint to the command by pressing the keys; `ctrl + shift + c`

## Environment (please complete the following information):
```
uname -ra
    Linux  5.11.0-22-generic  Ubuntu x86_64 GNU/Linux

lsb_release -ra
  No LSB modules are available.
  Distributor ID:	Ubuntu
  Description:	Ubuntu 21.04
  Release:	21.04
  Codename:	hirsute
```
```
wezterm -V
  wezterm 20210713-085818-b4c4c856
```
 - The active keyboard layout name (eg: ENG, DEU and so on)

## To Reproduce
- start wezterm
- run a long running command, eg; `sleep 120`
- send a sigint to the command by pressing the keys; `ctrl + shift + c`

## Configuration
```lua
local wezterm = require 'wezterm';

return {
    default_prog = {"zsh", "-l"},

    scrollback_lines = 3500,

    debug_key_events = true,

    keys = {
        {key="c", mods="CTRL", action=wezterm.action{CopyTo="ClipboardAndPrimarySelection"}},

        {key="v", mods="CTRL", action=wezterm.action{PasteFrom="Clipboard"}},
        {key="v", mods="CTRL", action=wezterm.action{PasteFrom="PrimarySelection"}},

        {key="t", mods="CTRL", action=wezterm.action{SpawnTab="CurrentPaneDomain"}},

        {key="w", mods="CTRL", action=wezterm.action{CloseCurrentTab={confirm=true}}},
    },
}
```

## Expected behavior
- I expected the long running command to exit. However it does not.

## Additional context
here are logs of the debug key events;
```sh
 2021-07-15T16:53:30.103Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('C'), modifiers: CTRL, raw_key: None, raw_modifiers: SHIFT | CTRL, raw_code: Some(54), repeat_count: 1, key_is_down: true }

 2021-07-15T16:53:31.580Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('C'), modifiers: CTRL, raw_key: None, raw_modifiers: SHIFT | CTRL, raw_code: Some(54), repeat_count: 1, key_is_down: true }

 2021-07-15T16:53:32.762Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('C'), modifiers: CTRL, raw_key: None, raw_modifiers: SHIFT | CTRL, raw_code: Some(54), repeat_count: 1, key_is_down: true }
```

**Comment by bew** [comment]
`^C` is the same as `^c` and both means `Ctrl-c`.
AFAIK there isn't currently a way to change the mapping for sigint, so you can't remap ctrl-c to copy and use sth else for sigint.

**Comment by komuw** [comment]
thanks for the info. 

i have been using both `gnome-terminal` and `terminator` before wezterm. In both I had mapped `ctrl + c` to copy and I was still able to send sigints to commands.

**Comment by wez** [comment]
ctrl-shift-c is by default assigned to `Copy`.

You can add an explicit binding to `SendString="\x03"` to have it send the same sequence as Ctrl-C would normally do.

https://wezfurlong.org/wezterm/config/lua/keyassignment/SendString.html

**Comment by komuw** [comment]
thank you!
