### ISSUE TITLE
IncreaseFontSize creates unreadable areas

### ISSUE THREAD

**Issue by seqizz** [wez/wezterm#946]
## Describe the bug

When you increase the font size, it just acts like it is graphically zooming top left of the terminal.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: `wezterm 2021-g1` (one of the last commits)
 - The active keyboard layout name: TR

## To Reproduce

- Print something to fill all of the terminal
- Trigger IncreaseFontSize
- You don't see the prompt anymore

## Configuration

Most related part:
```
  keys = {
    -- Turn off the defaults
    {key="=", mods="CTRL", action="DisableDefaultAssignment"},
    {key="RightArrow", mods="CTRL|SHIFT", action="DisableDefaultAssignment"},
    {key="LeftArrow", mods="CTRL|SHIFT", action="DisableDefaultAssignment"},
    {key="Enter", mods="ALT", action="DisableDefaultAssignment"},
    {key="n", mods="SUPER", action="DisableDefaultAssignment"},

    -- Assign new
    {key="+", mods="CTRL", action="IncreaseFontSize"},
    {key="4", mods="CTRL", action="IncreaseFontSize"},
    {key="-", mods="CTRL", action="DecreaseFontSize"},
    {key="0", mods="CTRL", action="ResetFontSize"},
    {key="Delete", mods="SHIFT", action="PastePrimarySelection"},
  }

```

## Expected behavior

Font size should increase, terminal should wrap the lines and keep focus on the bottom.

## Screenshots

Here is what happens when you print `dmesg` and trigger IncreaseFontSize 3 times on:

Wezterm, it sends text to invisible areas at the bottom and right:
![image](https://user-images.githubusercontent.com/307899/126003123-0ca15bf8-d6cc-4650-afc9-7b689ca7cd05.png)

Alacritty, keeps last part of the terminal workable:
![image](https://user-images.githubusercontent.com/307899/126003256-8ad6b61f-e00b-4279-b214-f394628c4ca1.png)

**Comment by wez** [comment]
Have you tried changing https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html to `false`?

**Comment by seqizz** [comment]
The configuration options worth a book themselves.. That'd be another one I'd vote for a different default though. Sorry for the noise and thanks :tada:
