### ISSUE TITLE
Question about japanese font

### ISSUE THREAD

**Issue by kuator** [wez/wezterm#948]
I love neovim and want to learn japanese. I decided to move from konsole to wezterm and I noticed a difference in how it displays japanese characters. The problem is I myself don't know whether it's an issue or not. I liked how Konsole displayed them though

Konsole:
![image](https://user-images.githubusercontent.com/25168308/126028317-4647ab3e-8e32-491b-b7ef-a1a41a82ff2b.png)
Wezterm:
![image](https://user-images.githubusercontent.com/25168308/126028324-40d0ba49-0a94-4a61-b8e3-b936187083fe.png)

**Comment by kuator** [comment]
My config:
```
local wezterm = require("wezterm")
return {
  font = wezterm.font("FuraCode Mono"),
  tab_bar_at_bottom = true,
}
```

**Comment by wez** [comment]
What exactly are you asking?  It looks like Konsole is using a bolder or larger font variant for that text.
Japanese glyphs typically come from a fallback font provided by the system, and those typically don't
have the same font metrics as your primary font.

I'd suggest increasing the size of the font to see if that make it look better, but you may also want to consider
explicitly specifying the name of a font that looks better, as explained in https://wezfurlong.org/wezterm/config/fonts.html#fallback

**Comment by kuator** [comment]
They are both using Fira Mono

**Comment by kuator** [comment]
So, I just need to find what font konsole uses as fallback and provide it as a fallback to wezterm as well?

**Comment by kuator** [comment]
Holy Moly! Thank you! I love wezterm!
![image](https://user-images.githubusercontent.com/25168308/126041604-1250cbf1-8c9b-455e-82e2-d56d439f2a96.png)
