### ISSUE TITLE
Vim background color is only applied partially 

### ISSUE THREAD

**Issue by skyline75489** [wez/wezterm#962]
## Describe the bug

The background in win32 vim is only partially applied and seems broken.

## Environment (please complete the following information):

 - OS: Windows
 - Version: release build at 1f5b900f3d04d259f2e28dbea0fb83be9289ea08
 - The active keyboard layout name: ENG

## To Reproduce

Open win32-vim with custom color scheme (for example: desert)

## Configuration

```lua
return {
        default_prog = {"pwsh.exe" },
        color_scheme = "Dracula",
}
```

## Expected behavior

This is how it looks in cmd.exe:

![image](https://user-images.githubusercontent.com/4710575/126158753-a503cceb-019c-4b72-9924-701650ea1830.png)

Same for Windows Terminal:

![image](https://user-images.githubusercontent.com/4710575/126158856-5e92c889-98c3-43e6-8053-189fc5ef6260.png)

## Screenshots

This is wezterm:

![image](https://user-images.githubusercontent.com/4710575/126158911-03ed1dc4-385f-4fb5-8b9a-c5e3f8edd15f.png)

**Comment by skyline75489** [comment]
sry if this a duplicate of other issues. I tried to search for similar issues but failed to find one. 

Really loving wezterm and this is the first day I tried it. I enjoy lots of cool features in it 👍

**Comment by MuhammedZakir** [comment]
This happens in Linux too.

* OS: Linux X11
* Version: 20210716-193137-f6a7df96
* The active keyboard layout name: ENG

**Comment by wez** [comment]
Hmm, can you try the last release as a point of comparison and see if it behaves the same there?

@MuhammedZakir: could you do a session recording of what you're seeing? https://github.com/wez/wezterm/blob/main/.github/ISSUE_TEMPLATE/bug_report.md#session-recording

**Comment by skyline75489** [comment]
I've switched to the last release (3f7122cb3f9d2fd92fb836e2f4b2aa7b839b6c86), compile it myself, and see the same behavior.

**Comment by MuhammedZakir** [comment]
> @MuhammedZakir: could you do a session recording of what you're seeing? https://github.com/wez/wezterm/blob/main/.github/ISSUE_TEMPLATE/bug_report.md#session-recording

[20210720044701.zip](https://github.com/wez/wezterm/files/6845608/20210720044701.zip)

\* I used zip for compressing because Github doesn't allow uploading tar files.

**Comment by cjnucette** [comment]
> This happens in Linux too.
> 
> * OS: Linux X11
> * Version: 20210716-193137-f6a7df96
> * The active keyboard layout name: ENG

I having the same issue in Ubuntu 20.04 with nighly `20210719-083608-91ae9bcb`

**Comment by cjgratacos** [comment]
I am having the same issue as well using nightly release. Reverted back to stable and it seems to be working.

**Comment by skyline75489** [comment]
A bit bisecting results in this:

```text
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
ad19b4f57b982d14434ef862f89ceebdfb7a7dc7
4e99edf6f5fc75dbdcf396a08f382e0368be2f32
db6da81272285fc91a3a326f277f22c3c31517b5
47839adf95cf9881e9888578f4de8c2261178daf
6aa575d8387b6cd2620798af87b9df6262c8c8df
cc2b9507f83d88f7e2a29f64cd4ec51d1598b55f
We cannot bisect more!
```

Some of the commits lead to build failure so I had to skip them.

**Comment by wez** [comment]
Thanks for the session recording @MuhammedZakir; that made it easy for me to see what's happening!
I just pushed a fix; it'll show up in the nightly builds in ~30 mins from now!

**Comment by MuhammedZakir** [comment]
> Thanks for the session recording @MuhammedZakir; that made it easy for me to see what's happening!

You're welcome! :-)

> I just pushed a fix; it'll show up in the nightly builds in ~30 mins from now!

It's fixed. Thanks!
