### ISSUE TITLE
Percieved latency when scrolling

### ISSUE THREAD

**Issue by Jnhtr** [wez/wezterm#963]
## Describe the bug

Latency when scrolling either with mouse or using `J` or `K` in Neovim, although not exclusive to - I can replicate this in nano also.

When opening a file in Neovim and scrolling with the mouse or using vim movement commands there is a noticeable latency in the cursor.

## Environment (please complete the following information):

 - OS: Arch Linux X11
 - Version: wezterm 20210718-000153-1f5b900f
 - The active keyboard layout name: ENG

## To Reproduce

Open a file of 180 lines, and attempt to scroll/use movement keys in nvim.

## Configuration

https://github.com/Jnhtr/dotfiles/blob/master/.config/wezterm/wezterm.lua

## Expected behavior

I expect the scroll/movement to not feel sluggish.

## Session Recording

[20210719174632.zip](https://github.com/wez/wezterm/files/6842959/20210719174632.zip)

**Comment by ahmedkhalf** [comment]
I can confirm, I experience the same latency.

**Comment by Jnhtr** [comment]
Currently on version `20210718-000153-1f5b900f` which seems to have resolved this issue for me.
