### ISSUE TITLE
Newlines gets eaten on right margin on window resize

### ISSUE THREAD

**Issue by kar1** [wez/wezterm#971]
## Describe the bug

If I cat a file to the terminal containing lines equal to the term column width, and then grow the terminal window, the lines equal to the former width will be concatenated with the next line.

Terminal window 20 columns wide before resize:
```
 0        1         2
 12345678901234567890
┌────────────────────┐
│ WezTerm Window     │
├────────────────────┤
│SSSSSSSSSS          │
│EEEEEEEEEEEEEEEEEEEE│
│SSSSSSSSSS          │
└────────────────────┘
```
Terminal window 40 columns wide after resize:
```
 0        1         2         3         4
 1234567890123456789012345678901234567890
┌───────────────────────────────────────┐
│ WezTerm Window                        │
├───────────────────────────────────────┤
│SSSSSSSSSS                             │
│EEEEEEEEEEEEEEEEEEEESSSSSSSSSS         │
└───────────────────────────────────────┘
```
Expected result:
```
 0        1         2         3         4
 1234567890123456789012345678901234567890
┌───────────────────────────────────────┐
│ WezTerm Window                        │
├───────────────────────────────────────┤
│SSSSSSSSSS                             │
│EEEEEEEEEEEEEEEEEEEE                   │
│SSSSSSSSSS                             │
└───────────────────────────────────────┘
```

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210721-085835-5434a2a5
 - The active keyboard layout name: DA

## To Reproduce

1.) Make a file containing:
```
====
SS
```
2.) Resize the terminal window to 4 columns and cat the file
3.) Resize the terminal window to >6 columns and observe the line "====SS"

## Configuration

Default config

## Expected behavior
Newlines on margin right edge be preserved on terminal resize

**Comment by wez** [comment]
Thanks for taking the time to make a nice and concise test case; I've seen this happen a few times but have always been in the middle of something else and then promptly forgotten about it!

**Comment by kar1** [comment]
Why was this issue closed? Is it a won't fix and why? I love this terminal and thank you for your work. Will you accept pull requests on this issue?
