### ISSUE TITLE
DECSET1003;1006 mode: Release of the second mouse button is not reported when two mouse buttons are pressed simultaneously

### ISSUE THREAD

**Issue by o-sdn-o** [wez/wezterm#973]
## Describe the bug

When using the DECSET 1003 + 1006 mode, if you simultaneously press two mouse buttons and release, then only one release is fired.

## Environment:

 - OS: Linux X11
 - Version: 20210502-154244-3f7122cb
 - The active keyboard layout name ENG

## To Reproduce

Run
```bash
echo -e "\e[?1003;1006h" ; cat
```
and  press and release both mouse buttons.

output:
```
^[[0;26;5M^[[<2;26;5M^[[<0;26;5m
```

## Expected behavior

output:
```
^[[0;26;5M^[[<2;26;5M^[[<0;26;5m^[[<2;26;5m
```

**Comment by wez** [comment]
I believe that this is now fixed in `main`.  It'll show up in the pre-built nightly binaries in ~30 minutes from now; please give it a try and let me know how it goes!

**Comment by o-sdn-o** [comment]
Great, it's works! Thank you!

All press/release events are reported correctly.

Three buttons pressed and released:
![image](https://user-images.githubusercontent.com/11535558/128627474-f3be18b8-cfc4-45bf-9506-cceddb1bea81.png)
