### ISSUE TITLE
Wrong parameters to the format-window-title event in format-window-title.md

### ISSUE THREAD

**Issue by Rrogntudju** [wez/wezterm#974]
The documented parameters are (tab, tabs, panes, config)
These parameters should be (active_tab, active_pane, tabs, panes, config) 

let v = config::lua::emit_sync_callback(
    &*lua,
    (
        "format-window-title".to_string(),
        (
            active_tab.clone(),
            active_pane.clone(),
            tabs,
            panes,
            (*self.config).clone(),
        ),
    ),
)?;

**Comment by wez** [comment]
Thanks!
