### ISSUE TITLE
Add Srcery color theme

### ISSUE THREAD

**Issue by planet36** [wez/wezterm#979]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add the Srcery color theme to wezterm.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/srcery-colors/srcery-terminal

**Comment by wez** [comment]
The color schemes in wezterm are synced from the upstream https://github.com/mbadolato/iTerm2-Color-Schemes project.
If you'd like to see your favorite scheme in wezterm, please submit a PR to https://github.com/mbadolato/iTerm2-Color-Schemes and then I can sync it back to wezterm!

**Comment by planet36** [comment]
Understood.
