### ISSUE TITLE
Fonts not identified after some update

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#984]
At some point in last couple of months, my wezterm config file that used to work stopped working. At launch I get errors that font is not found. Did something change in syntax?

Here's my original wezterm config:

```lua
local wezterm = require 'wezterm';

-- A helper function for my fallback fonts
local font_with_fallback = function(name, params)
    local names = {name, "Noto Color Emoji", "Arial Unicode MS", "Apple Symbols"}
    return wezterm.font_with_fallback(names, params)
end

return {
    --font = font_with_fallback("OperatorMono Nerd Font"),
    font = font_with_fallback("OperatorMonoNerdR"),
    font_size = 22, -- 20 for 2880x1680, 22 for 3840x2160
    font_rules = {
        {
            italic = true,
            font = font_with_fallback("OperatorMonoNerdI"),
        },
        {
            italic = true,
            intensity = "Bold",
            font = font_with_fallback("OperatorMonoNerdMI"),
        },
        {
            intensity = "Bold",
            font = font_with_fallback("OperatorMonoNerdM"),
        },
    },
    term = "wezterm", --"xterm-256color",
    color_scheme = "Pandora", --"Django",
    window_background_opacity = 1.0,
    window_close_confirmation = "NeverPrompt",
    allow_square_glyphs_to_overflow_width = "Always"
}

```

and error:

```
Unable to load a font matching one of your font_rules:
wezterm.font('OperatorMonoNerdM', {weight="Regular", stretch='Normal',
italic=false}). Fallback(s) are being used instead, and the terminal may not
render as intended. See https://wezfurlong.org/wezterm/config/fonts.html formore information

Unable to load a font specified by your font=wezterm.font('OperatorMonoNerdR',
{weight="Regular", stretch='Normal', italic=false}) configuration. Fallback(s)
are being used instead, and the terminal may not render as intended. See
https://wezfurlong.org/wezterm/config/fonts.html for more information
```

I tried all of names: Postscript name, Full name, Family as first argument to ``font_with_fallback()``. Currently I am on macOS 11.5, but the problem occurred on 11.4 as well.

![Screen Shot 2021-07-26 at 11 20 56 AM](https://user-images.githubusercontent.com/71736629/127038967-f2dbb287-92f4-4821-a80d-7e6f3a0f0efb.png)
![Screen Shot 2021-07-26 at 11 20 47 AM](https://user-images.githubusercontent.com/71736629/127038968-a1933e6b-d492-4d31-ad36-290fe5b234cd.png)
![Screen Shot 2021-07-26 at 11 20 37 AM](https://user-images.githubusercontent.com/71736629/127038970-4750c420-d470-4e0a-ba15-d231a1801da6.png)
![Screen Shot 2021-07-26 at 11 20 26 AM](https://user-images.githubusercontent.com/71736629/127038974-be21d372-716b-482a-9975-e911a686c20d.png)

**Comment by wez** [comment]
`wezterm ls-fonts` and/or `wezterm ls-fonts --list-system` are helpful for diagnosing font resolution issues.
See also https://github.com/wez/wezterm/commit/423b208780af0586472bba3719fa40031f91dd82

**Comment by horta** [comment]
I probably have the same issue.

From `wezterm ls-fonts --list-system` I get the one I want:

```
wezterm.font("FiraCode Nerd Font", {weight="Regular", stretch="Normal", italic=false}) -- /Users/horta/Library/Fonts/Fira Code Regular Nerd Font Complete.otf, CoreText
```

Having config as

```
% cat ~/.config/wezterm/wezterm.lua
local wezterm = require "wezterm"

return {
  font = wezterm.font("FiraCode Nerd Font", {weight = "Regular", stretch = "Normal", italic = false})
}
```
gives me

<img width="522" alt="Screenshot 2021-08-02 at 22 32 32" src="https://user-images.githubusercontent.com/514522/127926537-2f5da8ee-234d-4adc-957b-e16a0e070c78.png">

when opening Wezterm-nighlty build.

**Comment by wez** [comment]
when resolving a font by name, wezterm was asking coretext to only return fonts that have the monospace attribute.
Both of these fonts in this issue are patched fonts that don't have the monospace attribute (perhaps this is really a bug in the nerd fonts patcher?  It isn't the first one I've run into!), so they weren't matchable.

I've changed wezterm to remove that constraint.

**Comment by horta** [comment]
That is awesome, @wez . Thanks you!

**Comment by reportaman** [comment]
This is resolved, I no longer see the problem after your change. Thanks!
