### ISSUE TITLE
Terminfo/tmux sync feature does not work

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#999]
## Describe the bug

Cursor flickers in a tmux pane when there is activity in another tmux pane. Tmux has a new sync feature that syncs the updates before rendering a frame (afaik I understand). This is made possible by some new sync feature in terminfo.

From ``man tmux``'s TERMINFO EXTENSIONS section:
```
     Sync    Start (parameter is 1) or end (parameter is 2) a synchronized update.
```

Here's a video show the problem:

https://user-images.githubusercontent.com/71736629/128301405-fd7f845e-ffbf-4a43-9bfb-fbee0a39abb7.mp4

## Environment (please complete the following information):

 - OS: macOS 11.5
 - Version: wezterm 20210804-162508-e3acbd59
 - U.S.

## To Reproduce

Open tmux, create a few panes, run ``>>yes test`` in one pane, open nvim/vim in another and try typing something.

I tried adding ``Sync=\EP=%p1%ds\E\\,`` to wezterm.ti and recompiling it, it didn't change anything with that. 

Also, I tried with my modified xterm-256color. It didn't work with that either... 

This used to be a problem on alacritty, iTerm2, etc. But not since I have followed the steps here https://github.com/alacritty/alacritty/issues/4904#issuecomment-872614318, and since alacritty implemented the feature: https://github.com/alacritty/alacritty/pull/4768

P.S. entire TERMINFO EXTENSIONS section from ``man tmux``:
```
TERMINFO EXTENSIONS
     tmux understands some unofficial extensions to terminfo(5).  It is not normally necessary to set these manually, instead the terminal-features option should be used.

     AX      An existing extension that tells tmux the terminal supports default colours.

     Bidi    Tell tmux that the terminal supports the VTE bidirectional text extensions.

     Cs, Cr  Set the cursor colour.  The first takes a single string argument and is used to set the colour; the second takes no arguments and restores the default cursor colour.  If set, a sequence such as this may be used to change
             the cursor colour from inside tmux:

                   $ printf '\033]12;red\033\\'

     Cmg, Clmg, Dsmg, Enmg
             Set, clear, disable or enable DECSLRM margins.  These are set automatically if the terminal reports it is VT420 compatible.

     Dsbp, Enbp
             Disable and enable bracketed paste.  These are set automatically if the XT capability is present.

     Dseks, Eneks
             Disable and enable extended keys.

     Dsfcs, Enfcs
             Disable and enable focus reporting.  These are set automatically if the XT capability is present.

     Smol    Enable the overline attribute.

     Smulx   Set a styled underscore.  The single parameter is one of: 0 for no underscore, 1 for normal underscore, 2 for double underscore, 3 for curly underscore, 4 for dotted underscore and 5 for dashed underscore.

     Setulc, ol
             Set the underscore colour or reset to the default.  The argument is (red * 65536) + (green * 256) + blue where each is between 0 and 255.

     Ss, Se  Set or reset the cursor style.  If set, a sequence such as this may be used to change the cursor to an underline:

                   $ printf '\033[4 q'

             If Se is not set, Ss with argument 0 will be used to reset the cursor style instead.

>>   Sync    Start (parameter is 1) or end (parameter is 2) a synchronized update.

     Tc      Indicate that the terminal supports the `direct colour' RGB escape sequence (for example, \e[38;2;255;255;255m).

             If supported, this is used for the initialize colour escape sequence (which may be enabled by adding the `initc' and `ccc' capabilities to the tmux terminfo(5) entry).

             This is equivalent to the RGB terminfo(5) capability.

     Ms      Store the current buffer in the host terminal's selection (clipboard).  See the set-clipboard option above and the xterm(1) man page.

     XT      This is an existing extension capability that tmux uses to mean that the terminal supports the xterm(1) title set sequences and to automatically set some of the capabilities above.

```

**Comment by wez** [comment]
wezterm nightly builds implement this spec: https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036

For tmux to have flicker free updates then tmux itself needs to support using that sequence for its output.

I'm not sure if tmux supports that for input (so tmux itself knows when the embedded application is sync'd), for its output, or for both input and output.

The terminfo option you mentioned doesn't match the synchronized output spec that wezterm implements; I think you probably want `Sync=\E[?2026%?%p1%{1}%-%tl%eh` per this comment https://github.com/alacritty/alacritty/issues/4904#issuecomment-872093226

**Comment by reportaman** [comment]
@wez I compiled with ``Sync=\E[?2026%?%p1%{1}%-%tl%eh`` added to wezterm, xterm-256color, tmux-256color terminfo nothing changed.

Here's what I had:
1) In wezterm.lua I put term=wezterm, and then for second experiment term=xterm-256color
2) In tmux conf files I have:

```
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
```

Nothing changed with `Sync=\E[?2026%?%p1%{1}%-%tl%eh``

**Comment by reportaman** [comment]
Also, I just updated kitty term (had not used it since installing a 6 months ago), and without doing anything to it terminfo, it just worked. The previous version had the same flickering issue reported here.

**Comment by nicm** [comment]
Adding `Sync` to `terminal-features` will replace it with the DCS escape sequence, try adding it to `terminal-overrides` with the SM 2026 sequence instead.

**Comment by reportaman** [comment]
@nicm I tried these settings in my tmux conf file:

1. Did not change anything: 

```
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,xterm-256color:Sync"
```

2. Adds spurious escape characters to all new panes:

```
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,xterm-256color:Sync=\E[?2026%?%p1%{1}%-%tl%eh"
```

At this point all of my terminfos too have this setting ``Sync=\E[?2026%?%p1%{1}%-%tl%eh`` compiled into them.

**Comment by nicm** [comment]
Logs?

**Comment by nicm** [comment]
If you have `Sync` in your terminfo, do not add it with `terminal-features` or `terminal-overrides`.

**Comment by nicm** [comment]
It looks like this terminal supports `\033[>q` so you could try this and see if tmux detects this itself: [newsync.diff.txt](https://github.com/wez/wezterm/files/6944061/newsync.diff.txt)

**Comment by reportaman** [comment]
@nicm I tried with your patch, it slows down wezterm even more with ``>>yes test`` running in one of the panes. But the cursor flickering is gone. Though the delay between typing a character in an adjacent vim window and it appearing in vim seems to become much longer.

I have tried the inbuilt paning-windowing system of wezterm, and it does not have any of these problems. So seems there is some missing link. I moved completely to tmux for paning-windowing given its more portable way to do that among other benefits for my workflow.

**Comment by nicm** [comment]
A terminal managing multiple panes/windows itself is always likely to be faster than with tmux because they do not need to feed two input streams into one output stream, limited by the tty buffer size (which on macOS is small) and using one cursor. But there is no reason it should necessarily be slower than other terminals.

If you are running with any `-v`, tmux will be much much slower than without. Don't test for performance with logging on.

Are you splitting panes left-right or top-bottom? If the terminal does not support margins, the former will be slower than the latter.

If you do `tmux display -p '#{client_discarded}'`, is it nonzero and does it increase? If so, then the terminal does not seem able to accept the data volume so tmux will be doing full redraws instead of incremental updates which can be appear less responsive (although better than not responsive at all).

**Comment by reportaman** [comment]
@nicm I have attached screencasts comparing wezterm and alacritty for same setup (even same session).

1) First see wezterm, and lag:

https://user-images.githubusercontent.com/71736629/128492193-b933cc2b-c677-47dc-813e-ecd1b59c0281.mp4

2) Next see alacritty:

https://user-images.githubusercontent.com/71736629/128492489-ccb1097c-07e2-4e1a-b9ec-06ae4089efba.mp4

I think your patch might be still good, if I have some more reasonable log printing instead of atrocious ``>>yes test``, then there isn't such lag while typing in the pane with vim.

Not sure if the difference in behavior of alacritty and wezterm is because of their own performance numbers (where tmux might not be able to help). For example read the commit message of from alacritty repo https://github.com/alacritty/alacritty/commit/3c61e075fef7b02ae0d043e4a4e664b8bc7221e9

> "... Overall this has managed to reduce the time it takes to collect all renderable content from ~7-8ms in my large grid test to just ~3-4ms."

**Comment by wez** [comment]
> I tried with your patch, it slows down wezterm even more with `>>yes test` running in one of the panes. But the cursor flickering is gone with your patch. Though the delay between typing a character in an adjacent vim window and it appearing in vim seems to become much longer (unusably longer).

This could be a performance/tuning issue in wezterm; there's a lot that's in flux in the nightly builds at the moment.
You may want to try setting: `mux_output_parser_buffer_size=1000000` and see if that helps.

**Comment by reportaman** [comment]
@wez Setting ``mux_output_parser_buffer_size=1000000`` did not change anything, its still that way.

**Comment by kar1** [comment]
I also observed the lag with flickering of the cursor in the tmux pane when running `yes test` in another tmux pane. The non-tmux panes are not affected. The `mux_output_parser_buffer_size=1000000` setting fixes it for me, i.e. everything is smooth without flickering. I tested it on a rather slow laptop with x11 and wezterm 20210806-214445-e9ad4376.

**Comment by wez** [comment]
Based on your comments in https://github.com/wez/wezterm/issues/1102#issuecomment-913094184 it sounds like this is actually working for you now, so I'm closing this!
